### ISSUE TITLE
No versions of <pkg> match, version solving failed; only on MacOS

### ISSUE THREAD

**Issue by SabianF** [flutter/flutter#100012]
## Steps to Reproduce

1. Using
    - MacOS Big Sur 11.0.1
    - zsh terminal
    - `git clone https://github.com/flutter/flutter`
    - `flutter channel dev` or `master` or `stable`
    - `flutter upgrade`
1. start a project that depends on `flutter_appauth: ^2.4.1`
1. execute `flutter pub get`
1. See error `Because no versions of flutter_appauth match 2.4.1 and no versions of flutter_appauth match >2.4.1 <3.0.0, flutter_appauth ^2.4.1 is forbidden. So, because <app_name> depends on flutter_appauth ^2.4.1, version solving failed`

Note: these exact commands **work perfectly fine in my `Windows 10` environment**

## Logs

<details>
<summary>Logs (MacOS Big Sur 11.0.1) (Is failing)</summary>

- Note: due to GitHub's character limit, I've included only the relevant (error|exception|fail) parts of the log)

```
<user>@<user>s-MacBook-Pro flutter-app % flutter --verbose pub get

...

[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/io

[        ]     | Accept: application/vnd.pub.v2+json

[        ]     | X-Pub-OS: macos

[        ]     | X-Pub-Command: get

[        ]     | X-Pub-Session-ID: AD5C2AA4-6C9A-4205-855F-FF09C95F7831

[        ]     | X-Pub-Environment: flutter_cli:get

[        ]     | user-agent: Dart pub 2.17.0-69.2.beta

[        ] FINE: Failed to parse pubspec for flutter_appauth 2.4.1:

[        ]     | Error on line 1, column 125 of

../../../.pub-cache/hosted/pub.dartlang.org/flutter_appauth-2.4.1/pubspec.yaml:

Unexpected character.

[   +1 ms]     |   ╷

[        ]     | 1 │

...

[        ] IO  : Get versions from

https://pub.dartlang.org/api/packages/typed_data.

[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/typed_data

[        ]     | Accept: application/vnd.pub.v2+json

[        ]     | X-Pub-OS: macos

[        ]     | X-Pub-Command: get

[        ]     | X-Pub-Session-ID: AD5C2AA4-6C9A-4205-855F-FF09C95F7831

[        ]     | X-Pub-Environment: flutter_cli:get

[        ]     | user-agent: Dart pub 2.17.0-69.2.beta

[        ] SLVR:   fact: no versions of flutter_appauth match >2.4.1 <3.0.0

[        ] SLVR:   conflict: no versions of flutter_appauth match >2.4.1 <3.0.0

[        ] SLVR:   ! flutter_appauth >2.4.1 <3.0.0 is partially satisfied by not

flutter_appauth 2.4.1

[        ] SLVR:   ! which is caused by "no versions of flutter_appauth match

2.4.1"

[        ] SLVR:   ! thus: flutter_appauth ^2.4.1 is forbidden

[        ] SLVR:   ! flutter_appauth ^2.4.1 is satisfied by flutter_appauth

^2.4.1

[        ] SLVR:   ! which is caused by "<app_name> depends on flutter_appauth

^2.4.1"

[        ] SLVR:   ! thus: version solving failed

[        ] SLVR: Version solving took 0:00:03.402680 seconds.

[        ]     | Tried 1 solutions.

[        ] FINE: Resolving dependencies finished (3.507s).

[        ] IO  : Get versions from

https://pub.dartlang.org/api/packages/web_socket_channel.

[        ] ERR : Because no versions of flutter_appauth match >2.4.1 <3.0.0 and

no versions of flutter_appauth match 2.4.1, flutter_appauth ^2.4.1 is forbidden.

[        ]     | So, because <app_name> depends on flutter_appauth ^2.4.1, version

solving failed.

[        ] FINE: Exception type: SolveFailure

[  +21 ms] FINE: package:pub/src/solver/version_solver.dart 312:5

VersionSolver._resolveConflict

[        ]     | package:pub/src/solver/version_solver.dart 133:27

VersionSolver._propagate

[        ]     | package:pub/src/solver/version_solver.dart 97:11

VersionSolver.solve.<fn>

[        ]     | ===== asynchronous gap ===========================

[        ]     | dart:async

Future.catchError

[        ]     | package:pub/src/utils.dart 109:52

captureErrors.wrappedCallback

[        ]     | package:stack_trace

Chain.capture

[        ]     | package:pub/src/utils.dart 122:11

captureErrors

[        ]     | package:pub/src/command.dart 184:13

PubCommand.run

[        ]     | package:args/command_runner.dart 209:27

CommandRunner.runCommand

[   +7 ms]     | package:pub/src/command_runner.dart 174:24

PubCommandRunner.runCommand

[        ]     | package:pub/src/command_runner.dart 159:20

PubCommandRunner.run

[        ]     | package:dartdev/dartdev.dart 45:56

runDartdev

[        ]     | /opt/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart 11:9

main

[  +34 ms] IO  : Writing 528060 characters to text file

/Users/<user>/.pub-cache/log/pub_log.txt.

[  +48 ms] MSG : Logs written to /Users/<user>/.pub-cache/log/pub_log.txt.

[  +45 ms] IO  : HTTP GET

https://pub.dartlang.org/api/packages/web_socket_channel

[        ]     | Accept: application/vnd.pub.v2+json

[        ]     | X-Pub-OS: macos

[        ]     | X-Pub-Command: get

[        ]     | X-Pub-Session-ID: AD5C2AA4-6C9A-4205-855F-FF09C95F7831

[        ]     | X-Pub-Environment: flutter_cli:get

[        ]     | user-agent: Dart pub 2.17.0-69.2.beta

[   +9 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/crypto.

[  +10 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/crypto

[   +1 ms]     | Accept: application/vnd.pub.v2+json

[   +1 ms]     | X-Pub-OS: macos

[   +1 ms]     | X-Pub-Command: get

[  +10 ms]     | X-Pub-Session-ID: AD5C2AA4-6C9A-4205-855F-FF09C95F7831

[   +1 ms]     | X-Pub-Environment: flutter_cli:get

[   +4 ms]     | user-agent: Dart pub 2.17.0-69.2.beta

[  +26 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/args.

[   +2 ms] IO  : Get versions from

https://pub.dartlang.org/api/packages/logging.

[   +2 ms] IO  : Get versions from

https://pub.dartlang.org/api/packages/source_maps.

[   +5 ms] IO  : Get versions from

https://pub.dartlang.org/api/packages/vm_service.

[   +2 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/args

[   +1 ms]     | Accept: application/vnd.pub.v2+json

[        ]     | X-Pub-OS: macos

[        ]     | X-Pub-Command: get

[        ]     | X-Pub-Session-ID: AD5C2AA4-6C9A-4205-855F-FF09C95F7831

[        ]     | X-Pub-Environment: flutter_cli:get

[        ]     | user-agent: Dart pub 2.17.0-69.2.beta

[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/logging

[        ]     | Accept: application/vnd.pub.v2+json

[        ]     | X-Pub-OS: macos

[        ]     | X-Pub-Command: get

[        ]     | X-Pub-Session-ID: AD5C2AA4-6C9A-4205-855F-FF09C95F7831

[        ]     | X-Pub-Environment: flutter_cli:get

[   +1 ms]     | user-agent: Dart pub 2.17.0-69.2.beta

[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/source_maps

[        ]     | Accept: application/vnd.pub.v2+json

[        ]     | X-Pub-OS: macos

[   +1 ms]     | X-Pub-Command: get

[        ]     | X-Pub-Session-ID: AD5C2AA4-6C9A-4205-855F-FF09C95F7831

[   +1 ms]     | X-Pub-Environment: flutter_cli:get

[        ]     | user-agent: Dart pub 2.17.0-69.2.beta

[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/vm_service

[        ]     | Accept: application/vnd.pub.v2+json

[        ]     | X-Pub-OS: macos

[        ]     | X-Pub-Command: get

[        ]     | X-Pub-Session-ID: AD5C2AA4-6C9A-4205-855F-FF09C95F7831

[        ]     | X-Pub-Environment: flutter_cli:get

[        ]     | user-agent: Dart pub 2.17.0-69.2.beta

[+1120 ms] Running "flutter pub get" in flutter-app... (completed in 5.6s)

[   +3 ms] "flutter get" took 5,967ms.

[   +6 ms] pub get failed (1;     | user-agent: Dart pub 2.17.0-69.2.beta)

[   +1 ms] 

           #0      throwToolExit

(package:flutter_tools/src/base/common.dart:10:3)

           #1      _DefaultPub.batch

(package:flutter_tools/src/dart/pub.dart:373:7)

           <asynchronous suspension>

           #2      _DefaultPub.get

(package:flutter_tools/src/dart/pub.dart:254:7)

           <asynchronous suspension>

           #3      PackagesGetCommand._runPubGet

           (package:flutter_tools/src/commands/packages.dart:141:7)

           <asynchronous suspension>

           #4      PackagesGetCommand.runCommand

           (package:flutter_tools/src/commands/packages.dart:176:5)

           <asynchronous suspension>

           #5      FlutterCommand.run.<anonymous closure>

           (package:flutter_tools/src/runner/flutter_command.dart:1165:27)

           <asynchronous suspension>

           #6      AppContext.run.<anonymous closure>

           (package:flutter_tools/src/base/context.dart:150:19)

           <asynchronous suspension>

           #7      CommandRunner.runCommand

(package:args/command_runner.dart:209:13)

           <asynchronous suspension>

           #8      FlutterCommandRunner.runCommand.<anonymous closure>

           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)

           <asynchronous suspension>

           #9      AppContext.run.<anonymous closure>

           (package:flutter_tools/src/base/context.dart:150:19)

           <asynchronous suspension>

           #10     FlutterCommandRunner.runCommand

           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)

           <asynchronous suspension>

           #11     run.<anonymous closure>.<anonymous closure>

           (package:flutter_tools/runner.dart:62:9)

           <asynchronous suspension>

           #12     AppContext.run.<anonymous closure>

           (package:flutter_tools/src/base/context.dart:150:19)

           <asynchronous suspension>

           #13     main (package:flutter_tools/executable.dart:94:3)

           <asynchronous suspension>

           

           

[ +163 ms] ensureAnalyticsSent: 160ms

[   +1 ms] Running shutdown hooks

[        ] Shutdown hooks complete

[        ] exiting with code 1

```

```
<user>@<user>s-MacBook-Pro flutter-app % flutter --verbose doctor

[✓] Flutter (Channel dev, 2.11.0-0.1.pre, on macOS 11.0.1 20B29 darwin-x64,

    locale en-CA)

    • Flutter version 2.11.0-0.1.pre at /Users/<user>/src/flutter

    • Upstream repository https://github.com/flutter/flutter

    • Framework revision b101bfe32f (3 weeks ago), 2022-02-16 07:36:54 -0800

    • Engine revision e355993572

    • Dart version 2.17.0 (build 2.17.0-69.2.beta)

    • DevTools version 2.10.0-dev.1

[✗] Android toolchain - develop for Android devices

    ✗ Unable to locate Android SDK.

      Install Android Studio from:

      https://developer.android.com/studio/index.html

      On first launch it will assist you in installing the Android SDK

      components.

      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup

      for detailed instructions).

      If the Android SDK has been installed to a custom location, please use

      `flutter config --android-sdk` to update to that location.

 

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)

    • Xcode at /Applications/Xcode.app/Contents/Developer

    ! Flutter recommends a minimum Xcode version of 13.

      Download the latest version or update via the Mac App Store.

    ✗ CocoaPods not installed.

        CocoaPods is used to retrieve the iOS and macOS platform side's plugin

        code that responds to your plugin usage on the Dart side.

        Without CocoaPods, plugins will not work on iOS or macOS.

        For more info, see https://flutter.dev/platform-plugins

      To install see

      https://guides.cocoapods.org/using/getting-started.html#installation for

      instructions.

[✗] Chrome - develop for the web (Cannot find Chrome executable at

    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)

    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)

    • Android Studio not found; download from

      https://developer.android.com/studio/index.html

      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup

      for detailed instructions).

[!] Connected device

    ! No devices available

[✓] HTTP Host Availability

    • All required HTTP hosts are available

! Doctor found issues in 5 categories.

```

</details>

On the MacOS, I have tried using a downgraded version of flutter_appauth, but then another package starts having the same problem (stream_transform), and it wouldn't be feasible to downgrade n packages just because MacOS is suddenly not executing `flutter pub get` properly, I'm sure you agree.

Any ideas? Thanks for your help.

**Comment by danagbemava-nc** [comment]
Hi @SabianF, can you share your pubspec.yaml? I added `flutter_appauth` to a new project and run the `flutter pub get` command and everything worked as expected.

**Comment by SabianF** [comment]
Sure @danagbemava-nc 

`pubspec.yaml` (flutter_appauth section)</summary>

```yaml
# ...
dependencies:
  # ...
  # Used with Auth0 for user authentication management
  flutter_appauth: ^2.4.1
  # ...
# ...
```

<details>

<summary>pubspec.yaml (full)</summary>

```yaml
name: <app_name>
description: <app_description>

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Used for accessing environment variables within `.env` files
  flutter_dotenv: ^5.0.0

  # Used for icons that don't look like the crap stock ones
  font_awesome_flutter: ^9.2.0

  # Used to store and access scope-limited data throughout the app
  provider: ^5.0.0

  # Used for Internet=related calls, especially to our API
  http: ^0.13.3

  # Used with our NodeJS API to send/receive chat & other data
  # in realtime
  socket_io_client: ^1.0.1

  # Used to delay stream functions so they don't get called
  # excessively
  stream_transform: ^2.0.0

  # Used for storing the user's session when they log in, to keep them
  # logged in even after closing & reopening the app
  flutter_secure_storage: ^5.0.2

  # Used with Auth0 for user authentication management
  flutter_appauth: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/GaiaTreeGreenWhite.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/icons/
```

</details>

I'm able to run it fine on Windows, and was able to run it before on Mac (VMware WS 16) with stream_transform. Then due to another issue, I had to reinstall my MacOS in order to test the app on iOS, and then I wasn't able to `pub get` `flutter_appauth` or `stream_transform`

Does this info help?
