### ISSUE TITLE
dependency overrides not work

### ISSUE THREAD

**Issue by TechComet** [flutter/flutter#100236]
Hi,

It's not override `dart_vlc_ffi` package

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  dart_vlc:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      path: .
      ref: master


dependency_overrides:
  dart_vlc_ffi:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      path: ffi
      ref: master
```

---
flutter --version
```
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (2 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

I tested this before some months ago, It was working
