### ISSUE TITLE
Flutter App Created in Windows crashes on Mac when running in IOS simulator

### ISSUE THREAD

**Issue by briankariuki** [flutter/flutter#100459]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Flutter App launches, shows white screen then crashes in IOS simulator
3. Expected more information about the error in the console. Only shows remote notifications are not supported in the simulator then crashes.

**Expected results:** 

App should start normally as it does in the android emulator. 

**Actual results:** 

App shows white screen then crashes upon showing in the debug console the following error: remote notifications are not supported in the simulator

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  firebase_auth: ^3.3.11
  flutter_dotenv: ^5.0.0
  json_serializable: ^6.1.4
  cached_network_image: ^3.0.0
  lottie: ^1.0.1
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  collection: ^1.15.0
  image_picker: ^0.8.2
  smooth_page_indicator: ^1.0.0+2
  connectivity: ^3.0.3
  firebase_crashlytics: ^2.5.3
  firebase_core: ^1.13.1
  shared_preferences: ^2.0.5
  share: ^2.0.1
  permission_handler: ^8.3.0
  package_info_plus: ^1.0.4
  url_launcher: ^6.0.3
  animations: ^2.0.0
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.1.4
  dotted_border: ^2.0.0+2
  flutter_staggered_animations: ^1.0.0
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  google_mobile_ads: ^1.1.0
  facebook_audience_network: ^1.0.1
  image_gallery_saver: ^1.7.1
  uri_to_file: ^0.2.0
  date_time_format: ^2.0.1
  flutter_html: ^3.0.0-alpha.2
  dio: ^4.0.4


```

<details>
  <summary>Logs</summary>

```
[logs.txt](https://github.com/flutter/flutter/files/8312800/logs.txt)


```

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-x64, locale en-KE)
    • Flutter version 2.10.3 at /Users/brian/Documents/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/brian/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 99722D1A-ECBD-4841-B6CE-74E3AD9A3026 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.3 21E230 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>
