### ISSUE TITLE
[path_provider] path_provider_android 2.0.12 throws MissingPluginException

### ISSUE THREAD

**Issue by zmoshansky** [flutter/flutter#100844]
## Steps to Reproduce

1. Run `flutter clean && flutter pub get && flutter run`
2. In app, invoke `await getTemporaryDirectory()`
3. Observe the following error
```
E/flutter (32553): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter (32553): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (32553): <asynchronous suspension>
E/flutter (32553): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:55:24)
E/flutter (32553): <asynchronous suspension>
```

1. Revert `path_provider_android` in pubspec.lock to `2.0.11`
2. Run `flutter clean && flutter pub get && flutter run`
2. In app, invoke `await getTemporaryDirectory()`
3. Observe the app works normally.

**Expected results:** 
The call should succeed and return the director path.

**Actual results:** 
Plugin throws error as shown above. Given the plugin changelog mentions changing platform channel implementation, it seems like there may be a mismatch between the plugin and platform implementation.

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
path_provider:
    dependency: "direct main"
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.9"
path_provider_android:
    dependency: transitive
    description:
      name: path_provider_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.12"
```

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 11.6 20G165 darwin-x64, locale en-CA)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android SDK file not found: /....Android/sdk/platforms/android-32/android.jar.
```

</details>
