### ISSUE TITLE
Add flavor to pubspec.yaml

### ISSUE THREAD

**Issue by hasanm08** [flutter/flutter#100813]
## Use case
when we want have a multiplatform flavor we should do many configs foreach platform
so I think it's better that we can config it just once in pubspec.yaml

**Comment by EArminjon** [comment]
Share an exemple please :)

Adding flavors in puspec.yaml could be a good think for IDE'plugin to avoid creating run config inside .run folder or .vscode with uncmmon logic.

**Comment by iapicca** [comment]
@hasanm08
I like the idea, currently implementing flavors is cumbersome to say the least
I can immagine something like this in your `pubspec`:

```yaml
flavors: 
  production: 
    suffix: ""
    variables: 
      access_point: "production url"
  development: 
    suffix: ".dev"
    variables: 
      access_point: "development url"
  staging: 
    suffix: ".staging"
    variables: 
      access_point: "development url"
```

where tools generate the  native boilerplate for the app name and stuff
and exposes the variables as `dart define`

somewhat related, but not duplicate of https://github.com/flutter/flutter/issues/56792
