### ISSUE TITLE
Add a specific folder in plugins from github repository

### ISSUE THREAD

**Issue by apieceofcode1801** [flutter/flutter#100942]
I want to add a specific plugin from the plugins repo.
For example, I only want to add video_player for my project.
Something like this:
```
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  video_player: 
    git:
      url: https://github.com/flutter/plugins/tree/main/packages/video_player
      ref: main
```
Is there any way I can do this?
Thank you!

_I forked from the repository and changed something for temp bug fixes and want to pull the fixes from the forked repo._
