### ISSUE TITLE
Provide a pluggable method for asset transformation

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#101077]
The tool already does transformation of icon fonts at build time.

It would be good to make an interface like that open and pluggable, so that packages external to the tool could decide to transform assets. For example, `package:vector_graphics` will want to transform SVG files into a different kind of file at build time by invoking a Dart program to process them. 

@christopherfujino @jonahwilliams for input

**Comment by dnfield** [comment]
Some rough notes:

- The icon font shaker currently operates by getting fed all the files going into the asset bundle and sniffing the mime type. It then transforms the file and outputs a file with the same name and extension.
- Some transformers might want to replace existing files with brand new ones that have a different file name, but I feel like there's something I haven't thought all the way through here. Maybe keeping the file name the same is a good thing.
- We'll probably want ways to allow the manifest to specify which files get transformed and by which transformers, perhaps with regexps or globs for files?

**Comment by dnfield** [comment]
@jonahwilliams says he might be able to write a onepager on this. We talked some more this morning and agreed we don't need to make this work for the icon shaking, but it might help support some other features the tool has had requests for like platform specific assets.

**Comment by Hixie** [comment]
It would be great if we could make both the icon font transformer and the license file munger components that just plug into this more generic framework.

**Comment by jonahwilliams** [comment]
one of these ways I tried to make this tractable was to massively simplify the scope of what we could run over. By just allowing asset -> asset transformations, we allow for a very simple API with almost no configuration required. 

We must avoid making a generic build system, otherwise we'd probably be better taking something off the shelf. These usually come with severe tradeoffs and don't work in the same out of the box way that Flutter does today.

**Comment by Hixie** [comment]
oh totally, i wasn't suggesting making a build system. the icon transformer is asset->asset, right?
i agree that the license is more assets->assets, which is less of a good fit if the goal is simplicity.

**Comment by jonahwilliams** [comment]
its asset + compiled dart kernel -> asset, which relies on const finder and some tricky assumptions about how and when tree shaking applies to Dart code. 


Potentially a better fit would be something like the shader features which use impellerc to do shader compilation. The complications there have to do with
* communicating the right set of configuration to the tooing (i.e. which backend to target, which features to add) which will change over time 
* managing the (likely) breaking changes we'll need to make internal to impellerc in order to add support for more backends and to fix bugs once the feature is used more.

**Comment by Hixie** [comment]
Ah if you mean asset -> asset with literally no other inputs, not even inputs that would be the same for all assets, then yeah, the icon transformation doesn't fit either. A clean asset -> asset transformation with no dependencies at all is a very interesting subset of the problem space, because it can be parallelized very efficiently, so that makes sense to me.

Shader compilation seems like it has the same kind of needs (i.e. additional build-wide information) as the icon transformation.

**Comment by jonahwilliams** [comment]
Yeah, it has global configuration requirements, but it doesn't depend on the outputs of other build steps. So definitely a step in complexity from the asset -> asset transformations but not as complex as icons.

**Comment by Hixie** [comment]
Ah, fair. That distinction makes sense.

**Comment by andrewkolos** [comment]
> but it might help support some other features the tool has had requests for like platform specific assets.

@dnfield Do you recall where to find such requests? I'm interested in known potential use cases for asset transformation outside of easier use of `package:vector_graphics`.

**Comment by marandaneto** [comment]
It'd be cool if this feature provides a pluggable API that you can extend and run your own code.
An example that comes to mind is associating the generated obfuscation-map (via `save-obfuscation-map`) file when sending eg error reports such that those reports can symbolicate obfuscated class names, types, etc, because the final app knows its obfuscation map id that was generated and uploaded during build time, but the event should be sent at runtime so it should know its id.
We already do this for Android and Proguard, but that requires hooking up into Gradle directly, or, for each platform, ideally there'd be hooks in the Flutter build process that you can do such things.

**Comment by sivang** [comment]
@christopherfujino @jonahwilliams @dnfield If this work is still up for grabs, I'm interested investigating if I can take on this "Good Starter Project" but would require some guidance as to what&where to read code pertaining to the enhancement discussed here. In particular, I'm keen on devising up a generic use case that would ideally be platform-independent. (@marandaneto use case is one such case I'd think could be catered for)

**Comment by sivang** [comment]
Thanks @andrewkolos , I'm still interested in understanding the code behind this mechanism in the flutter build system, where to start reading? :)

**Comment by andrewkolos** [comment]
FYI I still plan on working on this, but I have delayed it until after https://github.com/flutter/flutter/pull/132985 since that PR and the one that would close this would both heavily modify pubspec parsing code. Trying to merge both concurrently would result in a lot of duplicated effort and/or merge conflicts.

**Comment by NashIlli** [comment]
@andrewkolos I just noticed that #132985 is already merged. Do you plan work on this in 2024? Thanks a lot! :)

**Comment by andrewkolos** [comment]
> @andrewkolos I just noticed that #132985 is already merged. Do you plan work on this in 2024? Thanks a lot! :)

Yes, this is what I plan on working on next (ignoring routine maintenance work).

**Comment by andrewkolos** [comment]
For anyone watching this issue or interested in how users will utilize this feature,

I'm currently drafting a PR for this. To help inform the design, I'm interested in any potential use case you might have for it.

Currently, I intend to provide a separate YAML section in the pubspec, where the user lists their transformers and what assets they will be run against:

```yaml

flutter:
  # ...
  assets:
    - assets/splash/logo.svg
    - assets/chatbot/
    - path: assets/integrations/free/
      flavor: free
    - path: assets/integrations/premium/
      flavor: premium
    # ...
  # ...
  asset-transformers:
    - package: vector_graphics_compiler
      args:
        - "--tesselate"
        - "--use-half-precision-control-points"
      assets:
        - "**/*.svg"
      # Globs are not normally supported for assets for technical reasons.
      # However, we can support them here since this doesn't *add* any
      # files—the glob is only run against the existing assets list.
```

Normally, I'd be hesitant to have something outside of the `assets` affect assets[^1], but I'm assuming that the vast majority of use cases of this feature are going to involve running a transformer against _all_ assets of a specific file type (like in the example scenario above, where I want to run a transformer against _all_ bundled SVG files, regardless of where they are being used in the app).

One alternative is to have asset tranformer definitions remain in their own YAML section (`asset-transformers`), but to not have them define an `assets` list. Instead, they would be given a `name`, and assets in the main `asset` list would provide any relevant transformations by name:

```yaml
flutter:
  # ...
  assets:
    - path: assets/splash/logo.svg
      transformers:
        - compileSvg # Refer to later transformer definition by name.
    - assets/chatbot/
    - path: assets/integrations/free/
      flavor: free
      # new:
    - path: assets/integrations/free/logos/
      flavor: free
      transformers:
        - compileSvg
    - path: assets/integrations/premium/
      flavor: premium
      # new:
    - path: assets/integrations/premium/logos/
      flavor: free
      transformers:
        - compileSvg
    # ...
  # ...
  asset-transformers:
    # This transformer definition no longer provides its own `assets` list, but it has a
    # name that can be referred to in the main `assets` section.
    - name: compileSvg
      package: vector_graphics_compiler
      args:
        - "--tesselate"
        - "--use-half-precision-control-points"

```

This keeps the `assets` section more complete in regards to containing all information related to assets, but it also makes the task of running a transformer against all files with a given type tedious.

[^1]: This makes pubspecs slightly harder to read for folks onboarding to a project and troubleshooting asset-related issues. They need to notice that some separate YAML section to have any clue that this feature is being used while all other asset-related info is kept together in `assets`.

**Comment by ueman** [comment]
Do packages with entries in that section automatically executed? I imagine that being useful, although it's a bit scare in regards to security

**Comment by andrewkolos** [comment]
Thanks for the questions!

> Do packages with entries in that section automatically executed? I imagine that being useful, although it's a bit scare with regard to security, since it basically allows arbitrary code execution. But it would be certainly nice from a DX experience. Just add a transformer as a dev dependency and it just works™️

Yes. In particular, they get run at `flutter run`/`flutter build`, and only if the user has configured their project to use them. Indeed, this could theoretically be exploited, but also consider the following:
  1) Dart packages already have these privileges if imported in user code (or explicitly run through `dart run <package-name>`).
  2) The upcoming [Native Assets](https://github.com/flutter/flutter/issues/129757) feature will (likely) allow code execution even from packages even more subtly (in a way similar to many existing ecosystems today do—[Rust's Cargo](https://doc.rust-lang.org/cargo/reference/build-scripts.html) and [Node Package Manager (NPM)](https://docs.npmjs.com/cli/v9/using-npm/scripts) scripts come to mind).

To put it more simply, I am comfortable having users needing to trust any dependency they add to their project.

> Do transformers know whether they get executed in debug or release mode? I kinda imagine that being useful. Ex: There's a transformer that optimizes the file size of images. Depending on the amount and size of the images, that could take a significant amount of time. Therefore, I might want to only execute it in release builds.

Good idea. `flutter` could make this available to the transformer either through an argument or through a new well-known environment variable (assuming it doesn't already exist).

> Another use case is the automatic creation of resolution-aware images. Imagine just the high resolution image (3x) gets added. Can a transformer create the 2x and 1x version of the image?

Right now, the feature is designed with one-to-one asset transformation in mind. Technically, there is nothing stopping a transformer from doing such a thing since it has access to the filesystem (though there are caveats here). Still, this use case would not explicitly supported.

If anyone has design ideas for how one-to-many (or many-to-one) asset transformation might work from the user's perspective, I would be interested—not necessarily because I would want to implement this in the initial feature, but because I'd like to make the sure the current design would not be incompatible with such an idea.

> Another question is do transformer also transform assets included by other packages?

Another good question. This is something I failed to consider carefully. As things are, transformers would apply to _any_ asset that matches one of its globs. As a result, it's possible that users may unintentionally transform assets from package dependencies. Let me illustrate this with a hypothetical scenario:

1. A flutter project has some SVG assets. To make these usable by the `vector_graphics` package, the user sets up a transformer in their pubspec like so:

```yaml
flutter:
  # ...
  asset-transformers:
    - package: vector_graphics_compiler # Suppose vector_graphics_compiler has been updated to support this feature.
      assets:
        - **.svg
```
2. The same project uses some widget that comes from a package dependency. We'll call this package `my_dependency` and the widget `PackageWidget`. `PacketWidget` depends on an SVG within the same package using this code: `SvgPicture.asset('packages/my_dependency/assets/file.svg')`. This uses the `flutter_svg`package to render its SVGs, not `vector_graphics`.
3. The user runs `flutter run`. The `flutter` tool transforms `packages/my_dependency/assets/file.svg` because it matches the `**.svg` glob. `SvgPicture.asset` will fail, presumably with a vague error message about `packages/my_dependency/assets/file.svg` being formatted incorrectly. This is both surprising and confusing to the end user, who was unaware that this file even existed, and they might not be able to figure out why this is happening.

We could certainly add some sort of guard against a user accidentally doing something like this, but it is unclear if it is worth the effort.
