### ISSUE TITLE
Add flake stress test mode to .ci.yaml

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#101084]
Frequently we need to analyze and fix a flaky test shard. Also frequently, flakiness is only reproducible on LUCI and not locally ([example](https://github.com/flutter/flutter/issues/97303)).

It is currently difficult to reproduce flakiness on LUCI. Later, when a fix is made, it is difficult to confirm the effectiveness of the fix.

## Proposal

`.ci.yaml` adds a new target parameter called `flake_stress_test` that takes an integer number greater than zero.

Example:

```yaml
targets:
  - name: Linux analyze
    flake_stress_test: 10
    recipe: flutter/flutter
    timeout: 60
    properties:
      tags: >
        ["framework","hostonly"]
      validation: analyze
      validation_name: Analyze
    scheduler: luci

  - name: Linux customer_testing
    flake_stress_test: 20
    recipe: flutter/flutter
    timeout: 60
    properties:
      tags: >
        ["framework","hostonly"]
      validation: customer_testing
      validation_name: Customer testing
    scheduler: luci

  - name: Linux firebase_abstract_method_smoke_test
    recipe: firebaselab/firebaselab
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:31v8"}
        ]
      tags: >
        ["firebaselab"]
      task_name: abstract_method_smoke_test
    scheduler: luci

```

Adding `flake_stress_test` and pushing code to a PR will cause LUCI skip all targets, and only run targets that have `flake_stress_test` set, running each that number of times. In the example above, LUCI will run the "Linux analyze" target 10 times, "Linux customer_testing" 20 times, and it will skip "Linux firebase_abstract_method_smoke_test".

## Why skip other targets?

- Targets other than those you are trying to deflake are not interesting and just pollute the output of the PR.
- Deflaking targets will require running them many times, which will already stress LUCI capacity. No need to make it worse by running uninteresting targets.

## Why support specifying `flake_stress_test` on multiple targets?

Some tests are sharded (web, tools) and flakiness does not reproduce on one specific shard. It would be useful to be able to specify `flake_stress_test`, for example, on all web targets.
