### ISSUE TITLE
[packages] pigeon isn't formatting dart code

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#101298]
## Explanation

pigeon doesn't generate formatted dart code. That means that you have to run an additional formatting step. My understanding with code generation is it's best practices (and in many cases absolutely required) to format with `dartfmt` after generation such that the output is deterministic even if format commands are run over the generated code afterwards.

## Environment

Pigeon version: 
`pigeon: ^2.0.3`

Flutter version:
```
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c860cba910 (10 days ago) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

## Repro

`pubspec.yaml`
```yaml
name: pigeon_formatting
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  pigeon: ^2.0.3

flutter:
  uses-material-design: true
```

`pigeons.dart`
```dart
import 'package:pigeon/pigeon.dart';

class Value {
  int? number;
}

@HostApi()
abstract class Api2Host {
  @async
  Value calculate(Value value);
}
```

### Steps

1. run `flutter pub run pigeon --input pigeons.dart --dart_out pigeons.g.dart`
2. stage all generated code
3. run `flutter format pigeons.g.dart`
4. git will show the diffs

Diffs are visible here: https://gist.github.com/lukepighetti/17f04f16083d6f42dfa740c5e273498f/revisions
