### ISSUE TITLE
Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found

### ISSUE THREAD

**Issue by esentis** [flutter/flutter#101421]
Getting this error (works fine for iOS) :

I already saw those [https://github.com/flutter/flutter/issues/100948](url) & [https://github.com/driftboat/flutter_zoom/issues/15#issuecomment-979940162](url) but unfortunately didn't solved my issue

`Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.17.0-runtime (com.google.android.exoplayer:exoplayer-core:2.17.0) and jetified-exoplayer-ui-2.14.2-runtime (com.google.android.exoplayer:exoplayer-ui:2.14.2)`

## Pubspec.yaml

```yaml
dependencies:
  flutter:
    sdk: flutter
  string_validator: ^0.3.0
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  flutter_tags: ^1.0.0-nullsafety.1
  sleek_circular_slider: ^2.0.1
  uuid: ^3.0.5
  device_info: ^2.0.3
  pin_code_fields: ^7.3.0
  intl_phone_field: ^2.1.0
  simple_rc4: ^0.2.0
  flutter_idensic_mobile_sdk_plugin: ^1.18.2
  carousel_slider: ^4.0.0
  get: ^4.3.8
  get_storage: ^2.0.3
  webview_flutter: ^2.3.1
  pusher_client: ^2.0.0
  share_plus: ^3.0.4
  firebase_analytics: ^8.3.4
  onesignal_flutter: ^3.2.7
  uni_links: ^0.5.1
  cupertino_icons: ^1.0.4
  logger: ^1.1.0
  sentry_flutter: ^6.1.2
  package_info_plus: ^1.3.0
  in_app_review: ^2.0.3
  flutter_screenutil: ^5.0.0+2
  flutter_facebook_sdk: ^1.0.0
  lint: ^1.7.2
  url_launcher: ^6.0.15
  lottie: ^1.2.1
  shimmer: ^2.0.0
  image_cropper: ^1.5.0
  flutter_switch: ^0.3.2
  string_extensions: ^0.4.0
  smooth_page_indicator: ^1.0.0+2
  visibility_detector: ^0.2.2
  collection: ^1.15.0-nullsafety.4
  cached_network_image: ^3.1.0+1
  flutter_widget_from_html: ^0.8.2
  pie_chart: ^5.1.0
  http: ^0.13.4
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  local_auth: ^1.1.9
  biometric_storage: ^4.0.0-dev.1
  ```
  
  ## fluter doctor -v
  
 ```
  [✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-arm, locale en-GR)
    • Flutter version 2.10.4 at /Users/esentis/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (12 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/esentis/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • Mi MIX 2 (mobile) • 8c99ccc1 • android-arm64  • Android 9 (API 28)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

I would really appreciate any hints or ideas.
