### ISSUE TITLE
[iOS] WebView nested in ListView glitches on scroll.

### ISSUE THREAD

**Issue by T-moz** [flutter/flutter#101776]
## Steps to Reproduce

1. Execute `flutter run` with the code sample on a physical iPhone.
2. Scroll up or scroll down.

**Expected results:**
The `AppBar` should not glitch.
There should be no white line appearing in the `AppBar` on scroll.
<img src="https://user-images.githubusercontent.com/28344195/163030458-0cd47473-5e7a-4826-87de-438fcc70585d.png" width="50%">

**Actual results:** 
The `AppBar` glitches.
There is a white line inside the `AppBar`
<img src="https://user-images.githubusercontent.com/28344195/163030371-29231b08-f410-42e1-b366-a49d1e843095.png" width="50%">

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'iOS Glitch'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: ListView(
        children: const <Widget>[
          SizedBox(
            width: double.infinity,
            height: 500,
            child: WebView(
              initialUrl: 'https://flutter.dev',
            ),
          )
        ],
      ),
    );
  }
}
```

Pubspec:
```yaml
name: ios_glitch
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

</details>

<details>
  <summary>Logs</summary>

Flutter analyze:

```bash
Analyzing ios_platformeview_glitch...                                  ⣷
No issues found! (ran in 1.9s)
```

Flutter Doctor:

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.66.1)
[✓] VS Code (version 1.47.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

https://user-images.githubusercontent.com/28344195/163033803-b6d9e116-835d-47f7-bbaa-b13620d39383.mov
