### ISSUE TITLE
App crashes on Android 10, flutter beta channel

### ISSUE THREAD

**Issue by jeromeDms** [flutter/flutter#102293]
Dear All
I'm facing multiple crashes reported by google play console, with the following trace, all crashes are for devices running Android 10, different devices (most of them seem Redmi)
I cannot find a clear way to solve this, after multiple hours searching.
I'm using flutter beta channel (Because it improves a lot the performances when displaying AdMob ads).
Any help would be greatly appreciated.
Jerome
 

```
backtrace:
  #00  pc 000000000005f356  /apex/com.android.runtime/lib/bionic/libc.so (abort+166)
  #00  pc 0000000000005a31  /system/lib/liblog.so (__android_log_assert+176)
  #00  pc 000000000029ec3b  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::getFrame()+26)
  #00  pc 00000000002a4b11  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+140)
  #00  pc 00000000002a414b  /system/lib/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+170)
  #00  pc 00000000002b1aef  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+158)
  #00  pc 00000000002b194d  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+72)
  #00  pc 000000000000d8b3  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+182)
  #00  pc 00000000000a6293  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  #00  pc 0000000000060803  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
```
   
 Below flutter doctor result :
 
```
 [✓] Flutter (Channel beta, 2.13.0-0.2.pre, on macOS 11.6.5 20G527 darwin-x64, locale fr-FR)
    • Flutter version 2.13.0-0.2.pre at /Users/jerome/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8662e22bac (19 hours ago), 2022-04-20 08:21:52 -0700
    • Engine revision 24a02fa5ee
    • Dart version 2.17.0 (build 2.17.0-266.5.beta)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jerome/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Using the following dependencies in my app :

```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  getwidget: ^2.0.5
  http: ^0.13.4
  url_launcher: ^6.0.20
  connectivity_plus: ^2.3.0
  adaptive_theme: ^2.3.1
  flex_color_scheme: ^5.0.0
  package_info_plus: ^1.4.2
  firebase_core: ^1.14.1
  firebase_analytics: ^9.1.5 # back in V10.2.0
  firebase_messaging: ^11.2.13
  firebase_crashlytics: ^2.6.2 # V10.2.0
  overlay_support: ^1.2.1
  flutter_device_type: ^0.4.0
  shared_preferences: ^2.0.13
  flutter_inappwebview: ^5.4.0+2
  badges: ^2.0.2
  path_provider: ^2.0.9
  fast_contacts: ^1.1.1
  permission_handler: ^9.2.0
  audioplayers: ^0.20.1
  dio: ^4.0.6
  universal_html: ^2.0.8
  open_file: ^3.2.1
  google_maps_flutter: ^2.1.3
  location: ^4.3.0
  clustering_google_maps: 0.1.2-nullsafety.3
  dart_geohash: ^2.0.2
  xml: ^5.3.1 # ^6.0.1
  plist_parser: ^0.0.7
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  auto_size_text: ^3.0.0
  google_mobile_ads: ^1.2.0
  flutter_funding_choices: ^0.3.0+2
  gdpr_dialog: ^2.1.1
  flutter_font_icons: ^2.2.4
  local_auth: ^2.0.0
  flutter_screen_lock: ^5.0.11+1

  flutter_localizations: # Add this line
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    flutter_lints: ^1.0.4
```
