### ISSUE TITLE
PhaseScriptExecution error during IOS build. 

### ISSUE THREAD

**Issue by RtypeStudios** [flutter/flutter#103254]
I have an issue during IOS build with flutter. I receive this error during build (Android builds fine):

`PhaseScriptExecution Run\ Script /Users/appveyor/Library/Developer/Xcode/DerivedData/Runner-edbyerddbiuubgfgxijtdvcduzhj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh`

The script being called exists and contains:

```
#!/bin/sh
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
```

The command being run from fastlane is:

`
Dir.chdir "../.." do sh("flutter", "build", "ios", "--release", "--no-codesign") end
`

This occurs on our build server.

For the life of me I cant figure this one out. I've been working on it a couple days.

My project was on flutter 1.25.0-8.3 BETA, I upgraded to flutter 2.8.0 STABLE

Any clues at to what I'm doing wrong? I have the build log if that would help, what is the best way to provide it?

## Steps to Reproduce

Execute from fastlane script: 

`
Dir.chdir "../.." do sh("flutter", "build", "ios", "--release", "--no-codesign") end
`

## Logs

<details>
<summary>Logs</summary>

I have detailed logs, but they are massive 3mb+ what is the best way of getting them to you?

```

Flutter doctor says:

worker-629-002:flutter appveyor$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
✗ Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[!] Connected device
! No devices available

! Doctor found issues in 4 categories.

```

</details>

**Comment by RtypeStudios** [comment]
I've tried adding 

`export FLUTTER_ROOT="/Users/appveyor/flutter"` as per here: https://github.com/flutter/flutter/issues/49495

**Comment by RtypeStudios** [comment]
Running the command results in:

```
worker-628-001:Runner.build appveyor$ ./Script-9740EEB61CF901F6004384FC.sh
/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
```

**Comment by darshankawar** [comment]
> My project was on flutter 1.25.0-8.3 BETA, I upgraded to flutter 2.8.0 STABLE

That beta version is a bit old and latest stable is 2.10.5.

Is there a way to provide complete verbose log that shows the error ? You can put that verbose log in a text file and share it here.

Also provide `ios/podfile`

**Comment by RtypeStudios** [comment]
There is currently no ios/podfile. This is something that has had me wondering, do you actually need to use Pod? or is it optional. As I previously had everything working without it?

[Runner-Runner.log](https://github.com/flutter/flutter/files/8650284/Runner-Runner.log)

**Comment by darshankawar** [comment]
> This is something that has had me wondering, do you actually need to use Pod? or is it optional. As I previously had everything working without it?

If you have plugins in your project, respective pods will be created. If you don't have any plugins, there won't be any pods.
From what I see, you don't seem to have any plugins and hence you don't see any podfile or pods, is it correct ?

But the log you shared seems to show plugins already, so that doesn't seem to be the case. If there are plugins in your app, you should see `ios/podfile`.

It seems your app with valid archs is messed up, as I see from the log: 

`export arch\=undefined_arch` 

So please check your app configuration once again because the error seems to be occuring due to mis-config or not using valid archs.

**Comment by RtypeStudios** [comment]
Admittedly, I have tried about 9 million things to try and get this to work. I might have had a pod file present during that build. 

Where do I define the Arch in flutter? Did a quick google but didn't return any info about it. Would this be in fastlane perhaps? 

Sadly, I've had to revert the entire project back to an earlier commit. I've spent about a week tracking this down and I have had no luck. My plan was to go back to a known good build and then move forward from there.

**Comment by RtypeStudios** [comment]
Okay after rolling everything back to latest known working. Still getting the same error. 

Flutter Doctor -V

```
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on Mac OS X 10.15.7 19H1715 darwin-x64, locale en-US)
    • Flutter version 2.6.0-5.2.pre at /Users/appveyor/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (8 months ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/appveyor/android-sdk
    • Platform android-29, build-tools 29.0.0
    • ANDROID_SDK_ROOT = /Users/appveyor/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode-12.3.app/Contents/Developer
    • CocoaPods version 1.11.3
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
[!] Connected device
    ! No devices available
! Doctor found issues in 4 categories.
```

Build machine Arch:

`Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz`

Flutter Version: 

`flutter_macos_2.6.0-5.2.pre-beta`

PodFile:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

pubspec.yaml (Last bits omitted.)

```
name: livevenue
description: test

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  livevenue_common:
    path: ../shared/livevenue_common
  livevenue_api:
    path: ../shared/livevenue_api
  intl: ^0.17.0
  url_launcher: ^6.0.3
  equatable: ^2.0.0
  geolocator: ^7.0.3
  rxdart: ^0.27.0
  flutter_bloc: ^7.0.0
  flutter_secure_storage: ^4.2.0
  font_awesome_flutter: ^9.0.0
  cached_network_image: ^3.0.0
  package_info: ^2.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  dio: ^4.0.0
  shimmer: ^2.0.0
  stripe_sdk: ^5.0.0-nullsafety.0
  awesome_card: ^1.1.5
  credit_card_validator: ^2.0.0-nullsafety.0
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  formz: ^0.4.0
  qr_code_scanner: ^0.4.0
  firebase_core: 1.3.0
  firebase_messaging: 10.0.2
  overlay_support: ^1.2.1
  flutter_local_notifications: 8.2.0
  collection: ^1.15.0-nullsafety.4
  vrouter: ^1.2.0+7
  badges: ^2.0.1
  timeago: ^3.1.0

  flutter:
    sdk: flutter
  

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter

```
