### ISSUE TITLE
Couldn't resolve the package 'path_provider' in 'package:path_provider/path_provider.dart' (Android Studio)

### ISSUE THREAD

**Issue by halhwadi** [flutter/flutter#104038]
Hello
I use Android Studio and just installed path_provider package, But I got this message error when run the App:

```
Invalid depfile: C:\Users\Husam.Alhwadi\StudioProjects\Bikum\.dart_tool\flutter_build\4a7dfe41f194fdc317c7d223950aeb41\kernel_snapshot.d
Invalid depfile: C:\Users\Husam.Alhwadi\StudioProjects\Bikum\.dart_tool\flutter_build\4a7dfe41f194fdc317c7d223950aeb41\kernel_snapshot.d
**Error: Couldn't resolve the package 'path_provider' in 'package:path_provider/path_provider.dart'.**
screens/lib/screens.dart:9:8: Error: Not found: 'package:path_provider/path_provider.dart'
import 'package:path_provider/path_provider.dart';
```

I tried flutter clean and restarted the android studio but didn't help....also I have downgraded the versions of path_provider to 2.0.9 but didn't help as well....

```
find below flutter Dcotor report for your reference(**Note: I don't need Visual Studio as I'm developing mobile app**) :
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1706])
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.67.1)
```

pubspec.yaml file:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # localization
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.4
  shared_preferences: ^2.0.13
  loading_animations: ^2.2.0
  connectivity_plus: ^2.3.0
  permission_handler: ^9.2.0
  flutter_map: ^0.14.0
  maps_launcher: ^2.0.1
  image_picker: ^0.8.5+3
  path_provider: ^2.0.10
```
