### ISSUE TITLE
`flutter_test` keeps me from installing `path 1.8.2`

### ISSUE THREAD

**Issue by mgenware** [flutter/flutter#104181]
## Steps to Reproduce

Have both `path 1.8.2` and `flutter_test` in deps.
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```

`flutter pub get` prints:
```
Because every version of flutter_test from sdk depends on path 1.8.1 and <app> depends on path >=1.8.2, flutter_test from sdk is forbidden
```

<details>
<summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale
    en-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>
