### ISSUE TITLE
Flutter 3.0 breaks code autocomplete when certain dependencies are added

### ISSUE THREAD

**Issue by serendipity1004** [flutter/flutter#104149]
## Details

1) add build_runner: ^2.0.0 to dev_dependencies in pubspec.yaml file.
2) run pub get
3) open any dart file in the project and try to get an autocompletion of import 'package:flutter/material.dart'.
4) The auto completion does not work not only for package:flutter but also for major code generation packages like retrofit or json_serializable
5) downgrade to v2.10.5.
6) leave everything as is and try the same auto completion as in (3).
7) works as expected.

**Comment by serendipity1004** [comment]
if I ignore the auto completion and just type everything up, the app works fine. It's just extremely inconvenient to work without the feature.

**Comment by maheshmnj** [comment]
Hi @serendipity1004, Thanks for filing the issue. What IDE are you using? I verified in vscode and it seems to work just fine on `stable 3.0`.
<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by DanTup** [comment]
> add build_runner: ^2.0.0 to dev_dependencies in pubspec.yaml file.
> open any dart file in the project and try to get an autocompletion of import 'package:flutter/material.dart'.
> if I ignore the auto completion and just type everything up, the app works fine

Where are the files you're trying to reference these packages in? The analyzer won't suggest symbols from dependencies in `dev_dependencies` inside folders like `lib` because `dev_dependencies` should not be required by your app at runtime (they're intended for development time scripts, like `tool` or `tests`).

Typing them manually works because the analzyer/runtime are able to _find_ those packages, but it's not a good idea. There's a lint [`depend_on_referenced_packages`](https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html) that should flag this use (if enabled).

**Comment by serendipity1004** [comment]
@maheshmnj 

pubspec.yaml

```yaml
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  bootpay_api: ^3.1.33
  go_router: ^3.1.0
  retrofit: '>=3.0.0 <4.0.0'
  badges: ^2.0.2
  dio: ^4.0.6
  logger: any
  equatable: ^2.0.3
  cached_network_image: ^3.2.0
  flutter_secure_storage: ^5.0.2
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.0.0 <4.0.0'
  json_serializable: '>4.4.0'
```

when I am using 2.10.5
<img width="531" alt="Screen Shot 2022-05-20 at 10 24 43 AM" src="https://user-images.githubusercontent.com/20388249/169430132-f446de17-a15d-4aa0-b0d5-093633ded20a.png">

flutter doctor
```sh
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.4 21F79 darwin-arm, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

when I am using 3.0.0

<img width="525" alt="Screen Shot 2022-05-20 at 10 30 22 AM" src="https://user-images.githubusercontent.com/20388249/169430674-f41d1f9f-fd67-4c35-986a-c68deacc2cde.png">

```sh
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 21F79 darwin-arm, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

I am using IntelliJ 2021.3.3.
