### ISSUE TITLE
crash with EXC_BAD_ACCESS with Geolocator or google_maps_flutter

### ISSUE THREAD

**Issue by johnspackman** [flutter/flutter#104417]
## Steps to Reproduce

Start the app, Google Maps loads, and then sometimes the app will crash. 

My Flutter app is intermittently crashing during a call to `Geolocator.getCurrentPosition` - this is not an exception which can be caught with try...catch, the application simply terminates when running under the VSCode debugger. On the few occasions when I have been able to make this happen while debugging with XCode, the error reported is EXC_BAD_ACCESS

This appears to coincide with a message in the console saying that Google Maps SDK is initialising, so I mention it here.

See also this report which seems very similar: https://issuetracker.google.com/issues/224584852?pli=1

Attached are screenshots from XCode when it caught the EXC_BAD_ACCESS exception; the error is in glvmRasterOpDepthStencilTest and in the previous stack element it appears that UIApplicationMain is trying to send the message "Application violated contract by causing UIApplicationMain() to return. This incident will be reported."

I have reported this to Geolocator also because it crashes in their function, even though it appears to be some kind of interaction with Google Maps that triggers it

See here: https://github.com/Baseflow/flutter-geolocator/issues/1062

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
Does not crash

**Actual results:** 
Crashes and app dies instantly

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
It's too long to paste here, i'll upload it separately as an attachment
```

```
 flutter analyze
Analyzing Kandula...                                                    
No issues found! (ran in 0.6s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 21F79 darwin-arm (Rosetta), locale en-GB)
    • Flutter version 3.0.0 at /Users/john/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/john/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 48292EA7-75CB-4649-B947-FFA02A4D56E9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.4 21F79
      darwin-arm (Rosetta)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @johnspackman,
As far as I can see, there are no `google_maps_flutter` dependencies in `flutter-geolocator`. 

It'll be great if you could provide us a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to verify this issue.
Thanks.

**Comment by johnspackman** [comment]
@huycozy They are definitely in use.  This is from my pubspec.yaml:

```
  google_maps_flutter: ^2.0.6
  geolocator: ^8.2.0
```

and pubspec.lock:
```
  geolocator:
    dependency: "direct main"
    description:
      name: geolocator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.2.1"
  geolocator_android:
    dependency: transitive
    description:
      name: geolocator_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.8"
  geolocator_apple:
    dependency: transitive
    description:
      name: geolocator_apple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
  geolocator_platform_interface:
    dependency: transitive
    description:
      name: geolocator_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.5"
  geolocator_web:
    dependency: transitive
    description:
      name: geolocator_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5"
  geolocator_windows:
    dependency: transitive
    description:
      name: geolocator_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1"
  google_maps_flutter:
    dependency: "direct main"
    description:
      name: google_maps_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5"
  google_maps_flutter_platform_interface:
    dependency: transitive
    description:
      name: google_maps_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5"
  google_maps_utils:
    dependency: "direct main"
    description:
      name: google_maps_utils
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.0+0"
```

Although I have tried to create a completed and minimal reproducible example, I have been unable to do so - presumably because of how this is related to timings in a non-trivial application.

Did you see that there is a bug report in Google Maps for iOS where there is an exception in the same method `glvmRasterOpDepthStencilTest`?

Looks like I forgot to upload the screenshots, apologies I'll do that now
