### ISSUE TITLE
`//flutter/ci/lint.sh` lints all files instead of just the ones modified in the patch.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#105068]
Per [a recent run](https://ci.chromium.org/p/flutter/builders/try/Mac%20clang-tidy/4231?), the `//flutter/ci/lint.sh` takes around ~27 mins to run over the entire codebase even though no source files were changed in that patch. Moreover, the linter goes over the files twice (at least) as the simulator variant is linted again (even though almost all the files are the same).

This step should ideally be a no-op but usually ends up taking over an hour.

**Comment by jmagman** [comment]
If you remove `--lint-all` from here:
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/engine_lint.py#77

I recommend a new task that _does_ lint all files, even ones that aren't changed, if `.clang-tidy` or its script is updated. This will allow us some confidence that we fixed all platforms when turning on new warnings (like https://github.com/flutter/engine/pull/33666)
```
  - name: Mac clang-tidy All
...
    timeout: 75
    runIf:
      - DEPS
      - .ci.yaml
      - .clang-tidy
      - tools/**
```
