### ISSUE TITLE
Run `flutter format .` on auto-generated localization files

### ISSUE THREAD

**Issue by ueman** [flutter/flutter#105013]
## Use case

We're using Flutters localization mechanism with the following `l10n.yaml`:

```yml
arb-dir: lib/l10n
template-arb-file: source.arb
output-localization-file: app_localizations.dart
synthetic-package: false
output-dir: lib/l10n/generated
output-class: AppLocalizations
nullable-getter: false
```

This means we have the generated files in our git repository. We're also using `flutter format .` as a step in our CI. We can manually format those files without a problem, but because flutter regenerated those files quite frequently, it's quite tedious to do that every time.
Thus I would like to see an option to have the formatter run on those files automatically.

## Proposal

Add an option to auto-format generated localization files.
