### ISSUE TITLE
Dart analysis fails after upgrade to Flutter 3 in Intellij IDEA

### ISSUE THREAD

**Issue by AlexBurdu** [flutter/flutter#105398]
Dart analysis shows `error: Target of URI doesn't exist` for all packages after upgrading to Flutter 3

I've been waiting since the initial Flutter 3 release for a fix to come and since none seems to have arrived, I decided to raise this issue as it makes Flutter 3 unusable for me.

## Steps to Reproduce

1. Use Intellij Idea Ultimate 2022.1.2 or Android Studio 2021.2.1 Patch 1 (probably happens on other versions as well, but I tried on these)
2. Upgrade Flutter from `2.10.5` to `3.0.1`
3. Update pubspec.yaml:

```
environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"
```
4. Update/fix outdated deps failing build
5. Run the application

### What happens?

- **Application builds and runs fine**
- Dart Analysis fails in the IDE and  there is no IDE indexation and support
- All imports are underlined with red and shown as errors

Example of errors:

```
error: Target of URI doesn't exist: 'package:flutter/material.dart'. (uri_does_not_exist at [finance] lib/finance.dart:4)
error: Target of URI doesn't exist: 'package:flutter/services.dart'. (uri_does_not_exist at [finance] lib/finance.dart:5)
error: Target of URI doesn't exist: 'package:flutter_gen/gen_l10n/app_localizations.dart'. (uri_does_not_exist at [finance] lib/finance.dart:6)
error: Target of URI doesn't exist: 'package:flutter_localizations/flutter_localizations.dart'. (uri_does_not_exist at [finance] lib/finance.dart:7)
```

**If I downgrade Flutter the errors go away and dart analysis works fine**

```
flutter downgrade 2.10.5
```

## Logs

<details>
<summary>Logs</summary>

```yaml
version: 1.0.0+1

publish_to: none

environment: # https://docs.flutter.dev/development/tools/sdk/releases
  sdk: ">=2.17.1 <3.0.0" # Dart SDK version
  flutter: ">=3.0.1"

dependencies:
  bloc: ^8.0.0
  collection: ^1.15.0
  dropdown_search: ^5.0.2
  fixnum: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations: # https://flutter.dev/docs/development/accessibility-and-localization/internationalization
    sdk: flutter
#  flutter_login: ^3.2.0
  http: ^0.13.4
  intl: ^0.17.0
  json_serializable: ^6.1.6
  logger: ^1.0.0
  protobuf: ^2.0.0-nullsafety.0
  session:
    path: ../session

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  test: ^1.21.1

flutter:
  generate: true    # Add this line
  uses-material-design: true

```

```
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.4.0-65-generic, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /home/burfee/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at /home/burfee/apps/AndroidSDK
    • Platform android-31, build-tools 31.0.0-rc5
    • ANDROID_HOME = /home/burfee/apps/AndroidSDK
    • Java binary at: /home/burfee/apps/JetBrains/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/burfee/apps/JetBrains/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/burfee/apps/JetBrains/apps/IDEA-U/ch-0/221.5787.30
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Pixel 6 (mobile) • 192.168.0.32:8888 • android-arm64  • Android 12 (API 32)
    • Linux (desktop)  • linux             • linux-x64      • Ubuntu 20.04.4 LTS 5.4.0-65-generic
    • Chrome (web)     • chrome            • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
