### ISSUE TITLE
Camera Package has problems with System.nanoTime on devices like: SAMSUNG J7 Prime

### ISSUE THREAD

**Issue by KBRR11** [flutter/flutter#105450]
My Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Versi¢n 10.0.22000.675], locale es-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```
My pubspect:
```
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  animate_do: ^2.1.0
  # awesome_select: ^5.2.0
  flutter_awesome_select: ^6.3.0
  back_button_interceptor: ^5.0.2
  camera: ^0.9.7+1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.1
  firebase_messaging: ^11.4.0
  flutter:
    sdk: flutter
  flutter_google_places_sdk: ^0.3.2+1
  flutter_image_compress: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_vibrate: ^1.3.0
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.4
  google_mlkit_face_detection: ^0.3.0
  http: ^0.13.4
  # image_gallery_saver: ^1.7.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  modal_bottom_sheet: ^2.0.1
  otp_text_field: ^1.1.3
  package_info_plus: ^1.4.2
  page_transition: ^2.0.5
  path_provider: ^2.0.10
  permission_handler: ^9.2.0
  provider: ^6.0.2
  rounded_loading_button: ^2.1.0
  url_launcher: ^6.1.0
  video_compress: ^3.1.0
  video_player: ^2.4.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
```
The problem arises when I stop the recording, get the specific path and I can see the first frame of the video in VideoPlayer, but when I try to play it the screen freezes and only the audio of the recording is heard.
I saw that in several forums it is mentioned that the problem was caused by the codec.

but I got this comment:
https://github.com/flutter/flutter/issues/53941#issuecomment-645258889
and it seems that it is true because I restarted the device and everything worked normally, but when I left the cell phone blocked for about 5 minutes the error reappeared(deep suspension)
Is there currently a solution for this? I have seen several problems closed because there is no solution.
