### ISSUE TITLE
Target aot_android_asset_bundle failed: IconTreeShakerException: Invalid ConstFinder result.

### ISSUE THREAD

**Issue by misici234** [flutter/flutter#105535]
## Steps to Reproduce
1. Execute `flutter build apk -v`

**Expected results:** APK file created

**Actual results:** Error
Target aot_android_asset_bundle failed: IconTreeShakerException: Invalid ConstFinder result. Expected "fontPackage" to be a String, "fontFamily"
to be a String, and "codePoint" to be an int, got: {codePoint: 0, fontFamily: null, fontPackage: null, matchTextDirection: false}.

<details>
I tried different versions of Flutter SDK and always got the same error above. Here are more details

```
--elf=/Users/borismisic/AndroidStudioProjects/how_flutter_creates_new_project1/.dart_tool/flutter_build/436f5bc7d9abfe781831a5d2c1bf5d27/x86_64/app.so --strip
/Users/borismisic/AndroidStudioProjects/how_flutter_creates_new_project1/.dart_tool/flutter_build/436f5bc7d9abfe781831a5d2c1bf5d27/app.dill
[ +303 ms] [ +313 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[ +198 ms] [ +245 ms] Running command: /Users/borismisic/Developer/SDKs/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/borismisic/Developer/SDKs/flutter/bin/cache/artifacts/engine/darwin-x64/const_finder.dart.snapshot --kernel-file
/Users/borismisic/AndroidStudioProjects/how_flutter_creates_new_project1/.dart_tool/flutter_build/436f5bc7d9abfe781831a5d2c1bf5d27/app.dill --class-library-uri
package:flutter/src/widgets/icon_data.dart --class-name IconData
[+32901 ms] [+32894 ms] android_aot_release_android-x64: Complete
[+1099 ms] [+1047 ms] android_aot_release_android-arm: Complete
[ +699 ms] [ +700 ms] android_aot_release_android-arm64: Complete
[ +101 ms] [  +99 ms] Persisting file store
[        ] [  +10 ms] Done persisting file store
[   +2 ms] [  +23 ms] Target aot_android_asset_bundle failed: IconTreeShakerException: Invalid ConstFinder result. Expected "fontPackage" to be a String, "fontFamily"
to be a String, and "codePoint" to be an int, got: {codePoint: 0, fontFamily: null, fontPackage: null, matchTextDirection: false}.
[   +4 ms]            To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command
[        ]            #0      IconTreeShaker._parseConstFinderResult (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:311:9)
[        ]            #1      IconTreeShaker._findConstants (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:299:12)
[        ]            <asynchronous suspension>
[        ]            #2      IconTreeShaker._getIconData (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:112:45)

```

I have the same error regardless of what I build: apk, appbundle or ipa.
Flutter build generates all this files if I add option --no-tree-shake-icons. Also I don't have any problem to build debug versions, only release.
I tried everything, 
flutter clean
flutter pub get
I created the project from scratch and copied everything relevant from old project to new and still the same error.
Please ask me for more details if you need it.
</details>

<details>
  <summary>Logs</summary>
`flutter analyze` outputs only info type messages; there are are no errors or warnings

```
```

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-x64, locale en-CA)
    • Flutter version 2.10.5 at /Users/borismisic/Developer/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (7 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/borismisic/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/borismisic/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/borismisic/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • 0F5D4584-E3CE-4D9D-BDBB-F139A8B12FBA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 102.0.5005.61
    ! Error: Boris’s iPhone is not connected. Xcode will continue when Boris’s iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Here is the content of my pubspec.yaml file without top part which is irrelevant
```

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.3
  http: ^0.13.4
  syncfusion_flutter_calendar: 20.1.50
  syncfusion_flutter_datepicker: 20.1.50
  syncfusion_flutter_core: 20.1.50
  intl: ^0.17.0
  flutter_local_notifications: ^9.5.3+1
  provider: ^6.0.3
  sqflite_sqlcipher: ^2.1.1
  visibility_detector: ^0.2.2
  synchronized: ^3.0.0+2
  local_auth: ^2.1.0
  font_awesome_flutter: ^10.1.0
  email_validator: ^2.0.1
  package_info_plus: 1.4.2
  connectivity_plus: ^2.3.2
  device_info_plus: 3.2.3
  crypto: ^3.0.1
  flutter_html: 2.2.1
  url_launcher: ^6.1.2
  flutter_inappwebview: ^5.4.3+7
  html_unescape: ^2.0.0
  signalr_core: ^1.1.1
  collection: ^1.15.0
  firebase_core: 1.12.0
  firebase_messaging: 11.2.6
  flutter_native_timezone: ^2.0.0
  webview_flutter: 2.8.0
  material_design_icons_flutter: ^5.0.6595
  html_editor_enhanced: 2.4.0+1
  encrypted_shared_preferences: ^3.0.0
  jwt_decoder: ^2.0.1
  flutter_native_splash: ^2.0.5
  geolocator: ^8.2.1
#  fk_user_agent: 2.1.0
  flash: ^2.0.3+2
  flutter_chat_bubble: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  # The following honors dependency for local_auth
  # flutter_plugin_android_lifecycle: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/images/
    - assets/localizations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#2196F3"
  image: "assets/images/splash-icon.png"
```
