### ISSUE TITLE
Ubuntu bot salt provision is failing when installing `firefox-esr`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#105740]
Ubuntu bots provisioning via salt is failing when installing package `firefox-esr`.

```
----------
          ID: packages
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit: run-r017352e3f78a40d98b56e4a48ccfc978.scope
                    E: Package 'firefox-esr' has no installation candidate
     Started: 13:54:54.623829
    Duration: 6892.22 ms
     Changes:   
```
