### ISSUE TITLE
no forward method in AnimationController : weird analyzer error in my flutter packages

### ISSUE THREAD

**Issue by rxlabz** [flutter/flutter#10579]
I have a weird analyzer error when I try to use some animationController methods in my Flutter (pure Dart, not plugin) packages  : 

`The method 'forward' isn't defined for the class 'AnimationController'`

![flutilz_example_dart_-_yx017-protos_-____projects_ytbx017_protos__-_intellij_idea_2017_1_4_eap](https://user-images.githubusercontent.com/1397248/26929626-a3a84764-4c5a-11e7-925a-6b95cb1c20ad.png)

Same symptom/errors if I run `flutter analyzer`

Here a package example : https://github.com/rxlabz/flutter_package_error

the pubspec.yaml

```
name: flutter_package_error
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0
```

Am I missing something ?

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale fr-FR, channel master)
    • Flutter at /Users/rxlabz/dev/tools/flutter
    • Framework revision 4d2806e7e5 (4 hours ago), 2017-06-08 10:51:56 +0200
    • Engine revision 1f765cdba7
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/rxlabz/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4 EAP)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4424.63

[✓] Connected devices
    • A3 A40    • 622004271815                             • android-arm • Android 6.0 (API 23)
    • RXMiniPad • f58ff425258a52e7af3a8509246f6e3f5b3c113a • ios         • iOS 10.3.2 (14F89)
```

Any idea ? Is it due to my environment ?

**Comment by mit-mit** [comment]
I can repro this; not sure what is causing it. @danrubel any ideas?

**Comment by mit-mit** [comment]
Removing `analysis_options.yaml` makes analysis pass. Not entirely sure why...

**Comment by rxlabz** [comment]
Thanks @mit-mit ! so it's not caused by my xcode9 beta installation :) 
Does it change something for the "Strong Mode activation" to remove `analysis_options.yaml` in a Flutter project ?

**Comment by Hixie** [comment]
You need to make sure you have
```yaml
analyzer:
  language:
    enableStrictCallChecks: true
    enableSuperMixins: true
    enableAssertInitializer: true
  strong-mode:
    implicit-dynamic: false
```

@pq any idea why this isn't working out of the box?
