### ISSUE TITLE
"Bad CPU type in executable" when building a flutter app for iOS from an Intel based Mac with Flutter v3.0.2

### ISSUE THREAD

**Issue by mikegogovapps** [flutter/flutter#106054]
### Environment

- OS: macOS Montgomery - 12.2.1
- Processor: 2.6 GHz Dual-Core Intel Core i5
- Flutter version: 3.0.2

### Steps to Reproduce

- Clone flutter v3.0.2
- Navigate to the hello world sample: `cd examples/hello_world `
- Build for iOS: `flutter build ios --release --no-codesign`
- Notice the error: **bin/internal/shared.sh: line 225: bin/cache/dart-sdk/bin/dart: Bad CPU type in executable**

I think this may have something to do with the change:
https://github.com/flutter/flutter/commit/bb4a5fa7ab825c3ab6541cf70353aaa7eb301aef#diff-fecfc9dccd8a04f4936b4fa1bf09db14f099197ead58e7633009ac282443c4d0R225

**Comment by ebjorklund01** [comment]
I am seeing this error building the app in our github actions, but I am not seeing this when I build locally on my intel mac.

`/Users/runner/hostedtoolcache/flutter/3.0.2-stable/x64/bin/internal/shared.sh: line 225: /Users/runner/hostedtoolcache/flutter/3.0.2-stable/x64/bin/cache/dart-sdk/bin/dart: Bad CPU type in executable`

```
 build:
    name: Build Apps
    runs-on: macos-11
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: gem install fastlane
    - run: flutter doctor -v
   ```

Still builds fine if I specify flutter 3.0.1.
