### ISSUE TITLE
Flutter display blank web page with webview_flutter on Android

### ISSUE THREAD

**Issue by riccardopirani** [flutter/flutter#106088]
I have a problem with the visualization of a web page with webview_flutter, I have to display a web view, when I run the code on ios the view is displayed correctly, when I run the same code on android I have a blank page, how do I solve this thing? To what it is due, I report below the source codes

## Steps to Reproduce

1. flutter pub get
2. flutte run
3.

**Expected results:** Display web page

**Actual results:** Display Blank page only on Android on ios it works

<details>
<summary>Pubspec.yaml</summary>

```yaml
name: myapp
description: sss

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  shared_preferences: ^2.0.0
  rflutter_alert: ^2.0.4
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  animations: ^2.0.0
  webview_flutter: ^3.0.4
  dio: ^4.0.6
  dartdoc: ^5.0.1
  nfc_manager: ^3.1.1
  permission_handler: ^9.2.0
  flutter_nfc_reader:
    git:
      url: git://github.com/matteocrippa/flutter-nfc-reader.git
      ref: master
  flutter_nfc_kit: ^3.3.1
  ndef: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
```
</details>

<details>
<summary>Flutter Code</summary>

```dart
import 'dart:io';

import 'package:appsafetyeurope/model/Manutenzione.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

String URLLOAD = "https://marconisoftware.com";

class ReportView extends StatefulWidget {
  final Manutenzione man;
  final String token;
  final String url;

  const ReportView(this.man, this.token, this.url);

  @override
  createState() => ReportViewState();
}

class ReportViewState extends State<ReportView> {
  void _handleLoad(String value) {}

  @override
  void initState() {
    super.initState();
    // Enable virtual display.
    if (Platform.isAndroid) {
      //WebView.platform = SurfaceAndroidWebView();
      WebView.platform = AndroidWebView();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            leading: IconButton(
              icon: Icon(Icons.arrow_back_ios),
              iconSize: 20.0,
              onPressed: () {
                Navigator.pop(context);
              },
            ),
            centerTitle: true,
            title: Text('Report')),
        body: IndexedStack(
          index: 0,
          children: [
            Column(
              children: <Widget>[
                Expanded(
                    child: WebView(
                  javascriptMode: JavascriptMode.unrestricted,
                  onWebViewCreated: (WebViewController webViewController) {
                    Map<String, String> headers = {"Cmdbuild-authorization": widget.token};
                    webViewController.loadUrl(
                        "https://platform.safetyeurope.eu/openmaint-test/services/rest/v3/reports/286763/Activity%20report.pdf?extension=pdf&parameters=%7B%22ProcessId%22%3A22222
                            "%7D",
                        headers: headers);
                  },
                  onPageFinished: _handleLoad,
                )),
              ],
            ),
            Container(
              color: Colors.white,
              child: Center(
                child: CircularProgressIndicator(),
              ),
            ),
          ],
        ));
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1
    21E258 darwin-arm, locale en-IT)
    • Flutter version 2.10.4 at
      /Users/riccardo/development/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 months ago),
      2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices
    (Android SDK version 31.0.0)
    • Android SDK at /Users/riccardo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • iPhone with Apple Watch (mobile) •
      66B7106A-CDE3-4FDF-988D-ACDC23A79EC9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-5
      (unsupported) (simulator)
    • Chrome (web)                     • chrome
      • web-javascript • Google Chrome 102.0.5005.115
    ! Error: iPhone di Riccardo is not connected. Xcode
      will continue when iPhone di Riccardo is connected.
      (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
