### ISSUE TITLE
[tool] Crash url is broken in logs

### ISSUE THREAD

**Issue by asashour** [flutter/flutter#106183]
On the crash reported in #106182, the URL written to the console is too long.

When it is opened by Chrome `102.0.5005.115`, there is an error.

<img src=https://user-images.githubusercontent.com/2410127/174271875-7baef648-a577-4801-a139-2a418a12e17f.png width=400>

>Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+RangeError%3A+RangeError+%28index%29%3A+Invalid+value%3A+Valid+value+range+is+empty%3A+0&body=%23%23+Command%0A%60%60%60%0Aflutter+--no-color+run+--machine+--track-widget-creation+--device-id%3Demulator-5554+--start-paused+--dart-define%3Dflutter.inspector.structuredErrors%3Dtrue+lib%5Cmain.dart%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0ARangeError%3A+RangeError+%28index%29%3A+Invalid+value%3A+Valid+value+range+is+empty%3A+0%0A%60%60%60%0A%230++++++_StringBase.%5B%5D+%28dart%3Acore-patch%2Fstring_patch.dart%3A260%3A41%29%0A%231++++++LocalizationsGenerator._isValidGetterAndMethodName+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A1048%3A13%29%0A%232++++++LocalizationsGenerator.loadResources+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A1073%3A12%29%0A%233++++++generateLocalizations+%28package%3Aflutter_tools%2Fsrc%2Flocalizations%2Fgen_l10n.dart%3A68%3A9%29%0A%234++++++GenerateLocalizationsTarget.build+%28package%3Aflutter_tools%2Fsrc%2Fbuild_system%2Ftargets%2Flocalizations.dart%3A56%3A5%29%0A%235++++++_BuildInstance._invokeInternal+%28package%3Aflutter_tools%2Fsrc%2Fbuild_system%2Fbuild_system.dart%3A839%3A27%29%0A%3Casynchronous+suspension%3E%0A%236++++++FlutterBuildSystem.build+%28package%3Aflutter_tools%2Fsrc%2Fbuild_system%2Fbuild_system.dart%3A606%3A16%29%0A%3Casynchronous+suspension%3E%0A%237++++++generateLocalizationsSyntheticPackage+%28package%3Aflutter_tools%2Fsrc%2Fdart%2Fgenerate_synthetic_packages.dart%3A58%3A30%29%0A%3Casynchronous+suspension%3E%0A%238++++++FlutterCommand.verifyThenRunCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1336%3A7%29%0A%3Casynchronous+suspension%3E%0A%239++++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1195%3A27%29%0A%3Casynchronous+suspension%3E%0A%2310+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2311+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%3Casynchronous+suspension%3E%0A%2312+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A281%3A9%29%0A%3Casynchronous+suspension%3E%0A%2313+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2314+++++FlutterCommandRunner.runCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A229%3A5%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+master%2C+3.1.0-0.0.pre.1288%2C+on+Microsoft+Windows+%5BVersion+10.0.19044.1706%5D%2C+locale+en-US%29%0A++++%E2%80%A2+Flutter+version+3.1.0-0.0.pre.1288+at+C%3A%5Cuse%5Cflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fasashour%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+58007fc64c+%283+hours+ago%29%2C+2022-06-17+08%3A16%3A06+%2B0200%0A++++%E2%80%A2+Engine+revision+ee71e31c36%0A++++%E2%80%A2+Dart+version+2.18.0+%28build+2.18.0-190.0.dev%29%0A++++%E2%80%A2+DevTools+version+2.14.0%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.0%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5Cahmed_ashour%5CAppData%5CLocal%5CAndroid%5CSdk%0A++++%E2%80%A2+Platform+android-33%2C+build-tools+33.0.0%0A++++%E2%80%A2+ANDROID_SDK_ROOT+%3D+C%3A%5CUsers%5Cahmed_ashour%5CAppData%5CLocal%5CAndroid%5CSdk%0A++++%E2%80%A2+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio1%5Cjre%5Cbin%5Cjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A++++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%E2%9C%93%5D+Visual+Studio+-+develop+for+Windows+%28Visual+Studio+Community+2022+17.2.3%29%0A++++%E2%80%A2+Visual+Studio+at+C%3A%5CProgram+Files%5CMicrosoft+Visual+Studio%5C2022%5CCommunity%0A++++%E2%80%A2+Visual+Studio+Community+2022+version+17.2.32526.322%0A++++%E2%80%A2+Windows+10+SDK+version+10.0.20348.0%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2021.1%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2021.2%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio1%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.12%2B7-b1504.28-7817840%29%0D%0A%0A%5B%E2%9C%93%5D+IntelliJ+IDEA+Community+Edition+%28version+2022.1%29%0A++++%E2%80%A2+IntelliJ+at+C%3A%5CProgram+Files%5CJetBrains%5CIntelliJ+IDEA+Community+Edition+2021.2.1%0A++++%E2%80%A2+Flutter+plugin+version+68.1.4%0A++++%E2%80%A2+Dart+plugin+version+221.5787.37%0A%0A%5B%E2%9C%93%5D+IntelliJ+IDEA+Ultimate+Edition+%28version+2022.1%29%0A++++%E2%80%A2+IntelliJ+at+C%3A%5CProgram+Files%5CJetBrains%5CIntelliJ+IDEA+221.5080.93%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+version+221.5480%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.67.1%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5Cahmed_ashour%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%A2+Flutter+extension+version+3.40.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%284+available%29%0A++++%E2%80%A2+sdk+gphone64+x86+64+%28mobile%29+%E2%80%A2+emulator-5554+%E2%80%A2+android-x64++++%E2%80%A2+Android+13+%28API+33%29+%28emulator%29%0A++++%E2%80%A2+Windows+%28desktop%29++++++++++++%E2%80%A2+windows+++++++%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.19044.1706%5D%0A++++%E2%80%A2+Chrome+%28web%29+++++++++++++++++%E2%80%A2+chrome++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+102.0.5005.115%0A++++%E2%80%A2+Edge+%28web%29+++++++++++++++++++%E2%80%A2+edge++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+102.0.1245.41%0A%0A%5B%E2%9C%93%5D+HTTP+Host+Availability%0A++++%E2%80%A2+All+required+HTTP+hosts+are+available%0A%0A%E2%80%A2+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+0.0.2%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+master%0A%2A%2ACreation+framework+version%2A%2A%3A+cbb8881b23e1ce453ca517e742a33413fd033f01%0A%23%23%23+Plugins%0Aflutter_background_service-2.1.3%0Aflutter_background_service_android-2.0.3%0Aflutter_background_service_ios-2.1.0%0Aflutter_facebook_auth-4.3.4%2B1%0Aflutter_facebook_auth_web-3.1.2%0Agoogle_sign_in-5.3.3%0Agoogle_sign_in_android-5.2.8%0Agoogle_sign_in_ios-5.3.1%0Agoogle_sign_in_web-0.10.1%2B2%0Alibphonenumber-2.0.2%0Alibphonenumber_plugin-0.2.3%0Alibphonenumber_web-0.2.0%2B1%0Apackage_info_plus-1.4.2%0Apackage_info_plus_linux-1.0.5%0Apackage_info_plus_macos-1.3.0%0Apackage_info_plus_web-1.0.5%0Apackage_info_plus_windows-1.0.5%0Apath_provider_linux-2.1.7%0Apath_provider_windows-2.0.7%0Ashared_preferences-2.0.15%0Ashared_preferences_android-2.0.12%0Ashared_preferences_ios-2.1.1%0Ashared_preferences_linux-2.1.1%0Ashared_preferences_macos-2.0.4%0Ashared_preferences_web-2.0.4%0Ashared_preferences_windows-2.1.1%0Asign_in_with_apple-4.0.0%0Asign_in_with_apple_web-1.0.1%0A%0A&labels=tool%2Csevere%3A+crash

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1288, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 3.1.0-0.0.pre.1288 at C:\use\flutter
    • Upstream repository https://github.com/asashour/flutter.git
    • Framework revision 58007fc64c (3 hours ago), 2022-06-17 08:16:06 +0200
    • Engine revision ee71e31c36
    • Dart version 2.18.0 (build 2.18.0-190.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\ahmed_ashour\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = C:\Users\ahmed_ashour\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.20348.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 221.5080.93
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 221.5480

[✓] VS Code (version 1.67.1)
    • VS Code at C:\Users\ahmed_ashour\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 102.0.1245.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by asashour** [comment]
Please find the [console output](https://github.com/flutter/flutter/files/8927661/log.txt) and the [crash log](https://github.com/flutter/flutter/files/8927670/flutter_03.log)

**Comment by maheshmnj** [comment]
Thanks for the info @asashour  Are there any known steps to reproduce this error?

**Comment by asashour** [comment]
The steps are the same as in #106182, considering Windows and Android Studio are installed.

Please find `pubspec.yaml` with all the dependencies, I assume the more dependencies, the longer the URL.

<details>
<summary>pubspec.yaml</summary>

```
name: abc
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  package_info_plus: ^1.4.2
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.3.4+2
  sign_in_with_apple: ^4.0.0
  http: ^0.13.4
  path: ^1.8.2
  intl: ^0.17.0
  flutter_background_service: ^2.1.3
  intl_phone_number_input: ^0.7.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.21.1
  flutter_lints: ^2.0.1
  icons_launcher: ^1.2.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - images/
    - images/flags/

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
```
</details>

**Comment by asashour** [comment]
Thanks, I investigate the issue further.

If the string is URL deocoded, there is a section:

```
## Flutter Application Metadata
**Type**: app
...
**Creation channel**: master
**Creation framework version**: cbb8881b23e1ce453ca517e742a33413fd033f01
### Plugins
...
...
...
```

This `### Plugins` section is making the URL too long, and it is printed only if `.flutter-plugins` exists

https://github.com/flutter/flutter/blob/3598f20002b5c722296ac283283c8b751e0bc2d3/packages/flutter_tools/lib/src/reporting/github_template.dart#L145-L146


So, the steps to reproduce this in a new project:

- Add some dependencies to `pubspec.yaml` (or more of you wish).
<details>
<summary>dependencies</summary>

```
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  package_info_plus: ^1.4.2
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.3.4+2
  sign_in_with_apple: ^4.0.0
  http: ^0.13.4
  path: ^1.8.2
  intl: ^0.17.0
  flutter_background_service: ^2.1.3
  intl_phone_number_input: ^0.7.0+2
```
</details>

- Have a valid `app_en.arb`, e.g.
```
{
  "abc": "ok"
}
```
- Then build the project for Android (so that `.flutter-plugins` is created)
- Then make the `app_en.arb` invalid, e.g.
```
{
  "": "oh no!"
}
```
- The error message would be too long.

**Comment by maheshmnj** [comment]
thanks for the info @asashour, i just realized that the link generated in your logs works fine too you can verify by decoding the url here https://meyerweb.com/eric/tools/dencoder/.

 Its the length of the url which is causing the issue. This length is enforced by the browser not sure if flutter can do anything here. Surprisingly I added all you dependencies and some more  additonal dependencies but for me the link gets decoded and works fine.

Can you please share your `pubspec.yaml`? 

<details>
<summary>pubspec.yaml</summary>

```yaml
name: locals_bug_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3  
  google_fonts: ^3.0.1
  navbar_router: ^0.2.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  flutter_background_service: ^2.1.3
  flutter_background_service_android: ^2.0.3
  flutter_background_service_ios: ^2.1.0
  flutter_facebook_auth: 4.3.4+2
  flutter_facebook_auth_web: ^3.1.2
  google_sign_in: ^5.3.3
  google_sign_in_android: ^5.2.8
  google_sign_in_ios: ^5.3.1
  google_sign_in_web: ^0.10.1+2
  package_info_plus: ^1.4.2
  package_info_plus_linux: ^1.0.5
  package_info_plus_macos: ^1.3.0
  package_info_plus_web: ^1.0.5
  package_info_plus_windows: ^1.0.5
  path_provider_linux: ^2.1.7
  path_provider_windows: ^2.0.7
  shared_preferences_android: ^2.0.12
  shared_preferences_ios: ^2.1.1
  shared_preferences_linux: ^2.1.1
  shared_preferences_macos: ^2.0.4
  shared_preferences_web: ^2.0.4
  shared_preferences_windows: ^2.1.1
  sign_in_with_apple: ^4.0.0
  sign_in_with_apple_web: ^1.0.1

  mask_text_input_formatter: ^1.0.6
  package_info: ^0.4.0+16
  path: ^1.6.4
  photo_view: ^0.14.0
  pin_code_text_field: ^1.7.1
  provider: ^5.0.0
  razorpay_flutter: ^1.2.7
  rxdart: ^0.27.3
  searchfield: ^0.3.1
  share: ^0.6.3+5
  shimmer: ^1.0.1
  sms_autofill: ^2.2.0
  sqflite: ^1.3.0
  webview_flutter: ^0.3.24

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
</details> 
 
<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (5 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.43.20220621

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
