### ISSUE TITLE
Flutter federated plugin - calling method doesn't go to implementation

### ISSUE THREAD

**Issue by PandaGeek1024** [flutter/flutter#106486]
## Steps to Reproduce

I have created a federated plugin with implementations for web, android and iOS. For some reason, however,it only works for web. When I run android and iOS, they all receive
`MissingPluginException(No implementation found for method getPlatformVersion on channel testerplugin)`

Looks like it goes to the interface package directly and not the actual android/iOS implementation. I observed that the url_launcher lib has the auto-generated class 'dart_plugin_registrant.dart', which does the routing job, that my plugin doesn't have. Am I missing any step?

I have also checked this [thread](https://github.com/flutter/flutter/issues/103632), but it seems different to my issue since ios works for him.

pubspec.yaml from the app facing plugin 'proxy_plugin:
```
environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  testerplugin_interface:
    path: ../testerplugin_interface
  testerplugin_test_ios:
    path: ../testerplugin_test_ios
  testerplugin_web:
    path: ../testerplugin_web
  tester_android:
    path: ../tester_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: tester_android
      ios:
        default_package: testerplugin_test_ios
      web:
        default_package: testerplugin_web
```

pubspec.yaml from tester_android
```
environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  testerplugin_interface:
    path: ../testerplugin_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: proxy_plugin
    platforms:
      android:
        package: com.example.tester_android
        pluginClass: TesterAndroidPlugin
```

tester_android code(iOS is similar):
```
class TesterAndroid extends TesterpluginPlatform {

  static void registerWith() {
    TesterpluginPlatform.instance = TesterAndroid();
  }

  @override
  Future<String?> getPlatformVersion() async {
    return 'android 1.0.0';
  }
}
```

pubspec.yaml from testerplugin_test_ios
```
environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  testerplugin_interface:
    path: ../testerplugin_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: proxy_plugin
    platforms:
      ios:
        pluginClass: TesterpluginTestIosPlugin

```
Please let me know if you anything else from me.

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-AU)
    • Flutter version 3.0.2 at /Users/jayhuang/Developer/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/jayhuang/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone 13 Pro Max (mobile)  • 7412786D-F15F-465E-8672-6F7EBB7AFEA0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>
