### ISSUE TITLE
Federated plugin + Incomplete import in the generated_plugin_registrant.dart

### ISSUE THREAD

**Issue by PandaGeek1024** [flutter/flutter#106467]
## Steps to Reproduce

I have a plugin created using the federated approach. The problem is that in the example of the app facing plugin the generated_plugin_registrant.dart contains an incomplete import which is pointing to the app-facing package but without completed. And there is a duplicated line causing error too.

I have tried clean and rebuild but no luck.

generated_plugin_registrant.dart in example
```
import 'package:testerplugin/'; //problematic incomplete line
import 'package:testerplugin_web/testerplugin_web.dart';

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
  TesterpluginWeb.registerWith(registrar);
  TesterpluginWeb.registerWith(registrar); // problematic duplicate line
  registrar.registerMessageHandler();
}
```
pubspec.yaml from my app facing plugin
```
environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  testerplugin_interface:
    path: ../testerplugin_interface
  testerplugin_ios:
    path: ../testerplugin_ios
  testerplugin_web:
    path: ../testerplugin_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TesterpluginIos
      web:
        pluginClass: TesterpluginWeb
```

pubspec.yaml for the testerplugin_web
```
environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  testerplugin_interface:
    path: ../testerplugin_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: testerplugin
    platforms:
      web:
        pluginClass: TesterpluginWeb
        fileName: testerplugin_web.dart
```
testerplugin_web.dart in testerplugin_web plugin
```
class TesterpluginWeb extends TesterpluginPlatform{
  static void registerWith(Registrar registrar) {
    TesterpluginPlatform.instance = TesterpluginWeb();
  }

  @override
  Future<String?> getPlatformVersion() async {
    return 'Web 1.0.0';
  }
}
```

Flutter doctor -v
```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-AU)
    • Flutter version 3.0.2 at /Users/jayhuang/Developer/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/jayhuang/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone 13 Pro Max (mobile)  • 7412786D-F15F-465E-8672-6F7EBB7AFEA0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>
