### ISSUE TITLE
Removed packages not getting removed from Xcode linked frameworks

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [flutter/flutter#106413]
Hi 👋🏼

I have a Flutter project that was initially written using v2.2.3. Below is the `pubspec.yaml` and the linker flags in the Xcode project. This project ran fine in Android and iOS both.

<details>
<summary>pubspec.yaml</summary>

```yaml
name: my_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.22+65

environment:
  sdk: ">=2.1.0 <3.0.0"

analyzer:
  enable-experiment:
    - control-flow-collections

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: 0.19.3
  intl: 0.17.0
  rxdart: 0.23.1
  provider: 4.3.2
  http: 0.12.2
  cached_network_image: 2.0.0
  flutter_secure_storage: 3.3.5
  shared_preferences: 0.5.12+4
  flutter_typeahead: 1.8.0
  flutter_signature_pad: 3.0.0
  dotted_border: 1.0.7
  dropdown_search: ^1.0.0
  flutter_webview_plugin: 0.4.0
  image_picker: 0.6.7+22
  sqflite: 1.3.2+4
  path_provider: 1.6.27

  package_info: ^2.0.2
  currency_text_input_formatter: 1.0.5
  fluttertoast: 8.0.8
  dart_ipify: ^1.1.1
  get_mac: ^0.0.1
  geolocator: 6.2.1
  http_parser: 3.1.4
  url_launcher: 5.7.10
  jwt_decode: ^0.3.1
  flutter_guid: 0.1.0
  mask_text_input_formatter: ^2.0.0
  flutter_email_sender: 5.0.2
  camera: 0.8.1+7
  sentry: 3.0.1
  system_info: 1.0.1
  device_info: 2.0.3
  flutter_sound_lite: 7.8.4
  permission_handler: 5.1.0+2
  wakelock: 0.2.1+1
  toggle_switch: ^1.4.0
  qr_code_scanner: ^0.7.0
  flutter_bloc: ^6.0.6
  equatable: ^2.0.3
  logger: ^0.9.4
  popover: ^0.2.6+3
  webview_flutter: ^2.0.13
  collection: ^1.15.0
  badges: ^2.0.2
  date_range_picker: ^1.0.5
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.8.0

flutter:
  uses-material-design: true
```
</details>

<details>
<summary>Images</summary>

<img width="548" alt="1" src="https://user-images.githubusercontent.com/2551877/175050629-b5dccb4c-e8b7-4e08-afea-8d9915bb2f9d.png">

<img width="550" alt="2" src="https://user-images.githubusercontent.com/2551877/175050677-3f3996dc-a6f6-47c5-8f5c-9f884924918f.png">
</details>

I recently upgraded this app to use Flutter v3.1.0. By upgrading I meant, I upped the flutter version (I use fvm) and one by one I added latest versions of the dependencies. Some of the previously used packages were out of date or simply did not work with the latest Flutter version. So I replaced them with newer versions or similar packages. Here is the updated `pubspec.yaml` file and the resulting linker flags.

<details>
<summary>Updated pubspec.yaml</summary>

```yaml
name: my_app
description: My app.

publish_to: "none"

version: 0.0.23+70

environment:
  sdk: ">=2.2.2 <3.0.0"

analyzer:
  enable-experiment:
    - control-flow-collections

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.5
  flutter_svg: 0.23.0+1
  intl: 0.17.0
  rxdart: 0.27.4
  provider: 6.0.3
  http: 0.13.4
  cached_network_image: 3.2.1
  flutter_secure_storage: 5.0.2
  shared_preferences: 2.0.15
  flutter_typeahead: 4.0.0
  flutter_signature_pad: 3.0.1
  dotted_border: 2.0.0+1
  dropdown_search: 5.0.2
  image_picker: 0.8.5+3
  sqflite: 2.0.2+1
  path_provider: 2.0.11
  package_info_plus: 1.4.2
  currency_text_input_formatter: 2.1.5
  fluttertoast: 8.0.9
  dart_ipify: 1.1.1
  get_mac: 0.0.1
  geolocator: 8.2.1
  http_parser: 4.0.1
  url_launcher: 6.1.3
  jwt_decode: 0.3.1
  flutter_guid: 0.2.0
  mask_text_input_formatter: 2.3.0
  flutter_email_sender: 5.1.0
  camera: 0.9.7+1
  sentry_flutter: 6.5.1
  system_info: 1.0.1
  device_info_plus: 3.2.4
  flutter_sound_lite: 8.5.0
  permission_handler: 9.2.0
  wakelock: 0.6.1+2
  toggle_switch: 2.0.1
  qr_code_scanner: 1.0.0
  flutter_bloc: 8.0.1
  equatable: 2.0.3
  logger: 1.1.0
  webview_flutter: 3.0.4
  collection: 1.16.0
  date_ranger: 0.0.1
  signalr_core: 1.1.1
  badges: 2.0.3
  uuid: 3.0.6
  app_settings: 4.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.9.3

flutter:
  uses-material-design: true
```
</details>

<details>
<summary>Images</summary>

<img width="573" alt="Screenshot 2022-06-22 at 7 47 08 PM" src="https://user-images.githubusercontent.com/2551877/175052352-46170ac1-ef3b-4804-a038-71c468b50f56.png">

<img width="572" alt="Screenshot 2022-06-22 at 7 47 34 PM" src="https://user-images.githubusercontent.com/2551877/175052536-7a50a7a6-843c-4b0f-af5d-196f382b45d2.png">
</details>

If you look closely you might notice even though the packages are updated, the linker flags are the same as the old version.

I anyway ran `flutter build ios` and I got this error.

<details>
<summary>Error logs</summary>

```bash
➜  my_app git:(flutter_upgrade) ✗ fvm flutter clean
Cleaning Xcode workspace...                                         6.5s
Deleting build...                                                  103ms
Deleting .dart_tool...                                              14ms
Deleting .packages...                                                0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting Flutter.podspec...                                          0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
➜  my_app git:(flutter_upgrade) ✗ fvm flutter build ios -t lib/main_qa.dart --flavor qa
Running "flutter pub get" in my_app...                          512ms
Building com.a1spareparts.mobileapp.qa for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: 74PQ29XM2K
Running pod install...                                           1,756ms
Running Xcode build...                                          
Xcode build done.                                           60.0s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[10976]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x219ccb640) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107fd42c8). One of the two will be used. Which one is undefined.
    objc[10976]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x219ccb690) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107fd4318). One of the two will be used. Which one is undefined.
    objc[10976]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x219ccb458) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107fd44f8). One of the two will be used. Which one is undefined.
    objc[10976]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x219ccb4a8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107fd4548). One of the two will be used. Which one is undefined.
    objc[10976]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x219ccb4f8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107fd4598). One of the two will be used. Which one is undefined.
    objc[10976]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x219ccb548) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107fd45e8). One of the two will be used. Which one is undefined.
    objc[10976]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x219ccb598) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107fd4638). One of the two will be used. Which one is undefined.
    objc[10976]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x219ccb5e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107fd4688). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/__/8vp0y8ld7dg5msyx608xzj1c0000gn/T/flutter_tools.q0bxmM/flutter_ios_build_temp_dirWtusTW/temporary_xcresult_bundle

    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/permission_handler_apple-9.0.4/ios/Classes/strategies/PhonePermissionStrategy.m:50:35: warning: 'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0 [-Wdeprecated-declarations]
        CTCarrier *carrier = [netInfo subscriberCellularProvider];
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                      serviceSubscriberCellularProviders
    In module 'CoreTelephony' imported from /Users/isuru/.pub-cache/hosted/pub.dartlang.org/permission_handler_apple-9.0.4/ios/Classes/strategies/PhonePermissionStrategy.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/System/Library/Frameworks/CoreTelephony.framework/Headers/CTTelephonyNetworkInfo.h:112:50: note: property 'subscriberCellularProvider' is declared deprecated here
    @property(readonly, retain, nullable) CTCarrier *subscriberCellularProvider API_DEPRECATED_WITH_REPLACEMENT("serviceSubscriberCellularProviders", ios(4.0, 12.0)) API_UNAVAILABLE(macos);
                                                     ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/System/Library/Frameworks/CoreTelephony.framework/Headers/CTTelephonyNetworkInfo.h:112:50: note: 'subscriberCellularProvider' has been explicitly marked deprecated here
    1 warning generated.
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-2.2.0/ios/Classes/GeolocatorPlugin.m:179:21: warning: 'openURL:' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
                        openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
                        ^~~~~~~
                        openURL:options:completionHandler:
    In module 'UIKit' imported from /Users/isuru/Desktop/my_app/ios/Pods/Target Support Files/geolocator_apple/geolocator_apple-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:124:1: note: 'openURL:' has been explicitly marked deprecated here
    - (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0)) NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    1 warning generated.
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_email_sender-5.1.0/ios/Classes/SwiftFlutterEmailSenderPlugin.swift:26:57: warning: 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes
            guard let viewController = UIApplication.shared.keyWindow?.rootViewController else {
                                                            ^
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundRecorderManager.mm:100:37: warning: comparison of distinct pointer types ('FlutterSoundRecorder *' and 'NSNull * _Nonnull') [-Wcompare-distinct-pointer-types]
                    if (aFlautoRecorder != [NSNull null])
                        ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~
    1 warning generated.
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundRecorder.mm:260:14: warning: unused variable 'b' [-Wunused-variable]
            bool b = [flautoRecorder deleteRecord: path];
                 ^
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundRecorder.mm:36:17: warning: method definition for 'setDbPeakLevelUpdate:result:' not found [-Wincomplete-implementation]
    @implementation FlutterSoundRecorder
                    ^
    In file included from /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundRecorder.mm:32:
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundRecorder.h:56:1: note: method 'setDbPeakLevelUpdate:result:' declared here
    - (void)setDbPeakLevelUpdate:(double)intervalInSecs result: (FlutterResult)result;
    ^
    2 warnings generated.
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundPlayer.mm:81:94: warning: implicit boolean conversion of Objective-C object literal always evaluates to true [-Wobjc-literal-conversion]
            [self invokeMethod:@"needSomeFood" numberArg: [NSNumber numberWithInt: ln]  success: @YES ];
            ~                                                                                    ^~~~
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundPlayer.mm:101:80: warning: implicit boolean conversion of Objective-C object literal always evaluates to true [-Wobjc-literal-conversion]
            [self invokeMethod:@"pause" numberArg: [self getPlayerStatus] success: @YES ];
            ~                                                                      ^~~~
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundPlayer.mm:106:82: warning: implicit boolean conversion of Objective-C object literal always evaluates to true [-Wobjc-literal-conversion]
            [self invokeMethod:@"resume" numberArg: [self getPlayerStatus]  success: @YES ];
            ~                                                                        ^~~~
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundPlayer.mm:111:87: warning: implicit boolean conversion of Objective-C object literal always evaluates to true [-Wobjc-literal-conversion]
            [self invokeMethod:@"skipForward" numberArg: [self getPlayerStatus]  success: @YES ];
            ~                                                                             ^~~~
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundPlayer.mm:117:88: warning: implicit boolean conversion of Objective-C object literal always evaluates to true [-Wobjc-literal-conversion]
            [self invokeMethod:@"skipBackward" numberArg: [self getPlayerStatus]  success: @YES ];
            ~                                                                              ^~~~
    5 warnings generated.
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.m:35:17: warning: class 'FlutterSoundManager' does not conform to protocol 'FlutterPlugin' [-Wprotocol]
    @implementation FlutterSoundManager
                    ^
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.m:35:17: note: add stubs for missing protocol requirements
    @implementation FlutterSoundManager
                    ^
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.m:109:17: warning: method definition for 'reset:result:' not found [-Wincomplete-implementation]
    @implementation Session
                    ^
    In file included from /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.m:31:
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.h:42:1: note: method 'reset:result:' declared here
    - (void)reset: (FlutterMethodCall*)call result: (FlutterResult)result;
    ^
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.m:109:17: warning: method definition for 'getStatus' not found [-Wincomplete-implementation]
    @implementation Session
                    ^
    In file included from /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.m:31:
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.h:43:1: note: method 'getStatus' declared here
    - (int) getStatus;
    ^
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.m:109:17: warning: method definition for 'freeSlot:' not found [-Wincomplete-implementation]
    @implementation Session
                    ^
    In file included from /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.m:31:
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.h:52:1: note: method 'freeSlot:' declared here
    - (void)freeSlot: (int)slotNo;
    ^
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.m:109:17: warning: method definition for 'invokeMethod:arguments:' not found [-Wincomplete-implementation]
    @implementation Session
                    ^
    In file included from /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.m:31:
    /Users/isuru/.pub-cache/hosted/pub.dartlang.org/flutter_sound_lite-8.5.0/ios/Classes/FlutterSoundManager.h:53:1: note: method 'invokeMethod:arguments:' declared here
    - (void)invokeMethod: (NSString*)methodName arguments: (NSDictionary*)call ;
    ^
    5 warnings generated.
    ld: framework not found device_info
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/isuru/Desktop/my_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'Toast' from project 'Pods')
    /Users/isuru/Desktop/my_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'MTBBarcodeScanner' from project 'Pods')
    /Users/isuru/Desktop/my_app/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'FMDB' from project 'Pods')

    Result bundle written to path:
        /var/folders/__/8vp0y8ld7dg5msyx608xzj1c0000gn/T/flutter_tools.q0bxmM/flutter_ios_build_temp_dirWtusTW/temporary_xcresult_bundle


Error (Xcode): Framework not found device_info

Encountered error while building for device.
```
</details>

As you can see it's throwing an error for a package that I no longer use (I replaced `device_info` with `device_info_plus`) in the new version. But it exists in the linker flags so this error comes.

## Things I Tried

* I deleted the `Pods` directory and `Podfile.lock` and ran `pod install` several times.
* Executed `pod deintegrate` and ran `pod install`.
* Executed `flutter clean` and `flutter pub get` several times.
* Executed `flutter pub cache clean`.
* Removed redundant frameworks (like `device_info`) from Xcode's linker flags list. It got past the initial error but then the same error started coming for packages that I actually use even in the upgraded version (like `webview_flutter`) which I cannot delete.
* Deleted the entire ios directory from the Flutter project, executed `flutter create` inside the root to regenerate the Xcode project. Here are the linker flags of the newly created Xcode project.

<details>
<summary>Images</summary>

<img width="554" alt="1" src="https://user-images.githubusercontent.com/2551877/175054795-97ad2a6e-a82b-438c-8534-f2516248ee1b.png">
<img width="561" alt="2" src="https://user-images.githubusercontent.com/2551877/175054819-d71a1d92-530b-4150-882f-630c179fa62b.png">
<img width="547" alt="3" src="https://user-images.githubusercontent.com/2551877/175054831-2182f2d4-81e2-4bf1-a42c-de9620a4973c.png">

</details>

It got rid of the pesky errors BUT it wasn't the end of my troubles. The first screen of the  app is a button that shows a webview. Now it doesn't show the webview at all. 

So none of the above attempts fully fixed my issues. Any suggestions would be greatly appreciated. Maybe on how to re-embed the frameworks in Xcode correctly without having to nuke the project and re-create it?

</details>

<details>
  <summary>Logs</summary>

[log.txt](https://github.com/flutter/flutter/files/8958665/log.txt)

There is a lot of errors (more than now actually) but these didn't pose any issues when I ran for iOS before the upgrade. I fixed some but there's more to go.

[analyze.txt](https://github.com/flutter/flutter/files/8958683/analyze.txt)

```
fvm flutter doctor -v
[✓] Flutter (Channel beta, 3.1.0, on macOS 12.4 21F79 darwin-arm, locale en-GB)
    • Flutter version 3.1.0 at /Users/isuru/fvm/versions/3.1.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bcea432bce (4 weeks ago), 2022-05-26 09:05:34 -0700
    • Engine revision 44e5b38ee8
    • Dart version 2.18.0 (build 2.18.0-44.1.beta)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/isuru/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (1 available)
    • iPhone 12 Pro (mobile) • 598A53C1-BFE9-4D58-80FD-CB1B9E67E199 • ios • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    ! Error: Mobile Team’s iPad is not connected. Xcode will continue when Mobile Team’s iPad is connected. (code -13)
    ! Error: Isuru's iPad is not connected. Xcode will continue when Isuru's iPad is connected. (code -13)
    ! Error: Isuru's iPhone is not connected. Xcode will continue when Isuru's iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>
