### ISSUE TITLE
iOS 15 crash: The application must have a host view since the keyboard client must be part of the responder chain to function. The host view controller is (null)

### ISSUE THREAD

**Issue by boluokvmd** [flutter/flutter#106404]
App crashes on iOS 15.0.0 and above

Steps to Reproduce
I do not have a clear way to reproduce this issue but i get crash reports from firebase Crashlytics here is the stack trace:
```
Fatal Exception: NSInternalInconsistencyException
The application must have a host view since the keyboard client must be part of the responder chain to function. The host view controller is (null)
```
This same crash was reported in a [previous issue](https://github.com/flutter/flutter/issues/87809) and should be resolved in the latest flutter rollout but is still happening. Also for context my app is a custom add2app scenario and this crash happens when my flutter application hands over control back to the native app

<details>
  <summary>crash logs</summary>
  
```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x92d0c __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  Foundation                     0x124c90 _userInfoForFileAndLine
3  Flutter                        0x28874 (Missing UUID bab62788d88339b192aed18e13dece71)
4  Flutter                        0x28dd4 (Missing UUID bab62788d88339b192aed18e13dece71)
5  Flutter                        0x2797c (Missing UUID bab62788d88339b192aed18e13dece71)
6  Flutter                        0x55a33c (Missing UUID bab62788d88339b192aed18e13dece71)
7  Flutter                        0x424e8 (Missing UUID bab62788d88339b192aed18e13dece71)
8  libdispatch.dylib              0x63094 _dispatch_call_block_and_release
9  libdispatch.dylib              0x64094 _dispatch_client_callout
10 libdispatch.dylib              0x10d44 _dispatch_main_queue_drain
11 libdispatch.dylib              0x10994 _dispatch_main_queue_callback_4CF$VARIANT$mp
12 CoreFoundation                 0x4e0c4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0xb5e8 __CFRunLoopRun
14 CoreFoundation                 0x1e240 CFRunLoopRunSpecific
15 GraphicsServices               0x1988 GSEventRunModal
16 UIKitCore                      0x4e541c -[UIApplication _run]
17 UIKitCore                      0x27eb88 UIApplicationMain
18 SwiftUI                        0x1f0d68 closure #1 in KitRendererCommon(_:)
19 SwiftUI                        0x13b83c runApp<A>(_:)
20 SwiftUI                        0x1211dc static App.main()
21                 0xae10 main (<compiler-generated>)
22 ???                            0x1070dc3d0 (Missing)
```

</details>

<details>
  <summary>flutter doctor -v</summary>
  
```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.3 21E230 darwin-arm, locale
    en-NG)
    • Flutter version 3.0.2 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at 
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart



```

</details>

<details>
  <summary>pubspec.yaml</summary>
  
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  mockito: ^5.0.7
  mask_text_input_formatter: ^2.0.0
  http: ^0.13.2
  loading_overlay: ^0.2.1
  url_launcher: ^6.0.12
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  pin_code_fields: ^7.3.0
  lottie: ^1.1.0
  sms_autofill: ^2.2.0
  connectivity_plus: ^2.0.2
  flutter_html: ^2.2.1
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2
  encrypt: ^5.0.1
  flutter_markdown: ^0.6.10
  firebase_crashlytics: ^2.8.1
  firebase_core: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1

flutter:
  uses-material-design: true


```

</details>
