### ISSUE TITLE
[fonts][ios] Some italic styles not rendering for TTF files under iOS

### ISSUE THREAD

**Issue by PeterDekkers** [flutter/flutter#106646]
Hello! I work for a type foundry. We're experiencing an issue with a particular font of ours called [Geograph](https://klim.co.nz/retail-fonts/geograph/). It doesn't render its italic styles correctly in Flutter iOS apps. The italic styles render as non-italicised text.

## Steps to Reproduce

1. Copy the test font files from [GeographTest.zip](https://github.com/flutter/flutter/files/8988741/GeographTest.zip) to a folder called `fonts/GeographTest` in your project.
1. Open the iOS Simulator `open -a simulator`
1. Execute `flutter run` on the code sample

**Expected results:** 

The app should show the following in italicised text: `Thin Italic, Light Italic, Regular Italic, Medium Italic, Bold Italic, Black Italic`.

**Actual results:** 

Only `Thin Italic` renders italicised, the other styles render incorrectly as non-italicised text.

<img width="376" alt="Screen Shot 2022-06-27 at 4 55 02 PM" src="https://user-images.githubusercontent.com/425971/175862885-ff4104a7-7663-48c5-90c0-3a9bdaa8171b.png">

We've tested a number of different typefaces, including several of our own, and all others work correctly. We've also double checked all settings in the Geograph TTF files, and from our point of view there doesn't seem to be anything wrong with the TTF files—they have been produced following industry standards.

As a workaround we can define separate font families in `pubspec.yaml`, one for each TTF file. This does allow the italic TTFs to load and display.

<details>
<summary>Code sample</summary>

`pubspec.yaml`
```yaml
name: geograph_italics_test
description: A Flutter project to test italics use in the Geograph font family.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Geograph 1.008 Test TTF
      fonts:
        - asset: fonts/GeographTest/GeographTest-Thin.ttf
          weight: 100
          style: normal
        - asset: fonts/GeographTest/GeographTest-Thin Italic.ttf
          weight: 100
          style: italic
        - asset: fonts/GeographTest/GeographTest-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/GeographTest/GeographTest-Light Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/GeographTest/GeographTest-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/GeographTest/GeographTest-Regular Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/GeographTest/GeographTest-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/GeographTest/GeographTest-Medium Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/GeographTest/GeographTest-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/GeographTest/GeographTest-Bold Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/GeographTest/GeographTest-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/GeographTest/GeographTest-Black Italic.ttf
          weight: 900
          style: italic
```

`main.dart`
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Italics test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Italics test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

List<Widget> test(String fontFamily) {
  return [
    Text('\n$fontFamily',
        style: TextStyle(
            fontWeight: FontWeight.w700, fontSize: 18, fontFamily: fontFamily)),
    RichText(
      text: TextSpan(children: [
        TextSpan(
            text: 'Thin Italic, ',
            style: TextStyle(
                fontWeight: FontWeight.w100,
                fontStyle: FontStyle.italic,
                color: Colors.black,
                fontFamily: fontFamily)),
        TextSpan(
            text: 'Light Italic, ',
            style: TextStyle(
                fontWeight: FontWeight.w300,
                fontStyle: FontStyle.italic,
                color: Colors.black,
                fontFamily: fontFamily)),
        TextSpan(
            text: 'Regular Italic, ',
            style: TextStyle(
                fontWeight: FontWeight.w400,
                fontStyle: FontStyle.italic,
                color: Colors.black,
                fontFamily: fontFamily)),
        TextSpan(
            text: 'Medium Italic, ',
            style: TextStyle(
                fontWeight: FontWeight.w500,
                fontStyle: FontStyle.italic,
                color: Colors.black,
                fontFamily: fontFamily)),
        TextSpan(
            text: 'Bold Italic, ',
            style: TextStyle(
                fontStyle: FontStyle.italic,
                fontWeight: FontWeight.w700,
                color: Colors.black,
                fontFamily: fontFamily)),
        TextSpan(
            text: 'Black Italic',
            style: TextStyle(
                fontStyle: FontStyle.italic,
                fontWeight: FontWeight.w900,
                color: Colors.black,
                fontFamily: fontFamily)),
      ]),
      textAlign: TextAlign.center,
    ),
  ];
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Padding(
          padding: const EdgeInsets.only(left: 18.0, right: 18.0),
          child: Center(
            child: Column(
              children: <Widget>[
                ...test('Geograph 1.008 Test TTF'),
              ],
            ),
          )),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

`flutter run --verbose`
```
// Output was way too long sorry... No exceptions were thrown... Ends with:
[   +9 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch 2BF3A75F-ADDA-4EB8-949C-4768BCB1254F com.klimTypeFoundry.geographItalicsTest --enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0
[ +119 ms] com.klimTypeFoundry.geographItalicsTest: 53139
[        ] Waiting for observatory port to be available...
[ +346 ms] Observatory URL on device: http://127.0.0.1:63550/QCwuyEmqP5A=/
[   +3 ms] Caching compiled dill
[  +50 ms] Connecting to service protocol: http://127.0.0.1:63550/QCwuyEmqP5A=/
[  +74 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:63550/QCwuyEmqP5A=/.
[  +72 ms] DDS is listening at http://127.0.0.1:63553/nVRjKOrHSu0=/.
[  +55 ms] Successfully connected to service protocol: http://127.0.0.1:63550/QCwuyEmqP5A=/
[  +19 ms] DevFS: Creating new filesystem on the device (null)
[  +12 ms] DevFS: Created new filesystem on the device (file:///Users/peter/Library/Developer/CoreSimulator/Devices/2BF3A75F-ADDA-4EB8-949C-4768BCB1254F/data/Containers/Data/Application/E1258C3D-F019-4643-9FB5-E01B63549214/tmp/FlutterTestAppZcKbDO/FlutterTestApp/)
[   +1 ms] Updating assets
[  +43 ms] Syncing files to device iPhone SE (3rd generation)...
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:geograph_italics_test/main.dart c8185bc7-ef7a-4a08-a74a-fdd09d5cd936
[        ] <- c8185bc7-ef7a-4a08-a74a-fdd09d5cd936
[   +2 ms] Bundle processing done.
[  +58 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device iPhone SE (3rd generation)... (completed in 63ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +4 ms] Connected to _flutterView/0x155836620.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[   +1 ms] h List all available interactive commands.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on iPhone SE (3rd generation) is available at: http://127.0.0.1:63553/nVRjKOrHSu0=/
[ +152 ms] The Flutter DevTools debugger and profiler on iPhone SE (3rd generation) is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:63553/nVRjKOrHSu0=/
```

`flutter analyze`
```
Analyzing FlutterTestApp...                                             
No issues found! (ran in 1.2s)
```

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-AU)
    • Flutter version 3.0.2 at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (3 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Users/peter/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Users/peter/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5787.30/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • 2BF3A75F-ADDA-4EB8-949C-4768BCB1254F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>
