### ISSUE TITLE
Flutter: Dart analysis doesn't work after using package in dev_dependencies.

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#107122]
Normally, dart analysis will notice every time something is not correctly like missing const.
![image](https://user-images.githubusercontent.com/59549741/177474388-b2836ef5-af90-4421-938f-ce4e5fa34b13.png)

But, dart analysis doesn't work after I use the flutter_native_splash or the flutter_native_splash package used in dev_dependencies. It shows only that thing.
![image](https://user-images.githubusercontent.com/59549741/177474408-38223bbe-1640-477a-9de2-bdea4803bfba.png)
I notice that after cloning a project. Before using these packages in the dev_dependencies, I saw many notices from dart analysis.

What going on? How to use these packages with dart analysis?

**Comment by SittiphanSittisak** [comment]
Thank you so much!
I see your pub pubspec.yaml and see something different.
I never notice `flutter_lints:`  .
So my pdev_dependencies look like this:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.4

flutter_native_splash:
  image: "asset/image.png"

#...
  flutter_lints: ^2.0.0
```

After I saw your comment. I go read the comment over `flutter_lints: ^2.0.0` and I understand this now.

I should place `flutter_lints: ^2.0.0` in `dev_dependencies:` .

I've been stuck with this for months because I think it's a bug. So poor TT.
