### ISSUE TITLE
Error: Couldn't find constructor 'VelocityTracker'. after 'flutter upgrade'

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#107404]
## Steps to Reproduce

1. Execute `flutter run` with these dependencies 

```
name: 
description: 
version: 0.5.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  adaptive_breakpoints: ^0.1.4
  animations: ^2.0.3
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  chewie: ^1.3.4
  cloud_firestore: ^3.2.1
  collection: ^1.15.0
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.5
  equatable: ^2.0.2
  file_picker: ^4.6.1
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_messaging: ^11.4.4
  firebase_storage: ^10.3.1
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_gallery_assets: ^1.0.2
  flutter_localized_locales: ^2.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_localizations:
    sdk: flutter
  flutter_braintree: ^2.3.1
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.8
  google_sign_in: ^5.3.3
  grinder: ^0.9.2
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  meta: ^1.7.0
  mime_type: ^1.0.0
  mockito: ^5.2.0
  package_info_plus: ^1.4.2
  path: ^1.8.1
  pie_chart: ^5.3.2
  provider: ^6.0.3
  rally_assets: ^3.0.1
  rxdart: ^0.27.4
  scoped_model: ^2.0.0-nullsafety.0
  scroll_snap_list: ^0.9.1
  shrine_images: ^2.0.1
  snapping_page_scroll: ^2.1.0
  share: ^2.0.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  vector_math: ^2.1.0
  video_player: ^2.4.5
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  args: ^2.3.1
  flutter_lints: ^2.0.1
  string_scanner: ^1.1.0
  test: ^1.21.1
  web_benchmarks: ^0.0.7
  bloc_test: ^9.0.3
  pedantic: ^1.11.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/vectors/
    - assets/icons/images/
    
 ```
3. upgrade Flutter from 2.10 to 3.0.4
4. run the app and at runtime see the error

**Expected results:** 
Expected the app to run

**Actual results:** 
```
[+1354 ms] ../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-2.0.0/lib/src/bottom_sheet.dart:303:28: Error: Couldn't find constructor 'VelocityTracker'.
[        ]         _velocityTracker = VelocityTracker();
[        ]                            ^^^^^^^^^^^^^^^
[+2943 ms] [+5423 ms] ../../flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-2.0.0/lib/src/bottom_sheet.dart:303:28: Error: Couldn't find constructor 'VelocityTracker'.
[        ] [   +1 ms]         _velocityTracker = VelocityTracker();
[        ] [        ]                            ^^^^^^^^^^^^^^^
```

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
