### ISSUE TITLE
Android production crash in libflutter.so

### ISSUE THREAD

**Issue by franklinharper** [flutter/flutter#10768]
## Steps to Reproduce

I tried, but failed to repro. on the emulator running Android x_86. I also tried using an ARM system image, but that wouldn't even boot the OS!

This is a crash in production. So far the crash has occurred 52 times on 1 type of device: Nexus 5X (bullhead) running Android 6.0. As of June 13th the app is installed on ~6K devices. The Play store doesn't tell me how many of those are Nexus 5Xes running Android 6.0.

The app is https://play.google.com/store/apps/details?id=dictionary.winesecretary.com. This is the first version of the app written using Flutter.

## Logs

> Run your application with `flutter run` and attach all the log output.

This doesn't seem relevant since I can't get the app to crash on any of the devices or emulators I have access to.

### Play Store Crash report

```
backtrace:
  native: pc 000000000053b448  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 000000000053b1c9  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 000000000051f52f  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 0000000000114abd  /data/local/tmp/libhooks.so
  native: pc 000000000004a47b  /data/local/tmp/libhooks.so (capture_native_bt(std::__ndk1::vector<void*, std::__ndk1::allocator<void*> >&)+26)
  native: pc 000000000004615b  /data/local/tmp/libhooks.so (dump_bt(__sFILE*)+126)
  native: pc 0000000000045fc7  /data/local/tmp/libhooks.so (log_stream(int, char const*, char const*, int, char const*, __sFILE*)+506)
  native: pc 0000000000046263  /data/local/tmp/libhooks.so (log_filesystem(int, char const*, char const*, int)+62)
  native: pc 0000000000046f95  /data/local/tmp/libhooks.so ($open(char const*, int, unsigned short)+464)
  native: pc 00000000000547d1  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 0000000000054513  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 00000000000544b3  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 00000000000543f1  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 000000000051dbc3  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 00000000000544e7  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 000000000006d57d  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 000000000004cfd7  /data/app/dictionary.winesecretary.com-1/lib/arm/libflutter.so
  native: pc 000000000002c5c5  /data/app/dictionary.winesecretary.com-1/oat/arm/base.odex
```

### flutter analyze

```
Analyzing /Users/frank/proj/flutter/wine-dictionary-cross-platform...
  error • 'lib' isn't a function at lib/i18n/stock_messages_all.dart:33:54 • invocation_of_non_function
  error • Target of URI doesn't exist: 'package:stocks/main.dart' at test_driver/scroll_perf.dart:6:8 • uri_does_not_exist
  lint • Don't import implementation files from another package at lib/i18n/stock_messages_all.dart:9:8 • implementation_imports
  hint • Unused import at lib/app_home.dart:2:8 • unused_import
  hint • The value of the field '_autorefresh' isn't used at lib/app_home.dart:28:8 • unused_field
  hint • The method '_handleOverflowMenu' isn't used at lib/app_home.dart:49:8 • unused_element
  hint • The method '_handleShowSettings' isn't used at lib/app_home.dart:103:8 • unused_element
  hint • Unused import at lib/app_strings.dart:1:8 • unused_import
  hint • The method '_setString' isn't used at lib/config/app_settings.dart:45:8 • unused_element
  hint • The method '_getString' isn't used at lib/config/app_settings.dart:48:10 • unused_element
10 issues found.
(Ran in 5.4s)
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel alpha)
    • Flutter at /Users/frank/proj/flutter/flutter-sdk
    • Framework revision e2f54df5ab (2 weeks ago), 2017-06-02 10:43:54 -0700
    • Engine revision 1f2aa07571
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/frank/Library/Android/sdk/
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/frank/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Dart plugin version 171.4694.29
    • Flutter plugin version 14.0

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.0.0 (API 26) (emulator)
    • iPhone 7                  • CF597AEE-F339-41AF-94CE-2292B1F12887 • ios         • iOS 10.3 (simulator)
```
