### ISSUE TITLE
[image_picker][android] App restarts on MIUI 12.5

### ISSUE THREAD

**Issue by martesabt** [flutter/flutter#107630]
Hi,
We noticed that using **image_picker [0.8.5+3]** in a **POCO M3 with MIUI 12.5.8.0 (Android 11)** causes the app to restart when the package is used.

It happens on debug and release modes.

## Steps to Reproduce

**Case 1:**
1. Try to pick an image from gallery or camera.
2. The application is restarted.

**Case 2:**
1. Try to pick an image from gallery or camera, but cancel the action.
2. The application is restarted.

**Expected results:** 
The image is returned.

**Actual results:**

App restarts and this LOG is printed:

W/Activity(13408): Slow Operation: Activity [app_pacakge_name].MainActivity onDestroy took 102ms

## CODE
<details>
<summary>pubspec.yaml</summary>

```
name: image_picker_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

</details>

<details>
<summary>main.dart</summary>

```
import 'package:flutter/material.dart';
import 'package:image_picker_test/app.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const App());
}
```

</details>

<details>
<summary>app.dart</summary>

```
import 'package:flutter/material.dart';

import 'main_window.dart';

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MainWindow(),
    );
  }
}
```

</details>

<details>
<summary>main_window.dart</summary>

```
import 'package:flutter/material.dart';

import 'image_picker.dart';

class MainWindow extends StatefulWidget {
  const MainWindow({Key? key}) : super(key: key);

  @override
  State<MainWindow> createState() => _MainWindowState();
}

class _MainWindowState extends State<MainWindow> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Home Screen"),
        backgroundColor: Colors.lightGreen,
      ),
      body: ElevatedButton(
        onPressed: () {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => const ImagePickerScreen()),
          );
        },
        child: Text("new screen"),
      ),
    );
  }
}
```

</details>

<details>
<summary>image_picker.dart</summary>

_We updated this dart file to show an AlertDialog to allow user to pick the image from gallery or camera._

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

class ImagePickerScreen extends StatefulWidget {
  const ImagePickerScreen({Key? key}) : super(key: key);

  @override
  State<ImagePickerScreen> createState() => _ImagePickerScreenState();
}

class _ImagePickerScreenState extends State<ImagePickerScreen> {
  XFile? pickedFile;
  File? imageFile = null;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("ImagePicker"),
      ),
      body: Column(
        children: [
          Container(
            padding: EdgeInsets.only(top: 100),
            child: ElevatedButton(
              child: Text("IMAGE PICKER"),
              onPressed: choosePicture,
            ),
          ),
          imageFile != null
              ? ClipRRect(
                  borderRadius: BorderRadius.circular(100),
                  child: Image.file(
                    imageFile!,
                    fit: BoxFit.cover,
                    height: 150.0,
                    width: 150.0,
                  ),
                )
              : Container()
        ],
      ),
    );
  }

  _getFromGallery() async {
    pickedFile = await ImagePicker().pickImage(
      source: ImageSource.gallery,
      maxWidth: 1024,
      maxHeight: 1024,
    );

    if (pickedFile != null) {
      setState(() {
        imageFile = File(pickedFile!.path);
        Navigator.pop(context);
      });
    }
  }

  _getFromCamera() async {
    pickedFile = await ImagePicker().pickImage(
      source: ImageSource.camera,
      maxWidth: 1024,
      maxHeight: 1024,
    );

    if (pickedFile != null) {
      setState(() {
        imageFile = File(pickedFile!.path);
        Navigator.pop(context);
      });
    }
  }

  Future<String?> choosePicture() {
    return showDialog<String>(
      context: context,
      builder: (BuildContext context) => AlertDialog(
        title: Center(
          child: Text(
            "Picture",
            style: TextStyle(color: Colors.black, fontWeight: FontWeight.w900),
          ),
        ),
        content: Text(
          "Choose an image source",
          style: TextStyle(color: Colors.black, fontSize: 14),
        ),
        actions: <Widget>[
          TextButton(
            onPressed: () => _getFromCamera(),
            child: Text(
              "Take a Photo",
            ),
          ),
          TextButton(
            onPressed: () => _getFromGallery(),
            child: Text(
              "Get From gallery",
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

## LOGS
<details>
  <summary>Logs flutter run --verbose</summary>

```
[   +1 ms] Installing APK.
[   +3 ms] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /Users/daniel/Library/Android/sdk/platform-tools/adb -s 4ec009ca0421 install -t -r
/Users/daniel/AndroidStudioProjects/image_picker_test/build/app/outputs/flutter-apk/app.apk
[+6321 ms] Performing Streamed Install
                    Success
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 6.3s)
[   +1 ms] executing: /Users/daniel/Library/Android/sdk/platform-tools/adb -s 4ec009ca0421 shell echo -n 7280b2d6097f9f1e954837f08a5392922ca6d6cf
> /data/local/tmp/sky.com.example.image_picker_test.sha1
[  +77 ms] executing: /Users/daniel/Library/Android/sdk/platform-tools/adb -s 4ec009ca0421 shell -x logcat -v time -t 1
[ +229 ms] --------- beginning of main
                    07-14 10:13:47.547 I/Avrcp_ext( 6135): updatePlayStatusForDevice: device: null
[  +10 ms] executing: /Users/daniel/Library/Android/sdk/platform-tools/adb -s 4ec009ca0421 shell am start -a android.intent.action.RUN -f
0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.image_picker_test/com.example.image_picker_test.MainActivity
[ +344 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.image_picker_test/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1737 ms] Observatory URL on device: http://127.0.0.1:39413/tKbgRU0ZYss=/
[   +1 ms] executing: /Users/daniel/Library/Android/sdk/platform-tools/adb -s 4ec009ca0421 forward tcp:0 tcp:39413
[  +17 ms] 57947
[        ] Forwarded host port 57947 to device port 39413 for Observatory
[   +5 ms] Caching compiled dill
[ +101 ms] Connecting to service protocol: http://127.0.0.1:57947/tKbgRU0ZYss=/
[ +347 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:57947/tKbgRU0ZYss=/.
[ +220 ms] DDS is listening at http://127.0.0.1:57952/fcfJ_QwPKeQ=/.
[  +67 ms] Successfully connected to service protocol: http://127.0.0.1:57947/tKbgRU0ZYss=/
[  +96 ms] DevFS: Creating new filesystem on the device (null)
[  +54 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.example.image_picker_test/code_cache/image_picker_testKMZOYH/image_picker_test/)
[   +2 ms] Updating assets
[  +98 ms] Syncing files to device M2010J19CG...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:image_picker_test/main.dart d6e72885-5d65-4a54-9ae2-26e86f53f9c4
[        ] <- d6e72885-5d65-4a54-9ae2-26e86f53f9c4
[   +1 ms] Bundle processing done.
[ +260 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device M2010J19CG... (completed in 266ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +6 ms] Connected to _flutterView/0xb40000757d821e20.
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on M2010J19CG is available at: http://127.0.0.1:57952/fcfJ_QwPKeQ=/
[ +860 ms] D/DecorView[](18082): getWindowModeFromSystem  windowmode is 1
[  +22 ms] The Flutter DevTools debugger and profiler on M2010J19CG is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:57952/fcfJ_QwPKeQ=/
[ +115 ms] E/LB      (18082): fail to open file: No such file or directory
[   +6 ms] I/age_picker_tes(18082): ProcessProfilingInfo new_methods=1080 is saved saved_to_disk=1 resolve_classes_delay=8000
[+4981 ms] V/MiuiFrameworkFactory(18082): get AllImpl object = android.common.MiuiFrameworkFactoryImpl@95d86a9
[   +8 ms] W/MirrorManager(18082): this model don't Support
[+2344 ms] I/Timeline(18082): Timeline: Activity_launch_request time:4101133
[+1554 ms] D/DecorView[](18082): getWindowModeFromSystem  windowmode is 1
[        ] D/DecorView(18082): createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
[ +126 ms] D/DecorView[](18082): getWindowModeFromSystem  windowmode is 1
[  +35 ms] D/SurfaceView(18082): UPDATE null, mIsCastMode = false
[+2154 ms] D/DecorView[](18082): getWindowModeFromSystem  windowmode is 1
```

</details>

<details>
  <summary>Logs flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 3.0.2 at /Users/daniel/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (5 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/daniel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (4 available)
    • M2010J19CG (mobile)        • 4ec009ca0421                         • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro Max (mobile) • 17BA3AE3-78CE-404F-A3DB-1F3706D03BB4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

## Screen recording

Here you can see a screen recording of the bug with the sample application:

https://drive.google.com/file/d/19eIRZRJXhWBh2xSC5qg76TTv9Q-TpIss/view?usp=sharing
