### ISSUE TITLE
Improve pod install latency

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10873]
Make sure no redundant work is done with CocoaPod during builds. 

Make sure repeated builds has a fast pod step.

**Comment by xster** [comment]
Related nature of issue #7673

**Comment by mit-mit** [comment]
Tagging customer-blocker and posse per discussion with Al.

**Comment by xster** [comment]
@alardizabal hoping to bug you guys with some extra info. Seems like you were hitting builds where the `pod install` step was taking 30s. Was it reproducible constantly or can you describe the project setup a bit if it is reproducible?

**Comment by mit-mit** [comment]
I tried to repro this by creating an app with lots of plugins in it (see `pubspec.yaml` below). This was slow on the first `flutter run`:

```
mit-macbookpro2:plugintest mit$ flutter run
Launching lib/main.dart on iPhone 6 in debug mode...
Running pod install...                               20.8s
Running Xcode build...                               22.4s
```

But subsequent runs were fairly fast:

```
mit-macbookpro2:plugintest mit$ flutter run
Launching lib/main.dart on iPhone 6 in debug mode...
Running pod install...                                3.0s
Running Xcode build...                               15.8s
```

My `pubspec.yaml`:

```
name: plugintest
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  sqflite: "^0.1.0"
  android_intent:
  battery:
  connectivity:
  google_sign_in:
  image_picker:
  package_info:
  path_provider:
  quick_actions:
  sensors:
  share:
  shared_preferences:
  url_launcher:
  firebase_analytics:
  firebase_auth:
  firebase_database:
  firebase_messaging:
  firebase_storage:
```

**Comment by alardizabal** [comment]
@xster @mit-mit Thanks for following up. I recently uninstalled Xcode 9 because I believe that was part of the slowdown. I'm not sure if you want to test building with Xcode 9. Since reverting back to Xcode 8.3.3 my build times have been more reasonable. My pubspec is below and for pods, I'm bringing in Firebase Auth and Stripe. My `flutter doctor` is below. The pod installs do get progressively quicker on subsequent builds. However, I'm still seeing a lot of observatory timeouts (see below).

```
dependencies:
  flutter:
    sdk: flutter
  path_provider: "^0.2.1+1"
  fluro: "^1.1.0"
  firebase_analytics: "^0.0.3"
  firebase_database: "^0.0.11"
  url_launcher: "^0.4.2+1"
  permit:
    path: ./plugins/permit
```

```
☆ flutter doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/albertlardizabal/dev/flutter
    • Framework revision cb4a54db8f (2 days ago), 2017-06-27 16:19:59 -0700
    • Engine revision 009d470d50
    • Tools Dart version 1.24.2

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b, 
    ✗ libimobiledevice and ideviceinstaller are not installed or require updating. To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Pixel                        • FA71A0302167                             • android-arm • Android 7.1.2 (API 25)
    • XT1032                       • TA9290K3WW                               • android-arm • Android 5.1 (API 22)
    • Albert Lardizabal's iPhone 6 • c0e109b7e55a826627aa0f3e79af8931534f3554 • ios         • iOS 11.0
    • Posse iPhone                 • ac24c3de3cbe39efed542095769ce83fc89630f7 • ios         • iOS 10.3.1
    • iPhone SE                    • FF1E1EF8-E9B0-48A1-97FD-CD606A0F586F     • ios         • iOS 10.3 (simulator)

[10:48:47] (al-stripe_test)
☆ flutter run -d ac24c3de3cbe39efed542095769ce83fc89630f7
Launching lib/main.dart on Posse iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 3MT3K2SKK7
Running pod install...                               16.7s
Running Xcode build...                               46.7s
Timeout while attempting to retrieve URL for Observatory

[10:51:08] (al-stripe_test)
☆ flutter run -d ac24c3de3cbe39efed542095769ce83fc89630f7
Launching lib/main.dart on Posse iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 3MT3K2SKK7
Running pod install...                               10.4s
Running Xcode build...                               45.9s
Timeout while attempting to retrieve URL for Observatory

[10:53:35] (al-stripe_test)
☆ flutter run -d ac24c3de3cbe39efed542095769ce83fc89630f7
Launching lib/main.dart on Posse iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 3MT3K2SKK7
Running pod install...                                8.5s
Running Xcode build...                               62.9s
```
