### ISSUE TITLE
[Android] App using background flutter engine closes when run in release mode

### ISSUE THREAD

**Issue by koga187** [flutter/flutter#109248]
I updated my flutter Beta from 3.1.0-9.0.pre to channel Beta 3.3+ and suddenly my app is crashing when using isolates.

## Steps to Reproduce

Clone the example app below: 
https://github.com/fluttercommunity/flutter_downloader

And run it on **release** mode
Click to download anything.

---
Flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 3.1.0-9.0.pre, on macOS 12.5 21G72 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by danagbemava-nc** [comment]
Hi @koga187, thanks for filing the issue.

What platform are you experiencing the crash on? 

Kindly also share the crash log 

Thank you

**Comment by koga187** [comment]
> Hi @koga187, thanks for filing the issue.
> 
> What platform are you experiencing the crash on?
> 
> Kindly also share the crash log
> 
> Thank you

I`m running the test on Google pixel 3a Android 12

With:

Flutter 3.3.0-0.2.pre • channel beta • git@github.com:flutter/flutter.git
Framework • revision 7ac27ac8e6 (8 days ago) • 2022-08-02 14:35:08 -0700
Engine • revision d1e7dc18bf
Tools • Dart 2.18.0 (build 2.18.0-271.4.beta) • DevTools 2.15.0

---

Log:

```log
Running "flutter pub get" in example...                            859ms
Launching lib/main.dart on Pixel 3a in release mode...
Running Gradle task 'assembleRelease'...                           66.4s
✓  Built build/app/outputs/flutter-apk/app-release.apk (7.0MB).
Installing build/app/outputs/flutter-apk/app.apk...              2,920ms

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
W/FlutterActivityAndFragmentDelegate(12662): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
I/flutter (12662): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (0)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (0)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (1)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (3)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (5)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (7)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (9)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (11)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (13)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (15)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (17)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (19)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (21)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (23)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (25)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (27)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (29)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (31)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (33)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (35)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (37)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (39)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (41)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (43)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (45)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (47)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (49)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (51)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (53)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (55)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (57)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (59)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (61)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (63)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (65)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (67)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (69)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (71)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (73)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (75)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (77)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (79)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (81)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (83)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (85)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (87)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (89)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (91)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (93)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (95)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (97)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (99)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(2)) and process (100)
I/flutter (12968): Callback on background isolate: task (2f86c0c7-74cd-4b70-ac60-5cb60a54ca9e) is in status (DownloadTaskStatus(3)) and process (100)
```

**Comment by atrope** [comment]
Hi! I can confirm it is happening here also with beta 3.3+ and current master.
Downgrading to 3.1 beta make it work again.

Testes on S21 Android 12 and S10 Android 11 and 10

Logs are the same as it is release mode. On profile and Debug it does not happen

**Comment by maheshmnj** [comment]
Hi @koga187, I am able to reproduce the issue on the latest master and beta channel and it works fine on the stable channel. 
The sample app for reproduction can be found here https://github.com/fluttercommunity/flutter_downloader/tree/master/example

Also, I can confirm that the crash only happens in release mode and works fine in debug and profile mode.

Unfortunately, logs don't seem to provide any helpful info. Complete logs can be found here [logs.txt](https://github.com/flutter/flutter/files/9306749/log.txt)


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel beta, 3.3.0-0.2.pre, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.3.0-0.2.pre on channel beta at /Users/mahesh/Documents/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ac27ac8e6 (8 days ago), 2022-08-02 14:35:08 -0700
    • Engine revision d1e7dc18bf
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)    • 192.168.1.4:5555 • android-arm64  • Android 11 (API 30)
    • sdk gphone arm64 (mobile) • emulator-5554    • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos            • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2186, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.2186 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 458c7b9c65 (24 hours ago), 2022-08-10 03:19:07 -0400
    • Engine revision 75e17f1a6f
    • Dart version 2.19.0 (build 2.19.0-81.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)    • 192.168.1.4:5555 • android-arm64  • Android 11 (API 30)
    • sdk gphone arm64 (mobile) • emulator-5554    • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos            • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by atrope** [comment]
Hi, we need this fix because we cannot update our current flutter channel. 🙏🏻

**Comment by maheshmnj** [comment]
cc: @zanderso

**Comment by jonahwilliams** [comment]
Is this crashing, or is it hitting the code below and calling exit?

https://github.com/fluttercommunity/flutter_downloader/blob/master/lib/src/callback_dispatcher.dart#L23-L27

**Comment by atrope** [comment]
hi @jonahwilliams , it is crashing

**Comment by jonahwilliams** [comment]
I don't see any stack traces or tombstones, instead it appears that the app is being backgrounded.

**Comment by jonahwilliams** [comment]
The app still appears to be running and actually performs the download in the background (as can be seen on my phone's status bar). I don't have any clues as to why this behavior would work differently on release vs debug mode.

**Comment by jonahwilliams** [comment]
Maybe @gaaclarke if you know of any changes we made here recently. Exit calls don't appear to be the culprit

**Comment by atrope** [comment]
@jonahwilliams 
```
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 Build fingerprint: 'samsung/o1sxxx/o1s:12/SP1A.210812.016/G991BXXU5CVGC:user/release-keys'
 Revision: '22'
 ABI: 'arm64'
 Processor: '3'
 Timestamp: 2022-08-15 15:35:53.044231831-0300
 Process uptime: 6s
 Cmdline: vn.hunghd.example
 pid: 4142, tid: 4529, name: 2.ui  >>> vn.hunghd.example <<<
 uid: 10795
 signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
 Abort message: '../../third_party/dart/runtime/vm/message_snapshot.cc: 576: error: expected: !lib.IsNull()'
     x0  0000000000000000  x1  00000000000011b1  x2  0000000000000006  x3  00000074bd6ca410
     x4  0000808000000000  x5  0000808000000000  x6  0000808000000000  x7  0000000080800000
     x8  00000000000000f0  x9  e1008f9ea7c98810  x10 0000000000000000  x11 ffffff80fffffbdf
     x12 0000000000000001  x13 000000000000005c  x14 0000000000000000  x15 0000000000000058
     x16 000000785427a058  x17 00000078542575c0  x18 00000074bc9fc000  x19 000000000000102e
     x20 00000000000011b1  x21 00000000ffffffff  x22 00000074bd6ca958  x23 b4000076089d05fa
     x24 b4000075989f5860  x25 0000000000000002  x26 0000000000000000  x27 00000074d8dbd000
     x28 00000074d8dc0000  x29 00000074bd6ca490
     lr  000000785420a03c  sp  00000074bd6ca3f0  pc  000000785420a068  pst 0000000000001000
 backtrace:
       #00 pc 0000000000051068  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 1001969d8caf747bff324cbb95af4b2e)
       #01 pc 000000000069610c  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #02 pc 00000000006ea444  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #03 pc 00000000006eec48  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #04 pc 00000000006d770c  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #05 pc 00000000006ddb10  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #06 pc 00000000005b3ae0  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #07 pc 000000000068d5a4  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #08 pc 000000000034601c  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #09 pc 00000000003495a8  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #10 pc 0000000000016918  /system/lib64/libutils.so (android::Looper::pollInner(int)+912) (BuildId: a8e5883b039c6d018dc9ced53f79b1d0)
       #11 pc 0000000000016520  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: a8e5883b039c6d018dc9ced53f79b1d0)
       #12 pc 0000000000017160  /system/lib64/libandroid.so (ALooper_pollOnce+100) (BuildId: 62576e3de04e2dffcf4fff97dc8f9fdf)
       #13 pc 00000000003496b4  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #14 pc 0000000000347cdc  /data/app/~~eOogrKH2YcwlxgGkpdC-IA==/vn.hunghd.example-zjXitEoFWeHPZta1M8EPEQ==/lib/arm64/libflutter.so (BuildId: f5aa5c6aaeb44d3f571872429658f249bb178d1a)
       #15 pc 00000000000b3020  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: 1001969d8caf747bff324cbb95af4b2e)
       #16 pc 000000000005288c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 1001969d8caf747bff324cbb95af4b2e)

```
