### ISSUE TITLE
Running build on Xcode Cloud Fails: module 'package_info_plus' not found

### ISSUE THREAD

**Issue by zdnk** [flutter/flutter#109551]
## Steps to Reproduce
Not sure, maybe I am doing something wrong. I get:
> module 'package_info_plus' not found

Pubspec
```
name: xxxx
description: A new Flutter project.
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fimber: ^0.6.6
  get_it: ^7.2.0
  sentry_flutter: ^6.5.1
  flutter_dotenv: ^5.0.2
  firebase_core: ^1.17.1
  stacked: ^2.3.12
  firebase_core_web: ^1.6.4
  package_info_plus_web: ^1.0.5
  package_info_plus: ^1.4.3
  gap: ^2.0.0
  flutter_staggered_grid_view: 0.4.0
  syncfusion_flutter_datepicker: ^20.2.38
  flutter_svg: ^1.1.1+1
  flutter_stripe: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  persistent_bottom_nav_bar_v2: ^4.2.4
  firebase_auth: ^3.6.2
  graphql_flutter: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.2.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - .env
flutter_intl:
  enabled: true

```
post clone script:
```
#!/bin/sh

# The default execution directory of this script is the ci_scripts directory.
cd $CI_WORKSPACE # change working directory to the root of your cloned repo.

# Install Flutter using git.
git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
export PATH="$PATH:$HOME/flutter/bin"

# Install Flutter artifacts for iOS (--ios), or macOS (--macos) platforms.
flutter precache --ios

# Install Flutter dependencies.
flutter pub get

# Install CocoaPods using Homebrew.
HOMEBREW_NO_AUTO_UPDATE=1 # disable homebrew's automatic updates.
brew install cocoapods

# Install CocoaPods dependencies.
cd ios && pod install # run `pod install` in the `ios` directory.

exit 0
```

## Logs

<details>
<summary>Logs</summary>

```
/Volumes/workspace/repository/ios/Runner/GeneratedPluginRegistrant.m:30:9: fatal error: module 'package_info_plus' not found
@import package_info_plus;
 ~~~~~~~^~~~~~~~~~~~~~~~~
```
</details>
