### ISSUE TITLE
[integration_test] Documentation of integration_test

### ISSUE THREAD

**Issue by kyeshmz** [flutter/flutter#109649]
The current documentation on the repo only lists `integration_test` as needed, while stating `flutter_test` is needed as well. 
It should align with the official intro, to be like
```yaml
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
```
https://docs.flutter.dev/cookbook/testing/integration/introduction
