### ISSUE TITLE
Flutter app is flagged for Non-SDK API usage violations by Firebase Test Lab

### ISSUE THREAD

**Issue by under3415** [flutter/flutter#109815]
When running Firebase Test Lab Flutter App targeting Android the following warnings are raised:

Your app uses 11 non-SDK interfaces, which are incompatible with Android P+:
See also: https://stackoverflow.com/questions/73369465/flutter-non-sdk-api-usage-violation

````
Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;

Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J

Landroid/util/LongArray;->get(I)J

Landroid/os/Trace;->isTagEnabled(J)Z

Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V

Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V

Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V

Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J

Landroid/media/AudioTrack;->getLatency()I

Landroid/media/AudioManager;->getOutputLatency(I)I

Landroid/os/Trace;->traceEnd(J)V
````

## Steps to Reproduce

1. Create Android app
2. Submit to Firebase Test Lab testing
3. App is using the following packages, not sure if any of that matters. Possibly for the media ones, but accessibility/os ones would not think so. In any case, I have no idea what these things are!

````
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.3
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  path_provider: ^2.0.11
  encrypt: ^5.0.1
  flutter_svg: ^1.1.4
  numberpicker: ^2.1.1
  carousel_slider: ^4.1.1
  lottie: ^1.4.1
  audioplayers: ^1.0.1
  wakelock: ^0.6.2
  assets_audio_player: ^3.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.0.1
  in_app_review: ^2.0.4
  in_app_purchase: ^3.0.6
  firebase_core: ^1.20.0
  firebase_analytics: ^9.3.0
  firebase_crashlytics: ^2.8.6
  app_install_date: ^0.1.1
````

## Logs

<details>
<summary>N/A</summary>

[√] Flutter (Channel beta, 3.3.0-0.3.pre, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.3.0-0.3.pre on channel beta at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8c1149878b (8 days ago), 2022-08-10 12:15:36 -0500
    • Engine revision f16e757d5d
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\dejan\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.22000.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these   
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\dejan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.80
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

```
```

</details>
