### ISSUE TITLE
flutter:stable issue si_signo=Segmentation fault(11), si_code=1, si_addr=0x10

### ISSUE THREAD

**Issue by chilio** [flutter/flutter#109818]
Steps to reproduce in gitlab environment  (gitlab-ci.yml):
1. Grab image, execute basic script:
```
 image: "cirrusci/flutter:stable"
  before_script:
    - flutter doctor
```
2. Error emerging on different multiple runners:

```
$ flutter doctor
../../runtime/bin/eventhandler_linux.cc: 416: error: Failed to start event handler thread 1
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x10
Aborting re-entrant request for stack trace.
/usr/bin/bash: line 1[21]...):    12 Aborted                 (core dumped) flutter doctor
```

Help appreciated

**Comment by huycozy** [comment]
Hi @chilio, are there any more logs you can provide? 
Also, when creating a new `gitlab-ci.yml` file same as yours, there is a warning: `This GitLab CI configuration is invalid: jobs config should contain at least one visible job.`. Could you please provide a complete `gitlab-ci.yml` file content?

**Comment by mraleph** [comment]
This is likely out-of-memory or low resource situation.

**Comment by bikeshedder** [comment]
I did run into the exact same problem as part of a CI pipeline:

```
$ flutter build web --release --web-renderer=auto --dart-define develop=true
../../runtime/bin/eventhandler_linux.cc: 416: error: Failed to start event handler thread 1
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x10
Aborting re-entrant request for stack trace.
/usr/bin/bash: line 126:    13 Aborted                 (core dumped) flutter build web --release --web-renderer=auto --dart-define develop=true
```

I monitored the RAM usage and it never peaks. The crash happens instantly upon starting `flutter build ...`. I don't think this is a low resource situation.

**Comment by bikeshedder** [comment]
I forgot to mention an important bit. The CI pipeline uses the following docker image:

```
Using docker image sha256:9c45b25211e9f91842623cbd2bef651b8b4cbc22b04e090876702d0c11cc07a8 for cirrusci/flutter:3.3.0 with digest cirrusci/flutter@sha256:b85c095fed123419d1cd5abe66c466e69377d2b2d15c23d774111604d98739e9 ...
```

**Comment by mraleph** [comment]
> I don't think this is a low resource situation.

There aren't that many other reasons why creating a new thread can fail. Some type of resource is being exhausted. It might be memory, but it might also be the hard limit on number of processes or threads. It might be the limit configured within the container (though in this case I would expect the error to be more deterministic), but it is possible that `dockerd` itself is hitting a limit imposed on it, this can happen when many containers are run concurrently under the same daemon. If you are controlling the machine which runs `dockerd` check how it is configured (more specifically `ulimit -T` and `ulimit -u` for the `dockerd` itself). If you don't control the machine - you might want to check with your cloud provider.

We can't really do much about this - you need to debug this concrete issue in your cloud environment.

**Comment by bikeshedder** [comment]
After switching from `cirrusci/flutter:3.3.0` to `fischerscode/flutter:3.3.0` the `flutter build` command no longer crashes. I can see a rather high memory usage during build though. All oft the available 4 GB of RAM is allocated almost immediately.

**Comment by chilio** [comment]
@huycozy sorry for late reply,  but here is the full .yml
```
# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Flutter.gitlab-ci.yml

code_quality:
  stage: test
  image: "cirrusci/flutter:1.22.5"
  before_script:
    - pub global activate dart_code_metrics
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test:
  stage: test
  image: "cirrusci/flutter:stable"
  before_script:
    - flutter doctor
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - flutter test > report.xml
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/coverage
    reports:
      junit: report.xml
```
