### ISSUE TITLE
Platform View drawn at wrong position

### ISSUE THREAD

**Issue by usamawork61** [flutter/flutter#110816]
Steps to Reproduce:
Install this library https://github.com/BindrUK/jitsi_meet/tree/platform-view into your app and open a meeting with a single participant.

Expected results:
The video meeting gets drawn within its parent container with bottom bar buttons. To see how it is supposed to look like you can run the app with any previous flutter version like 2.10.5.

Original result:
The video meeting fills whole of the screen and hides everything else. This was working fine on previous versions of flutter. i.e `2.10.5` but not on any `v3+`

**Comment by danagbemava-nc** [comment]
Hi @usamawork61, I created a project and integrated the plugin, and below is what I see.

What do you see on your end? 

Can you also provide a complete runnable code sample that reproduces the bug you're experiencing?

<img src="https://user-images.githubusercontent.com/88313112/188140824-408f82fd-ea39-416e-acc9-1b4850adbe7c.jpeg" width="300" />

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (4 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • M2007J20CG (mobile)    • 5dd3be00                             • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.101

HTTP Host availability check is taking a long time...[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Operation timed
      out

! Doctor found issues in 1 category.
```
</details>

**Comment by usamawork61** [comment]
<img width="342" alt="Screenshot 2022-09-05 at 10 39 59 PM" src="https://user-images.githubusercontent.com/97461994/188496417-f61c13a6-52e1-44ef-954c-86bf2aae02f4.png">

@danagbemava-nc  If you turn onn the camera this is what you will see, it hides all the bottom buttons which was not the case in the previous flutter versions. 

https://github.com/flutter/flutter/issues/103630
This is the link to the previous issue we were following.

**Comment by danagbemava-nc** [comment]
Hi @usamawork61, below is what I see on my end when I run the example and open the camera. 

#103630 has been fixed and the fix should be available on the latest version of stable(3.3.0), what version of flutter are you on?

<img src="https://user-images.githubusercontent.com/88313112/188570003-ca83d2c1-3da5-4e73-91f3-0d367ad877a0.jpeg" width="300"/>

**Comment by usamawork61** [comment]
@danagbemava-nc Can you switch to branch `platform-view` ? https://github.com/BindrUK/jitsi_meet/tree/platform-view
```
 jitsi_meet:
    git:
      url: https://github.com/BindrUK/jitsi_meet
      path: jitsi_meet
      ref: platform-view
```

**Comment by danagbemava-nc** [comment]
Hi @usamawork61, after switching to the `platform-view` branch I still cannot reproduce the issue


<img src="https://user-images.githubusercontent.com/88313112/188642354-22964df3-e30e-444f-876f-e4075fa1544c.jpeg" width="300" />

If possible, kindly share the code sample that you are experiencing the issue with. 

<details>
<summary>pubspec.yaml</summary>

```yaml
name: jmt
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  jitsi_meet:
    git:
      url: https://github.com/BindrUK/jitsi_meet
      path: jitsi_meet
      ref: platform-view

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

```
</details>
