### ISSUE TITLE
Flutter 3.3.0 building apk or ipa in profile and release mode gets stuck and never finishes,but it works fine in debug mode

### ISSUE THREAD

**Issue by CJChen98** [flutter/flutter#111160]
## Steps to Reproduce

1. flutter build apk --profile --verbose >build.log
2. The log shows that the build will get stuck at "aot_android_asset_bundle: Complete"

## Logs

<details>
<summary>Logs</summary>

[build.log](https://github.com/flutter/flutter/files/9522923/build.log)

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.3.0 on channel stable at
      /Users/chunjinchen/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (9 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/chunjinchen/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/chunjinchen/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/chunjinchen/Library/Android/sdk
    • Java binary at: /Users/chunjinchen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526
      /Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/chunjinchen/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code .app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • iPhone XR (mobile) • 00008020-001455C63CE9002E • ios            • iOS 13.6
      17G68
    • Chrome (web)       • chrome                    • web-javascript • Google
      Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by CJChen98** [comment]
Hello @danagbemava-nc,`flutter create` no such issue.
This problem occurs after I upgrade Flutter SDK from 3.0.5 to 3.3.0.

```yaml
name: smart_mi
description: Smartmi Link App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wis12h to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.8.3+36

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  # flutter_swiper: ^1.1.6
  card_swiper: ^2.0.4
  webview_flutter: ^3.0.4
  image_picker: ^0.8.3+2
  image_cropper: ^1.5.1
  flutter_image_compress: ^1.1.1
  path_provider: ^2.0.11
  flutter_cache_manager: ^3.1.2
  connectivity_plus: ^1.4.0
  archive: ^3.1.2
  wifi_info_flutter: ^2.0.2
  package_info: ^2.0.2
  flutter_staggered_animations: ^1.1.1
  app_settings: ^4.1.1
  cached_network_image: ^3.2.1
  flutter_easyrefresh: ^2.2.1
  url_launcher: ^6.0.9
  device_info: ^2.0.3
  permission_handler: ^10.0.0
  # firebase_core: ^1.7.0
  firebase_crashlytics: ^2.4.4
  firebase_core: ^1.10.6
  sign_in_with_apple: ^4.1.0
  the_google_sign_in:
    path: '../third_party_lib/the_google_sign_in'

  wifi:
    path: '../third_party_lib/wifi'
    # git:
    #   url: https://github.com/jya-software/wifi.git
    #   ref: v2.0.0

  flutter_cupertino_date_picker:
    path: '../third_party_lib/flutter-cupertino-date-picker'
    # git:
    #   url: https://github.com/jya-software/flutter-cupertino-date-picker.git
  intl: ^0.17.0

  base:
    path: '../base'
  common_ui:
    path: '../common_ui'
  iot_sdk:
    path: '../iot_sdk'
  config_service:
    path: '../config_service'
  device_service:
    path: '../device_service'
  account_service:
    path: '../account_service'
  ota_service:
    path: '../ota_service'
  scene_service:
    path: '../scene_service'
  # device project
  vacuum:
    path: '../projects/vacuum'
  airpurifier:
    path: '../projects/airpurifier'
  airp_zhimi_p2:
    path: '../projects/airp_zhimi_p2'
  airp_jya_e1:
    path: '../projects/airp_jya_e1'
  airheater:
    path: '../projects/airheater'
  circulator_fan:
    path: '../projects/circulator_fan'
  airp_jya_pro:
    path: '../projects/airp_jya_pro'
  rain_forest_humidifier:
    path: '../projects/rain_forest_humidifier'
  log_plugin:
    path: '../log_plugin'

  hetu_widget:
    path: ../hetu_widget
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    #    - family: DIN
    #      fonts:
    #        - asset: assets/fonts/DIN-Medium.otf
    #        - asset: assets/fonts/DIN-Regular.otf
    - family: HYQiHei50
      fonts:
        - asset: assets/fonts/HYQiHei-50J.ttf
    - family: HYQiHei55
      fonts:
        - asset: assets/fonts/HYQiHei-55S.ttf
    - family: HYQiHei-60S
      fonts:
        - asset: assets/fonts/HYQiHei-60J.ttf
    - family: HYQiHei70
      fonts:
        - asset: assets/fonts/HYQiHei-70J.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.otf
    - family: GilroyLight
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.otf
    - family: GilroySemBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.otf
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.otf
#    - family: JyaIcon
#      fonts:
#        - asset: assets/fonts/iconfont.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - scripts/flutter/
    - scripts/packages/
    - scripts/dart/
    - scripts/
    - scripts/user/
   
```

**Comment by danagbemava-nc** [comment]
Hi @CJChen98, are you perhaps using any icon codepoints directly somewhere in your code?

Also, can you provide the logs of the command completing successfully on stable 3.0.5?

**Comment by CJChen98** [comment]
@danagbemava-nc Yeah, i used icon codepoints like this :
```yaml
flutter:
  fonts:
    - family: JyaIcon
      fonts:
        - asset: assets/fonts/iconfont.ttf
```
```dart
class JyaIconData extends IconData {
  const JyaIconData(int codePoint) : super(codePoint, fontFamily: "JyaIcon",fontPackage: "common_ui");
}
```
```dart
class JyaIcons {
  static const IconData close = const JyaIconData(0xe60a);
  static const IconData play = const JyaIconData(0xe610);
  static const IconData pause = const JyaIconData(0xe60e);
  static const IconData save = const JyaIconData(0xe60b);
  static const IconData arrow_left = const JyaIconData(0xe60d);
  static const IconData arrow_right = const JyaIconData(0xe601);
  static const IconData lamp = const JyaIconData(0xe609);
  static const IconData music = const JyaIconData(0xe604);
  static const IconData power = const JyaIconData(0xe605);
  static const IconData arrow_up = const JyaIconData(0xe60f);
  static const IconData time = const JyaIconData(0xe606);
  static const IconData plus = const JyaIconData(0xe613);
  static const IconData battery = const JyaIconData(0xe608);
  static const IconData microphone = const JyaIconData(0xe60c);
  static const IconData batch_delete = const JyaIconData(0xe611);
  static const IconData arrow_right_list = const JyaIconData(0xe614);
  static const IconData loading = const JyaIconData(0xe612);
  static const IconData record_fill = const JyaIconData(0xe615);
  static const IconData complaints = const JyaIconData(0xe616);
  static const IconData experience = const JyaIconData(0xe617);
  static const IconData camera = const JyaIconData(0xe61b);
  static const IconData delete = const JyaIconData(0xe61c);
  static const IconData apple = const JyaIconData(0xe61d);
  static const IconData huawei = const JyaIconData(0xe619);
  static const IconData xiaomi = const JyaIconData(0xe618);
  static const IconData photo = const JyaIconData(0xe61b);
  static const IconData mi = const JyaIconData(0xe61e);
  static const IconData sin = const JyaIconData(0xe61f);
  static const IconData jya_fill = const JyaIconData(0xe620);
  static const IconData jya = const JyaIconData(0xe621);
  static const IconData record = const JyaIconData(0xe622);
  static const IconData music_pause = const JyaIconData(0xe602);
  static const IconData music_play = const JyaIconData(0xe603);
  static const IconData electric = const JyaIconData(0xe607);
}
```
This is build log on flutter 3.0.5 => [3.0.5_build.log](https://github.com/flutter/flutter/files/9555265/3.0.5_build.log)
