### ISSUE TITLE
chrome-infra-packages.appspot.com is not accessible (The semaphore timeout period has expired. , errno = 121)

### ISSUE THREAD

**Issue by alsaghir** [flutter/flutter#111387]
Anyway to use alternative to chrome-infra-packages.appspot.com ? If so, how and what ?

## Steps to Reproduce

1. Create new app using `flutter create my_app` then `cd my_app`
2. Execute `flutter run -d chrome`

**Expected results:** build to complete

**Actual results:**

```powershell
Failed to download
https://chrome-infra-packages.appspot.com/dl/flutter/web/canvaskit_bundle/+/yrsfF-vTvu4jzBBm1o6tDl70dky-l4G29Dnj75UvRDgC.
Ensure you have network connectivity and then try again.
SocketException: The semaphore timeout period has expired.
 (OS Error: The semaphore timeout period has expired.
, errno = 121), address = chrome-infra-packages.appspot.com, port = 62158
```

pubspec.yaml

```yaml
name: my_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

`flutter run -d chrome --verbose`  output

```powershell
[  +69 ms] executing: [D:\Apps\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +69 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4f9d92fbbdf072a70a70d2179a9f87392b94104c
[        ] executing: [D:\Apps\flutter/] git tag --points-at 4f9d92fbbdf072a70a70d2179a9f87392b94104c
[  +48 ms] Exit code 0 from: git tag --points-at 4f9d92fbbdf072a70a70d2179a9f87392b94104c
[        ] 3.3.1
[  +41 ms] executing: [D:\Apps\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [D:\Apps\flutter/] git ls-remote --get-url origin
[  +36 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [D:\Apps\flutter/] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +65 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +37 ms] executing: D:\Apps\AndroidSDK\platform-tools\adb.exe devices -l
[  +49 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +61 ms] Downloading Web SDK...
[ +443 ms] Content
https://storage.googleapis.com/flutter_infra_release/flutter/3efdf03e73dd352873fc5a7e1c0de04e52863b3a/flutter-web-sdk-windows-x64.zip md5 hash: 1lhIK2RgOqMoSeIo/Ino2w==
Terminate batch job (Y/N)? Y
D:\Code\my_app>
D:\Code\my_app>
D:\Code\my_app>
D:\Code\my_app>
D:\Code\my_app> flutter run -d chrome --verbose
[  +56 ms] executing: [D:\Apps\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4f9d92fbbdf072a70a70d2179a9f87392b94104c
[        ] executing: [D:\Apps\flutter/] git tag --points-at 4f9d92fbbdf072a70a70d2179a9f87392b94104c
[  +43 ms] Exit code 0 from: git tag --points-at 4f9d92fbbdf072a70a70d2179a9f87392b94104c
[        ] 3.3.1
[  +39 ms] executing: [D:\Apps\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [D:\Apps\flutter/] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +61 ms] executing: [D:\Apps\flutter/] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +55 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +70 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Downloading Web SDK...
[ +350 ms] Content
https://storage.googleapis.com/flutter_infra_release/flutter/3efdf03e73dd352873fc5a7e1c0de04e52863b3a/flutter-web-sdk-windows-x64.zip md5 hash: 1lhIK2RgOqMoSeIo/Ino2w==
[+8591 ms] Downloading Web SDK... (completed in 8.9s)
[+1415 ms] Downloading CanvasKit...
[+21122 ms] SocketException: The semaphore timeout period has expired.
                      (OS Error: The semaphore timeout period has expired.
                     , errno = 121), address = chrome-infra-packages.appspot.com, port = 62331
[        ] Downloading CanvasKit... (completed in 21.1s)
[        ] Downloading CanvasKit...
[+21038 ms] SocketException: The semaphore timeout period has expired.
                      (OS Error: The semaphore timeout period has expired.
                     , errno = 121), address = chrome-infra-packages.appspot.com, port = 62345
[        ] Downloading CanvasKit... (completed in 21.0s)
[        ] "flutter run" took 52,612ms.
[  +11 ms] Failed to download https://chrome-infra-packages.appspot.com/dl/flutter/web/canvaskit_bundle/+/yrsfF-vTvu4jzBBm1o6tDl70dky-l4G29Dnj75UvRDgC. Ensure you have network
connectivity
           and then try again.
           SocketException: The semaphore timeout period has expired.
            (OS Error: The semaphore timeout period has expired.
           , errno = 121), address = chrome-infra-packages.appspot.com, port = 62345
[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1062:11)
           <asynchronous suspension>
           #2      CachedArtifact.update (package:flutter_tools/src/cache.dart:810:5)
           <asynchronous suspension>
           #3      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
           <asynchronous suspension>
           #4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1326:7)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +174 ms] ensureAnalyticsSent: 173ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

`flutter analyze` output

```powershell
Analyzing my_app...
No issues found! (ran in 11.6s)
```

`flutter doctor -v` output

```powershell
[✓] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
    • Flutter version 3.3.1 on channel stable at D:\Apps\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (5 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\Apps\AndroidSDK
    • Platform android-31, build-tools 33.0.0
    • ANDROID_HOME = D:\Apps\AndroidSDK
    • Java binary at: D:\Apps\jdk17.0.3_6\bin\java
    • Java version OpenJDK Runtime Environment Corretto-17.0.3.6.1 (build 17.0.3+6-LTS)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio
    • Android Studio at D:\Apps\idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ android-studio-dir = D:\Apps\idea
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at D:\Apps\idea
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3739.24

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\omega\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.33

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
