### ISSUE TITLE
Error when running snapcraft command to create a snap

### ISSUE THREAD

**Issue by Haidar0096** [flutter/flutter#111606]
## Steps to Reproduce

Execute the steps mentioned in the [official docs](https://docs.flutter.dev/deployment/linux) to create a snap to upload to the snap store:

`snapcraft.yaml`:

```
name: batch-image-editor
version: 0.1.0
summary: Batch Image Editor
description: Basic image editor that can generate images using text from text files in batches.

confinement: strict
base: core18
grade: stable

slots:
  dbus-batch-image-editor:
    interface: dbus
    bus: session
    name: org.zlimits.batch_image_editor

apps:
  batch-image-editor:
    command: batch-image-editor
    extensions: [flutter-stable]
    plugs:
      - network
    slots:
      - dbus-batch-image-editor
parts:
  batch-image-editor:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

```

**Expected results:** 

The snap should be built normally when I run `snapcraft` at the root of my project

**Actual results:** 

Build fails with error

<details>
  <summary>Logs</summary>

This error happens when the build fails
```
Failed to run 'flutter build linux --release -v -t lib/main.dart' for 'batch-image-editor': Exited with code 1.
Verify that the part is using the correct parameters and try again.

```

Going up a little bit in the logs I can see the original error:

```
[  +60 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64
/root/parts/batch-image-editor/build/linux
[ +119 ms] CMake Error at flutter/generated_plugins.cmake:16 (add_subdirectory):
[   +3 ms]   add_subdirectory given source
[        ]   "flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux" which is not
[        ]   an existing directory.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:69 (include)
[        ] CMake Error at flutter/generated_plugins.cmake:16 (add_subdirectory):
[        ]   add_subdirectory given source
[        ]   "flutter/ephemeral/.plugin_symlinks/window_size/linux" which is not an
[        ]   existing directory.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:69 (include)
[   +1 ms] -- Configuring incomplete, errors occurred!
[        ] See also "/root/parts/batch-image-editor/build/build/linux/x64/release/CMakeFiles/CMakeOutput.log".
[  +32 ms] Building Linux application... (completed in 202ms)
[        ] "flutter linux" took 1,827ms.
[   +8 ms] Unable to generate build files
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmake (package:flutter_tools/src/linux/build_linux.dart:155:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:76:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:85:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

```

```
```

Results of flutter doctor on my device:
```
[✓] Flutter (Channel stable, 3.3.1, on Ubuntu 22.04.1 LTS 5.15.0-47-generic, locale en_US.UTF-8)
    • Flutter version 3.3.1 on channel stable at /home/haidar/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (8 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/haidar/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /snap/android-studio/123/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin version 70.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /snap/intellij-idea-ultimate/383
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-47-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

Flutter doctor inside the snap image gives:

```
[✓] Flutter (Channel stable, 3.3.2, on Ubuntu 18.04.6 LTS 5.15.0-47-generic, locale C.UTF-8)
    • Flutter version 3.3.2 on channel stable at /root/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (8 hours ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 18.04.6 LTS 5.15.0-47-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

</details>

**Comment by Haidar0096** [comment]
Hello @huycozy 
I solved the issue by an endless loop of cleaning the original project and the generated project inside the snap image.

finally the `snapcraft.yaml` now looks like this:

```
name: batch-image-editor
version: 0.1.0
summary: Batch Image Editor
description: Basic image editor that can generate images using text from text files in batches.

confinement: strict
base: core18
grade: stable

slots:
  dbus-batch-image-editor:
    interface: dbus
    bus: session
    name: org.zlimits.batch_image_editor

apps:
  batch-image-editor:
    command: photo_editor
    extensions: [flutter-stable]
    plugs:
      - network
    slots:
      - dbus-batch-image-editor
parts:
  batch-image-editor:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

```
 

I don't know what the actual solution was tbh, but I ran these commands inside the snap image:
`snapcraft clean`
`cd project`
`flutter clean`

and I also ran `flutter clean` in the original project.
