### ISSUE TITLE
The screen blinks every two to three minutes after upgrading to 3.3.x.

### ISSUE THREAD

**Issue by HuveD** [flutter/flutter#111881]
The screen blinks every two to three minutes after upgrading to 3.3.x (including 3.3.2 the latest version).

I was using the 3.0.4 version before upgrading.

Because of blinking, I had downgraded to 3.0.4. So the above problem was solved.

I think the previous screen is shown temporarily. I never saw the error message, but I recorded my screen.

I hope this problem will be solved in the latest version.

https://user-images.githubusercontent.com/48434145/191018045-5669ad07-75f1-4845-b14a-cb53652b6647.mp4

**Comment by teewhydope** [comment]
Also having the same issue

**Comment by JankoLancer** [comment]
Having the same issue

**Comment by exaby73** [comment]
@teewhydope @JankoLancer Please feel free to provide a code sample with reproducible steps so that I may verify this issue.

**Comment by HuveD** [comment]
@exaby73 
I really wanted to reproduce it, so I tried various things, but I can't reproduce it in the newly created sample project.
It is difficult to provide the sample code because it is occurring only in the existing project.

There is still a problem with version 3.3.3.

My app has an animation character, so the frame is always updated.
It is speculated that there may be a problem with the screen update, but it is difficult to provide information because it has not been reproduced in the sample project.

### **Flutter doctor**
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-x64, locale ko-KR)
    • Flutter version 3.3.3 on channel stable at /Users/jeonghyeon/Develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (2 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jeonghyeon/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/jeonghyeon/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • 유정현의 iPad (mobile) • 00008103-001570110EA3001E • ios            • iOS 15.7 19H12
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 105.0.5195.125
    ! Error: 유정현의 iPad is busy: Fetching debug symbols for 유정현의 iPad. Xcode will continue when 유정현의 iPad is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

Library in use
```
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # For Firebase
  firebase_in_app_messaging: ^0.6.0+24
  firebase_messaging: ^13.0.2
  firebase_dynamic_links: ^4.3.7
  firebase_crashlytics: ^2.8.10
  firebase_performance: ^0.8.3
  firebase_analytics: ^9.3.5
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1+1
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2

  # For Networking
  retrofit: '>=3.0.0 <4.0.0'
  dio: ^4.0.6

  # For Architecture
  flutter_riverpod: ^1.0.4

  # For User-Agent Client Hints
  #  ua_client_hints: ^1.1.0

  # For Model
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

  # For Multi-Platform
  universal_io: ^2.0.4

  # For Localization
  intl: ^0.17.0

  # For Utility
  shared_preferences: ^2.0.15
  screenshot: ^1.2.3
  path_provider: ^2.0.11
  wakelock: ^0.6.2
  logger: ^1.1.0
  url_launcher: ^6.1.5
  package_info_plus: ^1.4.3+1
  screen_brightness: ^0.2.1

  # For UI
  flutter_staggered_grid_view: ^0.6.2
  modal_bottom_sheet: ^2.1.2
  share_plus: ^4.1.0
  page_transition: ^2.0.9
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.5
  in_app_review: ^2.0.4
  rive: ^0.9.1
  in_app_purchase: ^3.0.7

  # For Ads
  google_mobile_ads: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.1

  # For Models
  json_serializable: ^6.3.2
  freezed: ^2.1.0+1

  # For Assets
  flutter_gen_runner: ^4.3.0

  # For Networking
  retrofit_generator: '>=4.0.0 <5.0.0'
```
