### ISSUE TITLE
Build errors shared_preferences

### ISSUE THREAD

**Issue by blue492** [flutter/flutter#111886]
After upgrading to Xcode 14, I got these errors messages when I try build/run my project on Mac: 
Android studio -> Build -> Flutter -> Build iOS

shared_preferences: ^2.0.15
Flutter version: 3.3.2

Note that everything were working without any problem before the upgrading

```
Automatically signing iOS for device deployment using specified development team in Xcode project: 65456KJ35R
Running Xcode build...                                          
Xcode build done.                                           18.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/cc/3b8b8j7s3nd92qwt4_6zgzhh0000gn/T/flutter_tools.DBua0Q/flutter_ios_build_temp_dirdSTTIY/temporary_xcresult_bundle

    /Users/test/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/ios/Classes/FLTSharedPreferencesPlugin.m:27:41: error: no type or protocol named 'FlutterPluginRegistrar'
    + (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
                                            ^
    /Users/test/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/ios/Classes/FLTSharedPreferencesPlugin.m:29:34: error: property 'messenger' not found on object of type 'NSObject *'
      UserDefaultsApiSetup(registrar.messenger, plugin);
                                     ^
    3 errors generated.
    Command SwiftCompile failed with a nonzero exit code
    note: Building targets in dependency order
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
    	/var/folders/cc/3b8b8j7s3nd92qwt4_6zgzhh0000gn/T/flutter_tools.DBua0Q/flutter_ios_build_temp_dirdSTTIY/temporary_xcresult_bundle


Generics Issue (Xcode): No type or protocol named 'FlutterPlugin'
/Users/test/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/ios/Classes/FLTSharedPreferencesPlugin.h:5:50

Generics Issue (Xcode): No type or protocol named 'FlutterPluginRegistrar'
/Users/test/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/ios/Classes/FLTSharedPreferencesPlugin.m:26:40

Semantic Issue (Xcode): Property 'messenger' not found on object of type 'NSObject *'
/Users/test/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/ios/Classes/FLTSharedPreferencesPlugin.m:28:33

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

Encountered error while building for device.
Process finished with exit code 1
```

**Comment by danagbemava-nc** [comment]
Hi @blue492, do you experience this issue when you add `shared_preferences` to a new `flutter create` project and try to build the app? Or is it only with your current project?

**Comment by blue492** [comment]
> Hi @blue492, do you experience this issue when you add `shared_preferences` to a new `flutter create` project and try to build the app? Or is it only with your current project?

In both, I tested now `shared_preferences` in a new project, it same issue in a new and my current project.
The new project worked fine without any plugins, but when I added `shared_preferences: ^2.0.15` the new project I got same errors

**Comment by blue492** [comment]
@danagbemava-nc I added my plugins which I use in my current project one after one to the new project, and its seems that there are many plugins have similar issues with the new iOS and Xcode, here is some of them:
```
searchable_dropdown: ^1.1.3
file_picker: ^4.6.1 
html_editor_enhanced: ^2.5.0
image_cropper: ^3.0.0
```

I have these plugins in my current project, and everything worked well before the upgrading of my Mac and Xcode
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:  
    sdk: flutter
  shared_preferences: ^2.0.15  
  http: ^0.13.5  
  intl: ^0.17.0 
  encrypt: ^5.0.1 
  json_annotation: ^4.6.0 
  searchable_dropdown: ^1.1.3  
  flutter_typeahead: ^4.1.1  
  flutter_datetime_picker: ^1.5.1 
  image_picker: ^0.8.5+3 
  connectivity_plus: ^2.3.7  
  flutter_svg: ^1.1.5  
  file_picker: ^4.6.1 
  open_file: ^3.2.1  
  permission_handler: ^10.0.0  
  path_provider: ^2.0.11 
  sqflite: ^2.0.3+1 
  device_info_plus: ^3.2.4 
  url_launcher: ^6.1.5 
  maps_launcher: ^2.0.1 
  package_info_plus: ^1.4.2 
  flutter_html: ^3.0.0-alpha.5  
  html_editor_enhanced: ^2.5.0 
  cupertino_icons: ^1.0.5 
  flutter_colorpicker: ^1.0.3
  syncfusion_flutter_calendar: ^20.2.49 
  syncfusion_localizations: ^20.2.49 
  syncfusion_flutter_charts: ^20.2.49 
  geolocator: ^9.0.1 
  mobile_scanner: ^2.0.0 
  image_cropper: ^3.0.0 
```
