### ISSUE TITLE
[flutter_markdown] Markdown is not defined

### ISSUE THREAD

**Issue by NicTanghe** [flutter/flutter#112539]
I put the thing below in my main dart

```dart
import 'package:markdown/markdown.dart' as md;

```
my dependencies look like this
```yaml
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  model_viewer_plus: ^1.3.3

  flutter_markdown: ^0.6.12
```

I ran flutter pub get.

Yet i still get the error markdown is not defined. 

It seems that the import sentence given in the readme is incorrect, and now 
```dart
import 'package:flutter_markdown/flutter_markdown.dart';
```
should be used.
Please update readme
