### ISSUE TITLE
Could not build the precompiled application for the device.  Error launching application on iPhone (8).

### ISSUE THREAD

**Issue by johnberang12** [flutter/flutter#112690]
## Steps to Reproduce

1. create a new flutter project
2. install these dependencies in pubspec.yaml:

<details>
<summary> pubspec content</summary>

```yaml
dependencies:
  algolia: ^1.1.1
  any_link_preview: ^2.0.9
  app_settings: ^4.1.8
  badges: ^2.0.3
  build_runner: ^2.2.0
  cached_network_image: ^3.2.1
  camera: ^0.10.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.5.0
  cloud_functions: ^3.3.5
  connectivity_plus: ^2.3.6
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.1.2
  emoji_picker_flutter: ^1.3.0
  firebase_auth: ^3.11.0
  firebase_core: ^1.24.0
  firebase_core_platform_interface: ^4.5.0
  firebase_messaging: ^13.0.2
  firebase_storage: ^10.3.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_keyboard_visibility: ^5.3.0
  flutter_layout_grid: ^2.0.1
  flutter_markdown: ^0.6.12
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: 2.0.0-dev.9
  flutter_screenutil: ^5.5.4
  flutter_spinkit: ^5.1.0
  flutterfire_ui: ^0.4.3+7
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  gallery_saver: ^2.3.2
  galleryimage: ^1.2.0
  geocoding: ^2.0.5
  georange: ^1.0.0
  go_router: ^4.5.1
  google_maps_flutter: ^2.2.0
  grouped_list: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  linkify: ^4.1.0
  location: ^5.0.0-dev.8
  mocktail: ^0.3.0
  overlay_support: ^2.0.1
  palette_generator: ^0.3.3+1
  path: ^1.8.1
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  pinput: ^2.2.11
  rxdart: ^0.27.4
  settings_ui: ^2.0.2
  share_plus: ^4.1.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sqflite: ^2.0.2+1
  timeago: ^3.2.2
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  video_player: ^2.4.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
```
</details>
  
4. hit flutter pub get then flutter run

<details>
<summary>logs</summary>

```
Launching lib/main.dart on iPhone (8) in debug mode...
lib/main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: MF77954W3J
Xcode build done.                                           133.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/r9/mj6my7012nnf89q6z3ytxsqr0000gn/T/flutter_tools.Fk5UuG/flutter_ios_build_temp_dirBAUZXC/temporary_xcresult_bundle
/Users/jober/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-4.2.3/ios/Classes/SwiftTwitterLoginPlugin.swift:52:19: warning: unnecessary check for 'iOS'; enclosing scope ensures guard will always be true
            } else if #available(iOS 11.0, *) {
                      ^
/Users/jober/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-4.2.3/ios/Classes/SwiftTwitterLoginPlugin.swift:34:9: note: enclosing scope here
            if #available(iOS 12.0, *) {
            ^
/Users/jober/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-4.1.0/ios/Classes/FLTSharePlusPlugin.m:12:44: warning: 'keyWindow' is deprecated: first deprecated in iOS 13.0 - Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes [-Wdeprecated-declarations]
      return [UIApplication sharedApplication].keyWindow.rootViewController;
                                               ^
    In module 'UIKit' imported from /Users/jober/AndroidStudioProjects/mainProject/muraita_main/ios/Pods/Target Support Files/share_plus/share_plus-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:135:51: note: 'keyWindow' has been explicitly marked deprecated here
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-arm, locale en-PH)
    • Flutter version 3.3.3 on channel stable at /Users/jober/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (2 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/jober/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • iPhone (8) (mobile)        • 00008030-001D49141484802E            • ios            • iOS 15.6.1 19G82
    • iPhone 14 Pro Max (mobile) • 7E66540A-D3EB-467D-B8B6-D7DAFA9869E2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
