### ISSUE TITLE
Image.opacity ignored on Mobile Agent [CanvasKit]

### ISSUE THREAD

**Issue by BrianCraig** [flutter/flutter#113089]
## Steps to Reproduce

1. go to https://dartpad.dev/?id=81f9a45be321e427a8f5da18d744b71c&channel=master on desktop chrome
2. Click `run`
3. Flutter image should be seen **Transparent**
4. Open browser developer tools
5. Change User Agent to Android (Network Conditions -> Uncheck `Use browser default`, select `chrome - Android browser`)
6. Reload page
7. Click `run`

**Expected results:**
8. Flutter image is **Transparent**

**Actual results:**
8. Flutter image is completely **Opaque**

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/widgets.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Image.network(
      'https://storage.googleapis.com/cms-storage-bucket/c823e53b3a1a7b0d36a9.png',
      opacity: const AlwaysStoppedAnimation(0.1),
    );
  }
}
```

</details>

<details>
`flutter doctor -v` 

```
[✓] Flutter (Channel master, 3.5.0-3.0.pre.1, on Ubuntu 22.04.1 LTS 5.15.0-48-generic, locale en_US.UTF-8)
    • Flutter version 3.5.0-3.0.pre.1 on channel master at /home/bri/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 900f540a5e (7 hours ago), 2022-10-06 19:58:08 -0400
    • Engine revision 7059da35c5
    • Dart version 2.19.0 (build 2.19.0-285.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/bri/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/bri/app/android-studio/jre/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/bri/app/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)

[✓] VS Code (version 1.71.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-48-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

## Video

[Screencast from 07-10-22 04:08:02.webm](https://user-images.githubusercontent.com/4956754/194490046-02d879b3-6b4a-41e8-a391-5d4d823d8640.webm)

## Affected

Master, Stable, and v3.0.0 has been tested, all with the same results:
|               | CanvasKit | HTMLRenderer |
|---------------|-----------|--------------|
| Desktop Agent | 👌Ok       | ❌Bug         |
| Mobile Agent  | ❌Bug      | ❌Bug         |

HTMLRenderer may not implement this functionality, but CanvasKit transparency should work on `Mobile`.

This bug is present on Android/IOS Browsers.

**Comment by danagbemava-nc** [comment]
Hi @BrianCraig, does this reproduce if you deploy the app and test on physical devices? I deployed your code sample and below is what I see when I opened the site on android and iOS. An interesting thing, however, is that I could not reproduce this with the user agent change on my mac, but my colleague could reproduce it on ubuntu. 

<details>
<summary>screenshots</summary>

| android | iOS | 
| -- | -- |
| <img src="https://user-images.githubusercontent.com/88313112/194549491-01a03db6-99fc-41b8-825d-dab0f3dd1a08.png" /> | <img src="https://user-images.githubusercontent.com/88313112/194549484-3d032360-ecb2-4f61-b7bc-54f2e31e98ee.jpg" /> |

</details>

**Comment by BrianCraig** [comment]
@danagbemava-nc Hi!

Yes, i found it because i was testing a release of a product, which contains a `DecorationImage` with opacity.
This release uses subosito Github Actions, on an Ubuntu Machine, with master channel, on release mode to deploy. 

| Desktop Browser, native, and expected | Xiaomi Redmi 9 | Moto E20 |
|---|---|---|
| ![](https://user-images.githubusercontent.com/4956754/194636279-8079e9f8-8f74-4f60-8f6c-cc06ca075b10.png) | ![](https://user-images.githubusercontent.com/4956754/194636217-52a1336e-dff8-4e41-979a-136367ea1608.jpeg) | ![](https://user-images.githubusercontent.com/4956754/194636205-43445b9d-ed85-4256-b857-bb924708dc83.jpeg) |
<details>
<summary>Github Action deploy code</summary>

```yaml
name: Release

on:
  push:
    tags:
      - release.*

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: Build
        working-directory: ./app
        run: flutter build web --release
      - run: cd ./app/build/web && zip -r ../../../web-release.zip .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            ./web-release.zip
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_SECRET }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: ./app/build/web
```

</details>

You can check it on https://segui.com.ar, pressing on the blue rounded button with the legend `toca aqui para agregar multiples envios de ejemplo`.

-----

Your example (https://ocr-test-4f3df.web.app/) surprises me because it works fine on my android, meanwhile the dartpad i submitted (https://dartpad.dev/?id=81f9a45be321e427a8f5da18d744b71c&channel=master) and an upload (https://flutter-opacity-master.surge.sh) doesn't.

| https://ocr-test-4f3df.web.app/ | https://flutter-opacity-master.surge.sh |
|---|---|
| ![](https://user-images.githubusercontent.com/4956754/194641246-57520ec0-fe8e-447d-ab5a-346eb27b63ed.jpeg) | ![](https://user-images.githubusercontent.com/4956754/194641249-e2e56d31-fe1d-4274-bba1-e82d50a6ff87.jpeg) |

https://flutter-opacity-master.surge.sh is a release `Flutter 3.5.0-3.0.pre.1 • channel master` that i built on my Ubuntu, the bug also happened on debug mode.  
How did you built `https://ocr-test-4f3df.web.app/` ?  
Later I'll upload and check a web build on my windows machine, it's strange that your build doesn't have the same problem.

Brian
