### ISSUE TITLE
Setting exact Flutter version in `pubspec.yaml` does not work

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#113169]
## Description

My goal is to set an exact (not `^`) Flutter in the `pubspec.yaml`. Using the following code does not work.

```yaml
environment:
  sdk: ">=2.17.0 <3.0.0"
  # We enforce a specific Flutter version to make sure that we all are use the
  # same Flutter version for this project.
  flutter: "3.3.0"
```

The problem is that it's still possible to run the project with a different Flutter version (like `3.3.3`).

| Version | Result |
|-|-|
| `>=3.3.0` | ✅ |
| `^3.3.0` | ✅ |
| `3.3.0` | ❌ |

## Steps to reproduce

1. Run `flutter create fix_version`
2. Run `cd fix_version`
3. Change
```yaml
environment:
  sdk: '>=2.18.2 <3.0.0'
```

to

```yaml
environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '2.10.5'
```
4. Run `flutter pub get` (use *not* Flutter v2.10.5)

However, it's possible to run `flutter pub get`:

```
$ flutter pub get
Running "flutter pub get" in fix_version...             229ms
```

Expected output is:
```
The current Flutter SDK version is 3.3.4.

Because fix_version requires Flutter SDK version 2.10.5, version solving failed.
pub get failed (1; Because fix_version requires Flutter SDK version 2.10.5, version solving failed.)
exit code 1
```

### Flutter Version
```
Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision eb6d86ee27 (4 days ago) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0
```
