### ISSUE TITLE
[Request] Compact pubspec.yaml to facilitate packages ordering

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#113787]
## Use case

There is an analysis option that asks for sort pub dependencies (which I like) and, at least in VSCode, a plugin that orders the selected lines using [F9].

The problem is: flutter dependencies are two liners, making impossible to easily sort dependencies.

```yaml
flutter:
  sdk: flutter
```

## Proposal

Just changing the template when creating a new flutter project to a one line flutter dependencies:

```yaml
dependencies:
  cupertino_icons: ^1.0.2
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: { sdk: flutter }
```
