### ISSUE TITLE
`flutter create --empty`

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#113853]
Creating a new empty Flutter project is a common use case for developers. It'd be nice to be able to do run `flutter create` and get an app that doesn't need lots of comments stripped from `lib/main.dart`

**Comment by gspencergoog** [comment]
So, when you say "empty", do you literally mean an empty file, or something like this:

```dart
void main() => runApp(const Placeholder());
```

Or something slightly larger, but without comments, like this?:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Placeholder(),
      ),
    );
  }
}
```

**Comment by domesticmouse** [comment]
More the latter than the former. I'd even go so far as to centre a 'Hello, world!' label as opposed to a placeholder. 

Thoughts @craiglabenz and @johnpryan

**Comment by craiglabenz** [comment]
I think either is fine, honestly. The value in this option is that developers aren't going to use _anything we put in here._

**Comment by gspencergoog** [comment]
Okay, I'm going to go with the second option for now.

**Comment by timsneath** [comment]
(Please don't turn off the debug banner in any boilerplate code! The point of that is to remind folk that they're running debug builds that may offer suboptimal runtime performance in return for a fantastic development experience. I rather wish that it wasn't possible to turn it off...)

**Comment by gspencergoog** [comment]
Okay, I'll make sure it's on.

**Comment by johnpryan** [comment]
It would be great if the `pubspec.yaml` could be empty too:

```yaml
name: new_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
```
