### ISSUE TITLE
Automatically call `build_runner` when compiling

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#113996]
## Use case

My app is using Protobuf, which needs us to generate the corresponding Dart files before building or analyzing. I spent some time configuring `build_runner` to handle this process for us because `build_runner` is considered the idiomatic way to do code gen in Dart. To that end, it would probably be useful if Flutter came with an option to run `flutter pub run build_runner build` when running flutter `build`, `run`, or `analyze`. I found `generate: true` in the pubspec file, but this doesn't accomplish what I want (it seems to be more related to [internationalization](https://docs.flutter.dev/development/accessibility-and-localization/internationalization) than generic code gen). I think this is pretty straightforward since a project usually, if not always, needs to generate everything before it can be compiled. 

My main motivation is that when adding some code gen, some parts of my team may not be familiar with it (like the frontend people), so having them dig into code gen themselves is counterintuitive when they could just keep running `flutter run` instead. 

## Proposal

`flutter run`, `flutter build`, and `flutter analyze` should all first run 
```
flutter run build_runner build
```
if Flutter detects a `build.yaml` file in the project directory. If having this on by default is too much, then there can be a setting for it, either a cli flag or an option in the pubspec. Currently, there is a `generate` option in the Flutter section: 
```yaml
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true  # includes the Material Design icons font 
  generate: true  # used for generating translations 
```
Perhaps `generate` here can be made broader and generate all needed code by calling `build_runner`.
