### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by definitelyme** [flutter/flutter#114128]
## Command
```
flutter pub upgrade --major-versions --dry-run
```

## Steps to Reproduce
1. Run `flutter pub upgrade --major-versions --dry-run` from  project root

## Expected Output
Print --dry-run results

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:271:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:270:5)
#8      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:431:21)
<asynchronous suspension>
#9      PackagesInteractiveGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:347:5)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
```
```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-NG)
    • Flutter version 3.3.4 on channel stable at /Users/brendan/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (3 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/brendan/Library/android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • ANDROID_HOME = /Users/brendan/Library/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • j@mon (mobile)  • 00008020-001240413C31002E • ios            • iOS 16.0.3 20A392
    • macOS (desktop) • macos                     • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 85684f9300908116a78138ea4c6036c35c9a1236

### Pubspec.yaml
```yaml
name: myapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  another_flushbar: ^1.12.29

  auto_route: ^5.0.2

  auto_size_text: ^3.0.0

  awesome_notifications: ^0.7.3

  # awesome_select: ^5.2.0

  badges: ^2.0.2

  bloc_concurrency: ^0.2.0

  cached_network_image: ^3.2.2

  chips_choice_null_safety: ^2.0.6

  connectivity_plus: ^2.3.6+1

  cupertino_icons: ^1.0.4

  cupertino_list_tile: ^0.2.1

  dartz: ^0.10.1

  date_format: ^2.0.5

  device_info_plus: ^4.1.2

  dio: ^4.0.4

  dio_cache_interceptor: ^3.3.1

  dismissible_page: ^0.7.3

  dotted_border: ^2.0.0+2

  emoji_picker_flutter: ^1.3.1

  enough_platform_widgets: ^0.5.0

  expandable: ^5.0.1

  extended_nested_scroll_view: ^5.0.0

  firebase_analytics: ^9.3.4

  firebase_core: ^1.22.0

  firebase_crashlytics: ^2.8.10

  firebase_dynamic_links: ^4.3.7

  firebase_messaging: ^13.0.1

  firebase_storage: ^10.3.8

  flutter_bloc: ^8.1.1

  flutter_keyboard_visibility: ^5.3.0

  flutter_masked_text2:
    git:
      url: https://github.com/Flutter-Fox/flutter_masked_text.git
      ref: hotfix-0.9.1

  flutter_multi_formatter: ^2.7.4

  flutter_native_splash: ^2.2.9

  # flutter_screenutil: ^5.5.4

  flutter_svg: ^1.1.3

  fluttertoast: ^8.0.8

  freezed_annotation: ^2.0.3

  get_it: ^7.2.0

  google_fonts: ^3.0.0

  google_sign_in: ^5.4.1

  hive_flutter:
    git:
      url: https://github.com/Flutter-Fox/hive.git
      ref: master
      path: hive_flutter/

  iconify_flutter: ^0.0.4

  image_picker: ^0.8.4+10

  in_app_update: ^3.0.0

  inflection3: ^0.5.3+2

  injectable: ^1.5.3

  internet_connection_checker: ^0.0.1+3

  intl: ^0.17.0

  intl_phone_number_input:
    git:
      url: https://github.com/Flutter-Fox/intl_phone_number_input.git
      ref: "0.7.0+2-patch"

  json_annotation: ^4.5.0

  kt_dart: ^0.10.0

  # like_button: ^2.0.4
  # like_button:
  #   path: ./like_button

  lottie: ^1.4.2

  modal_bottom_sheet: ^2.1.2

  new_version: ^0.3.1

  path_provider: ^2.0.8

  permission_handler: ^10.0.0

  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view.git
      ref: 8156907eecfa812b181a5a729d790f6d399f311b

  pinput: ^2.2.12

  pretty_dio_logger: ^1.1.1

  pull_to_refresh:
    git:
      url: https://github.com/miquelbeltran/flutter_pulltorefresh.git
      ref: 6d7fbdd5b3cde242a474d66da312aac4aa892b9b

  retrofit: ^3.0.1+1

  retry: ^3.1.0

  rxdart: ^0.27.3

  shimmer: ^2.0.0

  sign_in_with_apple: ^4.0.0

  timeago: ^3.3.0

  url_launcher: ^6.0.18

  uuid: ^3.0.6

dependency_overrides:
  analyzer: ^4.7.0
  flutter_screenutil: "5.5.3+2"

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.2

  build_runner: ^2.1.11

  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0

  freezed: ^2.0.3+1

  hive_generator:
    git:
      url: https://github.com/Flutter-Fox/hive.git
      ref: master
      path: hive_generator/

  injectable_generator: ^1.5.3

  json_serializable: ^6.2.0

  logger: ^1.0.0

  retrofit_generator:
    git:
      url: https://github.com/Flutter-Fox/retrofit.dart.git
      ref: ft/app_http_client
      path: generator/
```
