### ISSUE TITLE
[webview_flutter_android] crash with type 'RenderPointerListener' is not a subtype of type 'Copyable' in type cast

### ISSUE THREAD

**Issue by nvx** [flutter/flutter#115325]
## Steps to Reproduce
Relatively rare crash that came in through Crashlytics, so no direct steps to reproduce. Crash is as follows:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type 'RenderPointerListener' is not a subtype of type 'Copyable' in type cast. Error thrown Instance of 'ErrorDescription'.
0  ???                            0x0 (null).#0      InstanceManager.getInstanceWithWeakReference (package:webview_flutter_android/src/instance_manager.dart:153:25)
1  ???                            0x0 (null).#1      WebChromeClientFlutterApiImpl.onProgressChanged (package:webview_flutter_android/src/android_webview_api_impls.dart:814:10)
2  ???                            0x0 (null).#2      WebChromeClientFlutterApi.setup.<anonymous closure> (package:webview_flutter_android/src/android_webview.pigeon.dart:1932:15)
3  ???                            0x0 (null).#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
4  ???                            0x0 (null).#4      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
5  ???                            0x0 (null).#5      _invoke2 (dart:ui/hooks.dart:186:13)
6  ???                            0x0 (null).#6      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
7  ???                            0x0 (null).#7      _Channel.push (dart:ui/channel_buffers.dart:132:31)
8  ???                            0x0 (null).#8      ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
9  ???                            0x0 (null).#9      PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
10 ???                            0x0 (null).#10     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
11 ???                            0x0 (null).#11     _dispatchPlatformMessage (dart:ui/hooks.dart:87:1)
```

Device details: Android 12 Galaxy S21 5G

Versions as of time of crash:
```
  webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.4"
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.10.0"
  webview_flutter_platform_interface:
    dependency: transitive
    description:
      name: webview_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.3"
```

We've since updated to the latest version, but I don't see anything in the changelog between now and then that indicates this has been fixed already (it wasn't too far behind). Hopefully the stack trace is enough to figure out what went wrong.
