### ISSUE TITLE
[localizations] Bug Placeholder type int need format if other placeholder type is double or num

### ISSUE THREAD

**Issue by lsaudon** [flutter/flutter#115989]
## Description

Why the placeholder with an int type does not need a format when it is alone, but needs a format when there are other placeholders.

## Steps to Reproduce

1. Execute `flutter create my_app` on the code sample 
2. Add `flutter_localizations` and `intl` and `generate: true`:
  ```yml
name: my_app
description: My App
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: 3.3.6

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

flutter:
  uses-material-design: true
  generate: true

  ```

3. Add l10n.yaml file:
  ```yml
arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
  ```

4. Add `lib\l10n\arb\app_en.arb`
```json
{
  "@@locale": "en",
  "text": "a {number} {otherNumber}",
  "@text": {
    "placeholders": {
      "number": {
        "type": "int"
      },
      "otherNumber": {
        "type": "num",
        "format": "compact"
      }
    }
  }
}
```

**Expected results:** 

No error

**Actual results:** 
```sh
Generating synthetic localizations package failed with 1 error:

Exception: Number format null for the number placeholder does not have a corresponding NumberFormat constructor.
Check the intl library's NumberFormat class constructors for allowed number formats.
```
