### ISSUE TITLE
Package not available (the pubspec for image_picker 0.8.6 from git has version 0.8.5+3).

### ISSUE THREAD

**Issue by v-pavlovskyi** [flutter/flutter#116012]
I try to download package, but have an error "Package not available (the pubspec for image_picker 0.8.6 from git has version 0.8.5+3).".
In pubspec I added next lines:
```
image_picker:
    git:
      url: https://github.com/cpboyd/plugins.git
      ref: ios-no-permissions
      path: packages/image_picker/image_picker
```
