### ISSUE TITLE
Device: Redmi note 11 pro 5G (MIUI 13, android version 11)

### ISSUE THREAD

**Issue by MohamedSafvanKP-MSIL** [flutter/flutter#116253]
Device: Redmi note 11 pro 5G (MIUI 13, android version 11)
**The camera comes with one black screen.** 
Plugin Used up to camera 0.10.0+4

**logs getting on camera plugin 0.10.0+4**
```
Syncing files to device 2201116SI...
I/CameraManagerGlobal(22595): Connecting to camera service
W/CameraManagerGlobal(22595): [soar.cts] ignore the status update of camera: 2
W/CameraManagerGlobal(22595): [soar.cts] ignore the status update of camera: 3
W/CameraManagerGlobal(22595): [soar.cts] ignore the status update of camera: 4
W/CameraManagerGlobal(22595): [soar.cts] ignore the status update of camera: 5
W/CameraManagerGlobal(22595): [soar.cts] ignore the status update of camera: 6
I/CameraMetadataJV(22595): setAppNameAndSensorId all [com.antutu:0,ssize,12032x9024,0,false]
I/CameraMetadataJV(22595): setAppNameAndSensorId all [com.antutu:1,ssize,4608x3456,0,false]
W/CameraManagerGlobal(22595): ignore the torch status update of camera: 2
W/CameraManagerGlobal(22595): ignore the torch status update of camera: 3
W/CameraManagerGlobal(22595): ignore the torch status update of camera: 4
W/CameraManagerGlobal(22595): ignore the torch status update of camera: 5
I/flutter (22595): ====================CAMERA===================
I/flutter (22595): CameraDescription(0, CameraLensDirection.back, 90)
I/flutter (22595): CameraDescription(1, CameraLensDirection.front, 270)
I/flutter (22595): ====================CAMERA===================
I/flutter (22595): ====================CAMERA===================
I/flutter (22595): CameraDescription(0, CameraLensDirection.back, 90)
I/flutter (22595): CameraDescription(1, CameraLensDirection.front, 270)
I/flutter (22595): ====================CAMERA===================
E/LB      (22595): fail to open file: No such file or directory
I/mple.camerates(22595): ProcessProfilingInfo new_methods=1016 is saved saved_to_disk=1 resolve_classes_delay=8000
D/FrameIndicator(22595): support status: 1 0x79d0332018 0x79d03324c4
W/Camera  (22595): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
D/FrameIndicator(22595): support status: 1 0x79d0332018 0x79d03324c4
D/CameraInjector(22595): notifyRF for API 2 : cameraRoleId = 1, active = true
D/CameraInjector(22595): notifyRF cameraId = 1, active ? true
I/Camera  (22595): startPreview
D/FrameIndicator(22595): support status: 1 0x79d0332018 0x79d03324c4
I/Camera  (22595): CameraCaptureSession onConfigured
I/Camera  (22595): Updating builder settings
D/Camera  (22595): Updating builder with feature: ExposureLockFeature
D/Camera  (22595): Updating builder with feature: ExposurePointFeature
D/Camera  (22595): Updating builder with feature: ZoomLevelFeature
D/Camera  (22595): Updating builder with feature: AutoFocusFeature
D/Camera  (22595): Updating builder with feature: NoiseReductionFeature
I/Camera  (22595): updateNoiseReduction | currentSetting: fast
D/Camera  (22595): Updating builder with feature: FocusPointFeature
D/Camera  (22595): Updating builder with feature: ResolutionFeature
D/Camera  (22595): Updating builder with feature: SensorOrientationFeature
D/Camera  (22595): Updating builder with feature: FlashFeature
D/Camera  (22595): Updating builder with feature: ExposureOffsetFeature
D/Camera  (22595): Updating builder with feature: FpsRangeFeature
I/Camera  (22595): refreshPreviewCaptureSession
I/Camera  (22595): open | onError
I/Camera  (22595): close
D/CameraInjector(22595): notifyRF for API 2 : cameraRoleId = 1, active = false
D/CameraInjector(22595): notifyRF cameraId = 1, active ? false
W/BpBinder(22595): Slow Binder: BpBinder transact took 802 ms, interface=android.hardware.camera2.ICameraDeviceUser, code=1 oneway=false
I/Camera  (22595): open | onClosed
W/CameraManagerGlobal(22595): ignore the torch status update of camera: 5
W/CameraManagerGlobal(22595): [soar.cts] ignore the status update of camera: 5
W/CameraManagerGlobal(22595): ignore the torch status update of camera: 3
W/CameraManagerGlobal(22595): [soar.cts] ignore the status update of camera: 3
W/CameraManagerGlobal(22595): ignore the torch status update of camera: 2
W/CameraManagerGlobal(22595): [soar.cts] ignore the status update of camera: 2
W/CameraManagerGlobal(22595): ignore the torch status update of camera: 4
W/CameraManagerGlobal(22595): [soar.cts] ignore the status update of camera: 4
W/CameraManagerGlobal(22595): [soar.cts] ignore the status update of camera: 6
E/CameraManagerGlobal(22595): Camera 4 is not available. Ignore physical camera status change
```
And logs on camera plugin 0.9.2+2
```
I/Camera  (17719): open | onError
I/Camera  (17719): close
I/Camera  (17719): closeCaptureSession
E/CameraCaptureSession(17719): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(17719): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession(17719): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2327)
E/CameraCaptureSession(17719): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1273)
E/CameraCaptureSession(17719): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
E/CameraCaptureSession(17719): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1086)
E/CameraCaptureSession(17719): 	at io.flutter.plugins.camera.Camera.close(Camera.java:1093)
E/CameraCaptureSession(17719): 	at io.flutter.plugins.camera.Camera$1.onError(Camera.java:294)
E/CameraCaptureSession(17719): 	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1725)
E/CameraCaptureSession(17719): 	at android.hardware.camera2.impl.CameraDeviceImpl.lambda$oDs27OTfKFfK18rUW2nQxxkPdV0(Unknown Source:0)
E/CameraCaptureSession(17719): 	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$oDs27OTfKFfK18rUW2nQxxkPdV0.accept(Unknown Source:8)
E/CameraCaptureSession(17719): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:278)
E/CameraCaptureSession(17719): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
E/CameraCaptureSession(17719): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
E/CameraCaptureSession(17719): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession(17719): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(17719): 	at android.os.Looper.loop(Looper.java:237)
E/CameraCaptureSession(17719): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/CameraInjector(17719): notifyRF for API 2 : cameraRoleId = 1, active = false
D/CameraInjector(17719): notifyRF cameraId = 1, active ? false
```

Source code:

```
import 'dart:async';
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MaterialApp(home: MenuCamera()));
}

class MenuCamera extends StatefulWidget {
  const MenuCamera({Key? key}) : super(key: key);

  @override
  _MenuCameraState createState() => _MenuCameraState();
}

class _MenuCameraState extends State<MenuCamera> {

  Future<CameraDescription> camera() async {
    WidgetsFlutterBinding.ensureInitialized();

    // Obtain a list of the available cameras on the device.
    final cameras = await availableCameras();

    // Get a specific camera from the list of available cameras.
    var firstCamera = cameras[1];
    print('====================CAMERA===================');
    print(cameras[0]);
    print(firstCamera);
    print('====================CAMERA===================');

    return firstCamera;
  }

  @override
  void initState() {
    camera();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.blueGrey,
      body: FutureBuilder<CameraDescription>(
          future: camera(),
          builder: (context,AsyncSnapshot snapshot) {
            if (snapshot.data == null) {
              return const Center(
                child: CircularProgressIndicator(),
              );
            }
            return TakePictureScreen(
              camera: snapshot.data,
            );
          }),
    );
  }
}

// A screen that allows users to take a picture using a given camera.
class TakePictureScreen extends StatefulWidget {
  const TakePictureScreen({
    required this.camera,
  });

  final CameraDescription camera;

  @override
  TakePictureScreenState createState() => TakePictureScreenState();
}

class TakePictureScreenState extends State<TakePictureScreen> {
  late CameraController _controller;
  late Future<void> _initializeControllerFuture;

  @override
  void initState() {
    super.initState();
    // To display the current output from the Camera,
    // create a CameraController.
    _controller = CameraController(
      // Get a specific camera from the list of available cameras.
      widget.camera,
      // Define the resolution to use.
      ResolutionPreset.max,
    );

    // Next, initialize the controller. This returns a Future.
    _initializeControllerFuture = _controller.initialize();
  }

  @override
  void dispose() {
    // Dispose of the controller when the widget is disposed.
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Take a picture')),
      // You must wait until the controller is initialized before displaying the
      // camera preview. Use a FutureBuilder to display a loading spinner until the
      // controller has finished initializing.
      body: FutureBuilder<void>(
        future: _initializeControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the Future is complete, display the preview.
            return CameraPreview(_controller);
          } else {
            // Otherwise, display a loading indicator.
            return const Center(child: CircularProgressIndicator());
          }
        },
      ),
      floatingActionButton: FloatingActionButton(
        // Provide an onPressed callback.
        onPressed: () async {
          // Take the Picture in a try / catch block. If anything goes wrong,
          // catch the error.
          try {
            // Ensure that the camera is initialized.
            await _initializeControllerFuture;

            // Attempt to take a picture and get the file `image`
            // where it was saved.
            final image = await _controller.takePicture();

            // If the picture was taken, display it on a new screen.
            await Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) => DisplayPictureScreen(
                  // Pass the automatically generated path to
                  // the DisplayPictureScreen widget.
                  imagePath: image.path,
                ),
              ),
            );
          } catch (e) {
            // If an error occurs, log the error to the console.
            print(e);
          }
        },
        child: const Icon(Icons.camera_alt),
      ),
    );
  }
}

// A widget that displays the picture taken by the user.
class DisplayPictureScreen extends StatelessWidget {
  final String imagePath;

  const DisplayPictureScreen({required this.imagePath});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Display the Picture')),
      // The image is stored as a file on the device. Use the `Image.file`
      // constructor with the given path to display the image.
      body: Image.file(File(imagePath)),
    );
  }
}
```

and pubspec.yaml
```
name: cameratest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  camera: 0.9.2+2
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

_Originally posted by @MohamedSafvanKP-MSIL in https://github.com/flutter/flutter/issues/92762#issuecomment-1330617764_
