### ISSUE TITLE
[linux] snapcraft fails: undefined reference to `FT_Done_MM_Var'

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#116562]
Spent two days trying different things, but nothing works.

<details>
  <summary>Error</summary>
  
```
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[   +4 ms] /snap/flutter/current/usr/bin/ld: /snap/flutter/current/usr/lib/x86_64-linux-gnu/libharfbuzz.so: undefined reference to `FT_Done_MM_Var'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[   +1 ms] ninja: build stopped: subcommand failed.
```
</details>

<details>
  <summary>snapcraft.yaml</summary>
  
```
name: driftwood
version: '1.0.0'
summary: Driftwood
description: Used in conjunction with the Driftwood chrome plugin
icon: snap/gui/driftwood.png

confinement: strict
base: core18
grade: stable

apps:
  driftwood:
    command: driftwood
    extensions: [flutter-stable]
    plugs:
      - network
      - desktop

parts:
  driftwood:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

    build-packages:
      - libayatana-appindicator3-dev

    stage-packages:
      - libayatana-appindicator3-1
```
</details>

**Comment by sgehrman** [comment]
seems to have something to do with:

stage-packages:
      - libayatana-appindicator3-1

as it will build without that, but then running the app crashes saying 

/snap/driftwood/x1/bin/driftwood: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory

**Comment by exaby73** [comment]
Hello @sgehrman. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- Build comment used

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by sgehrman** [comment]
you can do it, I'm busy.

**Comment by exaby73** [comment]
@sgehrman I am here to verify and label issues for the team to look into later. Without verifying the issue with a reproducible sample, the issue cannot be taken forward. Please provide a sample when you can, so that I can verify it. 

Also, please read the [Code of Conduct](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct). Please refrain from comments such as these

**Comment by sgehrman** [comment]
Code of conduct?  Wow!  Do I need to wear a mask too?

**Comment by exaby73** [comment]
Following instructions from https://docs.flutter.dev/deployment/linux, I cannot reproduce this issue. Which is why I am asking you for a sample. How would someone fix the issue if it's not reproducible? I need a reproducible sample so that I can verify the issue and it can be taken forward. Without a reproducible sample, this issue would not be actionable unfortunately

**Comment by EsmaeilDansi** [comment]
I have this problem too

**Comment by sgehrman** [comment]
I switched to flatpak. It's much better.  Snap is a disaster.

**Comment by exaby73** [comment]
Since this is an issue with snap, I think this issue is better raised in the snap repo. Therefore I am closing this issue, If you disagree, please comment and I can reopen it. Thank you

**Comment by ContraryRobin3** [comment]
@exaby73 I am experiencing this issue as well. I also have a sample I can provide if that helps.

**Comment by exaby73** [comment]
@ContraryRobin3 If you can provide a reproducible sample, that would be great

**Comment by ContraryRobin3** [comment]
after following the instruction on https://docs.flutter.dev/deployment/linux . Add the following files to the snap/gui directory:
* <details><summary>CLICK ME</summary>
    <p>

        [Desktop Entry]
        Name=Sample
        Comment=Super Cool App that does everything
        Exec=sample
        Icon=${SNAP}/meta/gui/sample.png
        Terminal=false
        Type=Application
        Categories=Art and Design, Productivity 
        

* sample.png for the icon

edit the snapcraft.yaml to be
<details><summary>CLICK ME</summary>
<p>


```yaml
name: sample
title: Sample
version: 0.3.0
summary: Sample - sample
description: test description
icon: snap/gui/sample.png

confinement: strict
base: core18
grade: stable

slots:
  dbus-sample: 
    interface: dbus
    bus: session
    name: com.example.sample
    
apps:
  sample:
    command: sample
    extensions: [flutter-stable] # Where "master" defines which Flutter channel to use for the build
    plugs:
      - network
      - home
    slots: [ dbus-sample ]
parts:
  zenity:
    plugin: nil
    stage-packages:
      - zenity

  sample:
    after:
      - zenity
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
```

</p>
</details>

then run snapcraft --use-lxd to build
