### ISSUE TITLE
Flutter 3 is still using the SF UI Text (SF Pro Text) for all font sizes

### ISSUE THREAD

**Issue by jetlye2804** [flutter/flutter#116831]
It's already Flutter 3 right now, but the font family rendering in iOS is still terrible.

It is still using SF UI Text (SF Pro Text) in font size which greater than 19. Supposingly

To make a comparison, I imported both SF Pro Text, SF Pro Display font files into the project folder, and use SF Pro Text, Default font rendered by Flutter in iOS (SF UI Text), and SF Pro Display in three respective texts with the same content. Which is shown as the screenshot below.

![IMG_3445](https://user-images.githubusercontent.com/82960491/206862896-fadd8f1d-558b-4054-97d2-8bc66ed4500a.PNG)

In `pubspec.yaml`:
```
flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-UltralightItalic.otf
          weight: 100
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-ThinItalic.otf
          weight: 200
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-Black.otf
          weight: 900
        - asset: fonts/SF-Pro-Display/SF-Pro-Display-BlackItalic.otf
          weight: 900
          style: italic
    - family: SF Pro Text
      fonts:
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-UltralightItalic.otf
          weight: 100
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-ThinItalic.otf
          weight: 200
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Black.otf
          weight: 900
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-BlackItalic.otf
          weight: 900
          style: italic
```

In code:
```
Container(
        width: double.infinity,
        padding: const EdgeInsets.only(left: 16, right: 16),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            const Text('SF Pro Text',
                style: TextStyle(
                  fontSize: 18,
                )),
            const Text('Contacts',
                style: TextStyle(
                  fontSize: 84,
                  fontFamily: 'SF Pro Text',
                  fontWeight: FontWeight.w700,
                )),
            const Text('Flutter rendered default font in iOS',
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 18,
                )),
            const Text('Contacts',
                style: TextStyle(
                  fontSize: 84,
                  fontWeight: FontWeight.w700,
                )),
            const Text('Contacts',
                style: TextStyle(
                  fontSize: 84,
                  fontFamily: 'SF Pro Display',
                  fontWeight: FontWeight.w700,
                )),
            const Text('SF Pro Display',
                style: TextStyle(
                  fontSize: 18,
                )),
            const SizedBox(
              height: 20,
            ),
          ],
        ),
      ),
```

`flutter doctor -v`

```
[✓] Flutter (Channel beta, 3.6.0-0.1.pre, on macOS 13.0.1 22A400 darwin-arm64, locale en-US)
    • Flutter version 3.6.0-0.1.pre on channel beta at /Users/jetlye/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 75927305ff (3 weeks ago), 2022-11-17 05:52:50 +0530
    • Engine revision b754eabc98
    • Dart version 2.19.0 (build 2.19.0-374.1.beta)
    • DevTools version 2.19.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jetlye/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/jetlye/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (1 available)
    • Jet’s iPhone (mobile) • [HIDE IT INTENTIONALLY] • ios • iOS 16.1.2 20B110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by 88RIK88** [comment]
Would it not be possible to use SF-Pro by downloading it from Apple, then adding it to pubspec.yaml. The font styles can then either be hard coded or calculated. Looking at the source code of Cupertino Text Theme it appears this is the same approach used by Flutter but with only a few values hard coded and with SF Pro Text and SF Pro Display instead of the newer SF Pro.
```
fonts:
    - family: SF-Pro
      fonts:
        - asset: fonts/SF-Pro.ttf
```

Then addressing the tracking by either hard coding:

```
class UISFTextStyles {
  static const _font = 'SF-Pro';

  static const TextStyle body = TextStyle(
    fontFamily: _font,
    fontSize: 17,
    letterSpacing: -0.43,
  );
  static const TextStyle callout = TextStyle(
    fontFamily: _font,
    fontSize: 16,
    letterSpacing: -0.31,
  );
//etc..
}
```

or even calculating:

```
extension SFTextStylesTracking on TextStyle {
  tracking(double fontSize){ 
    return merge(
      TextStyle(letterSpacing: _Tracking[fontSize]);
    }
  }

  // source of values: https://developer.apple.com/design/human-interface-guidelines/foundations/typography/

class _Tracking {
        static const Map<int, double> tracking = {
            6: 0.24,
            7: 0.23,
            8: 0.21,
            9: 0.17,
            10: 0.12,
            11: 0.06,
            12: 0,
            13: -0.08,
        etc..
        }
}
```

Is there any reason why this would not be an acceptable compromise until the SF-Pro font becomes the default in CupertinoTextTheme.
