### ISSUE TITLE
For what's worth, @999eagle got caching working on both iOS and android on a custom fork of the plugins repository video_player. We hope to open a PR with this back into the plugins repo at some point.

### ISSUE THREAD

**Issue by farzasim1** [flutter/flutter#116827]
For what's worth, @999eagle got caching working on both iOS and android on a custom fork of the plugins repository video_player. We hope to open a PR with this back into the plugins repo at some point.

```
  video_player:
    git:
      url: https://github.com/999eagle/plugins.git
      ref: feature/caching
      path: packages/video_player
```

Limit is set to 200mbs

Here are the commits with the magic.

https://github.com/999eagle/plugins/commits/feature/caching

Thanks to her work, we've now got video playing in our app :-)

_Originally posted by @lifenautjoe in https://github.com/flutter/flutter/issues/28094#issuecomment-533831604_
