### ISSUE TITLE
ValueNotifier is not disposed by tooltip.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#117063]
To repro, attach leak_tracker to the counter app.

```
flutter --version
Flutter 3.7.0-7.0.pre.8 • channel master • git@github.com:polina-c/flutter.git
Framework • revision cd9a439c35 (20 hours ago) • 2022-12-13 14:40:48 -0500
Engine • revision 9872cc7add
Tools • Dart 3.0.0 (build 3.0.0-19.0.dev) • DevTools 2.20.0
```

```
# For memory leaks troubleshooting tips see
# https://github.com/dart-lang/leak_tracker

not-disposed:
  total: 1
  objects:
    ValueNotifier<bool>:
      identityHashCode: 16539540
      context:
        start: >
          #0      ObjectTracker.startTracking (package:leak_tracker/src/_object_tracker.dart:63:64)
          #1      dispatchObjectEvent (package:leak_tracker/src/_dispatcher.dart:38:19)
          #2      dispatchObjectEvent (package:leak_tracker/src/leak_tracker.dart:71:14)
          #3      main.<anonymous closure> (package:leak_tracker_minimal_flutter_example/main.dart:12:43)
          #4      MemoryAllocations.dispatchObjectEvent (package:flutter/src/foundation/memory_allocations.dart:238:23)
          #5      MemoryAllocations.dispatchObjectCreated (package:flutter/src/foundation/memory_allocations.dart:272:5)
          #6      new ValueNotifier (package:flutter/src/foundation/change_notifier.dart:473:34)
          #7      new OverlayEntry (package:flutter/src/widgets/overlay.dart:138:52)
          #8      TooltipState._createNewEntry (package:flutter/src/material/tooltip.dart:608:14)
          #9      TooltipState.ensureTooltipVisible (package:flutter/src/material/tooltip.dart:552:5)
          #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
          #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
          #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
          #13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```
