### ISSUE TITLE
import of dart:mirrors is not supported in the current Dart runtime

### ISSUE THREAD

**Issue by Djihanegh** [flutter/flutter#117142]
The app suddenly stopped working (crash on launch ) and i don't know which package is causing this error( see Logs part), i don't have ```json_serializable``` in my project ( Pubspec File )

**Tried before**

1. flutter clean + pub get ( it doesnt work )

<details>
<summary> Pubspec File</summary>

```
environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  flutter_svg: ^1.1.4
  square_percent_indicater: ^0.1.0
  device_apps: ^2.2.0
  flutter_bloc: ^8.1.1
  freezed:
  freezed_annotation:
  injectable:
  injectable_generator: ^1.5.4
  bloc: ^8.1.0
  usage_stats:
    git:
      url: https://github.com/Djihanegh/usage_stats.git
  app_usage: ^2.0.0
  shared_preferences: ^2.0.15
  flutter_foreground_task: ^3.10.0
  app_to_foreground: ^0.0.3
  system_alert_window: ^1.1.2
 # share_plus: ^4.4.0
  bg_launcher:
    git:
      url: https://github.com/Djihanegh/bg_launcher.git
      ref: main
 # receive_intent: ^0.2.0
  flutter_background_service: ^2.4.5
  flutter_local_notifications: ^11.0.1
  device_info_plus: ^4.1.2
  flutter_appavailability:
    git:
      url: https://github.com/LongXiangGuo/flutter_appavailability.git
      ref: master
  enum_to_string: ^2.0.1
  get: ^4.6.5
  path_provider: ^2.0.11
  isar: 3.0.5
  isar_flutter_libs: 3.0.5
  #workmanager: ^0.5.0
  #provider: ^6.0.4
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  cloud_firestore: ^4.0.4
  firebase_core: ^2.1.1
  uuid: ^3.0.7
  google_fonts: ^3.0.1
  intl: ^0.17.0
  flutter_overlay_window: ^0.3.2
dev_dependencies:
  build_runner:
  isar_generator: 3.0.5

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
```

</details>

<details>
  <summary>Logs</summary>

```
[ERROR:flutter/shell/common/shell.cc(93)] Dart Error: error: import of dart:mirrors is not supported in the current Dart runtime
E/flutter (21983): [ERROR:flutter/runtime/dart_isolate.cc(143)] Could not prepare isolate.
E/flutter (21983): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
E/flutter (21983): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.
E/flutter (21983): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: error: import of dart:mirrors is not supported in the current Dart runtime
E/flutter (21983): [ERROR:flutter/runtime/dart_isolate.cc(143)] Could not prepare isolate.
E/flutter (21983): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
E/flutter (21983): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.
```

```
```

```
```

</details>
