### ISSUE TITLE
i can't build flutter after 1 year, it worked before!

### ISSUE THREAD

**Issue by ezioadf2** [flutter/flutter#117596]
## Steps to Reproduce
hi
i can't build flutter after 1 year, it worked before!
its work when i want test app in emulator but at release version can't make output

**Expected results:** 

**Actual results:** 

<details>
<summary>gradle-wrapper.properties:</summary>

```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

```

</details>

<details>
<summary>build.gradle:</summary>

```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
...
}
```

</details>
<details>
  <summary>error Logs</summary>

```
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':url_launcher_android:debugUnitTestRuntimeClasspath'.
   > Could not find core-1.0.0.aar (androidx.test:core:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/test/core/1.0.0/core-1.0.0.aar
   > Could not find monitor-1.2.0.aar (androidx.test:monitor:1.2.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/test/monitor/1.2.0/monitor-1.2.0.aar

```

```
```

flutter doctor:
```
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 3.0.2 at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (7 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = D:\sdk
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\EzioSliverHand\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.53

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>
<details>
<summary>pubspec.yaml:</summary>

```
name: untitled
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-45.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animate_do: ^2.1.0
  percent_indicator: 4.2.2
  http: ^0.13.4
  flutter_svg: ^1.0.3
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.7
  persian_datetime_picker: ^2.5.0
  jalali_calendar: ^1.0.4
  persian_date: ^0.1.5
  internet_connection_checker: ^0.0.1+3
  shamsi_date: ^1.0.1
  super_list_view: ^0.0.5
  flutter_inappwebview: ^5.4.3+7
  model_viewer_plus: ^1.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/models/textures/
    - assets/models/scene.gltf

  fonts:
    - family: vazir
      fonts:
       - asset: assets/fonts/Vazir-Light.ttf
         weight: 700

```

</details>
