### ISSUE TITLE
ListView/ScrollView - Scrolling jumps to the bottom regardless of items on M1 iOS Simulator

### ISSUE THREAD

**Issue by louisoftokyo** [flutter/flutter#117632]
This is the same issue as [this](https://github.com/flutter/flutter/issues/79641), which is marked as closed. Please see that issue for details. According to that issue this was caused by the arm64 simulator and was fixed in an update, however, I have recently started Flutter development and am currently experiencing this issue.

Flutter 3.3.10
Xcode 14.2
M1  MacBook Pro

The scrolling behaviour works as expected on Android.

**Comment by huycozy** [comment]
@louisoftokyo Can you retry on the latest Flutter master channel (3.7.0.) to check if the issue still persists or not?

**Comment by louisoftokyo** [comment]
@huycozy I've switched to master (`flutter doctor` says `Flutter (Channel master, 3.7.0-13.0.pre.79, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)`) and the issue is still occurring.

**Comment by huycozy** [comment]
@louisoftokyo Can you confirm whether the issue happens with the normal list (from OP in #79641) or with Google Maps plugin as mentioned at https://github.com/flutter/flutter/issues/79641#issuecomment-868368492?

**Comment by louisoftokyo** [comment]
@huycozy I am using a normal ListView.separated().

**Comment by danagbemava-nc** [comment]
Hi @louisoftokyo, do you happen to have `google_maps_flutter` in your `pubspec.yaml`? If you have it included in the project, the simulator is run in Rosetta mode by default. See https://github.com/flutter/flutter/issues/112244#issuecomment-1259785112

**Comment by louisoftokyo** [comment]
@danagbemava-nc I do not have `google_maps_flutter` in my `pubspec.yaml`. Here it is:

```
name: my_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: any
  get_it: ^7.2.0
  intl: ^0.18.0
  timeago: ^3.2.2
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  animations: ^2.0.7
  zoom_tap_animation: ^1.1.0
  bubble: ^1.2.1
  dropdown_button2: ^1.9.2
  fluttertoast: ^8.1.2
  rounded_loading_button: ^2.1.0
  custom_refresh_indicator: ^2.0.1
  uuid: ^3.0.7
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
