### ISSUE TITLE
Make AppLocalizations.of not nullable

### ISSUE THREAD

**Issue by CodeDoctorDE** [flutter/flutter#118155]
## Use case

The current behavior of `AppLocalizations.of` gives a nullable object.
It's very exhausting to write an exclamation mark on every call

## Proposal

Make AppLocalizations.of non nullable.
Other `of` methods have the same behavior:
- https://api.flutter.dev/flutter/widgets/Navigator/of.html
- https://api.flutter.dev/flutter/material/Scaffold/of.html
- https://api.flutter.dev/flutter/search.html?q=Theme.of

**Comment by notDmDrl** [comment]
@CodeDoctorDE, you can make AppLocalizations.of non nullable by adding `nullable-getter: false` into your `l10n.yaml`

**Comment by maRci002** [comment]
Note when using `gen-l10n` tool directly then `--nullable-getter false` won't be recognized nor error will be raisen.

See: #118203

**Comment by thkim1011** [comment]
Seems like this is resolved? I'll take a look at the other issue where `--nullable-getter false` doesn't seem to throw an error.

**Comment by masreplay** [comment]
Also, you can add
```yaml
nullable-getter: false
```

into your **l10n.yaml** file like this:

```yaml
arb-dir: lib/l10n
template-arb-file: app_en.arb
preferred-supported-locales:
  - en
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.txt
nullable-getter: false
```
