### ISSUE TITLE
"server unavailable" issue while running `pub get` in github actions

### ISSUE THREAD

**Issue by muhammadmateen027** [flutter/flutter#118232]
For the last 1 week, I am facing the "server unavailable" issue while running the `flutter pub get` command in `GitHub` actions.
On the other hand, `flutter pub get` works totally fine on my local.

Additionally, I have already checked the `pubspec.yaml` file and there is no error.

What could be the problem and how to resolve it?

Error sample:
```dart
[+4101 ms] pub get failed (server unavailable) -- attempting retry 1 in 1 second...
[58](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:58)
[+1024 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[59](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:59)
[+4045 ms] pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
[60](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:60)
[+2001 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[61](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:61)
[+4075 ms] pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
[62](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:62)
[+4000 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[63](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:63)
[+4010 ms] pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
[64](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:64)
[+8000 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[65](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:65)
[+3920 ms] pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
[66](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:66)
[+16001 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[67](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:67)
[+4001 ms] pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
[68](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:68)
[+32000 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[69](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:69)
[+3923 ms] pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
[70](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:70)
[+64001 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[71](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:71)
[+4342 ms] pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...
[72](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:72)
[+64001 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[73](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:73)
[+3991 ms] pub get failed (server unavailable) -- attempting retry 9 in 64 seconds...
[74](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:74)
[+64001 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[75](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:75)
[+4008 ms] pub get failed (server unavailable) -- attempting retry 10 in 64 seconds...
[76](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:76)
[+64001 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[77](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:77)
[+4032 ms] pub get failed (server unavailable) -- attempting retry 11 in 64 seconds...
[78](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:78)
[+64001 ms] executing: [/__w/project-honey-badger/project-honey-badger/] /root/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose --directory . get --example
[79](https://github.com/upday/project-honey-badger/actions/runs/3881762842/jobs/6621133607#step:6:79)
[+3950 ms] pub get failed (server unavailable) -- attempting retry 12 in 64 seconds...
```

Flutter doctor summary:

```dart
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.4.0-34.1.pre, on macOS 12.6.1 21G217 darwin-x64, locale
    en-DE)
    ! Flutter version 3.4.0-34.1.pre on channel unknown at /Users/mmateen/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official
      channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
[✓] VS Code (version 1.74.2)
[!] Connected device
    ! No devices are available
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Comment by huycozy** [comment]
@muhammadmateen027 Look like your Github Actions is setting an unknown channel. There are [three Flutter channels](https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels): stable, beta and master. 

Please retry on one of these channels to see if the issue still persists or not.

Some issues may be related: 
- #95472: relate to Flutter SDK constraint. Can you share your `pubspec.yaml` file content? 
- #78956: relate to Git config. Can you share the complete Github Actions logs?

**Comment by muhammadmateen027** [comment]
> @muhammadmateen027 Look like your Github Actions is setting an unknown channel. There are [three Flutter channels](https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels): stable, beta and master.
> 
> Please retry on one of these channels to see if the issue still persists or not.
> 
> Some issues may be related:
> 
> * [[flutter_tools] pubspec.yaml environment.flutter constraint not respected by pub get #95472](https://github.com/flutter/flutter/issues/95472): relate to Flutter SDK constraint. Can you share your `pubspec.yaml` file content?
> * [pubspec with faulty git config leads to error 128 and infinite retries #78956](https://github.com/flutter/flutter/issues/78956): relate to Git config. Can you share the complete Github Actions logs?

I am using the same flutter version in my local with the same channel info.
There you go for my workflow:

```yml

name: Test Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ ESC-landing-page ]

jobs:
  android:
    name: Test Android
    runs-on: flutter
    container:
      image: upday/flutter-toolchain:3.4.0-34.1.pre
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.4.1

    - name: Info
      run: |
        flutter doctor -v

    - name: Clean
      run: flutter clean

    - name: Get dependencies
      run: flutter pub get --verbose

    - name: Check formatting
      run: flutter format . --set-exit-if-changed
```

**Comment by huycozy** [comment]
>https://github.com/flutter/flutter/issues/95472: relate to Flutter SDK constraint. Can you share your pubspec.yaml file content?
https://github.com/flutter/flutter/issues/78956: relate to Git config. Can you share the complete Github Actions logs?

Please check these issues mentioned in my above comment if they are similar and also provide the information so that we may verify this. We can not verify the issue in this case when it's running on your CI/CD system.

Also, let's try using other channels (stable/beta/master) to check if the issue still occurs.

**Comment by muhammadmateen027** [comment]
I have checked above mentioned comments and it is not relevant to my issue as I have tried, and here is my `pubspec.yaml` file content:

```yaml
name: Hello World
description: Hello World

publish_to: 'none'

version: 1.1.236+520

environment:
  sdk: ">=2.18.0-44.1.beta <3.0.0"
  flutter: ">=1.24.0-6.0.pre <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path_provider: ^2.0.11
  firebase_remote_config: ^3.0.5
  firebase_crashlytics: ^3.0.5
  firebase_performance: ^0.9.0+5
  firebase_messaging: ^14.1.0
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  flutter_redux: ^0.10.0
  redux_epics: ^0.15.1
  redux_logging: ^0.5.0
  rxdart: ^0.27.5
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  package_info_plus: ^3.0.1
  google_fonts: ^3.0.1
  meta: ^1.8.0
  recase: ^4.1.0
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.6
  google_sign_in: ^5.4.2
  network_image_mock: ^2.1.1
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.11
  dio: ^4.0.6
  palette_generator: ^0.3.3+2
  flutter_web_browser: ^0.17.1
  transparent_image: ^2.0.0
  quiver: ^3.1.0
  table_calendar: ^3.0.8
  google_mobile_ads: ^2.3.0
  flutter_local_notifications: ^12.0.3
  share_plus: ^6.2.0
  firebase_dynamic_links: ^5.0.5
  colorize: ^3.0.0
  visibility_detector: ^0.3.3
  adjust_sdk: ^4.32.0
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.0.0
  firebase_in_app_messaging: ^0.7.0+5
  drift_db_viewer: ^2.0.0
  cached_network_image: ^3.2.2
  flutter_cache_manager: ^3.3.0
  image_gallery_saver: ^1.7.1
  flutter_painter: ^1.0.1
  video_player: ^2.4.7
  showcaseview: ^2.0.0+1
  webview_flutter: ^3.0.4
  bottom_bar: ^2.0.2

  youtube_player_iframe:
    git:
      url: git@github.com:upday/youtube_player_flutter.git
      path: packages/youtube_player_iframe
      ref: v2.3.0-upday

  earli_audio_debug_utils:
    git:
      url: git@github.com:upday/earli-audio-debug-utils.git
      ref: 2.1.2

  earli_audio_logger:
    git:
      url: git@github.com:upday/earli-audio-logger.git
      ref: 2.1.0

  earli_audio_data_state:
    git:
      url: git@github.com:upday/earli-audio-data-state.git
      ref: 2.0.1-nullsafety.3

  earli_audio_connection_info:
    git:
      url: git@github.com:upday/earli-audio-connection-info.git
      ref: v2.0.0-nullsafety.1

  notification_handler_flutter:
    git:
      url: git@github.com:upday/notification_handler_flutter.git
      ref: v7.0.0

  flutter_sourcepoint_cmp:
    git:
      url: git@github.com:upday/flutter_sourcepoint_cmp.git
      ref: v1.3.0

  flutter_analytics_trackers:
    git:
      url: git@github.com:upday/flutter-analytics-trackers.git
      ref: v3.0.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  test:
  mocktail: ^0.3.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  process_run: ^0.12.3+2
  built_value: ">=8.1.0 <8.2.0"
  built_value_generator: ^8.4.2
  build_config: ^1.1.1
  build: ^2.3.1
  source_gen: ^1.2.6
  drift_dev: ^2.1.0
  graphql: ^5.1.1
  flutter_lints: ^2.0.1
  flutter_inappwebview: ^5.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/meme/

flutter_intl:
  enabled: true
```
