### ISSUE TITLE
Recording video on Android 13 API 33 fails with java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.ContentValues.put(java.lang.String, java.lang.Long)' on a null object reference

### ISSUE THREAD

**Issue by tomekit** [flutter/flutter#118443]
I am using Android Pixel 5 API 33 emulator. When I try to record a video and get the file, just after clicking "stop record" button I get this error:
```
E/AndroidRuntime(31578): FATAL EXCEPTION: main
E/AndroidRuntime(31578): Process: com.android.camera2, PID: 31578
E/AndroidRuntime(31578): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.ContentValues.put(java.lang.String, java.lang.Long)' on a null object reference
E/AndroidRuntime(31578): 	at com.android.camera.VideoModule.saveVideo(VideoModule.java:1263)
E/AndroidRuntime(31578): 	at com.android.camera.VideoModule.stopVideoRecording(VideoModule.java:1513)
E/AndroidRuntime(31578): 	at com.android.camera.VideoModule.onStopVideoRecording(VideoModule.java:656)
E/AndroidRuntime(31578): 	at com.android.camera.VideoModule.onShutterButtonClick(VideoModule.java:697)
E/AndroidRuntime(31578): 	at com.android.camera.ShutterButton.performClick(ShutterButton.java:190)
E/AndroidRuntime(31578): 	at android.view.View.performClickInternal(View.java:7483)
E/AndroidRuntime(31578): 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
E/AndroidRuntime(31578): 	at android.view.View$PerformClick.run(View.java:29334)
E/AndroidRuntime(31578): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(31578): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31578): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(31578): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(31578): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(31578): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31578): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(31578): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Flutter version
```
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (4 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

puspec.yaml
```
 image_picker: ^0.8.6
```

pubspec.lock
```
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.6"
  image_picker_android:
    dependency: transitive
    description:
      name: image_picker_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.5+4"
```

I can reproduce issue locally.
