### ISSUE TITLE
Include assets from a directory recursively

### ISSUE THREAD

**Issue by cbatson** [flutter/flutter#118635]
Greetings Flutter team & community,

I would like to re-open the discussion which started in #4890.

In particular, a mechanism to add asset files *recursively* would benefit my use case, and as evidenced by [this comment](https://github.com/flutter/flutter/issues/4890#issuecomment-407327749), I suspect would benefit use cases of others.

My present use case is that I would like to embed many files into the app, so that I do not have to stand up a back end to host the files. This seems like a fairly typical desire.

However, not being able to recursively add assets is a hindrance.

I understand that

- There are possible work-arounds, such as tools/scripts to generated the needed paths for the `assets` key
- The reason for not implementing recursive asset inclusion in #4890 relates to the handling of variants (see #16413 and [this](https://medium.com/flutter-community/contributing-to-flutter-part-3-4b96d924d8ba))

## Use case

Add many files as assets, for example, when you'd prefer to bundle files with the app package rather than download them separately.

## Proposal

I am mostly hoping to spark some conversation around this, although one possible way to do this given the legacy/constraints of variants would be to introduce a new pubspec.yaml key, analogous to `assets`, but which does not allow variants and will be capable of adding files recursively and/or by wildcard. Said new key could be named something like `nonvariant_assets`.

Thank you for your time.

**Comment by darshankawar** [comment]
Thanks for the report. Since the original issue is close and was an old one, I'll keep this issue open for team's attention if there's any changes in the approach since the last time this proposal was discussed.

**Comment by damywise** [comment]
Honestly this feature would be so awesome in my use case. I'm developing a package. It is for a toolkit that basically generates completely different folder structure dynamically every time it saves a project, depending on the settings and the contents.

This feature would completely remove the need of touching the `pubspec.yaml` every time the toolkit saves a project and regenerates the whole `assets/*` structure.

**Comment by spydon** [comment]
Since games usually make very heavy use of assets (much more so than normal apps) I think this would deserve the GameDev tag, what do you think @wolfenrain?

**Comment by pcornelissen** [comment]
The usecase is more likely for games, but larger applications may also suffer from this, when the icons are not in fonts, but seperate files or you have localized images of some kind etc.

I was very surprised that something like that doesn't exist and globbing for asset definitions shouldn't be hard to implement, when you have control over the build steps

**Comment by Luckey-Elijah** [comment]
To avoid unintended consequences and confusion, I think an "opt-in" approach would be best. I believe that is the intent mentioned here https://github.com/flutter/flutter/issues/4890#issuecomment-378604407 in an early iteration of the folder bundling.

Perhaps this could be enable in the `flutter:` entry in pubspec, allowing developers to explicitly enable the _recursive_ asset bundling.

For example:

```yaml
# pubspec.yaml
flutter:
  recursive-bundling: true # doesn't really matter what the key is
  assets: [...]
```

This approach avoids accidentally enabling the feature only via a vague glob-syntax mechanism (as mentioned [here](https://github.com/flutter/flutter/issues/4890#issuecomment-407327749) in #4890). Flutter developers still find asset declaration difficult, and some opt-in approach would prevent asset declaration from having other side effects.

**Comment by pcornelissen** [comment]
it's not necessary to use switches for that, you could follow general solutions other frameworks usw and just use /foo/** for recursive resource folders

**Comment by EArminjon** [comment]
If we can use a syntax similar of the .gitignore one, it will be perfect.

**Comment by spydon** [comment]
I think the least confusing would be to use globs (just like the gitignore) so that it aligns with how it will work with the packages list under the `workspace` key (https://github.com/dart-lang/pub/issues/4391). That would also not change the behavior of any current apps.

**Comment by qeepcologne** [comment]
i am very desperate on this feature, especially if you need a lot of transformers, there is a lot of repetition.
and i have another wish to add a flavor variable e.g.
```
    - path: assets/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/login/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icons/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/flags/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/guide/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/profile/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/flavor1/
      flavors:
      - flavor1
      transformers:
        - package: vector_graphics_compiler
    - path: assets/flavor2/
      flavors:
      - flavor2
      transformers:
        - package: vector_graphics_compiler
    - path: assets/flavor3/
      flavors:
      - flavor3
      transformers:
        - package: vector_graphics_compiler
    - path: assets/flavor4/
      flavors:
      - flavor4
      transformers:
        - package: vector_graphics_compiler
```
=>
```
    - path: assets/global/**
      transformers:
        - package: vector_graphics_compiler
    - path: assets/$flavor/**
      transformers:
        - package: vector_graphics_compiler
```
