### ISSUE TITLE
[W10] SwapChain11.cpp:947 / Frame Acquisition Crash

### ISSUE THREAD

**Issue by b-will-c** [flutter/flutter#118906]
I have been noticing a fairly strange crash, coming seemingly out of nowhere, for the app I'm working on. Describing the overall functionality of it all feels somewhat pointless, as this bug appears at random, without any consistent ties to any particular screen or widget - which I can only assume has to do with this being a deeper problem with the Windows build itself, rather than any particular mess in the code from my part. 

After at least 30 minutes (and usually - well after 1.5/2.5 hours), the app simply stops responding, the overall repaints cease to happen, and in the console I can see the following:

```
ERR: SwapChain11.cpp:947 (present): Present failed: the D3D11 device was removed, HRESULT: 0x887A0006
4050
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
```

If I were to provide any ...

## Steps to Reproduce

... they would go along the lines of:

1. Execute `flutter run`
2. Do whatever / Hot reload / Hot restart
3. Get ready for the app to freeze in an ~hour or two, randomly

**Expected results:** 

Ideally, I'd expect the whole app _not_ to do this?

**Actual results:** 

Crashes keep happening - not always, yet often enough to make the overall experience fairly terrible.

I could understand if it, at the very least, came crashing down _completely_ - or silently reload in the background with a warning in the console, restarting the overall D3D11 / Skia rendering process. But like this?

And I have no clue whatsoever as to where I could even begin to sort it all out.

<details>
<summary>pubspec.yaml</summary>

```yaml
...

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  date_time_format: ^2.0.1
  
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.2
  uuid: ^3.0.7
  fast_immutable_collections: ^8.1.0
  copy_with_extension: ^4.0.0
  freezed_annotation: ^2.2.0
  path_provider: ^2.0.11
  popover: ^0.2.6+3
  scrollable_positioned_list: ^0.3.5
  anitex: ^3.0.1
  animated_text_kit: ^4.2.2
  flutter_fortune_wheel: ^1.2.0
  readmore: ^2.1.0
  circular_countdown_timer: ^0.2.2
  convex_bottom_bar: ^3.1.0+1
  page_transition: "^2.0.9"
  badges: ^2.0.3
  flutter_spinkit: ^5.1.0
  reorderables: ^0.5.1
  icons_plus: ^3.0.0
  animated_flip_counter: ^0.2.5
  animated_digit: ^3.2.1
  group_list_view: ^1.1.1
  assorted_layout_widgets: ^7.0.0
  cart_stepper: ^4.0.0
  flutter_quill: ^6.1.11
  auto_size_text: ^3.0.0
  custom_rich_text: ^0.0.2
  flutter_datetime_picker: ^1.5.1
  duration_picker: ^1.1.1
  url_launcher: ^6.1.7
  flutter_smart_dialog: ^4.8.0
  dropdown_textfield: ^1.0.7
  moving_average: ^0.3.0
  date_time_picker: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  copy_with_extension_gen: ^4.0.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4

...

```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2486], locale en-GB)
    • Flutter version 3.3.10 on channel stable at E:\Development\Flutter\3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\Programs\AndroidSDK
    • Platform android-30, build-tools 30.0.3
    • Java binary at: E:\Programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.21)
    • Visual Studio at E:\Development\VS\Community
    • Visual Studio Community 2019 version 16.11.33027.164
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
    • Android Studio at E:\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
