### ISSUE TITLE
pubspec.lock is ignored when upgrading to flutter 3.7.0

### ISSUE THREAD

**Issue by Jordan-Nelson** [flutter/flutter#119091]
## Steps to Reproduce

1. Install flutter 3.3.10
2. Create a project that has some dependencies which are pinned to a version that is not the latest. For example, if package foo has version 1.0.1 as the latest version, lock on 1.0.0.

pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter
  foo: ^1.0.0
```
pubspec.lock
```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  foo:
    dependency: "direct main"
    description:
      name: foo
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
```
3. Run `flutter pub get` and notice that the package version is NOT upgraded since there is a lock file.
3. Upgrade to flutter 3.7.0
4. Run  `flutter pub get` and notice that the package version IS upgraded because the lock file was totally regenerated and the old one was ignored.

**Expected results:** 

pubspec.lock should always be honored. 

**Actual results:** 

pubspec.lock is ignored when upgrading to flutter 3.7.0

**Comment by exaby73** [comment]
Hello @Jordan-Nelson. Following your steps, with the `go_router` package instead of `foo` since it's not null safe, I cannot reproduce the issue.

I generated a project with 3.3.10, ran `flutter pub add go_router:6.0.0` (latest version is 6.0.1). I then changed the version in `pubspec.yaml` from `go_router: 6.0.0` to `go_router: ^6.0.0`. Running `flutter pub get` in both verisons, 3.3.10 and 3.7.0 produces the same result in the lock file. Here's a snippet after running `flutter pub get` on 3.7.0:

```yaml
...
  go_router:
    dependency: "direct main"
    description:
      name: go_router
      sha256: "788a89932142b0059c319e3153e73308e0fc8bbab78e9a66b0128423090c4e01"
      url: "https://pub.dev"
    source: hosted
    version: "6.0.0"
...
```
