### ISSUE TITLE
Flutter 3.7.0 build apk Segmentation fault(11) 

### ISSUE THREAD

**Issue by ffamar** [flutter/flutter#119354]
Hello,
I get si_signo=Segmentation fault(11), si_code=1, si_addr=0x3 when I build my application (flutter build apk).
I have no issues in debug mode or with the previous flutter version 3.3.10 .
I have the same result on Windows.
I have no issues with simple application.
Please help me!

flutter doctor -v
```
[✓] Flutter (Channel stable, 3.7.0, on Linux Mint 20.3 5.4.0-137-generic, locale en_US.UTF-8)
    • Flutter version 3.7.0 on channel stable at /home/famar/Works/toolchain/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (4 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/famar/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/famar/Works/toolchain/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/famar/Works/toolchain/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.74.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • VIE L09 (mobile) • N9Q7N16425005134 • android-arm64  • Android 7.0 (API 24)
    • Linux (desktop)  • linux            • linux-x64      • Linux Mint 20.3 5.4.0-137-generic
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
dependencies:
```
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0   
  uuid: ^3.0.7
  flutter_speed_dial: 6.2.0
  badges: ^2.0.3
  path_provider: ^2.0.11
  provider: ^6.0.3
  flutter_easyloading: ^3.0.5
  sliding_up_panel: ^2.0.0+1
  flutter_reactive_ble: ^5.0.3
  permission_handler: ^10.0.0
  share_plus: ^4.0.10
  receive_sharing_intent: ^1.4.5
  sqflite: ^2.0.3
  path: ^1.8.1
  pdf: ^3.8.4
  open_file: ^3.2.1
  dio: ^4.0.6
  wakelock: ^0.6.2
  pinput: ^2.2.11
  flutter_barcode_scanner: ^2.0.0
  mqtt_client: ^9.7.4
  flex_color_picker: ^3.0.2
  expandable: ^5.0.1
  hive: ^2.2.3
  mutex: ^3.0.1
  date_time_picker: "^2.1.0"
  material_design_icons_flutter: ^6.0.7096
```

flutter build apk 
```
💪 Building with sound null safety 💪


===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x3
version=2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "linux_arm"
pid=38107, thread=-1, isolate_group=isolate(0x55eecc6c79d0), isolate=(nil)((nil))
os=linux, arch=arm, comp=no, sim=no
isolate_instructions=0, vm_instructions=0
Stack dump aborted because InitialRegisterCheck failed.

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x3
version=2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "linux_x64"
pid=38110, thread=-1, isolate_group=isolate(0x55e96dd5eaf0), isolate=(nil)((nil))
os=linux, arch=x64, comp=yes, sim=no
isolate_instructions=0, vm_instructions=0
Stack dump aborted because InitialRegisterCheck failed.

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x3
version=2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "linux_simarm64"
pid=38109, thread=-1, isolate_group=isolate(0x56207e55bc30), isolate=(nil)((nil))
os=linux, arch=arm64, comp=yes, sim=yes
isolate_instructions=0, vm_instructions=0
Stack dump aborted because InitialRegisterCheck failed.
Dart snapshot generator failed with exit code -6
Dart snapshot generator failed with exit code -6
Dart snapshot generator failed with exit code -6
Target android_aot_release_android-arm failed: Exception: AOT snapshotter exited with code -6
Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -6
Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -6


FAILURE: Build failed with an exception.

* Where:
Script '/home/famar/Works/toolchain/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1151

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/home/famar/Works/toolchain/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Running Gradle task 'assembleRelease'...                           30.0s
Gradle task assembleRelease failed with exit code 1

```
