### ISSUE TITLE
o implementation found for method getAll on channel plugins.flutter.io/shared_preferences_android)

### ISSUE THREAD

**Issue by abdoul-kader1** [flutter/flutter#119625]
impossible to use the shared_preferences api I get this error: No implementation found for method getAll on channel plugins.flutter.io/shared_preferences_android)

**Comment by abdoul-kader1** [comment]
I even read other repositories which had the same problem but with their solution provided I still encounter the same problem

**Comment by huycozy** [comment]
@abdoul-kader1 Does the issue happen when running [shared_preferences example](https://github.com/flutter/plugins/tree/main/packages/shared_preferences/shared_preferences/example)? 

When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

<details>
<summary>Issue Template</summary>

```
If you are looking for support, please check out our documentation
or consider asking a question on Stack Overflow:
- https://flutter.dev/
- https://api.flutter.dev/
- https://stackoverflow.com/questions/tagged/flutter?sort=frequent

If you have found a bug or if our documentation doesn't have an answer
to what you're looking for, then fill our the template below. Please read
our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports

Steps to Reproduce

Please tell us exactly how to reproduce the problem you are running into.

Please attach a small application (ideally just one main.dart file) that
reproduces the problem. You could use https://gist.github.com/ for this.

If the problem is with your application's rendering, then please attach
a screenshot and explain what the problem is.

1. ...
2. ...
3. ...


Please tell us which target platform(s) the problem occurs (Android / iOS / Web / macOS / Linux / Windows)
Which target OS version, for Web, browser, is the test system running?
Does the problem occur on emulator/simulator as well as on physical devices?

Target Platform:
Target OS version/browser:
Devices:

Run your application with `flutter run --verbose` and attach all the
log output below between the lines with the backticks. If there is an
exception, please see if the error message includes enough information
to explain how to solve the issue.

Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Finally, paste the output of running `flutter doctor -v` here.
```
</details>

**Comment by deckerst** [comment]
I get this issue when running tests (but not in my app).

Here's a minimal test (`Sample 1`):
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  setUpAll(() async {
    await SharedPreferences.getInstance();
  });

  test('some test', () async {
    expect(1, 1);
  });
}
```

`Sample 1` worked fine with `Flutter v3.3.10` and `shared_preferences v2.0.16`.
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 22.10 5.19.0-29-generic, locale en_US.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/tibo/code/aves/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (7 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/tibo/Android/Sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.6
    • cmake version 3.24.2
    • ninja version 1.11.0
    • pkg-config version 0.29.2
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 72.0.1
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • SM G970N (mobile) • R39M4001Z1M • android-arm64 • Android 12 (API 31)
    • Linux (desktop)   • linux       • linux-x64     • Ubuntu 22.10 5.19.0-29-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>

<details>
<summary>pubspec.lock excerpt for shared_preferences versions</summary>

```
  shared_preferences:
    dependency: "direct main"
    description:
      name: shared_preferences
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.16"
  shared_preferences_android:
    dependency: "direct main"
    description:
      name: shared_preferences_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.14"
  shared_preferences_foundation:
    dependency: "direct main"
    description:
      name: shared_preferences_foundation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  shared_preferences_linux:
    dependency: transitive
    description:
      name: shared_preferences_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
  shared_preferences_platform_interface:
    dependency: transitive
    description:
      name: shared_preferences_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  shared_preferences_web:
    dependency: transitive
    description:
      name: shared_preferences_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  shared_preferences_windows:
    dependency: transitive
    description:
      name: shared_preferences_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
```
</details>

But `Sample 1` fails with `Flutter v3.7.1` and `shared_preferences v2.0.17` with the following issue:
```
Binding has not yet been initialized.
The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.
```

Addressing this issue, here's `Sample 2`:
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  setUpAll(() async {
    TestWidgetsFlutterBinding.ensureInitialized();
    await SharedPreferences.getInstance();
  });

  test('some test', () async {
    expect(1, 1);
  });
}
```

But `Sample 2` also fails with `Flutter v3.7.1` and `shared_preferences v2.0.17` with the following issue:
```
dart:async                                                _Completer.completeError
package:shared_preferences/shared_preferences.dart 38:19  SharedPreferences.getInstance
===== asynchronous gap ===========================
dart:async                                                _CustomZone.registerBinaryCallback
package:shared_preferences/shared_preferences.dart 33:13  SharedPreferences.getInstance
test/model/shared_pref_test.dart 9:29                     main.<fn>

MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.1, on Ubuntu 22.10 5.19.0-29-generic, locale en_US.UTF-8)
    • Flutter version 3.7.1 on channel stable at /home/tibo/code/aves/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (25 hours ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/tibo/Android/Sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.6
    • cmake version 3.24.2
    • ninja version 1.11.0
    • pkg-config version 0.29.2
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 72.0.1
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • SM G970N (mobile) • R39M4001Z1M • android-arm64 • Android 12 (API 31)
    • Linux (desktop)   • linux       • linux-x64     • Ubuntu 22.10 5.19.0-29-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>

<details>
<summary>pubspec.lock excerpt for shared_preferences versions</summary>

```
  shared_preferences:
    dependency: "direct main"
    description:
      name: shared_preferences
      sha256: "5949029e70abe87f75cfe59d17bf5c397619c4b74a099b10116baeb34786fad9"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.17"
  shared_preferences_android:
    dependency: transitive
    description:
      name: shared_preferences_android
      sha256: "955e9736a12ba776bdd261cf030232b30eadfcd9c79b32a3250dd4a494e8c8f7"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.15"
  shared_preferences_foundation:
    dependency: transitive
    description:
      name: shared_preferences_foundation
      sha256: "2b55c18636a4edc529fa5cd44c03d3f3100c00513f518c5127c951978efcccd0"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.3"
  shared_preferences_linux:
    dependency: transitive
    description:
      name: shared_preferences_linux
      sha256: f8ea038aa6da37090093974ebdcf4397010605fd2ff65c37a66f9d28394cb874
      url: "https://pub.dev"
    source: hosted
    version: "2.1.3"
  shared_preferences_platform_interface:
    dependency: transitive
    description:
      name: shared_preferences_platform_interface
      sha256: da9431745ede5ece47bc26d5d73a9d3c6936ef6945c101a5aca46f62e52c1cf3
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
  shared_preferences_web:
    dependency: transitive
    description:
      name: shared_preferences_web
      sha256: a4b5bc37fe1b368bbc81f953197d55e12f49d0296e7e412dfe2d2d77d6929958
      url: "https://pub.dev"
    source: hosted
    version: "2.0.4"
  shared_preferences_windows:
    dependency: transitive
    description:
      name: shared_preferences_windows
      sha256: "5eaf05ae77658d3521d0e993ede1af962d4b326cd2153d312df716dc250f00c9"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.3"
```
</details>
