### ISSUE TITLE
framed view for testWidgets

### ISSUE THREAD

**Issue by nilgaar** [flutter/flutter#119707]
When running tests with _flutter_test_ `testWidgets`, the emulator doesn't go full screen and the view is framed.

MacOS Simulator Version:

> Version 14.2 (986.5)
> SimulatorKit 627
> CoreSimulator 857.14

## Steps to Reproduce
Use sample code and run `main()` in myTests.dart

**Expected results:** View of tests and run look the same.

**Actual results:**
Widget test:
<img src="https://user-images.githubusercontent.com/73447234/216064763-2dff90ea-3911-424a-b968-f97c18139367.png" width=50% height=50%>

Normal run:
<img src="https://user-images.githubusercontent.com/73447234/216065127-cc41cb72-31e1-421e-94db-ef6ab05ba855.png" width=50% height=50%>

<details>
<summary>Code sample</summary>

**myTests.dart**
```dart
import 'package:arrimat_f/screens/shared/forgot_pass.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('MyWidget has a title and message', (tester) async {
    final SemanticsHandle handle = tester.ensureSemantics();
    await tester.pumpWidget(MaterialApp(
      home: ForgotPassword(),
      theme: ThemeData(
          colorSchemeSeed: const Color(0xff6750a4), useMaterial3: true),
    ));
    await expectLater(tester, meetsGuideline(androidTapTargetGuideline));
    handle.dispose();
  });
}
```

**ForgotPassword**
```dart
import 'package:flutter/material.dart';

class ForgotPassword extends StatelessWidget {
  const ForgotPassword({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(
      child: Padding(
          padding: const EdgeInsets.only(bottom: 20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              Padding(
                padding: const EdgeInsets.all(20.0),
                child: Padding(
                  padding: const EdgeInsets.only(top: 50),
                  child: Row(children: [
                    Padding(
                      padding: const EdgeInsets.only(left: 20),
                      child: GestureDetector(
                        onTap: () => Navigator.pop(context),
                        child: const Icon(
                          Icons.arrow_back_ios_new,
                          color: Color.fromRGBO(95, 46, 226, 1),
                        ),
                      ),
                    ),
                    const Expanded(
                      child: Padding(
                        padding: EdgeInsets.only(right: 40, top: 5),
                        child: Text('Forgotten password',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                                color: Color.fromRGBO(96, 46, 226, 1),
                                fontFamily: 'Gordita',
                                fontSize: 25,
                                letterSpacing: 0
                                fontWeight: FontWeight.bold,
                                height: 1)),
                      ),
                    ),
                  ]),
                ),
              ),
              const SizedBox(
                height: 30,
              ),
              const Padding(
                padding: EdgeInsets.symmetric(horizontal: 45),
                child: Text(
                  "Enter the e-mail you used to create your account. We will send you a password reset code.",
                  style: TextStyle(),
                  textAlign: TextAlign.justify,
                ),
              )
            ],
          )),
    ));
  }
}
```
**pubspec.yaml**
```yaml
name: arrimat_f
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line
  #intl_translation: ^0.18.0
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.9
  geocoding: ^2.0.4
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.2.0
  firebase_crashlytics: ^3.0.7
  google_sign_in: ^5.4.2
  flutter_riverpod: ^2.1.2
  firebase_ui_auth: ^1.1.5
  sign_in_with_apple: ^4.3.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  fonts:
    - family: Gordita
      fonts:
        - asset: assets/Gordita Bold.otf
          weight: 700
        - asset: assets/Gordita Regular.otf
          weight: 400
        - asset: assets/Gordita Medium.otf
          style: normal

  uses-material-design: true
  assets:
    - assets/barri2.jpg
    - assets/google.svg
    - assets/facebook.svg
    - assets/apple.svg
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
