### ISSUE TITLE
Allow .ci.yaml `platform_properties` to specify timeout, recipe, presubmit, runIf, etc. to be inherited by tasks

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#119962]
For example, in https://github.com/flutter/flutter/pull/119871 I added a `platform_property` for macOS benchmarks:

```yml
mac_benchmark:
    properties:
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      device_type: none
      mac_model: "Macmini8,1"
```
Per the [proto definition](https://flutter.googlesource.com/infra/+/refs/heads/main/config/lib/ci_yaml/scheduler.proto) I was only able to add `properties` and `dimensions`, so every `mac_platform` task needed to specify `presubmit`, `recipe`, and `timeout`, which were all identical:

```yml
  - name: Mac_benchmark basic_material_app_macos__compile
    presubmit: false
    recipe: devicelab/devicelab_drone
    timeout: 60
    properties:
      task_name: basic_material_app_macos__compile
```

Ideally this could be pushed up to the `platform_property` to deduplicate this logic, and allow us to update it in one place:
```yml
mac_benchmark:
    presubmit: false
    recipe: devicelab/devicelab_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      device_type: none
      mac_model: "Macmini8,1"
...
  - name: Mac_benchmark basic_material_app_macos__compile
    properties:
      task_name: basic_material_app_macos__compile
```
