### ISSUE TITLE
I can't deploy my flutter project.

### ISSUE THREAD

**Issue by MH0386** [flutter/flutter#120011]
```
name: personal_website

on:
  push:
    branches: [ "master", "gh-pages" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build/web/index.html
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
            baseHref: /MH0386.github.io/build/web/
```
what is the problem here?
