### ISSUE TITLE
How could we put a module into flutter application (something wrong with assets)

### ISSUE THREAD

**Issue by lihaozhe-alexis** [flutter/flutter#120282]
Dear Sir

I wrote a flutter app by using [ flutter application ], and then I want to move most of its logic into a [ flutter module ]. Since it will be possible for me to use an android app which is embedded with flutter module. However, most of the time I still want to use the flutter app for tuning, meaning I also want to put the module into my flutter application.

so, now the projects in folder are like this (same level)
- parent folder
    - flutter_app
      - assets
          // nothing is here
      - pubspec.yaml
      - lib
        - main.dart.   `runApp(MyApp());`
    - flutter_module
      - assets
        - images
          - xxx.jpg 
      - pubspec.yaml
      - lib
        // I wrote all my code here, in a dart file, 
        `class MyApp {   ...MaterialApp inside...   }  `
       `child: Image.asset("assets/images/xxx.jpg");`
    
**code in flutter_app's pubspec.yaml**
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_module:
    path: ../flutter_module
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # assets:
```
**code in flutter_module's pubspec.yaml**
```

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
       ... something else ...
       ... something else ...
       ... something else ...
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
```

When I run the flutter_module itself, everything was ok.
When I run flutter_app, most of the code was ok, however, when there was an image, Oh no !!!

**Unable to load asset: assets/images/xxx.jpg.**
