### ISSUE TITLE
[web] flutter web app works in debug mode but does not work in release mode

### ISSUE THREAD

**Issue by ZdenekKrcal** [flutter/flutter#120927]
When Im building app everything works great, but when I want to build release I can see only white screen.

Im building app in Ubuntu. (WSL 2 in windows)

I have never had problem like that and Im building for long time in that environment.

I can see only problem in web browser in console:

```
VM13:2 Uncaught (in promise) TypeError: Failed to resolve module specifier 'Instance of 'TrustedScriptURL''
    at window.ff_trigger_firebase_core (<anonymous>:2:18)
    at tp.w8 (js_patch.dart:217:12)
    at firebase_core_web.dart:140:13
    at bnY.a (async_patch.dart:317:19)
    at bnY.$2 (async_patch.dart:342:23)
    at Object.u (async_patch.dart:247:3)
    at aHS.b_Z (firebase_core_web.dart:106:26)
    at aHS.Nx (firebase_core_web.dart:106:26)
    at aHU.$1 (firebase_core_web.dart:169:16)
    at bx.u (iterable.dart:393:20)
VM14:2 Uncaught (in promise) TypeError: Failed to resolve module specifier 'Instance of 'TrustedScriptURL''
    at window.ff_trigger_firebase_app_check (<anonymous>:2:18)
    at tp.w8 (js_patch.dart:217:12)
    at firebase_core_web.dart:140:13
    at bnY.a (async_patch.dart:317:19)
    at bnY.$2 (async_patch.dart:342:23)
    at Object.u (async_patch.dart:247:3)
    at aHS.b_Z (firebase_core_web.dart:106:26)
    at aHS.Nx (firebase_core_web.dart:106:26)
    at aHU.$1 (firebase_core_web.dart:169:16)
    at bx.u (iterable.dart:393:20)
VM15:2 Uncaught (in promise) TypeError: Failed to resolve module specifier 'Instance of 'TrustedScriptURL''
    at window.ff_trigger_firebase_remote_config (<anonymous>:2:18)
    at tp.w8 (js_patch.dart:217:12)
    at firebase_core_web.dart:140:13
    at bnY.a (async_patch.dart:317:19)
    at bnY.$2 (async_patch.dart:342:23)
    at Object.u (async_patch.dart:247:3)
    at aHS.b_Z (firebase_core_web.dart:106:26)
    at aHS.Nx (firebase_core_web.dart:106:26)
    at aHU.$1 (firebase_core_web.dart:169:16)
    at bx.u (iterable.dart:393:20)
VM16:2 Uncaught (in promise) TypeError: Failed to resolve module specifier 'Instance of 'TrustedScriptURL''
    at window.ff_trigger_firebase_firestore (<anonymous>:2:18)
    at tp.w8 (js_patch.dart:217:12)
    at firebase_core_web.dart:140:13
    at bnY.a (async_patch.dart:317:19)
    at bnY.$2 (async_patch.dart:342:23)
    at Object.u (async_patch.dart:247:3)
    at aHS.b_Z (firebase_core_web.dart:106:26)
    at aHS.Nx (firebase_core_web.dart:106:26)
    at aHU.$1 (firebase_core_web.dart:169:16)
    at bx.u (iterable.dart:393:20)
VM17:2 Uncaught (in promise) TypeError: Failed to resolve module specifier 'Instance of 'TrustedScriptURL''
    at window.ff_trigger_firebase_auth (<anonymous>:2:18)
    at tp.w8 (js_patch.dart:217:12)
    at firebase_core_web.dart:140:13
    at bnY.a (async_patch.dart:317:19)
    at bnY.$2 (async_patch.dart:342:23)
    at Object.u (async_patch.dart:247:3)
    at aHS.b_Z (firebase_core_web.dart:106:26)
    at aHS.Nx (firebase_core_web.dart:106:26)
    at aHU.$1 (firebase_core_web.dart:169:16)
    at bx.u (iterable.dart:393:20)
VM18:2 Uncaught (in promise) TypeError: Failed to resolve module specifier 'Instance of 'TrustedScriptURL''
    at window.ff_trigger_firebase_storage (<anonymous>:2:18)
    at tp.w8 (js_patch.dart:217:12)
    at firebase_core_web.dart:140:13
    at bnY.a (async_patch.dart:317:19)
    at bnY.$2 (async_patch.dart:342:23)
    at Object.u (async_patch.dart:247:3)
    at aHS.b_Z (firebase_core_web.dart:106:26)
    at aHS.Nx (firebase_core_web.dart:106:26)
    at aHU.$1 (firebase_core_web.dart:169:16)
    at bx.u (iterable.dart:393:20)
```

flutter run -d chrome --release --verbose

```
[   +8 ms] executing: uname -m
[   +5 ms] Exit code 0 from: uname -m
[        ] x86_64
[        ] executing: [/home/zdenek/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9944297138845a94256f1cf37beb88ff9a8e811a
[        ] executing: [/home/zdenek/snap/flutter/common/flutter/] git tag --points-at 9944297138845a94256f1cf37beb88ff9a8e811a
[  +10 ms] Exit code 0 from: git tag --points-at 9944297138845a94256f1cf37beb88ff9a8e811a
[        ] 3.7.3
[   +8 ms] executing: [/home/zdenek/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/home/zdenek/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +14 ms] executing: [/home/zdenek/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +25 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +39 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] Skipping pub get: version match.
[  +29 ms] Found plugin cloud_firestore at /home/zdenek/.pub-cache/hosted/pub.dev/cloud_firestore-4.4.1/
[   +3 ms] Found plugin cloud_firestore_web at /home/zdenek/.pub-cache/hosted/pub.dev/cloud_firestore_web-3.3.1/
[   +5 ms] Found plugin device_info_plus at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus-4.1.3/
[        ] Found plugin device_info_plus_linux at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_linux-3.0.0/
[   +1 ms] Found plugin device_info_plus_macos at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_macos-3.0.0/
[   +1 ms] Found plugin device_info_plus_web at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_web-3.0.0/
[   +3 ms] Found plugin device_info_plus_windows at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_windows-4.1.0/
[   +3 ms] Found plugin file_picker at /home/zdenek/.pub-cache/hosted/pub.dev/file_picker-5.2.5/
[        ] Found plugin firebase_auth at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_auth-4.2.7/
[   +1 ms] Found plugin firebase_auth_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_auth_web-5.2.6/
[        ] Found plugin firebase_core at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_core-2.6.0/
[        ] Found plugin firebase_core_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_core_web-2.2.0/
[        ] Found plugin firebase_storage at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_storage-11.0.12/
[        ] Found plugin firebase_storage_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_storage_web-3.3.21/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at /home/zdenek/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.7/
[   +4 ms] Found plugin image_picker at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker-0.8.6+1/
[        ] Found plugin image_picker_android at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_android-0.8.5+6/
[        ] Found plugin image_picker_for_web at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_for_web-2.1.10/
[        ] Found plugin image_picker_ios at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.6+7/
[   +2 ms] Found plugin location at /home/zdenek/.pub-cache/hosted/pub.dev/location-5.0.0-dev.8/
[        ] Found plugin location_android at /home/zdenek/.pub-cache/hosted/pub.dev/location_android-5.0.0-dev.3/
[        ] Found plugin location_ios at /home/zdenek/.pub-cache/hosted/pub.dev/location_ios-5.0.0-dev.4/
[        ] Found plugin location_macos at /home/zdenek/.pub-cache/hosted/pub.dev/location_macos-5.0.0-dev.3/
[        ] Found plugin location_web at /home/zdenek/.pub-cache/hosted/pub.dev/location_web-5.0.0-dev.3/
[   +2 ms] Found plugin path_provider at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider-2.0.12/
[        ] Found plugin path_provider_android at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_android-2.0.22/
[        ] Found plugin path_provider_foundation at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_foundation-2.1.1/
[        ] Found plugin path_provider_linux at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.8/
[        ] Found plugin path_provider_windows at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_windows-2.1.3/
[   +1 ms] Found plugin pdfx at /home/zdenek/.pub-cache/hosted/pub.dev/pdfx-2.3.0/
[  +45 ms] Found plugin cloud_firestore at /home/zdenek/.pub-cache/hosted/pub.dev/cloud_firestore-4.4.1/
[   +1 ms] Found plugin cloud_firestore_web at /home/zdenek/.pub-cache/hosted/pub.dev/cloud_firestore_web-3.3.1/
[   +1 ms] Found plugin device_info_plus at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus-4.1.3/
[        ] Found plugin device_info_plus_linux at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_linux-3.0.0/
[        ] Found plugin device_info_plus_macos at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_macos-3.0.0/
[        ] Found plugin device_info_plus_web at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_web-3.0.0/
[        ] Found plugin device_info_plus_windows at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_windows-4.1.0/
[   +1 ms] Found plugin file_picker at /home/zdenek/.pub-cache/hosted/pub.dev/file_picker-5.2.5/
[        ] Found plugin firebase_auth at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_auth-4.2.7/
[        ] Found plugin firebase_auth_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_auth_web-5.2.6/
[        ] Found plugin firebase_core at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_core-2.6.0/
[        ] Found plugin firebase_core_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_core_web-2.2.0/
[        ] Found plugin firebase_storage at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_storage-11.0.12/
[        ] Found plugin firebase_storage_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_storage_web-3.3.21/
[        ] Found plugin flutter_plugin_android_lifecycle at /home/zdenek/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.7/
[   +1 ms] Found plugin image_picker at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker-0.8.6+1/
[        ] Found plugin image_picker_android at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_android-0.8.5+6/
[        ] Found plugin image_picker_for_web at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_for_web-2.1.10/
[        ] Found plugin image_picker_ios at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.6+7/
[   +1 ms] Found plugin location at /home/zdenek/.pub-cache/hosted/pub.dev/location-5.0.0-dev.8/
[        ] Found plugin location_android at /home/zdenek/.pub-cache/hosted/pub.dev/location_android-5.0.0-dev.3/
[        ] Found plugin location_ios at /home/zdenek/.pub-cache/hosted/pub.dev/location_ios-5.0.0-dev.4/
[        ] Found plugin location_macos at /home/zdenek/.pub-cache/hosted/pub.dev/location_macos-5.0.0-dev.3/
[        ] Found plugin location_web at /home/zdenek/.pub-cache/hosted/pub.dev/location_web-5.0.0-dev.3/
[   +3 ms] Found plugin path_provider at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider-2.0.12/
[        ] Found plugin path_provider_android at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_android-2.0.22/
[        ] Found plugin path_provider_foundation at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_foundation-2.1.1/
[        ] Found plugin path_provider_linux at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.8/
[        ] Found plugin path_provider_windows at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_windows-2.1.3/
[        ] Found plugin pdfx at /home/zdenek/.pub-cache/hosted/pub.dev/pdfx-2.3.0/
[  +21 ms] Found plugin cloud_firestore at /home/zdenek/.pub-cache/hosted/pub.dev/cloud_firestore-4.4.1/
[        ] Found plugin cloud_firestore_web at /home/zdenek/.pub-cache/hosted/pub.dev/cloud_firestore_web-3.3.1/
[   +2 ms] Found plugin device_info_plus at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus-4.1.3/
[        ] Found plugin device_info_plus_linux at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_linux-3.0.0/
[        ] Found plugin device_info_plus_macos at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_macos-3.0.0/
[        ] Found plugin device_info_plus_web at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_web-3.0.0/
[        ] Found plugin device_info_plus_windows at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_windows-4.1.0/
[   +1 ms] Found plugin file_picker at /home/zdenek/.pub-cache/hosted/pub.dev/file_picker-5.2.5/
[        ] Found plugin firebase_auth at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_auth-4.2.7/
[        ] Found plugin firebase_auth_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_auth_web-5.2.6/
[        ] Found plugin firebase_core at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_core-2.6.0/
[        ] Found plugin firebase_core_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_core_web-2.2.0/
[        ] Found plugin firebase_storage at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_storage-11.0.12/
[        ] Found plugin firebase_storage_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_storage_web-3.3.21/
[        ] Found plugin flutter_plugin_android_lifecycle at /home/zdenek/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.7/
[   +1 ms] Found plugin image_picker at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker-0.8.6+1/
[        ] Found plugin image_picker_android at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_android-0.8.5+6/
[        ] Found plugin image_picker_for_web at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_for_web-2.1.10/
[        ] Found plugin image_picker_ios at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.6+7/
[   +1 ms] Found plugin location at /home/zdenek/.pub-cache/hosted/pub.dev/location-5.0.0-dev.8/
[        ] Found plugin location_android at /home/zdenek/.pub-cache/hosted/pub.dev/location_android-5.0.0-dev.3/
[        ] Found plugin location_ios at /home/zdenek/.pub-cache/hosted/pub.dev/location_ios-5.0.0-dev.4/
[        ] Found plugin location_macos at /home/zdenek/.pub-cache/hosted/pub.dev/location_macos-5.0.0-dev.3/
[        ] Found plugin location_web at /home/zdenek/.pub-cache/hosted/pub.dev/location_web-5.0.0-dev.3/
[   +1 ms] Found plugin path_provider at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider-2.0.12/
[        ] Found plugin path_provider_android at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_android-2.0.22/
[        ] Found plugin path_provider_foundation at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_foundation-2.1.1/
[        ] Found plugin path_provider_linux at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.8/
[   +1 ms] Found plugin path_provider_windows at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_windows-2.1.3/
[        ] Found plugin pdfx at /home/zdenek/.pub-cache/hosted/pub.dev/pdfx-2.3.0/
[  +38 ms] Generating /home/zdenek/app_projects/easybau_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +153 ms] Launching lib/main.dart on Chrome in release mode...
[  +37 ms] Found plugin cloud_firestore at /home/zdenek/.pub-cache/hosted/pub.dev/cloud_firestore-4.4.1/
[        ] Found plugin cloud_firestore_web at /home/zdenek/.pub-cache/hosted/pub.dev/cloud_firestore_web-3.3.1/
[   +1 ms] Found plugin device_info_plus at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus-4.1.3/
[        ] Found plugin device_info_plus_linux at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_linux-3.0.0/
[        ] Found plugin device_info_plus_macos at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_macos-3.0.0/
[        ] Found plugin device_info_plus_web at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_web-3.0.0/
[        ] Found plugin device_info_plus_windows at /home/zdenek/.pub-cache/hosted/pub.dev/device_info_plus_windows-4.1.0/
[        ] Found plugin file_picker at /home/zdenek/.pub-cache/hosted/pub.dev/file_picker-5.2.5/
[        ] Found plugin firebase_auth at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_auth-4.2.7/
[        ] Found plugin firebase_auth_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_auth_web-5.2.6/
[        ] Found plugin firebase_core at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_core-2.6.0/
[   +1 ms] Found plugin firebase_core_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_core_web-2.2.0/
[        ] Found plugin firebase_storage at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_storage-11.0.12/
[        ] Found plugin firebase_storage_web at /home/zdenek/.pub-cache/hosted/pub.dev/firebase_storage_web-3.3.21/
[        ] Found plugin flutter_plugin_android_lifecycle at /home/zdenek/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.7/
[   +1 ms] Found plugin image_picker at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker-0.8.6+1/
[        ] Found plugin image_picker_android at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_android-0.8.5+6/
[        ] Found plugin image_picker_for_web at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_for_web-2.1.10/
[        ] Found plugin image_picker_ios at /home/zdenek/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.6+7/
[   +1 ms] Found plugin location at /home/zdenek/.pub-cache/hosted/pub.dev/location-5.0.0-dev.8/
[        ] Found plugin location_android at /home/zdenek/.pub-cache/hosted/pub.dev/location_android-5.0.0-dev.3/
[        ] Found plugin location_ios at /home/zdenek/.pub-cache/hosted/pub.dev/location_ios-5.0.0-dev.4/
[        ] Found plugin location_macos at /home/zdenek/.pub-cache/hosted/pub.dev/location_macos-5.0.0-dev.3/
[        ] Found plugin location_web at /home/zdenek/.pub-cache/hosted/pub.dev/location_web-5.0.0-dev.3/
[   +1 ms] Found plugin path_provider at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider-2.0.12/
[        ] Found plugin path_provider_android at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_android-2.0.22/
[        ] Found plugin path_provider_foundation at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_foundation-2.1.1/
[        ] Found plugin path_provider_linux at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.8/
[        ] Found plugin path_provider_windows at /home/zdenek/.pub-cache/hosted/pub.dev/path_provider_windows-2.1.3/
[        ] Found plugin pdfx at /home/zdenek/.pub-cache/hosted/pub.dev/pdfx-2.3.0/
[   +6 ms] generated_plugin_registrant.dart not found. Skipping.
[        ] Compiling lib/main.dart for the Web...
[   +2 ms] Initializing file store
[   +5 ms] Done initializing file store
[  +47 ms] Skipping target: web_entrypoint
[   +1 ms] Skipping target: gen_localizations
[        ] Skipping target: web_static_assets
[ +255 ms] Skipping target: dart2js
[   +8 ms] invalidated build due to missing files: /home/zdenek/app_projects/easybau_app/DOES_NOT_EXIST_RERUN_FOR_WILDCARD365184755
[  +51 ms] web_release_bundle: Starting due to {InvalidatedReasonKind.inputMissing: The following inputs were missing:
/home/zdenek/app_projects/easybau_app/DOES_NOT_EXIST_RERUN_FOR_WILDCARD365184755}
[  +57 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +11 ms] web_release_bundle: Complete
[ +157 ms] web_service_worker: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
build/web/index.html}
[ +151 ms] web_service_worker: Complete
[        ] Persisting file store
[   +6 ms] Done persisting file store
[  +17 ms] Compiling lib/main.dart for the Web... (completed in 768ms)
[  +98 ms] Using Chromium 110.0.5481.77 snap

[   +1 ms] executing: uname -m
[   +1 ms] Exit code 0 from: uname -m
[        ] x86_64
[ +188 ms] [CHROME]: 
[        ] [CHROME]: DevTools listening on ws://127.0.0.1:39701/devtools/browser/fbb4e8cc-b4f6-46cd-a7db-e80053edab8c
[  +58 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".

```

flutter doctor -v

```
[✓] Flutter (Channel stable, 3.7.3, on Ubuntu 22.04.1 LTS 5.15.79.1-microsoft-standard-WSL2, locale C.UTF-8)
    • Flutter version 3.7.3 on channel stable at /home/zdenek/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (8 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/zdenek/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.79.1-microsoft-standard-WSL2
    • Chrome (web)    • chrome • web-javascript • Chromium 110.0.5481.77 snap

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

flutter analyze

```
Analyzing easybau_app...                                                
No issues found! (ran in 2.2s)
```

My pubspec.yaml
```yaml
name: easybau
description: App for managing projects.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  go_router: ^6.0.0
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.6
  http: ^0.13.5
  intl: ^0.17.0
  pluto_grid: ^5.4.9
  dropdown_search: ^5.0.3
  image_picker: ^0.8.6
  open_street_map_search_and_pick: ^0.0.15
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.3
  cloud_firestore: ^4.1.0
  location: ^5.0.0-dev.8
  pdfx: ^2.3.0
  pdf: ^3.9.0
  easy_image_viewer: ^1.2.0
  mime: ^1.0.4
  file_picker: ^5.2.5
  safe_area_insets: ^0.1.2
  path_provider: ^2.0.12
  hand_signature: ^3.0.0
  flutter_svg: ^2.0.1

# dependency_overrides:
#   intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  build_runner: ^2.3.2
  riverpod_generator: ^1.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 700

```
