### ISSUE TITLE
`flutter build apk` produces different artifacts on Windows vs Linux and Linux artifact does not open on Android

### ISSUE THREAD

**Issue by kNoAPP** [flutter/flutter#121052]
**Background**
I have a GitHub Actions runner that produces an .apk artifact when code is pushed to develop. The action runs without errors. But when installing the .apk either directly to my Android device or via Firebase's app distribution (used in the GitHub Action), the app does not open. The install is successful, just the app doesn't open and instead hangs on the app icon splash screen.

Downloading the .apk from Firebase or GitHub to my Windows machine and installing via adb will also produce the same behavior.

However, producing the .apk from my Windows machine using `flutter build apk` and installing via adb works successfully. Running `flutter run` also is successful. In these cases, the app opens just fine.

I compared the file sizes of the GitHub Actions artifact and my Windows artifact, and they are off by 391 bytes. I compared the sha256 hashes and these are different. So it would seem there is a very minute difference between the two .apk files.
`829E4C9B2F942C634518E97266B8186596E31730106005B0E11264F96B83887F`
vs.
`3CD7A6BD4E1DFB6401B4B674CC0D658D07C841DA2F1814DB88084521BDEB957E`

This issue does not impact .aab app bundles. Even when created on Linux, .aab will install correctly to Android and can the app can then be opened normally.

## Steps to Reproduce
1. Build the default template Flutter application using GitHub Actions. Provided is an example taken from my repository. The decrypt secrets step installs an Android keystore and references it inside the `key.properties` file. This enables the GitHub Actions runner to create a release version of the app.
```
  pack-android:
    runs-on: ubuntu-latest
    needs: [semver]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Populate secrets
        run: ./decrypt-secrets.sh "$SECRETS_PASSPHRASE"
        env:
          SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
      - name: Build android
        run: |
          cd app
          flutter build apk --dart-define=env=develop --build-name ${{ needs.semver.outputs.version }} --build-number ${{ needs.semver.outputs.increment }}
          cd ../
          mv app/build/app/outputs/flutter-apk/app-release.apk android_app.apk
      - name: Android - Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: android_app.apk
          path: android_app.apk
          retention-days: 7
```
2. Install the produced apk directly on Android (I used a Pixel 6 Pro).
3. Try to open the apk

**Expected results:**
The apk opens and becomes interactive

**Actual results:** 
The apk hangs on the Flutter logo and does not open.

<details>
<summary>Code sample</summary>

```dart
void main() async {
  if (kIsWeb) {
    return await _startup();
  }

  // Catch any uncaught or buried Flutter exceptions. Not supported on web.
  runZonedGuarded<Future<void>>(() async {
    _startup();
  }, (error, stack) => FirebaseCrashlytics.instance.recordError(error, stack));
}

Future<void> _startup() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: () {
      switch (env) {
        // Defining use of the emulator is done below. The envLocalhost
        // definition isn't important here so just point at develop.
        case envLocalhost:
        case envDevelop:
          return DevelopFirebaseOptions.currentPlatform;
        case envProduction:
        default:
          return ProductionFirebaseOptions.currentPlatform;
      }
    }.call(),
  );

  // Disable logging and app check if we're actively developing the app.
  // There's no need to poison our release data pool or verify our app.

  if (env != envLocalhost) {
    await FirebaseAppCheck.instance.activate(
      webRecaptchaSiteKey: webRecaptchaSiteKey,

      // If you're running in debug mode, but trying to test production, you'll
      // need to grab the debug secret from console out and paste it into
      // the Firebase Console to whitelist your access:
      // `Enter this debug secret into the allow list in the Firebase Console
      // for your project: <secret>`
      // https://firebase.google.com/docs/app-check/android/debug-provider#emulator
      //
      // cspell:disable-next-line
      // Debug token for reference: eyJlcnJvciI6IlVOS05PV05fRVJST1IifQ==
      //
      // https://github.com/firebase/flutterfire/discussions/7998#discussioncomment-4867193
      androidProvider:
          kDebugMode ? AndroidProvider.debug : AndroidProvider.playIntegrity,
    );
    await FirebaseAppCheck.instance.setTokenAutoRefreshEnabled(true);
  }

  if (!kIsWeb) {
    // https://firebase.flutter.dev/docs/crashlytics/usage
    final firebaseCrashlytics = FirebaseCrashlytics.instance;

    await firebaseCrashlytics.setCrashlyticsCollectionEnabled(!kDebugMode);

    // Catch all uncaught errors and report them to FirebaseCrashlytics.
    FlutterError.onError = firebaseCrashlytics.recordFlutterError;
  }

  final firebaseAnalytics = FirebaseAnalytics.instance;
  await firebaseAnalytics.setAnalyticsCollectionEnabled(!kDebugMode);

  // FirebasePerformance firebasePerformance = FirebasePerformance.instance;
  // await firebasePerformance.setPerformanceCollectionEnabled(!kDebugMode);

  usePathUrlStrategy();

  // The last Firebase initialization action should be to check if we're running
  // in debug mode, and if so, use the Firebase emulators instead of the
  // production database.
  if (env == envLocalhost) {
    // You may need to override this line with an ip address pointing to your
    // local machine. If using an Android emulator, note that localhost must be
    // mapped to '10.0.2.2'. Flutter should do that automatically for you,
    // though.
    const host = 'localhost';

    FirebaseAuth.instance.useAuthEmulator(host, 9099);
    FirebaseFirestore.instance.useFirestoreEmulator(host, 8080);
    FirebaseFirestore.instance.clearPersistence();
    FirebaseFunctions.instance.useFunctionsEmulator(host, 5001);
  }

  runApp(const MyApp());
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing app...                                                        
No issues found! (ran in 51.5s)
```

```
PS C:\flutter> flutter doctor -v
[✓] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22621.1194], locale en-US)
    • Flutter version 3.7.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 9944297138 (10 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\alden\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.23)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33214.272
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.1)
    • VS Code at C:\Users\alden\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • Pixel 6 Pro (mobile) • 192.168.86.125:41791 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)    • windows              • windows-x64    • Microsoft Windows [Version 10.0.22621.1194]
    • Chrome (web)         • chrome               • web-javascript • Google Chrome 110.0.5481.104
    • Edge (web)           • edge                 • web-javascript • Microsoft Edge 109.0.1518.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
