### ISSUE TITLE
Conflicts

### ISSUE THREAD

**Issue by quickcodes** [flutter/flutter#121393]
## I am getting following issue in my flutter project. Please guide me to resolve this issue :

```

Launching lib\main.dart on SM J600G in debug mode...
: Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
import 'asset_manifest.dart';
^^^^^^^^^^^^^

: Error: 'DatePickerTheme' is imported from both 'package:flutter/src/material/date_picker_theme.dart' and 'package:flutter_datetime_picker/src/datetime_picker_theme.dart'.
import 'package:flutter_datetime_picker/src/datetime_picker_theme.dart';
^^^^^^^^^^^^^^^

: Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
AssetManifest assetManifest = AssetManifest();
                              ^^^^^^^^^^^^^
: Error: 'DatePickerTheme' is imported from both 'package:flutter/src/material/date_picker_theme.dart' and 'package:flutter_datetime_picker/src/datetime_picker_theme.dart'.
        this.theme = theme ?? DatePickerTheme(),
                              ^^^^^^^^^^^^^^^
: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^
: Error: The method 'FallThroughError' isn't defined for the class 'ActionCodeInfo'.
- 'ActionCodeInfo' is from 'package:firebase_auth_platform_interface/src/action_code_info.dart' ('../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_auth_platform_interface-6.10.1/lib/src/action_code_info.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FallThroughError'.
        throw FallThroughError();

              ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1154

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)


```

Here is my ```flutter doctor -v``` output : 

```
[√] Flutter (Channel master, 3.8.0-13.0.pre.22, on Microsoft Windows [Version 10.0.22621.1265], locale en-IN)
    • Flutter version 3.8.0-13.0.pre.22 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 911b13784b (9 days ago), 2023-02-15 02:54:25 -0500
    • Engine revision 44e36c9c0d
    • Dart version 3.0.0 (build 3.0.0-236.0.dev)
    • DevTools version 2.21.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\dhruv\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\dhruv\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (4 available)
    • SM J600G (mobile) • 5200636142c8b567 • android-arm    • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.1265]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 110.0.5481.104
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 110.0.1587.50

[√] Network resources
    • All expected network resources are available.
```

I have followed all the basic procedures like deleting build folder, and pubspec.lock file and flutter clean and get kindda stuff. I have also check my dependency there is no conflict.

**Comment by jayjah** [comment]
@quickcodes There are some conflicts with your imports statements, so e.G. the class you are using Is `AssetManifest`. 
This class is defined in `package:flutter/src/services/asset_manifest.dart` and `package:google_fonts/src/asset_manifest.dart`. 
There are two simple fixes you can choose from:

The first one, would be to hide the class `AssetManifest` from one of the imports, this would then look like: `import 'package:flutter/src/services/asset_manifest.dart' hide AssetManifest;` or `import 'package:google_fonts/src/asset_manifest.dart' hide AssetManifest;`. 

The second approach would be to make an alias for that specific import, this would look like: `import 'package:flutter/src/services/asset_manifest.dart' as services;`. And then when you are using that class it should look like the following: `services.AssetManifest`

Here is a small reference, which might help you [dart.dev](https://dart.dev/guides/libraries/create-library-packages).

The second error which you are getting is the fact, that the error `FallThroughError` just doesn't exist but you are using it.

**Comment by huycozy** [comment]
@quickcodes Please try above solution if it works for you. Also, you may wanna check this [solution](https://github.com/flutter/flutter/issues/120005#issuecomment-1418641834) if it's helpful.

**Comment by quickcodes** [comment]
I tried above solution. It's not working Let me check this link

**Comment by quickcodes** [comment]
## I upgraded google_fonts version in dependency and after that I'm getting the following errors : 
```

Launching lib\main.dart on SM J600G in debug mode...
Running Gradle task 'assembleDebug'...
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_datetime_picker-1.5.1/lib/flutter_datetime_picker.dart:6:1: Error: 'DatePickerTheme' is imported from both 'package:flutter/src/material/date_picker_theme.dart' and 'package:flutter_datetime_picker/src/datetime_picker_theme.dart'.
import 'package:flutter_datetime_picker/src/datetime_picker_theme.dart';
^^^^^^^^^^^^^^^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_datetime_picker-1.5.1/lib/flutter_datetime_picker.dart:199:31: Error: 'DatePickerTheme' is imported from both 'package:flutter/src/material/date_picker_theme.dart' and 'package:flutter_datetime_picker/src/datetime_picker_theme.dart'.
        this.theme = theme ?? DatePickerTheme(),
                              ^^^^^^^^^^^^^^^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/cloud_firestore_platform_interface-5.7.7/lib/src/platform_interface/utils/load_bundle_task_state.dart:13:13: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_auth_platform_interface-6.10.1/lib/src/action_code_info.dart:65:15: Error: The method 'FallThroughError' isn't defined for the class 'ActionCodeInfo'.
 - 'ActionCodeInfo' is from 'package:firebase_auth_platform_interface/src/action_code_info.dart' ('../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_auth_platform_interface-6.10.1/lib/src/action_code_info.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FallThroughError'.
        throw FallThroughError();
              ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1154

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 13s
Exception: Gradle task assembleDebug failed with exit code 1


```

**Comment by quickcodes** [comment]
I also tried to edit font.dart

**Comment by quickcodes** [comment]
I also tried ``` flutter pub cache repair ```

**Comment by jayjah** [comment]
please update the following packages as well: `flutter_datetime_picker`; `firebase_auth ` and `cloud_firestore `.

**Comment by quickcodes** [comment]
## I updated each dependency but they are conflicting with each other. Then I tried to override some but They are still conflicting 

### Here is my yaml file
```
name: cabme
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
#  firebase_core_platform_interface: 4.5.1
  firebase_core_platform_interface: ^4.5.3
  cached_network_image: ^3.2.3            # already updated
  clipboard: ^0.1.3                       # already updated
#  cloud_firestore: ^3.4.3
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.5                 # already updated
#  dio: ^4.0.6
  dio: ^5.0.1
  dotted_border: ^2.0.0+3                 # already updated
#  firebase_auth: ^3.3.19
  firebase_auth: ^4.2.9
#  firebase_core: ^1.20.0
  firebase_core: ^2.7.0
#  firebase_messaging: ^13.1.0
  firebase_messaging: ^14.2.5
#  firebase_storage: ^10.3.4
  firebase_storage: ^11.0.14
#  flutter_braintree: null
  flutter_braintree: ^3.0.0
  flutter_datetime_picker: ^1.5.1        # already updated
  flutter_easyloading: ^3.0.5            # already updated
  flutter_google_places: ^0.3.0          # already updated
#  flutter_html: null
  flutter_html: ^2.2.1
  flutter_local_notifications: ^13.0.0   # already updated
  flutter_native_image: ^0.0.6+1         # already updated
#  flutter_native_splash: ^2.2.7
  flutter_native_splash: ^2.2.18
  flutter_polyline_points: ^1.0.0        # already updated
  flutter_rating_bar: ^4.0.1             # already updated
#  flutter_stripe: ^7.0.0
  flutter_stripe: ^8.0.0+1
#  flutter_svg: ^1.1.6
#  flutter_svg: ^2.0.2
#  flutterwave_standard: ^1.0.4
  flutterwave_standard: ^1.0.7
  geocoding: ^2.0.5                      # already updated
  geolocator: ^9.0.2                     # already updated
  get: ^4.6.5                            # already updated
#  google_fonts: ^3.0.1
  google_fonts: ^4.0.3                   # already updated
#  google_maps_flutter: ^2.2.2
  google_maps_flutter: ^2.2.4
  http: ^0.13.5                          # already updated
#  image_picker: ^0.8.6
  image_picker: ^0.8.6+3
#  intl: ^0.17.0
  intl: ^0.18.0
#  intl_phone_number_input: ^0.7.1
  intl_phone_number_input: ^0.7.2
  launch_review: ^3.0.1                  # already updated
  location: ^4.4.0                       # already updated
  mercadopago_sdk: ^1.3.0                # already updated
#  paginate_firestore: ^1.0.3+1           # already updated
    paginate_firestore: 1.0.0
#  path_provider: ^2.0.11
  path_provider: ^2.0.13
#  paytm_allinonesdk: ^1.1.7
  paytm_allinonesdk: ^1.2.1
  photo_view: ^0.14.0                   # already updated
  pin_code_fields: ^7.4.0               # already updated
#  razorpay_flutter: null
  razorpay_flutter: ^1.3.4
#  shared_preferences: ^2.0.15
  shared_preferences: ^2.0.18
#  text_scroll: ^0.1.1
  text_scroll: ^0.1.2                   # already updated
#  url_launcher: ^6.1.7
  url_launcher: ^6.1.10
#  uuid: ^3.0.7
  uuid: ^3.0.7
  video_compress: ^3.1.2                # already updated
#  video_player: ^2.4.9
  video_player: ^2.5.2
  video_thumbnail: ^0.5.3               # already updated
#  webview_flutter: ^4.0.1
  webview_flutter: ^4.0.5

dependency_overrides:
#  cloud_firestore: 3.0.0
  webview_flutter: ^3.0.4
  image: ^3.0.2
  flutter_svg: 1.0.0
  xml: ^5.0.0
  intl: ^0.17.0


dev_dependencies:
  flutter_launcher_icons: ^0.11.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appIcon.png"

flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/images/splash_screen.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  
  # uses-material-design: true

  assets:
    - assets/images/
    - assets/file/
    - assets/icons/
    - assets/flags/
    - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
