### ISSUE TITLE
_googleSignIn.signIn() deadlock?

### ISSUE THREAD

**Issue by lukaselmer** [flutter/flutter#12137]
`_googleSignIn.signIn()` does not seem to work correctly?

This may be related to

* https://github.com/flutter/plugins/pull/94
* https://github.com/flutter/flutter/issues/10552

## Steps to Reproduce

You can reproduce it doing the flutter-firebase codelab (https://codelabs.developers.google.com/codelabs/flutter-firebase/#5), using Android 8 (SDK 26). There seems to be some kind of deadlock when calling this method.

It also does not seem to work using the following versions:

```yml
dependencies:
  flutter:
    sdk: flutter
  image_picker: 0.1.1
  google_sign_in: 0.3.1
  firebase_analytics: 0.1.0
  firebase_auth: 0.2.3
  firebase_database: 0.1.0
  firebase_storage: 0.0.6
  firebase_messaging: 0.0.5
```

We also found out that you can sign in like this:

* call `_googleSignIn.signIn()`
* select the user
* we noticed a very short flicker at the top of the screen, but that's it
* if you use `await _googleSignIn.signIn()`, the code below is never executed
* there is also no exception thrown
* (deadlock in async call?)
* close the app, so that it stops running in the background
* open the app again
* sign in using `_googleSignIn.signInSilently()`: this works now because the account has been selected already
