### ISSUE TITLE
'MenuController' is imported from both packages

### ISSUE THREAD

**Issue by reysagar** [flutter/flutter#121697]
I just updated the latest **flutter version 3.7.3** and all of a sudden I got a bunch of errors, which I resolved but I am constantly getting this error and I won't be able to solve it.

```
`Error` 

**(Xcode): lib/view/screens/dashboard/dashboard_screen.dart:7:1: Error: 'MenuController' is imported from both 'package:flutter/src/material/menu_anchor.dart' and 'package:sixvalley_delivery_boy/controller/menu_controller.dart'.**
```
[menu_anchor.dart.zip](https://github.com/flutter/flutter/files/10862532/menu_anchor.dart.zip)

Thank You !

**Comment by darshankawar** [comment]
@reysagar 
Can you try by upgrading all the packages you have in `pubspec.yaml` and also run `flutter pub get` and see if you still get same error ?

**Comment by reysagar** [comment]
Added this code on pubspec.yaml

```
dependency_overrides:
  modal_bottom_sheet:
git:
  url: [https://github.com/danReynolds/modal_bottom_sheet.git]
  (https://github.com/danReynolds/modal_bottom_sheet.git)

  path: modal_bottom_sheet
```
But got the 

```
Error on line 57, column 3 of pubspec.yaml: Expected ':'.
   ╷
57 │   path: modal_bottom_sheet
   │   ^
   ╵
```
