### ISSUE TITLE
How to import flutter module to a flutter project

### ISSUE THREAD

**Issue by tuphampro** [flutter/flutter#122004]
I wrote a Flutter module, then build **.aar**, .**xcframework** it doesn't run in other flutter project . How to import flutter module in other flutter project.

**Comment by Neurs12** [comment]
Nếu muốn nhập thư viện Flutter nội bộ trong máy vào trong 1 dự án khác:

Mở file có tên `pubspec.yaml` và thêm thư viện phụ thuộc:
```
...
dependencies:
  flutter:
    sdk: flutter
  package-name:
   path: .../package-name
...
```

Importing your local Flutter package to other Flutter projects:

Open `pubspec.yaml` and add your dependencies:
```
...
dependencies:
  flutter:
    sdk: flutter
  package-name:
   path: .../package-name
...
```

**Lưu ý / Note**: Dùng dấu `/` thay vì `\` / Use `/` instead of `\`

Ví dụ / Example:

(Mình sẽ dùng thư viện của mình đây / I'm going to use my package here 😅)

`pubspec.yaml`:
```
...
dependencies:
  flutter:
    sdk: flutter
  open_meteo:
    path: D:/Flutter Projects/open_meteo
...
```

`main.dart`:
```
import 'package:open_meteo/open_meteo;'

void main() async {
  var op = OpenMeteo(latitude: 52.52, longitude: 13.41);
  var hourly = Hourly(temperature_2m: true);
  var res = await op.raw_request(hourly: hourly);
  print(res);
}
```
