### ISSUE TITLE
webview_flutter: JavascriptChannel not working for Android but working fine for iOS

### ISSUE THREAD

**Issue by kainjinez** [flutter/flutter#123190]
## Steps to Reproduce

I am using webview_flutter (4.0.7) and implementing javascript channel to let the webview send to client a message.
It works for iOS but when build up in Android, it is not trigger my function. Here is my code:

```
import 'dart:developer';

import 'package:blitzcareer/features/dashboard/bloc/dashboard_page_bloc.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:webview_flutter/webview_flutter.dart';

class DashBoardPage extends StatefulWidget {
  const DashBoardPage({Key? key}) : super(key: key);

  @override
  State<DashBoardPage> createState() => _DashBoardPageState();
}

class _DashBoardPageState extends State<DashBoardPage>
    with AutomaticKeepAliveClientMixin<DashBoardPage> {
  late final WebViewController _controller;

  static const _webUrl = "https://example.com";
  static const _userIdJsChannel = "send_userid";

  @override
  void initState() {
    _initWebViewController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(child: WebViewWidget(controller: _controller)),
    );
  }

  void _initWebViewController() {
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..addJavaScriptChannel(_userIdJsChannel,
          onMessageReceived: _onUserIdMessageReceived)
      ..setBackgroundColor(const Color(0x00000000))
      ..loadRequest(Uri.parse(_webUrl));
  }

  void _onUserIdMessageReceived(JavaScriptMessage message) {
    log("user id: ${message.message}");
    context
        .read<DashboardPageBloc>()
        .add(ReceiveUserIdEvent(userId: message.message));
  }

  @override
  bool get wantKeepAlive => true;
}

```

Js call from webview:
```
window.webkit && window.webkit.messageHandlers ? window.webkit.messageHandlers.send_userid.postMessage(t.data.id) : console.log("")
```

I also tried with Android Native, and it is also work. Here is the code for example:
```
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        binding.buttonFirst.setOnClickListener {
            findNavController().navigate(R.id.action_FirstFragment_to_SecondFragment)
        }
        // post_userid
        // => String

        binding.wv.addJavascriptInterface(JsInterface(), "sendUserId")
        binding.wv.apply {
            settings.apply {
                javaScriptEnabled = true
            }
            webViewClient = object : WebViewClient() {
                override fun onPageStarted(view: WebView?, url: String?, favicon: Bitmap?) {
                    super.onPageStarted(view, url, favicon)
                    view?.evaluateJavascript("window.webkit = { messageHandlers: { send_userid: window.sendUserId} }") {}
                }
            }
            loadUrl("https://example.com")
        }
    }

    class JsInterface {
        @JavascriptInterface
        fun postMessage(userId: String) {
            Log.i("jsinterface", "$userId > userId")
        }
    }
```

**Expected results:** Seeing log "user id: abcxyz".

**Actual results:** Function `_onUserIdMessageReceived` is not triggered. I tried by putting debug point also. 

**Flutter doctor -v**
```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-arm64, locale en-VN)
    • Flutter version 3.7.7 on channel stable at /Volumes/Data/FlutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (13 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

⣷      [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Volumes/Data/AndroidSDK
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (4 available)
    • Pixel 4 (mobile)           • 99011FFAZ0008F                       • android-arm64  • Android 13 (API 33)
    • iPhone 14 Pro Max (mobile) • 04597950-EB6C-4687-A936-CE9C9A96ED60 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 111.0.5563.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
Thanks.

**Comment by danagbemava-nc** [comment]
Hi @kainjinez, are you facing the issue on android in `release` mode or do you face it in `debug` mode as well? 

Please provide your `pubspec.yaml` as well. 

Also, can you take a look at https://github.com/flutter/flutter/issues/92548 to see if it's similar to what you're facing?

**Comment by kainjinez** [comment]
@danagbemava-nc Hi.
I'm facing this problem even in debug mode.
Here is my pubspec.
```
name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Being able to compare objects
  equatable: ^2.0.3
  # Parsing JSON
  json_annotation: ^4.4.0
  # DI
  get_it: ^7.2.0
  # Multi locale
  intl: ^0.17.0
  # SVG
  flutter_svg: ^1.1.1+1
  # Animation, transtion
  animations: ^2.0.3
  retrofit: ^3.0.1+1
  logger: any
  dio: ^4.0.6
  shared_preferences: ^2.0.18
  # SQLite DB
  sqlite3_flutter_libs: ^0.5.0
  # Getting path
  path_provider: ^2.0.0
  path: ^1.8.2
  # DB (Similar to Android Room)
  drift: ^2.1.0
  # State management
  flutter_bloc: ^8.1.2
  bloc: ^8.0.3
  # DI
  provider: ^6.0.3
  google_fonts: ^4.0.3
  webview_flutter: ^4.0.7
  injectable: ^2.1.0
  flutter_html: ^3.0.0-alpha.5
  cached_network_image: ^3.2.3
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: '>4.4.0'
  retrofit_generator: '>=4.0.0 <5.0.0'
  drift_dev: ^2.1.0
  # add the generator to your dev_dependencies
  injectable_generator: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
flutter_intl:
  enabled: true
```
