### ISSUE TITLE
CI/CD/iOS: flutter build is failing on ios  in CI(Github actions) but building fine in local

### ISSUE THREAD

**Issue by Shriyanshx** [flutter/flutter#123408]
I am trying to build iOS build on CI but it keeps failing. I match the xcode and cling version same as my local machine but it is still failing.

Earlier I was getting this same issue on my local machine due to xcode version but when I upgraded to 14.1 it gets fixed.

But In the CI version is same but getting the same issue.

### Workflow
```
name: Flutter CI

on:
  push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH }}

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1'

      - name: check xcode and clang version
        run: |
          xcodebuild -version
          clang --version  

      - name: flutter pub get
        run: flutter pub get


      - name: Fastlane Match setup
        run: |
          cd ios
          fastlane dev
      

      - name: flutter build iOS
        run: flutter build ios --release --flavor dev -t lib/main_dev.dart

```

### Xcode version
```
Run xcodebuild -version
Xcode [1](https://github.com/dev-sunstone/hub_app/actions/runs/4513003849/jobs/7947225725#step:7:1)4.1
Build version [14](https://github.com/dev-sunstone/hub_app/actions/runs/4513003849/jobs/7947225725#step:7:15)B47b
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode_14.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### 
[logg.txt](https://github.com/flutter/flutter/files/11064462/logg.txt)
Log
