### ISSUE TITLE
artifacts from previous builds

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#12350]
There is this bug when sometimes flutter loads some code/assets from previous builds.

So basically you are developing, making build 1, do some changes in the code, assets or yaml configs, make a new build 2 and run it. Then you discover that the resulting app from build 2 contains some artifacts of the build 1.

Hard to track and reproduce this one.

**Comment by JFixby** [comment]
Two most repeating scenarios:
1)  gradle loads some older libs

2) pubsec.yaml refers to a config.yaml with 
```
flutter:
  uses-material-design: true

  assets:
    ...
    - config/config.yaml
```
and the apk contains older versions of the `config.yaml`
