### ISSUE TITLE
Flutter Web always force downloads fonts and CanvasKit from CDN, which violates European DSGVO laws.

### ISSUE THREAD

**Issue by pperle** [flutter/flutter#123601]
It is necessary to load local versions of CanvasKit and all fonts to comply with these laws.

Flutter web always downloads fonts and CanvasKit from a Content Delivery Network (CDN). This presents a problem for users in Europe who must comply with the European Data Protection Regulation (DSGVO) laws that restrict the transfer of data to third-party servers without explicit consent. To comply with DSGVO laws, it is necessary to load local versions of CanvasKit and all fonts. 

To load the local version of CanvasKit, I used `FLUTTER_WEB_CANVASKIT_URL` but as described in https://github.com/flutter/flutter/issues/112861#issuecomment-1268924177 it is loaded twice for some reason.
```
flutter build web \
  --dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/ \
  --web-renderer canvaskit \
  --release
```

I also downloaded the necessary fonts and tried to load them via Flutter as described in https://github.com/flutter/flutter/issues/77580#issuecomment-1112333700. This works for Roboto, but not for Noto Sans Symbols.
```
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/google_fonts/Roboto-Regular.ttf
    - family: Noto Sans Symbols
      fonts:
        - asset: assets/google_fonts/rP2up3q65FkAtHfwd-eIS2brbDN6gxP34F9jRRCe4W3gfQ8gavVFRkzrbQ.ttf
```

I know this is issue was raised before, e.g. https://github.com/flutter/flutter/issues/70101 (but it was closed without a solution) and https://github.com/flutter/flutter/issues/85793 (without any updates) and https://github.com/flutter/flutter/issues/60069.
I raised a new issue to emphasize the importance of complying with the European DSGVO laws when publishing a flutter web app.
