### ISSUE TITLE
[gen-l10n] Optional generate extension on BuildContext

### ISSUE THREAD

**Issue by SunlightBro** [flutter/flutter#124199]
## Use case

When using `flutter_localizations` to generate a package from .arb files,
I always create a extension on BuildContext for an easy getter:
```dart
extension L10nExt on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
```

## Proposal

Add an additional option for `l10n.yaml`
```yaml
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
# new option that defaults to false 
context-extension: true
```
that if true generates an extension on BuildContext.
