### ISSUE TITLE
[video_player][iOS] VideoPlayerController.value.position not updating on video completion for video_player_avfoundation > 2.4.2 

### ISSUE THREAD

**Issue by neeraj-dhake** [flutter/flutter#124475]
## Steps to Reproduce

1. Execute `flutter run` on the code sample linked below.
2. Wait till the end of the video (17s) and some more.
3. This doesn't happen if I pin the `video_player_avfoundation` to `2.4.1`

**Expected results:** The text below the video should get updated to `Completed`

**Actual results:** The text below the video doesn't get updated to `Completed` and remains `isPlaying`

From my debugging, what I could see was that the following [code](https://github.com/flutter/packages/blob/main/packages/video_player/video_player/lib/video_player.dart#L428-L434) was triggered:
```dart
        case VideoEventType.completed:
          // In this case we need to stop _timer, set isPlaying=false, and
          // position=value.duration. Instead of setting the values directly,
          // we use pause() and seekTo() to ensure the platform stops playing
          // and seeks to the last frame of the video.
          pause().then((void pauseResult) => seekTo(value.duration));
          break;
```
but in the `seekTo` [function](https://github.com/flutter/packages/blob/main/packages/video_player/video_player/lib/video_player.dart#L597-L608), the following does not complete:
```dart
    await _videoPlayerPlatform.seekTo(_textureId, position);
```
The change in `video_player_avfoundation = 2.4.2` was to make the seek async, so its highly likely that this is the issue.

<details>
<summary>Code sample</summary>
`main.dart`:

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Video Player')),
        body: const VideoPlayerExample(),
      ),
    );
  }
}

class VideoPlayerExample extends StatefulWidget {
  const VideoPlayerExample({super.key});

  @override
  VideoPlayerExampleState createState() => VideoPlayerExampleState();
}

class VideoPlayerExampleState extends State<VideoPlayerExample> {
  final controller = VideoPlayerController.network(
    'https://cdnapisec.kaltura.com/p/309/sp/0/playManifest/entryId/1_rcit0qgs/format/applehttp/protocol/https/flavorParamId/301971/manifest.m3u8',
  );
  late Future<void> initializeVideoPlayerFuture;

  @override
  void initState() {
    initializeVideoPlayerFuture = controller.initialize();
    controller.play();
    controller.addListener(listener);
    super.initState();
  }

  @override
  void dispose() {
    controller.removeListener(listener);
    controller.dispose();
    super.dispose();
  }

  void listener() {
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        FutureBuilder(
          future: initializeVideoPlayerFuture,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              return AspectRatio(
                aspectRatio: controller.value.aspectRatio,
                child: VideoPlayer(controller),
              );
            } else {
              return const CircularProgressIndicator();
            }
          },
        ),
        const SizedBox(height: 20),
        Text(
          controller.value.position >= controller.value.duration
              ? 'Completed'
              : 'Playing',
          style: const TextStyle(fontSize: 24),
        ),
      ],
    );
  }
}
```

`pubspec.yaml`:
```yaml
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.6.1
  video_player_avfoundation: ^2.4.2 # change this to 2.4.1 to see that this doesn't happen.
```

</details>

<details>
  <summary>Logs</summary>

Run `flutter analyze` and attach any output of that command below.
```
Analyzing video_player_example...                                       
No issues found! (ran in 1.0s)
```

Finally, paste the output of running `flutter doctor -v` here.

```
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3 22E252 darwin-arm64, locale en-IN)
    • Flutter version 3.7.10 on channel stable at /Users/neerajdhake/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (5 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/neerajdhake/android
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/neerajdhake/android
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.0.4.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

<img src="https://user-images.githubusercontent.com/20846526/230768728-e391bac1-f8ed-408e-a81a-d41f34dd012b.png" width="45%"/> <img src="https://user-images.githubusercontent.com/20846526/230769442-412abfa1-d891-421a-b693-22822fb8d816.png" width="45%"/>

**Comment by huycozy** [comment]
Hi @neeraj-dhake 
I'm checking this on the latest plugin version: `video_player: ^2.6.1` and `video_player_avfoundation: ^2.4.4` but don't see the issue. Verified on `iPhone 7, iOS 15.7.2`.

<details>
<summary>Demo</summary>

![IMG_4546](https://user-images.githubusercontent.com/104349824/230881293-92ad197f-ffda-4891-bc1a-91419c267a2b.png)

</details>

Which `video_player` version are you using? How often does this issue happen?

**Comment by neeraj-dhake** [comment]
I have the same versions as you.
<details>
<summary>This is my pubspec.lock file:</summary>

```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: bfe67ef28df125b7dddcea62755991f807aa39a2492a23e1550161692950bbe0
      url: "https://pub.dev"
    source: hosted
    version: "2.10.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: e6a326c8af69605aec75ed6c187d06b349707a27fbff8222ca9cc2cff167975c
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  clock:
    dependency: transitive
    description:
      name: clock
      sha256: cb6d7f03e1de671e34607e909a7213e31d7752be4fb66a86d29fe1eb14bfb5cf
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: cfc915e6923fe5ce6e153b0723c753045de46de1b4d63771530504004a45fae0
      url: "https://pub.dev"
    source: hosted
    version: "1.17.0"
  csslib:
    dependency: transitive
    description:
      name: csslib
      sha256: b36c7f7e24c0bdf1bf9a3da461c837d1de64b9f8beb190c9011d8c72a3dfd745
      url: "https://pub.dev"
    source: hosted
    version: "0.17.2"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      sha256: e35129dc44c9118cee2a5603506d823bab99c68393879edb440e0090d07586be
      url: "https://pub.dev"
    source: hosted
    version: "1.0.5"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      sha256: "511392330127add0b769b75a987850d136345d9227c6b94c96a04cf4a391bf78"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      sha256: aeb0b80a8b3709709c9cc496cdc027c5b3216796bc0af0ce1007eaf24464fd4c
      url: "https://pub.dev"
    source: hosted
    version: "2.0.1"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  html:
    dependency: transitive
    description:
      name: html
      sha256: "79d498e6d6761925a34ee5ea8fa6dfef38607781d2fa91e37523474282af55cb"
      url: "https://pub.dev"
    source: hosted
    version: "0.15.2"
  js:
    dependency: transitive
    description:
      name: js
      sha256: "5528c2f391ededb7775ec1daa69e65a2d61276f7552de2b5f7b8d34ee9fd4ab7"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.5"
  lints:
    dependency: transitive
    description:
      name: lints
      sha256: "5e4a9cd06d447758280a8ac2405101e0e2094d2a1dbdd3756aec3fe7775ba593"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: "16db949ceee371e9b99d22f88fa3a73c4e59fd0afed0bd25fc336eb76c198b72"
      url: "https://pub.dev"
    source: hosted
    version: "0.12.13"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      sha256: d92141dc6fe1dad30722f9aa826c7fbc896d021d792f80678280601aff8cf724
      url: "https://pub.dev"
    source: hosted
    version: "0.2.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "6c268b42ed578a53088d834796959e4a1814b5e9e164f147f580a386e5decf42"
      url: "https://pub.dev"
    source: hosted
    version: "1.8.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: db9d4f58c908a4ba5953fcee2ae317c94889433e5024c27ce74a37f94267945b
      url: "https://pub.dev"
    source: hosted
    version: "1.8.2"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      sha256: "6a2128648c854906c53fa8e33986fc0247a1116122f9534dd20e3ab9e16a32bc"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: dd904f795d4b4f3b870833847c461801f6750a9fa8e61ea5ac53f9422b31f250
      url: "https://pub.dev"
    source: hosted
    version: "1.9.1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      sha256: c3c7d8edb15bee7f0f74debd4b9c5f3c2ea86766fe4178eb2a18eb30a0bdaed5
      url: "https://pub.dev"
    source: hosted
    version: "1.11.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      sha256: "83615bee9045c1d322bbbd1ba209b7a749c2cbcdcb3fdd1df8eb488b3279c1c8"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: ad540f65f92caa91bf21dfc8ffb8c589d6e4dc0c2267818b4cc2792857706206
      url: "https://pub.dev"
    source: hosted
    version: "0.4.16"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  video_player:
    dependency: "direct main"
    description:
      name: video_player
      sha256: de95f0e9405f29b5582573d4166132e71f83b3158aac14e8ee5767a54f4f1fbd
      url: "https://pub.dev"
    source: hosted
    version: "2.6.1"
  video_player_android:
    dependency: transitive
    description:
      name: video_player_android
      sha256: a592048a711d5739d9cea2255d425779f138d41095b9149bda60ce4bc1af8871
      url: "https://pub.dev"
    source: hosted
    version: "2.4.4"
  video_player_avfoundation:
    dependency: "direct main"
    description:
      name: video_player_avfoundation
      sha256: "75c6d68cd479a25f34d635149ba6887bc8f1b2b2921841121fd44ea0c5bc1927"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.4"
  video_player_platform_interface:
    dependency: transitive
    description:
      name: video_player_platform_interface
      sha256: a8c4dcae2a7a6e7cc1d7f9808294d968eca1993af34a98e95b9bdfa959bec684
      url: "https://pub.dev"
    source: hosted
    version: "6.1.0"
  video_player_web:
    dependency: transitive
    description:
      name: video_player_web
      sha256: "44ce41424d104dfb7cf6982cc6b84af2b007a24d126406025bf40de5d481c74c"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.16"
sdks:
  dart: ">=2.19.6 <3.0.0"
  flutter: ">=3.3.0"
```
</details>

It happened every time for me (although on an internal stream URL, which unfortunately I can't share). We actually started noticing this on our content which is also kaltura delivered, and there it happens 100% of the time on multiple iOS devices - iPhone XS, iPhone 12, iPhone 13 Pro, regardless of whether there's seek or not.

For the URL I linked, it happened to me 3/3 times that I tested yesterday, however now it didn't. But I could reproduce 10/10 times it by seeking to 2 min at the beginning while initializing, and it didn't happen when the `video_player_avfoundation = 2.4.1`:
``` dart
    initializeVideoPlayerFuture = controller
        .initialize()
        .then((value) => controller.seekTo(const Duration(minutes: 2)));
```
