### ISSUE TITLE
DevFs takes too long times [about 30s] in creating new file systme

### ISSUE THREAD

**Issue by MinJun-chl** [flutter/flutter#124666]
I reported this issue before and thought I'd fixed it, but the same thing happened again.
[previous issue report](https://github.com/flutter/flutter/issues/123456)

all condition are totally same with previous issue report

1. This issue happens only AOS, regardless of API level (I tested from API 25 to 33)
2. It does not happen in first launch, but from the second time it happens every launch

I tried some cases
1. I tried newly created flutter project with same packages, but not happens.
2. I tried android studio emulator, it happens.
3. I tried to debug with break point, but it happens before my own code. (may be main()).

Here is my `flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.7.8, on macOS 12.6.1 21G217 darwin-arm64, locale ko-KR)
    • Flutter version 3.7.8 on channel stable at /Users/mj/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (3주 전), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mj/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (4 available)
    • SM N971N (mobile)          • R3CM80T1RRJ                          • android-arm64  • Android 12 (API 31)
    • iPhone 14 Pro Max (mobile) • 2A88B362-7B28-4A01-AFC9-65ACD776B868 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by MinJun-chl** [comment]
my packages 
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # firebase
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0

  # dio
  http: ^0.13.5
  dio: ^4.0.6

  #third party
  sign_in_with_apple: ^4.3.0
  kakao_flutter_sdk: ^1.4.0
  kakao_flutter_sdk_user: ^1.4.0
  flutter_naver_login: ^1.7.0

  #native
  permission_handler: ^10.2.0
  location: ^4.4.0
  shared_preferences: ^2.0.17
  app_settings: ^4.2.0
  intl: ^0.17.0
  flutter_reactive_ble: ^5.0.3
  camera: ^0.10.3
  image_picker: ^0.8.6+1
  geolocator: ^9.0.2

  #util
  provider: ^6.0.5
  flutter_html: ^3.0.0-alpha.6
  url_launcher: ^6.1.8
  logger: ^1.1.0
  yaml: ^3.1.1
  jwt_decode: ^0.3.1
  swipeable_page_route: ^0.3.0
  in_app_review: ^2.0.6
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  flutter_app_badger: ^1.5.0
  google_mlkit_text_recognition: ^0.5.0
  themed: ^4.0.0
  path_provider: ^2.0.14
  timezone: ^0.9.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  tuple: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_share: ^2.0.0

  #design
  fluttertoast: ^8.1.2
  loading_indicator: ^3.1.0
  skeletons: ^0.0.3
  flutter_secure_keyboard: ^2.2.2
  new_version: ^0.3.1
  animated_text_kit: ^4.2.2
  mobile_scanner: ^3.1.1
  animations: ^2.0.7
  meta: ^1.8.0
  flutter_native_splash: ^2.2.16
  safe_device: ^1.1.2
  webview_flutter: 3.0.4
  flutter_naver_map: ^1.0.0
  flutter_rating_bar: ^4.0.1
  store_redirect: ^2.0.1
  easy_debounce: ^2.0.3
  percent_indicator: ^4.2.2
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  firebase_analytics: ^10.2.0



  # 카메라 인식 및 카드 OCR 기능 탑재시 사용
  # google_mlkit_text_recognition: ^0.3.0
  # camera: ^0.10.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  # lint: ^1.10.0
  dart_code_metrics: ^5.5.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  # flutter pub run build_runner build
  json_serializable: ^6.6.0

  flutter_flavorizr: 2.1.5


  hive_generator: ^2.0.0

```
