### ISSUE TITLE
Fix not-disposed memory leaks in animation_sheet_test.dart.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#126096]
1. Open https://github.com/flutter/flutter/blob/master/packages/flutter/test/animation/animation_sheet_test.dart
2. Convert testWidgets to testWidgetsWithLeakTracking
3. Run the tests

Parent issue: https://github.com/flutter/devtools/issues/3951

**Comment by goderbauer** [comment]
I have a PR that fixes 2 of the 4 leaks this test reports. The remaining two leaks are somewhat hard to debug because the provided stack trace (see below) doesn't show who called the dart:ui method that is leaking. That makes it difficult to get to the bottom of the leak. @polina-c does the leak tracking library limit how many stack frames are shown?

Also cc @dnfield since the leak here is in the Image logic that you've touched a lot. Do you have any insights?

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: leak free
  Actual: <Instance of 'Leaks'>
   Which: contains leaks:
          # The text is generated by leak_tracker.
          # For leak troubleshooting tips open:
          # https://github.com/dart-lang/leak_tracker
          notDisposed:
            total: 2
            objects:
              Image:
                identityHashCode: 354261536
                context:
                  start: >
                    #0______ObjectTracker.startTracking_(package:leak_tracker/src/_object_tracker.dart:64:64)
                    #1______dispatchObjectEvent_(package:leak_tracker/src/_dispatcher.dart:40:19)
                    #2______dispatchObjectEvent.<anonymous_closure>_(package:leak_tracker/src/leak_tracker.dart:91:16)
                    #3______dispatchObjectEvent_(package:leak_tracker/src/leak_tracker.dart:94:4)
                    #4_______withFlutterLeakTracking.flutterEventToLeakTracker_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:109:12)
                    #5______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:238:23)
                    #6______MemoryAllocations._imageOnCreate_(package:flutter/src/foundation/memory_allocations.dart:312:5)
                    #7______new_Image.__(dart:ui/painting.dart:1715:15)
                    #8______Codec.getNextFrame.<anonymous_closure>_(dart:ui/painting.dart:2113:24)
              Image:
                identityHashCode: 60799503
                context:
                  start: >
                    #0______ObjectTracker.startTracking_(package:leak_tracker/src/_object_tracker.dart:64:64)
                    #1______dispatchObjectEvent_(package:leak_tracker/src/_dispatcher.dart:40:19)
                    #2______dispatchObjectEvent.<anonymous_closure>_(package:leak_tracker/src/leak_tracker.dart:91:16)
                    #3______dispatchObjectEvent_(package:leak_tracker/src/leak_tracker.dart:94:4)
                    #4_______withFlutterLeakTracking.flutterEventToLeakTracker_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:109:12)
                    #5______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:238:23)
                    #6______MemoryAllocations._imageOnCreate_(package:flutter/src/foundation/memory_allocations.dart:312:5)
                    #7______new_Image.__(dart:ui/painting.dart:1715:15)
                    #8______Codec.getNextFrame.<anonymous_closure>_(dart:ui/painting.dart:2113:24)
```
