### ISSUE TITLE
Fix non-disposed ValueNotifier<_OverlayEntryWidgetState?> memory leak

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#126100]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/about_test.dart 
2. Convert testWidgets to testWidgetsWithLeakTracking
3. Run the tests

Parent issue: https://github.com/flutter/devtools/issues/3951

### Expected results

-

### Actual results

-

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by goderbauer** [comment]
Stack traces of remaining leaks: 

```
          notDisposed:
            total: 2
            objects:
              ValueNotifier<_OverlayEntryWidgetState?>:
                identityHashCode: 351055822
                context:
                  start: >
                    #0______ObjectTracker.startTracking_(package:leak_tracker/src/_object_tracker.dart:64:64)
                    #1______dispatchObjectEvent_(package:leak_tracker/src/_dispatcher.dart:40:19)
                    #2______dispatchObjectEvent.<anonymous_closure>_(package:leak_tracker/src/leak_tracker.dart:91:16)
                    #3______dispatchObjectEvent_(package:leak_tracker/src/leak_tracker.dart:94:4)
                    #4_______withFlutterLeakTracking.flutterEventToLeakTracker_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:109:12)
                    #5______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:238:23)
                    #6______MemoryAllocations.dispatchObjectCreated_(package:flutter/src/foundation/memory_allocations.dart:272:5)
                    #7______new_ValueNotifier_(package:flutter/src/foundation/change_notifier.dart:508:34)
                    #8______new_OverlayEntry_(package:flutter/src/widgets/overlay.dart:141:79)
                    #9______ModalRoute.createOverlayEntries_(package:flutter/src/widgets/routes.dart:1757:21)
                    #10_____OverlayRoute.install_(package:flutter/src/widgets/routes.dart:59:28)
                    #11_____TransitionRoute.install_(package:flutter/src/widgets/routes.dart:265:11)
                    #12_____ModalRoute.install_(package:flutter/src/widgets/routes.dart:1235:11)
                    #13______RouteEntry.handleAdd_(package:flutter/src/widgets/navigator.dart:2903:11)
                    #14_____NavigatorState._flushHistoryUpdates_(package:flutter/src/widgets/navigator.dart:3936:17)
                    #15_____NavigatorState.restoreState_(package:flutter/src/widgets/navigator.dart:3410:5)
                    #16_____RestorationMixin._doRestore_(package:flutter/src/widgets/restoration.dart:912:5)
                    #17_____RestorationMixin.didChangeDependencies_(package:flutter/src/widgets/restoration.dart:898:7)
                    #18_____NavigatorState.didChangeDependencies_(package:flutter/src/widgets/navigator.dart:3428:11)
                    #19_____StatefulElement._firstBuild_(package:flutter/src/widgets/framework.dart:5237:11)
                    #20_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5062:5)
                    #21_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:3971:16)
                    #22_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3708:18)
                    #23_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5111:16)
                    #24_____StatefulElement.performRebuild_(package:flutter/src/widgets/framework.dart:5251:11)
                    #25_____Element.rebuild_(package:flutter/src/widgets/framework.dart:4805:7)
                    #26_____ComponentElement._firstBuild_(package:flutter/src/widgets/framework.dart:5068:5)
                    #27_____StatefulElement._firstBuild_(package:flutter/src/widgets/framework.dart:5242:11)
                    #28_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5062:5)
                    #29_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:3971:16)
                    #30_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3708:18)
                    #31______LayoutBuilderElement._layout.layoutCallback_(package:flutter/src/widgets/layout_builder.dart:135:18)
                    #32_____BuildOwner.buildScope_(package:flutter/src/widgets/framework.dart:2720:19)
                    #33______LayoutBuilderElement._layout_(package:flutter/src/widgets/layout_builder.dart:153:12)
                    #34_____RenderObject.invokeLayoutCallback.<anonymous_closure>_(package:flutter/src/rendering/object.dart:2506:59)
                    #35_____PipelineOwner._enableMutationsToDirtySubtrees_(package:flutter/src/rendering/object.dart:1062:15)
                    #36_____RenderObject.invokeLayoutCallback_(package:flutter/src/rendering/object.dart:2506:14)
                    #37_____RenderConstrainedLayoutBuilder.rebuildIfNecessary_(package:flutter/src/widgets/layout_builder.dart:228:7)
                    #38______RenderLayoutBuilder.performLayout_(package:flutter/src/widgets/layout_builder.dart:313:5)
                    #39_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #40_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #41_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #42_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #43_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #44_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #45_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #46_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #47_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #48_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #49_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #50_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #51_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #52_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #53_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #54_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #55_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #56_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #57_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #58_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #59_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #60_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #61_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #62_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #63_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #64_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #65_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #66_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #67_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #68_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #69_____RenderOffstage.performLayout_(package:flutter/src/rendering/proxy_box.dart:3759:13)
                    #70_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #71_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #72_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #73_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #74_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #75______RenderTheaterMixin.performLayout_(package:flutter/src/widgets/overlay.dart:838:15)
                    #76_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #77_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #78_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #79_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #80_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #81_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #82_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #83_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #84_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #85_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #86_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #87_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #88_____RenderCustomPaint.performLayout_(package:flutter/src/rendering/custom_paint.dart:554:11)
                    #89_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #90_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #91_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #92_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #93_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #94_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #95_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #96_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #97_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #98_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #99_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #100____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #101____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #102____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #103____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #104____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #105____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #106____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #107____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #108____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #109____RenderView.performLayout_(package:flutter/src/rendering/view.dart:173:14)
                    #110____RenderObject._layoutWithoutResize_(package:flutter/src/rendering/object.dart:2234:7)
                    #111____PipelineOwner.flushLayout_(package:flutter/src/rendering/object.dart:1016:18)
                    #112____AutomatedTestWidgetsFlutterBinding.drawFrame_(package:flutter_test/src/binding.dart:1396:23)
                    #113____RendererBinding._handlePersistentFrameCallback_(package:flutter/src/rendering/binding.dart:358:5)
                    #114____SchedulerBinding._invokeFrameCallback_(package:flutter/src/scheduler/binding.dart:1290:15)
                    #115____SchedulerBinding.handleDrawFrame_(package:flutter/src/scheduler/binding.dart:1220:9)
                    #116____AutomatedTestWidgetsFlutterBinding.pump.<anonymous_closure>_(package:flutter_test/src/binding.dart:1244:9)
                    #117_____rootRun_(dart:async/zone.dart:1399:13)
                    #118_____CustomZone.run_(dart:async/zone.dart:1301:19)
                    #119____TestAsyncUtils.guard_(package:flutter_test/src/test_async_utils.dart:68:41)
                    #120____AutomatedTestWidgetsFlutterBinding.pump_(package:flutter_test/src/binding.dart:1230:27)
                    #121____WidgetTester._pumpWidget_(package:flutter_test/src/widget_tester.dart:585:20)
                    #122____WidgetTester.pumpWidget.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:570:14)
                    #123_____rootRun_(dart:async/zone.dart:1399:13)
                    #124_____CustomZone.run_(dart:async/zone.dart:1301:19)
                    #125____TestAsyncUtils.guard_(package:flutter_test/src/test_async_utils.dart:68:41)
                    #126____WidgetTester.pumpWidget_(package:flutter_test/src/widget_tester.dart:569:27)
                    #127____main.<anonymous_closure>_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/material/about_test.dart:413:18)
                    #128____testWidgetsWithLeakTracking.wrappedCallback.<anonymous_closure>_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:58:27)
                    #129____withLeakTracking_(package:leak_tracker/src/orchestration.dart:88:19)
                    #130_____withFlutterLeakTracking.<anonymous_closure>_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:117:27)
                    #131_____rootRun_(dart:async/zone.dart:1399:13)
                    #132_____CustomZone.run_(dart:async/zone.dart:1301:19)
                    #133____TestAsyncUtils.guard_(package:flutter_test/src/test_async_utils.dart:68:41)
                    #134_____withFlutterLeakTracking_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:112:25)
                    #135____testWidgetsWithLeakTracking.wrappedCallback_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:57:11)
                    #136____testWidgets.<anonymous_closure>.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:163:29)
                    <asynchronous_suspension>
                    #137____StackZoneSpecification._registerUnaryCallback.<anonymous_closure>_(package:stack_trace/src/stack_zone_specification.dart:124:15)
                    <asynchronous_suspension>
              ValueNotifier<_OverlayEntryWidgetState?>:
                identityHashCode: 1010357253
                context:
                  start: >
                    #0______ObjectTracker.startTracking_(package:leak_tracker/src/_object_tracker.dart:64:64)
                    #1______dispatchObjectEvent_(package:leak_tracker/src/_dispatcher.dart:40:19)
                    #2______dispatchObjectEvent.<anonymous_closure>_(package:leak_tracker/src/leak_tracker.dart:91:16)
                    #3______dispatchObjectEvent_(package:leak_tracker/src/leak_tracker.dart:94:4)
                    #4_______withFlutterLeakTracking.flutterEventToLeakTracker_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:109:12)
                    #5______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:238:23)
                    #6______MemoryAllocations.dispatchObjectCreated_(package:flutter/src/foundation/memory_allocations.dart:272:5)
                    #7______new_ValueNotifier_(package:flutter/src/foundation/change_notifier.dart:508:34)
                    #8______new_OverlayEntry_(package:flutter/src/widgets/overlay.dart:141:79)
                    #9______ModalRoute.createOverlayEntries_(package:flutter/src/widgets/routes.dart:1756:23)
                    #10_____OverlayRoute.install_(package:flutter/src/widgets/routes.dart:59:28)
                    #11_____TransitionRoute.install_(package:flutter/src/widgets/routes.dart:265:11)
                    #12_____ModalRoute.install_(package:flutter/src/widgets/routes.dart:1235:11)
                    #13______RouteEntry.handleAdd_(package:flutter/src/widgets/navigator.dart:2903:11)
                    #14_____NavigatorState._flushHistoryUpdates_(package:flutter/src/widgets/navigator.dart:3936:17)
                    #15_____NavigatorState.restoreState_(package:flutter/src/widgets/navigator.dart:3410:5)
                    #16_____RestorationMixin._doRestore_(package:flutter/src/widgets/restoration.dart:912:5)
                    #17_____RestorationMixin.didChangeDependencies_(package:flutter/src/widgets/restoration.dart:898:7)
                    #18_____NavigatorState.didChangeDependencies_(package:flutter/src/widgets/navigator.dart:3428:11)
                    #19_____StatefulElement._firstBuild_(package:flutter/src/widgets/framework.dart:5237:11)
                    #20_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5062:5)
                    #21_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:3971:16)
                    #22_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3708:18)
                    #23_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5111:16)
                    #24_____StatefulElement.performRebuild_(package:flutter/src/widgets/framework.dart:5251:11)
                    #25_____Element.rebuild_(package:flutter/src/widgets/framework.dart:4805:7)
                    #26_____ComponentElement._firstBuild_(package:flutter/src/widgets/framework.dart:5068:5)
                    #27_____StatefulElement._firstBuild_(package:flutter/src/widgets/framework.dart:5242:11)
                    #28_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5062:5)
                    #29_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:3971:16)
                    #30_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3708:18)
                    #31______LayoutBuilderElement._layout.layoutCallback_(package:flutter/src/widgets/layout_builder.dart:135:18)
                    #32_____BuildOwner.buildScope_(package:flutter/src/widgets/framework.dart:2720:19)
                    #33______LayoutBuilderElement._layout_(package:flutter/src/widgets/layout_builder.dart:153:12)
                    #34_____RenderObject.invokeLayoutCallback.<anonymous_closure>_(package:flutter/src/rendering/object.dart:2506:59)
                    #35_____PipelineOwner._enableMutationsToDirtySubtrees_(package:flutter/src/rendering/object.dart:1062:15)
                    #36_____RenderObject.invokeLayoutCallback_(package:flutter/src/rendering/object.dart:2506:14)
                    #37_____RenderConstrainedLayoutBuilder.rebuildIfNecessary_(package:flutter/src/widgets/layout_builder.dart:228:7)
                    #38______RenderLayoutBuilder.performLayout_(package:flutter/src/widgets/layout_builder.dart:313:5)
                    #39_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #40_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #41_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #42_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #43_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #44_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #45_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #46_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #47_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #48_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #49_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #50_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #51_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #52_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #53_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #54_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #55_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #56_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #57_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #58_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #59_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #60_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #61_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #62_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #63_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #64_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #65_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #66_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #67_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #68_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #69_____RenderOffstage.performLayout_(package:flutter/src/rendering/proxy_box.dart:3759:13)
                    #70_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #71_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #72_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #73_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #74_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #75______RenderTheaterMixin.performLayout_(package:flutter/src/widgets/overlay.dart:838:15)
                    #76_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #77_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #78_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #79_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #80_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #81_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #82_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #83_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #84_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #85_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #86_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #87_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #88_____RenderCustomPaint.performLayout_(package:flutter/src/rendering/custom_paint.dart:554:11)
                    #89_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #90_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #91_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #92_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #93_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #94_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #95_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #96_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #97_____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #98_____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #99_____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #100____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #101____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #102____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #103____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #104____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #105____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #106____RenderProxyBoxMixin.performLayout_(package:flutter/src/rendering/proxy_box.dart:122:14)
                    #107____RenderObject.layout_(package:flutter/src/rendering/object.dart:2395:7)
                    #108____RenderBox.layout_(package:flutter/src/rendering/box.dart:2386:11)
                    #109____RenderView.performLayout_(package:flutter/src/rendering/view.dart:173:14)
                    #110____RenderObject._layoutWithoutResize_(package:flutter/src/rendering/object.dart:2234:7)
                    #111____PipelineOwner.flushLayout_(package:flutter/src/rendering/object.dart:1016:18)
                    #112____AutomatedTestWidgetsFlutterBinding.drawFrame_(package:flutter_test/src/binding.dart:1396:23)
                    #113____RendererBinding._handlePersistentFrameCallback_(package:flutter/src/rendering/binding.dart:358:5)
                    #114____SchedulerBinding._invokeFrameCallback_(package:flutter/src/scheduler/binding.dart:1290:15)
                    #115____SchedulerBinding.handleDrawFrame_(package:flutter/src/scheduler/binding.dart:1220:9)
                    #116____AutomatedTestWidgetsFlutterBinding.pump.<anonymous_closure>_(package:flutter_test/src/binding.dart:1244:9)
                    #117_____rootRun_(dart:async/zone.dart:1399:13)
                    #118_____CustomZone.run_(dart:async/zone.dart:1301:19)
                    #119____TestAsyncUtils.guard_(package:flutter_test/src/test_async_utils.dart:68:41)
                    #120____AutomatedTestWidgetsFlutterBinding.pump_(package:flutter_test/src/binding.dart:1230:27)
                    #121____WidgetTester._pumpWidget_(package:flutter_test/src/widget_tester.dart:585:20)
                    #122____WidgetTester.pumpWidget.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:570:14)
                    #123_____rootRun_(dart:async/zone.dart:1399:13)
                    #124_____CustomZone.run_(dart:async/zone.dart:1301:19)
                    #125____TestAsyncUtils.guard_(package:flutter_test/src/test_async_utils.dart:68:41)
                    #126____WidgetTester.pumpWidget_(package:flutter_test/src/widget_tester.dart:569:27)
                    #127____main.<anonymous_closure>_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/material/about_test.dart:413:18)
                    #128____testWidgetsWithLeakTracking.wrappedCallback.<anonymous_closure>_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:58:27)
                    #129____withLeakTracking_(package:leak_tracker/src/orchestration.dart:88:19)
                    #130_____withFlutterLeakTracking.<anonymous_closure>_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:117:27)
                    #131_____rootRun_(dart:async/zone.dart:1399:13)
                    #132_____CustomZone.run_(dart:async/zone.dart:1301:19)
                    #133____TestAsyncUtils.guard_(package:flutter_test/src/test_async_utils.dart:68:41)
                    #134_____withFlutterLeakTracking_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:112:25)
                    #135____testWidgetsWithLeakTracking.wrappedCallback_(file:///Users/goderbauer/dev/flutter/packages/flutter/test/foundation/leak_tracking.dart:57:11)
                    #136____testWidgets.<anonymous_closure>.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:163:29)
                    <asynchronous_suspension>
                    #137____StackZoneSpecification._registerUnaryCallback.<anonymous_closure>_(package:stack_trace/src/stack_zone_specification.dart:124:15)
                    <asynchronous_suspension>
```

Looks like this is a problem with OverlayEntry and/or ModalRoute cc @chunhtai @LongCatIsLooong
