### ISSUE TITLE
Archive error when building ipa with flutter 3.10.2

### ISSUE THREAD

**Issue by daviddavis83** [flutter/flutter#128004]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I upgraded my flutter version from 3.7 to 3.10.2 and now when I build the ipa I receive an error
`flutter build ipa`

### Expected results

Expected results is the ipa file is built.

### Actual results

Actual results give me this output
```Running pod install...                                             16.7s
Running Xcode build...                                                  
Xcode archive done.                                          8.4s
Failed to build iOS app
Error (Xcode): Multiple commands produce
'/Users/daviddavis/Library/Developer/Xcode/DerivedData/Runner-gstheibdinekovgxtuibwoflplax/Build/Intermed
iates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleU
tilities.framework'


Encountered error while archiving for device.
```

### Code sample

```flutter build ipa```

### Logs

logs posted above

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.10.2 on channel stable at /Users/daviddavis/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (8 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/daviddavis/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 Plus (mobile) • FFCF7C0D-CACB-42EA-B009-8AED0A8285BE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64 (Rosetta)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 114.0.5735.90

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by daviddavis83** [comment]
I have tried updating all my packages in my pubspec.yaml. I have also removed the Pods folder and the Podfile.lock and reinstalled pods. Here is my podfile

```
# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end

################  Awesome Notifications FCM pod mod  ###################
awesome_fcm_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications_fcm', 'ios', 'Scripts', 'AwesomeFcmPodFile'), '.symlinks')
require awesome_fcm_pod_file
target 'DSTServiceExtension' do
  use_frameworks!
  use_modular_headers!
  
  install_awesome_fcm_ios_pod_target File.dirname(File.realpath(__FILE__))
end
update_awesome_fcm_service_target('DSTServiceExtension', File.dirname(File.realpath(__FILE__)), flutter_root)
################  Awesome Notifications FCM pod mod  ###################
```

And here is my pubspec.yaml
```
dependencies:
  asset_webview: ^1.0.0
  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: ^0.7.4+1
  collection: ^1.17.1
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^21.2.8
  http: ^0.13.0
  get_it: ^7.6.0
  get_it_mixin: ^4.2.0
  app_tracking_transparency: ^2.0.4
  intl_phone_field:
    git:
      url: https://github.com/Anan-Saadi/intl_phone_field.git
      ref: master
  badges: ^3.1.1
  json_diff: ^0.2.1
  flutter_datetime_picker: 
    git: 
      url: https://github.com/ryojiro/flutter_datetime_picker.git 
      ref: 32ea47240c10469ad31db0084f5d9b7a12d16e01
  path: ^1.8.3
  path_provider: ^2.0.15
  google_mobile_ads: ^3.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  flutter_slidable: ^3.0.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.2
  data_table_2: ^2.2.0
  dropdown_button2: ^2.1.3
  intl: ^0.18.1
  font_awesome_flutter: ^10.4.0
  firebase_auth: ^4.6.2
  firebase_crashlytics: ^3.3.2
  flutter_inappwebview: ^5.7.2+3
  flutter_secure_storage: ^8.0.0
  flutter_config: ^2.0.0
  flutter_native_timezone: ^2.0.0
  fraction: ^5.0.0
  modal_bottom_sheet: ^3.0.0-pre
  json_annotation: ^4.4.0
  pdf: ^3.8.1
  printing: ^5.11.0
  remove_emoji: ^0.0.7
  regexed_validator: ^2.0.0+1
  in_app_purchase: ^3.1.7
  in_app_purchase_storekit: ^0.3.6+4
  in_app_review: ^2.0.6
  textfield_tags: ^2.0.2
  rrule: ^0.2.10
  url_launcher: ^6.1.2
  uuid: ^3.0.6
```

The app runs as expected when I run `flutter run` and I can build the android appbundle. I'm not sure why building the ipa is causing this issue. I have a hunch it's something to do with flutter_awesome_notifications
