### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug'. - Failed to run after upgrade to flutter 3.10.4

### ISSUE THREAD

**Issue by tajjacob** [flutter/flutter#128684]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. flutter upgrade
2. flutter clean
3. flutter pub get

### Expected results

The others projects work fine and this is the logs
```
[   +7 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch A836A4F9-7BBE-4902-8F88-014B0E3CD68C com.tajjacob.exampleflutterapp --enable-dart-profiling --start-paused --enable-checked-mode --verify-entry-points
[ +989 ms] com.tajjacob.exampleflutterapp: 94951
[        ] Waiting for VM Service port to be available...
[ +523 ms] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
[ +143 ms] VM Service URL on device: http://127.0.0.1:56409/Msox4cmuK04=/
[  +10 ms] Caching compiled dill
[  +97 ms] Connecting to service protocol: http://127.0.0.1:56409/Msox4cmuK04=/
[ +142 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:56409/Msox4cmuK04=/.
[  +63 ms] DDS is listening at http://127.0.0.1:56414/B9UvUfoCses=/.
[  +32 ms] Successfully connected to service protocol: http://127.0.0.1:56409/Msox4cmuK04=/
[  +26 ms] DevFS: Creating new filesystem on the device (null)
[  +34 ms] DevFS: Created new filesystem on the device (file:///Users/tajjacob/Library/Developer/CoreSimulator/Devices/A836A4F9-7BBE-4902-8F88-014B0E3CD68C/data/Containers/Data/Application/0FBF9D1E-1F6E-45D0-BB2A-328E98D9C152/tmp/exampleShBQ6T/example/)
[   +1 ms] Updating assets
Debug service listening on ws://127.0.0.1:56414/B9UvUfoCses=/ws
[{"event":"app.debugPort","params":{"appId":"7425240b-3eb3-4d18-b8e3-5b85a3b6c129","port":56414,"wsUri":"ws://127.0.0.1:56414/B9UvUfoCses=/ws",
```

### Actual results

After upgrading to 3.10.4, my project unable to flutter run and the errors appears as below but the other projects got no issues. My first assumption is maybe related to some plugins in pubspec.yaml not supported flutter 3.10.4. In the first error, there's error from chewie plugin and I never use chewie plugin. 

first error:
```
[+2284 ms] [+2643 ms] ../../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/material_controls.dart:441:50: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
[  +34 ms] [   +5 ms]  - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../development/flutter/packages/flutter/lib/src/material/theme_data.dart').
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
[        ] [        ]                   playedColor: Theme.of(context).accentColor,
[        ] [        ]                                                  ^^^^^^^^^^^
[        ] [        ] ../../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/material_controls.dart:442:50: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
[        ] [        ]  - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../development/flutter/packages/flutter/lib/src/material/theme_data.dart').
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
[        ] [        ]                   handleColor: Theme.of(context).accentColor,
[        ] [        ]                                                  ^^^^^^^^^^^
[        ] [        ] ../../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:144:18: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.
[        ] [        ]     SystemChrome.setEnabledSystemUIOverlays(
[        ] [        ]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:157:20: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.
[        ] [        ]       SystemChrome.setEnabledSystemUIOverlays(
[        ] [        ]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:161:20: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.
[        ] [        ]       SystemChrome.setEnabledSystemUIOverlays([]);
[        ] [        ]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [   +3 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:244:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
[        ]            <asynchronous suspension>
[        ]            #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
[        ]            <asynchronous suspension>
[        ]            #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:315:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
[        ]            <asynchronous suspension>
[        ]            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
[        ]            <asynchronous suspension>
[        ]            #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
[        ]            <asynchronous suspension>
[        ]            #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
[        ]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
```

Second errors: 
```
[ +402 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/tajjacob/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1201
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command '/Users/tajjacob/development/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] * Exception is:
[        ] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileFlutterBuildDebug'.
```

and I got gradle warning:
```
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[        ] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 1 actionable task: 1 executed
[        ] Watched directory hierarchies: [/Users/tajjacob/StudioProjects/example/android]
[{"event":"app.progress","params":{"appId":"94c2b807-ddc3-4f55-b56b-42b9c374aef5","id":"0","progressId":null,"finished":true}}]
[+7495 ms] ../../.pub-cache/hosted/pub.dev/chewie-1.0.0/lib/src/chewie_player.dart:144:18: Error: Member not found: 'SystemChrome.setEnabledSystemUIOverlays'.
```

Here is my pubspec.yaml
```
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.1

  animations: ^2.0.7
  adaptive_dialog: ^1.9.0-0
  cupertino_icons: ^1.0.5
  email_validator: ^2.1.17 # tutorial https://www.youtube.com/watch?v=mXyifVJ-NFc
  flutter_screenutil: ^5.8.3
  get: ^4.6.5
  google_fonts: ^4.0.4
  intl_phone_number_input: ^0.7.3+1
  line_icons: ^2.0.1
  rename: ^2.1.1
  flutter_svg: ^2.0.6
#  flutter_svg_image: ^1.1.0+1
  health: ^6.0.0
  page_transition: ^2.0.9
  permission_handler: ^10.3.0
  provider: ^6.0.5
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.2
  community_charts_flutter: ^1.0.1
  d_chart: ^2.2.11
  dio: ^5.2.1
  pretty_dio_logger: ^1.3.1
  dio_smart_retry: ^5.0.0
  dio_cache_interceptor: ^3.4.2
  intl: ^0.17.0 # health depend on this
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  html: ^0.15.4
  cached_network_image: ^3.2.3
  internet_connection_checker: ^1.0.0+1
  flutter_cached_pdfview: ^0.4.1
  pie_chart: ^5.3.2
  image_picker: ^0.8.8
  path_provider: ^2.0.15
  file_picker: ^5.3.0
  flutter_pdfview: ^1.3.1
  pinput: ^2.2.31
  fl_chart: ^0.63.0
  maps_launcher: ^2.2.0
  flutter_widget_from_html: ^0.10.1
  easy_refresh: ^3.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  #flutter_launcher_icons command: flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale en-MY)
    • Flutter version 3.10.4 on channel stable at /Users/tajjacob/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (6 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/tajjacob/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] VS Code (version 1.80.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.67.20230601

[✓] Connected device (7 available)
    • M2101K6G (mobile)           • 17f890c8                             • android-arm64  • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • Taj Jacob’s iPhone (mobile) • 00008101-000D65E91139003A            • ios            • iOS 16.5 20F66
    • iPhone 14 Pro (mobile)      • A836A4F9-7BBE-4902-8F88-014B0E3CD68C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro Max (mobile)  • 62CD7EC2-60E5-4C7A-AFC2-8A9808FA495C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>
