### ISSUE TITLE
Given multiple GoogleMaps, ClipRRect does not work except the last one.

### ISSUE THREAD

**Issue by yukimatsus** [flutter/flutter#128845]
### Steps to reproduce

Run the attached code. I have run this code on a Simulator of iOS 16.4 iPhone 14.

<details>
<summary>pubspec.yaml</summary>

```
name: google_map_sample
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/
```

</details>

### Expected results

All GoogleMaps in the screen are clipped by ClipRRect.

### Actual results

All but the last one are not clipped.

### Code sample

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          children: [
            Expanded(
              flex: 1,
              child: _buildMap(),
            ),
            const SizedBox(height: 24),
            Expanded(
              flex: 1,
              child: _buildMap(),
            ),
            const SizedBox(height: 24),
            Expanded(
              flex: 1,
              child: _buildMap(),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildMap() {
    return ClipRRect(
      borderRadius: const BorderRadius.all(Radius.circular(24)),
      child: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(
            37.7902519,
            -124.8048854,
          ),
          zoom: 1,
        ),
      ),
    );
  }
}
```

### Screenshots or Video

<img src='https://github.com/flutter/flutter/assets/56015262/7d3dc2ea-b270-4436-92e5-e840a30fda34' alt='screenshot' width='300px'/>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.3.1 22E772610a darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.79.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>

Thank you for reading.
