### ISSUE TITLE
Windows app crashes ("Lost connection to device.") when using native File Explorer related plugins.

### ISSUE THREAD

**Issue by F4de-lux** [flutter/flutter#129005]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

There seems to be a bug in windows flutter apps with the FilePicker.platform.getDirectoryPath() function as it is causing a crash without any exception being outputed (Simply the "`Lost connection to Device.`"). I noticed that if i first use the FilePicker.platform.pickFiles() and then call teh getDirectoryPath after it will actually work without crash.

Flutter code:
```dart
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';

class TestPage extends StatefulWidget {
  const TestPage({super.key});

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  getFolderName() async {
    try {
      String? selectedDirectory = await FilePicker.platform.getDirectoryPath();

      if (selectedDirectory != null) {
        print('Folder name: $selectedDirectory');
      } else {
        print('No folder was selected.');
      }
    } catch (e) {
      print('An error occured.');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(onPressed: getFolderName, child: Icon(Icons.explore)),
    );
  }
}
```
pubspec.yaml:
```yaml
name: desktop_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
...
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
...
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  image: ^4.0.16
  dartzmq: ^1.0.0-dev.15
  rxdart: ^0.27.7
  stream_transform: ^2.1.0
  file_picker: ^5.3.2
  url_launcher: ^6.1.11
  http: ^1.0.0
  encrypt: ^5.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  ...
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
...
  # the material Icons class.
  uses-material-design: true
...
```

The file picker opens without any issue but when I select a folder and click on the 'select folder' button the app crashes after some seconds. Sometimes a even get to print the valid value of a but the app still crashes anyway.

**IMPORTANT**:
The error however isn't only in the `file_picker` plugin as I am getting the exact same result with **at least 3 other windows compatible file/folder picking plugins** like `flutter_desktop_folder_picker`. I am using dart.

- Dart: 3.0.3 (installed with chocolately)
- Flutter: 3.10.4 (installed with chocolately)
- Windows 11: Latest version

Troubleshooting:
I have already tried restarting the app, restarting windows, flutter clean + flutter pub get, going back to older versions of the plugins.... Nothing works.

### Expected results

Expectations:
`Folder name: C:\Users\username\Desktop`

### Actual results

Results:
```
flutter: Folder name: C:\Users\username\Desktop
Lost connection to device.
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';

class TestPage extends StatefulWidget {
  const TestPage({super.key});

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  getFolderName() async {
    try {
      String? selectedDirectory = await FilePicker.platform.getDirectoryPath();

      if (selectedDirectory != null) {
        print('Folder name: $selectedDirectory');
      } else {
        print('No folder was selected.');
      }
    } catch (e) {
      print('An error occured.');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(onPressed: getFolderName, child: Icon(Icons.explore)),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v
[√] Flutter (Channel stable, 3.10.4, on
    Microsoft Windows [Version
    10.0.22621.1848], locale en-US)
    • Flutter version 3.10.4 on channel
      stable at C:\src\flutter
    • Upstream repository
      https://github.com/flutter/flutte
      r.git
    • Framework revision 682aa387cf (11
      days ago), 2023-06-05 18:04:56
      -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[√] Windows Version (Installed version
    of Windows is version 10 or higher)

[√] Android toolchain - develop for
    Android devices (Android SDK       
    version 33.0.2)
    • Android SDK at
      C:\Users\username\AppData\Local\Andr
      oid\sdk
    • Platform android-33-ext4,        
      build-tools 33.0.2
    • Java binary at: C:\Program       
      Files\Android\Android
      Studio\jbr\bin\java
    • Java version OpenJDK Runtime     
      Environment (build
      11.0.15+0-b2043.56-9505619)      
    • All Android licenses accepted.   

[√] Chrome - develop for the web       
    • Chrome at C:\Program
      Files\Google\Chrome\Application\c
      hrome.exe

[√] Visual Studio - develop for Windows
    (Visual Studio Build Tools 2019    
    16.11.24)
    • Visual Studio at C:\Program Files
      (x86)\Microsoft Visual
      Studio\2019\BuildTools
    • Visual Studio Build Tools 2019   
      version 16.11.33328.57
    • Windows 10 SDK version
      10.0.19041.0

[√] Android Studio (version 2022.1)    
    • Android Studio at C:\Program     
      Files\Android\Android Studio     
    • Flutter plugin can be installed  
      from:
      
      https://plugins.jetbrains.com/plu
      gin/9212-flutter
    • Dart plugin can be installed     
      from:
      
      https://plugins.jetbrains.com/plu
      gin/6351-dart
    • Java version OpenJDK Runtime
      Environment (build
      11.0.15+0-b2043.56-9505619)      

[√] VS Code (version 1.79.2)
    • VS Code at
      C:\Users\username\AppData\Local\Prog
      rams\Microsoft VS Code
    • Flutter extension version 3.66.0 

[√] Connected device (3 available)     
    • Windows (desktop) • windows •    
      windows-x64    • Microsoft       
      Windows [Version 10.0.22621.1848]
    • Chrome (web)      • chrome  •    
      web-javascript • Google Chrome   
      114.0.5735.134
    • Edge (web)        • edge    •    
      web-javascript • Microsoft Edge  
      114.0.1823.41

[√] Network resources
    • All expected network resources   
      are available.

• No issues found!
```

</details>
