### ISSUE TITLE
flutter manifest validator for assets section out-dated; it incorrectly detects asset variants

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#129446]
Consider a flutter application setup:

```
.
├── pubspec.yaml
├── lib
├── ...etc...
└── assets/
    ├── strawberry/
    │   └── scoop.jpg
    └── vanilla/
        └── scoop.jpg
```

And a pubspec.yaml:

```yaml
flutter:
  assets:
    - assets/scoop.jpg # We should get a warning here: 
                       #    The asset file 'assets/scoop.jpg' doesn't exist.
                       #    Try creating the file or fixing the path to the file.
```

Normally, `flutter analyze` would report a warning on `assets/scoop.jpg`, because the file doesn't exist. It does not however, presumably because it sees `strawberry/scoop.jpg` and `vanilla/scoop.jpg`, which it considers to be variants of `assets/scoop.jpg`. However, since https://github.com/flutter/flutter/pull/110721, these are no longer considered valid variants of `assets/scoop.jpg`.
