### ISSUE TITLE
[webview_flutter_wkwebview] ARC Semantic Issue (Xcode): No visible @interface for 'FWFWebView' declares the selector 'setInspectable:'

### ISSUE THREAD

**Issue by SPodjasek** [flutter/flutter#129587]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Upgrade webview_flutter_wkwebview to 3.6.0

### Expected results

Successful build

### Actual results

Builds are failing with following error:

```
flutter \
    build ipa \
    --release \
    --no-codesign \
    --no-pub \
    --build-name=2.0.0 \
    --build-number=20141
  shell: /bin/bash -e {0}
  env:
    SSH_AUTH_SOCK: ***
    SSH_AGENT_PID: ***
    FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.10.5-x6[4] ***
    PUB_CACHE: /Users/runner/hostedtoolcache/flutter/stable-3.10.[5] ***

Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Archiving ***...
Adding input path to Thin Binary build phase.
Running pod install...                                              4.9s
Running Xcode build...                                          
Xcode archive done.                                         25.[8](https://github.com/***)s
Failed to build iOS app
ARC Semantic Issue (Xcode): No visible @interface for 'FWFWebView' declares the selector 'setInspectable:'
/Users/runner/hostedtoolcache/flutter/stable-3.[10]***

Encountered error while archiving for device.
Error: Process completed with exit code 1.
```

Some irrelevant strings were replaced with `***`

### Code sample

<details><summary>Code sample</summary>

This issue is webview package related so I don't believe any code sample is applicable. Possibly any example app using webview should fail build for iOS.

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 12.6.6 21G646 darwin-x64, locale en)
    • Flutter version 3.10.5 on channel stable at /Users/runner/hostedtoolcache/flutter/stable-3.10.5-x64
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (13 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/runner/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/runner/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/runner/Library/Android/sdk
    • Java binary at: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.372-7/x64/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Temurin)(build 1.8.0_372-b07)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode_14.2.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.6 21G6[46]*** darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.[57]***35.133

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
The Flutter CLI developer tool uses Google Analytics to report usage and diagnostic data
along with package dependencies, and crash reporting to send basic crash reports.
This data is used to help improve the Dart platform, Flutter framework, and related tools.

Telemetry is not sent on the very first run.
To disable reporting of telemetry, run this terminal command:

flutter --disable-telemetry.
If you opt out of telemetry, an opt-out event will be sent,
and then no further information will be sent.
This data is collected in accordance with the
Google Privacy Policy (https://policies.google.com/privacy).```

</details>

**Comment by SPodjasek** [comment]
I can confirm that after reverting from:

```yaml
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      sha256: "7b203961d6830f3e5ed1df4c4f0493fea8388a46c4d43716167c4a8ba8ecbe83"
      url: "https://pub.dev"
    source: hosted
    version: "3.6.0"
```

to 

```yaml
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      sha256: ecc9e9ea15216afc5ba3b1f14aa19414ceba526e57b19cebd970bfa91a0f4058
      url: "https://pub.dev"
    source: hosted
    version: "3.5.0"
```

builds are successful again.
