### ISSUE TITLE
Run flutter analyze - flutter has exited unexpectedly: "FileSystemException: Directory listing failed, path = '/Users/flutter/examples/' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by harrytran998** [flutter/flutter#129619]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use Flutter version 3.3.9 and Dart version 2.18.5
2. Create an `analysis_option.yml` with the following content

```yml
# Extend from Flutter main project
# https://github.com/flutter/flutter/blob/master/analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/models/*.g.dart
    - lib/routes/**
    - lib/**/*.g.dart
    - lib/models/proto/**
    - ios/**
    - android/**
    - fastlane/**

  errors:
    missing_required_param: error
    missing_return: warning
    todo: ignore
    deprecated_member_use_from_same_package: ignore
    sdk_version_async_exported_from_core: ignore
    unused_import: warning
    unused_local_variable: warning
    dead_code: error
    sort_constructors_first: ignore
    library_private_types_in_public_api: ignore
    constant_identifier_names: ignore
    avoid_unnecessary_containers: ignore
    curly_braces_in_flow_control_structures: ignore
    no_leading_underscores_for_local_identifiers: ignore
    sort_child_properties_last: ignore
    avoid_function_literals_in_foreach_calls: ignore
    prefer_interpolation_to_compose_strings: ignore
    prefer_function_declarations_over_variables: ignore
    sized_box_for_whitespace: ignore
    use_build_context_synchronously: ignore
    depend_on_referenced_packages: ignore
    no_logic_in_create_state: ignore
    provide_deprecation_message: ignore
    empty_catches: ignore
    null_closures: ignore
    prefer_const_constructors_in_immutables: ignore

linter:
  rules:
    # STYLE
    - file_names
    - camel_case_extensions
    - camel_case_types
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    # - lines_longer_than_80_chars # Should follow this(except specific case)
    - directives_ordering
    # - constant_identifier_names # needs an opt-out https://github.com/dart-lang/linter/issues/204
    # these rules are documented on and in the same order as

    # DOCUMENTATION
    - slash_for_doc_comments
    - package_api_docs # prefer
    # - public_member_api_docs # prefer
    # - comment_references # Unused because https://github.com/dart-lang/sdk/issues/36974

    # USAGE

    # the Dart Lint rules page to make maintenance easier
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    #    - always_declare_return_types
    #    - always_put_control_body_on_new_line
    # - always_put_required_named_parameters_first # we prefer having parameters in the same order as fields https://github.com/flutter/flutter/issues/10219
    - always_require_non_null_named_parameters
    #    - always_specify_types
    # - always_use_package_imports # we do this commonly
    - annotate_overrides
    # - avoid_annotating_with_dynamic # conflicts with always_specify_types
    # - avoid_as # required for implicit-casts: true
    - avoid_bool_literals_in_conditional_expressions
    # - avoid_catches_without_on_clauses # we do this commonly
    # - avoid_catching_errors # we do this commonly
    #    - avoid_classes_with_only_static_members
    # - avoid_double_and_int_checks # only useful when targeting JS runtime
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    # - avoid_escaping_inner_quotes # not yet tested
    - avoid_field_initializers_in_const_classes
    # - avoid_function_literals_in_foreach_calls
    # - avoid_implementing_value_types # not yet tested
    - avoid_init_to_null
    # - avoid_js_rounded_ints # only useful when targeting JS runtime
    - avoid_null_checks_in_equality_operators
    # - avoid_positional_boolean_parameters # not yet tested
    - avoid_print # not yet tested
    # - avoid_private_typedef_functions # we prefer having typedef (discussion in https://github.com/flutter/flutter/pull/16356)
    # - avoid_redundant_argument_values # not yet tested
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    # - avoid_returning_null # there are plenty of valid reasons to return null
    # - avoid_returning_null_for_future # not yet tested
    - avoid_returning_null_for_void
    # - avoid_returning_this # there are plenty of valid reasons to return this
    # - avoid_setters_without_getters # not yet tested
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    # - avoid_type_to_string # we do this commonly
    - avoid_types_as_parameter_names
    # - avoid_types_on_closure_parameters # conflicts with always_specify_types
    # - avoid_unnecessary_containers # not yet tested
    - avoid_unused_constructor_parameters
    #    - avoid_void_async
    # - avoid_web_libraries_in_flutter # not yet tested
    - await_only_futures
    - cancel_subscriptions
    # - cascade_invocations # not yet tested
    # - close_sinks # not reliable enough
    # - comment_references # blocked on https://github.com/flutter/flutter/issues/20765

    - control_flow_in_finally
    # - curly_braces_in_flow_control_structures # not required by flutter style
    # - diagnostic_describe_all_properties # not yet tested

    # - do_not_use_environment # we do this commonly
    #    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    #   - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    # - invariant_booleans # too many false positives: https://github.com/dart-lang/linter/issues/811
    - iterable_contains_unrelated_type
    # - join_return_with_assignment # not required by flutter style
    - leading_newlines_in_multiline_strings

    - list_remove_unrelated_type
    # - literal_only_boolean_expressions # too many false positives: https://github.com/dart-lang/sdk/issues/34181
    # - missing_whitespace_between_adjacent_strings # not yet tested
    - no_adjacent_strings_in_list
    # - no_default_cases # too many false positives
    - no_duplicate_case_values
    #    - no_logic_in_create_state
    # - no_runtimeType_toString # ok in tests; we enable this only in packages/

    # - null_closures # not required by flutter style
    ## opposite of always_specify_types
    #    - omit_local_variable_types
    # - one_member_abstracts # too many false positives
    # - only_throw_errors # https://github.com/flutter/flutter/issues/5792
    - overridden_fields
    # - package_names # non conforming packages in sdk
    - package_prefixed_library_names
    - parameter_assignments # we do this commonly
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    #   - prefer_asserts_with_message # not required by flutter style
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    # - prefer_constructors_over_static_methods # far too many false positives
    - prefer_contains
    - prefer_single_quotes # opposite of prefer_double_quotes
    - prefer_equal_for_default_values
    # - prefer_expression_function_bodies # conflicts with https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#consider-using--for-short-functions-and-methods
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    # - prefer_function_declarations_over_variables # not yet tested
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    # - prefer_int_literals # not yet tested
    # - prefer_interpolation_to_compose_strings # not yet tested
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    # - prefer_mixin # https://github.com/dart-lang/language/issues/32
    # - prefer_null_aware_operators # disable until NNBD, see https://github.com/flutter/flutter/pull/32711#issuecomment-492930932
    # - prefer_relative_imports # not yet tested
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    # - provide_deprecation_message # not yet tested
    # - public_member_api_docs # enabled on a case-by-case basis; see e.g. packages/analysis_options.yaml
    - recursive_getters
    # - sized_box_for_whitespace # not yet tested
    # - sort_child_properties_last # not yet tested
    # - sort_constructors_first
    # - sort_pub_dependencies # prevents separating pinned transitive dependencies
    #    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    # - type_annotate_public_apis # subset of always_specify_types
    - type_init_formals
    # - unawaited_futures # too many false positives
    # - unnecessary_await_in_return # not yet tested
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    # - unnecessary_final # conflicts with prefer_final_locals
    - unnecessary_getters_setters
    # - unnecessary_lambdas # has false positives: https://github.com/dart-lang/linter/issues/498
    - unnecessary_new
    - unnecessary_null_aware_assignments
    # - unnecessary_null_checks # not yet tested
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings # not yet tested
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    # - unsafe_html # not yet tested
    - use_full_hex_values_for_flutter_colors
    # - use_function_type_syntax_for_parameters # not yet tested
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors # not yet tested
    - use_late_for_private_fields_and_variables
    - use_raw_strings
    - use_rethrow_when_possible
    # - use_setters_to_change_properties # not yet tested
    # - use_string_buffers # has false positives: https://github.com/dart-lang/sdk/issues/34182
    # - use_to_and_as_if_applicable # has false positives, so we prefer to catch this by code-review
    - valid_regexps
    - void_checks

```

3. Run `flutter analyze`

### Expected results

Everything run ok like a liting tools.

### Actual results

`Oops; flutter has exited unexpectedly: "FileSystemException: Directory listing failed, path =
'/Users/flutter/examples/' (OS Error: No such file or directory, errno = 2)".
A crash report has been written to /Users/Desktop/project_dir/flutter_05.log.`

### Code sample

No Code

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Crash Log

<details>
<summary>Logs</summary>

```console
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter analyze

## exception

FileSystemException: FileSystemException: Directory listing failed, path = '/Users/harrytran/flutter/examples/' (OS Error: No such file or directory, errno = 2)


#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      FlutterCommandRunner._gatherProjectPaths (package:flutter_tools/src/runner/flutter_command_runner.dart:309:8)
#5      FlutterCommandRunner.getRepoPackages.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:298:40)
#6      ExpandIterator.moveNext (dart:_internal/iterable.dart:481:31)
#7      MappedIterator.moveNext (dart:_internal/iterable.dart:390:19)
#8      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#9      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#10     new List.of (dart:core-patch/array_patch.dart:51:28)
#11     Iterable.toList (dart:core/iterable.dart:470:12)
#12     FlutterCommandRunner.getRepoPackages (package:flutter_tools/src/runner/flutter_command_runner.dart:300:8)
#13     AnalyzeCommand.runCommand (package:flutter_tools/src/commands/analyze.dart:170:17)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1374:12)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#21     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>


## flutter doctor


[!] Flutter (Channel unknown, 3.3.9, on macOS 13.3.1 22E772610a darwin-arm, locale en-US)
    ! Flutter version 3.3.9 on channel unknown at /Users/flutter
    ! Upstream repository unknown
    • Framework revision b8f7f1f986 (7 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.3345.108

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>
