### ISSUE TITLE
failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug

### ISSUE THREAD

**Issue by discoveruz** [flutter/flutter#130222]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce
```console
Launching lib/main.dart on iPhone 14 in debug mode...
main.dart:1
Xcode build done.                                           33.1s
Failed to build iOS app
Swift Compiler Error (Xcode): Using bridging headers with module interfaces is unsupported

Uncategorized (Xcode): Command SwiftDriver emitted errors but did not return a nonzero exit code to indicate failure

Error (Xcode): no such module '__ObjC'
/Users/developer/Library/Developer/Xcode/DerivedData/Runner-ehbwirhhihsvqbalntxqsnjtbgfz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.swiftinterface:9:18

Error (Xcode): failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug
/Users/developer/Library/Developer/Xcode/DerivedData/Runner-ehbwirhhihsvqbalntxqsnjtbgfz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.swiftinterface:0:0

Error (Xcode): no such module '__ObjC'
/Users/developer/Library/Developer/Xcode/DerivedData/Runner-ehbwirhhihsvqbalntxqsnjtbgfz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.private.swiftinterface:9:18

Error (Xcode): failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug
/Users/developer/Library/Developer/Xcode/DerivedData/Runner-ehbwirhhihsvqbalntxqsnjtbgfz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.private.swiftinterface:0:0

Could not build the application for the simulator.
Error launching application on iPhone 14.
Exited
```
**Runner.swiftinterface**
```swiftinterface
// swift-interface-format-version: 1.0
// swift-compiler-version: Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
// swift-module-flags: -target arm64-apple-ios13.0-simulator -enable-objc-interop -enable-library-evolution -swift-version 5 -enforce-exclusivity=checked -Onone -module-name Runner
// swift-module-flags-ignorable: -enable-bare-slash-regex
import Flutter
import Swift
import UIKit
import _Concurrency
import _StringProcessing
@_exported import __ObjC
```

### Expected results

---

### Actual results

not running app in ios

### Code sample

<details><summary>Code sample</summary>

**AppDelegate.swift**
```swift
import UIKit
import Flutter
// import awesome_notifications
// import shared_preferences_foundation

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
        // SwiftAwesomeNotificationsPlugin.setPluginRegistrantCallback { registry in          
          // SwiftAwesomeNotificationsPlugin.register(
            // with: registry.registrar(forPlugin: "io.flutter.plugins.awesomenotifications.AwesomeNotificationsPlugin")!)          
          // SharedPreferencesPlugin.register(
            // with: registry.registrar(forPlugin: "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")!)
      // }

      return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**pubspec.yaml**

```yaml
environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  flutter_screenutil: 5.7.0
  shared_preferences: 2.2.0 
  intl_phone_field: ^3.1.0
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  equatable: ^2.0.5
  keyboard_dismisser: ^3.0.0
  easy_localization: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.2.3
  animations: ^2.0.7
  flutter_snake_navigationbar: ^0.6.1
  flutter_countdown_timer: ^4.1.0
  pin_code_fields: ^7.4.0
  modal_bottom_sheet: ^3.0.0-pre
  file_picker: ^5.2.5
  voice_message_package: ^0.0.74
  path_provider: ^2.0.11
  dio: ^4.0.6
  url_launcher: ^6.1.9
  video_player: ^2.5.1
  pusher_channels_flutter: ^2.1.0
  firebase_core: ^2.6.0
  pusher_beams: ^1.1.1
  awesome_notifications: any
  clipboard: ^0.1.3
  avatar_glow: ^2.0.2
  audio_waveforms: ^1.0.4
  badges: ^3.1.1
  # geolocator: ^9.0.2 #setting android and ios
  # yandex_mapkit: ^3.2.0 #setting android and ios
  vibration: ^1.8.1 #setting android and ios
#  flutter_yandex_ads: ^1.0.0+1 #setting android and ios

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/fonts/
    - assets/translations/
    - assets/images/home/
    - assets/images/flags/
    - assets/images/onboarding/
    - assets/images/slides/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets\fonts\Montserrat-Regular.ttf
          weight: 400
        - asset: assets\fonts\Montserrat-Medium.ttf
          weight: 500
        - asset: assets\fonts\Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Montserrat-Bold.ttf
          weight: 700
```
Podfile
```podfile
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                  config.build_settings['OTHER_SWIFT_FLAGS'] = '-no-verify-emitted-module-interface'
             end
        end
 end
    installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1260" alt="image" src="https://github.com/flutter/flutter/assets/83630149/42361cb7-6f9a-4f68-9a31-74a9f1bc3701">

</details>

### Logs

<details><summary>Logs</summary>

flutter run -v
```console
[  +11 ms] Failed to build iOS app
[   +1 ms] Swift Compiler Error (Xcode): Using bridging headers with module interfaces is unsupported
           
[   +1 ms] Uncategorized (Xcode): Command SwiftDriver emitted errors but did not return a nonzero exit code to indicate failure
           
[        ] Error (Xcode): no such module '__ObjC'

/Users/developer/Library/Developer/Xcode/DerivedData/Runner-ehbwirhhihsvqbalntxqsnjtbgfz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-
           normal/arm64/Runner.swiftinterface:9:18
           
[   +2 ms] Error (Xcode): failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug

/Users/developer/Library/Developer/Xcode/DerivedData/Runner-ehbwirhhihsvqbalntxqsnjtbgfz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-
           normal/arm64/Runner.swiftinterface:0:0
           
[        ] Error (Xcode): no such module '__ObjC'

/Users/developer/Library/Developer/Xcode/DerivedData/Runner-ehbwirhhihsvqbalntxqsnjtbgfz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-
           normal/arm64/Runner.private.swiftinterface:9:18
           
[        ] Error (Xcode): failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug

/Users/developer/Library/Developer/Xcode/DerivedData/Runner-ehbwirhhihsvqbalntxqsnjtbgfz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-
           normal/arm64/Runner.private.swiftinterface:0:0
           
[   +1 ms] Could not build the application for the simulator.
[   +3 ms] Error launching application on iPhone 14.
[   +1 ms] "flutter run" took 26,895ms.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:722:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +251 ms] ensureAnalyticsSent: 250ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-UZ)
    • Flutter version 3.7.5 on channel stable at /Users/developer/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (5 months ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/developer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • 7AEB5845-A86D-4EF0-B0C7-8E1FD80AF881 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
