### ISSUE TITLE
ContextMenuController does not dispose OverlayEntry.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#130467]
To repro:

1. Remove notDisposedAllowList from packages/flutter/test/material/text_form_field_test.dart 
2. Then see the modified test is failing

PR that adds notDisposedAllowList: https://github.com/flutter/flutter/pull/130468

Creation call stack: https://raw.githubusercontent.com/polina-c/spikes/master/notes/failures/2023-July-12/text_form_field_test_107.txt

**Comment by huycozy** [comment]
Hi @polina-c 
I can't find `notDisposedAllowList ` from `packages/flutter/test/material/text_form_field_test.dart`. Could you give a simple use case of ContextMenuController that causes this issue?

**Comment by polina-c** [comment]
notDisposedAllowList is added by PR that is linked in description: https://github.com/flutter/flutter/pull/130468/files

**Comment by polina-c** [comment]
Feel free to tweet me or to chat me, to setup GVC. I will be happy to explain details.

**Comment by polina-c** [comment]
This PR reproduces the issue: https://github.com/flutter/flutter/pull/130742/checks?check_run_id=15111129175

**Comment by polina-c** [comment]
This PR reproduces the issue: https://github.com/flutter/flutter/pull/130743/checks?check_run_id=15111140218

**Comment by goderbauer** [comment]
cc @justinmc

**Comment by justinmc** [comment]
* When [the test](https://github.com/flutter/flutter/blob/81b0e9f1113c390f9e0b09d0eea1b4c13029c615/packages/flutter/test/material/text_form_field_test.dart#L107) is run with testWidgetsWithLinkTracking, then the EditableTextState (and the whole widget tree in pumpWidget?) is never disposed at the end of the test.  If I change it to testWidgets, then it is disposed.
  * (Using testWidgetsWithLinkTracking) Bizarrely, if I comment out [this line](https://github.com/flutter/flutter/blob/81b0e9f1113c390f9e0b09d0eea1b4c13029c615/packages/flutter/lib/src/widgets/text_selection.dart#L1370) where _handles is set to null, then EditableTextState does get disposed.  This is true even if I hack out all of the accesses of _handles after it's set to null, leading me to think something deep behind the scenes is doing this.

@polina-c Is there anything that testWidgetsWithLeakTracking does that could prevent the widget tree from being disposed?

<details>

<summary>Here's a simpler test that still reproduces the problem:</summary>

```dart
  testWidgetsWithLeakTracking('leak test', (WidgetTester tester) async {
    final TextEditingController controller = TextEditingController(
      text: 'blah1 blah2',
    );
    await tester.pumpWidget(
      MaterialApp(
        home: Material(
          child: Center(
            child: TextField(
              controller: controller,
            ),
          ),
        ),
      ),
    );

    final Offset startBlah1 = textOffsetToPosition(tester, 0);
    await tester.tapAt(startBlah1);
    await tester.pump(const Duration(milliseconds: 100));
    await tester.tapAt(startBlah1);
    await tester.pumpAndSettle();
  },
    variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.macOS }),
    skip: kIsWeb, // [intended] we don't supply the cut/copy/paste buttons on the web.
  );
```

</details>

**Comment by polina-c** [comment]
Thanks. For some reasons with leak tracker BuildOwner.finalizeTree is invoked 6 times instead of 7, where 7th one triggers disposal. 

At the moment I am refactoring leak tracker for performance, that may side effect in this side effect disappearing.
So, reassigning the issue to me and shelving till after refactoring.

**Comment by polina-c** [comment]
@justinmc

It seems after refactoring flakiness disappeared. Returning the issue to you.

Remaining leaks:

```
            notDisposed:
              total: 4
              objects:
                RestorableBool:
                  test: can use the desktop cut/copy/paste buttons on Windows and Linux
                  identityHashCode: 1004453175
                RestorableStringN:
                  test: can use the desktop cut/copy/paste buttons on Windows and Linux
                  identityHashCode: 715878348
                RestorableBool:
                  test: can use the desktop cut/copy/paste buttons on Windows and Linux
                  identityHashCode: 69970577
                RestorableStringN:
                  test: can use the desktop cut/copy/paste buttons on Windows and Linux
                  identityHashCode: 283658580
```

To see callstack for creation, set this config:
```
leakTrackingTestConfig: const LeakTrackingTestConfig.debugnotDisposed()
```
