### ISSUE TITLE
Running the App Ends up opening Problem Report for Runner in iOS

### ISSUE THREAD

**Issue by yahu1031** [flutter/flutter#130451]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Any working project with the following dependencies.

```yaml
name: sky_migration
description: Sky application migration
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^14.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  lottie: ^2.3.2
  permission_handler: ^10.2.0
  responsive_sizer: ^3.1.1
  rounded_loading_button: ^2.1.0
  sky_client: # custom package
    path: /Users/mr.minnu/Documents/sky_client
  tabler_icons: ^2.5.0+1
  url_launcher: ^6.1.11

dependency_overrides:
  # intl: ^0.18.1
  collection: ^1.17.2

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/lottie/
    - assets/images/
    - assets/images/ic/
    - assets/images/ic/banners/
    - assets/images/ic/flags/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/SatoshiRegular.otf
        - weight: 500
        - asset: assets/fonts/SatoshiBold.otf
        - weight: 700
```

## NOTE:
This was observed in `Sonoma - MacOS 14.0 (23A5286i) - Beta`
```console
Model Name:	MacBook Pro
Chip:	Apple M2 Pro
Total Number of Cores:	10 (6 performance and 4 efficiency)
Memory:	16 GB
System Firmware Version:	10151.0.172.0.3
OS Loader Version:	10151.0.172.0.3
System Version:	macOS 14.0 (23A5286i)
Kernel Version:	Darwin 23.0.0
Boot Volume:	Macintosh HD
Boot Mode:	Normal
Secure Virtual Memory:	Enabled
System Integrity Protection:	Enabled
```

### Expected results

Should open the app normally.

### Actual results

Opens `Problem Report for Runner` Logs - [runner.log](https://github.com/flutter/flutter/files/12033162/runner.log)

### Code sample

[sky-master.zip](https://github.com/flutter/flutter/files/12033143/sky-master.zip)
[sky_client-master.zip](https://github.com/flutter/flutter/files/12033144/sky_client-master.zip)

### Screenshots or Video

Not available

### Logs

[Flutter run verbose logs](https://github.com/flutter/flutter/files/12033153/flutter-logs.log)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.5, on macOS 14.0 23A5286i darwin-arm64, locale en-IN)
    • Flutter version 3.10.5 on channel stable at /Users/mr.minnu/Development/flutter3
    ! Warning: `flutter` on your path resolves to /Users/mr.minnu/Development/flutter/bin/flutter, which is not inside your current
      Flutter SDK checkout at /Users/mr.minnu/Development/flutter3. Consider adding /Users/mr.minnu/Development/flutter3/bin to the
      front of your path.
    ! Warning: `dart` on your path resolves to /Users/mr.minnu/Development/flutter/bin/dart, which is not inside your current Flutter
      SDK checkout at /Users/mr.minnu/Development/flutter3. Consider adding /Users/mr.minnu/Development/flutter3/bin to the front of
      your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update
      checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mr.minnu/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A5195m
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64 • Android 14 (API 34) (emulator)
    • iPhone 14 Pro Max (mobile)  • D30B3598-14D4-4CB1-8810-1DC22222C0C1 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-17-0
      (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64  • macOS 14.0 23A5286i darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>
