### ISSUE TITLE
Build app size increasing 2.5x bigger after updating pubspec.lock

### ISSUE THREAD

**Issue by mimamch** [flutter/flutter#130800]
## Details

**Target Platform: Android**
**Target OS version/browser: Android 8+**
**Devices: Pixel 4 API 30**

## Logs

app build output .apk or .aab increased 2.5x bigger after I updated pubspec.lock.
this issue reproduce when i am add new dependencies, and pubspect.lock will change/updating automatically

before updating :**Built build\app\outputs\flutter-apk\app-release.apk (27.2MB).**
after updating : **Built build\app\outputs\flutter-apk\app-release.apk (65.1MB).**

EDITED: I have delete all my dependencies and smaller build size (2x MB) 

<summary>Logs</summary>

Here is my pubspec.yaml

```
dependencies:
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  dio_http_cache_lts: ^0.4.1
  esc_pos_utils_plus: ^2.0.1+6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.2.10+1
  fluttercontactpicker: ^4.7.0
  go_router: ^7.1.1
  google_fonts: ^4.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  move_to_background: ^1.0.2
  onesignal_flutter: ^3.4.1
  path_provider: ^2.0.11
  pdf: ^3.8.4
  permission_handler: ^10.2.0
  print_bluetooth_thermal: ^1.0.5
  printing: ^5.11.0
  share_plus: ^6.3.0
  shimmer: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.2.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
```

here is my main.dart file, i trying to delete all code and still has big depedencies.

```
import 'package:flutter/material.dart';

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(),
    );
  }
}

```

```
$ flutter analyze
Analyzing KYS-reload-app...                                             
No issues found! (ran in 25.2s)
```

```
$ flutter doctor -v
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19043.1526], locale en-ID)
    • Flutter version 3.10.5 on channel stable at D:\SOFTWARE\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\SOFTWARE\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = D:\SOFTWARE\Android\Sdk
    • Java binary at: D:\SOFTWARE\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
    • Visual Studio at D:\SOFTWARE\Visual Studio
    • Visual Studio Community 2022 version 17.3.32811.315
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at D:\SOFTWARE\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.62

[√] Network resources
    • All expected network resources are available.

• No issues found!

Noxious@DESKTOP-0DPF4CN MINGW64 /d/Project Flutter/KYS-reload-app (master)
$ flutter doctor -v
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19043.1526], locale en-ID)
    • Flutter version 3.10.5 on channel stable at D:\SOFTWARE\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\SOFTWARE\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = D:\SOFTWARE\Android\Sdk
    • Java binary at: D:\SOFTWARE\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
    • Visual Studio at D:\SOFTWARE\Visual Studio
    • Visual Studio Community 2022 version 17.3.32811.315
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at D:\SOFTWARE\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1526]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 107.0.1418.62

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>
