### ISSUE TITLE
[go_router_builder] Back from web navigator with extra implementing toJson does not work

### ISSUE THREAD

**Issue by ZaraclaJ** [flutter/flutter#130990]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new Flutter project
2.a. In the `pubspec.yaml` file, add `go_router: ^9.1.0` as dependencies
2.b. In the `pubspec.yaml` file, add `build_runner: ^2.4.6`and `go_router_builder: ^2.2.2` as dev_dependencies
3. Replace the main file code by the following :

<details><summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'main.g.dart';

class CustomClass {
  const CustomClass(this.value);

  final String value;

  String toJson() => value;
}

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      routerConfig: router,
    );
  }
}

final GoRouter router = GoRouter(
  routes: [
    ...$appRoutes,
  ],
  initialLocation: const PageARoute().location,
);

@TypedGoRoute<PageARoute>(
  path: '/pageA',
  routes: <TypedGoRoute<GoRouteData>>[
    TypedGoRoute<PageBRoute>(
      path: 'pageB',
      routes: <TypedGoRoute<GoRouteData>>[
        TypedGoRoute<PageCRoute>(
          path: 'pageC',
        ),
      ],
    )
  ],
)
class PageARoute extends GoRouteData {
  const PageARoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return _Page(
      title: 'Page A',
      onPressed: () {
        const PageBRoute(
          $extra: CustomClass('extra data'),
        ).go(context);
      },
    );
  }
}

class PageBRoute extends GoRouteData {
  const PageBRoute({
    this.$extra,
  });

  final CustomClass? $extra;

  @override
  Widget build(BuildContext context, GoRouterState state) {
    final extra = $extra;
    return _Page(
      title: 'Page B',
      extra: extra,
      onPressed: () {
        const PageCRoute().go(context);
      },
    );
  }
}

class PageCRoute extends GoRouteData {
  const PageCRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const _Page(
      title: 'Page C',
    );
  }
}

class _Page extends StatelessWidget {
  const _Page({Key? key, required this.title, this.extra, this.onPressed}) : super(key: key);

  final String title;
  final CustomClass? extra;
  final void Function()? onPressed;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          children: [
            Text(title),
            if (extra != null) Text(extra!.value),
            if (onPressed != null)
              ElevatedButton(
                onPressed: onPressed,
                child: const Text('Next'),
              ),
          ],
        ),
      ),
    );
  }
}
```

</details>

4. Run the following commands :
`flutter pub get`
`flutter pub run build_runner build --delete-conflicting-outputs`
This will generate the following file `main.g.dart`:

<details><summary>main.g.dart</summary>

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'main.dart';

// **************************************************************************
// GoRouterGenerator
// **************************************************************************

List<RouteBase> get $appRoutes => [
      $pageARoute,
    ];

RouteBase get $pageARoute => GoRouteData.$route(
      path: '/pageA',
      factory: $PageARouteExtension._fromState,
      routes: [
        GoRouteData.$route(
          path: 'pageB',
          factory: $PageBRouteExtension._fromState,
          routes: [
            GoRouteData.$route(
              path: 'pageC',
              factory: $PageCRouteExtension._fromState,
            ),
          ],
        ),
      ],
    );

extension $PageARouteExtension on PageARoute {
  static PageARoute _fromState(GoRouterState state) => const PageARoute();

  String get location => GoRouteData.$location(
        '/pageA',
      );

  void go(BuildContext context) => context.go(location);

  Future<T?> push<T>(BuildContext context) => context.push<T>(location);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location);

  void replace(BuildContext context) => context.replace(location);
}

extension $PageBRouteExtension on PageBRoute {
  static PageBRoute _fromState(GoRouterState state) => PageBRoute(
        $extra: state.extra as CustomClass?,
      );

  String get location => GoRouteData.$location(
        '/pageA/pageB',
      );

  void go(BuildContext context) => context.go(location, extra: $extra);

  Future<T?> push<T>(BuildContext context) =>
      context.push<T>(location, extra: $extra);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location, extra: $extra);

  void replace(BuildContext context) =>
      context.replace(location, extra: $extra);
}

extension $PageCRouteExtension on PageCRoute {
  static PageCRoute _fromState(GoRouterState state) => const PageCRoute();

  String get location => GoRouteData.$location(
        '/pageA/pageB/pageC',
      );

  void go(BuildContext context) => context.go(location);

  Future<T?> push<T>(BuildContext context) => context.push<T>(location);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location);

  void replace(BuildContext context) => context.replace(location);
}

```

</details>

5. Run the code in web (chrome) in debug mode.
6. The app contains 3 pages (page A, page B, page C), the next button is used to navigate (page A => page B => page C)
7. You can back on the previous page by using the back from the app bar (working well) or with the navigator back button (not working for page C => page B)

### Expected results

From page C, using the back from the navigator should return on the page B 

### Actual results

The back navigation from C to B (using navigator back) raised an exception :

`Expected a value of type 'CustomClass?', but got one of type 'String'`

<details><summary>Full exception</summary>

```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown while dispatching notifications for
GoRouteInformationProvider:
Expected a value of type 'CustomClass?', but got one of type 'String'
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 121:3       castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 529:12  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 417:9        as
packages/go_router/src/route_data.dart 97:53                                      factoryImpl
packages/go_router/src/route_data.dart 107:28                                     redirect
packages/go_router/src/configuration.dart 466:34                                  [_getRouteLevelRedirect]
packages/go_router/src/configuration.dart 462:9                                   processRouteRedirect
packages/go_router/src/configuration.dart 484:14                                  [_getRouteLevelRedirect]
packages/go_router/src/configuration.dart 424:13                                  processTopLevelRedirect
packages/go_router/src/configuration.dart 440:16                                  processRedirect
packages/go_router/src/configuration.dart 446:14                                  redirect
packages/go_router/src/parser.dart 149:10                                         [_redirect]
packages/go_router/src/parser.dart 74:12                                          parseRouteInformationWithDependencies
packages/flutter/src/widgets/router.dart 704:12                                   [_processRouteInformation]
packages/flutter/src/widgets/router.dart 723:5                                    [_handleRouteInformationProviderNotification]
packages/flutter/src/foundation/change_notifier.dart 403:24                       notifyListeners
packages/go_router/src/information_provider.dart 141:11                           notifyListeners
packages/go_router/src/information_provider.dart 236:5                            [_platformReportsNewRouteInformation]
packages/go_router/src/information_provider.dart 267:5                            didPushRouteInformation
packages/flutter/src/widgets/binding.dart 685:23                                  _handlePushRouteInformation
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 784:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 584:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 657:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15               <fn>
The GoRouteInformationProvider sending notification was:
  Instance of 'GoRouteInformationProvider'
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

This seems to happen because the class used in extra implement the `toJson` method :
```dart
class CustomClass {
  const CustomClass(this.value);

  final String value;

  String toJson() => value;
}
  ```
  
  This seems related to the following code of `go_router-9.1.0` (`match.dart`) : 

  ```dart
   static Map<Object?, Object?> _toPrimitives(String location, Object? extra,
      {List<Map<Object?, Object?>>? imperativeMatches, String? pageKey}) {
    String? encodedExtra;
    try {
      encodedExtra = json.encoder.convert(extra);
    } on JsonUnsupportedObjectError {/* give up if not serializable */}
    return <Object?, Object?>{
      RouteMatchListCodec._locationKey: location,
      if (encodedExtra != null) RouteMatchListCodec._extraKey: encodedExtra,
      if (imperativeMatches != null)
        RouteMatchListCodec._imperativeMatchesKey: imperativeMatches,
      if (pageKey != null) RouteMatchListCodec._pageKey: pageKey,
    };
  }
```

On the generated code from `go_router_builder`, this exception should be fix if we do not directly cast the `state.extra`.

Replace this code :
```dart
 static PageBRoute _fromState(GoRouterState state) => PageBRoute(
        $extra: state.extra as CustomClass?,
      );
```
With the following :
```dart
static PageBRoute _fromState(GoRouterState state) {
    final extra = state.extra;
    return PageBRoute(
      $extra: extra is CustomClass? ? extra : null,
    );
  }
```

### Code sample

<details><summary>pubspec.yaml</summary>

```yaml
name: go_router_builder_extra
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^9.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

</details>

<details><summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'main.g.dart';

class CustomClass {
  const CustomClass(this.value);

  final String value;

  String toJson() => value;
}

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      routerConfig: router,
    );
  }
}

final GoRouter router = GoRouter(
  routes: [
    ...$appRoutes,
  ],
  initialLocation: const PageARoute().location,
);

@TypedGoRoute<PageARoute>(
  path: '/pageA',
  routes: <TypedGoRoute<GoRouteData>>[
    TypedGoRoute<PageBRoute>(
      path: 'pageB',
      routes: <TypedGoRoute<GoRouteData>>[
        TypedGoRoute<PageCRoute>(
          path: 'pageC',
        ),
      ],
    )
  ],
)
class PageARoute extends GoRouteData {
  const PageARoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return _Page(
      title: 'Page A',
      onPressed: () {
        const PageBRoute(
          $extra: CustomClass('extra data'),
        ).go(context);
      },
    );
  }
}

class PageBRoute extends GoRouteData {
  const PageBRoute({
    this.$extra,
  });

  final CustomClass? $extra;

  @override
  Widget build(BuildContext context, GoRouterState state) {
    final extra = $extra;
    return _Page(
      title: 'Page B',
      extra: extra,
      onPressed: () {
        const PageCRoute().go(context);
      },
    );
  }
}

class PageCRoute extends GoRouteData {
  const PageCRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const _Page(
      title: 'Page C',
    );
  }
}

class _Page extends StatelessWidget {
  const _Page({Key? key, required this.title, this.extra, this.onPressed}) : super(key: key);

  final String title;
  final CustomClass? extra;
  final void Function()? onPressed;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          children: [
            Text(title),
            if (extra != null) Text(extra!.value),
            if (onPressed != null)
              ElevatedButton(
                onPressed: onPressed,
                child: const Text('Next'),
              ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details><summary>main.g.dart</summary>

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'main.dart';

// **************************************************************************
// GoRouterGenerator
// **************************************************************************

List<RouteBase> get $appRoutes => [
      $pageARoute,
    ];

RouteBase get $pageARoute => GoRouteData.$route(
      path: '/pageA',
      factory: $PageARouteExtension._fromState,
      routes: [
        GoRouteData.$route(
          path: 'pageB',
          factory: $PageBRouteExtension._fromState,
          routes: [
            GoRouteData.$route(
              path: 'pageC',
              factory: $PageCRouteExtension._fromState,
            ),
          ],
        ),
      ],
    );

extension $PageARouteExtension on PageARoute {
  static PageARoute _fromState(GoRouterState state) => const PageARoute();

  String get location => GoRouteData.$location(
        '/pageA',
      );

  void go(BuildContext context) => context.go(location);

  Future<T?> push<T>(BuildContext context) => context.push<T>(location);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location);

  void replace(BuildContext context) => context.replace(location);
}

extension $PageBRouteExtension on PageBRoute {
  static PageBRoute _fromState(GoRouterState state) => PageBRoute(
        $extra: state.extra as CustomClass?,
      );

  String get location => GoRouteData.$location(
        '/pageA/pageB',
      );

  void go(BuildContext context) => context.go(location, extra: $extra);

  Future<T?> push<T>(BuildContext context) =>
      context.push<T>(location, extra: $extra);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location, extra: $extra);

  void replace(BuildContext context) =>
      context.replace(location, extra: $extra);
}

extension $PageCRouteExtension on PageCRoute {
  static PageCRoute _fromState(GoRouterState state) => const PageCRoute();

  String get location => GoRouteData.$location(
        '/pageA/pageB/pageC',
      );

  void go(BuildContext context) => context.go(location);

  Future<T?> push<T>(BuildContext context) => context.push<T>(location);

  void pushReplacement(BuildContext context) =>
      context.pushReplacement(location);

  void replace(BuildContext context) => context.replace(location);
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/34095172/78c69ec4-59ed-477d-9f92-fa97c7433d45

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F770820d darwin-x64, locale fr-FR)
    • Flutter version 3.10.5 on channel stable at /Users/jordanalcaraz/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/jordanalcaraz/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>
