### ISSUE TITLE
`dart doc` warns about Flutter's `gen_l10n`

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#130969]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Follow the steps to add `l10n` support: https://docs.flutter.dev/accessibility-and-localization/internationalization
2. Run `dart doc`

### Expected results

`dart doc` runs without warnings

### Actual results

Docs are generated with warnings

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

export 'package:flutter_gen/gen_l10n/app_localizations.dart';

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this)!;
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
$ dart doc --dry-run
  warning: private API of package:synthetic_package is reexported by libraries in other packages: 
    from l10n.AppLocalizations.AppLocalizations: (file:///<elided>/.dart_tool/flutter_gen/gen_l10n/app_localizations.dart:63:3)
    referred to by l10n: (file:///<elided>/lib/l10n/l10n.dart:1:1)
  warning: private API of package:synthetic_package is reexported by libraries in other packages:
    from l10n.lookupAppLocalizations: (file:///<elided>/.dart_tool/flutter_gen/gen_l10n/app_localizations.dart:1042:18)
    referred to by l10n: (file:///<elided>/lib/l10n/l10n.dart:1:1)
Found 2 warnings and 0 errors.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Versi¢n 10.0.22621.1992], locale es-ES)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2022.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @Zazo032 
I check this issue with [my sample code](https://github.com/huycozy/Flutter-demo-l10n) but there is no warning from the output (command: `dart doc --dry-run`). Please try my sample code. If you can't see the issue, please provide a minimal sample code so we may verify this. Thanks!

**Comment by Zazo032** [comment]
Seems like our approach was either incomplete or outdated.

Our old `l10n.yaml`:
```yaml
arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated.txt
```

Your `l10n.yaml`:
```yaml
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
output-dir: lib/l10n
output-class: AppLocalizations
nullable-getter: false
untranslated-messages-file: untranslated_messages.txt
```

Our new `l10n.yaml`:
```yaml
arb-dir: lib/l10n/arb
nullable-getter: false
output-class: AppLocalizations
output-dir: lib/l10n
output-localization-file: app_localizations.dart
synthetic-package: false
template-arb-file: app_en.arb
untranslated-messages-file: untranslated.txt
```

Our old `l10n.dart`:
```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

export 'package:flutter_gen/gen_l10n/app_localizations.dart';

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this)!;
}
```

Our new `l10n.dart`:
```dart
import 'package:craftos/l10n/app_localizations.dart';
import 'package:flutter/widgets.dart';

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
```

After some changes to those files, we no longer get the error when running `dart doc` ⭐
