### ISSUE TITLE
collapse when using local_sesssion_time together

### ISSUE THREAD

**Issue by KevinTsangSKH** [flutter/flutter#132556]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

Web

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec</summary>
<p>

```
name: ccs
description: Case Care System

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  flutter_redux: ^0.10.0
  intl: ^0.18.0
  package_info_plus: ^4.1.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  flutter_side_menu: ^0.4.0
  responsive_table: ^0.2.0+2
  excel: ^2.1.0
  dropdown_button2: ^2.3.5
  flutter_tags_x: ^1.1.0
  toggle_switch: ^2.1.0
  flutter_reorderable_list: ^1.3.0
  shared_preferences: ^2.1.2
  json_annotation: ^4.8.1
  dart_jsonwebtoken: ^2.8.2
  flutter_spinkit: ^5.2.0
  dio: ^5.3.2
  fluttertoast: ^8.2.2
  reflectable: ^4.0.5
  collection: ^1.17.1
  loader_overlay: ^2.2.0
  jiffy: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.12
  universal_html: ^2.2.3
  dropdown_search: ^5.0.6
  go_router: ^10.0.0
  local_session_timeout: ^2.3.0
  #flutter_keyboard_visibility: ^5.4.1

  ### Modify the source code from 3rd parties
  flutter_login:
    path: packages/flutter_login-master
  easy_localization:
    path: packages/easy_localization-develop
  resizable_widget:
    path: packages/resizable_widget-main
  ### Modify the source code from 3rd parties

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.6.2
  hive_generator: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - env.etx
    - assets/translations/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

``` 

</p>
</details> 

### Steps to reproduce

1. GoRouter add redirect but no refreshListenable
2. When using local_session_timeout to call sessionStateStream.add(SessionState.stopListening) or sessionStateStream.add(SessionState.startListening)
3. the redirect will re-execute
4. sessionStateStream is StreamController<SessionState>()

### Expected results

```
call sessionStateStream.add(SessionState.stopListening) or sessionStateStream.add(SessionState.startListening) will not call redirect, only execute the context.go will call redirect
``` 

### Actual results

```
once call sessionStateStream.add(SessionState.stopListening) or sessionStateStream.add(SessionState.startListening)  will trigger the redirect make the page refresh
``` 

### Code sample

```dart
GoRouter(
    initialLocation: CommonRoutes.index,
    navigatorKey: navigatorKey,
    redirect: (BuildContext context, GoRouterState state) {
      final db = Database.box;
      final toast = Toast(context);
....
if (isTimeout) {
        db.deleteAll(
            [Database.accessToken, Database.user, Database.centerLanguages]);
        Future.delayed(const Duration(seconds: 1)).then((value) =>
            toast.showToast(ToastType.error, tr('IdleTimeoutMessage'),
                durationTime: Duration.secondsPerDay * 3));
        return CommonRoutes.index;
      }
.....


ServicesBinding.instance.keyboard.addHandler((KeyEvent event) {
      if (event is KeyDownEvent) {
        sessionStateStream.add(SessionState.stopListening);
      } else if (event is KeyUpEvent) {
        sessionStateStream.add(SessionState.startListening);
      }
      return false;
    });

``` 

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
