### ISSUE TITLE
Shared app launcher icon for both platforms

### ISSUE THREAD

**Issue by MarkOSullivan94** [flutter/flutter#13293]
Most apps share the icon they use for both platforms and so it would be great if it was possible to specify an app launcher icon for both the iOS project and Android project without having to delve into both projects and adding image files in two separate locations. 

I think the current way is specified within this Stack Overflow question: https://stackoverflow.com/questions/43928702/how-to-change-the-application-icon-on-flutter

The assets and images guide describes how you can have shared assets among both projects, perhaps this would be the best place to include shared app launcher icons? Default projects could come with this asset directory preloaded with the default flutter icon which is used as an app launcher icon for both apps.

Perhaps for the very few cases where developers want to specify slightly different app launcher icons, you could configure the `pubspec.yaml` so that you can declare if you want a shared app launcher icon or if not, could specify what app icon from the asset directory that you want for each platform.

```
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Line for having a shared app launcher icon
  uses-shared-app-icon: true

  # if above line isn't used then the next two lines would be required to supply icon for both platforms
  android-app-icon: 'assets/android-icon/*'
  ios-app-icon: 'assets/ios-icon/*

```

Not sure if this idea would be a good way to specify the shared icons but having the ability to do so would be greatly appreciated.
