### ISSUE TITLE
Doc on how to use fonts from Google Fonts directly

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13292]
Not clear from https://flutter.io/custom-fonts/ whether it's the right practice is to download the font from Google Fonts first and then add them locally to the Flutter project or whether CDN hosted font files can be cached and managed by the pub mechanism directly.

**Comment by xster** [comment]
Doesn't seem to work if I just add
```
  fonts:
    - family: Nunito
      fonts:
        - asset: https://fonts.gstatic.com/s/nunito/v9/ZvK1I6E_n0tqLlSfX5iQt4X0hVgzZQUfRDuZrPvH3D8.woff2
```
to pubspec.yaml
