### ISSUE TITLE
`[In App Purchase]`: Migrate Google Play Billing to either 5.2.1 or 6.0.1 and above for Android 14

### ISSUE THREAD

**Issue by petermusembi69** [flutter/flutter#133331]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Update to flutter version 3.13.1
2. Add [in_app_purchase: ^3.1.8](https://pub.dev/packages/in_app_purchase) package
3. Bump `compileSdkVersion` & `targetSdkVersion` to 34
4. Create an app bundle and upload to play console

### Expected results

Create a play store release successfully

### Actual results

Play console throw the following error.

**This app targets Android 14 or above, and your current Play Billing Library version doesn't support Android 14. To target the latest Android version, please update your PBL version to either 5.2.1, or 6.0.1 and above.**

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
    • Flutter version 3.13.1 on channel stable at C:\src\flutter
    ! Warning: `dart` on your path resolves to C:\Program Files\Dart\dart-sdk\bin\dart.exe, which is not inside your
      current Flutter SDK checkout at C:\src\flutter. Consider adding C:\src\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (2 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 116.0.5845.98
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 116.0.1938.54

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by stuartmorgan** [comment]
The plugin was [already updated to 6.0.1](https://github.com/flutter/packages/blob/bd4a8eb6a424ab6a0aa0e9aea907c2964e56f91a/packages/in_app_purchase/in_app_purchase_android/android/build.gradle#L64). Could you provide your `pubspec.lock` file (or at least the parts about any `in_app_purchase_*` packages)?

> * Update to flutter version 3.13.1
> * Add [in_app_purchase: ^3.1.8](https://pub.dev/packages/in_app_purchase) package
> * Bump `compileSdkVersion` & `targetSdkVersion` to 34
> * Create an app bundle and upload to play console

Did you follow these steps in a new app, adding `in_app_purchase` to an app that had previously not used it at all? Doing so should have given you the latest version of all the dependencies, whereas if you updated just `in_app_purchase` in an existing app you would get different results?

**Comment by camsim99** [comment]
@zoeyfan FYI, this is a bug that concerns monetization. Please let us know if you think it should be escalated further.

**Comment by petermusembi69** [comment]
Hey @stuartmorgan 
>Could you provide your pubspec.lock file (or at least the parts about any in_app_purchase_* packages)?
<details><summary>pubspec.lock parts</summary>

```yaml
  in_app_purchase:
    dependency: "direct main"
    description:
      name: in_app_purchase
      sha256: "944b9a9d8cce41a0ac057dd6984c942f01bfed9a8106247f2f630b06f5db8aab"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.8"
  in_app_purchase_android:
    dependency: transitive
    description:
      name: in_app_purchase_android
      sha256: c1b8eba009db6002c6dd5ae1110d2445297dfd83b9c11e8f9ddb7411cb9dbee6
      url: "https://pub.dev"
    source: hosted
    version: "0.3.0+5"
  in_app_purchase_platform_interface:
    dependency: transitive
    description:
      name: in_app_purchase_platform_interface
      sha256: "356a855d5a1f92b0d06a739e702fd732b56ee1914e6ba0f2ba08a2cb8e2cc3f8"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.4"
  in_app_purchase_storekit:
    dependency: transitive
    description:
      name: in_app_purchase_storekit
      sha256: f598169999604d9c40c28bb6f47b58e03c8c498e344cdc015f937a1f528982ab
      url: "https://pub.dev"
    source: hosted
    version: "0.3.6+4"
```

</details>

> Did you follow these steps in a new app, adding `in_app_purchase` to an app that had previously not used it at all? 

No, I updated the `in app purchase` version to an app that was previously using it prior flutter 3.13.* release

> Doing so should have given you the latest version of all the dependencies, whereas if you updated just `in_app_purchase` in an existing app you would get different results?

Why is this case? What are the implications of the different results?

I was thinking may be this could be the issue,  https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/android/build.gradle#L29

Also btw, I only use `in app purchase` on iOS only, is there a way I can disable this on android and not show the `in-app purchase flag on the description of my app on google.play`?
