### ISSUE TITLE
Label in Badge is not in center (flutter web)

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#133801]
A minor, but irritating enough. Observed on Web. Not so bad in android native:

Badge label (Text) is not centered inside the badge in web, it is slightly leveled above center: 
![image](https://github.com/flutter/flutter/assets/11217296/2087b832-62d5-4b43-9314-47850582371c)

Better in native:
![image](https://github.com/flutter/flutter/assets/11217296/46fe9605-35b2-4029-9cf0-3794728d2616)

Code example: 

```
IconButton(
          onPressed: !present?null:(){
            if(widget.homeListKey?.currentState?.mounted==true){
              (widget.homeListKey?.currentState as HomeList2State).expanded["show_order_pictures_${widget.order.frmNo}-${widget.order.ordNo}"] = !(expanded??false);
              setState(() {});
            }
          }, 
          icon:Badge(
            label: Text("$count"),
            child: Icon(expanded==true?Icons.compress_outlined:Icons.expand_outlined)
          )
        )
```

Flutter doctor: 
```
PS C:\FlutterProjects\mwork> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 3.14.0-0.1.pre, on Microsoft Windows [Version 10.0.22621.2134], locale nb-NO)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.3)
[√] Android Studio (version 2022.2)
[√] Android Studio (version 2022.3)
[√] Android Studio (version 2022.2)
[√] Android Studio (version 2022.3)
[√] Android Studio (version 2023.1)
[√] Android Studio (version 2023.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

```

pubspec.yaml:
```
name: mwork
description: A tool for handling orders in Norva24.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.1+29

environment:
  #sdk: ">=2.16.0-80.1.beta <4.0.0"
  sdk: ">=2.17.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:

  #_fe_analyzer_shared: 51.0.0
  #analyzer: ^6.2.0
  #camera_web: ^0.3.0
  #characters: ^1.2.1
  #material_color_utilities: ^0.1.5

  #webview_flutter: 4.0.1


  #flutter_webview_plugin:
  #  git: https://github.com/nuc134r/flutter_webview_plugin.git

  msal_js: ^2.14.0

  #--- aad-oauth Azure Active Directory login by Earlybyte ---
  aad_oauth: ^0.4.4
  #aad_oauth:
  #  git: https://github.com/Earlybyte/aad_oauth.git


  provider: ^6.0.3
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  #introduction_screen: ^3.0.2
  intl: ^0.18.0
  #socket_io_client: ^2.0.0-beta.4-nullsafety.0
  flutter:
    sdk: flutter

  #--jwt--- makes it possible to analyze jwt
  jwt_decode: ^0.3.1

  #---Swagger changes---
  chopper: ^6.0.0
  json_annotation: ^4.5.0

  #---Google Maps---
  google_maps_flutter: ^2.4.0
  google_maps_flutter_web: ^0.5.3
  google_static_maps_controller: ^1.0.0

  #---Pointer interceptor
  pointer_interceptor: ^0.9.3+4

  #---Location data (GPS)---
  #location: ^4.4.0
  location: ^5.0.2+1

  #---Get---
  get: ^4.6.5

  #---Flutter Bloc---
  flutter_bloc: ^8.0.1

  #---Settings / preferences ---
  #flutter_settings_screens: ^0.3.2-null-safety
  pref: ^2.6.0

  #---Camera function---
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  path: ^1.8.3

  #---image_picker function
  image_picker: ^1.0.2
  image_picker_for_web: ^3.0.0

  #---Floor functionality---
  #floor: ^1.2.0

  #---Drift functionality---
  drift: ^2.3.0
  #drift:
  #  git:
  #    url: https://github.com/simolus3/drift.git
  #    ref: develop
  #    path: drift
  #drift: 1.7.1
  sqlite3_flutter_libs: ^0.5.7


  #---Url launcher
  url_launcher: ^6.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  #---badges for icons
  badges: ^3.0.1

  #---flutter webview plugin displace
  #flutter_webview_plugin:
  #    git: https://github.com/nuc134r/flutter_webview_plugin.git

  #---logging:
  logging: ^1.0.2
  firebase_core: ^2.0.0
  firebase_crashlytics: ^3.0.1
  package_info_plus: ^4.0.0
  firebase_performance: ^0.9.0+1

  #---db_inspector
  drift_db_viewer: ^2.0.0

  #---validators
  email_validator: ^2.1.17

  #---list extensions
  collection: ^1.16.0

  #---flag
  flag: ^7.0.0

  #---data table 2
  data_table_2: ^2.4.2

  #---devuce info plus
  device_info_plus: ^9.0.2
  label_marker: ^1.0.1
  custom_info_window: ^1.0.1

  #---file picker
  file_picker: ^5.3.3

  #---http
  http: ^0.13.6
  http_parser: ^4.0.2

  #---dio
  dio: ^5.3.2

  #---exif
  exif: ^3.1.4

  #---flutter_media_metadata
  #flutter_media_metadata: 1.0.0+1

  #---date_util
  #date_util: 0.1.4

  #---flutter_native_splash
  #flutter_native_splash: ^2.2.16


  #---Animated splashscreen:
  #animated_splash_screen: ^1.3.0
#---Icons---



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_round.png"
  adaptive_icon_background: "#666666"

dev_dependencies:
  flutter_test:
    sdk: flutter

  #---swagger changes---
  build_runner: ^2.1.11
  chopper_generator: ^6.0.0
  json_serializable: ^6.2.0
  swagger_dart_code_generator: ^2.8.7

  #---Launcher icons---
  flutter_launcher_icons: ^0.13.0

  #---floor generators---
  #floor_generator: ^1.2.0

  #---drift generators---
  drift_dev: ^2.3.0
  #drift_dev: 1.7.1

  #--- analyzer
  #analyzer: ^4.1.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



```
