### ISSUE TITLE
Federated plugins should only include the assets of the specific platform package 

### ISSUE THREAD

**Issue by littleGnAl** [flutter/flutter#134029]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm working on a plugin by following the [Federated plugins](https://docs.flutter.dev/packages-and-plugins/developing-packages#federated-plugins), and I want to bundle my custom js implementation as an asset of the web specific platform package. e.g., the project structure

```
hello
|___hello
|      |___lib/
|      |___pubspec.yaml
|
|___hello_web
       |___lib/
       |___pubspec.yaml
       |___assets/aa.js
```
`hello/hello/pubspec.yaml`
```yaml
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  hello_web:
    path: ../hello_web

...

flutter:
  plugin:
    platforms:
      ...
      web:
        default_package: hello_web
```

`hello/hello_web/pubspec.yaml`
```yaml
flutter:
  plugin:
    platforms:
      web:
        pluginClass: HelloWebWeb
        fileName: hello_web_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/aa.js
```
If I build the example for the non-web platform, say that for Android, run the `flutter build apk`, the `hello/hello_web/assets/aa.js` still be included in the apk.

<img width="775" alt="image" src="https://github.com/flutter/flutter/assets/8847263/de103062-0f44-4772-a818-f87a855e62f2">

### Proposal

Only include the assets of the specific platform package
