### ISSUE TITLE
[Linux] Gdk-CRITICAL **: 12:31:09.378: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

### ISSUE THREAD

**Issue by mubin986** [flutter/flutter#135547]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. I've successfully built my flutter app using snapcraft for linux core22
2. after builing the snap i've publish it to snapcraft store edge channel
3. then, install my app using `snap install ostad --edge` command which also works fine
4. but, cannot open my app. after openning my app from terminal, it shows the error

### Expected results

App should run perfectly

### Actual results

Gtk-Message: 12:31:08.895: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(ostad_app:22066): Gtk-WARNING **: 12:31:08.999: GTK+ module /snap/ostad/58/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 12:31:08.999: Failed to load module "canberra-gtk-module"

(ostad_app:22066): Gtk-WARNING **: 12:31:09.004: GTK+ module /snap/ostad/58/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 12:31:09.004: Failed to load module "canberra-gtk-module"

(ostad_app:22066): Gdk-CRITICAL **: 12:31:09.378: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
libGL error: did not find extension DRI_Mesa version 1
libGL error: failed to load driver: iris
libGL error: did not find extension DRI_Mesa version 1
libGL error: failed to load driver: iris
libGL error: did not find extension DRI_Mesa version 1
libGL error: failed to load driver: swrast

** (ostad_app:22066): WARNING **: 12:31:10.563: Failed to start Flutter renderer: Unable to create a GL context
package:media_kit_libs_linux registered.

### Code sample

 <details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
>Gtk-Message: 12:31:08.895: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

Please check [this](https://stackoverflow.com/a/75819818/5921933) to see if it can help. And please provide the output of `flutter doctor -v` as well.

**Comment by hungryemon** [comment]
Tried the given solution but it does not work.

### **this issue only happens in production(downloaded and installed from snap store).**
works well while testing in debug/release mode.
So flutter doctor -v output does not matter in this case. Still providing current output below:

```
[✓] Flutter (Channel stable, 3.13.2, on Ubuntu 22.04.2 LTS 6.2.0-33-generic,
    locale en_US.UTF-8)
    • Flutter version 3.13.2 on channel stable at
      /home/dev/flutter_linux_3.7.10-stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (5 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/dev/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /snap/android-studio/126/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.2)
    • Android Studio at /snap/android-studio/126/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.72.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.2 LTS
      6.2.0-33-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by huycozy** [comment]
> gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

I see there is a similar issue https://github.com/flutter/flutter/issues/130514 reported for this error that has been fixed recently and is available on beta/master channel: https://github.com/flutter/engine/commit/2408de624915a92d4b16d878a8a3debdc2d674c8. Could you try switching to these channel and confirm?

```
flutter channel master
flutter upgrade
```

**Comment by mubin986** [comment]
> > gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
> 
> I see there is a similar issue #130514 reported for this error that has been fixed recently and is available on beta/master channel: [flutter/engine@2408de6](https://github.com/flutter/engine/commit/2408de624915a92d4b16d878a8a3debdc2d674c8). Could you try switching to these channel and confirm?
> 
> ```
> flutter channel master
> flutter upgrade
> ```

Not working. Still same problem~!

**Comment by huycozy** [comment]
Can you try running your project in `release` mode to see if the issue also appears locally? 

If the issue only appears after being released to Snap store, it could be related to snapcraft tool builds, please share your `snapcraft.yaml` file content as well. 

Regarding to this, please check this if it can help: https://forum.snapcraft.io/t/libgl-error-did-not-find-extension-dri-mesa-version-1/36528/4
```
libGL error: did not find extension DRI_Mesa version 1
libGL error: failed to load driver: iris
libGL error: did not find extension DRI_Mesa version 1
libGL error: failed to load driver: iris
libGL error: did not find extension DRI_Mesa version 1
libGL error: failed to load driver: swrast
```

**Comment by mubin986** [comment]
> Can you try running your project in `release` mode to see if the issue also appears locally?
> 
> If the issue only appears after being released to Snap store, it could be related to snapcraft tool builds, please share your `snapcraft.yaml` file content as well.
> 
> Regarding to this, please check this if it can help: https://forum.snapcraft.io/t/libgl-error-did-not-find-extension-dri-mesa-version-1/36528/4
> 
> ```
> libGL error: did not find extension DRI_Mesa version 1
> libGL error: failed to load driver: iris
> libGL error: did not find extension DRI_Mesa version 1
> libGL error: failed to load driver: iris
> libGL error: did not find extension DRI_Mesa version 1
> libGL error: failed to load driver: swrast
> ```

Here is my snapcraft.yml

```
name: abc
version: git
summary: Abc - App
description: Abc is a linux app
confinement: strict
base: core22
grade: stable
license: GPL-3.0+
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
assumes:
  - snapd2.46

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.13.5
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    prime:
      - -*

  abc:
    after: [ flutter-git ]
    plugin: nil
    source: .
    override-build: |
      set -eux
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
    build-packages:
      - mpv
      - gir1.2-keybinder-3.0
      - keybinder-3.0-doc
      - libmpv-dev
      - libkeybinder-3.0-0
      - libkeybinder-3.0-dev
      - libslang2 # Added libslang2 package
    stage-packages:
      - mpv
      - libmpv-dev
      - libkeybinder-3.0-0
      - libglu1-mesa # Added libglu1-mesa package
      - freeglut3 # Added freeglut3 package
      - libslang2 # Added libslang2 package
      - libsmbclient
      - libblas3

apps:
  abc:
    command: bin/abc_app
    desktop: meta/gui/abc.desktop
    extensions: [gnome]
    plugs:
      - network
      - desktop
      - lxd
      - home
      - audio-playback
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/lib:$LD_LIBRARY_PATH
      # LD_LIBRARY_PATH: $SNAPCRAFT_PART_INSTALL/abc/usr/lib/x86_64-linux-gnu:$SNAPCRAFT_PART_INSTALL/abc/lib:$LD_LIBRARY_PATH

```
