### ISSUE TITLE
Windows framework_tests_widgets is 2.04% flaky

### ISSUE THREAD

**Issue by fluttergithubbot** [flutter/flutter#135577]
The post-submit test builder `Windows framework_tests_widgets` had a flaky ratio 2.04% for the past (up to) 100 commits, which is above our 2.00% threshold.

One recent flaky example for a same commit: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20framework_tests_widgets/13226
Commit: https://github.com/flutter/flutter/commit/6d88ade70af6a7d0b961b14058a9f9283999337a

Flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20framework_tests_widgets/13226
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20framework_tests_widgets/13225

Recent test runs:
https://flutter-dashboard.appspot.com/#/build?taskFilter=Windows%20framework_tests_widgets

Please follow https://github.com/flutter/flutter/wiki/Reducing-Test-Flakiness#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness).

**Comment by goderbauer** [comment]
All the failures linked above are related to leak tracking:

```
01:59 +3633 ~78 -1: C:/b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/routes_test.dart: ModalRoute (tearDownAll) [E]
  Expected: leak free
    Actual: <Instance of 'Leaks'>
     Which: contains leaks:
            # The text is generated by leak_tracker.
            # For leak troubleshooting tips open:
            # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
            notDisposed:
              total: 2
              objects:
                FocusNode:
                  test: Can autofocus a TextField nested in a Focus in a route.
                  identityHashCode: 901896964
                TextEditingController:
                  test: Can autofocus a TextField nested in a Focus in a route.
                  identityHashCode: 830505743
            
            
  
  package:matcher                                                  expect
  package:flutter_test/src/widget_tester.dart 458:18               expect
  package:leak_tracker_flutter_testing/src/test_widgets.dart 81:5  _tearDownTestingWithLeakTracking
  ===== asynchronous gap ===========================
  dart:async                                                       _CustomZone.registerBinaryCallback
```

@polina-c Can you please take a look at what causes these flakes?
