### ISSUE TITLE
Get several `A disposed RenderObject was mutated.` messages while creating `RawChip`s

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#135703]
I canot find the source for this error in my log, other than it has someting to do with creating / laying out my RawChips definitions.

I cannot find any useful hints in Stackoverflow etc. to track this error.

But there is a reference [here](https://fossies.org/linux/flutter/packages/flutter/lib/src/rendering/object.dart)  (line 1881)

on a file called: `Member "flutter-3.13.6/packages/flutter/lib/src/rendering/object.dart" (27 Sep 2023, 203827 Bytes) of package /linux/misc/flutter-3.13.6.tar.gz:`

The error looks like this: 

<details><summary>Logs</summary>
<p>

```
======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
A disposed RenderObject was mutated.

The disposed RenderObject was: _RenderChip#ef52b DISPOSED
  needs compositing
  parentData: MISSING (can use size)
  constraints: BoxConstraints(unconstrained)
  size: Size(161.3, 28.0)
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
packages/flutter/src/rendering/object.dart 1939:9                                 <fn>
packages/flutter/src/rendering/object.dart 2043:9                                 get [_debugCanPerformMutations]
packages/flutter/src/rendering/object.dart 2254:12                                markNeedsLayout
packages/flutter/src/rendering/box.dart 2381:11                                   markNeedsLayout
packages/flutter/src/animation/listener_helpers.dart 161:19                       notifyListeners
packages/flutter/src/animation/animation_controller.dart 830:5                    [_tick]
packages/flutter/src/scheduler/ticker.dart 249:12                                 [_tick]
packages/flutter/src/scheduler/binding.dart 1325:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1177:11                               <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13          forEach
packages/flutter/src/scheduler/binding.dart 1175:16                               handleBeginFrame
packages/flutter/src/scheduler/binding.dart 1092:5                                [_handleBeginFrame]
dart-sdk/lib/async/zone.dart 1415:13                                              _rootRunUnary
dart-sdk/lib/async/zone.dart 1308:19                                              runUnary
dart-sdk/lib/async/zone.dart 1217:7                                               runUnaryGuarded
lib/_engine/engine/platform_dispatcher.dart 1297:9                                invoke1
lib/_engine/engine/platform_dispatcher.dart 227:5                                 invokeOnBeginFrame
lib/_engine/engine/initialization.dart 177:45                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
The AnimationController notifying listeners was: AnimationController#f3f18(⏮ 0.000; paused)
====================================================================================================


```

</p>
</details> 

Here's as snippet of the widget that produces the error...

<details><summary>Code Sample</summary>
<p>

```
SingleChildScrollView(
          controller: topicScrollController,
          scrollDirection: Axis.horizontal,
          child: Padding(
            padding: const EdgeInsets.all(4.0),
            child: Wrap(
              spacing: 4,
              children: [
                StreamBuilder<UserSelection?>(
                  stream: globals.mWorkDatabase.getUserSelection(SettingKey.userSelectionMyDayDate).watchSingleOrNull(),
                  builder: (context, snapshot){
                    if(snapshot.hasError){
                      return RawChip(
                          key: dateChipKey,
                          backgroundColor: Colors.red,
                          avatar: const Icon(Icons.today),
                          deleteIcon: const Icon(Icons.warning_amber),
                          label: Text(
                              snapshot.error.toString()
                          )
                      );
                    }

                    if(snapshot.connectionState==ConnectionState.waiting){
                      return RawChip(
                          key: dateChipKey,
                          showCheckmark: false,
                          avatar: const Icon(Icons.today),
                          deleteIcon: const CircularProgressIndicator(),
                          deleteButtonTooltipMessage: "",
                          onDeleted: (){},
                          label: const Text("Loading date...")
                      );
                    }

                    if(snapshot.hasData) {
                      var dateSelection = snapshot.data;

                      if (dateSelection != null) {
                        return RawChip(
                          tooltip: (dateSelection.intValue==null)?"":dateSelection.intValue.toDateTimeFromDateInt()?.toDayOfWeekString(),
                          key: dateChipKey,
                          showCheckmark: false,
                          avatar: const Icon(Icons.today),
                          selected: selectedChip == 5,
                          selectedColor: Colors.lightBlue,
                          label: Text("${dateSelection.intValue
                              .toDateMonthYearString()}"),
                          deleteIcon: Icon((dateSelection.boolValue??false)?Icons.check_box_outlined:Icons.check_box_outline_blank),
                          deleteButtonTooltipMessage: "Show only this date",
                          onDeleted: () async {

                            await globals.mWorkDatabase.into(globals.mWorkDatabase.userSelectionsTable).insertOnConflictUpdate(
                              UserSelectionsTableCompanion(
                                  selection: const drift.Value(SettingKey.userSelectionMyDayDate),
                                  intValue: drift.Value(dateSelection.intValue??-1),
                                  boolValue: drift.Value(!(dateSelection.boolValue??false))
                              ),

                            );
                          },
                          onPressed: () {
                            if (selectedChip == 5) {
                              selectedChip = null;
                            } else {
                              selectedChip = 5;
                            }
                            setState(() {});


                          },
                        );
                      }
                    }

                    return RawChip(
                      key: dateChipKey,
                      showCheckmark: false,
                      selected: selectedChip==5,
                      backgroundColor: Colors.red,
                      selectedColor: Colors.red[900],
                      avatar: const Icon(Icons.today),
                      label: const Text("No date selected !", style: TextStyle(color: Colors.yellow),),
                      deleteIcon: const Icon(Icons.warning_amber_outlined),
                      onDeleted: (){},
                      onPressed: (){
                        if(selectedChip==5) {
                          selectedChip = null;
                        } else {
                          selectedChip = 5;
                        }
                        setState(() {});
                      },
                      deleteButtonTooltipMessage: "Select a date !",
                    );


                  }
                ),
                StreamBuilder<GetSelectedCar2Result?>(
                  stream: globals.mWorkDatabase.getSelectedCar2(SettingKey.userSelectionSelectedCar, SettingKey.userSelectionSelectedFirm).watchSingleOrNull(),
                  builder: (context, snapshot) {
                    if(snapshot.hasError){
                      return RawChip(
                          key: carChipKey,
                          backgroundColor: Colors.red,
                          avatar: const Icon(Icons.local_shipping_outlined),
                          deleteIcon: const Icon(Icons.warning_amber),
                          label: Text(
                              snapshot.error.toString()
                          )
                      );
                    }

                    if(snapshot.connectionState==ConnectionState.waiting){
                      return RawChip(
                        key: carChipKey,
                        showCheckmark: false,
                          avatar: const Icon(Icons.local_shipping_outlined),
                          deleteIcon: const CircularProgressIndicator(),
                          deleteButtonTooltipMessage: "",
                          onDeleted: (){},
                          label: const Text("Loading car...")
                      );
                    }

                    if(snapshot.hasData){
                      var car = snapshot.data;

                      return RawChip(
                        tooltip: car?.nm,
                        key: carChipKey,
                        showCheckmark: false,
                        selected: selectedChip==0,
                        selectedColor: Colors.lightBlue,
                        avatar: const Icon(Icons.local_shipping_outlined),
                        label: Text(detailedInfo?"${car?.rNo??"??"}: ${car?.nm??"<not set>"}":"${car?.rNo??"??"}"),
                        deleteIcon: Icon((car?.checked??false)?Icons.check_box_outlined:Icons.check_box_outline_blank),
                        deleteButtonTooltipMessage: "Show only this car",
                        onDeleted: ()async{
                          await globals.mWorkDatabase.into(globals.mWorkDatabase.userSelectionsTable).insertOnConflictUpdate(
                            UserSelectionsTableCompanion(
                                selection: const drift.Value(SettingKey.userSelectionSelectedCar),
                                intValue: drift.Value(car?.rNo??-1),
                                boolValue: drift.Value(!(car?.checked??false))
                            ),

                          );
                        },
                        onPressed: (){
                          if(selectedChip==0) {
                            selectedChip = null;
                          } else {
                            selectedChip = 0;
                          }
                          setState(() {});

                          loadCars();

                        },
                      );
                    } else {
                      return RawChip(
                        key: carChipKey,
                        showCheckmark: false,
                        selected: selectedChip==0,
                        backgroundColor: Colors.red,
                        selectedColor: Colors.red[900],
                        avatar: const Icon(Icons.local_shipping_outlined),
                        label: const Text("No car selected !", style: TextStyle(color: Colors.yellow),),
                        deleteIcon: const Icon(Icons.warning_amber_outlined),
                        onDeleted: (){},
                        onPressed: (){
                          if(selectedChip==0) {
                            selectedChip = null;
                          } else {
                            selectedChip = 0;
                          }
                          setState(() {});

                          loadCars();
                        },
                        deleteButtonTooltipMessage: "Reselect car !",
                      );
                    }
                  }
                ),
                StreamBuilder<GetSelectedOffice2Result?>(
                  stream: globals.mWorkDatabase.getSelectedOffice2(SettingKey.userSelectionSelectedOffice,SettingKey.userSelectionSelectedFirm).watchSingleOrNull(),
                  builder: (context, snapshot) {

                    if(snapshot.hasError){
                      return RawChip(
                          key: officeChipKey,
                          backgroundColor: Colors.red,
                          avatar: const Icon(Icons.home_work_outlined),
                          deleteIcon: const Icon(Icons.warning_amber),
                          label: Text(
                              snapshot.error.toString()
                          )
                      );
                    }

                    if(snapshot.connectionState==ConnectionState.waiting){
                      return RawChip(
                        key: officeChipKey,
                          avatar: const Icon(Icons.home_work_outlined),
                          deleteIcon: const CircularProgressIndicator(),
                          deleteButtonTooltipMessage: "",
                          onDeleted: (){},
                          label: const Text("Loading office...")
                      );
                    }

                    if(snapshot.hasData){
                      var office = snapshot.data;
                      return RawChip(
                        tooltip: office?.nm,
                        key: officeChipKey,
                        showCheckmark: false,
                        selected: selectedChip==1,
                        selectedColor: Colors.lightBlue,
                        avatar: const Icon(Icons.home_work_outlined),
                        label: Text(detailedInfo?"${office?.rNo??"??"}: ${office?.nm??"<not set>"}":office?.rNo??"??"),
                        deleteIcon: Icon((office?.checked??false)?Icons.check_box_outlined:Icons.check_box_outline_blank),
                        deleteButtonTooltipMessage: "Show only this office",
                        onDeleted: ()async{
                          await globals.mWorkDatabase.into(globals.mWorkDatabase.userSelectionsTable).insertOnConflictUpdate(
                            UserSelectionsTableCompanion(
                                selection: const drift.Value(SettingKey.userSelectionSelectedOffice),
                                intValue: drift.Value(int.tryParse(office?.rNo??"-1")??-1),
                                boolValue: drift.Value(!(office?.checked??false))
                            ),

                          );
                        },
                        onPressed: ()async{
                          if(selectedChip==1) {
                            selectedChip = null;
                          } else {
                            selectedChip = 1;
                          }
                          setState(() {});

                          loadOffices();

                        },
                      );
                    } else {
                      return RawChip(
                        key: officeChipKey,
                        showCheckmark: false,
                        selected: selectedChip==1,
                        backgroundColor: Colors.red,
                        selectedColor: Colors.red[900],
                        avatar: const Icon(Icons.home_work_outlined),
                        label: const Text("No office selected !", style: TextStyle(color: Colors.yellow),),
                        deleteIcon: const Icon(Icons.warning_amber_outlined),
                        onDeleted: (){},
                        onPressed: (){
                          if(selectedChip==1) {
                            selectedChip = null;
                          } else {
                            selectedChip = 1;
                          }
                          setState(() {});

                          loadOffices();

                        },
                        deleteButtonTooltipMessage: "You need to select an office !",
                      );
                    }
                  }
                ),
                StreamBuilder<GetOperatorResult?>(
                    stream: globals.mWorkDatabase.getOperator(SettingKey.userSelectionSelectedOperator).watchSingleOrNull(),
                    builder: (context, snapshot) {

                      if(snapshot.hasError){
                        return RawChip(
                            backgroundColor: Colors.red,
                            avatar: const Icon(Icons.person_outlined),
                            deleteIcon: const Icon(Icons.warning_amber),
                            label: Text(
                                snapshot.error.toString()
                            )
                        );
                      }

                      if(snapshot.connectionState==ConnectionState.waiting){
                        return RawChip(
                            avatar: const Icon(Icons.person_outlined),
                            deleteIcon: const CircularProgressIndicator(),
                            deleteButtonTooltipMessage: "",
                            onDeleted: (){},
                            label: const Text("Loading operator...")
                        );
                      }

                      if(snapshot.hasData){
                        var operator = snapshot.data;
                        return RawChip(
                          tooltip: operator?.nm,
                          showCheckmark: false,
                          selected: selectedChip==4,
                          selectedColor: Colors.lightBlue,
                          avatar: const Icon(Icons.person_outlined),
                          label: Text(detailedInfo?"${operator?.empNo}: ${operator?.nm}":"${operator?.empNo}"),
                          deleteIcon: Icon((operator?.checked??false)?Icons.check_box_outlined:Icons.check_box_outline_blank),
                          deleteButtonTooltipMessage: "Show only this operator",
                          onDeleted: ()async{

                            await globals.mWorkDatabase.into(globals.mWorkDatabase.userSelectionsTable).insertOnConflictUpdate(
                                UserSelectionsTableCompanion(
                                    selection: const drift.Value(SettingKey.userSelectionSelectedOperator),
                                    intValue: drift.Value(operator?.empNo??-1),
                                    boolValue: drift.Value(!(operator?.checked??false))
                                ),

                            );

                          },
                          onPressed: (){
                            if(selectedChip==4) {
                              selectedChip = null;
                            } else {
                              selectedChip = 4;
                            }
                            setState(() {});
                          },
                        );
                      } else {
                        return const RawChip(
                          backgroundColor: Colors.red,
                          avatar: Icon(Icons.person_outlined),
                          label: Text("No operator found !", style: TextStyle(color: Colors.yellow),),
                          deleteIcon: Icon(Icons.warning_amber_outlined),
                          deleteButtonTooltipMessage: "Please try to login again !",
                        );
                      }


                    }
                ),
                StreamBuilder<OrderFirm?>(
                  stream: globals.mWorkDatabase.getSelectedFirm2(SettingKey.userSelectionSelectedFirm,SettingKey.userSelectionSelectedCountry).watchSingleOrNull(),
                  builder: (context, snapshot) {

                    if(snapshot.hasError){
                      return RawChip(
                        key: firmChipKey,
                          backgroundColor: Colors.red,
                          avatar: const Icon(Icons.apartment_outlined),
                          deleteIcon: const Icon(Icons.warning_amber),
                          label: Text(
                              snapshot.error.toString()
                          )
                      );
                    }

                    if(snapshot.connectionState==ConnectionState.waiting){
                      return RawChip(
                        key: firmChipKey,
                          showCheckmark: false,
                          avatar: const Icon(Icons.apartment_outlined),
                          deleteIcon: const CircularProgressIndicator(),
                          deleteButtonTooltipMessage: "",
                          onDeleted: (){},
                          label: const Text("Loading firm...")
                      );
                    }

                    if(snapshot.hasData){
                      var firm = snapshot.data;
                      return RawChip(
                        tooltip: firm?.nm,
                        key: firmChipKey,
                        selected: selectedChip==2,
                        showCheckmark: false,
                        selectedColor: Colors.lightBlue,
                        avatar: const Icon(Icons.apartment_outlined),
                        label: Text(detailedInfo?"${firm?.frmNo??"??"}: ${firm?.nm??"<not set>"}":"${firm?.frmNo??"??"}"),
                        onPressed: () async {
                          if(selectedChip==2){
                            selectedChip=null;
                          } else {
                            selectedChip = 2;
                          }
                          setState(() {});

                          loadFirms();

                        },
                      );
                    } else {
                      return RawChip(
                        key: firmChipKey,
                        showCheckmark: false,
                        selected: selectedChip==2,
                        backgroundColor: Colors.red,
                        selectedColor: Colors.red[900],
                        avatar: const Icon(Icons.apartment_outlined),
                        label: const Text("No firm selected !", style: TextStyle(color: Colors.yellow),),
                        deleteIcon: const Icon(Icons.warning_amber_outlined),
                        deleteButtonTooltipMessage: "Select a firm if available !",
                        onDeleted: (){},
                        onPressed: (){
                          if(selectedChip==2) {
                            selectedChip = null;
                          } else {
                            selectedChip = 2;
                          }
                          setState(() {});

                          loadFirms();

                        },
                      );
                    }

                  }
                ),
                StreamBuilder<OrderFirmCountry?>(
                  stream: globals.mWorkDatabase.getSelectedCountry2(SettingKey.userSelectionSelectedCountry).watchSingleOrNull(),
                  builder: (context, snapshot) {

                    if(snapshot.hasError){
                      return RawChip(
                        key: countryChipKey,
                          backgroundColor: Colors.red,
                          avatar: const Icon(Icons.flag_outlined),
                          deleteIcon: const Icon(Icons.warning_amber),
                          label: Text(
                              snapshot.error.toString()
                          )
                      );
                    }

                    if(snapshot.connectionState==ConnectionState.waiting){
                      return RawChip(
                        key: countryChipKey,
                          avatar: const Icon(Icons.flag_outlined),
                          deleteIcon: const CircularProgressIndicator(),
                          deleteButtonTooltipMessage: "",
                          onDeleted: (){},
                          label: const Text("Loading country...")
                      );
                    }

                    if(snapshot.hasData){
                      var country = snapshot.data;
                      return RawChip(
                        tooltip: country?.nm,
                        key: countryChipKey,
                        showCheckmark: false,
                        selected: selectedChip==3,
                        selectedColor: Colors.lightBlue,
                        avatar: Flag.fromString(
                          country?.flag??'XX',
                          height: 25,
                          width: 30,
                          fit: BoxFit.scaleDown,
                          borderRadius: 2,
                          replacement: const SizedBox(height: 25, width: 30,),
                        ),
                        label: Text(detailedInfo?"${country?.ctryNo??"??"}: ${country?.nm??"<not set>"}":"${country?.ctryNo??"??"}"),
                        onPressed: (){
                          if(selectedChip==3) {
                            selectedChip = null;
                          } else {
                            selectedChip = 3;
                          }
                          setState(() {});

                          getCountries();

                        },
                      );
                    } else {
                      return RawChip(
                        key: countryChipKey,
                        showCheckmark: false,
                        selected: selectedChip==3,
                        backgroundColor: Colors.red,
                        selectedColor: Colors.red[900],
                        avatar: const Icon(Icons.flag_outlined),
                        label: const Text("No country selected !", style: TextStyle(color: Colors.yellow),),
                        deleteIcon: const Icon(Icons.warning_amber_outlined),
                        onDeleted: (){},
                        deleteButtonTooltipMessage: "Select a country if available!",
                        onPressed: (){
                          if(selectedChip==3) {
                            selectedChip = null;
                          } else {
                            selectedChip = 3;
                          }
                          setState(() {});
                          getCountries();
                        },
                      );
                    }
                  }
                ),
              ],
            ),
          )
        ),
```

</p>
</details> 

Flutter doctor -v: 

<details><summary>flutter doctor -v</summary>
<p>

```
[√] Flutter (Channel beta, 3.15.0-15.2.pre, on Microsoft Windows [Version 10.0.22621.2283], locale nb-NO)
    • Flutter version 3.15.0-15.2.pre on channel beta at c:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0d074ced6c (7 days ago), 2023-09-21 10:24:15 -0700
    • Engine revision 453411bcf3
    • Dart version 3.2.0 (build 3.2.0-134.1.beta)
    • DevTools version 2.27.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\roarg\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\roarg\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android Studio\Android Studio 2023.2.1.4\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.8+0--10799086)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2022.3.1.19
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2022.3.1.16
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2023.1.1.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2023.2.1.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.8+0--10799086)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.92
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.43

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</p>
</details> 

pubspec.yaml:

<details><summary>pubspec.yaml</summary>
<p>

```
name: mwork
description: A tool for handling orders in Norva24.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.4.1+34

environment:
  #sdk: ">=2.16.0-80.1.beta <4.0.0"
  sdk: ">=2.17.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #_fe_analyzer_shared: 51.0.0
  #analyzer: ^6.2.0
  #camera_web: ^0.3.0
  #characters: ^1.2.1
  #material_color_utilities: ^0.1.5

  #webview_flutter: 4.0.1


  #flutter_webview_plugin:
  #  git: https://github.com/nuc134r/flutter_webview_plugin.git

  msal_js: ^2.14.0

  #--- aad-oauth Azure Active Directory login by Earlybyte ---
  aad_oauth: ^0.4.4
  #aad_oauth:
  #  git: https://github.com/Earlybyte/aad_oauth.git


  provider: ^6.0.3
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  #introduction_screen: ^3.0.2
  intl: ^0.18.0
  #socket_io_client: ^2.0.0-beta.4-nullsafety.0


  #--jwt--- makes it possible to analyze jwt
  jwt_decode: ^0.3.1

  #---Swagger changes---
  chopper: ^6.0.0
  json_annotation: ^4.5.0

  #---Google Maps---
  google_maps_flutter: ^2.4.0
  google_maps_flutter_web: ^0.5.3
  google_static_maps_controller: ^1.0.0

  #---Pointer interceptor
  pointer_interceptor: ^0.9.3+4

  #---Location data (GPS)---
  #location: ^4.4.0
  location: ^5.0.2+1

  #---Get---
  get: ^4.6.5

  #---Flutter Bloc---
  flutter_bloc: ^8.0.1

  #---Settings / preferences ---
  #flutter_settings_screens: ^0.3.2-null-safety
  shared_preferences: ^2.2.1
  #pref: ^2.6.0

  #---Camera function---
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  path: ^1.8.3

  #---image_picker function
  image_picker: ^1.0.2
  image_picker_for_web: ^3.0.0

  #---Floor functionality---
  #floor: ^1.2.0

  #---Drift functionality---
  drift: ^2.3.0
  #drift:
  #  git:
  #    url: https://github.com/simolus3/drift.git
  #    ref: develop
  #    path: drift
  #drift: 1.7.1
  sqlite3_flutter_libs: ^0.5.7


  #---Url launcher
  url_launcher: ^6.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  #---badges for icons
  #badges: ^3.0.1

  #---flutter webview plugin displace
  #flutter_webview_plugin:
  #    git: https://github.com/nuc134r/flutter_webview_plugin.git

  #---logging:
  logging: ^1.0.2
  firebase_core: ^2.0.0
  firebase_crashlytics: ^3.0.1
  package_info_plus: ^4.0.0
  firebase_performance: ^0.9.0+1

  #---db_inspector
  drift_db_viewer: ^2.0.0

  #---validators
  email_validator: ^2.1.17

  #---list extensions
  collection: ^1.16.0

  #---flag
  flag: ^7.0.0

  #---data table 2
  data_table_2: ^2.4.2

  #---devuce info plus
  device_info_plus: ^9.0.2
  label_marker: ^1.0.1
  custom_info_window: ^1.0.1

  #---file picker
  file_picker: ^5.3.3

  #---http
  http: ^0.13.6
  http_parser: ^4.0.2

  #---dio
  dio: ^5.3.2

  #---exif
  exif: ^3.1.4

  #---flutter_media_metadata
  #flutter_media_metadata: 1.0.0+1

  #---date_util
  #date_util: 0.1.4

  #---flutter_native_splash
  #flutter_native_splash: ^2.2.16


  #---Animated splashscreen:
  #animated_splash_screen: ^1.3.0
#---Icons---



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_round.png"
  adaptive_icon_background: "#666666"

dev_dependencies:
  flutter_test:
    sdk: flutter

  #---swagger changes---
  build_runner: ^2.1.11
  chopper_generator: ^6.0.0
  json_serializable: ^6.2.0
  swagger_dart_code_generator: ^2.8.7

  #---Launcher icons---
  flutter_launcher_icons: ^0.13.0

  #---floor generators---
  #floor_generator: ^1.2.0

  #---drift generators---
  drift_dev: ^2.3.0
  #drift_dev: 1.7.1

  #--- analyzer
  #analyzer: ^4.1.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



```

</p>
</details> 

The widget works ok, and I have user the same in other similar projects, but this one (in this flutter dev version), it floods the log with mentioned errors.
