### ISSUE TITLE
inaccurate error text shown when a non-null non-list is provided for `assets` section for a deferred component in pubspec

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#136163]
Consider this pubspec manifest:

```yaml
name: test
dependencies:
  flutter:
    sdk: flutter
flutter:
  deferred-components:
    - name: blah
      assets: blah
```

Notice that, under the first and only deferred component, `assets` has a string value rather than a list.
In this case, the tool will print an error: `Expected "assets" key in the 0 element of "deferred-components" to be a list, but got blah (String).` However, the value is not a list, so the error is inaccurate.

Interestingly, providing `assets: blah` directly under flutter results in more accurate error text: `Expected "assets" to be a list, but got blah (String).\n` This is a result of us using completely separate parsing and validation code for parsing the top-level `assets` section and the `assets` sections under any deferred components.

https://github.com/flutter/flutter/blob/9644aa8d76475185352994f241ce152acd75a8fa/packages/flutter_tools/test/general.shard/flutter_manifest_test.dart#L1444-L1463
