### ISSUE TITLE
NativeCodec.getNextFrame does not dispose Image working with AnimationSheetBuilder.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#136513]
PR that marks the leak: https://github.com/flutter/flutter/pull/136514

To repro, update the test `'Should show event indicator for pointer events with setSurfaceSize'`, with `leakTrackingTestConfig: LeakTrackingTestConfig.debugNotDisposed(),`.

**Comment by polina-c** [comment]
Creation stack trace:

```

  Expected: leak free
    Actual: <Instance of 'Leaks'>
     Which: contains leaks:
            # The text is generated by leak_tracker.
            # For leak troubleshooting tips open:
            # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
            notDisposed:
              total: 4
              objects:
                Image:
                  test: Should show event indicator for pointer events with setSurfaceSize
                  identityHashCode: 532238987
                  context:
                    start: >
                      #6_______flutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/test_widgets.dart:24:23)
                      #7______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:241:23)
                      #8______MemoryAllocations._imageOnCreate_(package:flutter/src/foundation/memory_allocations.dart:315:5)
                      #9______new_Image.__(dart:ui/painting.dart:1697:15)
                      #10______NativeCodec.getNextFrame.<anonymous_closure>_(dart:ui/painting.dart:2116:24)
                Image:
                  test: Should show event indicator for pointer events with setSurfaceSize
                  identityHashCode: 739222931
                  context:
                    start: >
                      #6_______flutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/test_widgets.dart:24:23)
                      #7______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:241:23)
                      #8______MemoryAllocations._imageOnCreate_(package:flutter/src/foundation/memory_allocations.dart:315:5)
                      #9______new_Image.__(dart:ui/painting.dart:1697:15)
                      #10______NativeCodec.getNextFrame.<anonymous_closure>_(dart:ui/painting.dart:2116:24)
                Image:
                  test: Should show event indicator for pointer events with setSurfaceSize
                  identityHashCode: 294513492
                  context:
                    start: >
                      #6_______flutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/test_widgets.dart:24:23)
                      #7______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:241:23)
                      #8______MemoryAllocations._imageOnCreate_(package:flutter/src/foundation/memory_allocations.dart:315:5)
                      #9______new_Image.__(dart:ui/painting.dart:1697:15)
                      #10______NativeCodec.getNextFrame.<anonymous_closure>_(dart:ui/painting.dart:2116:24)
                Image:
                  test: Should show event indicator for pointer events with setSurfaceSize
                  identityHashCode: 733169598
                  context:
                    start: >
                      #6_______flutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/test_widgets.dart:24:23)
                      #7______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:241:23)
                      #8______MemoryAllocations._imageOnCreate_(package:flutter/src/foundation/memory_allocations.dart:315:5)
                      #9______new_Image.__(dart:ui/painting.dart:1697:15)
                      #10______NativeCodec.getNextFrame.<anonymous_closure>_(dart:ui/painting.dart:2116:24)
```

**Comment by polina-c** [comment]
@dkwingsmt , can you take a look?

**Comment by droidbg** [comment]
@polina-c Getting similar leak in https://github.com/flutter/flutter/pull/136696 
```
 Expected: leak free
    Actual: <Instance of 'Leaks'>
     Which: contains leaks:
            # The text is generated by leak_tracker.
            # For leak troubleshooting tips open:
            # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
            notDisposed:
              total: 4
              objects:
  Image:
                  test: SweepGradient(center: Alignment.center, startAngle: 0.0, endAngle: 6.3, colors: [Color(0xffffffff), Color(0xff000088)], tileMode: TileMode.clamp, transform: GradientRotation(radians: 0.8))
                  identityHashCode: 1023853463
                  context:
                    start: >
                      #6_______flutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/test_widgets.dart:24:23)
                      #7______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:241:23)
                      #8______MemoryAllocations._imageOnCreate_(package:flutter/src/foundation/memory_allocations.dart:315:5)
                      #9______new_Image.__(dart:ui/painting.dart:1697:15)
                      #10______NativeCodec.getNextFrame.<anonymous_closure>_(dart:ui/painting.dart:2120:24)

 Image:
                  test: SweepGradient(center: Alignment.center, startAngle: 0.0, endAngle: 6.3, colors: [Color(0xffffffff), Color(0xff000088)], tileMode: TileMode.clamp, transform: GradientRotation(radians: 0.8))
                  identityHashCode: 36086123
                  context:
                    start: >
                      #6_______flutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/test_widgets.dart:24:23)
                      #7______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:241:23)
                      #8______MemoryAllocations._imageOnCreate_(package:flutter/src/foundation/memory_allocations.dart:315:5)
                      #9______new_Image.__(dart:ui/painting.dart:1697:15)
                      #10______NativeCodec.getNextFrame.<anonymous_closure>_(dart:ui/painting.dart:2120:24)
```
