### ISSUE TITLE
Unable to load asset (The asset does not exist or has empty data)

### ISSUE THREAD

**Issue by execOQ** [flutter/flutter#137523]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Added exiv2 assets for Mac to pubspec.yaml
2. try rootBundle.load assets

### Expected results

Exiv2 files for Mac should be copied to a temporary folder.

### Actual results

I need to copy the exiv2 executable files from the assets of the program to a temporary folder. exiv2 has different files for each platform. There were no problems copying files for Windows, but I can’t copy files for Mac, I get the error “FlutterError (Unable to load asset: “assets/exiv2-mac/exiv2”. The asset does not exist or has empty data.) ". I tried to copy them not only on the Mac, but also on the Windows system, and all to no avail. I tried to set the file permissions to 755, but apparently this is not the case. What could be the problem?

error:
FlutterError (Unable to load asset: "assets/exiv2-mac/exiv2".
The asset does not exist or has empty data.)

in:
final assetList = await rootBundle.load(convertedFile.path);

### Code sample

<details><summary>Code sample</summary>

```dart
const List<String> exiv2WinFiles = [
  "assets/exiv2-windows/bin/exiv2.exe",
  "assets/exiv2-windows/bin/addmoddel.exe",
  "assets/exiv2-windows/bin/exifcomment.exe",
  "assets/exiv2-windows/bin/exifdata.exe",
  "assets/exiv2-windows/bin/exifprint.exe",
  "assets/exiv2-windows/bin/exifvalue.exe",
  "assets/exiv2-windows/bin/exiv2.dll",
  "assets/exiv2-windows/bin/geotag.exe",
  "assets/exiv2-windows/bin/iptceasy.exe",
  "assets/exiv2-windows/bin/iptcprint.exe",
  "assets/exiv2-windows/bin/metacopy.exe",
  "assets/exiv2-windows/bin/mrwthumb.exe",
  "assets/exiv2-windows/bin/taglist.exe",
  "assets/exiv2-windows/bin/xmpdump.exe",
  "assets/exiv2-windows/bin/xmpparse.exe",
  "assets/exiv2-windows/bin/xmpprint.exe",
  "assets/exiv2-windows/bin/xmpsample.exe",
];

const List<String> exiv2MacFiles = [
  "assets/exiv2-mac/exiv2",
  "assets/exiv2-mac/libbrotlicommon.1.1.0.dylib",
  "assets/exiv2-mac/libbrotlicommon.1.dylib",
  "assets/exiv2-mac/libexiv2.0.28.0.dylib",
  "assets/exiv2-mac/libexiv2.28.dylib",
  "assets/exiv2-mac/libexiv2.dylib",
  "assets/exiv2-mac/libinih.0.dylib",
  "assets/exiv2-mac/libintl.8.dylib",
];

const List<String> exiv2LinuxFiles = [
  "assets/exiv2-linux/exiv2",
];

class Assets {
  static String getExiv2folder({returnWithExecutable}) {
    String os = Variables.currentPlatform;
    String directoryName = '';

    if (os == 'windows') {
      directoryName = 'exiv2-windows/bin';
      if (returnWithExecutable) {
        directoryName = '$directoryName/exiv2.exe';
      }
    } else if (os == 'mac') {
      directoryName = 'exiv2-mac/bin';
      if (returnWithExecutable) {
        directoryName = '$directoryName/exiv2';
      }
    } else if (os == 'linux') {
      directoryName = 'exiv2-linux/bin';
      if (returnWithExecutable) {
        directoryName = '$directoryName/exiv2';
      }
    }

    return directoryName;
  }

  static List<String> exiv2Assets() {
    String os = Variables.currentPlatform;
    List<String> directoryName = [];

    if (os == 'windows') {
      directoryName = exiv2WinFiles;
    } else if (os == 'mac') {
      directoryName = exiv2MacFiles;
    } else if (os == 'linux') {
      directoryName = exiv2LinuxFiles;
    }

    return directoryName;
  }

  static Future<void> copyAssets() async {
    String temporaryDir = (await getApplicationSupportDirectory()).path;
    String exiv2Path = getExiv2folder(returnWithExecutable: false);

    // path to exiv2 folder in app's assets
    String directoryPath = 'assets/$exiv2Path/';

    final targetDirectory = Directory('$temporaryDir/$exiv2Path');

    // check if folder where exiv2 files will be copied is created
    if (!targetDirectory.existsSync()) {
      await targetDirectory.create(recursive: true);
    }

    List<String> exiv2AssetsFiles = exiv2Assets();
    // get list of files in right exiv2 folder
    //final files = Directory(directoryPath).listSync().toList();
    for (final file in exiv2AssetsFiles) {
      File convertedFile = File(file);
      final assetList = await rootBundle.load(convertedFile.path);
      final ByteData data = assetList.buffer.asByteData();

      // coping exiv2 files in application folder
      if (convertedFile.existsSync()) {
        final assetData =
            data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
        final targetFilePath = path.join(
            targetDirectory.path, convertedFile.uri.pathSegments.last);
        final targetFile = File(targetFilePath);

        if (!targetFile.existsSync()) {
          print('22');
          await targetFile.writeAsBytes(assetData, flush: true);
        }
      }
    }
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/44172382/0fc43b6e-191a-4b4c-b3af-b95a25673efb)
(left console shows exiv2 files for windows, right one shows files for macOS)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
artem@Artems-MacBook-Pro flutter_app % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1 23B74 darwin-x64, locale en-GB)
    • Flutter version 3.13.9 on channel stable at /Users/Shared/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (5 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      flutter config --android-sdk to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.14.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 14.1 23B74 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.
```

</details>

**Comment by execOQ** [comment]
pubspec.yaml

```yaml
name: aqua
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  file_picker: ^6.0.0
  flutter_map: ^6.0.1
  animations: ^2.0.8
  http: ^1.1.0
  fraction: ^5.0.2
  gpx: ^2.2.1
  path: ^1.8.3
  latlong2: ^0.9.0
  flutter_riverpod: ^2.4.4
  material_symbols_icons: ^4.2671.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  observe_internet_connectivity: ^1.0.2
  window_manager: ^0.3.7
  flutter_map_tile_caching: ^9.0.0-dev.5
  flutter_map_animations: ^0.5.3
  flutter_map_cache: ^1.3.1
  flutter_map_cancellable_tile_provider: ^1.0.0
  flutter_animate: ^4.2.0+1
  hovering: ^1.0.4
  photo_view: ^0.14.0
  url_launcher: ^6.1.14
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_file_store: ^1.2.2
  sentry_flutter: ^7.11.0
  path_provider: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/img/
   - assets/exiv2-linux/bin/


   - assets/exiv2-windows/bin/
   - assets/exiv2-mac/bin/
```
