### ISSUE TITLE
[Linux] Downloading and saving file using dio and path_provider completely works fine on development but does not work after installing from snapstore (worked before in 3.10.1) (Currently using 3.13.9)

### ISSUE THREAD

**Issue by hungryemon** [flutter/flutter#137661]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Download file using Dio anddownload file in getApplicationDocumentsDirectory() using path_provider.

### Expected results

Show error if any or download should work.

### Actual results

No error is thrown, this snippet not working now in production.

### Code sample

```dart
String fileName = url.substring(url.lastIndexOf('/') + 1);

    try {
      await Dio().download(
              url,
              savePath,
              onReceiveProgress: (rcv, total) {
                var progress = (rcv / total) * 100;
                // logger.d("progress: $progress");
                onProgressUpdate(progress);
              },
              cancelToken: cancelToken,
              deleteOnError: false,
            );
      onProgressUpdate(100.0);
     
      bool isInternetAvailable = await isInternetConnectionAvailable();
      if (isInternetAvailable) {
       XToast.success(
          msg: 'Downloaded Successfully',
          context: Get.context!,
          isMobile: isMobile,
        );
      } else {
         XToast.error(
          msg: 'No Internet Connection',
          context: Get.context!,
          isMobile: isMobile,
        );
      }
    } catch (err, st) {
      debugPrint(err.toString());
    }
```
##Not sure if its the issue related to snap or flutter

My previous snapcraft.yml File which worked
```yml
name: X
version: git
summary: X-A name
description: X is a solution
confinement: strict
base: core22
grade: stable
license: GPL-3.0+
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
assumes:
  - snapd2.46

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.10.1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    prime:
      - -*

  X:
    after: [ flutter-git ]
    plugin: nil
    source: .
    override-build: |
      set -eux
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
    build-packages:
      - mpv
      - gir1.2-keybinder-3.0
      - keybinder-3.0-doc
      - libmpv-dev
      - libkeybinder-3.0-0
      - libkeybinder-3.0-dev
      - libslang2 # Added libslang2 package
    stage-packages:
      - mpv
      - libmpv-dev
      - libkeybinder-3.0-0
      - libglu1-mesa # Added libglu1-mesa package
      - freeglut3 # Added freeglut3 package
      - libslang2 # Added libslang2 package
      - libsmbclient
      - libblas3

# plugs:
#   read-home:
#     interface: personal-files
#     read:
#       - $HOME/.X
     
apps:
 X:
    command: bin/X_app
    desktop: meta/gui/X.desktop
    extensions: [gnome]
    plugs:
      - network
      - desktop
      - lxd
      - home
      - audio-playback
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/lib:$LD_LIBRARY_PATH
      # LD_LIBRARY_PATH: $SNAPCRAFT_PART_INSTALL/ostad/usr/lib/x86_64-linux-gnu:$SNAPCRAFT_PART_INSTALL/ostad/lib:$LD_LIBRARY_PATH
```

Current snapcraft.yml file: 
```yml
name: X
version: git
summary: X-A name
description: X is a solution
confinement: strict
base: core22
grade: stable
license: GPL-3.0+
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
assumes:
  - snapd2.46

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.13.9
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    prime:
      - -*

  X:
    after: [flutter-git]
    plugin: nil
    source: .
    override-build: |
      set -eux
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
    build-packages:
      - mpv
      - gir1.2-keybinder-3.0
      - keybinder-3.0-doc
      - libmpv-dev
      - libkeybinder-3.0-0
      - libkeybinder-3.0-dev
      - libslang2 # Added libslang2 package
    stage-packages:
      - mpv
      - libmpv-dev
      - libkeybinder-3.0-0
      - libglu1-mesa # Added libglu1-mesa package
      - freeglut3 # Added freeglut3 package
      - libslang2 # Added libslang2 package
      - libsmbclient
      - libblas3

# plugs:
#   read-home:
#     interface: personal-files
#     write:
#       - '$HOME'  # This grants write access to the user's home directory
#     read:
#       - '$HOME'  # This grants read access to the user's home directory

apps:
  X:
    command: bin/X_app
    desktop: meta/gui/X.desktop
    extensions: [gnome]
    plugs:
      - network
      - desktop
      - lxd
      - home  # Include the home plug to access the user's home directory
      - audio-playback
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/lib:$LD_LIBRARY_PATH

```

### Flutter Doctor output

```console
[✓] Flutter (Channel stable, 3.13.9, on Ubuntu 22.04.2 LTS 6.2.0-36-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version unknown)
    ✗ Unable to determine VS Code version.
[✓] Connected device (2 available)
[✓] Network resources
```
