### ISSUE TITLE
firebase_auth 0.4.0, DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by xinoxapps** [flutter/flutter#13784]
After upgrading gradle tools from 2.x.x to 3.1.0, the build failed with an exception:

```
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

```
pubspec.yaml:

```
dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.4.0                                             # new
  #
  discoveryapis_generator: "^0.9.1+1"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  http: '>=0.11.3+12'
```

firebase_auth is the problem. I noticed that the library is referring to 'api 'com.google.firebase:firebase-core:[11.4.0,12.0['', and the other fire packages are using ''com.google.firebase:firebase-core:11.+''

_Removing firebase_auth solves the build error.
Migrating back to 0.3.2 also solved the build error._
