### ISSUE TITLE
[Engine] Investigate if `.ci.yaml`'s `runIfNot: ...` works as expected

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#138559]
In https://github.com/flutter/engine/pull/47994, I accidentally broke the Fuchsia build, despite all of the checks passing (and using the new `test: all` check to additionally run post-submits as pre-submits). It was reverted in https://github.com/flutter/engine/pull/48130.

(h/t @jonahwilliams - I think this is the file I missed: https://github.com/flutter/engine/blob/d8fb1b1e719dd00b5b2e43f731f139ffa73db130/shell/platform/fuchsia/flutter/external_view_embedder.cc#L105)

I have a _theory_ that [`runIfNot`](https://github.com/flutter/engine/blob/d8fb1b1e719dd00b5b2e43f731f139ffa73db130/.ci.yaml#L177-L184) doesn't work as expected, i.e. if _any_ of the globs match, the target is not run:
```yaml
  - name: Linux Fuchsia
    bringup: true
    recipe: engine/engine
    properties:
      build_fuchsia: "true"
      fuchsia_ctl_version: version:0.0.27
      # ensure files from pre-production Fuchsia SDK tests are purged from cache
      clobber: "true"
    timeout: 90
    runIfNot:
      - lib/web_ui/**
      - shell/platform/android/**
      - shell/platform/darwin/**
      - shell/platform/glfw/**
      - shell/platform/linux/**
      - shell/platform/windows/**
      - web_sdk/**
```

For example, I edited:

- `shell/platform/android/external_view_embedder/external_view_embedder.cc`

I'll test this theory with a junk PR.
