### ISSUE TITLE
use package: references in the assets section of a pubspec file

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#13875]
You can currently refer to assets from another package using the `packages/package_name/asset_name` format. We should move to using a `package:package_name/asset_name` format - this will be the same as other url references (like imports).

**Comment by devoncarew** [comment]
@szakarias

**Comment by Hixie** [comment]
if we do this we should do it ASAP since it's a breaking change

**Comment by szakarias** [comment]
Could you elaborate a bit more on why we want this? 

It would have the unfortunate effect of entries with two colons in the `fonts` section, for instance 
```
     - family: Raleway
       fonts:
         - asset: assets/fonts/Raleway-Regular.ttf
         - asset: package:my_package/fonts/Raleway-Medium.ttf
           weight: 500
```
