### ISSUE TITLE
Build error with flutter 3.16 on iOS (Null check operator used on a null value)

### ISSUE THREAD

**Issue by tanguy-penfen** [flutter/flutter#138795]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Build a flutter project on iOS with the 3.16 flutter version

### Expected results

Build should be successful

### Actual results

Build fails with the following error : 

```
Unhandled exception:
    Null check operator used on a null value
    #0      Context.embedFlutterFrameworks
    (file:///Users/xxx/flutter/packages/flutter_tools/bin/xcode_backend.dart:235:68)
    #1      Context.run
    (file:///Users/xxx/flutter/packages/flutter_tools/bin/xcode_backend.dart:59:9)
    #2      main (file:///Users/xxx/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
    #3      _delayEntrypointInvocation.<anonymous closure>
    (dart:isolate-patch/isolate_patch.dart:295:33)
    #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
    Command PhaseScriptExecution failed with a nonzero exit code
```

Notes :

It seems that during build the environment variable FLUTTER_BUILD_DIR can not be retrieved so the null check in the following line fails : 
`final String flutterBuildDir = environment['FLUTTER_BUILD_DIR']!;
`(in flutter/packages/flutter_tools/bin/xcode_backend.dart)

The build is successful if this line is modified : 
`final String flutterBuildDir = environment['FLUTTER_BUILD_DIR'] ?? 'build';`

### Code sample

None

### Flutter Doctor output

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.6.1 22G313 darwin-x64, locale fr-FR)
    • Flutter version 3.16.0 on channel stable at /Users/Tanguy/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (6 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/Tanguy/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • iPhone Tanguy (mobile) • 00008110-000A104E36C3401E • ios            • iOS 17.1.1 21B91
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 13.6.1 22G313 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.
``` 

</p>
</details>

**Comment by behnamsattar** [comment]
Here is how you can resolve this:
https://stackoverflow.com/a/77525213/1501604

**Comment by dam-ease** [comment]
Thanks for your input @behnamsattar 
Can you try this out to see if works in your case @tanguy-penfen?

**Comment by tanguy-penfen** [comment]
@dam-ease 
The suggestion from @behnamsattar wasn't specific enough and we didn't feel like manually editing the project.pbxproj file.
While looking into it we realised the structure of this file and of the iOS folder has been modified with latest update, so we created a new project with same name and moved the content of the new iOS folder in the old one.

After updating some configuration elements in Xcode that were lost in the process everything is working fine now.

**Comment by dam-ease** [comment]
Thanks for your response. 
Closing this per your last comment, if you disagree, please comment and I'll reopen this.
Thank you!

**Comment by rayyan808** [comment]
I'm having the same issue, but only on my GitHub workflow. The project builds fine locally. My Github workflow file:
```
name: CI Workflow
on:
  push:
    branches: [main, stage]
  pull_request:
    branches: [dev]
jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle
  apple:
    name: Build iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        architecture: x64
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign
    ```
    
    Flutter doctor from our development MacBooks:
    ```
    [✓] Flutter (Channel stable, 3.16.0, on macOS 14.0 23A344 darwin-arm64, locale
    en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (2 available)
[✓] Network resources

    ```
