### ISSUE TITLE
Flutter pub get set sdks.dart value in pubspec.lock to "<empty>"

### ISSUE THREAD

**Issue by ziqq** [flutter/flutter#138796]
### Steps to reproduce

Run the command `flutter pub get` only

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="778" alt="image" src="https://github.com/flutter/flutter/assets/20646071/3427df2c-4221-4529-b5ed-45ba3b971bd0">
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @ziqq, do you have this issue with a new `flutter create`'d app? Or is it with your existing project? 

If it is with your existing project, can you share your pubspec.yaml?

**Comment by ziqq** [comment]
Hello @danagbemava-nc, i have this issue with my existing project.

<details><summary>pubspec.yaml</summary>

```yaml
name: app_name
description:  app description
publish_to: none
version: 1.2.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^2.0.7
  flutter_hooks: ^0.18.6
  flutter_slidable: ^3.0.0
  flutter_markdown: ^0.6.17+3
  flutter_widgetkit: ^1.0.3
  flutter_speed_dial: ^7.0.0
  flutter_easyloading: ^3.0.5
  flutter_check_box_rounded: ^3.1.5
  flutter_local_notifications: ^15.1.1
  flutter_in_store_app_version_checker: ^1.5.0

  dio: ^5.3.3
  path: ^1.8.3
  intl: ^0.18.0
  rive: ^0.11.1
  crypto: ^3.0.2
  confetti: ^0.7.0
  equatable: ^2.0.0
  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  contacts_service: ^0.6.3
  package_info_plus: ^4.1.0
  permission_handler: ^10.0.0
  mask_text_input_formatter: ^2.5.0

  # appmetrica plugins
  appmetrica_plugin: ^1.0.1

  # rate my app
  in_app_review: ^2.0.8

  # helpers
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.1.0
  showcaseview: ^2.0.3

  # inversion of control
  get_it: ^7.6.4
  injectable: ^2.3.0

  # firebase
  firebase_core: ^2.16.0
  firebase_analytics: ^10.6.3
  firebase_messaging: ^14.6.8
  firebase_crashlytics: ^3.3.6

  # data store
  # shared_preferences: ^2.2.1

  # state managment
  logger: ^1.1.0
  stacked: ^3.4.1+1
  stacked_hooks: ^0.2.3
  stacked_themes: ^0.3.10
  stacked_services: ^1.3.0

  # custom widgets
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  extended_image: ^8.1.1
  grouped_list: ^5.1.2
  lazy_load_scrollview: ^1.3.0
  modal_bottom_sheet: ^3.0.0-pre
  quick_actions: ^1.0.6
  pull_down_button: ^0.9.3
  shimmer: ^3.0.0
  sticky_headers: ^0.3.0+2
  scrollable_positioned_list: ^0.3.5
  syncfusion_flutter_datepicker: ^23.1.38
  table_sticky_headers: ^2.0.5

  # Map
  google_maps_flutter: 2.1.1

  # custom packages & plugins
  shake:
    git:
      url: git@github.com:ziqq/flutter_shake_detector.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  stacked_generator: ^1.5.1
  injectable_generator: ^2.4.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1

  # testing
  faker: ^2.0.0
  mockito: ^5.3.2
  plugin_platform_interface: ^2.1.6
  url_launcher_platform_interface: ^2.1.5

  flutter_lint_rules:
    git:
      url: https://github.com/ziqq/flutter_lint_rules.git
      ref: main

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
```
</details>
