### ISSUE TITLE
Couldn't resolve the package 'build_tool' in 'package:build_tool/build_tool.dart'

### ISSUE THREAD

**Issue by ddxl123** [flutter/flutter#139925]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I don't know what operation caused the problem.

### Actual results

Windows 11、IDEA

### Logs

```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: C:\Users\LongPC\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\super_native_extensions-0.7.3\android\src\main\java\com\superlist\super_native_extensions\DragDropHelper.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the file specified.
The system cannot find the file specified.
Cannot operate on packages inside the cache.
Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
Error: Couldn't resolve the package 'build_tool' in 'package:build_tool/build_tool.dart'.
bin/build_tool_runner.dart:1:8: Error: Not found: 'package:build_tool/build_tool.dart'
import 'package:build_tool/build_tool.dart' as build_tool;
       ^
bin/build_tool_runner.dart:3:15: Error: Method not found: 'runMain'.
   build_tool.runMain(args);
              ^^^^^^^
Could not find a command named "bin\build_tool_runner.dill".

Usage: dart <command|dart-file> [arguments]

Global options:
-v, --verbose               Show additional command output.
    --version               Print the Dart SDK version.
    --enable-analytics      Enable analytics.
    --disable-analytics     Disable analytics.
    --suppress-analytics    Disallow analytics for this `dart *` run without changing the analytics configuration.
-h, --help                  Print this usage information.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  info       Show diagnostic information about the installed tooling.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the file specified.
The system cannot find the file specified.
Cannot operate on packages inside the cache.
Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
Error: Couldn't resolve the package 'build_tool' in 'package:build_tool/build_tool.dart'.
bin/build_tool_runner.dart:1:8: Error: Not found: 'package:build_tool/build_tool.dart'
import 'package:build_tool/build_tool.dart' as build_tool;
       ^
bin/build_tool_runner.dart:3:15: Error: Method not found: 'runMain'.
   build_tool.runMain(args);
              ^^^^^^^
Could not find a command named "bin\build_tool_runner.dill".

Usage: dart <command|dart-file> [arguments]

Global options:
-v, --verbose               Show additional command output.
    --version               Print the Dart SDK version.
    --enable-analytics      Enable analytics.
    --disable-analytics     Disable analytics.
    --suppress-analytics    Disallow analytics for this `dart *` run without changing the analytics configuration.
-h, --help                  Print this usage information.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  info       Show diagnostic information about the installed tooling.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
[CXX1101] NDK at C:\Users\LongPC\AppData\Local\Android\Sdk\ndk-bundle did not have a source.properties file
[CXX1101] NDK at C:\Users\LongPC\AppData\Local\Android\Sdk\ndk-bundle did not have a source.properties file
[CXX1101] NDK at C:\Users\LongPC\AppData\Local\Android\Sdk\ndk-bundle did not have a source.properties file
[CXX1101] NDK at C:\Users\LongPC\AppData\Local\Android\Sdk\ndk-bundle did not have a source.properties file
[CXX1101] NDK at C:\Users\LongPC\AppData\Local\Android\Sdk\ndk-bundle did not have a source.properties file
[CXX1101] NDK at C:\Users\LongPC\AppData\Local\Android\Sdk\ndk-bundle did not have a source.properties file
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app-debug.apk...
Debug service listening on ws://127.0.0.1:56605/SZGQvykai3I=/ws
Syncing files to device Android SDK built for x86...
```

### Flutter Doctor output

```
D:\flutter\bin\flutter.bat doctor --verbose
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.23595.1001], locale zh-CN)
    • Flutter version 3.16.3 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (6 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\LongPC\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: D:\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
    • Visual Studio at D:\Microsoft Visual Studio
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = D:\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at D:\IntelliJ IDEA 2022.2.2
    • Flutter plugin version 72.1.3
    • Dart plugin version 222.4560

[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at D:\IntelliJ IDEA 2023.1.4
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.8660.129

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.23595.1001]
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 120.0.2210.61

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by danagbemava-nc** [comment]
Hi @ddxl123, do you have this issue with the flutter counter app? 

What command did you run? Have you enabled developer mode in your settings?

**Comment by ddxl123** [comment]
This issue did not appear in the flutter counter app.
Whether running `futter run -- debug `or clicking the `run` button in IDEA, this issue will occur.
Both Windows settings and Android settings have developer options enabled.

```
name: aaa_memory
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  drift_db_viewer: ^2.0.0
  animated_bottom_navigation_bar: ^1.3.0
  pull_to_refresh: ^2.0.0
  extended_nested_scroll_view: ^6.1.2
  dropdown_button2: ^2.3.9
  font_awesome_flutter: ^10.6.0
  line_icons: ^2.0.3
  math_expressions: ^2.4.0
  dio: ^5.4.0
  back_button_interceptor: ^7.0.0

  flutter_quill: ^9.0.1
  flutter_quill_extensions: ^9.0.1
  vsc_quill_delta_to_html: ^1.0.3
  flutter_html: ^3.0.0-beta.2

  flutter_spinkit: ^5.2.0
  flutter_smart_dialog: ^4.9.5+1
  #  catcher: ^0.7.0
  dotted_border: ^2.1.0
  async: ^2.11.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_staggered_grid_view: ^0.7.0
  textfield_tags: ^2.0.2
  just_the_tooltip: ^0.0.12
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  syncfusion_flutter_sliders: ^23.2.7

  like_button: ^2.0.5

  build_runner: ^2.4.7
  source_gen: ^1.4.0

  uuid: ^4.2.1

  logger: ^2.0.2+1

  flip_card: ^0.7.0

  carousel_slider: ^4.2.1

  flutter_speed_dial: ^7.0.0

  drift_main:
    path: ./subpackages/drift_main

  drift_custom:
    path: ./subpackages/drift_custom

  tools:
    path: ./subpackages/tools

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  analyzer: ^6.2.0

flutter:
  uses-material-design: true

```

drift_main:
```
name: drift_main
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.2.1

  logger: ^2.0.2+1
  dio: ^5.4.0
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


  drift_dev: ^2.14.0
  build: ^2.4.1
  build_runner: ^2.4.7
  source_gen: ^1.4.0



  drift_custom:
    path: ../drift_custom
  tools:
    path: ../tools

flutter:
```

drift_custom:
```
name: drift_custom
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: ^2.4.7
  source_gen: ^1.4.0
flutter:

```

tools:
```
name: tools
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.2.1

  logger: ^2.0.2+1

  dropdown_button2: ^2.3.9

  pull_to_refresh: ^2.0.0

  flutter_smart_dialog: ^4.9.5+1

  font_awesome_flutter: ^10.6.0

  device_info_plus: ^9.1.1

  package_info_plus: ^5.0.1

  flutter_spinkit: ^5.2.0

  back_button_interceptor: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:

```
