### ISSUE TITLE
Build ipa/ios/apk Unhandled exception: RangeError (offset): Invalid value: Not in inclusive range 0..4102: 9987

### ISSUE THREAD

**Issue by smiera** [flutter/flutter#140318]
### Steps to reproduce

I don't know exactly how to reproduce.
I have two apps. One builds without problems, and the other has an error.

### Actual results

When build my app, I get error(see Logs section).
Build example:
```
flutter build apk --release --tree-shake-icons --obfuscate --split-debug-info=build/split-debug-info/android 
```

In the emulator, the application runs without problems.

<details>
<summary>dependencies</summary>

```yaml
environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  cupertino_icons: ^1.0.2
  go_router: ^6.0.3
  flutter_native_splash: ^2.2.14
  provider: ^6.0.5
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.3
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.0+1
  gap: ^3.0.1
  vibration: ^1.7.6
  collection: ^1.17.0
  dropdown_search: ^5.0.6
  syncfusion_flutter_datepicker: ^22.2.9
  crypto: ^3.0.2
  path_provider: ^2.0.12
  path: ^1.8.2
  url_launcher: ^6.1.9
  flutter_pdfview: ^1.2.5
  fluttertoast: ^8.2.1
  visibility_detector: ^0.3.3
  custom_refresh_indicator: ^2.0.1
  flutter_vibrate: ^1.3.0
  http: ^1.0.0
  package_info_plus: ^4.0.0
  device_info_plus: ^9.0.3
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  permission_handler: ^10.4.3

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Firebase
  firebase_messaging: ^14.7.3
  firebase_core: ^2.21.0
  firebase_crashlytics: ^3.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  isar_generator: ^3.1.0+1
  hive_generator: ^2.0.0

```

</details>

### Logs

<details open>
<summary>Logs</summary>

```console

flutter build apk --release --tree-shake-icons --obfuscate --split-debug-info=build/split-debug-info/android

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/smirnov/.pub-cache/hosted/pub.dev/firebase_messaging-14.7.4/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Unhandled exception:
RangeError (offset): Invalid value: Not in inclusive range 0..4102: 9987
#0      RangeError.checkValueInInterval (dart:core/errors.dart:313:7)
#1      Source.getLocation (package:kernel/ast.dart:14692:16)
#2      Component.getLocation (package:kernel/ast.dart:14456:31)
#3      _getLocationInComponent (package:kernel/ast.dart:14907:22)
#4      Constructor._getLocationInEnclosingFile (package:kernel/ast.dart:2631:12)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:203:20)
#6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:203:20)
#7      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:203:20)
#8      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:203:20)
#9      TreeNode.location (package:kernel/ast.dart:199:12)
#10     getFreshStructuralParametersFromTypeParameters.<anonymous closure> (package:kernel/type_algebra.dart:187:39)
#11     new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#12     getFreshStructuralParametersFromTypeParameters (package:kernel/type_algebra.dart:183:11)
#13     FunctionNode.computeThisFunctionType (package:kernel/ast.dart:3754:11)
#14     FunctionNode.computeFunctionType (package:kernel/ast.dart:3792:12)
#15     FunctionExpression.getStaticTypeInternal (package:kernel/ast.dart:8511:21)
#16     StaticTypeContextImpl.getExpressionType (package:kernel/type_environment.dart:753:19)
#17     Expression.getStaticType (package:kernel/ast.dart:3920:20)
#18     SummaryCollector._staticDartType (package:vm/transformations/type_flow/summary_collector.dart:1284:12)
#19     SummaryCollector._staticType (package:vm/transformations/type_flow/summary_collector.dart:1287:36)
#20     SummaryCollector.visitFunctionExpression (package:vm/transformations/type_flow/summary_collector.dart:1630:12)
#21     FunctionExpression.accept (package:kernel/ast.dart:8515:44)
#22     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:846:44)
#23     SummaryCollector.visitFieldInitializer (package:vm/transformations/type_flow/summary_collector.dart:2434:19)
#24     FieldInitializer.accept (package:kernel/ast.dart:3340:45)
#25     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:849:10)
#26     List.forEach (dart:core-patch/growable_array.dart:416:8)
#27     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:706:29)
#28     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1650:55)
#29     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:298:42)
#30     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#31     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1539:27)
#32     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1798:23)
#33     Call.apply (package:vm/transformations/type_flow/summary.dart:359:31)
#34     Summary.apply (package:vm/transformations/type_flow/summary.dart:1075:28)
#35     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:307:24)
#36     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#37     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1539:27)
#38     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1798:23)
#39     Call.apply (package:vm/transformations/type_flow/summary.dart:359:31)
#40     Summary.apply (package:vm/transformations/type_flow/summary.dart:1075:28)
#41     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:307:24)
#42     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#43     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1539:27)
#44     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:449:44)
#45     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#46     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:423:12)
#47     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1539:27)
#48     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1481:7)
#49     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1676:14)
#50     transformComponent (package:vm/transformations/type_flow/transformer.dart:114:20)
#51     runGlobalTransformations (package:vm/kernel_front_end.dart:573:20)
#52     compileToKernel (package:vm/kernel_front_end.dart:477:11)
<asynchronous suspension>
#53     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:635:17)
<asynchronous suspension>
#54     starter (package:frontend_server/starter.dart:102:12)
<asynchronous suspension>
#55     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
<asynchronous suspension>

Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/opt/homebrew/Caskroom/flutter/3.3.1/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1350

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/opt/homebrew/Caskroom/flutter/3.3.1/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 49s
Running Gradle task 'assembleRelease'...                           50,1s
Gradle task assembleRelease failed with exit code 1


```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.16.4, on macOS 14.2 23C64 darwin-arm64, locale uk-UA)
    • Flutter version 3.16.4 on channel stable at /opt/homebrew/Caskroom/flutter/3.3.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (7 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/smirnov/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.1)
    • IntelliJ at /Users/smirnov/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 233.11799.172

[✓] Connected device (3 available)
    • iPhone 12 (mobile)     • 11434F9C-5740-4751-8AB5-27E5A30A6EE4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!


```

</details>
