### ISSUE TITLE
Crash when filling a TextFormField | Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) | Cause: null pointer dereference

### ISSUE THREAD

**Issue by ldsouza93** [flutter/flutter#140720]
### Steps to reproduce

The app has a TextFormField that's being constantly filled, everything was working perfectly.  After upgrading Flutter and probably some Plugins upgrades, the app began to randomly crash when filling the TextFormFIeld.

The problem happens only on Android on profile and release mode, when debugging i couldn't reproduce the issue.

<details open><summary>TextFormFIeld Widget</summary>

```dart
Form(
  key: formKey,
  child: RawKeyboardListener(
    focusNode: FocusNode(),
    onKey: (RawKeyEvent event) {
      if (coletaEmAndamento || !tagFieldFocusNode.hasFocus || coletaAbastecimento) return;
    },
    child: TextFormField(
      autofocus: true,
      autocorrect: false,
      enableSuggestions: false,
      readOnly: coletaEmAndamento,
      textInputAction: TextInputAction.none,
      maxLength: 24,
      controller: tagFieldController,
      focusNode: tagFieldFocusNode,
      style: TextStyle(fontWeight: FontWeight.bold, fontSize: telaTablet ? 20.f : 9.f),
      decoration: InputDecoration(counterText: '', contentPadding: EdgeInsets.only(top: 1.5.h)),
      onTap: () => tagFieldController.clear(),
      onFieldSubmitted: (v) =>
          ((v == '#2' ? false : v.length < 24) && !coletaEmAndamento && !coletaAbastecimento) ? tagFieldController.clear() : null,
      onChanged: (value) => textFieldOnChangedFunction(value),
    ),
  ),
),
```

</details>

<details close><summary>pubspec.yaml</summary>

```yaml
name: logti_rfid
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  ota_update: ^6.0.0
  just_audio: ^0.9.32
  wakelock: ^0.6.2
  mask_text_input_formatter: ^2.3.0
  flutter_keyboard_visibility: ^5.4.1
  file_picker: ^5.2.5
  open_file: ^3.3.1
  csv: ^5.0.2
  pluto_grid: ^7.0.2
  flutter_bluetooth_serial:
    git:
      url: https://github.com/pst9354/flutter_bluetooth_serial
      ref: master
  http: ^1.1.0
  shared_preferences: ^2.0.5
  intl: ^0.18.0
  path_provider: ^2.0.9
  dio: ^5.0.2
  sizer_pro: ^3.0.0-alpha
  #^2.2.0
  flutter:
    sdk: flutter

dependency_overrides:
  ffi: ^2.0.1
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
    - oldAssets/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

</details>

<details open><summary>Console LOG</summary> 

```console
[+3006 ms] F/libc    (26751): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 26777 (1.ui), pid 26751 (mple.logti_rfid)
[ +124 ms] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
[        ] Build fingerprint: 'xiaomi/daisy/daisy_sprout:10/QKQ1.191002.002/V11.0.21.0.QDLMIXM:user/release-keys'
[        ] Revision: '0'
[        ] ABI: 'arm64'
[        ] Timestamp: 2023-12-28 21:29:55-0500
[        ] pid: 26751, tid: 26777, name: 1.ui  >>> com.example.logti_rfid <<<
[        ] uid: 10195
[        ] signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
[        ] Cause: null pointer dereference
[        ]     x0  0000000000000000  x1  0000007bbf0ddcc9  x2  0000000000000000  x3  0000000000000020
[        ]     x4  0000000000000000  x5  0000000000000020  x6  0000000000000000  x7  0000000000000006
[        ]     x8  00000000be21d448  x9  000000007fc00000  x10 000000007f800000  x11 0000000000000000
[        ]     x12 0000000000000007  x13 0000000000000000  x14 0000000000000008  x15 0000200000000000
[        ]     x16 0000007bd1df7df8  x17 0000007cbd4ea100  x18 0000007bcf41c000  x19 0000000000000081
[        ]     x20 0000007c2a7f7c00  x21 0000007bc283d700  x22 0000007bc64f5900  x23 0000007c2a7f7ca8
[        ]     x24 0000007c2a7f7cb8  x25 0000007bc2841080  x26 0000000000000100  x27 0000007c2a5ad808
[        ]     x28 0000007c2a325b00  x29 0000007bc64e2680
[        ]     sp  0000007c2a4f8a80  lr  0000007bd1a4e9c4  pc  0000007bd1a4e9c8
[        ] backtrace:
[        ]       #00 pc 0000000000a239c8  /data/app/com.example.logti_rfid-vcZsk4qETeheffeC1Ze4-g==/lib/arm64/libflutter.so!libflutter.so (offset 0x73e000)  
(BuildId: 0424820c482bb2e78a617033ebca731a95ffeb8e)
[ +897 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +2 ms] "flutter run" took 126.407ms.
[ +169 ms] ensureAnalyticsSent: 165ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 0
```
</details>

### Flutter Doctor output

<details close><summary>Doctor output</summary>

```console
C:\Windows\system32>flutter doctor -v
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19045.3803], locale pt-BR)
    • Flutter version 3.16.5 on channel stable at C:\Src\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (9 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Lucas\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\Lucas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (3 available)
    • Mi A2 Lite (mobile) • 6943d09c0605 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)   • windows      • windows-x64    • Microsoft Windows [Version 10.0.19045.3803]
    • Edge (web)          • edge         • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>
