### ISSUE TITLE
Error running app on android after flutter reinstallation

### ISSUE THREAD

**Issue by crobertson247** [flutter/flutter#141261]
### Steps to reproduce

1. Install flutter into C:src
2.  add path to its bin in env variables
3. installed jdk 21 from oracle and added JAVA_HOME path (also tried 17)
4. installed vs code and android studio and the cli tools for android studio
5. add the following pubspec.yaml to the file:
```
name: presentpal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+5

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  # proivder was 6.0.1
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  http: ^1.1.0
  url_launcher: ^6.1.12
  device_calendar: ^4.3.2
  permission_handler: ^11.1.0
  
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2

  syncfusion_flutter_calendar: ^23.2.5

  awesome_notifications: ^0.8.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  progress_state_button: ^1.0.4
  get: ^4.3.8

  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.7.2
  #cloud_firestore: ^4.8.4  # For Cloud Firestore
  #firebase_storage: ^11.2.5 # For Firebase Cloud Storage
  
  firebase_analytics: ^10.4.4 # For Firebase Analytics (Optional)

  #Google Sign In
  google_sign_in: ^6.1.6

  google_mobile_ads: ^3.0.0

  timezone: ^0.9.2

  #In-app Purchases 
  purchases_flutter: ^6.4.0
  cloud_firestore: ^4.8.4

  #chatGPT
  #chat_gpt_sdk: ^2.2.5
  flutter_dotenv: ^5.1.0
  #firebase_core:
  #firebase_auth:

  flutter_svg: ^2.0.7
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
```

### Actual results

Every time i try run my app on android i get an error about some android Manifest permission. I'm 99% sure it isn't a problem with the code but rather flutter itself as it was working prior to reinstalling and I've tried to run prior working versions from git as well.

The error message looks like: 
```
C:\Users\cianr\AppData\Local\Pub\Cache\hosted\pub.dev\firebase_messaging-14.7.10\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingPlugin.java:389: error: cannot find symbol
            .checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)
```

```
flutter clean
flutter pub cache clean
flutter pub cache repair
```

None of the above work, would love to hear some solutions to the problem

### Logs

<details open>
<summary>Logs</summary>

```console

PS C:\Users\cianr\OneDrive\Business\PresentPal\App\presentpal> flutter run
"ar": 4 untranslated message(s).
"bn": 4 untranslated message(s).
"de": 4 untranslated message(s).
"es": 4 untranslated message(s).
"fr": 4 untranslated message(s).
"hi": 4 untranslated message(s).
"it": 4 untranslated message(s).
"ko": 4 untranslated message(s).
"pt": 4 untranslated message(s).
"ru": 4 untranslated message(s).
"zh": 4 untranslated message(s).
"zh_HK": 4 untranslated message(s).
To see a detailed report, use the untranslated-messages-file
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection>


This will generate a JSON format file containing all messages that
need to be translated.
Launching lib\main.dart on sdk gphone x86 64 in debug mode...
Building with Flutter multidex support enabled.
C:\Users\cianr\OneDrive\Business\PresentPal\App\presentpal\android\key.properties
C:\Users\cianr\AppData\Local\Pub\Cache\hosted\pub.dev\firebase_messaging-14.7.10\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingPlugin.java:389: error: cannot find symbol
            .checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)
                                                    ^
  symbol:   variable POST_NOTIFICATIONS
  location: class permission
C:\Users\cianr\AppData\Local\Pub\Cache\hosted\pub.dev\firebase_messaging-14.7.10\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebasePermissionManager.java:63: error: cannot find symbol
    permissions.add(Manifest.permission.POST_NOTIFICATIONS);
                                       ^
  symbol:   variable POST_NOTIFICATIONS
  location: class permission
Note: C:\Users\cianr\AppData\Local\Pub\Cache\hosted\pub.dev\firebase_messaging-14.7.10\android\src\main\java\io\flutter\plugins\firebase\messaging\JobIntentService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\cianr\AppData\Local\Pub\Cache\hosted\pub.dev\firebase_messaging-14.7.10\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_messaging:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Running Gradle task 'assembleDebug'...                             28,7s
Exception: Gradle task assembleDebug failed with exit code 1

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22631.3007], locale en-ZA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the  
      "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

```

</details>
