### ISSUE TITLE
Collect non-benchmark tests which use a physical device

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#142070]
Most non-benchmark tests should be able to run without a physical device, and an emulator should be used instead to save limited DeviceLab resources and potentially improve the test execution time.

This bug tracks to collect the list.

/cc @matanlurey @jonahwilliams @jmagman

**Comment by matanlurey** [comment]
Thank you! Here is an easy one:

```yaml
  - name: Linux_pixel_7pro external_ui_integration_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: external_textures_integration_test

  - name: Mac_ios external_ui_integration_test_ios
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "ios", "mac"]
      task_name: external_textures_integration_test_ios
      ignore_flakiness: "true"
```

These don't need a physical device.

**Comment by jmagman** [comment]
`external_ui_integration_test_ios` is using the `dev/devicelab/integration_test` runners which check which devices are running, and pass `-d` to the tool, and fail if there are no devices tethered.  So this change isn't just to change the bot properties, it would involve swapping them to a different or more flexible test runner, like moving them into the tools tests.

Same for:
`channels_integration_test_ios`
`route_test_ios`
`flavors_test_ios`
`flavors_test_ios_xcode_debug`
`integration_test_test_ios`
`integration_ui_ios_driver`
`integration_ui_ios_driver_xcode_debug`
and others on the `devicelab/devicelab_drone` recipe.

**Comment by jonahwilliams** [comment]
Some more tests that can be emulators

```
  - name: Linux_pixel_7pro android_defines_test
    recipe: devicelab/devicelab_drone
    presubmit: true
    timeout: 60
    dimensions:
      kvm: "1"
      cores: "8"
      machine_type: "n1-standard-8"
    properties:
      contexts: >-
        [
          "android_virtual_device"
        ]
      device_type: "none"
      tags: >
        ["devicelab", "linux"]
      task_name: android_defines_test
      dependencies: >-
        [
          {"dependency": "android_virtual_device", "version": "34"}
        ]

  - name: Linux_pixel_7pro android_obfuscate_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: android_obfuscate_test

  - name: Linux_pixel_7pro android_semantics_integration_test
    recipe: devicelab/devicelab_drone
    bringup: true # Flaky: https://github.com/flutter/flutter/issues/124636
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: android_semantics_integration_test

  - name: Linux_pixel_7pro basic_material_app_android__compile
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: basic_material_app_android__compile
      
 - name: Linux_pixel_7pro channels_integration_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: channels_integration_test


  - name: Linux_pixel_7pro drive_perf_debug_warning
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: drive_perf_debug_warning

- name: Linux_pixel_7pro embedded_android_views_integration_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: embedded_android_views_integration_test

  - name: Linux_pixel_7pro external_ui_integration_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: external_ui_integration_test

  - name: Linux_pixel_7pro flavors_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: flavors_test

  - name: Linux_pixel_7pro flutter_gallery_android__compile
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: flutter_gallery_android__compile


  - name: Linux_pixel_7pro frame_policy_delay_test_android
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: frame_policy_delay_test_android

  - name: Linux_pixel_7pro integration_ui_driver
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: integration_ui_driver

  - name: Linux_pixel_7pro integration_ui_keyboard_resize
    bringup: true # Flaky https://github.com/flutter/flutter/issues/140645
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: integration_ui_keyboard_resize
      
        - name: Linux_pixel_7pro integration_ui_textfield
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: integration_ui_textfield

  - name: Linux_pixel_7pro native_assets_android
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: native_assets_android

  - name: Linux_pixel_7pro platform_channel_sample_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: platform_channel_sample_test

  - name: Linux_pixel_7pro platform_interaction_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: platform_interaction_test

  - name: Linux_pixel_7pro routing_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: routing_test

  - name: Linux_pixel_7pro service_extensions_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: service_extensions_test


  - name: Linux_pixel_7pro android_choreographer_do_frame_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: android_choreographer_do_frame_test


  - name: Mac_pixel_7pro entrypoint_dart_registrant
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "mac", "pixel", "7pro"]
      task_name: entrypoint_dart_registrant
    runIf:
      - dev/**
      - packages/flutter_tools/**
      - bin/**
      - .ci.yaml

  - name: Mac_pixel_7pro hello_world_android__compile
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "mac", "pixel", "7pro"]
      task_name: hello_world_android__compile


  - name: Mac_pixel_7pro integration_test_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "mac", "pixel", "7pro"]
      task_name: integration_test_test


  - name: Mac_pixel_7pro integration_ui_frame_number
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "mac", "pixel", "7pro"]
      task_name: integration_ui_frame_number


  - name: Mac_pixel_7pro native_assets_android
    recipe: devicelab/devicelab_drone
    presubmit: false
    bringup: true
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "mac", "pixel", "7pro"]
      task_name: native_assets_android

  - name: Mac_pixel_7pro run_debug_test_android
    recipe: devicelab/devicelab_drone
    presubmit: false
    runIf:
      - .ci.yaml
      - dev/**
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "mac", "pixel", "7pro"]
      task_name: run_debug_test_android

  - name: Mac_pixel_7pro run_release_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    runIf:
      - .ci.yaml
      - dev/**
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "mac", "pixel", "7pro"]
      task_name: run_release_test

```


Not sure about this one (@yjbanov ) but it looks like this should not be a device test at all

```

  - name: Linux_pixel_7pro flutter_gallery_v2_chrome_run_test
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: flutter_gallery_v2_chrome_run_test
      
        - name: Linux_pixel_7pro linux_chrome_dev_mode
    recipe: devicelab/devicelab_drone
    presubmit: false
    timeout: 60
    properties:
      tags: >
        ["devicelab", "android", "linux", "pixel", "7pro"]
      task_name: linux_chrome_dev_mode
      ```
