### ISSUE TITLE
Custom font is not being picked up in Flutter

### ISSUE THREAD

**Issue by LahaLuhem** [flutter/flutter#142373]
### Steps to reproduce

1. Download the 'VCR OSD Mono' font 
[VCR_OSD_MONO.zip](https://github.com/flutter/flutter/files/14072074/VCR_OSD_MONO.zip)

2. Create a new app and place the TTF inside 'assets/fonts' directory like so:
<img width="169" alt="image" src="https://github.com/flutter/flutter/assets/47954571/8fdb83bc-ac20-46a5-8632-66ce86059982">

3. Use the following pubspec.yaml
```yml
name: pong
description: My old-school Pong game
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flame: ^1.9.1
  flame_audio: ^2.1.1
  flame_behaviors: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  #  google_fonts: ^6.1.0
  intl: ^0.18.1
  light_logger: ^0.0.3
#  mockingjay: ^0.4.0

dev_dependencies:
  #  bloc_test: ^9.1.4
  #dart run dart_code_metrics:metrics check-unused-files lib
  dart_code_metrics: ^5.7.6
  #dart run dependency_validator
  dependency_validator: ^3.2.3
  #  flame_test: ^1.13.1
  flutter_test:
    sdk: flutter
  #  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  #  assets:
  #    - assets/audio/

  fonts:
    - family: VCR OSD Mono
      fonts:
        - asset: assets/fonts/VCR_OSD_MONO.ttf

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: "en"
  output_dir: lib/l10n/generated
  line_length: 100
  # use_deferred_loading: true
```

4. Build and run the app using the code sample provided in the 'Code Sample' section

### Expected results

The Text is rendered in with specified font, as seen in the IDE itself:
<img width="621" alt="image" src="https://github.com/flutter/flutter/assets/47954571/1982b59f-a022-44bd-87ed-b9456ceceb77">

### Actual results

The Text is rendered with the default style:
<img width="418" alt="image" src="https://github.com/flutter/flutter/assets/47954571/b803a0e4-e09a-4376-b01c-f619b104ef23">

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(
    _PongGameApp(),
  );
}
class _PongGameApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        theme: ThemeData(fontFamily: 'VCR OSD Mono'),
        home: Scaffold(
          body: Center(
            child: Text(
              '01 ABC',
              style: TextStyle(fontFamily: 'VCR OSD Mono'),
            ),
          ),
        ),
      );
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="910" alt="image" src="https://github.com/flutter/flutter/assets/47954571/d4c3b77b-f11c-4be3-9812-c067318eb25f">
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.1, on Microsoft Windows [Version 10.0.22621.3007], locale en-NL)
    • Flutter version 3.16.1 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (9 weeks ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\ahalm\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Other Apps\programming\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Other Apps\programming\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at C:\Program Files\Other Apps\programming\IntelliJ IDEA 2023.1.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.3007]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 120.0.6099.227
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 120.0.2210.144

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>
