### ISSUE TITLE
_RawView is leaking in 'runApp throws if given a View'

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#142416]
The leak is introduced by https://github.com/flutter/flutter/pull/142344
The leak does not repro on mac, but repros on Windows, with bots.
PR that repros the leak: https://github.com/flutter/flutter/pull/142414

Can it by test only because of using `FakeFlutterView`?

Code that creates not disposed objects:

```
  @override
  RenderObjectElement createElement() => _RawViewElement(this);

  @override
  RenderObject createRenderObject(BuildContext context) {
    return _deprecatedRenderView ?? RenderView(
      view: view,
    );
  }

```

Failing test: `runApp throws if given a View`

**Comment by polina-c** [comment]
```
01:25 +2722 ~102 -1: C:/b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/multi_view_binding_test.dart: (tearDownAll) [E]
  Expected: leak free
    Actual: <Instance of 'Leaks'>
     Which: contains leaks:
            # The text is generated by leak_tracker.
            # For leak troubleshooting tips open:
            # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
            notDisposed:
              total: 2
              objects:
                _RawViewElement:
                  test: runApp throws if given a View
                  identityHashCode: 224269123
                  context:
                    start: >
                      #6_______dispatchFlutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/testing.dart:74:23)
                      #7______FlutterMemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:249:23)
                      #8______FlutterMemoryAllocations.dispatchObjectCreated_(package:flutter/src/foundation/memory_allocations.dart:283:5)
                      #9______new_Element_(package:flutter/src/widgets/framework.dart:3391:41)
                      #10_____new_RenderObjectElement_(package:flutter/src/widgets/framework.dart)
                      #11_____new_RenderTreeRootElement_(package:flutter/src/widgets/framework.dart)
                      #12_____new__RawViewElement_(package:flutter/src/widgets/view.dart)
                      #13______RawView.createElement_(package:flutter/src/widgets/view.dart:247:42)
                      #14_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4331:42)
                      #15_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3847:18)
                      #16_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #17_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #18_____ComponentElement._firstBuild_(package:flutter/src/widgets/framework.dart:5463:5)
                      #19_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5457:5)
                      #20_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4336:16)
                      #21_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3841:20)
                      #22_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #23_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #24_____ProxyElement.update_(package:flutter/src/widgets/framework.dart:5810:5)
                      #25_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #26_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #27_____StatefulElement.performRebuild_(package:flutter/src/widgets/framework.dart:5644:11)
                      #28_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #29_____StatefulElement.update_(package:flutter/src/widgets/framework.dart:5667:5)
                      #30_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #31_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #32_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #33_____ProxyElement.update_(package:flutter/src/widgets/framework.dart:5810:5)
                      #34_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #35_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #36_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #37_____ProxyElement.update_(package:flutter/src/widgets/framework.dart:5810:5)
                      #38_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #39______RawViewElement._updateChild_(package:flutter/src/widgets/view.dart:291:16)
                      #40______RawViewElement.update_(package:flutter/src/widgets/view.dart:378:5)
                      #41_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #42_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #43_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #44_____StatelessElement.update_(package:flutter/src/widgets/framework.dart:5557:5)
                      #45_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #46_____RootElement._rebuild_(package:flutter/src/widgets/binding.dart:1434:16)
                      #47_____RootElement.update_(package:flutter/src/widgets/binding.dart:1412:5)
                      #48_____RootElement.performRebuild_(package:flutter/src/widgets/binding.dart:1426:7)
                      #49_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #50_____BuildOwner.buildScope_(package:flutter/src/widgets/framework.dart:2905:19)
                      #51_____AutomatedTestWidgetsFlutterBinding.drawFrame_(package:flutter_test/src/binding.dart:1419:19)
                      #52_____RendererBinding._handlePersistentFrameCallback_(package:flutter/src/rendering/binding.dart:443:5)
                      #53_____SchedulerBinding._invokeFrameCallback_(package:flutter/src/scheduler/binding.dart:1386:15)
                      #54_____SchedulerBinding.handleDrawFrame_(package:flutter/src/scheduler/binding.dart:1311:9)
                      #55_____AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame_(package:flutter_test/src/binding.dart:1365:5)
                      #56______runWidget_(package:flutter/src/widgets/binding.dart:1295:7)
                      #57_____runApp_(package:flutter/src/widgets/binding.dart:1226:3)
                      #58_____main.<anonymous_closure>_(file:///C:/b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/multi_view_binding_test.dart:44:5)
                      #59_____testWidgets.<anonymous_closure>.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:183:29)
                      <asynchronous_suspension>
                      #60_____TestWidgetsFlutterBinding._runTestBody_(package:flutter_test/src/binding.dart:1019:5)
                      <asynchronous_suspension>
                      #61_____StackZoneSpecification._registerCallback.<anonymous_closure>_(package:stack_trace/src/stack_zone_specification.dart:114:42)
                      <asynchronous_suspension>
                RenderView:
                  test: runApp throws if given a View
                  identityHashCode: 946076616
                  context:
                    start: >
                      #6_______dispatchFlutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/testing.dart:74:23)
                      #7______FlutterMemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:249:23)
                      #8______FlutterMemoryAllocations.dispatchObjectCreated_(package:flutter/src/foundation/memory_allocations.dart:283:5)
                      #9______new_RenderObject_(package:flutter/src/rendering/object.dart:1659:41)
                      #10_____new__RenderView&RenderObject&RenderObjectWithChildMixin_(package:flutter/src/rendering/view.dart)
                      #11_____new_RenderView_(package:flutter/src/rendering/view.dart)
                      #12______RawView.createRenderObject_(package:flutter/src/widgets/view.dart:251:37)
                      #13_____RenderObjectElement.mount_(package:flutter/src/widgets/framework.dart:6448:52)
                      #14______RawViewElement.mount_(package:flutter/src/widgets/view.dart:310:11)
                      #15_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4336:16)
                      #16_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3847:18)
                      #17_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #18_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #19_____ComponentElement._firstBuild_(package:flutter/src/widgets/framework.dart:5463:5)
                      #20_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5457:5)
                      #21_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4336:16)
                      #22_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3841:20)
                      #23_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #24_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #25_____ProxyElement.update_(package:flutter/src/widgets/framework.dart:5810:5)
                      #26_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #27_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #28_____StatefulElement.performRebuild_(package:flutter/src/widgets/framework.dart:5644:11)
                      #29_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #30_____StatefulElement.update_(package:flutter/src/widgets/framework.dart:5667:5)
                      #31_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #32_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #33_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #34_____ProxyElement.update_(package:flutter/src/widgets/framework.dart:5810:5)
                      #35_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #36_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #37_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #38_____ProxyElement.update_(package:flutter/src/widgets/framework.dart:5810:5)
                      #39_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #40______RawViewElement._updateChild_(package:flutter/src/widgets/view.dart:291:16)
                      #41______RawViewElement.update_(package:flutter/src/widgets/view.dart:378:5)
                      #42_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #43_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5506:16)
                      #44_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #45_____StatelessElement.update_(package:flutter/src/widgets/framework.dart:5557:5)
                      #46_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3825:15)
                      #47_____RootElement._rebuild_(package:flutter/src/widgets/binding.dart:1434:16)
                      #48_____RootElement.update_(package:flutter/src/widgets/binding.dart:1412:5)
                      #49_____RootElement.performRebuild_(package:flutter/src/widgets/binding.dart:1426:7)
                      #50_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5197:7)
                      #51_____BuildOwner.buildScope_(package:flutter/src/widgets/framework.dart:2905:19)
                      #52_____AutomatedTestWidgetsFlutterBinding.drawFrame_(package:flutter_test/src/binding.dart:1419:19)
                      #53_____RendererBinding._handlePersistentFrameCallback_(package:flutter/src/rendering/binding.dart:443:5)
                      #54_____SchedulerBinding._invokeFrameCallback_(package:flutter/src/scheduler/binding.dart:1386:15)
                      #55_____SchedulerBinding.handleDrawFrame_(package:flutter/src/scheduler/binding.dart:1311:9)
                      #56_____AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame_(package:flutter_test/src/binding.dart:1365:5)
                      #57______runWidget_(package:flutter/src/widgets/binding.dart:1295:7)
                      #58_____runApp_(package:flutter/src/widgets/binding.dart:1226:3)
                      #59_____main.<anonymous_closure>_(file:///C:/b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/multi_view_binding_test.dart:44:5)
                      #60_____testWidgets.<anonymous_closure>.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:183:29)
                      <asynchronous_suspension>
                      #61_____TestWidgetsFlutterBinding._runTestBody_(package:flutter_test/src/binding.dart:1019:5)
                      <asynchronous_suspension>
                      #62_____StackZoneSpecification._registerCallback.<anonymous_closure>_(package:stack_trace/src/stack_zone_specification.dart:114:42)
                      <asynchronous_suspension>

```
