### ISSUE TITLE
Consider a custom generator for `.dart_tool/package_config.json` in `engine/tools/...`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144043]
My proposal is to roll our own `.dart_tool/package_config.json`, or something the Dart team might have developed for their own mono repos, instead of using `dart pub get` with a lot of confusing constraints.

## Background

The engine _nominally_ uses `pubspec.yaml` files to define repository-private Dart packages:

[![Screenshot 2024-02-23 at 11 19 20 AM](https://github.com/flutter/flutter/assets/168174/381b5977-4724-4efe-986c-798391d3e90f)](https://github.com/search?q=repo%3Aflutter%2Fengine+path%3Apubspec.yaml&type=code)

We add a scary message to most of them:

```txt
# Do not add any dependencies that require more than what is provided in
# //third_party/pkg, //third_party/dart/pkg, or
# //third_party/dart/third_party/pkg. In particular, package:test is not usable
# here.

# If you do add packages here, make sure you can run `pub get --offline`, and
# check the .packages and .package_config to make sure all the paths are
# relative to this directory into //third_party/dart
```

... and use [quasi-custom tooling to enforce that all paths come from local dependencies](https://github.com/flutter/engine/blob/main/tools/pub_get_offline.py).

Developing these packages, updating the pubspec, is cumbersome, because we need to (manually) iterate out all transitive dependencies via `dependency_overrides` and point to a confusing matrix of local dependencies. For example, [`dir_contents_diff`](https://github.com/flutter/engine/blob/main/tools/dir_contents_diff/pubspec.yaml):

```yaml
dev_dependencies:
  litetest: any
  path: any
dependency_overrides:
  async_helper:
    path: ../../../third_party/dart/pkg/async_helper
  expect:
    path: ../../../third_party/dart/pkg/expect
  litetest:
    path: ../../testing/litetest
  meta:
    path: ../../../third_party/dart/pkg/meta
  path:
    path: ../../../third_party/dart/third_party/pkg/path
  smith:
    path: ../../../third_party/dart/pkg/smith
```
