### ISSUE TITLE
App stays atop the lock screen on Android

### ISSUE THREAD

**Issue by imdatsolak** [flutter/flutter#144674]
### Steps to reproduce

1. Start my app
2. Use the Android phone's physical lock button -> the device screen is locked and off
3. Use the same lock button again to activate the device

### Expected results

Only the Android lock screen is shown and requires unlocking the device to see the app.

### Actual results

My app is shown, without the need to unlock the device in the first place.

### Code sample

<details open><summary>No code sample, only pubspec.yaml</summary>

```yaml
name: cicero
description: Ginlo.net Cicero Core package
homepage: https://github.com/ginlo2/cicero
copyright: Copright (c) 2021 Imdat Celeste Solak, Copyright (c) 2022-2024 ginlo.net GmbH
publish_to: 'none'

version: 1.0.0+534

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.19.1'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: '^2.0.2'

  flutter_localizations:
    sdk: flutter

  # ## FROM HERE UNTIL "END", please KEEP ALPHABETICALLY SORTED, MAKES LIFE EASIER
  adaptive_theme: '^3.1.1'

  airplane_mode_checker: '^2.0.0'

  app_group_directory: '^2.0.0'

  audio_session: '^0.1.16'

  # ASN.1 Parser for Dart
  asn1lib: '^1.0.2'

  badges: '^3.0.2'

  basic_utils: '^5.5.3'

  # For hashing the phone numbers & email addresses, *sigh*
  bcrypt: '^1.1.3'

  camera: '^0.10.5'
  camera_windows: '^0.2.1+6'
  camera_macos: '^0.0.6+5'

  collection: '^1.17.0'

  connectivity_plus: '^5.0.2'

  country_picker: '^2.0.20'

  # iOS Icons
  cupertino_icons: '^1.0.2'

  croppy: '^1.1.4'

  # cryptography
  # ECC
  # AES
  # KDF
  cryptography: '^2.5.0'
  cryptography_flutter: '^2.3.0'

  # Hardware info
  device_info_plus: '^9.0.0'

  # Webview for macOS, Windows & Linux
  # For Windows 10 we need to decide how to distribute Webview2
  # https://pub.dev/packages/desktop_webview_window
  desktop_webview_window: '^0.2.0'

  duration_picker: '^1.1.1'

  # email validator
  email_validator: '^2.1.2'

  emoji_picker_flutter: '^1.6.4'

  # encrypt: we still need this for RSA (only)
  encrypt: '^5.0.0'

  # TODO:
  # epub_view: 3.0.0

  # file_selector; to choose files to import/send
  file_picker: '^6.1.1'

  flutter_app_badger: '^1.5.0'

  # Bar Code/QR-Code Scanner (iOS/Android only)
  flutter_barcode_scanner: '^2.0.0'

  flutter_broadcasts:
    git:
      url: git@github.com:imdatsolak/flutter_broadcasts.git
      ref: ics/android-14-support

  # CallKit Integration
  flutter_callkit_incoming: '^2.0.0+1'

  # Flutter Contact Picker for iOS/Android
  flutter_contacts: '^1.1.4'

  # Date/Time Picker
  flutter_datetime_picker_bdaya: '^3.0.1'

  flutter_email_sender: '^6.0.2'

  # Broadcastlist face-pile
  flutter_face_pile: '^0.0.3'

  # highlighter
  flutter_highlighter: '^0.1.1'

  # To preview documents/attachments
  flutter_inappwebview: '^6.0.0-beta.24+1'

  # Linkify text
  flutter_linkify: '^6.0.0'

  # Local Notifications, mainly for macOS, Linux (Windows?)
  flutter_local_notifications: '^16.1.0'

  # flutter map: support mapping
  flutter_map: '^4.0.0'

  # Display markdown content
  flutter_markdown: '^0.6.14'

  # Secure Storage (Keychain, etc)
  # Check out: https://pub.dev/packages/flutter_secure_storage#configure-linux-version
  # to build  Linux Client
  flutter_secure_storage: '^9.0.0'

  # Receive Sharing on iOS/Android
  flutter_sharing_intent:
    git:
      url: git@github.com:imdatsolak/flutter_sharing_intent.git
      ref: imdatsolak/ios-fix

  # Slide list-entries to show action buttons
  flutter_slidable: '^3.0.0'

  # To show toast messages - no support for Desktop
  fluttertoast: '^8.0.7'

    # gallery_saver: '^2.3.2'

  # Check if Google Service is available on Andriod
  google_api_availability: '^5.0.0'

  # google fonts
  google_fonts: '^4.0.4'

  # gRPC Plugin
  grpc: '^3.1.0'

  # http
  http: '^0.13.5'

  # A Dart library providing the ability to load, save and manipulate images in a variety of different file formats.
  image: '^4.0.10'

  #
  image_gallery_saver: '^2.0.3'

  # Support for webp-images
  # image_compression_flutter: '^1.0.2'

  # Flutter image picker for iOS and Android
  image_picker: '^1.0.0'

  # Network Connectivity; check whether we have a network
  internet_connection_checker: '^1.0.0+1'

  # Internationalization & Localization
  intl: '^0.18.0'

  intl_utils: '^2.5.1'

  is_lock_screen2: '^2.0.1'

  # Hopefully a well mainted jitsi-meet wrapper
  jitsi_meet_flutter_sdk: '^0.1.9'

  # Necessary for parsing JSON
  json_annotation: '^4.8.1'

  # Just Audio - playback audio
  just_audio: '^0.9.28'

  # Windows - Version
  just_audio_windows: '^0.2.0'

  # Waveform
  just_waveform: '^0.0.3'

  # Latitude/Longitude
  latlong2: '^0.8.1'

  linkify: '^5.0.0'

  # Biometric authentication
  local_auth: '^2.1.6'
  local_auth_android:
  local_auth_ios:
  local_auth_platform_interface:

  # Location
  location: '5.0.0'

  # Loggerpgger
  logging: '^1.0.2'

  # Not to forget: for animations
  lottie: '^3.0.0'

  # dart markdown
  markdown: '^7.0.1'

  # Modal Bottom Sheet
  modal_bottom_sheet: '^3.0.0-pre'

  # Android Lockscreen problem
  move_to_background:
    git:
      url: git@github.com:imdatsolak/move_to_background.git

  # Required to prevent crasing in shared_preferences
  mutex: '^3.0.0'

  # Package Info that provides information about the application from its package
  package_info_plus: '^5.0.1'

  # Path tools
  path: '^1.8.3'

  # ... and we need to know our application's data directory
  path_provider: '^2.0.1'

  pdfx:
    git:
      url: git@github.com:imdatsolak/packages.flutter.git
      ref: imdatsolak/dip
      path: packages/pdfx

  permission_handler: '^11.2.0'

  # phone number formatting, parsing, editing - pure dart
  phone_numbers_parser: '^8.1.3'

  photo_view: '^0.14.0'

  pin_code_fields: '^8.0.1'

  # PointyCastle for RSA
  pointycastle: '^3.7.2'

  # Protocol Buffers for gRPC
  protobuf: '^3.0.0'

  # QR-Code generator
  qr_flutter: '^4.0.0'

  # Audio Recorder for Android, iOS, Linux, MacOS, Windows
  record: '^5.0.1'

  # reorderable
  reorderables: '0.6.0'

  # rxdart: needs to be replaced,
  rxdart: '^0.27.5'

  # We use scoped_model for keeping the app state
  scoped_model: '^2.0.0-nullsafety.0'

  # screenshot
  screenshot:
    git:
      url: git@github.com:imdatsolak/screenshot.git
      ref: ics/f319

  # Scroll to a specific position in listview
  scrollview_observer: '^1.10.1'

  # Share for iOS/Android only
  # Use drag & drop for Desktop
  share_plus: '^7.0.2'

  # For general settings, configuration, state saving
  shared_preferences: '^2.1.2'

  # TODO: replace using flutter_contacts (or so)
  simple_vcard_parser: '^0.2.0'

  # Your standard sprintf
  sprintf: '^7.0.0'

  # We store data in SQLite; sqflite supports iOS, Android, macOS
  # For Windows/Linux, we need to add sqflite_common_ffi (check out lib/main.dart)
  sqflite: '^2.0.0+3'
  sqflite_common_ffi: '^2.0.0'

  # List with section headers
  sticky_and_expandable_list: '^1.1.0'

  # This is supposed to be multi-platform drag and drop
  super_clipboard: '^0.7.3'
  super_drag_and_drop: '^0.7.3'

  # open url in external browser
  url_launcher: '^6.1.7'

  # UUID Generation for GUIDs, unique file names, etc.
  uuid: '^4.1.0'

  # Video compress/thumbnailer: iOS, Android, macOS
  video_compress:
    git:
      url: git@github.com:imdatsolak/VideoCompress.git
      ref: imdatsolak/duration-fix

  # video player for iOS/Android
  video_player: '^2.6.0'

  window_manager: '^0.3.5'

  # Xml Parser
  xml_parser: '^1.0.0'

  # ## END (of main plugins)

dev_dependencies:
  flutter_lints: '^3.0.1'
  build_runner: '^2.1.5'
  json_serializable: '^6.0.1'
  lints: '^3.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: eu.ginloapps.cicero
        pluginClass: CiceroPlugin
      ios:
        pluginClass: CiceroPlugin
      linux:
        pluginClass: CiceroPlugin
      macos:
        pluginClass: CiceroPlugin
      windows:
        pluginClass: CiceroPluginCApi

  uses-material-design: true

flutter_intl:
  enabled: true
```

And `pubspec.yaml` of the app itself:

```yaml
name: ginlo2ps
description: Ginlo 2 Staging
publish_to: 'none'
copyright: Copyright (c) 2023-2024 ginlo.net GmbH

version: 1.0.0+534

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.19.1'

dependencies:
  flutter:
    sdk: flutter

  firebase:
    git: 
      url: git@github.com:ginlo2/firebase.git
      ref: main

  flutter_localizations:
    sdk: flutter

  cicero:
    git:
      url: git@github.com:ginlo2/cicero.git
      ref: develop

  cupertino_icons: '^1.0.2'

  flutter_sharing_intent:
    git:
      url: git@github.com:imdatsolak/flutter_sharing_intent.git
      ref: imdatsolak/ios-fix

  intl: '^0.18.0'

  window_manager: '^0.3.7'

dev_dependencies:
  flutter_lints: '^2.0.2'
  lints: '^2.1.1'


flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - rsrc/animations/
    - rsrc/animations/lottie/
    - rsrc/ca/
    - rsrc/images/
    - rsrc/images/appIcons/
    - rsrc/images/backgrounds/
    - rsrc/images/filetypes/
    - rsrc/images/logos/
    - rsrc/images/mini_logos/
    - rsrc/images/placeholders/
    - rsrc/images/others/
    - rsrc/sounds/
    - rsrc/sounds/notifications/
    - rsrc/sounds/notifications/classic/
    - rsrc/sounds/notifications/modern/
    - rsrc/texts/
    - rsrc/texts/de/
    - rsrc/texts/en/
    - rsrc/texts/font_licenses/

flutter_intl:
  enabled: true
```
</details>


### Screenshots or Video

<details open>
<summary>
Two files attached: `expected_behavior.mov` and `actual_behavior.mov`

The `expected_behavior` is implemented by me by checking if the lock-button was pressed when my app is PAUSED. I then send my app to the background. This should be default behavior.
</summary>

https://github.com/flutter/flutter/assets/10852644/1e7b97dd-c9e8-4082-8349-f979075efacf


https://github.com/flutter/flutter/assets/10852644/542fab21-d756-42f5-a039-c6b19b7f97a2




</details>


### Logs

<details open><summary>N/A</summary>

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
╰─ flutter doctor -v                                                                                                                                                                                                                                 
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
    • Flutter version 3.19.1 on channel stable at /Users/iso/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (2 weeks ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/iso/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/iso/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (7 available)
    • Pixel 6 (mobile)  • 23311FDF600421            • android-arm64 • Android 14 (API 34)
    • SM T860 (mobile)  • R52N8175P2E               • android-arm64 • Android 12 (API 32)
    • SM A536B (mobile) • RZCT909TEZY               • android-arm64 • Android 14 (API 34)
    • Goldie (mobile)   • 00008110-0012158C0EE8401E • ios           • iOS 17.3.1 21D61
    • iPad (mobile)     • 00008020-000108D13A41002E • ios           • iOS 17.3.1 21D61
    • iPro S (mobile)   • 00008112-000879201408C01E • ios           • iOS 17.3.1 21D61
    • macOS (desktop)   • macos                     • darwin-arm64  • macOS 14.3.1 23D60 darwin-arm64
    ! Error: iPhone 6s (2) has recently restarted. Xcode will continue when iPhone 6s (2) is unlocked. (code -14)
    ! Error: iPhone X has recently restarted. Xcode will continue when iPhone X is unlocked. (code -14)
    ! Error: Browsing on the local area network for isoWatch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>
