### ISSUE TITLE
Guideline 2.3.1 - Performance

### ISSUE THREAD

**Issue by Ameenhamed** [flutter/flutter#144684]
Every time I get this response , even though I don't use the hidden codes from what he mentioned

```
Hello,

Thank you for your resubmission. Upon further review, we identified additional issues that need your attention. See below for more information.

If you have any questions, we are here to help. Reply to this message in App Store Connect and let us know. 

Guideline 2.3.1 - Performance

The app may contain hidden features, functionality, or content.

Specifically, the app may still contain financial transactions without the necessary authorization. Apps that provide financial transactions without the necessary authorization do not comply with guidelines [3.2.2](https://developer.apple.com/app-store/review/guidelines/#unacceptable) and [5.1.1(ix)](https://developer.apple.com/app-store/review/guidelines/#data-collection-and-storage). 

Users should never be misled about the apps they download. Attempting to hide features, functionality, or content in the app may lead to removal from the Apple Developer Program.

Next Steps

It would be appropriate to identify any hidden features, functionality, or content in the app, including in third-party code or SDKs, and revise or remove the hidden material before resubmitting for review. 

If you feel that we have misunderstood how the app functions, reply to this message in App Store Connect to explain how these features work.
```

٫٫٫٫٫٫٫٫٫٫٫٫٫٫٫٫٫٫

I only use these packages has anyone encountered this problem and what is the solution
٫٫٫٫٫٫٫٫٫٫٫٫٫٫٫٫٫٫٫٫

```
environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.3
  get: ^4.6.6
  http: ^1.1.2
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.9
  top_snackbar_flutter: ^3.1.0
  line_icons: ^2.0.3
  socket_io_client: ^2.0.3+1
  permission_handler: ^11.1.0
  lecle_yoyo_player: ^0.0.8
  pull_to_refresh: ^2.0.0
  shimmer_pro: ^0.0.6
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  visibility_detector: ^0.4.0+2
  detectable_text_field: ^2.1.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  appinio_video_player: ^1.2.2
  flutter_social_textfield: ^0.1.2
  url_launcher: ^6.2.3
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  chewie: ^1.7.5
  file_picker: ^6.1.1
  flutter_polls: ^0.1.5
  just_audio: ^0.9.36
 
  intl: ^0.19.0
  onesignal_flutter: ^5.1.0
  dotlottie_loader: ^0.0.3
  lottie: ^3.0.0
  quickalert: ^1.0.2
  video_editor: ^2.4.0
  flutter_otp_text_field: ^1.1.1
  flutter_vibrate: ^1.3.0
  extended_phone_number_input: ^1.0.2
  loading_indicator: ^3.1.1
  uuid: ^4.3.3
  ant_media_flutter: ^1.0.10
  flutter_randomcolor: ^1.0.14

  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  flutter_dialogs: ^3.0.0
  ionicons: ^0.2.2
  flutter_deep_linking: ^0.2.1
  uni_links: ^0.5.1
  vs_story_designer: ^2.2.0
  webview_flutter: ^4.7.0
  google_fonts: ^6.1.0
  flutter_cached_video_player_plus: ^2.1.3
  flutter_hooks: ^0.18.6
  google_mobile_ads: ^4.0.0
  package_info_plus: ^5.0.1
  nb_utils: ^6.1.2
  flutter_paypal_payment: ^1.0.6
  pretty_qr_code: ^3.2.1
  flutter_barcode_scanner: ^2.0.0
  emoji_picker_flutter: ^2.1.0

  record: ^5.0.4
  audioplayers: ^5.2.1
```
