### ISSUE TITLE
Minify the CSS code injected/generated during a web build

### ISSUE THREAD

**Issue by ClementBeal** [flutter/flutter#145584]
### Use case

During a web build, some CSS code is generated in the `main.dart.js` but it is not minified. For example, 

```css
input[type=range] {  appearance: none;  -webkit-appearance: none;  width: 100%;  position: absolute;  border: none;  top: 0;  right: 0;  bottom: 0;  left: 0;}
```

It's a part of the CSS code we can find. As you can see, there's a lot of unnecessary white spaces.

### Proposal

Someone can clear all the white spaces we find in this file :

https://github.com/flutter/engine/blob/f9a34ae0b14f4dfd6a8cf9181ab5db3c14c0246d/lib/web_ui/lib/src/engine/view_embedder/style_manager.dart

It would save some bytes in the final `main.dart.js`
