### ISSUE TITLE
[flutter_tools] Supports multi-platform module config

### ISSUE THREAD

**Issue by mit-73** [flutter/flutter#145640]
### Use case

The module config declaration is not extensibility friendly and departs from the concept of multi-platform separation.

```yaml
flutter:
  module:
    androidX: true
    androidPackage: {{androidIdentifier}}
    iosBundleIdentifier: {{iosIdentifier}}
```

### Proposal

Необходимо переделать конфигурацию модулей в pubspec по аналогии plugin

```yaml
flutter:
  module:
    platforms:
      android:
        androidX: true
        package: {{androidIdentifier}}
      ios:
        bundleIdentifier: {{iosIdentifier}}
```

**Comment by christopherfujino** [comment]
@mit-73 can you elaborate more on why this change is needed?

**Comment by christopherfujino** [comment]
> This edit will improve the overall style of the code. I aim to create a structure similar to that of plugins. Currently, it appears as though the two platforms have been combined without any organization or structure.

I agree that the proposed style is an improvement. However, there is also a cost to migrating the schema of config file that users are maintaining. What I'm trying to decide if the benefits outweigh the costs.

> @christopherfujino this is needed to extend the possible configurable values, e.g. I want to solve problem #78862 in this way.

Technically, it's not required, right? We could do something ugly like:

```yaml
flutter:
  module:
    androidX: true
    minimumIosSdkVersion: 1.2.3
```

Right? Again, I'm not saying we *should* do this, but trying to understand and document the constraints.

Overall, I think this proposal makes a lot of sense. However, there is a cost to changing this schema. Also, if 6 months from now we realize that we actually want a DIFFERENT schema, we will have to pay the cost of changing it yet again.

So I think we need to carefully consider what we want this configuration to look like. I'm going to close your [PR](https://github.com/flutter/flutter/pull/145641) for now, not because it isn't helpful, but because I am not sure in my own mind how this should be implemented, and I think it's best to discuss first here on this issue, and possibly with a [design doc](https://github.com/flutter/flutter/wiki/Design-Documents).

**Comment by mit-73** [comment]
I realize that I was rushed and you are correct. This edit needs to be described in the design document first.

Unfortunately it is catastrophically important for me to fix issue #78862 in the nearest time and I will have to make it in an "ugly" style, I hope you don't mind?

**Comment by christopherfujino** [comment]
> Unfortunately it is catastrophically important for me to fix issue #78862 in the nearest time and I will have to make it in an "ugly" style, I hope you don't mind?

Can you elaborate more? You mean you have to merge an ugly fix upstream to flutter/flutter now? Or you need to have a workaround for your own use case?

And would https://github.com/flutter/flutter/issues/49378 avoid this catastrophe?

**Comment by mit-73** [comment]
I want to add something like that:

```
flutter:
  module:
    androidCompileSdkVersion: 34
    androidMinSdkVersion: 21
    androidTargetSdkVersion: 34
    iosDeploymentTarget: 14.0
    iosPlatformVersion: 14.0
```

It seems this could be used very easily in these places ([android](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/migrations/min_sdk_version_migration.dart#L21), [ios](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/migrations/ios_deployment_target_migration.dart#L10)) to override the values at the module.

On the other hand we can use the mechanism from #49378, but as I think it is not very convenient, because too many parameters will have to be passed through env (and they still need to be remembered), in the current example there are already 5 of them.
