### ISSUE TITLE
compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by YawarOsman** [flutter/flutter#145702]
### Steps to reproduce

IDK how to tell you to reproduce, but i have create a new flutter project and moved my old project files to it

### Actual results

This is my `android/build.gradle `file:

```
buildscript {
    ext.kotlin_version = '1.7.10' // Change here
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

    }
    
    apply plugin: 'android'

}



allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}


```

And this is `app/build.gradle `file:

```


plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.example.test_app"
    compileSdk 33
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.test_app
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 24
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {}


```

I have also tried `compileSdkVersion` and i also tried to put it inside `defaultConfig`, but nothing helped

### Logs

<details open>
<summary>Logs</summary>

```console

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 875ms
Error: Gradle task assembleDebug failed with exit code 1


Exited (1).


```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.19.2, on macOS 14.3.1 23D60 darwin-x64, locale en-IQ)
    • Flutter version 3.19.2 on channel stable at /Users/yara/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (4 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/yara/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.0)
    • VS Code at /Users/yara/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5556             • android-x64    • Android 14 (API 34) (emulator)
    • 3.14 (mobile)                • 00008101-001C688114E8001E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)              • macos                     • darwin-x64     • macOS 14.3.1 23D60 darwin-x64
    • Chrome (web)                 • chrome                    • web-javascript • Google Chrome 123.0.6312.59

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@YawarOsman 
Can you try `compileSdkVersion flutter.compileSdkVersion` and see if it helps ?
Also, check https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply and see if it helps or not.

**Comment by YawarOsman** [comment]
I tried it and not helped, both inside `android{` and `debugConfig{`.


And also i have did exactly what the docs said but now this error shows off:
```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```


 Here are my fiels:
 
` android/build.gradle:`

```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

`android/app/build.gradle:`
```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.example.test_app"
    compileSdk flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.test_app"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {}
```

`setting.gradle:`

```
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()
   
        includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
}

include ":app"

```


` ./gradlew --version`

``` 
------------------------------------------------------------
Gradle 7.6.3
------------------------------------------------------------

Build time:   2023-10-04 15:59:47 UTC
Revision:     1694251d59e0d4752d547e1fd5b5020b798a7e71

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          21.0.2 (Eclipse Adoptium 21.0.2+13-LTS)
OS:           Mac OS X 14.3.1 x86_64

**Comment by darshankawar** [comment]
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
> The following dependencies do not satisfy the required version:
> project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

What's the gradle version you are using in your gradle-wrapper ? Try to have it (something like 7.6.3) and see if it helps.

**Comment by YawarOsman** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-all.zip

**Comment by darshankawar** [comment]
> project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

This is pointing to community package. Try to upgrade it to latest version if not already on it and re-run, which should ideally solve the issue.
See https://github.com/creativecreatorormaybenot/wakelock/issues/231#issuecomment-1961218080

**Comment by YawarOsman** [comment]
I don't know what `wakelock` package has to do with that, but here is here is the result:

```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Error: Gradle task assembleDebug failed with exit code 1
```

And this is `pubspec.yaml` file:

```
name: ****

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_treeview: any
  dotted_border: any
  multi_dropdown: any
  calendar_date_picker2: any
  intl: any
  shared_preferences: any
  localization: any
  provider: any
  google_fonts: any
  font_awesome_flutter: any
  dropdown_search: any
  dropdown_textfield: any
  go_router: any
  http: any
  flutter_dotenv: any
  video_player: any
  data_table_2: any
  video_player_web: any
  firebase_auth: any
  firebase_core: any
  image_picker: any
  multiple_search_selection: any
  qr_flutter: any
  image_downloader_web: any
  syncfusion_flutter_charts: any
  crop_image: any
  image: any
  universal_html: any
  intl_phone_field: any
  location: any
  google_maps: any
  flutter_rating_bar: any
  flutter_colorpicker: any
  vsc_quill_delta_to_html: any
  chewie: ^1.7.5
  desktop_drop: any
  url_launcher: any
  flutter_svg: any
  phone_numbers_parser: any
  intl_translation: any
  syncfusion_flutter_datagrid: any
  syncfusion_flutter_core: any
  logger: any
  reorderable_grid: any
  two_dimensional_scrollables: any
  socket_io_client: any
  path_provider: any
  firebase_crashlytics: any
  package_info_plus: ^5.0.1
  flutter_native_splash: any
  cached_network_image: any
  wakelock: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_web_compilers: ^4.0.5

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # generate: ^0.2.1+3
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env


  fonts:
    - family: Rudaw
      fonts:
        - asset: assets/fonts/Rudaw.ttf

```
