### ISSUE TITLE
`hook/link.dart` consume data assets from pubspec.yaml

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#146265]
After https://github.com/flutter/flutter/issues/146263 and https://github.com/flutter/flutter/issues/146264 have landed, we could consider sending existing flutter data assets to link hooks:

```yaml
# pubspec.yaml of my_app
...
flutter:
...
  assets:
    - path: assets/translations.json
      link: messages # invokes package:messages' hook/link.dart to shrink  assets/translations.json
```

Alternatively, we could tell users that if they would like their assets to be tree shaken by a link hook, they must use a build hook to report them.

Somewhat similar behavior to

* https://github.com/flutter/flutter/issues/143348

Related umbrella issues:

* https://github.com/flutter/flutter/issues/129757
* https://github.com/dart-lang/native/issues/154

cc @mosuem @andrewkolos @christopherfujino
