### ISSUE TITLE
Issue from website page JSON and serialization: use latest json_serializable

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#14645]
From URL: https://flutter.io/json/#serializing-json-using-code-generation-libraries

Follow this PR (soon to land) https://github.com/dart-lang/json_serializable/pull/103

```yaml
dev_dependencies:
  build_runner: ^0.7.6
  json_serializable: ^0.3.2
```

Notice that library directives

```dart
library user;
```

Are no longer required! 

CC @sethladd @roughike
