### ISSUE TITLE
Root layer is not disposed in RenderView.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#146742]
To repro follow the steps: https://github.com/flutter/flutter/issues/141198#issuecomment-1987383965

Looks strange, because the layer seems to be accurately managed by a layer handle.

PR: https://github.com/flutter/flutter/pull/146743

**Comment by polina-c** [comment]
```
            notDisposed:
              total: 1
              objects:
                TransformLayer:
                  test: Should show event indicator for pointer events with setSurfaceSize
                  identityHashCode: 193929604
                  context:
                    start: >
                      #6_______dispatchFlutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/testing.dart:74:23)
                      #7______FlutterMemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:249:23)
                      #8______FlutterMemoryAllocations.dispatchObjectCreated_(package:flutter/src/foundation/memory_allocations.dart:283:5)
                      #9______new_Layer_(package:flutter/src/rendering/layer.dart:143:41)
                      #10_____new_ContainerLayer_(package:flutter/src/rendering/layer.dart)
                      #11_____new_OffsetLayer_(package:flutter/src/rendering/layer.dart)
                      #12_____new_TransformLayer_(package:flutter/src/rendering/layer.dart)
                      #13_____RenderView._updateMatricesAndCreateNewRootLayer_(package:flutter/src/rendering/view.dart:223:38)
                      #14_____RenderView.configuration=_(package:flutter/src/rendering/view.dart:156:24)
                      #15_____RendererBinding.handleMetricsChanged_(package:flutter/src/rendering/binding.dart:362:12)
                      #16_____WidgetsBinding.handleMetricsChanged_(package:flutter/src/widgets/binding.dart:726:11)
                      #17_____TestWidgetsFlutterBinding.setSurfaceSize.<anonymous_closure>_(package:flutter_test/src/binding.dart:531:7)
                      #18______rootRun_(dart:async/zone.dart:1399:13)
                      #19______CustomZone.run_(dart:async/zone.dart:1301:19)
                      #20_____TestAsyncUtils.guard_(package:flutter_test/src/test_async_utils.dart:71:41)
                      #21_____TestWidgetsFlutterBinding.setSurfaceSize_(package:flutter_test/src/binding.dart:525:27)
                      #22_____main.<anonymous_closure>_(file:///Users/polinach/_/flutter_dev/packages/flutter/test/animation/live_binding_test.dart:115:26)
                      #23_____testWidgets.<anonymous_closure>.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:183:29)
                      <asynchronous_suspension>
                      #24_____TestWidgetsFlutterBinding._runTestBody_(package:flutter_test/src/binding.dart:1017:5)
                      <asynchronous_suspension>
                      #25_____StackZoneSpecification._registerCallback.<anonymous_closure>_(package:stack_trace/src/stack_zone_specification.dart:114:42)
                      <asynchronous_suspension>
            
```
