### ISSUE TITLE
Camera plugin should use FLT prefix for all Objective-C types

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#14777]
The main `CameraPlugin` type has no prefix (possibly others too). To make that work with Flutter tooling, an `ios_prefix` clause must be added to the `pubspec.yaml` file:
```yaml
flutter:
  plugin:
    androidPackage: io.flutter.plugins.camera
    iosPrefix: FLT
    pluginClass: CameraPlugin
```
