### ISSUE TITLE
friendlychats

### ISSUE THREAD

**Issue by Santolama** [flutter/flutter#14778]
```Running "flutter packages get" in flutter-demo...
Error on line 6, column 5 of pubspec.yaml: A dependency may only have one source.
sdk: flutter
^^^^^^^^^^^^^^
---- Log transcript ----
FINE: Pub 2.0.0-dev.16.0
IO : Spawning "cmd /c ver" in C:\Users\James adelaja\flutter-dev\flutter-demo.
IO : Finished ver. Exit code 0.
| stdout:
| |
| | Microsoft Windows [Version 10.0.16299.192]
| Nothing output on stderr.
MSG : Resolving dependencies...
FINE: Resolving dependencies finished (0.0s).
ERR : Error on line 6, column 5 of pubspec.yaml: A dependency may only have one source.
| sdk: flutter
| ^^^^^^^^^^^^^^
FINE: Exception type: PubspecException
FINE: package:pub/src/pubspec.dart 910 Pubspec._error
| package:pub/src/pubspec.dart 761 Pubspec._parseDependencies.<fn>
| dart:collection MapView.forEach
| package:pub/src/pubspec.dart 725 Pubspec._parseDependencies
| package:pub/src/pubspec.dart 169 Pubspec.dependencies
| package:pub/src/package.dart 52 Package.dependencies
| package:pub/src/solver/backtracking_solver.dart 840 BacktrackingSolver._logParameters
| package:pub/src/solver/backtracking_solver.dart 163 BacktrackingSolver.solve
| package:pub/src/solver/version_solver.dart 42 resolveVersions.<fn>
| package:pub/src/log.dart 409 progress
| package:pub/src/solver/version_solver.dart 40 resolveVersions
| package:pub/src/entrypoint.dart 195 Entrypoint.acquireDependencies
| package:pub/src/command/get.dart 38 GetCommand.run
| package:args/command_runner.dart 194 CommandRunner.runCommand
| package:pub/src/command_runner.dart 167 PubCommandRunner.runCommand.<fn>
| dart:async new Future.sync
| package:pub/src/utils.dart 103 captureErrors.<fn>
| package:stack_trace Chain.capture
| package:pub/src/utils.dart 118 captureErrors
| package:pub/src/command_runner.dart 167 PubCommandRunner.runCommand
| package:pub/src/command_runner.dart 116 PubCommandRunner.run
| E:\b\build\slave\dart-sdk-windows-dev\build\sdk\third_party\pkg\pub\bin\pub.dart 8 main
| ===== asynchronous gap ===========================
| dart:async _Completer.completeError
| package:pub/src/solver/backtracking_solver.dart BacktrackingSolver.solve
| ===== asynchronous gap ===========================
| dart:async new Future.microtask
| package:pub/src/solver/backtracking_solver.dart 160 BacktrackingSolver.solve
| package:pub/src/solver/version_solver.dart 42 resolveVersions.<fn>
| package:pub/src/log.dart 409 progress
| package:pub/src/solver/version_solver.dart 40 resolveVersions
| package:pub/src/entrypoint.dart 195```

**Comment by zoechi** [comment]
This still needs the `pubspec.yaml` properly formatted
Here it's the same as in Gitter - add ``` before and after the code

**Comment by Santolama** [comment]
i am following the  codelab tutorial

**Comment by Santolama** [comment]
```
name: demo_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
    image_picker: 0.1.1
    google_sign_in: 0.3.1
    firebase_analytics: 0.0.4
    firebase_auth: 0.2.0
    firebase_database: 0.0.12
    firebase_storage: 0.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

```

**Comment by Santolama** [comment]
my pubspec.yaml

**Comment by xqwzts** [comment]
Looks like an indentation issue:
```
dependencies:
  flutter:
    sdk: flutter
  image_picker: 0.1.1
  google_sign_in: 0.3.1
  firebase_analytics: 0.0.4
  firebase_auth: 0.2.0
  firebase_database: 0.0.12
  firebase_storage: 0.0.5
```

**Comment by Santolama** [comment]
```
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.1.1
  google_sign_in: ^0.3.1
  firebase_analytics: ^0.0.4
  firebase_auth: ^0.2.0
  firebase_database: ^0.0.12
  firebase_storage: ^0.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
```
