### ISSUE TITLE
[url_launcher] The windows demo is breaking `build_runner` builds because of `pigeon`

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#147909]
### Steps to reproduce

Add `url_launcher` and `json_serializable` to your `pubspec.yaml`. **DON'T add `pigeon`**, adding it fixed the issue (But I don't want to use it).

Here's mine:

```yaml
environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  dio: ^5.3.3
  firebase_remote_config: ^4.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  package_info_plus: ^4.2.0
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.3
```

Add some freezed code, then run `dart run build_runner watch -d`

### Expected results

`build_runner` will run without errors

### Actual results

We get this error in the console:

```console
[SEVERE] json_serializable on example/ios/.symlinks/plugins/url_launcher_ios/pigeons/messages.dart (cached):

line 1, column 925 of asset:mpf_forced_updates/example/ios/.symlinks/plugins/url_launcher_ios/pigeons/messages.dart: Could not resolve annotation for `abstract class UrlLauncherApi`.
  ╷
1 │ @HostApi()
  │ ^^^^^^^^^^
  ╵
[SEVERE] json_serializable on example/windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/pigeons/messages.dart (cached):

line 1, column 204 of asset:mpf_forced_updates/example/windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/pigeons/messages.dart: Could not resolve annotation for `abstract class UrlLauncherApi`.
  ╷
1 │ ┌ @ConfigurePigeon(PigeonOptions(
2 │ │   dartOut: 'lib/src/messages.g.dart',
3 │ │   cppOptions: CppOptions(namespace: 'url_launcher_windows'),
4 │ │   cppHeaderOut: 'windows/messages.g.h',
5 │ │   cppSourceOut: 'windows/messages.g.cpp',
6 │ │   copyrightHeader: 'pigeons/copyright.txt',
7 │ └ ))
  ╵
[SEVERE] Failed after 311ms
```

### Code sample

I don't think this is related to code, I think the dependencies from the plugin are not well defined so `build_runner` is getting confused about them.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-AU)
    • Flutter version 3.19.6 on channel stable at /Users/michelfeinstein/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/michelfeinstein/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/michelfeinstein/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • E37C05EC-694C-4EDF-928A-4D162D46673E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 124.0.6367.119

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @feinstein 
I checked this on a new Flutter project with adding only two package as mentioned, but couldn't see the issue:

```console
➜  repro_147909 dart run build_runner watch -d
Building package executable... (10.6s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 435ms
[INFO] Precompiling build script... completed, took 5.4s
[INFO] Setting up file watchers completed, took 19ms
[INFO] Waiting for all file watchers to be ready completed, took 199ms
[INFO] Building new asset graph completed, took 1.5s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Generating SDK summary completed, took 6.7s
[INFO] Running build completed, took 20.2s
[INFO] Caching finalized dependency graph completed, took 110ms
[INFO] Succeeded after 20.3s with 48 outputs (100 actions)
```

Here are my dependencies:

```yaml
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
```

Looks like you are using old versions, could you try upgrading them to the latest versions and retry?
