### ISSUE TITLE
Request: Expand `flutter packages` CLI functionality

### ISSUE THREAD

**Issue by Phrohdoh** [flutter/flutter#14876]
## Feature Request

The ability to modify `*dependencies` blocks in the `pubspec.yaml` from the CLI.

## Examples

Let's assume this is the user's current `dependencies` section in their manifest.

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
```

Running this command...

```sh
$ flutter packages add url_launcher
```

Would modify said section to be the following.

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  url_launcher: 2.0.1
```

This would be done by querying `pub.dartlang.org`'s API and getting the latest version of the given package (which at the time of writing is `2.0.1`).

Perhaps a `--version x.y.z` option could be provided (which would not be validated against the registry so no network requests would be made) (bikeshed the syntax).

Bonus points: Support `flutter packages add a b c d` (which would add all packages if they all exist in the registry).

---

As the inverse of `flutter packages add` a `flutter packages remove` command could be implemented.

This would remove the node with the given name (or error if no such node exists).

---

## Question

Is this something that the flutter team is interested in?

If so, would someone be open to mentoring the implementation if necessary?

---

[`cargo-edit`](https://github.com/killercup/cargo-edit) is the inspiration for this feature request.
