### ISSUE TITLE
rejected (bundle format is ambiguous (could be app or framework))

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#148994]
### Steps to reproduce

When signing and notarizing my Flutter app using Xcode I get the following message:
```
spctl --assess --type execute --verbose MySingnedAndNotizedApp.app
MySingnedAndNotizedApp.app/: accepted
source=Notarized Developer ID
```
but if zip then unzip my app the message changes:
```
spctl --assess --type execute --verbose MySingnedAndNotizedApp.app
rejected (bundle format is ambiguous (could be app or framework))
```
I have signed and notarized applications in the past on the same machine without any issues.
I'm not sure if the first one is a false-positive or if zipping the file changes something in the .app bundle.
Do you have any idea what would cause this issue?

here is the list of packages I use:
```
  flutter:
    sdk: flutter
  path: ^1.8.0
  file_picker: ^8.0.0+1
  dynamic_height_grid_view: ^0.0.3
  path_provider: ^2.0.5
  provider: ^6.0.5
  flutter_fancy_tree_view: ^1.3.0
  multi_split_view: ^2.4.0
  desktop_drop: ^0.4.4
  random_string: ^2.3.1
  async: ^2.11.0
```

### Expected results

up

### Actual results

up

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
