### ISSUE TITLE
FocusManager related leak.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#148985]
PR https://github.com/flutter/flutter/pull/148612 introduced a leak to existing test "Material3 - Barriers show when using PageRouteBuilder".

To repro run:
```
flutter test test/widgets/page_route_builder_test.dart --dart-define LEAK_TRACKING=true
```

**Comment by polina-c** [comment]
```
Expected: leak free
    Actual: <Instance of 'Leaks'>
     Which: contains leaks:
            # The text is generated by leak_tracker.
            # For leak troubleshooting tips open:
            # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
            notDisposed:
              total: 541
              objects:
                StatelessElement:
                  test: Material3 - Barriers show when using PageRouteBuilder
                  identityHashCode: 380143882
                StatefulElement:
                  test: Material3 - Barriers show when using PageRouteBuilder
                  identityHashCode: 505076395
                _MaterialAppState:
                  test: Material3 - Barriers show when using PageRouteBuilder
                  identityHashCode: 359752437
                HeroController:
                  test: Material3 - Barriers show when using PageRouteBuilder
                  identityHashCode: 145017926
...
```
