### ISSUE TITLE
conditionnal platform assets

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#149272]
### Use case

in `pubspec.yaml` I have the following assets:
```
  assets:
    - assets/other/foo.txt
    - assets/other/bar.jpg
    - assets/bin/mac/my_bin
    - assets/bin/windows/my_bin.exe
```
So on Windows, my app contains a useless MacOS binary and on MacOS my  app contains a useless Windows binary

Can we add a way to declare assets for specific platforms?

### Proposal

```
  assets:
    - assets/other/foo.txt
    - assets/other/bar.jpg
    mac:
         - assets/bin/mac/my_bin
    windows:
         - assets/bin/windows/my_bin.exe
```
