### ISSUE TITLE
Build ios simulator error: Invalid Podfile file: File exists

### ISSUE THREAD

**Issue by borithnget** [flutter/flutter#149650]
I'm trying build app for ios simulator. Im getting below error, any idea what i'm missing here ?

```
[!] Invalid `Podfile` file: File exists @ syserr_fail2_in -
    /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/connectivity_plus.

     #  from /Users/macbookpro/Documents/SourceCode/xschool/ios/Podfile:34
     #  -------------------------------------------
     #  
     >    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
     #  end
     #  -------------------------------------------

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:335:in `rescue in block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:329:in `block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in `from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:293:in `from_file'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/share_plus: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/google_sign_in_ios: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/firebase_crashlytics: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/firebase_auth: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/wakelock: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/package_info_plus: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/url_launcher_ios: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/flutter_secure_storage: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/firebase_messaging: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/connectivity_plus: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/firebase_core: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/sqflite: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/fluttertoast: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/webview_flutter_wkwebview: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/shared_preferences_foundation: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/firebase_app_check: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/flutter_inappwebview: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/flutter_facebook_auth: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/video_player_avfoundation: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/device_info_plus: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/file_picker: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/smart_auth: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/image_picker_ios: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/in_app_purchase_storekit: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/webview_cookie_manager: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins/path_provider_foundation: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks/plugins: Permission denied
    rm: /Users/macbookpro/Documents/SourceCode/xschool/ios/.symlinks: Permission denied
```

- flutter doctor -v

```
[✓] Flutter (Channel stable, 3.22.1, on macOS 13.6.7 22G720 darwin-x64, locale en-KH)
    • Flutter version 3.22.1 on channel stable at /Users/macbookpro/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (13 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode copy.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • Irith  (mobile) • 00008030-000849322638802E • ios            • iOS 16.1.1 20B101
    • macOS (desktop) • macos                     • darwin-x64     • macOS 13.6.7 22G720 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 84.0.4147.105

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

- flutter build ios --verbose
```
           Build version 15F31d
[ +116 ms] executing: [/Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/] xcrun xcodebuild -list
[+2584 ms] Command line invocation:
                        "/Applications/Xcode copy.app/Contents/Developer/usr/bin/xcodebuild" -list

                    User defaults from command line:
                        IDEPackageSupportUseBuiltinSCM = YES

                    Information about project "Runner":
                        Targets:
                            Runner

                        Build Configurations:
                            Debug
                            Release
                            Profile

                        If no build configuration is specified and -scheme is not passed then "Debug" is used.

                        Schemes:
                            Runner
           
[   +6 ms] Error output from CocoaPods:
           ↳
[        ]     rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/share_plus: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/google_sign_in_ios: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/firebase_crashlytics: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/firebase_auth: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/wakelock: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/package_info_plus: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/url_launcher_ios: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/flutter_secure_storage: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/firebase_messaging: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/connectivity_plus: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/firebase_core: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/sqflite: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/fluttertoast: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/webview_flutter_wkwebview: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/shared_preferences_foundation: Permission
denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/firebase_app_check: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/flutter_inappwebview: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/flutter_facebook_auth: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/video_player_avfoundation: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/device_info_plus: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/file_picker: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/smart_auth: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/image_picker_ios: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/in_app_purchase_storekit: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/webview_cookie_manager: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins/path_provider_foundation: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks/plugins: Permission denied
               rm: /Users/macbookpro/Documents/SourceCode/masterstudyapplication_release/ios/.symlinks: Permission denied
           
[  +54 ms] "flutter ios" took 11,549ms.
[  +47 ms] Error running pod install
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      CocoaPods._runPodInstall (package:flutter_tools/src/macos/cocoapods.dart:359:7)
           <asynchronous suspension>
           #2      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:177:7)
           <asynchronous suspension>
           #3      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:43:30)
           <asynchronous suspension>
           #4      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:252:3)
           <asynchronous suspension>
           #5      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:673:37)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[  +60 ms] ensureAnalyticsSent: 56ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[ +129 ms] exiting with code 1
```

-pubspec.yaml

```
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.5+67

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #networking
  http: ^0.13.4
  dio: ^5.2.1+1

  #stateManagement
  flutter_bloc: ^8.1.3

  #utils
  meta: ^1.1.6
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  share_plus: ^6.3.1
  package_info_plus: ^3.1.2
  device_info_plus: ^8.1.0
  overlay_support: ^2.1.0
  intl: ^0.17.0


  #googleSignIn
  google_sign_in: ^6.0.2

  #facebookSignIn
  flutter_facebook_auth: ^5.0.7

  #utils
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  #webview_flutter: ^4.2.1
  webview_flutter: ^4.7.0
  webview_cookie_manager: ^2.0.6
  webview_flutter_wkwebview: ^3.0.4
  webview_flutter_android: ^3.9.3
  flutter_inappwebview: ^5.7.2+3
  connectivity_plus: ^3.0.3
  external_path: ^1.0.1
  logger: ^1.3.0

  #video_players
  vimeo_video_player: ^0.0.10
  youtube_player_flutter: ^8.1.2
  video_player: ^2.6.1
  chewie: ^1.5.0

  #firebase
  firebase_crashlytics: ^3.3.3
  firebase_core: ^2.14.0
  #firebase_messaging: ^10.25.0
  firebase_messaging: ^14.6.4

  #ui
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.5
  shimmer: 2.0.0
  image_picker: ^0.8.4+11
  transparent_image: ^2.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_html: 3.0.0-alpha.6
  #flutter_html: ^2.2.1
  file_picker: ^5.2.5
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.0.20
  #cached_network_image: ^3.2.0
  #cached_network_image: ^3.2.0
  cached_network_image: ^3.3.1
  html_unescape: ^2.0.0
  page_transition: ^2.0.9
  in_app_purchase: ^3.0.8
  image: ^3.1.3
  fluttertoast: ^8.2.1
  email_validator: ^2.1.17
  firebase_auth: ^4.19.4
  pinput: ^4.0.0
  firebase_app_check: ^0.2.2+4
  country_picker: ^2.0.25


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  json_serializable: ^6.6.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/Logo_White.png
    - assets/images/
    - assets/icons/
    - assets/localization/default_locale.json
    - assets/localization/km_locale.json
```

- Podfile
```
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
       end
  end
end
```
