### ISSUE TITLE
_TreeSliverState is leaking CurvedAnimation.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#149711]
Introduced by https://github.com/flutter/flutter/pull/147171

To repro run `flutter test test/widgets/sliver_tree_test.dart --dart-define LEAK_TRACKING=true`

To see creation call stack add to the failing test: `experimentalLeakTesting: LeakTesting.settings.withCreationStackTrace(),`

<img width="206" alt="Screenshot 2024-06-04 at 8 13 11 PM" src="https://github.com/flutter/flutter/assets/12115586/0d11680a-02e3-4164-8fd6-93887e89f6e7">

**Comment by polina-c** [comment]
@Piinks

**Comment by polina-c** [comment]
```
            notDisposed:
              total: 6
              objects:
                CurvedAnimation:
                  test: Can toggleNode, to collapse or expand
                  identityHashCode: 3085566
                  context:
                    start: >
                      #6_______dispatchFlutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/testing.dart:74:23)
                      #7______FlutterMemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:249:23)
                      #8______FlutterMemoryAllocations.dispatchObjectCreated_(package:flutter/src/foundation/memory_allocations.dart:283:5)
                      #9______new_CurvedAnimation_(package:flutter/src/animation/animations.dart:385:41)
                      #10______TreeSliverState.toggleNode.<anonymous_closure>_(package:flutter/src/widgets/sliver_tree.dart:898:44)
                      #11_____State.setState_(package:flutter/src/widgets/framework.dart:1203:30)
                      #12______TreeSliverState.toggleNode_(package:flutter/src/widgets/sliver_tree.dart:862:5)
                      #13_____TreeSliverController.toggleNode_(package:flutter/src/widgets/sliver_tree.dart:220:20)
                      #14_____main.<anonymous_closure>.<anonymous_closure>_(file:///Users/polinach/_/flutter_dev/packages/flutter/test/widgets/sliver_tree_test.dart:275:18)
                      <asynchronous_suspension>
                      #15_____testWidgets.<anonymous_closure>.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:183:15)
                      <asynchronous_suspension>
                      #16_____TestWidgetsFlutterBinding._runTestBody_(package:flutter_test/src/binding.dart:1025:5)
                      <asynchronous_suspension>
                      #17_____StackZoneSpecification._registerCallback.<anonymous_closure>_(package:stack_trace/src/stack_zone_specification.dart:114:42)
                      <asynchronous_suspension>
                CurvedAnimation:
                  test: Can toggleNode, to collapse or expand
                  identityHashCode: 271398839
                  context:
                    start: >
                      #6_______dispatchFlutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/testing.dart:74:23)
                      #7______FlutterMemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:249:23)
                      #8______FlutterMemoryAllocations.dispatchObjectCreated_(package:flutter/src/foundation/memory_allocations.dart:283:5)
                      #9______new_CurvedAnimation_(package:flutter/src/animation/animations.dart:385:41)
                      #10______TreeSliverState.toggleNode.<anonymous_closure>_(package:flutter/src/widgets/sliver_tree.dart:898:44)
                      #11_____State.setState_(package:flutter/src/widgets/framework.dart:1203:30)
                      #12______TreeSliverState.toggleNode_(package:flutter/src/widgets/sliver_tree.dart:862:5)
                      #13_____TreeSliverController.toggleNode_(package:flutter/src/widgets/sliver_tree.dart:220:20)
                      #14_____main.<anonymous_closure>.<anonymous_closure>_(file:///Users/polinach/_/flutter_dev/packages/flutter/test/widgets/sliver_tree_test.dart:295:18)
                      <asynchronous_suspension>
                      #15_____testWidgets.<anonymous_closure>.<anonymous_closure>_(package:flutter_test/src/widget_tester.dart:183:15)
                      <asynchronous_suspension>
                      #16_____TestWidgetsFlutterBinding._runTestBody_(package:flutter_test/src/binding.dart:1025:5)
                      <asynchronous_suspension>
                      #17_____StackZoneSpecification._registerCallback.<anonymous_closure>_(package:stack_trace/src/stack_zone_specification.dart:114:42)
                      <asynchronous_suspension>
                CurvedAnimation:
                  test: Can collapseNode, then expandAll
                  identityHashCode: 16633433
                CurvedAnimation:
                  test: Can expandNode, then collapseAll
                  identityHashCode: 1029452442
                CurvedAnimation:
                  test: Can expandNode, then collapseAll
                  identityHashCode: 943478248
                CurvedAnimation:
                  test: Can expandNode, then collapseAll
                  identityHashCode: 744261437
```
