### ISSUE TITLE
Dependency on flutter sdk doesn't pin dependency versions to match Flutter's deps

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14992]
## Steps to Reproduce

1. Sync flutter to 9a9aed191d (just so the versions I report here will match)
1. Run `flutter create foo & cd foo`
2. Edit the `dependencies` and `dev_dependencies` sections of `pubspec.yaml` file to look like the following by adding a dependency on `args: 1.4.1` and replacing the `flutter_test` dependency with `test: ^0.12.0`:

    ```
      flutter:
        sdk: flutter
      args: 1.4.1

      # The following adds the Cupertino Icons font to your application.
      # Use with the CupertinoIcons class for iOS style icons.
      cupertino_icons: ^0.1.0

    dev_dependencies:
      test: ^0.12.0
    ```
3. Run `flutter packages upgrade`
4. Inspect the `.packages` file

## Expected behavior

The flutter sdk at our revision [pins args to 1.3.0](https://github.com/flutter/flutter/blob/9a9aed191df3163ed1cbe891fa94df201a243f4d/packages/flutter/pubspec.yaml#L22) and [pins test to 0.12.30+4](https://github.com/flutter/flutter/blob/9a9aed191df3163ed1cbe891fa94df201a243f4d/packages/flutter/pubspec.yaml#L61), so you expect pub to present an error in step 3, saying that the version constraints are incompatible.

## Actual behavior

* Step 3 completes successfully
* Step 4 shows that pub has resolved `args` to `1.4.1` and `test` to `0.12.31`
