### ISSUE TITLE
Flutter Native Splash, not showing logo.

### ISSUE THREAD

**Issue by Bakir-Alkaraki** [flutter/flutter#150059]
### Steps to reproduce

Hello there, i have notice a wired problem/bug,

i'm using flutter native spalsh screen, and when i put my app in secure Folder, i can't see splash logo, only background color, otherwise working fine.

### Expected results

```
`flutter_native_splash:
  color: "#ffffff"
  image: assets/images/last.png

  android_12:
    color: "#ffffff"
    image: assets/images/last.png
    
```
    this splash yaml, should be fine!`

### Actual results

.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
