### ISSUE TITLE
 flutter_gallery打不开

### ISSUE THREAD

**Issue by dingjiansheji** [flutter/flutter#15010]
用android studio3.0打不开 flutter_gallery这个例子
提示如下：
![tim 20180301130609](https://user-images.githubusercontent.com/35317999/36827897-599814b0-1d51-11e8-87a4-1770fb6e0849.png)

**Comment by zlab** [comment]
## pubspec.yaml
```
  flutter_gallery_assets:
    git:
   #   url: https://flutter.googlesource.com/gallery-assets
      url: https://github.com/zlab/gallery-assets
```
