### ISSUE TITLE
RangeError: RangeError: Value not in range: 226

### ISSUE THREAD

**Issue by junhyunpark0716** [flutter/flutter#150201]
### Steps to reproduce

1, App crashes only on real device.
2. After few minutes
3. Console shows `RangeError: RangeError: Value not in range: 226`

I have never seen this kind of error

This is my try
1. Delete`build` folder
2. `flutter clean`
3. `flutter pub get`

this only extends app live time. app crashes again.

### Expected results

Debug on real device

### Actual results

on real device, the app crashes on debug mode.
If i build app production mode `flutter run --release` app does not crash.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
#0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:5141:5)
#1      _ByteBuffer.asUint8List (dart:typed_data-patch/typed_data_patch.dart:1925:5)
#2      new Uint8List.view (dart:typed_data:891:19)
#3      decodeMDnsResponse.readResourceRecord (package:multicast_dns/src/packet.dart:343:23)
#4      decodeMDnsResponse (package:multicast_dns/src/packet.dart:372:38)
#5      MDnsClient._handleIncoming (package:multicast_dns/multicast_dns.dart:239:46)
#6      MDnsClient.start.<anonymous closure> (package:multicast_dns/multicast_dns.dart:160:47)
#7      _rootRunUnary (dart:async/zone.dart:1415:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#13     _StreamController._add (dart:async/stream_controller.dart:658:7)
#14     _StreamController.add (dart:async/stream_controller.dart:606:5)
#15     new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2537:33)
#16     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.22.1, on macOS 14.4 23E214 darwin-arm64, locale en-KR)
    • Flutter version 3.22.1 on channel stable at /Users/junhyunpark/Development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.3.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/junhyunpark/Development/flutter. Consider adding /Users/junhyunpark/Development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/junhyunpark/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/junhyunpark/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.3)
    • IntelliJ at /Users/junhyunpark/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (8 available)
    • SM A102N (mobile)               • RF9N20046KW                          • android-arm    • Android 11 (API 30)
    • Junhyun's iPhone (mobile)       • 00008110-001651C922C2801E            • ios            • iOS 17.5.1 21F90
    • 박준현의 iPhone (mobile)            • 00008030-0015681A1AEB802E            • ios            • iOS 17.3.1 21D61
    • iPhone 15 (mobile)              • 7984E68A-8FD4-4945-8202-72D1233852BB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • iPhone 15 Pro Max (mobile)      • 6D2AC24E-1FC8-4CE9-98EA-7BA6157D345E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@junhyunpark0716 The stacktrace looks similar to https://github.com/flutter/flutter/issues/136008 but it requires reproducible steps to make it actionable. Is there a way for you to provide reproducible code that consistently triggers this crash ? If not, I'll need to close this in favor of the linked one.

**Comment by junhyunpark0716** [comment]
[#136008](https://github.com/flutter/flutter/issues/136008) looks very similar.
I cannot identify where the problem is causing. I wish I can share the source code, but i really don't know which part of code shall be shared.


just in case below is the packages I am using.

```
name: AAAA
description: "AAAA - Mobile Application"
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rxdart: ^0.27.7
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.32.6
  shared_preferences: ^2.2.3
  device_info_plus: ^10.1.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  envied: ^0.5.4+1
  flutter_localizations:
    sdk: flutter
  intl: any
  cryptography: ^2.7.0
  msgpack_dart: ^1.0.1
  path_provider: ^2.1.3
  web_socket_channel: ^2.0.0
  unique_identifier: ^0.3.0
  go_router: ^14.1.1
  google_sign_in: ^6.2.1
  firebase_core: ^2.31.1
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.19.6
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  kakao_flutter_sdk: ^1.9.2
  kakao_flutter_sdk_user: ^1.9.2
  kakao_flutter_sdk_share: ^1.9.2
  kakao_flutter_sdk_talk: ^1.9.2
  kakao_flutter_sdk_friend: ^1.9.2
  kakao_flutter_sdk_navi: ^1.9.2
  kakao_flutter_sdk_common: ^1.9.2
  url_strategy: ^0.2.0
  wrapped_korean_text: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/apple/
    - assets/logos/
    - assets/src/
    - assets/hicardi_core/
    - assets/tutorials/
  fonts:
    - family: AAAA
      fonts:
        - asset: lib/AAAA/fonts/AAAA.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900

flutter_intl:
  enabled: true

```
