### ISSUE TITLE
Rewrite paths for conditionally included assets

### ISSUE THREAD

**Issue by RepliedSage11** [flutter/flutter#151342]
### Use case

There is a [feature](https://docs.flutter.dev/deployment/flavors#conditionally-bundling-assets-based-on-flavor) in Flutter that allows you to conditionally define assets on a per-flavor basis. 

We are developing an application that needs to include different assets per flavor, but have them in the same folder structure for each flavor. 

The simplest example would be localization files (we are using easy_localization).
Our current structure is assets/translations/{flavor}/*.json. We then conditionally include these localization files like so:

```yaml
flutter:

  assets:
    - assets/common/
    - path: assets/translations/banana/
      flavors:
        - banana
    - path: assets/translations/apple/
      flavors:
        - apple
```

Then we change the asset path depending on the current flavor:

```dart
EasyLocalization(
      path: 'assets/translations/$appFlavor',
      ...
    ),
```

What we would like is for the assets to be available under assets/translations/*.json when the app is built, so that we can specify it like this, no matter which flavor is selected.

```dart
EasyLocalization(
      path: 'assets/translations/',
      ...
    ),
```

### Proposal

Add an ability to specify a rewrite for the path when bundling the assets. This can be an option only for the conditionally included assets or for all assets.

Example of the new syntax:

```yaml
flutter:

  assets:
    - assets/common/
    - path: assets/translations/banana/
      bundle_path: assets/translations/
      flavors:
        - banana
      
    - path: assets/translations/apple/
      bundle_path: assets/translations/
      flavors:
        - apple
```
