### ISSUE TITLE
Assets Only Deferred Component not working at all 

### ISSUE THREAD

**Issue by denghejun** [flutter/flutter#151368]
### Steps to reproduce

- pubspec.yaml

```yaml
flutter:
  deferred-components:
    - name: gameAssets
      assets:
        - assets/images/animations/
        - assets/images/animations/guider/
    - name: gameAssets1
      assets:
        - assets/images/animations/magic/lw/
        - assets/images/animations/magic/lw/weapons/
    - name: gameAssets2
      assets:
        - assets/images/parallax/
        - assets/images/parallax/bg_7/
```

- main.dart
```dart
await services.DeferredComponent.installDeferredComponent(componentName: "gameAssets");
await services.DeferredComponent.installDeferredComponent(componentName: "gameAssets1");
await services.DeferredComponent.installDeferredComponent(componentName: "gameAssets2");
```
        

### Expected results

download assets success

### Actual results

not working

### Code sample

<details open><summary>Code sample</summary>

- pubspec.yaml
```yaml
flutter:
  deferred-components:
    - name: gameAssets
      assets:
        - assets/images/animations/
        - assets/images/animations/guider/
    - name: gameAssets1
      assets:
        - assets/images/animations/magic/lw/
        - assets/images/animations/magic/lw/weapons/
    - name: gameAssets2
      assets:
        - assets/images/parallax/
        - assets/images/parallax/bg_7/
```

- main.dart
```dart
await services.DeferredComponent.installDeferredComponent(componentName: "gameAssets");
await services.DeferredComponent.installDeferredComponent(componentName: "gameAssets1");
await services.DeferredComponent.installDeferredComponent(componentName: "gameAssets2");
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
