### ISSUE TITLE
The build `flutter build ipa` remains stuck.

### ISSUE THREAD

**Issue by lsaudon** [flutter/flutter#151332]
### Steps to reproduce

When I launch the build in the GitHub Action, it blocks.
My repository https://github.com/lsaudon/releascribe_cli/actions/workflows/example_cd.yaml

```bash
`[        ] executing: [/Users/runner/work/releascribe_cli/releascribe_cli/example/ios/] /usr/bin/arch -arm64e xcrun xcodebuild -configuration Release VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -destination generic/platform=iOS -resultBundlePath /var/folders/h9/l1shxhdd69nct08ylzq0n6q00000gn/T/flutter_tools.0PeSiQ/flutter_ios_build_temp_dirDOrowy/temporary_xcresult_bundle -resultBundleVersion 3 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -archivePath /Users/runner/work/releascribe_cli/releascribe_cli/example/build/ios/archive/Runner archive`
```

### Expected results

No stuck

### Actual results

https://pastebin.com/7rx751HP

### Code sample

<details open><summary>Code sample</summary>

```yaml
name: Continuous Delivery

on:
  workflow_dispatch

env:
  FLUTTER_VERSION: 3.22.2

jobs:
  continuous-delivery-ios:
    runs-on: macos-latest
    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@v4
      - name: 🗒️🔏 Ajouter le certificat de signature
        run: |
          # Créer un trousseau temporaire
          keychainPassword=$(openssl rand -base64 50)
          security create-keychain -p "$keychainPassword" temp.keychain
          security set-keychain-settings -lut 21600 temp.keychain
          security unlock-keychain -p "$keychainPassword" temp.keychain

          # Importer le certificat de signature
          echo "${{ secrets.DEV_IOS_P12_FILE }}" | base64 --decode -o certificat.p12
          security import certificat.p12 -P "${{ secrets.DEV_IOS_P12_PASSWORD }}" -A -t cert -f pkcs12 -k temp.keychain
          security list-keychain -d user -s temp.keychain
      - name: 📱🔏 Ajouter le profil de provisionnement et le fichier exportOptions
        run: |
          echo ${{ secrets.DEV_IOS_PROFILE }} | base64 --decode -o profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          uuid=`security cms -D -i profile.mobileprovision | grep -aA1 UUID | grep -o "[-a-zA-Z0-9]\{36\}"`
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$uuid.mobileprovision

          echo ${{ secrets.DEV_IOS_EXPORT_OPTIONS }} | base64 --decode -o exportOptions.plist
      - name: 🐦 Install flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: 📦 Installer les dépendances
        run: |
          cd example
          flutter pub get
      - name: 🧱 Construire l'application
        run: |
          cd example
          flutter build ipa --no-pub --release --export-options-plist ../exportOptions.plist -v
```

</details>

### Logs

<details open><summary>Logs</summary>

[flutter build ipa --no-pub --release --export-options-plist ../exportOptions.plist -v](https://pastebin.com/7rx751HP)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>
</details>
