### ISSUE TITLE
Flutter App Displays Blank White UI on iOS 14 & 15, but Works Fine on Android and Other iOS Versions

### ISSUE THREAD

**Issue by JIT-Surya** [flutter/flutter#152192]
### Steps to reproduce

I have developed a Flutter app that functions correctly on Android and other iOS versions. However, on iOS 14 and 15, the app displays a blank white screen upon launch. This issue does not occur on other iOS versions or Android devices.

I’ve tested the app on various Android devices and iOS versions, where it works as expected. The problem persists when testing on iOS 14 and 15 simulators. I anticipated that the app would display its main content and UI elements properly across all supported iOS versions.

pubspec.yaml file for plugin details:

<details>
<summary>pubspec.yaml</summary>

```yaml
name: Demo
description: ""
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.10+1
  cupertino_icons: ^1.0.2
  data_connection_checker_tv: ^0.3.5-nullsafety
  get: ^4.6.6
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  logger: ^2.1.0
  flutter_screenutil: ^5.9.0
  pin_code_text_field: ^1.8.0
  dots_indicator: ^3.0.0
  table_calendar: ^3.1.0
  carousel_slider: ^4.2.1
  image_picker: ^1.0.7
  swipe_cards: ^2.0.0+1
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  flutter_rating_bar: ^4.0.1
  permission_handler: ^11.3.1
  http: ^1.2.1
  flutter_easyloading: ^3.0.5
  share_plus: ^9.0.0
  url_launcher: ^6.2.6
  time_range_picker: any
  grouped_list: ^6.0.0
  geocoding: ^3.0.0
  emoji_picker_flutter: ^2.2.0
  file_picker: ^8.0.3
  social_media_recorder: ^1.1.13
  cached_network_image: ^3.3.1
  mapbox_search: ^4.2.2
  geolocator: ^12.0.0
  flutter_debouncer: ^2.0.0
  socket_io_client: ^3.0.0-beta.2
  web_socket_channel: ^3.0.0
  injector: ^3.0.0
  instant: ^0.5.1
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  flutter_sound: ^9.1.9
  connectivity_plus: ^6.0.3
  audio_waveforms: ^1.0.5
  shimmer: ^3.0.0
  firebase_core: ^3.2.0
  flutter_web_auth: ^0.5.0
  crypto: ^3.0.3
  path: ^1.9.0
  month_picker_dialog: ^4.0.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.1.2
  firebase_crashlytics: ^4.0.3
  loading_animation_widget: ^1.2.1
  sign_in_with_apple: ^6.1.1
  country_code_picker: ^3.0.0
  location: ^6.0.2

dev_dependencies:
  rename: ^3.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/drawer_icons/
    - assets/icons/chat_icon/
    - assets/icons/nav_icons/
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-SemiBold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
```
</details>

### Expected results

It should works fine in all os versions.

### Actual results

I have developed a Flutter app that functions correctly on Android and other iOS versions. However, on iOS 14 and 15, the app displays a blank white screen upon launch. This issue does not occur on other iOS versions or Android devices.

I’ve tested the app on various Android devices and iOS versions, where it works as expected. The problem persists when testing on iOS 14 and 15 simulators. I anticipated that the app would display its main content and UI elements properly across all supported iOS versions.

### Code sample

versions I have used

<details>
<summary>pubspec.yaml</summary>

```yaml
name: Demo
description: ""
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.10+1
  cupertino_icons: ^1.0.2
  data_connection_checker_tv: ^0.3.5-nullsafety
  get: ^4.6.6
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  logger: ^2.1.0
  flutter_screenutil: ^5.9.0
  pin_code_text_field: ^1.8.0
  dots_indicator: ^3.0.0
  table_calendar: ^3.1.0
  carousel_slider: ^4.2.1
  image_picker: ^1.0.7
  swipe_cards: ^2.0.0+1
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  flutter_rating_bar: ^4.0.1
  permission_handler: ^11.3.1
  http: ^1.2.1
  flutter_easyloading: ^3.0.5
  share_plus: ^9.0.0
  url_launcher: ^6.2.6
  time_range_picker: any
  grouped_list: ^6.0.0
  geocoding: ^3.0.0
  emoji_picker_flutter: ^2.2.0
  file_picker: ^8.0.3
  social_media_recorder: ^1.1.13
  cached_network_image: ^3.3.1
  mapbox_search: ^4.2.2
  geolocator: ^12.0.0
  flutter_debouncer: ^2.0.0
  socket_io_client: ^3.0.0-beta.2
  web_socket_channel: ^3.0.0
  injector: ^3.0.0
  instant: ^0.5.1
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  flutter_sound: ^9.1.9
  connectivity_plus: ^6.0.3
  audio_waveforms: ^1.0.5
  shimmer: ^3.0.0
  firebase_core: ^3.2.0
  flutter_web_auth: ^0.5.0
  crypto: ^3.0.3
  path: ^1.9.0
  month_picker_dialog: ^4.0.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.1.2
  firebase_crashlytics: ^4.0.3
  loading_animation_widget: ^1.2.1
  sign_in_with_apple: ^6.1.1
  country_code_picker: ^3.0.0
  location: ^6.0.2

dev_dependencies:
  rename: ^3.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/drawer_icons/
    - assets/icons/chat_icon/
    - assets/icons/nav_icons/
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-SemiBold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
```
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale
    en-IN)
    • Flutter version 3.22.3 on channel stable at
      /Users/jitpc/Devlopment/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (7 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jitpc/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.81.1)
    • VS Code at /Users/jitpc/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 126.0.6478.183

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>
