### ISSUE TITLE
Flutter web app cannot start after upgrading to flutter 3.22.3

### ISSUE THREAD

**Issue by thcbk** [flutter/flutter#152437]
### Steps to reproduce

1. Open my project folder
2. Run my project in Chrome

### Expected results

My web app should show as usual.

### Actual results

It could not ran into main() even from first line of code and it produce the following blue message in the debug console:

```
Rejecting promise with error: TypeError: Cannot set properties of undefined (setting 'nativeCommunication')

A message on the flutter/lifecycle channel was discarded before it could be handled.
This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the ChannelBuffers API documentation for details on how to configure the channel to expect more messages, or to expect messages to get discarded:
 https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html
```

This happen after I run flutter upgrade and update the html_editor_enhanced from 2.5.1 to 2.6.0. But if I keep html_editor_enhanced 2.5.1 it produces a series of error for html_editor_enhanced so I had to update it to 2.6.0.
I tried flutter clean but no help.

### Code sample

Here is my pubspec.yaml:

```
name: luyendonglaocai
description: Chi nhánh luyện đồng Lào Cai
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  scrollable_positioned_list: ^0.3.8
  smooth_page_indicator: ^1.1.0
  dotted_line: ^3.2.2
  device_info_plus: ^9.0.3
  go_router: ^10.2.0

  firebase_core: ^2.27.2

  #Online storage for files
  firebase_storage: ^11.6.6

  #Online database for data
  cloud_firestore: ^4.15.5

  #Google sign in, facebook sign in, Phone auth ...
  firebase_auth: ^4.17.5
  # flutter_widget_from_html: ^0.10.5
  flutter_widget_from_html_core: ^0.14.11
  fwfh_url_launcher: ^0.9.0+3
  
  html_editor_enhanced: ^2.6.0
  file_picker: ^8.0.3
  file_manager: ^1.0.2
  url_launcher: ^6.2.6
  pointer_interceptor: ^0.10.1+1
  tiengviet: ^0.5.0
  # flutter_html_v3: ^3.0.6
  # flutter_quill: ^7.4.9
  # google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  provider: ^6.0.5
  google_sign_in: ^6.1.5
  image_size_getter: ^2.1.2
  # image_size_getter_http_input: ^2.0.0
  # path_provider: ^2.1.1 
  # lifecycle: 0.8.0

  # window_location_href: ^1.0.1+2

  # Moi them  
  # plugin_platform_interface: ^2.0.2
  # js: ^0.6.7
  # async: ^2.11.0
  # syncfusion_flutter_pdf: ^24.1.44
  # syncfusion_flutter_pdfviewer: ^24.1.44
  # Moi them  


  # pdfx: ^2.4.0
  # internet_file: ^1.2.0
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  url_strategy: ^0.2.0
  universal_html: ^2.2.4
  html: any
  # flutter_svg: ^2.0.10+1
  # vm_service: ^14.2.1
  # web: ^0.5.1
  # js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  # flutter_lints: ^2.0.0
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # Moi them  
  # plugin:
  #   platforms:
  #     web:
  #       pluginClass: MyWebPlugin
  #       fileName: web/web_plugin.dart
  # Moi them  


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:

    - family: ArialTh
      fonts:
        - asset: fonts/ArialTh.ttf
    - family: arial
      fonts:
        - asset: fonts/arial.ttf

    - family: Times New Roman
      fonts:
        - asset: fonts/Times New Roman-Regular.ttf
        - asset: fonts/Times New Roman-Italic.ttf
          style: italic
        - asset: fonts/Times New Roman-Bold.ttf
          weight: 700

    - family: TimesNewRoman
      fonts:
        - asset: fonts/TimesNewRoman-Regular.ttf
        - asset: fonts/TimesNewRoman-Italic.ttf
          style: italic
        - asset: fonts/TimesNewRoman-Bold.ttf
          weight: 700

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700

    - family: JosefinSans
      fonts:
          - asset: fonts/JosefinSans-Regular.ttf
          - asset: fonts/JosefinSans-Italic.ttf

    - family: DancingScript
      fonts:
          - asset: fonts/DancingScript-Regular.ttf
          - asset: fonts/DancingScript-Bold.ttf

  assets:
      - images/
      # - images/anh_may_duc.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://drive.google.com/file/d/1W4X2xpULYZ1w9IFyCSck3x2EbUMLcgxR/view?usp=sharing

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4651], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (not installed)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 3 categories.
```

</details>
