### ISSUE TITLE
Using Git as Dependency fails with pubspec.yaml

### ISSUE THREAD

**Issue by Purus** [flutter/flutter#15252]
Using the below dependency in pubspec.yaml fails with the error message.

```
   cloud_firestore:
     git:
       url: https://github.com/theshiftstudio/flutter_plugins.git
       ref: 9cabcc57e63fbc9be4fafee08e6435a1a8c71d61
       path: packages/cloud_firestore
```

Error message received in VS Code.

```
Running "flutter packages get" in silkthread...
Error on line 1, column 1: Missing the required "name" field.
pub get failed (65)
exit code 65
```

**Comment by zoechi** [comment]
Do you actually have a `name: foo` in your `pubspec.yaml` like the error message demands?

I use Git dependencies quite frequently without issues, but I haven't used `path` **and** `ref` together yet.

**Comment by JohnDoneth** [comment]
@zoechi The problem only arose when I was using path and ref together. I solved this problem personally by using a newer version of flutter and skipping the git repository link altogether but the problem may still persist.

**Comment by zoechi** [comment]
This should be reported in dart-lang/pub instead then

**Comment by tamcy** [comment]
This also happens to me, but I'm not using `ref` at all. I didn't use git repo but a recent update of Flutter beta forced me to try with an unpublished version of `jaguar_serializer_cli` to see if a problem has been fixed. Then I encountered the `Missing the required "name" field.` error. 

Here's an excerpt of my `pubspec.yaml`:
```yaml
name: flutterapp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.15.6
  intl_translation: 0.16.6
  # ....
  jaguar_serializer: ^1.0.0-dev6
  jaguar_serializer_cli:
      git:
        url: git://github.com/Jaguar-dart/jaguar_serializer.git
        path: jaguar_serializer_cli
```

This is what is said on the [using packages](https://flutter.io/using-packages/#dependencies-on-unpublished-packages) page. And here's the output of `flutter packages upgrade`:
```
Running "flutter packages upgrade" in mobile...
Error on line 1, column 1: Missing the required "name" field.
pub upgrade failed (65)
```

I also tried changing `git://github.com/Jaguar-dart/jaguar_serializer.git` to `https://github.com/Jaguar-dart/jaguar_serializer.git` but no difference.
