### ISSUE TITLE
The generated aar for native plugin in build/host/outputs/repo should have a correct version number.

### ISSUE THREAD

**Issue by chunfengyao** [flutter/flutter#152538]
### Steps to reproduce

1. create a flutter project
2. add a plugin with native code, such as image_picker(It depens on image_picker_android)
3. build AAR for android with `flutter  build aar --build-number 2.0`

### Expected results

The generated aar for image_picker_android in build/host/outputs/repo should have the correct version number.

### Actual results

It always has the same version of `--build-number`, even though I didn't change the version number of image_picker in pubspec.yaml.

### Code sample

<details open><summary>Code sample for pubspec.yaml</summary>

```yaml
version: 1.0.0+1

environment:
  sdk: ^3.6.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter
  image_picker: 1.0.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  module:
    androidX: true
    androidPackage: com.example.flutter_project
    iosBundleIdentifier: com.example.flutterProject
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.24.0-1.0.pre.349, on macOS 14.5 23F79 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>
