### ISSUE TITLE
[shared_preferences] cast exception with get/setStringList: `type 'List<Object?>' is not a subtype of type 'List?'`

### ISSUE THREAD

**Issue by itismejy** [flutter/flutter#152607]
### Steps to reproduce

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'List<Object?>' is not a subtype of type 'List<String>?' in type cast

### Expected results

setStringList is not working properly

### Actual results

Should be a `List<String>`, not `List<Object>`

### Code sample

<details open><summary>Code sample</summary>

```dart
final SharedPreferencesWithCache prefsWithCache =
    await SharedPreferencesWithCache.create(
  cacheOptions: const SharedPreferencesWithCacheOptions(
    // When an allowlist is included, any keys that aren't included cannot be used.
    allowList: <String>{'action'},
  ),
);

await prefsWithCache!.setStringList('action', <String>['Earth', 'Moon', 'Sun']);
                            
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by iapicca** [comment]
works for me

```dart
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

final class SharedPreferencesKeys {
  static const action = 'action';
}

void main() async {
  final prefsWithCache = await SharedPreferencesWithCache.create(
    cacheOptions: const SharedPreferencesWithCacheOptions(
      allowList: {SharedPreferencesKeys.action},
    ),
  );

  await prefsWithCache.setStringList(
    SharedPreferencesKeys.action,
    const ['Earth', 'Moon', 'Sun'],
  );

  final actions =
      prefsWithCache.getStringList(SharedPreferencesKeys.action) ?? [];

  runApp(
    MaterialApp(
      home: Material(
        child: Column(
          children: [
            for (final action in actions) Text(action),
          ],
        ),
      ),
    ),
  );
}
```
```console
[!] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.4.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/francesco/fvm/versions/stable. Consider adding /Users/francesco/fvm/versions/stable/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources
```
```yaml
name: issue_152607
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
```
