### ISSUE TITLE
[gen_l10n] Why doesn't `isCustomDateFormat` accept an actual boolean?

### ISSUE THREAD

**Issue by kzrnm** [flutter/flutter#153420]
### Steps to reproduce
1. Create a project as follows
2. `flutter gen-l10n`

```
<root>
├── pubspec.yaml
└── lib
    └── l10n
        └── app_en.arb
```

**pubspec.yaml**

```yaml
name: gen_l10n
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  generate: true
```

**app_en.arb**

```json
{
  "@@locale": "en",
  "springBegins": "Spring begins on {springStartDate}",
  "@springBegins": {
    "description": "The first day of spring",
    "placeholders": {
      "springStartDate": {
        "type": "DateTime",
        "format": "asdf",
        "isCustomDateFormat": true
      }
    }
  }
}
```

Or running the following shell script.

```sh

# Set up
# In empty directory

# Init
flutter create . --platforms=web
mkdir -p lib/l10n

# Setup Localization
echo 'name: gen_l10n
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  generate: true
' >  pubspec.yaml

echo '{
  "@@locale": "en",
  "springBegins": "Spring begins on {springStartDate}",
  "@springBegins": {
    "description": "The first day of spring",
    "placeholders": {
      "springStartDate": {
        "type": "DateTime",
        "format": "asdf",
        "isCustomDateFormat": true
      }
    }
  }
}' > lib/l10n/app_en.arb

flutter pub get

# gen-l10n
flutter gen-l10n
```

### Expected results

AppLocalizations is generated.

### Actual results

> The "isCustomDateFormat" value of the "springStartDate" placeholder in message springBegins must be a boolean value.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
