### ISSUE TITLE
launchUrlString crash on windows

### ISSUE THREAD

**Issue by dailei2018** [flutter/flutter#153542]
### Steps to reproduce

1. win11
2. call await launchUrlString('file:\\\\C:\\Users\\dl\\Downloads'); more than 5 times,random crash

### Expected results

no crash

### Actual results

random crash when call launchUrlString more than 5 times。before crash,all going well.

### Code sample

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher_string.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Simple Animated Tree Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: IconButton(
        onPressed: () async {
          var res = await launchUrlString('file:\\\\C:\\Users\\dl\\Downloads');
          print(res);
        },

        icon: Icon(Icons.computer),
      )
    );
  }
}
```

### part of pubspec.yaml
```
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sidebarx: ^0.17.1
  animated_tree_view: ^2.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

### Screenshots or Video
#
_No response_

### Flutter Doctor output

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [版本 10.0.22000.2538], locale zh-CN)
    • Flutter version 3.22.2 on channel stable at D:\root\usr\local\msys2\usr\local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (2 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at D:\root\usr\local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: D:\root\usr\local\androidStudio2024\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.9.7)
    • Visual Studio at D:\root\usr\local\msys2\usr\local\vs\2022\Professional
    • Visual Studio Professional 2022 version 17.9.34902.65
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at D:\root\usr\local\androidStudio2024
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.74

[√] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>
