### ISSUE TITLE
[Impeller][Android] Font is bolder/thicker after upgrading to stable 3.24.0

### ISSUE THREAD

**Issue by liuzehnhang** [flutter/flutter#153677]
### Steps to reproduce

After upgrading Flutter 3.24.0, the font size of FontWeighta.w400 on Android has become thicker

### Expected results

After upgrading Flutter 3.24.0, the font size of FontWeighta.w400 on Android has become thicker

### Actual results

After upgrading Flutter 3.24.0, the font size of FontWeighta.w400 on Android has become thicker

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @liuzehnhang, please provide a complete minimal reproducible code sample so that we can properly investigate this. 

Are you using impeller on android?

What version of flutter were you using prior to 3.24.0? 

Please also include some screenshots and the output of `flutter doctor -v`

In the future, please do not file an issue without the information requested in the template. 

Thank you

**Comment by liuzehnhang** [comment]
My previous version was 3.22.3
![WeChat1ddd7f71ef87d31d6600b02f7722300b](https://github.com/user-attachments/assets/455f8131-08bc-439e-9aeb-e6a6f6432d4b)

![WechatIMG304](https://github.com/user-attachments/assets/d272e551-da59-4c0a-b69f-ed2b7e40af04)
![WechatIMG305](https://github.com/user-attachments/assets/372a402b-bc24-4a1e-91b8-16b06eec03d7)

**Comment by liuzehnhang** [comment]
@danagbemava-nc

**Comment by tihimsm** [comment]
same issue on Japanese Hiragana ,Katakana and Kanji.

**Comment by danagbemava-nc** [comment]
Hi @liuzehnhang, @tihimsm, are you seeing this with specific fonts or are all fonts affected? Can either of you provide a complete minimal reproducible code sample so that we can properly investigate this? 

Thank you

**Comment by liuzehnhang** [comment]
The issue has been temporarily resolved，MaterialApp   add " textTheme:  GoogleFonts.poppinsTextTheme() " , change font

**Comment by danagbemava-nc** [comment]
Hi @liuzehnhang, what font were you using initially?

**Comment by liuzehnhang** [comment]
@danagbemava-nc    Initially not set, it should be the default font

**Comment by liuzehnhang** [comment]
My phone is Xiaomi 13

**Comment by naivetoby** [comment]
### Bug Report: Flutter Default Font (Roboto) Not Applied on Xiaomi Hyper OS and Color OS after Upgrading to Flutter 3.24.0

#### Issue Description:
After upgrading to Flutter 3.24.0, the default font (Roboto) is not applied correctly on certain Android systems, specifically:

- **Xiaomi Hyper OS**: The font weight is incorrectly displayed as bold.
- **Color OS**: The font weight appears lighter than expected.

When the Roboto font is not applied, the system default font is used instead.

#### Steps to Fix:
1. In your `MaterialApp`, specify the following `fontFamilyFallback`:

   ```dart
   fontFamilyFallback: Platform.isIOS
       ? ['.AppleSystemUIFont', 'PingFang SC']
       : ['Roboto'],
   ```

2. Add the Roboto font in `pubspec.yaml`:

   ```yaml
   flutter:
     uses-material-design: true
     fonts:
       - family: Roboto
         fonts:
           - asset: fonts/Roboto-Black.ttf
           - asset: fonts/Roboto-BlackItalic.ttf
           - asset: fonts/Roboto-Bold.ttf
           - asset: fonts/Roboto-BoldItalic.ttf
           - asset: fonts/Roboto-Italic.ttf
           - asset: fonts/Roboto-Light.ttf
           - asset: fonts/Roboto-LightItalic.ttf
           - asset: fonts/Roboto-Medium.ttf
           - asset: fonts/Roboto-MediumItalic.ttf
           - asset: fonts/Roboto-Regular.ttf
           - asset: fonts/Roboto-Thin.ttf
           - asset: fonts/Roboto-ThinItalic.ttf
   ```

3. Run the app on devices with Xiaomi Hyper OS or Color OS.

#### Observed Behavior:
- **Xiaomi Hyper OS**: The issue is resolved by manually importing the Roboto font.
- **Color OS**: The app still uses the system default font, and the issue persists despite the manual font import.

Additionally, if the system default font is changed in the device settings, the app's font also changes accordingly on these systems.

#### Expected Behavior:
- The default Roboto font should be applied consistently across all Android systems.
- Changes to the system default font in the device settings should not affect the app's font when the Roboto font is specified.

#### Flutter Version:
- Flutter 3.24.0
