### ISSUE TITLE
Flutter Web blank/white screen after hot reload or hot restart

### ISSUE THREAD

**Issue by ldsouza93** [flutter/flutter#153927]
### Steps to reproduce

When I first run the project the page loads correctly, but after the first hot reload or hot restart I get blank/white page and a console log loop.

### Expected results

The page should load on hotreload or hot restart.

### Actual results

Blank page with a console output loop

### Code sample

<details open><summary>pubspec.yaml</summary>

```yaml
name: wms_main
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  xml: ^6.5.0
  excel: ^4.0.6
  file_picker: ^8.0.3
  ota_update: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  printing: ^5.11.0
  pdf: ^3.10.8
  http: ^1.2.2
  pluto_grid_plus: ^8.3.0
  universal_html: ^2.2.2
  mask_text_input_formatter: ^2.3.0
  dio: ^5.1.0
  open_file: ^3.3.2
  csv: ^6.0.0
  shared_preferences: ^2.0.11
  intl: ^0.19.0
  responsive_sizer: 3.3.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
      - images/
      - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

</details>

### Logs

<details open><summary>debug console</summary>

```console
[  +10 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:56515/main_module.bootstrap.js
[+5762 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +55 ms] ChromeProxyService: Caching package:flutter/src/widgets/widget_inspector.dart in expression compiler worker
[  +34 ms] DevHandler: Debug service listening on ws://127.0.0.1:56622/AeNXKVvW5pI=/ws

[  +21 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 10, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 10, params: {streamId: Stdout, includePrivateMembers: false}}}}
[   +3 ms] This app is linked to the debug service: ws://127.0.0.1:56622/AeNXKVvW5pI=/ws
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 11, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 11, params: {streamId: Stderr, includePrivateMembers: false}}}}
[   +9 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 13, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 13, params: {streamId: Isolate, includePrivateMembers: false}}}}
[   +4 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 14, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 14, params: {streamId: Extension, includePrivateMembers: false}}}}
[   +2 ms] Debug service listening on ws://127.0.0.1:56622/AeNXKVvW5pI=/ws
Connecting to VM Service at ws://127.0.0.1:56622/AeNXKVvW5pI=/ws
Connected to the VM Service.
[  +57 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 18, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 18, params: {streamId: Isolate, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 19, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 19, params: {streamId: Debug, includePrivateMembers: false}}}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 20, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 20, params: {streamId: Logging, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 21, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 21, params: {streamId: Extension, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 22, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 22, params: {streamId: Service, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 23, error: {code: -32602, message: The stream `ToolEvent` is not supported on web devices}}
[  +77 ms] ExpressionEvaluator: Evaluating "() { return true; }" at packages/flutter/src/widgets/unique_widget.dart
[   +5 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 28, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 29, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 30, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 31, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 32, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 33, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 34, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 35, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +7 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 36, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 37, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 38, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 39, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 40, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 41, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 42, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 43, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 44, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 45, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 46, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 47, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 48, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 49, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 50, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 51, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 52, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 53, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 54, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 55, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 56, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +6 ms] ExpressionEvaluator: Evaluating JS: "function () {
             try {
               return   (function() {
                   const dart_sdk = require('dart_sdk');
                   const dart_rti = dart_sdk.dart_rti;
                   const dart = dart_sdk.dart;
                   var T = {
                     VoidTobool: () => (T.VoidTobool = dart.constFn(dart_rti.findType("core|bool()")))()
                   };
                   return dart.fn(() => true, T.VoidTobool());
                 }(

                 ))();
             } catch (error) {
               return error.name + ": " + error.message;
             }
           }" with scope: {}
[   +7 ms] ExpressionEvaluator: Evaluated "() { return true; }" to "{type: boolean, value: true}"
[ +775 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 66, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 66, params: {streamId: Debug, includePrivateMembers: false}}}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 67, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 67, params: {streamId: Extension, includePrivateMembers: false}}}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 69, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 69, params: {streamId: Isolate, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 70, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 70, params: {streamId: Logging, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 71, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 71, params: {streamId: Stderr, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 72, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 72, params: {streamId: Stdout, includePrivateMembers: false}}}}
[   +4 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 75, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 75, params: {streamId: Service, includePrivateMembers: false}}}}
[ +177 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 94, error: {code: 106, message: Can only perform operation while paused.}}
[ +520 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 112, error: {code: -32602, message: Source report kind Coverage not supported}}
[+24636 ms] DevHandler: VmService proxy responded with an error:
            {jsonrpc: 2.0, id: 113, error: {code: -32601, message: streamCpuSamplesWithUserTag: Not supported on web devices}}
[+3548 ms] Skipping target: gen_localizations
[        ] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[        ] complete
[  +78 ms] Scanned through 838 files in 76ms
[   +2 ms] <- recompile org-dartlang-app:/web_entrypoint.dart 0e2fda63-00f4-4f08-af15-a455daa94747
[        ] package:wms_main/pages/loginPage/login_page.dart
[        ] <- 0e2fda63-00f4-4f08-af15-a455daa94747
[ +224 ms] Synced 0.7MB.
[        ] <- accept
[   +2 ms] DwdsVmClient: Attempting a hot restart
[        ] DwdsVmClient: Attempting to disable breakpoints and resume the isolate
[   +2 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[        ] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestartDwds request
[   +2 ms] ChromeProxyService: Destroying isolate
[        ] BatchedExpressionEvaluator: Closed
[  +62 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +14 ms] DwdsVmClient: $dartHotRestartDwds request complete.
[        ] DwdsVmClient: Waiting for Isolate Start event.
[  +17 ms] DwdsVmClient: Successful hot restart
[        ] ChromeProxyService: Caching package:flutter/src/widgets/widget_inspector.dart in expression compiler worker
[   +8 ms] Restarted application in 411ms.
[  +28 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 120, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 120, params: {streamId: Isolate, includePrivateMembers: false}}}}
[  +28 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 123, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 124, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 125, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 126, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +5 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 127, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 128, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 129, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 130, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 131, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 132, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 133, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 134, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 135, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 136, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 137, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 138, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 139, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 140, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 141, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 142, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 143, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 144, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 145, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 146, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 147, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 148, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 149, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 150, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 151, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}
[ +122 ms] ExpressionEvaluator: Evaluating "() { return true; }" at packages/flutter/src/widgets/unique_widget.dart
[  +17 ms] ExpressionEvaluator: Evaluating JS: "function () {
             try {
               return   (function() {
                   const dart_sdk = require('dart_sdk');
                   const dart_rti = dart_sdk.dart_rti;
                   const dart = dart_sdk.dart;
                   var T = {
                     VoidTobool: () => (T.VoidTobool = dart.constFn(dart_rti.findType("core|bool()")))()
                   };
                   return dart.fn(() => true, T.VoidTobool());
                 }(

                 ))();
             } catch (error) {
               return error.name + ": " + error.message;
             }
           }" with scope: {}
[   +1 ms] ExpressionEvaluator: Evaluated "() { return true; }" to "{type: boolean, value: true}"
[+4225 ms] A message on the flutter/lifecycle channel was discarded before it could be handled.
           This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the ChannelBuffers API documentation for details on how to configure the channel to expect more messages, or to expect messages to get discarded:
             https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html
[+1095 ms] A message on the flutter/lifecycle channel was discarded before it could be handled.
           This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the ChannelBuffers API documentation for details on how to configure the channel to expect more messages, or to expect messages to get discarded:
             https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
C:\Windows\system32>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.19045.4780], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.0)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.2)
[√] Connected device (2 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

-----------------
edit: after downgrading to flutter version 3.22 its working correctly
