### ISSUE TITLE
Tree red because Devicelab bot failed to codesign ios app

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#154881]
flutter-devicelab-mac-28
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20integration_ui_ios_frame_number/17071/infra

flutter-devicelab-mac-7
 - https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20platform_view_ios__start_up/18668/infra
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20very_long_picture_scrolling_perf_ios__e2e_summary/5453/overview

```
[2024-09-09 15:24:49.376561] [STDOUT] stdout:             error: [   +8 ms] Target profile_ios_bundle_flutter_assets failed: Exception: Failed to codesign /opt/s/w/ir/x/w/rc/tmp5q9tece5/flutter sdk/dev/benchmarks/macrobenchmarks/build/ios/Profile-iphoneos/App.framework/App with identity 6475AE66068783D9C7566E71522EA3915C7D6C9A.
[2024-09-09 15:24:49.376569] [STDOUT] stdout:                        /opt/s/w/ir/x/w/rc/tmp5q9tece5/flutter sdk/dev/benchmarks/macrobenchmarks/build/ios/Profile-iphoneos/App.framework/App: errSecInternalComponent
```

**Comment by christopherfujino** [comment]
The next build for mac-28 then passed, and seemed to be able to codesign: https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_ios%20integration_ui_ios_driver/18757/overview

**Comment by jmagman** [comment]
It's spreading to more bots

flutter-devicelab-mac-3
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20route_test_ios/14739/infra

flutter-devicelab-mac-6
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20route_test_ios/14740/infra

**Comment by christopherfujino** [comment]
Possibly prior art: https://github.com/flutter/flutter/issues/137166

**Comment by bdero** [comment]
```bash
PASSWORD=mysecretpassword
sudo salt -G 'device_os:ios' cmd.run "security set-keychain-settings -l -u -t 1800 login.keychain && security unlock-keychain login.keychain -p $PASSWORD" runas="swarming"
```

**Comment by bdero** [comment]
The problem is likely that every hour (+-15 minutes), the keychain is getting destroyed and recreated.
There's a rule to only do this when files copied from `salt://flutter/code_signing/` have changed locally. But I confirmed that it's executing for every state sync.

When I run `salt-call state.sls flutter/code_signing`, the re-creation gets skipped because no changes are reported. But when I apply the full state on the minion (`sudo salt-call state.apply`), the recreation doesn't get skipped because permissions change on some files.

Trying to work out what's causing the permissions to change.

**Comment by bdero** [comment]
I tracked this down to two states that are copying in the same files with different permissions. I updated the permissions of the files being copied from the repo on the salt master, so the issue should hopefully begin to subside now.

**Comment by bdero** [comment]
Confirmed that it's properly skipping the keychain recreation for full state runs now:

```
          ID: /opt/flutter/code_signing
    Function: file.recurse
      Result: True
     Comment: The directory /opt/flutter/code_signing is in the correct state
     Started: 16:58:54.334501
    Duration: 2722.539 ms
     Changes:
----------
          ID: restore_keychain
    Function: cmd.run
        Name: cd /opt/flutter/code_signing
LOGIN_PASSWORD=dartydartdart ./nuke.sh
security create-keychain -p dartydartdart login.keychain
security set-keychain-settings -l -u -t 1800 login.keychain
LOGIN_PASSWORD=dartydartdart ./restore.sh

      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 16:58:57.058021
    Duration: 0.004 ms
     Changes:
```
