### ISSUE TITLE
Unable to install apk on emulator using Flutter >=3.24.2

### ISSUE THREAD

**Issue by felangel** [flutter/flutter#155178]
### Steps to reproduce

1. `flutter create -e example`
2. `flutter build apk --release`
3. Install the apk via `bundletool` (`bundletool install-apks --apks=/MyApp/my_app.apks --allow-downgrade`)

### Expected results

I expect the apk to be installed successfully (it works fine on older Flutter versions).

### Actual results

```
Failed to install apks: The APKs have been extracted in the directory: /tmp/2153388737290565326
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Installation of the app failed.
at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:196)
at com.android.tools.build.bundletool.commands.InstallApksCommand.lambda$execute$1(InstallApksCommand.java:234)
at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:81)
at com.android.tools.build.bundletool.device.AdbRunner.run(AdbRunner.java:61)
at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:233)
at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:117)
at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)
Caused by: com.android.ddmlib.InstallException: Failed to commit install session 1858312453 with command cmd package install-commit 1858312453.
Error: INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1858312453.tmp/0_universal: Attempt to get length of null array
at com.android.ddmlib.SplitApkInstallerBase.installCommit(SplitApkInstallerBase.java:99)
at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:85)
at com.android.ddmlib.internal.DeviceImpl.installPackages(DeviceImpl.java:1166)
at com.android.tools.build.bundletool.device.DdmlibDevice.installApks(DdmlibDevice.java:180)
```

### Code sample

<details open><summary>Code sample</summary>

```sh
#!/bin/bash -ex

# This script tests the patching functionality of Shorebird.
# It creates a new empty, flutter project, initializes Shorebird,
# creates a new release, patches the release, and then ensures
# that the patch was applied correctly.
#
# Pre-requisites:
# - Flutter must be installed.
# - Android SDK must be installed.
# - ADB must be installed and be part of PATH.
# - Android emulator must be running.
# - Shorebird must be installed.
#
# Usage: ./patch_e2e.sh <flutter-version>

FLUTTER_VERSION=$1

# Intentionally including a space in the path.
TEMP_DIR=$(mktemp -d -t 'shorebird workspace-XXXXX')
cd "$TEMP_DIR"

# Create a new empty flutter project
flutter create e2e_test --empty --platforms android
cd e2e_test

# Replace the contents of "lib/main.dart" with a single print statement.
echo "void main() { print('hello world'); }" >lib/main.dart

# Initialize Shorebird
shorebird init --force -v

# Point to the development environment
echo "base_url: https://api-dev.shorebird.dev" >> shorebird.yaml

# Extract the app_id from the "shorebird.yaml"
APP_ID=$(cat shorebird.yaml | grep 'app_id:' | awk '{print $2}')

# Create a new release on Android
shorebird release android --flutter-version=$FLUTTER_VERSION -v

# Run the app on Android and ensure that the print statement is printed.
while IFS= read line; do
    if [[ "$line" == *"I flutter : hello world"* ]]; then
        adb kill-server
        echo "✅ 'hello world' was printed"
        break
    fi
done < <(shorebird preview --release-version 0.1.0+1 --app-id $APP_ID --platform android)

# Replace lib/main.dart "hello world" to "hello shorebird"
sed -i 's/hello world/hello shorebird/g' lib/main.dart

echo "lib/main.dart is now:"
cat lib/main.dart

# Create a patch
shorebird patch android -v

# Run the app on Android and ensure that the original print statement is printed.
while IFS= read line; do
    if [[ "$line" == *"Patch 1 successfully"* ]]; then
        # Kill the app so we can boot the patch
        adb shell am force-stop com.example.e2e_test
        echo "✅ Patch 1 successfully installed"
        break
    fi
done < <(shorebird preview --release-version 0.1.0+1 --app-id $APP_ID --platform android)

# Re-run the app, *not* using shorebird preview, as that installs the base release.
adb shell monkey -p com.example.e2e_test -c android.intent.category.LAUNCHER 1

# Re-run the app on Android and ensure that the new print statement is printed,
# tailing adb logs and printing the last 10 seconds of logs in case the
# "hello shorebird" statement was printed before entering the loop.
while IFS= read line; do
    if [[ "$line" == *"I flutter : hello shorebird"* ]]; then
        adb kill-server
        echo "✅ 'hello shorebird' was printed"
        break
    fi
done < <(adb logcat -T '10.0')

echo "✅ All tests passed!"
exit 0
```

```yaml
name: e2e

on: [pull_request]

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        flutter-version: [3.24.3, 3.24.1, 3.24.0, 3.22.3, 3.22.2, 3.19.6]

    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      SHOREBIRD_HOSTED_URL: https://api-dev.shorebird.dev

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🖥️ Add Shorebird to PATH
        shell: bash
        run: echo "${GITHUB_WORKSPACE}/bin/" >> $GITHUB_PATH

      - name: 🐦 Verify Shorebird Installation
        run: |
          if [[ $(shorebird --version) =~ "Engine • revision" ]]; then          
            echo '✅ Shorebird CLI is installed!'
          else
            echo '❌ Shorebird CLI is not installed.'
          exit 1
          fi
        shell: bash

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: 🎯 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ matrix.flutter-version }}
          cache: true

      - name: 🤖 AVD Cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-34

      - name: 🤖 Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: aosp_atd
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD Snapshot"

      - name: 🧪 Run Patch E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: aosp_atd
          arch: x86_64
          script: ./scripts/patch_e2e.sh ${{ matrix.flutter-version }}
```
</details>

### Screenshots or Video

https://github.com/shorebirdtech/shorebird/actions/runs/10855015557/job/30126696710

### Logs

<details open><summary>Logs</summary>
https://github.com/shorebirdtech/shorebird/actions/runs/10855015557/job/30126696710
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on Ubuntu 22.04.4 LTS 6.5.0-1025-azure, locale C.UTF-8)
    • Flutter version 3.24.3 on channel stable at /opt/hostedtoolcache/flutter/stable-3.24.3-x64
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /usr/local/lib/android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /usr/local/lib/android/sdk
    • ANDROID_SDK_ROOT = /usr/local/lib/android/sdk
    • Java binary at: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64/bin/java
    • Java version OpenJDK Runtime Environment Temurin-17.0.12+7 (build 17.0.12+7)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✗] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.30.3
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.0
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
[✓] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)                       • linux         • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-1025-azure
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 128.0.6613.119
[✓] Network resources
    • All expected network resources are available.
! Doctor found issues in 2 categories.
```

</details>
