### ISSUE TITLE
After MacOs 15.0 Update facing this issue

### ISSUE THREAD

**Issue by khushal-chothani** [flutter/flutter#155471]
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_database.FLTFirebaseDatabaseObserveStreamHandler': '/Users/khushal/Projects/Flutter/Inhouse/kunj_fashion/kunj_fashion/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/khushal/.pub-cache/hosted/pub.dev/firebase_database-11.1.3/ios/Classes/FLTFirebaseDatabaseObserveStreamHandler.h:3:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_database.FLTFirebaseDatabasePlugin': '/Users/khushal/Projects/Flutter/Inhouse/kunj_fashion/kunj_fashion/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/khushal/.pub-cache/hosted/pub.dev/firebase_database-11.1.3/ios/Classes/FLTFirebaseDatabasePlugin.h:3:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_database.FLTFirebaseDatabaseUtils': '/Users/khushal/Projects/Flutter/Inhouse/kunj_fashion/kunj_fashion/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/khushal/.pub-cache/hosted/pub.dev/firebase_database-11.1.3/ios/Classes/FLTFirebaseDatabaseUtils.h:3:8

Could not build the application for the simulator.
Error launching application on iPhone 16.

pub file

```
name:  abc
 
description: "A new Flutter project."
 
publish_to: 'none'  
 
version: 1.0.0+1

environment:
  sdk: ^3.5.2
 
dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^8.0.0

  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  get: ^4.6.6
  connectivity_plus: ^6.0.5
  # Local cache
  shared_preferences: ^2.3.2

  # Navigation
  go_router: ^14.2.7

  intl: ^0.19.0

  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  firebase_auth: ^5.3.0
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0
 
flutter:

  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 100
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 600

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    
    
    ```
