### ISSUE TITLE
 java.lang.SecurityException: com.vazra.apps: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by RuberDucky** [flutter/flutter#155814]
**I am getting a crash with my Flutter apps, which shows a security exception with the targetSDKVersion 34.**

Here is my android/build.gradle file: 

```
buildscript {
    ext.kotlin_version = '1.8.21'
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" } //Added this line
    }

    dependencies {
         classpath 'com.android.tools.build:gradle:7.1.2'
         classpath 'com.google.gms:google-services:4.3.5'
         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.2'
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
         }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}
```

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

app/build.gradle file:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
   compileSdkVersion 34

   compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }


    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.vazra.apps"
        minSdkVersion 24
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            shrinkResources false
            minifyEnabled false
        }
    }


    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
 
    buildTypes {
        release {
          signingConfig signingConfigs.release
       }
    }
      packagingOptions {
    pickFirst '**/*.so'
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.android.support:multidex:1.0.3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:32.2.3')
    implementation 'com.google.firebase:firebase-core:21.1.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    implementation 'com.google.firebase:firebase-auth:22.1.1'
    implementation 'com.google.firebase:firebase-messaging:23.2.1'
    implementation 'com.google.firebase:firebase-crashlytics:18.4.1'
    implementation 'com.google.firebase:firebase-analytics:21.3.0'
    implementation 'androidx.browser:browser:1.3.0'
    implementation("com.google.firebase:firebase-auth")
}

 configurations.all {
    resolutionStrategy {
        force 'com.google.android.gms:play-services-location:21.0.1'
        
     }
 }
```
Flutter Doctor:
```
[√] Flutter (Channel stable, 3.13.8, on Microsoft Windows [Version 10.0.21996.1], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] Connected device (4 available)
[√] Network resources
```
I try this solution by adding the following code snippet in the androidMenifest.xmll file but got the same error: 
```
	<receiver
    	android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
    	android:exported="true"
    	android:permission="com.google.android.c2dm.permission.SEND">
    <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <category android:name="${applicationId}" />
    </intent-filter>
	</receiver>
```

**Comment by darshankawar** [comment]
@RuberDucky 
It probably could be due to one of the plugins you are using. Can you share your `pubspec.yaml` ?

**Comment by RuberDucky** [comment]
```
version: 2.0.16+100
# version: 2.1.0+0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  extended_image: 8.1.0
  flutter_image_compress: 2.0.4
  cached_network_image: 3.2.3
  image_picker: ^1.0.6
  ffmpeg_kit_flutter: 5.1.0
  flutter_launcher_plus: 0.0.6
  font_awesome_flutter: 10.5.0
  image_editor: 1.3.0

  google_translate: 0.0.6
  logger: 1.4.0
  cloud_functions: 4.1.0
  audioplayers: 4.0.1
  pin_input_text_field: 4.2.0
  audio_session: 0.1.13
  flutter_cache_manager: 3.3.0
  rxdart: 0.27.5
  better_open_file: 3.6.4
  file_saver: 0.1.1
  gallery_saver: 2.3.2
  url_launcher: 6.1.12
  circular_countdown_timer: 0.2.1
  camera: ^0.10.5+9
  oktoast: 3.3.1
  holding_gesture: 1.1.0
  flutter_emoji: 2.4.0
  pip_view: 0.9.6-nullsafety
  page_transition: 2.0.5
  wechat_assets_picker: ^8.8.1+1
  video_editor: 3.0.0
  mime: 1.0.4
  video_compress: ^3.1.3
  link_preview_generator: 1.2.0
  any_link_preview: 3.0.1
  google_mobile_ads: 2.0.1
  sms_autofill: 2.2.0
  receive_sharing_intent: 1.4.5
  firebase_crashlytics: 3.0.3
  async: 2.11.0
  emoji_picker_flutter: 1.3.1
  flutter_video_info: 1.3.1
  group_button: 3.3.1
  flutter_colorpicker: 0.6.1
  devicelocale: 0.5.4
  http_auth: 1.0.2
  cloud_firestore: 4.7.0
  flutter_cached_pdfview: 0.4.1
  firebase_messaging: ^14.6.0
  firebase_storage: 11.0.3
  device_info_plus: 9.0.2
  file_picker: 5.3.3
  path_provider: 2.0.12
  path: 1.8.3
  flutter_sound: 9.2.13
  percent_indicator: 4.2.2
  string_validator: 1.0.0
  ntp: 2.0.0
  random_string: 2.3.1
  intl: 0.18.1
  connectivity_plus: 3.0.3
  http: 1.1.0
  provider: 6.0.5
  firebase_auth: 4.1.0
  html: 0.15.4
  universal_platform: 1.0.0+1
  flutter_linkify: 5.0.2
  dotted_border: 2.0.0+1
  diacritic: 0.1.3
  image_cropper: 1.5.1
  contacts_service: 0.6.3
  share: 2.0.4
  scoped_model: 2.0.0-nullsafety.0
  local_auth: 2.1.6
  crypto: 3.0.2
  encrypt: 5.0.1
  localstorage: 4.0.0+1
  # photo_view: 0.12.0
  # flutter_photo_view: 1.0.3
  launch_review: 3.0.1
  overlay_support: 2.0.1
  jiffy: 6.2.1
  geolocator: ^10.1.0
  video_player: 2.7.0
  video_thumbnail: 0.5.3
  chewie: 1.7.0
  media_info: 0.8.0
  firebase_core: 2.12.0
  shared_preferences: 2.2.0
  permission_handler: ^11.0.1
  agora_rtc_engine: 6.1.1+1
  flutter_local_notifications: 12.0.4
  flutter_secure_storage: 5.0.2
  package_info_plus: 4.0.2
  giphy_get: 3.4.2
  wakelock_plus: 1.1.1
  cupertino_icons: 1.0.5
  collection: 1.17.2
  dropdown_plus: 0.0.9
  gif: ^2.2.0
  rename: ^2.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  flutter_driver:
    sdk: flutter
  test: ^1.16.8
dependency_overrides:
  http: "0.13.4"

  flutter_launcher_icons: ^0.9.0
flutter_icons:
  # android: "ic_launcher"
  ios: true
  image_path: "assets/appicon/appicon.jpg"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/flags/
    - lib/Services/localization/json_languages/
```
