### ISSUE TITLE
Forced Pod install creates recursive check that creates build issues

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#15591]
Using Flutter master
Mac OS

`flutter build` will run `pod install` which creates a **Framework Search Paths** entry that is recursive. i.e.: `$(PODS_ROOT)/**`. With certain plugins (e.g. Firebase) this will lead to the following build error:

```
Argument list too long: recursive header expansion failed at /<ios project directory>/Pods/.symlinks/plugins/firebase_storage-0.1.4/android/build/intermediates/classes/debug/com/google/firebase/storage/api.
```

Removing the recursive entry will allow the build to complete successfully.

**Comment by xster** [comment]
cc @mravn-google, may be related to #14748

**Comment by mravn-google** [comment]
@lukef I cannot reproduce with current Flutter master, Cocoapods 1.5.0, Xcode 9.3, 
```yaml
dependencies:
  google_sign_in:
  firebase_admob:
  firebase_analytics:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  firebase_storage:
  flutter:
    sdk: flutter
```
If you can still reproduce, please provide more details on your setup.
