### ISSUE TITLE
Good reason that hot restart in command line release should take longer than ordinary command line release ?

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#156319]
![image](https://github.com/user-attachments/assets/587c7c3f-14be-4953-bacd-8bb0433c3d48)

Sometimes i need to run my app in release mode to fix tideous bugs.

But in later Flutter versions (3.16+) the "hot restart" 'r' button takes 15 seconds longer to execute than others.

Shouldn't it be faster than inital run ?

**Comment by huycozy** [comment]
Hi @RoarGronmo 
I checked this on the latest Flutter stable 3.24.3 but couldn't seem to see the issue after several times triggering `hot restart`:

```console
➜  repro_stable flutter run -d chrome --release 
Launching lib/main.dart on Chrome in release mode...
Compiling lib/main.dart for the Web...                             39.8s
✓ Built build/web

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".


✓ Built build/web
Performing hot restart...                                        1,058ms
Restarted application in 1,062ms.

✓ Built build/web
Performing hot restart...                                          971ms
Restarted application in 973ms.

✓ Built build/web
Performing hot restart...                                        1,044ms
Restarted application in 1,044ms.

✓ Built build/web
Performing hot restart...                                          946ms
Restarted application in 946ms.

✓ Built build/web
Performing hot restart...                                          906ms
Restarted application in 907ms.
```

Since you are on an old Flutter version, can you try upgrading and retrying on Flutter 3.24.3? Do you only see the issue on your project or does this also occur on a newly created project?

**Comment by RoarGronmo** [comment]
Of course, I should supply `flutter doctor -v` output: Here it is:

```
PS C:\FlutterProjects\mPortal> flutter doctor -v
[√] Flutter (Channel beta, 3.26.0-0.1.pre, on Microsoft Windows [Version 10.0.22631.4249], locale nb-NO)
    • Flutter version 3.26.0-0.1.pre on channel beta at c:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee624bc4fd (4 weeks ago), 2024-09-10 17:41:06 -0500
    • Engine revision 059e4e6d8f
    • Dart version 3.6.0 (build 3.6.0-216.1.beta)
    • DevTools version 2.39.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\roarg\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:\Users\roarg\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android Studio\Android Studio 2024.1.1.13\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.40)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.35229.62
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2023.1.1.28
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2023.2.1.25
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2023.3.1.20
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2024.1.2.13
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2024.2.1.9
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2024.2.2.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4249]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.60
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.79

[√] Network resources
    • All expected network resources are available.

• No issues found!
PS C:\FlutterProjects\mPortal> 

```
When I said 3.16+, it is an observation I have had since then, not that I am on that version now (I am on 3.26 beta channel now). This project is "medium" large an uses among `drift` as an internal SQL database, which may be of course a complicating factor. I won't blame any (I don't like blaming any). Compiling to web takes sometimes looong time, and even longer when the target is android (there I haven't done hot reload from console so many times, so I haven't any data for you).

Further, this is my `pubspec.yaml` file, which may be to your help:

```
name: m_portal
description: "Norva24 Customer Portal v2"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

version: 0.4.24+60

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #---flag
  flag: ^7.0.0

  #---email_validator
  email_validator: ^3.0.0

  #drift
  drift: ^2.13.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

  #drift_db_viewer
  drift_db_viewer: ^2.0.0

  #swagger_dart_code_generator
  swagger_dart_code_generator: ^3.0.0
  #swagger_dart_code_generator:
  #  git:
  #    url: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator.git
  #    ref: bacb7781f94e44cb217f163aee8cb681b40d55af

  chopper: ^8.0.0
  json_annotation: ^4.8.0

  #---jwt_decoder
  jwt_decoder: ^2.0.1
  google_maps_flutter: ^2.5.3
  flutter_resizable_container: ^3.0.0
  horizontal_data_table: ^4.3.1

  #---http:
  http: ^1.2.0

  #---collection:
  collection: ^1.18.0

  #---pdf:
  #pdf: ^3.10.7

  #---pdfx:
  pdfx: ^2.6.0

  #---intl:
  intl: ^0.19.0

  #---flutter_charts:
  flutter_charts: ^0.5.2
  week_number: ^1.1.0

  #---data_table_2:
  data_table_2: ^2.5.11

  #---package_info_plus:
  package_info_plus: ^8.0.0

  #---mock_data
  mock_data: ^2.0.1

  #---pointer_interceptor
  pointer_interceptor: ^0.10.1

  #---flutter_carousel_widget
  flutter_carousel_widget: ^3.0.1

  #---web
  web: ^1.0.0

  pubspec_parse: ^1.3.0
  version: ^3.0.2

  universal_io: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  #drift
  drift_dev: ^2.13.0


  #swagger_dart_code_generator
  build_runner: ^2.4.3
  chopper_generator: ^8.0.0
  json_serializable: ^6.6.1


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
