### ISSUE TITLE
Error (Xcode): Framework not found FMDB

### ISSUE THREAD

**Issue by ChurikiTenna** [flutter/flutter#157397]
### Steps to reproduce

The error started appear after I updated flutter to 3.24.3 in order to install `youtube_player_flutter`, and resolved conflicts and stuff.
I don't to remember all the steps...

After misoraneous attempts, conflicts have been resolved. `flutter pub get` works.
But `flutter run` to an iOS device or `flutter build ios` fails.

What I tried:
- Removed the youtube_player_flutter
- flutter clean, upgrade, pub get
- Deleting Derived Data, and flutter clean

Other flutter projects are working just fine. Only this one project is facing the issue.
Running to Web platform works fine.

### Expected results

Run the app on iOS device.

### Actual results

Could not build the precompiled application for the device.
Error (Xcode): Framework not found FMDB

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Error launching application on my iPhone11.

### Code sample

my Podfile looks like this:

<details open><summary>Code sample</summary>

```dart
platform :ios, '16.0'

$iOSVersion = '16.0' 

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'FirebaseCoreExtension', '11.3'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  #target 'RunnerTests' do
  #  inherit! :search_paths
  #end
end

post_install do |installer|
  # fix xcode 15 DT_TOOLCHAIN_DIR - remove after fix oficially - https://github.com/CocoaPods/CocoaPods/issues/12065
  installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      flutter_additional_ios_build_settings(target)
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
          xcconfig_path = config.base_configuration_reference.real_path
          IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end
end
```

</details>

Removing `pod 'FirebaseCoreExtension', '11.3'` causes this error:
https://github.com/firebase/flutterfire/issues/13527

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Automatically signing iOS for device deployment using specified development team in Xcode project:
9N3857N23W
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         3.2s
Xcode build done.                                           44.5s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Framework not found FMDB


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)



Error launching application on Tenna’s iPhone11.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
    • Flutter version 3.24.3 on channel stable at /Users/tenna/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tenna/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (8 available)
    • Tenna’s iPhone11 (mobile)       • 00008030-0012304A01D3402E                • ios            • iOS
      17.6.1 21G93
    • tenna’s iphone15 (mobile)       • 00008120-00120DDA1E10A01E                • ios            • iOS 18.1
      22B5075a
    • Tenna’s iPad (mobile)           • d1802c9bcfe7b9b836383ca90361f9c15180f21e • ios            • iOS
      17.6.1 21G93
    • Tenna’s iPad (2) (mobile)       • 00008101-0015198A28782C3A                • ios            • iOS
      17.5.1 21F90
    • Sota’s iPad (mobile)            • 00008030-0011253134E0C02E                • ios            • iOS
      17.6.1 21G93
    • macOS (desktop)                 • macos                                    • darwin-arm64   • macOS
      14.1.1 23B81 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                    • darwin         • macOS
      14.1.1 23B81 darwin-arm64
    • Chrome (web)                    • chrome                                   • web-javascript • Google
      Chrome 130.0.6723.59

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ChurikiTenna** [comment]
Current pubspec.yaml

```
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.6
  syncfusion_flutter_charts: ^27.1.55
  path_provider: ^2.0.11
  http: ^1.2.2
  shared_preferences: ^2.0.15
  keyboard_actions: ^4.1.0
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.4.0
  dotted_border: ^2.0.0+3
  page_transition: ^2.0.9
  package_info_plus: ^8.1.0
  permission_handler: ^11.3.1
  in_app_review: ^2.0.6
  loading_animation_widget: ^1.2.0+4
  flutter_localization: ^0.2.2
  google_fonts: ^6.2.1
  app_tracking_transparency: ^2.0.4
  crypto: ^3.0.3
  camera: ^0.11.0+2
  pie_chart: ^5.4.0
  intl: ^0.19.0
  universal_html: ^2.2.3
  image: ^4.0.17
  statistics: ^1.0.25
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  path: ^1.8.3
  csv: ^6.0.0
  share_plus: ^10.1.0
  device_info_plus: ^11.1.0
  blur: ^4.0.0
  infinite_listview: ^1.1.0
  flutter_launcher_icons: ^0.14.1
  sliding_up_panel: ^2.0.0+1
  hovering: ^1.0.4
  provider: ^6.1.2
  local_auth: ^2.3.0
  flutter_screen_lock: ^9.1.0
  hooks_riverpod: ^2.5.4
  freezed_annotation: ^2.4.4
  state_notifier: ^1.0.0
  app_settings: ^5.1.1
  #youtube_player_flutter: ^9.0.4
  google_mlkit_image_labeling: ^0.13.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.3.3
  firebase_storage: ^12.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
```
