### ISSUE TITLE
dependency_overrides not working

### ISSUE THREAD

**Issue by xiedeacc** [flutter/flutter#157665]
### Steps to reproduce

1. flutter create hello_world
2.  change pubspec.yaml
```
dependency_overrides:
  analyzer: ^6.3.0
  meta: ^1.11.0
  analyzer_plugin: ^0.11.3
  custom_lint: ^0.6.4
```
3. flutter pub get
even though I overides anlyzer and custom_lint version, but flutter still get anlyzer 6.7.0 and custom_lint 0.6.10, why?

### Expected results

flutter get use overided version

### Actual results

flutter get wrong version

### Code sample

```
name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: 3.24.3

dependencies:
  path_provider_ios:
  photo_manager: ^3.5.1
  photo_manager_image_provider: ^2.2.0
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  intl: ^0.19.0
  auto_route: ^9.2.0
  fluttertoast: ^8.2.4
  video_player: ^2.8.2
  chewie: ^1.7.4
  socket_io_client: ^2.0.3+1
  maplibre_gl: 0.19.0+2
  geolocator: ^11.0.0 # used to move to current location in map view
  flutter_udid: ^3.0.0
  flutter_svg: ^2.0.9
  package_info_plus: ^8.0.1
  url_launcher: ^6.2.4
  http: ^1.1.0
  cancellation_token_http: ^2.0.0
  easy_localization: ^3.0.3
  share_plus: ^10.0.0
  flutter_displaymode: ^0.6.0
  scrollable_positioned_list: ^0.3.8
  path: ^1.8.3
  path_provider: ^2.1.2
  collection: ^1.18.0
  http_parser: ^4.0.2
  flutter_web_auth: ^0.5.0
  easy_image_viewer: ^1.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  permission_handler: ^11.2.0
  device_info_plus: ^11.0.0
  connectivity_plus: ^6.0.0
  wakelock_plus: ^1.1.4
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.2
  octo_image: ^2.0.0
  thumbhash: 0.1.0+1
  async: ^2.11.0
  dynamic_color: ^1.7.0 #package to apply system theme
  background_downloader: ^8.5.5
  crop_image: ^1.0.13
  image_picker: ^1.0.7 # only used to select user profile image from system gallery -> we can simply select an image from within immich?
  logging: ^1.2.0
  file_picker: ^8.0.0+1

dependency_overrides:
  analyzer: ^6.3.0
  meta: ^1.11.0
  analyzer_plugin: ^0.11.3
  custom_lint: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.3.9
  isar_generator: ^3.1.0+1
  integration_test:
    sdk: flutter
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9
  mocktail: ^1.0.3
  linter:
    path: './linter'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/
  fonts:
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata-Regular.ttf
    - family: Overpass
      fonts:
        - asset: fonts/overpass/Overpass-Regular.ttf
          weight: 400
        - asset: fonts/overpass/Overpass-Italic.ttf
          style: italic
        - asset: fonts/overpass/Overpass-Medium.ttf
          weight: 500
        - asset: fonts/overpass/Overpass-SemiBold.ttf
          weight: 600
        - asset: fonts/overpass/Overpass-Bold.ttf
          weight: 700
    - family: OverpassMono
      fonts:
        - asset: fonts/overpass/OverpassMono.ttf
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
[!] Flutter (Channel [user-branch], 3.24.3, on Microsoft Windows [Version 10.0.19045.5011], locale en-US)
    ! Flutter version 3.24.3 on channel [user-branch] at D:\code\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\android_sdk\
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.11.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.11.35222.181
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code (version 1.94.2)
    • VS Code at C:\Users\tiger\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • M2101K9G (mobile) • 192fe6de • android-arm64  • Android 12 (API 32)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19045.5011]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 130.0.6723.70
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 129.0.2792.65

[!] Network resources                   
    X A network error occurred while checking "https://maven.google.com/": The semaphore timeout period has expired.

    X An HTTP error occurred while checking "https://github.com/": Connection closed before full header was received

! Doctor found issues in 2 categories.

```
