### ISSUE TITLE
Having trouble uploading playstore due to new video policy of playstore

### ISSUE THREAD

**Issue by ferisetyo1** [flutter/flutter#158315]
### Manifest
```
 <uses-permission
        android:name="android.permission.INTERNET" />
    <uses-permission
        android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission
        android:name="android.permission.CAMERA" />
    <uses-permission
        android:name="android.permission.GALLERY" />
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission
        android:name="android.permission.READ_INTERNAL_STORAGE" />
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission
        android:name="android.hardware.microphone" />
    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
```

### Dependencies
```
dependencies:
  # alice: ^0.4.2
  android_intent_plus: ^5.0.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  dropdown_search: ^6.0.1
  file_picker: ^8.0.7
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_in_app_messaging: ^0.8.0+3
  firebase_messaging: ^15.0.3
  firebase_remote_config: ^5.1.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.0.1
  flutter_form_builder: ^9.2.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_audio: ^3.0.0-beta.2
  flutter_html_iframe: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_html_video: ^3.0.0-beta.2
  flutter_local_notifications: ^18.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  form_builder_image_picker: ^4.1.0
  form_builder_validators: any
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  gettext: ^1.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  icons_launcher: ^2.1.7
  image_cropper: ^7.1.0
  image_picker: ^1.1.0
  intl: any
  json_annotation: ^4.9.0
  jwt_decode: ^0.3.1
  latlong2: ^0.9.1
  open_filex: ^4.5.0
  package_info_plus: any
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^26.1.41+1
  table_calendar: ^3.1.2
  timeago: ^3.7.0
  timeago_flutter: ^3.7.0
  upgrader: ^11.3.0
  url_launcher: ^6.3.0
  very_good_infinite_list: ^0.7.1
```

### Message from Playstore

Issue found: Permission use is not directly related to your app’s core purpose.
We found that your app is not compliant with how the READ_MEDIA_IMAGES/READ_MEDIA_VIDEO permissions are allowed to be used.

Your app only requires one-time or infrequent access to media files on the device. Only apps with a core use case that require persistent access to photo and video files located in shared storage on devices are allowed to use photo and video permissions. For more details on the requirements, please see [Google Play's Photo and Video Permissions policy](https://notifications.google.com/g/p/ANiao5rxovv4if__2FbMiynAVAa0iZZQF0sfSinWkS7QuCY2b9-fz0KIJAnyW7EI0XhYlGySzBDhu3vfIoQZ7s9Vvumer27PMdESz9oI0cckF0UGUUA4rook2CXoYlIDNXIRn3ziab052bitLrcewPMUKN2ibBH-nSLN138dQM29_85-SAsKCdbHOWx2lH-aN1T0hYBcVF4KkX9ObYdyg15CPVm1Z1kph2WTjJjJAcaxut8NnVBBIVDX_s1JGtxvsGno3Fw).

Issue details

We found an issue in the following area(s):

Version code 42
To bring your app into compliance, follow these steps:

To comply with [Google Play's Photo and Video Permissions policy](https://notifications.google.com/g/p/ANiao5onyjLRsK4YCD0qEuJ2C7Q6okOGQS7Wi-7FGRsxS6qsgf7-UHrxj9HFjMtmzBjYFJGXnmLjanXABFEdbMJGUdfH2_CuGNKGh7dXDPsOT7n6CdaoehCzarSJYkog2cFOjrUHGebfULqyeR-Gfvr3YBU5WJS0aqf8PaUcnNAaj8UEunNZ5n-LViqb-JY4x0A8lot7xjsYAxPEobUUeLdqmE70ptORYW9-Be9-cFaNZIeXdyMjLZLVTpUIf1M7TMSqyumW2XOjgH8), please adjust the following requirements by January 22nd 2025 (or May 28th 2025, if you have already applied for an extension):

Remove the use of READ_MEDIA_IMAGES/READ_MEDIA_VIDEO permission from all version codes within the submission. This includes both production and testing tracks.
If your app requires one-time, or limited use of photo and video file, remove the permissions and consider using the [Android photo picker](https://notifications.google.com/g/p/ANiao5ofZzioK62GcWmsi_rN6QG117vI3GoRLcbbYLidSTk3dADlqoKXk9MO4bU2GwP3fWoDWTvHCt35vqnkTPFaFm-8y2p3eviiQ7QOE60E1IpMREpN5gAR8TX7D_yhRNl5eToJxv0vSx4v2yfBAwk2nwUU3l47hMLVMaXelUfozW0zvStXzk7nxmeI6JqHV7a0Gxs1yNdmb1ooNJVjoRMhsOkzbySOKEDjXy8kmZHBRrIRu6lBERUsTVBX_UKU8knzLj85T__P1700).
If you need more time to implement, you may use the self-service option to request an extension in Play Console until May 28th, 2025.
About the [Photo and Video Permissions policy](https://notifications.google.com/g/p/ANiao5rxovv4if__2FbMiynAVAa0iZZQF0sfSinWkS7QuCY2b9-fz0KIJAnyW7EI0XhYlGySzBDhu3vfIoQZ7s9Vvumer27PMdESz9oI0cckF0UGUUA4rook2CXoYlIDNXIRn3ziab052bitLrcewPMUKN2ibBH-nSLN138dQM29_85-SAsKCdbHOWx2lH-aN1T0hYBcVF4KkX9ObYdyg15CPVm1Z1kph2WTjJjJAcaxut8NnVBBIVDX_s1JGtxvsGno3Fw)
READ_MEDIA_IMAGES/READ_MEDIA_VIDEO is a restricted permission and apps must only declare this permission if their core functionality requires broad access to all photo or video files on the device. Apps that request this restricted permission are subject to review, and those that do not meet the acceptable use case criteria will be disallowed from publishing on Google Play.

If your app requires one-time, or limited use of photo and video files, you are requested to use a system picker such as the [Android photo picker](https://notifications.google.com/g/p/ANiao5qniQc39YtyTFDIIz_uhUK2m1tKrX3RuqKjljAIUYdDi9_Ag8MoIzPg1G5w_rTk-zG6zuheQAc4SLHSAukZwBAOWNCmDDIQN8aFLl40XSKTGpAYdqV5QDwFj7BkHyGux62ODBt_ASAWaLpcmSzxwoh3FtQyH4AgbHNRhruVCzE_55H9Lqz91ik4gCl0q5vjmaS4I1b-2iDXL6IadvPLuKm0j8GKscByMkkyAB6THp6gT-ktvLRNICozbBST1wn-GQ).

For more information on the Android Photo picker, please see this [developer guidance](https://notifications.google.com/g/p/ANiao5ofZzioK62GcWmsi_rN6QG117vI3GoRLcbbYLidSTk3dADlqoKXk9MO4bU2GwP3fWoDWTvHCt35vqnkTPFaFm-8y2p3eviiQ7QOE60E1IpMREpN5gAR8TX7D_yhRNl5eToJxv0vSx4v2yfBAwk2nwUU3l47hMLVMaXelUfozW0zvStXzk7nxmeI6JqHV7a0Gxs1yNdmb1ooNJVjoRMhsOkzbySOKEDjXy8kmZHBRrIRu6lBERUsTVBX_UKU8knzLj85T__P1700).

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

https://support.google.com/googleplay/android-developer/answer/15444680
<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/cec5fe4a-0a3c-4df2-b537-f02821b5509c)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-arm64, locale
    en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.1)
[✓] Connected device (4 available)
[✓] Network resources
```
