### ISSUE TITLE
Does Flutter currently support catalogs?

### ISSUE THREAD

**Issue by android-dev2015** [flutter/flutter#158368]
### Use case

setting.gradle.kts
pluginManagement {
    val flutterSdkPath = run {
        val properties = java.util.Properties()
        file("local.properties").inputStream().use { properties.load(it) }
        val path = properties.getProperty("flutter.sdk")
        checkNotNull(path) { "flutter.sdk not set in local.properties" }
        path
    }
    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    alias(libs.plugins.flutterPluginLoader)
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
}

include(":app")
include(":core")

### Proposal

e: file:///D:/Android/xx/xx/android/settings.gradle.kts:33:11: Unresolved reference: libs

**Comment by huycozy** [comment]
As I can see, [version catalog](https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog) doesn't seem to be supported on Android. Marking this as a feature request. I also add `android/gradle/libs.versions.toml` file content here to test later:

```toml
[versions]
agp = "8.7.0"
kotlin = "1.8.22"
flutterPlugin = "1.0.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
flutterPluginLoader = { id = "dev.flutter.flutter-plugin-loader", version.ref = "flutterPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
```
