### ISSUE TITLE
[Web] fontFamily in ThemeData is not applied on web platform

### ISSUE THREAD

**Issue by Heyholder** [flutter/flutter#158364]
### Steps to reproduce

When applying the Pretendard font through ThemeData, there is no visible change in the font appearance. As shown in the attached screenshots, the text rendering remains identical before and after applying the Pretendard fontFamily in the theme.

### Expected results

Text should render using the Pretendard font when specified in ThemeData.fontFamily.

### Actual results

The font appearance remains unchanged after applying Pretendard font through ThemeData. As shown in the attached screenshots, there is no visible difference between before and after applying the font.

before.
<img width="730" alt="before" src="https://github.com/user-attachments/assets/4bf68f89-ec90-47f7-bbe7-6ca40c27d6fd">

applied Pretendard fonts.
<img width="727" alt="after" src="https://github.com/user-attachments/assets/9f1b2d9d-6392-4046-92ef-24c97f1775ec">

### Code sample

pubspec.yaml
```
name: fontfamilytest
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
  
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: fonts/Pretendard-Light.ttf
          weight: 300
        - asset: fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: fonts/Pretendard-Black.ttf
          weight: 900

  uses-material-design: true
```

main.dart
```
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
        fontFamily: "Pretendard"
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page by applied Pretendard fonts'),
    );
  }
}
```
fonts
<img width="444" alt="스크린샷 2024-11-08 오후 1 47 03" src="https://github.com/user-attachments/assets/7b587d0e-e340-433f-bb2b-afb7f3052b8f">

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale ko-KR)
    • Flutter version 3.24.4 on channel stable at /Users/hyungryulpark/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (2 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/hyungryulpark/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    ! iOS 18.1 Simulator not installed; this may be necessary for iOS and macOS development.
      To download and install the platform, open Xcode, select Xcode > Settings > Platforms,
      and click the GET button for the required platform.

      For more information, please visit:
        https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes
    • CocoaPods version 1.16.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 82.1.3
    • Dart plugin version 242.22855.32

[✓] Connected device (4 available)
    • Broheat’s phone (mobile)        • 00008110-000818DC01F3801E • ios            • iOS 18.0.1 22A3370
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

```

</details>
