### ISSUE TITLE
Add auto href set to the index.html build

### ISSUE THREAD

**Issue by mohammadamirnm** [flutter/flutter#158513]
### Use case

I was using flutter build for gitlab pages. When deploying I needed to set a base href in the command `flutter build web --base-href="/project_repo/".
However when using gitlab parallel pages it does not work anymore and I have to set it again based on each page I use it on.

### Proposal

There is a script that I found that works for all the situations. I was wondering is it possible to always add this to the top of the `index.html`? 

`<script>(function() {document.write('<base href="' + document.location.pathname + '" />');}());</script> `

I did it via this script in my gitlabCI file:
`-  echo -e "<script>(function() {document.write('<base href=\"' + document.location.pathname + '\" />');}());</script>\n$(cat build/web/index.html)" > build/web/index.html`

**Comment by huycozy** [comment]
>However when using gitlab parallel pages it does not work anymore

Hi @mohammadamirnm, can you be more specific about "gitlab parallel pages"? Can you share a sample code for this? Thanks!

**Comment by mohammadamirnm** [comment]
Hi @huycozy,
Thank you for the fast response.

So GitLab pages (and also GitHub) have an option where you can provide gitlab parallel deployments as mentioned here:
https://docs.gitlab.com/ee/user/project/pages/#parallel-deployments 
https://docs.gitlab.com/ee/ci/yaml/index.html#pagespagespath_prefix
This is basically a location where you deploy your web builds but you can do it for multiple branches. As shown in the shared documentation like this:
```yml
pages:
  stage: deploy
  script:
    - echo "Pages accessible through ${CI_PAGES_URL}/${CI_COMMIT_BRANCH}"
  pages:
    path_prefix: "$CI_COMMIT_BRANCH"
  artifacts:
    paths:
    - public
``` 

So in order for the flutter build to be able to run on the GitLab pages you would have to use the `--base-href` tag for the command like this:
```yml
pages:
  stage: deploy
  script:
    - cp -r build/web --base-href="/reponame/" public
    - echo "the build is uploaded to ${PAGES_URL}"
  variables:
    PAGES_PREFIX: "$CI_COMMIT_BRANCH"
    PAGES_URL: "${CI_PAGES_URL}/${PAGES_PREFIX}"
  pages:
    path_prefix: "$PAGES_PREFIX"
  environment:
    name: "Pages ${PAGES_PREFIX}"
    url: "$PAGES_URL"
  artifacts:
    paths:
      - public
```

However when using the `path_prefix` I noticed that gitlab puts the files in different locations ( not a specific one ) so the simple  `--base-href` tag does not work. What did work was adding the mentioned line to the build as this:

```yml
build:
  stage: build
  extends: .setup-flutter-env
  script:
    - flutter build web
    # This script is to add a line on the top of index.html to set base href variable based on the location of the build
    - echo -e "<script>(function() {document.write('<base href=\"' + document.location.pathname + '\" />');}());</script>\n$(cat build/web/index.html)" > build/web/index.html
  artifacts:
    paths:
      - build/web
```

So if you could somehow add that script to the build process it would be really helpful since it just uses the `location.pathname` for the base href always.
