### ISSUE TITLE
flutter create should initialize analytics_options.yaml with stricter settings

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#159182]
### Use case

When creating a new flutter project with `fluter create` the generated `analysis_options.yaml` does only contain 
`flutter_lints`

### Proposal

It should at least set 

```yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true	
```

also some lints should be set to level `errror` see

https://github.com/dart-lang/sdk/issues/57098#issuecomment-2485661859
