### ISSUE TITLE
`flutter config --explicit-package-dependencies` breaks `flutter build apk`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#160407]
Looking at the failures still being flagged in https://github.com/flutter/flutter/pull/160289, I see a trend where `flutter build apk` (which implicitly is release mode) causes the `integration_test` package itself to fail to be built ([example](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8728333052554778833/+/u/run_plugin_dependencies_test/stdout)); I'm guessing that when we short-circuit the build, we're still leaving artifacts that `integration_test` is depended on, but not in a way that compilation succeeds.

Reproduces at HEAD:

```sh
# Opt-in to the feature
flutter config --explicit-package-dependencies

# Create an Android plugin
flutter create plugin_a --template=plugin --platforms=android

# Try to build the example app for the plugin
cd plugin_a/example
flutter build apk
```

By opting-out again (`flutter config --no-explicit-package-dependencies`) the build succeeds.

Interestingly, the [integration test for this feature](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/android_release_builds_exclude_dev_dependencies_test.dart) _does_ do a `flutter build apk --release`, so I'm guessing this has something to do with how `integration_test` imports and uses the Android embedder (i.e. `import io.flutter.embedding.android.FlutterActivity` and like), and the default (empty) plugin template does not - we should add a regression test as part of fixing this.

---

Some potentially useful bits:

<details>

<summary>With the flag enabled, <code>.flutter-plugins-dependencies</code> looks like this</summary>

```json
{
  "info": "This is a generated file; do not edit or check into version control.",
  "plugins": {
    "ios": [
      {
        "name": "integration_test",
        "path": "/Users/matanl/Developer/flutter/packages/integration_test/",
        "native_build": true,
        "dependencies": [],
        "dev_dependency": true
      }
    ],
    "android": [
      {
        "name": "integration_test",
        "path": "/Users/matanl/Developer/flutter/packages/integration_test/",
        "native_build": true,
        "dependencies": [],
        "dev_dependency": true
      },
      {
        "name": "plugin_a",
        "path": "/private/tmp/flutter.tmp/plugin_a/",
        "native_build": true,
        "dependencies": [],
        "dev_dependency": false
      }
    ],
    "macos": [],
    "linux": [],
    "windows": [],
    "web": []
  },
  "dependencyGraph": [
    {
      "name": "integration_test",
      "dependencies": []
    },
    {
      "name": "plugin_a",
      "dependencies": []
    }
  ],
  "date_created": "2024-12-16 20:52:06.884223",
  "version": "3.28.0-1.0.pre.157",
  "swift_package_manager_enabled": {
    "ios": false,
    "macos": false
  }
}
```

</details>

<details>

<summary>Here is what <code>plugin_a/pubspec.yaml</code> looks like</summary>

```yaml
dependencies:
  flutter:
    sdk: flutter

  plugin_a:
    # When depending on this package from a real application you should use:
    #   plugin_a: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
```

</details>

I assume it's further work required in `flutter.groovy`: https://github.com/flutter/flutter/blob/27ef1967b09e32971075bae06309f742625f7237/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L764-L829
