### ISSUE TITLE
Cannot load assets from a directory

### ISSUE THREAD

**Issue by maxfrees** [flutter/flutter#160720]
### Steps to reproduce

```
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/audios/
```

```
Image.asset('assets/images/login/logo_company.png', height: 22)
```

### Expected results

![image](https://github.com/user-attachments/assets/c6fc89b7-8d93-474b-b335-916aa1a725d4)

### Actual results

-

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>
-

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
