### ISSUE TITLE
App Crash with io.flutter.embedding.engine.FlutterJNI in ensureRunningOnMainThread

### ISSUE THREAD

**Issue by FantaMagier** [flutter/flutter#162369]
### Steps to reproduce

Pubspec
```yaml
version: 3.0.0+102

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl: any

  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  http: ^1.3.0

  device_info_plus: ^11.2.2
  app_settings: ^5.1.1

  camera: ^0.11.0+2
  camera_android_camerax: 0.6.11
  camerawesome: ^2.1.0
  google_mlkit_barcode_scanning: 0.11.1
  google_mlkit_text_recognition: 0.12.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  openfoodfacts: ^3.18.1
  share_plus: ^10.1.4
  onesignal_flutter: ^5.2.9

  drift: ^2.24.0
  sqlite3_flutter_libs: ^0.5.29
  sqlite3: ^2.7.2
  drift_db_viewer: ^2.1.0
  archive: ^4.0.2
  file_picker: ^8.1.7

  telemetrydecksdk: ^2.0.1
  in_app_review: ^2.0.10
  sentry_flutter: ^8.12.0
  qonversion_flutter: ^9.2.1
  flutter_branch_sdk: ^8.3.2
  
  shared_preferences: ^2.4.0
  url_launcher: ^6.3.1

  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  font_awesome_flutter: ^10.8.0
  flutter_markdown: ^0.7.5
  pdf: ^3.11.2
  printing: ^5.14.0
  flutter_image_compress: ^2.4.0

  tuple: ^2.0.2
  path_provider: ^2.1.5
  path: ^1.9.0

  # crisp_chat: ^2.0.0
  wiredash: ^2.3.0

  omni_datetime_picker: ^2.0.6

```

### Expected results

No Crash on this Samsung Device. On every other device it is running

### Actual results

```
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: DefaultDispatcher-worker-2
    at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(SourceFile:34)
    at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(SourceFile:1)
    at I6.m.j(SourceFile:54)
    at Q3.c.r(SourceFile:6)
    at Q6.b.r(SourceFile:5)
    at S1.g.a(SourceFile:45)
    at Y1.D.b(SourceFile:185)
    at O6.d.onRequestPermissionsResult(SourceFile:67)
    at android.app.Activity.requestPermissions(Activity.java:5673)
    at v0.c.b(SourceFile:1)
    at v0.g.d(SourceFile:120)
    at Y1.D.c(SourceFile:87)
    at Y1.B.invokeSuspend(SourceFile:46)
    at h8.a.resumeWith(SourceFile:9)
    at H9.M.run(SourceFile:109)
    at L.k.run(SourceFile:1011)
    at O9.j.run(SourceFile:3)
    at O9.a.run(SourceFile:93)
```

RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: DefaultDispatcher-worker-2

Galaxy S22 SM-S901B
Unhandled

### Code sample

<details open><summary>Code sample</summary>

```dart
No Code needed
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
No logs
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.3, on macOS 15.2 24C101 darwin-arm64, locale de-DE)
    • Flutter version 3.27.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.10.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c519ee916e (8 days ago), 2025-01-21 10:32:23 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/jonahhadt/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] VS Code (version 1.96.4)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.2 24C101 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.2 24C101 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 132.0.6834.111

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>
