### ISSUE TITLE
[video_player] VideoPlayerPlatform (AndroidVideoPlayer) has a bug and is sending more than one initialized event per instance.

### ISSUE THREAD

**Issue by pranavo72bex** [flutter/flutter#162655]
### Steps to reproduce

I am getting sentry initialization issue  

`'package:video_player/video_player.dart': Failed assertion: line 469 pos 13: '!initializingCompleter.isCompleted': VideoPlayerController already initialized. This is typically a sign that an implementation of the VideoPlayerPlatform (AndroidVideoPlayer) has a bug and is sending more than one initialized event per instance.`

`video_player.dart in VideoPlayerController.initialize.eventListener at line 469:13 within video_player`

`video_player: ^2.9.2`

### Expected results

I was not getting this issue previous version.

### Actual results

I was not getting this issue previous version.

### Code sample

```
class VideoPlayerScreen extends ConsumerStatefulWidget {
  const VideoPlayerScreen({
    super.key,
    required this.args,
  });

  final VideoPlayerArgs args;

  @override
  _VideoPlayerScreenState createState() => _VideoPlayerScreenState();
}

class _VideoPlayerScreenState extends ConsumerState<VideoPlayerScreen> {
  late VideoPlayerController _videoPlayerController;
  ChewieController? _chewieController;

  bool isChewieInitialized = false;

  @override
  void initState() {
    super.initState();
    _videoPlayerController = VideoPlayerController.networkUrl(
      Uri.parse(widget.args.videoUrl),
    );
    _videoPlayerController.initialize().then((value) {
      setState(() {
        isChewieInitialized = true;
      });
      _chewieController = ChewieController(
        allowedScreenSleep: false,
        allowFullScreen: true,
        deviceOrientationsOnEnterFullScreen: [
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown,
          DeviceOrientation.landscapeRight,
          DeviceOrientation.landscapeLeft,
        ],
        deviceOrientationsAfterFullScreen: [
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown,
        ],
        videoPlayerController: _videoPlayerController,
        autoInitialize: true,
        autoPlay: true,
        showControls: true,
        showOptions: Platform.isAndroid ? false : true,
      );
    });
  }

  @override
  void dispose() async {
    _videoPlayerController.dispose();
    _chewieController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        leading: IconButton(
          onPressed: () => Navigator.pop(context),
          icon: SvgPicture.asset(
            StaticImageConstants.closeIcon,
            width: Sizes.dimen_24,
            height: Sizes.dimen_24,
            colorFilter: const ColorFilter.mode(Colors.white, BlendMode.srcIn),
          ),
        ),
      ),
      body: !isChewieInitialized
          ? const Center(
              child: LoadingIndicator(
                color: Colors.white,
              ),
            )
          : SafeArea(
              child: Align(
                alignment: Alignment.center,
                child: Chewie(
                  controller: _chewieController!,
                ),
              ),
            ),
    );
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

'package:video_player/video_player.dart': Failed assertion: line 469 pos 13: '!initializingCompleter.isCompleted': VideoPlayerController already initialized. This is typically a sign that an implementation of the VideoPlayerPlatform (AndroidVideoPlayer) has a bug and is sending more than one initialized event per instance.

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.3, on macOS 15.2 24C101 darwin-arm64, locale en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.96.4)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by n3rdkid** [comment]
Getting similar issue when the video is being played and application lifecycle changes such as background and foreground.

**Comment by huycozy** [comment]
@pranavo72bex: The sample code seems to contains 3rd party packages (riverpod, chewie). For us to further investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.

> I was not getting this issue previous version.

Can you share the working version previously?

@n3rdkid Your issue doesn't look similar to this issue, please file a separate issue for better tracking. Thanks!

**Comment by pranavo72bex** [comment]
without chewie package 
```
class VideoPlayerScreen extends ConsumerStatefulWidget {
  const VideoPlayerScreen({
    super.key,
    required this.args,
  });

  final VideoPlayerArgs args;

  @override
  _VideoPlayerScreenState createState() => _VideoPlayerScreenState();
}

class _VideoPlayerScreenState extends ConsumerState<VideoPlayerScreen> {
  late VideoPlayerController _videoPlayerController;
  bool isInitialized = false;

  @override
  void initState() {
    super.initState();
    _videoPlayerController = VideoPlayerController.networkUrl(
      Uri.parse(widget.args.videoUrl),
    )..initialize().then((_) {
        setState(() {
          isInitialized = true;
        });
        _videoPlayerController.play();
      });
  }

  @override
  void dispose() {
    _videoPlayerController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        leading: IconButton(
          onPressed: () => Navigator.pop(context),
          icon: SvgPicture.asset(
            StaticImageConstants.closeIcon,
            width: Sizes.dimen_24,
            height: Sizes.dimen_24,
            colorFilter: const ColorFilter.mode(Colors.white, BlendMode.srcIn),
          ),
        ),
      ),
      body: !isInitialized
          ? const Center(
              child: LoadingIndicator(
                color: Colors.white,
              ),
            )
          : SafeArea(
              child: GestureDetector(
                onTap: () {
                  setState(() {
                    if (_videoPlayerController.value.isPlaying) {
                      _videoPlayerController.pause();
                    } else {
                      _videoPlayerController.play();
                    }
                  });
                },
                child: Center(
                  child: AspectRatio(
                    aspectRatio: _videoPlayerController.value.aspectRatio,
                    child: VideoPlayer(_videoPlayerController),
                  ),
                ),
              ),
            ),
    );
  }
}
```

**Comment by huycozy** [comment]
Thanks for your update but the sample code above still uses riverpod package. Can you try using [example](https://github.com/flutter/packages/tree/main/packages/video_player/video_player/example)and reproduce the issue with it?

**Comment by pranavo72bex** [comment]
I am able to resolve the issue by updating pubspec.lock file 

```
dependency: "direct main"
    description:
      name: chewie
      sha256: "335df378c025588aef400c704bd71f0daea479d4cd57c471c88c056c1144e7cd"
      sha256: "645fbca3f22309381edb5af59a4c8aa544a3d3872d7b7b7c986c2b18b3bdd265"
      url: "https://pub.dev"
    source: hosted
    version: "1.8.5"
    version: "1.10.0"
  clock:
    dependency: transitive
    description:
@@ -2249,34 +2249,34 @@ packages:
    dependency: transitive
    description:
      name: video_player_android
      sha256: "45d21bbba3d10b7182aa08ade5d4c68ed3367016d40f29732bb04a799b26842d"
      sha256: "391e092ba4abe2f93b3e625bd6b6a6ec7d7414279462c1c0ee42b5ab8d0a0898"
      url: "https://pub.dev"
    source: hosted
    version: "2.7.5"
    version: "2.7.16"
  video_player_avfoundation:
    dependency: transitive
    description:
      name: video_player_avfoundation
      sha256: d1e9a824f2b324000dc8fb2dcb2a3285b6c1c7c487521c63306cc5b394f68a7c
      sha256: "8a4e73a3faf2b13512978a43cf1cdda66feeeb900a0527f1fbfd7b19cf3458d3"
      url: "https://pub.dev"
    source: hosted
    version: "2.6.1"
    version: "2.6.7"
  video_player_platform_interface:
    dependency: transitive
    description:
      name: video_player_platform_interface
      sha256: "236454725fafcacf98f0f39af0d7c7ab2ce84762e3b63f2cbb3ef9a7e0550bc6"
      sha256: df534476c341ab2c6a835078066fc681b8265048addd853a1e3c78740316a844
      url: "https://pub.dev"
    source: hosted
    version: "6.2.2"
    version: "6.3.0"
  video_player_web:
    dependency: transitive
    description:
      name: video_player_web
      sha256: "6dcdd298136523eaf7dfc31abaf0dfba9aa8a8dbc96670e87e9d42b6f2caf774"
      sha256: "3ef40ea6d72434edbfdba4624b90fd3a80a0740d260667d91e7ecd2d79e13476"
      url: "https://pub.dev"
    source: hosted
    version: "2.3.2"
    version: "2.3.4"
```
