### ISSUE TITLE
Your app is not compliant with Google Play Policies -Why am i getting this

### ISSUE THREAD

**Issue by samgetbitmoney** [flutter/flutter#162716]
Please help , I have posted my manifest and dependencies file

Issue found: Permission use is not directly related to your app’s core purpose.

We found that your app is not compliant with how the READ_MEDIA_IMAGES/READ_MEDIA_VIDEO permissions are allowed to be used.

Your app only requires one-time or infrequent access to media files on the device. Only apps with a core use case that require persistent access to photo and video files located in shared storage on devices are allowed to use photo and video permissions. For more details on the requirements, please see [Google Play's Photo and Video Permissions policy](https://notifications.google.com/g/p/ANiao5rcHUkY6MxMM-3AqFXNO6U8AunEmHGHh8gMQPr17l05oCV8DCmpqfqpDU-ba2kj9yI-KhGl3xw4o_HfpHjzdN-f19WrZFDiPkiTnMZaeCS0GrYOXIeMLWNJ04Hloc0Nnfb1_hTC80ROvZYGjDe1b-Vw-BamBPEdDkSZmKvM4wgxPSo).

Issue details

We found an issue in the following area(s):

    Policy Declaration for Photo Picker: Your app only requires one-time or infrequent access to media files on the device.
```
dependencies:
  alice: ^0.4.2
  carousel_slider: ^5.0.0
  clipboard: ^0.1.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.7.0
  dlibphonenumber: ^1.1.28
  easy_refresh: ^3.4.0
  firebase_analytics: ^10.0.4
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.4
  fl_chart: ^0.69.2
  flutter_flavor: ^3.1.1
  flutter_image_compress: ^2.3.0
  flutter_svg: ^2.0.2
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.4.0
  get: ^4.6.6
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  in_app_update: ^4.2.3
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  line_icons: ^2.0.3
  mailto: ^2.0.0
  mask_text_input_formatter: ^2.9.0
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  smooth_page_indicator: 1.0.0+2
  sms_autofill: ^2.4.1
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.2
  win32: ^5.8.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

```

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.getbitmoney.getbit">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
   <application
        android:label="GetBit"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <meta-data 
           android:name="photopicker_activity:0:required" 
           android:value="" />
       <meta-data
           android:name="firebase_crashlytics_collection_enabled"
           android:value="true" />
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:enableOnBackInvokedCallback="true"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```
