### ISSUE TITLE
Custom font family does not work on macOS

### ISSUE THREAD

**Issue by armin1440** [flutter/flutter#162954]
### Steps to reproduce

1. Create a flutter project
2. Add OpenSans font family files as an asset
3. Update pubspec.yaml according to the assets.
4. Add a text widget and use the font.
5. Run project on macOS and Web.

### Expected results

Both web and macOS apps should look identical.

### Actual results

It seems like the font is not used in macOS and the text font is different from web.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage();

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    return const Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'این یک تست است',
              style: TextStyle(fontFamily: 'OpenSans'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/3755b6c1-0b5d-4d30-889f-6367a457128e" />

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.3 24D60 darwin-arm64, locale en-US)
    • Flutter version 3.24.5 on channel stable at /Users/alitimajchi/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 months ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
    • Android SDK at /Users/alitimajchi/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.3 24D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.3 24D60 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 132.0.6834.162

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @armin1440, you are using an older version of flutter. Kindly upgrade to the latest version of flutter stable to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v` along with the font file so that we can properly investigate this.

Thank you

**Comment by armin1440** [comment]
I used another macbook with newer flutter version. I still get the same output. Here is the output of `flutter doctor -v`

```
[✓] Flutter (Channel stable, 3.27.2, on macOS 13.6.2 22G320 darwin-arm64, locale
    en-IR)
    • Flutter version 3.27.2 on channel stable at /Library/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68415ad1d9 (4 weeks ago), 2025-01-13 10:22:03 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    35.0.0-rc3)
    • Android SDK at /Users/fps/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0-rc3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/fps/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 13.6.2 22G320 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 13.6.2 22G320 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 132.0.6834.162
    ! Error: Browsing on the local area network for iPad. Ensure the device is
      unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
    ! Error: iPhone (2) has recently restarted. Xcode will continue when iPhone
      (2) is unlocked. (code -14)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by armin1440** [comment]
Here are the font style files:

[opensans.zip](https://github.com/user-attachments/files/18747479/opensans.zip)

and here is the font section of my pubspec.yaml:

```
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
        - asset: assets/fonts/opensans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/opensans/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/opensans/OpenSans-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/opensans/OpenSans-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/opensans/OpenSans-SemiBoldItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/opensans/OpenSans-Bold.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/opensans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/opensans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic


```
