### ISSUE TITLE
Unable to build with Firestore 0.4.0

### ISSUE THREAD

**Issue by sabik22** [flutter/flutter#16310]
Packages get result: 
E:\flutter\flutter\bin\flutter.bat --no-color packages upgrade
Running "flutter packages upgrade" in futsal_hub...
Package cloud_firestore has no versions that match >=0.4.0 <0.5.0 derived from:
- futsal_hub depends on version ^0.4.0
pub upgrade failed (1)
Process finished with exit code 1

Flutter Doctor Result:
E:\flutter\flutter\bin\flutter.bat --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.15063], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.0)
[√] Android Studio (version 3.0)
[!] IntelliJ IDEA Community Edition (version 2017.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code, 32-bit edition (version 1.13.0)
[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
Process finished with exit code 0

Popspec.yaml
```
name: futsal_hub
description: Smart Solution for Futsal Company.

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: "^0.4.0"
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
```

Can anyone help me...
Thank you..
