### ISSUE TITLE
ANR io.flutter.plugin.platform.SingleViewFakeWindowViewGroup.<init> Input dispatching timed out

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#163283]
### Steps to reproduce

Just spotted this new ANR in my Google Play console, happened in the foregroind with Android 13

```
Thread 1
"main" tid=1 Native
Main thread
  #00  pc 0x000000000005e378  /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
  #01  pc 0x0000000000210bff  /apex/com.android.art/lib/libart.so (art::ConditionVariable::WaitHoldingLocks+86)
  #02  pc 0x000000000059d9dd  /apex/com.android.art/lib/libart.so (artJniMethodEnd+312)
  #03  pc 0x00000000000a4189  /apex/com.android.art/lib/libart.so (art_jni_method_end+8)
  at android.content.res.AssetManager.nativeThemeApplyStyle (Native method)
  at android.content.res.AssetManager.applyStyleToTheme (AssetManager.java:1222)
  at android.content.res.ResourcesImpl$ThemeImpl.applyStyle (ResourcesImpl.java:1356)
  at android.content.res.Resources$Theme.applyStyle (Resources.java:1568)
  at android.view.ContextThemeWrapper.onApplyThemeResource (ContextThemeWrapper.java:203)
  at android.view.ContextThemeWrapper.initializeTheme (ContextThemeWrapper.java:216)
  at android.view.ContextThemeWrapper.getTheme (ContextThemeWrapper.java:175)
  at android.content.Context.obtainStyledAttributes (Context.java:901)
  at android.view.View.<init> (View.java:5532)
  at android.view.ViewGroup.<init> (ViewGroup.java:704)
  at android.view.ViewGroup.<init> (ViewGroup.java:700)
  at android.view.ViewGroup.<init> (ViewGroup.java:696)
  at android.view.ViewGroup.<init> (ViewGroup.java:692)
  at io.flutter.plugin.platform.SingleViewFakeWindowViewGroup.<init> (SingleViewFakeWindowViewGroup.java)
  at io.flutter.plugin.platform.SingleViewPresentation.onCreate (SingleViewPresentation.java:29)
  at android.app.Dialog.dispatchOnCreate (Dialog.java:436)
  at android.app.Dialog.show (Dialog.java:325)
  at android.app.Presentation.show (Presentation.java:279)
  at io.flutter.plugin.platform.VirtualDisplayController.<init> (VirtualDisplayController.java:1)
  at io.flutter.plugin.platform.VirtualDisplayController.create (VirtualDisplayController.java:201)
  at io.flutter.plugin.platform.PlatformViewsController.configureForVirtualDisplay (PlatformViewsController.java:201)
  at io.flutter.plugin.platform.PlatformViewsController.access$800 (PlatformViewsController.java:201)
  at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer (PlatformViewsController.java:201)
  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create (PlatformViewsChannel.java:896)
  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall (PlatformViewsChannel.java:896)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:17)
  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java:138)
  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0 (DartMessenger.java:138)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7941)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:569)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1019)
```

 

### Expected results

No ANR

### Actual results

ANR

### Code sample

No repro steps unfortunately. This ANR is some low level stuff, and not obvious from the crash logs.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.29.0, on Microsoft Windows [Version 10.0.26100.3194], locale en-US) [516ms]
    • Flutter version 3.29.0 on channel stable at D:\flutter
    ! Warning: `flutter` on your path resolves to D:\projects\xxxx\flutter, which is not inside your current Flutter SDK checkout at D:\flutter. Consider adding D:\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (3 days ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (11 Pro 64-bit, 24H2, 2009) [3.2s]

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0) [2.5s]
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: C:\Program Files\Microsoft\jdk-17.0.13.11-hotspot\bin\java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment Microsoft-10376486 (build 17.0.13+11-LTS)
    • All Android licenses accepted.

[√] Chrome - develop for the web [146ms]
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.9) [144ms]
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2023.2) [31ms]
    • Android Studio at C:\Program Files\Android\Android Studio 2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2024.2) [29ms]
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12508038-b607.1)

[√] VS Code (version 1.97.2) [29ms]
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.104.0

[√] Connected device (4 available) [418ms]
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.26100.3194]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 133.0.6943.59
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 132.0.2957.140

[√] Network resources [758ms]
    • All expected network resources are available.

```

</details>

**Comment by maheshj01** [comment]
@giorgio79 Can you please share your projects pubspec.yaml? Also Do you have more stack traces from play console?

**Comment by giorgio79** [comment]
Thanks @maheshj01 here is my pubspec and attaching full log from Google Play

```
name: cashtic
description: A new Flutter application.
publish_to: none
version: 6.3.88+368

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_place_picker_mb:
    git:
      url: https://github.com/giorgio79/google_maps_place_picker_mb
      ref: master
  nordigen_integration:
    git:
      url: https://github.com/giorgio79/nordigen_integration
      ref: main
  flutter_icons:
    git:
      url: https://github.com/giorgio79/flutter-icons.git
      ref: master
  geoflutterfire:
    git:
      url: https://github.com/giorgio79/geoflutterfire
      ref: master
  geocoder2:
    git:
      url: https://github.com/giorgio79/geocoder2
      ref: main
  weekday_selector:
    git:
      url: https://github.com/smaho-engineering/weekday_selector.git
      ref: e9c604a8cabb04ea3a169c3379c270c59810e4b0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.3
  crypto: ^3.0.6
  duration: ^4.0.3
  firebase_analytics: ^11.4.2
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.2
  firebase_messaging: ^15.2.2
  firebase_storage: ^12.4.2
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_facebook_auth: ^7.1.1
  flutter_firebase_chat_core: ^1.6.8
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_rating_bar: ^4.0.1
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  glob: ^2.1.3
  google_maps_flutter: ^2.10.0
  google_maps_flutter_android: ^2.14.12
  google_maps_flutter_platform_interface: ^2.10.0
  google_maps_flutter_web: ^0.5.10
  google_mobile_ads: ^5.3.1
  google_sign_in: ^6.2.2
  http: ^1.3.0
  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.3.21
  in_app_review: ^2.0.10
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mobile_number: ^3.0.0
  numberpicker: ^2.1.2
  open_route_service: ^1.2.7
  pin_code_fields: ^8.0.1
  rxdart: ^0.28.0
  search_choices: ^2.3.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.1
  sign_button: ^2.0.6
  sign_in_with_apple: ^6.1.4
  simple_icons: ^10.1.3
  translations_cleaner: ^0.0.5
  url_launcher: ^6.3.1
  app_links: ^6.3.3
  uuid: ^4.5.1
  l10n_currencies: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "lib/images/icon-ios.png"
  image_path_android: "lib/images/icon-android.png"

dev_dependencies:
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  dependency_validator: ^5.0.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - path: lib/images/
    - path: lib/images/currency/
    - path: lib/models/


```

[stacktrace.log](https://github.com/user-attachments/files/18808251/stacktrace.log)
