### ISSUE TITLE
Problem loading multiple font styles on iOS

### ISSUE THREAD

**Issue by steniooliv** [flutter/flutter#163699]
I have an app with the Helvetica font, and I need to use weights of 400 and 500.
I have the fonts added to a Design System and when I load them, only the Regular format (w400) is displayed. This error only happens on iOS.

When I build on Android, both styles are loaded correctly.
The test was done on both Simulators/Emulators and physical devices, and both gave the same result.

Below is a screenshot on iOS and Android respectively, and you can see the difference in headline 2 and 3, which have the same size, but h2 with w500 and h3 with w400.

<div>
  iOS
  <img width=200 src=https://github.com/user-attachments/assets/d989a01c-9e83-4632-80bf-c776747f6fc4/>
  Android
  <img width=200 src=https://github.com/user-attachments/assets/f9776f19-b034-4cfb-8e3e-115dc253e19c/>
</div>

</br>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3.1 24D70 darwin-arm64, locale en-BR) [1,483ms]
    • Flutter version 3.29.0 on channel stable at /Users/stenio/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (9 days ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [3.4s]
    • Android SDK at /Users/stenio/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/stenio/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1,666ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [12ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1) [11ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.97.2) [10ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.104.0

[✓] Connected device (3 available) [7.6s]
    • iPhone de Stenio (mobile)       • 00008030-001228EE11B8C02E • ios            • iOS 18.2.1
      22C161
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.3.1
      24D70 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome
      133.0.6943.99

[✓] Network resources [377ms]
    • All expected network resources are available.

• No issues found!
```
</details>

</br>

<details>
<summary>Design System pubspec.yaml assets</summary>

```yaml
flutter:
  assets:
    - lib/assets/images/png/
    - lib/assets/images/svg/

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: lib/assets/fonts/HelveticaNeue-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/HelveticaNeue-Medium.ttf
          weight: 500

    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-VariableFont.ttf
          weight: 700
```
</details>

</br>

<details>
<summary>App pubspec.yaml assets</summary>

```yaml
flutter:
  uses-material-design: true

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: packages/design_system/assets/fonts/HelveticaNeue-Regular.ttf
          weight: 400
        - asset: packages/design_system/assets/fonts/HelveticaNeue-Medium.ttf
          weight: 500
          
    - family: Inter
      fonts:
        - asset: packages/design_system/assets/fonts/Inter-VariableFont.ttf
          weight: 700
```
</details>

</br>

<details>
<summary>👎 Not Good Solution</summary>

```yaml
fonts:
    - family: Helvetica Neue
      fonts:
        - asset: lib/assets/fonts/HelveticaNeue-Regular.ttf
          weight: 400

    - family: Helvetica Neue Medium
      fonts:
        - asset: lib/assets/fonts/HelveticaNeue-Medium.ttf
          weight: 500

    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-VariableFont.ttf
          weight: 700
```
</details>
