### ISSUE TITLE
cannot find symbol       flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin());

### ISSUE THREAD

**Issue by PindoliaRajshree** [flutter/flutter#163820]
### Steps to reproduce

```
cannot find symbol
      flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin());
                                                                              ^
  symbol:   class FlutterFirebaseMessagingPlugin
  location: package io.flutter.plugins.firebase.messaging
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

### Expected results

I faced this error while creating app bundle. Please help me with these. While debugging, Its not coming

### Actual results

I want to successfully create app bundle

### Code sample

```yaml
name: support
description: Support

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.5.6+53

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # A
  agora_rtc_engine: ^6.3.2
  adaptive_theme: ^3.3.0
  avatar_glow: ^2.0.2
  audioplayers: ^4.1.0
  agora_chat_sdk: ^1.2.0

  # B

  # C
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.1
  carousel_slider: ^4.2.1
  card_swiper: ^3.0.1
  camera: ^0.10.5+9
  comment_box: ^0.0.18
  cached_video_player_plus: ^3.0.3

  # D
  dio: ^5.2.1+1
  device_info_plus: ^9.0.2
  dotted_border: ^2.1.0

  # E
  extended_image: ^8.0.2

  # F
  firebase_core: ^2.4.1
  firebase_auth: ^4.4.2
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^14.7.10
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^15.0.0
  firebase_crashlytics: ^3.0.9
  firebase_storage: ^11.0.10
  fluttertoast: ^8.2.1
  flutter_windowmanager: ^0.2.0
  flutter_phoenix: ^1.1.1
  flutter_ringtone_player: ^3.2.0
  file_picker: ^6.1.1
  flutter_staggered_animations: ^1.1.1
  firebase_analytics: ^10.8.0
  flutter_reaction_button: ^3.0.0+3
  floating: ^2.0.2
  flutter_cashfree_pg_sdk: ^2.0.18+21
  fcm_channels_manager: ^0.0.7
  flutter_switch: ^0.3.2
#  flutter_foreground_task: ^8.17.0

  # G
  google_fonts: ^4.0.3
  get: ^4.6.5
  get_time_ago: ^1.2.4
  google_sign_in: ^6.1.5
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1

  # H
  http: ^0.13.5

  # I
  intl_phone_field: ^3.1.0
  image_picker: ^1.0.0
  intl: ^0.18.1
  in_app_review: ^2.0.8
  image_cropper: ^4.0.1
  image_gallery_saver: ^2.0.3
  in_app_update: ^4.2.3

  # J
  just_audio: ^0.9.32

  #L
  loading_animation_widget: ^1.2.1

  #N
  #O

  # P
  pin_code_fields: ^8.0.1
  permission_handler: ^10.2.0
  percent_indicator: ^4.2.3
  pull_to_refresh: ^2.0.0
  persistent_bottom_nav_bar: ^5.0.2

  # R
  rive: ^0.13.4

  # S
  shared_preferences: ^2.1.0
  stop_watch_timer: ^2.0.0
  shimmer: ^3.0.0
  share_plus: ^7.0.2
  swipe_to: ^1.0.2
  scratcher: ^2.3.0
  story_view: ^0.16.0
  syncfusion_flutter_charts: ^20.4.49
  syncfusion_flutter_gauges:

  #  T
  timeago_flutter: ^3.4.0

  #  U
  url_launcher: ^6.1.10

  # V
  vibration: ^1.8.4
  video_player: ^2.7.2
  video_thumbnail: ^0.5.3

  #  W

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/mood/
    - assets/sound/
    - assets/emoji/
```

Pubspec.yaml

#Flutter Wrapper

```pro
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.google.firebase.** { *; }
-keep class com.hyphenate.** {*;}
-dontwarn  com.hyphenate.**
```

Proguard-rules.pro

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.support">

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

    <uses-permission
        android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_PRIVILEGED" />
    <uses-permission
        android:name="android.permission.BLUETOOTH_SCAN" />

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
<!--    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />-->
    <uses-permission android:name="android.permission.INTERNET" />

    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<!--    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />-->

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-permission android:name="android.hardware.sensor.proximity" />

    <uses-feature
        android:name="android.hardware.microphone"
        android:required="true" />
    <uses-feature
        android:name="android.hardware.bluetooth"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.bluetooth_le"
        android:required="false" />

    <uses-permission
        android:name="android.permission.READ_PRIVILEGED_PHONE_STATE"
        tools:ignore="ProtectedPermissions" />
    <uses-permission android:name="com.google.android.gms.permission.AD_ID" />

    <application
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:label="Support"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
        tools:node="merge"
        tools:replace="android:label">
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:exported="true"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:supportsPictureInPicture="true"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            <!--
            Specifies an Android theme to apply to this Activity as soon as
            the Android process has started. This theme is visible to the user
            while the Flutter UI initializes. After that, this theme continues
            to determine the Window background behind the Flutter UI.
            -->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />

            <meta-data
                android:name="com.google.android.gms.wallet.api.enable"
                android:value="true" />

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <meta-data
                android:name="com.google.firebase.messaging.default_notification_channel_id"
                android:resource="@drawable/ic_launcher" />

            <!--			<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />-->
            <!--			<intent-filter android:autoVerify="true">-->
            <!--				<action android:name="android.intent.action.VIEW" />-->
            <!--				<category android:name="android.intent.category.DEFAULT" />-->
            <!--				<category android:name="android.intent.category.BROWSABLE" />-->
            <!--				<data android:scheme="http" android:host="supportletstalk.com" />-->
            <!--				<data android:scheme="https" android:host="supportletstalk.com" />-->
            <!--			</intent-filter>-->


        </activity>
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />

        <!--
        Don't delete the meta-data below.
        This is used by the Flutter tool to generate GeneratedPluginRegistrant.java
        -->
<!--        <service-->
<!--            android:name=".MyForegroundService"-->
<!--            android:exported="true"-->
<!--            android:permission="android.permission.FOREGROUND_SERVICE">-->
<!--            <intent-filter>-->
<!--                <action android:name="com.example.support.MyForegroundService"/>-->
<!--            </intent-filter>-->
<!--        </service>-->

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />
        <meta-data
            android:name="com.facebook.sdk.ClientToken"
            android:value="@string/facebook_client_token" />
    </application>
</manifest>
```

Android manifest.xml

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
