### ISSUE TITLE
Use `pubspec_overrides.yaml` in pathified actions?

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#164222]
Dart allows adding "dependency overrides" without modifying the original pubspec.yaml, by adding a "pubspec_overrides.yaml" file next to it, for example:

```yaml
# pubspec_overrides.yaml
dependency_overrides:
  package: ...
```

(The only docs I can find about this feature is here: https://dart.dev/tools/pub/workspaces#dependency-overrides-in-a-workspace)

Having a pubspec_overrides file may simplify/reduce the noise in pathified PRs (and also should simplify the "diffing"/"sorting" of pubspecs in our scripts? maybe?)
