### ISSUE TITLE
[url_launcher] Swift Compiler Error (Xcode): Type 'UIApplication' does not conform to protocol 'Launcher'

### ISSUE THREAD

**Issue by nimr77** [flutter/flutter#164477]
### Steps to reproduce
install url launcher 3.6.1

### Error
Couldn't run the mobile app in iOS due an issue in the URL launcher plugin 

error logs 

```
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Type 'UIApplication' does not conform to protocol 'Launcher'
/Users/mac/.pub-cache/hosted/pub.dev/url_launcher_ios-6.3.0/ios/url_launcher_ios/Sources/url_launcher_ios/Launcher.swift:21:0

Uncategorized (Xcode): Command SwiftEmitModule failed with a nonzero exit code
2

Error launching application on iPhone (wireless).
```

### flutter doctor logs 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3.1 24D70 darwin-arm64, locale en-MA)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.97.2)
[✓] Connected device (5 available)
```

### Expected results

the app to be built 

### Actual results

error while building the app on ios 

### Code sample

<details open><summary>Code sample</summary>

```yaml

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  # path_provider: ^2.0.11
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.2.0+3
  # font_awesome_flutter: ^10.3.0
  # google_maps_flutter: ^2.5.1
  # apple_maps_flutter: ^1.2.0
  # flutter_typeahead: ^5.2.0
  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  # autoscale_tabbarview: ^1.0.2
  # flutter_html: ^3.0.0-alpha.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_analytics: ^11.3.6
  google_sign_in: ^6.2.2
  google_sign_in_android: ^6.1.34

  sign_in_with_apple: ^6.1.4
  # dart_jsonwebtoken: ^2.7.1
  flutter_secure_storage: ^9.2.2
  lottie: ^3.3.0
  # sprintf: "^7.0.0"
  # share_plus: ^9.0.0
  # uni_links: ^0.5.1
  device_info_plus: ^11.2.0
  flutter_svg: ^2.0.16
  pay: ^2.0.0
  # scrollable_positioned_list: ^0.3.5
  # label_marker: ^1.0.1
  connectivity_plus: ^6.1.1
  modal_bottom_sheet: ^3.0.0
  syncfusion_flutter_datepicker: ^28.1.33
  colorize_text_avatar:
    git:
      url: https://github.com/nimr77/colorize-text-avatar
  firebase_remote_config: ^5.2.0
  flutter_widget_from_html_core: ^0.15.2
  # flutter_staggered_grid_view: ^0.7.0
  # sentry_flutter: ^7.4.1
  url_launcher: ^6.3.1
  in_app_review: ^2.0.10
  package_info_plus: ^8.1.2
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  # flutter_inappwebview:
  #   git:
  #     url: https://github.com/vixez/flutter_inappwebview.git
  #     ref: fix-xcode-17
  # widget_zoom: ^0.0.4
  # like_button: ^2.0.5
  sizer: ^3.0.5
  webview_flutter: ^4.10.0
  firebase_crashlytics: ^4.2.0

  # dropdown_search: ^5.0.6
  # visibility_detector: ^0.4.0+2
  # shimmer: ^3.0.0
  firebase_messaging: ^15.1.6
  # flutter_local_notifications: ^17.0.0
  # path: ^1.8.3
  # sentry_dart_plugin: ^1.0.0
  get_it: ^8.0.3
  logger: ^2.5.0
  flutter_native_splash: ^2.4.3
  dio: ^5.7.0
  go_router: ^14.6.2
  animations: ^2.0.11
  devicelocale: ^0.8.1
  alert_banner: ^1.0.1
  flutter_animate: ^4.5.2
  gaimon: ^1.4.0
  syncfusion_flutter_sliders: ^28.1.33
  syncfusion_flutter_core: ^28.1.33
  # fl_chart: ^0.66.2
  # flutter_map: ^6.1.0
  # flutter_map_cache: ^1.5.0
  card_swiper: ^3.0.1
  readmore: ^3.0.0
  html_unescape: ^2.0.0
  sliver_tools: ^0.2.12
  string_validator: ^1.1.0
  adaptive_dialog: ^2.3.0
  validated: ^2.0.0
  auth_buttons: ^3.0.3
  # flutter_map_animations: ^0.6.0
  visibility_detector: ^0.4.0+2
  # swipeable_page_route: ^0.4.4
  swipeable_page_route: ^0.4.7
  # fluster:
  #   git:
  #     url: https://github.com/nimr77/fluster.git
  # flutter_map_marker_cluster: any
  # crypto: ^3.0.3
  # flutter_inappwebview: ^6.0.0
  # vector_map_tiles: ^7.3.1
  apple_maps_flutter:
    git:
      url: https://github.com/nimr77/apple_maps_flutter
  country_flags: ^3.1.0
  loading_animation_widget: ^1.3.0
  app_settings: ^5.1.1
  app_links: ^6.3.3
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  zoom_widget: ^2.0.1
  google_maps_flutter: ^2.10.0
  device_region: ^1.4.0
  country_ip: ^3.0.0

  flutter_native_html_to_pdf: ^1.0.1
  share_plus: ^10.1.3
  flutter_styled_toast: ^2.2.1
  flutter_keyboard_visibility: ^6.0.0
  glass: ^2.0.0+2
  quickalert: ^1.1.0
  sentry: ^8.11.1
  sentry_logging: ^8.11.1
  logging: ^1.3.0
  sentry_dio: ^8.11.1
  firebase_performance: ^0.10.0+11
  # google_mlkit_text_recognition: ^0.13.0
  # camera: ^0.11.0+2
  flutter_credit_card_scanner: ^0.11.9
  adyen_checkout: ^1.2.0
  credit_card_validator: ^2.1.0
  font_awesome_icon_class: ^0.0.6
  credit_card_type_detector: ^3.0.0
  onesignal_flutter:
    git:
      url: https://github.com/milansurelia/OneSignal-Flutter-SDK.git
  cloud_firestore: ^5.6.0
  retry: ^3.1.2
  intl_utils: ^2.8.10
  # flutter_clarity: ^1.0.0+3
  # permission_handler: ^11.3.1
  # ml_card_scanner: ^0.2.0
  # ml_card_scanner:
  #   path: /Users/mac/MyProjects/ml_card_scanner
  # card_scanner:
  #   path: /Users/mac/MyProjects/card-scanner-flutter
  # google_maps_cluster_manager: ^3.1.0

# flutter_icons:
#   #  image_path: "assets/images/icon-128x128.png"
#   image_path_android: "assets/images/icon-710x599-android.png"
#   image_path_ios: "assets/images/icon-1024x1024.png"
#   android: true # can specify file name here e.g. "ic_launcher"
#   ios: true # can specify file name here e.g. "My-Launcher-Icon"
#   adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
#   adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   remove_alpha_ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/cards/
    - assets/icons/langs/
    - assets/icons/tripadvisor/
    - assets/icons/amunities/
    - assets/json/
    - assets/animations/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: CentraNo2
      fonts:
        - asset: assets/fonts/CentraNo2-Book.ttf
        - asset: assets/fonts/CentraNo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/CentraNo2-Extrabold.ttf
          weight: 900
          # style: italic
    # - family: RobotoMono
    #   fonts:
    #     - asset: assets/fonts/RobotoMono-Regular.ttf
    #     - asset: assets/fonts/RobotoMono-Bold.ttf
    #       weight: 700

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: false
  project: flutter-mobile-app
  org: prestigia
  # auth_token: ...
  # release: com.prestigia.ltd@2.0.6+35
  wait_for_processing: true
  log_level: error
  commits: auto
  ignore_missing: true
flutter_intl:
  enabled: true

```

</details>

**Comment by maheshj01** [comment]
Hey @nimr77, Thanks for filing the issue. I added all your dependencies in pubspec.yaml and I was able to build the ios app

- create a new sample project
- added all your dependencies
- set minimum deployment target to 15.5
- flutter run

<details>
<summary>pubspec.yaml</summary>

```yaml
name: sample_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  # path_provider: ^2.0.11
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.2.0+3
  # font_awesome_flutter: ^10.3.0
  # google_maps_flutter: ^2.5.1
  # apple_maps_flutter: ^1.2.0
  # flutter_typeahead: ^5.2.0
  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  # autoscale_tabbarview: ^1.0.2
  # flutter_html: ^3.0.0-alpha.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_analytics: ^11.3.6
  google_sign_in: ^6.2.2
  google_sign_in_android: ^6.1.34

  sign_in_with_apple: ^6.1.4
  # dart_jsonwebtoken: ^2.7.1
  flutter_secure_storage: ^9.2.2
  lottie: ^3.3.0
  # sprintf: "^7.0.0"
  # share_plus: ^9.0.0
  # uni_links: ^0.5.1
  device_info_plus: ^11.2.0
  flutter_svg: ^2.0.16
  pay: ^2.0.0
  # scrollable_positioned_list: ^0.3.5
  # label_marker: ^1.0.1
  connectivity_plus: ^6.1.1
  modal_bottom_sheet: ^3.0.0
  syncfusion_flutter_datepicker: ^28.1.33
  colorize_text_avatar:
    git:
      url: https://github.com/nimr77/colorize-text-avatar
  firebase_remote_config: ^5.2.0
  flutter_widget_from_html_core: ^0.15.2
  # flutter_staggered_grid_view: ^0.7.0
  # sentry_flutter: ^7.4.1
  url_launcher: ^6.3.1
  in_app_review: ^2.0.10
  package_info_plus: ^8.1.2
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  # flutter_inappwebview:
  #   git:
  #     url: https://github.com/vixez/flutter_inappwebview.git
  #     ref: fix-xcode-17
  # widget_zoom: ^0.0.4
  # like_button: ^2.0.5
  sizer: ^3.0.5
  webview_flutter: ^4.10.0
  firebase_crashlytics: ^4.2.0

  # dropdown_search: ^5.0.6
  # visibility_detector: ^0.4.0+2
  # shimmer: ^3.0.0
  firebase_messaging: ^15.1.6
  # flutter_local_notifications: ^17.0.0
  # path: ^1.8.3
  # sentry_dart_plugin: ^1.0.0
  get_it: ^8.0.3
  logger: ^2.5.0
  flutter_native_splash: ^2.4.3
  dio: ^5.7.0
  go_router: ^14.6.2
  animations: ^2.0.11
  devicelocale: ^0.8.1
  alert_banner: ^1.0.1
  flutter_animate: ^4.5.2
  gaimon: ^1.4.0
  syncfusion_flutter_sliders: ^28.1.33
  syncfusion_flutter_core: ^28.1.33
  # fl_chart: ^0.66.2
  # flutter_map: ^6.1.0
  # flutter_map_cache: ^1.5.0
  card_swiper: ^3.0.1
  readmore: ^3.0.0
  html_unescape: ^2.0.0
  sliver_tools: ^0.2.12
  string_validator: ^1.1.0
  adaptive_dialog: ^2.3.0
  validated: ^2.0.0
  auth_buttons: ^3.0.3
  # flutter_map_animations: ^0.6.0
  visibility_detector: ^0.4.0+2
  # swipeable_page_route: ^0.4.4
  swipeable_page_route: ^0.4.7
  # fluster:
  #   git:
  #     url: https://github.com/nimr77/fluster.git
  # flutter_map_marker_cluster: any
  # crypto: ^3.0.3
  # flutter_inappwebview: ^6.0.0
  # vector_map_tiles: ^7.3.1
  apple_maps_flutter:
    git:
      url: https://github.com/nimr77/apple_maps_flutter
  country_flags: ^3.1.0
  loading_animation_widget: ^1.3.0
  app_settings: ^5.1.1
  app_links: ^6.3.3
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  zoom_widget: ^2.0.1
  google_maps_flutter: ^2.10.0
  device_region: ^1.4.0
  country_ip: ^3.0.0

  flutter_native_html_to_pdf: ^1.0.1
  share_plus: ^10.1.3
  flutter_styled_toast: ^2.2.1
  flutter_keyboard_visibility: ^6.0.0
  glass: ^2.0.0+2
  quickalert: ^1.1.0
  sentry: ^8.11.1
  sentry_logging: ^8.11.1
  logging: ^1.3.0
  sentry_dio: ^8.11.1
  firebase_performance: ^0.10.0+11
  # google_mlkit_text_recognition: ^0.13.0
  # camera: ^0.11.0+2
  flutter_credit_card_scanner: ^0.11.9
  adyen_checkout: ^1.2.0
  credit_card_validator: ^2.1.0
  font_awesome_icon_class: ^0.0.6
  credit_card_type_detector: ^3.0.0
  onesignal_flutter:
    git:
      url: https://github.com/milansurelia/OneSignal-Flutter-SDK.git
  cloud_firestore: ^5.6.0
  retry: ^3.1.2
  intl_utils: ^2.8.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  shaders:
    - lib/test_shader.frag

  assets:
    - assets/

```
</details> 


<details>
<summary>logs</summary>

```console
(.venv) mahesh@MacBook-Pro-10 sample_app % cd ios
(.venv) mahesh@MacBook-Pro-10 ios % pod install
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '11.8.0' defined in 'firebase_core'
firebase_analytics: Using Firebase SDK version '11.8.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '11.8.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.8.0' defined in 'firebase_core'
Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this error is unexpected, try running flutterfire configure again.
firebase_crashlytics: Using Firebase SDK version '11.8.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '11.8.0' defined in 'firebase_core'
firebase_performance: Using Firebase SDK version '11.8.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '11.8.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '11.8.0' defined in 'firebase_core'
Downloading dependencies
Installing Adyen (5.15.0)
Installing Adyen3DS2 (2.4.2)
Installing AdyenNetworking (2.0.0)
Installing AppAuth (1.7.6)
Installing BoringSSL-GRPC (0.0.36)
Installing Firebase (11.8.0)
Installing FirebaseABTesting (11.8.0)
Installing FirebaseAnalytics (11.8.0)
Installing FirebaseAppCheckInterop (11.8.0)
Installing FirebaseAuth (11.8.1)
Installing FirebaseAuthInterop (11.8.0)
Installing FirebaseCore (11.8.1)
Installing FirebaseCoreExtension (11.8.0)
Installing FirebaseCoreInternal (11.8.0)
Installing FirebaseCrashlytics (11.8.0)
Installing FirebaseFirestore (11.8.0)
Installing FirebaseFirestoreInternal (11.8.0)
Installing FirebaseInstallations (11.8.0)
Installing FirebaseMessaging (11.8.0)
Installing FirebasePerformance (11.8.0)
Installing FirebaseRemoteConfig (11.8.0)
Installing FirebaseRemoteConfigInterop (11.9.0)
Installing FirebaseSessions (11.8.0)
Installing FirebaseSharedSwift (11.8.0)
Installing FirebaseStorage (11.8.0)
Installing Flutter (1.0.0)
Installing GTMAppAuth (4.1.1)
Installing GTMSessionFetcher (3.5.0)
Installing Google-Maps-iOS-Utils (6.1.0)
Installing GoogleAppMeasurement (11.8.0)
Installing GoogleDataTransport (10.1.0)
Installing GoogleMLKit (7.0.0)
Installing GoogleMaps (9.3.0)
Installing GoogleSignIn (7.1.0)
Installing GoogleToolboxForMac (4.2.1)
Installing GoogleUtilities (8.0.2)
Installing MLImage (1.0.0-beta6)
Installing MLKitCommon (12.0.0)
Installing MLKitTextRecognition (5.0.0)
Installing MLKitTextRecognitionCommon (4.0.0)
Installing MLKitVision (8.0.0)
Installing OneSignalXCFramework (5.2.9)
Installing PromisesObjC (2.4.0)
Installing PromisesSwift (2.4.0)
Installing RecaptchaInterop (100.0.0)
Installing abseil (1.20240116.2)
Installing adyen_checkout (0.0.1)
Installing app_links (0.0.2)
Installing app_settings (5.1.1)
Installing apple_maps_flutter (0.0.1)
Installing apple_vision_recognize_text (0.0.4)
Installing camera_avfoundation (0.0.1)
Installing cloud_firestore (5.6.5)
Installing connectivity_plus (0.0.1)
Installing device_info_plus (0.0.1)
Installing device_region (0.0.1)
Installing devicelocale (0.0.1)
Installing firebase_analytics (11.4.4)
Installing firebase_auth (5.5.1)
Installing firebase_core (3.12.1)
Installing firebase_crashlytics (4.3.4)
Installing firebase_messaging (15.2.4)
Installing firebase_performance (0.10.1-4)
Installing firebase_remote_config (5.4.2)
Installing firebase_storage (12.4.4)
Installing flutter_credit_card_scanner (0.0.1)
Installing flutter_keyboard_visibility (0.0.1)
Installing flutter_native_html_to_pdf (0.0.1)
Installing flutter_native_splash (2.4.3)
Installing flutter_secure_storage (6.0.0)
Installing gRPC-C++ (1.65.5)
Installing gRPC-Core (1.65.5)
Installing gaimon (0.0.1)
Installing geolocator_apple (1.2.0)
Installing google_maps_flutter_ios (0.0.1)
Installing google_mlkit_commons (0.9.0)
Installing google_mlkit_text_recognition (0.14.0)
Installing google_sign_in_ios (0.0.1)
Installing image_picker_ios (0.0.1)
Installing in_app_review (2.0.0)
Installing leveldb-library (1.22.6)
Installing nanopb (3.30910.0)
Installing onesignal_flutter (5.2.9)
Installing package_info_plus (0.4.5)
Installing path_provider_foundation (0.0.1)
Installing pay_ios (0.0.1)
Installing share_plus (0.0.1)
Installing shared_preferences_foundation (0.0.1)
Installing sign_in_with_apple (0.0.1)
Installing sqflite_darwin (0.0.4)
Installing url_launcher_ios (0.0.1)
Installing webview_flutter_wkwebview (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 43 dependencies from the Podfile and 92 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
(.venv) mahesh@MacBook-Pro-10 ios % cd ..
(.venv) mahesh@MacBook-Pro-10 sample_app % flutter run
Could not load custom device from config index 0: Expected enabled to be a boolean.
Launching lib/main.dart on iPhone 16 Pro in debug mode...
Running pod install...                                             27.4s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        38.8s
Xcode build done.                                           617.9s
Syncing files to device iPhone 16 Pro...                           251ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone 16 Pro is available at: http://127.0.0.1:62290/HNeKDbx7bHI=/
The Flutter DevTools debugger and profiler on iPhone 16 Pro is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:62290/HNeKDbx7bHI=/

```
</details> 


<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.29.0, on macOS 15.1.1 24B2091 darwin-arm64, locale en-US) [769ms]
    • Flutter version 3.29.0 on channel stable at /Users/mahesh/Development/flutter
    ! Warning: `flutter` on your path resolves to /Users/mahesh/Development/flutter_master/bin/flutter, which is not
      inside your current Flutter SDK checkout at /Users/mahesh/Development/flutter. Consider adding
      /Users/mahesh/Development/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/mahesh/Development/flutter_master/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/mahesh/Development/flutter. Consider adding
      /Users/mahesh/Development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (3 weeks ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0) [3.2s]
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0) [1,540ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [132ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1) [131ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1) [130ms]
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.96.2) [21ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available) [7.4s]
    • iPhone 16 Pro (mobile)          • 34497AEA-B6B0-4F79-99A3-6E40007745A3 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.1.1 24B2091
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.1.1 24B2091
      darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome
      131.0.6778.265

[✓] Network resources [407ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details> 

Please run the following commands in order and share the output in a text format

```bash
flutter pub upgrade
flutter clean
flutter pub get
cd ios

# delete podfile.lock
pod install
cd ..
flutter run -v
```
