### ISSUE TITLE
DVTDeviceOperation: Encountered a build number "" that is incompatible with DVTBuildVersion.

### ISSUE THREAD

**Issue by dmiedev** [flutter/flutter#164842]
### Steps to reproduce

Unfortunately I cannot provide exact steps to reproduce, but the issue appeared after upgrading Flutter, CocoaPods, and app dependencies.

### Expected results

Flutter run and build work.

### Actual results

Flutter run nor build work. 
I get this error message. See logs section.
I have tried downgrading Flutter, CocoaPods, upgrading iOS SDK, allowing modular imports, clearing caches (Flutter, Xcode), downgrading packages to the previous version... Nothing helped. I'm completely stuck.
Created a new sample app with the same dependencies, it builds without problems.
I guess the issue may be in the Xcode project configuration or Podfile or elsewhere, but I don't know where. 

### Code sample

<details open><summary>Code sample</summary>

Please let me know what other files I should provide...

Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '16.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'PhoneNumberKit/PhoneNumberKitCore', :git => 'https://github.com/marmelroy/PhoneNumberKit', :tag => '3.8.0'
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  # target 'RunnerTests' do
  #   inherit! :search_paths
  # end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_LOCATION=1',
        'PERMISSION_NOTIFICATIONS=1',
      ]
    end
  end
end

```

pubspec.yaml

```yaml
name: app
description: Mobile App
version: 2.17.1+117
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auth_repository:
    path: packages/auth_repository
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  bloc_event_transformers: ^1.0.1
  cached_network_image: ^3.2.3
  collection: ^1.18.0
  company_repository: 
    path: packages/company_repository
  confetti: ^0.7.0
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_dynamic_links: ^6.0.8
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_google_places_sdk: ^0.3.6
  flutter_libphonenumber: ^2.1.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  geolocator: ^11.0.0
  go_router: ^8.1.0
  google_maps_flutter: ^2.3.1
  in_app_notification: ^1.1.2
  in_app_review: ^2.0.10
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.3+1
  meta: ^1.9.1
  mobile_scanner: ^6.0.1
  modal_bottom_sheet: ^3.0.0
  offer_repository:
    path: packages/offer_repository
  pass_repository:
    path: packages/pass_repository
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  region_repository:
    path: packages/region_repository
  replay_bloc: ^0.2.4
  shared_preferences: ^2.1.2
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  uneeqly_api:
    path: packages/uneeqly_api
  uneeqly_ui:
    path: packages/uneeqly_ui
  url_launcher: ^6.1.12
  video_player: ^2.9.2

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  translations_cleaner: ^0.0.5
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - graphics/
    - assets/

  fonts:
    - family: Poppins
      fonts:
      - asset: fonts/Poppins-Thin.ttf
        weight: 100
      - asset: fonts/Poppins-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: fonts/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: fonts/Poppins-Light.ttf
        weight: 300
      - asset: fonts/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: fonts/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: fonts/Poppins-Black.ttf
        weight: 900
      - asset: fonts/Poppins-BlackItalic.ttf
        weight: 900
        style: italic
    - family: Cocon Pro
      fonts:
      - asset: fonts/Cocon-Pro.otf
        weight: 400
      - asset: fonts/Cocon-Pro-Bold.otf
        weight: 700
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main_production.dart on excentrist (wireless) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: QY7RJCY9KV
Xcode build done.                                           22,1s
Failed to build iOS app
Could not build the precompiled application for the device.
Error output from Xcode build:
↳
    2025-03-08 14:04:00.190 xcodebuild[15917:195810]  DVTDeviceOperation: Encountered a build number "" that is incompatible with DVTBuildVersion.
    2025-03-08 14:04:00.753 xcodebuild[15917:195805] [MT] DVTDeviceOperation: Encountered a build number "" that is incompatible with DVTBuildVersion.
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/jf/rw9twt2n5m50mbz2f6zcw5jm0000gn/T/flutter_tools.AAoIL2/flutter_ios_build_temp_dirtTLXlg/temporary_xcresult_bundle

    ld: warning: no platform load command found in '/Users/excentrist/Uneeqly/uneeqly_app/ios/Pods/MLKitBarcodeScanning/Frameworks/MLKitBarcodeScanning.framework/MLKitBarcodeScanning', assuming: iOS
    /Users/excentrist/Library/Developer/Xcode/DerivedData2/Runner-frqsljsrraldvfaxmqtsafrlekfh/Build/Intermediates.noindex/Runner.build/Debug-production-iphoneos/Runner.build/Script-AECCFD5EAC884B94A8F767B7.sh: line 5: flutterfire: command not found
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleToolboxForMac-GoogleToolboxForMac_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'PromisesObjC-FBLPromises_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'PhoneNumberKit-PhoneNumberKitPrivacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'url_launcher_ios-url_launcher_ios_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'permission_handler_apple-permission_handler_apple_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'shared_preferences_foundation-shared_preferences_foundation_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'nanopb-nanopb_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'OrderedSet-OrderedSet_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'sms_autofill' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleUtilities-GoogleUtilities_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GooglePlaces-GooglePlacesResources' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleMaps-GoogleMapsResources' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'mobile_scanner-mobile_scanner_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'geolocator_apple-geolocator_apple_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'flutter_native_splash-flutter_native_splash_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GTMSessionFetcher-GTMSessionFetcher_Core_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'wakelock_plus-thermal' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'video_player_avfoundation-video_player_avfoundation_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'unique_identifier' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'sqflite_darwin-sqflite_darwin_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'path_provider_foundation-path_provider_foundation_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'package_info_plus-package_info_plus_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'in_app_review-in_app_review_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'flutter_secure_storage' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'permission_handler_apple' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'nanopb' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'google_maps_flutter_ios-google_maps_flutter_ios_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'url_launcher_ios' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'PhoneNumberKit' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'OrderedSet' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'shared_preferences_foundation' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'PromisesObjC' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleUtilities' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleToolboxForMac-GoogleToolboxForMac_Logger_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'wakelock_plus' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'sqflite_darwin' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'video_player_avfoundation' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'package_info_plus' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'path_provider_foundation' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'in_app_review' from project 'Pods')
    warning: no rule to process file '/Users/excentrist/.pub-cache/hosted/pub.dev/in_app_review-2.0.10/ios/in_app_review/Sources/in_app_review/PrivacyInfo.xcprivacy' of type 'text.xml' for architecture 'arm64' (in target 'in_app_review' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'geolocator_apple' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'flutter_native_splash' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GTMSessionFetcher' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'libphonenumber_plugin' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'flutter_libphonenumber_ios-flutter_libphonenumber_ios' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'flutter_inappwebview_ios-flutter_inappwebview_ios_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'firebase_messaging-firebase_messaging_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleToolboxForMac' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleDataTransport-GoogleDataTransport_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'Google-Maps-iOS-Utils' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseCoreInternal-FirebaseCoreInternal_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseCoreInternal' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'flutter_inappwebview_ios' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleDataTransport' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'flutter_libphonenumber_ios' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'mobile_scanner' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'flutter_google_places_sdk_ios' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'google_maps_flutter_ios' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseCore-FirebaseCore_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseCore' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseInstallations-FirebaseInstallations_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseDynamicLinks-FirebaseDynamicLinks_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseInstallations' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseDynamicLinks' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseMessaging-FirebaseMessaging_Privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseMessaging' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'firebase_core' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'firebase_analytics' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'firebase_dynamic_links' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'firebase_messaging' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'Pods-Runner' from project 'Pods')
    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'FlutterFire: "flutterfire bundle-service-file"' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleMaps' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'Firebase' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleAppMeasurement' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'MLKitVision' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'MLImage' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GoogleMLKit' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'MLKitCommon' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'GooglePlaces' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'FirebaseAnalytics' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'Flutter' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'MLKitBarcodeScanning' from project 'Pods')


Error launching application on excentrist (wireless).

Exited (1).


</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.1, on macOS 15.3.1 24D70 darwin-arm64, locale cs-CZ) [440ms]
    • Flutter version 3.29.1 on channel stable at /Users/excentrist/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 09de023485 (8 days ago), 2025-02-28 13:44:05 -0800
    • Engine revision 871f65ac1b
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0) [1 459ms]
    • Android SDK at /Users/excentrist/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [795ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome) [29ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.1) [29ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "17.0.10" 2024-01-16

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.2) [28ms]
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.98.0) [9ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.106.0

[✓] Connected device (3 available) [6,0s]
    • excentrist (wireless) (mobile)  • 00008101-001518C00206001E • ios          • iOS 18.3.1 22D72
    • macOS (desktop)                 • macos                     • darwin-arm64 • macOS 15.3.1 24D70 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin       • macOS 15.3.1 24D70 darwin-arm64
    ! Error: Browsing on the local area network for Dmitry – Apple Watch. Ensure the device is unlocked and discoverable via
      Bluetooth. (code -27)

[✓] Network resources [374ms]
    • All expected network resources are available.

</details>
