### ISSUE TITLE
Swift Compiler Error (Xcode): Default argument value of type 'UIApplication' does not conform to 'Launcher'

### ISSUE THREAD

**Issue by NikhilIfanow** [flutter/flutter#165192]
### Steps to reproduce

```yaml
name: mob_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.39+99

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  http: ^0.13.6 
  date_field: 
  flex_color_picker:
  local_auth: ^2.1.5	
  pin_code_fields: ^8.0.1
  # dropdown_button2: ^1.2.5
  network_info_plus: any
  form_field_validator: ^1.1.0
  cupertino_icons: ^1.0.2
  convert: ^3.0.1
  shared_preferences: ^2.0.13
  localstorage: ^4.0.0+1
  provider: ^6.0.2
  pie_chart: ^5.3.0
  flutter_screenutil: ^5.5.3+2
  # loadmore: ^2.0.1
  # visibility_detector: ^0.2.2
  permission_handler: ^11.0.1 
  intl: any
  # firebase_crashlytics: ^3.3.3
   # firebase_analytics: ^10.4.3
  path_provider: ^2.0.9
  pattern_formatter: any	
  expandable: ^5.0.1
  syncfusion_flutter_charts: any
  page_view_indicators: ^2.0.0
  flutter_localization: ^0.1.11
  dartx: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  url_launcher: ^6.3.1
  loading_animation_widget: ^1.2.0+2
  dotted_border: ^2.0.0+2
  file_picker: ^5.0.1
  image_picker: ^0.8.5+3
  whiteboard: ^0.0.1
  flutter_svg: ^2.0.9
  # flutter_cached_pdfview: ^0.4.1
  carousel_slider: ^5.0.0
  flutter_profile_picture: ^2.0.0
  fl_chart: ^0.55.2
  connectivity_plus: any
  percent_indicator: ^3.4.0
  syncfusion_flutter_pdfviewer:  
  rename_app:
  dio: ^4.0.6
  device_info_plus: ^9.1.1 
  number_to_character:  
  path: 
  flutter_webview_plugin_ios_android: ^0.3.12
  get: ^4.6.5
  flutter_html: 
  package_info_plus: ^4.0.2
  in_app_update:
  launch_review: ^3.0.1
  smooth_page_indicator: ^1.0.1
  page_transition: ^2.0.9
  flutter_typeahead: ^3.1.1
  app_settings: ^5.0.0
  lottie: ^2.3.1
  syncfusion_flutter_sliders: 
  scgateway_flutter_plugin: ^2.4.0+3
  scloans: ^0.1.0+3
  share_plus: ^7.2.1
  open_file: ^3.3.2
  # open_app_file: ^4.0.2
  syncfusion_flutter_datepicker: any
  webview_flutter: ^4.2.0
  app_version_update: ^4.0.1
  flutter_local_notifications: ^16.0.0
  internet_connection_checker: ^0.0.1+4
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.1.0
  timeline_tile: ^2.0.0
  calendar_date_picker2: ^0.5.3
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  html_to_pdf: ^0.8.1
  encrypt: ^5.0.3
  video_player: ^2.8.1
  glowy_borders: ^1.0.2
  carousel_slider_plus: ^7.1.0
  app_links: ^6.2.0
  gif_view: ^0.3.1






  




flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
dev_dependencies:
  flutter_native_splash:
  flutter_test:
    sdk: flutter
  # flutter_localizations: # Add this line
  #   sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/Language/en.json
    - lib/Language/hi.json
    - lib/Language/mr.json
    - lib/Language/gu.json
    - lib/Language/te.json
    - lib/Language/ta.json
    - lib/Language/bn.json
    - lib/Language/ml.json
    - lib/Language/kn.json
    - assets/icons/
    - assets/images/
    - assets/videos/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
    
  fonts:
    - family: Sentient
      fonts:
        - asset: assets/fonts/sentient/Sentient-Regular.otf
        - asset: assets/fonts/sentient/Sentient-Italic.otf
          style: italic
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Regular.otf
        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

this my yaml file

```
# Uncomment this line to define a global platform for your project
platform :ios, '15.5'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'FMDB'
 
end
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
      '$(inherited)',
       # dart: PermissionGroup.camera
      'PERMISSION_CAMERA=1',
      # dart: PermissionGroup.photos
      'PERMISSION_PHOTOS=1',
      # dart: PermissionGroup.mediaLibrary
      # 'PERMISSION_MEDIA_LIBRARY=1',
    ]
      end
    end
  end
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Actual results

when build this application gettng this issue

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>
