### ISSUE TITLE
Impossible to see dependency path of  'dart:mirrors' usage from error message

### ISSUE THREAD

**Issue by olostan** [flutter/flutter#165243]
### Steps to reproduce

After some changes I start seeing "import of dart:mirrors is not supported in the current Dart runtime" message and it was absolutely not understandable which library or code caused that message.

### Expected results

When 'dart:mirrors' is detected, show path of which libraries requested 'dart:mirrors'

### Actual results

when I am launching app I have:
```
[ERROR:flutter/shell/common/shell.cc(115)] Dart Error: error: import of dart:mirrors is not supported in the current Dart runtime
[ERROR:flutter/runtime/dart_isolate.cc(146)] Could not prepare isolate.
[ERROR:flutter/runtime/runtime_controller.cc(557)] Could not create root isolate.
[ERROR:flutter/shell/common/shell.cc(668)] Could not launch engine with configuration.
```

The problem that I can't see which package imported `dart:mirror`. I searched whole workspace for `dart:mirror` but haven't found any.

### Code sample

<details open><summary>Code sample</summary>

my dependencies: 
```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.3
  stream_transform: ^2.1.0
  overlapped_carousel: ^1.0.2
  infinite_carousel: ^1.1.1
  flutter_animate: ^4.5.0
  flutter_custom_carousel: ^0.1.0+1
  flutter_launcher_icons: ^0.14.1
  path: ^1.9.0

  source_gen: any
  build: any
  quickalert: ^1.1.0
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  rxdart: ^0.28.0
  subscription_tracker: ^1.0.1
  flutter_offline: ^4.0.0
  connectivity_plus: ^6.0.5
  loading_animation_widget: ^1.2.1
  audioplayers: ^6.1.0
  retry: ^3.1.2
  flutter_markdown: ^0.7.3+1
  shared_preferences: ^2.3.2
  carousel_slider: ^5.0.0
  cloud_functions: ^5.1.3
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  firebase_storage: ^12.3.7
  sign_in_with_apple: ^6.1.4
  firebase_app_check: ^0.3.2+4
  cached_network_image: ^3.4.1


flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/icon/friendy_main_logo.png"

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.13
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.4
  yaml: ^3.1.2
  logger: ^2.4.0
  analyzer: ^7.3.0
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Just while screen

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone 16 in debug mode...
Xcode build done.                                           37.9s
[ERROR:flutter/shell/common/shell.cc(115)] Dart Error: error: import of dart:mirrors is not supported in the current Dart runtime
[ERROR:flutter/runtime/dart_isolate.cc(146)] Could not prepare isolate.
[ERROR:flutter/runtime/runtime_controller.cc(557)] Could not create root isolate.
[ERROR:flutter/shell/common/shell.cc(668)] Could not launch engine with configuration.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, 3.29.1, on macOS 15.3.1 24D70 darwin-arm64, locale en-US) [252ms]
    • Flutter version 3.29.1 on channel stable at /Users/olostan/code/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 09de023485 (2 weeks ago), 2025-02-28 13:44:05 -0800
    • Engine revision 871f65ac1b
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [853ms]
    • Android SDK at /Users/olostan/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [455ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [8ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.98.2) [7ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.106.0

[✓] Connected device (4 available) [5.6s]
    • iPhone 16 (mobile)              • A6D6D7FD-5032-4446-A429-3FDA1719BC90 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.3.1 24D70 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.3.1 24D70 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 134.0.6998.89

[✓] Network resources [734ms]
    • All expected network resources are available.

• No issues found!
```

</details>
