### ISSUE TITLE
Garbled text appears randomly

### ISSUE THREAD

**Issue by aarjan** [flutter/flutter#165309]
### Steps to reproduce

The app shows garbled text sometimes. 
It is not yet reproducible.
It has been reported by many users, multiple times a day. 

### Expected results

The app should show the texts as normal.

### Actual results

The app shows garbled text sometimes. 
It has been reported by many users, multiple times a day. 
It is not yet reproducible in my device, but has been reported by multiple users.
It works if the app is closed an reopen again.
As you can see in the screenshot, it doesn't show the arrow_forward_ios icon also in the effected list item.

Reported devices:
One plus Nord ce3, Android 14
Redmi note 11

### Code sample

<details open><summary>Code sample</summary>

pubspec.yaml
```yaml
flutter:
  fonts:
    - family: Manrope
      fonts:
        - asset: google_fonts/Manrope-ExtraLight.ttf
        - asset: google_fonts/Manrope-Light.ttf
        - asset: google_fonts/Manrope-Regular.ttf
        - asset: google_fonts/Manrope-Medium.ttf
        - asset: google_fonts/Manrope-SemiBold.ttf
        - asset: google_fonts/Manrope-Bold.ttf
        - asset: google_fonts/Manrope-ExtraBold.ttf

```

I use the fonts like this.
```dart
TextStyle(
    fontFamily: 'Manrope',
    fontWeight: FontWeight.w700,
    color: const Color(0xFF644A73),
    fontSize: 16.sp,
  )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Image](https://github.com/user-attachments/assets/8b5d2405-087c-4ac6-a0ac-8202986e8eca)

![Image](https://github.com/user-attachments/assets/a517b91d-bfa6-4700-b461-4ead5c389ebe)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on Ubuntu 24.04.2 LTS 6.8.0-55-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.98.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>
