### ISSUE TITLE
There's no Desaturate widget

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#166590]
# There's no Desaturate widget

I already searched [here](https://github.com/flutter/flutter/issues?q=is%3Aissue+There's%20no%20Desaturate%20widget) and didn’t find anything that matches.

It's common task in frontend development to desaturate an entire component (disabled variant for example). There's no canonical way to desaturate a Widget in flutter.

---

## pubspec.yaml

<details>

```yaml
name: app
description: mup_app
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1
  context_watch: ^5.1.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_animate: ^4.5.2
  flutter_confetti: ^0.5.1
  in_app_review: ^2.0.10
  infamous_squircle: ^0.2.0
  intl: ^0.20.2
  lottie: ^3.3.1
  nanoid2: ^2.0.1
  progressive_time_picker: ^1.0.3
  pull_down_button: ^0.10.2
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  sprung: ^3.0.1
  typeset: ^2.2.0
  vibration: ^3.1.3
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
```

</details>

## flutter doctor -v

<details>

```
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.3.2 24D2082 darwin-arm64, locale en-US) [131ms]
    • Flutter version 3.29.2 on channel stable at /Users/lukepighetti/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (3 weeks ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✗] Android toolchain - develop for Android devices [89ms]
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [480ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome) [5ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed) [5ms]
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.99.0) [5ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.108.0

[✓] Connected device (3 available) [5.7s]
    • Luke Pighetti’s iPhone (mobile) • 00008140-000E18E43E3B001C • ios          • iOS 18.3.2 22D82
    • macOS (desktop)                 • macos                     • darwin-arm64 • macOS 15.3.2 24D2082 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin       • macOS 15.3.2 24D2082 darwin-arm64

[✓] Network resources [221ms]
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>
