### ISSUE TITLE
Flaky bot is not re-enabling some (?) `bringup: true` builds that are passing forever

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#166758]
For example, `Windows plugin_test`:
```yaml
# excerpt from flutter/flutter/.ci.yaml

  - name: Windows plugin_test
    bringup: true # Flaky https://github.com/flutter/flutter/issues/148834
    recipe: devicelab/devicelab_drone
    timeout: 60
```
... was marked `bringup: true` with https://github.com/flutter/flutter/issues/148835, on May 2024.

The [last 200 builds are green](https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.prod/Windows%20plugin_test_windows?limit=200), but there does not appear to be [any attempt to re-enable the tests](https://github.com/flutter/flutter/pulls?q=is%3Apr+%22Windows+plugin_test%22+is%3Aclosed+sort%3Aupdated-desc).
