### ISSUE TITLE
Conditional bundling of assets based on environment

### ISSUE THREAD

**Issue by timcreatedit** [flutter/flutter#166842]
For building a whitelabel app, it would be very useful for us to be able to bundle assets based on environment variables. I am aware that this is supported using flavors, but those are not supported on web, and are generally less flexible than environment variables. Especially when it comes to having multiple configuration parameters, flavors don't scale well because you need to add every permutation as a flavor.

This has previously been discussed.

From #96514:

> We could augment this syntax to, for example, conditionally bundle assets based on environment variable(s):
> 
> 
> 
> ```yaml
> flutter:
>   assets:
>     - path: assets/dogfood/ # Only gets bundled when `BUILD=ENV` is set to `dogfood` during flutter run/build.
>       env:
>          - BUILD_ENV=dogfood
> ```
> 
 _Originally posted by @andrewkolos in [#96514](https://github.com/flutter/flutter/issues/96514#issuecomment-1832864375)_

**Comment by maheshj01** [comment]
Seems like a reasonable ask.

**Comment by Calpoog** [comment]
I have a proposed implementation for this and wanted to document the intended syntax and semantics before opening the PR.

## Motivation

Our project has multiple independent build dimensions: three applications and internal/production distributions. Encoding every combination as a native Android product flavor and Xcode scheme creates a growing matrix of native configuration.

Environment-conditioned assets would allow these dimensions to select assets without requiring a native flavor for every combination.

## Proposed syntax

```yaml
flutter:
  assets:
    - assets/common/

    - path: assets/apps/alpha/
      environment:
        APP: alpha

    - path: assets/apps/alpha/non_production/
      environment:
        APP: alpha
        AUDIENCE:
          - internal
          - staging
```

Draft implementation PR: flutter/flutter#192739

Draft documentation PR: flutter/website#13886
