### ISSUE TITLE
streamCallback has some issues in AndroidCameraCameraX

### ISSUE THREAD

**Issue by leessmin** [flutter/flutter#167482]
### Steps to reproduce

Add streamCallback when recording video in AndroidCameraCameraX

### Expected results

The preview video should be the same as when you started recording it

### Actual results

The preview video will change as a result, but the saved video will display normally

### Code sample

<details open><summary>Code sample</summary>

```dart
  void _startVideoRecording() async {
    try {
      await _camerax.startVideoCapturing(
        VideoCaptureOptions(_cameraId, streamCallback: (imageData) {
        }),
      );
      setState(() {
        isRecording = true;
      });
    } on PlatformException catch (e) {
      debugPrint("err,code: ${e.code}, msg: ${e.message}");
    }
  }

  Widget _buildPreview() {
    try {
      return _camerax.buildPreview(_cameraId);
    } on PlatformException catch (e) {
      debugPrint("error: code: ${e.code} -> ${e.message}");
      throw CameraException(e.code, e.message);
    }
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
My English is not very good, please understand if the description is not clear
[video](https://0x0.st/8OFy.mp4)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v                                                                                                                         ─╯
[✓] Flutter (Channel stable, 3.29.3, on Arch Linux 6.14.3-arch1-1, locale en_US.UTF-8) [131ms]
    • Flutter version 3.29.3 on channel stable at /home/leessmin/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (10 days ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [871ms]
    • Android SDK at /home/leessmin/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /home/leessmin/Android/Sdk
    • Java binary at: /home/leessmin/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)
    • All Android licenses accepted.

[✓] Chrome - develop for the web [73ms]
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop [193ms]
    • clang version 19.1.7
    • cmake version 4.0.1
    • ninja version 1.12.1
    • pkg-config version 2.4.3

[✓] Android Studio (version 2024.3) [72ms]
    • Android Studio at /home/leessmin/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin version 85.2.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3) [8ms]
    • IntelliJ at /home/leessmin/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available) [157ms]
    • Redmi K30 (mobile) • 58002c6d • android-arm64  • Android 15 (API 35)
    • Linux (desktop)    • linux    • linux-x64      • Arch Linux 6.14.3-arch1-1
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 135.0.7049.95

[✓] Network resources [6.3s]
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by SnowStar0423** [comment]
If you just want to avoid the issue for now, modify your recording function to skip streamCallback:
`void _startVideoRecording() async {
  try {
    await _camerax.startVideoCapturing(
      VideoCaptureOptions(_cameraId), // <-- no streamCallback
    );
    setState(() {
      isRecording = true;
    });
  } on PlatformException catch (e) {
    debugPrint("err,code: ${e.code}, msg: ${e.message}");
  }
}
`

**Comment by renealexander616** [comment]
You only use streamCallback when needed (e.g., manually before recording):

`void startStreamOnly() async {
  await _camerax.startImageStream(
    StreamOptions(_cameraId, streamCallback: (imageData) {
      // process frames here
    }),
  );
}
`
And stop it before recording:

`void stopStreamBeforeRecording() async {
  await _camerax.stopImageStream();
}
`

**Comment by leessmin** [comment]
@danagbemava-nc this is my dependencies:
```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  camera_android_camerax: ^0.6.15
  camera_platform_interface: ^2.10.0
  video_player: ^2.9.5
  permission_handler: ^12.0.0+1
  image: ^4.5.4
  intl: ^0.20.2
```

```yaml
  camera_android_camerax:
    dependency: "direct main"
    description:
      name: camera_android_camerax
      sha256: "26673643ed8f4a468a81ebd7ca760bc1d8c4c741df6d731cc958585ac1983126"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.15"
  camera_platform_interface:
    dependency: "direct main"
    description:
      name: camera_platform_interface
      sha256: "2f757024a48696ff4814a789b0bd90f5660c0fb25f393ab4564fb483327930e2"
      url: "https://pub.dev"
    source: hosted
    version: "2.10.0"
```

my code
[camera_example_home.dart](https://0x0.st/8VKf.dart)


I only found this problem on redmi k30 and redmi k60 so far, I don't have any more devices to do this test on.
Thank you for taking the time out of your busy schedule to check this out
