### ISSUE TITLE
App crashes after newest flutter upgrade

### ISSUE THREAD

**Issue by CrazyStaff** [flutter/flutter#16852]
My Flutter settings
```
Flutter 0.3.3-pre.12 • channel master • https://github.com/flutter/flutter.git
Framework • revision fb18ac650e (8 hours ago) • 2018-04-21 19:52:46 -0700
Engine • revision cb3376c5de
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b
```

**Through debugging I found out that when this command is executed the app crashes..**
`SharedPreferences _sharedPreferences = await SharedPreferences.getInstance();`

Perhaps it is caused by the same issue mentioned [in this thread](https://github.com/flutter/flutter/issues/16846)

The app crashes while  launching the app. No logs are provided where the problem lies.
```
Launching lib/main.dart on HTC U11 in debug mode...
Initializing gradle...                                       0,8s
Resolving dependencies...                                    1,8s
Running 'gradlew assembleDebug'...
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Configuration 'compile' in project ':firebase_analytics' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':map_view' is deprecated. Use 'implementation' instead.
Built build\app\outputs\apk\debug\app-debug.apk (37.8MB).

```

When I try **pub get** on this project the problem below is shown. **flutter packages get** just works fine without mentioning any problems.

```
Because no versions of shared_preferences match >0.4.1 <0.5.0 and shared_preferences 0.4.1
  requires the Flutter SDK, shared_preferences ^0.4.1 is forbidden.
So, because myapp_foundation depends on shared_preferences ^0.4.1, version solving failed.

Flutter users should run `flutter packages get` instead of `pub get`.
```

**Comment by zoechi** [comment]
please add the content of your `pubspec.yaml` file

**Comment by CrazyStaff** [comment]
Acutally it consists of three projects. However i havent changed any dependencies in the last days.
And yesterday everything worked fine.

All ../plugins dependencies got updated with the newest version, but it still doesnt work

**nalisa_app_foundation**

```
name: nalisa_app_fondation
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: 0.0.4
  nalisa_foundation:
       path: ../nalisa_foundation
  connectivity:
       path: ../plugins/connectivity
  path_provider: "^0.4.0"
  shared_preferences: "^0.4.1"
```

**nalisa_foundation**
```
name: nalisa_foundation
description: An absolute bare-bones foundation app.

dependencies:
  meta: "^1.1.2"
  intl: "^0.15.6"
  http: "^0.11.3+16"
  great_circle_distance: "^1.0.1"
  redstone_mapper_mongo:
       path: ../redstone_mapper_mongo
  jaguar_serializer: ^1.0.0-dev1

dev_dependencies:
   build_runner: ^0.7.0
   jaguar_serializer_cli: ^1.0.0-dev1
```

**main project:** And this are the dependencies of the **main project**.

```
name: learning_flutter16_auth_firebase
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  numberpicker: "^0.1.0"
  location: "^1.2.0"
  google_sign_in: "^2.1.0"
  firebase_auth: "^0.5.3"
  firebase_messaging: "^0.2.1"
  map_view: "^0.0.12"
  redstone: "^0.6.4"
  share: "^0.4.0"

  nalisa_foundation:
    path: ../nalisa_foundation
  nalisa_app_fondation:
    path: ../nalisa_app_fondation
  video_player:
    path: ../plugins/video_player
  async_loader: "^0.1.0"
  fluro:
     git: git://github.com/goposse/fluro.git
  image_picker: "^0.3.1"
  path_provider: "^0.4.0"

dependency_overrides:
   async: "^2.0.6"

```
