### ISSUE TITLE
Remove Jetifier support by default

### ISSUE THREAD

**Issue by rekire** [flutter/flutter#168540]
### Steps to reproduce

1. Create a new Flutter project
2. Add a native JDK 21 dependency for Android like `org.bouncycastle:bcprov-jdk18on:1.79`
3. The project cannot compile

### Expected results

The project can be executed

### Actual results

The build is broken

### Code sample

<details open><summary>Code sample</summary>

**`android/app/build.gradle`**:

```dart
...
dependency {
    implementation 'org.bouncycastle:bcprov-jdk18on:1.79'
}
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform bcprov-jdk18on-1.79.jar (org.bouncycastle:bcprov-jdk18on:1.79) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: [...]/bcprov-jdk18on-1.79.jar.
         > Failed to transform '[...]/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk18on/1.79/4d8e2732bcee15f1db93df266c3f5b70ce5cac21/bcprov-jdk18on-1.79.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 65. (Run with --stacktrace for more details.)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Does not matter the it is the default for 6 years. See [`gradle.properties.tmpl`](https://github.com/flutter/flutter/blame/76747c0ecef6b24087f451f64142c7d053bd71a4/packages/flutter_tools/templates/app/android.tmpl/gradle.properties.tmpl#L3)

</details>

**Comment by darshankawar** [comment]
> jdk18on

This dependency seems to be using jdk 18 and you have jdk 21 for Flutter. Could it be the reason for the error due to incompatibility ?

**Comment by rekire** [comment]
While debugging in installed multiple JDKs. Based on [this table from StackOverflow](https://stackoverflow.com/q/9170832):
|Java| Major version |
|--:|:---|
| 24 | 68 |
| 23 | 67 |
| 22 | 66 |
| 21 | 65 |
| 20 | 64 |
| 19 | 63 |
| 18 | 62 |
| 17 | 61 |

This hints that the mentioned _"Unsupported class file major version 65"_ is from JDK 21 even if the name implies that it should be for JDK 18. Don't ask me.

**Comment by darshankawar** [comment]
Keeping the issue open for team's tracking.

**Comment by rekire** [comment]
After a short discussion on discord I took the top 70 pub.dev packages as dependency of a fresh project to check if there are dependencies to `androidx.` or the problematic `android.support.` packages. There were no dependencies on both packages.

<details><summary>`pubspec.yaml` dependencies</summary>

```yaml
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  firebase_core: ^3.13.0
  sqflite: ^2.4.2
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.4
  bloc: ^9.0.0
  device_info_plus: ^11.4.0
  riverpod: ^2.6.1
  share_plus: ^11.0.0
  firebase_messaging: ^15.2.5
  geolocator: ^14.0.0
  flutter_native_splash: ^2.4.6
  firebase_auth: ^5.5.3
  win32: ^5.13.0
  cloud_firestore: ^5.6.7
  built_value: ^8.9.5
  just_audio: ^0.10.2
  firebase_crashlytics: ^4.3.5
  infinite_scroll_pagination: ^5.0.0
  sign_in_with_apple: ^7.0.1
  drift: ^2.26.1
  characters: ^1.4.0
  location: ^8.0.0
  sensors_plus: ^6.1.1
  animated_text_kit: ^4.2.3
  toggle_switch: ^2.3.0
  chopper: ^8.1.0
  network_info_plus: ^6.1.4
  flutter_rust_bridge: ^2.9.0
  cloud_functions: ^5.5.0
  mobx: ^2.5.0
  android_intent_plus: ^5.3.0
  flex_color_scheme: ^8.2.0
  flame: ^1.28.1
  battery_plus: ^6.2.1
  flutter_mobx: ^2.3.0
  flutter_redux: ^0.10.0
  convex_bottom_bar: ^3.2.0
  googleapis: ^14.0.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_svg: ^2.1.0
  json_serializable: ^6.9.5
  video_player: ^2.9.5
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  flutter_local_notifications: ^19.2.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.8.0
  flutter_slidable: ^4.0.0
  flutter_animate: ^4.5.2
  firebase_storage: ^12.4.5
  built_collection: ^5.1.1
  fpdart: ^1.1.1
  msix: ^3.16.9
  beamer: ^1.7.0
  feedback: ^3.1.0
  #mobx_codegen: ^2.7.0 # conflicts but as codegen not relevant I guess
  macos_ui: ^2.1.10
  built_value_generator: ^8.9.5
  fluentui_system_icons: ^1.1.273
  android_alarm_manager_plus: ^4.0.7
  bottom_navy_bar: ^6.1.0
  sentry_flutter: ^8.14.2
  sentry: ^8.14.2
  rxdart: ^0.28.0
  redux: ^5.0.0
```

</details>

`./gradlew :app:dependencies | grep android.support. | wc -l` returned nothing. So there are no problematic dependencies.
