### ISSUE TITLE
Top-level  `.ci.yaml` `enabled_branches` is not considered in release recipes

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#168875]
Consider the following:
```yaml
# .ci.yaml
enabled_branches:
   - master
   - flutter-\d+\.\d+-candidate\.\d+

targets:
   - name: Linux docs_publish
     recipe: flutter/docs
```
Elsewhere (i.e. in Coocon and friends), this means "all targets without an explicit `enabled_branches` inherit from the top-level `enabled_branches`. In `release_builder.py`, only the target-level branches are checked. By happenstance (due to false-y-ness), an _empty_ `enabled_branches` happens to mean "enabled", because of Python truthiness, but this is confusing.
```py
  # Enabled for current branch
  enabled_branches = target.get('enabled_branches', [])
  if enabled_branches and target.get('scheduler') != 'release':
```
