### ISSUE TITLE
Remove `schedule_during_release_override: true` and use two targets instead

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#168913]
In https://github.com/flutter/flutter/issues/168709 we added a workaround, `schedule_during_release_override: true`:
```yaml
targets:
  - name: Linux docs_publish
    schedule_during_release_override: true
```
Unfortunately it does not completely fix every issue that was originally regressed in https://github.com/flutter/flutter/pull/162557, namely now `Linux docs_publish` is run twice - once on `Linux flutter_release_builder`, and once on post-submit tasks scheduled after the release builder. 

As far as I can tell this has no negative side-effects other than being wasteful (GCS buckets should be the same, output should be the same).

To make everything simpler, both in the recipes, and not having to add code elsewhere, we should just do:
```yaml
targets:
  - name: Linux docs_publish
    enabled_branches: [master]

  - name: Linux docs_publish_release
    scheduler: release
```

To do this:
- [x] Add support for `scheduler: release` in the `is is_release_candidate:` branch of `release_builder.py`
- [x] Split the target branches in `master`
- [x] Split the target branches in `flutter-3.32-candidate.0`
- [ ] Remove `schedule_during_release_override`
