### ISSUE TITLE
Custom font don't work

### ISSUE THREAD

**Issue by azabcodes** [flutter/flutter#169375]
```
ls assets/fonts

Tajawal-Black.ttf       Tajawal-ExtraBold.ttf   Tajawal-Light.ttf       Tajawal-Regular.ttf
Tajawal-Bold.ttf        Tajawal-ExtraLight.ttf  Tajawal-Medium.ttf
```

```
fonts:
  - family: "Tajawal"
    fonts:
      - asset: assets/fonts/Tajawal-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Tajawal-Light.ttf
        weight: 300
      - asset: assets/fonts/Tajawal-Regular.ttf
        weight: 400
      - asset: assets/fonts/Tajawal-Medium.ttf
        weight: 500
      - asset: assets/fonts/Tajawal-Bold.ttf
        weight: 700
      - asset: assets/fonts/Tajawal-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Tajawal-Black.ttf
        weight: 900
```

```
final ThemeData lightTheme = ThemeData(
  useMaterial3: true,
  fontFamily: 'Tajawal',
  brightness: Brightness.light,
  primaryColor: HexColorManager.colorF6F7F8,
  scaffoldBackgroundColor: HexColorManager.colorF6F7F8,
  appBarTheme: AppBarTheme(
    backgroundColor: HexColorManager.whiteColor,
    iconTheme: IconThemeData(color: HexColorManager.color313737),
    centerTitle: true,
    titleTextStyle: TextStyle(
      color: HexColorManager.color343F52,
      fontSize: 17.07,
      fontWeight: FontWeight.w600,
      letterSpacing: 1.07,
    ),
  ),
  textTheme: TextTheme(
    titleSmall: TextStyle(
      color: HexColorManager.blackColor,
      fontWeight: FontWeight.w500,
      fontSize: 10,
    ),
  ),
);
```

```
  Text(
                      context.l10n.complete_profile,
                      style: context.textTheme.titleSmall,
                      textAlign: TextAlign.center,
                      textScaler: const TextScaler.linear(1.0),
                    ),
```
