### ISSUE TITLE
CupertinoCheckbox doesn't appear to match HIG

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#169532]
HIG has an example of a checkbox but `CupertinoCheckbox` doesn't match it visually. I suspect it's also the wrong size.

![Image](https://github.com/user-attachments/assets/008b861f-68e9-4d9c-83fd-b1587aa63b4a)

<img width="495" alt="Image" src="https://github.com/user-attachments/assets/724ff751-69ef-4377-972a-a84dc8d2e652" />

https://developer.apple.com/design/human-interface-guidelines/toggles

---
## pubspec.yaml

<details>

```yaml
name: apm
description: alpine mode - battery bumps for thru-hikers
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  drops: ^0.0.5
  flutter_animate: ^4.5.2
  http: ^1.4.0
  purchases_flutter: ^8.8.1
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  sprung: ^3.0.1
  url_launcher: ^6.3.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  pull_down_button: ^0.10.2
  firebase_messaging: ^15.2.6
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
```
</details>

## flutter doctor -v

<details>

```
[✓] Flutter (Channel stable, 3.32.0, on macOS 15.5 24F74 darwin-arm64, locale en-US) [181ms]
    • Flutter version 3.32.0 on channel stable at /Users/lukepighetti/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision be698c48a6 (8 days ago), 2025-05-19 12:59:14 -0700
    • Engine revision 1881800949
    • Dart version 3.8.0
    • DevTools version 2.45.1

[✗] Android toolchain - develop for Android devices [157ms]
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [613ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [5ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed) [5ms]
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.100.2) [5ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (3 available) [5.9s]
    • Luke Pighetti’s iPhone (mobile) • 00008140-000E18E43E3B001C • ios            • iOS 18.5 22F76
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 136.0.7103.114

[✓] Network resources [236ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>
