### ISSUE TITLE
iOS app crashes on relaunch after closing — does not happen on Android

### ISSUE THREAD

**Issue by BackdoorTech** [flutter/flutter#171268]
After force-closing the Flutter app on iOS and trying to relaunch it, the app crashes immediately. This issue does not occur on Android — the app works as expected there.

**Steps to Reproduce**

1. Launch the app on an iOS device or simulator.
2. Let the app load normally.
3. Force-close the app (swipe up in app switcher).
4. Reopen the app.
5. The app crashes instantly.

**Expected Behavior**
App should reopen normally after being closed, just like it does on Android.

**Actual Behavior**
App crashes immediately upon relaunch after being force-closed.

**Flutter Doctor Output**

```bash
#!/bin/bash
flutter doctor -v

[✓] Flutter (Channel stable, 3.29.0, on macOS 14.6 23G80 darwin-arm64, locale en-AO) [4.3s]
    • Flutter version 3.29.0 on channel stable at /Users/ito/fvm/versions/3.29.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (5 months ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2
 
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [7.9s]
    • Android SDK at /Users/ito/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.
 
[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [8.1s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2
 
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome) [11ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
 
[✓] Android Studio (version 2024.2) [11ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
 
[✓] VS Code (version 1.96.2) [10ms]
    • VS Code at /Users/ito/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.104.0
 
[✓] Connected device (4 available) [11.2s]
    • iPhone de ITO (wireless) (mobile) • 00008030-001539EA0A13402E            • ios          • iOS 18.5 22F76
    • iPhone 13 Pro Max (mobile)        • 9B63FB27-3CE5-49AB-BFDF-E315111A7308 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-18-2 (simulator)
    • macOS (desktop)                   • macos                                • darwin-arm64 • macOS 14.6 23G80 darwin-arm64
    • Mac Designed for iPad (desktop)   • mac-designed-for-ipad                • darwin       • macOS 14.6 23G80 darwin-arm64
    ! Error: Browsing on the local area network for suraia’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone  de Celestino . Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone (7). Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
 
[✓] Network resources [1,896ms]
    • All expected network resources are available.
 
! Doctor found issues in 1 category.
```

**Platform**

- IOS (crashes)
- Android (works fine)
- IOS Emulator (works fine)

**Additional Information**

- I have tried flutter version 3.24.0 and 3.29.0
- It does not throw any exeption to loki on the aplication level

My pubspec.yaml

```yaml

name: doneit_mobile
description: "DoneIt"
version: 1.0.0+101
publish_to: none

environment:
  sdk: ">=3.2.3 <3.24.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.3
  just_audio: ^0.9.39
  get: ^4.7.2
  flutter_chat_reactions:
  scrollable_positioned_list: 0.3.8
  sticky_grouped_list: ^3.1.0
  cupertino_icons: ^1.0.2
  opentelemetry: 0.18.6
  opentelemetry_dart: ^0.0.2
  get_it: ^7.7.0
  dio: ^5.5.0+1
  google_fonts:
  retry: ^3.1.2
  pretty_dio_logger: ^1.4.0
  flutter_cached_pdfview: 0.4.2
  dartz: ^0.10.1
  flutter_flavorizr: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  adaptive_theme: ^3.6.0
  easy_localization: ^3.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mobx: ^2.3.3+2
  choice: ^2.3.2
  flutter_mobx: ^2.2.1+1
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  cached_network_image:
  device_info_plus: ^10.1.1
  package_info_plus: ^8.0.1
  focus_detector: ^2.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.1
  local_auth: ^2.3.0
  flutter_screen_lock: ^9.1.0
  image_picker: ^1.1.2
  crop_your_image: ^1.1.0
  image_editor_plus: ^1.0.6
  flutter_sharing_intent: ^1.1.1
  flutter_datetime_picker_plus: ^2.2.0
  dropdown_button2: ^2.3.9
  dartx: ^1.2.0
  collection: ^1.18.0
  flutter_timezone: ^2.1.0
  table_calendar: ^3.1.2
  flutter_slidable:
    git: "https://github.com/IldySilva/flutter_slidable"
  flutter_carousel_slider: ^1.1.0
  path: ^1.9.0
  uuid: ^4.4.2
  quill_html_editor:
    path: ./quill_html_editor
  appinio_video_player: ^1.2.2
  time_picker_spinner: ^1.0.0
  social_media_recorder: ^1.1.13
  voice_message_package: ^2.2.1
  toastification: ^2.1.0
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3
  ffmpeg_kit_flutter:
    git:
      url: https://github.com/carl-designlibro/ffmpeg-kit.git
      path: flutter/flutter
      ref: flutter_fix_retired_v6.0.3  # For version 6.0.3
    # ref: flutter_fix_retired_v5.1.0  # For version 5.1.0
  path_provider: ^2.1.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  internet_connection_checker: ^1.0.0+1
  flutter_expandable_fab: 2.0.0
  flutter_animate: ^4.5.0
  feather_icons: any
  html_unescape: 2.0.0
  flutter_widget_from_html: ^0.15.2
  flutter_pdfview: ^1.2.7
  flutter_speed_dial: ^7.0.0
  sliver_tools: ^0.2.12
  responsive_builder: ^0.7.1
  video_trimmer:
    path: ./video_trimmer
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  flutter_camera: ^1.0.0
  sleek_circular_slider: ^2.0.1
  signalr_netcore: ^1.4.0
  flutter_inappwebview: ^6.1.5
  http: ^1.2.0
  video_compress: ^3.1.2
  cmdr:
    git: "https://github.com/IldySilva/cmdr.git"
  webview_flutter: any
  chewie: ^1.8.5
  string_unescape: ^2.0.0
  logger: ^2.5.0
  logging: ^1.3.0
  provider: ^6.1.2
  pointycastle: ^3.9.1
  html: ^0.15.5
  firebase_crashlytics: ^4.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  mobx_codegen:
  very_good_analysis: ^6.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/drawables/
    - assets/translations/

```
