### ISSUE TITLE
showing error No file or variants found for asset: loadjson/person.json.

### ISSUE THREAD

**Issue by sovoereign** [flutter/flutter#17283]
```
name: jsondata
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
    cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  assets:
     - loadjson/person.json
  uses-material-design: true
```
