### ISSUE TITLE
Encourage reproducible builds

### ISSUE THREAD

**Issue by fmatosqg** [flutter/flutter#17464]
I've been thinking about how this could be tackled for a while, but what triggered me to open this issue was a question by a fellow flutter dev.

"Is there any way to see which flutter version someone is using from their github repo?"  - @iampawan
 Although I consider good practice writing `pubspec.yaml` with specific versions (no ^ or ranges) and explicit flutter version `environment: \n flutter: 0.x.x` , these rarely happen.

I noticed `pubspec.lock` doesn't contain a number to the flutter version used as well:
```
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
```

**Comment by iampawan** [comment]
@passsy created that flutter wrapper. @fmatosqg I guess that can help.

**Comment by fmatosqg** [comment]
Thx for mentioning it, I'm aware of the wrapper https://github.com/passsy/flutter_wrapper.

I think it should have 1st class support for a number of reasons. Also this is only one part (maybe the most important) of making sure that builds can be 100% reproducible.

The hardest to tackle for example is declaring that good practices mention dependency exact versions instead of ranges or unbounded upgrades.

**Comment by passsy** [comment]
Version ranges are fine if they are locked with the `pubspec.lock`. Make sure to add it to git. 

By calling `flutter packages get` pub resolves all defined dependencies and transitive dependencies. The concrete versions will be stored in the `pubspec.lock` file. This file should be added to your git repository allowing everyone to build the app with the same dependency versions. The `pubspec.lock` package versions will be used until `flutter packages upgrade` is called.

> For application packages, do commit `pubspec.lock`. This file is the recommended way for non-shared resources such as applications to manage their dependencies. ([src](https://www.dartlang.org/guides/libraries/private-files#pubspeclock))

```yaml
dependencies:
  flutter:
    sdk: flutter
```

```yaml
# Generated by pub
# See https://www.dartlang.org/tools/pub/glossary#lockfile
packages:
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.6"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
    
  [...]
  
sdks:
  dart: ">=1.21.0 <=2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c"
```

The only exception are local dependencies, provided by sdks such as `flutter`. They can change without changing the version or don't have a version at all. This is possible because versions can be omitted for local packages, packages which haven’t been published to pub. Local packages then fallback to version `0.0.0` (`flutter` in this case).

Two possible solutions:
1. Lock the dependency of the SDK by setting a explicit version as environment:

```
dependencies:
  flutter:
    sdk: flutter
environment:
  flutter: "0.4.5-pre.57"
```

2. Add the sdks as submodule (which locks the version). The https://github.com/passsy/flutter_wrapper can be helpful to achieve this.
