### ISSUE TITLE
firebase_messaging and geolocation Plugins make crash flutter default application

### ISSUE THREAD

**Issue by acrozes** [flutter/flutter#17588]
When I enable this two plugins, the default app launch and crash on android phone.
pubspec.yaml :
```
dependencies:
  flutter:
    sdk: flutter
  geolocation: any
  firebase_messaging: any

dev_dependencies:
  flutter_test:
    sdk: flutter
```
I try with several "firebase-core" version in gradle file like 'com.google.firebase:firebase-core:15.0.2'.
Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [version 6.3.9600], locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.
```
