### ISSUE TITLE
flutter.gradle issue when running flutter clean before flutter run

### ISSUE THREAD

**Issue by artAst** [flutter/flutter#17737]
This is an intermittent error. Most of the time I encountered this when I do flutter clean and then flutter run on my project. I experienced this error when I upgraded the flutter version that has Dart 2.0

Is it possible that this is pointing to an old version of Dart?

## Logs
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
compiler message: file:///Users/macbook/.pub-cache/hosted/pub.dartlang.org/lists-0.0.22/lib/src/range_list.dart:87:21: Error: The parameter 'value' of the method 'RangeList::contains' has type dart.core::int, which does not match the corresponding type in the overridden method (dart.core::Object).
compiler message: Change to a supertype of dart.core::Object (or, for a covariant parameter, a subtype).
compiler message:   bool contains(int value) {
compiler message:                     ^
compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart: Context: This is the overriden method ('contains').
compiler message: file:///Users/macbook/.pub-cache/hosted/pub.dartlang.org/lists-0.0.22/lib/src/step_list.dart:73:21: Error: The parameter 'value' of the method 'StepList::contains' has type dart.core::int, which does not match the corresponding type in the overridden method (dart.core::Object).
compiler message: Change to a supertype of dart.core::Object (or, for a covariant parameter, a subtype).
compiler message:   bool contains(int value) {
compiler message:                     ^
compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart: Context: This is the overriden method ('contains').
compiler message: file:///Users/macbook/.pub-cache/hosted/pub.dartlang.org/lists-0.0.22/lib/src/list_pointer.dart:60:48: Error: A value of type 'dart.core::List<dynamic>' can't be assigned to a variable of type 'dart.core::num'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to 'dart.core::num'.
compiler message:       return new ListPointer<T>(base, offset + other);
compiler message:                                                ^
Compiler failed on /Users/macbook/Documents/flProjects/myapp/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/macbook/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 435

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command '/Users/macbook/Documents/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Finished with error: Gradle build failed: 1

## Flutter Doctor

[✓] Flutter (Channel dev, v0.4.4, on Mac OS X 10.13.4 17E199, locale en-PH)
    • Flutter version 0.4.4 at /Users/macbook/Documents/flutter
    • Framework revision f9bb4289e9 (7 days ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Android NDK at /Users/macbook/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 28.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[!] VS Code (version 1.17.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

**Comment by zoechi** [comment]
Did you check version constraints in your `pubspec.yaml` allows the latest versions of dependencies and run `flutter packages upgrade`?

**Comment by artAst** [comment]
```
dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    path: firebase_plugins/firebase_auth
  firebase_database:
    path: firebase_plugins/firebase_database
  firebase_dynamic_link:
    path: firebase_plugins/firebase_dynamic_link
  firebase_storage:
    path: firebase_plugins/firebase_storage
  validator: ">=0.0.4 <0.1.0"
  intl: "^0.15.2"
  http: "^0.11.3+14"
  path_provider: "^0.2.2"
  facebook_sign_in:
    path: FB-Signin-Plugin
  mframe_plugins:
    path: mframe_plugins
  stripe_plugin:
      path: stripe_plugin
  font_awesome_flutter: "^6.0.0"
  url_launcher: "^3.0.0"
  strings: "^0.0.6"
  flutter_launcher_icons: "^0.2.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
```

I also did `flutter packages upgrade`
and `flutter update-packages --force-upgrade`
