### ISSUE TITLE
firebase_core FirebaseConfiguration support

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#17763]
Right now `FirebaseConfiguration` isn't implemented in firebase_core

Plugin works fine, but this should blocking 1.0 release

**Comment by JonathanSum** [comment]
Then you can just install the firebase_core.
https://pub.dartlang.org/packages/firebase_core
[How to install](https://pub.dartlang.org/packages/firebase_core#-installing-tab-)

The pubspec file manages the assets for a Flutter app. In pubspec.yaml, add  firebase_core to the dependencies list. 
```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  firebase_core: ^0.2.3
```
