### ISSUE TITLE
warning: The asset images/new.jpeg does not exist. (asset_does_not_exist at [fade_in] pubspec.yaml:28)

### ISSUE THREAD

**Issue by Sacchid** [flutter/flutter#18820]
### Steps to Reproduce
I am getting error -
No file or variants found for asset: images/new.jpeg.
 
 **Whereas its present in directory -  \fade_in\assets\images\new.jpeg**
_______________________________________
`Error building assets
FAILURE: Build failed with an exception.`
`* Where:
Script 'C:\Users\sacch\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 435`
`* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.`
`> Process 'command 'C:\Users\sacch\flutter\bin\flutter.bat'' finished with non-zero exit value 1`
`* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`
`* Get more help at https://help.gradle.org
BUILD FAILED in 9s
Finished with error: Gradle build failed: 1`

`I/flutter (17633): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter (17633): The following assertion was thrown resolving an image codec:
I/flutter (17633): Unable to load asset: assets/images/new.jpg
I/flutter (17633): 
I/flutter (17633): When the exception was thrown, this was the stack:
I/flutter (17633): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
I/flutter (17633): <asynchronous suspension>
I/flutter (17633): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:383:44)
I/flutter (17633): <asynchronous suspension>
I/flutter (17633): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:368:14)
I/flutter (17633): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:86)
I/flutter (17633): #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82:22)
I/flutter (17633): #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:63)
I/flutter (17633): (elided 8 frames from package dart:async)
I/flutter (17633): 
I/flutter (17633): Image provider: AssetImage(bundle: null, name: "assets/images/new.jpg")
I/flutter (17633): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#27ad0(), name: "assets/images/new.jpg",
I/flutter (17633): scale: 1.0)
I/flutter (17633): ════════════════════════════════════════════════════════════════════════════════════════════════════`

__________________________________________
### Flutter Logs
`Launching lib/main.dart on Pixel 2 in debug mode...
Initializing gradle...                                       1.4s
Resolving dependencies...                                    3.4s
Running 'gradlew assembleDebug'...
Error detected in pubspec.yaml:
No file or variants found for asset: images/new.jpeg.
Error building assets
FAILURE: Build failed with an exception.`
`* Where:
Script 'C:\Users\sacch\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 435`
`* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.`
`> Process 'command 'C:\Users\sacch\flutter\bin\flutter.bat'' finished with non-zero exit value 1`
`* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`
`* Get more help at https://help.gradle.org
BUILD FAILED in 10s
Gradle build failed: 1
`
________________________________________
### Flutter Doctor
`Doctor summary (to see all details, run flutter doctor -v):`
`[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.16299.431], locale en-IN)`
`[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)`
`[√] Android Studio (version 3.1)`
`[√] Android Studio (version 3.0)`
`[√] IntelliJ IDEA Community Edition (version 2017.3)`
`[√] IntelliJ IDEA Ultimate Edition (version 2018.1)`
`[√] Connected devices (1 available)`

`• No issues found!`
`
_____________________________
### Github link - 
[https://github.com/Sacchid/fade_in](url)

**Comment by Sacchid** [comment]
Its added in pubspec.yaml 
[https://github.com/Sacchid/fade_in/blob/master/pubspec.yaml](url)

**Comment by Sacchid** [comment]
### pubspec.yaml
Adding `pubspec.yaml`  and `main.dart` because of some reason github link isn't working.
```
name: fade_in
description: Fade in Flutter

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
     - images/new.jpeg
     - umbrella.jpg
```
________________________________________________
### main.dart
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final title = 'Fade in images';
//assets/images/umbrella.jpg
    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
       body: DecoratedBox(decoration: BoxDecoration(
         image: DecorationImage(
           image: AssetImage('assets/images/new.jpg'
           ),
         ),
       ),
       ),
      ),
    );
  }
}
```
