### ISSUE TITLE
Flutter upgrade not upgrade to the latest release version.

### ISSUE THREAD

**Issue by jaggerwang** [flutter/flutter#18893]
## Steps to Reproduce

1. Open project in vs code and get a notice to upgrade flutter.
2. Run `flutter upgrade` in terminal, it says "Already up-to-date". But my local version is still `0.5.1`, not the latest release version `0.5.5` in github.

## Logs

```
➜  app git:(master) flutter upgrade
Upgrading Flutter from /Users/jagger/flutter...
From https://github.com/flutter/flutter
   2e559584e..35ad2a786  master     -> origin/master
 * [new branch]          revert-18560-integration-tests -> origin/revert-18560-integration-tests
 * [new branch]          revert-18808-swap_values -> origin/revert-18808-swap_values
 * [new branch]          revert-18868-add-output-and-unskip -> origin/revert-18868-add-output-and-unskip
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (4 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

Running "flutter packages upgrade" in app...                19.5s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.24.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

```yaml
name: tangbole
description: A tumblr client app.

dependencies:
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.1
  flutter_webview_plugin: ^0.1.6
  http: ^0.11.3+16
  logging: ^0.11.3+1
  meta: ^1.1.5
  uri: ^0.11.2
  redux: ^3.0.0
  redux_logging: ^0.3.0
  redux_persist: ^0.7.0-rc.2
  redux_persist_flutter: ^0.6.0-rc.1
  validate: ^1.6.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg

```
