### ISSUE TITLE
Xcode archive fails but flutter run and flutter build ios work fine

### ISSUE THREAD

**Issue by asibilia** [flutter/flutter#19149]
## Steps to Reproduce

1. `flutter create demo`, `cd demo`
2. Update `pubspec.yaml`:
```yaml
...
dependencies:
  flutter:
    sdk: flutter

  #Dialogflow //NEW
  flutter_dialogflow: ^0.0.1

  #Firebase //NEW
  firebase_core: ^0.2.4
  firebase_auth: ^0.5.12
  cloud_firestore: ^0.7.3

  #Time Formatting //NEW
  intl: ^0.15.6

  #Google Sign In //NEW
  google_sign_in: ^3.0.4

  # Strings //NEW
  strings: ^0.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
...
```

3. `flutter packages get`, `flutter packages upgrade`
4. `flutter run -d <DEVICE_NAME>`
5. `flutter build ios`
6. Try to create an archive in Xcode. Archive will throw errors while installing pods.

#### Xcode Archive Process Output:
```
compiler message: file:///Users/<username>/.pub-cache/hosted/pub.dartlang.org/lists-0.0.22/lib/src/range_list.dart:87:21: Error: The parameter 'value' of the method 'RangeList::contains' has type dart.core::int, which does not match the corresponding type in the overridden method (dart.core::Object).
compiler message: Change to a supertype of dart.core::Object (or, for a covariant parameter, a subtype).
compiler message:   bool contains(int value) {
compiler message:                     ^
compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart:1: Context: This is the overriden method ('contains').
compiler message: file:///Users/<username>/.pub-cache/hosted/pub.dartlang.org/lists-0.0.22/lib/src/step_list.dart:73:21: Error: The parameter 'value' of the method 'StepList::contains' has type dart.core::int, which does not match the corresponding type in the overridden method (dart.core::Object).
compiler message: Change to a supertype of dart.core::Object (or, for a covariant parameter, a subtype).
compiler message:   bool contains(int value) {
compiler message:                     ^
compiler message: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart:1: Context: This is the overriden method ('contains').
compiler message: file:///Users/<username>/.pub-cache/hosted/pub.dartlang.org/lists-0.0.22/lib/src/list_pointer.dart:60:48: Error: A value of type 'dart.core::List<dynamic>' can't be assigned to a variable of type 'dart.core::num'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to 'dart.core::num'.
compiler message:       return new ListPointer<T>(base, offset + other);
```

#### Flutter Doctor -v
```bash
[✓] Flutter (Channel master, v0.5.7-pre.62, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.7-pre.62 at /Users/<username>/Github/flutter
    • Framework revision 7ac183794b (2 days ago), 2018-07-06 15:21:29 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[!] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/<username>/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.25.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.15.0

[✓] Connected devices (1 available)
    • iPhone 7 • 19CEDA6B-XXXX-XXXX-XXXX-8CCA550BE02C • ios • iOS 11.4 (simulator)

! Doctor found issues in 2 categories.
```
