### ISSUE TITLE
Docs have thin fonts, which are annoying to read

### ISSUE THREAD

**Issue by devxpy** [flutter/flutter#19394]
The flutter doc page has a font-weight of `300`, which is a notch down than the normal `400`.

I understand this provides an aesthetic appeal to the website, but for long reading, it is fatiguing.

This could be an issue with low-res displays like mine (its a TN 720p panel).

---

Here is what it looks like on my screen -

![image](https://user-images.githubusercontent.com/19492893/42742472-6bcd860e-88d8-11e8-8c1b-9cd2a5c86cf1.png)

If I reset the font-weight using a little bit of css (`* { font-weight: normal !important; }`), it looks a lot more read-able.

![image](https://user-images.githubusercontent.com/19492893/42742485-824a5f92-88d8-11e8-8f0e-693baf47ad6a.png)

---

This is specially true for the links, since they are both `thin` and `light-colored`.

![image](https://user-images.githubusercontent.com/19492893/42742419-1636eac8-88d8-11e8-8202-88302e547bc9.png)

![image](https://user-images.githubusercontent.com/19492893/42742416-11bab934-88d8-11e8-89f6-3bc05f276ed0.png)

---

As a temporary fix, I have installed the [Stylus]( https://chrome.google.com/webstore/detail/stylus-beta/apmmpaebfobifelkijhaljbmpcgbjbdo) google chrome extension, and added the following css rule.

```css
* {
    font-weight: normal !important;
    font-size: 100%  !important;
    font-family: inherit !important;
}
code[class*="language-"], pre[class*="language-"] {
    font-family: monospace !important;
}
```

P.S.  I'm not a designer by any means. I'm just trying to read the docs!
