### ISSUE TITLE
Flutter crashes when using custom fonts on iOS

### ISSUE THREAD

**Issue by JoeCherry** [flutter/flutter#19452]
## Sample pubspec.yaml

```
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: ProductSans-Bold
      fonts:
        - asset: assets/fonts/Product Sans Bold.ttf
    - family: ProductSans-Regular
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
    - family: CPMono-Black
      fonts:
       - asset: assets/fonts/CPMono_v07_Black.otf
    - family: CPMono-Bold
      fonts:
       - asset: assets/fonts/CPMono_v07_Bold.otf
    - family: CPMono-ExtraLight
      fonts:
       - asset: assets/fonts/CPMono_v07_ExtraLight.otf
    - family: CPMono-Light
      fonts:
       - asset: assets/fonts/CPMono_v07_Light.otf
    - family: CPMono-Plain
      fonts:
       - asset: assets/fonts/CPMono_v07_Plain.otf
```

## Steps to Reproduce

1. Add custom fonts to Flutter application
2. Run on iOS device
3. Observe random crash. Sometimes on startup other times when navigating to new widgets

note: I have not tried running on Android yet

## Logs

```
[        ] [DEVICE LOG] 2018-07-17 01:00:30.274749-0400  localhost Runner[91528]: (Flutter) [VERBOSE-2:FontFamily.cpp(184)] Could not get cmap table size!
[        ] [DEVICE LOG] 2018-07-17 01:00:30.274920-0400  localhost Runner[91528]: (Flutter) [VERBOSE-3:FontCollection.cpp(94)] nTypefaces == 0
[        ] [VERBOSE-2:FontFamily.cpp(184)] Could not get cmap table size!
[        ] [VERBOSE-3:FontCollection.cpp(94)] nTypefaces == 0
[   +3 ms] Service protocol connection closed.
[        ] Lost connection to device.
```

```
[✓] Flutter (Channel master, v0.5.7-pre.126, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.5.7-pre.126 at /Users/josephcherry/Development/flutter
    • Framework revision 6a8f904104 (15 hours ago), 2018-07-16 16:21:20 +0200
    • Engine revision c5a63d28bf
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/josephcherry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.25.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (1 available)
    • iPhone 8 • 4A63DBDC-0389-4FA0-B31B-C855247128F2 • ios • iOS 11.4 (simulator)

• No issues found!
```
