### ISSUE TITLE
Error detected in pubspec.yaml

### ISSUE THREAD

**Issue by shockw4ver** [flutter/flutter#19505]
## Steps to Reproduce

1. Create a flutter app.
2. Modify pubspec.yaml for adding some vendors:
```
name: alfraid
description: Something I need

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  flutter_swiper: ^1.0.2
  carousel: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icons/today.png
    - images/icons/today_on.png
    - images/icons/explore.png
    - images/icons/explore_on.png
    - images/icons/mine.png
    - images/icons/mine_on.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

```
3. ``Error detected in pubspec.yaml`` occured within compilation.

## Logs
* **Within compilation**
```
Initializing hot reload...
#/properties/flutter: type: wanted [object] got null
Error detected in pubspec.yaml:
#/properties/flutter: type: wanted [object] got null
Error detected in pubspec.yaml:
```

* **Ran flutter analyze and result didn't mention it**
```
nalyzing /Users/zhangyongchao/AndroidStudioProjects/alfraid...
  lint • Name non-constant identifiers using lowerCamelCase at lib/Constants/Api.dart:2:23 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/Constants/Api.dart:5:23 • non_constant_identifier_names
  lint • Prefer using /// for doc comments at lib/Utils/Network.dart:4:1 • slash_for_doc_comments
  hint • Unused import: 'dart:convert' at lib/main.dart:1:8 • unused_import
  hint • Unused import: 'package:flutter_swiper/flutter_swiper.dart' at lib/pages/Recommend.dart:2:8 • unused_import
  hint • Unused import: 'dart:async' at lib/pages/Today.dart:1:8 • unused_import
  hint • Unused import: 'dart:convert' at lib/Utils/Network.dart:2:8 • unused_import
  hint • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib/Widgets/Avatar.dart:3:7 • must_be_immutable
8 issues found.
(Ran in 5.6s)

```

* **Either after running ``flutter doctor``** 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.0)
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

```
