### ISSUE TITLE
Flutter build IOS error Firebase performance

### ISSUE THREAD

**Issue by artAst** [flutter/flutter#19635]
Encountered issue on Firebase Performance Plugin.
Not sure if this is Firebase Performance issue or not.
Tried to run on my project:
```
>> flutter build ios --release
```
It's weird though because I have also run this on my local machine and its working fine. That error occurred on Dev machine. version for flutter and pods are all the same from my local vs dev

## Logs
```
Error: 'package:firebase_performance/src/performance_attributes.dart': error: line 24 pos 51: semicolon expected
build   20-Jul-2018 05:15:32         Map<String, String> get attributes => Map<String, String>.from(_attributes);
build   20-Jul-2018 05:15:32                                                         ^
build   20-Jul-2018 05:15:32       Dart snapshot generator failed with exit code 254
```

## Flutter doctor
```
[✓] Flutter (Channel dev, v0.4.4, on Mac OS X 10.13.2 17C88, locale en-US)
    • Flutter version 0.4.4 at /Applications/Flutter
    • Framework revision f9bb4289e9 (2 months ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /usr/local/Caskroom/android-sdk/3859397,26.0.2
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] Connected devices
    ! No devices available
```

## Pubspec yaml
```
dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    path: firebase_plugins/firebase_auth
  firebase_database:
    path: firebase_plugins/firebase_database
  firebase_dynamic_links:
    path: firebase_plugins/firebase_dynamic_links
  firebase_storage:
    path: firebase_plugins/firebase_storage
  firebase_analytics:
    path: firebase_plugins/firebase_analytics
  firebase_performance:
    path: firebase_plugins/firebase_performance
  firebase_remote_config:
    path: firebase_plugins/firebase_remote_config
  firebase_messaging:
    path: firebase_plugins/firebase_messaging
  http: "0.11.3+16"

  validator: ">=0.0.4 <0.1.0"
  intl: "^0.15.2"
  path_provider: "^0.2.2"
  facebook_sign_in:
    path: FB-Signin-Plugin
  mframe_plugins:
    path: mframe_plugins
  stripe_plugin:
      path: stripe_plugin
  font_awesome_flutter: "^6.0.0"
  url_launcher: "^3.0.0"
  flutter_launcher_icons: "^0.2.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
```
