### ISSUE TITLE
"flutter packages get" removes entire packages directory.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#19859]
I was trying to create a new application that included an app and some packages.  I started by making an app using `flutter create --org=io.flutter generate`.  I removed the `lib` directory (I was actually making a command-line dart script that depended upon flutter libs), and copied in an entire directory hierarchy under a "packages" directory.

The pubspec.yaml looked like this:
```yaml
name: generator
description: Generator script for building API doc assets.

dependencies:
  flutter:
    sdk: flutter
  diagram_capture:
    path: packages/diagram_capture
  diagrams:
    path: packages/diagrams
  path_provider: any
  archive: 1.0.33
  process: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
```

Then I ran `flutter packages get` in the top level `generate` directory, which succeeded.

The directory hierarchy before I ran `flutter packages get` was this:

[start.log](https://github.com/flutter/flutter/files/2234470/start.log)

but *after* I ran `flutter packages get`, it was this:

[end.log](https://github.com/flutter/flutter/files/2234469/end.log)

It entirely removed the packages directory, and a total of 144 files!

_How and why did a score of files get deleted?_

Running `flutter packages get` a second time failed, of course: the pubspec depends upon packages in the packages dir.

Regardless of how screwed up my configuration was (and I have no doubt that things weren't right), it shouldn't be deleting non-generated existing files...
