### ISSUE TITLE
using firebase_ml_vision, failed to run on ios

### ISSUE THREAD

**Issue by sayurikunugi** [flutter/flutter#20786]
hello.
I'm trying to build an app using mlkit on flutter.
while my app run on android successfully, it failed to build when using iOS.

here's my pubspec.yaml
```yml
name: flutter_mlkit
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.4.5
  firebase_ml_vision: ^0.1.1
....
```

and when I try to run on iOS, I have following errors.
```
/Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.1.1/ios/Classes/TextDetector.m:9:7: Use of undeclared identifier 'textDetector'
/Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.1.1/ios/Classes/TextDetector.m:11:5: Use of undeclared identifier 'textDetector'
Parse Issue Group
/Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.1.1/ios/Classes/TextDetector.m:4:8: Expected identifier or '('
ARC Semantic Issue Group
/Users/kunugisayuri/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.1.1/ios/Classes/TextDetector.m:15:7: No known class method for selector 'detectInImage:completion:'
```
what's wrong with my project?
