### ISSUE TITLE
Some image assets are not imported correctly, only as white images

### ISSUE THREAD

**Issue by SteepSheep** [flutter/flutter#21151]
This issue first happened today, after running flutter upgrade today on the beta channel.
Now some image assets are only imported as white images (but the image alphas are correct). It doesn't seem to be related to image type or path.

Here's the flutter doctor result:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 10.0.17134.228], locale de-AT)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.1)
[√] Connected devices (2 available)

• No issues found!
```

Steps to reproduce:
1) Create a new flutter project
2) Import some images and edit the pubspec.yaml
3) Make an app that uses the images

Here's the asset part of my pubspec.yaml: (all the paths are correct, this configuration already worked before)
```
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/drawerlogo.png
   - assets/header_good.png
   - assets/logo.png
```

Here's an example build function:
```
Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Image.asset('assets/drawerlogo.png', height: 128.0,),
            new Image.asset('assets/header_good.png', height: 128.0,),
            new Image.asset('assets/logo.png', height: 128.0,),
          ],
        ),
      ),
      backgroundColor: Colors.grey,
    );
  }
```
Here's a screenshot of the example app:
![screenshot_1535532984](https://user-images.githubusercontent.com/10418840/44777180-2e8aac80-ab7a-11e8-9bab-3ad42c4adc03.png)

I attached the images I'm using (only the first one works):
![drawerlogo](https://user-images.githubusercontent.com/10418840/44777076-f4b9a600-ab79-11e8-91e9-f7ec2bef5f96.png)
![header_good](https://user-images.githubusercontent.com/10418840/44777077-f5523c80-ab79-11e8-9807-1560af65c8c0.png)
![logo](https://user-images.githubusercontent.com/10418840/44777078-f5523c80-ab79-11e8-914e-56d95402be52.png)
