### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by development-s365** [flutter/flutter#21421]
After updating from version 0.5.1 to 0.7.3 I get this message:
```
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because test_app depends on test_lib from path which requires SDK version <2.0.0, version solving failed.
pub upgrade failed (1)
```

Where test_app is a flutter application and test_lib is a package that I made and in pubsec i refer to this package with `path`

## Steps to Reproduce

1. Updating flutter from 0.5.1 to 0.7.3 on beta
2. Upgrading packages in self made package
3. Upgrading packages in application

## Logs

```
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because building_viewer depends on fw_flutter from path which requires SDK version <2.0.0, version solving failed.
pub upgrade failed (1)
```

## Things I've already tried

1. Reinstalling the SDK
2. Invalidating caches in Android Studio
3. `flutter clean`
4. `flutter update-packages`

Thanks in advance

**Comment by zoechi** [comment]
You need to fix `environment:` in `pubspec.yaml` to allow the Dart SDK version you are using (the one from Flutter)

```yml
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
```
The essential part is `<3.0.0`

**Comment by zoechi** [comment]
> test_lib from path which requires SDK version <2.0.0

That clearly states that `test_lib` claims to depend on SDK <2.0.0.
Can you please post the `pubspec.yaml` of `test_lib` and from `test_app`'s `pubspec.yaml` where it declares `test_lib` as dependency.

**Comment by development-s365** [comment]
test_app pubsec: 
```
...
dependencies:
  flutter:
    sdk: flutter

  sqflite: any
  path_provider: "^0.4.1"
  url_launcher: "^3.0.2"
  postgres: "^1.0.0-beta.1"
  crypto: ^2.0.3
  cupertino_icons: ^0.1.0
  http: "^0.11.3+16"
  shared_preferences: "^0.4.2"
  connectivity: "^0.3.1"
  pointycastle: ^1.0.0-rc2
  mailer2: ^1.2.3
  uuid: ^1.0.1
  device_info: ^0.2.1

  # Local packages
  # Version 0.5.0
  test_lib:
    path: "/home/programmeur/Software/android_studio_workspace_01/test_lib"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
...
```


test_lib pubsec: 
```
...
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: "^0.11.3+16"
  sqflite: any
  shared_preferences: ^0.4.2
  connectivity: "^0.3.1"
  path_provider: "^0.4.1"
  pointycastle: ^1.0.0-rc2
  mailer2: ^1.2.3
  postgres: "^1.0.0-beta.1"
  device_info: ^0.2.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
...
```

**Comment by zoechi** [comment]
Seems you left the `environment` part out from `test_lib` `pubspec.yaml`. Can you please add .

**Comment by development-s365** [comment]
That fixed it.
First I added the environment property to both pubsec files.

**Comment by ashish0910** [comment]
Running "flutter packages get" in gym...
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because flutter_calendar <0.0.3 requires SDK version >=1.8.0 <2.0.0 and flutter_calendar >=0.0.3 depends on date_utils ^0.0.1, every version of flutter_calendar requires date_utils ^0.0.1.
So, because date_utils <0.1.0 requires SDK version >=1.20.1 <2.0.0 and gym depends on flutter_calendar ^0.0.1, version solving failed.
pub get failed (1)
exit code 1


hey , i am also facing similar problem after updating flutter.
this is doctor command output .

[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.2 17C88, locale en-IN)
    • Flutter version 0.7.3 at /Users/ashishaggarwal/flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/ashishaggarwal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.



here is pubspec.yaml file

name: gym
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: any
  firebase_auth: any
  flutter_calendar: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

@zoechi 


thanks in advance

**Comment by zoechi** [comment]
@ashish0910 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

You need to check that you have the latest versions of dependencies.
```yml
flutter_calendar: ^0.0.1
```
should be changed to
```yml
flutter_calendar: ^0.1.0
```
For versions where the major number is `0` (like `0.1.2` the `^` only allows versions where the build major and minor is the same like `0.1.7`.
for versions where major number is `>=1` `^` allows all versions with the same major number like `1.19.42`

See also https://www.dartlang.org/tools/pub/versioning

**Comment by ashish0910** [comment]
@zoechi 

i wrote this 
flutter_calendar: ^0.0.4

i got this 

The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because flutter_calendar >=0.0.3 depends on date_utils <0.1.0 which requires SDK version >=1.20.1 <2.0.0, flutter_calendar >=0.0.3 is forbidden.
So, because gym depends on flutter_calendar ^0.0.4, version solving failed.
pub get failed (1)
exit code 1

**Comment by zoechi** [comment]
I think there is something wrong with `0.0.4` of `flutter_calendar`
I think it's better to report the issue in https://github.com/apptreesoftware/flutter_calendar

**Comment by CharlesCleveJr** [comment]
@zoechi  Can you identify where to place the "environment:" in pubsec.yaml.  I'm getting the following errors `Running "flutter packages get" in example...                    
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because myfavkpop_example depends on myfavkpop from path which requires SDK version <2.0.0, version solving failed.`

**Comment by zoechi** [comment]
@CharlesCleveJr 
```
name: myfavkpop
description: some description
version: 0.1.0
environment:
  sdk: '>=2.0.0 <3.0.0'
```

**Comment by CharlesCleveJr** [comment]
@zoechi This did not work.  I tried downloading dart 1.24 but it did not recognize the new file.  Is there a way to do this through flutter tools?

**Comment by zoechi** [comment]
> myfavkpop from path which requires SDK version <2.0.0, version solving failed.

Why does `myfavkpop` require `SDK version <2.0.0`?

I'd suggest you create a StackOverflow question where you post the content of `pubspec.yaml` from `myfavkpop`.

**Comment by kaushal312** [comment]
To fix this issue, update version of all "dependencies" and "dev_dependenciesin" in pubspecs.yaml file with a latest version of all packages from https://pub.dartlang.org/

**Comment by mudgesteve** [comment]
This is such a simple things and yet its like scared data.  Is there a web page that list current version numbers of any files that would go into the pubSpec.yaml file?

If not why not?

**Comment by mudgesteve** [comment]
i still have been hunting and pecking trying to follow along with a class for learning this stuff and have to take an HOUR or % HOUR break because of such a little SMALL amount of information needed.

Please advise this old man
thanks in advance

**Comment by zoechi** [comment]
@mudgesteve I'd suggest to ask a proper question on StackOverflow with the information what you try to accomplish, your `pubspec.yaml` and the full error output.

**Comment by mudgesteve** [comment]
I am sorry to be so unclear.

I have been trying to learn this stuff following dated video tutorials, as
a result (being very new to this) i am lost many times due to dated video
training.

I will try to learn faster

Thanks for your help

**Comment by zoechi** [comment]
@mudgesteve you might be looking for http://pub.dartlang.org where all packages that can be used with Flutter or Dart are listed will all available versions

**Comment by icestation1978** [comment]
is there any version of indux compatible with Dart 2.

**Comment by Tareque16** [comment]
The solution is in your plugins pubspec.yaml. Just change the environment sdk setup please

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"

**Comment by Sanaebadi97** [comment]
```
environment:
  sdk: ">=2.2.2 <3.0.0"
```

set it, and write "`any`" from ur package that not resolved

**Comment by irahulcse** [comment]
name: products_tutorial
description: A new Flutter project.

environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.11.3+16
  scoped_model: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages


I was trying to configure someone's old Flutter project, none of the above-given solutions had worked for me. Instead of I had to change the version of the scoped model to 1.0.1. Is there any way to rectify it.
@zoechi @Sanaebadi97

**Comment by AdamMusa** [comment]
enter this on your terminal it will fix all the reversion problem that sdk has to meet :
         flutter upgrade  --force

**Comment by alnaughty** [comment]
just upgrade your flutter version run flutter upgrade or if you want to specify sdk version run flutter version then it will return flutter versions and choose your version and run flutter version *your chosen version*

**Comment by SunnySkss** [comment]
Hello friends,
I am not able to get mobile number in Android API 5.0 with flutter app. I am using dependency mobile_number: ^0.0.4

**Comment by nitashadhingra** [comment]
```
name: image
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img2.jpg

```
  
OUTPUT:

> [image] flutter.bat pub get
> Running "flutter pub get" in image...                           
> Because image depends on flutter_test any from sdk which depends on image 2.1.4, image 2.1.4 is required.
> 
> So, because image is 1.0.0+1, version solving failed.
> pub get failed (1; So, because image is 1.0.0+1, version solving failed.)
> exit code 1


Please help me fix this
