### ISSUE TITLE
unable to load image

### ISSUE THREAD

**Issue by kavkum393** [flutter/flutter#21434]
```yml
name: earth_flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
assets:
  - android/images/bmi.JPG
```

CODE:

```dart
class _PlanetHomeState extends State<PlanetHome> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: AppBar(
        centerTitle: false,
        title: new Text('Weight On Planet X'),
        backgroundColor: Colors.green,
      ),
      body: new Container(
        child: new ListView(
          children: <Widget>[
            new Image.asset('Snapshot/earth_flutter_app/android/images/bmi.JPG'),
          ],
        ),
      ),
    );
  }
}
```
