### ISSUE TITLE
Cannot find a Git executable when I use Git dependency in yaml file.

### ISSUE THREAD

**Issue by xia-weiyang** [flutter/flutter#22032]
I installed Git, and I reinstall Git. The result is still 'Cannot find a Git executable'.I don`t know how to resolve this question.

This error info.
```
D:\Develop\flutter\flutter\bin\flutter.bat --no-color packages get
Active code page: 65001
Running "flutter packages get" in oldtime...
Active code page: 65001
Cannot find a Git executable.
Please ensure Git is correctly installed.
pub get failed (1)
Process finished with exit code 1
```

This is a part of my yaml file.
```yaml
#  multi_image_picker: ^2.1.1
#  不清楚git方式为什么不行，只能暂时使用本地path方式
  multi_image_picker:
    path: ../../multi_image_picker/
#    git:
#      url: git://github.com:otjiushig/multi_image_picker.git
  fab_dialer:
    git: https://github.com/otjiushig/flutter_fab_dialer.git
```
This is git
```
D:\Develop\Java\Projects\OldTime-Api\code>git --version
git version 2.18.0.windows.1
```
Run flutter doctor
```
D:\Develop\Java\Projects\OldTime-Api\code>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.7.3, on Active code page: 65001

Microsoft Windows [Version 10.0.17134.285], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code, 32-bit edition
[√] Connected devices (1 available)

! Doctor found issues in 2 categories.
```
