### ISSUE TITLE
Display list view on centre and webview on bottom 

### ISSUE THREAD

**Issue by knightkhan** [flutter/flutter#22800]
How can I combine two dart file one contain list view and other dart file contain web view 
I am beginer user 
Can any help what code I use to combine these two dart file

**Comment by zoechi** [comment]
The available webview plugins don't make this easy.
The upcoming https://github.com/flutter/plugins/tree/master/packages/webview_flutter supports being inlined.

This plugin is currently an unpublished preview, but can be tried with a git dependency already
by adding it to `pubspec.yaml` like

```yml
dependencies:
  webview_flutter:
    git:
      url: git@github.com:flutter/plugins.git
      path: packages/webview_flutter 
```
(See also https://www.dartlang.org/tools/pub/dependencies#git-packages)

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
