### ISSUE TITLE
Runtime Exception while getting firebase notification.

### ISSUE THREAD

**Issue by awazgyawali** [flutter/flutter#22901]
I was planning to add messaging to my Flutter app, I added the fire Flutter package. Added `google-services.json` to Android project and build the project. The project ran on android properly except I got runtime exception when app receives notification. I think this is because of different  dependency versions.

Here is the list of the packages that I am using on my project, I think all are up to date.

```yml
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: "^0.5.20"
  firebase_messaging: "^2.0.0"
  firebase_analytics: "^1.0.3"
  firebase_admob: "^0.6.1"
  firebase_core: "^0.2.5+1"
  firebase_database: "^1.0.4"
  firebase_storage: "^1.0.3"
  google_sign_in: "^3.2.1"
  image_picker: "^0.4.10"
  url_launcher: "^4.0.1"
  sqflite: "^0.12.1"
  path: "^1.6.2"
  path_provider: "^0.4.1"
  async_loader: "^0.1.2"
  flutter_image: "^1.0.0"
  flutter_search_bar: "^2.0.7"
  shared_preferences: "^0.4.3"
  groovin_material_icons: ^1.1.5`
```

Here is the issue that I am getting when I receive notification.

```
java.lang.NoSuchMethodError: No static method zzah()Lcom/google/firebase/iid/zzau; in class Lcom/google/firebase/iid/zzau; or its super classes (declaration of 'com.google.firebase.iid.zzau' appears in /data/app/com.brainants.meroshare-PlTXYg9vGisDS0Gq8tbcVA==/base.apk)
E/AndroidRuntime(23824):        at com.google.firebase.messaging.FirebaseMessagingService.zzb(Unknown Source:7)
E/AndroidRuntime(23824):        at com.google.firebase.iid.zzb.onStartCommand(Unknown Source:16)
E/AndroidRuntime(23824):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3802)
E/AndroidRuntime(23824):        at android.app.ActivityThread.access$1800(ActivityThread.java:207)
E/AndroidRuntime(23824):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
E/AndroidRuntime(23824):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(23824):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(23824):        at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(23824):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23824):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(23824):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/OPDiagnose(23824): getService:OPDiagnoseService NULL
D/OSTracker(23824): OS Event: crash
I/Process (23824): Sending signal. PID: 23824 SIG: 9
Lost connection to device.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by awazgyawali** [comment]
`[✓] Flutter (Channel dev, v0.9.6, on Mac OS X 10.14.1 18B50c, locale en-US)
    • Flutter version 0.9.6 at /Users/muskan/flutter
    • Framework revision 13684e4f8e (8 days ago), 2018-10-02 14:15:17 -0400
    • Engine revision f6af1f20ba
    • Dart version 2.1.0-dev.6.0.flutter-8a919426f0

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/muskan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • ONEPLUS A6000 • 3fabac74 • android-arm64 • Android 9 (API 28)

• No issues found!`

**Comment by siteslave** [comment]
Me too.

**Comment by rizkyandriawan** [comment]
me too, I think, my error:

`java.lang.NoSuchMethodError: No static method zzah()Lcom/google/firebase/iid/zzau; in class Lcom/google/firebase/iid/zzau; or its super classes (declaration of 'com.google.firebase.iid.zzau' appears in /data/app/xxxx.xxxx.xxxxx-xxxxxxxxx==/base.apk:classes2.dex)`

flutter doctor result:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
[!] VS Code (version 1.26.1)
[✓] Connected devices (1 available)
```

pubspec.yaml

```
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.5.20
  font_awesome_flutter: 8.0.1
  scoped_model: ^0.3.0
  cloud_firestore: ^0.8.1
  google_sign_in: ^3.0.5
  firebase_messaging: ^2.0.0
```
