### ISSUE TITLE
How to access assets from external packages?

### ISSUE THREAD

**Issue by anderscheow** [flutter/flutter#22934]
Package_A
An image under `lib/images/sample_photo.png`

Package_B yaml
```
dependencies:
  Package_A:
    path: ../Package_A

assets:
    - packages/images/sample_photo.png
```

When I try to use `Image.asset('packages/images/sample_photo.png')` on Package_A, it thrown unable to load asset
