### ISSUE TITLE
Does not includes all the assets under a folder from external package

### ISSUE THREAD

**Issue by anderscheow** [flutter/flutter#22944]
## Steps to Reproduce

Package_A
Several images under `lib/images/`

Package_B yaml
```
dependencies:
  Package_A:
    path: ../Package_A

assets:
    # Works by specifying the asset name
    - packages/Package_A/images/sample_photo.png

    # Does not work by just specifying the folder
    # Console throws Error: unable to find directory entry in pubspec.yaml: /Package_A/packages/Package_B/resources/images/
    - packages/Package_A/images/
```

## Logs

```
[✓] Flutter (Channel dev, v0.10.0, on Mac OS X 10.14 18A391, locale en-MY)
    • Flutter version 0.10.0 at /Users/anders/flutter
    • Framework revision d954ae6850 (35 hours ago), 2018-10-09 16:21:06 -0400
    • Engine revision bf377896ff
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/anders/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```
