### ISSUE TITLE
How to have fonts in a flutter package?

### ISSUE THREAD

**Issue by felangel** [flutter/flutter#22976]
I am trying to create a separate widget catalog as a flutter package and am unable to get my fonts to be recognized. The flutter app builds and runs just fine but the font is still the standard material font.

My setup is as follows:

fonts are located in `./my_ui_catalog/lib/fonts/my_font.ttf`
`./my_ui_catalog/pubspec.yaml`:
```
name: my_ui_catalog
description: custom ui catalog
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/my_ui_catalog/assets/my_logo.png
  fonts:
    - family: MyCustomFont
      fonts:
        - asset: packages/my_ui_catalog/fonts/my_font.ttf
          style: normal
```

`./pubspec.yaml`:

```
name: example
description: example

version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  my_ui_catalog:
    path: ./my_ui_catalog
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
`./lib/main.dart`:

```
import 'package:flutter/material.dart';

import 'package:my_ui_catalog/my_ui_catalog.dart';

void main() => runApp(
   MaterialApp(
        themeData: ThemeData(fontFamily: 'MyCustomFont'),
        home: Scaffold(
          body: (
            child: Center(
              child: Text('Hello'),
            )
          )
        )
      ),
    );
```
