### ISSUE TITLE
Build Failed image_picker:verifyReleaseResources

### ISSUE THREAD

**Issue by tiholic** [flutter/flutter#23044]
# SHOWSTOPPER
### !! Not able to release the app update to playstore due to this issue. Request to resolve ASAP

I'm facing the issue only after upgrading from 0.5.1-Beta to 0.9.4-Beta

## Steps to Reproduce

dependencies

```yaml
dependencies:
  flutter:
    sdk: flutter
  adhara: ^0.1.41
  fluttertoast: ^2.0.9
  font_awesome_flutter: ^8.1.0
  image_picker: 0.4.10
  video_player: ^0.6.5
  firebase_messaging: ^2.0.0
  flutter_local_notifications: 0.3.9
  image: ^2.0.4
  simple_moment:
      git: https://github.com/rinukkusu/simple_moment
  flutter_swiper: ^1.1.3
  path_provider: ^0.4.1
  flutter_socket_io: ^0.4.3
  html: ^0.13.3+3
```

Try to build 

## Logs

```
Initializing gradle...                                      17.7s
Resolving dependencies...                                   10.1s
Gradle task 'assembleRelease'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sqflite:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aa
pt2Exception: AAPT2 error: check logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --s
can to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 45s
Gradle task 'assembleRelease'... Done                       166.2s
Gradle task assembleRelease failed with exit code 1
```
## flutter doctor -v

```
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-IN)
    • Flutter version 0.9.4 at C:\flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Rohit\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Rohit\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • ONEPLUS A5010 • f0f79579 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```
