### ISSUE TITLE
Version Solving Failed

### ISSUE THREAD

**Issue by ajaynonstopio** [flutter/flutter#23914]
Here are the logs
```
Running "flutter packages get" in tour2_app...                  
Because no versions of flutter_html_view match >0.5.8 <0.6.0 and flutter_html_view 0.5.8 depends on flutter_custom_tabs ^0.3.0, flutter_html_view ^0.5.8 requires flutter_custom_tabs ^0.3.0.
Because flutter_custom_tabs 0.3.0 depends on url_launcher ^3.0.0 and no versions of flutter_custom_tabs match >0.3.0 <0.4.0, flutter_custom_tabs ^0.3.0 requires url_launcher ^3.0.0.
Thus, flutter_html_view ^0.5.8 requires url_launcher ^3.0.0.
So, because my_app depends on both url_launcher ^4.0.1 and flutter_html_view ^0.5.8, version solving failed.
```

pub get failed (1)
Process finished with exit code 1

 **pubspec.yaml**

```
 name: my_app
description: A new Flutter application.
 
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html_view: ^0.5.8
  url_launcher: ^4.0.1
 
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:

  
  uses-material-design: true
```

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_IN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 3.2)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0

```
