### ISSUE TITLE
dart analyzer exclude doesn't work

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#24656]
I have the following analyzer options:

```
include: package:flutter/analysis_options_user.yaml

analyzer:
  exclude:
    - 'bin/**'
    - 'lib/l10n/messages/**'
    - 'lib/**/*.*.dart'
    - 'ios/**'
    - 'android/**'
  errors:
    no_duplicate_case_values: error
    avoid_relative_lib_imports: error
    always_put_required_named_parameters_first: error
    always_declare_return_types: error
    invariant_booleans: error
    avoid_init_to_null: error
    mixin_inherits_from_not_object: ignore

linter:
  rules:
   ...
```

But it still complaining about excluded files... 

output: 

```
....
  lint • Prefer single quotes where they won't require escape sequences at lib/l10n/messages/error_messages_en.dart:139:5 • prefer_single_quotes
  lint • Prefer single quotes where they won't require escape sequences at lib/l10n/messages/error_messages_en.dart:139:69 • prefer_single_quotes
  lint • Prefer single quotes where they won't require escape sequences at lib/l10n/messages/error_messages_en.dart:140:5 • prefer_single_quotes
  lint • Prefer single quotes where they won't require escape sequences at lib/l10n/messages/error_messages_en.dart:140:72 • prefer_single_quotes
  lint • Prefer single quotes where they won't require escape sequences at lib/l10n/messages/error_messages_en.dart:141:5 • prefer_single_quotes
  lint • Prefer single quotes where they won't require escape sequences at lib/l10n/messages/error_messages_en.dart:141:70 • prefer_single_quotes
  lint • Prefer single quotes where they won't require escape sequences at lib/l10n/messages/error_messages_en.dart:142:5 • prefer_single_quotes
hint • The value of the field '_isAudioConnected' isn't used at lib/dongle/dongle_manager.dart:62:8 • unused_field
  hint • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib/merchant/models/merchant.dart:12:7 • must_be_immutable
  hint • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib/transactions/models/transaction.dart:22:7 • must_be_immutable
  hint • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib/transactions/models/transaction_event.dart:12:7 • must_be_immutable
  hint • The value of the local variable 'newModel' isn't used at lib/transactions/models/transaction_event.jorm.dart:99:24 • unused_local_variable
  hint • The value of the local variable 'newModel' isn't used at lib/transactions/models/transaction_event.jorm.dart:116:24 • unused_local_variable
...
```

Am I doing something wrong ? 

```
[✓] Flutter (Channel beta, v0.11.7, on Mac OS X 10.14.1 18B75, locale fr-FR)
    • Flutter version 0.11.7 at /Users/jaumard/flutter
    • Framework revision 7a005e1dcd (3 days ago), 2018-11-19 11:14:05 -0500
    • Engine revision 2e06da3df9
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK at /Users/jaumard/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] Connected device (1 available)
    • iPhone 5s • D4458C05-61F9-435E-B62E-BBA5E15D2C01 • ios • iOS 12.1 (simulator)

• No issues found!

```
