### ISSUE TITLE
Google map not displaying after updating flutter version

### ISSUE THREAD

**Issue by ZeroCool00** [flutter/flutter#24774]
## Steps to Reproduce

until now its working fine in android, but for iOS support i upgrade Flutter version and now it's not showing Google Maps on both platform.

What actually happening is:
Google Maps now overlapping whole screen, even my appbar is missing now, but bottombar is still there. I think now it's displaying blank webview top on whole view.
code: 

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      key: globalKey,
      appBar: AppBar(
        backgroundColor: backgroundColor,
        centerTitle: false,
        title: appBarTitle,
        actions: showActions()
      ),
      drawer: new Drawer(
            elevation: 10.0,
            child: new DrawerComponent()
      ),
      body: Container(
        child: mapWidget()
      ),
    );
  }

Widget mapWidget() {
    return FractionallySizedBox(
      child: GoogleMap(
                onMapCreated: _onMapCreated,
                options: _googleMapOptions,
              ),
    );
  }
```
## Logs
No logs when map screen opening.
-->

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.11.9, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.11.9 at /MyDrive/flutter
    • Framework revision d48e6e433c (6 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/micra/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode_10.app/Contents/Developer
    • Xcode 10.0, Build version 10A254a
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • motorola one power • ZF6223RHJL • android-arm64 • Android 8.1.0 (API 27)
```

![screenshot_1543314695](https://user-images.githubusercontent.com/18139594/49075916-d5581500-f25d-11e8-831e-2fa39faa4288.png)

**Comment by ZeroCool00** [comment]
@zoechi can you tell me how to revert back to previous version?

**Comment by zoechi** [comment]
You can use `ref: ...` to use a specific commit or tag https://www.dartlang.org/tools/pub/dependencies#git-packages

**Comment by amirh** [comment]
The error on the second screenshot looks like it is using a Flutter version older than https://github.com/flutter/flutter/commit/707eaf5edf4342c62ae647b7e0cac8fc1b3bac50

Please try to use the latest Flutter version, and the latest google_maps_flutter version.

**Comment by zoechi** [comment]
I copied the screenshot from #23199 because the link to the issue wasn't too clear.
@ZeroCool00 please clarify or update the issue with a recent screenshot.

**Comment by ZeroCool00** [comment]
old screen issue is already been solved, there is no need to write second screen.. updated. i didnt put iphone screenshot, bcz its a same as android.

**Comment by amirh** [comment]
Which google_maps_flutter version are you using? can you share the `pubspec.yaml` for your app?

**Comment by ZeroCool00** [comment]
here my whole pubspace:

```
name: Cragger
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
   git:
     url: git://github.com/flutter/plugins
     path: packages/google_maps_flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.19.0 
  http: ^0.12.0
  fluttertoast: ^2.1.1
  shared_preferences: ^0.4.3
  flutter_svg: ^0.6.1+1
  intl: ^0.15.7
  flutter_staggered_grid_view: "^0.2.3"
  carousel_pro: ^0.0.13
  charts_flutter: ^0.4.0
  flutter_facebook_login: ^1.1.1
  flutter_charts: ^0.1.10
 # flutter_twitter_login: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/home-icon.png
  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets/fonts/SF-UI-Display-Medium.ttf


```
