### ISSUE TITLE
The current Flutter SDK version is 0.0.0-unknown.

### ISSUE THREAD

**Issue by LilySny** [flutter/flutter#24956]
I'm trying to add the path_provider package in my dependencies, but i always get this error:

```
The current Flutter SDK version is 0.0.0-unknown.


Because lista_tarefas depends on path_provider >=0.4.0 which requires Flutter SDK version >=0.1.4 <2.0.0, version solving failed.

pub upgrade failed (1)
```

I've already tried:

    packages get
    packages upgrade
    flutter upgrade
    flutter clean
    Write other version in enviroment variable in pugspec.yaml
    Delete enviroment variable in pugspec.yaml
    Use an older version of path_provider
    Invalidating caches in Android Studio
    Uninstalling and installing again flutter plugin 

My current pubspec.yaml file:

...
```

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: "^0.4.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
```
