### ISSUE TITLE
Problem with adding external libraries

### ISSUE THREAD

**Issue by tsheetiz** [flutter/flutter#25441]
Hello,

I was trying to add this following line of code to my project: 

`import 'package:http/http.dart' as http;

But I get this error: Target of URI doesn't exist: : "package:http/http.dart"

I tried to add the following to my pubspec.yaml file:

```yml
name: barcode

version: 0.0.1

description: A simple console application.

dependencies:

http:
```

And then I go into android studios and then click Get Dependencies to download the libraries, but I get this error: 

```
Error on line 4, column 1 of pubspec.yaml: Duplicate mapping key.
name: barcode
^^^^

pub get failed (65)`
```
Hoping someone can help me out, thanks!
