### ISSUE TITLE
Error on line 12, column 30 of pubspec.lock: Expected a key while parsing a block mapping.     dependency: "direct main"cupertino_icons                              ^  pub get failed (65)

### ISSUE THREAD

**Issue by caiorngcai** [flutter/flutter#25710]
I meet this question when i run packages get:

```
Running "flutter packages get" in myosc...                      
Error on line 12, column 30 of pubspec.lock: Expected a key while parsing a block mapping.
    dependency: "direct main"cupertino_icons
                             ^

pub get failed (65)
```
this is my pubspec.yaml：
```
name: flutter_osc
description: An oschina Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  flutter_webview_plugin: ^0.3.0+2
  image_picker: ^0.4.10
  shared_preferences: ^0.4.3
  event_bus: ^1.0.1
  barcode_scan: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/ic_avatar_default.png
    - images/ic_nav_news_normal.png
    - images/ic_nav_news_actived.png
    - images/ic_nav_tweet_normal.png
    - images/ic_nav_tweet_actived.png
    - images/ic_nav_discover_normal.png
    - images/ic_nav_discover_actived.png
    - images/ic_nav_my_normal.png
    - images/ic_nav_my_pressed.png
    - images/ic_discover_gist.png
    - images/ic_discover_git.png
    - images/ic_discover_nearby.png
    - images/ic_discover_pos.png
    - images/ic_discover_scan.png
    - images/ic_discover_shake.png
    - images/ic_discover_softwares.png
    - images/ic_arrow_right.png
    - images/ic_my_blog.png
    - images/ic_my_message.png
    - images/ic_my_question.png
    - images/ic_my_recommend.png
    - images/ic_my_team.png
    - images/ic_test.png
    - images/ic_hongshu.jpg
    - images/ic_img_default.jpg
    - images/ic_comment.png
    - images/cover_img.jpg
    - images/leftmenu/ic_xiaoheiwu.png
    - images/leftmenu/ic_fabu.png
    - images/leftmenu/ic_about.png
    - images/leftmenu/ic_settings.png
    - images/ic_osc_logo.png
    - images/ic_add_pics.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```
 I am confused because i run the same pubspec.yaml in an other project ，it can work.
