### ISSUE TITLE
Target of URI doesn't exist

### ISSUE THREAD

**Issue by maggot99999** [flutter/flutter#25838]
## Steps to Reproduce

1. Had Android Studio before
2. Have **Flutter SDK** in `C:\Flutter\` directory
3. Followed set up instructions successfully
4. Created **New Project Flutter** in **Android Studio**
5. Got to Step 2 successfully in https://flutter.io/docs/get-started/codelab
6. Added `english_words: ^3.1.0` to **pubspec.yaml** as follows:

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0`
```

7. Run `flutter packages get`.
8. Checked **pubspec.lock**. Got the following:

```
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2"
  english_words:
    dependency: "direct main"
    description:
      name: english_words
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.5"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
```
9. Added line `import 'package:english_words/english_words.dart';` to **main.dart** as follows:
https://gist.github.com/maggot99999/6ac13f31e436a37b15ffe967672062c9

10. States such plugin does not exists

![image](https://user-images.githubusercontent.com/10854805/50510782-ed040280-0a82-11e9-8a2d-b555245a4195.png)

## Logs

> flutter analyze

```
Analyzing startup_namer...

   info - Unused import: 'package:english_words/english_words.dart' - lib\main.dart:2:8 - unused_import

1 issue found. (ran in 18.0s)
```

> flutter doctor -v

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
    • Flutter version 1.0.0 at C:\Flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\maggo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Mi A2 Lite • 4a8122e29905 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```
