### ISSUE TITLE
App crashes in runtime after adding plugins

### ISSUE THREAD

**Issue by KarimMohamed2005** [flutter/flutter#25862]
## I have a project and it 's now in deployment in pubspec.yaml I have some plugins that i need 
 ```yml
  file_picker: any
  location: any
  device_calendar: any
  flutter_pdf_viewer: any
  http: any
  sqflite: any
  path_provider: any
  url_launcher: any
  share: any
  shared_preferences: any
  datetime_picker_formfield: any
  fluttertoast: any
  google_maps_flutter: any
  cupertino_icons: any
  firebase_messaging: any
  image_picker: any
  flutter_local_notifications: any
```
# after run 
### flutter build apk
```
> * What went wrong:
> Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:appcompat-v7' has different version for the compile (27.1.0) > and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution
```
 but after adding this code to 
```gradle
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.0"
            }
        }
    }
}
 ```
to android/build.gradle it solved but now I had a many problems in runtime and app always crashes anyone can help ?
