### ISSUE TITLE
Flutter App 211 MB after release with 8 photos Only

### ISSUE THREAD

**Issue by KarimMohamed2005** [flutter/flutter#25996]
I have a **Flutter Application** and I was running it normal but now it is running infinite at
` Installing build/app/outputs/apk/app.apk... `
and I told myself sure this isn't normal and I was trying to build it by 
` flutter build apk ` 
and drag and drop into my emulator but surprise it 's **211 MB** and FYI I haven't added anything more than my past code and before this issue it was **33 MB** in this app and after this I wanted to know why this do for me I was need to check about apk in Android Studio and another surprise this is because only 8 photos in **assets**!
and each photo doesn't reach 1-2 MB 
![Assets](https://user-images.githubusercontent.com/37942217/50623013-86fffb00-0f1a-11e9-8777-7d81ddf081e8.png)
Anyone have solution or Why this is doing for me ?

**Comment by KarimMohamed2005** [comment]
FYI again it's also running **infinity** when I am drop this apk in _Emulator_

**Comment by KarimMohamed2005** [comment]
![screenshot from 2019-01-03 05-54-26](https://user-images.githubusercontent.com/37942217/50623207-0fcb6680-0f1c-11e9-83e6-8422cfe9214e.png)

**Comment by kangwang1988** [comment]
Paste your pubspec.yaml and whole content of flutter_assets please.
@KarimMohamed2005

**Comment by KarimMohamed2005** [comment]
```
name: gocloud
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  file_picker: any
  location: any
  device_calendar: any
  flutter_pdf_viewer: any
  http: any
  sqflite: any
  path_provider: any
  url_launcher: any
  share: any
  shared_preferences: any
  datetime_picker_formfield: any
  fluttertoast: any
  google_maps_flutter: any
  cupertino_icons: any
  #firebase_messaging: any
  image_picker: any
  flutter_local_notifications: any
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/background.png
    - background_al.png
    - B.G_verify.png
    - assets/icon_membership.png
    - assets/doctor.png
    - assets/Lab.png
    - assets/facility.png
    - assets/card_holder.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```
