### ISSUE TITLE
Crash when running Archive/Exported ipa

### ISSUE THREAD

**Issue by kokizzu** [flutter/flutter#26215]
This only happened when `Archive` the App, then installing from `Devices and Simulators` which is what Apple Review Board do.
This doesn't happened when using `flutter run`

The log from device:
https://pastebin.com/8Nh8qiiD

Which part that causes this?

my App dependencies:
```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  image: "^2.0.0"
  args: "^1.5.0"
  dart_config:
      git:
        url: https://github.com/MarkOSullivan94/dart_config.git
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  splashscreen: ^1.1.0
  shared_preferences: ^0.4.2
  font_awesome_flutter: ^8.0.1
  uuid: ^1.0.3
  intl: ^0.15.7
  http: ^0.12.0
  moment: ^0.0.1
  flutter_web_view: 
    path: flutter_webview
  image_picker_saver: ^0.1.0
  video_player: ^0.7.2
  dio: 1.0.9
  cached_network_image: ^0.5.1
  animated_text_kit: ^1.2.0
  unicorndial: ^1.1.5
  firebase_messaging: ^2.1.0
  percent_indicator: ^1.0.10
  flutter_youtube: ^1.1.4
  device_info: ^0.3.0
  badge: ^0.0.3
  stack_trace: ^1.9.2
  modal_progress_hud: ^0.1.2
  url_launcher: ^4.0.3
  package_info: ^0.3.2
  autocomplete_textfield: ^1.6.4
```

the flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
[!] VS Code (version 1.30.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
