### ISSUE TITLE
Icons Rendered to Chinese character on android

### ISSUE THREAD

**Issue by gabeaventh** [flutter/flutter#26346]
Icons Rendered to Chinese character on android, and its only happened in my current project
## Steps to Reproduce

1. its starting to render chinese character on android since i push and pull it from my own gitlab repo
2. at first menu icon turns into chinese character on android when i use Icon(Icons.menu) so i use FontAwesomeIcon instead to fix it
3. now it shown on showDatePicker() back and forward icon

## Logs

flutter run --verbose
https://pastebin.com/1tdwWgtA

flutter analyze
https://pastebin.com/KK0tzyEk

flutter doctor -v
https://pastebin.com/cgrA1cdG

![whatsapp image 2019-01-09 at 9 23 40 pm](https://user-images.githubusercontent.com/7519522/50949492-040e1000-14d9-11e9-9b1a-92413eac8469.jpeg)

**Comment by gabeaventh** [comment]
inside my pubspec.yaml

```
name: some_app
description: some_app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model:
  bloc:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_bloc:

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.0.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/login_logo.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

```
