### ISSUE TITLE
Error when pubspec.yaml contain chinese

### ISSUE THREAD

**Issue by fengqiangboy** [flutter/flutter#26340]
## Steps to Reproduce

1、Edit `pubspec.yaml` description with chinese, like :
 
```
name: bbq

#here have some chinese
description: flutter项目

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
```

2、use flutter_launcher_icons plugin

3、run flutter_launcher_icons `flutter packages pub run flutter_launcher_icons:main `

4、If I delete chinese character in `pubspec.yaml`, It fixed.

## Logs

```
Unhandled exception:
Error on line 2, column 25: Unexpected character.
description: flutteré¡¹ç�®
                        ^
#0      Parser.parse (package:yaml/src/parser.dart:50:7)
#1      Loader._loadMapping (package:yaml/src/loader.dart:171:23)
#2      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#3      Loader._loadDocument (package:yaml/src/loader.dart:62:20)
#4      Loader.load (package:yaml/src/loader.dart:54:20)
#5      loadYamlDocument (package:yaml/yaml.dart:51:25)
#6      loadYamlNode (package:yaml/yaml.dart:42:5)
#7      loadYaml (package:yaml/yaml.dart:34:5)
#8      YamlConfigParser.parse (package:dart_config/parsers/config_parser_yaml.dart:12:15)
#9      Config.readConfig.<anonymous closure> (package:dart_config/config.dart:44:25)
#10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
pub finished with exit code 255
```
