### ISSUE TITLE
[Feature request] [google_maps_flutter] : Support for on map click listener

### ISSUE THREAD

**Issue by Muhammad-saafan** [flutter/flutter#26761]

**Comment by Muhammad-saafan** [comment]
I am making ride hailing app but the problem is I can't make the user choose his destination by pointing onto the map to choose his destination So i need onMapClickListener badly pleeeeease

**Comment by zxc123zxc** [comment]
I have made branch with fix for Android.
I hope it helps.

If someone can help with iOS version - ping me pls
https://github.com/zxc123zxc/plugins/tree/26761-map-tap-events/packages/google_maps_flutter

```
  google_maps_flutter:
    git:
      ref: 26761-map-tap-events
      url: https://github.com/zxc123zxc/plugins.git
      path: packages/google_maps_flutter
```


```
    controller.onMapTapped.add((coord) {
      print(coord);
    });

    controller.onMapLongTapped.add((coord) {
      print(coord);
    });
```
