### ISSUE TITLE
flutter_local_notifications fails to build

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#26933]
When trying to run an app with the `flutter_local_notifications` plugin, I get the following error message. This started happening after adding said plugin.

```
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-compat' has different version for the compile (26.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution
```

These are my dependencies in `pubspec.yaml`:

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences:
  url_launcher:
  firebase_messaging:
  share:
  http:
  connectivity:
  package_info:
  flutter_local_notifications:
```
