### ISSUE TITLE
The method 'signInWithPhoneNumber' isn't defined for the class 'FirebaseAuth.'

### ISSUE THREAD

**Issue by Yogita75** [flutter/flutter#27119]
this is my `signInWithPhoneNumber` method 
```dart
 Future<void> _signInWithPhoneNumber() async {
    final errorMessage = "We couldn't verify your code, please try again!";
    await _auth
        .signInWithPhoneNumber(
        verificationId: _verificationId, smsCode: smsCodeController.text)
        .then((user) async {
      await _onCodeVerified(user).then((codeVerified) async {
        this._codeVerified = codeVerified;

        FirebaseAuth _auth = FirebaseAuth.instance;

        debugPrint('auth:_auth.currentUser()');
        print(_auth.currentUser());
        FirebaseUser  mCurrentUser = await _auth.currentUser();
        print('Hello ' + mCurrentUser.displayName.toString());

        setState(() {
          mCurrentUser != null ? accountStatus = 'Signed In' : 'Not Signed In';
        });


        Logger.log(
          TAG,
          message: "Returning ${this._codeVerified} from _onCodeVerified",
        );
        if (this._codeVerified) {
          await _finishSignIn(user);
        } else {
          _showErrorSnackbar(errorMessage);
        }
      });
    }, onError: (error) {
      print("Failed to verify SMS code: $error");
      _showErrorSnackbar(errorMessage);
    });
  }
```

Here is my `pubspec.yaml` file--

```yml
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  country_pickers: ^1.0.1
  firebase_core: ^0.3.0
  firebase_auth: ^0.8.0
  google_sign_in: ^3.2.4
  firebase_analytics: ^1.0.4
  firebase_database: ^1.0.5
  image_picker: ^0.4.12
  firebase_storage: ^1.0.4
  image_picker_ui: ^0.1.2
  transparent_image: ^0.1.0
  intl: ^0.15.2
  dropdown_menu: ^1.1.1
  carousel_pro: ^0.0.13
  cloud_firestore: ^0.9.0
  fluttertoast: ^2.2.6
  cached_network_image: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/chat.png
    - images/fast.jpg
    - images/power.jpg
    - images/secure.png
```
