### ISSUE TITLE
firebase_messaging not getting notifications on iOS TestFlight

### ISSUE THREAD

**Issue by bbedward** [flutter/flutter#27143]
I recently pushed an application I made with Flutter to iOS TestFlight, and just recently pushed an update on TestFlight that added push notifications via Firebase messaging.

The notifications work as-expected on Android, and they worked as expected on iOS during testing. However, after pushing to TestFlight the push notifications do not work on the build installed from testflight. I'm presuming it's some type of certificate issue but I'm not sure what.

I'm using `firebase_messaging: 2.1.0`, and I added the app to the firebase console and uploaded the `.p8` file, APNs authentication key that I created in the apple developer portal. As well as enabled push notifications in xcode and added the `GoogleServices-info.plist`.

In the app, I register firebase in my main page's `initState` method like

```dart
    // Register push notifications
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
      },
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
      },
    );
    _firebaseMessaging.requestNotificationPermissions(
        const IosNotificationSettings(sound: true, badge: true, alert: true));
    _firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      if (settings.alert || settings.badge || settings.sound) {
        SharedPrefsUtil.inst.getNotificationsSet().then((beenSet) {
          if (!beenSet) {
            SharedPrefsUtil.inst.setNotificationsOn(true);
          }
        });
        _firebaseMessaging.getToken().then((String token) {
          if (token != null) {
            RxBus.post(token, tag: RX_FCM_UPDATE_TAG);
          }
        });
      } else {
        SharedPrefsUtil.inst.setNotificationsOn(false).then((_) {
          _firebaseMessaging.getToken().then((String token) {
            RxBus.post(token, tag: RX_FCM_UPDATE_TAG);
          });
        });
      }
    });
    _firebaseMessaging.getToken().then((String token) {
      if (token != null) {
        RxBus.post(token, tag: RX_FCM_UPDATE_TAG);
      }
    });
```

I use the token to send notifications to individual clients, and can verify that the app server is receiving the tokens and sending the notification message I expect - but the client is not receiving the message.

Again it works when deploying to an iPhone in development, works on Android, just isn't working on TestFlight and I can't seem to figure out why so was hoping for some help/insight.

I've read about sandbox and production mode for APN authentication, but the newer APNs authentication key I'm using only has 1 certificate (not a separate one for dev/release mode), and I don't really see anything in the messaging API relating to that.

Thanks

**Comment by zoechi** [comment]
Might be a dup of #21443

**Comment by bbedward** [comment]
Fwiw here are my dependencies

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Securley store data in a keystore
  flutter_secure_storage: ^3.1.3

  # Nano core functions
  flutter_nano_core: ^1.0.1

  # Shared prefs
  shared_preferences: ^0.4.3

  # Flare for animations
  flare_flutter: ^1.2.0

  # Websockets
  web_socket_channel: ^1.0.9

  # Platform-specific build info
  package_info: ^0.3.2+1

  # Device-specific info
  device_info: ^0.3.0

  # JSON Serialization
  json_annotation: ^2.0.0

  # Localization
  intl: ^0.15.7

  # BigDecimal alternative
  decimal: ^0.3.3

  # Logger
  logging: ^0.11.3+2

  # Native webview plugin
  flutter_webview_plugin: ^0.3.0+2

  # SQLite
  sqflite: ^1.0.0

  # Android/iOS path provider
  path_provider: ^0.4.1

  # TouchID/FaceID
  local_auth: ^0.3.1

  # RXDart
  rxdart : ^0.20.0

  # SVG
  flutter_svg: ^0.10.3
    
  # QR Codes
  qr_flutter: ^1.1.6 # Generator
  barcode_scan:
    git:
      url: https://github.com/bbedward/flutter_barcode_reader.git
      ref: master

  # Share files
  share:
    git:
      url: https://github.com/pboos/plugins.git
      path: packages/share
      ref: feature/shareFile

  # File picker
  file_picker: ^1.1.1

  # Deep link support
  uni_links: ^0.1.4

  # HTTP client
  http: ^0.12.0+1

  # Vibrate
  vibrate:
    git:
      url: https://github.com/bbedward/flutter_vibrate.git
      ref: master

  # Toast
  oktoast: ^2.1.4

  # Push notifications - TODO update to newer androidX version
  firebase_messaging: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.3
  json_serializable: ^2.0.1
  intl_translation: ^0.17.2
```

Not using flutter_local_notifications and as stated, I'm only having issues with the builds uploaded to appstore connect via testflight, am getting notifications on dev builds on iOS
