### ISSUE TITLE
Firebase Auth missing a lot of sign in methods

### ISSUE THREAD

**Issue by kenwen** [flutter/flutter#27427]
## Steps to Reproduce

Firebase Auth methods for Google Sign In, Phone Sign appear to be missing.
```
final GoogleSignIn googleSignIn = GoogleSignIn();
final FirebaseAuth auth = FirebaseAuth.instance;
GoogleSignInAccount googleUser = await googleSignIn.signIn();
GoogleSignInAuthentication googleAuth = await googleUser.authentication;
auth.signInWithGoogle <- this method doesn't exist
```

pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons:
  cloud_firestore:
  cloud_functions:
  firebase_auth: ^0.8.0+1
  firebase_core:
  firebase_messaging: 3.0.0
  firebase_storage:
  google_sign_in: 4.0.0
  image:
  shared_preferences:
```
I've tried cleaning build, clearing the packages cache, shaking my fist at my laptop, no joy. The method just doesn't appear to exist. Happening across all projects as well.

## Logs

Flutter doctor output
```
Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale en-GB)
    • Flutter version 1.1.8 at /Users/kenwen/Dev Tools/flutter
    • Framework revision 985ccb6d14 (4 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kenwen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```
