### ISSUE TITLE
Can't compile when firebase_remote_config is installed

### ISSUE THREAD

**Issue by Butzlabben** [flutter/flutter#27493]
Hey there,

when I am using `firebase_remote_config`, I get a big exception during compiling:
```
Exception:
Launching lib\main.dart on ONE E1003 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_remote_config-0.1.0\android\src\main\java\io\flutter\plugins\firebase\firebaseremoteconfig\FirebaseRemoteConfigPlugin.java:5: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_remote_config-0.1.0\android\src\main\java\io\flutter\plugins\firebase\firebaseremoteconfig\FirebaseRemoteConfigPlugin.java:82: error: cannot find symbol
                    public void onComplete(@NonNull Task<Void> task) {
                                            ^
  symbol: class NonNull
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_remote_config:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle task assembleDebug failed with exit code 1
```
`pubspec.yaml`
```yml
name: App
description: My app

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.2
  http: ^0.12.0+1
  path_provider: 0.5.0
  date_format: 1.0.6
  audioplayer: ^0.5.2
  firebase_analytics: ^2.0.0
  flutter_html: ^0.8.2
  share: ^0.6.0
  url_launcher: ^5.0.0
  firebase_remote_config: ^0.1.0


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

Output of flutter doctor -v:
```
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17763.253], locale de-DE)
    • Flutter version 1.1.8 at C:\Program Files\flutter
    • Framework revision 985ccb6d14 (4 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Daniel\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[!] VS Code (version 1.28.2)
    • VS Code at C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • ONE E1003 • 4a6eac49 • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 2 categories.
```
