### ISSUE TITLE
Meta issue for the difficulty of using assets with Flutter

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#27802]
I wanted to try and highlight how several outstanding issues related to assets really hurt productivity:

* [ ] Including all the files in a directory is only supported for the _current_ package:

  ```yaml
  flutter:
    assets:
      - assets/country_flags/ # OK
      - packages/country_flag_icons/assets/ # Silently does not work
  ```

  Related: https://github.com/flutter/flutter/issues/22944

* [x] Flutter _packages_ (i.e. not apps) cannot declare their own assets:

  ```yaml
  # A package I'd like to host on Pub or GitHub.
  name: country_flag_icons

  flutter:
    assets:
      - assets/country_flags/
  ```

  ```yaml
  name: my_app

  dependencies:
    country_flag_icons: ^1.0.0
  ```

  ... will result in runtime asset errors. See above issue for why this is difficult to workaround.

  Related: https://github.com/flutter/flutter/issues/22921

* [ ] Asset inclusion only works by individual file or individual folder

  ```yaml
  # Let me write...
  flutter:
    assets:
      - assets/icons/**.png
  ```

  Related: https://github.com/flutter/flutter/issues/27801

* [x] Assets added to a directory are not picked up during hot reload/restart:

  ... leading the need of killing and restarting the app from scratch when working with assets.

  Related: https://github.com/flutter/flutter/issues/18896

* [x] Assets are not usable in (non-driver) tests:

  ... meaning that testing packages that provide assets is very difficult.

  Related: https://github.com/flutter/flutter/issues/12999
