### ISSUE TITLE
Support wildcard/globs in `flutter: assets:` YAML

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#27801]
See https://github.com/flutter/flutter/issues/4890#issuecomment-407327749.

I'd like to write:

```yaml
flutter:
  assets:
    - assets/icons/**.png
```

... instead of ...

```yaml
flutter:
  assets:
    - assets/icons/country_flags/
    - assets/icons/currency_codes/
    - assets/icons/credit_card_vendors/
```

**Comment by jonahwilliams** [comment]
Looked into this today.

The asset parsing code is in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/asset.dart#L524. The difficulty is that we cannot just start using Globs as

- the flutter tool uses interfaces which implement dart:io, but aren't dart:io. Glob's listSync returns a different file type than we expect and its not compatible with our test infra.
- The resolution logic is fairly specialized, and should probably just be refactored as a part of this change. It might make more sense to build out our own glob logic.

**Comment by marnberg** [comment]
Thank you @jonahwilliams for looking into this. This is been on our watch list for a long time since we have images in assets/1.0x  assets/2.0x and so on. Flutter picks the right asset listing the path without the scale factor but currently we have to list every asset in the yaml file. This is a big issue because we build multiple versions of our app with different assets.

**Comment by ph55** [comment]
Another use case.
Loading query language files. For example GraphQL files. They will usually will stick to it's library and won't be placed in one directory.

```
/lib/user/get_users.gql
/lib/user/register.gql
/lib/todo/get_todos.gql
```

So pattern in this case would be any `.gql` file in `lib` folder:
```yaml
flutter:
  assets:
    - lib/**/*.gql
```

**Comment by nimi0112** [comment]
@matanlurey  @jonahwilliams  what is wrong with writing 

``` yaml

assets:
    - assets/images/
```

**Comment by mhmdanas** [comment]
@nimi0112 I don't know about the others, but I use macOS, and I caught .DS_Store files being put in assets.

**Comment by JaffaKetchup** [comment]
Bumping this 2 years later :)

As a workaround, what if there was a `flutter pub registerassets` tool that read from a file supporting wildcards and auto generated the necessary pubspec?

**Comment by Conrad33** [comment]
Another use case is with the new [Asset transformation](https://docs.flutter.dev/ui/assets/asset-transformation#specifying-asset-transformations) feature. For example something like:
```yaml
flutter:
  assets:
    - path: assets/images/
      transformers:
        - package: vector_graphics_compiler
```
doesn't work if the `images` folder contains anything other than `.svg` files. 
Instead we could do:
```yaml
flutter:
  assets:
    - assets/images/
    - path: assets/images/**.svg
      transformers:
        - package: vector_graphics_compiler
```
and only transform the assets we want to, ignoring any `.png` and `.jpg` files in the same folder.
