### ISSUE TITLE
cloud_firestore release error AndroidX

### ISSUE THREAD

**Issue by DarthWindu** [flutter/flutter#27901]
There appear to be two missing resources in `values.xml` from the release output from `cloud_firestore`.

## Steps to Reproduce

1. migrate project to AndroidX using Android studio
2. add `cloud_firestore`  and `shared_preferences` as flutter dependencies
3. run `flutter build apk`

Expected output:
```

         *********************************************************
WARNING: This version of shared_preferences will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cloud_firestore:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  F:\...\build\cloud_firestore\intermediates\res\merged\release\values\values.xml:276: error: resource android:attr/fontVariationSettings not found.
  F:\...\build\cloud_firestore\intermediates\res\merged\release\values\values.xml:277: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

## Flutter Doctor

```
$ flutter doctor -v
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.556], locale en-US)
    • Flutter version 1.1.8 at C:\flutter_windows_v0.11.11-beta\flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Jackie\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 182.5124
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\Jackie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • SM N910T • c253d892 • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.
```
I'd be happy to add my `pubspec.yaml` if that'd help.

**Comment by mklim** [comment]
Thanks for filing an issue!

It's really common to still see that error if there's AndroidX incompatibilities somewhere in the app still, even though the message looks completely unrelated. You mention that you've already migrated, so I'm guessing that either the migration missed something somehow or there's still an issue with another plugin you're including being incompatible.

> I'd be happy to add my `pubspec.yaml` if that'd help.

That would be really useful, thanks.

**Comment by DarthWindu** [comment]
Let me know how I can help :)

```
name: timeswap_core
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
# 
# the number after '+' is the version code -- version name is before
version: 0.1.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cloud_firestore:

  firebase_auth:
  
  google_sign_in:

  flutter_facebook_login:

  flutter_firebase_ui:
  
  dotenv:

  colorize:

  progress_hud:

  square_in_app_payments:

  uuid:

  flutter_slidable:

  flutter_sms:

  dynamic_theme:
  
  shared_preferences:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.5.1
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - cfg/env.json
    - assets/   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```

**Comment by fpiruzi** [comment]
Same issue for me!

**Comment by zoechi** [comment]
@fpiruzi 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by xTaz1** [comment]
I have the same. 
My gradle properties 

`org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true`

I have also changed `targetSdkVersion 28`

My pubspec.yaml 
`cloud_firestore: 0.9.0+1
  firebase_auth: 0.8.1`

**Comment by xTaz1** [comment]
```
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
D8: Cannot fit requested classes in a single dex file (# methods: 67113 > 65536)
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.

FAILURE: Build failed with an exception.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.

         *********************************************************
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\3.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\47.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\48.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\50.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\51.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\52.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\53.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\54.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\56.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\57.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\58.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\59.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\60.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\61.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\62.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\63.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\64.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\65.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\66.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\67.jar, C:\Users\byxta\Documents\projects\TrainingsDiary\build\app\intermediates\transforms\dexBuilder\debug\68.jar
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Finished with error: Gradle task assembleDebug failed with exit code 1

```

**Comment by xTaz1** [comment]
I commented out cloud_firestore and firebase_auth, now my project is compiled and run

**Comment by mklim** [comment]
@xTaz1 your specific error isn't related to AndroidX. It's a really unfortunate limitation of how many Java methods can be included in an Android APK at a time by default. `Error while merging dex archives: The number of method references in a .dex file cannot exceed 64K.` We're tracking this at #20747 and #27702. You can find more info about it and links to fixing it in [this comment](https://github.com/flutter/flutter/issues/20747#issuecomment-463410454). 

@DarthWindu thanks! That gives me enough info to debug the problem. It's unfortunately pretty tricky.

So in your pubspec these plugins are still using the deprecated libraries, at least right now:

- flutter_facebook_login
- flutter_firebase_ui

This means that you can't migrate your app to AndroidX yet, because those plugins will always try to bring in the old support libraries still and crash at compile time. So for your case you're probably going to want to revert your migration and [downgrade](https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility#avoiding-androidx) to the earlier versions of the plugins, from before they were migrated to AndroidX:

```
  cloud_firestore: ^0.8.2+3
  firebase_auth: ^0.6.2
  google_sign_in: ^3.2.4
  shared_preferences: ^0.4.3
```

On the plugins side it would be really helpful if we could diagnose incompatible plugins like this better. #27748 is similar to this, it's about automatically handling dependency matching in pub. Ideally for now we could at least update the guide with some type of command to run to check and make sure that your plugins are all compatible with AndroidX *before* migrating. I think theoretically we should be able to print transitive dependencies with Gradle at the command line and grep through them.

**Comment by DarthWindu** [comment]
For anyone having difficulty reverting, here's the `pubspec.yaml` that worked for both iOS and Android (release and debug) builds.

```
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cloud_firestore: 0.8.2+1

  firebase_auth: 0.7.0
  
  # google_sign_in:

  colorize:

  progress_hud:

  square_in_app_payments: 1.0.1

  uuid:

  flutter_slidable:

  flutter_sms: 0.0.3

  dynamic_theme:
  
  shared_preferences: 0.4.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.5.1
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
```
