### ISSUE TITLE
The named parameter arrayContains isn't defined

### ISSUE THREAD

**Issue by alex-lushiku** [flutter/flutter#27923]
The documentation states that `arrayContains` has been added since v0.8.0, but it is not working in my Query using `cloud_firestore 0.9.0+1`. Did I forget to import something?

**pubspec:**
```
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  firebase_auth: ^0.5.15
  firebase_core: any
  firebase_messaging: ^1.0.5
  flutter_facebook_login: ^1.1.1
  json_annotation: ^0.2.3
  cloud_firestore: ^0.9.0+1
  shared_preferences: ^0.4.2
  country_icons: ^1.1.0
```

**Code:**
```
stream: Firestore.instance.collection('pools')
                .where('participants', arrayContains: 'VyJPuoe6xQbzILcvgZJ1LPfP73P2')
                .snapshots(),
```

**flutter doctor:**
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.253], locale en-US)
    • Flutter version 1.0.0 at C:\flutter\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\undefined\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • POCOPHONE F1 • xxx.xxx.x.xx:5555 • android-arm64 • Android 9 (API 28)

• No issues found!
```
