### ISSUE TITLE
Build Release APK Failed

### ISSUE THREAD

**Issue by fpiruzi** [flutter/flutter#27933]
Hi, I can't build a release APK.
Thanks in advance!
```
Error:
> WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't > compatible with AndroidX.
>          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
>          This warning prints for all Android build failures. The real root cause of the error may be unrelated.

> FAILURE: Build failed with an exception.
> What went wrong:
> Execution failed for task ':firebase_analytics:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  .../build/firebase_analytics/intermediates/res/merged/release/values/values.xml:197: error: resource android:attr/fontVariationSettings not found.
  .../build/firebase_analytics/intermediates/res/merged/release/values/values.xml:198: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```
- Flutter doctor
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A391, locale es-AR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)
```
- `android/build.gradle`:

```gradle
buildscript {
     repositories {
         maven { url 'https://maven.google.com' }
         jcenter()
         maven {
             url 'https://maven.fabric.io/public'
         }
     }
     dependencies {
         classpath 'com.android.tools.build:gradle:3.2.1'
         classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.11'
         classpath 'com.google.gms:google-services:4.2.0'
         classpath 'io.fabric.tools:gradle:1.27.0'
     }
 }

allprojects {
    repositories {
        google()
        maven {
            url 'https://maven.google.com'
        }
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "26.1.0"
            }
        }
    }
}
```

- app/build.gradle
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '0.1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'io.fabric'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.flutter.sample"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            profile {
                matchingFallbacks = ['debug', 'release']
            }
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources false
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.71'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.firebase:firebase-core:16.0.6'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.7'
}

apply plugin: 'com.google.gms.google-services'
```

- gradle.properties
```
org.gradle.jvmargs=-Xmx1536M
extra-gen-snapshot-options=--obfuscate
android.useAndroidX=true
android.enableJetifier=true
android.debug.obsoleteApi=true
```

- pubspec.yaml

```yml
name: sampleapp
description: The sampleApp Mobile Client.
version: 0.1.0+1 #buildName+buildNumber

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_auth: ^0.8.0+1
  google_sign_in: ^3.3.0
  cloud_firestore: ^0.9.0+1
  firebase_storage: ^1.1.0
  flutter_crashlytics: ^0.2.0
  firebase_analytics: ^1.2.0
  firebase_core: ^0.3.0
  #others
  cupertino_icons: ^0.1.2
  transparent_image: ^0.1.0
  datetime_picker_formfield: ^0.1.2
  image_picker: ^0.5.0+3
  location: ^1.4.1
  simple_permissions: ^0.1.9
  validate: ^1.6.0
  modal_progress_hud: ^0.1.0
  shared_preferences: ^0.4.2
  connectivity: ^0.4.0
  device_info: ^0.3.0
  pull_to_refresh: ^1.1.5
  uuid: ^1.0.3
  url_launcher: ^4.0.2
  flutter_image_compress: ^0.2.3
  path_provider: ^0.4.1
  material_design_icons_flutter: 3.0.3392
  charts_flutter: ^0.5.0
  package_info: ^0.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter
```

- Proguard
```
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.google.firebase.** { *; }
```
