### ISSUE TITLE
Build failure with AndroidX

### ISSUE THREAD

**Issue by kiruto** [flutter/flutter#28303]
```
 Android dependency 'androidx.***' has different version for the compile (1.0.0-beta01) and runtime (1.0.0-rc01) classpath. You should manually set the same version via DependencyResolution
```

I created a gist [here](https://gist.github.com/kiruto/d8a4c612229c39ce1f4c3e671294d1cc) of the logs when the command below fired.
```bash
flutter run -t main.dart --verbose
```

My project have a lot of dependencies, but it can be sure that flutter plugins may cause the error.

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  camera: ^0.4.0+2
  barcode_scan:
    git:
      url: git@github.com:apptreesoftware/flutter_barcode_reader.git
  meta: any
  json_serializable: any
  json_annotation: any
  http_client:
    path: ../http_client
  flutter_spinkit: any
  intl: any
  cached_network_image: ^0.5.1
  url_launcher: any
  sentry: any
  curl: any
  uuid: any
  flutter_secure_storage: any
  permission_handler: ^2.1.3
  package_info: ^0.4.0+1
  device_info: ^0.4.0+1
```
