### ISSUE TITLE
iOs App Crashes on Navigation.push, but works fine on android

### ISSUE THREAD

**Issue by trey-rosius** [flutter/flutter#28328]
Hi, 
I created this app a while back. Then i updated to AndroidX and also updated all the plugins. The app runs well on android, but crashed on ios, throwing this exception.
```
2019-02-22 13:01:32.098854+0100 Runner[5805:66022] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:

(
	0   CoreFoundation                      0x000000010edba1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010e358735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ed064ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010ee29541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x000000010edb5c9b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   Runner                              0x000000010a625059 getDictionaryFromFIRApp + 217
	6   Runner                              0x000000010a624ea1 -[FLTFirebaseCorePlugin handleMethodCall:result:] + 4225
	7   Flutter                             0x000000010bb6a61a __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
	8   Flutter                             0x000000010bb873dc _ZNK5shell21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEE + 166
	9   Flutter                             0x000000010bb8af20 _ZN5shell15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEE + 38
	10  Flutter                             0x000000010bbdfdc7 _ZNSt3__110__function6__funcIZN5shell5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEEE4$_27NS_9allocatorIS9_EEFvvEEclEv + 57
	11  Flutter                             0x000000010bb96d3e _ZN3fml15MessageLoopImpl15RunExpiredTasksEv + 522
	12  Flutter                             0x000000010bb9a0bc _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	13  CoreFoundation                      0x000000010ed1ff34 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	14  CoreFoundation                      0x000000010ed1fb32 __CFRunLoopDoTimer + 1026
	15  CoreFoundation                      0x000000010ed1f39a __CFRunLoopDoTimers + 266
	16  CoreFoundation                      0x000000010ed19a1c __CFRunLoopRun + 2252
	17  CoreFoundation                      0x000000010ed18e11 CFRunLoopRunSpecific + 625
	18  GraphicsServices                    0x00000001111ea1dd GSEventRunModal + 62
	19  UIKitCore                           0x0000000116b0481d UIApplicationMain + 140
	20  Runner                              0x000000010a40c6b0 main + 112
	21  libdyld.dylib                       0x000000010fb4e575 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
The app crashes when it reaches a Navigator.push method. 

```yml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  firebase_messaging: ^3.0.1
  url_launcher: "^3.0.2"
  geolocator: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  http: ^0.12.0+1
  shared_preferences: ^0.4.3
  cached_network_image: ^0.5.1
  firebase_database: ^2.0.1

  intl_translation: "^0.17.0"

  image_picker: ^0.5.0+3

  intl: "^0.15.7"
  firebase_auth: ^0.8.1
  firebase_core: ^0.3.0

  google_sign_in: ^4.0.1+1
  flutter_webview_plugin: ^0.2.1+2


```

**Flutter doctor**
```

[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.13.6 17G65, locale en-CM)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[!] Android Studio (not installed)
[✓] VS Code (version 1.31.0)
[✓] Connected device (2 available)

! Doctor found issues in 3 categories.

```
