### ISSUE TITLE
Flutter hangs when building for iOS

### ISSUE THREAD

**Issue by mikhail-tokarev** [flutter/flutter#28415]
iOS builds sporadically hang at executing xcodebuild -list. This happens so for ~20% builds (every 5th build). We've tried building different iOS apps, reinstall Flutter from a scratch (channel Stable), removing $HOME/.pub-cache

## Steps to Reproduce

1. `rm $HOME/.pub-cache`
2. `git fetch`
3. `flutter channel stable`
4. `flutter upgrade`
5. `cd $HOME/myapp`
2. `flutter build ios --debug --no-codesign -v`

## Logs

```
[  +47 ms] executing: [/Users/greenhouse/programs/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/greenhouse/programs/flutter/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +1 ms] executing: [/Users/greenhouse/programs/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter
[        ] executing: [/Users/greenhouse/programs/flutter/] git log -n 1 --pretty=format:%H
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +4 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Users/greenhouse/programs/flutter/] git log -n 1 --pretty=format:%ar
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 months ago
[   +1 ms] executing: [/Users/greenhouse/programs/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[ +875 ms] Contents of .packages:
[   +3 ms] # Generated by pub on 2019-02-23 23:46:11.590745.
           analyzer:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/analyzer-0.34.3/lib/
           args:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/args-1.5.1/lib/
           async:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/async-2.0.8/lib/
           boolean_selector:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/boolean_selector-1.0.4/lib/
           charcode:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.2/lib/
           collection:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/
           convert:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/convert-2.0.2/lib/
           crypto:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/crypto-2.0.6/lib/
           csslib:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/csslib-0.14.6/lib/
           cupertino_icons:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/cupertino_icons-0.1.2/lib/
           file:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/file-5.0.6/lib/
           flutter:file:///Users/greenhouse/programs/flutter/packages/flutter/lib/
           flutter_driver:file:///Users/greenhouse/programs/flutter/packages/flutter_driver/lib/
           flutter_test:file:///Users/greenhouse/programs/flutter/packages/flutter_test/lib/
           front_end:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.9+1/lib/
           fuchsia_remote_debug_protocol:file:///Users/greenhouse/programs/flutter/packages/fuchsia_remote_debug_protocol/lib/
           glob:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/glob-1.1.7/lib/
           html:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/html-0.13.3+3/lib/
           http:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/
           http_multi_server:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/http_multi_server-2.0.5/lib/
           http_parser:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.3/lib/
           intl:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/intl-0.15.7/lib/
           io:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/io-0.3.3/lib/
           js:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/
           json_rpc_2:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/json_rpc_2-2.0.9/lib/
           kernel:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.9+1/lib/
           logging:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/logging-0.11.3+2/lib/
           matcher:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.3+1/lib/
           meta:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/meta-1.1.6/lib/
           mime:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/mime-0.9.6+2/lib/
           multi_server_socket:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/multi_server_socket-1.0.2/lib/
           node_preamble:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/node_preamble-1.4.4/lib/
           package_config:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/package_config-1.0.5/lib/
           package_resolver:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/package_resolver-1.0.7/lib/
           path:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/path-1.6.2/lib/
           platform:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/platform-2.2.0/lib/
           plugin:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/plugin-0.2.0+3/lib/
           pool:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/pool-1.4.0/lib/
           process:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/process-3.0.9/lib/
           pub_semver:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/pub_semver-1.4.2/lib/
           quiver:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/quiver-2.0.1/lib/
           shelf:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/shelf-0.7.4/lib/
           shelf_packages_handler:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/shelf_packages_handler-1.0.4/lib/
           shelf_static:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/shelf_static-0.2.8/lib/
           shelf_web_socket:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/shelf_web_socket-0.2.2+4/lib/
           sky_engine:file:///Users/greenhouse/programs/flutter/bin/cache/pkg/sky_engine/lib/
           source_map_stack_trace:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/source_map_stack_trace-1.1.5/lib/
           source_maps:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/source_maps-0.10.8/lib/
           source_span:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/source_span-1.4.1/lib/
           stack_trace:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.9.3/lib/
           stream_channel:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/stream_channel-1.6.8/lib/
           string_scanner:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.4/lib/
           term_glyph:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.0.1/lib/
           test:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/test-1.5.1+1/lib/
           test_api:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.1/lib/
           test_core:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/test_core-0.2.0+1/lib/
           typed_data:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/typed_data-1.1.6/lib/
           utf:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/utf-0.9.0+5/lib/
           vector_math:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/
           vm_service_client:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/vm_service_client-0.2.6/lib/
           watcher:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.7+10/lib/
           web_socket_channel:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/web_socket_channel-1.0.9/lib/
           yaml:file:///Users/greenhouse/.pub-cache/hosted/pub.dartlang.org/yaml-2.1.15/lib/
           capybara:lib/

[   +3 ms] Contents of pubspec.lock:
[   +7 ms] # Generated by pub
           # See https://www.dartlang.org/tools/pub/glossary#lockfile
           packages:
             analyzer:
               dependency: transitive
               description:
                 name: analyzer
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.34.3"
             args:
               dependency: transitive
               description:
                 name: args
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.5.1"
             async:
               dependency: transitive
               description:
                 name: async
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "2.0.8"
             boolean_selector:
               dependency: transitive
               description:
                 name: boolean_selector
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.0.4"
             charcode:
               dependency: transitive
               description:
                 name: charcode
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.1.2"
             collection:
               dependency: transitive
               description:
                 name: collection
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.14.11"
             convert:
               dependency: transitive
               description:
                 name: convert
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "2.0.2"
             crypto:
               dependency: transitive
               description:
                 name: crypto
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "2.0.6"
             csslib:
               dependency: transitive
               description:
                 name: csslib
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.14.6"
             cupertino_icons:
               dependency: "direct main"
               description:
                 name: cupertino_icons
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.1.2"
             file:
               dependency: transitive
               description:
                 name: file
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "5.0.6"
             flutter:
               dependency: "direct main"
               description: flutter
               source: sdk
               version: "0.0.0"
             flutter_driver:
               dependency: "direct dev"
               description: flutter
               source: sdk
               version: "0.0.0"
             flutter_test:
               dependency: "direct dev"
               description: flutter
               source: sdk
               version: "0.0.0"
             front_end:
               dependency: transitive
               description:
                 name: front_end
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.1.9+1"
             fuchsia_remote_debug_protocol:
               dependency: transitive
               description: flutter
               source: sdk
               version: "0.0.0"
             glob:
               dependency: transitive
               description:
                 name: glob
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.1.7"
             html:
               dependency: transitive
               description:
                 name: html
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.13.3+3"
             http:
               dependency: transitive
               description:
                 name: http
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.12.0+1"
             http_multi_server:
               dependency: transitive
               description:
                 name: http_multi_server
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "2.0.5"
             http_parser:
               dependency: transitive
               description:
                 name: http_parser
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "3.1.3"
             intl:
               dependency: transitive
               description:
                 name: intl
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.15.7"
             io:
               dependency: transitive
               description:
                 name: io
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.3.3"
             js:
               dependency: transitive
               description:
                 name: js
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.6.1+1"
             json_rpc_2:
               dependency: transitive
               description:
                 name: json_rpc_2
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "2.0.9"
             kernel:
               dependency: transitive
               description:
                 name: kernel
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.3.9+1"
             logging:
               dependency: transitive
               description:
                 name: logging
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.11.3+2"
             matcher:
               dependency: transitive
               description:
                 name: matcher
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.12.3+1"
             meta:
               dependency: transitive
               description:
                 name: meta
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.1.6"
             mime:
               dependency: transitive
               description:
                 name: mime
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.9.6+2"
             multi_server_socket:
               dependency: transitive
               description:
                 name: multi_server_socket
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.0.2"
             node_preamble:
               dependency: transitive
               description:
                 name: node_preamble
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.4.4"
             package_config:
               dependency: transitive
               description:
                 name: package_config
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.0.5"
             package_resolver:
               dependency: transitive
               description:
                 name: package_resolver
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.0.7"
             path:
               dependency: transitive
               description:
                 name: path
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.6.2"
             platform:
               dependency: transitive
               description:
                 name: platform
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "2.2.0"
             plugin:
               dependency: transitive
               description:
                 name: plugin
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.2.0+3"
             pool:
               dependency: transitive
               description:
                 name: pool
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.4.0"
             process:
               dependency: transitive
               description:
                 name: process
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "3.0.9"
             pub_semver:
               dependency: transitive
               description:
                 name: pub_semver
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.4.2"
             quiver:
               dependency: transitive
               description:
                 name: quiver
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "2.0.1"
             shelf:
               dependency: transitive
               description:
                 name: shelf
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.7.4"
             shelf_packages_handler:
               dependency: transitive
               description:
                 name: shelf_packages_handler
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.0.4"
             shelf_static:
               dependency: transitive
               description:
                 name: shelf_static
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.2.8"
             shelf_web_socket:
               dependency: transitive
               description:
                 name: shelf_web_socket
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.2.2+4"
             sky_engine:
               dependency: transitive
               description: flutter
               source: sdk
               version: "0.0.99"
             source_map_stack_trace:
               dependency: transitive
               description:
                 name: source_map_stack_trace
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.1.5"
             source_maps:
               dependency: transitive
               description:
                 name: source_maps
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.10.8"
             source_span:
               dependency: transitive
               description:
                 name: source_span
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.4.1"
             stack_trace:
               dependency: transitive
               description:
                 name: stack_trace
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.9.3"
             stream_channel:
               dependency: transitive
               description:
                 name: stream_channel
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.6.8"
             string_scanner:
               dependency: transitive
               description:
                 name: string_scanner
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.0.4"
             term_glyph:
               dependency: transitive
               description:
                 name: term_glyph
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.0.1"
             test:
               dependency: "direct dev"
               description:
                 name: test
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.5.1+1"
             test_api:
               dependency: transitive
               description:
                 name: test_api
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.2.1"
             test_core:
               dependency: transitive
               description:
                 name: test_core
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.2.0+1"
             typed_data:
               dependency: transitive
               description:
                 name: typed_data
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.1.6"
             utf:
               dependency: transitive
               description:
                 name: utf
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.9.0+5"
             vector_math:
               dependency: transitive
               description:
                 name: vector_math
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "2.0.8"
             vm_service_client:
               dependency: transitive
               description:
                 name: vm_service_client
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.2.6"
             watcher:
               dependency: transitive
               description:
                 name: watcher
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "0.9.7+10"
             web_socket_channel:
               dependency: transitive
               description:
                 name: web_socket_channel
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "1.0.9"
             yaml:
               dependency: transitive
               description:
                 name: yaml
                 url: "https://pub.dartlang.org"
               source: hosted
               version: "2.1.15"
           sdks:
             dart: ">=2.1.0-dev.5.0 <3.0.0"

[  +16 ms] executing: /usr/bin/defaults read /Users/greenhouse/tmpfz_8o40x/ios/Runner/Info CFBundleIdentifier
[  +73 ms] Exit code 0 from: /usr/bin/defaults read /Users/greenhouse/tmpfz_8o40x/ios/Runner/Info CFBundleIdentifier
[        ] $(PRODUCT_BUNDLE_IDENTIFIER)
[   +8 ms] Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
[   +4 ms] Building io.codemagic.capybara for device (ios)...
[ +378 ms] Using legacy Xcode build system.
[  +70 ms] executing: [/Users/greenhouse/tmpfz_8o40x/ios/] /usr/bin/xcodebuild -list
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D42, locale en-US)
    • Flutter version 1.0.0 at /Users/greenhouse/programs/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/greenhouse/programs/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/greenhouse/programs/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode-10.1.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
