### ISSUE TITLE
video_player plugin always shows isBuffering as false

### ISSUE THREAD

**Issue by divyanshub024** [flutter/flutter#28494]
## Description
Flutter video player plugin always shows `isBuffering` as `false`. Even in video_player plugin example, the code is there to show `CircularProgressIndicator` while buffering but it does not show. https://github.com/flutter/plugins/blob/347f508dd403f6b26789852b503199af5e8ee9f6/packages/video_player/example/lib/main.dart#L85

**Comment by 4ever911** [comment]
same here, even i set the buffer color, it never displays.

**Comment by divyanshub024** [comment]
@4ever911 Yeah! It's not showing. Even in the video_player example.

**Comment by WoKee** [comment]
Yes,Have you found a solution?

**Comment by shmy** [comment]
same here

**Comment by shmy** [comment]
@WoKee  try this
```yaml
video_player:
    git:
      url: git://github.com/shmy/video_player_flutter.git
```
