### ISSUE TITLE
Adding a custom kernel transformer to the frontend server

### ISSUE THREAD

**Issue by Norbert515** [flutter/flutter#28523]
I'm working on an interactive widget editor and I need to write a custom kernel transformer.

The flutter/engine repository contains a frontend server which is a wrapper around the dart frontend server, in Flutter the compiled frontend server is included as `bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot`. It is used by the Flutter tool to generate the .dill files. 
What I'd like to do is to replace that frontend server with a custom one which adds a custom kernel transformer.

**What I tried:**
I downloaded the flutter engine with the gclient and synced it but when resolving the dependencies it wasn't able to find a few of them:
```yml
dependencies:
  args: any
  async: any
  charcode: any
  collection: any
  convert: any
  crypto: any
  front_end: any
  flutter_kernel_transformers: any
  kernel: any
  logging: any
  meta: any
  quiver: any
  package_config: any
  path: any
  source_span: any
  typed_data: any
  usage: any
  vm: any
```
For example, I was able to resolve the vm dependency by changing it to a path dependency and pointing to the downloaded vm package, but after changing a few things more and more errors kept popping up.

I tried implementing the changes using the dart repository directly but I ran into version conflicts and ultimately syncing dart + engine + flutter version didn't sound like a lot of fun.

I had problems building dart/ the engine on my machine (I'm on Windows).

**What worked:**
I've set up a Linux VM and downloaded the engine, I also was able to build it and therefore generate a `frontend_server.dart.snapshot`. Unfortunately, the build took around 4 hours.

Ideally, I'd like to open up the frontend_server as a separate package, add changes and compile the `frontend_server.dart.snapshot` using the correct version of dart/ the engine. 

I've seen @jacob314 implemented the track-widget-creation transformer, I'd love to hear how you went about it!

Any help is appreciated, thanks in advance.
