### ISSUE TITLE
How to use Font Weights with names?

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#28543]
I want to use `Roboto Medium` as my font, but I can only see options like `FontWeight.bold` for setting the font weight and it's not close to `Roboto Medium`.

Is it possible to access the name of a given Font Weight defined in a Font?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by feinstein** [comment]
I will, it's just that I think this might be a bug (a functionality missing) or lack of documentation, so I rather open it as an issue as well.

**Comment by zoechi** [comment]
This is why I kept it open. I don't know if this is supported or not.
Asking on StackOverflow or similar before reporting a bug/feature request is always a good idea though.

**Comment by anderscheow** [comment]
Since `FontWeight.bold` refer to `FontWeight.w700`, you can try this in your `pubspec.yaml`

```
fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Medium.ttf
            weight: 700
```
