### ISSUE TITLE
await url_launcher launch not working

### ISSUE THREAD

**Issue by aBuder** [flutter/flutter#28606]
```
  Future onTapPayPal(String url, int credit) async {
    var payPalUrl = url.replaceAll("CENT", credit.toString());
    if (await canLaunch(payPalUrl)) {
      await launch(
        payPalUrl,
        forceSafariVC: true,
        forceWebView: true,
        statusBarBrightness: Brightness.dark,
      );
      print("finish");
    }
  }
```

## Steps to Reproduce

Call method on top, and after finish viewing the url, the current widget should be reloaded. The code after await launch would not called.

pubspec.yml

```
name: TestProject
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^0.12.0
  fcharts: ^0.0.9
  json_serializable: ^1.1.0
  barcode_scan: ^0.0.8
  shared_preferences: ^0.4.3
  url_launcher: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png

```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale de-DE)
    • Flutter version 1.0.0 at /Users/abuder/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/abuder/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.1

[✓] Connected device (1 available)
    • iPhone X • 7CA15801-09C2-4DE1-85EF-95A3E2A261A5 • ios • iOS 12.1 (simulator)

• No issues found!
```
