### ISSUE TITLE
I can't create flutter project

### ISSUE THREAD

**Issue by katari-code** [flutter/flutter#28757]
every time when I try to create my flutter project I got this error in VS code.
please does anyone can help me?   
`...
….
ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  ios\Runner\Base.lproj\Main.storyboard (created)
  ios\Runner\Info.plist (created)
  ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  lib\main.dart (created)
  dsd.iml (created)
  pubspec.yaml (created)
  README.md (created)
  test\widget_test.dart (created)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 1e24ce1acbc26062)
Crash report written to C:\Users\.....\Desktop\flutter_project\dsd\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
exit code 1
`

[flutter_01.log](https://github.com/flutter/flutter/files/2921626/flutter_01.log)

**Comment by jonahwilliams** [comment]
From the log:

```

## command

flutter create .

## exception

YamlException: Error on line 1, column 1: Unexpected character.
  ╷
1 │ 
  │ ^
  ╵

```
#0      Parser.parse (package:yaml/src/parser.dart:50:7)
#1      Loader.load (package:yaml/src/loader.dart:48:25)
#2      loadYamlDocument (package:yaml/yaml.dart:51:25)
#3      loadYamlNode (package:yaml/yaml.dart:42:5)
```

It looks like you've got an invalid character in your pubspec.yaml, could you post the contents?

**Comment by katari-code** [comment]
This is the content 
![56bb7bcf-7afb-412b-bb11-b47d16af186e png](https://user-images.githubusercontent.com/38846741/53676319-73cf9880-3cdb-11e9-8d7e-4f29ba241ec6.jpg)

**Comment by jonahwilliams** [comment]
Those are unicode replace characters - that means your pubspec.yaml is corrupt. Can you delete that file and try flutter create again?

Did you add that file or was it created that way by `flutter create` ?

**Comment by katari-code** [comment]
I used flutter create

**Comment by jonahwilliams** [comment]
can you replace the contents of pubspec.yaml with this and retry:

```
name: dsd
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```
