### ISSUE TITLE
Hot Reload don't work in AndroidStudio 3.3.2 ( In Windows)

### ISSUE THREAD

**Issue by JeeseC** [flutter/flutter#29121]
My environment is wIndow + AndroidStudio 3.3.2, everything is ok, but Hot Reload don't work.
The small lightning icon is displayed normally ,it's also clickable.
And the console display : 
"Initializing hot reload...
Syncing files to device Android SDK built for x86...
Reloaded 2 of 568 libraries in 1,181ms."
But there is no reload of the modified content on the emulator.
Please help me.

**Comment by VNAPNIC** [comment]
me too

**Comment by dnfield** [comment]
@VNAPNIC please avoid comments like "me too" or "+1", which ends up notifying everyone subscribed to this issue..  Instead, upvote the original issue, which helps us better triage the issue and gauge how many people it's affecting.

**Comment by dnfield** [comment]
@JeeseC can you share the output of `flutter doctor -v`?

**Comment by JeeseC** [comment]
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.2.1 at F:\flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

**Comment by ened** [comment]
@JeeseC how do you verify if hot reload worked? What did you try to change & what is the expected & actual output? Stating from the log message above, it seems to work well. 

Do note that stateful widgets may require a `restart`, not a `reload`, if you change underlying implementation. Alternatively, just navigate out and back into the specific area of your App.

**Comment by JeeseC** [comment]
@ened I just change some words of the textview, and then click the Hot reload button. But the simulator display nothing to change, so I think the hot reload don't work.
The hot restart work well.

**Comment by ffey** [comment]
I have the same problem that when I change my code and save(Ctrl + S), it not reload. I must press the hot reload icon it will work.
it output when I run ```flutter doctor -v```
```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.619], locale zh-CN)
    • Flutter version 1.2.1 at D:\flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • STF AL10 • 5JPDU17712006976 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by DanTup** [comment]
I can't repro on my PC and an Android 7.1 physical device. I created a new Flutter app using the wizard and made changes to the text and clicked save.

Just trying to get an Android 8 emulator to work.

Can anyone reproduce it from the terminal with `flutter run`, or only in Android Studio?

**Comment by ffey** [comment]
thanks for response !  when I save my code , nothing will show in the debug console . but I press the hot reload icon it show ```Reloaded 3 of 558 libraries in 1,163ms.```. This problem happen in vscode and AndroidStudio. I think it's not the problem of editor.

**Comment by jonahwilliams** [comment]
If you're noticing that hot restart is working and not hot reload, then it would be helpful if you shared the code you are trying to hot reload.

If hot restart works, then does hot reload work following that hot restart?

**Comment by jonahwilliams** [comment]
When I run your application via the command line, hot reload works as expected - is this the case for you as well?

However running in vs code, I'm noticing that hot reload on save does not work as expected and I have to hot restart. cc @DanTup, but this might be the existing vs code bug.

On Intellij, hot reload mostly works - but sometimes I see "Reload not performed: analysis issues found". However the only problems in this project are some lints, nothing that should stop compilation. cc @devoncarew   

To trigger this I've been toggling the colors in the material app in WanAndroidPage.dart:

```
    return new MaterialApp(
      navigatorKey: navigatorKey,
      theme: new ThemeData(
          primaryColor: Colors.blue,
          accentColor: Colors.green // Change to a different color and save, sometimes the reload fails
      ),
```

**Comment by ffey** [comment]
I download the vscode 1.31. it can work well.  anroidStudio won`t work sometimes. #29096 thanks very much.

**Comment by DanTup** [comment]
> cc @DanTup, but this might be the existing vs code bug.

Yep, based on @ffey's last comment about 1.31 working, the VS Code issue is likely [this regression](https://github.com/Microsoft/vscode/issues/69534) (which affects more than just Hot Reload). I'm hoping there will be a VS Code recovery release this week to address.

**Comment by nemoryoliver** [comment]
I thought I messed up something myself that broke the hot reload feature. Glad to know to downgrade to VS Code 1.31 is the temp fix at least.

**Comment by JeeseC** [comment]
@jonahwilliams Now it make sure hot reload don't work well in Android Studio, it's right?
@DanTup I hope Android Studio can be solved together.

**Comment by DanTup** [comment]
@JeeseC 

> I hope Android Studio can be solved together.

The VS Code v1.32 issue is a bug in VS Code and unrelated to hot reload not working in Android Studio (though I appreciate it seems coincidental for both to crop up within a few days). The VS Code issue will be fixed with a VS Code recovery release soon (see [VS Code February 2019 Recovery 2 Endgame](https://github.com/Microsoft/vscode/issues/70350)) and does not require a Flutter or VS Code extension fix.

I don't think the cause of this issue in Android Studio is clear yet. Can you clarify whether you can repro this issue from the command line (using `flutter run`) and exactly what changes you're making that aren't applying when reloading, to make sure we can test the same thing?

 @devoncarew @jacob314 is there a way to get Android Studio to log the `flutter run` output?

**Comment by Ruzo** [comment]
Hey guys, I've had the same problem after installing flutter and Android Studio a couple of days ago. Since I just started a course and coding with Flutter for the first time, Hot Reload would not work in vscode or Android Studio when I changed and saved my main.dart file.

However, as soon as I started using a new dart file that was imported into the main.dart one, Hot Reload started working.

So, in my case, Hot Reload does not work in vscode or Android Studio when I save the main.dart file. It works with other files of the project.

**Comment by DanTup** [comment]
@Ruzo What did your `main.dart` look like? Changes directly in the `main()` method won't work ([see here](https://flutter.dev/docs/development/tools/hot-reload#recent-ui-change-is-excluded)), as `main` is not re-executed during a hot reload.

If what you'er seeing isn't described by that, could you provide some sample code of what didn't work? Thanks!

**Comment by Ruzo** [comment]
@DanTup I guess that was the issue because the code was written inside the main() method until it was time to move it to a separate file. Kind of like:
```
void main() {
  var App = MaterialApp(
     home: Scaffold( ...
}

```
Sorry. It was just a beginner's ignorance.

**Comment by DanTup** [comment]
@Ruzo Thanks for confirming! I [made this same mistake](https://github.com/flutter/flutter/issues/10620#issue-235071501) too :-)

@JeeseC might this explain your original issue too? Can you give an example of the changes you were making?

**Comment by BufferUnderflower** [comment]
There's definitely some issue with plugin, it just sometimes stops listening to IDE save event. 
At some point in time hitting save stops triggering the reload (which is still fully functional using icon). 

Re-plugging the phone as well as re-running the code doesn't help.
Restarting AS makes it work again for some time.

This usually happens after making changes for top-level functions/constants which i guess can't be hot-reloaded, but such situations shouldn't break the plugin's save on reload part at all.
Also might happen after phone being unplugged.

**Comment by wk1017553772** [comment]
I can use Hot Reload in some root page, but not useful in deep route page in Android

> [√] Flutter (Channel master, v1.3.14-pre.7, on Microsoft Windows [Version 10.0.17134.648], locale zh-CN)
>     • Flutter version 1.3.14-pre.7 at D:\flutter
>     • Framework revision ee3e621f02 (28 hours ago), 2019-03-18 21:40:21 -0700
>     • Engine revision 5088735e5f
>     • Dart version 2.2.1 (build 2.2.1-dev.1.1 None)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\wangk\AppData\Local\Android\Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = C\:\\Users\\wangk\\AppData\\Local\\Android\\Sdk
>     • Java binary at: D:\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.2)
>     • Android Studio at D:\Android\Android Studio
>     • Flutter plugin version 31.3.1
>     • Dart plugin version 181.5656
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

**Comment by DanTup** [comment]
> I can use Hot Reload in some root page, but not useful in deep route page in Android

Can you provide sample code showing the issue that we try to reproduce with?

**Comment by wk1017553772** [comment]
In my  project  depend  local Library  each other,flutter-app is root project
flutter-app pubspec.yaml:
```
name: flutter_app
description: A new Flutter application.
dependencies:
   flutter:
     sdk: flutter
   flutter_localizations:
     sdk: flutter
     cupertino_icons: ^0.1.2
   # Local Library
   app_home_page:
     path: ../app-home-page
   app_login:
     path: ../app-login
```
app_home_page pubspec.yaml:
```
name: app_home_page
description: A new flutter package project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  # Local Library
  app_base:
    path: ../app-base

  app_theme_manager:
    path: ../app-theme-manager

  advertising_material:
    path: ../yezi_modules/advertising_material

  base_info:
    path: ../yezi_modules/base_info

   ......

```
 Hot Reload is useful and nomal  in root project app_home_page and app-login .
But no use for the subprocject app_base,advertising_material,base_info ,etc.
In the subprocject change file ,it will show
`Reloaded 0 of 1291 libraries in xxxms.`
and nothing  to change(AndroidStudio and Vs code all not work ). 
It become this  after I upgrade Flutter version in Flutter version 1.3.14-pre.7

**Comment by wk1017553772** [comment]
> > I can use Hot Reload in some root page, but not useful in deep route page in Android
> 
> Can you provide sample code showing the issue that we can try to reproduce with?

In my project depend local Library each other,flutter-app is root project
flutter-app pubspec.yaml:

```
name: flutter_app
description: A new Flutter application.
dependencies:
   flutter:
     sdk: flutter
   flutter_localizations:
     sdk: flutter
     cupertino_icons: ^0.1.2
   # Local Library
   app_home_page:
     path: ../app-home-page
   app_login:
     path: ../app-login
```
app_home_page pubspec.yaml:

```
name: app_home_page
description: A new flutter package project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  # Local Library
  app_base:
    path: ../app-base

  app_theme_manager:
    path: ../app-theme-manager

  advertising_material:
    path: ../yezi_modules/advertising_material

  base_info:
    path: ../yezi_modules/base_info

   ......
```

Hot Reload is useful and nomal in root project app_home_page and app-login .
But no use for the subprocject app_base,advertising_material,base_info ,etc.
In the subprocject change file ,it will show
`Reloaded 0 of 1291 libraries in xxxms.`
and nothing to change(AndroidStudio and Vs code all not work ).
It become this after I upgrade Flutter version in Flutter version 1.3.14-pre.7
