### ISSUE TITLE
How to set the Flutter SDK version in the pubspec.yaml file？

### ISSUE THREAD

**Issue by Thomaszhouwu** [flutter/flutter#29211]
My pubspec.yaml

```
dependencies:
  flutter:
    sdk: flutter 
    version: 1.2.1 
```

errors:
flutter packages get
Running "flutter packages get" in xxxx...                
Because xxxx depends on flutter 1.2.1 from sdk which doesn't match any versions, version solving failed.
pub get failed (1)
exit code 1

How do I set this version to 1.2.1?

**Comment by Thomaszhouwu** [comment]
flutter --version
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (4 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

**Comment by HustLion** [comment]
In my understanding, You select your flutter version by unzipping the corresponding zip file. The `flutter` in your `PATH` specify the version of your flutter. And you can see the version using `flutter doctor -v`.  `pubspec.yaml ` doesn't specify flutter version.

**Comment by panzerwurst** [comment]
According to the [documentation](https://dart.dev/tools/pub/pubspec#sdk-constraints), you can specify the Flutter version in the `environment` section:

```
environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ^0.1.2
```

**Comment by kf6gpe** [comment]
This looks like a problem with the version set for https://github.com/dart-lang/intl.

**Comment by danielgomezrico** [comment]
I prefer to have defined all of my dependencies without dynamic versioning, I have lived a lot of issues with bad dependency resolution in the past and just got tired of this possibility (I am curious of why the flutter team advise to not do this in https://flutter.dev/docs/development/packages-and-plugins/using-packages#conflict-resolution).

# Set fixed dart version works
I am been able to set a fixed dart version in `pubspec.yml` like:

```
environment:
  sdk: "2.8.4" # Dart
```

# Set fixed flutter version does not
1. Im setting the flutter version in:
```YAML
dependencies:
  flutter:
    sdk: flutter
    version: 1.17.5
```

2. Im setting my flutter sdk to the stable channel:
> flutter channel stable

And then the doctor prints this
> flutter doctor

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-CO)
```

But after I run `flutter pub get` I get this error:
```
$ flutter pub get
Because banjen_flutter depends on flutter 1.17.5 from sdk which doesn't match any versions, version solving failed.
Running "flutter pub get" in banjen_flutter...
pub get failed (1; Because banjen_flutter depends on flutter 1.17.5 from sdk which doesn't match any versions, version solving failed.)
```

# Other facts
in `pubspec.lock` I see:
```YAML
flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
```

and:

```YAML
sdks:
  dart: "2.8.4"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"
```

I cant find a way to do this

**Comment by danielgomezrico** [comment]
I was able to set the version fixed for `flutter` and `dart` with the environment block:

```
environment:
  sdk: "2.8.4" # Dart
  flutter: 1.17.5
```

with that the `pubspec.lock` does have the fixed version:
```
sdks:
  dart: "2.8.4"
  flutter: "1.17.5"
```

**Comment by markusaksli-nc** [comment]
Leaving this open since it still doesn't seem to be in any of the official documentation (maybe [here](https://flutter.dev/docs/development/packages-and-plugins/using-packages))

**Comment by Gintasz** [comment]
I had added flutter version to the environment block like this:

```
environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: 1.17.5
```

But during pub get, I get this:

```
The current Flutter SDK version is 1.21.0-6.0.pre.37.

Because slide_puzzle requires Flutter SDK version 1.17.5, version solving failed.
pub get failed (1; Because slide_puzzle requires Flutter SDK version 1.17.5, version solving failed.)
```

Is there a way for flutter to auto download & activate the required flutter version based on pubspec.yaml?

**Comment by danielgomezrico** [comment]
@Gintasz I believe you need to call this to change the flutter on your environment:

> flutter channel stable

**Comment by Gintasz** [comment]
Yeah, but is there any way to get flutter to do that itself? Relevant if
different projects use different channels

2020-07-30, kt 17:11 Daniel Gomez <notifications@github.com> rašė:

**Comment by passsy** [comment]
I always pin the Flutter version for each project with https://github.com/passsy/flutter_wrapper

**Comment by hrishikesh-kadam** [comment]
As of writing, I am on Flutter version 2.0.3.
After creating the template project using `flutter create myapp`, pubspec.yaml and pubspec.lock files didn't have Flutter SDK constraint.

I added the Flutter SDK constraint as below -

```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: '2.0.3'
```

Executing `flutter pub get` command, updated the pubspec.lock file as below - 

```yaml
sdks:
  dart: ">=2.12.0-0.0 <3.0.0"
  flutter: ">=2.0.3"
```

Even after specifying Flutter SDK constraint in exact syntax, the updated pubspec.lock file has the lower bound constraint instead of the range constraint. That's strange.

Also, specifying the caret syntax as below generates the same constraints as above - 

```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: '^2.0.3'
```
