### ISSUE TITLE
P0: Use flutter_chromeos_bestpractices enabled in the Flutter lint config

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#29238]
As part of linting apps for ARC++ on ChromeOS, we want to be able to have a top level best-practices flag for all potential lint messages when linting for ChromeOS apps.

There's open discussion --- which should occur on this thread --- as to whether this should be on or off by default.

**Comment by devoncarew** [comment]
This is done - closing.

The way to enable these lints are to add an `analysis_options.yaml` file to the top level of the project, with the following contents:

```yaml
include: package:pedantic/analysis_options.yaml

analyzer:
  optional-checks:
    chrome-os-manifest-checks
```

We'll need to document that (as part of whatever docs we have in progress for Flutter and CrOS) in order for users to know how to enable these lints.
