### ISSUE TITLE
print() on Flutter apps/packages does not allow usage of stdout colors

### ISSUE THREAD

**Issue by jorgecoca** [flutter/flutter#29255]
When using pure Dart packages, it is possible to colorize the message printed in the `stdout`. Libraries like `colorize` or `colorize_lumberdash` rely on this.

However, when using them in a flutter context, this is what gets printed instead:

```bash
flutter: \^[[33mmy warning<…>
```

That same code is printed in yellow without `flutter: \^[[33mmy` in a pure Dart app/package.

Steps to reproduce:

1) pubspec.yaml

```yaml
name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  colorize: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
```

2) main.dart

```dart
import 'package:flutter/material.dart';
import 'package:colorize/colorize.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    final message = Colorize('my warning');
    message.yellow();
    print(message);

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Text('Home Page'),
    );
  }
}
```

* Expected: a `my warning` message yellow printed in stdout
* Recevied: `flutter: \^[[33mmy warning<…>`
* Also reproducible with `colorize_lumberdash` on Flutter packages
* Works as expected on pure Dart packages
