### ISSUE TITLE
Flutter Camera plugin captures video rotated 90 degrees when in Landscape on iPhone

### ISSUE THREAD

**Issue by Dwarfie** [flutter/flutter#29951]
Using the detailed example when I capture video in Landscape on an iPhone the preview is in Portrait aspect ratio with video rotated 90 degrees.
I am uploading the video to Firebase to confirm that video is rotated 90 degrees.

I don't have a physical Android device to check if it is the same.

pubspec.yaml

version: 1.0.0+1

environment: sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies: flutter: sdk: flutter

cupertino_icons: ^0.1.2

camera: ^0.4.2

path_provider: ^0.5.0

video_player: ^0.10.0

firebase_core: ^0.2.5

flutter doctor

[✓] Flutter (Channel unknown, v1.1.0, on Mac OS X 10.14.3 18D109, locale en-AU)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)

[✓] Android Studio (version 3.2)

[✓] Connected device (1 available)

![IMG_2941](https://user-images.githubusercontent.com/48934060/54966265-7c0bb280-4fbf-11e9-83e0-f96dc219675f.png)

**Comment by Dwarfie** [comment]
Still  no answer on this.
How do I contact the authors of the plugin ?

**Comment by quentinleguennec** [comment]
Hi @Dwarfie. I've been working on a fix for the rotation on iOS for the last 2 weeks. It's a complicated piece as metadata are handle differently on different platform and different video players. It looks like I found a way to fix it though and I'm creating a few PR. I'll keep you updated.

**Comment by quentinleguennec** [comment]
I added a fix for video orientation metadata when recording a video with the camera plugin. The PR is this one: flutter/plugins#1452
I also added a fix to the video_player. The PR is here: flutter/plugins#1451
Please don't hesitate to have a look at the PRs and leave comments or suggestions to push the review process.

**Comment by Dwarfie** [comment]
Hi @quentinleguennec , thanks for the response and the fix. I'm just not sure how I test it.
Is it similar to the way I have referenced map_view in the pub spec.yaml ?

map_view:
    git:
        url: git://github.com/Eimji/flutter_google_map_view.git

**Comment by Dwarfie** [comment]
I think I have figure that out, I copied the updated codebase to my projects level and:

  camera:
    path: ./plugins-tengio_camera_added_rotation_metadata_ios/packages/camera/
  path_provider: ^0.5.0
  video_player:
    path: ./plugins-tengio_improved_video_player/packages/video_player/
  firebase_storage: ^2.1.0+1

I can report that I can record video in Landscape and check it by saving to Firebase Storage

However the view finder on the sample app is messed up for both Portrait and Landscape.

![IMG_2969](https://user-images.githubusercontent.com/48934060/57117222-db6a9880-6d9d-11e9-8912-1ac06b802c93.png)
![IMG_2970](https://user-images.githubusercontent.com/48934060/57117232-eae9e180-6d9d-11e9-98c4-3c7d01ace809.png)

**Comment by quentinleguennec** [comment]
Hi @Dwarfie 
The cleanest way to test and use this modify version of the plugin would be to reference the giihub commit in your pubspec.yaml like this:
```
 video_player:
    git:
      url: git://github.com/tengio/plugins.git
      ref: 9d00507431d3d11e9d7b5f3db91bf4c86614c99b
      path: packages/video_player
  camera:
    git:
      url: git://github.com/tengio/plugins.git
      ref: 0793000a6b4e9f141dd2a18e9336a39cf98b4a07
      path: packages/camera
```

**Comment by quentinleguennec** [comment]
Now, when I worked on solving those issue I did 4 fixes in the camera plugin and video_player plugin. And it is quite possible it will only work well only with the 4 fixes together. Here is the list of PR (only one of them has been merged so far and I have yet to get any answer from reviewers on the others):
 - https://github.com/flutter/plugins/pull/1452
 - https://github.com/flutter/plugins/pull/1403
 - https://github.com/flutter/plugins/pull/1451
 - https://github.com/flutter/plugins/pull/1470

I created a branch with those 4 fixes merged together, I suggest you try this branch first and see if it works on your side:
https://github.com/Tengio/plugins/tree/tested4you_video_player_camera_merge

You can use it by adding this in your pubspec.yaml:
```
 video_player:
    git:
      url: git://github.com/tengio/plugins.git
      ref: 310a8f06c4981121a5553b0f6f3a8cdf475b8af1
      path: packages/video_player
  camera:
    git:
      url: git://github.com/tengio/plugins.git
      ref: 310a8f06c4981121a5553b0f6f3a8cdf475b8af1
      path: packages/camera
```
