### ISSUE TITLE
flutter build IOS Simulator Crashes: Runner quit unexpectedly 

### ISSUE THREAD

**Issue by mdtaqi98** [flutter/flutter#30101]
pubspec.yaml:

```
name: analise_test
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: 0.15.7
  font_awesome_flutter: 8.2.0
  timeago: 2.0.1
  firebase_auth: 0.7.0
  cloud_firestore: 0.8.2+3
  firebase_database: 1.0.5
  firebase_core: 0.2.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/login-screen-background.png
  - assets/signup-screen-background.png
  - assets/starrbucks.png
  - assets/mcdonalds.png
  - assets/photo_camera.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/Montserrat-Light.ttf
    - asset: assets/Montserrat-LightItalic.ttf
      style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
```  

##Pod File:
```
# platform :ios, '12.2'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do

    use_frameworks!
    pod 'Firebase/Core'

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }
  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

> 

Flutter Doctor: flutter doctor -v

```
/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale en-IN)
    • Flutter version 1.3.8 at /Users/mdtaqi/Downloads/flutter
    • Framework revision e5b1ed7a7f (3 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mdtaqi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/mdtaqi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5912.23

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone 6s • 649A0E13-9AA1-4F2B-9458-99DD1FC2CD19 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
Process finished with exit code 0
```

```
cd ios 
pod install
Ios Simulator => RUN
```

```
Launching lib/main.dart on iPhone 6s in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           113.8s
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001109ca6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010ff6eac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001109ca555 +[NSException raise:format:] + 197
	3   Runner                              0x000000010a524072 +[FIRApp configure] + 562
	4   Runner                              0x000000010a9b72b9 -[FLTCloudFirestorePlugin init] + 185
	5   Runner                              0x000000010a9b7169 +[FLTCloudFirestorePlugin registerWithRegistrar:] + 297
	6   Runner                              0x000000010a4cb210 +[GeneratedPluginRegistrant registerWithRegistry:] + 112
	7   Runner                        <…>
```

Error: IOS Simulator Crashes: Runner quit unexpectedly

Process:               Runner [8244]
Path:                  /Users/USER/Library/Developer/CoreSimulator/Devices/649A0E13-9AA1-4F2B-9458-99DD1FC2CD19/data/Containers/Bundle/Application/F4B6622F-3DA2-423A-B85D-203880CD657E/Runner.app/Runner
Identifier:            Runner
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [5880]
Responsible:           Runner [8244]
User ID:               501

Date/Time:             2019-03-28 15:13:49.870 +0530
OS Version:            Mac OS X 10.14.3 (18D109)
Report Version:        12
Anonymous UUID:        D39C8D84-3773-71B1-0F0A-850821481972

Time Awake Since Boot: 2400 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'
terminating with uncaught exception of type NSException
abort() called
CoreSimulator 587.35 - Device: iPhone 6s (649A0E13-9AA1-4F2B-9458-99DD1FC2CD19) - Runtime: iOS 12.2 (16E226) - DeviceType: iPhone 6s
Runner Docs:
![ios_Runner](https://user-images.githubusercontent.com/25418424/55148859-10684780-516f-11e9-9af8-62a34d3e34f4.png)
Pods Docs:
![Ios_pod](https://user-images.githubusercontent.com/25418424/55148902-24ac4480-516f-11e9-931f-cc4edf0ea27e.png)
