### ISSUE TITLE
[firebase_crashlytics] not reporting errors in firebase console

### ISSUE THREAD

**Issue by JuliethR** [flutter/flutter#30387]
I'm using firebase_crashlytics to report crash errors in my project but is not working. The library does not send the report to firebase console. I am using the following configs:

android/build.gradle:

```
dependencies {
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'io.fabric.tools:gradle:1.26.1'
    }
repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
```

android/app/build.gradle:

```
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.android.gms:play-services-basement:16.2.0'
    compile 'com.segment.analytics.android:analytics:4.+'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9'
}

apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
```

Included file google-services.json in android/app

pubspec.yaml:
```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.0.1
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  flutter_facebook_login: ^1.2.0
  flutter_secure_storage: ^3.1.3
  http: ^0.12.0
  intl: ^0.15.7
  flutter_cupertino_date_picker: ^0.3.0
  firebase_crashlytics: ^0.0.2
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
```

The flutter console printed "Error caught by Crashlytics plugin" and "Error reported to Crashlytics" but in firebase console I can't see the errors.

If I change the google-service.json configuration, for example the current_key, the result not change. 

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.2.1 at /home/julieth/Documentos/flutter
    • Framework revision 8661d8aecd (hace 7 semanas), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/julieth/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/73/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/73/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /home/julieth/Descargas/idea-IC-183.4886.37
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.31.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • Moto G Play • ZY2243K29F • android-arm • Android 7.1.1 (API 25)
```
