### ISSUE TITLE
Improve fallback font handling on Linux

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30700]
It's common for people running the shell to have missing text; https://github.com/google/flutter-desktop-embedding/issues/57 and https://github.com/google/flutter-desktop-embedding/issues/212 are two examples, but it's come up several other times as well.

We should ensure that the default font fallback handling for Linux has reasonably good behavior with the default fonts on popular distros (and potentially improve logging).

**Comment by stuartmorgan** [comment]
As part of this we need a solution for emoji handling; see https://github.com/google/flutter-desktop-embedding/issues/90 and https://github.com/flutter/flutter/issues/17786

**Comment by schmidp** [comment]
Happens on my Ubuntu 18.04.3 LTS Desktop as well. No fonts unless specified in the pubspec.yaml
BTW, specifying them like this:

```
fonts:
    - family: 'Roboto'
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf 
    - family: ''
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf 
```

"breaks" flutter web on the otherhand, fonts that should be thin, become bold.
