### ISSUE TITLE
[firebase_analytics plugin] Can't disable collection Android Advertising ID and my app was removed from Google Play

### ISSUE THREAD

**Issue by opengamer29** [flutter/flutter#30711]
## Steps to Reproduce

- create a simple flutter app, 
- add ```firebase_analytics: ^2.0.3``` dependencie
- add ```navigatorObservers: [
        FirebaseAnalyticsObserver(analytics: analytics),
      ],``` in ```MaterialApp```
- add ```<meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />``` in AndroidManifest.xml to disable collection of Android Advertising ID
- and google play blocked my app due to Violation of Usage of Android Advertising ID policy

## Logs

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.opengamer.profcomdiscount">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Profcom discount"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />

    </application>
</manifest>
```

```
pubspec.yaml

name: profcom_discount
description: An application with discounts for students.

version: 1.0.1+3

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.2
  firebase_storage: ^1.0.4
  qr_flutter: ^2.0.0
  url_launcher: ^5.0.1
  flutter_tags: ^0.2.2
  rxdart: ^0.21.0
  flutter_cache_manager: ^0.3.2
  cached_network_image: ^0.7.0
  firebase_analytics: ^2.0.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
```

```
Analyzing profcom_discount...                                           

   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/FirebaseCacheManager.dart:24:3 •
          sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/FirebaseCacheManager.dart:29:10 •
          sdk_version_async_exported_from_core
   info • Unused import: 'dart:async' • lib/HomeScreen.dart:1:8 • unused_import

3 issues found. (ran in 6.2s)

```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-RU)
    • Flutter version 1.2.1 at /Users/opengamer/Development/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/opengamer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/opengamer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Mi A2 • 1356f08 • android-arm64 • Android 9 (API 28)
```
