### ISSUE TITLE
Can't get cloud functions to work

### ISSUE THREAD

**Issue by ericel** [flutter/flutter#31403]
```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.8.4+2
  google_sign_in: ^4.0.1+3
  flutter_facebook_login: ^2.0.0
  cloud_functions: ^0.1.2+1
  firebase_core: ^0.3.4
  cloud_firestore: ^0.9.13+1
  scoped_model: ^1.0.1
  rxdart: ^0.21.0
```

App works well without cloud_functions: ^0.1.2+1. But When I include functions, do get packages and restart application, app breaks with no debugging errors.
