### ISSUE TITLE
Access to flavors on pubspec.yaml to gain more granular control over my artifacts

### ISSUE THREAD

**Issue by jorgecoca** [flutter/flutter#32036]
## Use case

As a developer, I'd like to have access to my Android/iOS flavors in my pubspec.yaml, so I can have more control over what's included in the final artifacts.

For example:
In an application that relies on using maps, I might want to use Google Maps everywhere except for China, where I would want to use a different provider, such as Autonavi. With the existing setup, I would end up including both Google Maps and Autonavi in my final apk/ipa. However, if I was able to access the flavors at the pubspec level, I could define a common API as a common module, and include Autonavi only on the chinese flavor, and GMaps on the other ones.

### Ideal solution:
I would have one `pubspec.yaml` that would look like this:

```yaml
name: flavors
description: flavors
version: 1.0.0

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  common:
    flutter:
      sdk: flutter
    common_map_api: 1.0.0
  china:
    autonavi_map: 1.0.0
  rest_of_the_wrold:
    google_maps: 1.0.0

flutter:
  uses-material-design: true
```

where `china` and `rest_of_the_world` would be my build flavors.

### Alternative solution:
As a transition plan, we could have a "pubspec generator". This generator would receive a different yaml with a format like this:

```yaml
common:
    flutter:
      sdk: flutter
    common_map_api: 1.0.0
  china:
    autonavi_map: 1.0.0
  rest_of_the_wrold:
    google_maps: 1.0.0
```

and when running the flutter application, it would generate a pubspec.yaml with only the necessary content depending on which flavor you are running.

This solution is far from ideal, though, since your pubspec would change its content depending on which flavor you run, creating, IMO, a lot of confusion for developers.
