### ISSUE TITLE
Could not find a file named "pubspec.yaml"

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#32033]
I am having this error when adding a new library to my pubspec.yaml.

`Could not find a file named "pubspec.yaml" in "C:\Users\shina\Desenvolvimento\flutter\.pub-cache\hosted\pub.dartlang.org\rxdart-0.21.0".
pub get failed (66)`

_More details about the problem_:
After doing a `pub packages get`, the library folder is created inside `flutter/.pub-cache/hosted/pub.dartlang.org/rxdart-0.21.0` but it's empty, not a single content inside.
The problem seens to happen to some libraries only, all the others are libraries are downloaded properly.

Here are some libraries that are not being downloaded by flutter tools:
* rxdart
* duration
* flutter_staggered_grid_view
* groovin_widgets

I've already tried:
* Deleting the `.pub-cache` folder.
* Reinstalling `flutter` by deleting the entire flutter folder and unzipping it again.
* Chaging the channel to `beta` and also `master`
* Creating a new project to see if maybe it's a pubspec problem. No success.

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [versÃ£o 10.0.17763.437], locale pt-BR)
    • Flutter version 1.2.1 at C:\Users\shina\Desenvolvimento\flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\shina\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
    • Flutter plugin version 35.2.3
    • Dart plugin version 191.7019

[√] VS Code (version 1.30.1)
    • VS Code at C:\Users\shina\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Moto G 5S • ZY322MBJ7L • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by Solido** [comment]
Did you check that your pubspec is well formated ?

**Comment by shinayser** [comment]
Yes!
It's bugging also for old projects already on github for months, not just one project.

:(

**Comment by Solido** [comment]
Post your PubSpec it will help.

**Comment by shinayser** [comment]
```
name: mydenox_flutter
description: MyDenox feito em Flutter.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.1.13+163

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  async_loader: ^0.1.2
  shared_preferences: ^0.5.1+1
  cached_network_image: ^0.7.0
  rxdart: ^0.21.0
#  collapsing_drawer: ^0.0.2
  flutter_map: ^0.1.4
  video_player: ^0.10.0+1
  package_info: ^0.4.0+2
  camera: ^0.4.2
  web_socket_channel: ^1.0.12
  flutter_spinkit: ^3.1.0
  flutter_speed_dial: ^1.1.0
  quiver: ^2.0.1 #HASHCODE
  flutter_masked_text: ^0.8.0
#  image: ^2.0.7
  permission_handler: ^3.0.0
  flutter_image_compress: ^0.3.1
  tinycolor: ^1.0.2
  device_info: ^0.4.0+1
  get_version: ^0.1.0
  #  flutter_statusbarcolor: 0.1.3
#  flutter_statusbar_manager: ^1.0.2
  vibrate: ^0.0.4
  bloc_pattern: ^1.5.1
  flutter_staggered_grid_view: ^0.2.7
  rounded_modal: ^1.0.0
  collection: ^1.14.11
  groovin_widgets: ^1.3.2
  flutter_native_timezone: 1.0.4
  datetime_picker_formfield: ^0.1.8
  google_maps_flutter: ^0.5.7
#  geocoder: ^0.1.2
  duration: ^2.0.4
#  hydrated: ^1.2.2
  google_maps_webservice: ^0.0.13
  carousel_slider: ^1.3.0
  image_picker: ^0.5.0+9
  qr_code_scanner: ^0.0.5
  location: ^2.3.5
  #  flutter_google_places: ^0.2.1
  #  flutter_speed_dial:
  #    git: git://github.com/darioielardi/flutter_speed_dial.git
  shinayser_essentials_flutter:
    git:
      url: https://github.com/shinayser/ShinayserEssentialsFlutter.git
      ref: 1.6.1

  geocoder:
    git:
      url: https://github.com/Eimji/flutter_geocoder.git

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/montserrat/Montserrat-Regular.ttf
    - assets/fonts/montserrat/Montserrat-Italic.ttf
    - assets/fonts/montserrat/Montserrat-Bold.ttf
    - assets/fonts/DenoxIcons.ttf
    - assets/image/
  #    - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        #           weight: 900
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
    #           weight: 900

    - family:  DenoxIcons
      fonts:
        - asset: assets/fonts/DenoxIcons.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```
