### ISSUE TITLE
`flutter create` pubspec.yaml contains a Dart version but not a Flutter version

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#32150]
An example pubspec.yaml from `flutter create`:
```yaml
name: foo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
```

Having a Dart version is potentially in conflict with Flutter's distribution mechanism of Dart, since `flutter upgrade` will pull new versions of dart automatically.

If we had a version it would make more sense to have a flutter version, since that version would control the dart version.

@Hixie mentioned that we might be including a Dart version because failing to do so might cause pub to default to 1.0?  I haven't tested myself.

FYI @mit-mit @munificent
