### ISSUE TITLE
Application is restarting the device

### ISSUE THREAD

**Issue by yuridiniz** [flutter/flutter#32261]
Some users are reporting on Google Play that the app is **restarting device**! 
Really ... I do not know what to do ...
I noticed that there are some similar incidents but I'm not sure if it's the same problem

## Steps to Reproduce

Unfortunately I do not have any devices that reproduce this, I ran the app in release mode in several Devices Farms and none reproduce this error.

These are the packages I'm using

```yml
dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.1
  firebase_analytics: ^2.1.1+3
  connectivity: ^0.4.3+1
  synchronized: ^2.1.0
  shared_preferences: ^0.5.2
  geolocator: "^3.0.1"
  intl: ^0.15.8
  firebase_messaging: 
    path: ../plugins/plugins/packages/firebase_messaging 
  bloc_provider: ^0.6.0  
  cupertino_icons: ^0.1.2
  rxdart: ^0.21.0
  http: ^0.12.0+2
  latlong: ^0.6.1
  location: ^2.3.5
  flutter_statusbar_manager:
    path: ../plugins/flutter_statusbar_manager 
  google_maps_flutter:
    path: ../plugins/plugins/packages/google_maps_flutter

dev_dependencies:
  build_runner: ^0.9.2
  built_path: ^0.1.0
  flutter_test:
    sdk: flutter
```

I found these other reports, but I do not know if it's the same problem, I really hope it's the same thing, because I'm aware that with just the information I'm going through it's really very difficult for you to debug the problem:

[https://github.com/flutter/flutter/issues/28208](https://github.com/flutter/flutter/issues/28208)
[https://github.com/flutter/flutter/issues/31844](https://github.com/flutter/flutter/issues/31844)
[https://github.com/flutter/flutter/issues/31580](https://github.com/flutter/flutter/issues/31580)

I'm here for what I can help!

## Logs

Log from Google Play 

Moto G (2nd Gen) (titan_umtsds) Android 6.0
Moto G (2nd Gen) (titan_udstv) Android 6.0

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> br.com.projectnetwork.onibus <<<

backtrace:
  #00  pc 0000000000043098  /system/lib/libc.so (tgkill+12)
  #01  pc 0000000000041d85  /system/lib/libc.so (pthread_kill+32)
  #02  pc 000000000001b8e7  /system/lib/libc.so (raise+10)
  #03  pc 0000000000018a99  /system/lib/libc.so (__libc_android_abort+34)
  #04  pc 0000000000016920  /system/lib/libc.so (abort+4)
  #05  pc 0000000000136b03  /data/app/br.com.projectnetwork.onibus-2/lib/arm/libflutter.so
  #06  pc 00000000001545a7  /data/app/br.com.projectnetwork.onibus-2/lib/arm/libflutter.so
  #07  pc 000000000012d903  /data/app/br.com.projectnetwork.onibus-2/lib/arm/libflutter.so
  #08  pc 000000000046b8c5  /data/app/br.com.projectnetwork.onibus-2/oat/arm/base.odex
```

```
[✓] Flutter (Channel master, v1.5.9-pre.148, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.5.9-pre.148 at /home/yuri/development/flutter
    • Framework revision d53115ab2e (6 hours ago), 2019-05-04 22:13:25 +0900
    • Engine revision 1d062db4db
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 dbe80f3397)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/yuri/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/yuri/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/yuri/android-studio
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.26.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

• No issues found!
```
