### ISSUE TITLE
[web]: Trouble with webdev serve (dev compiler)

### ISSUE THREAD

**Issue by bgetsug** [flutter/flutter#32347]
* Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale en-US)
* Chrome Version 74.0.3729.131 (Official Build) (64-bit)
* IntelliJ IDEA 2019.1.2 (Ultimate Edition) Build #IU-191.7141.32, built on April 30, 2019

## Excerpt of `pubspec.yaml`:
```yaml
#...

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

  firebase: ^5.0.3

#...

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
  json_serializable: ^2.2.2
  mockito: ^4.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```
## Excerpt of `lib/main.dart`:
```dart
import 'package:firebase/firebase.dart' as firebase;
import 'package:firebase/firestore.dart';

firebase.App fb;
Firestore firestore;

void main() async {
  fb = firebase.initializeApp(
    apiKey: "...",
    authDomain: "...",
    databaseURL: "...",
    projectId: "...",
    storageBucket: "...",
    messagingSenderId: "...",
  );

  firestore = fb.firestore();

//...
  runApp(App());
}
```

I'm attempting to get the [firebase](https://github.com/FirebaseExtended/firebase-dart) package to work with `flutter_web`. When running `webdev serve`, I receive the following error in the Chrome Dev Tools console:

```
require.js:143 Uncaught Error: type arguments should not be null: T => {
    class JsObjectWrapper extends core.Object {
      get jsObject() {
        return this[jsObject$];
      }
      set jsObject(value) {
        super.jsObject = value;
      }
    }
    (JsObjectWrapper.fromJsObject = function(jsObject) {
      this[jsObject$] = jsObject;
      ;
    }).prototype = JsObjectWrapper.prototype;
    dart.addTypeTests(JsObjectWrapper);
    JsObjectWrapper.prototype[_is_JsObjectWrapper_default] = true;
    const jsObject$ = Symbol("JsObjectWrapper.jsObject");
    dart.setFieldSignature(JsObjectWrapper, () => ({
      __proto__: dart.getFields(JsObjectWrapper.__proto__),
      jsObject: dart.finalFieldType(T)
    }));
    return JsObjectWrapper;
  }
    at Object.dart.throwInternalError (dart_sdk.js:3610)
    at Object.makeGenericType [as JsObjectWrapper$] (dart_sdk.js:3773)
    at top_level.dart:23
    at Object.execCb (require.js:1696)
    at Module.check (require.js:878)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```

The error looks similar to those shown in the following issues:
* https://github.com/dart-lang/sdk/issues/30082
* https://github.com/dart-lang/sdk/issues/34244
* https://github.com/dart-lang/sdk/issues/36001

**When I run `webdev serve -r` (production compiler), the app loads properly** (but is rather difficult to debug after minification).

**Comment by yjbanov** [comment]
/cc @vsmenon does this look like a DDC bug?

@bgetsug A workaround might be to build using `webdev serve -r` but disable minification in your `build.yaml` (a file next to your `pubspec.yaml`), for example:

```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
        - web/**.dart
        options:
          dart2js_args:
            - --no-minify
            - -O4
```

**Comment by bgetsug** [comment]
@yjbanov, thank you...definitely an acceptable workaround for now.

**Comment by vsmenon** [comment]
@yjbanov - definitely looks like a DDC bug.

**Comment by vsmenon** [comment]
I suspect specific to JS interop in DDC.  @natebosch - can you take a look?

**Comment by jakemac53** [comment]
You can also try using the old analyzer based DDC to see if that works, you can do that by limiting to `build_web_compilers: ^1.0.0` in your pubspec (at 2.0 it switched to kernel, and we are still shaking out a few bugs).

**Comment by natebosch** [comment]
Yeah, this is https://github.com/dart-lang/sdk/issues/36912

Here's the `build.yaml` I'd recommend if you want to use `dart2js` during development:

```yaml
targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        dev_options:
          compiler: dart2js
          dart2js_args:
            - --no-minify
```

**Comment by bgetsug** [comment]
With the following edit to my dependencies, as suggested by @jakemac53, my app appears to be running much better **for development**:
```yaml
dev_dependencies:
  build_runner: any
  build_web_compilers: '>=1.0.0 <2.0.0'
```

However, with or without those changes, if I use `webdev serve -r` (`dart2js`), with or without minify, I've noticed that my app breaks silently (no errors or warnings in Chrome console) in a number of places, including `CheckboxListTile`, the buttons I have in `trailing` on `ListTile`s, etc. I assume those are separate issues, but thought I'd mention here just in case.
