### ISSUE TITLE
[web build] webdev could not run for this project

### ISSUE THREAD

**Issue by Kermit-Xuan** [flutter/flutter#32456]
After running `pub get` and `flutter packages pub global run webdev build` in `flutter_web/examples/gallery`, it appears following error msg:

![image](https://user-images.githubusercontent.com/33770367/57498357-23456e80-730e-11e9-968d-9bde8ec4c1bb.png)

**Comment by ganeshp0001** [comment]
@Kermit-Xuan 
I was facing the same problem, as per the documentation I tried following command which worked:

`flutter packages pub global run webdev `

**Comment by Kermit-Xuan** [comment]
> @Kermit-Xuan
> I was facing the same problem when I was running "webdev serve" command, so as per the documentation I tried following command which worked:
> 
> `flutter packages pub global run webdev serve`

![image](https://user-images.githubusercontent.com/33770367/57590654-dfe23e80-755f-11e9-9b8b-1f4f95f5cfc0.png)

It don't work in my computer.

**Comment by Dibitybopty** [comment]
> 
> 
> @Kermit-Xuan
> I was facing the same problem when I was running "webdev serve" command, so as per the documentation I tried following command which worked:
> 
> `flutter packages pub global run webdev serve`

Worked perfect, thanks!

@Kermit-Xuan Did you try `flutter packages pub global activate webdev` ?

I followed the instructions from this site: [medium - Create and Deploy Flutter for Web](https://medium.com/flutter-community/flutter-create-and-deploy-a-website-from-scratch-4a026ebd6c)

**Comment by Kermit-Xuan** [comment]
> > @Kermit-Xuan
> > I was facing the same problem when I was running "webdev serve" command, so as per the documentation I tried following command which worked:
> > `flutter packages pub global run webdev serve`
> 
> Worked perfect, thanks!
> 
> @Kermit-Xuan Did you try `flutter packages pub global activate webdev` ?
> 
> I followed the instructions from this site: [medium - Create and Deploy Flutter for Web](https://medium.com/flutter-community/flutter-create-and-deploy-a-website-from-scratch-4a026ebd6c)

I try it. But it appears the same error.

**Comment by Unfreeze-kk** [comment]
```
flutter pub get 
```
then
```
flutter packages pub global run webdev serve
```
Try this.

**Comment by Kermit-Xuan** [comment]
> ```
> flutter pub get 
> ```
> 
> then
> 
> ```
> flutter packages pub global run webdev serve
> ```
> 
> Try this.

it doesn't work

**Comment by kevmoo** [comment]
@Kermit-Xuan so you run `flutter pub global run webdev serve`

What do you see? Can you paste the entire output? Can you also include the contents of `pubspec.yaml`?

**Comment by Kermit-Xuan** [comment]
@kevmoo The content of `pubspec.yaml`:
``` yml
name: flutter_web.examples.gallery

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  intl: ^0.15.7

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  flutter_web_test: any
  test: ^1.0.0

dependency_overrides:
  flutter_web:
    path: ../../packages/flutter_web
  flutter_web_test:
    path: ../../packages/flutter_web_test
  flutter_web_ui:
    path: ../../packages/flutter_web_ui
```

The output of running `flutter pub global run webdev serve`:

![image](https://user-images.githubusercontent.com/33770367/58296182-3de70f80-7e05-11e9-8636-58b9f725a443.png)
