### ISSUE TITLE
How should open-source packages deal with breaking changes in Flutter?

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#32474]
Some recent changes broke an open source package I maintain.
That's fine, and I did the fix.

But how can packages add proper version constraints to prevent that from happening?

I know that we can add the following to `pubspec.yaml`:

```yaml
environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: <something>
```

But Flutter doesn't use semantic versioning.

So we can't use version constraints similar to:

```yaml
environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">= 1.5.0 <= 1.6.0"
```

because between `1.5.0` and the latest version (currently `1.5.8`), there are multiple breaking changes introduced.
