### ISSUE TITLE
[web]: JS interop does not work within a flutter_web project with build_web_compilers 2.x

### ISSUE THREAD

**Issue by aryzhov** [flutter/flutter#32524]
I tried using the `firebase` package in my simple flutter_web app as follows:

```dart
import 'package:flutter_web/material.dart';
import 'package:firebase/firebase.dart';
import 'package:firebase/firestore.dart';

void main() {
  // The values were copied from Firebase console 
  initializeApp(
    apiKey: "...",
    authDomain: "...",
    databaseURL: "...",
    projectId: "...",
    storageBucket: "...",
    messagingSenderId: "...",
    name: "...",
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text("Hello"),
        ),
        body: Center(
          child: Text("Hello, Flutter"),
        ),
      ),
    );
  }
}
```

When I run the application, with the `initializeApp()` call, I get a blank page with an error in JS console:
```
Uncaught Error: type arguments should not be null: T => {
    class JsObjectWrapper extends core.Object {
      get jsObject() {
        return this[jsObject$];
      }
      set jsObject(value) {
        super.jsObject = value;
      }
    }
    (JsObjectWrapper.fromJsObject = function(jsObject) {
      this[jsObject$] = jsObject;
      ;
    }).prototype = JsObjectWrapper.prototype;
    dart.addTypeTests(JsObjectWrapper);
    JsObjectWrapper.prototype[_is_JsObjectWrapper_default] = true;
    const jsObject$ = Symbol("JsObjectWrapper.jsObject");
    dart.setFieldSignature(JsObjectWrapper, () => ({
      __proto__: dart.getFields(JsObjectWrapper.__proto__),
      jsObject: dart.finalFieldType(T)
    }));
    return JsObjectWrapper;
  }
    at Object.dart.throwInternalError (dart_sdk.js:3610)
    at Object.makeGenericType [as JsObjectWrapper$] (dart_sdk.js:3773)
    at top_level.dart:23
    at Object.execCb (require.js:1696)
    at Module.check (require.js:878)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```
Removing `initializeApp()` makes it run ok, so the error must be the result of `initializeApp()`.
I was assuming `firebase` package should work because its dependencies are only `http` and `js`.

## flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.13.6 17G6030, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.33.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

## pubspec.yaml
```
name: helloworld
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  firebase: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```

**Comment by natebosch** [comment]
This is most likely https://github.com/dart-lang/sdk/issues/36912

**Comment by kevmoo** [comment]
Going to close this out as a duplicate of dart-lang/sdk#36912 – not related to Flutter web work

**Comment by kevmoo** [comment]
Reopening so folks can find this one.

**Comment by bgetsug** [comment]
@aryzhov, I reported the same thing in #32347. Downgrading `build_web_compilers` worked for me:
```yaml
dev_dependencies:
  build_runner: any
  build_web_compilers: '>=1.0.0 <2.0.0'
```
