### ISSUE TITLE
[web]: Firebase Firestore web plugin 

### ISSUE THREAD

**Issue by passsy** [flutter/flutter#32637]
I'd like to use Firebase Firestore in my Flutter web app. What's the process?

Possible solutions:
- Communicate with the Firebase [javascript library](https://firebase.google.com/docs/web/setup) via platform channels. If so I'm looking for examples of how to communicate with js libraries.
- Use the [Rest API](https://firebase.google.com/docs/firestore/reference/rest) and build a pure dart package

**Comment by kevmoo** [comment]
Try this https://pub.dev/packages/firebase

But we are having issues – see https://github.com/flutter/flutter/issues/32524

**Comment by aryzhov** [comment]
@passy I've been able to make `firebase` package work in flutter_web after correcting `pubspec.yaml` as follows:
```yaml
dependencies:
  flutter_web: any
  flutter_web_ui: any
  firebase: any

dev_dependencies:
  build_runner: any
  build_web_compilers: '>=1.0.0 <2.0.0'
  pedantic: ^1.0.0
```
The key here is the version of `build_web_compilers`.
