### ISSUE TITLE
[cloud_firestore] startAfterDocument() doesn't work

### ISSUE THREAD

**Issue by dblokhin** [flutter/flutter#33021]
I'm trying to paginate comments. The first 10 comments is loading ok, but next ones (when query contains `startAfterDocument`) return error like:

```
Query(comments where movie_id == 1041047 order by -created, __name__) failed: Status{code=FAILED_PRECONDITION, description=The query requires an index. You can create it here: https://console.firebase.google.com/project/......., cause=null}
```

But this index is already exist, I created it before. And if I follow the suggestion link Firebase Console tells me the same: this index is exist.

```dart
  /// loads page of docs from previous one [lastDoc].
  Future<List<DocumentSnapshot>> _loadPageFrom(DocumentSnapshot lastDoc) async {
    final query = (lastDoc == null)
        ? Firestore.instance
            .collection('comments')
            .where('movie_id', isEqualTo: movieId)
            .orderBy('created', descending: true)
            .limit(10)
        : Firestore.instance
            .collection('comments')
            .where('movie_id', isEqualTo: movieId)
            .orderBy('created', descending: true)
            .startAfterDocument(lastDoc)
            .limit(10);

    final snapshot = await query.getDocuments();
    return snapshot.documents;
  }

```

```
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 7a4c33425d (3 недели назад) • 2019-04-29 11:05:24 -0700 
Engine • revision 52c7a1e849 Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```
```yaml
cloud_firestore:
    dependency: "direct main"
    description:
      name: cloud_firestore
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.0+2"
```
