### ISSUE TITLE
setting the userId in firebase admob rewarded video.

### ISSUE THREAD

**Issue by soofi-cheenilabs** [flutter/flutter#33033]
I am using the firebase rewarded video and there's a method called setUserId(String userId) in the following link: 
https://developers.google.com/android/reference/com/google/android/gms/ads/reward/RewardedVideoAd.html#setUserId(java.lang.String)

I am using the flutter firebase_admob plugin available at the link: 
https://github.com/flutter/plugins/tree/master/packages/firebase_admob

How to use the method setUserId(String userId) in flutter using the flutter firebase_admob plugin? I couldn't find this in the plugin. 

Will be thankful for the reply!

**Comment by soofi-cheenilabs** [comment]
This issue has been solved now as I included the following API:
```
public void setCustomData(String customData){
  // pass custom data to the server
}
```
This API is used for SSV (Server-Side Verification). 

I am currently using this API for passing custom data to the server. For those of you who are looking for an immediate solution and don't want to wait till the Google Flutter Team adds the missing APIs, can use this plugin by adding this plugin in the pubspec.yaml file in the following way:

```
dependencies:
  firebase_admob:
    git:
      url: git://github.com/soofi-cheenilabs/firebase_admob.git
  # your other dependencies
```
