### ISSUE TITLE
firebase_core-0.4.0+1  uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#33270]
I've been trying to use the auth, firestore firebase in an Android / IOS flutter application, and have been experiencing many different issues, after testing several different versions, now it's showing me several messages in the build.

build log
```console
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
ERROR: [TAG] Failed to resolve variable '${junit.version}'
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.11.0+2\android\src\main\java\io\flutter\plugins\fireb
ase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.11.0+2\android\src\main\java\io\flutter\plugins\fireb
ase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.3+1\android\src\main\java\io\flutter\plugins\connectiv
ity\ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+1\android\src\main\java\io\flutter\plugins\firebase
\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       100,6s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                         2,6s
I/FA      ( 9009): Tag Manager is not found and thus will not be used
I/OpenGLRenderer( 9009): Initialized EGL, version 1.4
D/OpenGLRenderer( 9009): Swap behavior 1
D/        ( 9009): HostConnection::get() New Host Connection established 0xdefd2fc0, tid 9055
W/OpenGLRenderer( 9009): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer( 9009): Swap behavior 0
D/EGL_emulation( 9009): eglCreateContext: 0xe2fc72e0: maj 3 min 1 rcv 4
D/EGL_emulation( 9009): eglMakeCurrent: 0xe2fc72e0: ver 3 1 (tinfo 0xe2f31bf0)
E/eglCodecCommon( 9009): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon( 9009): glUtilsParamSize: unknow param 0x000082da
D/        ( 9009): HostConnection::get() New Host Connection established 0xdef85180, tid 9041
D/EGL_emulation( 9009): eglCreateContext: 0xdb2eab00: maj 3 min 1 rcv 4
D/EGL_emulation( 9009): eglMakeCurrent: 0xdb2eab00: ver 3 1 (tinfo 0xe2ffecc0)
E/eglCodecCommon( 9009): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon( 9009): glUtilsParamSize: unknow param 0x000082da
D/EGL_emulation( 9009): eglMakeCurrent: 0xe2fc72e0: ver 3 1 (tinfo 0xe2f31bf0)
W/BiChannelGoogleApi( 9009): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@
e775b43
W/BiChannelGoogleApi( 9009): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@
e775b43
E/EnhancedIntentService( 9009): binding to the service failed

```

build.gradle file
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "br.gov.rj.riodasostras.appjazz"
        minSdkVersion 21
        multiDexEnabled true
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
   //sign release
    signingConfigs {
        release {
            keyAlias localProperties['keyAlias']
            keyPassword localProperties['keyPassword']
            storeFile file(localProperties['storeFile'])
            storePassword localProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            //signingConfig signingConfigs.debug
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.android.support:multidex:1.0.3' // abilita multidex
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

apply plugin: 'com.google.gms.google-services'
```

```yaml
name: appjazz
description: Aplicativo do Jazz e Blues

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  path_provider: ^0.5.0
  flutter_advanced_networkimage: ^0.4.15
  sqflite: ^1.1.0
  connectivity: ^0.4.3+1
  url_launcher: ^3.0.0  
  flutter_markdown: 
  cloud_firestore: ^0.11.0+2
  firebase_auth: ^0.11.1
  google_sign_in: ^4.0.1+3 

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.1

  assets:
    - assets/logoJazz.png
    - assets/bakground.jpg   
    - assets/fundo1.jpg
    - assets/fundo2.jpg
    - assets/fundo3.jpg     
    - assets/userAvatar.png
    - assets/logo-pmro-2018-cinza.png
    - assets/pmro2018-logo.png
    - assets/termos.txt
    - assets/sobreHeader.jpg

  fonts:
     - family: Big Noodle Titling
       fonts:
         - asset: fonts/big_noodle_titling.ttf
         - asset: fonts/big_noodle_titling_oblique.ttf
           style: italic
```
