### ISSUE TITLE
flutter packages upgrade not working in flutter for web project?

### ISSUE THREAD

**Issue by dev-akshat** [flutter/flutter#33309]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by arnemolland** [comment]
You're not providing any info or logs whatsoever. Please follow the issue template, as it's difficult to understand what you mean by "not working". There is no plugin system in place for flutter_web yet, which means that any packages depending on flutter will not work at the moment.

Your dependencies should look like this (with the inclusion of any pure dart dependencies you might have):
```yml
environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```

Also, make sure the `webdev` plugin is installed and activated as per the instructions.
