### ISSUE TITLE
Firestore runTransaction never runs

### ISSUE THREAD

**Issue by crushman1** [flutter/flutter#33310]
I have been stuck on this issue for weeks.
I am having the strangest problem. One day, out of the blue, runTransaction simply stopped running completely. no errors. no messages. any print statements i put there never runs. nothing. like as if the runTransaction statement is not there at all.
On IOS, sometimes it would run multiple times ( up to about 50) like as if it cant tell whether it ran itself or not. on android it just does nothing at all.

My code is exactly like the example code on the pub. if i just run `update `or `set `or `add `without the transaction it works perfectly.
```
final DocumentReference postRef = Firestore.instance.document('all_tokens/123');
Firestore.instance.runTransaction((Transaction tx) async {
                  DocumentSnapshot postSnapshot = await tx.get(postRef);
                  if (postSnapshot.exists) {
                    await tx.update(postRef, <String, dynamic>{'likesCount': postSnapshot.data['likesCount'] + 1});
                  }else{
                    await tx.set(postRef, <String, dynamic>{'likesCount': postSnapshot.data['likesCount'] + 1});
                  }
                });
```
No error messages at all. nothing in the `try catch`, nothing in `then`. The entire thing never runs. its like its being skipped.

here is my pubspec.yaml:

```
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  font_awesome_flutter: ^8.2.0
  fluttertoast: ^3.0.4
  datetime_picker_formfield: ^0.1.7
  flutter_image_compress: ^0.4.0
  cloud_firestore: ^0.11.0+2
  firebase_auth: ^0.11.1
  google_sign_in: ^4.0.1+3
  firebase_messaging: ^4.0.0+3
  shared_preferences: ^0.5.2
  firebase_storage: ^3.0.0
  flutter_rating: ^0.0.2
  flutter_typeahead: ^1.4.0
  url_launcher: ^4.0.3
  flutter_facebook_login: ^2.0.0
  algolia: ^0.1.5
  geolocator: ^4.0.3
  provider: ^2.0.1
```
Any help is greatly appreciated.

**Comment by alfiepoleon** [comment]
I have the same issue, worked a while back, think it stopped when I upgraded packages because of androidX, iOS works fine, here's the exact code:
```dart
// It checks for the current user in an array of users, updates inLobby bool to true, sends the new doc
Firestore.instance.runTransaction((Transaction tx) async {
      DocumentSnapshot postSnapshot =
          await tx.get(gameRef).catchError((e) => print(e));
      if (postSnapshot.exists) {
        // Get current user map from users array
        List players = postSnapshot.data['players'];
        final Map player =
            players.singleWhere((u) => u['uid'] == appState.user.uid);
        // Update the online status of the user map we've downloaded
        Map newPlayer = Map.from(player);
        newPlayer['inLobby'] = true;
        // Delete the user map on server
        await tx.update(gameRef, <String, dynamic>{
          'players': FieldValue.arrayRemove([player])
        });
        // Upload our copy
        await tx.update(gameRef, <String, dynamic>{
          'players': FieldValue.arrayUnion([newPlayer])
        });
      }
    });
```
Here is the `flutter doctor -v` output:
```zsh
→ flutter doctor -v                
[✓] Flutter (Channel dev, v1.6.3, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.6.3 at /Users/alfie/bin/flutter
    • Framework revision bc7bc94083 (25 hours ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alfie/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/alfie/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/alfie/Library/Android/sdk
    • Java binary at: /Users/alfie/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5529924/Android Studio 3.5
      Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Users/alfie/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5529924/Android Studio 3.5
      Preview.app/Contents
    • Flutter plugin version 35.3.2
    • Dart plugin version 191.7019
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.0.2 (API 21)
      (emulator)

• No issues found!
```

My dependencies:
```yaml
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.11.0+2
  firebase_auth: ^0.11.1
  # firebase_dynamic_links: ^0.4.0
  google_sign_in: ^4.0.1+3
  dio: ^2.0.11
  progress_indicators: ^0.1.2
  qr_flutter: ^2.0.0+51
  fluttertoast: ^3.0.3
  flutter_crashlytics: ^0.3.0
  cached_network_image: ^0.8.0
  flutter_launcher_icons: "^0.7.0"
  flutter_spinkit: "^3.1.0"
  flutter_platform_widgets: ^0.9.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
```
