### ISSUE TITLE
Programmatically show a Marker InfoWindow on Google Map

### ISSUE THREAD

**Issue by RyanRamchandar** [flutter/flutter#33481]
Add a way to programmatically show a Marker InfoWindow on a Google Map widget.

![image](https://user-images.githubusercontent.com/3187342/58521263-9873c900-8181-11e9-9023-be9eb798ef6e.png)

On Android: https://stackoverflow.com/a/15899827/723980

Related: #29899

**Comment by RyanRamchandar** [comment]
@iskakaushik

**Comment by lucien-theron** [comment]
related to #29899 and #19647

**Comment by sh0umik** [comment]
Any updates ?

**Comment by cataCostea** [comment]
any updates on this issue?

**Comment by mathronaut** [comment]
I am also waiting for this feature.

**Comment by overgaardmorten** [comment]
Awaiting this feature - any news?

**Comment by giancarlopro** [comment]
I did implement `showInfoWindow` for a private project.

as a workaround you could use my implementation, just replace `google_maps_flutter` dependency with
```YAML
google_maps_flutter:
    git:
      url: git://github.com/giancarlopro/plugins.git
      path: packages/google_maps_flutter
      ref: development
```
and use your `GoogleMapController` to show the info window
```Dart
googleMapController.showMarkerInfoWindow(markerId);
```

I'm planning to make a pull request for this issue, but as i need this feature too i'm trying to maintain my `development` branch synced with flutter's `master` branch while i figure out a better way to do it.
