### ISSUE TITLE
flutter_web

### ISSUE THREAD

**Issue by nxSin** [flutter/flutter#33651]
VSCode , Use  F5 run project , I get error :

```
webdev could not run for this project.
This version of webdev does not support the `build_daemon` protocol used by your version of `build_runner`.
A newer version of webdev is available which supports your version of the `build_daemon`. Please update.
```
but , I use webdev serve in terminal  , can run project

config:

![image](https://user-images.githubusercontent.com/14179843/58699688-a5d2c280-83d0-11e9-8af1-a9bffe09d468.png)

**Comment by timsneath** [comment]
What version of `webdev` do you have installed? (Run `webdev --version` from a command line)

**Comment by gray419** [comment]
This is also happening for me.  I created a new web project from the VS Code plugin. 

webdev version `2.0.4`

**Comment by gray419** [comment]
Fixed temporarily by bumping down the `build_daemon` from `1.0.0` to `0.6.1`

```
dev_dependencies:
  build_runner: ^1.4.0
  build_daemon: 0.6.1
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
```
