### ISSUE TITLE
after install google_maps_flutter the app doesn't start on iOS

### ISSUE THREAD

**Issue by MorochoRochaDarwin** [flutter/flutter#33716]
these are my dependeces in my `pubspec.yaml`
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  google_maps_flutter: ^0.5.15
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  flutter_spinkit: "^3.1.0"
  firebase_core: ^0.4.0
  firebase_auth: ^0.11.0
  google_sign_in: ^4.0.1+3
  pointycastle: ^1.0.1
  flutter_svg: ^0.12.0
  flutter_secure_storage: ^3.2.1+1

```

after install  `google_maps_flutter: ^0.5.15` and tried to run my app the app launch not woking
```
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3
    @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: targeted OS version does not support use of thread local variables in __ZN9GMSx_absl18container_internal21ShouldInsertBackwardsEmPa for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)


```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14 18A391, locale es-EC)
    • Flutter version 1.5.4-hotfix.2 at /Users/macboookpro/development/flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/macboookpro/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/macboookpro/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone X • FA8578EA-ADC9-4F0F-AFDB-57EA99D09B6D • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.


```
