### ISSUE TITLE
google_maps_flutter plugin fails to compile with Flutter v.1.7.0

### ISSUE THREAD

**Issue by DewangS** [flutter/flutter#33888]
## Steps to Reproduce

My pubspec.yaml looks like ...

```
name: my_mobile_app
description: My mobile application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^4.0.1
  flutter_launcher_icons: "^0.6.1"
  json_annotation: ^2.0.0
  flutter_webview_plugin: ^0.3.0+2
  webfeed: ^0.4.2
  http: ^0.12.0+1
  #map_view: "^0.0.14"
  google_maps_flutter: ^0.2.0+3
  location: "^1.4.0"
  xml: "^3.0.0"
  intl: ^0.15.7
  sqflite: ^1.1.0
  path: ^1.6.2
  path_provider: ^0.5.0+1
  
dev_dependencies:
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter
```
when I run flutter build apk  from command line, I get below errors and build fails...

## Logs

```
Initializing gradle...                                              0.8s
Resolving dependencies...                                           1.5s
D8: Program type already present: android.support.v4.app.INotificationSideChannel
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/31.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/32.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/33.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/34.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/35.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/37.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/38.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/39.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/40.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/41.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/42.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/43.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/44.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/45.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/46.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/47.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/48.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/49.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/50.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/51.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/52.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/53.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/54.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/55.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/56.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/57.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/58.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/59.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/60.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/61.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/62.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/63.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/64.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/65.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/66.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/67.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/68.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/69.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/70.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/71.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/72.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/73.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/74.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/75.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/76.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/77.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/78.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/79.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/80.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/81.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/82.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/83.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/84.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/85.jar, /Users/dewang/wsumobileapps/western-sydney-mobile-app/build/app/intermediates/transforms/dexBuilder/release/86.jar
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 16s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      16.9s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleRelease failed with exit code 1
```

```
```

```
```
