### ISSUE TITLE
[firebase_performance] iOS crashes and Android throws an error on a hot restart

### ISSUE THREAD

**Issue by wreppun** [flutter/flutter#34165]
## Steps to Reproduce

1.  Add `firebase_performance` package
2. Call `FirebasePerformance.instance` somewhere in the code
3. Hot _restart_ the app

### iOS

```
Performing hot restart...                                       
Restarted application in 1,378ms.
Lost connection to device.
*** First throw call stack:
(
        0   CoreFoundation                      0x000000010b31f6fb __exceptionPreprocess + 331
        1   libobjc.A.dylib                     0x000000010a8cbac5 objc_exception_throw + 48
        2   Runner                              0x0000000102ea07c0 +[FLTFirebasePerformancePlugin addMethodHandler:methodHandler:] + 288
        3   Runner                              0x0000000102ea04d5 -[FLTFirebasePerformancePlugin handleMethodCall:result:] + 325
        4   Flutter                             0x0000000108abdb9a __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
        5   Flutter                             0x0000000108adbc52 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
        6   Flutter                             0x0000000108adf1ee _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessage<…>
```

### Android

```
I/flutter ( 9261): PlatformException(error, Object for handle already exists: 0, null)                          
I/flutter ( 9261): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
I/flutter ( 9261): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
I/flutter ( 9261): <asynchronous suspension>
I/flutter ( 9261): #2      new FirebasePerformance._ (package:firebase_performance/src/firebase_performance.dart:15:13)
I/flutter ( 9261): #3      FirebasePerformance.instance (package:firebase_performance/src/firebase_performance.dart:31:27)
I/flutter ( 9261): #4      FirebasePerformance.instance (package:firebase_performance/src/firebase_performance.dart:30:36)
I/flutter ( 9261): #5      new _MetricHttpClient (package:unrulr_mobile/data/external/api.dart:30:37)
I/flutter ( 9261): #6      new Api._internal (package:unrulr_mobile/data/external/api.dart:196:37)
I/flutter ( 9261): #7      Api.instance (package:unrulr_mobile/data/external/api.dart:180:35)
I/flutter ( 9261): #8      Api.instance (package:unrulr_mobile/data/external/api.dart:180:20)
I/flutter ( 9261): #9      new Api (package:unrulr_mobile/data/external/api.dart:187:12)
I/flutter ( 9261): #10     new AuthenticationBloc (package:unrulr_mobile/blocs/authentication_bloc.dart:37:16)
```

### flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (2 available)
```

pubspec (firebase)

```
  firebase_analytics: ^3.0.1
  firebase_auth: ^0.11.1
  firebase_core: ^0.4.0+1
  firebase_messaging: ^5.0.1+1
  firebase_performance: ^0.3.0
```

lock file (firebase)

```
  firebase_analytics:
    dependency: "direct main"
    description:
      name: firebase_analytics
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  firebase_auth:
    dependency: "direct main"
    description:
      name: firebase_auth
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.1+1"
  firebase_core:
    dependency: "direct main"
    description:
      name: firebase_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.0+1"
  firebase_messaging:
    dependency: "direct main"
    description:
      name: firebase_messaging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.1+1"
  firebase_performance:
    dependency: "direct main"
    description:
      name: firebase_performance
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.0"
```
