### ISSUE TITLE
Dropdown bug doesn't work with scoped-model

### ISSUE THREAD

**Issue by netopaez97** [flutter/flutter#34168]
Good afternoon, dear community.

I am using the scoped-model package to centralize a dropdownbutton. I am giving a list of item to the dropdown, but when I call the list, the debug-console shows me an error. It says: the items parameters is null. Look at the code.

The dropdown:
```
Widget _calificacion( Function actualizarReporteEnPunto) {
    return
      Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          DropdownButton(
            value: widget.valor, //This value is arrived from other page
            items: listaCalificaciones,
            //hint: Text('Calificación'),
            onChanged: (value) => {
              setState(() {
                actualizarReporteEnPunto('chasisDerecho', 'otro', 'calificacion', value);
              })
            },
          )
        ],
      );
  }
```

The list of items:
```
List<DropdownMenuItem<String>> listaCalificaciones = [];
  void cargarDropDownCalificacion() {
      listaCalificaciones.add( DropdownMenuItem (
        child: new Text('OK'),
        value: 'OK',
      ));
      listaCalificaciones.add( DropdownMenuItem (
        child: new Text('P0'),
        value: 'P0',
      ));
      listaCalificaciones.add( DropdownMenuItem (
        child: new Text('P1'),
        value: 'P1',
      ));
      listaCalificaciones.add( DropdownMenuItem (
        child: new Text('P2'),
        value: 'P2',
      ));
      listaCalificaciones.add( DropdownMenuItem (
        child: new Text('P3'),
        value: 'P3',
      ));
      listaCalificaciones.add( DropdownMenuItem (
        child: new Text('P4'),
        value: 'P4',
      ));
      listaCalificaciones.add( DropdownMenuItem (
        child: new Text('NA'),
        value: 'NA',
      ));
      listaCalificaciones.add( DropdownMenuItem (
        child: new Text('NI'),
        value: 'NI',
      ));
  }
```

The init state
```
  @override
  initState() {
    super.initState();
    _controller = TextEditingController(text: widget.valor); //You can ignore this
    cargarDropDownCalificacion();
  }
```

And the output shows:

> flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building ScopedModelDescendant<MainModel>(dirty, dependencies:
flutter: [_InheritedModel<MainModel>]):
flutter: 'package:flutter/src/material/dropdown.dart': Failed assertion: line 609 pos 15: 'items == null ||
flutter: items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value ==
flutter: value).length == 1': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md

![9AD9203C-257B-43B4-97E3-A52DD3AC33B7](https://user-images.githubusercontent.com/48258819/59219651-a0236c80-8b88-11e9-9a4c-a14493f6aace.png)

The error is showed in the column C of the picture.

These are my dependencies:

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.4.12
  firebase_storage: ^1.0.4
  http: ^0.12.0+1
  photo_view: ^0.2.4
  intl: ^0.15.8
  flutter_datetime_picker: ^1.1.6
  firebase_database: ^1.0.5
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
```
