### ISSUE TITLE
firebase_core 0.4.x ../../pubspec.yaml (No such file or directory)

### ISSUE THREAD

**Issue by DagobertDokate** [flutter/flutter#34385]
Hello, everybody,

I'm trying to integrate Firebase right now. Flutter shows me no errors.
But when I compile the apk it breaks and it fails:
```
* Error running Gradle:
ProcessException: Process "/Users/.../Projekte/test/mepmep/android/gradlew" exited abnormally:
         *********************************************************
WARNING: This version of firebase_analytics will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/.../Library/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.0+4/android/build.gradle' line: 44

* What went wrong:
A problem occurred evaluating project ':firebase_core'.
> ../../pubspec.yaml (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command: /Users/.../Projekte/test/mepmep/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
```
pubspec.yaml:
```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+4
  firebase_analytics: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
Does anyone know advice?
