### ISSUE TITLE
Lost connection to device(iOS)

### ISSUE THREAD

**Issue by TheKonnectApp** [flutter/flutter#34497]
**Issue:**
I am working on an app that simply loads profile pictures(from Firebase Storage), loads user information from Firebase Cloud Firestore and uses Google Maps API to show a map where the user can mark locations. On an iOS device, when I tap slowly through my app I get zero crashes but when I start switching between my pages at a fast rate the app will crash with no output error except for "Lost Connection To Device". 

**What I have tried:**
1. I thought it was my dependencies causing the _Lost Connection To Device_ error so I have changed them all around from the newest to the ones I first started with. No luck there.
2. I have thoroughly went through my code to make sure I haven't made a mistake. Please see attached an example page where I fetch a user's notifications. Do I need to override and dump memory myself?
3. I have tested this on real devices for both Android and iOS. The Android device doesn't have the random crashes like the iOS device does. 

**Flutter Doctor(This is from my windows laptop, I normally do most of my development from my MacMini where I have zero Flutter Doctor issues):**
```
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.829], locale en-US)
    • Flutter version 1.6.3 at C:\Users\Whitten\Desktop\FlutterSDK\flutter
    • Framework revision bc7bc94083 (3 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Whitten\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.34.0)
    • VS Code at C:\Users\Whitten\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**My Dependencies(Yes, I am currently using older dependencies as I thought it was a dependency issue but that's not the case as I have tested with the latest updates for of all my dependencies):**
```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.1+1 # add dependency for Firebase Core
  firebase_analytics: ^2.0.3
  cloud_firestore: ^0.9.5+2
  firebase_auth: ^0.8.1+4
  firebase_storage: ^2.1.0+1
  google_sign_in: ^4.0.1+1
  google_maps_flutter: ^0.5.7
  location: ^2.3.0
  geolocator: ^3.0.1
  http: ^0.12.0+1
  webview_flutter: ^0.3.6
  shared_preferences: ^0.5.2
  image_picker: ^0.6.0+9
  datetime_picker_formfield: ^0.2.0
  firebase_messaging: ^4.0.0+4
  #cached_network_image: ^0.8.0
  transparent_image: ^1.0.0
  #extended_image: ^0.3.2
  flutter_screenutil: ^0.5.2
  latlong: ^0.6.1
  flutter_google_places: ^0.2.3
  flutter_facebook_login: ^2.0.0
  flutter_signin_button: ^0.2.8
  square_in_app_payments: ^1.1.1
  cloud_functions: ^0.2.0+1
  image: ^2.1.1
  path_provider: ^1.1.0
  flutter_native_image: ^0.0.4
```
**Sample Code of Notifications Page:**
**Please see attached!**
[user_notifications_page.zip](https://github.com/flutter/flutter/files/3290992/user_notifications_page.zip)

**My Theory:**
1. My theory is that the app is using way to much RAM and the iOS device(I'm using an XS Max) isn't garbage collecting fast enough and thus the app is crashing. Please see below a Android Studio Profiler output:
**Android Device ~150MB**
![KonnectAndroidProfilerOutput](https://user-images.githubusercontent.com/43386300/59516385-3c9e8500-8e8f-11e9-840e-6bb44e8e96d1.PNG)

**I am currently not at my MacMini but when I run the Android Profiler I am getting an outputs that sometimes say 0.3Gb (YES, Gigabyte) and then other times it will stay between 400-500MB before it crashes. When I get home i will post up the snapshot.**

Any ideas? This is the only thing stopping me from publishing this app to the App Store right now. I have completed all of the functionality that was desired for the app. But with random crashes like this, there's no way I can publish it.
