### ISSUE TITLE
flutter pub run build_runner build failed in CI

### ISSUE THREAD

**Issue by codekeyz** [flutter/flutter#34492]
## Details

When i run this command `flutter pub run build_runner build` locally, it works just fine, generates `*.g.dart*` files. But when i run in Gitlab CI, doesn't work. It throws an error

## Logs

```
$ flutter pub run build_runner build
Failed to set file modification time, path = './pubspec.lock' (OS Error: Operation not permitted, errno = 1)
---- Log transcript ----
FINE: Pub 2.3.0-dev.0.5.flutter-a1668566e5
ERR : Failed to set file modification time, path = './pubspec.lock' (OS Error: Operation not permitted, errno = 1)
FINE: Exception type: FileSystemException
FINE: dart:io                                 _File.setLastModifiedSync
    | package:pub/src/io.dart 802:39          touch
    | package:pub/src/entrypoint.dart 404:9   Entrypoint.assertUpToDate
    | package:pub/src/entrypoint.dart 108:5   Entrypoint.packageGraph
    | package:pub/src/command/run.dart 70:25  RunCommand.run
    | ===== asynchronous gap ===========================
    | dart:async                              _AsyncAwaitCompleter.completeError
    | package:pub/src/command/run.dart        RunCommand.run
---- End log transcript ----
pub failed (66)

```

##  flutter docter -v
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/precious/Flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/precious/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/precious/Android/Studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/precious/Android/Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.35.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.1.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

## Gitlab CI .gitlab-ci.yml
```yml
image: cirrusci/flutter
stages:
  - build

build:apk:
  stage: build
  script:
    # - flutter pub get
    # - flutter pub run build_runner build --delete-conflicting-outputs
    - flutter packages get
    - flutter pub run build_runner build
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release
    expire_in: 5 days

```
