### ISSUE TITLE
webview_flutter plugin JavaScript popup boxes are not shown

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#34853]
In Android WebView, JavaScript popups normally work without any extra coding in the WebView. Unfortunately, they are not working in my app using webview_flutter plugin. 

## Steps to Reproduce

You can reproduce by setting your webview_flutter plugin running on Android url to: 'https://www.w3schools.com/js/tryit.asp?filename=tryjs_confirm' and clicking the "try it" button. 

## Logs
```
[+5119 ms] D/ViewRootImpl@b42e355[MainActivity](26027): ViewPostIme pointer 0 

[  +93 ms] D/ViewRootImpl@b42e355[MainActivity](26027): ViewPostIme pointer 1 

[  +23 ms] W/cr_WebViewCallback(26027): Unable to create JsDialog without an Activity 

[   +2 ms] D/InputMethodManager(26027): HSIFW - flag : 0 Pid : 26027 

[        ] I/InputMethodManager(26027): hideSoftInputFromWindow ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :io.flutter.view.FlutterView{e9b5fd1 VFE...... .F....I. 0,0-1920,1200} 
```

**Comment by jerryzhoujw** [comment]
Same in iOS's webview.

**Comment by jerryzhoujw** [comment]
You can use
```
flutter_webview_plugin:
    git:
      ref: "dev/fix_alert_not_work_in_webview"
      url: "https://github.com/jerryzhoujw/flutter_webview_plugin"
      source: git
```
this as temp in `pubspec.yaml` before merge [PR](https://github.com/fluttercommunity/flutter_webview_plugin/pull/522)
