### ISSUE TITLE
Upgrade Google Play Developer API

### ISSUE THREAD

**Issue by maxlapides** [flutter/flutter#34881]
The Google Play Store has started giving me this warning:

>We’ve detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date.

It links to this page: https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

Does anyone have any idea where this might be coming from? I'm not using in-app purchases or anything. I'm not sure where in my app the Google Play Developer API is being used, or how I would update it.

```
❯ flutter doctor -v
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.6.3 at /Users/maxlapides/flutter
    • Framework revision bc7bc94083 (4 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/maxlapides/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/maxlapides/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone X • A43FAF21-05EC-4D53-86C4-B63C319D5247 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by eseidelGoogle** [comment]
Would you be willing to share the dependencies list from your pubspec.yaml?  Thanks!

**Comment by maxlapides** [comment]
@eseidelGoogle Sure!

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^2.0.1
  built_collection: ^4.2.2
  built_redux: ^7.5.3
  built_value: ^6.6.0
  cached_network_image: ^0.8.0
  convert: ^2.1.1
  cupertino_icons: ^0.1.2
  device_info: ^0.4.0
  firebase_core: ^0.4.0
  firebase_analytics: ^3.0.2
  flutter_built_redux: ^0.6.0
  flutter_launcher_icons: ^0.7.2
  flutter_secure_storage: ^3.2.1
  flutter_slidable: ^0.5.3
  flutter_statusbarcolor: ^0.2.0
  flutter_sticky_header: ^0.4.0
  flutter_svg: ^0.13.0
  http: ^0.12.0
  intl_translation: ^0.17.4
  intl: ^0.15.8
  launch_review: ^2.0.0
  memoize: ^2.0.0
  mockito: ^4.1.0
  package_info: ^0.4.0
  path_drawing: ^0.4.1
  path_provider: ^0.5.0+1
  pedantic: ^1.5.0
  pub_semver: ^1.4.2
  quiver: ^2.0.3
  reselect: ^0.4.0
  sentry: ^2.2.0
  stream_transform: ^0.0.19
  uri: ^0.11.3
  url_launcher: ^5.0.2

dev_dependencies:
  build_runner: ^1.3.1
  built_value_generator: ^6.5.0
  flutter_test:
    sdk: flutter
```

**Comment by eseidelGoogle** [comment]
launch_review looks like the potential user of the API?

**Comment by eseidelGoogle** [comment]
It also might be possible via gradle to figure out the dependencies?
https://stackoverflow.com/questions/21645071/using-gradle-to-find-dependency-tree

I'm not sure.  Another way we could test if this is "core flutter" is to see if this warning appears when we next publish the Flutter Gallery.

**Comment by eseidelGoogle** [comment]
@RedBrogdon can you keep a look out for this next time you're pushing to the store?  If this is a general issue, we will need to take action.  If this is just due to a single plugin in @maxlapides's app, there may be action in our ecosystem to take as well (but likely less urgency).  Thanks!

FYI @tvolkert @Hixie.

**Comment by maxlapides** [comment]
Ah thanks @eseidelGoogle! I was able to get a tree of dependencies out of Gradle and it looks like it might actually be `firebase_analytics` but I'm not entirely sure I'm reading this thing right 🤔 Here's a chunk that seems relevant:

```
releaseCompileClasspath - Resolved configuration for compilation for variant: release
+--- project :flutter_secure_storage
+--- project :sqflite
+--- project :device_info
+--- project :package_info
+--- project :flutter_statusbarcolor
+--- project :url_launcher
+--- project :firebase_analytics
|    \--- com.google.firebase:firebase-analytics:16.5.0
|         +--- com.google.android.gms:play-services-measurement:16.5.0
|         |    +--- com.google.android.gms:play-services-basement:16.2.0
|         |    |    \--- com.android.support:support-v4:26.1.0
|         |    |         +--- com.android.support:support-compat:26.1.0
|         |    |         |    +--- com.android.support:support-annotations:26.1.0
|         |    |         |    \--- android.arch.lifecycle:runtime:1.0.0
|         |    |         |         +--- android.arch.lifecycle:common:1.0.0
|         |    |         |         \--- android.arch.core:common:1.0.0
|         |    |         +--- com.android.support:support-media-compat:26.1.0
|         |    |         |    +--- com.android.support:support-annotations:26.1.0
|         |    |         |    \--- com.android.support:support-compat:26.1.0 (*)
|         |    |         +--- com.android.support:support-core-utils:26.1.0
|         |    |         |    +--- com.android.support:support-annotations:26.1.0
|         |    |         |    \--- com.android.support:support-compat:26.1.0 (*)
|         |    |         +--- com.android.support:support-core-ui:26.1.0
|         |    |         |    +--- com.android.support:support-annotations:26.1.0
|         |    |         |    \--- com.android.support:support-compat:26.1.0 (*)
|         |    |         \--- com.android.support:support-fragment:26.1.0
|         |    |              +--- com.android.support:support-compat:26.1.0 (*)
|         |    |              +--- com.android.support:support-core-ui:26.1.0 (*)
|         |    |              \--- com.android.support:support-core-utils:26.1.0 (*)
|         |    +--- com.google.android.gms:play-services-measurement-base:[16.5.0] -> 16.5.0
|         |    |    \--- com.google.android.gms:play-services-basement:16.2.0 (*)
|         |    +--- com.google.android.gms:play-services-measurement-impl:[16.5.0] -> 16.5.0
|         |    |    +--- com.google.android.gms:play-services-ads-identifier:16.0.0
|         |    |    |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    |    +--- com.google.android.gms:play-services-basement:16.2.0 (*)
|         |    |    +--- com.google.android.gms:play-services-measurement-base:[16.5.0] -> 16.5.0 (*)
|         |    |    \--- com.google.android.gms:play-services-stats:16.0.1
|         |    |         \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    \--- com.google.android.gms:play-services-stats:16.0.1 (*)
|         +--- com.google.android.gms:play-services-measurement-api:16.5.0
|         |    +--- com.google.android.gms:play-services-basement:16.2.0 (*)
|         |    +--- com.google.android.gms:play-services-measurement-base:[16.5.0] -> 16.5.0 (*)
|         |    +--- com.google.android.gms:play-services-measurement-impl:[16.5.0] -> 16.5.0 (*)
|         |    +--- com.google.android.gms:play-services-measurement-sdk-api:[16.5.0] -> 16.5.0
|         |    |    +--- com.google.android.gms:play-services-basement:16.2.0 (*)
|         |    |    \--- com.google.android.gms:play-services-measurement-base:[16.5.0] -> 16.5.0 (*)
|         |    +--- com.google.android.gms:play-services-tasks:16.0.1
|         |    |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    +--- com.google.firebase:firebase-common:16.0.3 -> 16.1.0
|         |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    |    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|         |    |    \--- com.google.auto.value:auto-value-annotations:1.6
|         |    +--- com.google.firebase:firebase-iid:17.1.2
|         |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    |    +--- com.google.android.gms:play-services-stats:16.0.1 (*)
|         |    |    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|         |    |    +--- com.google.firebase:firebase-common:16.1.0 (*)
|         |    |    \--- com.google.firebase:firebase-iid-interop:16.0.1
|         |    |         +--- com.google.android.gms:play-services-base:16.0.1
|         |    |         |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    |         |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|         |    |         \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         |    \--- com.google.firebase:firebase-measurement-connector:17.0.1
|         |         \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.2.0 (*)
|         \--- com.google.android.gms:play-services-measurement-sdk:16.5.0
|              +--- com.google.android.gms:play-services-basement:16.2.0 (*)
|              +--- com.google.android.gms:play-services-measurement-base:[16.5.0] -> 16.5.0 (*)
|              +--- com.google.android.gms:play-services-measurement-impl:[16.5.0] -> 16.5.0 (*)
|              \--- com.google.android.gms:play-services-measurement-sdk-api:[16.5.0] -> 16.5.0 (*)
+--- project :path_provider
+--- project :launch_review
+--- project :firebase_core
|    \--- com.google.firebase:firebase-core:16.0.9
|         \--- com.google.firebase:firebase-analytics:16.5.0 (*)
+--- com.google.firebase:firebase-core:11.4.2 -> 16.0.9 (*)
+--- com.google.firebase:firebase-analytics:{strictly 16.5.0} -> 16.5.0 (c)
+--- com.google.android.gms:play-services-measurement:{strictly 16.5.0} -> 16.5.0 (c)
+--- com.google.android.gms:play-services-basement:{strictly 16.2.0} -> 16.2.0 (c)
+--- com.android.support:support-v4:{strictly 26.1.0} -> 26.1.0 (c)
+--- com.android.support:support-compat:{strictly 26.1.0} -> 26.1.0 (c)
+--- com.android.support:support-annotations:{strictly 26.1.0} -> 26.1.0 (c)
+--- android.arch.lifecycle:runtime:{strictly 1.0.0} -> 1.0.0 (c)
+--- android.arch.lifecycle:common:{strictly 1.0.0} -> 1.0.0 (c)
+--- android.arch.core:common:{strictly 1.0.0} -> 1.0.0 (c)
+--- com.android.support:support-media-compat:{strictly 26.1.0} -> 26.1.0 (c)
+--- com.android.support:support-core-utils:{strictly 26.1.0} -> 26.1.0 (c)
+--- com.android.support:support-core-ui:{strictly 26.1.0} -> 26.1.0 (c)
+--- com.android.support:support-fragment:{strictly 26.1.0} -> 26.1.0 (c)
+--- com.google.android.gms:play-services-measurement-base:{strictly 16.5.0} -> 16.5.0 (c)
+--- com.google.android.gms:play-services-measurement-impl:{strictly 16.5.0} -> 16.5.0 (c)
+--- com.google.android.gms:play-services-ads-identifier:{strictly 16.0.0} -> 16.0.0 (c)
+--- com.google.android.gms:play-services-stats:{strictly 16.0.1} -> 16.0.1 (c)
+--- com.google.android.gms:play-services-measurement-api:{strictly 16.5.0} -> 16.5.0 (c)
+--- com.google.android.gms:play-services-measurement-sdk-api:{strictly 16.5.0} -> 16.5.0 (c)
+--- com.google.android.gms:play-services-tasks:{strictly 16.0.1} -> 16.0.1 (c)
+--- com.google.firebase:firebase-common:{strictly 16.1.0} -> 16.1.0 (c)
+--- com.google.auto.value:auto-value-annotations:{strictly 1.6} -> 1.6 (c)
+--- com.google.firebase:firebase-iid:{strictly 17.1.2} -> 17.1.2 (c)
+--- com.google.firebase:firebase-iid-interop:{strictly 16.0.1} -> 16.0.1 (c)
+--- com.google.android.gms:play-services-base:{strictly 16.0.1} -> 16.0.1 (c)
+--- com.google.firebase:firebase-measurement-connector:{strictly 17.0.1} -> 17.0.1 (c)
+--- com.google.android.gms:play-services-measurement-sdk:{strictly 16.5.0} -> 16.5.0 (c)
\--- com.google.firebase:firebase-core:{strictly 16.0.9} -> 16.0.9 (c)
```

**Comment by tvolkert** [comment]
It looks like there's some confusion around what's triggering this warning message in the Android community.  [Here's an example](https://www.reddit.com/r/androiddev/comments/c38b5r/weve_detected_that_your_app_is_using_an_old/erseflk/) of it being triggered by the use of the Jenkins Google Android Publisher plugin to upload the app to the Play Store. 

/cc @collinjackson @bparrishMines for the `firebase_analytics` connection.

**Comment by tvolkert** [comment]
https://github.com/flutter/plugins/blob/410095a1bae31e888d0f9d668510190c9eda5102/packages/firebase_analytics/android/build.gradle#L48

I don't see any suspicious dependencies in `firebase_analytics`...

@RedBrogdon let me know if you're able to reproduce this next time you upload an app.

**Comment by tvolkert** [comment]
Looking through our entire plugins repo and the https://developers.google.com/android-publisher/libraries, I don't see any references to that API anywhere in our plugins (either in Gradle files or the Java code).

**Comment by alexlindroos** [comment]
I noticed this same warning today. I am also using firebase_core and firebase_analytics. 

@maxlapides Are you using Fastlane? I feel like the warning was not there before I made an alpha release using Fastlane.

**Comment by rifal-klikeat** [comment]
i have same issue  today on play console dashboard

> We’ve detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date.

plugin : 
  ```
flare_flutter: ^1.5.0
  rxdart: ^0.21.0
  shimmer: ^0.0.6
  flutter_swiper: ^1.1.4
  flutter_cache_manager: ^0.3.2
  cached_network_image: ^0.8.0
  sqflite: ^1.1.5
  flutter_html: ^0.8.2
  intl: ^0.15.7
  badges: ^0.0.6
  flutter_staggered_grid_view: ^0.3.0
  google_maps_flutter:  0.0.3+3
  photo_view: ^0.4.0
  rounded_modal: ^1.0.0
  url_launcher: 4.1.0+1
  cupertino_range_slider: ^1.0.1
  modal_progress_hud: ^0.1.2
  package_info: 0.3.2+1
  easy_listview: ^0.1.3
  flutrans: ^0.0.2
  cupertino_icons: ^0.1.2
```
how to fix this ?

**Comment by brmaleo** [comment]
Same problem here.

```
  package_info: ^0.4.0+5
  scoped_model: ^1.0.1
  provider: ^3.0.0+1
  photo_view: any
  uuid: any
  share: ^0.6.1+1
  shared_preferences: ^0.5.3+2
  sqflite: ^1.0.0
  path_provider: any
  launch_review: ^1.0.1
  url_launcher: ^5.0.3
  audioplayers: ^0.12.1
  device_info: ^0.4.0+2
  sentry: any
  in_app_purchase: any
  firebase_core: any
  firebase_analytics: any
```
With warnings "...uses or overrides a deprecated API" from `FirebaseAnalyticsPlugin.java` and `PackageInfoPlugin.java`.

Not sure whether it's related, but also getting four "Pre-launch report" > "Android compatibility" warnings from Play Developer Console like this "`StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/util/LongArray;->get(I)J`"

**Comment by amirh** [comment]
Our in_app_purchase plugin is using PBL 1.2, which will trigger this warning, filed https://github.com/flutter/flutter/issues/37021 to track updating that plugin.

I'm not sure I see a dependency that triggers this warning in the Gradle dependencies posted by @maxlapides, any chance you're using the publishing API to upload the app as Todd suggested?

**Comment by amirh** [comment]
We've checked with the play team and PBL 1.2 isn't triggering this warning (so it's not the in_app_purchase) dependency.

The publishing API still sounds like a reasonable suspect, would love to get feedback on whether these apps were published using a tool or directly through the web console.

**Comment by maxlapides** [comment]
I'm not getting this warning anymore! I've been using Bitrise to build and push my app to Google Play. I'm not sure what changed, unfortunately. Could have been Bitrise or one of my app dependencies.

**Comment by Hixie** [comment]
@maxlapides If you're not seeing this anymore, should we close this issue, or is there still something you would like us to do?

**Comment by maxlapides** [comment]
@Hixie from my standpoint, this is resolved! I don't know if others are experiencing the issue, but I'm good at this point.

**Comment by tvolkert** [comment]
Thanks.  I'm going to close this issue then, but feel free to re-open if needed.

**Comment by glennmichaelmejias** [comment]
same problem.
`
dev_dependencies:
  http:
  url_launcher: ^5.1.1
  path_provider:
  path_provider_ex: ^1.0.1
  sqflite: ^1.1.1
  intl: ^0.15.8
  audioplayers: ^0.13.1
  permission_handler: ^3.2.2
  flutter_local_notifications: ^0.8.2+1
  open_file: ^2.0.3
  html_unescape: ^1.0.1+3
  share:
  firebase_admob: ^0.9.0+7
  floating_bubble: ^0.0.4
  font_awesome_flutter:
  path: ^1.6.4
`

**Comment by marcmarder** [comment]
Don't close this! Still happening!

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart:
  provider: ^3.1.0
  path_provider: ^1.4.0
  cloud_firestore: ^0.12.9+4
  intl:
  permission_handler: ^3.3.0
  # carousel_slider: ^1.3.1
  shared_preferences: ^0.5.4+1
  dynamic_theme: ^1.0.1
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  charts_flutter: ^0.8.1
  json_serializable: ^3.2.3
  camera:
  photo_view: ^0.6.0
  firebase_storage: ^3.0.6
  connectivity: ^0.4.5+1
  firebase_admob: ^0.9.0+7
  firebase_dynamic_links: ^0.5.0+1
  share: ^0.6.3+1
  firebase_analytics: ^5.0.2
  firebase_remote_config: ^0.2.0+7
  firebase_crashlytics: ^0.1.0+3
  firebase_messaging: ^5.1.6
  flutter_local_notifications: ^0.8.4
  firebase_performance: 0.3.0+5
  url_launcher: ^5.2.5
  shimmer: ^1.0.1
  flutter_speed_dial: ^1.2.3
  fluttertoast: ^3.1.3
```
