### ISSUE TITLE
Flutter Web: The argument type can`t be assigned to the parameter type widget

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#35004]
I want to user [Swiper ](https://github.com/best-flutter/flutter_swiper)plugin in my flutter web project. I have added it in pubspec.yamel
but when i import it it shows this exception 
`The argument type 'Swiper' can`t be assigned to the parameter type widget`

```
name: flutter_web.examples.hello_world

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  flutter_swiper: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_swiper:
    git:
      url: https://github.com/best-flutter/flutter_swiper
      ref: 71eb23671d46f624790019963c7ce10456dec652

```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.175], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.35.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```
