### ISSUE TITLE
Flutter crashes on iOS because of GL

### ISSUE THREAD

**Issue by Dominic12** [flutter/flutter#35040]
## Steps to Reproduce

With Google maps on the newest version, switch fast between Tabs. This will crash the application. 

This is probably related to [Issue](https://github.com/flutter/flutter/issues/31152) and this [PR](https://github.com/flutter/engine/pull/9377) but this seems not to fix the underlying issue.

## Logs

```
thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2ed7a)
    frame #0: 0x0000000102bc3cd8 Runner`gmscore::renderer::GLState::DeleteBuffers(int, unsigned int const*) + 36
    frame #1: 0x0000000102bbaca0 Runner`gmscore::renderer::BufferObject::~BufferObject() + 44
    frame #2: 0x0000000102c40434 Runner`gmscore::renderer::SafeVBOWithAttributes<gmscore::vector::GMSLineColorAndWidthAttributes>::~SafeVBOWithAttributes() + 12
    frame #3: 0x0000000102aba0d0 Runner`gmscore::base::ReferenceCounted::GMSx_Unref() + 64
    frame #4: 0x0000000102c3e5a4 Runner`gmscore::base::reffed_ptr<gmscore::renderer::SafeVBOWithAttributes<gmscore::vector::GMSLineColorAndWidthAttributes> >::~reffed_ptr() + 28
    frame #5: 0x0000000102c3e55c Runner`std::__1::__vector_base<gmscore::base::reffed_ptr<gmscore::renderer::SafeVBOWithAttributes<gmscore::vector::GMSLineColorAndWidthAttributes> >, std::__1::allocator<gmscore::base::reffed_ptr<gmscore::renderer::SafeVBOWithAttributes<gmscore::vector::GMSLineColorAndWidthAttributes> > > >::~__vector_base() + 44
    frame #6: 0x0000000102ccfdc4 Runner`gmscore::vector::StrokeVertexData::~StrokeVertexData() + 84
    frame #7: 0x0000000102ccfe04 Runner`gmscore::vector::StrokeVertexData::~StrokeVertexData() + 12
    frame #8: 0x0000000102aba0d0 Runner`gmscore::base::ReferenceCounted::GMSx_Unref() + 64
    frame #9: 0x0000000102bc24c0 Runner`gmscore::base::reffed_ptr<gmscore::renderer::VertexData>::~reffed_ptr() + 28
    frame #10: 0x0000000102bc1610 Runner`gmscore::renderer::Entity::~Entity() + 72
    frame #11: 0x0000000102c8d2f0 Runner`gmscore::vector::GMSVectorMapEntity::~GMSVectorMapEntity() + 12
    frame #12: 0x0000000102aba0d0 Runner`gmscore::base::ReferenceCounted::GMSx_Unref() + 64
    frame #13: 0x00000001029f1250 Runner`gmscore::base::reffed_ptr<gmscore::renderer::Entity>::~reffed_ptr() + 28
    frame #14: 0x0000000102c1fd44 Runner`std::__1::__vector_base<gmscore::base::reffed_ptr<gmscore::renderer::Entity>, std::__1::allocator<gmscore::base::reffed_ptr<gmscore::renderer::Entity> > >::~__vector_base() + 44
    frame #15: 0x0000000102c3dd10 Runner`gmscore::vector::GLStrokeLayer::~GLStrokeLayer() + 360
    frame #16: 0x0000000102c3dea4 Runner`gmscore::vector::GLStrokeLayer::~GLStrokeLayer() + 12
    frame #17: 0x0000000102c15fac Runner`std::__1::shared_ptr<gmscore::vector::GLStrokeLayer>::~shared_ptr() + 64
    frame #18: 0x0000000102c366a8 Runner`std::__1::__vector_base<std::__1::shared_ptr<gmscore::vector::GLStrokeLayer>, std::__1::allocator<std::__1::shared_ptr<gmscore::vector::GLStrokeLayer> > >::~__vector_base() + 44
    frame #19: 0x0000000102c36514 Runner`gmscore::vector::GLStrokeLayerGroup::~GLStrokeLayerGroup() + 36
    frame #20: 0x0000000102aba0d0 Runner`gmscore::base::ReferenceCounted::GMSx_Unref() + 64
    frame #21: 0x0000000102c8a630 Runner`gmscore::base::reffed_ptr<gmscore::vector::GLFeatureGroup>::~reffed_ptr() + 28
    frame #22: 0x0000000102c8a5e8 Runner`std::__1::__vector_base<gmscore::base::reffed_ptr<gmscore::vector::GLFeatureGroup>, std::__1::allocator<gmscore::base::reffed_ptr<gmscore::vector::GLFeatureGroup> > >::~__vector_base() + 44
    frame #23: 0x00000001e783a7cc libobjc.A.dylib`object_cxxDestructFromClass(objc_object*, objc_class*) + 148
    frame #24: 0x00000001e784a6b8 libobjc.A.dylib`objc_destructInstance + 68
    frame #25: 0x00000001e784a720 libobjc.A.dylib`object_dispose + 16
    frame #26: 0x0000000102abcf54 Runner`-[GMSLRUCacheEntry dealloc] + 48
    frame #27: 0x00000001e8697954 CoreFoundation`cow_cleanup + 176
    frame #28: 0x00000001e854ee38 CoreFoundation`-[__NSDictionaryM dealloc] + 68
    frame #29: 0x0000000102abd0a8 Runner`-[GMSLRUCache dealloc] + 48
    frame #30: 0x0000000102c6bd8c Runner`-[GMSRenderTileProvider .cxx_destruct] + 288
    frame #31: 0x00000001e783a7cc libobjc.A.dylib`object_cxxDestructFromClass(objc_object*, objc_class*) + 148
    frame #32: 0x00000001e784a6b8 libobjc.A.dylib`objc_destructInstance + 68
```

My plugins

```
name: sbb_hunting_frontend
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  permission_handler: ^3.0.0
  flutter_launcher_icons: ^0.7.0
  geolocator: ^3.0.1
  google_maps_flutter: ^0.5.19
  json_annotation: ^2.0.0
  fluttertoast: ^3.0.4
  android_intent: ^0.3.0+2
  shared_preferences: 
  vibrate: ^0.0.4
  cloud_firestore: ^0.12.1
  cloud_functions: ^0.4.0
  flutter_spinkit: ^3.1.0
  firebase_auth: ^0.11.1+7
  location_background_plugin: ^0.0.2
  flutter_local_notifications: ^0.7.1+1
  flutter_jailbreak_detection:
  flutter_markdown: ^0.2.0
  admob_flutter: ^0.3.1
  firebase_core: ^0.4.0+6
  custom_radio:
    git:
      url: https://github.com/Dominic12/custom_radio.git
      ref: ac5b14debaf4ff72357384579e22b356d7cea27c

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher/app-icon-kb-challenge-prev-512.png"
  adaptive_icon_background: "assets/launcher/app-icon-kb-challenge-background.png"
  adaptive_icon_foreground: "assets/launcher/app-icon-kb-challenge-prev-foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/i18n/de.json
    - assets/i18n/fr.json
    - assets/i18n/it.json
    - assets/i18n/en.json
    - assets/images/sbb.png
    - assets/images/logo.png
    - assets/images/sign-icon.png
    - assets/md/licenses.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: sbbicons
      fonts:
        - asset: assets/fonts/sbbicons.ttf
    - family: SBBWeb
      fonts:
        - asset: assets/fonts/SBBWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/SBBWeb-Light.ttf
          weight: 300
    - family: goicons
      fonts:
        - asset: assets/fonts/go-icons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```

```
[✓] Flutter (Channel master, v1.7.9-pre.11, on Mac OS X 10.14.5 18F132, locale
    en-GB)
    • Flutter version 1.7.9-pre.11 at
      /Users/dominicjarmann/Documents/developement/flutter
    • Framework revision 25b5656969 (13 hours ago), 2019-06-24 11:09:07 -0700
    • Engine revision 4444c9cb6c
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/dominicjarmann/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (3 available)
    • Dominic’s iPhone • d738cbe523807492ac441d6e98d0f4bf8f0ac0d6 • ios
      • iOS 12.3.1
    • macOS            • macOS                                    • darwin-x64
      • Mac OS X 10.14.5 18F132
    • Chrome           • chrome                                   •
      web-javascript • Google Chrome 75.0.3770.100 


! Doctor found issues in 2 categories.

```
