### ISSUE TITLE
'flutter pub pub publish' prints 'Package dependency flutter is not hosted on pub.dev'

### ISSUE THREAD

**Issue by kekland** [flutter/flutter#35634]
## Steps to reproduce

I've created a new package project using:

```bash
flutter create --template=package equinox
```

Then, I've filled in required parameters in pubspec.yaml:

```yaml
name: equinox
description: my description
author: kekland <kk.erzhan@gmail.com>
homepage: https://github.com/kekland/equinox

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
```

After that, I've called `flutter pub pub publish`, and it errors out with `Package dependency flutter is not hosted on pub.dev.`.

Interestingly, `flutter pub publish` does nothing after printing the file tree (I've waited for 3 minutes), and has 0% CPU and network usage.

## Logs

```bash
PS D:\Projects\current\equinox> flutter pub pub publish
Publishing equinox 0.0.1 to https://pub.dartlang.org:
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- android
|   |-- app
|   |   '-- src
|   |       '-- main
|   |           '-- java
|   |               '-- io
|   |                   '-- flutter
|   |                       '-- plugins
|   |                           '-- GeneratedPluginRegistrant.java
|   '-- local.properties
|-- equinox.iml
|-- ios
|   |-- Flutter
|   |   '-- Generated.xcconfig
|   '-- Runner
|       |-- GeneratedPluginRegistrant.h
|       '-- GeneratedPluginRegistrant.m
|-- lib
|   '-- equinox.dart
'-- pubspec.yaml

Looks great! Are you ready to upload your package (y/n)? y
Uploading...
Package dependency flutter is not hosted on pub.dev.
pub finished with exit code 1
```

```bash
PS D:\Projects\current\equinox> flutter pub publish
Publishing equinox 0.0.1 to https://pub.dartlang.org:
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- android
|   |-- app
|   |   '-- src
|   |       '-- main
|   |           '-- java
|   |               '-- io
|   |                   '-- flutter
|   |                       '-- plugins
|   |                           '-- GeneratedPluginRegistrant.java
|   '-- local.properties
|-- equinox.iml
|-- ios
|   |-- Flutter
|   |   '-- Generated.xcconfig
|   '-- Runner
|       |-- GeneratedPluginRegistrant.h
|       '-- GeneratedPluginRegistrant.m
|-- lib
|   '-- equinox.dart
'-- pubspec.yaml


```

```bash
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18356.1], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code, 64-bit edition
[!] Connected device
    ! No devices available
```
