### ISSUE TITLE
[cloud_firestore 0.12.6]  CloudFirestorePlugin.m:6:9: fatal error: 'UserAgent.h' file not found

### ISSUE THREAD

**Issue by sensuikan1973** [flutter/flutter#35670]
## Steps to Reproduce
1. I update `cloud_firestore` plugin to [0.12.6](https://pub.dev/packages/cloud_firestore#0126) from 0.12.5+2
2. flutter run
3. failed...

【 error log】
```log
=== BUILD TARGET cloud_firestore OF PROJECT Pods WITH CONFIGURATION Debug-development ===
               ~/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.6/ios/Classes/CloudFirestorePlugin.m:6:9: fatal error: 'UserAgent.h' file not found
               #import "UserAgent.h"
                       ^~~~~~~~~~~~~
               1 error generated.
```

【 pubsec.yaml】
```pubsec.yml
name: foo
description: foo
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  package_info: 0.4.0+4
  pub_semver: 1.4.2
  device_info: 0.4.0+2
  dynamic_theme: 1.0.1
  page_transition: 1.1.4
  loadmore: 1.0.3
  cupertino_icons: 0.1.2
  font_awesome_flutter: 8.4.0
  flutter_auth_buttons: 0.5.0
  bubble_bottom_bar: 1.2.0
  auto_size_text: 2.0.1
  quiver: 2.0.2
  synchronized: 2.1.0+1
  rxdart: 0.22.0
  bloc_provider: 0.6.2+1

  flutter_localizations:
    sdk: flutter

  shared_preferences: 0.5.3+1
  flutter_secure_storage: 3.2.1+1
  cached_network_image: 1.0.0

  cloud_firestore: 0.12.6
  firebase_auth: 0.11.1+7
  firebase_crashlytics: 0.0.4+8
  firebase_analytics: 3.0.3
  firebase_performance: 0.3.0+2
  firebase_core: 0.4.0+6
  firebase_dynamic_links: 0.4.0+4
  firebase_messaging: 5.0.4

  share: 0.6.1+1
  google_sign_in: 4.0.2
  flutter_facebook_login: 2.0.1
  flutter_twitter_login: # See: https://github.com/roughike/flutter_twitter_login/issues/9
    git:
      url: git://github.com/dlutton/flutter_twitter_login.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.6.1
  mockito: 4.1.0
  intl_translation: any
  flutter_launcher_icons:
    git:
      url: git://github.com/fluttercommunity/flutter_launcher_icons.git # See: https://github.com/fluttercommunity/flutter_launcher_icons/pull/69 and https://medium.com/flutter-jp/icon-935d637d2da0
      ref: flavors

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/dat/
```

## Logs

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale ja-JP)
    • Flutter version 1.5.4-hotfix.2 at /Users/shimizunaoki/development/flutter
    • Framework revision 7a4c33425d (10 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shimizunaoki/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPad (6th generation) • 388C13A3-E134-40C1-B333-5731D3EE190C • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by sensuikan1973** [comment]
I tried this.

• `flutter clean`
• Clean Build Folder from Xcode
• delete Podfile.lock

But, this don't work.

So, I deintegrate pod.

```sh
cd ios
pod deintegrate
pod install
```

This works.

**Comment by TylerSustare** [comment]
This is happening to me also and @sensuikan1973's trick didn't work for me. `  firebase_core: ^0.4.4+2`

**Comment by msnowshadali** [comment]
• flutter clean
• Clean Build Folder from Xcode
• delete Podfile.lock

But, this didn't work.

So, I deintegrate pod.

cd ios
pod deintegrate
pod install


this worked for me

**Comment by Dx** [comment]
In my case, it was possible to resolve like this

```
dependency_overrides:
  firebase_core: 0.4.4
```

**Comment by abharku** [comment]
I also had to downgrade firebase_auth along with firebase_core. Seem to be issue with newer minor version. 
thanks to @Dx , I now have:
dependency_overrides:
  firebase_core: 0.4.4
  firebase_auth: 0.15.0

**Comment by dpedrinha** [comment]
Even though I downgraded firebase_core to 0.4.4 and firebase_auth to 0.15.0 I keep getting the same error pointing to 0.4.4+2:

`flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+2/darwin/Classes/FLTFirebaseCorePlugin.m:6:9: fatal error:
    'UserAgent.h' file not found
    #import "UserAgent.h"`

For some reason it's not downgrading no matter how many times I `flutter clean`.

**Comment by abharku** [comment]
@dpedrinha  try cleaning the cache and restart Studio:
In AndroidStudio ->File->InvalidateCache/Restart

**Comment by dpedrinha** [comment]
I'm on Visual Studio.

**Comment by abharku** [comment]
@dpedrinha try generating the POD's manually
cd to ios folder
pod deintegrate
pod install

**Comment by dpedrinha** [comment]
Didn't work.
Still getting wrong version errors.

`/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.5+2/darwin/Classes/FLTFirebaseAuthPlugin.m:7:9: fatal error:
    'UserAgent.h' file not found
    #import "UserAgent.h"`

Even though my pubspec.yaml says 0.15.0

**Comment by lvlrSajjad** [comment]
@abharku I have exactly the same problem with firebase_core: 0.4.4+2
```
↳
    /Users/lvlrx/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+2/darwin/Classes/FLTFirebaseCorePlugin.m:6:9: fatal error: 'UserAgent.h' file not found
    #import "UserAgent.h"
            ^~~~~~~~~~~~~
```
I tried 

```
cd to ios
pod deintegrate
pod install
```
No luck ...
I think there is something with .pub-cache

**Comment by abharku** [comment]
@lvlrSajjad @dpedrinha Please guys make sure you are not sourcing minor versions (Notice no ^ in front):

dependency_overrides:
firebase_core: 0.4.4
firebase_auth: 0.15.0

if It still doesn't work, please attach your pubsec.yml so that I can try and recreate

**Comment by lvlrSajjad** [comment]
@abharku  I can't use 0.4.4 because it has a problem with Firestore I have to use   firebase_core: 0.4.4+2
Btw this is my pubspec
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  inject:
    path: ./injection/inject.dart/package/inject
  apple_sign_in: 0.1.0
  audioplayers: 0.14.0
  cached_network_image: 2.0.0
  carousel_slider: 1.4.1
  cloud_firestore: 0.13.4
  cloud_functions: 0.4.1+8
  connectivity: 0.4.6+2
  country_pickers: 1.1.0
  cupertino_icons: 0.1.2
  device_id: 0.2.0
  device_info: 0.4.1+4
  firebase_admob: 0.9.0+10
  firebase_analytics: 5.0.11
  firebase_auth: 0.15.4
  firebase_core: 0.4.4+2
  firebase_crashlytics: 0.1.3
  firebase_messaging: 6.0.9
  firebase_performance: 0.3.1+5
  firebase_remote_config: 0.3.0+1
  firebase_storage: 3.1.1
  flare_flutter: 2.0.1
  flash: 1.2.0
  flutter_cache_manager: 1.1.3
  flutter_facebook_login: 3.0.0
  flutter_ip: 0.2.0
  flutter_native_splash: 0.1.9
  flutter_range_slider: 1.4.0
  flutter_secure_storage: 3.3.1+1
  flutter_slidable: 0.5.4
  flutter_svg: 0.15.0
  font_awesome_flutter: 8.7.0
  geocoder: 0.2.1
  geohash: 0.2.1
  geolocator: 5.2.0
  google_sign_in: 4.1.0
  googleapis: 0.54.0
  http: 0.12.0+4
  image_cropper: 1.2.1
  image_downloader: 0.19.1
  image_picker: 0.6.3+4
  intl: 0.16.0
  json_serializable: 3.1.0
  local_auth: 0.6.1
  location: 2.3.5
  location_permissions: 2.0.4+1
  material_design_icons_flutter: 3.4.4995
  package_info: 0.4.0+14
  path: 1.6.4
  path_provider: 1.5.1
  permission_handler: 4.2.0+hotfix.3
  photo_view: 0.9.1
  reorderables: 0.2.12
  rxdart: 0.23.1
  sembast: 2.2.0
  share: 0.6.3+6
  shared_preferences: 0.5.6
  store_redirect: 1.0.2
  transparent_image: 1.0.0
  url_launcher: 5.2.7
  vibration: 1.2.2
  smooth_page_indicator: 0.1.4
#  algolia: 0.1.7
#  clipboard_manager: ^0.0.4
#  flutter_google_places: 0.2.3
#  flutter_twitter_login: 1.1.0
#  geoflutterfire: 2.0.3+8
#  toast: 0.1.5
#  video_player: 0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.7.4
  inject_generator:
    path: ./injection/inject.dart/package/inject_generator
```
