### ISSUE TITLE
Build failed just after adding plugins

### ISSUE THREAD

**Issue by tanzimfahim** [flutter/flutter#36069]
my pubspec.yaml file contains
```
http:
  cloud_firestore: 
  intl: 
  firebase_admob: 
  firebase_core:
  firebase_auth: 
  firebase_database: 
  cupertino_icons: 
  shared_preferences:  
  emoji_picker:
  google_sign_in: 
  flutter_facebook_login:
  firebase_messaging: 
  image_picker_modern: 
  firebase_storage: 
  font_awesome_flutter: 
  in_app_purchase: 
```
these dependencies.
I tried almost all methods of internet but no result.
upgraded to androidX, multidexenabled true, 

Seems like the some packages doesn't match with each other. How can i know which version to use for comfortablity 

flutter doctor -v 
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-BD)
    • Flutter version 1.7.8+hotfix.3 at /Users/tanzimfahim/flutter
    • Framework revision b712a172f9 (3 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tanzimfahim/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • ONEPLUS A5000 • ceecb6b2 • android-arm64 • Android 9 (API 28)

• No issues found!
```
```
With version:
  http:
  onesignal: ^1.1.0
  cloud_firestore: ^0.8.2
  intl: ^0.15.8
  firebase_admob: 
  firebase_core:
  firebase_auth: 
  firebase_database: ^1.0.5
  cupertino_icons: ^0.1.2
  shared_preferences: 0.5.3+1 
  emoji_picker:
  google_sign_in: ^4.0.1+1
  flutter_facebook_login:
  firebase_messaging: ^4.0.0
  image_picker_modern: ^0.4.12+2
  firebase_storage: 
  font_awesome_flutter: ^8.0.1
```

But same result :(
