### ISSUE TITLE
DropdownButton has an empty square instead of a downward arrow

### ISSUE THREAD

**Issue by hermantai** [flutter/flutter#36140]
I am seeing an empty square instead of an arrow for the DropdownButton:

<img width="1406" alt="Screen Shot 2019-07-13 at 3 19 46 PM" src="https://user-images.githubusercontent.com/3487143/61177093-ad65b980-a581-11e9-9f6b-c3dcc60f5228.png">

I created a project with intellij: flutter web project.

Then, simply add the DropdownButton like this:

```
var choices = ['hello','bye'];
...
children: <Widget>[
            Text(
              'Hello, World!',
            ),
            DropdownButton<String>(
              onChanged: (v) => {},
              value: 'hello',
              items: choices.map<DropdownMenuItem<String>>((choice) {
                return DropdownMenuItem<String>(
                  value: choice,
                  child: Text(choice),
                );
              }).toList(),
            ),
          ],
```

I then started the project with:
flutter packages pub global run webdev serve web:8083

pubspec.lock file:
```
  flutter_web:
    dependency: "direct main"
    description:
      path: "packages/flutter_web"
      ref: HEAD
      resolved-ref: "8d4c12a4e9b45f82b5cb862840ac47445e136f7b"
      url: "https://github.com/flutter/flutter_web"
    source: git
    version: "0.0.0"
  flutter_web_ui:
    dependency: "direct main"
    description:
      path: "packages/flutter_web_ui"
      ref: HEAD
      resolved-ref: "8d4c12a4e9b45f82b5cb862840ac47445e136f7b"
      url: "https://github.com/flutter/flutter_web"
    source: git
    version: "0.0.0"
```
Chrome:  75.0.3770.100
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-US)

The whole pubspec.yaml file:

```
name: test_dropdown
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```
