### ISSUE TITLE
Custom fonts CookBook example not working as expected

### ISSUE THREAD

**Issue by miquelbeltran** [flutter/flutter#36739]
I added custom fonts to my project following the explanation in https://flutter.dev/docs/cookbook/design/fonts 

In the example you can find:

```
- family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
```

So I followed it and in my `pubspec.yaml` I have:
```
fonts:
    - family: Edmondsans
      fonts:
        - asset: fonts/Edmondsans-Regular.otf
        - asset: fonts/Edmondsans-Medium.otf
          weight: 500
        - asset: fonts/Edmondsans-Bold.otf
          weight: 700
```

Then in my code:

```
TextStyle(
      fontFamily: "Edmondsans",
      fontWeight: FontWeight.w500,
    );
```

However I noticed that:

- The w500 (medium) was not being rendered, and instead, it was rendering the Edmondsans-Regular.
- The w700 (bold) was not rendering Edmondsans-Bold but instead making a bold version of Edmondsans-Regular (they looked different)

To actually use my Medium and Bold custom font files, I had to use them in a different way:
```
fonts:
    - family: Edmondsans
      fonts:
        - asset: fonts/Edmondsans-Regular.otf
    - family: Edmondsans-Medium
      fonts:
        - asset: fonts/Edmondsans-Medium.otf
    - family: Edmondsans-Bold
      fonts:
        - asset: fonts/Edmondsans-Bold.otf
```

Then in my code, this will work as expected:

```
TextStyle(
      fontFamily: "Edmondsans-Medium",
    );
```

My configuration info:

```
[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-DE)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (1 available)
```

This issue here seem to be related: https://github.com/flutter/flutter/issues/29806

I'd suggest to change the cookbook examples until custom fonts work as expected.
