### ISSUE TITLE
[web]: Fetch Data Example throws "Failed assertion: boolean expression must not be null" error

### ISSUE THREAD

**Issue by testphys** [flutter/flutter#36778]
I am on firefox 68.0 and the error I get when I run `webdev serve` is "Failed assertion: boolean expression must not be null" which is caused by a `snapshot.hasData` being null and not boolean.

```
name: leadership_coach

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  http: ^0.12.0+2

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```
