### ISSUE TITLE
Open Video Default app

### ISSUE THREAD

**Issue by aoulddaouia** [flutter/flutter#37200]
Hello friends,

I'm in trouble with a flutter app. What i want is to open a url of a video on the default video app on android. I have used the url_launcher plugin but the plugin just open the url in the browser. i found a plugin "video_launcher" but is not compatible on DART 2.

And I'm sorry about my English.

**Comment by miyoyo** [comment]
This should not be an issue on github.
Not every phone has a builtin video player, but I assume the most straightforward way would be to either pass a link to the video stream as an intent, or download then open the file.

**Comment by BugsBunnyBR** [comment]
I fixed the video_launcher project, but I don't intent to keep it in the long run or publish it.
You should fork my version (as I will probably delete it at some moment in the future) and point your pubspect.yaml to your fork.

https://github.com/BugsBunnyBR/flutter_video_launcher

something like this
```
flutter_video_launcher:
    git:
      url: git@github.com:BugsBunnyBR/flutter_video_launcher.git
      ref: master
```
I may help with android issues, but for iOS issues you are in your own.
