### ISSUE TITLE
Why is build.gradle still using plugin version 3.2.1?

### ISSUE THREAD

**Issue by repentsinner** [flutter/flutter#37523]
Hi Flutter team, quick question regarding the Android boilerplate and gradle configuration:

I'm running Flutter 1.7.8+hotfix.4, and a fresh `flutter create` results in an Android gradle configuration which uses plugin 3.2.1 with distribution 4.10.2.

_android/build.gradle_:
```
dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
}
```

_android/gradle/wrapper/gradle-wrapper.properties_:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
```

How come plugin 3.3.x isn't used, since it's supported by this distribution?

Somewhat related, the Flutter AndroidX [migration docs](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#not-recommended-manually-migrate-your-app) recommends to upgrade to `3.3.0`, but doesn't say if this is detrimental for a non-AndroidX project or not. If `flutter create --androidx` is run, it still generates a classpath to use plugin 3.2.1, although it really sounds like AndroidX requires plugin >=3.3.0 per the migration docs.

I recently ran into a [build issue on Windows](https://stackoverflow.com/questions/57238933/gradle-failure-a-problem-occurred-evaluating-project-app/57334098#57334098) that was resolved by updating the gradle plugin >3.2.1, and am just curious as to whether `flutter create` boilerplate should be tracking current gradle more closely or not.

Thanks for considering!

**Comment by artob** [comment]
For what it's worth, the latest Android Gradle 3.3.x plugin release works fine with Flutter stable (v1.7.8+hotfix.4) on projects migrated to AndroidX:

    classpath 'com.android.tools.build:gradle:3.3.2'

Upgrading to the 3.4.2 plugin and the Gradle 5.1.1 wrapper doesn't work, though; [the build fails](https://github.com/flutter/flutter/issues/24645) even with the Flutter beta and dev channels. So, it seems that 3.3.2 plugin and the 4.10.3 wrapper constitute the current upwards limits.

**Comment by repentsinner** [comment]
@artob interesting, I'll have to dig into my settings further - I _appear_ to be using Gradle 5.1.1 with plugin 3.4.2 on Flutter stable (v1.7.8+hotfix.4):

./android/gradle/gradle-wrapper.properties:
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip`

./android/build.gradle:
`classpath 'com.android.tools.build:gradle:3.4.2'`

flutter build apk -v
```
...
[ +112 ms] executing: /Users/deg/Development/Sidecar/user_app/android/gradlew -v
[ +915 ms] 
                    ------------------------------------------------------------
                    Gradle 5.1.1
                    ------------------------------------------------------------

                    Build time:   2019-01-10 23:05:02 UTC
                    Revision:     3c9abb645fb83932c44e8610642393ad62116807

                    Kotlin DSL:   1.1.1
                    Kotlin:       1.3.11
                    Groovy:       2.5.4
                    Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Mac OS X 10.14.6 x86_64
[  +17 ms] Initializing gradle... (completed in 1.5s)
...
```

Not sure where in there it says what plugin it's using, but this makes it seem like it's using gradle 5.1.1?

**Comment by artob** [comment]
@repentsinner Success in using the newer wrapper and plugin versions might have to do with which dependencies you're pulling in; or as it may be, not pulling in.

It was difficult to troubleshoot why building with Gradle 5.1.1 (or 5.5.1, for that matter) failed in my project, due to [absolutely no relevant Gradle output](https://github.com/flutter/flutter/issues/24645) about the proximate cause let alone root cause, but I suspect it must have to do with processing a dependency or another.

A less complex project with fewer dependencies might have better luck, though it could then run into trouble over time as dependencies are added or the like.

**Comment by repentsinner** [comment]
@artob yup, I've definitely run into dependency-dependent build issues and you're right, as the projects grow the random shenanigans appear to grow with them.

Here's an excerpt from my `pubspec.yaml` that still appears to work with gradle plugin 3.4.2. I haven't stripped it back to a MCVE lately.

```yaml
dependencies:
  flutter:
    sdk: flutter
  video_player:
  esys_flutter_share:
  cloud_firestore:
  cloud_functions:
  firebase_analytics:
  firebase_auth:
  provider:
  audioplayers:
  receive_sharing_intent:
  http:
  progress_dialog:
  flutter_launcher_icons:
  json_annotation:
  package_info:
  in_app_purchase:
  firebase_storage_image:
  flutter_widgets:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
```
