### ISSUE TITLE
Options for customizing auto-generated ios/android folder

### ISSUE THREAD

**Issue by IchordeDionysos** [flutter/flutter#37689]
## Use case

I have frequently run into #32883 where I have to constantly edit my .ios/.android folder to update the minimal ios version or add the google-services.json/GoogleService-Info.plist back in again or to convert the project to AndroidX again.

Doing these repetitive and simple changes over and over again is time-consuming and makes me again as productive as writing native iOS/Android code.

## Proposal

So for the minimally targeted OS version, an option in the pubspec.yaml would be great, like:

```yaml
flutter:
    min-os-version:
        androidMinSdkVersion: 16
        iosMinimumDeploymentTarget: 9.0
```

For adding files like google-services.json/GoogleService-Info.plist it would be great if there was some way of running post-creation scripts which are capable of copying these files to the .ios/.android folder. 
(Something like in the Firebase CLI https://firebase.google.com/docs/cli#hooks)

```yaml
flutter:
    post-creation-script:
        android: 
        - ./post-creation-android.sh
        ios: 
        - ./post-creation-ios.sh
```

And the most important: 
There should be an option:

```yaml
flutter:
    use-android-x: true
```
