### ISSUE TITLE
[web]: BoxDecoration border doesn't render if borderRadius is set

### ISSUE THREAD

**Issue by TheRealWelshCJ** [flutter/flutter#37772]
If borderRadius is set within the Container BoxDecoration then it overwrites a border in the same BoxDecoration.

```
 Container(
          height: 100,
          width: 100,
          decoration: BoxDecoration(
            border: Border.all(color: Colors.orange, width: 2),
            borderRadius: BorderRadius.all(
               Radius.circular(10.0),
            ),
            color: Colors.green,
          ),
        ),

```

The code above is wrapped in a Row in the new flutter_web boiler plate.

In Chrome it looks like:
![chrome1](https://user-images.githubusercontent.com/20382617/62627163-bd727e00-b920-11e9-86a5-07f5b0bfe2ef.png) 
if I comment out the borderRadius, then in chrome I get:

```
 Container(
          height: 100,
          width: 100,
          decoration: BoxDecoration(
            border: Border.all(color: Colors.orange, width: 2),
           // borderRadius: BorderRadius.all(
           //    Radius.circular(10.0),
           // ),
            color: Colors.green,
          ),
        ),

```

![chrome2](https://user-images.githubusercontent.com/20382617/62627164-be0b1480-b920-11e9-89bd-32df9b826d99.png) 
The border seems to be being over written by the borderRadius in flutter_web.

The same code (as the first code block) on Android, produces this:

![android](https://user-images.githubusercontent.com/20382617/62627162-bd727e00-b920-11e9-8829-1d1840689b77.png)

Chrome Version:  Version 76.0.3809.100 (Official Build) (64-bit)

Webdev Version: 2.3.0

Command: flutter pub global run webdev serve --launch-in-chrome --auto refresh

Flutter_Web:

```
 flutter_web:
    dependency: "direct main"
    description:
      path: "packages/flutter_web"
      ref: HEAD
      resolved-ref: "88a6325290b75326c072ae63bf3016e15a08fccc"
      url: "https://github.com/flutter/flutter_web"
    source: git
    version: "0.0.0"
  flutter_web_ui:
    dependency: "direct main"
    description:
      path: "packages/flutter_web_ui"
      ref: HEAD
      resolved-ref: "88a6325290b75326c072ae63bf3016e15a08fccc"
      url: "https://github.com/flutter/flutter_web"
    source: git
    version: "0.0.0"
```
