### ISSUE TITLE
flutter_svg not showing on latest version

### ISSUE THREAD

**Issue by shree-krishna-gapi** [flutter/flutter#37843]
SvgPicture.asset(
                      'assets/svg/HotelSimplifyLogo.svg',
                      height: 100,
                      width: 100,
                    ),

**Comment by fliermanrw** [comment]
What if you try to change the pubspec.yaml to this:

```
flutter_svg:
    git:
      url: git://github.com/dnfield/flutter_svg.git
      ref: master
```

I had the same issue a few weeks ago. When I changed to the latest version on github it worked again. Maybe some bugfix that hasn't been pushed, don't know the exact reason. Worth a try.
