### ISSUE TITLE
Images Do not load/show up at runtime, Error loading Asset

### ISSUE THREAD

**Issue by AkposCodex** [flutter/flutter#38322]
Hello, I just started coding in Flutter(Around a week since) and I cant seem to load images into my app.
Anytime I call an Image asset into my app it never shows up, it keeps saying that it cant load the asset: ``` Error loading asset "Unable to load assets:assets/images/kenkaneki" ```
this is a section of my code:
```


import 'package:flutter/material.dart';

class ImageBanner extends StatelessWidget{
  final String _assetPath;

  ImageBanner(this._assetPath);
  
  @override 
  Widget build(BuildContext context){
     return Container(
        constraints: BoxConstraints.expand(
          height:150.2,
          width: 130.0
        ),
        decoration: BoxDecoration(color: Colors.grey),
          child: Image.asset(
            _assetPath,
            fit: BoxFit.cover,
          ),
      );
  }
}
```

```
class LocationDetail extends StatelessWidget{
  @override 
  Widget build(BuildContext context){
    return Scaffold(
      appBar: AppBar(
        title: Text('Hello'),
      ),
      body:Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [ 
          ImageBanner("assets/images/kenkaneki"),
         TextSection("Memorii","Piglet"),
         TextSection("Summm","mewmew"),
         TextSection("Sumumumu","UwU"),
        ]
    )
    );
  }
}
```

and this is my pubsec.yaml file:
```
name: mewmewuwu
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

I really need help with this issue urgently
Thank you.

Also my asset file **IS** loaded properly and I have tried the flutter clean.

I also want to know if the image size affects anything.

**Comment by melwinlobo18** [comment]
You have not specified the extension of the image. Try passing the `_assetPath` with the image extension. If the error still persists please attach a screenshot of your directory structure.

**Comment by AkposCodex** [comment]
I have already tried that. I even tried using a different directory to load the image.
![Screenshot (39)](https://user-images.githubusercontent.com/38590783/63105715-49b41f00-bf79-11e9-8173-b17ada02e15e.png)

**Comment by AkposCodex** [comment]
```
name: phoenix
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icons/008-tshirt.png
     - assets/images/ 
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
       - family: Lora
         fonts:
           - asset: assets/fonts/Lora-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
```
import 'package:flutter/material.dart';

class HorizontalList extends StatelessWidget{
  @override 
  Widget build(BuildContext context){
    return Container(
      height: 130,
      child: ListView(
        scrollDirection: Axis.horizontal,
        children: <Widget>[
          Category('assets/icons/008-tshirts.png', 'T-Shirs')
        ]
      ),
    );
  }
}


class Category extends StatelessWidget {
  final String image_location;
  final String image_caption;

  Category(this.image_location, this.image_caption );
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(2.0),
      child: InkWell(
        onTap: (){},
        child:Container(
          width: 159.0,               
          height: 60.0,
        child: ListTile(
          title: Image.asset(image_location),
          subtitle: Text(image_caption),
        )
        ),
      ),
    );
  }
}
```
my pubsec.yaml file and program code.
