### ISSUE TITLE
Would be nice to version the flutter tool separately from the flutter package

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3865]
If you work on multiple flutter projects, it's possible they want to be pinned to different versions of flutter.

We don't currently document best practices for pinning to a version of flutter (see https://github.com/flutter/flutter/issues/3770), but some clients have used git submodules successfully.

However, even if you are able to pin your sources, you still have now two copies of the flutter tool.  Which one do you put in your path?

It would be nice if you could just have a single `flutter` tool in your path and that it could respect a flutter sdk version/path expressed in your pubspec.yaml.

For example, one proposal would be a pubspec.yaml:
```
name: my_project
dependencies:
 - flutter: any
environment:
 - flutter_sdk:
     path: /src/flutter
```

Presumably in this scenerio, the flutter tool would know to shell out to the flutter tool in that specified SDK?

@devoncarew
