### ISSUE TITLE
Dart 2.3.2 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#38697]
Im using json_serializable and build_runner packages and when i run this command 
`pub run build_runner watch
`
it gives me: ` Dart 2.3.2 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.`

running pub get gives me: 
```
Because wallbay depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.
Flutter users should run flutter packages get instead of pub get.
```

**pubspec.yaml**

```
name: wallbay
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  json_annotation: ^3.0.0
  url_launcher: ^5.1.2
  uni_links: ^0.2.0
  shared_preferences: ^0.5.3+4
  cached_network_image: ^1.1.1
  flutter_advanced_networkimage: any
  flutter_spinkit: ^3.1.0
  color: any
  dio: any
  shimmer: ^1.0.0
  share: ^0.6.2+1
  flutter_speed_dial: ^1.2.1
  bottom_navy_bar: ^5.1.0
  material_search: ^0.2.8
  loader_search_bar: ^1.0.3+3




dev_dependencies:
  build_runner: ^1.6.6
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

```

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.37.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by tvolkert** [comment]
What happens when you run `flutter pub get`?

**Comment by mohamed6996** [comment]
```
C:\Users\M.Ali\FlutterProjects\wallbay>flutter pub get
Running "flutter pub get" in wallbay...                             1.1s

C:\Users\M.Ali\FlutterProjects\wallbay>
```

**Comment by tvolkert** [comment]
Try `flutter pub run build_runner watch`

**Comment by mohamed6996** [comment]
Worked! 
Also, this command is working `flutter packages pub run build_runner build lib`

**Comment by tvolkert** [comment]
Great!  I'm gonna close this issue then.

**Comment by NagendraHariKarthick** [comment]
I am getting the same error with dart 2.10.4, when i ran `flutter packages pub run build_runner build `
`Dart 2.10.4 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.
pub finished with exit code 65
`
Sharing pubspec.yaml file for reference.
```
name: flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  json_annotation: ^3.0.0


dev_dependencies:
  build_runner: ^1.6.6
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

```
