### ISSUE TITLE
Firebase and Google Maps breaks the project

### ISSUE THREAD

**Issue by herrytco** [flutter/flutter#40036]
## Steps to Reproduce

1. create a new project
2. add Firebase according to their step-by-step guide
3. add the following plugins:

**pubspec.yaml**
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21
  google_sign_in: ^4.0.7       
  flutter_auth_buttons: ^0.5.0 
  shared_preferences: ^0.5.3+4 
  firebase_core: ^0.3.4
```

4. `flutter run`

The problem occurs on master and dev channel and on manually migrated androidx projects as well as projects created with the --androidx flag

## Logs
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.android.gms:play-services-tasks' has different version for the compile (16.0.1) and runtime (17.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
