### ISSUE TITLE
iOS builds fail with new pubspec format due to class prefix

### ISSUE THREAD

**Issue by jkurtw** [flutter/flutter#40369]
I updated a plugin pubspec to work with new format in order to add web support. It builds and works for web, but fails for iOS.

The pubspec looks like:
```yaml
flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.urllauncher
        pluginClass: UrlLauncherPlugin
      ios:
        pluginClass: UrlLauncherPlugin
      web:
        fileName: url_launcher_web.dart
        pluginClass: UrlLauncherPlugin
```

The iOS build fails with complaining that the class UrlLauncherPlugin is not found and "did you mean FLTUrlLauncherPlugin?" 

I also tried adding the prefix with:
```yaml
      ios:
        pluginClass: FLTUrlLauncherPlugin
```

However, this also fails saying that the file FLTUrlLauncherPlugin.h cannot be found, because the filenames do not have the prefix. It's just UrlLauncherPlugin.h.

If you open and modify UrlLauncherPlugin.h and .m, replacing all instances of FLTUrlLauncherPlugin to be UrlLauncherPlugin, then it works.
