### ISSUE TITLE
After upgrading to 1.9 apple requires strings for location

### ISSUE THREAD

**Issue by Vanethos** [flutter/flutter#40362]
After upgrading to Flutter 1.9, and with no other upgrades on any packages, I get this message from Apple:

> Dear Developer,    We identified one or more issues with a recent delivery   for your app, "Ianum" 1.1.2 (131).                  
> Your delivery was successful, but you may wish to correct the following issues in your next delivery:                        	I
> 
> TMS-90683: Missing Purpose String in Info.plist -  Your app's  code references one or more APIs that access sensitive user data. The  app's Info.plist file should contain a NSLocationAlwaysUsageDescription  key with a user-facing purpose string explaining clearly and completely  why your app needs the data. Starting Spring 2019, all apps submitted  to the App Store that access user data are required to include a purpose  string. If you're using external libraries or SDKs, they may reference  APIs that require a purpose string. While your app might not use these  APIs, a purpose string is still required. You can contact the developer  of the library or SDK and request they release a version of their code  that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).               	
> 
> ITMS-90683: Missing Purpose String in Info.plist -  Your app's  code references one or more APIs that access sensitive user data. The  app's Info.plist file should contain a NSLocationWhenInUseUsageDescription  key with a user-facing purpose string explaining clearly and completely  why your app needs the data. Starting Spring 2019, all apps submitted  to the App Store that access user data are required to include a purpose  string. If you're using external libraries or SDKs, they may reference  APIs that require a purpose string. While your app might not use these  APIs, a purpose string is still required. You can contact the developer  of the library or SDK and request they release a version of their code  that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).                                          
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.                   
>Best regards, The App Store Team

```
[✓] Flutter (Channel beta, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F203, locale en-PT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.0)
[✓] Connected device (1 available)

• No issues found!
```

pubspec.yaml:

```yaml
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  built_collection: ^4.1.0
  built_value: ^6.3.0
  rxdart: ^0.22.0
  pull_to_refresh: ^1.4.6

  #UI
  country_pickers: ^1.0.1
  modal_progress_hud: ^0.1.2
  fast_qr_reader_view: # local
  flutter_page_indicator: ^0.0.3
  transparent_image: ^0.1.0
  flutter_markdown: ^0.2.0
  cached_network_image: ^0.5.1
  flare_flutter:  ^1.5.0
  keyboard_actions: ^1.0.3
  flutter_platform_widgets: ^0.12.0

  # Core
  shared_preferences: ^0.4.3

  # App Linking
  uni_links: ^0.2.0

  # Network
  dio: 2.1.0
  http: ^0.12.0

  # Firebase
  firebase_messaging: ^5.1.2
  firebase_dynamic_links: ^0.4.0+4
  firebase_performance: ^0.3.0+4

  qr_code_scanner:
    path: /Users/goncalopalma/FlutterProjects/openSource/qr_code_scanner

  #translations
  intl: ^0.15.7
  intl_translation: ^0.17.0

  # Misc
  flutter_local_notifications: ^0.8.0
  url_launcher: ^4.0.2
  package_info: ^0.4.0+4
  notification_permissions: # local
  clock: ^1.0.1
  launch_review: ^2.0.0
  connectivity: ^0.4.3+2
  sms_autofill: ^1.1.0


  flutter_crashlytics: ^0.2.0

  cupertino_icons: ^0.1.2

  pedantic: ^1.7.0

dev_dependencies:
  build_runner: ^1.2.3
  built_value_generator: ^6.3.0
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter


flutter:
  assets:
  - assets/
  uses-material-design: true

```

**UPDATE:**
the connectivity package does seem to have a `NSLocation` String that I wasn't aware of, but then again, I've been using this package for some months now, with no problem, and didn't update it.

```
There is a helper method provided in this plugin to request the location authorization: `requestLocationServiceAuthorization`.
To request location authorization, make sure to add the following keys to your _Info.plist_ file, located in `<project root>/ios/Runner/Info.plist`:

* `NSLocationAlwaysAndWhenInUseUsageDescription` - describe why the app needs access to the user’s location information all the time (foreground and background). This is called _Privacy - Location Always and When In Use Usage Description_ in the visual editor.
* `NSLocationWhenInUseUsageDescription` - describe why the app needs access to the user’s location information when the app is running in the foreground. This is called _Privacy - Location When In Use Usage Description_ in the visual editor.
```

However  the functionality depicted above is not in use in the app
