### ISSUE TITLE
Flutter plugin example crashes on dev channel

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#40623]
## Steps to Reproduce

1. Create a new project with the "plugin" project type
2. Run the example in the example/ directory on iOS
3. Observe crash with the message`The application's Info.plist does not contain CFBundleVersion` (see crash report down below)

Running the example app directly from XCode succeeds.

## Crash Report

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d 865295E6-847C-4E9E-809E-F5CDAE046EB1

## exception
```
ProcessException: ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain CFBundleVersion.
Ensure your bundle contains a CFBundleVersion with a valid semantic version number.
  Command: /usr/bin/xcrun simctl install 865295E6-847C-4E9E-809E-F5CDAE046EB1 /Users/ryjohn/code/github/johnpryan/interactive_canvas/example/build/ios/iphonesimulator/Runner.app
```
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:138:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:272:19)
<asynchronous suspension>
#2      SimControl.install (package:flutter_tools/src/ios/simulators.dart:145:29)
#3      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:447:31)
<asynchronous suspension>
#4      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:350:15)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.10.2, on Mac OS X 10.14.6 18G84, locale en-US)
    [32m•[39m Flutter version 1.10.2 at /Users/ryjohn/code/github/flutter/flutter
    [32m•[39m Framework revision f5733f7a62 (5 days ago), 2019-09-11 21:03:42 -0700
    [32m•[39m Engine revision 7ea9884ab0
    [32m•[39m Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/ryjohn/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 37.0.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m Android Studio
    [32m•[39m Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    [32m•[39m Flutter plugin version 34.0.4
    [32m•[39m Dart plugin version 191.6183.87
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2019.2)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [32m•[39m Flutter plugin version 38.2.4
    [32m•[39m Dart plugin version 192.5728.98

[32m[✓][39m VS Code (version 1.37.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.2.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m iPhone Xʀ • 865295E6-847C-4E9E-809E-F5CDAE046EB1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    [32m•[39m Chrome    • chrome                               • web-javascript • Google Chrome 77.0.3865.75
    [32m•[39m Server    • web                                  • web-javascript • Flutter Tools

[32m•[39m No issues found!
```

**Comment by jmagman** [comment]
This is https://github.com/flutter/flutter/issues/38610 with a fix I just merged with https://github.com/flutter/flutter/issues/38610.  See also discussion in https://github.com/flutter/flutter/pull/37707.
You can work around this by adding a version field to your example/pubspec.yaml:
```
version: 0.0.1
```

**Comment by delizondo** [comment]
Please reopen this ticket!

I've been developing my flutter project for more than a year, and everything was working fine until this week, that I updated to Xcode11 and started getting the error reported.

Several months ago I added the `version` in the pubspec.yaml file using this guide:
https://medium.com/@ralphbergmann/versioning-with-flutter-299869e68af4

With that change I was able to submit my application to the Google Play Store and the Apple App Store with no problems at all. For every new version I pushed to the App Store, the `CFBundleShortVersionString` and the `CFBundleVersion` were able to pick their corresponding values from Flutter, but this week, I updated to Xcode11, and started getting the following error message:

```
Launching lib/main_dev.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           43.1s
Finished with error: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain CFBundleVersion.
Ensure your bundle contains a CFBundleVersion.
  Command: /usr/bin/xcrun simctl install FFC86F2A-A6B3-44BF-A44F-03D69D046756 /Users/david/Proyectos/Fixar/fixar_bike/build/ios/iphonesimulator/Runner.app

```

Something to mention here is that my project is split in 2 environments (production and develop)

Flutter Doctor:
```
Davids-MacBook-Pro-2:~ david$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G87, locale en-CR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!

```

pubspec.yaml

```
name: xxxxx
description: xxxxxx.
version: 1.8+34

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  cloud_firestore: ^0.12.9+1
  firebase_storage: ^3.0.6
  firebase_auth: ^0.14.0+4
  firebase_analytics: ^5.0.1
  firebase_crashlytics: ^0.1.0+3
  firebase_core: ^0.4.0+9
  intl: ^0.16.0
  connectivity: ^0.4.3+7
  cached_network_image: ^1.1.1
  flutter_webview_plugin: ^0.3.7
  flutter_duration_picker: ^1.0.4
  flutter_svg: ^0.14.0
  google_maps_flutter: ^0.5.20+6
  geolocator: ^5.1.3
  url_launcher: ^5.1.2
  country_code_picker: ^1.1.5
  image_picker: ^0.6.1+4
  flutter_swiper: ^1.1.6
  json_annotation: ^3.0.0
  fixar_core:
    path: ../fixar_core




dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.0
  build_runner: ^1.6.6

```


As you can see, the `version` is setup in my pubspec.yaml file, however Xcode is not reading it's values.
