### ISSUE TITLE
Remove firebase_analytics

### ISSUE THREAD

**Issue by lifenautjoe** [flutter/flutter#40967]
I've submitted my APK for inspection to the exodus service.

It detects the signatures of firebase_analytics.

How can we remove the code entirely? We're not using analytics.

https://reports.exodus-privacy.eu.org/en/reports/91532/

![image](https://user-images.githubusercontent.com/12737509/65329293-741c7c00-dbb8-11e9-943a-632701b1e33f.png)

**Comment by escamoteur** [comment]
Are you using any Firebase?

**Comment by lifenautjoe** [comment]
Nope. 

```
name: Okuna
description: Social Network

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.0.52+59

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  html: ^0.14.0+2
  expandable: ^2.2.2+3
  uuid: ^2.0.1
  flutter_image_compress: ^0.6.3
  inview_notifier_list:
    git:
      url: https://github.com/OkunaOrg/inview_notifier_list.git
      ref: c74749a052f91fbdd11fad959c2c59d0d10c7695
  connectivity: ^0.4.4
  flutter_widgets: ^0.1.6
  http_retry: ^0.1.1+3
  flutter_exif_rotation: ^0.2.2
  video_thumbnail: ^0.1.5+1
  flutter_ffmpeg: ^0.2.7
  open_iconic_flutter: ^0.3.0
  shared_preferences: ^0.5.2
  flutter_markdown: ^0.2.0
  file_picker: ^1.3.8
  sentry: ^2.2.0
  screen: ^0.0.5
  back_button_interceptor: ^4.0.1
  flutter_colorpicker: any
  intercom_flutter: ^1.0.11
  device_info: ^0.4.0+1
  flutter_pagewise: ^1.2.2
  tinycolor: ^1.0.2
  onesignal_flutter: ^2.0.2
  flutter_advanced_networkimage: ^0.5.0
  dcache: ^0.1.0
  validators: ^1.0.0+1
  url_launcher: ^4.0.1
  uni_links: ^0.1.4
  flutter_slidable: "^0.4.9"
  flutter_cache_manager: ^1.1.1
  cached_network_image: ^1.1.1
  timeago: ^2.0.9
  public_suffix: ^1.2.0
  pigment: ^1.0.3
  photo_view: ^0.4.2
  flutter_svg: ^0.13.0
  flutter_secure_storage: ^3.1.2
  mime: ^0.9.6+2
  http: ^0.12.0
  intl: ^0.15.7
  rxdart: ^0.18.1
  video_player:
    git:
      url: https://github.com/999eagle/plugins.git
      ref: feature/caching
      path: packages/video_player
  sprintf: "^4.0.0"
  image_picker: 0.6.1
  image_cropper: ^1.0.1
  shimmer: ^1.0.0
  share: ^0.6.1
  path: ^1.6.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  intl_translation: ^0.17.1

```
