### ISSUE TITLE
Flutter Web - Fonts/MaterialIcons not working on Safari iOS13

### ISSUE THREAD

**Issue by GaspardMerten** [flutter/flutter#41354]
Hello,

I just migrated my app to flutter web, and everything was working 'fine'.

But on iOS13, fonts are not loaded, and that's a big issue for me because I use `MaterialIcons` everywhere in my app...

Here is my `pubspec.yaml` file:
```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  giveactions_core:
    path: ../project_core
  universal_html: ^1.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: ressources/fonts/Comfortaa-Regular.ttf

    - family: LemonMilk
      fonts:
        - asset: ressources/fonts/LemonMilk.otf
  assets:
    - ressources/image/background.jpg
    - ressources/image/favicon.png
    - ressources/image/google.png
    - ressources/image/giveactions-full.png

  uses-material-design: true
```

I'm using the latest version of Flutter (on master)

Any idea on how to solve that? (It works perflectly on iOS12, Android, Desktop)
