### ISSUE TITLE
[web]: Flutter web not working in for existing Flutter app

### ISSUE THREAD

**Issue by rahuldevanavar91** [flutter/flutter#41470]
We have existing Flutter app, want to add Flutter web support. but it gives the error 

```
$ flutter create .

Ambiguous organization in existing files: {com.mansh.purplle, com.mansh.purplle.fluttermodule}. The --org command line argument must be specified to recreate project.

```
if We run 

`$flutter create --org  com.manash.purplle .`
it won't give an error  but web folder is not created

If create any new sample project flutter web is working perfectly.
 
**Flutter doctor** 

```
[✓] Flutter (Channel master, v1.10.7-pre.23, on Linux, locale en_IN)
    • Flutter version 1.10.7-pre.23 at /home/ag-purplle/Downloads/flutter
    • Framework revision e0247442d0 (30 hours ago), 2019-09-26 02:49:41 -0400
    • Engine revision 3713ecf107
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 c6a14f4459)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/ag-purplle/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/ag-purplle/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/ag-purplle/Downloads/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 76.0.3809.132
    • Server                    • web           • web-javascript • Flutter Tools

• No issues found!

```

Modules in `pubsec.yml
`
```

# This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidPackage: com.mansh.purplle.fluttermodule
    iosBundleIdentifier: com.mansh.purplle.flutterModule
```
