### ISSUE TITLE
[in_app_purchase] Define clang modules plugin for iOS

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#41648]
Define clang modules in in_app_purchase plugin to:
1. Allow it to be imported into Swift apps as libraries without `use_frameworks!`.
1. Allow it to be module imported `@import` into Objective-C apps.

See further details in https://github.com/flutter/flutter/issues/41007

### Import into Swift app as a library
1. `flutter create test_create_app`
2. Add in_app_purchase to the pubspec.
```
dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: any
```
3. In generated `ios/Podfile` remove `use_frameworks!`
4. `flutter build ios`
5. In AppDelegate.swift add `import in_app_purchase` at the top.
6. Build.

Compilation error: no such module 'in_app_purchase'

### Module import (`@import`) into Objective-C app
1. `flutter create -i objc test_create_app`
2. Add in_app_purchase.
```
dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: any
```
3. `flutter build ios`
4. In AppDelegate.m add `@import in_app_purchase;` at the top.
5. Build.

Compilation error: no such module 'in_app_purchase'
