### ISSUE TITLE
[android_alarm_manager] Define clang module for iOS

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#41855]
Define clang modules in android_alarm_manager plugin to:
1. Allow it to be imported into Swift apps as libraries without `use_frameworks!`.
1. Allow it to be module imported `@import` into Objective-C apps.

See further details in https://github.com/flutter/flutter/issues/41007

### Import into Swift app as a library
1. `flutter create test_create_app`
2. Add android_alarm_manager to the pubspec.
```
dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: any
```
3. In generated `ios/Podfile` remove `use_frameworks!`
4. `flutter build ios`
5. In AppDelegate.swift add `import android_alarm_manager` at the top.
6. Build.

Compilation error: no such module 'android_alarm_manager'

### Module import (`@import`) into Objective-C app
1. `flutter create -i objc test_create_app`
2. Add android_alarm_manager.
```
dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: any
```
3. `flutter build ios`
4. In AppDelegate.m add `@import android_alarm_manager;` at the top.
5. Build.

Compilation error: no such module 'android_alarm_manager'
