### ISSUE TITLE
[connectivity] Define clang module for iOS

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#41883]
Define clang modules in connectivity plugin to:
1. Allow it to be imported into Swift apps as libraries without `use_frameworks!`.
1. Allow it to be module imported `@import` into Objective-C apps.

See further details in https://github.com/flutter/flutter/issues/41007

### Import into Swift app as a library
1. `flutter create test_create_app`
2. Add connectivity to the pubspec.
```
dependencies:
  flutter:
    sdk: flutter
  connectivity: any
```
3. In generated `ios/Podfile` remove `use_frameworks!`
4. `flutter build ios`
5. In AppDelegate.swift add `import connectivity` at the top.
6. Build.

Compilation error: no such module 'connectivity'

### Module import (`@import`) into Objective-C app
1. `flutter create -i objc test_create_app`
2. Add connectivity.
```
dependencies:
  flutter:
    sdk: flutter
  connectivity: any
```
3. `flutter build ios`
4. In AppDelegate.m add `@import connectivity;` at the top.
5. Build.

Compilation error: no such module 'connectivity'
