### ISSUE TITLE
Flutter iOS : Terminated due to memory issue

### ISSUE THREAD

**Issue by shyjuzz** [flutter/flutter#42307]
My flutter app is crashing with an error "Message from debugger: Terminated due to memory issue" while running on iPhone 6 plus device. The crash occurs when we scroll the list with images. The sample project which demonstrates the crash is available  https://github.com/shyjuzz/flutter-samples/tree/master/crash_test

```
`import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

final images = [
  'https://firebasestorage.googleapis.com/v0/b/eventurboapp.appspot.com/o/userposts%2F2019-09-14T19%3A42%3A13.717163.jpg?alt=media&token=733bf554-168b-4ef3-ac91-b7e4911a5531',
  'https://firebasestorage.googleapis.com/v0/b/eventurboapp.appspot.com/o/userposts%2F2019-08-26T15%3A11%3A41.359199.jpg?alt=media&token=c3d7876a-28c4-4800-aa85-39c980b5dc5',
  'https://firebasestorage.googleapis.com/v0/b/eventurboapp.appspot.com/o/userposts%2F2019-08-26T15%3A03%3A12.813399.jpg?alt=media&token=e0ba4903-0282-43f2-94bf-1f841a7c7d33',
  'https://firebasestorage.googleapis.com/v0/b/eventurboapp.appspot.com/o/userposts%2F2019-08-22T16%3A00%3A28.429855.jpg?alt=media&token=915b9ea8-8370-4ff0-aaa6-89c23c28b89b'
];

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    //var list = new List<int>.generate(60, (i) => i + 1);

    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: ListView.builder(
                itemCount: images.length,
                itemBuilder: (BuildContext context, int index) {
                  return Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Column(
                      children: <Widget>[
                        Text('$index'),
                        Center(
                          child: CachedNetworkImage(
                            placeholder: (context, url) => CircularProgressIndicator(),
                            imageUrl: images[index],
                          ),
                        ),
                      ],
                    ),
                  );
                }),
          )), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}`
```

Please help me to find a solution why this is happening even if we use CachedNetworkImage ?

**Comment by iapicca** [comment]
Hi @shyjuzz 
can you please post your yaml file 
and the error log 
thank you

**Comment by Vitaly-V** [comment]
I have the same behavior as a topic starter has. 
I'm also using iPhone 6+ for development.

**Comment by shyjuzz** [comment]
> Hi @shyjuzz
> can you please post your yaml file
> and the error log
> thank you

The sample project to replicate the issue is available here https://github.com/shyjuzz/flutter-samples/tree/master/crash_test

Error log shows only the "Terminated due to memory issue " message

Pubspec

```
name: crash_test
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cached_network_image: ^1.1.1

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
