### ISSUE TITLE
snackbar hides behind keyboard

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#42428]
In my A AndroidManifest.xml  in activity I have:

**android:windowSoftInputMode="adjustResize"**

My flutter sdk is stable 1.9.1 hot fix 4.

I have a simple form and always snackbar shows behind keyboard. Any special configuration so I can show my snackbar top of the keyboard in android and iOS. Any idea? Thanks

**Comment by NTMS2017** [comment]
Below it shown my pub specs.yaml configuration. If I create a simple flutter project and use only  card_settings: ^1.4.2 plugin my snackbar shows top of the keyboard. But if I put all the plugin in  pub specs.yaml configuration than my snackbar shows behind keyboard.

is it possible to flutter to warn plugin vendor about this type of negative effect? Or at least flutter  should put some debugging on console so we can correct it the plugin or file a issue to plugin vendor.

Kind Regards

**My Flutter doctor -v output**
```
 flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale tr-TR)
    • Flutter version 1.9.1+hotfix.4 at /Users/niyazitoros/flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.1.4
    • Dart plugin version 192.6817.14

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)



```
**My pub spec.yaml configuration:**
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.4
  decimal: ^0.3.5
  intl: ^0.15.8
  encrypt: 2.1.0
  image: ^2.1.4
  path_provider: ^1.3.0
  mailer: ^3.0.3
  flutter_slidable: ^0.4.9
  xml: ^3.5.0
  http: ^0.12.0+2
  page_transition: ^1.1.4
  flutter_swiper: ^1.1.6
  card_settings: ^1.4.2
  flutter_speed_dial: ^1.2.1
  drop_cap_text: ^1.0.1
  diacritic: ^0.1.1
  ntp: ^1.0.4
  flare_flutter: ^1.5.12
  image_picker: ^0.6.1+4
  image_crop: ^0.3.1
  webview_flutter: ^0.3.14+1
  url_launcher: ^5.1.4
  package_info: ^0.4.0+6
  flutter_screenutil: ^0.6.0
  flutter_barcode_scanner: ^0.1.7
  auto_size_text: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```
