### ISSUE TITLE
Flutter App Crash - App crash after I work with google map and firebase messages

### ISSUE THREAD

**Issue by almohitapp** [flutter/flutter#42567]
I am very confused about this. No anyone got the same problem as me after I checked on Github Issues. In Android work well but iOS doesn't. 

I just follow the instructions of using the google_maps_flutter, firebase_database, and firebase_storage, but I'm not getting the same result as the instructions.

This is the result I have got in my app:
[click here to see the problem!](https://drive.google.com/open?id=1p12dgyZboo72bwxdiGVmhUxTh31nnUef)

### If I run **flutter doctor -v**:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/builder/programs/flutter
    • Framework revision cc949a8e8b (2 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/builder/programs/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/builder/programs/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode-11.1.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

### this is my `Info.plist`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>المحيط</string>
	<key>CFBundleDisplayName</key>
    <string>Almohit</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>

	<key>NSPhotoLibraryUsageDescription</key>
    <string>Photo Library Access Warning</string>
    <key>NSCameraUsageDescription</key>
    <string>Camera Library Access Warning</string>
    <key>NSMicrophoneUsageDescription</key>
    <string>Microphone Library Access Warning</string>

	<key>LSRequiresIPhoneOS</key>
	<true/>


	<key>io.flutter.embedded_views_preview</key>
    <true/>

    <key>NSLocationWhenInUseUsageDescription</key>
    <string>When In Use Permission</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>Always Permission</string>
    <key>NSLocationAlwaysAndWhenInUsageDescription</key>
    <string>Always And In Use Permission</string>


	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
    <true/>
</dict>
</plist>
```

### This is `pubspec.yaml`
```

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  ## flutter_webview_plugin: ^0.2.1+2
  ## url_launcher: ^3.0.0



  ##http: ^0.12.0+2 # Firebase real time db + http connection
  flutter_spinkit: "^3.1.0" #loading icons

  shared_preferences: ^0.5.2 #save data locally
  dio: ^2.1.10
  cloud_firestore: ^0.12.9
  flutter_plugin_pdf_viewer: ^1.0.6
  date_range_picker: ^1.0.5 #date picker
  flutter_custom_tabs: ^0.6.0
  connectivity: ^0.4.0 # internet connection
  google_maps_flutter: ^0.5.21+3 #^0.5.19+2 #^0.4.0
  ##geolocator: ^2.1.0
  #geo_location_finder: ^1.0.8
  location: ^2.3.5
  geocoder: ^0.2.1
  firebase_database: ^3.0.5
  image_picker: ^0.6.0+9
  toast: ^0.1.3
  firebase_storage: ^3.0.2
  #google_maps_webservice: ^0.0.14
  #firebase_messaging: ^5.1.6 #^5.0.4

  webview_flutter: ^0.3.14+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

#dependency_overrides:
  #image: 2.0.7

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon@2x.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
  - assets/img/
  - assets/img/doc/
  - assets/img/ic_user.png
  - assets/img/ic_navigation.png
  - assets/img/call.png
  - assets/img/message.png

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
        - asset: assets/fonts/ElMessiri-Medium.ttf
        - asset: assets/fonts/ElMessiri-Regular.ttf
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          style: normal
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/Scheherazade-Bold.ttf
        - asset: assets/fonts/Scheherazade-Regular.ttf
          weight: 700
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```
Btw in android work well but iOS does not work.
