### ISSUE TITLE
[web] Ignoring assets MIME type

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#42612]
## Use case
I have a js file that gets loaded from a service worker from the assets, but in debug I get the error that the MIME type is wrong. When running in production the web server handles the MIME type.

## Proposal
Flutter seems to have no way of setting the MIME type of an asset.
Maybe a key like `assets-mime-type` could be added to the `pubspec.yaml` to set the type for every asset file if needed.
But there is the problem that not every character is valid yaml character.

Something like this:
```yaml
flutter:
  assets:
    - image.png
    - test.js
  assets-mime-type:
    image.png: image/png
    test.js: application/javascript
```
