### ISSUE TITLE
some CupertinoIcons is missing are `flutter/lib/src/cupertino/icons.dart`

### ISSUE THREAD

**Issue by lpe234** [flutter/flutter#42886]
such as `0xf375` icon, can't find in `flutter/lib/src/cupertino/icons.dart`.

i hava updated my `pubspec.yaml`, 

```yaml
  cupertino_icons:
    git:
      url: "https://github.com/flutter/cupertino_icons"
```

---

i can use it in this way, `Icon(IconData(0xf375, fontFamily: 'CupertinoIcons', fontPackage: 'cupertino_icons')`.
