### ISSUE TITLE
Crash on iOS Platform

### ISSUE THREAD

**Issue by Gengpp** [flutter/flutter#42976]
**Target Platform:**    iOS 
```
	 flutter: Observatory listening on http://127.0.0.1:64078/wquBJF9ir0k=/
  flutter: route: PageEnum.Recent_Service_page
  flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
  flutter: The following StackOverflowError was thrown attaching to the render tree:
  flutter: Stack Overflow
  flutter:
  flutter: When the exception was thrown, this was the stack:
  flutter: #1      AbstractNode.detach (package:flutter/src/foundation/node.dart)
  flutter: #2      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2784:11)
  flutter: #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #6      _RenderStack&RenderBox&ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3054:13)
  flutter: #7      __RenderTheatre&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #8      __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin&ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3051:11)
  flutter: #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #12     RenderPointerListener.detach (package:flutter/src/rendering/proxy_box.dart:2651:11)
  flutter: #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #14     RenderCustomPaint.detach (package:flutter/src/rendering/custom_paint.dart:501:11)
  flutter: #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #19     _RenderStack&RenderBox&ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3054:13)
  flutter: #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #21     RenderDecoratedBox.detach (package:flutter/src/rendering/proxy_box.dart:1908:11)
  flutter: #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #27     _RenderStack&RenderBox&ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3054:13)
  flutter: #28     __RenderTheatre&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #29     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin&ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3051:11)
  flutter: #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #33     RenderPointerListener.detach (package:flutter/src/rendering/proxy_box.dart:2651:11)
  flutter: #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #35     RenderCustomPaint.detach (package:flutter/src/rendering/custom_paint.dart:501:11)
  flutter: #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #40     _RenderStack&RenderBox&ContainerRenderObjectMixin.detach (package:flutter/src/rendering/object.dart:3054:13)
  flutter: #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: #42     RenderDecoratedBox.detach (package:flutter/src/rendering/proxy_box.dart:1908:11)
  flutter: #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.detach (package:flutter/src/rendering/object.dart:2786:14)
  flutter: ...
  flutter: ...
  flutter: #7040   Element.detachRenderObject (package:flutter/src/widgets/framework.dart:2989:5)
  flutter: #7041   Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2990:13)
  flutter: #7042   ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
  flutter: #7043   Element.detachRenderObject (package:flutter/src/widgets/framework.dart:2989:5)
  flutter: #7044   Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2990:13)
  flutter: #7045   ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
  flutter: #7046   Element.detachRenderObject (package:flutter/src/widgets/framework.dart:2989:5)
  flutter: #7047   Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2990:13)
  flutter: #7048   ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
  flutter: #7049   Element.detachRenderObject (package:flutter/src/widgets/framework.dart:2989:5)
  flutter: #7050   Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2990:13)
  flutter: #7051   ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
  flutter: #7052   Element.detachRenderObject (package:flutter/src/widgets/framework.dart:2989:5)
  flutter: #7053   Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2990:13)
  flutter: #7054   ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3955:14)
  flutter: #7055   Element.detachRenderObject (package:flutter/src/widgets/framework.dart:2989:5)
  flutter: #7056   Element.deactivateChild (package:flutter/src/widgets/framework.dart:3119:11)
  flutter: #7057   Element.updateChild (package:flutter/src/widgets/framework.dart:2884:7)
  flutter: #7058   RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
  flutter: #7059   RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:917:5)
  flutter: #7060   RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:931:7)
  flutter: #7061   Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
  flutter: #7062   BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
  flutter: #7063   _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
  flutter: #7064   _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
  flutter: #7065   _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
  flutter: #7066   _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
  flutter: #7067   _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
  flutter: #7076   _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
  flutter: #7077   _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
  flutter: #7078   _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
  flutter: (elided 9 frames from class _AssertionError, package dart:async, and package dart:async-patch)
  flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
  flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1164 pos 12: 'child.parentData != null': is not true.
  flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2338 pos 16: '!_dirtyElements[index]._active || _dirtyElements[index]._debugIsInScope(context)': is not true.
  flutter: Another exception was thrown: Stack Overflow
  flutter: Another exception was thrown: RenderSemanticsAnnotations does not meet its constraints.
  flutter: Another exception was thrown: RenderRepaintBoundary does not meet its constraints.
(lldb) 
```

```
Last login: Thu Oct 17 21:41:44 on ttys001
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-HK)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!
➜  ~
```
