### ISSUE TITLE
Building flutter tool... - not responding and not stopping after update hotfix 5

### ISSUE THREAD

**Issue by boyfox** [flutter/flutter#43066]
After updating flutter_macos_v1.9.1+hotfix.5-stable i get following bug:

`Building flutter tool...
`
after updating flutter build tool not responding, and if you open yaml file also android studio will not answer.

**Comment by jmagman** [comment]
Do you know what version you were on before the upgrade
Can we get a `--verbose` output of the command you were trying to run?  That may give us a hint as to where it's stuck.

**Comment by boyfox** [comment]
Hi @iapicca, sorry for late answer:

```
My-MacBook-Pro:~ soporboy$ flutter upgrade
Upgrading Flutter from /Users/soporboy/Library/Flutter...
Updating c382b8e99..68587a091
 25 files changed, 574 insertions(+), 331 deletions(-)
Building flutter tool...

Upgrading engine...

Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (6 weeks ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-UZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

I have not problem with installation of flutter, I upgraded 1.9.1+hotfix.6 but problem still exists. I can't open pubspec.yaml inside Android Studio, because if I will open pubspec.yaml inside Android Studio it not responding then I can't work android studio because it not respond. To avoid that problem i must kill android studio and restart again and don't open pubspec.yaml inside Android Studio. Need work just in console of MacOS Catalina. I tried change PUB_HOSTED_URL to another **https://pub.flutter-io.cn/** but not helped

**Comment by boyfox** [comment]
@jmagman I used flutter version v1.9.1+hotfix.4 version before I installed flutter version v1.9.1+hotfix.5 version. After appeared that problem I delete flutter sdk and I downloaded v1.9.1+hotfix.5 full-archive and upgrade it to v1.9.1+hotfix.6. But Android Studio still stuck when I opening pubspec.yaml file.

File **pubspec.yaml** :
```
name: fanta
description: Fanta mobile application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.5+9

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  feather_icons_flutter: ^4.7.4
  shared_preferences: ^0.5.3+5
  firebase_messaging: ^5.1.4
  web_socket_channel: ^1.1.0
  http: ^0.12.0+2
  dio: ^3.0.3
  photo_view: ^0.6.0
  uuid: ^2.0.2
  flutter_range_slider: ^1.4.0
  timeago: ^2.0.21
  geocoder: ^0.2.1
  transparent_image: ^1.0.0
  image_picker: ^0.6.1+8
  outline_material_icons: ^0.1.1
  intl: ^0.15.8
  geolocator: ^5.1.4+2
  url_launcher: ^5.2.3
  timezone: ^0.5.5
  units: ^0.0.7
  device_info: ^0.4.0+4
  flutter_image_compress: ^0.6.3
  android_intent: ^0.3.4+3
  flutter_svg: ^0.14.2
  google_maps_flutter: ^0.5.21+8
  location: ^2.3.5
  sms_autofill: ^1.1.0
  flutter_local_notifications: ^0.8.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - content/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```

File **pubspec.lock:**
```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  android_intent:
    dependency: "direct main"
    description:
      name: android_intent
      url: "https://pub.dev/"
    source: hosted
    version: "0.3.4+4"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dev/"
    source: hosted
    version: "2.3.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dev/"
    source: hosted
    version: "1.0.5"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dev/"
    source: hosted
    version: "1.1.2"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dev/"
    source: hosted
    version: "1.14.11"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dev/"
    source: hosted
    version: "2.1.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dev/"
    source: hosted
    version: "2.1.3"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dev/"
    source: hosted
    version: "0.1.2"
  device_info:
    dependency: "direct main"
    description:
      name: device_info
      url: "https://pub.dev/"
    source: hosted
    version: "0.4.1+1"
  dio:
    dependency: "direct main"
    description:
      name: dio
      url: "https://pub.dev/"
    source: hosted
    version: "3.0.3"
  feather_icons_flutter:
    dependency: "direct main"
    description:
      name: feather_icons_flutter
      url: "https://pub.dev/"
    source: hosted
    version: "4.7.4"
  firebase_messaging:
    dependency: "direct main"
    description:
      name: firebase_messaging
      url: "https://pub.dev/"
    source: hosted
    version: "5.1.6"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_image_compress:
    dependency: "direct main"
    description:
      name: flutter_image_compress
      url: "https://pub.dev/"
    source: hosted
    version: "0.6.3"
  flutter_local_notifications:
    dependency: "direct main"
    description:
      name: flutter_local_notifications
      url: "https://pub.dev/"
    source: hosted
    version: "0.8.4"
  flutter_localizations:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_range_slider:
    dependency: "direct main"
    description:
      name: flutter_range_slider
      url: "https://pub.dev/"
    source: hosted
    version: "1.4.0"
  flutter_svg:
    dependency: "direct main"
    description:
      name: flutter_svg
      url: "https://pub.dev/"
    source: hosted
    version: "0.14.3"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  geocoder:
    dependency: "direct main"
    description:
      name: geocoder
      url: "https://pub.dev/"
    source: hosted
    version: "0.2.1"
  geolocator:
    dependency: "direct main"
    description:
      name: geolocator
      url: "https://pub.dev/"
    source: hosted
    version: "5.1.4+2"
  google_api_availability:
    dependency: transitive
    description:
      name: google_api_availability
      url: "https://pub.dev/"
    source: hosted
    version: "2.0.1"
  google_maps_flutter:
    dependency: "direct main"
    description:
      name: google_maps_flutter
      url: "https://pub.dev/"
    source: hosted
    version: "0.5.21+8"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev/"
    source: hosted
    version: "0.12.0+2"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dev/"
    source: hosted
    version: "3.1.3"
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      url: "https://pub.dev/"
    source: hosted
    version: "0.6.1+8"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dev/"
    source: hosted
    version: "0.15.8"
  location:
    dependency: "direct main"
    description:
      name: location
      url: "https://pub.dev/"
    source: hosted
    version: "2.3.5"
  location_permissions:
    dependency: transitive
    description:
      name: location_permissions
      url: "https://pub.dev/"
    source: hosted
    version: "2.0.3"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dev/"
    source: hosted
    version: "0.12.5"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dev/"
    source: hosted
    version: "1.1.7"
  outline_material_icons:
    dependency: "direct main"
    description:
      name: outline_material_icons
      url: "https://pub.dev/"
    source: hosted
    version: "0.1.1"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dev/"
    source: hosted
    version: "1.6.4"
  path_drawing:
    dependency: transitive
    description:
      name: path_drawing
      url: "https://pub.dev/"
    source: hosted
    version: "0.4.1"
  path_parsing:
    dependency: transitive
    description:
      name: path_parsing
      url: "https://pub.dev/"
    source: hosted
    version: "0.1.4"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dev/"
    source: hosted
    version: "1.8.0+1"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.dev/"
    source: hosted
    version: "2.4.0"
  photo_view:
    dependency: "direct main"
    description:
      name: photo_view
      url: "https://pub.dev/"
    source: hosted
    version: "0.6.0"
  pin_input_text_field:
    dependency: transitive
    description:
      name: pin_input_text_field
      url: "https://pub.dev/"
    source: hosted
    version: "2.1.0"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dev/"
    source: hosted
    version: "2.2.1"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dev/"
    source: hosted
    version: "2.0.5"
  shared_preferences:
    dependency: "direct main"
    description:
      name: shared_preferences
      url: "https://pub.dev/"
    source: hosted
    version: "0.5.4+1"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  sms_autofill:
    dependency: "direct main"
    description:
      name: sms_autofill
      url: "https://pub.dev/"
    source: hosted
    version: "1.1.1"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dev/"
    source: hosted
    version: "1.5.5"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dev/"
    source: hosted
    version: "1.9.3"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dev/"
    source: hosted
    version: "2.0.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dev/"
    source: hosted
    version: "1.0.5"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dev/"
    source: hosted
    version: "1.1.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dev/"
    source: hosted
    version: "0.2.5"
  timeago:
    dependency: "direct main"
    description:
      name: timeago
      url: "https://pub.dev/"
    source: hosted
    version: "2.0.21"
  timezone:
    dependency: "direct main"
    description:
      name: timezone
      url: "https://pub.dev/"
    source: hosted
    version: "0.5.5"
  transparent_image:
    dependency: "direct main"
    description:
      name: transparent_image
      url: "https://pub.dev/"
    source: hosted
    version: "1.0.0"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dev/"
    source: hosted
    version: "1.1.6"
  units:
    dependency: "direct main"
    description:
      name: units
      url: "https://pub.dev/"
    source: hosted
    version: "0.0.7"
  url_launcher:
    dependency: "direct main"
    description:
      name: url_launcher
      url: "https://pub.dev/"
    source: hosted
    version: "5.2.5"
  url_launcher_platform_interface:
    dependency: transitive
    description:
      name: url_launcher_platform_interface
      url: "https://pub.dev/"
    source: hosted
    version: "1.0.1"
  uuid:
    dependency: "direct main"
    description:
      name: uuid
      url: "https://pub.dev/"
    source: hosted
    version: "2.0.2"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dev/"
    source: hosted
    version: "2.0.8"
  web_socket_channel:
    dependency: "direct main"
    description:
      name: web_socket_channel
      url: "https://pub.dev/"
    source: hosted
    version: "1.1.0"
  xml:
    dependency: transitive
    description:
      name: xml
      url: "https://pub.dev/"
    source: hosted
    version: "3.5.0"
sdks:
  dart: ">2.4.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"
```
