### ISSUE TITLE
Flutter relative path dependency are awkward

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#4344]
Is there any solution to the flutter relative path? It's somewhat frustrating having to change it for every app I want to build:

```yaml
dependencies:
  flutter:
    path: ../../flutter/packages/flutter
```

I noticed there was a ticket in pub here: https://github.com/dart-lang/pub/issues/1358
It seems there is no intention of supporting environment variables.

I'm assuming the end goal is to push flutter to pub, but until then is there any sane best practice people are using that I'm not realizing?
