### ISSUE TITLE
Can't run app on android.

### ISSUE THREAD

**Issue by axelFrau** [flutter/flutter#43493]
Basically my app works perfectly on iOS and it builds but for Android it won't work i tried anything and i don't know what to do anymore.

Here is my "flutter doctor -v" :
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-FR)
    • Flutter version 1.9.1+hotfix.6 at /Users/axel/flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/axel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

Then here is "my flutter run -v" logs  :
```
[ +148 ms] Building APK
[  +39 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] executing: [/Users/axel/Documents/CSC/flutter-app/android/] /Users/axel/Documents/CSC/flutter-app/android/gradlew -Pverbose=true -Ptarget=/Users/axel/Documents/CSC/flutter-app/lib/main.dart
-Ptrack-widget-creation=false -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+1121 ms] > Configure project :app
[        ] WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
[        ] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
[        ] WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
[        ] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
[        ] WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
[        ] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
                                                                             
                                                                             .
                                                                             .
                                                                             .
                                                                             .

[+4191 ms] > Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
[        ]          *********************************************************
[        ] WARNING: This version of firebase_core will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] 285 actionable tasks: 10 executed, 275 up-to-date
[        ] /Users/axel/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.6.0+1/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java:16: error: package io.flutter.plugins.localauth.AuthenticationHelper
does not exist
[   +2 ms] import io.flutter.plugins.localauth.AuthenticationHelper.AuthCompletionHandler;
[ +140 ms]                                                         ^
[        ] /Users/axel/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.6.0+1/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java:62: error: cannot find symbol
[        ]       AuthenticationHelper authenticationHelper =
[        ]       ^
[        ]   symbol:   class AuthenticationHelper
[        ]   location: class LocalAuthPlugin
[        ] /Users/axel/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.6.0+1/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java:63: error: cannot find symbol
[        ]           new AuthenticationHelper(
[        ]               ^
[        ]   symbol:   class AuthenticationHelper
[   +1 ms]   location: class LocalAuthPlugin
[        ] /Users/axel/flutter/.pub-cache/hosted/pub.dartlang.org/local_auth-0.6.0+1/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java:66: error: cannot find symbol
[        ]               new AuthCompletionHandler() {
[        ]                   ^
[        ]   symbol:   class AuthCompletionHandler
[        ]   location: class LocalAuthPlugin
[        ] 4 errors
[ +311 ms] Running Gradle task 'assembleDebug'... (completed in 7.3s)
[   +4 ms] "flutter run" took 16,407ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:751:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:494:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:486:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#28     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#36     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

and finally there is my pubspec.yaml : 
```
name: [secret]
description: [secret]

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.43

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.2
  cached_network_image: ^1.1.1
  flutter_svg: ^0.13.1
  rflutter_alert: ^1.0.3
  flutter_bloc: ^0.11.1
  equatable: ^0.1.6
  flutter_secure_storage: ^3.2.1
  local_auth: ^0.6.0+1
  http_auth: ^0.2.5
  firebase_core: ^0.4.0+9
  firebase_messaging: ^5.1.6
  validate: ^1.7.0
  kiwi: ^0.1.0
  image_picker: ^0.6.1
  flutter_crashlytics: ^1.0.0
  flutter_sticky_header: ^0.4.0
  dio: ^2.1.0
  auto_size_text: ^1.1.1
  flutter_masked_text: ^0.8.0
  permission_handler: '^3.2.0'
  path_provider: ^0.5.0+1
  flutter_email_sender: ^2.0.0
  flutter_swiper: ^1.1.6
  contacts_service: ^0.2.8
  geolocator: ^5.1.1+1
  google_maps_flutter: ^0.5.20+1
  url_launcher: ^5.0.2
  qr_mobile_vision: ^0.2.2
  qr_flutter: ^2.0.0+51
  csv: ^4.0.3
  share_extend: ^1.0.8
  country_pickers: ^1.1.0
  diacritic: ^0.1.1
  recase: ^2.0.1
  keyboard_visibility: ^0.5.6

  flutter_worldpay:
    path: ../flutter_worldpay/

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato.ttf
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
```
