### ISSUE TITLE
Unable to pub get flutter_driver

### ISSUE THREAD

**Issue by sklan** [flutter/flutter#43706]
I want to run tests on my app. However, I am unable to get the flutter_driver package.
## Steps to Reproduce
1.  ```flutter pub get``` 
```
Because flutter_app depends on flutter_driver any which doesn't exist (could not find package flutter_driver at https://pub.dartlang.org), version solving failed.
pub get failed (69) -- attempting retry 1 in 1 second...                
Because flutter_app depends on flutter_driver any which doesn't exist (could not find package flutter_driver at https://pub.dartlang.org), version solving failed.
pub get failed (69) -- attempting retry 2 in 2 seconds...               
Because flutter_app depends on flutter_driver any which doesn't exist (could not find package flutter_driver at https://pub.dartlang.org), version solving failed.
pub get failed (69) -- attempting retry 3 in 4 seconds... 
```
## Pubspec.yaml
```
name: flutter_app
description: The Flutter App
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_settings: ^1.0.6+2
  async: ^2.3.0
  cached_network_image: ^1.1.2
  cloud_firestore: ^0.12.9+5
  connectivity: ^0.4.5+2
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  flutter_launcher_icons: ^0.7.4
  geoflutterfire: ^2.0.3+5
  geolocator: ^5.1.4+2
  http: ^0.12.0+2
  location_permissions: ^2.0.3
  provider: ^3.1.0+1
  shared_preferences: ^0.5.4+3
  url_launcher: ^5.2.5



dev_dependencies:
  flutter_driver: any
  flutter_test:
    sdk: flutter
  test: ^1.0.0
  mockito: 4.1.1


flutter:
  assets:
    - assets/
  fonts:
    - family: NotoSerif
      fonts:
        - asset: fonts/NotoSerif-Bold.ttf
          weight: 200
        - asset: fonts/NotoSerif-BoldItalic.ttf
        - asset: fonts/NotoSerif-Regular.ttf
        - asset: fonts/NotoSerif-RegularItalic.ttf


  uses-material-design: true
```
## Log

Output of flutter doctor
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A583, locale
    en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/sklan/flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sklan/Library/Android/sdk
    • Android NDK at /Users/sklan/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Mi A1     • 51c7c2bf0704                         • android-arm64 • Android
      9 (API 28)
    • iPhone Xʀ • F740444A-F962-4600-9E2E-4157A85C6296 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```
