### ISSUE TITLE
[androidx-migration] No Usages Found in the Project

### ISSUE THREAD

**Issue by vishesh-allahabadi** [flutter/flutter#43845]
i am not able to build my apk as it tells me that my app has Android X incompatibilities.
When i try migrating by the method stated on flutter.dev it gives me a warning message "No Usages Found in the Project"

What should i do ?

**Comment by BondarenkoStas** [comment]
@vishesh-allahabadi did you add 
```
android.useAndroidX=true
android.enableJetifier=true
```
to your android/gradle.properties?

**Comment by vishesh-allahabadi** [comment]
Yes i did that

**Comment by vishesh-allahabadi** [comment]
If this is of any help, it gives me the following error in terminal:

Warning: there were 6 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 1 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        75.3s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task bundleRelease failed with exit code 1

**Comment by BondarenkoStas** [comment]
@vishesh-allahabadi please paste your flutter doctor -v output. And probably send your pubspec.yaml

**Comment by BondarenkoStas** [comment]
I don't know how exactly it's connected with your situation, the issue seems similar about No usage found in the Project. You didn't show the full log, apparently there was some info about those classes, and you can hide those warnings with https://github.com/flutter/flutter/issues/39650#issuecomment-527767673.

**Comment by blasten** [comment]
@vishesh-allahabadi would you mind pasting the content of pubspec.yaml?

**Comment by vishesh-allahabadi** [comment]
Here's my pubspec.yaml
```
name: calendar
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.0+7


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - images/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

**Comment by vishesh-allahabadi** [comment]
Latest complete Log report:

`Running "flutter pub get" in calender...                            2.1s
Initializing gradle...                                              2.5s
Resolving dependencies...                                          10.5s
Running Gradle task 'bundleRelease'...
Request to incrementing alive workforce from 0. Current workforce (dead or alive) 0
thread-pool size=4
Warning: Exception while processing task java.io.IOException: proguard.ParseException: Expecting class member name before ';' in line 12 of file 'C:\Users\Vishesh\
AndroidStudioProjects\fartsounds_app\calender\android\app\proguard-rules.pro'
Thread(Tasks limiter_1): destruction

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 42s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                       223.4s (!)
Gradle task bundleRelease failed with exit code 1

`

**Comment by jiajunhuang** [comment]
I got the same problem, please help

**Comment by kf6gpe** [comment]
@jiajunhuang  and @vishesh-allahabadi --- can you please give us the results of `flutter doctor`?

**Comment by jiajunhuang** [comment]
hello, I've resolved this question by change `build.gradle` according to this: https://github.com/flutter/flutter/issues/27679

**Comment by spydon** [comment]
I have the same problem, this is the output of my `flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/lukasklingsbo/bin/flutter
    • Framework revision 27321ebbad (11 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/lukasklingsbo/bin/android/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/81/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/81/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/lukasklingsbo/bin/idea
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • XT1670 • ZY3226QLCD • android-arm64 • Android 9 (API 28)
```
And this is the content of my `pubspec.yaml`:
```
name: leftiverse
description: A game built around swarm optimization

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: "^1.9.1"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.16.1
  optional: ^3.0.0
  charts_flutter: ^0.8.1
  async: ^2.4.0
  cupertino_icons: ^0.1.2

flutter:
  uses-material-design: true
  assets:
   - assets/images/1.png
   - assets/images/2.png
   - assets/images/3.png
   - assets/images/4.png
   - assets/images/5.png
```
