### ISSUE TITLE
Flutter currently only builds on stable channel

### ISSUE THREAD

**Issue by kasonde** [flutter/flutter#43895]
## Steps to Reproduce

1. ... Install flutter and switch to dev channel
2. ...
3. ...

## Logs

```
Note: the configuration keeps the entry point 'io.flutter.plugin.platform.SingleViewPresentation { 
SingleViewPresentation(android.content.Context,android.view.Display,io.flutter.plugin.platform.AccessibilityEventsDelegate,io.flutter.plugin.platform.SingleViewPresentation$PresentationState,android.view.View$OnFocusChangeListener,boolean); }', but not the descriptor class 'io.flutter.plugin.platform.SingleViewPresentation$PresentationState'
Note: there were 1 references to unknown classes.                                     
You should check your configuration for typos.                                  
(http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
Note: there were 1 references to unknown class members.                               
You should check your configuration for typos.                            
Note: there were 85 unkept descriptor classes in kept class members.                  
You should consider explicitly keeping the mentioned classes                    
(using '-keep').                                                                
(http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
Note: there were 21 unresolved dynamic references to classes or interfaces.           
You should check if you need to specify additional program jars.                
(http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 13 accesses to class members by means of introspection.              
You should consider explicitly keeping the mentioned class members              
(using '-keep' or '-keepclassmembers').                                         
(http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
Thread(Tasks limiter_1): destruction                                            
Warning: there were 696 unresolved references to classes or interfaces.                  
You may need to add missing library jars or update their versions.              
If your code works fine without the missing classes, you can suppress           
the warnings with '-dontwarn' options.                                          
(http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
                                                                                
FAILURE: Build failed with an exception.                                                                                                                        
* What went wrong:                                                              
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details                                                                                                                             
* Try:                                                                          
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more 
log output. Run with --scan to get full insights.
                                                                                
* Get more help at https://help.gradle.org                                                                                                                      
BUILD FAILED in 5m 22s                                                          
Running Gradle task 'assembleRelease'...                                        
Running Gradle task 'assembleRelease'... Done                     
322.7s (!)
Gradle task assembleRelease failed with exit code 1
```

```
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.6 18G95, locale
    en-ZM)
    • Flutter version 1.10.14 at /Users/Richard/flutter
    • Framework revision 1946fc4da0 (3 weeks ago), 2019-10-07
      15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK 
    version 29.0.2)
    • Android SDK at /Users/richard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for
      native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/richard/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 •
      Android 7.0 (API 24) (emulator)

• No issues found!
```

**Comment by kasonde** [comment]
I've just reviewed your comment. I'm not using proguard for this particular app.

**Comment by liyuqian** [comment]
CC @blasten who might have more insights about this issue.

**Comment by blasten** [comment]
@kasonde what plugins and versions are you using?

**Comment by kasonde** [comment]
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter:
  geolocator:
  dio:
  scoped_model:
  shared_preferences:
  http:
  url_launcher:
  android_intent:
  flutter_rating:
  smooth_star_rating:
  intl:
  share:
  image_picker:
  device_info:
  flutter_signin_button:
  country_code_picker:
  pin_entry_text_field:
  flutter_webview_plugin: ^0.3.8
  flutter_advanced_networkimage: 0.5.0
  flutter_image_compress:
  path_provider:
  rxdart:
  google_sign_in:
  graphql_flutter:
  memoize:
  xml2json:
  exif:
  native_device_orientation:
  firebase_core:
  firebase_messaging:
  firebase_analytics:
  flutter_svg:
  charts_flutter:
  cached_network_image:
  webview_flutter:
  carousel_slider:
  sentry:
```
