### ISSUE TITLE
Flutter Web - Failed to decode downloaded font: <url>

### ISSUE THREAD

**Issue by zeromaro** [flutter/flutter#43925]
Hello,

I've deployed my flutter web app with custom fonts. I opened my console and saw several warnings with different fonts. 
`Failed to decode downloaded font: https://domainname.com/assets/assets/fonts/Montserrat-Black.ttf`.

I have my fonts set-up as follows:
```
-projectName
--assets
---fonts
----Montserrat-Black.ttf
```

and

```
-projectName
--web
---assets
----fonts
-----Montserrat-Black.ttf
```

For the latter, I don't remember the exact reason, but there was some issue, that I found out if I put them into web - it worked.

`pubspec.yaml`
```
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
```

`flutter doctor`
```
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.15 19A602, locale en-HK)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (3 available)

• No issues found!
```

Live link to test - https://rentmi.co/company/#/

**Comment by jonahwilliams** [comment]
Unfortunately our last dev release was a long-time ago, since then there have been many fixes to the web tooling master. I would recommend 1) removing the assets under web/ and 2) updating to master.

If it still doesn't work, please update the issue with whatever that error is instead.

**Comment by zeromaro** [comment]
Deleted everything from web, updated branch to master.
`flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.361, on Mac OS X 10.15 19A602, locale en-HK)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (3 available)

• No issues found!
```

Exact same issues still.

**Comment by jonahwilliams** [comment]
> Exact same issues still.

Is the link you've posted updated too?

**Comment by zeromaro** [comment]
Yes, I've updated it with latest changes.

**Comment by jonahwilliams** [comment]
Thank you!

Adding @yjbanov and @hterkelsen to take a look

**Comment by hterkelsen** [comment]
Something is going wrong with loading the font over the network...

This works when I run it from the console:

```javascript
window.fetch('assets/assets/fonts/Montserrat-Black.ttf')
```

and returns a Promise that completes to a readable byte stream.

However, when I try this:

```javascript
var fontface = new FontFace('Montserrat', 'url(assets/assets/fonts/Montserrat-Black.ttf)')
fontface.load()
```

I see this:
```
Uncaught (in promise) DOMException: A network error occurred.
```

So something odd is happening with how `Fontface.load()` is loading the fonts over the network. I'll investigate further.

**Comment by hterkelsen** [comment]
Actually, it seems like the server is returning a 0-byte response when I try to fetch the font:

![zero-length-font](https://user-images.githubusercontent.com/1961493/67994263-8f3fca00-fc01-11e9-9e32-de87c01f5eca.png)

Can you double-check your server?

**Comment by zeromaro** [comment]
Thank you for your response!

How can I check that? You mean fonts doesn't exist between my files?
I've tried raw entering `https://rentmi.co/company/assets/assets/fonts/Montserrat-BlackItalic.ttf` - it downloads the font.  Furthermore, checking source with DevConsole shows it also exists.
![image](https://user-images.githubusercontent.com/12739071/68006667-04eb7a80-fc82-11e9-983d-8868b7e82e5e.png)

**Comment by hterkelsen** [comment]
I just entered `https://rentmi.co/company/assets/assets/fonts/Montserrat-BlackItalic.ttf` into Chrome and it downloaded a file, but it was 0-bytes.

**Comment by zeromaro** [comment]
.... sh1t. You are right. I need to figure out what the hell happened. Thanks @hterkelsen 
![image](https://user-images.githubusercontent.com/12739071/68051509-3733c100-fcf0-11e9-8155-2f28160c8ff1.png)

**Comment by zeromaro** [comment]
Yes, I have downloaded new fonts and it worked. If anyone will be browsing this, font set-up as follows:
```
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 200
```
And font path is
```
-projectName
--assets
---fonts
----Montserrat-..
```

Thank you guys for pointing to the problem! Cheers
