### ISSUE TITLE
Runner.app size is about 400mb. How to reduce it?

### ISSUE THREAD

**Issue by Kastrcn** [flutter/flutter#44072]
Runner.app size is about 400mb. How to reduce it?

**pubspec.yaml** using
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  url_launcher: ^5.1.4
  share: ^0.6.2+1
  dio: ^3.0.3
  fluttertoast: ^3.1.3
  device_info: ^0.4.0+3   
  package_info: ^0.4.0+6  
  shared_preferences: ^0.5.3+4
  webview_flutter: ^0.3.14+1
  sqfentity: ^1.2.0+6
  sqfentity_gen: ^1.1.0+4
  provider: ^3.1.0+1
  cached_network_image: ^1.1.2+1
```
`$  flutter --version`
Flutter 1.10.7-pre.78 • channel master • https://github.com/flutter/flutter.git
Framework • revision 839fdbd2ed (5 weeks ago) • 2019-09-29 21:32:06 -0700
Engine • revision 5b952f286f
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 6ff8d2199d)
![image](https://user-images.githubusercontent.com/19508899/68088841-dfd35380-fe9d-11e9-96f0-3953cb78035b.png)
![image](https://user-images.githubusercontent.com/19508899/68088845-f11c6000-fe9d-11e9-91f6-02ef8d679170.png)
