### ISSUE TITLE
ITMS-90809: Deprecated API Usage - warning only for one flavor

### ISSUE THREAD

**Issue by furaiev** [flutter/flutter#44175]
I have 1 app in 2 variants (full and cut) that have different designs.
The difference between variants are:
- assets
- GoogleService-Info.plist
- provision profiles

The 1st variant Apple releases without any warnings when the 2nd one returns warning "ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs ."

So, pods are the same, flutter packages are the same, also I've compare an XCode build logs - they are identical. In GoogleService-Info.plist are different only id/name fields.

Could you please advice what can I check to find the reason of the warning?

## `flutter doctor -v` 

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale ru-UA)
    • Flutter version 1.9.1+hotfix.6 at /Users/admin/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by iapicca** [comment]
Hi @furaiev 
would be helpful to have more details about your app;
could you please provide  your `pubspec.yaml`.
Given the presence of  `GoogleService-Info.plist ` in description you provided
I suspect the issue to be related to a FlutterFire plugin. 
Thank you

**Comment by furaiev** [comment]
@iapicca thank you,
I also thought that the reason is FlutterFire, but why it is an issue only in one case... I should be an issue in both cases, shouldn't it?

**pubspec.yaml**
```
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.13.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_messaging: ^5.1.6
  flutter_xlider: ^2.5.2
  amazon_cognito_identity_dart: ^0.0.22
  built_value: ^6.6.0
  built_collection: ^4.2.2
  kiwi: ^0.1.0
  modal_progress_hud: ^0.1.3
  graphql_flutter: ^1.0.0
  shared_preferences: ^0.5.3+1
  youtube_player_flutter: 5.2.0+1
  pull_to_refresh: ^1.4.5
  carousel_slider: ^1.3.0
  outline_material_icons: ^0.1.1
  cached_network_image: ^1.0.0
  country_code_picker: ^1.1.7
  flare_flutter: ^1.5.5
  firebase_dynamic_links: ^0.5.0+1
  uni_links: ^0.2.0
  sentry: ^2.3.1
  firebase_crashlytics: ^0.1.0+3
  webview_flutter: ^0.3.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.0
  built_value_generator: ^6.6.0
  mockito: ^4.1.0
```
**GoogleService-Info.plist**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CLIENT_ID</key>
	<string>*****</string>
	<key>REVERSED_CLIENT_ID</key>
	<string>*****</string>
	<key>API_KEY</key>
	<string>*****</string>
	<key>GCM_SENDER_ID</key>
	<string>*****</string>
	<key>PLIST_VERSION</key>
	<string>1</string>
	<key>BUNDLE_ID</key>
	<string>com.*****</string>
	<key>PROJECT_ID</key>
	<string>*****</string>
	<key>STORAGE_BUCKET</key>
	<string>*****</string>
	<key>IS_ADS_ENABLED</key>
	<false></false>
	<key>IS_ANALYTICS_ENABLED</key>
	<false></false>
	<key>IS_APPINVITE_ENABLED</key>
	<true></true>
	<key>IS_GCM_ENABLED</key>
	<true></true>
	<key>IS_SIGNIN_ENABLED</key>
	<true></true>
	<key>GOOGLE_APP_ID</key>
	<string>*****</string>
	<key>DATABASE_URL</key>
	<string>*****</string>
</dict>
</plist>
```
