### ISSUE TITLE
connectivity-0.4 ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#44580]
When I compile I see these notes on the console screen

```console
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.5+3\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.

```

pubspec.yaml
```yaml
name: appjazz
description: Aplicativo do Jazz e Blues
version: 8.0.0+8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  path_provider: ^1.4.0
  sqflite: ^1.1.7+2
  connectivity: ^0.4.5+3
  url_launcher: ^5.2.5 
  cloud_firestore: ^0.12.10
  firebase_auth: ^0.14.0+8
  google_sign_in: ^4.0.11
  firebase_database: ^3.0.9
  rxdart: ^0.22.6  
  webview_flutter: ^0.3.15+1
  auto_size_text: ^2.1.0 
  latlong: ^0.6.1
  queries: ^0.1.12
  firebase_analytics: ^5.0.6
  shared_preferences: ^0.5.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.7


flutter:
 
  uses-material-design: true
  
  assets:
    - assets/logoJazz.png
    - assets/bakground.jpg   
    - assets/fundo1.jpg
    - assets/fundo2.jpg
    - assets/fundo3.jpg     
    - assets/userAvatar.png
    - assets/logo-pmro-2018-cinza.png
    - assets/pmro2018-logo.png
    - assets/termos.txt
    - assets/sobreHeader.jpg
    - assets/backgroundMenu.png
    - assets/wood.jpeg
    - assets/praia.jpeg
    - assets/praia2.jpeg
    - assets/logoSVG.svg

  fonts:
     - family: Big Noodle Titling
       fonts:
         - asset: fonts/big_noodle_titling.ttf
     - family: GlosaDisplayW01-Bold
       fonts:
         - asset: fonts/glosa_display_w01_bold.ttf
     - family: BakerieSmoothCondensedMedium
       fonts:
         - asset: fonts/BakerieSmoothCondensed-Medium.otf
     - family: BakerieSmoothBold
       fonts:
         - asset: fonts/BakerieSmooth-Bold.otf
     - family: iconsmind
       fonts:
         - asset: fonts/iconsmind.ttf
```
         

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [versÃ£o 10.0.18362.418], locale pt-BR)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.39.2)
[√] Connected device (1 available)
```
