### ISSUE TITLE
[BUG] No images on iOS (real device) after upgrade (master channel) !!

### ISSUE THREAD

**Issue by mahmoudrabie** [flutter/flutter#45032]
Dear Flutter Team,

I am using Flutter **master** channel. After the last upgrade all assets images are not appearing any more when testing my flutter app on iOS real device. They were working perfectly before upgrade. 
Regarding android real device, it is running fine. The problem only on iOS of real device (iPhone 7)

Here is the output of **flutter doctor --verbose**

`flutter doctor --verbose`

> Downloading android-arm-profile/darwin-x64 tools...                 1.5s
> Downloading android-arm-release/darwin-x64 tools...                 1.5s
> Downloading android-arm64-profile/darwin-x64 tools...               1.5s
> Downloading android-arm64-release/darwin-x64 tools...               1.4s
> Downloading android-x86 tools...                                    5.4s
> Downloading android-x64 tools...                                    5.1s
> Downloading android-arm tools...                                    3.0s
> Downloading android-arm-profile tools...                            2.0s
> Downloading android-arm-release tools...                            1.8s
> Downloading android-arm64 tools...                                  2.9s
> Downloading android-arm64-profile tools...                          1.9s
> Downloading android-arm64-release tools...                          1.9s
> Downloading package sky_engine...                                   1.2s
> Downloading common tools...                                         2.9s
> Downloading common tools...                                         3.0s
> Downloading darwin-x64 tools...                                     9.9s
> [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-SA)
>     • Flutter version 1.9.1+hotfix.6 at /Users/mahmoudrabie/MyMobileDev/flutter
>     • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/mahmoudrabie/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_HOME = /Users/mahmoudrabie/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2.1, Build version 11B53
>     • CocoaPods version 1.6.2
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /Users/mahmoudrabie/Library/Application
flutter doctor --verbose
> [✓] Flutter (Channel master, v1.12.3-pre.43, on Mac OS X 10.14.6 18G103, locale en-SA)
>     • Flutter version 1.12.3-pre.43 at /Users/mahmoudrabie/MyMobileDev/flutter
>     • Framework revision 35043cbbe3 (2 hours ago), 2019-11-15 23:52:17 -0500
>     • Engine revision 59b5a0cf76
>     • Dart version 2.7.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/mahmoudrabie/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_HOME = /Users/mahmoudrabie/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2.1, Build version 11B53
>     • CocoaPods version 1.6.2
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /Users/mahmoudrabie/Library/Application
>       Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android Studio.app/Contents
>     • Flutter plugin version 38.2.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [✓] VS Code (version 1.40.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.6.0
> 
> [✓] Connected device (2 available)
>     • SM J600F • 5200e04dee5885d1                         • android-arm • Android 9 (API 28)
>     • MMSS     • 40238a9f36e8911c5c875e1403ed4d3e125071d0 • ios         • iOS 13.1.3
> 
> • No issues found!

I would appreciate your help

Regards
Mahmoud

**Comment by yuanjiong** [comment]
I have the same issue after upgrade,no just pictures, but other ui.

**Comment by yuanjiong** [comment]
I have found my reason. It is because a third-party plug-in "flutter_screenutil" was used incorrectly, which caused the image width and height to be set to 0. It is normal after I fixed it, I hope it can help you

**Comment by mahmoudrabie** [comment]
Thanks a lot for your feedback.

Here is the dependencies section of my **pubspec.yaml**

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  random_pk: any
  shimmer: ^0.0.6
  flutter_slidable: ^0.4.9
  flutter_rating: ^0.0.2
  flutter_auth_buttons: ^0.5.0
  firebase_core: ^0.4.1+3
  google_sign_in: ^4.0.11
  firebase_auth: ^0.14.0+8
  #firebase_crashlytics: ^0.1.1+2
  firebase_dynamic_links: ^0.5.0
  cloud_firestore: ^0.12.9
  flutter_facebook_login: ^2.0.1
  carousel_slider: ^1.3.0
  provider: ^2.0.1+1
  libphonenumber: ^1.0.0
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+2
  cloud_functions: ^0.4.1
  grouped_buttons: ^1.0.4
  get_it: ^3.0.0+1
  transparent_image: ^1.0.0
  flutter_google_places: ^0.2.3
  google_maps_webservice: ^0.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"
```

Any suggestions are more than welcome

Regards
Mahmoud
