### ISSUE TITLE
overlay below a widget with an overlay image "The application may be doing too much work on its main thread."

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#45409]
Is there any better way to overlay below a widget with an overlay image Flutter.

The designer gave me these images for me to develop an APP in Flutter.

![Iphone - Home – 8](https://user-images.githubusercontent.com/12227024/69450340-b0e12c80-0d3b-11ea-8851-0d791de1e121.png)

**My current code is this.**

```dart
class HomePage extends StatefulWidget {
  HomePage({Key key}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return new HomePageState();
  }
}

class HomePageState extends State<HomePage> {
  BuildContext _ctx;
  final _scaffoldKey = new GlobalKey<ScaffoldState>();
  bool _loading = false;
  var apiRest = new ApiService();
  Size screenSize;

  @override
  void initState() {
    super.initState();
    initHomePageState();
  }

  initHomePageState() async {
    print("initHomePageState:");
  }

  @override
  Widget build(BuildContext context) {
    _ctx = context;
    return Scaffold(
      //appBar: AppBar(),
      key: _scaffoldKey,
      //backgroundColor: AppStyle.backgroundDark, //#3b4455
      body: Stack(
        children: _buildList(context),
      ),
      drawer: MenuPrincipal(),
    );
  }

  List<Widget> _buildList(BuildContext context) {
    final mediaQueryData = MediaQuery.of(context);
    screenSize = mediaQueryData.size;

    var listview = SingleChildScrollView(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisSize: MainAxisSize.max,
        children: <Widget>[
          //logo
          Container(
            width: double.infinity,
            height: screenSize.height / 3.7,
            child: Padding(
              padding: EdgeInsets.fromLTRB(0, 25, 0, 10),
              child: Image.asset('assets/logo.png'),
            ),
          ),
          //menu
          Container(
            width: screenSize.width,
            height: screenSize.height -20,
            child: Stack(
              children: <Widget>[
                Positioned(
                  left: (screenSize.width - 300) / 2,
                  top: 0,
                  child: Container(
                    width: 300,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(10),
                      boxShadow: [
                        BoxShadow(color: Color.fromRGBO(128,251, 255, 0.52), blurRadius: 10),
                      ],
                    ),
                    height: 500, //vertival=360 horizontal=240,
                    child: ClipRRect(
                      borderRadius: BorderRadius.all(Radius.circular(10)),
                      child: Container(
                        //padding: EdgeInsets.all(10),
                        color: Colors.white,
                        child: Wrap(
                          children: <Widget>[
                            tile(route: "/agendas", title: "PROGRAMAÇÃO", iconUnicode: "\uEB0C"),
                            tile(route: "/atracoes", title: "ARTISTAS", iconUnicode: "\uE851"),
                            tile(route: "/hospedagem", title: "ONDE FICAR", iconUnicode: "\uE6FA"),
                            tile(route: "/alimentacao", title: "ONDE COMER", iconUnicode: "\uEB84"),
                            tile(route: "/noticia", title: "NOTÍCIAS", iconUnicode: "\ueafe"),
                            tile(route: "/live", title: "LIVE", iconUnicode: "\uedd1"),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),

                //wave
                Positioned(
                  bottom: 0,
                  child: Container(//color: Colors.red,
                    width: screenSize.width,
                    //color: Colors.amberAccent,
                    height: 220,
                    child: Padding(
                      padding: EdgeInsets.fromLTRB(0, 0, 0, 0),
                      child: Image.asset(
                        'assets/wave-bottom.png',
                        fit: BoxFit.fill,
                      ),
                    ),
                  ),
                ),

                //logo
                Positioned(
                  left: (screenSize.width-screenSize.width/2)/2,
                  bottom: 30,
                  child: Container(
                    width: screenSize.width/2,
                    child: Padding(
                      padding: EdgeInsets.fromLTRB(0, 0, 0, 0),
                      child: Image.asset(
                        'assets/logo-pmro-branco.png',
                        fit: BoxFit.fitHeight,
                      ),
                    ),
                  ),
                ),


              ],
            ),
          )

          //
        ],
      ),
    );

    var l = new List<Widget>();

    //background page
    l.add(
      Container(
        width: double.infinity,
        height: double.infinity,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage('assets/background.png'),
            fit: BoxFit.cover,
          ),
        ),
      ),
    );

    l.add(listview);

    //botão menu
    l.add(Positioned(
        left: 10,
        top: 25,
        child: Container(
          decoration: BoxDecoration(
            color: Color(0xAA26B4D6), //Colors.lightBlue[100]
            shape: BoxShape.circle,
          ),
          child: IconButton(
            icon: Icon(
              Icons.menu,
              color: Colors.white,
            ),
            onPressed: () => _scaffoldKey.currentState.openDrawer(),
          ),
        )));

    if (_loading) {
      l.add(modalProgressIndicator());
    }
    return l;
  }

  tile({Function onTap, String title, String route, String iconUnicode = "\uEB0C"}) {
    return InkWell(
      onTap: onTap != null
          ? onTap
          : () {
              if (route != null) {
                Navigator.of(context).pushNamed(route);
              }
            },
      child: Container(
        width: 150,
        height: 120,
        decoration: BoxDecoration(
          border: Border.all(color: Color.fromRGBO(15, 60, 225, 0.11), width: 0.5),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Padding(
              padding: EdgeInsets.fromLTRB(5, 10, 5, 10),
              child: Stack(
                children: <Widget>[
                  Text(
                    iconUnicode,
                    style: TextStyle(
                      fontSize: 40,
                      fontFamily: "iconsmind",
                      color: Color(0xFF26B4D6),
                    ),
                  )
                ],
              ),
            ),
            Text(
              title,
              style: TextStyle(fontSize: 15, fontFamily: 'Roboto', color: Color(0xFF26B4D6), fontWeight: FontWeight.bold),
            ),
          ],
        ),
      ),
    );
  }
}
```

![image](https://user-images.githubusercontent.com/12227024/69451666-b1c78d80-0d3e-11ea-909c-d6ec5dcdc172.png)

The way I did it does not seem to have been very optimized, it seems to be generating overhead on the main thread UI, and it is not responsive, because when I rotate the screen everything is damaged

![6hSwE](https://user-images.githubusercontent.com/12227024/69451679-b5f3ab00-0d3e-11ea-9d45-f692ba378c3a.png)

https://www.youtube.com/watch?v=EMlWUs15VsU

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [versÃ£o 10.0.18362.476], locale pt-BR)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.39.2)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

```

pubspec.yaml
```yaml
name: appsescverao
description: Aplicativo do Sesc Verão Rio das Ostras

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  path_provider: ^1.4.0
  flutter_advanced_networkimage: ^0.5.0
  sqflite: ^1.1.7+2
  connectivity: ^0.4.5+3
  url_launcher: ^5.2.5
  cloud_firestore: ^0.12.10
  firebase_auth: ^0.14.0+8
  google_sign_in: ^4.0.11
  firebase_database: ^3.0.9
  rxdart: ^0.22.6
  webview_flutter: ^0.3.15+1
  auto_size_text: ^2.1.0
  flutter_map: ^0.7.3
  latlong: ^0.6.1
  queries: ^0.1.12
  firebase_analytics: ^5.0.6
  shared_preferences: ^0.5.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.7

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/background.png
    - assets/background2.png
    - assets/background3.png
    - assets/user-avatar.png
    - assets/logo-pmro-cinza.png
    - assets/logo-pmro-branco.png
    - assets/wave-bottom.png
    - assets/wave-top.png

  fonts:
    - family: Big Noodle Titling
      fonts:
        - asset: fonts/big_noodle_titling.ttf
    - family: GlosaDisplayW01-Bold
      fonts:
        - asset: fonts/glosa_display_w01_bold.ttf
    - family: BakerieSmoothCondensedMedium
      fonts:
        - asset: fonts/BakerieSmoothCondensed-Medium.otf
    - family: BakerieSmoothBold
      fonts:
        - asset: fonts/BakerieSmooth-Bold.otf
    - family: iconsmind
      fonts:
        - asset: fonts/iconsmind.ttf

```
