### ISSUE TITLE
Version conflicts with flutter_driver and flutter_form_builder

### ISSUE THREAD

**Issue by shashikantshaale** [flutter/flutter#45829]
pubspec.yaml

```
dependencies:
  flutter_form_builder: ^3.6.1
dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
```

console logs:
```
Because every version of flutter_driver from sdk depends on intl 0.15.8 and flutter_form_builder 3.6.1 depends on intl ^0.16.0, flutter_driver from sdk is incompatible with flutter_form_builder 3.6.1.

And because no versions of flutter_form_builder match >3.6.1 <4.0.0, flutter_driver from sdk is incompatible with flutter_form_builder ^3.6.1.

So, because shaale depends on both flutter_form_builder ^3.6.1 and flutter_driver any from sdk, version solving failed.
pub get failed (1)
Process finished with exit code 1
```
