### ISSUE TITLE
[firebase_auth_web] Support verifyPhoneNumber

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#46021]
For the phone verification workflow on Firebase web, you must show a reCaptcha to prevent phone numbers from being spammed. In order to do this, we need for the web plugin to create a reCaptcha `HtmlElementView` widget that is displayed in the app.

This change will require modifying the `package:firebase_auth` API, probably adding an optional parameter to `verifyPhone` for a callback to return a `Widget` for the verifier.

**Comment by ian-pinto-ketto** [comment]
Is there a workaround available till this issue is resolved? Has anyone got firebase phone auth to work for a web app?

**Comment by phamnhuvu-dev** [comment]
@ian-pinto-ketto I use this package to implement firebase phone auth for flutter web https://pub.dev/packages/firebase for now

**Comment by phamnhuvu-dev** [comment]
I am working on a tight deadline. So can't complete the checklist soon of my PR.
If you need to phone auth for your flutter web. Please add following code to your project:
```yaml
dependencies:
  firebase_auth:
    git:
      url: git@github.com:phamnhuvu-dev/flutterfire.git
      path: packages/firebase_auth/firebase_auth

dependency_overrides:
  firebase_auth_web:
    git:
      url: git@github.com:phamnhuvu-dev/flutterfire.git
      path: packages/firebase_auth/firebase_auth_web
```

**Comment by Gintasz** [comment]
I also cheer for phone auth to be supported in firebase_auth web

**Comment by nipunasudha** [comment]
> I am working on a tight deadline. So can't complete the checklist soon of my PR.
> If you need to phone auth for your flutter web. Please add following code to your project:
> 
> ```yaml
> dependency_overrides:
>   firebase_auth_web:
>     git:
>       url: git@github.com:phamnhuvu-dev/flutterfire.git
>       path: packages/firebase_auth/firebase_auth_web
> ```

I am forever grateful for this one. I was stuck & helpless with my deadlines.

**Comment by gsusI** [comment]
> I am working on a tight deadline. So can't complete the checklist soon of my PR.
> If you need to phone auth for your flutter web. Please add following code to your project:
> 
> ```yaml
> dependency_overrides:
>   firebase_auth_web:
>     git:
>       url: git@github.com:phamnhuvu-dev/flutterfire.git
>       path: packages/firebase_auth/firebase_auth_web
> ```

Thanks for this, for some reason image captcha doesn't work, I get a "Try again" error message. Audio captcha works perfectly fine. 

My pubspec:

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.0+9

  firebase_auth: ^0.16.0
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.13.5
  provider: ^4.0.5
  fluttertoast: ^4.0.1
  country_pickers: ^1.2.1
  flutter_form_builder: ^3.8.3
  intl_phone_number_input: ^0.4.0+2
  cupertino_icons: ^0.1.3

**Comment by stuartkuentzel** [comment]
@gsusI I'm having the same issue, I keep getting "Try again" issue using the fix posted by @phamnhuvu-dev . After maybe a minute or two of trying again and failing, it sometimes works and sometimes blocks. Could you kindly point me on docs how to use a different recaptcha?

**Comment by phamnhuvu-dev** [comment]
@gsusI @stuartkuentzel Our front-end is having the same issue when implementing on the native web not flutter. You should try on the release build, deploy to host and aware of captcha for **a car** and **cars**. I will plan to finish that PR after our new version release in this week

**Comment by formatCvt** [comment]
@phamnhuvu-dev any news?

**Comment by GyuriMajercsik** [comment]
> I am working on a tight deadline. So can't complete the checklist soon of my PR.
> If you need to phone auth for your flutter web. Please add following code to your project:
> 
> ```yaml
> dependency_overrides:
>   firebase_auth_web:
>     git:
>       url: git@github.com:phamnhuvu-dev/flutterfire.git
>       path: packages/firebase_auth/firebase_auth_web
> ```

Thank you for the quick solution ! I found some issues and fixed (will just drop the code below): 
  * the Captcha logo on bottom-right of the screen doesn't disappear after successful login 
  * the Captcha fails to reappear after clicking outside of it and retrying the flow

Here are my changes: 

 ```
 @override
  Future<void> verifyPhoneNumber(String app,
      {String phoneNumber,
      Duration timeout,
      int forceResendingToken,
      PhoneVerificationCompleted verificationCompleted,
      PhoneVerificationFailed verificationFailed,
      PhoneCodeSent codeSent,
      PhoneCodeAutoRetrievalTimeout codeAutoRetrievalTimeout}) async {
    var element = window.document.getElementById("recaptcha-container");

    if (element == null) {
      element = DivElement()..id = "recaptcha-container";
      window.document.documentElement.children
          .add(element);
    } else {
      element.remove(); // we already found one element, we need to recreate it
      element = DivElement()..id = "recaptcha-container";
      window.document.documentElement.children
          .add(element);
    }
    firebase.RecaptchaVerifier verifier =
        firebase.RecaptchaVerifier('recaptcha-container', {
      'size': 'invisible',
      'callback': (resp) {
        print('reCAPTCHA solved, allow signInWithPhoneNumber.');
        element.remove();
      },
      'expired-callback': () {
        print('failed');
        verificationFailed(
            AuthException('expired-callback', 'reCAPTCHA expired'));
      }
    });
    verifier.render();
    firebase.ConfirmationResult _confirmationResult;
    try {
      _confirmationResult =
          await firebase.auth().signInWithPhoneNumber(phoneNumber, verifier);
    } on AuthException catch (e) {
      verificationFailed(e);
    } catch (error) {
      verificationFailed(AuthException('verificationFailed', error.toString()));
    }
    if (_confirmationResult != null) {
      codeSent(_confirmationResult.verificationId);
    }
  }
```

**Comment by ianvillamia** [comment]
Hi! new here can someone tell me what I'm doing wrong? I've got this error in using this
I just pasted it in the pubspec.yaml
```
dependency_overrides:
  firebase_auth_web:
    git:
      url: git@github.com:phamnhuvu-dev/flutterfire.git
      path: packages/firebase_auth/firebase_auth_web
```
here's the error
![image](https://user-images.githubusercontent.com/25190455/85709618-03daf200-b718-11ea-8695-4dc7d77d1486.png)

**Comment by GyuriMajercsik** [comment]
> Hi! new here can someone tell me what I'm doing wrong? I've got this error in using this
> I just pasted it in the pubspec.yaml
> 
> ```
> dependency_overrides:
>   firebase_auth_web:
>     git:
>       url: git@github.com:phamnhuvu-dev/flutterfire.git
>       path: packages/firebase_auth/firebase_auth_web
> ```
> 
> here's the error
> ![image](https://user-images.githubusercontent.com/25190455/85709618-03daf200-b718-11ea-8695-4dc7d77d1486.png)

Change the link to: https://github.com/phamnhuvu-dev/flutterfire.git

Use the following dependency: 

```
dependency_overrides:
  firebase_auth_web:
    git:
      url: https://github.com/phamnhuvu-dev/flutterfire.git
      path: packages/firebase_auth/firebase_auth_web
```

**Comment by ianvillamia** [comment]
> https://github.com/phamnhuvu-dev/flutterfire.git

Thank You very much!!

**Comment by GAyan17** [comment]
Is this dependency override supports production ready? I'm trying to deploy a Flutter Web, and want to have Firebase Phone Authentication, but it doesn't working on non whitelisted numbers.

**Comment by ValentinTaleb** [comment]
Thanks for the fork, it works fine :)

Do somebody knows if that will be merged in the official repository anytime soon?

**Comment by monkeyMax-SVG** [comment]
In my case, I added firebase_auth_web: ^0.1.3+1 with firebase_auth: ^0.15.4 but it has same issue.

`Error: UnimplementedError: verifyPhoneNumber
    at Object.throw_ [as throw] (http://localhost:57224/dart_sdk.js:4463:11)
    at verifyPhoneNumber (http://localhost:57224/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:277:19)
    at verifyPhoneNumber.next (<anonymous>)
    at runBody (http://localhost:57224/dart_sdk.js:37195:34)
    at Object._async [as async] (http://localhost:57224/dart_sdk.js:37226:7)
    at firebase_auth_web.FirebaseAuthWeb.new.verifyPhoneNumber (http://localhost:57224/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:276:20)
    at firebase_auth.FirebaseAuth.__.verifyPhoneNumber (http://localhost:57224/packages/firebase_auth/firebase_auth.dart.lib.js:342:77)
    at LoginScreen._LoginScreenState.new._verifyPhoneNumber (http://localhost:57224/packages/mmmhelper/ui/SignUpScreen.dart.lib.js:91711:39)
    at _verifyPhoneNumber.next (<anonymous>)
    at runBody (http://localhost:57224/dart_sdk.js:37195:34)
    at Object._async [as async] (http://localhost:57224/dart_sdk.js:37226:7)
    at LoginScreen._LoginScreenState.new.[_verifyPhoneNumber] (http://localhost:57224/packages/mmmhelper/ui/SignUpScreen.dart.lib.js:91673:20)
    at LoginScreen._LoginScreenState.new.<anonymous> (http://localhost:57224/packages/mmmhelper/ui/SignUpScreen.dart.lib.js:91830:61)
    at Generator.next (<anonymous>)
    at http://localhost:57224/dart_sdk.js:37175:33
    at _RootZone.runUnary (http://localhost:57224/dart_sdk.js:37029:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:57224/dart_sdk.js:32116:29)
    at handleValueCallback (http://localhost:57224/dart_sdk.js:32663:49)
    at Function._propagateToListeners (http://localhost:57224/dart_sdk.js:32701:17)
    at _Future.new.[_completeWithValue] (http://localhost:57224/dart_sdk.js:32544:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57224/dart_sdk.js:32566:35)
    at Object._microtaskLoop (http://localhost:57224/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:57224/dart_sdk.js:37296:13)
    at http://localhost:57224/dart_sdk.js:32918:9[2020-07-15T04:32:46.532Z]  @firebase/firestore:`

Please help me.

**Comment by chertov** [comment]
Please change the priority of the issue. The phone number auth is a killer-feature of firebase API. This is a very important authentication method.

**Comment by cyanglaz** [comment]
@kroikie Should we move this to the flutterfire repo?

**Comment by kroikie** [comment]
@cyanglaz Yes this should be in flutterfire repo.

**Comment by phamnhuvu-dev** [comment]
I see it implemented add this commit https://github.com/FirebaseExtended/flutterfire/tree/4a05ceba74c805bc5528137d40c75865cd21d687

It works in my project.
Please use this ref
```yml
dependency_overrides:
  firebase_auth:
    git: 
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_auth/firebase_auth
      ref: a17e36768abc779085dea0079e98e2a2e9c75c0d
  
  firebase_auth_web:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_auth/firebase_auth_web
      ref: a17e36768abc779085dea0079e98e2a2e9c75c0d
  
  firebase_auth_platform_interface:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_auth/firebase_auth_platform_interface
      ref: a17e36768abc779085dea0079e98e2a2e9c75c0d     
```
