### ISSUE TITLE
[video_player] How to open ios plugin at Xcode?

### ISSUE THREAD

**Issue by otopba** [flutter/flutter#46551]
I want make some changes in plugin, but I can't open it at Xcode. There are no project files in plugins. 
How to open ios plugin at Xcode?

Maybe you should add this information to contributing guide

Thank you

**Comment by iapicca** [comment]
Hi @otopba 
you can fork the [repo](https://github.com/flutter/plugins/tree/master/packages/video_player/video_player)
apply the changes you have inn mind and then import it

```
dependencies:
  video_player: any

dependency_overrides:
  video_player:
    git:
      url: https://github.com/<YOUR FORK>
      path: packages/video_player
```

does this solution answer you question?
thank you
