### ISSUE TITLE
Allow plugins not to support macOS

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#46618]
With the federated model, adding a macos platform to a frontend plugin pubspec.yaml results in a failure. This [line](https://github.com/flutter/flutter/blob/fc05c3738ca64f65484527d7a9a824a0f0bc5706/packages/flutter_tools/templates/cocoapods/Podfile-macos#L38) detects there's a macos plugin, and expects a `macos`. The work around solution is to add a macos folder with a no-op podspec, just as we are doing for [iOS](https://github.com/flutter/flutter/issues/39659) on macos plugins.

**Comment by franciscojma86** [comment]
This is the error I get when `flutter run -d macos` on url_launcher (WIP) 
```
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral/.symlinks/flutter/darwin-x64`
    -> Fetching podspec for `url_launcher` from `Flutter/ephemeral/.symlinks/plugins/url_launcher/macos`
    [!] No podspec found for `url_launcher` in `Flutter/ephemeral/.symlinks/plugins/url_launcher/macos`

```

**Comment by franciscojma86** [comment]
Pubspec looks like this:

```
flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.urllauncher
        pluginClass: UrlLauncherPlugin
      ios:
        pluginClass: FLTURLLauncherPlugin
      web:
        default_package: url_launcher_web
      macos:
        default_package: url_launcher_macos

```
