### ISSUE TITLE
gracefully handle when ~/.flutter is not writable

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#4674]
We should handle situations where we're not able to write to `~/.flutter`. The solution might look something like:
- disabling analytics for that run
- not displaying the large, multi-line analytics warning
- possibly showing a one line warning about being unable to write to the settings file

**Comment by Hixie** [comment]
cc @abarth since this affected Fuchsia's build recently.

**Comment by Hixie** [comment]
I'm punting this for now (few people have a read-only home directory); let me know if there's a reason this should be considered higher priority.

**Comment by ron-wolf** [comment]
> let me know if there's a reason this should be considered higher priority.

Because it brings the installer to a halt for no good reason. This is not to be expected of a library whose strengths include quality and compatibility; ignoring small and easily solved issues like these is death by a thousand cuts.

If the home directory could not be found or is not writeable, pretty much all platforms have other directories you can write to (for instance, `Library/Application Support` on macOS, or `%APPDATA%` on Windows). If this is too much to ask, then at the very least, please support [this specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for base directories. I should add that I would be glad to help implement this if given the right location in the codebase.

**Comment by rrousselGit** [comment]
I've hit this when writing a workflow file for github actions:

```yaml
on: push
name: Flutter Lint, Format, Test and build+deploy

jobs:
  test:
    name: health check
    runs-on: ubuntu-latest

    container: cirrusci/flutter:master

    steps:
      - uses: actions/checkout@v1
      - run: flutter doctor -v
      - run: flutter packages get
      - run: flutter format --set-exit-if-changed .
      - run: flutter test
```

This makes the `flutter doctor` step fail with a:

> Unhandled exception:
FileSystemException: Cannot create file, path = '/github/home/.flutter' (OS Error: Permission denied, errno = 13)
