### ISSUE TITLE
Tool crash Github template should include enabled/disabled features

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#46936]
For example, the results of flutter config (minus signing cert info)

```
Settings:
  flutter-web: true
  flutter-linux-desktop: true
  enable-macos-desktop: true
  ~~ios-signing-cert: iPhone Developer: Jonah Williams (XXXX)~~
  enable-web-incremental-compiler: false


```
