### ISSUE TITLE
Error building in release mode for android after upgrading to v1.12.13+hotfix.5 - Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints

### ISSUE THREAD

**Issue by andrewpmoore** [flutter/flutter#46976]
## Steps to Reproduce

The app built fine in previous version of flutter on the stable channel and it also works in debug mode, but if running 

`flutter run --release`

we get the error below.

I've already tried 

```
flutter clean
flutter pub cache repair
```

Here's the pubspec.yaml

```
name: fmps
description: Flutter version of MPS

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2000002
build_type: internal

#to build a release for android's play store run the below command to create the .aap
#flutter build appbundle


environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl:
  intl_translation:
  provider: ^3.0.0+1
  connectivity: ^0.4.4
  http: ^0.12.0+2
  webview_flutter: ^0.3.17   #this is now fixed in the webview, but the version of flutter needs to propogate down to "stable" for it to work
  flutter_webview_plugin: #^0.3.10  #hacky one, but work betters until fixes in the above one for the android keyboard not popping
    path: ./modified_packages/flutter_webview_plugin-0.3.10
  package_info: ^0.4.0+6
#  flutter_statusbarcolor: any
  shared_preferences: ^0.5.6
#  sqflite:     ##this is the default version
  sqflite:      ##this is the encrypted version
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: 889a156
  path:
  get_it: ^1.0.3+2
#  flutter_stetho: ^0.6.0-dev.1
  flutter_user_agent: ^1.0.1
  dotted_border: ^1.0.2
  equatable: ^0.1.5
  flutter_html: ^0.10.4
  flare_flutter: ^1.5.8
  uuid: ^2.0.2
  flutter_sidekick: ^0.1.3
  cached_network_image: ^2.0.0-rc
  image_picker: ^0.6.1+4
  validators: ^2.0.0+1
  device_info: ^0.4.0+2
  reorderables: ^0.2.12
  percent_indicator: ^2.1.1
  local_auth: ^0.6.0+1
  flutter_local_notifications: ^0.8.1
  notification_permissions: ^0.4.0
  launch_review: ^2.0.0
  video_player: ^0.10.5
  chewie: ^0.9.7
  flutter_widgets: ^0.1.5
  transformer_page_view: ^0.1.6
  android_intent: ^0.3.2
  #in_app_purchase: ^0.2.1
  #mps mod allows for changing subscription from monthly<-->yearly
  in_app_purchase: 0.2.2+4
    #path: ./modified_packages/in_app_purchase-0.2.1-mps-mod
  flutter_calendar_carousel: ^1.4.2
  url_launcher: ^5.1.2
  flutter_sequence_animation: ^3.0.1
  flutter_branch_io_plugin:
    path: ./modified_packages/flutter_branch_io_plugin-0.0.2+2
  event_bus: ^1.1.0
  audio_service: ^0.4.1
  path_provider: ^1.3.0
  #audioplayer: ^0.5.2
  rxdart: ^0.22.3
  audioplayers:
    path: ./modified_packages/audioplayers-0.13.3
  audio_player_service:
    path: ./modified_packages/audio_player_service_ios
  sliding_up_panel: ^0.3.6
  flutter_media_notification:
    path: ./modified_packages/flutter_media_notification-1.2.6
  avatar_glow: ^1.1.0
  simple_animations: ^1.3.4
  sensors: ^0.4.0+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0


dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: 0eff382dcc45322edfa94d222cadf3e28fc5a95a


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icons/launcher/launcher_ios.png"
  image_path_android: "assets/images/icons/launcher/launcher.png"
  adaptive_icon_background: "assets/images/icons/launcher/launcher_background.png"
  adaptive_icon_foreground: "assets/images/icons/launcher/launcher_foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # main asset paths, mostly set in constants.dart so they can be moved without refactoring code
  assets:
    - assets/json/
    - assets/audio/
    - assets/images/
    - assets/images/icons/
    - assets/images/module_images/
    - assets/images/series_images/
    - assets/images/icons/library/
    - assets/images/icons/form/
    - assets/animations/flare/
    - pubspec.yaml


  fonts:
    - family: Nunito
      fonts:
      - asset: assets/fonts/ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Light.ttf
        weight: 300
      - asset: assets/fonts/LightItalic.ttf
        style: italic
        weight: 300
      - asset: assets/fonts/Regular.ttf
        weight: 400
      - asset: assets/fonts/SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Bold.ttf
        weight: 700
      - asset: assets/fonts/ExtraBold.ttf
        weight: 800

```

**Target Platform:** Android
**Target OS version/browser:** Android 10
**Devices:** Pixel 4xl

## Logs

```
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not resolve com.android.support:support-annotations:25.0.0.
  Required by:
      project :
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints: 
        Dependency path 'io.flutter.plugins.inapppurchase:in_app_purchase:1.0' --> 'android.arch.lifecycle:runtime:1.1.1' --> 'com.android.support:support-annotations:26.1.0'
        Dependency path 'io.flutter.plugins.inapppurchase:in_app_purchase:1.0' --> 'android.arch.lifecycle:common:1.1.1' --> 'com.android.support:support-annotations:26.1.0'
        Dependency path 'io.flutter.plugins.inapppurchase:in_app_purchase:1.0' --> 'android.arch.lifecycle:common-java8:1.1.1' --> 'com.android.support:support-annotations:26.1.0'
        Dependency path 'io.flutter.plugins.inapppurchase:in_app_purchase:1.0' --> 'com.android.billingclient:billing:1.2' --> 'com.android.support:support-annotations:25.0.0'
        Dependency path 'io.flutter.plugins.inapppurchase:in_app_purchase:1.0' --> 'android.arch.lifecycle:runtime:1.1.1' --> 'android.arch.lifecycle:common:1.1.1' --> 'com.android.support:support-annotations:26.1.
0'
        Dependency path 'io.flutter.plugins.inapppurchase:in_app_purchase:1.0' --> 'android.arch.lifecycle:runtime:1.1.1' --> 'android.arch.core:common:1.1.1' --> 'com.android.support:support-annotations:26.1.0'
        Constraint path 'io.flutter.plugins.inapppurchase:in_app_purchase:1.0' --> 'com.android.support:support-annotations' strictly '25.0.0' because of the following reason: releaseRuntimeClasspath uses version 2
5.0.0

> Could not resolve com.android.support:support-annotations:26.1.0.
  Required by:
      project : > android.arch.lifecycle:runtime:1.1.1
      project : > android.arch.lifecycle:common:1.1.1
      project : > android.arch.lifecycle:common-java8:1.1.1
      project : > android.arch.lifecycle:runtime:1.1.1 > android.arch.core:common:1.1.1
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints

```
```
```

```
Analyzing MPS_Flutter...

   info - The value of the field '_panelController' isn't used -
          lib\ui\widgets\music_player\music_player_panel\bottom_player_panel.dart:20:19 - unused_field
   info - 'seekCompleteHandler' is deprecated and shouldn't be used -
          modified_packages\audioplayers-0.13.3\lib\audioplayers.dart:562:16 - deprecated_member_use_from_same_package
   info - 'prefer_bool_in_asserts' is a deprecated lint rule and should not be used -
          modified_packages\flutter_webview_plugin-0.3.10\analysis_options.yaml:74:5 - deprecated_lint_hint
   info - 'prefer_bool_in_asserts' is a deprecated lint rule and should not be used -
          modified_packages\flutter_webview_plugin-0.3.10\analysis_options.yaml:74:5 - deprecated_lint_hint
   info - 'super_goes_last' is a deprecated lint rule and should not be used -
          modified_packages\flutter_webview_plugin-0.3.10\analysis_options.yaml:100:5 - deprecated_lint_hint
   info - 'super_goes_last' is a deprecated lint rule and should not be used -
          modified_packages\flutter_webview_plugin-0.3.10\analysis_options.yaml:100:5 - deprecated_lint_hint
   info - Prefer typing uninitialized variables and fields -
          modified_packages\flutter_webview_plugin-0.3.10\lib\src\webview_scaffold.dart:88:7 -
          prefer_typing_uninitialized_variables
   info - Prefer typing uninitialized variables and fields -
          modified_packages\flutter_webview_plugin-0.3.10\lib\src\webview_scaffold.dart:125:9 -
          prefer_typing_uninitialized_variables

8 issues found. (ran in 38.3s)
```
```
```

PS C:\Users\andre\projects\flutter\MPS_Flutter> flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.19037.1], locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at c:\flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\andre\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\andre\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Pixel 4 XL • 98311FFBA005Z6 • android-arm64 • Android 10 (API 29)

• No issues found!
```
```
