### ISSUE TITLE
Android add-to-app build fails when using platform plugin that supports Desktop or Web

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#47055]
When building an existing app and embedding flutter, and using the latest version of the `url_launcher` plugin, the build will fail because the `url_launcher_web` and `url_launcher_macos` will get built by gradle, when building task ` assembleAndroidTest`.

```
> Task :url_launcher_web:transformClassesWithDexBuilderForDebugAndroidTest FAILED

...

> Task :url_launcher_macos:transformClassesWithDexBuilderForDebugAndroidTest FAILED

```

It's important to note the combination of using a plugin that supports multiple platforms, and building the ` assembleAndroidTest` task causes this problem. It basically prevents us from building our Debug flavors without tweaking the pubspec.yaml file of the plugin.

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/danny.valente/Library/flutter/1.12.13+hotfix.5-stable
    • Framework revision 27321ebbad (4 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by iapicca** [comment]
Hi @dannyvalentesonos 
can you please provide your `flutter run --verbose`?
Thank you

**Comment by dannyvalentesonos** [comment]
@iapicca This is an add2app scenario. We are basically building a Flutter module. Doesn't `flutter run` actually build the host app and run it? That does not work in our situation.
This bug causes the build itself to fail for existing app integration scenarios.
Please advise what `flutter run` will give and if it's needed?
Thanks.

**Comment by xster** [comment]
@blasten can you take a look?

**Comment by blasten** [comment]
I think this is already fixed. Would you mind trying again?

**Comment by dannyvalentesonos** [comment]
@blasten I still see the same build errors with the latest on the master branch.

**Comment by yjbanov** [comment]
@blasten can you please set an appropriate milestone to this issue?

**Comment by xster** [comment]
@blasten is OOO currently. @amirh may have some context too.

**Comment by amirh** [comment]
Which versions of the url_launcher packages are used? (You can check in pubspec.lock) can you try running 'flutter pub upgrade' to make sure you have the latest versions?

**Comment by dannyvalentesonos** [comment]
We are using the url_launcher 5.4.1. The issue is that the latest versions support multiple platforms. When we download the plugin and have it saved locally, changing the pubspec.yaml of the plugin like so allows the build to succeed:
```
name: url_launcher
description: Flutter plugin for launching a URL on Android and iOS. Supports
  web, phone, SMS, and email schemes.
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
version: 5.4.1

flutter:
  plugin:
    androidPackage: io.flutter.plugins.urllauncher
    iosPrefix: FLT
    pluginClass: UrlLauncherPlugin

dependencies:
  flutter:
    sdk: flutter
  url_launcher_platform_interface: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

```
