### ISSUE TITLE
SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#47222]
i'm having this problem with my app

C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferen
ces\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [versÃ£o 10.0.18362.535], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.39.2)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

```
<details>
  <summary>pubspec.yaml</summary>

```yaml
name: appsescverao
description: Aplicativo do Sesc Verão Rio das Ostras

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.0+2
  path_provider: ^1.5.1
  flutter_advanced_networkimage: ^0.6.2
  sqflite: ^1.2.0
  connectivity: ^0.4.6+1
  url_launcher: ^5.4.1
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.2
  google_sign_in: ^4.1.0
  firebase_database: ^3.1.1
  rxdart: ^0.23.1
  webview_flutter: ^0.3.18+1
  auto_size_text: ^2.1.0
  flutter_map: ^0.8.0
  latlong: ^0.6.1
  queries: ^0.1.12
  firebase_analytics: ^5.0.9
  shared_preferences: ^0.5.6
  #audioplayers: ^0.13.5
  #audio_streams: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.7

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/background.png
    - assets/background2.png
    - assets/background3.png
    - assets/user-avatar.png
    - assets/logo-pmro-cinza.png
    - assets/logo-pmro-branco.png
    - assets/wave-bottom.png
    - assets/wave-top.png
    - assets/logo2.png
    - assets/logo-branca.png

  fonts:
    - family: Big Noodle Titling
      fonts:
        - asset: fonts/big_noodle_titling.ttf
    - family: GlosaDisplayW01-Bold
      fonts:
        - asset: fonts/glosa_display_w01_bold.ttf
    - family: BakerieSmoothCondensedMedium
      fonts:
        - asset: fonts/BakerieSmoothCondensed-Medium.otf
    - family: BakerieSmoothBold
      fonts:
        - asset: fonts/BakerieSmooth-Bold.otf
    - family: iconsmind
      fonts:
        - asset: fonts/iconsmind.ttf
```

</details>

<details>
  <summary>code sample</summary>

```dart
import 'dart:async';
import 'dart:collection';
import 'dart:convert';
import 'package:flutter/material.dart';

import 'cache.dart';
import 'dart:io';
import '../util/response_list.dart';
import 'package:path_provider/path_provider.dart';
import '../util/serialization_interface.dart';
import 'package:shared_preferences/shared_preferences.dart';

class DiskCache<T> implements Cache<T> {
  final Map<Type, Function> factories; // = <Type, Function>{};
  Duration cacheValidDuration = Duration(minutes: 30);

  //DateTime lastFetchTime = DateTime.fromMillisecondsSinceEpoch(0);
  String cacheFileName;

  //RList<T> allRecords = RList<T>();
  //{@required this.factories}
  DiskCache(this.factories, [this.cacheFileName]) {
    //factories[T](item)
    if (this.cacheFileName == null) {
      cacheFileName = factories.keys.first.toString();
    }
    print(cacheFileName);
  }

  //is update the cache
  Future<bool> isShouldRefresh() async {
    var records = await _readFromDiskRecords(isFast: true);
    var lastFetchTime = await getLastFetchTime();
    return (null == records || records.isEmpty || null == lastFetchTime || lastFetchTime.isBefore(DateTime.now().subtract(cacheValidDuration)));
  }

  @override
  Future<RList<T>> getAll() async {
    return await _readFromDiskRecords();
  }

  @override
  Future<void> putAll(RList<T> objects) async {
    setLastFetchTime(DateTime.now());
    await _writeToDiskRecords(objects);
  }

  @override
  Future<void> putAllAsync(Future<RList<T>> objects) async {
    var records = await objects;
    setLastFetchTime(DateTime.now());
    await _writeToDiskRecords(records);
  }

  //parth
  Future<String> get _localPath async {
    final directory = await getApplicationDocumentsDirectory();
    return directory.path;
  }

  //file pointer
  Future<File> get _getLocalFile async {
    final path = await _localPath;
    return File('$path/$cacheFileName.json');
  }

  //write to file Records
  Future<File> _writeToDiskRecords(RList<T> records) async {
    try {
      File recordedFile;
      if (records != null) {
        var map = records.map((c) {
          var item = c as ISerialization;
          return item.toJson();
        }).toList();

        var jsonString = jsonEncode(map);

        final file = await _getLocalFile;
        // Write the file
        recordedFile = await file.writeAsString(jsonString);
      }
      return recordedFile;
    } catch (e) {
      print("writeToDisk: " + e.toString());
      return null;
    }
  }

  Future<RList<T>> _readFromDiskRecords({bool isFast = false}) async {
    try {
      final file = await _getLocalFile;

      // Read the file
      String contents = await file.readAsString();
      List parsedJson = jsonDecode(contents);
      var records = RList<T>();
      if (isFast) {
        records.add(factories[T](parsedJson.first));
      } else {
        for (var item in parsedJson) {
          records.add(factories[T](item));
        }
      }

      return records;
    } catch (e) {
      print("readFromDisk: $e");
      return null;
    }
  }

  Future<DateTime> getLastFetchTime() async {
    //DateTime lastFetchTime = DateTime.fromMillisecondsSinceEpoch(0);
    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      return DateTime.parse(prefs.getString(cacheFileName));
    } catch (e) {
      print("getLastFetchTime $e");
      return null;
    }
  }

  Future<void> setLastFetchTime(DateTime lastFetchTime) async {
    //DateTime lastFetchTime = DateTime.fromMillisecondsSinceEpoch(0);
    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      await prefs.setString(cacheFileName, lastFetchTime.toString());
    } catch (e) {
      print("setLastFetchTime $e");
    }
  }
}

```

</details>

<details>
  <summary>logs</summary>

```console
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.3+1\android\src\main\java\io\flutter\plugins\firebase\co
re\FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.0+1\android\src\main\java\io\flutter\plugins\firebase
\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.9\android\src\main\java\io\flutter\plugins\firebase
analytics\FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.1.1\android\src\main\java\io\flutter\plugins\firebase\
database\FirebaseDatabasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.5.1\android\src\main\java\io\flutter\plugins\pathprovider\
PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferen
ces\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.


 ```

</details>
