### ISSUE TITLE
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#47343]
This error seems to be related to some problem with TextFiled and TextFormField, after I put TextFiled in a 38 height containner.

```
Syncing files to device SM J120H...
Reloaded 20 of 1030 libraries in 2.433ms.
I/flutter ( 3344): obteve  do cache

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField file:///D:/MyDartProjects/appsescverao/lib/widgets/appbar_search.dart:47:14
When the exception was thrown, this was the stack: 
#2      new TextPosition (dart:ui/text.dart:1372:15)
#3      RenderEditable._updateSelectionExtentsVisibility (package:flutter/src/rendering/editable.dart:367:7)
#4      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1956:7)
#5      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2012:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#63e9d relayoutBoundary=up32
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=191.0, 0.0<=h<=14.0)
...  size: Size(191.0, 14.0)
...  cursorColor: Color(0x004285f4)
...  showCursor: ValueNotifier<bool>#05e19(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: pt_BR
...  selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: null, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#01cd6(offset: 0.0, range: 0.0..0.0, viewport: 191.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#b88bc, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge((blackMountainView subhead).apply)).merge(unknown)
    inherit: false
    color: Color(0xdd000000)
    family: Roboto
    size: 15.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
RenderObject: RenderEditable#63e9d relayoutBoundary=up32
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=191.0, 0.0<=h<=14.0)
  size: Size(191.0, 14.0)
  cursorColor: Color(0x004285f4)
  showCursor: ValueNotifier<bool>#05e19(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: pt_BR
  selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#01cd6(offset: 0.0, range: 0.0..0.0, viewport: 191.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#b88bc, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge((blackMountainView subhead).apply)).merge(unknown)
    inherit: false
    color: Color(0xdd000000)
    family: Roboto
    size: 15.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```dart
import 'package:flutter/material.dart';

class SearchAppBar extends StatefulWidget with PreferredSizeWidget {
  //"Big Noodle Titling"
  static const textStyle = TextStyle(color: Colors.white, fontFamily: "Roboto");
  static const backColor = Color.fromRGBO(239, 237, 222, 0.0);
  String title = "";
  TextStyle styleTitle = textStyle;
  Color colorIcon = Colors.white;
  Color backgroundColor = backColor;
  double elevation = 0;
  bool centerTitle = true;
  Function searchOpening;
  Function onKeypress;
  bool showSearch = true;
  Size preferredSize = AppBar().preferredSize;
  final List<Widget> actions;

  SearchAppBar({Key key, this.title = "", this.colorIcon = Colors.white, this.backgroundColor = backColor, this.styleTitle = textStyle, this.showSearch = true, this.searchOpening, @required this.onKeypress, this.elevation = 0, this.centerTitle = true, this.actions}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return new SearchAppBarState();
  }
}

class SearchAppBarState extends State<SearchAppBar> {
  final TextEditingController _filter = TextEditingController();
  Icon _searchIcon = Icon(Icons.search);
  bool _isSearching = false;

  _buildTitle() {
    return Text(
      widget.title,
      style: widget.styleTitle,
    );
  }

  _buildSearchField() {
    return Container(
      padding: EdgeInsets.fromLTRB(15, 0, 10, 0),
      height: 38,
      decoration: BoxDecoration(color: Color.fromRGBO(255, 255, 255, 1), borderRadius: BorderRadius.all(Radius.circular(25))),
      child: TextField(
        style: TextStyle(fontSize: 15),
        autofocus: true,
        controller: _filter,
        decoration: InputDecoration(
          border: InputBorder.none,
          /*OutlineInputBorder(
          borderRadius: BorderRadius.circular(25.0),
          borderSide: BorderSide(),
        ),*/
          //prefixIcon: Icon(Icons.search),
          hintText: 'Buscar...',
          hintStyle: TextStyle(fontFamily: "Roboto"),
        ),
      ),
    );
  }

  Widget _buildBar(BuildContext context) {
    var appBar = AppBar(
        iconTheme: IconThemeData(
          color: widget.colorIcon, //change your color here
        ),
        centerTitle: widget.centerTitle,
        titleSpacing: 0.0,
        title: _isSearching ? _buildSearchField() : _buildTitle(),
        backgroundColor: widget.backgroundColor,
        elevation: widget.elevation,
        actions: widget.showSearch
            ? <Widget>[
                IconButton(
                    icon: _searchIcon,
                    onPressed: () {
                      _searchPressed();
                    }),
              ]
            : widget.actions);

    widget.preferredSize = appBar.preferredSize;
    return appBar;
  }

  void _searchPressed() async {
    setState(() {
      if (this._searchIcon.icon == Icons.search) {
        this._searchIcon = Icon(Icons.close);
        _isSearching = true;
      } else {
        this._searchIcon = Icon(Icons.search);
        _filter.clear();
        _isSearching = false;
      }

      if (widget.searchOpening != null) {
        widget.searchOpening();
      }
    });
  }

  @override
  void initState() {
    super.initState();
    initWidgetState();
  }

  initWidgetState() async {
    //ouvinte de vento onkeypress do searchbox
    _filter.addListener(() {
      if (widget.onKeypress != null) {
        widget.onKeypress(_filter.text);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    var screenSize = MediaQuery.of(context).size;
    return _buildBar(context);
  }
}

```

```yaml
name: appsescverao
description: Aplicativo do Sesc Verão Rio das Ostras

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.0+2
  path_provider: ^1.5.1
  flutter_advanced_networkimage: ^0.6.2
  sqflite: ^1.2.0
  connectivity: ^0.4.6+1
  url_launcher: ^5.4.1
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.2
  google_sign_in: ^4.1.0
  firebase_database: ^3.1.1
  rxdart: ^0.23.1
  webview_flutter: ^0.3.18+1
  auto_size_text: ^2.1.0
  flutter_map: ^0.8.0
  latlong: ^0.6.1
  queries: ^0.1.12
  firebase_analytics: ^5.0.9
  shared_preferences: ^0.5.6
  #audioplayers: ^0.13.5
  #audio_streams: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.7

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/background.png
    - assets/background2.png
    - assets/background3.png
    - assets/user-avatar.png
    - assets/logo-pmro-cinza.png
    - assets/logo-pmro-branco.png
    - assets/wave-bottom.png
    - assets/wave-top.png
    - assets/logo2.png
    - assets/logo-branca.png

  fonts:
    - family: Big Noodle Titling
      fonts:
        - asset: fonts/big_noodle_titling.ttf
    - family: GlosaDisplayW01-Bold
      fonts:
        - asset: fonts/glosa_display_w01_bold.ttf
    - family: BakerieSmoothCondensedMedium
      fonts:
        - asset: fonts/BakerieSmoothCondensed-Medium.otf
    - family: BakerieSmoothBold
      fonts:
        - asset: fonts/BakerieSmooth-Bold.otf
    - family: iconsmind
      fonts:
        - asset: fonts/iconsmind.ttf
```
