### ISSUE TITLE
An error occurred during packaging: A problem occurred evaluating root project 'url_launcher_macos'.

### ISSUE THREAD

**Issue by januwA** [flutter/flutter#47751]
```bash
λ flutter build apk --split-per-abi
Running "flutter pub get" in flutter_video_app...                   1.8s
Running Gradle task 'assembleRelease'...
Removed unused resources: Binary resource data reduced from 193KB to 184KB: Removed 4%
Running Gradle task 'assembleRelease'...
Removed unused resources: Binary resource data reduced from 193KB to 184KB: Removed 4%
Running Gradle task 'assembleRelease'...
Removed unused resources: Binary resource data reduced from 193KB to 184KB: Removed 4%
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
FAILURE: Build failed with an exception.
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
* What went wrong:
Running Gradle task 'assembleRelease'...
Execution failed for task ':system_shortcuts:verifyReleaseResources'.
Running Gradle task 'assembleRelease'...
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Running Gradle task 'assembleRelease'...
   > Android resource linking failed
Running Gradle task 'assembleRelease'...
     C:\Users\ajanuw\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
     C:\Users\ajanuw\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
* Try:
Running Gradle task 'assembleRelease'...
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
* Get more help at https://help.gradle.org
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'...
BUILD FAILED in 2m 26s
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'... Done                     147.1s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin http_interceptor...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    3.1s
√ Built build\app\outputs\repo.
Building plugin package_info...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    3.3s
√ Built build\app\outputs\repo.
Building plugin sqflite...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    4.8s
√ Built build\app\outputs\repo.
Building plugin system_shortcuts...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    3.3s
√ Built build\app\outputs\repo.
Building plugin url_launcher...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    4.5s
√ Built build\app\outputs\repo.
Building plugin url_launcher_macos...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    2.4s


FAILURE: Build failed with an exception.

* Where:
Build file 'D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\url_launcher_macos-0.0.1+2\android\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'url_launcher_macos'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\url_launcher_macos-0.0.1+2\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s


The plugin url_launcher_macos could not be built due to the issue above.
```

```console
λ flutter doctor -v
[√] Flutter (Channel master, v1.13.6-pre.22, on Microsoft Windows [Version 10.0.17763.914], locale zh-CN)
    • Flutter version 1.13.6-pre.22 at D:\flutter
    • Framework revision d874596e38 (17 hours ago), 2019-12-23 16:16:43 -0800
    • Engine revision 33813929e3
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    • Android SDK at D:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc3
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: D:\Android\Android_Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup
      for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\Android_Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by januwA** [comment]
🥺

**Comment by iapicca** [comment]
Hi @januwA  
could you please run 
`flutter clean`
`flutter pub cache repair`
let me know if the issue persists
thank you

**Comment by januwA** [comment]
Hi @iapicca 

I executed `flutter pub cache repair` and re-installed` flutter` still failed during packaging

```
λ flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.914], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    • Android SDK at D:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc3
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: D:\Android\Android_Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\Android_Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

pubspec.yaml
```
name: ttt
description: '-'
version: 0.6.2

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  cupertino_icons: ^0.1.2
  rxdart: ^0.23.1
  built_value:
  built_collection: ^4.3.0
  url_launcher: ^5.4.1
  mobx: ^0.3.10
  flutter_mobx: ^0.3.4+1
  video_box: ^0.8.1
  html: ^0.14.0+3
  webview_flutter: ^0.3.18+1
  moor_flutter: ^1.7.0
  package_info:
  flushbar: ^1.9.1
  flutter_slidable: ^0.5.4
  bubble_bottom_bar: ^1.2.0
  flutter_ajanuw_router: ^0.2.2
  get_it: ^3.0.3
  http_interceptor:
    git:
      url: https://github.com/januwA/http_interceptor.git
      ref: master
  
  toast: ^0.1.5
  breakpoints: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  built_value_generator: ^6.7.1
  mobx_codegen:
  moor_generator:

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
```
