### ISSUE TITLE
Flutter v1.12.13+hotfix.5 unstable on android10

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#48039]
![image](https://user-images.githubusercontent.com/379339/71642567-1229e300-2c8c-11ea-8caf-1f5122206cd9.png)

Prior to point A: version 1.10.7 beta (because of Adreno 308 bug which rendered black screen on many devices).

Point A: applying the new "stable" version 1.12 (that fixes the Adreno 308 bug). It's the exactly same code. Thousands of crashes. Thousands of affected users (I have 140k users and the crashes affected +20k)

Point B: rollback to version 1.10.7 beta. (Not perfect, but at least I get 99.86% crash free)

I can't provide "steps to reproduce" nor more info because I don't have them (none of my devices show abnormal behavior), but I'm happy to share all Crashlytics and Google Play Console data, if it is usefull.

```console
[√] Flutter (Channel unknown, v1.10.7, on Microsoft Windows [Version 10.0.18362.535], locale pt-BR)
    • Flutter version 1.10.7 at C:\flutter
    • Framework revision e70236e36c (3 months ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.4.0 1103600280)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\jckod\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\jckod\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\jckod\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.4.29519.181

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (3 available)
    • XT1033   • 0423490246 • android-arm • Android 5.0.2 (API 21)
    • SM J415G • 785dd05b   • android-arm • Android 9 (API 28)
    • Windows  • Windows    • windows-x64 • Microsoft Windows [Version 10.0.18362.535]

• No issues found!
```

```yaml
environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  before_after: ^2.0.0
  cached_network_image: ^1.1.3
  connectivity: ^0.4.4
  datetime_picker_formfield: ^1.0.0-pre.5
  device_info: ^0.4.1+1
  diacritic: ^0.1.1
  dio: ^3.0.1
  firebase_admob: ^0.9.0+10
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.15.1+1
  firebase_crashlytics: ^0.1.2+4
  firebase_messaging: ^6.0.9
  flutter_alert: ^0.4.0
  flutter_custom_tabs: ^0.6.0
  flutter_device_type: ^0.2.0
  flutter_email_sender: ^2.2.2
  flutter_facebook_login:
    git:
      url: https://github.com/CodeArtBR/flutter_facebook_login.git
  flutter_html: ^0.11.1
  flutter_image_compress: ^0.6.3
  flutter_local_notifications: ^0.9.1
  flutter_masked_text: ^0.8.0
  flutter_mobx: ^0.3.4+1
  flutter_secure_storage: ^3.3.1+1
  flutter_speed_dial: ^1.2.1
  flutter_svg: ^0.15.0
  flutter_svprogresshud: ^0.0.2
  google_api_availability: ^2.0.1
  google_sign_in: ^4.0.16
  image_cropper:
    git:
      url: https://github.com/hsangtini/flutter_image_cropper
  image_picker: ^0.6.1+4
  in_app_purchase: ^0.2.2+2
  jaguar_jwt: ^2.1.6
  material_design_icons_flutter: ^3.4.4795
  mobx: ^0.3.10
  path_provider: ^1.5.1
  photo_view: ^0.9.0
  rate_my_app: ^0.4.0
  sqflite: ^1.1.8
  sticky_headers: ^0.1.8
  table_calendar: ^2.0.2
  timeago: ^2.0.19
  timeago_flutter: ^0.1.0
  url_launcher: ^5.2.7
  uuid: ^2.0.2
  zefyr: ^0.8.0

dev_dependencies:
  build_runner: ^1.7.1
  mobx_codegen: ^0.3.9+1

dependency_overrides:
  json_annotation:
    path: lib/wsfx/builders/json_annotation
  json_serializable:
    path: lib/wsfx/builders/json_serializable
```
