### ISSUE TITLE
Error in pubspec.yaml: Unexpected child "asserts" found under "flutter"

### ISSUE THREAD

**Issue by iKK001** [flutter/flutter#48203]
Using Flutter, I get the following error message when building:

`Error detected in pubspec.yaml:`
`Unexpected child "asserts" found under "flutter".`

What is there to change in order to get rid of this error message ?

Here is my pubspec.yaml file:

```yaml
name: AppName
description: My App rocks.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6
  sqflite: ^1.1.8
  intl: ^0.16.0
  tuple: ^1.0.3
  material_design_icons_flutter: ^3.4.4795
  launch_review: ^2.0.0
  fit_image: ^0.1.2
  datetime_picker_formfield: ^1.0.0-pre.5
  flutter_screenutil: ^0.7.0
  path_provider: ^1.5.0
  image_picker: ^0.6.2+3
  url_launcher: ^5.4.1
  permission_handler: ^4.0.0
  page_transition: ^1.1.5
  cupertino_icons: ^0.1.3
  # flutter_downloader: ^1.3.4
  flutter_downloader:
   git:
      url: https://github.com/fluttercommunity/flutter_downloader.git
      ref: embedding-v2

#   flutter_launcher_icons: ^0.7.2

# flutter_icons:
#   image_path: "assets/app_icon/app_icon_3072.png"
#   adaptive_icon_background: "#0099CC"
#   android: true
#   ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/en.json
    - assets/lang/de.json
    - assets/lang/fr.json
    - assets/lang/it.json
    - assets/logo.png
    - assets/flag.png
    - assets/stops.db
    - assets/default_locations.db
    - assets/CancelButtonInLabel@3x.png
    - assets/continueBtn@3x.png
    - assets/continueBtnGrey@3x.png
    - assets/close.png
    - assets/gifs/video1_en.gif
    - assets/gifs/video1_de.gif
    - assets/gifs/video1_fr.gif
    - assets/gifs/video1_it.gif
    - assets/gifs/video2_en.gif
    - assets/gifs/video2_de.gif
    - assets/gifs/video2_fr.gif
    - assets/gifs/video2_it.gif
    - assets/gifs/video3_en.gif
    - assets/gifs/video3_de.gif
    - assets/gifs/video3_fr.gif
    - assets/gifs/video3_it.gif
    - assets/cities/Zurich.jpg
    - assets/cities/Bern.jpg
    - assets/cities/Basel.jpg
    - assets/cities/Luzern.jpg
    - assets/cities/Zug.jpg
    - assets/cities/Stgallen.jpg
    - assets/cities/Lugano.jpg
    - assets/cities/Biel.jpg
    - assets/cities/Lausanne.jpg
    - assets/cities/Geneve.jpg
    - assets/cities/Chur.jpg
    - assets/cities/Schaffhausen.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```

Here is my `flutter doctor -v` log:
```dart
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CH)
    • Flutter version 1.12.13+hotfix.5 at /Users/stephankorner/Documents/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/stephankorner/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Dance • d709a1319de65e7429258466dbac6d29f05924e8 • ios • iOS 13.3

• No issues found!
```
