### ISSUE TITLE
package:flutter_test should not pin `pedantic` version

### ISSUE THREAD

**Issue by davidmorgan** [flutter/flutter#48246]
See complaint at https://github.com/dart-lang/pedantic/issues/46

I believe the fix is for `flutter_test` to allow the version it is using or any later version.

Inside `package:pedantic` the analysis options files are versioned, so you can still pin to a specific set of lints by using the versioned file name in your `analysis_options.yaml` file.

Thanks.

**Comment by dnfield** [comment]
I believe we intentionally pin all of our packages to keep our builds and version solving repeatable. We have specific logic in the repo to check for this and make sure it's the case.

@jonahwilliams or @hixie might have more context there.  In general though, if you want to use a particular package we depend on, we require that you use the exact version we do - and we try to limit what we depend on as much as possible.  Maybe we can avoid depending on pedantic entirely though.  I'm not sure why we do (we've eliminated instances of `unawaited` from package:pedantic in at least some places).

**Comment by dnfield** [comment]
Ah - we transitively depend on pedantic.

**Comment by dnfield** [comment]
If we could get test_api to not depend on pedantic we could remove the dep entirely.

**Comment by dnfield** [comment]
Adding here as well - if a user really wants this _now_, you can do something like this:

```yaml
name: flutter_project

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.8.0+1

dependency_overrides:
  pedantic: 1.9.0
```
