### ISSUE TITLE
Getting Compile Error - pub get failed (1; So, because <#projectx> depends on both flutter_localizations any from sdk and l10n ^1.4.0, version solving failed.)

### ISSUE THREAD

**Issue by starman-karthik** [flutter/flutter#48286]
I recently updated flutter to v1.12 and tried to compile the code using,

`flutter build ios`

I am getting _'Compilation Error'_ with 

_**Because no versions of l10n match >1.4.0 <2.0.0 and l10n 1.4.0 depends on intl ^0.15.0, l10n ^1.4.0 requires intl ^0.15.0.
And because every version of flutter_localizations from sdk depends on intl 0.16.0, l10n ^1.4.0 is incompatible with flutter_localizations from sdk.
So, because <#projectx> depends on both flutter_localizations any from sdk and l10n ^1.4.0, version solving failed.
Running "flutter pub get" in Source...                                  
pub get failed (1; So, because <#projectx> depends on both flutter_localizations any from sdk and l10n ^1.4.0, version solving failed.)**_

I am getting same error when I try to run build apk.

Where is the flutter doctor log 

**Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[!] Connected device
    ! No devices available**

**! Doctor found issues in 1 category.**

**Comment by VladyslavBondarenko** [comment]
Hi @starman-karthik 

Try to use the last version of [intl](https://pub.dev/packages/intl)

```
dependency_overrides:
  intl: ^0.16.1
```

Does it help to you?
Thank you

**Comment by Kar7h1k** [comment]
Hi @VladyslavBondarenko ,

I tried changing the dependency, error still exists,

**Because l10n >=1.4.0 depends on intl ^0.15.0 and every version of flutter_localizations from sdk depends on intl 0.16.0, l10n >=1.4.0 is incompatible with flutter_localizations from sdk.
So, because <#projectx> depends on both flutter_localizations any from sdk and l10n ^2.0.19, version solving failed.
Running "flutter pub get" in Source...                                  
pub get failed (1; So, because <#projectx> depends on both flutter_localizations any from sdk and l10n ^2.0.19, version solving failed.)**

Here is the list of dependencies I have in my project,

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  connectivity: ^0.4.0
  device_info: ^0.3.0
  package_info: ^0.3.2
  flutter_email_sender:
    path: plugins/flutter_email_sender-master
  http: ^0.12.0+1
  http_parser: ^3.1.3
  l10n: ^2.0.19
  intl_translation: ^0.17.8
  shared_preferences: ^0.4.3
  json_annotation: ^2.0.0
  sqflite: ^0.13.0
  flutter_markdown: ^0.2.0
  dio: ^1.0.13
  simple_permissions: ^0.1.9
  cached_network_image:
    path: plugins/cached_network_image-0.5.1
  local_auth: ^0.6.1
  store_redirect: ^1.0.1
  url_launcher: ^4.0.3
  version: ^1.0.3
  location: ^1.4.1
  flutter_webview_plugin: ^0.3.0+2
  flutter_secure_storage: ^3.1.2
  image_picker_saver:
    path: plugins/image_picker_saver-master
  vibrate: ^0.0.4
  auto_size_text: ^0.2.2
  google_maps_flutter: ^0.0.3+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  uuid: ^1.0.3
  geocoder:

  flutter_cupertino_date_picker: ^0.3.0
  flutter_masked_text: ^0.7.0
  firebase_dynamic_links: ^0.5.0
  firebase_messaging: ^5.1.2
  path_provider: ^0.4.1
  screen: ^0.0.4
  camera:
    path: plugins/camera-master
  firebase_analytics: ^4.0.2
  flutter_crashlytics: ^0.2.1
  latlong: ^0.6.1
  flutter_card_io:
    path: plugins/flutter_card_io-master
  orientation:
    path: plugins/orientation-master
  native_device_orientation: ^0.1.2
  share: ^0.6.0+1
  ios_device_check: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
```
