### ISSUE TITLE
[google_sign_in] Animation Problem: Android Black Status Bar Slide to Bottom

### ISSUE THREAD

**Issue by Peng-Qian** [flutter/flutter#48371]
Hi
As the gif shows, when google sign in plugin (https://pub.dev/packages/google_sign_in) active, it will change the status bar to be black and after the process has done, the black bar will slide to the bottom.

It really breaks the UI appearance, is there any approach can fix it?

I have tried it on different android versions and create a brand new project as following, but the problem remains.

![google_sign_in_bug](https://user-images.githubusercontent.com/37643086/71949043-ed5ae000-3236-11ea-9953-78f9302b1dfe.gif)

<details>
	<summary>pubspec.yaml</summary>

```yaml
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  google_sign_in: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

</details>

```console
[✓] Flutter (Channel dev, v1.13.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-NZ)
    • Flutter version 1.13.6 at /Users/pq/Developer/SDK/flutter
    • Framework revision 659dc8129d (8 days ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pq/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/pq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
Process finished with exit code 0

```
