### ISSUE TITLE
[WEB] Buttons with icon don't work fine in the web.

### ISSUE THREAD

**Issue by Kassan424kh** [flutter/flutter#48887]
Hy Flutters,

I discovered that all buttons with icons don't work's fine on the web, the problem is, when I set icon in a button widget like (IconButton, ReisedButton.icon, etc.), click cann't  working if clicked on the icon or on the left button tail after the icon, not only clicking function cann't working, rather too effects like splashing and hovering.

```dart
SizedBox(
      width: 51,
      height: 51,
      child: RaisedButton(
        elevation: 0,
        hoverElevation: 0,
        highlightElevation: 0,
        disabledElevation: 0,
        focusElevation: 0,
        animationDuration: Duration(milliseconds: 350),
        color: color.withOpacity(_selectedTheme[ElementStylingParameters.buttonsBackgroundColorOpacity]),
        splashColor: color.withOpacity(_selectedTheme[ElementStylingParameters.splashOpacity]),
        focusColor: Colors.transparent,
        textColor: Colors.transparent,
        highlightColor: Colors.transparent,
        disabledTextColor: Colors.transparent,
        disabledColor: Colors.transparent,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.all(Radius.circular(100)),
        ),
        onPressed: onClick,
        child: Icon(
          icon,
          color: color,
          size: 20,
        ),
      ),
    )
```

```bash
▶ flutter doctor -v
[✓] Flutter (Channel master, v1.13.10-pre.65, on Mac OS X 10.14.6 18G103, locale
    en-GB)
    • Flutter version 1.13.10-pre.65 at /Users/kkhalil/flutter
    • Framework revision 5d37de2685 (8 hours ago), 2020-01-15 01:23:02 -0500
    • Engine revision bc41ab5139
    • Dart version 2.8.0 (build 2.8.0-dev.1.0 fe666ce592)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kkhalil/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/kkhalil/Library/Android/sdk
    • Java binary at: /Users/kkhalil/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/kkhalil/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android
      Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Users/kkhalil/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 41.1.1
    • Dart plugin version 191.8593

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (3 available)
    • SM N960F   • 254a9fa0431c7ece • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome           • web-javascript • Google Chrome
      79.0.3945.117
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!
```

```yaml
name: flutter_berichtsheft_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  google_fonts: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bh_logo_dark.png
    - assets/images/bh_logo_hell.png
    - assets/avatars/avatar_dark.png
    - assets/avatars/avatar_hell.png
```
