### ISSUE TITLE
[cocoon] Datastore latency on Task entity caused by large number of composite indexes

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#48914]
According to Datastore best practices:
> Avoid having too many composite indexes. Excessive use of composite indexes could result in increased latency and increased storage costs of index entries. If you need to execute ad hoc queries on large datasets without previously defined indexes, use BigQuery.

For example, `Task` has 5 different composite indexes. Entities are recommended to just have 1 composite index. We should look at simplifying our use of these indexes to improve the runtime of our queries. The Dart Datastore implementation will convert all `filter` and `order` actions into composite actions (see https://github.com/dart-lang/gcloud/blob/master/lib/src/datastore_impl.dart#L232-L252 for filters).

It takes the build dashboard ~7 seconds to query Datastore to get the latest 100 commits, and removing unnecessary indexes should be able to get this down to under 3 seconds.

There is a trade off to this as we will incur more reads. However, some of these filters are only used in debug endpoints that are never run. We will have to update our code to not rely on these filters and orders, and handle it in the code.

Additionally, we should convert our timestamp indexes to just be simple indexes that Datastore handles for us, that do not incur any additional latency.

# Composite indexes to investigate:
- [ ] Create timestamp (descending) (includes ancestors)
- [ ] Stage name (including ancestors)
- [ ] Stage name (descending), checklist key (ascending) (https://github.com/flutter/cocoon/pull/636)
- [ ] Name (ascending) create timestamp (descending)
- [ ] Name (ascending) create timestamp (descending) (includes ancestors)
- [ ] Name (ascending) status (ascending) create timestamp (descending)
- [X] Status (https://github.com/flutter/cocoon/pull/634)
- [X] Reserved for agent id (https://github.com/flutter/cocoon/pull/635)

**Comment by CaseyHillers** [comment]
While removing the reserved for agent id composite index, gcloud reported there are more indexes on Cocoon's datastore than we have listed in our index.yaml:

`gcloud datastore indexes cleanup index.yaml`

```
kind: Task
properties:
- direction: asc
  name: Name
- direction: desc
  name: CreateTimestamp
```

```
kind: Task
properties:
- direction: asc
  name: ChecklistKey
- direction: desc
  name: StageName
```

```
kind: LogChunk
properties:
- direction: asc
  name: OwnerKey
- direction: desc
  name: CreateTimestamp
```

```
kind: Task
properties:
- direction: asc
  name: Name
- direction: asc
  name: Status
- direction: desc
  name: CreateTimestamp
```

I'll follow up with a PR to add these missing indexes so we have a better idea of what's in datastore.
