### ISSUE TITLE
local_auth is not working after added easy_localization 1.3.1 into project

### ISSUE THREAD

**Issue by siva563** [flutter/flutter#49190]
In my app, I need to Use localization and local_auth. I added two Plugins.

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  grouped_buttons: ^1.0.4
  local_auth: ^0.6.0
  http: ^0.12.0
  queries: ^0.1.12
  fluttertoast: ^3.1.3
  pin_code_fields: ^2.3.0+3
  url_launcher: ^5.4.1
  uuid: ^2.0.4
  shared_preferences: ^0.5.6
  webview_flutter: ^0.3.14+1
  json_annotation:
  global_configuration: ^1.4.0
  flutter_webview_plugin: ^0.3.10+1
  toast: ^0.1.5
  easy_localization: ^1.3.1
```
It was working fine before adding   `easy_localization: ^1.3.1`, once added  `easy_localization: ^1.3.1`

I am getting below error:
`PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null)`

Could you please help me out.
