### ISSUE TITLE
Need the ability to pull packages from an internal repository

### ISSUE THREAD

**Issue by PopperJuan** [flutter/flutter#49221]
I'm in a corporate firewall which blocks me from pulling packages from pub.dev. However i was given the option to use an internal repository where I can pull the packages from there. 

Maven and Gradle already has the ability to allow me to pull packages from another sources. However, after reading `https://flutter.dev/docs/development/packages-and-plugins/using-packages`, I don't see where anything where I can do something like this in my `pubspec.yaml` file:
```
dependencies:
  flutter:
    sdk: flutter

  a_general_package: ^0.1.0
      source: https://internal.repo.com/my/packages/here
```

I see that you can pull from github directly however that is also blocked by our proxy.

Is there any plans to be able to do this? It'll make software development in Enterprise companies more efficient
