### ISSUE TITLE
local_auth and  flutter_localizations not able to use.

### ISSUE THREAD

**Issue by siva563** [flutter/flutter#49294]
Hi I am working one Project which is required both 

`Local_Auth` and  `flutter_localizations `and `easy_localization`

My pubspec.yml
----------------------------
```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  grouped_buttons: ^1.0.4
  local_auth: ^0.4.0+1
  http: ^0.12.0
  queries: ^0.1.12
  fluttertoast: ^3.1.3
  pin_code_fields: ^2.3.0+3
  url_launcher: ^5.4.1
  uuid: ^2.0.4
  shared_preferences: ^0.5.6
  webview_flutter: ^0.3.14+1
  json_annotation:
  global_configuration: ^1.4.0
  flutter_webview_plugin: ^0.3.10+1
  toast: ^0.1.5
  easy_localization: ^1.3.1

  #flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable:
  json_model:
  flutter_test:
    sdk: flutter
```
I am getitng below Error:

`Because every version of easy_localization depends on flutter_localizations any from sdk which depends on intl 0.16.0, every version of easy_localization requires intl 0.16.0.`
 
`And because local_auth 0.4.0+1 depends on intl ^0.15.1 and no versions of local_auth match >0.4.0+1 <0.5.0, easy_localization is incompatible with local_auth ^0.4.0+`1.
 
`So, because ntta_mobile_app depends on both local_auth ^0.4.0+1 and easy_localization ^1.3.1, version solving failed.`
`pub get failed (1; So, because ntta_mobile_app depends on both local_auth ^0.4.0+1 and easy_localization ^1.3.1, version solvi`ng failed.)
`exit code 1`

Could you please sombody help me how to fix this version issue.
