### ISSUE TITLE
[flutter_plugin_android_lifecycle] cannot install on the latest flutter stable build

### ISSUE THREAD

**Issue by Inconnu08** [flutter/flutter#49524]
While my android app works fine on the emulator, it keeps crashing during start-up in actual devices. The issue was `image_picker: ^0.6.3+1`looking for invoking virtual method `androidX.lifecycle.f.a`. After googling whats the issue, it turns out I need `flutter_plugin_android_lifecycle`. But now I'm facing the following:

## Error
```
Because app_name depends on flutter_plugin_android_lifecycle >=1.0.4 which requires Flutter SDK version >=1.12.13 <2.0.0, version solving failed.
pub get failed (1; Because app_name depends on flutter_plugin_android_lifecycle >=1.0.4 which requires Flutter SDK version >=1.12.13 <2.0.0, version solving failed.)
exit code 1

```

## Steps to Reproduce
Run `flutter pub get` with these:

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3+1
  flutter_plugin_android_lifecycle: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
```

## flutter doctor -v
```
[√] Flutter (Channel 45043, v1.10.15-pre.687, on Microsoft Windows [Version 10.0.18362.592], locale en-US)
    • Flutter version 1.10.15-pre.687 at E:\Dart\projects\flutter
    • Framework revision 8913abdc21 (11 days ago), 2020-01-16 01:08:37 +0600
    • Engine revision b6b54fd606
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Taufiq\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Taufiq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```
