### ISSUE TITLE
Expected "fonts" to be a list,

### ISSUE THREAD

**Issue by fredgrott** [flutter/flutter#49616]
This is something new flutter sdk version 1.12.hotfix5

my pubspec code:
``fonts:
    family: WorkSans
    fonts:
        asset: fonts/WorkSans-Black.ttf
        weight: 900

Same exact error if its asserts/fonts ub directory

It matches the cookbook example and comments of how to do it in pubspec and it happens to be how I did it before with some previous releases of the flutter sdk.

Not real immediate but I do need to set fonts for the cupertinoApp theme texttheme portion so its a pain

**Comment by VladyslavBondarenko** [comment]
Hi @fredgrott 

You pubspec code is expected to be:

```
fonts:
  - family: WorkSans
    fonts:
      - asset: fonts/WorkSans-Black.ttf
        weight: 700

```

Closing the issue
If you sure it's not a matter of formatting,
please write in the comments and I will reopen it. 
Thank you
