### ISSUE TITLE
Check Mobile Network Before Loading Web View

### ISSUE THREAD

**Issue by KANCybernet** [flutter/flutter#49652]
Hello.. I have this code already displaying webview of a platform. But then, there is a flaw which i intend to correct but as a newbie, am still finding it difficult scaling. I included a code to check for network availability before loading the webview, but it is giving me some error which i cant understand it's origin or how to go around it. Would appreciate if you can fix it or restructure it please:

Main.dart
```dart
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:connectivity/connectivity.dart';

void main() => runApp(MyApp());

var connectivityResult = await (Connectivity().checkConnectivity());

await(Future<ConnectivityResult> checkConnectivity) {
}

class MyApp extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
      
        primarySwatch: Colors.yellow
      ),
      home: MyHomePage(title: 'Flutter Demooo Home Page'),
    );
  }
}
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);


  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}


class _MyHomePageState extends State<MyHomePage> {
  
  final Completer<WebViewController> _controller=Completer<WebViewController>();

  
  @override
  Widget build(BuildContext context) {

    return Scaffold(
      
      body: WebView(
        if (connectivityResult == ConnectivityResult.mobile) {
  // I am connected to a mobile network.
} else if (connectivityResult == ConnectivityResult.wifi) {
  // I am connected to a wifi network.

        initialUrl: "https://google.com/",
        onWebViewCreated: (WebViewController webViewController){
          _controller.complete(webViewController);
        },}
        else{
          //i am not connected to any network
        }
      ) );
       
       
    
  }
}
```

Pubspec.yaml
```yaml
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  webview_flutter: 0.2.0
  connectivity: ^0.4.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

```
