### ISSUE TITLE
Custom package library needs a dependency from project where is imported on

### ISSUE THREAD

**Issue by sami-samcla** [flutter/flutter#49781]
I have created a custom package library. This library has http package dependency defined in pubspec.yaml.

```
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  http: ^0.12.0+4
```

I imported this custom library in another project. When I run this project, shows this error related with http package:

```
Compiler message:
Error: Could not resolve the package 'http' in 'package:http/http.dart'.
Error: Could not resolve the package 'http_parser' in 'package:http_parser/http_parser.dart'.
../xxxxx/lib/src/network/base/http_request.dart:4:8: Error: Not found: 'package:http/http.dart'
import 'package:http/http.dart';
```

I don't understand why need to import this package dependency in project if this http package is used only in custom library.

This is my Flutter setup summary:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.3 19D76, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
```
Thanks in advance.
