### ISSUE TITLE
SharedPreferences.getInstance();   crash 

### ISSUE THREAD

**Issue by fordringd2008** [flutter/flutter#49937]
```console
[✓] Flutter (Channel unknown, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.7 at /Users/3irobotics/flutter/flutter
    • Framework revision 9f5ff2306b (5 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/3irobotics/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 879FD9B7-29ED-49A8-9D72-E2AE03FBB898 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

<details>
  <summary>pubspec</summary>

```yaml
packages:
  _fe_analyzer_shared:
    dependency: transitive
    description:
      name: _fe_analyzer_shared
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.0.3"
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.39.4"
  archive:
    dependency: transitive
    description:
      name: archive
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.0.11"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.5.2"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.4.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.0.5"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.1.2"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.14.11"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.1.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.1.3"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.16.1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.1.3"
  dart_style:
    dependency: transitive
    description:
      name: dart_style
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.3.3"
  dio:
    dependency: "direct main"
    description:
      name: dio
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "3.0.8"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_localizations:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  glob:
    dependency: transitive
    description:
      name: glob
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.2.0"
  html:
    dependency: transitive
    description:
      name: html
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.14.0+3"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "3.1.3"
  image:
    dependency: transitive
    description:
      name: image
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.1.4"
  infinite_listview:
    dependency: "direct main"
    description:
      name: infinite_listview
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.0.1+1"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.16.0"
  intl_translation:
    dependency: "direct dev"
    description:
      name: intl_translation
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.17.9"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.6.1+1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.12.6"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.1.8"
  nested:
    dependency: transitive
    description:
      name: nested
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.0.4"
  node_interop:
    dependency: transitive
    description:
      name: node_interop
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.0.3"
  node_io:
    dependency: transitive
    description:
      name: node_io
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.0.1+2"
  package_config:
    dependency: transitive
    description:
      name: package_config
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.1.0"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.6.4"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.8.0+1"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.4.0"
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "4.0.2"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.4.2"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.0.5"
  shared_preferences:
    dependency: "direct main"
    description:
      name: shared_preferences
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.5.4"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.5.5"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.9.3"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.0.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.0.5"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.1.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.2.11"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.1.6"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.0.8"
  watcher:
    dependency: transitive
    description:
      name: watcher
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.9.7+13"
  xml:
    dependency: transitive
    description:
      name: xml
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "3.5.0"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "2.2.0"
sdks:
  dart: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.1 <2.0.0"
```

</details>

![1580562350592](https://user-images.githubusercontent.com/12234250/73592565-b4144800-4536-11ea-88f3-3505023d2852.jpg)
