### ISSUE TITLE
dart:ui not found

### ISSUE THREAD

**Issue by orangeswim** [flutter/flutter#49962]
## Steps to Reproduce

1. Run `flutter create test_app`. change directory to test_app. 
2. Update the files as follows: 
Add flutter_driver to pubspec.yaml
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
```
add test_driver/app.dart
```
import 'package:test_app/main.dart' as app;
import 'package:flutter_driver/driver_extension.dart';

void main() {
  // This line enables the extension
  enableFlutterDriverExtension();

  // Call the `main()` function of your app or call `runApp` with any widget you
  // are interested in testing.
  app.main();
}
```
add test_driver/app_test.dart
```
import 'package:flutter_driver/flutter_driver.dart';
import 'package:flutter_test/flutter_test.dart';


void main() {
  group('Flutter Driver demo', () {
    FlutterDriver driver;

    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    tearDownAll(() async {
      if (driver != null) {
        await driver.close();
      }
    });

    test('check flutter driver health', () async {
      Health health = await driver.checkHealth();
      print(health.status);
    });
  });
}
```

3. From terminal, Run `flutter packages get`, `flutter drive --target=flutter_driver/app.dart`

**Expected results:** 
```
00:01 +0: Flutter Driver demo check flutter driver health
HealthStatus.ok
00:01 +1: Flutter Driver demo (tearDownAll)
00:01 +1: All tests passed!
Stopping application instance.
```
**Actual results:** 
```
\test_app> flutter drive --target=test_driver/app.dart
Using device Android SDK built for x86.
Starting application: test_driver/app.dart
Installing build\app\outputs\apk\app.apk...                         0.8s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         6.6s
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                         0.7s
I/flutter ( 8415): Observatory listening on http://127.0.0.1:41663/3iI-YvpeVn8=/
../../flutter_src/flutter_windows_v1.9.1+hotfix.5-stable/flutter/packages/flutter_test/lib/src/accessibility.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../flutter_src/flutter_windows_v1.9.1+hotfix.5-stable/flutter/packages/flutter_test/lib/src/binding.dart:7:8: Error: 
Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../flutter_src/flutter_windows_v1.9.1+hotfix.5-stable/flutter/packages/flutter_test/lib/src/matchers.dart:8:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../flutter_src/flutter_windows_v1.9.1+hotfix.5-stable/flutter/packages/flutter_test/lib/src/matchers.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
../../flutter_src/flutter_windows_v1.9.1+hotfix.5-stable/flutter/packages/flutter_test/lib/src/test_pointer.dart:12:1: Error: Not found: 'dart:ui'
export 'dart:ui' show Offset;
^
../../flutter_src/flutter_windows_v1.9.1+hotfix.5-stable/flutter/packages/flutter_test/lib/src/window.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' hide window;
       ^
../../flutter_src/flutter_windows_v1.9.1+hotfix.5-stable/flutter/packages/flutter_test/lib/src/_matchers_io.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../flutter_src/flutter_windows_v1.9.1+hotfix.5-stable/flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paint, Path, Canvas;
       ^
../../flutter_src/flutter_windows_v1.9.1+hotfix.5-stable/flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../flutter_src/flutter_windows_v1.9.1+hotfix.5-stable/flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: 
Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
Stopping application instance.
Driver tests failed: 254
```
<details>
  <summary>Logs</summary>

```
```

```
Analyzing test_app...

   info - 'display1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. 
          The modern term is headline4. This feature was deprecated after v1.13.8. - lib\main.dart:99:50 -
          deprecated_member_use

1 issue found. (ran in 13.0s)
```

```
[√] Flutter (Channel master, v1.14.7-pre.83, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
    • Flutter version 1.14.7-pre.83 at C:\Users\Cyprian\Dev\flutter_src\flutter_windows_v1.9.1+hotfix.5-stable\flutter
    • Framework revision e10df3c1a6 (27 hours ago), 2020-02-01 11:23:01 +0800
    • Engine revision e625e174c5
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 5ae5aff640)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Cyprian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 79.0.3945.130
    • Web Server                • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

```
```

</details>

**Comment by orangeswim** [comment]
This is a fresh project trying to run and use flutter_driver and it cannot find dart.ui. The app compiles and runs on android and web fine. However trying flutter drive per the docs and per https://medium.com/flutter-community/testing-flutter-ui-with-flutter-driver-c1583681e337 , I'm getting the error described above.

**Comment by orangeswim** [comment]
retried on stable channel with the same results sadly

**Comment by VladyslavBondarenko** [comment]
Hi @orangeswim 
I see there's an issue addressing the case you described.
Please take a look at the solution https://github.com/flutter/flutter/issues/27826#issuecomment-480827492

try to import in your `test_driver/app_test.dart`
```
import 'package:test/test.dart';
```
instead of
```
import 'package:flutter_test/flutter_test.dart';
```

I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Comment by orangeswim** [comment]
Currently running into this issue 
```
Because test >=1.11.1 depends on test_api 0.2.13 and every version of flutter_driver from sdk depends on test_api 0.2.11, test >=1.11.1 is incompatible with flutter_driver from sdk.
So, because test_app depends on both flutter_driver any from sdk and test ^1.11.1, version solving failed. 
```
Trying to find a version that will make both packages happy. #27826 didn't encounter this issue.

**Comment by orangeswim** [comment]
If anyone else encounters this issue,

the following pubspec.yaml finally worked. See #21338 
```
name: test_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
