### ISSUE TITLE
Unable to load asset: assets/i18n/en.json

### ISSUE THREAD

**Issue by mscherer82** [flutter/flutter#49975]
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
E/flutter ( 8334): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/i18n/en.json
E/flutter ( 8334): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
```

#  Steps to Reproduce

Create a new project. Try to access an asset file.

pubscpec.yaml:
```
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/i18n/en.json
    - assets/i18n/de.json

```
