### ISSUE TITLE
"flutter create --with-driver-test" fails to create project because of version solving

### ISSUE THREAD

**Issue by ksilz** [flutter/flutter#50179]
## Steps to Reproduce

1. Run `flutter create --with-driver-test version_solving_failure`.

**Expected results:**
The project gets created and fully initialized.

**Actual results:**
During the creation, `flutter pub get`fails:

````
version_solving_failure/test_driver/main_test.dart (created)
Because test >=1.6.2 <1.6.4 depends on test_api 0.2.5 and every version of flutter_driver from sdk depends on test_api 0.2.11, test >=1.6.2 <1.6.4 is incompatible with flutter_driver from sdk.
So, because version_solving_failure depends on both flutter_driver any from sdk and test 1.6.2, version solving failed.
Running "flutter pub get" in version_solving_failure...
pub get failed (1; So, because version_solving_failure depends on both flutter_driver any from sdk and test 1.6.2, version solving failed.)
````

Manually running `flutter pub get` in the app directory produces the same error.

<details>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by helinanever** [comment]
Hi @ksilz 
Can you please provide `flutter run --verbose`?
Thank you

**Comment by ksilz** [comment]
I did. Here's the relevant section from my `pubspec.yaml` now:

````
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  test_api: 0.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.6.2
````

And I attached the output of running `flutter run --verbose` with that new configuration.

[flutter-run.txt](https://github.com/flutter/flutter/files/4160206/flutter-run.txt)

**Comment by VladyslavBondarenko** [comment]
Hi @ksilz 
You can you this combination:

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  test_api: 0.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.9.4
```

I don't have the conflict with these versions, but I'm not sure about the rest of your dependencies (if you have more the in your sample)

Is it solved?
