### ISSUE TITLE
Because flutter_gallery depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.dartlang.org), version solving failed.

### ISSUE THREAD

**Issue by EmmanuelAmodu** [flutter/flutter#50545]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
>pubspec.yaml
```yaml
name: Eyo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_paystack: ^1.0.2+1
  http: ^0.12.0+3
  uuid: ^2.0.0
  sqflite: ^1.2.0
  webview_flutter: ^0.3.19+4
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  qr_flutter: ^3.1.0
  video_player: ^0.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - images/splash_illustration.png
   - images/burna_boy.png
   - images/profile_image.png
   - images/undraw_ice_cream_s2rh.png
   - images/mastercard_logo.png
   - images/visacard_logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Black.ttf
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf

        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf

        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf

        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Italic.ttf

        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-LightItalic.ttf

        - asset: fonts/Poppins/Poppins-SemiBold.ttf
        - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf

        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins/Poppins-ExtraBoldItalic.ttf
      
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins/Poppins-ExtraLightItalic.ttf

        - asset: fonts/Poppins/Poppins-Thin.ttf
        - asset: fonts/Poppins/Poppins-ThinItalic.ttf
```
3. Error occurs when trying to `flutter update-packages --force-upgrade`

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
