### ISSUE TITLE
Flutter using outdated packages won't let me run my application

### ISSUE THREAD

**Issue by allenind** [flutter/flutter#51120]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
I want my application to run properly

**Actual results:** 
Error about the packages?
<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel unknown, v1.10.16, on Microsoft Windows [Version 10.0.18362.657], locale en-PH)
    • Flutter version 1.10.16 at C:\flutter
    • Framework revision 798e4272a2 (4 months ago), 2019-11-06 21:04:17 -0500
    • Engine revision 34a40cfbfd
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available
```

</details>
I made a pretty big project a few months ago(I stopped developing December 2019), but since then I stopped developing the project at around 80% to completion, and recently I've gotten some free time to finish the remaining 20% of the project. So I decided to jump back in, but it appears I can no longer run my code that was running 100% smoothly back then.. Is it because i'm using outdated packages?

Here's the error i'm getting:
```
Compiler message:
../../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-1.1.2+1/lib/src/cached_network_image_provider.dart:53:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/C:/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
../../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-1.1.2+1/lib/src/scaled_file_image.dart:45:24: Error: The method 'ScaledFileImage.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(ScaledFileImage key) {
                       ^
/C:/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Gradle task assembleDebug failed with exit code 1
```

Here is my dependencies in pubspec.yaml(I removed all the package_name : ^ 1.00, because I believe that forces it to use later versions? Kindly correct me if I am wrong.)

```
name: myApp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2
  intl: 0.16.0
  syncfusion_flutter_charts: 17.3.14
  provider: 3.1.0
  cloud_firestore: 0.12.9+5
  firebase_storage: 3.0.6
  firebase_auth: 0.14.0+5
  animator: 1.0.0+1
  google_maps_flutter: 0.5.21+8
  location: 2.3.5
  file_picker: 1.4.2
  firebase_core: 0.4.0+9
  image_picker: 0.6.1+8
  cached_network_image: 1.1.2+1
  photo_view: 0.6.0
  http: 0.12.0+2
  url_launcher: 5.2.5
  flutter_web_browser: 0.11.0
  pull_to_refresh: 1.5.7
  frideos: 0.7.0+1
  font_awesome_flutter: 8.5.0
  clipboard_manager: 0.0.4
  percent_indicator: 2.1.1+1
  shared_preferences: 0.5.4+5
  flutter_local_notifications: 0.8.4+3
  badges: 1.1.0
  timeago: 2.0.22
```

The reason why I don't want to use the updated packages is this: I would have to refactor most of the Provider code that I created, because I used ChangeNotifierProvider and wrapped it in the main.dart widgets, and that would take up a lot of my time. Any help would be appreciated! Thank you so much!
