### ISSUE TITLE
[Gradle] - Again the stable update is causing problems.

### ISSUE THREAD

**Issue by srburton** [flutter/flutter#51270]
*pubspec*

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  dson: any
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.5.6+2
  localstorage: 3.0.1+4
  flushbar: ^1.9.1
  progress_dialog: ^1.2.0
  google_maps_flutter: ^0.5.21+15
  flutter_spinkit: ^2.1.0
  sliding_up_panel: ^0.3.4
  network_image_to_byte: ^0.0.1
  image_cropper: ^1.2.1
  file_picker: ^1.4.3+2
  dio: 2.1.16
  flare_flutter: ^1.6.4
  line_icons: ^0.2.0
  cached_network_image: ^2.0.0-rc
  new_geolocation: ^1.0.0
  permission_handler: '^4.2.0+hotfix.2'
  badges: ^1.1.0
  intl: 0.16.0
  flutter_swiper: ^1.1.6
  provider: ^2.0.0
  share: ^0.6.3+5
  toast: ^0.1.5
  animated_text_kit: ^2.0.0
  video_player: ^0.10.5+2
  story_view: ^0.11.2
  flutter_i18n: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  build_web_compilers: any

```

*fluter --version*
```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (11 days ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

*build*

`flutter build apk --release -v`

*output*

```
[   +3 ms] Running Gradle task 'assembleAarRelease'... (completed in 4,2s)
[   +6 ms] √ Built build\app\outputs\repo.
[   +1 ms] Building plugin flutter_plugin_android_lifecycle...
[   +8 ms] Running Gradle task 'assembleAarRelease'...
[   +7 ms] gradle.properties already sets `android.enableR8`
[  +25 ms] Using gradle from C:\\Users\\srburton\\AppData\\Roaming\\Pub\\Cache\\hosted\\pub.dartlang.org\\flutter_plugin_android_lifecycle-1.0.6\\android\gradlew.bat.
[   +1 ms] executing: [C:\\Users\\srburton\\AppData\\Roaming\\Pub\\Cache\\hosted\\pub.dartlang.org\\flutter_plugin_android_lifecycle-1.0.6\\android\]
C:\\Users\\srburton\\AppData\\Roaming\\Pub\\Cache\\hosted\\pub.dartlang.org\\flutter_plugin_android_lifecycle-1.0.6\\android\gradlew.bat -I=C:\src\flutter\packages\flutter_tools\gradle\aar_init_script.gradle -Pflutter-root=C:\src\flutter
-Poutput-dir=C:\Users\srburton\Documents\Projetos\waygo.app\build\app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+2543 ms]
                    FAILURE: Build failed with an exception.

                    * Where:
                    Build file 'C:\Users\srburton\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\build.gradle' line: 22

                    * What went wrong:
                    A problem occurred evaluating root project 'flutter_plugin_android_lifecycle'.
                    > Failed to apply plugin [id 'com.android.library']
                       > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in
                       C:\Users\srburton\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 2s
[   +3 ms] Running Gradle task 'assembleAarRelease'... (completed in 2,6s)
[   +1 ms] 
           FAILURE: Build failed with an exception.
           
           * Where:
           Build file 'C:\Users\srburton\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\build.gradle' line: 22
           
           * What went wrong:
           A problem occurred evaluating root project 'flutter_plugin_android_lifecycle'.
           > Failed to apply plugin [id 'com.android.library']
              > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in
C:\Users\srburton\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 2s
           
[  +10 ms] "flutter apk" took 98.213ms.
The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:726:7)
#2      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#3      _rootRunBinary (dart:async/zone.dart:1146:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#8      Future._completeError (dart:async/future_impl.dart:532:5)
#9      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#10     buildGradleAar (package:flutter_tools/src/android/gradle.dart)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#12     _rootRunUnary (dart:async/zone.dart:1134:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#20     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#22     _rootRunUnary (dart:async/zone.dart:1134:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#28     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#29     _rootRunUnary (dart:async/zone.dart:1134:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#34     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#35     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```
