### ISSUE TITLE
upgrade dependency of flutter_localization 

### ISSUE THREAD

**Issue by mohammadne** [flutter/flutter#51561]
```
Because dart_json_mapper >=1.3.3 depends on intl ^0.16.1 and every version of flutter_localizations from sdk depends on intl 0.16.0, dart_json_mapper >=1.3.3 is incompatible with flutter_localizations from sdk.
```
I wan't to use dart_json_mapper which depends on intl:16.0.1 because of some problems but as you know , flutter_localization depends on intl:16.0.0 , so I can't get it to work.
Thanks.

**Comment by TahaTesser** [comment]
Hi @mohammadne 
Try this
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dart_json_mapper: any
  intl: any
```
Thank you

**Comment by mohammadne** [comment]
that is not the solution .
version solving is not failed but:
some features like ```JsonMapperAdapter``` will added in version ```1.5.2``` but with your solution it fails.
means it doesn't use version ```1.5.2```
I want to use latest version of ```dart_json_mapper```

**Comment by mohammadne** [comment]
my problem is that ```flutter_localizations``` depends on ```intl:16.0.0```
you should upgrade it to ```intl:16.0.1```

**Comment by TahaTesser** [comment]
Hi @mohammadne 
Try this, you can override intl to support both `flutter_localizations` and `dart_json_mapper` latest version
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dart_json_mapper: ^1.5.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dependency_overrides:
    intl: ^0.16.1
```
Thank you
