### ISSUE TITLE
Ability to merge application pubspec.yaml with flavor specific versions

### ISSUE THREAD

**Issue by ened** [flutter/flutter#51751]
## Use case

A white labeled application needs to be published for different package IDs, version numbers and assets.

While basic building of the application flavors can be accomplished by using `flutter build ... --flavor xxx`, a key component like pubspec.yaml can not be customized as detailed as needed. Only the version name and build number can be specified on the command line.

The assets part is not easy to maintain for separate applications.

## Proposal

`flutter --flavor xxx` should resolve the following pubspec.yaml files by default:
- pubspec.yaml
- pubspec.xxx.yaml

The keys from `pubspec.xxx.yaml` should be merged into pubspec.yaml.
Existing non-array keys (name, version) should be overwritten.
Maps and Array keys should be extended.
E.g.:
If pubspec.yaml contains:
```
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/sounds/
```
And pubspec.xxx.yaml contains:
```
flutter:
  assets:
    - assets/fonts/xxx/
    - assets/icons/xxx/
```

Then the resulting flutter.assets path should be parsed as:
```
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/xxx/
    - assets/icons/
    - assets/icons/xxx/
    - assets/sounds/
```

This would be a extension on how flutter handles pubspec.yaml and should probably not become part of the generic `pub` command.
