### ISSUE TITLE
Attempt to execute code removed by Dart AOT compiler (TFA)

### ISSUE THREAD

**Issue by fluttdev** [flutter/flutter#51828]
I see this error once I install the release apk on an Android device - "Attempt to execute code removed by Dart AOT compiler (TFA)". Maybe it's a dependency like in [this post](https://github.com/flutter/flutter/issues/39096) causing the issue.

## Steps to Reproduce
Stacktrace:
```
E/flutter ( 7030): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Attempt to execute method removed by Dart AOT compiler (TFA)
E/flutter ( 7030): #0      EvidenceQualityDao.replaceAll (package:biodiversity_v4/component/dao/EvidenceQualitiyDao.dart:0)
E/flutter ( 7030): #1      SyncService._doSync.<anonymous closure> (package:biodiversity_v4/component/service/SyncService.dart:61)
E/flutter ( 7030): <asynchronous suspension>
E/flutter ( 7030): #2      SyncService._iterateOverAtlasesWithLoginSaved.<anonymous closure> (package:biodiversity_v4/component/service/SyncService.dart:36)
E/flutter ( 7030): #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417)
E/flutter ( 7030): #4      ListIterator.moveNext (dart:_internal/iterable.dart:346)
E/flutter ( 7030): #5      Future.wait (dart:async/future.dart:393)
E/flutter ( 7030): #6      SyncService._iterateOverAtlasesWithLoginSaved (package:biodiversity_v4/component/service/SyncService.dart:34)
E/flutter ( 7030): <asynchronous suspension>
E/flutter ( 7030): #7      SyncService._doSync (package:biodiversity_v4/component/service/SyncService.dart:57)
E/flutter ( 7030): #8      SyncService.init (package:biodiversity_v4/component/service/SyncService.dart:27)
E/flutter ( 7030): #9      main (package:biodiversity_v4/main.dart:30)
E/flutter ( 7030): <asynchronous suspension>
E/flutter ( 7030): #10     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239)
E/flutter ( 7030): #11     _rootRun (dart:async/zone.dart:1126)
E/flutter ( 7030): #12     _CustomZone.run (dart:async/zone.dart:1023)
E/flutter ( 7030): #13     _runZoned (dart:async/zone.dart:1518)
E/flutter ( 7030): #14     runZoned (dart:async/zone.dart:1502)
E/flutter ( 7030): #15     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231)
E/flutter ( 7030): #16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307)
E/flutter ( 7030): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174)
```

Invokation:
`await SyncService().init();`

Involved classes where the problem occurs:

```
import 'dart:async';
import 'dart:io';

import 'package:biodiversity_v4/component/dao/EvidenceMethodDao.dart';
import 'package:biodiversity_v4/component/dao/EvidenceQualitiyDao.dart';
import 'package:biodiversity_v4/component/dao/SavedLoginDao.dart';
import 'package:biodiversity_v4/component/dao/SightingReportDao.dart';
import 'package:biodiversity_v4/component/dao/SpeciesDao.dart';
import 'package:biodiversity_v4/component/dao/shared/DbConnection.dart';
import 'package:biodiversity_v4/component/entity/Atlas.dart';
import 'package:biodiversity_v4/component/entity/SavedLogin.dart';
import 'package:biodiversity_v4/component/entity/SightingReport.dart';
import 'package:biodiversity_v4/component/entity/dto/UserInformationResponse.dart';
import 'package:biodiversity_v4/component/service/ReportService.dart';
import 'package:biodiversity_v4/component/service/UserService.dart';

class SyncService {
  static final SyncService _singleton = SyncService._internal();

  factory SyncService() {
    return _singleton;
  }

  SyncService._internal();

  Future<void> init() async {
    await _doSync();
  }

  Future<void> _iterateOverAtlasesWithLoginSaved(Function atlasFunction, {Function appConfigurationFunction}) async {
    DbConnection dbConnectionAppConfiguration = DbConnection(dbType: DbType.appConfiguration);
    List<Atlas> atlasesWithLoginSaved = await SavedLoginDao(dbConnectionAppConfiguration).getAtlasesWithLoginSaved();

    await Future.wait(atlasesWithLoginSaved.map((atlas) async {
      DbConnection dbConnectionAtlas = DbConnection(dbType: DbType.atlas, atlas: atlas, isTemporaryConnection: true);
      await atlasFunction(dbConnectionAtlas, atlas);

      if (appConfigurationFunction != null) await appConfigurationFunction(dbConnectionAppConfiguration, atlas);
    }));
  }

  Future<List<SightingReport>> syncSightingReports() async {
    _iterateOverAtlasesWithLoginSaved((dbConnection, atlas) async {
      SightingReportDao sightingReportDao = new SightingReportDao(dbConnection);

      List<SightingReport> sightingReportsToSync =
          await sightingReportDao.getSightingReportWithStatus(SightingReportStatus.notSynchronized);

      if (sightingReportsToSync.isNotEmpty)
        sightingReportsToSync.map((sightingReport) => sightingReport.submit(atlas: atlas));
    });
  }

  Future<void> _doSync() async {
    ReportService reportService = new ReportService();

    await _iterateOverAtlasesWithLoginSaved((dbConnection, atlas) async {
      try {
        //eagerError = true: completes with an error immediately on the first error from one of the futures
        await Future.wait([
          new SpeciesDao(dbConnection).replaceAll(await reportService.getAllSpecies(atlas: atlas)),
          new EvidenceQualityDao(dbConnection).replaceAll(await reportService.getAllEvidenceQualities(atlas: atlas)),
          new EvidenceMethodDao(dbConnection).replaceAll(await reportService.getAllEvidenceMethods(atlas: atlas))
        ], eagerError: true);
      } on SocketException catch (e) {
        //device is offline
        print(e);
      }
    }, appConfigurationFunction: (dbConnection, atlas) async{
          SavedLoginDao savedLoginDao =  new SavedLoginDao(dbConnection);
          SavedLogin savedLogin = await savedLoginDao.getLogin(atlas: atlas);
          UserInformationResponse userInformationResponse = await new UserService().getUserInformation(savedLogin);

          savedLogin.firstname = userInformationResponse.firstname;
          savedLogin.lastname = userInformationResponse.lastname;

          await savedLoginDao.saveLogin(savedLogin);
    });
  }
}
```
EvidenceQualiityDao:

```
Future<void> replaceAll(List<EvidenceQuality> evidenceQualities) async {
    final db = await dbConnection.getDatabase();
    return db.delete(TABLE_NAME).then((i) => evidenceQualities
        .forEach((EvidenceQuality evidenceQuality) async => await db.insert(TABLE_NAME, evidenceQuality.toMap(), conflictAlgorithm: ConflictAlgorithm.replace)));
  }
```

pubspec.yaml:
```
name: biodiversity_v4
description: Biodiversity Warehouse Cross Platform App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.0+4
  sqflite:
  path:
  crypto: ^2.1.3
  flutter_typeahead: ^1.8.0
  image_picker: ^0.6.3+4
  google_maps_flutter: ^0.5.24+1
  http_parser: ^3.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/img/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale de-DE)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter_windows_v1.9.1+hotfix.5-stable\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pschu\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\pschu\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.42.1)
    • VS Code at C:\Users\pschu\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

</details>
