### ISSUE TITLE
[Web] Dart 2.7.1 is incompatible with your dependencies' SDK constraints.

### ISSUE THREAD

**Issue by Kassan424kh** [flutter/flutter#52095]
Hy Flutters,

I try now to start a server with webdev in my application but it can't,
if I type this command he gives me this error
▶ webdev serve
```BASH
webdev could not run for this project.
Dart 2.7.1 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.
```
What should I do to fix it or get it works :).

▶ flutter doctor -v: 
```BASH
[✓] Flutter (Channel master, v1.15.17-pre.4, on Mac OS X 10.14.6 18G103, locale
    en-GB)
    • Flutter version 1.15.17-pre.4 at /Users/kkhalil/flutter
    • Framework revision c4525aebd0 (2 hours ago), 2020-03-06 02:56:02 -0500
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kkhalil/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/kkhalil/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] Android Studio (version 3.5)
    • Android Studio at /Users/kkhalil/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android
      Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Users/kkhalil/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.14.6 18G103
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

▶ pubspec.yaml
```YAML
name: flutter_berichtsheft_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  google_fonts: ^0.3.2
  outline_material_icons: ^0.1.1
  flutter_datetime_picker: ^1.3.4
  intl: ^0.16.1
  http: ^0.12.0+4
  sqflite: ^1.2.0
  path: ^1.6.4
  loading: ^1.0.2
  dio: ^3.0.8
  jose: ^0.1.2
  pdf: ^1.5.0
  printing: ^3.1.0
  js: ^0.6.1+1
  crypted_preferences: ^0.0.2

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/LightLogoWithText.png
    - assets/images/DarkLogoWithoutText.png
    - assets/images/DarkLogoWithText.png
    - assets/images/LightLogoWithoutText.png
    - assets/images/profile_light.png
    - assets/images/profile_dark.png
    - assets/images/null_delet_dark.png
    - assets/images/null_delet_light.png
    - assets/images/null_reports_dark.png
    - assets/images/null_reports_light.png
    - assets/images/null_search_dark.png
    - assets/images/null_search_light.png
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/arial.ttf
```
