### ISSUE TITLE
Schema validation: Property 'uses-material-design' is not allowed

### ISSUE THREAD

**Issue by andesappal** [flutter/flutter#52252]
From this definition, 
```
name: mobile_
description: Mobile...

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  url_launcher: 5.4.2
  meta: ^1.1.6
  equatable: ^1.0.0
  flutter_bloc: any
  common:
    path: ../common
  user:
    path: ../user
  firebase_core: 0.4.4  
  firebase_auth: 0.15.3
  google_sign_in: ^4.0.1+3
  rxdart: any
  bloc: any

dev_dependencies:
  flutter:
    uses-material-design: true
    ˆˆˆˆˆˆˆˆˆˆˆˆˆˆˆˆˆˆˆˆˆˆˆˆ
    (Schema validation: Property 'uses-material-design' is not allowed)
```

I get, beside the issue above, the message below
```
/Users/johnappleseed/development/flutter/bin/flutter --no-color packages get
Running "flutter pub get" in mobile_...                      
Because mobile_ depends on both flutter from sdk and flutter from uses-material-design, version solving failed.
pub get failed (1; Because mobile_ depends on both flutter from sdk and flutter from uses-material-design, version solving failed.)
Process finished with exit code 1
```

**Comment by andesappal** [comment]
Strangely, from another project with pubspec.yaml
```
name: m
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: 5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    uses-material-design: true
```
I have no issues.
