### ISSUE TITLE
[webview_flutter] Google console Crashes report java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by duongtruong12** [flutter/flutter#52712]
After upgrade to newest version flutter it seem like my users get crashed a lot. Primarily on android 9, android 8 and android 10 got crashed too but not much

#### The details crash is:
```
java.lang.UnsupportedOperationException: 
  at io.flutter.embedding.engine.plugins.shim.ShimRegistrar.view (ShimRegistrar.java:4)
  at io.flutter.plugins.webviewflutter.WebViewFlutterPlugin.registerWith (WebViewFlutterPlugin.java:10)
  at io.flutter.plugins.GeneratedPluginRegistrant.registerWith (GeneratedPluginRegistrant.java:139)
  at jp.techforlife.wellgo.Application.registerWith (Application.java)
  at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.b (HeadlessTask.java:120)
  at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.a (HeadlessTask.java:4)
  at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run (HeadlessTask.java)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:359)
  at android.app.ActivityThread.main (ActivityThread.java:7418)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:935)
```

#### My plugin
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation: ^0.17.7
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+1
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.10
  google_sign_in: ^4.1.1
  oauth2: ^1.5.0
  io: ^0.3.3
  url_launcher: ^5.4.1
  path_provider: ^1.5.1
  background_fetch: ^0.5.4
  connectivity: ^0.4.6+2
  charts_flutter: ^0.8.1
  package_info: ^0.4.0+13
  flutter_circular_chart: ^0.1.0
  launch_review: ^2.0.0
  frideos: ^1.0.0+1
  dio: ^3.0.8
  webview_flutter: ^0.3.19+9
  oauth1: ^1.0.4
  provider: ^4.0.2
  flutter_webview_plugin: ^0.3.10+1
  flutter_barcode_scanner: ^0.1.7
  quiver: ^2.0.5
  logger: ^0.8.3
  flutter_advanced_networkimage: ^0.6.2
  flutter_datetime_picker: ^1.3.4
  flutter_linkify: ^3.1.0
  flutter_svg: 0.17.1
  mp_chart: 0.1.4
  auto_size_text: 2.1.0
  dots_indicator: ^1.1.0
  e2e:
    path: ../plugin/e2e
  flutter_appavailability:
    git:
      url: "https://github.com/pichillilorenzo/flutter_appavailability.git"
      ref: "a9e2fa38d8c9334c89d13c69c69db29030c926d5"

  android_alarm_manager:
    path: ../plugin/android_alarm_manager

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
  flutter_driver:
      sdk: flutter
  test: any


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
```

#### My flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/macos/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macos/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • macos’s iPhone • 6aabac61dc97b149689a56d3718b6ae20c79bf88 • ios • iOS
      13.3.1

• No issues found!
```
