### ISSUE TITLE
Packages GET failes with "The plugin `flutter_plugin_android_lifecycle` doesn't"

### ISSUE THREAD

**Issue by julien100000** [flutter/flutter#52739]
## Steps to Reproduce

`1. Run flutter pub get`
`2. Error comes in console`

Error:

> The plugin flutter_plugin_android_lifecycle doesn't have a main class defined in C:\Users\julie\Documents\biodiversity\flutter_windows_v1.9.1+hotfix.4-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\src\main\java\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.java or C:\Users\julie\Documents\biodiversity\flutter_windows_v1.9.1+hotfix.4-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\src\main\kotlin\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.kt. This is likely to due to an incorrect androidPackage: io.flutter.plugins.flutter_plugin_android_lifecycle or mainClass entry in the plugins pubspec.yaml.
If you are the author of this plugin, fix the androidPackage entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.

The error disappears when I use version 0.6.0 of the ImagePicker plugin.

pubspec.yaml:
```
name: biodiversity_v4
description: Biodiversity Warehouse Cross Platform App

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.1+3

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.0+4
  sqflite: ^1.3.0
  path: ^1.6.4
  crypto: ^2.1.3
  flutter_typeahead: ^1.7.0
  image_picker: 0.6.3+4
  google_maps_flutter: 0.5.21+14
  http_parser: ^3.1.3

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.9




flutter:
  assets:
    - assets/
    - assets/img/

  uses-material-design: true
```

Flutter Doctor:

```
[√] Flutter (Channel dev, v1.15.21, on Microsoft Windows [Version 10.0.17134.1365], locale de-DE)
    • Flutter version 1.15.21 at C:\Users\julie\Documents\biodiversity\flutter_windows_v1.9.1+hotfix.4-stable\flutter
    • Framework revision e2b4edd286 (4 days ago), 2020-03-13 02:46:02 -0400
    • Engine revision d7a00b8b09
    • Dart version 2.8.0 (build 2.8.0-dev.14.0 eb9c26bd37)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\julie\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.


</details>
```
