### ISSUE TITLE
Flutter build appbundle fails

### ISSUE THREAD

**Issue by sampathkumar7** [flutter/flutter#52883]
After updating flutter 
`flutter build appbundle` fails but `flutter run --release` works

```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

```
org.gradle.jvmargs=-Xmx1536M

android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
```

```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
```

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0  
  facebook_audience_network: ^0.5.0
  flutter_local_notifications: ^0.8.4
  android_alarm_manager: ^0.4.4
  share: ^0.6.3+6
  firebase_dynamic_links: ^0.5.0+6
  http: ^0.12.0+2
  youtube_player_flutter: ^6.1.0+4  
  shared_preferences: ^0.5.6+3
  device_id: ^0.2.0
  mailer: ^3.0.4
  flutter_pollfish: ^0.2.3
  ```
