### ISSUE TITLE
Flutter TMS-90809: Deprecated API Usage IWebView url_launcher: ^5.4.2

### ISSUE THREAD

**Issue by daniele777** [flutter/flutter#52965]
My  pubspec.yaml dependeces as... 

```yaml
 cupertino_icons: ^0.1.2
  rxdart: ^0.22.6
  rflutter_alert: ^1.0.2
  url_launcher: ^5.4.2
  map_launcher: ^0.4.3
  social_share_plugin: ^0.3.0+1
  image_picker: ^0.6.3+4
  flutter_email_sender: ^2.2.2
```

Seems problem was url_launcher...
No other problem only that ...Anyone fix that problem? thx

after running grep 

```bash
grep -r UIWebView ios/Pods/ 

Binary file ios/Pods//TwitterKit/iOS/TwitterKit.framework/TwitterKit matches
ios/Pods//TwitterKit/iOS/TwitterKit.framework/Headers/TWTRTweet.h: *  Suitable for loading in a `UIWebView`, `WKWebView` or passing to Safari:

**greb edit this line**

**

The permalink URL for this Tweet.
Suitable for loading in a UIWebView, WKWebView or passing to Safari:
[[UIApplication sharedApplication] openURL:tweet.permalink];
*/
@Property (nonatomic, copy, readonly) NSURL *permalink;
```

what mean....help
