### ISSUE TITLE
Flutter application blurred screen & garbled page problem

### ISSUE THREAD

**Issue by waitwalker** [flutter/flutter#52991]
Recently, I have encountered some strange problems in the development of app with Flutter. At present, I am developing in the master branch, and with the command of flutter build apk to create android package. After installation, there will be the problem of blurred screen & garbled page. The specific reason I haven't found. And iOS also meets similar problems.
Then I tryed to switch to the stable branch for packaging, and find that the stable branch can solve the blurred screen & garbled page problem, but iOS will encounter other problems.

#### **1. The master branch has blurred screen & garbled page problem.**
[screenshot 1](https://raw.githubusercontent.com/waitwalker/Resources/master/Flutter/problem/1.jpg)
[screenshot 2](https://raw.githubusercontent.com/waitwalker/Resources/master/Flutter/problem/2.jpg)
Operation steps:
1. in my project, there is a video player (Chewie: ^ 0.9.10). Open a video at random, play it for about 20s, and then click the screen to have such a problem
2. or turn on the camera (image_picker: ^ 0.6.3 + 4) and return to take a picture
3. similar problems may occur in other operations
4. steps 1 & 2 are very likely to occur

### Project pependences:
```
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2


  # 系统分享插件
  share_extend: ^1.1.0

  font_awesome_flutter: ^8.0.1
  rxdart: ^0.21.0
  flutter_masked_text: ^0.6.0
  webview_flutter: ^0.3.5+2
  tripledes: ^2.1.0
  json_annotation: ^2.0.0
  dio: ^3.0.9
  shared_preferences: ^0.4.3
  sqflite: any
  path_provider: ^1.3.0
  flare_flutter: ^1.3.3
  # fluwx: ^0.6.1
  # flutter_alipay: "^0.1.0"
  # recorder_wav: ^0.1.0
  camera: ^0.5.7+2
  fluttertoast: ^3.0.3
  flutter_native_image: ^0.0.5+2


  logging: ^0.11.3+2
  # intl: ^0.16.0
  url_launcher: ^5.0.2
  connectivity: ^0.4.2
  encrypt: ^0.2.0+2
  video_player: ^0.10.0+4
  oauth2: ^1.2.3
  flutter_redux: ^0.5.3
  event_bus:  ^1.0.1
  scoped_model: ^1.0.1
  flutter_spinkit: ^3.1.0
  lottie_flutter: ^0.2.0
  flutter_easyrefresh: ^1.2.7
  image_picker: ^0.6.3+4
  # image_crop: ^0.3.0
  image_cropper: ^1.0.2
  #flutter_datetime_picker: ^1.1.5
  flutter_datetime_picker:
    git:
      url: https://github.com/waitwalker/flutter_datetime_picker.git
  flutter_downloader: 1.1.6
  permission_handler: ^4.0.0
  package_info: ^0.4.0+2
  flutter_rating: ^0.0.2
  device_info: ^0.4.0+1
  # timeline_list: ^0.0.3
  # percent_indicator: ^1.0.15
  flutter_localizations:
    sdk: flutter
  intl_translation: ^0.17.4
  shimmer: ^1.0.0
  quiver: ^2.0.3
  equatable: ^0.2.0
  image_picker_saver: ^0.3.0
  udid: ^0.0.2
  screen: ^0.0.5
  path_drawing: ^0.4.1
  flutter_svg: ^0.17.3+1
  date_format: ^1.0.8
  pdf_viewer_plugin: ^1.0.0+2
  table_calendar: ^2.0.1
  paging: ^0.1.0
  photo_view: ^0.8.0
  http: ^0.12.0+4

  # 转场动画
  page_transition: ^1.1.5

  # 刷新
  pull_to_refresh: ^1.5.7

  # 日志信息输出
  logger: ^0.8.3

  # 下拉刷新 上拉加载更多插件
  #pull_to_refresh:
    #git:
      #url: https://github.com/waitwalker/flutter_pulltorefresh.git
      #ref: 'master'

  # 播放器
  #chewie: ^0.9.10
  chewie:
    git:
      url: https://github.com/waitwalker/chewie.git
      ref: 'master'
  jpush_flutter: 
    git:
      url: https://github.com/waitwalker/jpush-flutter-plugin.git
      ref: 'master'
  wangxiao_plugin:
    path: ./wangxiao_plugin
  flutter_webview_plugin: 
    git:
      url: https://github.com/laxian/flutter_webview_plugin.git
      ref: 'master'
  flutter_umeng_analytics:
    git: 
      url: https://github.com/waitwalker/flutter_umeng_analytics.git
      ref: 'master'

  real_rich_text:
    git:
      url: https://github.com/waitwalker/RealRichText.git
      ref: 'master'

dependency_overrides:
  video_player:
    path: ./video_player
  path_drawing: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  json2entity: ^1.0.8


flutter:
  uses-material-design: true

  assets:
    - static/images/1.5x/
    - static/images/2.0x/
    - static/images/3.0x/
    - static/images/
    - static/svgs/
    - assets/

  fonts:
    - family: aliIconFont
      fonts:
        - asset: static/font/iconfont.ttf
```

### Flutter doctor:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.16.1-pre.18, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.1)
[✓] Connected device (1 available)

• No issues found!
```

最近用flutter开发遇到一些奇怪的问题,目前在master分支进行开发,运行flutter build apk 打出来的Android包,安装之后会出现花屏&页面乱码问题,具体原因我还没有找到,iOS打出来的包也遇到类似问题.
于是切换到stable分支进行打包,发现stable分支可以解决Android花屏&乱码问题,但是iOS的会遇到其他问题
主要问题:
1.master分支会出现花屏&页面乱码问题
[screenshot 1](https://raw.githubusercontent.com/waitwalker/Resources/master/Flutter/problem/1.jpg)
[screenshot 2](https://raw.githubusercontent.com/waitwalker/Resources/master/Flutter/problem/2.jpg)
操作步骤:
1).我的项目中有视频播放器(chewie: ^0.9.10),随便打开一个视频,播放20s左右,然后点击屏幕就会出现这样的问题.
2).或者打开相机(image_picker: ^0.6.3+4)拍照后返回也会出现这种情况.
3).其他操作也可能出现类似问题.
4).步骤1&2出现的几率很大.
2.stable分支iOS无法运行打包问题[52084](https://github.com/flutter/flutter/issues/52084).
![1](https://user-images.githubusercontent.com/16695783/77217099-a0f71f00-6b5a-11ea-8e78-41ccfe8b342a.jpg)
![2](https://user-images.githubusercontent.com/16695783/77217101-a2c0e280-6b5a-11ea-8cbc-9febaa6fb4a2.jpg)
