### ISSUE TITLE
Allow include other yaml file in pubsepc.yaml to share the version between flutter packages

### ISSUE THREAD

**Issue by littleGnAl** [flutter/flutter#53109]
## Use case
On Android, it's so common that share versions between different modules by storing the version in the individual Gradle file or inside the `buildscript` block, like how [the sun-flower sample](https://github.com/android/sunflower/blob/e5fdb5ec55311449b507b6215d6def3c1cd884f6/build.gradle#L26) do. We have spilt our Flutter APP to multiple packages by business logic. There's no easy for us to update the dependency version, but change the version for each package one by one.  It's good to have feature that allows sharing versions by including a common YAML file in the pubspec.yaml for the multiple packages project in Flutter. 

## Proposal
Say I have a `versions.yaml` file in the root of the project:
```
|__mypackage1
|   |__lib
|   |   |__main.dart
|   |__pubspec.yaml
|__versions.yaml
```
I can add the version in the `versions.yaml`, and make it as anchors, such like:
```yaml
# versions.yaml

analyzer_version: &analyzer_version ^0.39.4
```

so I can include the `versions.yaml` to my pubsepc.yaml file and use the aliases:
```yaml
# mypackage1/pubspec.yaml
include: ../versions.yaml

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: *analyzer_version
  ...
```
