### ISSUE TITLE
/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.h:7:45: error: no type or protocol     named 'FlutterPlugin'     @interface FLTURLLauncherPlugin : NSObject <FlutterPlugin>

### ISSUE THREAD

**Issue by azhar-rafiq** [flutter/flutter#53215]
#ask help how to fix this error when flutter build ios :'(

**How to Reproduce:**
1. flutter build ios
2. Build Failed

**Problem with:**
url_launcher-5.4.2

**Cronology:**
The apps is works fine in Android (device and simulator) and iOS (simulator).
Build APK release in Android Studio works fine.
Build ios release with XCode v11.3.1 (11C504) FAILED WITH 20 ERRORs.

**Flutter Doctor:**
```
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
`
```

Error Log:
```
`                                                  
Xcode build done.                                           99.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:7:
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.h:7:45: error: no type or protocol
    named 'FlutterPlugin'
    @interface FLTURLLauncherPlugin : NSObject <FlutterPlugin>
                                                ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:12:28: error: unknown type name
    'FlutterResult'
    @property(copy, nonatomic) FlutterResult flutterResult;
                               ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:12:1: error: property with 'copy'
    attribute must be of object type
    @property(copy, nonatomic) FlutterResult flutterResult;
    ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:25:24: warning: incompatible
    pointer to integer conversion assigning to 'int' from '__strong id' [-Wint-conversion]
        self.flutterResult = result;
                           ^ ~~~~~~
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:37:23: error: called object type
    'int' is not a function or function pointer
        self.flutterResult(nil);
        ~~~~~~~~~~~~~~~~~~^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:39:25: error: use of undeclared
    identifier 'FlutterError'
        self.flutterResult([FlutterError
                            ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:66:41: error: no type or protocol
    named 'FlutterPluginRegistrar'
    + (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
                                            ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:74:27: error: expected a type
    - (void)handleMethodCall:(FlutterMethodCall *)call result:(FlutterResult)result {
                              ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:74:60: error: expected a type
    - (void)handleMethodCall:(FlutterMethodCall *)call result:(FlutterResult)result {
                                                               ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:110:20: error: expected a type
                 call:(FlutterMethodCall *)call
                       ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:111:20: error: expected a type
               result:(FlutterResult)result {
                       ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:132:53: error: expected a type
    - (void)launchURLInVC:(NSString *)urlString result:(FlutterResult)result API_AVAILABLE(ios(9.0)) {
                                                        ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:144:33: error: expected a type
    - (void)closeWebViewWithResult:(FlutterResult)result API_AVAILABLE(ios(9.0)) {
                                    ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:67:3: error: use of undeclared
    identifier 'FlutterMethodChannel'
      FlutterMethodChannel *channel =
      ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:67:25: error: use of undeclared
    identifier 'channel'
      FlutterMethodChannel *channel =
                            ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:68:8: error: use of undeclared
    identifier 'FlutterMethodChannel'
          [FlutterMethodChannel methodChannelWithName:@"plugins.flutter.io/url_launcher"
           ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:71:14: error: no visible
    @interface for 'NSObject' declares the selector 'addMethodCallDelegate:channel:'
      [registrar addMethodCallDelegate:plugin channel:channel];
       ~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:75:24: error: property 'arguments'
    not found on object of type '__strong id'
      NSString *url = call.arguments[@"url"];
                           ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:76:42: error: property 'method'
    not found on object of type '__strong id'
      if ([@"canLaunch" isEqualToString:call.method]) {
                                             ^
    /direktori/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/ios/Classes/FLTURLLauncherPlugin.m:77:11: error: called object type
    'id' is not a function or function pointer
        result(@([self canLaunchURL:url]));
        ~~~~~~^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    1 warning and 20 errors generated.
`
```

**Comment by iapicca** [comment]
Hi @azhar-rafiq 
can you please provide your full `flutter build ios --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by azhar-rafiq** [comment]
pubspec.yaml:
```
name: app_name
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.9.1+912

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+1
  cloud_firestore: ^0.13.0+1

  google_sign_in: ^4.0.1+3
  firebase_auth: ^0.11.1
  firebase_database:
  http:
  intl:
  url_launcher: ^5.4.2
  share: 0.6.0+1

  audioplayers: ^0.14.2

  package_info: 0.4.0+13
  flutter_html: 0.11.1
  intro_views_flutter: '^2.8.0'
  lottie: 0.3.2
  flutter_youtube: "^2.0.0"
  shared_preferences: 0.5.6+3
  tutorial_coach_mark: 0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo
  #  - images/a_dot_ham.jpeg
```

> Hi @azhar-rafiq
> can you please provide your full `flutter build ios --verbose`
> and your `pubspec.yaml`
> or if possible a reproducible minimal code sample.
> Thank you
