### ISSUE TITLE
no longer needed

### ISSUE THREAD

**Issue by andyyyyyyyyyyyyyyyy** [flutter/flutter#53474]
no longer needed

**Comment by iapicca** [comment]
Hi @andyyyyyyyyyyyyyyyy 
can you please provide your `flutter doctor -v` , 
your `flutter build appbundle --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by andyyyyyyyyyyyyyyyy** [comment]
> Hi @andyyyyyyyyyyyyyyyy
> can you please provide your `flutter doctor -v` ,
> your `flutter build appbundle --verbose`
> and your `pubspec.yaml`
> or if possible a reproducible minimal code sample.
> Thank you

Hi @iapicca  , 

`flutter doctor -v : `


```
$ flutter doctor -v
[√] Flutter (Channel master, v1.15.4-pre.169, on Microsoft Windows [Version 10.0.18363.720], locale en-SG)
    • Flutter version 1.15.4-pre.169 at D:\flutter
    • Framework revision 492fb6381e (5 weeks ago), 2020-02-25 22:29:16 -0500
    • Engine revision 888a62cf22
    • Dart version 2.8.0 (build 2.8.0-dev.10.0 73f6d15665)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Andy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\Andy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```


> flutter build appbundle --verbose

https://drive.google.com/file/d/123jfG1EWKgaAB4euMfJjFLD-A0s7QXV0/view?usp=sharing


> pubspecl.yaml

```
name: ninjavpn
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+4045

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vpn: ^0.7.0
  font_awesome_flutter: 8.4.0
  country_icons: 1.1.1
  provider: 3.2.0
  loading_overlay: 0.2.0

  cloud_firestore: 0.13.4+1
  intro_slider: ^2.2.9
  firebase_auth: ^0.15.5+2
  shared_preferences: ^0.5.6+3

  package_info: ^0.4.0+16

  firebase_admob: 0.9.2+1
  rate_my_app: ^0.6.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/icon.png"
  adaptive_icon_background: "#03A9F4"
  adaptive_icon_foreground: "dev_assets/icon_adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
