### ISSUE TITLE
Flutter with FFI produces overly large APK

### ISSUE THREAD

**Issue by vaind** [flutter/flutter#53738]
(escalation of issue https://github.com/objectbox/objectbox-dart/issues/97)

## Steps to Reproduce
Created a minimal sample at https://github.com/vaind/objectbox-flutter-size using:
1. `flutter create with_objectbox` and `flutter create without_objectbox`
2. adding objectbox to `with_objectbox/podspec.yaml`
  ```
dependencies:
    objectbox: ^0.6.2

dev_dependencies:
    build_runner: ^1.0.0
    objectbox_generator: ^0.6.2
```
3. ran `flutter pub get` in both 
4. and built (release) using `flutter build apk` and `flutter build appbundle`

| project | apk | appbundle |
|----------|-------|----------------|
| with OBX |  40.7 MB | 17.3 MB |
| without OBX | 15.2 MB | 15.3 MB |

So it seems only APK is much larger than expected, appbundle is in line with the expected increase of about 2 MB for objectbox, FFI, etc.

Flutter version:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
```
