### ISSUE TITLE
Working Flutter App Releasing to Web causes Errors

### ISSUE THREAD

**Issue by oscarlindenbaum** [flutter/flutter#54192]
## Steps to Reproduce

1. Run `flutter build web`.
2. Copy whole build/web folder to website destination
3. Load website destination

**Actual results:**
The app won't load or display anything.
```
Uncaught ReferenceError: firebase is not defined
    at Object.a1Q (top_level.dart:80)
    at Object.a3z (cloud_firestore_web.dart:33)
    at cloud_firestore_web.dart:26
    at a_3.a (async_patch.dart:308)
    at a_3.$2 (async_patch.dart:333)
    at Object.Z (async_patch.dart:238)
    at Object.Ii (main.dart:8)
    at js_helper.dart:3221
    at js_helper.dart:3221
    at dartProgram (js_helper.dart:3221)
```

Firebase is configured correctly in index.html

I have also tried embeding the build index.html in an iframe.
<details>
<summary>Files</summary>

**Pubspec.yaml**

```
name: cook_safe_v3
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  url_launcher: ^5.4.2
  url_launcher_web:
  firebase_auth_web:
  flutter_custom_clippers:
  auto_size_text:
  font_awesome_flutter: ^8.8.1
  uuid:
  firebase:
  firebase_core:
  firebase_auth: 
  fluttertoast: 
  firebase_storage: 
  intl: 
  firebase_analytics: ^5.0.11
  firebase_database:
  cloud_firestore: ^0.13.4+2
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

**index.html**

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="IE=Edge" http-equiv="X-UA-Compatible">
    <meta name="description" content="A new Flutter project.">

    <!-- iOS meta tags & icons -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="cook_safe_v3">
    <link rel="apple-touch-icon" href="icons/Icon-192.png">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="favicon.png" />

    <title>cook_safe_v3</title>
    <link rel="manifest" href="manifest.json">
</head>

<body>
    <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
    <script>
        if ('serviceWorker' in navigator) {
            window.addEventListener('load', function() {
                navigator.serviceWorker.register('flutter_service_worker.js');
            });
        }
    </script>
    <script src="main.dart.js" type="application/javascript"></script>

    <script src="https://www.gstatic.com/firebasejs/7.13.2/firebase-app.js"></script>

    <!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
    <script src="https://www.gstatic.com/firebasejs/7.13.2/firebase-analytics.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.13.2/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.13.2/firebase-firestore.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.13.2/firebase-storage.js"></script>
    <script>
        // Your web app's Firebase configuration
        var firebaseConfig = {
            apiKey: "",
            authDomain: "",
            databaseURL: "",
            projectId: "",
            storageBucket: "",
            messagingSenderId: "",
            appId: "",
            measurementId: ""
        };
        // Initialize Firebase
        firebase.initializeApp(firebaseConfig);
        firebase.analytics();
    </script>
</body>

</html>
```

</details>

<details>
  <summary>Logs</summary>

flutter run -d web --verbose (APP RUNS AS EXPECTED ON ALL PLATFORMS)

```
[  +22 ms] executing: [C:\Flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +92 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8f7327f83a3e094285163ae402c6f94190fc1674
[        ] executing: [C:\Flutter/] git describe --match *.*.* --first-parent --long --tags
[  +97 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[  +14 ms] 1.18.0-dev.3.0-4-g8f7327f83
[  +15 ms] executing: [C:\Flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +107 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [C:\Flutter/] git ls-remote --get-url origin
[  +61 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +109 ms] executing: [C:\Flutter/] git rev-parse --abbrev-ref HEAD
[ +112 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +110 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +20 ms] executing: C:\Users\Oscar\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +76 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +58 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +34 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +105 ms] Found plugin cloud_firestore at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4+2\
[  +38 ms] Found plugin cloud_firestore_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[  +12 ms] Found plugin firebase_analytics at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.11\
[  +40 ms] Found plugin firebase_auth at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[   +7 ms] Found plugin firebase_auth_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[  +42 ms] Found plugin firebase_core at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +6 ms] Found plugin firebase_core_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +40 ms] Found plugin firebase_database at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_database-3.1.3\
[   +5 ms] Found plugin firebase_storage at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-3.1.5\
[ +158 ms] Found plugin fluttertoast at C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluttertoast-4.0.1\[  +86 ms] Found plugin url_launcher at C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.4.2\[  +30 ms] Found plugin url_launcher_macos at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+4\
[   +8 ms] Found plugin url_launcher_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[ +112 ms] Found plugin cloud_firestore at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4+2\
[   +6 ms] Found plugin cloud_firestore_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[  +81 ms] Found plugin firebase_analytics at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.11\
[  +44 ms] Found plugin firebase_auth at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[   +4 ms] Found plugin firebase_auth_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[  +50 ms] Found plugin firebase_core at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[  +40 ms] Found plugin firebase_core_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +2 ms] Found plugin firebase_database at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_database-3.1.3\
[   +2 ms] Found plugin firebase_storage at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-3.1.5\
[  +10 ms] Found plugin fluttertoast at C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluttertoast-4.0.1\[  +63 ms] Found plugin url_launcher at C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.4.2\[  +62 ms] Found plugin url_launcher_macos at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+4\
[  +83 ms] Found plugin url_launcher_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[ +149 ms] Generating C:\Users\Oscar\OneDrive - University of
Birmingham\Coding\Flutter\cook_safe_top\cook_safe_v3\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +710 ms] Launching lib\main.dart on Web Server in debug mode...
[ +162 ms] Updating assets
[ +325 ms] Syncing files to device Web Server...
[  +15 ms] Found plugin cloud_firestore at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4+2\
[   +4 ms] Found plugin cloud_firestore_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[  +23 ms] Found plugin firebase_analytics at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.11\
[  +22 ms] Found plugin firebase_auth at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[   +6 ms] Found plugin firebase_auth_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[  +26 ms] Found plugin firebase_core at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +6 ms] Found plugin firebase_core_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +52 ms] Found plugin firebase_database at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_database-3.1.3\
[   +2 ms] Found plugin firebase_storage at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-3.1.5\
[  +18 ms] Found plugin fluttertoast at C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluttertoast-4.0.1\[ +115 ms] Found plugin url_launcher at C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.4.2\[ +126 ms] Found plugin url_launcher_macos at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+4\
[  +83 ms] Found plugin url_launcher_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[  +68 ms] Found plugin cloud_firestore at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4+2\
[  +61 ms] Found plugin cloud_firestore_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[ +111 ms] Found plugin firebase_analytics at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-5.0.11\
[   +5 ms] Found plugin firebase_auth at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.15.5+3\
[ +158 ms] Found plugin firebase_auth_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +6 ms] Found plugin firebase_core at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +4 ms] Found plugin firebase_core_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +57 ms] Found plugin firebase_database at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_database-3.1.3\
[   +2 ms] Found plugin firebase_storage at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_storage-3.1.5\
[   +7 ms] Found plugin fluttertoast at C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\fluttertoast-4.0.1\[ +120 ms] Found plugin url_launcher at C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.4.2\[  +51 ms] Found plugin url_launcher_macos at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+4\
[   +4 ms] Found plugin url_launcher_web at
C:\Users\Oscar\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[  +12 ms] Generating C:\Users\Oscar\OneDrive - University of
Birmingham\Coding\Flutter\cook_safe_top\cook_safe_v3\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +170 ms] <- reset
[ +110 ms] C:\Flutter\bin\cache\dart-sdk\bin\dart.exe
C:\Flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Oscar\AppData\Local\Temp\flutter_tool.2d33b4f7-78d4-11ea-a18f-a0c58962a77c\app.dill --libraries-spec
file:///C:/Flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\Oscar\OneDrive - University of
Birmingham\Coding\Flutter\cook_safe_top\cook_safe_v3\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
C:\Users\Oscar\AppData\Local\Temp\flutter_tools.2d33b4f8-78d4-11ea-a18f-a0c58962a77c --filesystem-scheme org-dartlang-app 
--initialize-from-dill build\cache.dill --platform
file:///C:/Flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill`

```
```

flutter analyze

`
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance          fields aren't final: FullPageResult.imageUrl, FullPageResult.recipeName, FullPageResult.rating,
          FullPageResult.description, FullPageResult.cookingTime, FullPageResult.preparationTime, FullPageResult.index -  
          lib\full_result_page.dart:16:7 - must_be_immutable
   info - Unused import: 'package:cook_safe_v3/lib/result.dart' - lib\lib\card_item.dart:3:8 - unused_import
   info - 'display1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design.
          The modern term is headline4. This feature was deprecated after v1.13.8. - lib\lib\card_item.dart:25:55 -       
          deprecated_member_use
   info - Unused import: 'package:cook_safe_v3/lib/card_item.dart' - lib\lib\message_viewer.dart:2:8 - unused_import
   info - Unused import: 'package:flutter/foundation.dart' - lib\lib\message_viewer.dart:5:8 - unused_import
   info - Name non-constant identifiers using lowerCamelCase - lib\lib\message_viewer.dart:23:17 -
          non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\lib\result.dart:43:8 - non_constant_identifier_names   
   info - Avoid empty statements - lib\lib\result.dart:49:3 - empty_statements
   info - Name non-constant identifiers using lowerCamelCase - lib\lib\result.dart:268:8 - non_constant_identifier_names  
   info - Name non-constant identifiers using lowerCamelCase - lib\lib\result.dart:480:8 - non_constant_identifier_names  
   info - Unused import: 'package:cook_safe_v3/lib/moderator_login.dart' - lib\main.dart:3:8 - unused_import
   info - Unused import: 'package:font_awesome_flutter/font_awesome_flutter.dart' - lib\main.dart:8:8 - unused_import     
   info - Unused import: 'lib/result.dart' - lib\main.dart:12:8 - unused_import
   info - 'await' applied to 'void', which is not a 'Future' - lib\main.dart:39:5 - await_only_futures
   info - 'await' applied to 'void', which is not a 'Future' - lib\main.dart:40:5 - await_only_futures
   info - 'await' applied to 'void', which is not a 'Future' - lib\main.dart:44:5 - await_only_futures
   info - 'await' applied to 'void', which is not a 'Future' - lib\main.dart:45:5 - await_only_futures
   info - 'await' applied to 'void', which is not a 'Future' - lib\main.dart:80:19 - await_only_futures
   info - 'await' applied to 'void', which is not a 'Future' - lib\main.dart:87:19 - await_only_futures
   info - 'await' applied to 'void', which is not a 'Future' - lib\main.dart:90:19 - await_only_futures
   info - 'await' applied to 'void', which is not a 'Future' - lib\main.dart:91:19 - await_only_futures
   info - Name non-constant identifiers using lowerCamelCase - lib\main.dart:104:10 - non_constant_identifier_names       
   info - Name types using UpperCamelCase - lib\moderator_login_page.dart:10:7 - camel_case_types
   info - Unused import: 'package:cook_safe_v3/lib/result.dart' - lib\top_bar.dart:2:8 - unused_import
   info - Unused import: 'package:flutter_custom_clippers/flutter_custom_clippers.dart' - lib\top_bar.dart:5:8 -
          unused_import
   info - Name non-constant identifiers using lowerCamelCase - lib\top_bar.dart:100:18 - non_constant_identifier_names    
   info - Unused import: 'package:cook_safe_v3/main.dart' - test\widget_test.dart:11:8 - unused_import
  error - The function 'MyApp' isn't defined - test\widget_test.dart:16:29 - undefined_function`

```

flutter doctor -v

```
[√] Flutter (Channel master, v1.18.1-pre.4, on Microsoft Windows [Version 10.0.18362.720], locale en-GB)
    • Flutter version 1.18.1-pre.4 at C:\Flutter
    • Framework revision 8f7327f83a (11 hours ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Oscar\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\Oscar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

```

</details>
