### ISSUE TITLE
connectivity_macos-0.1.0+2 Minimum supported Gradle version is 5.4.1. Current version is 4.10.2.

### ISSUE THREAD

**Issue by niranjan-b-prajapati** [flutter/flutter#54460]
## Steps to Reproduce

I hope anyone is able to reproduce this.

I have performed a `flutter upgrade` on my existing flutter project which was earlier on **v1.9.1+hotfix.6** to current stable release **v1.12.13+hotfix.9**. Post the upgrade I had run the app using VSCode on android and the app run successfully. 

But when I try to create a release build using `flutter build appbundle --release` it gives me the following error :

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Library/FlutterSdk/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_macos-0.1.0+2/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'connectivity'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /Library/FlutterSdk/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_macos-0.1.0+2/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s


The plugin connectivity_macos could not be built due to the issue above.
```

But when I opened Android Studio and Gradle sync the project it gave me below warning :

> Unsupported Modules Detected: Compilation is not supported for following modules: connectivity_macos, connectivity, file_picker, flutter_acpanalytics, flutter_acpcore, flutter_mailer, flutter_plugin_android_lifecycle, fluttertoast, path_provider, path_provider_macos, package_info, pdf_viewer_plugin, shared_preferences_macos, shared_preferences, shared_preferences_web, user_experior, url_launcher, adobe_analytics. Unfortunately, you can't have non-Gradle Java modules and Android-Gradle modules in one project.

But the app runs properly on the device connected. And the shocking point was I was able to create release build from the android studio.

I even tried to upgrade my project's Gradle version to 5.4.1 by changing it in the Gradle wrapper properties file. But still no success.

 Also tried `flutter pub cache repair`, `flutter clean` and then `flutter pub get`

<details>
  <summary>Logs</summary>

Running `flutter analyze` gives warnings and no errors.

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.2 19C57,
    locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at /Library/FlutterSdk/flutter
    • Framework revision f139b11009 (11 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Mi A3 • 5380418c1454 • android-arm64 • Android 9 (API 28)

• No issues found!

```

</details>

I hope anyone has got some solution to this. I tried to troubleshoot everything I can to resolve this issue from the last 2 days.

**Comment by TahaTesser** [comment]
Hi @niranjan-b-prajapati 
Please check out this [solution](https://github.com/flutter/flutter/issues/42082#issuecomment-564252848)

Thank you

**Comment by niranjan-b-prajapati** [comment]
@TahaTesser I saw that solution, I had already tried changing the version in my project's gradle-wrapper.properties file. Still, it returned me the same error. Flutter mentioned in the error to change the version in `/Library/FlutterSdk/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_macos-0.1.0+2/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip` file but I strongly feel this is not the correct way to do it, making changes to the Flutter SDK

**Comment by niranjan-b-prajapati** [comment]
> Hi @niranjan-b-prajapati
> Please check out this [solution](https://github.com/flutter/flutter/issues/42082#issuecomment-564252848)
> 
> Thank you

I had tried the solution mentioned in the link of making the version change in my project's gradle-wrapper.properties file but still, got the same error. 
Flutter gave me a suggestion with the error to make changes to `/Library/FlutterSdk/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_macos-0.1.0+2/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip` file but I strongly feel this is not the correct way to solve it, by making changes to FlutterSDK.

**Comment by TahaTesser** [comment]
hi @niranjan-b-prajapati 
Can you post your `pubspec.yaml`?
Thank you

**Comment by niranjan-b-prajapati** [comment]
Hi @TahaTesser 

Following are the contents of pubspec.yaml 

```
name: My_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+65

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^2.0.1
  get_it: ^3.0.1
  http: ^0.12.0+2
  rflutter_alert: ^1.0.3
  connectivity: ^0.4.4
  pin_code_text_field: 1.4.0
  modal_progress_hud: ^0.1.1
  flushbar: 1.9.1
  shared_preferences: ^0.5.4+3
  intl: ^0.16.0
  carousel_slider: ^1.3.0
  flutter_screenutil: ^0.5.3
  draggable_scrollbar: ^0.0.4
  file_picker: ^1.4.2
  url_launcher: ^3.0.3
  dio: ^3.0.7
  fluttertoast: ^3.1.3
  adobe_analytics: ^0.0.2
  flutter_staggered_animations: "^0.1.2"
  package_info: ^0.4.0+12
  path_provider: ^1.4.5
  flutter_mailer: ^0.4.1+1
  pdf_viewer_plugin: ^1.0.0+2
  user_experior: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    # Other Icons
    - assets/images/tick.png
    - assets/images/small_circle.png
    - assets/images/warning_amber.png
    - assets/images/info_note.png
    - assets/images/alert_icon_with_circle.png
    - assets/images/alert_icon_with_circle_red.png
    - assets/images/warning_icon_with_circle.png
    - assets/images/warning_icon_with_circle_fill_color.png
    - assets/images/notification_flag_blue_icon.png
    - assets/images/notification_flag_blue_icon_fill_color.png
    - assets/images/notification_upload_icon.png
    - assets/images/notification_upload_icon_fill_color.png
    - assets/images/notification_edit_icon.png
    - assets/images/notification_edit_icon_fill_color.png
    - assets/images/notification_calendar_green_icon.png
    - assets/images/notification_calendar_green_fill_color_icon.png
    - assets/images/notification_calendar_orange_icon.png
    - assets/images/notification_calendar_orange_fill_color_icon.png
    - assets/images/warning_info.png
    - assets/images/export_pdf.png
    - assets/images/facebook_icon.png
    - assets/images/google_plus_icon.png
    - assets/images/linkedln_icon.png
    - assets/images/twitter_icon.png
    - assets/images/confirmation_icon.png
    - assets/images/confirmation_green_icon_with_circle.png
    - assets/images/sort_disabled_up_down_arrow.png
    - assets/images/download_statement.png
    - assets/images/rupee_black.png
    - assets/images/check_green_gray_background.png
    - assets/images/green_notification_bell.png
    - assets/images/instagram_icon.png
    - assets/images/youtube_icon.png
    - assets/images/hide_password_blue.png
    - assets/images/warning_icon_with_gray_circle.png
    - assets/images/green_notification_bell2.png
    - assets/images/intro_bg_gradient.png
    - assets/images/intro_cf_icon.png
    - assets/images/intro_tl_icon.png

    # Gray Icons
    - assets/images/grey_icons/mobile_icon_gray.png
    - assets/images/grey_icons/email_icon_gray.png
    - assets/images/grey_icons/hide_password_gray.png
    - assets/images/grey_icons/show_password_gray.png
    - assets/images/grey_icons/info_icon_gray.png
    - assets/images/grey_icons/lock_gray.png
    - assets/images/grey_icons/profile_icon_gray.png
    - assets/images/grey_icons/email_mobile_gray.png
    - assets/images/grey_icons/notification_bell_grey.png

    # Pop Card Icons
    - assets/images/pop_card_icons/pdf-download.png
    - assets/images/pop_card_icons/email.png

    # Blue Icons
    - assets/images/blue_icons/email_blue.png
    - assets/images/blue_icons/show_password_blue.png
    - assets/images/blue_icons/edit_blue.png
    - assets/images/blue_icons/bottom_arrow_blue.png
    - assets/images/blue_icons/right_arrow_blue.png
    - assets/images/blue_icons/left_arrow_blue.png
    - assets/images/blue_icons/info_blue.png
    - assets/images/blue_icons/lock_blue.png
    - assets/images/blue_icons/profile_blue.png
    - assets/images/blue_icons/doc_blue.png
    - assets/images/blue_icons/file_download_blue.png
    - assets/images/blue_icons/up_arrow_blue.png
    - assets/images/blue_icons/sorting_blue.png
    - assets/images/blue_icons/logout_bottom_nav_bar_menu_blue.png
    - assets/images/blue_icons/menu_bottom_nav_bar_enabled_blue.png
    - assets/images/blue_icons/profile_bottom_nav_bar_enabled_blue.png
    - assets/images/blue_icons/track_application_bottom_nav_bar_menu_blue.png
    - assets/images/blue_icons/menu_bottom_nav_bar_disabled_blue.png
    - assets/images/blue_icons/notifcation_bottom_nav_bar_disabled_blue.png
    - assets/images/blue_icons/notifcation_bottom_nav_bar_enabled_blue.png
    - assets/images/blue_icons/home_bottom_nav_bar_enabled_blue.png
    - assets/images/blue_icons/home_bottom_nav_bar_disabled_blue.png
    - assets/images/blue_icons/profile_bottom_nav_bar_disabled_blue.png
    - assets/images/blue_icons/lock_light_blue.png
    - assets/images/blue_icons/faq_light_blue.png
    - assets/images/blue_icons/location_light_blue.png
    - assets/images/blue_icons/location_icon.png
    - assets/images/blue_icons/close_blue.png
    - assets/images/blue_icons/file_upload_blue.png
    - assets/images/blue_icons/search_blue.png
    - assets/images/blue_icons/sort_background_gray_blue.png
    - assets/images/blue_icons/down_arrow_gray_background_blue.png
    - assets/images/blue_icons/sort_ascending_arrow_blue.png
    - assets/images/blue_icons/sort_descending_arrow_blue.png
    - assets/images/blue_icons/excel_background_gray_blue.png
    - assets/images/blue_icons/logout_circular_blue.png
    - assets/images/blue_icons/update_circular_blue.png
    - assets/images/blue_icons/file_circular_blue.png
    - assets/images/blue_icons/privacy_circular_blue.png
    - assets/images/blue_icons/setting_circular_blue.png
    - assets/images/blue_icons/info_circular_blue.png
    - assets/images/blue_icons/filter_blue.png
    - assets/images/blue_icons/attach_file_blue.png
    - assets/images/blue_icons/file_attach_blue.png
    - assets/images/blue_icons/calendar_blue.png
    - assets/images/blue_icons/cancel_blue.png
    - assets/images/blue_icons/info_background_blue.png
    - assets/images/blue_icons/sorting_disable_blue.png
    - assets/images/blue_icons/sorting_ascending_blue.png
    - assets/images/blue_icons/sorting_descending_blue.png
    - assets/images/blue_icons/fab_menu_tds_blue.png
    - assets/images/blue_icons/fab_menu_balance_confirmation_blue.png
    - assets/images/blue_icons/fab_menu_sr_blue.png
    - assets/images/blue_icons/fab_menu_get_assistance_blue.png
    - assets/images/blue_icons/balance_confirmation_menu_icon_blue.png
    - assets/images/blue_icons/service_request_menu_icon_blue.png
    - assets/images/blue_icons/get_assistance_menu_icon_blue.png
    - assets/images/blue_icons/draw_down_request_menu_icon_blue.png
    - assets/images/blue_icons/limit_activation_menu_icon_blue.png
    - assets/images/blue_icons/reports_menu_icon_blue.png
    - assets/images/blue_icons/track_app_menu_icon_blue.png
    - assets/images/blue_icons/statement_account_menu_icon_blue.png
    - assets/images/blue_icons/view_repayment_schedule_menu_icon_blue.png
    - assets/images/blue_icons/upload_download_menu_icon_blue.png
    - assets/images/blue_icons/no_notification_blue.png
    - assets/images/blue_icons/empty_state_no_accounts.png
    - assets/images/blue_icons/empty_state_no_download_statement.png
    - assets/images/blue_icons/empty_state_no_internet.png
    - assets/images/blue_icons/empty_state_no_sr_data.png
    - assets/images/blue_icons/empty_state_no_upload_statement.png

    # White Icons
    - assets/images/white_icons/down_arrow_white.png
    - assets/images/white_icons/show_password_white.png
    - assets/images/white_icons/email_white.png
    - assets/images/white_icons/info_white.png
    - assets/images/white_icons/lock_white.png
    - assets/images/white_icons/profile_white.png
    - assets/images/white_icons/edit_white.png
    - assets/images/white_icons/plus_white.png
    - assets/images/white_icons/doc_white.png
    - assets/images/white_icons/warning_white.png
    - assets/images/white_icons/prefix_pan_icon_white.png
    - assets/images/white_icons/tick_icon_white.png
    - assets/images/white_icons/confirmation_white.png
    - assets/images/white_icons/reject_white.png
    - assets/images/white_icons/view_certificate_white.png
    - assets/images/white_icons/down_arrow_4x_size_white.png
    - assets/images/white_icons/hide_password_white.png
    - assets/images/white_icons/download_white.png
    - assets/images/white_icons/my_profile_logo_white.png

    # Gifs
    - assets/images/gifs/document_upload_loader.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
