### ISSUE TITLE
Federated plugins issue 

### ISSUE THREAD

**Issue by git-elliot** [flutter/flutter#54588]
I have implemented a package in pure dart and flutter, and uses isolates and sqflite in this package. Isolates and sqflite aren't supported in flutter web, so I was thinking to write the web plugin side of this package but I'm having a issue defining the android plugin in pubspec.yaml. 

1. Pubspec configuration says that I have to provide package and plugin class name, but as the I don't have any specific implementation for any platform. I'm writing a package that will support the plugin out of the box on Android, iOS and Web.

2. If I write like this 
```
 name: unevalib
 description: A new Flutter package.
 version: 0.0.1
 author:
 homepage: "adf"

 environment:
   sdk: ">=2.1.0 <3.0.0"
  
 flutter:
   plugin:
     platforms:
       android:
         default_package: unevalib
       ios:
         default_package: unevalib
       web:
         default_package: unevalib_web

 dependencies:
   flutter:
     sdk: flutter
   flutter_web_plugins:
     sdk: flutter  
   unevalib_platform_interface:
     path: ../unevalib_platform_interface
   unevalib_web:
     path: ../unevalib_web
```

It doesn't works and throws error

```Compiler message:
../../../programs/flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart:29:5: Error: Method not found: 'webOnlySetPluginHandler'.
    ui.webOnlySetPluginHandler(_binaryMessenger.handlePlatformMessage); 
```

3. I know the above method is wrong. but I don't have any android or iOS code for this plugin. Just all dart code inside this package unevalib. 

4. The official document says to write like this.
```
flutter:
  plugin:
    platforms:
      android:
        package: com.example.hello
        pluginClass: HelloPlugin
      ios:
        pluginClass: HelloPlugin
      macos:
        pluginClass: HelloPlugin
      web:
        pluginClass: HelloPlugin
        fileName: hello_web.dart
```

5. I don't know how to tell the plugin that this package supports android and iOS in dart only.
6. Please provide a way to define that unevalib package is for android and iOS and unevalib_web package is for web.

P. S. : I have successfully integrated the web part but platform integration failing in android.
