### ISSUE TITLE
[proposal] Provide Official DockerHub Image

### ISSUE THREAD

**Issue by zzj0402** [flutter/flutter#55006]
## Use case

GitLab CI to pull the image to test and deploy web app.

```
stages:
  - test
  - deploy

tests:
  image: cirrusci/flutter:stable-web
  stage: test
  script:
    - flutter test

pages:
  image: cirrusci/flutter:stable-web
  stage: deploy
  script:
    - flutter channel master
    - flutter upgrade
    - flutter config --enable-web
    - flutter create .
    - flutter build web
    - mkdir .public
    - cp -r ./build/web/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
```

## Issue

After run `flutter create`, the local version `flutter test` okay. But the CI version returns error. Maybe with an official version, this would not be an issue.

### Error
```
 Compiler message:
 ../lib/main.dart:101:50: Error: The getter 'headline4' isn't defined for the class 'TextTheme'.
  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/home/cirrus/sdks/flutter/packages/flutter/lib/src/material/text_theme.dart').
 Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline4'.
               style: Theme.of(context).textTheme.headline4,
                                                  ^^^^^^^^^
 00:10 +0 -1: loading /builds/zzj0402/geno/test/widget_test.dart [E]                                                                                                                                    
   Failed to load "/builds/zzj0402/geno/test/widget_test.dart":
   Compilation failed
   Test: /builds/zzj0402/geno/test/widget_test.dart
   Shell: /home/cirrus/sdks/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester
```
