### ISSUE TITLE
Crash during app startup (Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8)

### ISSUE THREAD

**Issue by nioncode** [flutter/flutter#55051]
I don't have much to say about this specific crash, except that it happened on app startup on the emulator.

Is the backtrace of any help?

Backtrace:
```
F/libc    ( 3604): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 3640 (example.app), pid 3604 (example.app)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/sdk_phone_x86/generic_x86:10/QPP6.190730.005.B1/5775370:userdebug/test-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-04-16 20:48:46+0200
pid: 3604, tid: 3640, name: example.app  >>> com.example.app <<<
uid: 10105
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Cause: null pointer dereference
    eax 00000000  ebx f0b69c34  ecx 8294da04  edx 00000000
    edi 8294da04  esi 00002240
    ebp 800ba758  esp 800ba640  eip f0ab82f7
backtrace:
      #00 pc 000742f7  /apex/com.android.runtime/lib/bionic/libc.so (extent_deregister_impl+327) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #01 pc 0006fd78  /apex/com.android.runtime/lib/bionic/libc.so (extent_recycle+584) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #02 pc 0007121f  /apex/com.android.runtime/lib/bionic/libc.so (je_extent_alloc_wrapper+223) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #03 pc 000567dd  /apex/com.android.runtime/lib/bionic/libc.so (je_arena_extent_alloc_large+493) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #04 pc 000755a0  /apex/com.android.runtime/lib/bionic/libc.so (je_large_palloc+320) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #05 pc 0007544d  /apex/com.android.runtime/lib/bionic/libc.so (je_large_malloc+45) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #06 pc 0005881d  /apex/com.android.runtime/lib/bionic/libc.so (je_arena_malloc_hard+1117) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #07 pc 0004b397  /apex/com.android.runtime/lib/bionic/libc.so (je_malloc+2487) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #08 pc 00046489  /apex/com.android.runtime/lib/bionic/libc.so (malloc+41) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #09 pc 012b4ed2  /data/app/com.example.app-txtgkHwviHtCTJYL_8WIKw==/lib/x86/libflutter.so (BuildId: d94d72de3ac0ee06)
      #10 pc 011b42f3  /data/app/com.example.app-txtgkHwviHtCTJYL_8WIKw==/lib/x86/libflutter.so (BuildId: d94d72de3ac0ee06)
      #11 pc 01234e9c  /data/app/com.example.app-txtgkHwviHtCTJYL_8WIKw==/lib/x86/libflutter.so (BuildId: d94d72de3ac0ee06)
      #12 pc 0123511b  /data/app/com.example.app-txtgkHwviHtCTJYL_8WIKw==/lib/x86/libflutter.so (BuildId: d94d72de3ac0ee06)
      #13 pc 0123438c  /data/app/com.example.app-txtgkHwviHtCTJYL_8WIKw==/lib/x86/libflutter.so (BuildId: d94d72de3ac0ee06)
      #14 pc 012348d1  /data/app/com.example.app-txtgkHwviHtCTJYL_8WIKw==/lib/x86/libflutter.so (BuildId: d94d72de3ac0ee06)
      #15 pc 0116fd5d  /data/app/com.example.app-txtgkHwviHtCTJYL_8WIKw==/lib/x86/libflutter.so (BuildId: d94d72de3ac0ee06)
      #16 pc 01158efd  /data/app/com.example.app-txtgkHwviHtCTJYL_8WIKw==/lib/x86/libflutter.so (BuildId: d94d72de3ac0ee06)
      #17 pc 01158c99  /data/app/com.example.app-txtgkHwviHtCTJYL_8WIKw==/lib/x86/libflutter.so (BuildId: d94d72de3ac0ee06)
      #18 pc 011592af  /data/app/com.example.app-txtgkHwviHtCTJYL_8WIKw==/lib/x86/libflutter.so (BuildId: d94d72de3ac0ee06)
      #19 pc 0011a8e5  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+53) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #20 pc 000af6a7  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
Lost connection to device.
```

flutter doctor -v:
```
flutter doctor -v
[  +27 ms] executing:
[/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +23 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing:
[/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git describe
--match v*.*.* --first-parent --long --tags
[   +7 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +3 ms] executing:
[/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git rev-parse
--abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +28 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] executing:
/nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version
[  +45 ms] Exit code 0 from:
/nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +9 ms] executing:
[/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing:
[/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git ls-remote
--get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +13 ms] executing:
[/nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped/] git -c
log.showSignature=false log -n 1 --pretty=format:%ar
[   +7 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 9 weeks ago
[  +16 ms] executing:
/home/nion/.cache/flutter/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[   +6 ms] Exit code 255 from:
/home/nion/.cache/flutter/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[        ] At least one input is required
           Usage: gen_snapshot [<vm-flags>] [<options>] <dart-kernel-file>             

           Common options:                                                             
           --help                                                                      
             Display this message (add --verbose for information about all VM options).
           --version                                                                   
             Print the VM version.                                                     

           To create a core snapshot:                                                  
           --snapshot_kind=core                                                        
           --vm_snapshot_data=<output-file>                                            
           --isolate_snapshot_data=<output-file>                                       
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as assembly suitable for compilation  
           as a static or dynamic library:                                             
           --snapshot_kind=app-aot-assembly                                            
           --assembly=<output-file>                                                    
           [--obfuscate]                                                               
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as an ELF shared library:             
           --snapshot_kind=app-aot-elf                                                 
           --elf=<output-file>                                                         
           [--strip]                                                                   
           [--obfuscate]                                                               
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           AOT snapshots can be obfuscated: that is all identifiers will be renamed    
           during compilation. This mode is enabled with --obfuscate flag. Mapping     
           between original and obfuscated names can be serialized as a JSON array     
           using --save-obfuscation-map=<filename> option. See dartbug.com/30524       
           for implementation details and limitations of the obfuscation pass.
[   +9 ms] executing:
/nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version
[  +46 ms] Exit code 0 from:
/nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +5 ms] java -version
[  +99 ms] executing: /home/nion/opt/android-sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /home/nion/opt/android-sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +3 ms] [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
[   +1 ms]     • Flutter version 1.12.13+hotfix.8 at
                 /nix/store/bxyz9r12vvlg2n37kmpk2rqjxi4s70gj-flutter-stable-1.12.13+hotfix.8-unwrapped
[        ]     • Framework revision 0b8abb4724 (9 weeks ago), 2020-02-11 11:44:36 -0800
[        ]     • Engine revision e1e6ced81d
[        ]     • Dart version 2.7.0
[  +10 ms] executing: /home/nion/opt/android-sdk/platform-tools/adb devices -l
[  +37 ms] List of devices attached
[  +30 ms] executing: /home/nion/opt/android-sdk/tools/bin/sdkmanager --licenses
[+1085 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[        ]     • Android SDK at /home/nion/opt/android-sdk
[        ]     • Android NDK location not configured (optional; useful for native profiling support)
[        ]     • Platform android-29, build-tools 29.0.3
[        ]     • ANDROID_HOME = /home/nion/opt/android-sdk
[        ]     • Java binary at:
                 /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/
                 bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[        ]     • All Android licenses accepted.
[        ] [✓] Android Studio (version 3.6)
[        ]     • Android Studio at
                 /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped
[        ]     • Flutter plugin version 45.0.1
[        ]     • Dart plugin version 192.7761
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[        ] [!] Connected device
[        ]     ! No devices available
[        ] ! Doctor found issues in 1 category.
[  +10 ms] "flutter doctor" took 1,560ms.
```

**Comment by iapicca** [comment]
Hi @nioncode 
could you please run `flutter upgrade --force`
and if the issue persists
provide your updated `flutter doctor -v` ,
and your `flutter run --verbose` 
Thank you

**Comment by nioncode** [comment]
The issue only happened randomly, so I can't easily reproduce this. Shouldn't it be possible to symbolize the backtrace and identify possible root causes of the issue that way?

**Comment by iapicca** [comment]
Hi @nioncode 
answering your last message and
your message on the closed issue
> The backtraces are different, that's why I opened separate issues. Why do you think they are caused by the same thing and should not be treated as separate issues?

both issue might depend from your emulator,
regardless the issue occurrence frequency
could you please upgrade your flutter version and
provide the info indicated [above](https://github.com/flutter/flutter/issues/55051#issuecomment-616331723), also could you please try running your app on a physical device as well?
Thank you

**Comment by intellitour** [comment]
I am facing the same issue on some physical devices:

- Samsung Galaxy J4 (Android 9)
- Samsung Galaxy J5 Prime (Android 8)
- Motorola G7 Power (Android 9)
- Motorola G7 (Android 9)
- Asus Zenfone 4 (ASUS_X00LD) (Android 8.1.0)

```shell
F/libc    (25085): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 25267 (1.ui)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/on5xelteub/on5xelte:8.0.0/R16NW/G570MUBS7CTA1:user/release-keys'
Revision: '5'
ABI: 'arm'
pid: 25085, tid: 25267, name: 1.ui  >>> br.med.maisvida.maisvida_beneficiario <<<
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    r0 caa427b0  r1 caa427fc  r2 0174d478  r3 00000008
    r4 caa427a4  r5 cc006158  r6 00000000  r7 ca8a4570
    r8 c9c19170  r9 c9c19de4  sl fe8b2b87  fp c9c19de4
    ip cbfe9108  sp cbd0f378  lr ca93350d  pc ebd69c00  cpsr 600b0010
backtrace:
    #00 pc 00018c00  /system/lib/libc.so (sigsetjmp+136)
    #01 pc 000e850b  [stack:25268:ca84b000]
Lost connection to device.
```

**Comment by iapicca** [comment]
Hi @intellitour 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by intellitour** [comment]
@iapicca Here it is:

[flutter_doctor.txt](https://github.com/flutter/flutter/files/4530282/flutter_doctor.txt)
[flutter_run.log.zip](https://github.com/flutter/flutter/files/4530313/flutter_run.log.zip) (very verbose)

I can't provide code, but here is my pubspec:

```yaml
name: maisvida_beneficiario
description: Aplicativo para o Beneficiário na plataforma MAISVIDA;

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.10+11

environment:
  sdk: ">=2.7.0 <3.0.0"

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true

dependencies:
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  rxdart: ^0.23.1
  flutter_modular: ^1.1.1
  community_material_icon: ^3.5.95
  flutter_page_indicator: ^0.0.3
  flutter_sidekick: ^0.1.3
  device_info: ^0.4.2+1
  flutter_web_auth: ^0.1.3
  flutter_svg: ^0.17.4
  toast: ^0.1.5
  modal_progress_hud: ^0.1.3
  table_calendar: ^2.2.3
  cached_network_image: ^2.0.0
  html_unescape: ^1.0.1+3
  flutter_html_textview_render: ^0.1.3
  auto_size_text: ^2.1.0
  flutter_flip_view: ^1.0.3
  event_bus: ^1.1.1
  device_calendar: ^3.1.0
  google_maps_flutter: ^0.5.25+3
  map_launcher: ^0.4.4
  url_launcher: ^5.4.2
  onesignal_flutter: ^2.4.0
  location: ^3.0.2
  flutter_local_notifications: ^1.4.1
  sqflite: ^1.3.0
  flutter_time_picker_spinner: ^1.0.6
  toggle_switch: ^0.1.4
  maisvida_flutter_core:
    git:
      url: (supressed)
      ref: master
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.2
  build_runner: ^1.7.4
  flutter_launcher_icons: "^0.7.3"
  flutter_launcher_name: "^0.0.1"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path_android: "assets/app_icon.png"
  adaptive_icon_background: "assets/android_icon_adaptative_background.png"
  adaptive_icon_foreground: "assets/android_icon_adaptative_foreground.png"
  ios: true
  image_path_ios: "assets/app_icon.png"

flutter_launcher_name:
  name: "Mais Vida"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/i18n/translations.json
    - assets/img/
    - assets/onboarding/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: fonts/ProximaNova-Regular.otf
          style: normal
          weight: 400
        - asset: fonts/ProximaNova-Black.otf
          weight: 900
        - asset: fonts/ProximaNova-Bold.otf
          weight: 700
        - asset: fonts/ProximaNova-Extrabold.otf
          weight: 800
        - asset: fonts/ProximaNova-Thin.otf
          weight: 200
    - family: Proxima Nova Alt
      fonts:
        - asset: fonts/ProximaNova-AltBold.otf
          weight: 400
        - asset: fonts/ProximaNova-AltLight.otf
          weight: 300
        - asset: fonts/ProximaNova-AltThin.otf
          weight: 100


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
