### ISSUE TITLE
[Share Plugin] Sharing text in iOS results in blank pop-up

### ISSUE THREAD

**Issue by benPesso** [flutter/flutter#55061]
Running the below test app, you get a black iOS Share prompt, and a weird `)` printout in the `DEBUG CONSOLE`. 

![screenshot](https://user-images.githubusercontent.com/921173/79609603-b3d02580-80ff-11ea-83f8-694d05cbeaba.png)

### pubspec.yaml
```yaml
name: app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  share: ^0.6.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
```

### main.dart
```dart
import 'package:flutter/material.dart';
import 'package:share/share.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Share Plugin Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Share Plugin Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Text(
          'Click the FAB to share `This is a test`.',
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => Share.share('This is a test'),
        tooltip: 'Share',
        child: Icon(
          Icons.share,
        ),
      ),
    );
  }
}
```

### Flutter Doctor
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.17.0 at /Users/user/Projects/flutter
    • Framework revision d3ed9ec945 (11 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone 11 Pro • 0F869680-8774-48CD-8B55-DF8D62281692 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4
      (simulator)

• No issues found!
