### ISSUE TITLE
build aar outputs web and macos plugins

### ISSUE THREAD

**Issue by chris-rutkowski** [flutter/flutter#55145]
Hello, I've noticed strange dependencies when using the following plugins:
- image_picker (0.6.5)
- shared_preferences (0.5.6+1)

We attach the Flutter module to an existing app by adding frameworks/aars, and we use the most recent beta.

```console
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d3ed9ec945 (13 days ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)
```
our yaml:
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_spinkit:
  http:
  uuid:
  data_connection_checker:
  rxdart:
  get_it:
  shared_preferences:
  equatable:
  cached_network_image:
  image_picker:
```

After building frameworks:

```flutter build ios-framework --xcframework --no-universal```

The one name is very suspicious: **flutter_plugin_android_lifecycle**.
Android lifecycle for iOS? This one is added when we list image_picker in dependencies.

After building aars:

```build-android-aars```

There are multiple shared preferences folders, apart from simply "sharedpreferences", there are also **shared_preferences_macos** and **shared_preferences_web**, . The naming implies they shouldn't be built for Android, but for web or macOS. When I remove them - the app won't compile.
I have exactly the same outcome when using stable.

<img width="410" alt="Screen Shot 2563-04-19 at 17 40 55" src="https://user-images.githubusercontent.com/58718695/79685725-18f15b80-8265-11ea-98d2-1a709fe6f976.png">
<img width="380" alt="Screen Shot 2563-04-19 at 17 36 52" src="https://user-images.githubusercontent.com/58718695/79685731-20b10000-8265-11ea-8fbc-e9f8079d0533.png">
