### ISSUE TITLE
Flutter Android internet doesnt work on real device, but works on emulator 

### ISSUE THREAD

**Issue by marhyno** [flutter/flutter#55896]
**Expected results:** Application is working on real android device - Moto G5s Plus with internet connection - api calls

**Actual results:** Application works on real device but internet connection doesnt so I cannot even pass the login screen. But the error shows nothing about internet connectivity.

_**Devices**_
**Internet doesnt work** -> Moto G 5S Plus            • ZY322HCR5P    • android-arm    • Android 8.1.0 (API 27)
**Build and tested on - internet works** -> Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)

Details
**\android\app\src\main\AndroidManifest.xml**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.App">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="App"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

*I also added internet permissions to \android\app\src\debug\AndroidManifest.xml and 
\android\app\src\profile\AndroidManifest.xml to test it, none of them works.

Tried also 
```
flutter clean
flutter build apk
flutter install
```

And plain

```
flutter run -d ZY322HCR5P
```

<details>
Emulator is 
  <summary>Error - expand to show details</summary>

```
An Observatory debugger and profiler on Moto G 5S Plus is available at: http://127.0.0.1:59445/x_VtQy28Opc=/
[+4065 ms] I/flutter (13870): {email: stefan.marcin74@gmail.com, password: mypassword}
[  +32 ms] E/flutter (13870): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'length' was
called on null.
[   +1 ms] E/flutter (13870): Receiver: null
[        ] E/flutter (13870): Tried calling: length
[   +4 ms] E/flutter (13870): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[   +2 ms] E/flutter (13870): #1      _parseJson (dart:convert-patch/convert_patch.dart:30:28)
[   +1 ms] E/flutter (13870): #2      JsonDecoder.convert (dart:convert/json.dart:505:36)
[        ] E/flutter (13870): #3      JsonCodec.decode (dart:convert/json.dart:153:41)
[        ] E/flutter (13870): #4      jsonDecode (dart:convert/json.dart:96:10)
[        ] E/flutter (13870): #5      Network._getToken (package:MyHorse.sk/network_utils/api.dart:13:13)
[        ] E/flutter (13870): <asynchronous suspension>
[        ] E/flutter (13870): #6      Network.postData (package:MyHorse.sk/network_utils/api.dart:19:11)
[        ] E/flutter (13870): #7      _LoginState._login (package:MyHorse.sk/screen/login.dart:183:31)
[        ] E/flutter (13870): #8      _LoginState.build.<anonymous closure> (package:MyHorse.sk/screen/login.dart:112:23)
[   +5 ms] E/flutter (13870): #9      StyledFlatButton.build.<anonymous closure> (package:MyHorse.sk/styles/styles.dart:80:23)
[   +1 ms] E/flutter (13870): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
[   +6 ms] E/flutter (13870): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)       
[   +2 ms] E/flutter (13870): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[   +1 ms] E/flutter (13870): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
[        ] E/flutter (13870): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
[        ] E/flutter (13870): #15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
[        ] E/flutter (13870): #16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)      
[        ] E/flutter (13870): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
[        ] E/flutter (13870): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:122:9)
[        ] E/flutter (13870): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
[   +7 ms] E/flutter (13870): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[   +1 ms] E/flutter (13870): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
[   +1 ms] E/flutter (13870): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
[        ] E/flutter (13870): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
[        ] E/flutter (13870): #24     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
[        ] E/flutter (13870): #25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
[        ] E/flutter (13870): #26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
[        ] E/flutter (13870): #27     _rootRunUnary (dart:async/zone.dart:1196:13)
[        ] E/flutter (13870): #28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +8 ms] E/flutter (13870): #29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
[   +1 ms] E/flutter (13870): #30     _invoke1 (dart:ui/hooks.dart:275:10)
[        ] E/flutter (13870): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

```
```
</details>

[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale sk-SK)
    • Flutter version 1.17.0 at D:\SideProjects\MyHorse.sk\flutter
    • Framework revision d3ed9ec945 (3 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Owner\AppData\Local\Android\Sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Owner\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.44.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (4 available)
    • Moto G 5S Plus            • ZY322HCR5P    • android-arm    • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 81.0.4044.122
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by aseef17** [comment]
Hey, from what I can see in the logs, there seems to be some code specific error about trying get the length of a variable. I don’t suppose anyone would be able to help you out without any sample code presented to try to reproduce the issue

**Comment by marhyno** [comment]
This is the code which should be executed right after app starts, but its not or is not even returning anything like it has nevered fired, and when I hit Login button it should fire another login function but it returns the error 
```
///function which should run after start in main.dart
Future<bool> _checkIfLoggedInBackend() async {
    var res = await Network().postData(null,'/auth/checkIfLogged',context, "Nepodarilo sa prihlásiť.");
    if (res == null){return false;}
    var body = json.decode(res.body);
    print(body);
    if (body["status"] == 200) {
      return true;
    } else {
      return false;
    }
  }

/// getting api data
  postData(data, apiUrl, context, errorMessage) async {
    Loading().showLoadingDialog(context);
    var fullUrl = _url + apiUrl;
    await _getToken();
    try {
      var ret = await http
          .post(fullUrl, body: jsonEncode(data), headers: _setHeaders())
          .timeout(const Duration(seconds: 10));
      if (ret != null){
        Navigator.of(context, rootNavigator: true).pop();
        return ret;
      }
    } catch (e) {
      Navigator.of(context, rootNavigator: true).pop();
      Loading().showErrorLoadingDialog(context, errorMessage);
    }
  }


///login function from login screen

  void _login() async {
    var data = {
      'email': emailController.text,
      'password': passwordController.text
    };
    print(data);

    var res = await Network().postData(data, '/auth/login',context,"Nepodarilo sa prihlásiť.");
    if (res == null){return;}
    var body = json.decode(res.body);
    print(body);
    if (body['status'] == 200) {
      SharedPreferences localStorage = await SharedPreferences.getInstance();
      localStorage.setString('token', json.encode(body['access_token']));
      localStorage.setString('user', json.encode(body['user']));
      Navigator.pushNamedAndRemoveUntil(
          context, '/myhorses', (Route<dynamic> route) => false);
    } else {
      _showMsg("Neplatný email alebo heslo. Skúste znovu.");
    }
  }
```

**Comment by marhyno** [comment]
I am also adding pubspec.yaml

```
name: MyHorse.sk
description: A to do project that uses a REST API.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.4.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  shared_preferences: ^0.5.6+1
  provider: ^3.0.0
  flutter_calendar_carousel: ^1.4.11
  datetime_picker_formfield: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```
