### ISSUE TITLE
Hot Reload: Error 105 received from application: Isolate must be runnable

### ISSUE THREAD

**Issue by nalnir** [flutter/flutter#55953]
I've seen couple of similar posts, but none of them helped.
This is happening only on ios emulator. Android works perfectly.

When I `flutter run` the app starts normally, but with blank white screen on the emulator. When I hot reload I get this error
```
Initializing hot reload...                                             ⣽Error 105 received from application: Isolate must be runnable
       ⣻Hot reload received invalid response: {code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: false, rootLibUri:
file:///Users/juico/Library/Developer/CoreSimulator/Devices/5A6AACF5-D693-40E0-A5CA-2F377A2FE8F7/data/Containers/Data/Application/F9531B29-E971-40DA-B48F-CBC24D821564/tmp/bountyhunteraYWMWu/bountyhunter/lib/main.dart.incremental.dill,
packagesUri: file:///Users/juico/Library/Developer/CoreSimulator/Devices/5A6AACF5-D693-40E0-A5CA-2F377A2FE8F7/data/Containers/Data/Application/F9531B29-E971-40DA-B48F-CBC24D821564/tmp/bountyhunteraYWMWu/bountyhunter/.packages, isolateId:
isolates/1307987886176599}}, details: Isolate must be runnable before this request is made.}}
```

On hot restart the app crashes with:
```
Performing hot restart...                                              ⣻Error 105 received from application: Isolate must be runnable
        
Restarted application in 1,730ms.
Application finished.
hot restart failed to complete
Error -32000 received from application: Could not run configuration in engine.
```

I've seen in few posts that it might be the problem with some packages, like firebase_messaging.
Here is my pubspec.yaml:

```
dependencies:
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter
    
  firebase_auth: ^0.14.0+5
  flutter_auth_buttons: ^0.6.0
  firebase_storage: ^3.1.3
  firebase_database: ^3.1.3
  cloud_firestore: ^0.13.4+2
  # Facebook Login
  flutter_facebook_login: ^3.0.0
  # Password Packages
  flutter_password_strength: ^0.1.4
  password_strength: ^0.1.2
  # Font Awesome
  font_awesome_flutter: ^8.7.0
  # Image Picker
  image_picker: ^0.6.3+4
  # Money Parser
  flutter_masked_text: ^0.7.0
  # Google Maps
  google_maps_flutter: ^0.5.25+2
  #Geocode
  geocoder: ^0.2.1
  # Nanoid - ID generator
  nanoid: ^0.1.0
  # URL Launcher
  url_launcher: ^5.4.2
  # Charts
  multi_charts: ^0.2.0
  # Launcher Icons
  flutter_launcher_icons: ^0.7.4
  # Flare Animations
  flare_flutter: ^2.0.3


dependency_overrides:
  firebase_core: 0.4.4
```

The error Happens on stable channel. When changing to master, it works, but throws all sorts of other errors for both android and ios.
