### ISSUE TITLE
Becouse stockexchange depends on flutter any from sdk, version solving failed.

### ISSUE THREAD

**Issue by vishnuiiit** [flutter/flutter#56017]
I was trying to create a new flutter project but there were errors for URI doesn't exist for material.dart
So I checked libraries in project structure and to my surprise, there was no "Dart Packages" library in the libraries section so I tried creating one but there was no option for dart libraries to add.

![image](https://user-images.githubusercontent.com/53317018/80678958-8f018800-8ad9-11ea-86bd-3fbd8d71cb01.png)

![image](https://user-images.githubusercontent.com/53317018/80679176-01726800-8ada-11ea-94e1-c54b5b2d6fe9.png)

so I ran flutter doctor -v
```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17763.1039], locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at D:\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

flutter pub get
```
D:\FlutterProjects\stock_exchange>flutter pub get
Because every version of flutter_test from sdk depends on test_api 0.2.11 which doesn't match any versions, flutter_test from sdk is forbidden.
So, because stockexchange depends on flutter_test any from sdk, version solving failed.
Running "flutter pub get" in stock_exchange...
pub get failed (1; So, because stockexchange depends on flutter_test any from sdk, version solving failed.)
```

packages.yaml
```
name: stockexchange
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

flutter:

  uses-material-design: true
```

**Comment by aseef17** [comment]
Might be related to [This](https://github.com/flutter/flutter/issues/19382)

**Comment by vishnuiiit** [comment]
> Might be related to [#19382](https://github.com/flutter/flutter/issues/19382)

sorry abt this but unfortunately not, already tried it starts giving me other errors like node preamble v.1.4.8 doesn't exist, version solving failed

**Comment by aseef17** [comment]
> > Might be related to [#19382](https://github.com/flutter/flutter/issues/19382)
> 
> 
> 
> sorry abt this but unfortunately not, already tried it starts giving me other error, node preamble v.1.4.8 doesn't exist, version solving failed

Can you share your complete pubspec.yaml?
Try bumping up the SDK version and see if that helps

**Comment by vishnuiiit** [comment]
I have latest sdk version, just downloaded

this is my complete pubspec.yaml since I just created a project
```
name: stockexchange
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

flutter:

  uses-material-design: true
```

**Comment by aseef17** [comment]
```
dev_dependencies:
  flutter_test:
    sdk: flutter
    test_api: ^0.2.13

dependency_overrides:
  test_api: ^0.2.13
```

Try to add this to your pubspec.yaml and let me know if that works

**Comment by vishnuiiit** [comment]
it game this error
```
Error on line 11, column 5 of pubspec.yaml: A dependency may only have one source.
   ╷
11 │ ┌     sdk: flutter
12 │ │     test_api: ^0.2.13
13 │ │ 
14 │ │   cupertino_icons: ^0.1.2
   │ └──^
   ╵
Running "flutter pub get" in stock_exchange...
pub get failed (65;    ╵)
```

pubspec.yaml
```
name: stockexchange
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    test_api: ^0.2.13

  cupertino_icons: ^0.1.2

dependency_overrides:
  test_api: ^0.2.13

flutter:

  uses-material-design: true

```
