### ISSUE TITLE
dart:ui not found (integration testing)

### ISSUE THREAD

**Issue by rrifafauzikomara** [flutter/flutter#56192]
### Steps to Reproduce

1. Add `flutter_driver` to `pubspec.yaml`
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
```
2. Add `test_driver/app.dart`
```
import 'package:flutter_driver/driver_extension.dart';
import 'package:moviecatalogue/ui/launcher/main-dev.dart' as development;

void main() {
  enableFlutterDriverExtension();

  development.main();
}
```
3. Add `test_driver/app_test.dart`
```
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

import 'app_test_key.dart';

void main() {
  group("Movies Development Test", (){

    FlutterDriver driver;

    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
    });

    test("show list now plauing", () async {
      await driver.waitFor(homeKey);
      await driver.waitFor(tapBottomNowPlayingKey);
      await Future.delayed(Duration(seconds: 3));
      await driver.waitFor(tapListViewNowPlayingKey);
      await Future.delayed(Duration(seconds: 1));
      await driver.scroll(tapListViewNowPlayingKey, 0, 200, Duration(milliseconds: 500));
      await driver.scroll(tapListViewNowPlayingKey, 0, -600, Duration(milliseconds: 500));
      await driver.scroll(tapListViewNowPlayingKey, 0, 800, Duration(milliseconds: 500));
      await Future.delayed(Duration(seconds: 1));
      await driver.tap(tapItemNowPlayingKey);
      await Future.delayed(Duration(seconds: 3));
      await driver.tap(tapItemFavoriteKey);
      await Future.delayed(Duration(seconds: 1));
      await driver.tap(tapBackButtonKey);
      await Future.delayed(Duration(seconds: 1));
    });

    test("show list up comming", () async {
      await driver.waitFor(tapBottomUpComingKey);
      await Future.delayed(Duration(seconds: 3));
      await driver.waitFor(tapListViewUpComingKey);
      await Future.delayed(Duration(seconds: 1));
      await driver.scroll(tapListViewUpComingKey, 0, 200, Duration(milliseconds: 500));
      await driver.scroll(tapListViewUpComingKey, 0, -600, Duration(milliseconds: 500));
      await driver.scroll(tapListViewUpComingKey, 0, 800, Duration(milliseconds: 500));
      await Future.delayed(Duration(seconds: 1));
      await driver.tap(tapItemUpComingKey);
      await Future.delayed(Duration(seconds: 3));
      await driver.tap(tapItemFavoriteKey);
      await Future.delayed(Duration(seconds: 1));
      await driver.tap(tapBackButtonKey);
      await Future.delayed(Duration(seconds: 1));
    });

    test("show list popular", () async {
      await driver.waitFor(tapBottomPopularKey);
      await Future.delayed(Duration(seconds: 3));
      await driver.waitFor(tapListViewPopularKey);
      await Future.delayed(Duration(seconds: 1));
      await driver.scroll(tapListViewPopularKey, 0, 200, Duration(milliseconds: 500));
      await driver.scroll(tapListViewPopularKey, 0, -600, Duration(milliseconds: 500));
      await driver.scroll(tapListViewPopularKey, 0, 800, Duration(milliseconds: 500));
      await Future.delayed(Duration(seconds: 1));
      await driver.tap(tapItemPopularKey);
      await Future.delayed(Duration(seconds: 3));
      await driver.tap(tapItemFavoriteKey);
      await Future.delayed(Duration(seconds: 1));
      await driver.tap(tapBackButtonKey);
      await Future.delayed(Duration(seconds: 1));
    });

    test("show list top rated", () async {
      await driver.waitFor(tapBottomTopKey);
      await Future.delayed(Duration(seconds: 3));
      await driver.waitFor(tapListViewTopRatedKey);
      await Future.delayed(Duration(seconds: 1));
      await driver.scroll(tapListViewTopRatedKey, 0, 200, Duration(milliseconds: 500));
      await driver.scroll(tapListViewTopRatedKey, 0, -600, Duration(milliseconds: 500));
      await driver.scroll(tapListViewTopRatedKey, 0, 800, Duration(milliseconds: 500));
      await Future.delayed(Duration(seconds: 1));
      await driver.tap(tapItemTopRatedKey);
      await Future.delayed(Duration(seconds: 3));
      await driver.tap(tapItemFavoriteKey);
      await Future.delayed(Duration(seconds: 1));
      await driver.tap(tapBackButtonKey);
      await Future.delayed(Duration(seconds: 1));
    });

    test("show about", () async {
      await driver.waitFor(tapBottomAboutKey);
    });

  });
}
```
4. From terminal, Run `flutter drive --target=test_driver/app.dart --flavor development`
#### Log result
```
Using device iPhone 11 Pro Max.
Starting application: test_driver/app.dart
 
Running pod install...                                              2.3s
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                          13.9s
 └─Compiling, linking and signing...                         9.7s
Xcode build done.                                           35.2s
flutter: Observatory listening on http://127.0.0.1:58760/7VXycg307vg=/
../../Documents/flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paint, Path, Canvas;
       ^
../../Documents/flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../Documents/flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
../../Documents/flutter/packages/flutter/lib/src/material/app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../Documents/flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../Documents/flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../Documents/flutter/packages/flutter/lib/src/material/bottom_sheet_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../Documents/flutter/packages/flutter/lib/src/material/button_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../Documents/flutter/packages/flutter/lib/src/material/card_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
../../Documents/flutter/packages/flutter/lib/src/material/chip_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
Stopping application instance.
Driver tests failed: 254
```

### FYI
1. `pubspec.yaml`
```
name: moviecatalogue
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # This is our modular
  core:
    path: core
  shared:
    path: shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  json_serializable: any
  shimmer: ^1.1.1
  cached_network_image: ^2.2.0
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/movie_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          style: italic
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
```
2. Structur project
```
    # Root Project
    .
    ├── core                   # Name of module (new package)
    │   ├── bloc               # Business logic component.
    │   └── network            # Remote Data Handlers
    |       ├── api            # Retrofit API for remote end point, model using Equatable.
    │       └── repository     # Single source of data and for handling data from network to cache.
    |
    ├── lib                    # Name of module (default from Flutter)
    │   └── ui                 # Activity/View layer
    |
    └── shared                 # Name of module (new package)
        ├── common             # Common shared.
        │   ├── helpers        # Custom function, extension, etc which can be used repeatedly on each method.
        │   ├── styles         # Custom style that will be used on each widget.
        │   └── utils          # Utility classes.
        └── widget             # Custom widget which can be used repeatedly.
```
3. Full source code [here](https://github.com/rrifafauzikomara/MovieCatalogue)
4. Flutter doctor result
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57,
    locale en-US)
    • Flutter version 1.12.13+hotfix.8 at
      /Users/rrifafauzikomara/Documents/flutter
    • Framework revision 0b8abb4724 (3 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/rrifafauzikomara/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 641006EC-FDB0-4918-B547-593818B98B05 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```
