### ISSUE TITLE
Pub get flutter_test version solving failed on Beta 1.17.0-3.4.pre

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#56287]
I just updated path in my project because I needed the latest one and I get this error 
Because every version of flutter_test from sdk depends on path 1.6.4 and yaip depends on path ^1.7.0, flutter_test from sdk is forbidden. 

I started trying out and preparing my project on Beta to get ready to go live to Playstore. Now I read from here https://www.gitmemory.com/issue/flutter/flutter/55453/618436399 that its been updated on master and dev channels but not on beta and stable channels. Kindly updated it on the remain channels as well so that I don't have to downgrade my path version as I really need the latest.

**Comment by TahaTesser** [comment]
Hi @MichaelSowah 
Can you please post your `pubspec.yaml`?

This works fine on `beta` channel
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel beta, v1.17.0-3.4.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.17.0-3.4.pre at /Users/taha/Code/flutter_beta
    • Framework revision e6b34c2b5c (2 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • SM M305F            • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • AOSP on IA Emulator • emulator-5554    • android-x86    • Android 9 (API
      28) (emulator)
    • Chrome              • chrome           • web-javascript • Google Chrome
      81.0.4044.129
    • Web Server          • web-server       • web-javascript • Flutter Tools

• No issues found!
taha@MacBook-Pro And
``` 

</details> 


Thank you

**Comment by MichaelSowah** [comment]
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  flutter_svg: ^0.17.4
  cached_network_image: ^2.2.0
  sembast: ^2.4.3
  path: ^1.7.0
  path_provider: ^1.6.7


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by MichaelSowah** [comment]
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  flutter_svg: ^0.17.4
  cached_network_image: ^2.2.0
  sembast: ^2.4.3
  path: ^1.7.0
  path_provider: ^1.6.7


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by MichaelSowah** [comment]
@TahaTesser 
this is my 
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  flutter_svg: ^0.17.4
  cached_network_image: ^2.2.0
  sembast: ^2.4.3
  path: ^1.7.0
  path_provider: ^1.6.7


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by TahaTesser** [comment]
Hi @MichaelSowah 

Please add `dependency_overrides` move `path` to `dependency_overrides` and it should solve the issue

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  flutter_svg: ^0.17.4
  cached_network_image: ^2.2.0
  sembast: ^2.4.3
  path: ^1.7.0
  path_provider: ^1.6.7

dependency_overrides:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
```
