### ISSUE TITLE
[web]: `flutter build web` doesn't generate a proper build

### ISSUE THREAD

**Issue by skipmeister123** [flutter/flutter#56337]
My webapp isn't building properly.  It runs fine on Android, and even iOS.  If I peek into the `web` directory, there's nothing in there but the boilerplate stuff.  If I'm doing something wrong, I'd love to learn what.  If something isn't working as expected, I'd like to see it fixed. :)

<img width="1145" alt="Screen Shot 2020-05-04 at 8 02 29 PM" src="https://user-images.githubusercontent.com/1911919/81024812-9c54a480-8e42-11ea-949a-4146d73fbd68.png">

The code generated for the index page seems to be boilerplate:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="t4c_companion">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="favicon.png"/>

  <title>t4c_companion</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>

```

The web console throws a few errors:
```
Uncaught TypeError: Cannot set property 'getModuleLibraries' of undefined
    at main_module.bootstrap.js:16
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
top_level.dart:78 Uncaught (in promise) TypeError: Cannot read property 'app' of undefined
    at Object.app$ [as app] (top_level.dart:78)
    at appNamed (firebase_core_web.dart:22)
    at appNamed.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at firebase_core_web.FirebaseCoreWeb.new.appNamed (firebase_core_web.dart:20)
    at appNamed (firebase_app.dart:36)
    at appNamed.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at Function.appNamed (firebase_app.dart:34)
    at configure (firebase_app.dart:58)
    at configure.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at Function.configure (firebase_app.dart:50)
    at main$ (main.dart:53)
    at main$.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at Object.main$ [as main] (main.dart:48)
    at main$ (web_entrypoint.dart:8)
    at main$.next (<anonymous>)
    at onValue (async_patch.dart:47)
    at _RootZone.runUnary (zone.dart:1439)
    at _FutureListener.thenAwait.handleValue (future_impl.dart:141)
    at handleValueCallback (future_impl.dart:682)
    at Function._propagateToListeners (future_impl.dart:711)
    at async._AsyncCallbackEntry.new.callback (future_impl.dart:391)
    at Object._microtaskLoop (schedule_microtask.dart:43)
    at _startMicrotaskLoop (schedule_microtask.dart:52)
    at async_patch.dart:168
```

Here's the pubspec.yaml:
```yaml
name: t4c_companion
description: A helpful companion for T4C players and a reference for the rest of us.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path:
  async:
  basic_utils: ^1.2.0
  provider: ^3.1.0+1
  package_info: ^0.4.0+3
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.16.0
  firebase_database:
  firebase_crashlytics:
  flare_flutter: ^1.8.3
  intl:
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/equipment/armor/
    - assets/images/equipment/bow/
    - assets/images/equipment/jewelry/
    - assets/images/equipment/quiver/
    - assets/images/equipment/weapon/
    - assets/images/monsters/
    - assets/images/remorts/
    - assets/images/servers/
    - assets/images/badges/
    - assets/images/skills/
    - assets/images/skills/realmud/

  fonts:
    - family: T4CBeaulieux
      fonts:
        - asset: assets/t4cbeaulieuxV3.otf
    - family: HackNF
      fonts:
        - asset: assets/HackNF.ttf
```
