### ISSUE TITLE
Program type already present: io.flutter.plugins.webviewflutter.DisplayListenerProxy$1

### ISSUE THREAD

**Issue by KartikPatelOfficial** [flutter/flutter#56360]
* What went wrong:

Execution failed for task ':app:multiDexListDebug'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > Error while merging dex archives:

     Program type already present: io.flutter.plugins.webviewflutter.DisplayListenerProxy$1

     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by VladyslavBondarenko** [comment]
Hi @KartikPatelOfficial 
could you provide your `flutter doctor -v` and a minimal app to reproduce the error?

**Comment by KartikPatelOfficial** [comment]
flutter doctor -v

> [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale en-IN)
>     • Flutter version 1.12.13+hotfix.9 at C:\Users\karti\development\flutter
>     • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
>     • Engine revision af51afceb8
>     • Dart version 2.7.2
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at C:\Users\karti\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.44.2)
>     • VS Code at C:\Users\karti\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.10.1
> 
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 1 category.

[pgurus_new-master.zip](https://github.com/flutter/flutter/files/4585355/pgurus_new-master.zip)

**Comment by VladyslavBondarenko** [comment]
@KartikPatelOfficial 
I can successfully run your app with `stable v1.12.13+hotfix.9` or `dev 1.18.0-10.0.pre`.
Does `flutter clean` `flutter pub get` help?

**Comment by KartikPatelOfficial** [comment]
@VladyslavBondarenko 
I tried in mac os and windows both. but can't run it. Already tried it.

**Comment by iapicca** [comment]
Hi @KartikPatelOfficial 
given your last message I feel confident to close the issue.
If you disagree please write in the comment and I will reopen it
Thank you

**Comment by KartikPatelOfficial** [comment]
Sorry i sent you modified project(removed webview_flutter and used flutter_html that was perfectly working on my device too.). The issue is with webview_flutter.

[pgurus_new-master.zip](https://github.com/flutter/flutter/files/4586787/pgurus_new-master.zip)

try to run this project.

**Comment by iapicca** [comment]
Hi @KartikPatelOfficial
could you please provide a reproducible minimal code sample
rather than a full production app
Thank you

**Comment by KartikPatelOfficial** [comment]
Here's my pubspec.yaml file.
```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  http: ^0.12.0+4
  flutter_html: ^0.11.1
  youtube_player_flutter: ^6.1.0+4
  google_fonts: ^0.3.9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.4+2
  fluttertoast: ^3.1.3
  google_sign_in: ^4.0.2
  share: ^0.6.3+5
  sqflite: ^1.2.0
  path: ^1.6.4
  package_info: ^0.4.0+3
  progress_dialog: ^1.2.1
  intl: ^0.16.1
  pull_to_refresh: ^1.5.8
  firebase_messaging: ^6.0.13
  auto_route: ^0.3.0
  app_settings: ^3.0.1
  admob_flutter: ^0.3.4
  flutter_facebook_login: ^3.0.0
  url_launcher: ^5.4.2
  flare_flutter: ^2.0.1
  palette_generator: ^0.2.2
  provider: ^4.0.4
  html_character_entities: ^0.1.2+4
  webview_flutter:

dependency_overrides:
  firebase_core: 0.4.4

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  auto_route_generator: ^0.3.0
  build_runner:
  flutter_test:
    sdk: flutter
```
