### ISSUE TITLE
FLTGoogleMapsPlugin.m:17:14: error: no visible @interface for 'NSObject<FlutterPluginRegistrar>' declares the selector 'registerViewFactory:withId:gestureRecognizersBlockingPolicy:'

### ISSUE THREAD

**Issue by marekkxyz** [flutter/flutter#57100]
Building app with `google_maps_flutter` for iOS cause crash:

```
/Users/marekk/Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.27+3/ios/Classes/FLTGoogleMapsPlugin.m:17:14: error: no visible @interface for 'NSObject<FlutterPluginRegistrar>' declares the selector 'registerViewFactory:withId:gestureRecognizersBlockingPolicy:'
             [registrar registerViewFactory:googleMapFactory
              ~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           1 error generated.

```
`flutter doctor` says:

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
[✓] VS Code (version 1.45.0)
[✓] Connected device (1 available)

• No issues found!
```

`pubspec.lock`

```
  google_maps_flutter:
    dependency: "direct main"
    description:
      name: google_maps_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.27+3"
  google_maps_flutter_platform_interface:
    dependency: transitive
    description:
      name: google_maps_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
```

Xcode `Version 11.4.1 (11E503a)`

Do you have any ideas how to solve issue?
