### ISSUE TITLE
adding the connectivity packages crashes the app!

### ISSUE THREAD

**Issue by hiwa-jalal** [flutter/flutter#57169]
when i add the connectivity widget i can't run or build my app because i get the following error:
```
Parameter format not correct -
D:\Flutter projects\in_bed_idea\build\connectivity\intermediates\runtime_library_classes\release\classes.jar: R8: Type io.flutter.plugins.connect
ivity.BuildConfig is defined multiple times: D:\Flutter projects\in_bed_idea\build\connectivity\intermediates\runtime_library_classes\release\cla
sses.jar:io/flutter/plugins/connectivity/BuildConfig.class, D:\Flutter projects\in_bed_idea\build\simple_connectivity\intermediates\runtime_libra
ry_classes\release\classes.jar:io/flutter/plugins/connectivity/BuildConfig.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insigh
ts.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 56s
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'... Done                     123.2s (!)
[!] The shrinker may have failed to optimize the Java bytecode.
    To disable the shrinker, pass the `--no-shrink` flag to this command.
```

my app build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"


def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}


android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.hiwa.inbedidea"
        minSdkVersion 22
        targetSdkVersion 29
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
 
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
        }
        debug {
            minifyEnabled true
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.firebase:firebase-analytics:17.3.0'
    implementation "android.arch.lifecycle:extensions:1.1.1"
    annotationProcessor "android.arch.lifecycle:common-java8:1.1.1"
    implementation 'com.android.support:multidex:1.0.3'
}
```
project build.gradle

```

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
 i looked into all the others issues and stack overflow questions related to this problem but nothing worked.

**Comment by liodali** [comment]
try this:
https://issuetracker.google.com/issues/150325706#comment25

**Comment by hiwa-jalal** [comment]
@liodali i added `  classpath 'com.android.tools:r8:1.6.82' ` above gradle but still the same problem!

**Comment by liodali** [comment]
try to disabled by adding this line in your gradle.properties file :
  `android.enableR8=false`

**Comment by hiwa-jalal** [comment]
i did it and got this
```
Warning: there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyDebugWithProguard'.
> java.io.IOException: Please correct the above warnings first.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 38s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin admob_flutter...
Running Gradle task 'assembleAarRelease'...
Starting a Gradle Daemon (subsequent builds will be faster)


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'admob_flutter'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s

Exception: The plugin admob_flutter could not be built due to the issue above.
```

**Comment by liodali** [comment]
you have  AndroidX incompatibilities problem in admob_flutter

**Comment by liodali** [comment]
it old package ,if you run with last flutter version 1.17 you need to migrate the package with androidx

**Comment by hiwa-jalal** [comment]
i am using flutter 1.7 and migrated my project to AndroidX following [this](https://flutter.dev/docs/development/androidx-migration) but still the same problem!

**Comment by liodali** [comment]
you need to migrate the package also
the package it old,so you need to find other package or clone it and migrate it and published with other name

**Comment by hiwa-jalal** [comment]
and how can i do that?

**Comment by TahaTesser** [comment]
Hi @hiwa-jalal 
You have wrong androidx depedency in your project
You need to use androidx multidex after migrating to androidx 

```
    def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"
```

can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by liodali** [comment]
for admob_flutter ,use beta version,it up to date 
admob_flutter: ^1.0.0-beta.2

**Comment by hiwa-jalal** [comment]
@liodali that didn't change anything.

**Comment by hiwa-jalal** [comment]
@TahaTesser that also didn't  worked,

flutter doctor -v output:
```
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\hiwad\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\hiwad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
****
```
flutter run --verbose output:
```
[  +24 ms] D:\Flutter projects\in_bed_idea\build\connectivity\intermediates\runtime_library_classes\debug\classes.jar: R8: Type
io.flutter.plugins.connectivity.BuildConfig is defined multiple times: D:\Flutter
projects\in_bed_idea\build\connectivity\intermediates\runtime_library_classes\debug\classes.jar:io/flutter/plugins/connectivity/BuildConfig.class
, D:\Flutter
projects\in_bed_idea\build\simple_connectivity\intermediates\runtime_library_classes\debug\classes.jar:io/flutter/plugins/connectivity/BuildConfi
g.class
[  +79 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Execution failed for task ':app:minifyDebugWithR8'.
[   +1 ms] > com.android.tools.r8.CompilationFailedException: Compilation failed to complete
[   +6 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 2m 34s
[   +1 ms] 553 actionable tasks: 24 executed, 529 up-to-date
[+6929 ms] Running Gradle task 'assembleDebug'... (completed in 166.7s, longer than expected)
[  +27 ms] [!] The shrinker may have failed to optimize the Java bytecode.
[   +2 ms]     To disable the shrinker, pass the `--no-shrink` flag to this command.
[        ]     To learn more, see: https://developer.android.com/studio/build/shrink-code
[  +49 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +17 ms] "flutter run" took 183,954ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

```

**Comment by liodali** [comment]
show us build.gradle(app) again

**Comment by hiwa-jalal** [comment]
here it is
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"


def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}


android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.hiwa.inbedidea"
        minSdkVersion 22
        targetSdkVersion 29
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
 
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
        }
        debug {
            minifyEnabled true
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.firebase:firebase-analytics:17.4.1'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    annotationProcessor 'androidx.lifecycle:lifecycle-common-java8:2.2.0'
    def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"
}

```

**Comment by liodali** [comment]
try to make  minifyEnabled false

**Comment by hiwa-jalal** [comment]
i noticed that in my `pubsec.yaml` file there were 4 packages related to keyboard because i was testing with them so i thought maybe those packages get conflicted with each other thus producing an error so i removed all except one and it worked! but i don't understand why the problem happened when i added the `connectivity` package and why the error was mentioning it as the problem!

**Comment by liodali** [comment]
if you want to give us other library that you use, to test with them

**Comment by hiwa-jalal** [comment]
here is what my `pubsec.yaml` file looks now:
```
name: inbedidea
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  screen: ^0.0.5
  torch_compat: ^1.0.2
  flutter_auth_buttons: ^0.8.0
  google_sign_in: ^4.4.6
  intl: ^0.16.1
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  provider: ^4.1.2
  flushbar: ^1.10.2
  flare_flutter: ^2.0.3
  video_player: ^0.10.10
  getflutter: ^1.0.11
  get_it: ^4.0.2
  argon_buttons_flutter: ^1.0.2
  flutter_spinkit: ^4.1.2+1
  flutter_xlider: ^3.4.0
  admob_flutter: ^0.3.4
  connectivity: ^0.4.8+6
  flutter_keyboard_size: ^0.1.2+2














dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "assets/new.png"
  android: true
  ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/teddy.flr
    - assets/splash.flr


  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


```

**Comment by liodali** [comment]
i tested , it works without problems
just i upgrade gradle in admob to 3.6.3 and kotlin version also and i upgrade firebase.ads dependencies to 19.1.0
for connectivity package i didn't face any problem with it 
you can use other package like data_connection_checker or simple_connectivity

**Comment by hiwa-jalal** [comment]
yes it works because as i said i removed the other keybaord packages, the not working file was this:

```
name: inbedidea
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  keyboard_utils: ^1.2.1
  screen: ^0.0.5
  torch_compat: ^1.0.2
  flutter_auth_buttons: ^0.8.0
  google_sign_in: ^4.4.6
  intl: ^0.16.1
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  provider: ^4.1.1
  flushbar: ^1.10.2
  flare_flutter: ^2.0.3
  video_player: ^0.10.11
  getflutter: ^1.0.11
  get_it: ^4.0.2
  argon_buttons_flutter: ^1.0.2
  flutter_spinkit: ^4.1.2+1
  flutter_xlider: ^3.4.0
  admob_flutter: ^0.3.4
  keyboard_avoider: ^0.1.2
  flutter_keyboard_visibility: ^2.0.0
  connectivity_widget: ^0.1.5
  connectivity: ^0.4.8+6
  flutter_keyboard_size: ^0.1.2+2














dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "assets/new.png"
  android: true
  ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/teddy.flr
    - assets/splash.flr


  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


```
