### ISSUE TITLE
Execution failed for task ':image_picker:javaPreCompileDebug'. > Could not resolve all files for configuration ':image_picker:debugCompileClasspath'.

### ISSUE THREAD

**Issue by JoDeveloper** [flutter/flutter#57309]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_picker:javaPreCompileDebug'.
> Could not resolve all files for configuration ':image_picker:debugCompileClasspath'.
   > Could not find core.jar (androidx.core:core:1.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/core/core/1.1.0/core-1.1.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin app_settings...
Running Gradle task 'assembleAarRelease'...

> Configure project :
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings


FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/joe/flutter/.pub-cache/hosted/pub.dartlang.org/app_settings-4.0.0/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin app_settings could not be built due to the issue above.
```

**Comment by JoDeveloper** [comment]
@rrousselGit

**Comment by JoDeveloper** [comment]
**flutter doctor -v**

```
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0 at /home/joe/flutter
    • Framework revision e6b34c2b5c (13 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/joe/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/joe/Android/Sdk
    • ANDROID_SDK_ROOT = /home/joe/Android/Sdk
    • Java binary at:
      /home/joe/Desktop/programs/android-studio-ide-192.6241897-linux/android-st
      udio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at
      /home/joe/Desktop/programs/android-studio-ide-192.6241897-linux/android-st
      udio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • STK L21 • TMFNW19726000813 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @JoDeveloper 
I recently [tested](https://github.com/flutter/flutter/issues/56708#issuecomment-627787587) image_picker and seems to work as intended;
could you please run flutter upgrade --force,
make sure you are using the latest version of image picker
```yaml
image_picker: ^0.6.6+1
```
if the issue persists please provide 
your updated `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by JoDeveloper** [comment]
ok @iapicca

**Comment by JoDeveloper** [comment]
**pubspec.yaml**
```
name: fstore
description: Mobile commerce app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.0+35

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.1
  html_unescape: 1.0.1+3
  provider: 4.0.5+1
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.8.1
  vector_math: 2.0.8
  carousel_pro: 1.0.0
  flutter_widget_from_html: 0.3.3
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.26
  share: 0.6.4
  validate: 1.7.0
  country_pickers: 1.2.1
  shared_preferences: 0.5.7
  firebase_messaging: 6.0.13
  firebase_analytics: 5.0.11
  transparent_image: 1.0.0
  pull_to_refresh: 1.5.8
  localstorage: 3.0.2+5
  notification_permissions: 0.4.4
  flare_splash_screen: 3.0.1
  rate_my_app: ^0.6.0+3
  page_indicator: 0.3.0
  intro_slider: 2.2.9
  url_launcher: 5.4.5
  extended_image: 0.7.3-dev # if using Flutter Master channel you should upgrade to 0.7.3-dev
  firebase_core: 0.4.4 # keep these version as there is new issue
  firebase_auth: 0.15.3 # with the latest firebase https://github.com/FirebaseExtended/flutterfire/issues/2084
  flutter_webview_plugin: 0.3.11
  connectivity: 0.4.8+2
  random_string: 2.0.1
  google_maps_flutter: 0.5.26+4
  cached_network_image: 2.1.0+1
  uuid: 2.0.4
  uni_links: 0.2.0
  flutter_staggered_grid_view: 0.3.0
  auto_size_text: 2.1.0
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.12
  video_player: 0.10.9+1
  flutter_spinkit: 4.1.2+1
  percent_indicator: 2.1.3
  animated_text_kit: 2.0.0
  wave: 0.0.8
  http_auth: 0.2.9
  firebase_admob: 0.9.3+2
  facebook_audience_network: 0.5.0
  pin_code_fields: 2.5.1
  flutter_facebook_login: 3.0.0
  webview_flutter: 0.3.21
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  custom_splash: 0.0.2
  apple_sign_in: 0.1.0
  google_sign_in: 4.4.4
  google_fonts: 1.0.0
  flutter_statusbarcolor: 0.2.3
  app_settings: 4.0.0
  animated_splash: 1.0.0
  firebase_database: 3.1.3
  event_bus: 1.1.1
  country_code_picker: 1.3.11
  flutter_typeahead: 1.8.0
  cloud_firestore: 0.13.4
  firestore_ui: ^1.9.1

  flash: 1.3.1
  flutter_cupertino_date_picker: 1.0.23+1
  image_picker: ^0.6.6+1
  location: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.4
  pedantic: 1.8.0+1 # Analysis
  flutter_driver:
    sdk: flutter

# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/mocks/
    - lib/config/states/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - assets/images/background/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons.ttf
    - family: Entypo
      fonts:
        - asset: assets/fonts/Entypo.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/fonts/MaterialCommunityIcons.ttf
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
```
