### ISSUE TITLE
[iOS]  Xcode installation is incomplete...

### ISSUE THREAD

**Issue by rayad** [flutter/flutter#57410]
```bash
Running "flutter pub get" in schoolapp...                        

The current Flutter SDK version is 0.0.0-unknown.
Because connectivity 0.4.8+6 requires Flutter SDK version >=1.12.13+hotfix.5 <2.0.0 and no versions of connectivity match >0.4.8+6 <0.5.0, connectivity ^0.4.8+6 is forbidden.

So, because schoolapp depends on connectivity ^0.4.8+6, version solving failed.
pub get failed (1; So, because schoolapp depends on connectivity ^0.4.8+6, version solving failed.)
exit code 1
```

this error is coming for almost all the plugins.
  I am using Mac and after i restarted my machine then i start getting the error.
I tried below steps to fix this issue.

```console
flutter upgrade
flutter clean
uninstall and install flutter
git upgrade
```
and follow the suggestions given in these links.

https://github.com/flutter/flutter/issues/24956

https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

Here is the output of Flutter Doctor

```console
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-IN)
    • Flutter version 1.17.1 at /Users/rayad/Desktop/flutter
    • Framework revision f7a6a7906b (4 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rayad/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
(base) 

I am out of options now.

**Comment by TaimoorHassan** [comment]
where exactly does 

> SDK version is 0.0.0-unknown

This show up ?

**Comment by rayad** [comment]
@TaimoorHassan When i save the pubspecs.yaml file or when i try to run the app.

**Comment by iapicca** [comment]
Hi @rayad 
can you please provide your `pubspec.yaml` , 
your `flutter pub get --verbose` 
Thank you

**Comment by rayad** [comment]
I run the command and below is the output. One important thing i observed i am getting this error only after my Mac restarted. 

```
name: testapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  flutter:
    sdk: flutter
  shimmer: ^1.0.1
  font_awesome_flutter: ^8.8.1
  geocoder: ^0.2.1
  geolocator: ^5.3.1
  permission_handler: ^4.4.0+hotfix.2
  android_intent: ^0.3.6+12
  device_info: ^0.4.0+1
  localstorage: ^3.0.2+5
  shared_preferences: ^0.5.7
  get_ip: ^0.4.0
  local_auth: ^0.6.2+1
  image_picker: ^0.6.6+1
  image_cropper: ^1.2.2
  mime: ^0.9.6+3
  toast: ^0.1.5
  dio: ^3.0.9
  path: 1.6.4
  #connectivity: '>=0.4.y+x <2.0.0'
  connectivity: ^0.4.8+6
  rxdart: ^0.24.0
  auto_route: ^0.5.0

  
  #trust_location: ^2.0.10
  #root_checker: ^0.1.3
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.5.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/tmp_img/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
       - asset: assets/fonts/Pacifico-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
