### ISSUE TITLE
Getting dependencies is not working - pub get failed (server unavailable)

### ISSUE THREAD

**Issue by echanlee** [flutter/flutter#57502]
When I run flutter pub get on a newly cloned repo this is what I get

```
Package doesn't exist (the pubspec for firebase_dynamic_links 0.5.0+5 from git has version 0.5.0+8).
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Package doesn't exist (the pubspec for firebase_dynamic_links 0.5.0+5 from git has version 0.5.0+8).
pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
Package doesn't exist (the pubspec for firebase_dynamic_links 0.5.0+5 from git has version 0.5.0+8).
pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
Package doesn't exist (the pubspec for firebase_dynamic_links 0.5.0+5 from git has version 0.5.0+8).
pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
Package doesn't exist (the pubspec for firebase_dynamic_links 0.5.0+5 from git has version 0.5.0+8).
pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
Package doesn't exist (the pubspec for firebase_dynamic_links 0.5.0+5 from git has version 0.5.0+8).
pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
Package doesn't exist (the pubspec for firebase_dynamic_links 0.5.0+5 from git has version 0.5.0+8).
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
Running "flutter pub get" in cashcoach_app...                           
Package doesn't exist (the pubspec for firebase_dynamic_links 0.5.0+5 from git has version 0.5.0+8).
pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...
```
I've tried doing the solution [here ](https://github.com/flutter/flutter/issues/46641#issuecomment-574198530)

This is what happens when I do flutter doctor -v (I am currently running on visual studio code)

```
[√] Flutter (Channel unknown, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-CA)
    • Flutter version 1.17.1 at C:\Users\evett\Documents\cash coach\flutter
    • Framework revision f7a6a7906b (6 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\evett\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\evett\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available
```

This is the pubspec.yaml file

```
# Run:
# ```bash
# flutter pub run build_runner build --delete-conflicting-outputs
# ```
# to update models

name: application
description: application.

version: 1.0.5+20051501

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: 1.17.1

dependencies:
  after_layout: ^1.0.7+2
  amplitude_flutter: 1.4.0
  appmetrica_sdk: ^0.0.5+1
  android_intent: ^0.3.7+2
  async_redux: ^2.8.6
  cashcoach_common:
    path: ../cashcoach_common
  # catcher: ^0.1.4
  # charts_flutter: ^0.8.1
  charts_flutter:
    git:
      url: https://github.com/priezz/charts
      path: charts_flutter
  # charts_flutter:
  #   path: ../../../Modules/flutter/charts/charts_flutter
  # chewie: ^0.9.10
  cloud_firestore: ^0.13.5
  cloud_functions: ^0.5.0
  dotted_border: ^1.0.5
  # easy_web_view: ^1.0.1
  expandable: 3.0.1
  fijkplayer: ^0.8.3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.16.0
  # flutter_bugfender: ^1.1.0
  firebase_core: ^0.4.4+3
  firebase_crashlytics: ^0.1.3+3
  # firebase_dynamic_links: ^0.5.0+9
  firebase_dynamic_links:
    git:
      url: https://github.com/mrmilu/flutterfire.git
      path: packages/firebase_dynamic_links
      ref: firebase_dynamic_links-29
  # firebase_messaging: ^6.0.9
  firebase_messaging:
    git:
      url: https://github.com/Eddydpyl/flutterfire
      path: packages/firebase_messaging
  flutter:
    sdk: flutter
  flutter_appavailability: ^0.0.21
  flutter_branch_sdk: ^0.5.0
  flutter_cache_store: ^0.7.2
  # flutter_downloader:
  #   git:
  #     url: git://github.com/Mahfoud047/flutter_downloader.git
  flutter_device_type:
    git:
      url: https://github.com/leogouveia/flutter_device_type
      ref: add-has-notch
  #     ref: fix-uncompatibility-with-background-registeration-context
  flutter_html: 0.11.1
  flutter_launcher_icons: ^0.7.5
  flutter_local_auth_invisible: ^0.4.1+2
  # flutter_local_auth_invisible:
  #   path: ../../../Modules/flutter/local_auth
  # flutter_local_notifications: ^1.4.2
  # flutter_markdown: ^0.3.4
  flutter_markdown:
    # path: ../../../Modules/flutter/flutter_markdown
    git: https://github.com/priezz/flutter_markdown
  # flutter_money_formatter: ^0.8.3
  # flutter_search_bar:
  #   git: git://github.com/priezz/flutter-search-bar
  flutter_spinkit: ^4.1.2+1
  # flutter_svg: ^0.17.3+1
  flutter_svg:
    git: git://github.com/priezz/flutter_svg
  flutter_webview_plugin: ^0.3.11
  # flutter_web_auth: ^0.1.2
  #     commit: bb2126bd7bd6be9d6e77764a8c7fbfa8f6373815
  google_sign_in: ^4.4.6
  googleapis: ^0.55.0
  # icons_helper:
  #   git: git://github.com/sjmcdowall/icons_helper
  # intl: ^0.15.8
  # keyboard_visibility: ^0.5.6
  # local_auth: 0.5.3
  logger: ^0.9.1
  # logger_flutter: ^0.7.0
  multi_masked_formatter: ^0.1.1
  notification_permissions: ^0.4.4
  password: ^1.0.0
  path_provider: ^1.6.8
  provider: ^4.1.2
  provider_for_redux: ^1.1.1
  rect_getter: ^0.1.0
  # reflectable: any
  # rxdart: ^0.19.0
  sentry: ^3.0.1
  scroll_to_index: ^1.0.6
  shared_preferences: ^0.5.7+2
  # sliding_up_panel: ^0.3.4
  syncfusion_flutter_core: ^17.4.51
  # syncfusion_flutter_charts: ^17.3.26
  syncfusion_flutter_charts:
    # path: ../../../Modules/flutter/syncfusion_flutter_charts
    git: https://github.com/priezz/syncfusion_flutter_charts
  synchronized: ^2.2.0
  # tuple: ^1.0.2
  uni_links: ^0.2.0
  url_launcher: ^5.4.7
  # video_player: ^0.10.8+1

dev_dependencies:
  analyzer: ^0.39.8
  build_runner: ^1.10.0
  data_classes_generator:
    git:
      url: https://github.com/priezz/data_classes.git
      path: data_classes_generator
  # flutter_test:
  #   sdk: flutter
  lint: ^1.2.0
  # test: ^1.12.1

# dependency_overrides:
#   analyzer: ^0.39.4
#   # data_classes:
#   #   path: ../../../Modules/flutter/data_classes/data_classes/
#   # data_classes_generator:
#   #   path: ../../../Modules/flutter/data_classes/data_classes_generator/

flutter:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here. Each entry in this list
  # should have a "family" key with the font family name, and a "fonts" key with a list.
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: B612Mono
      fonts:
        - asset: assets/fonts/B612_Mono/B612Mono-Bold.ttf
          weight: 700
        - asset: assets/fonts/B612_Mono/B612Mono-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/B612_Mono/B612Mono-Italic.ttf
          style: italic
        - asset: assets/fonts/B612_Mono/B612Mono-Regular.ttf
          weight: 400
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Light.ttf
          weight: 200
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-LightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-BoldItalic.ttf
          style: italic
          weight: 700
    - family: IBMPlexSansCond
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans_Condensed/IBMPlexSansCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM_Plex_Sans_Condensed/IBMPlexSansCondensed-Italic.ttf
          style: italic
        - asset: assets/fonts/IBM_Plex_Sans_Condensed/IBMPlexSansCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM_Plex_Sans_Condensed/IBMPlexSansCondensed-Light.ttf
          weight: 200
        - asset: assets/fonts/IBM_Plex_Sans_Condensed/IBMPlexSansCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM_Plex_Sans_Condensed/IBMPlexSansCondensed-SemiBold.ttf
          weight: 600
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Italic.ttf
          style: italic
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Light.ttf
          weight: 200
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-SemiBold.ttf
          weight: 600
    - family: KomikaAxis
      fonts:
        - asset: assets/fonts/Komika_Axis/KOMIKAX.ttf

  # The following line ensures that the Material Icons font is included with your application
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/avatars/
    - assets/icons/categories/
    - assets/icons/navigation/
    - assets/icons/other/
    - assets/icons/social/
    - assets/icons/ui/
    - assets/illustrations/
    - assets/levels/
    - assets/other/
    - assets/screens/
    - assets/screens/benchmark/
    - assets/screens/profile/
    - assets/screens/track/
    - assets/screens/reply/
    - assets/flags/

# Run to update:
#   flutter packages pub run flutter_launcher_icons:main
flutter_icons:
  image_path_ios: "resources/icon_1024.png"
  image_path_android: "resources/icon.png"
  android: true
  adaptive_icon_background: "#2c2e30"
  ios: true
```
