### ISSUE TITLE
iOS app size on the App Store is 10x the same Android app on Google Play store

### ISSUE THREAD

**Issue by gapspt** [flutter/flutter#57578]
The issue is quite simple: The same project makes an iOS final build that is roughly 10 times the size of the Android one.

The iOS build is gigantic, around 300MB, but I know it contains bitcode, so I uploaded it to the store anyway. The size on the App Store is still way too large, 63.7MB, as can be seen here:
https://apps.apple.com/us/app/100-menu/id1513624029

It's android counterpart yet is just over 7MB:
https://play.google.com/store/apps/details?id=menu.a100.client
(I don't think it's possible to see the size until the install button is pressed, so I attached a screenshot)
![image](https://user-images.githubusercontent.com/5992125/82334730-49512480-99e0-11ea-9aa7-21b81a678b8c.png)

**Build commands:**
flutter build appbundle --obfuscate --split-debug-info=debug-info
flutter build ios --obfuscate --split-debug-info=debug-info

**Other environment details:**
flutter --version
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (7 days ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2

xcodebuild -version
Xcode 11.4.1
Build version 11E503a

flutter analyze
Analyzing client_100_menu_flutter...
No issues found! (ran in 8.9s)

**pubspec.yaml file:**
``` yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.2.0+1
  cupertino_icons: ^0.1.3
  diacritic: ^0.1.1
  extended_tabs: ^0.2.3
  flutter_cache_manager: ^1.2.2
  google_maps_flutter: ^0.5.27+3
  http: ^0.12.1
  i18n_extension: ^1.3.6
  url_launcher: ^5.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
```

Note 1: The assets/images contains a single image with 18 KB
Note 2: The entire ios folder (which contains the icon and launcher images) is 170 KB

This app size for quite a simple app is unbearable and users are not installing it as it generates distrust, because there is no way the app as it is described in the store can be 67 MB! (I wouldn't install it either)
