### ISSUE TITLE
NoSuchMethodError: The getter 'path' was called on null. When trying to build web app version.

### ISSUE THREAD

**Issue by astrO1** [flutter/flutter#58223]
I follow all the comands from Flutter oficial documentation for transform my app in a web project, this is the steps I followed to make the problem show

 **flutter channel beta
 flutter upgrade
 flutter config --enable-web**

When I execute this

**flutter devices**

worked fine and give me this result

**Web Server • web-server • web-javascript • Flutter Tools
Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129**

after I make this

**flutter create . ( to add web support to my project )** 

and finally when I do this 

**flutter run -d chrome**

just show me this error

```


Unhandled exception:
NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:150:65)
<asynchronous suspension>
#2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:627:20)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:533:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)
#5      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1164:26)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#9      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#10     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#11     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#12     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#13     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#14     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#15     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#19     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#20     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#21     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#22     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#23     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:315:20)
#24     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:308:5)
#25     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#31     _StreamController._add (dart:async/stream_controller.dart:655:7)
#32     _StreamController.add (dart:async/stream_controller.dart:597:5)
#33     _Socket._onData (dart:io-patch/socket_patch.dart:1999:41)
#34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#37     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#38     _StreamController._add (dart:async/stream_controller.dart:655:7)
#39     _StreamController.add (dart:async/stream_controller.dart:597:5)
#40     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1544:33)
#41     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1036:14)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
the Dart compiler exited unexpectedly.
Syncing files to device Chrome...                               20.944ms (!)
Failed to compile application.
```

This is my flutter doctor :

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [versÃ£o 10.0.18363.836], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Chrome - develop for the web
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.45.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @astrO1 
I just followed the same steps 
with the "hello world" app
without encountering issues

<details>
  <summary>logs</summary>

```bash
 nevercode@Nevercodes-Air  ~/Desktop/projects  flutter_beta create beta                                                                                    ✔  1671  11:26:44
Creating project beta...
  beta/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  beta/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  beta/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  beta/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  beta/ios/Flutter/Release.xcconfig (created)
  beta/ios/Flutter/Debug.xcconfig (created)
  beta/ios/Flutter/AppFrameworkInfo.plist (created)
  beta/ios/.gitignore (created)
  beta/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  beta/ios/Runner/Base.lproj/Main.storyboard (created)
  beta/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  beta/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  beta/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  beta/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  beta/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  beta/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  beta/ios/Runner/Info.plist (created)
  beta/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  beta/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  beta/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  beta/test/widget_test.dart (created)
  beta/.gitignore (created)
  beta/web/favicon.png (created)
  beta/web/index.html (created)
  beta/web/manifest.json (created)
  beta/web/icons/Icon-512.png (created)
  beta/web/icons/Icon-192.png (created)
  beta/.metadata (created)
  beta/android/app/src/profile/AndroidManifest.xml (created)
  beta/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  beta/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  beta/android/app/src/main/res/drawable/launch_background.xml (created)
  beta/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  beta/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  beta/android/app/src/main/res/values/styles.xml (created)
  beta/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  beta/android/app/src/main/AndroidManifest.xml (created)
  beta/android/app/src/debug/AndroidManifest.xml (created)
  beta/android/gradle/wrapper/gradle-wrapper.properties (created)
  beta/android/gradle.properties (created)
  beta/android/.gitignore (created)
  beta/android/settings.gradle (created)
  beta/android/app/build.gradle (created)
  beta/android/app/src/main/kotlin/com/example/beta/MainActivity.kt (created)
  beta/android/beta_android.iml (created)
  beta/android/build.gradle (created)
  beta/beta.iml (created)
  beta/README.md (created)
  beta/pubspec.yaml (created)
  beta/ios/Runner.xcodeproj/project.pbxproj (created)
  beta/ios/Runner/AppDelegate.swift (created)
  beta/ios/Runner/Runner-Bridging-Header.h (created)
  beta/lib/main.dart (created)
  beta/.idea/libraries/Dart_SDK.xml (created)
  beta/.idea/libraries/KotlinJavaRuntime.xml (created)
  beta/.idea/modules.xml (created)
  beta/.idea/workspace.xml (created)
  beta/.idea/runConfigurations/main_dart.xml (created)
Running "flutter pub get" in beta...                                2.5s
Wrote 76 files.

All done!
[✓] Flutter: is fully installed. (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.3.1)
[✓] Chrome - develop for the web: is fully installed.
[✓] Android Studio: is fully installed. (version 3.6)
[✓] VS Code: is fully installed.
[✓] Connected device: is fully installed. (5 available)

In order to run your application, type:

  $ cd beta
  $ flutter run

Your application code is in beta/lib/main.dart.

 nevercode@Nevercodes-Air  ~/Desktop/projects  cd beta                                                                                                     ✔  1672  11:27:23
 nevercode@Nevercodes-Air  ~/Desktop/projects/beta  flutter_beta config --enable-web                                                                       ✔  1673  11:27:33
Setting "enable-web" value to "true".

You may need to restart any open editors for them to read new settings.
 nevercode@Nevercodes-Air  ~/Desktop/projects/beta  flutter_beta create .                                                                                  ✔  1674  11:27:44

Recreating project ....
Wrote 3 files.

All done!
[✓] Flutter: is fully installed. (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.3.1)
[✓] Chrome - develop for the web: is fully installed.
[✓] Android Studio: is fully installed. (version 3.6)
[✓] VS Code: is fully installed.
[✓] Connected device: is fully installed. (5 available)

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.

 nevercode@Nevercodes-Air  ~/Desktop/projects/beta  flutter_beta run -d chrome                                                                             ✔  1675  11:28:16
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...
23,537ms (!)
Debug service listening on ws://127.0.0.1:58953/83YFHH0Qq6o=

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
For a more detailed help message, press "h". To quit, press "q".

Application finished.
 nevercode@Nevercodes-Air  ~/Desktop/projects/beta 
```

</details>


Can you please provide your `pubspec.yaml` 
and a minimal complete reproducible code sample.
Thank you

**Comment by astrO1** [comment]
Of couse

```

name: App44Online
description: Plataforma online que conecta lojistas da 44 e revendedoras do Brasil inteiro.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+10

environment:
  sdk: ">=2.7.0 < 3.0.0"

dependencies:
  font_awesome_flutter: ^8.8.1
  configurable_expansion_tile: ^1.0.0
  flutter_widget_from_html: ^0.3.3+4
  transparent_image: ^1.0.0
  flutter_sticky_header: "^0.4.2"
  visibility_detector: ^0.1.5
  flutter_staggered_grid_view: "^0.3.0"
  extended_image: ^0.8.0
  cached_network_image: ^2.2.0+1
  carousel_pro: ^1.0.0
  shared_preferences: ^0.5.7+3
  event_bus: ^1.1.1
  pull_to_refresh: ^1.5.7
  provider: ^4.1.2
  after_layout: ^1.0.7+2
  google_fonts: ^1.0.0
  intl: ^0.16.1
  url_launcher: ^5.4.5
  video_player:
  animations: ^1.0.0+5
  progress_dialog: ^1.2.2
  fluttertoast: ^4.0.0
  responsive_builder:
  device_preview:
  page_transition: "^1.1.5"
  flutter_spinkit: "^4.1.2"
  flutter_swiper: ^1.1.6
  rxdart: "0.23.1"
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_mobile.png"
  adaptive_icon_background: "#3f1585"
  adaptive_icon_foreground: "assets/icons/adaptive_logo_mobile.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/icons/error/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
