### ISSUE TITLE
Sliding between tabs is very sluggish/unnatural [web] on some devices 

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#58526]
Demo recorded on Samsung A40 (SM-A405FN): https://youtu.be/4f3Qnstxzic 
<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel dev, 1.19.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale es-ES)
    • Flutter version 1.19.0-2.0.pre at /Users/tomas/Development/flutter
    • Framework revision 1d395c5e18 (2 days ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • iPhone 11  • 04298E38-2633-4586-B868-1FBD5C708AF7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @tomasbaran 
Tested this [example](https://flutter.dev/docs/cookbook/design/tabs), performance is fine on web on android chrome

Can you please provide and a minimal complete reproducible code sample.
Thank you"

**Comment by tomasbaran** [comment]
## The original issue (#58526)
Uff, man. It took me a few hours to play with it until I found what's causing the sluggishness but I got it :) 

It's the ListView as children in the TabBarView widget. Here is the live demo: https://experiment0.firebaseapp.com
<details>
<summary>Minimal reproduction code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              ListView(children: [Icon(Icons.directions_car)]),
              ListView(children: [Icon(Icons.directions_transit)]),
              ListView(children: [Icon(Icons.directions_bike)]),
            ],
          ),
        ),
      ),
    );
  }
}

```
</details>

The issue is with the gesture detection delay. When I slide my thumb to the right/left minimal distance (I don't know maybe 1mm), there are 2 possible scenarios:

- if my children in the TabBarView are NOT ListViews: there is no gesture detection delay and detects my left/right slide movement right away
- if my children in the TabBarView ARE ListViews: there is gesture detection delay and it takes a little distance until it detects that I'm sliding right/left. 

Surely, it's because the gesture detector is confused and doesn't know whether to look for up/down movement or left/right movement. BUT, there is no gesture confusion on iPhone XR, only on Samsung A40.

## Second issue

I tried your demo and I wouldn't say it's permorning very well on Samsung A40 either. I'd say it performed like this:

- on iPhone XR (real device iOS 13.5): 100%
- Samsung A40 (real device Android 9): 90% (it doesn't react on all of my swipes only on 9 out of 10)

## Third issue

Then I adjusted your sample code and it got multiple times frozen (when one of the left or right tabs was selected) to a point that I had to refresh the page:

<details>
<summary> Adjusted Sample Code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            title: Text('Tabs Demo'),
          ),
          body: Column(
            children: [
              Padding(
                padding: const EdgeInsets.only(top: 8.0),
                child: TabBar(
                  isScrollable: true,
                  labelColor: Colors.pink,
                  unselectedLabelColor: Colors.pink,
                  indicatorColor: Colors.pink,
                  indicatorSize: TabBarIndicatorSize.label,
                  indicatorWeight: 1,
                  indicatorPadding: EdgeInsets.fromLTRB(0, 0, -24, 12),
                  labelPadding: EdgeInsets.only(
                    bottom: 0,
                    left: 24,
                    right: 24,
                  ),
                  labelStyle: Theme.of(context).textTheme.subtitle1,
                  tabs: [
                    Tab(
                      text: 'ENTRANTES',
                    ),
                    Tab(text: 'MARISCOS'),
                    Tab(text: 'PIZZASANTORINI'),
                  ],
                ),
              ),
              TabBarView(
                children: [
                  Icon(Icons.directions_car),
                  Icon(Icons.directions_transit),
                  Icon(Icons.directions_bike),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by tomasbaran** [comment]
Just adding to the knowledgebase. I just found an even more extreme example where sliding btw tabs is just horrible on Android:

May be related: https://github.com/flutter/flutter/issues/62670

A. See video: https://youtu.be/KGaINlhww6s

or 

B. Open: https://experiment25.web.app/#/ on Samsung A20 (run it on the latest OS for Samsung A20 which is Android 9)

or

C. Run min repro code


## Min repro code
<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'screens/demo_screen.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DemoScreen(),
    );
  }
}
```
</details>

<details>
<summary>demo_screen.dart</summary>

```dart
import 'package:chefmenu2/theme/style_constants.dart';
import 'package:chefmenu2/widgets/gradient_background_wrapper.dart';
import 'package:flutter/material.dart';
import 'package:chefmenu2/widgets/my_tab_bar.dart';

class DemoScreen extends StatelessWidget {
  static String id = '/demo';

  List<Widget> listViewItems() {
    List<Widget> items = [];

    for (int i = 0; i < 500; i++) {
      Widget widgetItem = Text(
        'item $i',
        textAlign: TextAlign.center,
        style: TextStyle(color: Colors.white),
      );
      items.add(widgetItem);
    }
    return items;
  }

  List<Widget> tabbarViewItems() {
    List<Widget> items = [];
    for (int i = 0; i < 25; i++) {
      Widget listView = ListView(children: listViewItems());
      items.add(listView);
    }
    return items;
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 25,
      child: Scaffold(
        floatingActionButton: MyTabBar(),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
        body: GradientBackgroundWrapper(
            child: TabBarView(
          children: tabbarViewItems(),
        )),
      ),
    );
  }
}

```
</details>

<details>
<summary>my_tab_bar.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:chefmenu2/theme/style_constants.dart';
import 'package:chefmenu2/widgets/custom_icon.dart';

class MyTabBar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.symmetric(horizontal: 4),
      padding: EdgeInsets.all(6),
      width: MediaQuery.of(context).size.width,
      decoration: BoxDecoration(
        color: colorShade3,
        borderRadius: BorderRadius.circular(30),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30),
        child: TabBar(
          isScrollable: true,
          labelColor: Colors.black,
          unselectedLabelColor: colorShade2,
          indicatorColor: Colors.white,
          indicator: BoxDecoration(shape: BoxShape.rectangle, borderRadius: BorderRadius.all(Radius.circular(30)), color: Colors.white),
          tabs: [
            Tab(icon: CustomIcon('icons/001-sausage-2.svg')),
            Tab(icon: CustomIcon('icons/028-steak.svg')),
            Tab(icon: CustomIcon('icons/061-pizza-2.svg')),
            Tab(icon: CustomIcon('icons/117-hot-dog.svg')),
            Tab(icon: CustomIcon('icons/185-cocktail.svg')),
            Tab(icon: CustomIcon('icons/001-sausage-2.svg')),
            Tab(icon: CustomIcon('icons/028-steak.svg')),
            Tab(icon: CustomIcon('icons/061-pizza-2.svg')),
            Tab(icon: CustomIcon('icons/117-hot-dog.svg')),
            Tab(icon: CustomIcon('icons/185-cocktail.svg')),
            Tab(icon: CustomIcon('icons/001-sausage-2.svg')),
            Tab(icon: CustomIcon('icons/028-steak.svg')),
            Tab(icon: CustomIcon('icons/061-pizza-2.svg')),
            Tab(icon: CustomIcon('icons/117-hot-dog.svg')),
            Tab(icon: CustomIcon('icons/185-cocktail.svg')),
            Tab(icon: CustomIcon('icons/001-sausage-2.svg')),
            Tab(icon: CustomIcon('icons/028-steak.svg')),
            Tab(icon: CustomIcon('icons/061-pizza-2.svg')),
            Tab(icon: CustomIcon('icons/117-hot-dog.svg')),
            Tab(icon: CustomIcon('icons/185-cocktail.svg')),
            Tab(icon: CustomIcon('icons/001-sausage-2.svg')),
            Tab(icon: CustomIcon('icons/028-steak.svg')),
            Tab(icon: CustomIcon('icons/061-pizza-2.svg')),
            Tab(icon: CustomIcon('icons/117-hot-dog.svg')),
            Tab(icon: CustomIcon('icons/185-cocktail.svg')),
          ],
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>style_constants.dart</summary>

```dart
import 'package:flutter/material.dart';

const Color colorShade1 = Color(0xFFEFF0F2);
const Color colorShade2 = Color(0xFF777777);
const Color colorShade3 = Color(0xFF424242);
const Color colorShade4 = Color(0xFF4B4935);
const Color colorShade5 = Color(0xFF3D2916);
const Color colorShade6 = Color(0xFF1D1C0A);

const double kTabIconHeight = 28;

```
</details>

<details>
<summary>gradient_background_wrapper.dart</summary>
```dart
import 'package:flutter/material.dart';

const Color colorShade1 = Color(0xFFEFF0F2);
const Color colorShade2 = Color(0xFF777777);
const Color colorShade3 = Color(0xFF424242);
const Color colorShade4 = Color(0xFF4B4935);
const Color colorShade5 = Color(0xFF3D2916);
const Color colorShade6 = Color(0xFF1D1C0A);

const double kTabIconHeight = 28;

```
</details>

<details>
<summary>pubspec.yaml</summary>

```yaml
name: chefmenu2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


```
</details>




**Target Platform:** web, engine:skia: `flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true --release`
**Target OS version/browser:** Android 9/Chrome
**Devices:** Samsung A20

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.117, on Mac OS X 10.15.5 19F101, locale es-ES)
    • Flutter version 1.21.0-6.0.pre.117 at /Users/tomas/Development/flutter
    • Framework revision 7ec2d360bc (27 hours ago), 2020-07-29 23:25:38 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • iPhone (mobile)    • 00008020-000415840E50003A            • ios            • iOS 14.0
    • iPhone 11 (mobile) • 04298E38-2633-4586-B868-1FBD5C708AF7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>
