### ISSUE TITLE
Unable to update xml package due to flutter_test

### ISSUE THREAD

**Issue by enricobenedos** [flutter/flutter#58597]
Good Morning,
I'm trying to update the `xml` package included on my project but seems that I cannot do that due to a conflict with `flutter_test` package. 
## Steps to Reproduce

1. add `xml: ^3.7.0` to `pubspec.yaml`
```yaml
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  intl: ^0.16.1
  local_auth: ^0.6.1
  random_string: ^2.0.1
  shared_preferences: ^0.5.6+1
  queries: ^0.1.14
  flutter_markdown: ^0.4.1
  simple_gravatar: ^1.0.5
  xml: ^3.7.0
  package_info: ^0.4.0+13
  sticky_headers: ^0.1.8+1
  provider: ^4.0.4
  flutter_bloc: ^4.0.0
  equatable: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter
```
2. `flutter pub get`

**Actual results:** 
`Because every version of flutter_test from sdk depends on xml 3.6.1 and fcsreport_flutter_app depends on xml ^3.7.0, flutter_test from sdk is forbidden.
So, because fcsreport_flutter_app depends on flutter_test any from sdk, version solving failed.`

```
PS E:\Projects\VS CODE\report-mobile-flutter> flutter doctor -v
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.17.2 at C:\SDKs\flutter
    • Framework revision 5f21edf8b6 (6 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\enricobenedos\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\enricobenedos\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```
```
PS E:\Projects\VS CODE\report-mobile-flutter> flutter analyze
Because every version of flutter_test from sdk depends on xml 3.6.1 and fcsreport_flutter_app depends on xml ^3.7.0, flutter_test from sdk is forbidden.
So, because fcsreport_flutter_app depends on flutter_test any from sdk, version solving failed.
Running "flutter pub get" in report-mobile-flutter...
pub get failed (1; So, because fcsreport_flutter_app depends on flutter_test any from sdk, version solving failed.)
```
Removing `flutter_test` it works but I cannot do that due to the fact that I use test package.
