### ISSUE TITLE
Abnormal running to iOS device through Android Studio

### ISSUE THREAD

**Issue by HLQ-Struggle** [flutter/flutter#58739]
Hello, when I run on iOS devices through Android Studio, Android Studio prompts as follows:

```
Launching lib/main.dart on HLQ_Struggle in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: xxx
Running Xcode build...
Xcode build done.                                           39.9s
Could not find the built application bundle at build/ios/iphoneos/Runner.app.
Error launching application on HLQ_Struggle.
```

When I searched for the corresponding path address according to the prompt, I found that the Runner.app generated in the prompt directory was not Runner.app, but xxx.app named after our project. So what can I do to run directly to iOS devices in Android Studio?

**Comment by iapicca** [comment]
Hi @HLQ-Struggle 
does this [solution](https://github.com/flutter/flutter/issues/58601#issuecomment-638704859) works for you?

Are you experiencing the issue only with Android Studio / IntelliJ or with VS Code as well?

Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and your `pubspec.yaml`
Thank you

**Comment by HLQ-Struggle** [comment]
Hi @iapicca 

## flutter doctor -v

```
Last login: Fri Jun  5 06:14:16 on ttys000
 heliquan@Mac  ~  flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.5 19F101, locale
    zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/HLQ/flutter
    • Framework revision e6b34c2b5c (5 周前), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/HLQ/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/HLQ/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • PCT AL10     • xxx          • android-arm64 • Android 10 (API
      29)
    • HLQ_Struggle • xxx• ios           • iOS 13.4.1

• No issues found!
```

## flutter run --verbose

Brother, I think this log is too long, so only the abnormal part is intercepted.

```
[+1012 ms] Could not find the built application bundle at build/ios/iphoneos/Runner.app.
[   +2 ms] Error launching application on HLQ_Struggle.
[   +6 ms] "flutter run" took 63,083ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#19     _rootRun (dart:async/zone.dart:1184:13)
#20     _CustomZone.run (dart:async/zone.dart:1077:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## pubspec.yaml

```
name: Test
description: 

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.7+2
  permission_handler: ^5.0.0+hotfix.6
  fluro: ^1.6.3
  dio: ^3.0.9
  fluttertoast: ^4.0.1
  connectivity: ^0.4.4
  crypto: ^2.1.4
  flutter_easyloading: ^1.1.4
  device_info: ^0.4.2+4
  flutter_easyrefresh: ^2.1.1
  transparent_image: ^1.0.0
  webview_flutter: ^0.3.22+1
  flutter_html: ^1.0.0
  url_launcher: ^5.4.10
  package_info: ^0.4.0+18

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/graphics/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Fredoka
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf
```
