### ISSUE TITLE
Help - no text or any widget show correctly

### ISSUE THREAD

**Issue by niypoo** [flutter/flutter#59214]
Sorry if issue details is less but I can't catch the error yet.
I have noticed this issue only in ios and only when I open the app and make it in background not close it and after duration of time open the app it's happen, and when close the app and re-open again it's work normal.

in development mode it's not show  , and in firebase Crashlytics only catch any error  related with this issue.

only I have recorded to catch this issue.
![DB3705FC-E713-4D05-AB72-D4D40A61127A_1_105_c](https://user-images.githubusercontent.com/13227239/84328288-dcb1eb80-ab81-11ea-8270-03cea5d82ae7.jpeg)
![D98AFDA2-A9B7-48C9-A75E-408721440E77_1_105_c](https://user-images.githubusercontent.com/13227239/84328292-e3d8f980-ab81-11ea-8a97-2150d685c8fd.jpeg)

any advice for how can catch what is wrong

```

Last login: Tue Jun  9 17:09:14 on ttys001
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Mahmouds-MacBook-Pro:~ mahmoudnabhan$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.3 19D76, locale en-EG)
    • Flutter version 1.17.3 at /Volumes/SSD/Library/flutter
    • Framework revision b041144f83 (6 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Volumes/SSD/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Volumes/SSD/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Volumes/SSD/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[✓] Connected device (1 available)
    • Mahmoud’s iPhone • d9e2b71bdf6e24f7520962be8965ef34a16c0f52 • ios • iOS 13.5.1

! Doctor found issues in 1 category.

```

```
version: 0.0.4+0.4.1
environment:
  sdk: ">=2.3.0 <3.0.0"

dependency_overrides:
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_auth: any #^0.16.0 #0.15.5+3 #^0.15.4 #updated from ^0.15.3+1 
  flutter_local_notifications: ^1.4.2  #^1.1.5+1 #updated from ^0.8.4+3
  firebase_messaging: ^6.0.13 #updated from 6.0.2 #------->
  firebase_dynamic_links: ^0.5.1  #^0.5.0+8 #------->
  cached_network_image: ^2.1.0+1 #^2.0.0 #------->
  apple_sign_in: ^0.1.0 #------->
  flutter_sticky_header: ^0.4.2  #^0.4.0 #------->
  shared_preferences: ^0.5.7 #^0.5.6+2  #^0.5.6 #------->
  flutter_spinkit: ^4.1.2+1 #^4.1.2  #^4.1.1+1 #------->
  # in_app_purchase: ^0.3.4  #^0.2.2+4 #------->
  purchases_flutter: ^1.1.1
  webview_flutter: ^0.3.20+2 #^0.3.20 #------->^0.3.10+1
  flutter_vibrate: ^1.0.0 #------->
  jiffy: ^3.0.1 #^3.0.0 #^2.2.0 #------->
  connectivity: ^0.4.8+2 #^0.4.8+1 #^0.4.6+2 #------->
  device_info: ^0.4.2+2 #^0.4.1+5 #------->
  rate_my_app: ^0.6.0+2  #^0.6.0 #------->
  firebase_remote_config: ^0.3.0+3  #^0.3.0+1 #------->
  soundpool: ^1.0.1 #------->
  swipedetector: ^1.2.0 #------->
  carousel_pro: ^1.0.0 #------->
  google_places_picker: ^2.1.0+2 #------->
  # flutter_facebook_login: ^3.0.0 #-------> deprecated
  flutter_facebook_auth: ^0.2.2+1
  flutter_twitter_login:
    git: 
      url: https://github.com/Kiruel/flutter_twitter_login
  # flutter_twitter: ^1.1.3 #-------> to avoid release issue
  # flutter_twitter_login:
  #   git: git://github.com/eudangeld/flutter_twitter_login.git
  flushbar: ^1.10.0 #^1.9.1 #-------> 
  provider: ^4.1.3  #^4.0.5+1 #^4.0.4 #^3.1.0+1
  cloud_firestore: 0.13.4+2  #^0.13.4+1 
  intl: ^0.16.1 #^0.16.0
  google_sign_in: ^4.4.4 #^4.1.4 # ^4.0.11
  google_maps_flutter: ^0.5.26+4 #^0.5.25+3  #^0.5.21+15
  share: ^0.6.4+3 #^0.6.3+6 #^0.6.3+3
  flare_flutter: ^2.0.3 #^2.0.1
  flutter_slidable: ^0.5.4
  http: ^0.12.0+4 #^0.12.0+2
  sqflite: ^1.3.0 #^1.2.2
  flutter_translate: ^1.6.0 #^1.5.7
  geolocator: ^5.3.1 #^5.3.0 #^5.1.5
  introduction_screen: ^1.0.8
  flutter_platform_widgets: ^0.32.5  #^0.32.4 
  font_awesome_flutter: ^8.8.1 #^8.7.0
  firebase_analytics: ^5.0.11
  translator: ^0.1.4
  speech_to_text: ^2.1.0 #^2.0.1
  quick_actions: ^0.4.0+4 #^0.4.0+2
  flutter_background_geolocation: ^1.8.0 #flutter_background_geolocation: ^1.7.3
  nanoid: ^0.1.0
  firebase_crashlytics: ^0.1.3+3
  floating_action_row: ^0.1.0
  # numberpicker: ^1.2.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: "^0.7.4"
```
