### ISSUE TITLE
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.

### ISSUE THREAD

**Issue by liudonghua123** [flutter/flutter#59750]
## Steps to Reproduce

1. I used the master channel of flutter
2. Then I want to build linux binary for upload to release. The releated github action file is below.

```yaml
name: Linux-CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Change flutter channel to master, enable linux support
        run: |
          flutter channel master
          flutter upgrade
          flutter config --enable-linux-desktop
          flutter pub get

      - name: Build linux
        run: |
          flutter build linux

      - name: Debug
        run: |
          sudo npm install tree-node-cli -g
          treee build

      - name: Prepare release files
        run: |
          cp -r build/linux/release python_exercise_builder-linux-${{ steps.branch_name.outputs.SOURCE_NAME }}
          zip python_exercise_builder-linux-${{ steps.branch_name.outputs.SOURCE_NAME }}.zip -r python_exercise_builder-linux-${{ steps.branch_name.outputs.SOURCE_NAME }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: python_exercise_builder-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
```

3. When the ci run, it failed with the following error.

**Expected results:** 
Linux build successfully.

**Actual results:** 
Linux build failed.

<details>
  <summary>Logs</summary>

```
Run flutter build linux
Downloading linux-x64/linux-x64-flutter-gtk tools...                1.5s
Downloading linux-x64-profile/linux-x64-flutter-gtk tools...         0.9s
Downloading linux-x64-release/linux-x64-flutter-gtk tools...         0.8s
Building Linux application...                                   
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Unable to generate build files
##[error]Process completed with exit code 1.
```

```
```

```
```

</details>
