### ISSUE TITLE
[Bug] Flutter Blank Screen on IOS

### ISSUE THREAD

**Issue by duongtruong12** [flutter/flutter#59754]
Flutter Application showing **blank screen** when kept in the background about half an hour that means when I resuming the app after sometime it is showing blank screen. If anyone experienced this problem could you help me please. For normal resuming (i.e, minimize and resuming), the application was working without any problem. But after some **long time(more than 1 hour)** it was showing blank screen. After killed app and turn it on again it was fine
Here I am sharing application screenshot when I got the blank screen.

Plugin using: 
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation: ^0.17.7
  cupertino_icons: ^0.1.3
  shared_preferences: 0.5.6+1
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.12
  google_sign_in: ^4.5.1
  oauth2: ^1.6.1
  io: ^0.3.4
  url_launcher: ^5.4.11
  path_provider: ^1.6.11
  background_fetch: ^0.5.5
  connectivity: ^0.4.8+6
  charts_flutter: ^0.9.0
  package_info: ^0.4.1
  flutter_circular_chart: ^0.1.0
  launch_review: ^2.0.0
  frideos: ^1.0.1
  dio: ^3.0.8
  webview_flutter: ^0.3.22+1
  oauth1: ^1.0.4
  provider: ^4.1.3
  flutter_webview_plugin: ^0.3.11
  barcode_scan: ^3.0.1
  quiver: ^2.1.3
  logger: ^0.9.1
  flutter_advanced_networkimage: ^0.6.2
  flutter_datetime_picker: ^1.3.8
  flutter_linkify: ^3.1.0
  flutter_svg: ^0.17.4
  mp_chart: ^0.2.1
  auto_size_text: ^2.1.0
  dots_indicator: ^1.1.0
  image_picker: 0.6.3+4
  sprintf: ^4.0.2
  device_apps: ^1.0.9
  timeago: ^2.0.26
  selectable_autolink_text: ^1.3.1
  table_calendar: ^2.2.3
  permission_handler: ^5.0.0+hotfix.4

  flutter_local_notifications: ^1.4.3
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.6

  android_alarm_manager:
    path: ../../plugin/android_alarm_manager
```

Flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.3 at /Users/macos/flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macos/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/macos/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
• No issues found!
```

![IMG_0913](https://user-images.githubusercontent.com/32258832/85009102-18534380-b188-11ea-8143-49aa759f5a11.PNG)
