### ISSUE TITLE
Framework crash in showAboutDialog()

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#59881]
## Steps to reproduce

Run the following app.  Then click the "About" popup menu item after clicking "Click Me".

```dart
import 'dart:ui' show window;

import 'package:flutter/material.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Localizations(
      locale: Locale('en', 'US'),
      delegates: [
        DefaultWidgetsLocalizations.delegate,
        DefaultMaterialLocalizations.delegate,
      ],
      child: MediaQuery(
        data: MediaQueryData.fromWindow(window).copyWith(size: const Size(800, 600)),
        child: Directionality(
          textDirection: TextDirection.ltr,
          child: Navigator(
            onGenerateRoute: (RouteSettings settings) {
              return MaterialPageRoute<void>(
                settings: settings,
                builder: (BuildContext context) {
                  return Material(
                    child: PopupMenuButton<int>(
                      child: Text('Click Me'),
                      itemBuilder: (BuildContext context) {
                        return <PopupMenuEntry<int>>[
                          PopupMenuItem(
                            value: 1,
                            child: Text('About'),
                          ),
                        ];
                      },
                      onSelected: (int value) {
                        showAboutDialog(context: context);
                      },
                    ),
                  );
                },
              );
            },
          ),
        ),
      ),
    );
  }
}
```

## Expected Behavior

You expect to see a basic about dialog without any errors.

## Actual behavior

You get the following exception (the specific numbers differ based on device, but I was able to replicate the exception in Android, iOS, and MacOS):

```
The following assertion was thrown during performLayout():
RenderIntrinsicWidth does not meet its constraints.
Constraints:
  BoxConstraints(280.0<=w<=331.4, 0.0<=h<=611.4)
Size:
  Size(259.0, 184.0)
If you are not writing your own RenderBox subclass, then this is not your fault. Contact support:
https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  Navigator file:///Users/tvolkert/project/sci/apps/payouts/lib/bug_report.dart:19:18

When the exception was thrown, this was the stack:
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1977:9)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2036:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1754:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1756:6)
#4      RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:653:7)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#13     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#15     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:270:13)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#17     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:396:13)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#19     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#21     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#36     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3221:13)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1774:7)
#38     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
#39     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1637:7)
#40     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:894:18)
#41     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
#42     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
#43     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#44     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1115:15)
#45     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1054:9)
#46     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:970:5)
#50     _invoke (dart:ui/hooks.dart:269:10)
#51     _drawFrame (dart:ui/hooks.dart:227:3)
(elided 3 frames from dart:async)

The following RenderObject was being processed when the exception was fired: RenderIntrinsicWidth#b3cb6 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: IntrinsicWidth ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
    _InkFeatures-[GlobalKey#5cb52 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
    CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← _MaterialInterior ← Material ← ConstrainedBox ←
    ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(280.0<=w<=331.4, 0.0<=h<=611.4)
  size: Size(259.0, 184.0)
  stepWidth: null
  stepHeight: null
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderFlex#193c0 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child 1: RenderRepaintBoundary#7ffb3 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderCustomPaint#bbcf8 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderRepaintBoundary#8bf04 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: _RenderScrollSemantics#42c8c relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child 2: RenderPadding#94830 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderPadding#8a396 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: _RenderButtonBarRow#99717 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child 1: RenderPadding#8b6e5 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child 2: RenderPadding#701bf relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
════════════════════════════════════════════════════════════════════════════════════════════════════
```
