### ISSUE TITLE
This is not working with chewie

### ISSUE THREAD

**Issue by imSanjaySoni** [flutter/flutter#59925]
@WoKee  try this
```yaml
video_player:
    git:
      url: git://github.com/shmy/video_player_flutter.git
```

_Originally posted by @shmy in https://github.com/flutter/flutter/issues/28494#issuecomment-476198373_
