### ISSUE TITLE
Too many different d: unknown option: -target error

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#59974]
Hi,
    I am trying to build my ios for submission but suprisingly when I build from xcode and run on my phone or emulator no error. Then I go to visual code terminal and run this command flutter build ios --release --no-codesign 
I get few different error example some times is this 

```
Xcode's output:
↳
    ld: unknown option: -target
    location_permissions-coaigneefjjdkbaiiroewrsqusfe
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'OneSignal' from project 'Pods')
```
Then I run flutter clean then again I run build command I get this error 

```
Xcode's output:
↳
    ld: unknown option: -target
    Pods-OneSignalNotificationServiceExtension-coaigneefjjdkbaiiroewrsqusfe
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.5.99. (in target 'OneSignal' from project 'Pods')

```

So how to resolve this issue of this ios build

**Comment by iapicca** [comment]
Hi @newbieflutter 
Can you please provide your `flutter doctor -v`, 
your `flutter build ios --no-codesign --verbose` 
and your `pubspec.yaml`.
Thank you

**Comment by newbieflutter** [comment]
Hi Iapica,
                Here is my flutter doctor -v

```
flutter doctor -v
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-0.0.pre at /usr/local/flutter
    • Framework revision d9653445f4 (13 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/shaisingh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • iPhone 11 Pro              • BA573E88-2BCE-42D7-8907-ADD2EB7DEB69     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • iPhone SE (2nd generation) • E4B0E457-E3DD-43BB-8F22-503DF9D77EA1     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

! Doctor found issues in 1 category.



```
Here is my pubspec.yaml. 
```

description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences:
  http:
  built_value: ^6.3.1
  built_collection: ^4.1.0
  google_maps_flutter:
  flutter_bloc: ^0.9.0
  flutter_launcher_icons: ^0.7.0
  onesignal_flutter: ^2.0.0
  intl:
  location: ^2.5.2
  geolocator:
  url_launcher:
  url_launcher_web:
  expandable: ^4.0.2
  flutter_datetime_picker:
  flutter_secure_storage:
  provider: ^4.0.2
  progress_dialog: ^1.2.1  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.3  
  built_value_generator: ^6.3.1


flutter_icons:
  image_path: "lib/assets/installerIcon.png"
  image_path_android: "lib/assets/installerIcon.png"
  image_path_ios: "lib/assets/installerIcon.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/assets/alarm.png
    - lib/assets/A2B.png
    - lib/assets/cbg.png
    - lib/assets/logo.png
    - lib/assets/loadingbg.png
    - lib/assets/loadinglogoname.png
    - lib/assets/loadingmapanimation.gif
    - lib/assets/loadinganimation.gif
    - lib/assets/loadingtitle.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: BPreplay
      fonts:
        - asset: fonts/BPreplay.otf
    - family: BPreplayBold
      fonts:
        - asset: fonts/BPreplayBold.otf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.otf
    - family: QuicksandBold
      fonts:
        - asset: fonts/Quicksand-Bold.otf
```

I have issue on this flutter build ios --no-codesign --verbose I cant capture the output is too long ? What is best way to send to a file ?
