### ISSUE TITLE
Simples app for flutter build release ios is also getting build failed

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#60065]
I have been facing problem with this command  `flutter build ios --release --verbose` for my other app. So what I did I build a basic bare minimal flutter app just the counter example. So then I build it I assign the signing and capabilities etc. Then I tried to run this command `flutter build ios --release --verbose `it also failed so meaning some thing else need to be done is it for it to be successful. 

Here is the output of the logs just the part where it shows failed.

```
Failed to build iOS app
[        ] Error output from Xcode build:
           ↳
[        ]     ** BUILD FAILED **
           
           
               The following build commands failed:
                Ld /Users/mymac/Library/Developer/Xcode/DerivedData/Runner-cnsnreurrfqzvcbaxnkjmnpjzoqh/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Binary/Runner normal
armv7
                Ld /Users/mymac/Library/Developer/Xcode/DerivedData/Runner-cnsnreurrfqzvcbaxnkjmnpjzoqh/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Binary/Runner normal
arm64
               (2 failures)
```

So what should be done to get a successful build release and also the obfuscate and to be able to upload app store.

**Comment by iapicca** [comment]
Hi @newbieflutter 
Can you please provide your `flutter doctor -v`, 
your `flutter build ios --verbose` 
and your `pubspec.yaml`.
Thank you

**Comment by newbieflutter** [comment]
Here is all the details.

1. flutter doctor -v
```

[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-0.0.pre at /usr/local/flutter
    • Framework revision d9653445f4 (2 weeks ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mymac/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

2. flutter build ios --verbose
Its very long to be pasted here so its pasted on this link

https://pastebin.com/hHqzLNKh

3. pubspec.yaml

```
name: testrelease
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
