### ISSUE TITLE
font weights are not rendered properly on iOS 13.3

### ISSUE THREAD

**Issue by tsahnar** [flutter/flutter#60477]
Hi!  when running our app in iPhoneX simulator - iOS version 13.5 everything works good.

In iPhone X  simulator with version **iOS 13.3**, all text with fontWeight 300 (and other weights which are not "normal") do not render properly - see photos attached. (you can see that letter spacing is not even) The fonts we are using is "Helvetica neue".

this is how we define the fonts in the pubspec.yml file:

```yaml
- family: Halvetica
  fonts:
    - asset: fonts/Helvetica45Light.ttf
    - asset: fonts/Helvetica25UltraLight.ttf
      weight: 100
    - asset: fonts/Helvetica35Thin.ttf
      weight: 300
    - asset: fonts/Helvetica55Roman.ttf
      weight: 500
    - asset: fonts/Helvetica65Medium.ttf
      weight: 600
    - asset: fonts/Helvetica85Heavy.ttf
      weight: 700
```

This is how the font family is set:
`var baseTextStyle = TextStyle(fontFamily: "Halvetica", color: AppColors.black);`

I have a config where I create a custom theme:
```dart
class AppTheme {
 static ThemeData of(context) {
   var theme = Theme.of(context);
   return theme.copyWith(...); // Here I override the default theme
 }
}
```

output from flutter doctor:

```console
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.4 19E266, locale en-IL)
    • Flutter version 1.17.3 at /Users/XXX/Desktop/Dev/tools/flutter
    • Framework revision b041144f83 (3 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

 
[✓] Connected device (3 available)            
    • sdk gphone x86 arm • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 8           • 1EAA0FC8-F445-4D6C-9030-E6E9BB21924B • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • iPhone x           • 8E1A08DD-905F-4BD2-9BAE-01702A4007C4 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

<img width="655" alt="iOS 13 3" src="https://user-images.githubusercontent.com/24475519/85954328-54a05400-b97f-11ea-89ad-3f20ccd46fc4.png">
<img width="301" alt="iOS 13 5" src="https://user-images.githubusercontent.com/24475519/85954331-566a1780-b97f-11ea-8f55-5f72b60651ac.png">
