### ISSUE TITLE
Flutter Analyzer crashes multiples times when running medium/large apps 

### ISSUE THREAD

**Issue by dungnv2602** [flutter/flutter#60537]
Okay, Flutter Analyzer most likely doesn't crash at all if my app scale is small. When my app scales up to medium, it begins crashing several times (5-10 times a day), every restart takes 1-2 mins. I'm basically can't do anything while it restarting. Can we make this a top priority issue? Cause it really slows down dev time, a lot?

**Comment by TahaTesser** [comment]
Hi @dungnv2602 
Can you please provide your `flutter doctor -v` your `flutter analyze --verbose` while crash, your `pubspec.yaml`
Thank you"

**Comment by dungnv2602** [comment]
flutter doctor -v

```
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.17.4 at D:\flutter
    • Framework revision 1ad9baa8b9 (13 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\dungk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by dungnv2602** [comment]
flutter analyze --verbose
[flutter_analyzer_log](https://gist.githubusercontent.com/dungnv2602/eb8ff3ae05197fe835748937db73a4d5/raw/f947d64c32cfe051eddd12ff6343f66222e37c4a/flutter_analyzer_log.md)

**Comment by dungnv2602** [comment]
pubspec.yaml
```
name: flutter_tmdb
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  tmdb_dart:
    path: ../tmdb_dart
  flutter_icons:
    path: ../flutter_icons

  # state
  provider: ^4.1.3
  flutter_bloc: ^4.0.1
  # hydrated_bloc: ^3.1.0
  flutter_stream_listener: ^1.0.0
  stream_listener: ^2.0.0
  rxdart: ^0.24.1
  dartz: ^0.9.1
  json_annotation: ^3.0.1
  freezed_annotation: ^0.11.0
  get_it: ^4.0.2

  # local persistent
  # hive: ^1.4.1+1
  # hive_flutter: ^0.3.0+2
  flutter_secure_storage: ^3.3.3

  # caching
  memoize: ^2.0.0

  # images
  flutter_svg: ^0.17.1
  # cached_network_image: ^2.0.0
  flutter_advanced_networkimage: ^0.7.0
  # flutter_blurhash: ^0.1.2

  # icons
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  material_design_icons_flutter: ^4.0.5345
  flutter_spinkit: ^4.1.2+1
  smooth_page_indicator: ^0.1.5
  flutter_gallery_assets: ^0.2.0

  # alert
  fluttertoast: ^4.0.1
  rflutter_alert: ^1.0.3

  # verification
  # email_validator: ^1.0.4

  # device info
  # path_provider: ^1.6.5
  # package_info: ^0.4.0+16

  # listener
  # flutter_keyboard_visibility: ^0.7.0
  # connectivity: ^0.4.8+2
  data_connection_checker: ^0.3.4

  # UIs
  flutter_staggered_grid_view: ^0.3.0
  drag_select_grid_view: ^0.2.0
  # direct_select_flutter: ^1.0.5

  # utils
  # flutter_page_transition: ^0.1.6
  shimmer: ^1.1.1
  # flutter_rating_bar: ^3.0.1+1
  url_launcher: ^5.4.11
  flutter_money_formatter: ^0.8.3
  animations: ^1.1.1


# dependency_overrides:
#   tmdb_dart:
#     git:
#       url: https://github.com/dungnv2602/tmdb_dart.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  bloc_test: ^5.0.0
  build_runner: ^1.10.0
  freezed: ^0.10.5
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true

  assets:
   - assets/jpgs/
   - assets/svgs/
   - assets/svgs/primary/
   - assets/svgs/surface/
   - assets/svgs/tmdb_logos_modified/
    # test_libs
   - assets/images/
   - assets/images/base/
   - assets/images/carousel/
   - assets/images/filter_menu/
   - assets/images/onboarding_concept/
    # flutter_gallery_assets
   - packages/flutter_gallery_assets/people/ali_landscape.png
   - packages/flutter_gallery_assets/monochrome/red-square-1024x1024.png
   - packages/flutter_gallery_assets/logos/flutter_white/logo.png
   - packages/flutter_gallery_assets/logos/fortnightly/fortnightly_logo.png
   - packages/flutter_gallery_assets/videos/bee.mp4
   - packages/flutter_gallery_assets/videos/butterfly.mp4
   - packages/flutter_gallery_assets/animated_images/animated_flutter_lgtm.gif
   - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
   - packages/flutter_gallery_assets/food/butternut_squash_soup.png
   - packages/flutter_gallery_assets/food/cherry_pie.png
   - packages/flutter_gallery_assets/food/chopped_beet_leaves.png
   - packages/flutter_gallery_assets/food/fruits.png
   - packages/flutter_gallery_assets/food/pesto_pasta.png
   - packages/flutter_gallery_assets/food/roasted_chicken.png
   - packages/flutter_gallery_assets/food/spanakopita.png
   - packages/flutter_gallery_assets/food/spinach_onion_salad.png
   - packages/flutter_gallery_assets/food/icons/fish.png
   - packages/flutter_gallery_assets/food/icons/healthy.png
   - packages/flutter_gallery_assets/food/icons/main.png
   - packages/flutter_gallery_assets/food/icons/meat.png
   - packages/flutter_gallery_assets/food/icons/quick.png
   - packages/flutter_gallery_assets/food/icons/spicy.png
   - packages/flutter_gallery_assets/food/icons/veggie.png
   - packages/flutter_gallery_assets/logos/pesto/logo_small.png
   - packages/flutter_gallery_assets/places/india_chennai_flower_market.png
   - packages/flutter_gallery_assets/places/india_thanjavur_market.png
   - packages/flutter_gallery_assets/places/india_tanjore_bronze_works.png
   - packages/flutter_gallery_assets/places/india_tanjore_market_merchant.png
   - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple.png
   - packages/flutter_gallery_assets/places/india_pondicherry_salt_farm.png
   - packages/flutter_gallery_assets/places/india_chennai_highway.png
   - packages/flutter_gallery_assets/places/india_chettinad_silk_maker.png
   - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple_carvings.png
   - packages/flutter_gallery_assets/places/india_chettinad_produce.png
   - packages/flutter_gallery_assets/places/india_tanjore_market_technology.png
   - packages/flutter_gallery_assets/places/india_pondicherry_beach.png
   - packages/flutter_gallery_assets/places/india_pondicherry_fisherman.png
   - packages/flutter_gallery_assets/products/backpack.png
   - packages/flutter_gallery_assets/products/belt.png
   - packages/flutter_gallery_assets/products/cup.png
   - packages/flutter_gallery_assets/products/deskset.png
   - packages/flutter_gallery_assets/products/dress.png
   - packages/flutter_gallery_assets/products/earrings.png
   - packages/flutter_gallery_assets/products/flatwear.png
   - packages/flutter_gallery_assets/products/hat.png
   - packages/flutter_gallery_assets/products/jacket.png
   - packages/flutter_gallery_assets/products/jumper.png
   - packages/flutter_gallery_assets/products/kitchen_quattro.png
   - packages/flutter_gallery_assets/products/napkins.png
   - packages/flutter_gallery_assets/products/planters.png
   - packages/flutter_gallery_assets/products/platter.png
   - packages/flutter_gallery_assets/products/scarf.png
   - packages/flutter_gallery_assets/products/shirt.png
   - packages/flutter_gallery_assets/products/sunnies.png
   - packages/flutter_gallery_assets/products/sweater.png
   - packages/flutter_gallery_assets/products/sweats.png
   - packages/flutter_gallery_assets/products/table.png
   - packages/flutter_gallery_assets/products/teaset.png
   - packages/flutter_gallery_assets/products/top.png
   - packages/flutter_gallery_assets/people/ali.png
   - packages/flutter_gallery_assets/people/square/ali.png
   - packages/flutter_gallery_assets/people/square/peter.png
   - packages/flutter_gallery_assets/people/square/sandra.png
   - packages/flutter_gallery_assets/people/square/stella.png
   - packages/flutter_gallery_assets/people/square/trevor.png

  fonts:
    - family:  TypiconsStars
      fonts:
       - asset: assets/fonts/TypiconsStars.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
```

**Comment by dungnv2602** [comment]
> Hi @dungnv2602
> Can you please provide your `flutter doctor -v` your `flutter analyze --verbose` while crash, your `pubspec.yaml`
> Thank you"

Here you go, analyzer log is too long that I have to publish it as a gist, sorry for the inconvenience.

**Comment by TahaTesser** [comment]
Hi @dungnv2602 
Looking at your logs, it doesn't that long (ran in 24.1s) for 276 issues to be found, `flutter analyze` would take time to go through that many issues to be found 

```
[   +4 ms] "flutter analyze" took 13,884ms.
276 issues found. (ran in 24.1s)
```

**Comment by dungnv2602** [comment]
> Hi @dungnv2602
> Looking at your logs, I notice you have lots 276, which be causing this crash, do you notice same with less or no issues at all?
> 
> ```
> [   +4 ms] "flutter analyze" took 13,884ms.
> 276 issues found. (ran in 24.1s)
> ```

I will post a new log when it crashes, but I suppose it is pretty much the same since they are just warning issues, my app runs perfectly fine.

**Comment by dungnv2602** [comment]
> Hi @dungnv2602
> Looking at your logs, I notice you have lots 276, which be causing this crash, do you notice same with less or no issues at all?
> 
> ```
> [   +4 ms] "flutter analyze" took 13,884ms.
> 276 issues found. (ran in 24.1s)
> ```
[analyzer_log_07012020](https://gist.github.com/dungnv2602/eb8ff3ae05197fe835748937db73a4d5)
I updated the log for today's crash, I took it while it restarting so you can see that it took very long to generate log.

**Comment by dungnv2602** [comment]
I've reduced the number of issues by half [https://gist.github.com/dungnv2602/be39eb13461312495a811de443f1c342](flutter_analyzer_07302020), 
Most of the issues come from [https://github.com/rrousselGit/freezed](freezed), which the code does satisfy this lint [https://dart-lang.github.io/linter/lints/avoid_equals_and_hash_code_on_mutable_classes.html](avoid_equals_and_hash_code_on_mutable_classes).

Lint Rules I use for my project:
```
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
    # Ignore analyzer hints for updating pubspecs when using Future or
    # Stream and not importing dart:async
    # Please see https://github.com/flutter/flutter/pull/24528 for details.
    sdk_version_async_exported_from_core: ignore
  exclude:
    - "bin/cache/**"
    # the following two are relative to the stocks example and the flutter package respectively
    # see https://github.com/dart-lang/sdk/issues/28463
    - "lib/i18n/messages_*.dart"
    - "lib/src/http/**"
    # ignore vscode .history files
    - .history/**
    - test/_data/**
    - test/mock_packages/**
    - test/rules/**

linter:
  rules:
    # these rules are documented on and in the same order as
    # the Dart Lint rules page to make maintenance easier
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    - always_declare_return_types
    # - always_put_control_body_on_new_line # violates Effective Dart "DO format your code using dartfmt". See note about Flutter SDK style below
    # - always_put_required_named_parameters_first # does not allow for other logical orderings of parameters, such as matching the class field order or alphabetical. We prefer having parameters in the same order as fields https://github.com/flutter/flutter/issues/10219
    - always_require_non_null_named_parameters
    # - always_specify_types # violates Effective Dart "AVOID type annotating initialized local variables" and others. See note about Flutter SDK style below
    - annotate_overrides
    # - avoid_annotating_with_dynamic # violates Effective Dart "PREFER annotating with dynamic instead of letting inference fail". conflicts with always_specify_types
    # - avoid_as # does not reflect common usage. See note about Flutter SDK style below
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses # is too strict, catching anything is useful and common even if not always the most correct thing to do.
    - avoid_catching_errors # is too strict, the distinction between Error and Exception is followed closely in the SDK but is impractical to follow everywhere.
    - avoid_classes_with_only_static_members # is too strict, Effective Dart explicitly calls out some cases (constants, enum-like types) where it makes sense to violate this lint.
    # - avoid_double_and_int_checks # only useful when targeting JS runtime
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    # - avoid_js_rounded_ints # only useful when targeting JS runtime
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    # - avoid_private_typedef_functions # we prefer having typedef (discussion in https://github.com/flutter/flutter/pull/16356)
    # - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    # - avoid_returning_null # https://dart-lang.github.io/linter/lints/avoid_returning_null.html. there are plenty of valid reasons to return null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    # - avoid_returning_this # https://dart-lang.github.io/linter/lints/avoid_returning_this.html. there are plenty of valid reasons to return this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io # gives wrong advice if the underlying filesystem has unusual properties, for example a network mount.
    - avoid_types_as_parameter_names
    # - avoid_types_on_closure_parameters # conflicts with always_specify_types
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_types
    - camel_case_extensions
    - cancel_subscriptions
    # - cascade_invocations
    # - close_sinks # not reliable enough https://github.com/dart-lang/linter/issues/268
    # - comment_references # blocked on https://github.com/flutter/flutter/issues/20765, https://github.com/dart-lang/sdk/issues/36974
    # - constant_identifier_names # needs an opt-out https://github.com/dart-lang/linter/issues/204
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    # - diagnostic_describe_all_properties # not yet tested
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    # - invariant_booleans # experimental, too many false positives: https://github.com/dart-lang/linter/issues/811
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - library_names
    - library_prefixes
    # - lines_longer_than_80_chars # avoid
    - list_remove_unrelated_type
    # - literal_only_boolean_expressions # too many false positives: https://github.com/dart-lang/sdk/issues/34181
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    # - no_logic_in_create_state # not yet tested
    - non_constant_identifier_names
    - null_closures
    # - omit_local_variable_types # opposite of always_specify_types
    - one_member_abstracts
    # - only_throw_errors # https://github.com/flutter/flutter/issues/5792
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    # - prefer_asserts_with_message # not yet tested
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    # - prefer_double_quotes # opposite of prefer_single_quotes
    - prefer_equal_for_default_values
    # - prefer_expression_function_bodies # conflicts with https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#consider-using--for-short-functions-and-methods
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    # - prefer_if_elements_to_conditional_expressions # prefer this
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    # - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin # https://github.com/dart-lang/language/issues/32
    # - prefer_null_aware_operators # disable until NNBD, see https://github.com/flutter/flutter/pull/32711#issuecomment-492930932
    # - prefer_relative_imports # conflict with avoid_relative_lib_imports
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    # - public_member_api_docs # enabled on a case-by-case basis; see e.g. packages/analysis_options.yaml
    - recursive_getters
    - slash_for_doc_comments
    # - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    # - type_annotate_public_apis # subset of always_specify_types
    - type_init_formals
    # - unawaited_futures # too many false positives
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    # - unnecessary_final # conflicts with prefer_final_locals
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    # - unsafe_html # not yet tested
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    # - use_setters_to_change_properties # too strict
    # - use_string_buffers # has false positives: https://github.com/dart-lang/sdk/issues/34182
    - use_to_and_as_if_applicable # has false positives, so we prefer to catch this by code-review
    - valid_regexps
    - void_checks
```
