### ISSUE TITLE
Xcode 11.5 archive build failed flutter

### ISSUE THREAD

**Issue by IliaKhuzhakhmetovRoonyx** [flutter/flutter#60599]
I try to take these steps: "Product" -> "Archive" to unload the application to testers, but when these steps are performed, this error is constantly displayed:

    Multiple commands produce '/Users/user/Library/Developer/Xcode/DerivedData/Runner-dpjgfafimzpddicamlmtfyiidicx/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework':
    1) Target 'GoogleUtilities-00567490' has create directory command with output '/Users/user/Library/Developer/Xcode/DerivedData/Runner-dpjgfafimzpddicamlmtfyiidicx/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
    2) Target 'GoogleUtilities-Environment-Logger-UserDefaults' has create directory command with output '/Users/user/Library/Developer/Xcode/DerivedData/Runner-dpjgfafimzpddicamlmtfyiidicx/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'

**Flutter doctor:** 
```

    [✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.4 19E287, locale ru-RU)
        • Flutter version 1.17.4 at /Users/user/dev/flutter
        • Framework revision 1ad9baa8b9 (13 days ago), 2020-06-17 14:41:16 -0700
        • Engine revision ee76268252
        • Dart version 2.8.4
    
     
    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
        • Android SDK at /Users/user/Library/Android/sdk
        • Platform android-29, build-tools 29.0.3
        • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    
    [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Xcode 11.5, Build version 11E608c
        • CocoaPods version 1.9.1
    
    [✓] Android Studio (version 4.0)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin version 46.0.1
        • Dart plugin version 192.8052
        • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    
    [✓] VS Code (version 1.46.1)
        • VS Code at /Users/user/Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.12.0
    
    [✓] Connected device (1 available)
        • iPhone (Илья) • 6cd3a4fb82220c402eee2444a3db70abb14b53ab • ios • iOS 13.5.1
    
```
I also tried to do the actions that were described in other Issue, but nothing helped, the error was still there

I tried to set in the settings of the build Use legacy system, it did not help :(

**Comment by VladyslavBondarenko** [comment]
Hi @IliaKhuzhakhmetovRoonyx 
does it happen with a new project as well?
could you provide screenshot of your Runner configs?

**Comment by IliaKhuzhakhmetovRoonyx** [comment]
@VladyslavBondarenko 
No, with new projects its all okay

Did you mean Release.xconfig? Or something else? (About configs)

**Comment by VladyslavBondarenko** [comment]
@IliaKhuzhakhmetovRoonyx 
from xcode
![image](https://user-images.githubusercontent.com/17024977/86141955-52fb9b00-bafb-11ea-97fe-bb57b52df493.png)

**Comment by jmagman** [comment]
@IliaKhuzhakhmetovRoonyx  Can we get your pubspec.yaml?  Looks like plugins are trying to copy `GoogleUtilities.framework` twice.

**Comment by IliaKhuzhakhmetovRoonyx** [comment]
@jmagman 
**pubspec.yaml:**
```
name: pj
description: Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.3+11

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:

  cloud_firestore: ^0.13.4+1
  flutter:
    sdk: flutter
  http: ^0.12.0+2  
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.0
  google_sign_in: ^4.4.1
  flutter_facebook_login: ^3.0.0
  #purchases_flutter:
    #git: https://github.com/LaraDP/purchases-flutter.git
  in_app_purchase: ^0.3.4+1
  url_launcher: ^5.4.2
  firebase_ml_vision: ^0.9.3+8
  permission_handler: ^3.2.2
  image_picker: ^0.6.1+4
  firebase_storage: ^3.1.5
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.2
  share: ^0.6.3+6
  package_info: ^0.4.0+17
  # A comprehensive, cross-platform path manipulation library for Dart.
  path: ^1.6.2
  nima: ^1.0.5
  # A Flutter plugin for finding commonly used locations on the filesystem.
  path_provider: ^1.3.0
  # downloads_path_provider: ^0.1.0
  # RxDart is a reactive functional programming library for Google Dart, based on ReactiveX.
  rxdart: ^0.21.0
  video_player: ^0.10.2+1
  camera: ^0.5.6+1
  flutter_downloader: ^1.2.2
  firebase_crashlytics: ^0.1.3+2
  # A Flutter plugin to store data in secure storage.
  flutter_secure_storage: ^3.2.1+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # tfLite - https://pub.dev/packages/tflite
  tflite: ^1.0.5
  # for advanced work with images - https://pub.dev/packages/image
  image: ^2.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter                                                                                                                                            


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - .config
   - assets/images/
   - assets/icons/
   - assets/flare/New File 9.nma.bytes
   - assets/tflite/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoe-UI.ttf
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura-Medium-Italic-font.ttf    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
