### ISSUE TITLE
Listview.builder inside ExpansionTile throws exception: type 'bool' is not a subtype of type 'double' in type cast

### ISSUE THREAD

**Issue by mostafa2142** [flutter/flutter#60676]
when i have listview.builder inside ExpnasionTile children it cause error 

this is my code : 
```flutter
ListView.builder(
                              itemCount: snap.data['result'].length,
                              itemBuilder: (context1, pos1) {
                                return ExpansionTile(
                                  children: <Widget>[
                                    ListView.builder(
                                        itemCount:snap.data['result'][pos1]['branches'].length,
                                        itemBuilder: (context2,pos2){
                                          return ExpansionTile(
                                            key: PageStorageKey(snap.data['result'][pos1]['branches'][pos2]['branch_name']),
                                            title:snap.data['result'][pos1]['branches'][pos2]['branch_name'] ,
                                          );
                                        })
                                  ],
                                  key: PageStorageKey(snap.data['result'][pos1]['cross_section_name']),
                                  title: Text(
                                    snap.data['result'][pos1]['cross_section_name'],
                                    style: TextStyle(fontSize: Components.getTitleSize(),
                                    ),
                                  ),
                                );
                              }),
```

this is the error i get

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following _CastError was thrown building ListView(scrollDirection: vertical, primary: using primary controller, AlwaysScrollableScrollPhysics, dependencies: [PrimaryScrollController, MediaQuery]):
type 'bool' is not a subtype of type 'double' in type cast

The relevant error-causing widget was: 
  ListView file:///D:/AndroidStudioProjects/ebag/lib/tabBars/tabBarCaregoryScreen/handouts.dart:114:46
When the exception was thrown, this was the stack: 
#0      ScrollPosition.restoreScrollOffset (package:flutter/src/widgets/scroll_position.dart:382:102)
#1      new ScrollPosition (package:flutter/src/widgets/scroll_position.dart:108:7)
#2      new ScrollPositionWithSingleContext (package:flutter/src/widgets/scroll_position_with_single_context.dart:57:8)
#3      ScrollableState._updatePosition (package:flutter/src/widgets/scrollable.dart:374:10)
#4      ScrollableState.didChangeDependencies (package:flutter/src/widgets/scrollable.dart:382:5)

```

flutter doctor :

```
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.17.2 at D:\flutter_sdk\flutter_windows_v1.7.8+hotfix.4-stable\flutter
    • Framework revision 5f21edf8b6 (5 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\Sdk\tools_r25.2.5-windows
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\Sdk\tools_r25.2.5-windows
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

• No issues found!
```

Pubspec.yaml : 

```
name: ebag
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.3+1
  connectivity: ^0.4.8+6
  http: ^0.12.1
  shared_preferences: ^0.5.7+1
  cached_network_image: ^2.2.0+1
  flutter_image: ^3.0.0
  expandable: ^4.1.3
  flutter_rating_bar: ^3.0.1+1
  #  incrementally_loading_listview: ^0.3.0
  shimmer: ^1.1.1
  #  rflutter_alert: ^1.0.3
  pull_to_refresh: ^1.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #   - lib/assets/Intro/arrowRight.svg
    - lib/assets/Intro/pagination_1.svg
    - lib/assets/Intro/pagination_2.svg
    - lib/assets/Intro/pagination_3.svg
    - lib/assets/Intro/pagination_4.svg
    #   - lib/assets/Intro/ButtonRectangle.svg
    - lib/assets/Intro/backGroundIntro_1.svg
    - lib/assets/Intro/backGroundIntro_2.svg
    - lib/assets/Intro/backGroundIntro_3.svg
    - lib/assets/Intro/backGroundIntro_4.svg
    - lib/assets/login/backGroundTest.png
    - lib/assets/login/systemLogin.svg
    - lib/assets/login/googleLogin.svg
    - lib/assets/login/rectAngle.svg
    - lib/assets/bottomNavigation/addHandoutItem.svg
    - lib/assets/bottomNavigation/categoryItem.svg
    - lib/assets/bottomNavigation/homeItem.svg
    - lib/assets/bottomNavigation/profileItem.svg
    - lib/assets/bottomNavigation/shelfItem.svg
    - lib/assets/actionbar/cart.png
    - lib/assets/actionbar/notification.png
    - lib/assets/filterBtns/books.png
    - lib/assets/filterBtns/filter.png
    - lib/assets/filterBtns/handout.png
    - lib/assets/filterBtns/nemoneSoal.png
    - lib/assets/openItemMainAssets/bookmark.png
    - lib/assets/openItemMainAssets/cart.png
    - lib/assets/openItemMainAssets/prvScreen.png
    - lib/assets/openItemMainAssets/unBookmark.png
    - lib/assets/test.png
    - lib/assets/vip.png
    - lib/assets/comments/like.png
    - lib/assets/comments/dislike.png
    - lib/assets/profile/editProfile.png
    - lib/assets/profile/menu.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

the error says type 'bool' is not a subtype of type 'double' in type cast
but i dont have bool or even double !
