### ISSUE TITLE
Flutter run takes very long time  with version 1.17.4

### ISSUE THREAD

**Issue by surpriso1997** [flutter/flutter#60752]
This problem didn't exist before flutter upgrade. I know that flutter run, on first time is supposed to take long time. But with this version of flutter it takes long time (10-15  minutes)  every single flutter run or debug. It feels as if flutter clean is happening every single time in flutter run. This is happening even if I have not changed single line fo code in the project.
While viewing message in vscode , "Running Gradle task assembleDebug" seems to take the longest time during flutter run.
 

These are my dependencies in pubspec.yaml:
```

version: 2.3.4+64

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.2.0
  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  sqflite: any
  connectivity: ^0.4.4
  shared_preferences: ^0.5.7+3
  dio: any
  get_it: ^4.0.2
  cached_network_image: ^2.3.0-beta.1+1

  app_settings: ^4.0.1+1
  firebase_crashlytics: ^0.1.0+3ub
  

  firebase_analytics:
  firebase_messaging: ^6.0.16
  firebase_dynamic_links: ^0.5.0+11
  firebase_remote_config: ^0.3.0+3
  google_sign_in: ^4.0.7
  flutter_facebook_login: ^3.0.0
  firebase_in_app_messaging: ^0.1.2

  flutter_local_notifications: ^1.4.4
  intl: ^0.16.0
  url_launcher: ^5.1.4
  in_app_purchase: ^0.3.4

  image_picker: ^0.6.1+4
  flutter_html: ^0.11.1
  fluttertoast: ^4.0.1

  flutter_webview_plugin: ^0.3.9+1
  flutter_email_sender: ^3.0.1
  path_provider:
  package_info:

  sleek_circular_slider:

  responsive_flutter: ^0.0.4
  carousel_slider: ^2.0.0
  jiffy: ^3.0.1
  lazy_load_scrollview: ^1.1.0
  device_preview:
  flutter_spinkit:
  logger:
  flutter_svg: ^0.17.4
  shimmer:
  flutter_screenutil:
  rxdart: ^0.24.0
  flutter_bloc: ^4.0.0
  responsive_grid: ^1.1.1
  modal_progress_hud: ^0.1.3
  country_pickers: ^1.3.0
  pull_to_refresh: ^1.5.8
  device_info: ^0.4.2
  flutter_share: ^1.0.2+1
  google_api_availability: ^2.0.4
  sign_in_with_apple: ^2.5.0
  firebase_admob: ^0.9.3+2
  flutter_native_admob: ^2.1.0
 # assets_audio_player: ^2.0.5+2S
  flutter_inapp_purchase: ^2.2.0

  assets_audio_player:
    git:
      url: https://github.com/Timus23/Flutter-AssetsAudioPlayer.git
      ref: dev

  flutter_downloader:
    path: ./gv-flutter-downloader

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic

    - family: GoodVibesIcons
      fonts:
        - asset: assets/fonts/GoodVibesIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: BackIcon
      fonts:
        - asset: assets/icons/BackIcon.ttf
    - family: NavMenu
      fonts:
        - asset: assets/icons/NavMenu.ttf


```

flutter doctor:

```
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.17.4 at E:\Sdks\flutter
    • Framework revision 1ad9baa8b9 (2 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\acer\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\acer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (1 available)
```
