### ISSUE TITLE
iOS build fails: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by samycodes** [flutter/flutter#60851]
The app works fine on Android but does not run on iOS. I have tried to create another repository and build but that still does not work. I have also tried to change my flutter channel to master, but still having the error.

Here are the packages, I use:

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation:
  audioplayers: ^0.15.1
  wakelock:
  shared_preferences:
  vibration: ^1.4.0
  flutter_local_notifications: ^1.1.5+1
  flutter_icons: ^1.0.0+1
  flutter_launcher_icons: ^0.7.4
  url_launcher: ^5.4.2
  get: ^1.15.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

```

When I run app, I get these warnings and errors.
```
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
 
Running pod install...                                              6.4s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           53.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/apple/desktop/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.15.1/darwin/Classes/AudioplayersPlugin.m:88:37:
    warning: incompatible pointer types sending 'FlutterEngine *' to parameter of type 'NSObject<FlutterBinaryMessenger> * _Nonnull'
    [-Wincompatible-pointer-types]
                        binaryMessenger:_headlessEngine];
                                        ^~~~~~~~~~~~~~~
    In module 'Flutter' imported from
    /Users/apple/desktop/dev/flutter/.pub-cache/hosted/pub.dartlang.org/audioplayers-0.15.1/darwin/Classes/AudioplayersPlugin.h:2:
    /Users/apple/Desktop/dev/upwork/body_alarm/ios/Flutter/Flutter.framework/Headers/FlutterChannels.h:178:74: note: passing argument
    to parameter 'messenger' here
                          binaryMessenger:(NSObject<FlutterBinaryMessenger>*)messenger;
                                                                             ^
    1 warning generated.
    /Users/apple/desktop/dev/flutter/.pub-cache/hosted/pub.dartlang.org/vibration-1.4.0/ios/Classes/VibrationPlugin.m:6:4: warning:
    'SwiftVibrationPlugin' is only available on iOS 13.0 or newer [-Wunguarded-availability-new]
      [SwiftVibrationPlugin registerWithRegistrar:registrar];
       ^~~~~~~~~~~~~~~~~~~~
    In file included from
    /Users/apple/desktop/dev/flutter/.pub-cache/hosted/pub.dartlang.org/vibration-1.4.0/ios/Classes/VibrationPlugin.m:2:
    /Users/apple/Desktop/dev/upwork/body_alarm/build/ios/Debug-iphonesimulator/vibration/vibration.framework/Headers/vibration-Swift.h
    :213:12: note: 'SwiftVibrationPlugin' has been marked as being introduced in iOS 13.0 here, but the deployment target is iOS 8.0.0
    @interface SwiftVibrationPlugin : NSObject <FlutterPlugin>
               ^
    /Users/apple/desktop/dev/flutter/.pub-cache/hosted/pub.dartlang.org/vibration-1.4.0/ios/Classes/VibrationPlugin.m:6:4: note:
    enclose 'SwiftVibrationPlugin' in an @available check to silence this warning
      [SwiftVibrationPlugin registerWithRegistrar:registrar];
       ^~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    ../../../../desktop/dev/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:279:8: Error: The
    method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
      void install(OverlayEntry insertionPoint) {
           ^
    ../../../../desktop/dev/flutter/packages/flutter/lib/src/widgets/routes.dart:46:8: Context: This is the overridden method
    ('install').
      void install() {
           ^
    ../../../../desktop/dev/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/routes/default_route.dart:242:9: Error: No
    named parameter with the name 'animation'.
            animation: animation,
            ^^^^^^^^^
    ../../../../desktop/dev/flutter/packages/flutter/lib/src/cupertino/route.dart:542:3: Context: Found this candidate, but the
    arguments don't match.
      CupertinoFullscreenDialogTransition({
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../../desktop/dev/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:289:18: Error: Too
    many positional arguments: 0 allowed, but 1 found.
    Try removing the extra positional arguments.
        super.install(insertionPoint);
                     ^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone SE (2nd generation).
```

Flutter doctor result.
```
[✓] Flutter: is fully installed. (Channel master, 1.20.0-3.0.pre.126, on Mac OS
    X 10.15.4 19E287, locale en-PK)
[✓] Android toolchain - develop for Android devices: is fully installed.
    (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.4.1)
[✓] Android Studio: is fully installed. (version 3.6)
[✓] VS Code: is fully installed. (version 1.46.1)
[✓] Connected device: is fully installed. (1 available)
```

Please help me to resolve this issue. I shall be very thankful to you.

Best regards,
