### ISSUE TITLE
Problem related to grcpp?

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#61131]
## Steps to Reproduce

1. Run `flutter create any_thing`.
2. Update the `pubspec.yaml` with the provided things below.
3. Run app with `flutter run`

**Expected results:** 
The app runs as a regular app connected to firebase. Keep in mind that the app runs on android normally

**Actual results:** 

<details>
  <summary>Logs</summary>

Was too long to put here
```
https://pastebin.com/sxQrNkSC
```

Short Version of Flutter run: 

```bash
yazeed@Yazeeds-iMac beast % flutter run -d 35c01b97dacc7ab0aa241e20fb2593d9ce6c920f            
Launching lib/main.dart on Yazeed AlKhalaf in debug mode...
 
Automatically signing iOS for device deployment using specified development team in Xcode project: M5NN92249U
Running Xcode build...                                                  
                                                   
Xcode build done.                                           15.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/yazeed/Desktop/beast/ios/Pods/gRPC-C++/src/cpp/server/channel_argument_option.cc:19:10: fatal error:
    'grpcpp/impl/channel_argument_option.h' file not found
    #include <grpcpp/impl/channel_argument_option.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yazeed/Desktop/beast/ios/Pods/gRPC-C++/src/cpp/server/channel_argument_option.cc:19:10: note: did not find header
    'impl/channel_argument_option.h' in framework 'grpcpp' (loaded from
    '/Users/yazeed/Desktop/beast/build/ios/Debug-iphoneos/gRPC-C++')
    1 error generated.
    /Users/yazeed/Desktop/beast/ios/Pods/gRPC-C++/src/cpp/server/async_generic_service.cc:19:10: fatal error:
    'grpcpp/generic/async_generic_service.h' file not found
    #include <grpcpp/generic/async_generic_service.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yazeed/Desktop/beast/ios/Pods/gRPC-C++/src/cpp/server/async_generic_service.cc:19:10: note: did not find header
    'generic/async_generic_service.h' in framework 'grpcpp' (loaded from
    '/Users/yazeed/Desktop/beast/build/ios/Debug-iphoneos/gRPC-C++')
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on Yazeed AlKhalaf.
```

```bash
yazeed@Yazeeds-iMac beast % flutter analyze
Analyzing beast...                                                      

   info • Unused import: 'package:flutter/cupertino.dart' • lib/src/app/generated/router/router.gr.dart:8:8 • unused_import
   info • 'pickImage' is deprecated and shouldn't be used. Use imagePicker.getImage() method instead. •
          lib/src/app/utils/utils.dart:25:44 • deprecated_member_use
   info • 'pickVideo' is deprecated and shouldn't be used. Use imagePicker.getVideo() method instead. •
          lib/src/app/utils/utils.dart:37:44 • deprecated_member_use
   info • The value of the field 'safeBlockHorizontal' isn't used • lib/src/ui/global/ui_helpers.dart:12:17 • unused_field
   info • The value of the field 'safeBlockVertical' isn't used • lib/src/ui/global/ui_helpers.dart:13:17 • unused_field
   info • This function has a return type of 'Text', but doesn't end with a return statement •
          lib/src/ui/views/chats/chats_view.dart:79:11 • missing_return
   info • Unused import: 'package:beast/main.dart' • lib/src/ui/views/sign_up/signup_view.dart:1:8 • unused_import
   info • Unused import: 'package:beast/src/app/generated/router/router.gr.dart' •
          lib/src/ui/views/user_details/user_details_view.dart:2:8 • unused_import
   info • Unused import: 'package:beast/src/app/constants/config.dart' •
          lib/src/ui/views/user_details/user_details_view_model.dart:1:8 • unused_import
   info • Unused import: 'package:beast/src/ui/global/ui_helpers.dart' •
          lib/src/ui/views/user_details/user_details_view_model.dart:5:8 • unused_import
   info • Unused import: 'package:beast/src/ui/widgets/busy_button.dart' •
          lib/src/ui/views/user_details/user_details_view_model.dart:6:8 • unused_import
   info • Unused import: 'package:beast/src/ui/widgets/custom_app_bar.dart' •
          lib/src/ui/views/user_details/user_details_view_model.dart:7:8 • unused_import
   info • Unused import: 'package:beast/src/ui/widgets/text_link.dart' •
          lib/src/ui/views/user_details/user_details_view_model.dart:8:8 • unused_import
   info • Unused import: 'package:beast/src/ui/widgets/user_circle.dart' •
          lib/src/ui/views/user_details/user_details_view_model.dart:9:8 • unused_import

14 issues found. (ran in 10.0s)
```

```bash
yazeed@Yazeeds-iMac fff % flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale
    en-SA)
    • Flutter version 1.17.5 at /Users/yazeed/development/flutter
    • Framework revision 8af6b2f038 (8 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0)
    • Android SDK at /Users/yazeed/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (2 available)
    • Yazeed AlKhalaf   • 35c01b97dacc7ab0aa241e20fb2593d9ce6c920f • ios •
      iOS 12.4.6
    • iPhone 11 Pro Max • 3A5436D6-E754-4C04-A47D-925CB088FFC3     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

</details>

My problem is that i want to run my app on iOS but this error keeps on popping up!

```bash
yazeed@Yazeeds-iMac beast % flutter run -d 35c01b97dacc7ab0aa241e20fb2593d9ce6c920f
Launching lib/main.dart on Yazeed AlKhalaf in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: M5NN92249U
Running pod install...                                             13.8s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           146.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/yazeed/Desktop/beast/ios/Pods/gRPC-C++/src/cpp/util/string_ref.cc:19:10: fatal error: 'grpcpp/support/string_ref.h'
    file not found
    #include <grpcpp/support/string_ref.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yazeed/Desktop/beast/ios/Pods/gRPC-C++/src/cpp/util/string_ref.cc:19:10: note: did not find header
    'support/string_ref.h' in framework 'grpcpp' (loaded from '/Users/yazeed/Desktop/beast/build/ios/Debug-iphoneos/gRPC-C++')
    1 error generated.
    /Users/yazeed/Desktop/beast/ios/Pods/gRPC-C++/src/cpp/common/version_cc.cc:22:10: fatal error: 'grpcpp/grpcpp.h' file not
    found
    #include <grpcpp/grpcpp.h>
             ^~~~~~~~~~~~~~~~~
    /Users/yazeed/Desktop/beast/ios/Pods/gRPC-C++/src/cpp/common/version_cc.cc:22:10: note: did not find header 'grpcpp.h' in
    framework 'grpcpp' (loaded from '/Users/yazeed/Desktop/beast/build/ios/Debug-iphoneos/gRPC-C++')
    1 error generated.
    /Users/yazeed/Desktop/beast/ios/Pods/gRPC-C++/src/cpp/util/status.cc:19:10: fatal error: 'grpcpp/support/status.h' file not
    found
    #include <grpcpp/support/status.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yazeed/Desktop/beast/ios/Pods/gRPC-C++/src/cpp/util/status.cc:19:10: note: did not find header 'support/status.h' in
    framework 'grpcpp' (loaded from '/Users/yazeed/Desktop/beast/build/ios/Debug-iphoneos/gRPC-C++')
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on Yazeed AlKhalaf.
```

- pubpsec.yaml

```yaml
name: beast
description: A chat app build with Flutter + Firebase.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Cupertino Icons
  cupertino_icons: ^0.1.3

  # Stacked
  stacked: ^1.7.1+1
  # third-party services
  stacked_services: ^0.4.4+3
  # navigation
  auto_route: ^0.6.1
  # inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  # Flutter Spinkit
  flutter_spinkit: ^4.1.2+1
  # Logger
  logger: ^0.9.1

  # cached network image
  cached_network_image: ^2.2.0+1
  # flutter video compress
  # flutter_video_compress: ^0.3.7+8
  video_compress: ^2.0.0
  # video player
  video_player: ^0.10.11+2
  # image picker
  image_picker: ^0.6.7+4
  # image cropper
  image_cropper: ^1.2.3

  # shimmer
  shimmer: ^1.1.1
  # gradient appbar
  gradient_app_bar: ^0.1.3

  # cloud firestore
  cloud_firestore: ^0.13.7
  # firebase auth
  firebase_auth: ^0.16.1
  # firebase storage
  firebase_storage: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^1.10.0
  auto_route_generator: ^0.6.0
  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/title.png
    - assets/images/icon_large.png

```

I have tried reading all readme of the packages.  i can't figure it out. I hope you can help me guys
