### ISSUE TITLE
Wrap widget doesn't layout correctly in certain cases, like Column does

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#61204]
When using the technique listed here, under the heading "Expanding content to fit the viewport": https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html,

a Column widget works very well, but a Wrap does not. Is there something maybe missing from the way the Wrap widget lays itself out that could be improved to act more like a Column?

Essentially, the following sample shows the problem. If you run this app on a device, it should start out with a view that can be scrolled so all children are accessible. Hitting the button at the top to switch to using a Wrap will cause an Overflow.
Switching back to a Column, you can scroll again, and if you change the number in the text field to a smaller number, you can get the Wrap widget to work well as long as no Overflow happens.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: WrapHomePage(),
    );
  }
}

class WrapHomePage extends StatefulWidget {
  const WrapHomePage();

  @override
  _WrapHomePageState createState()  => _WrapHomePageState();
}

class _WrapHomePageState extends State<WrapHomePage> {

  bool _useColumn = true;
  int _numTexts = 8;

  List<Widget> _buildTexts(int numTexts) {
    List<Widget> texts = [];
    for (int i=0; i<numTexts; i++) {
      texts.add(Padding(
        padding: const EdgeInsets.only(top: 24.0),
        child: Text(
            "Hello, this is some long text. It can go on and on. This test is to make sure we can scroll"),
      ));
    }
    return texts;
  }

  @override
  Widget build(BuildContext context) {

    final texts = _buildTexts(_numTexts);

    return Scaffold(
        body: SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: LayoutBuilder(
              builder: (context, constraints) {
                return SingleChildScrollView(
                    child: ConstrainedBox(
                      constraints: BoxConstraints(
                        minHeight: constraints.maxHeight,
                      ),
                      child: IntrinsicHeight(
                        child: DefaultTextStyle(
                          style: TextStyle(fontSize: 20, color: Colors.black),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.start,
                            mainAxisSize: MainAxisSize.max,
                            children: [
                              FlatButton(
                                  onPressed: () {
                                    setState(() {
                                      _useColumn = !_useColumn;
                                    });
                                  },
                                  child: Text(_useColumn ? "Switch to Wrap!" : "Switch to Column!", style: TextStyle(fontSize: 20, color: Colors.black))
                              ),
                              if (_useColumn)
                                Column(
                                  key: ValueKey("header"),
                                  children: texts,
                                )
                              else
                                Wrap(
                                  key: ValueKey("header"),
                                  children: texts,
                                ),
                              Expanded(
                                  key: ValueKey("middle"),
                                  child: Container(
                                    color: Colors.red,
                                    child: Center(
                                        child: TextField(
                                          onChanged: (value) {
                                            setState(() {
                                              _numTexts = int.parse(value);
                                            });
                                          },
                                        )
                                    ),
                                  )
                              ),
                              Padding(
                                key: ValueKey("footer"),
                                padding: const EdgeInsets.only(top: 24.0),
                                child: Column(
                                  children: [
                                    Text("Final message")
                                  ],
                                ),
                              )
                            ],
                          ),
                        ),
                      ),
                    )
                );
              }
            ),
          )
        )
    );
  }
}
```

**Comment by dannyvalentesonos** [comment]
The flutter_markdown plugin works by creating Wrap widgets, and thus cannot be used in this type of layout unfortunately. Also, what is strange is if the code is changed to create multiple Wrap widgets inside of a Column, then it causes other issues, such as sometimes not generating an Overflow warning, but instead causes the Expanded child of the outer column to not render.

**Comment by iapicca** [comment]
Hi @dannyvalentesonos 
you may want to with the change below

```dart
Wrap(
  direction: Axis.vertical, /// <= THIS
  key: ValueKey("header"),
  children: texts,
),
```

please let me know if it fixes the issue
thank you

**Comment by dannyvalentesonos** [comment]
Thanks @iapicca . It does fix the overflow, but it causes the text to get truncated on the horizontal axis, and it prevents a Wrap from being used in the intended fashion for the Markdown plugin. The intent is to place all pieces next to each other horizontally and then flow downward as needed.

So this unfortunately does not solve the problem.
Thanks.

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (3 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • SM M305F (mobile)      • 32003c30dc19668f                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.5.1
    • iPhone 11 (mobile)     • C56E212F-BE8E-4766-8610-12CFADC797F0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.5 19F101
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 83.0.4103.116

• No issues found!

```

</details>

**Comment by Piinks** [comment]
Hi @dannyvalentesonos can you describe the expected behavior? I am not sure what the Wrap widget should be doing in your use case that is incorrect.

**Comment by dannyvalentesonos** [comment]
@Piinks The expected behavior is for the Wrap widget to behave like a Column, so that the elements can all be scrolled nicely in the example I attached in the description. If you run the app with the code I attached, you can see that when using a Wrap, it causes an overflow, even though the widget is inside a scrollable view. When using a Column, everything works as expected. Is it possible to have the Wrap widget behave properly in that scenario? I've also noticed that different behavior can be seen when `Wrap` widgets inside a `Column`, which is how the Flutter Markdown plugin works. It's rather strange.

In any case, as @iapicca pointed out, using `direction: Axis.vertical, /// <= THIS` fixes the issue, but it doesn't give the actual result the developer wants, which is to lay elements out horizontally first.

**Comment by Piinks** [comment]
It sounds like a `Column` gives you the expected behavior, is there a reason why a `Column` will not satisfy your need?
I don't know that the `Wrap` widget can be expected to work as a `Column` would. They have very different render objects, `RenderFlex` for the `Column` and `RenderWrap` for the `Wrap`, and they calculate their layout in different ways. 

The expanding behavior described in the sample code from the api docs above (re: `SingleChildScrollView`) is referring to `Flex` widgets, but `Wrap` isn't one of those.

**Comment by dannyvalentesonos** [comment]
@Piinks Thanks for explaining that.
In my description, I wrote

> a Column widget works very well, but a Wrap does not. Is there something maybe missing from the way the Wrap widget lays itself out that could be improved to act more like a Column?

Therefore, if you tell me it's not possible, then that can be enough. The unfortunate problem is that the flutter markdown plugin uses the `Wrap` widget for laying pieces out horizontally first, then vertically. This prevents us from using it in our layouts.

I will see about putting in a Feature Request with them to possibly use Wrap widgets only when absolutely necessary.

**Comment by Piinks** [comment]
Would you say it is the fact that the Wrap overflows that is the issue? 
I'm going to dig a bit more on this and see what's happening in the layout for Wrap. I'm going to try to reduce the code above to a more minimal sample. I think there is a way to achieve the desired layout with Wrap, just with a different composition since the sample was intended to work with Flex widgets. :)

**Comment by dannyvalentesonos** [comment]
Thanks @Piinks . You should be able to reduce the code quite a bit. I did it that way so anyone who works on it could easily see the difference between Column and Wrap.

It's important to note that we absolutely need to have a SingleChildScrollView with a IntrinsicHeight because we do need Flex widgets. I'm not sure what you're proposing about a new layout, but we'll need to still work just like the sample code does.

Thanks!

**Comment by dannyvalentesonos** [comment]
@Piinks ok here's a smaller example, that uses the layout we need to use, along with the Markdown plugin's `MarkdownBody` widget.

<details><summary>Code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: WrapHomePage2(),
    );
  }
}

class WrapHomePage2 extends StatefulWidget {
  const WrapHomePage2();

  @override
  _WrapHomePage2State createState()  => _WrapHomePage2State();
}

class _WrapHomePage2State extends State<WrapHomePage2> {

  @override
  Widget build(BuildContext context) {

    final List<Widget> middleTexts = [];
    for (int i=0; i<15; i++) {
      middleTexts.add(
          Padding(
            padding: const EdgeInsets.only(top: 24.0, bottom: 24.0),
            child: Text("Yo"),
          )
      );
    }

    String shortText = "This is paragraph.";
    String longText = "This is paragraph. Making it run onto 2 lines causes the problem!";

    // use longText to cause an overflow!
    //String firstParagraph = shortText;
    String firstParagraph = longText;
    String secondParagraph = "This is some **bold** text!";

    TextStyle defaultStyle = TextStyle(
      fontSize: 16.0,
      color: Colors.black
    );

    return Scaffold(
        body: SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: LayoutBuilder(
              builder: (context, constraints) {
                return SingleChildScrollView(
                    child: ConstrainedBox(
                      constraints: BoxConstraints(
                        minHeight: constraints.maxHeight,
                      ),
                      child: IntrinsicHeight(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.start,
                          mainAxisSize: MainAxisSize.max,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 24.0),
                              child: Column(
                                mainAxisSize: MainAxisSize.max,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.stretch,
                                children: [
                                  Text("Header text can go here", style: TextStyle(fontSize: 24),),
                                  Padding(
                                    padding: const EdgeInsets.only(top: 24.0),
                                    child: MarkdownBody(
                                        data: "$firstParagraph"
                                              "\n\n"
                                              "$secondParagraph",
                                        styleSheet: MarkdownStyleSheet.fromTheme(Theme.of(context)).copyWith(
                                            p: defaultStyle,
                                            a: defaultStyle.copyWith(decoration: TextDecoration.underline, color: Colors.blue),
                                            em: defaultStyle.copyWith(fontStyle: FontStyle.italic),
                                            strong: defaultStyle.copyWith(fontWeight: FontWeight.bold),
                                            blockSpacing: 24.0,
                                        ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Expanded(
                                child: Column(
                                  mainAxisSize: MainAxisSize.max,
                                  crossAxisAlignment: CrossAxisAlignment.stretch,
                                  children: middleTexts
                                )
                            ),
                            Padding(
                              key: ValueKey("footer"),
                              padding: const EdgeInsets.only(top: 24.0),
                              child: Column(
                                children: [
                                  Text("Bottom")
                                ],
                              ),
                            )
                          ],
                        ),
                      ),
                    )
                );
              }
            ),
          )
        )
    );
  }
}

```

</details>

<details><summary>pubspec.yaml</summary>

```
name: flutter_wrap_issues_test
description: A Flutter application to test the Wrap widget.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: 0.4.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

</details>

The issue stems whenever the Wrap widget has actual content that ends up having to lay itself out vertically because it can't lay itself out completely horizontally.

The following lines can be modified to see it working properly, or make it cause an overflow at the bottom of the page.

```
    // use longText to cause an overflow!
    //String firstParagraph = shortText;
    String firstParagraph = longText;
```
