### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by ahmaddarwesh** [flutter/flutter#61226]
I have create a flutter app 
this app use Hive package as database and use Shared preferences 
the app working perfectly on
-iOS Simulator 13.5 
-Android Emulator all android version 
-physical device (debugging mode)
-physical device (Profiling mode)

but when  I trying to get app as release mode and install it on my physical device I have this issue:

` [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
 
**and this another issue happened when app call this** 

`var dir = await getApplicationDocumentsDirectory();
   await Hive.initFlutter(dir.path);`

**Issue** 
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)`

Additional information 

**doctor -verbose** 

```
`[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-LB)
    • Flutter version 1.17.5 at /Users/ahmaddarwesh/Documents/Development/flutter
    • Framework revision 8af6b2f038 (10 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ahmaddarwesh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/ahmaddarwesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • MHA L29   • AHK7N17216007023                     • android-arm64 • Android 9 (API 28)
    • iPhone 11 • B2558C2D-C6E8-47CF-8CE1-8BD935A9F761 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!`
```

**pubspace.yaml**

```
`dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.8
  smooth_page_indicator: ^0.1.5
  #responsive and Sizes
  flutter_screenutil: ^2.2.0
  #badges for Cart and Notification
  badges: ^1.1.1
  #Animate for clicking
  flutter_bounce: ^1.0.8
  #For Expendable List (Categories)
  sticky_and_expandable_list: ^0.2.1
 
  cupertino_icons: ^0.1.3
  #Icons Material
  material_design_icons_flutter: 4.0.5345
  #Button to progress
  flutter_progress_button: ^1.0.0
  #Text Replacment
  auto_size_text: ^2.1.0
  #hasura connect for graphql database
  graphql_flutter: ^3.0.1
  #dialogs
  flutter_animated_dialog: ^1.1.0
  #zooming
  pinch_zoom_image_last: ^0.3.1
  #Scrollable List
  scrollable_positioned_list: ^0.1.6
  #Routing management
  get: ^3.2.2
  #Database
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  #shimmer
  shimmer: ^1.1.1
  #Permission manager
  permission_handler: ^5.0.1+1
  #map helper
  google_maps_flutter: ^0.5.28+1
  #Location helper
  geolocator: ^5.3.2+2

  path_provider: ^1.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter`
```
