### ISSUE TITLE
[flutter_tool] flutter plugin yaml format not correct but validation let it pass 

### ISSUE THREAD

**Issue by Chaoyang0201** [flutter/flutter#61337]
If a plugin is migrating from old plugin format to new plugin format (The multi-platform format) and forgot to add the key `flutter.plugin.platforms` at `pubspec.yaml` like below

```yaml
flutter:
  plugin:
    android:
      package: packageName
      pluginClass: className
```

and users upgrade the plugin, they will not receive any error but the build will pass as before.

BUT the plugin's platform side registrar already missing, because the `flutter_tool` can't found the correct platform type for it to generate it.

I was meet this problem recently, I will create a PR associate to this issue
  
> https://pub.dev/packages/flutter_growingio_track  version: 2.6.5  is a real case
