### ISSUE TITLE
Flutter app is not working smoothly, It starts dropping frames after several pages are switched. Scrolling is also not smooth.

### ISSUE THREAD

**Issue by Manthan-tech** [flutter/flutter#61416]
Hi there, I build an eCommerce app that loads products and its info from cloud firestore and displays in form of list. I have used Listview.builder for that. The app does somewhat better performance in release mode but it is still 'janky'. I am using the 'Provider' class for accessing data loaded from the cloud firestore.

Here is my flutter doctor --verbose

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.17763.1282], locale en-IN)
    • Flutter version 1.17.5 at G:\flutter
    • Framework revision 8af6b2f038 (13 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Manthan-PC\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.46.1)
    • VS Code at C:\Users\Manthan-PC\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available
```

these are my dependencies:-

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rubber: ^0.3.2
  pin_code_text_field: ^1.3.6
  intl: any
  flutter_svg: ^0.17.3+1
  firebase:
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.3+3
  flutter_bloc: ^3.1.0
  equatable: ^1.1.0
  shared_preferences: ^0.5.8
  fluttertoast:
  simple_animations:
  cloud_firestore: ^0.13.7
  image_picker:
  firebase_storage:
  path_provider: ^1.6.11
  carousel_pro:
  flutter_launcher_icons: ^0.7.3
  flutter_spinkit:
  firebase_messaging:
  location: any
  location_permissions: ^3.0.0+1
  location_platform_interface: ^1.0.0
  location_web: ^1.0.0
  meta: ^1.1.8
  geolocator: ^5.3.2+2
  timeline_tile: ^0.1.2
  google_fonts: ^1.1.0
  firebase_in_app_messaging: ^0.1.2
  transparent_image: ^0.1.0
```
