### ISSUE TITLE
Confusing Error Log Message on Git Dependencies

### ISSUE THREAD

**Issue by supamunkey** [flutter/flutter#61910]
## Use case

The problem arises when adding a GitHub dependency to a project. For example, say I have the following Flutter projects `projectA`, `projectB`, and `projectC`. 

In `projectC` there exist a dependency to project `projectB` in the pubspec.yml

```
/// projectC pubspec.yml

dependencies:
  flutter:
    sdk: flutter

  projectB:
    git:
      url: https://github.homedepot.com/projectB/projectB
```

Now in `projectA`, I decide to add the dependencies: `projectB` and `projectC`.

```
/// projectA pubspec.yml
dependencies:
  flutter:
    sdk: flutter

  projectB:
    git:
      url: https://github.homedepot.com/projectB/projectB
  projectC:
    git:
      url: https://github.homedepot.com/projectB/projectB
```

When running `flutter pub get`. I am now presented the following error 

> Because every version of projectC from git depends on projectB from git {url: https://github.homedepot.com/my-account/projectC.git, ref: HEAD, path: .} and projectA depends on projectB from git {url: https://github.homedepot.com/my-account/projectB, ref: HEAD, path: .}, projectC from git is forbidden.
So, because projectA depends on projectC from git, version solving failed.
pub get failed (1; So, because projectA depends on projectC from git, version solving failed.)
exit code 1

This message is overtly obtuse, and doesn't even begin to explain the actual solution to the problem.

**Solution**: add the `.git` extension to the urls. i.e https://github.homedepot.com/projectB/projectB.git

## Proposal

This error message should directly describe that the references are improperly written, causing a versioning failure. It should at least hint to the end user that they should use the git clone urls and not the repository URL, as a simple mistake like this makes it seem like the dependency management is broken as a whole.
