### ISSUE TITLE
firebase_core 0.5.0-dev.1 version solving failed

### ISSUE THREAD

**Issue by deependrasolanky** [flutter/flutter#61946]
```
dependencies:
  flutter:
    sdk: flutter

  firebase_core: "0.5.0-dev.1"
  firebase_auth: "0.16.1"
```
```
Running "flutter pub get" in <myappname>...             

Because firebase_auth 0.16.1 depends on firebase_core ^0.4.4 and <myappname> depends on firebase_core 0.5.0-dev.1, firebase_auth 0.16.1 is forbidden.
So, because <myappname> depends on firebase_auth 0.16.1, version solving failed.
pub get failed (1; So, because <myappname> depends on firebase_auth 0.16.1, version solving failed.)
Process finished with exit code 1
```
I am following official FlutterFire docs but getting above error while installing packages.

**Comment by VladyslavBondarenko** [comment]
@deependrasolanky note that 0.5.0-dev.1 is prerelease versions of firebase_core. Consider to use [latest stable `firebase_core: ^0.4.5`](https://pub.dev/packages/firebase_core/install) with stable firebase_auth.
Closing since this is not an issue with flutter.
What the official FlutterFire docs do you mean?

**Comment by deependrasolanky** [comment]
@VladyslavBondarenko I am referring to https://firebase.flutter.dev/docs/overview for the docs. 
```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: "0.5.0-dev.1"
```
For beginners in Flutter it is suggested to mention package incompatibility in the docs.
