### ISSUE TITLE
google_sign_in is failing with a PlatformException(exception, Unknown, null)

### ISSUE THREAD

**Issue by nerder** [flutter/flutter#62058]
When the user attempts to sign-in using `Google Sign in` an error is returned

## Steps to Reproduce

This is something we are not able to reproduce, but that one of our users is reporting. And we see it reflected in our logs.

**Expected results:** 

Let the user sign-in correctly

**Actual results:** 

An exception is returned

<details>
  <summary>Logs</summary>

**Exception**
```
Non-fatal Exception: java.lang.Exception: PlatformException(exception, Unknown, null)
       at StandardMethodCodec.decodeEnvelope(StandardMethodCodec.java:569)
       at MethodChannel._invokeMethod(MethodChannel.java:159)
       at MethodChannel.invokeMapMethod(MethodChannel.java:359)
```

**pubspec.yml**

```yml
name: checkin
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_crashlytics: ^0.1.1+2
  firebase_messaging: ^5.1.8
  firebase_dynamic_links: ^0.5.0+9
  firebase_storage: ^3.1.6
  firebase_analytics: ^5.0.15
  cloud_firestore: ^0.13.6
  cloud_functions: ^0.4.1+4
  google_sign_in: ^4.5.1
  sign_in_with_apple: ^2.5.1
  share: ^0.6.3+5
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  cached_network_image: 2.0.0-rc
  fluro: ^1.6.1
  platform: ^2.2.1
  json_annotation: ^3.0.0
  i18n_extension: 1.3.0
  url_launcher: ^5.4.1
  table_calendar: ^2.2.2
  flutter_svg: ^0.17.4
  package_info: ^0.4.0+14
  open_appstore: ^1.0.2
  pub_semver: ^1.4.2
  rxdart: ^0.23.1
  freezed: ^0.10.8
  image_cropper: ^1.2.3
  image_picker: ^0.6.7+1
  crypto: ^2.1.5
  http: ^0.12.1
  google_fonts: ^1.1.0

dev_dependencies:
  test: ">=1.6.3 <2.0.0"
  mockito: ^4.1.1
  bloc_test: ^4.0.0
  flutter_launcher_icons: "^0.7.5"
  stack_trace: ^1.9.3
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo-ios.png"
  adaptive_icon_background: "assets/images/bg.png"
  adaptive_icon_foreground: "assets/images/fg.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
          style: normal
        - asset: fonts/Raleway-LightItalic.ttf
          style: italic
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 700

```

```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.19.0-4.1.pre at /Users/nerder/flutter
    • Framework revision f994b76974 (6 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nerder/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.7846.93

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 84.0.4147.89

```

</details>
