### ISSUE TITLE
"flutter create --platforms=android -t plugin" for a new project shows message "The `pubspec.yaml` under the project directory must be updated to support android"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#62594]
`flutter create --platforms=android -t plugin` correctly creates the `android` directory.

### Steps to reproduce
```
$ flutter create --platforms=android -t plugin test_ada_plugin_android_only
Creating project test_ada_plugin_android_only...
  test_ada_plugin_android_only/LICENSE (created)
  test_ada_plugin_android_only/test/test_ada_plugin_android_only_test.dart (created)
  test_ada_plugin_android_only/test_ada_plugin_android_only.iml (created)
  test_ada_plugin_android_only/.gitignore (created)
  test_ada_plugin_android_only/.metadata (created)
  test_ada_plugin_android_only/android/settings.gradle (created)
  test_ada_plugin_android_only/android/gradle/wrapper/gradle-wrapper.properties (created)
  test_ada_plugin_android_only/android/gradle.properties (created)
  test_ada_plugin_android_only/android/.gitignore (created)
  test_ada_plugin_android_only/android/src/main/AndroidManifest.xml (created)
  test_ada_plugin_android_only/android/build.gradle (created)
  test_ada_plugin_android_only/android/test_ada_plugin_android_only_android.iml (created)
  test_ada_plugin_android_only/android/src/main/kotlin/com/example/test_ada_plugin_android_only/TestAdaPluginAndroidOnlyPlugin.kt (created)
  test_ada_plugin_android_only/pubspec.yaml (created)
  test_ada_plugin_android_only/README.md (created)
  test_ada_plugin_android_only/lib/test_ada_plugin_android_only.dart (created)
  test_ada_plugin_android_only/.idea/runConfigurations/example_lib_main_dart.xml (created)
  test_ada_plugin_android_only/.idea/libraries/Dart_SDK.xml (created)
  test_ada_plugin_android_only/.idea/modules.xml (created)
  test_ada_plugin_android_only/.idea/workspace.xml (created)
  test_ada_plugin_android_only/CHANGELOG.md (created)
Running "flutter pub get" in test_ada_plugin_android_only...         0.8s
The `pubspec.yaml` under the project directory must be updated to support android,
Add below lines to under the `platform:` key:


android:
 pluginClass: TestAdaPluginAndroidOnlyPlugin
 package: com.example.test_ada_plugin_android_only



If the `platforms` key does not exist in the `pubspec.yaml`, it might because that the plugin project does not
use the multi-platforms plugin format. We highly recommend a migration to the multi-platforms plugin format.
For detailed instructions on how to format the pubspec.yaml to support platforms using the multi-platforms format, see:
https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
...
```
The pubspec shows the Android platform:
```yml
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.test_ada_plugin_android_only
        pluginClass: TestAdaPluginAndroidOnlyPlugin
```

**Comment by jmagman** [comment]
I was able to repro this on master and on the 1.20 cherry-pick https://github.com/flutter/flutter/issues/59811

**Comment by jmagman** [comment]
\cc @cyanglaz

**Comment by jmagman** [comment]
Specifying just `--platforms=ios` when creating a new app shows the warning:
```
The `pubspec.yaml` under the project directory must be updated to support ios,
Add below lines to under the `platform:` key:


ios:
 pluginClass: TestAdaPluginIosMasterPlugin
```
However the pubspec.yaml already has 
```yml
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      ios:
        pluginClass: TestAdaPluginIosMasterPlugin
```

**Comment by jmagman** [comment]
I'm actually not reproducing the pubspec platform issue now from the cherry-pick, when I specify `--platforms=android` it is now consistently adding
```yml
    platforms:
      android:
        package: com.example.test_ada_plugin_android_only
        pluginClass: TestAdaPluginAndroidOnlyPlugin
```
However I do still see the message:
```
The `pubspec.yaml` under the project directory must be updated to support android,
Add below lines to under the `platform:` key:
```
@cyanglaz already has a fix ready, PR incoming.
