### ISSUE TITLE
Performance issues on web on low-end Android (e.g. Samsung A20)

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#62670]
## Details

A. See video: https://youtu.be/9kC7S_ILaho

or 

B. Open: https://experiment25.web.app/#/ on Samsung A40 (run it on the latest OS for Samsung A40 which is Android 9)

or

C. Run min repro code

## Min repro code

**icons folder** 
[icons.zip](https://github.com/flutter/flutter/files/5016821/icons.zip)

<details>
<summary>pubscpec.yaml</summary>

```yaml
name: issue62670
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
</details>

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'screens/demo_screen.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DemoScreen(),
    );
  }
}
```
</details>

<details>
<summary>demo_screen.dart</summary>

```dart
import 'package:chefmenu2/theme/style_constants.dart';
import 'package:chefmenu2/widgets/gradient_background_wrapper.dart';
import 'package:flutter/material.dart';
import 'package:chefmenu2/widgets/my_tab_bar.dart';

class DemoScreen extends StatelessWidget {
  static String id = '/demo';

  List<Widget> listViewItems() {
    List<Widget> items = [];

    for (int i = 0; i < 500; i++) {
      Widget widgetItem = Text(
        'item $i',
        textAlign: TextAlign.center,
        style: TextStyle(color: Colors.white),
      );
      items.add(widgetItem);
    }
    return items;
  }

  List<Widget> tabbarViewItems() {
    List<Widget> items = [];
    for (int i = 0; i < 25; i++) {
      Widget listView = ListView(children: listViewItems());
      items.add(listView);
    }
    return items;
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 25,
      child: Scaffold(
        floatingActionButton: MyTabBar(),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
        body: GradientBackgroundWrapper(
            child: TabBarView(
          children: tabbarViewItems(),
        )),
      ),
    );
  }
}

```
</details>

<details>
<summary>my_tab_bar.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:chefmenu2/theme/style_constants.dart';
import 'package:chefmenu2/widgets/custom_icon.dart';

class MyTabBar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.symmetric(horizontal: 4),
      padding: EdgeInsets.all(6),
      width: MediaQuery.of(context).size.width,
      decoration: BoxDecoration(
        color: colorShade3,
        borderRadius: BorderRadius.circular(30),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30),
        child: TabBar(
          isScrollable: true,
          labelColor: Colors.black,
          unselectedLabelColor: colorShade2,
          indicatorColor: Colors.white,
          indicator: BoxDecoration(shape: BoxShape.rectangle, borderRadius: BorderRadius.all(Radius.circular(30)), color: Colors.white),
          tabs: [
            Tab(icon: CustomIcon('icons/001-sausage-2.svg')),
            Tab(icon: CustomIcon('icons/028-steak.svg')),
            Tab(icon: CustomIcon('icons/061-pizza-2.svg')),
            Tab(icon: CustomIcon('icons/117-hot-dog.svg')),
            Tab(icon: CustomIcon('icons/185-cocktail.svg')),
            Tab(icon: CustomIcon('icons/001-sausage-2.svg')),
            Tab(icon: CustomIcon('icons/028-steak.svg')),
            Tab(icon: CustomIcon('icons/061-pizza-2.svg')),
            Tab(icon: CustomIcon('icons/117-hot-dog.svg')),
            Tab(icon: CustomIcon('icons/185-cocktail.svg')),
            Tab(icon: CustomIcon('icons/001-sausage-2.svg')),
            Tab(icon: CustomIcon('icons/028-steak.svg')),
            Tab(icon: CustomIcon('icons/061-pizza-2.svg')),
            Tab(icon: CustomIcon('icons/117-hot-dog.svg')),
            Tab(icon: CustomIcon('icons/185-cocktail.svg')),
            Tab(icon: CustomIcon('icons/001-sausage-2.svg')),
            Tab(icon: CustomIcon('icons/028-steak.svg')),
            Tab(icon: CustomIcon('icons/061-pizza-2.svg')),
            Tab(icon: CustomIcon('icons/117-hot-dog.svg')),
            Tab(icon: CustomIcon('icons/185-cocktail.svg')),
            Tab(icon: CustomIcon('icons/001-sausage-2.svg')),
            Tab(icon: CustomIcon('icons/028-steak.svg')),
            Tab(icon: CustomIcon('icons/061-pizza-2.svg')),
            Tab(icon: CustomIcon('icons/117-hot-dog.svg')),
            Tab(icon: CustomIcon('icons/185-cocktail.svg')),
          ],
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>style_constants.dart</summary>

```dart
import 'package:flutter/material.dart';

const Color colorShade1 = Color(0xFFEFF0F2);
const Color colorShade2 = Color(0xFF777777);
const Color colorShade3 = Color(0xFF424242);
const Color colorShade4 = Color(0xFF4B4935);
const Color colorShade5 = Color(0xFF3D2916);
const Color colorShade6 = Color(0xFF1D1C0A);

const double kTabIconHeight = 28;

```
</details>

<details>
<summary>gradient_background_wrapper.dart</summary>
```dart
import 'package:flutter/material.dart';

const Color colorShade1 = Color(0xFFEFF0F2);
const Color colorShade2 = Color(0xFF777777);
const Color colorShade3 = Color(0xFF424242);
const Color colorShade4 = Color(0xFF4B4935);
const Color colorShade5 = Color(0xFF3D2916);
const Color colorShade6 = Color(0xFF1D1C0A);

const double kTabIconHeight = 28;

```
</details>

<details>
<summary>pubspec.yaml</summary>

```yaml
name: chefmenu2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


```
</details>

**Target Platform:** web, engine:skia: `flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true --release`
**Target OS version/browser:** Android 9/Chrome
**Devices:** Samsung A20

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.117, on Mac OS X 10.15.5 19F101, locale es-ES)
    • Flutter version 1.21.0-6.0.pre.117 at /Users/tomas/Development/flutter
    • Framework revision 7ec2d360bc (27 hours ago), 2020-07-29 23:25:38 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • iPhone (mobile)    • 00008020-000415840E50003A            • ios            • iOS 14.0
    • iPhone 11 (mobile) • 04298E38-2633-4586-B868-1FBD5C708AF7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

<details>
  <summary>flutter run --verbose</summary>

```
[ +224 ms] executing:
[/Users/tomasbaran/dev/flutter/] git -c
log.showSignature=false log -n 1
--pretty=format:%H
[ +140 ms] Exit code 0 from: git -c
log.showSignature=false log -n 1
--pretty=format:%H
[   +2 ms]
e606910f28be51c8151f6169072afe3b3a8b3c5e
[   +5 ms] executing:
[/Users/tomasbaran/dev/flutter/] git tag
--contains HEAD
[ +501 ms] Exit code 0 from: git tag
--contains HEAD
[   +1 ms] 1.20.0-7.3.pre
[  +21 ms] executing:
[/Users/tomasbaran/dev/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse
--abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing:
[/Users/tomasbaran/dev/flutter/] git ls-remote
--get-url origin
[  +23 ms] Exit code 0 from: git ls-remote
--get-url origin
[        ]
https://github.com/flutter/flutter.git
[  +92 ms] Unable to locate an Android SDK.
[  +20 ms] executing:
[/Users/tomasbaran/dev/flutter/] git rev-parse
--abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse
--abbrev-ref HEAD
[   +1 ms] beta
[  +23 ms] executing: sw_vers -productName
[  +94 ms] Exit code 0 from: sw_vers
-productName
[   +1 ms] Mac OS X
[        ] executing: sw_vers -productVersion
[  +64 ms] Exit code 0 from: sw_vers
-productVersion
[   +1 ms] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +31 ms] Exit code 0 from: sw_vers
-buildVersion
[   +1 ms] 19D76
[ +112 ms] Artifact Instance of
'AndroidMavenArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of
'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of
'AndroidInternalBuildArtifacts' is not
required, skipping update.
[        ] Artifact Instance of
'IOSEngineArtifacts' is not required, skipping
update.
[   +5 ms] Artifact Instance of
'FlutterWebSdk' is not required, skipping
update.
[  +15 ms] Artifact Instance of
'WindowsEngineArtifacts' is not required,
skipping update.
[ +127 ms] Artifact Instance of
'MacOSEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of
'LinuxEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of
'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of
'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of
'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of
'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +132 ms] Unable to locate an Android SDK.
[  +12 ms] executing: /usr/bin/xcode-select
--print-path
[  +16 ms] Exit code 0 from:
/usr/bin/xcode-select --print-path
[        ] /Library/Developer/CommandLineTools
[   +2 ms] executing: /usr/bin/xcodebuild
-version
[  +15 ms] Exit code 1 from:
/usr/bin/xcodebuild -version
[   +1 ms] xcode-select: error: tool
'xcodebuild' requires Xcode, but active
developer directory
'/Library/Developer/CommandLineTools' is a
command line tools instance
[   +1 ms] Xcode not found. Run 'flutter
doctor' for more information.
[  +12 ms] executing: /usr/bin/xcodebuild
-version
[   +8 ms] Exit code 1 from:
/usr/bin/xcodebuild -version
[   +1 ms] xcode-select: error: tool
'xcodebuild' requires Xcode, but active
developer directory
'/Library/Developer/CommandLineTools' is a
command line tools instance
[  +54 ms] Artifact Instance of
'AndroidMavenArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of
'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +7 ms] Artifact Instance of
'AndroidInternalBuildArtifacts' is not
required, skipping update.
[  +12 ms] Artifact Instance of
'IOSEngineArtifacts' is not required, skipping
update.
[   +6 ms] Artifact Instance of
'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of
'MacOSEngineArtifacts' is not required,
skipping update.
[  +10 ms] Artifact Instance of
'LinuxEngineArtifacts' is not required,
skipping update.
[   +3 ms] Artifact Instance of
'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +3 ms] Artifact Instance of
'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of
'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[   +4 ms] Artifact Instance of
'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +43 ms] executing: /usr/bin/xcodebuild
-version
[  +11 ms] Exit code 1 from:
/usr/bin/xcodebuild -version
[   +1 ms] xcode-select: error: tool
'xcodebuild' requires Xcode, but active
developer directory
'/Library/Developer/CommandLineTools' is a
command line tools instance
[ +137 ms] Multiple devices found:
[ +341 ms] Web Server (web) • web-server •
web-javascript
                    • Flutter Tools
[   +3 ms] Chrome (web)     • chrome     •
web-javascript
           • Google Chrome 84.0.4147.105
[   +5 ms] [0]: Web Server (web-server)
[        ] [1]: Chrome (chrome)
[   +3 ms] Please choose one:
[        ]  [0|1]
[        ] : 
[+158033 ms] 1
[ +306 ms] Generating
/Users/tomasbaran/code/chefmenu2/android/app/s
rc/main/java/io/flutter/plugins/GeneratedPlugi
nRegistrant.java
[ +142 ms] Launching lib/main.dart on Chrome
in debug
                    mode...
[  +95 ms] Updating assets
[+1107 ms] Manifest contained wildcard assets.
Inserting missing file into build graph to
force rerun. for more information see #56466.
[  +14 ms] Syncing files to device Chrome...
[ +156 ms] Generating
/Users/tomasbaran/code/chefmenu2/android/app/s
rc/main/java/io/flutter/plugins/GeneratedPlugi
nRegistrant.java
[ +831 ms] <- reset
[  +32 ms]
/Users/tomasbaran/dev/flutter/bin/cache/dart-s
dk/bin/dart --disable-dart-dev
/Users/tomasbaran/dev/flutter/bin/cache/artifa
cts/engine/darwin-x64/frontend_server.dart.sna
pshot --sdk-root
/Users/tomasbaran/dev/flutter/bin/cache/flutte
r_web_sdk/ --incremental --target=dartdevc
--debugger-module-names
-Ddart.developer.causal_async_stacks=true
--output-dill
/var/folders/21/dn28ljzs4xd2d3rznzyxy3v40000gn
/T/flutter_tools.FEwp3z/flutter_tool.awnVL2/ap
p.dill --libraries-spec
file:///Users/tomasbaran/dev/flutter/bin/cache
/flutter_web_sdk/libraries.json --packages
.packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-
info,debugger-stops,instance-field-initializer
s,keep-unreachable-code,avoid-closure-call-ins
tructions --enable-asserts
--track-widget-creation --filesystem-root
/var/folders/21/dn28ljzs4xd2d3rznzyxy3v40000gn
/T/flutter_tools.FEwp3z/flutter_tools.w0BJOB
--filesystem-scheme org-dartlang-app
--initialize-from-dill
build/cache.dill.track.dill --platform
file:///Users/tomasbaran/dev/flutter/bin/cache
/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +31 ms] <- compile
org-dartlang-app:/web_entrypoint.dart
[+27365 ms] Syncing files to device Chrome...
(completed in 28.401ms, longer than expected)
[   +2 ms] Synced 28.4MB.
[        ] <- accept
[        ] Caching compiled dill
[+13116 ms] [CHROME]:
[   +2 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:54632/devtools/browser/4bff7573
-0d19-49f5-9263-11de97337c46
[+5347 ms] Debug service listening on
ws://127.0.0.1:54690/7oydC6nLZqA=

[ +344 ms] Debug service listening on

ws://127.0.0.1:54690/7oydC6nLZqA=
[   +5 ms] Warning: Flutter's support for web
development
           is not stable yet and hasn't
[        ] been thoroughly tested in
production
           environments.
[        ] For more information see
           https://flutter.dev/web
```
</details>
