### ISSUE TITLE
new url_launcher versions should be requiring url_launcher_web 0.1.2 or later

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#62759]
#57777 still occurs, even after the true fix was made in #46282.

Basically, I'm still always seeing this output: 
`Plugin project :url_launcher_web not found. Please update settings.gradle.` when building my app which uses the url_launcher plugin.

The fix in #46282 skips plugins that don't have an `android/build.gradle` file, however, the only issue with this is that the only version of the url_launcher_web plugin that finally removed the `android` directory is 0.1.2, and the url_launcher plugin itself still only requires `url_launcher_linux: ^0.0.1`, which means that flutter pub get will only ever get version 0.1.1+6.

So this error still is always present.

I'd recommend that a new url_launcher plugin version is released which requires url_launcher_web 0.1.2 or newer.

**Comment by pedromassangocode** [comment]
Hi @dannyvalentesonos 
Can you please provide your `pubspec.yaml`. 
Thank you

**Comment by dannyvalentesonos** [comment]
Sorry, forgot to add that.

<details><summary>pubspec.yaml</summary>

```
name: my_app
description: My test app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: 0.4.2

  url_launcher: 5.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - videos/
    - images/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

</details>

It's important to note that I've tracked down where this issue stems from and it might be specific to the Add2App feature.

The issue is that .flutter-plugins-dependencies now only contains the correct dependencies for each platform, and so for android, the url_launcher_web plugin is not listed. So, the flutter sdk's `module_plugin_loader.gradle` file doesn't include it as a project.

However, the flutter sdk's `flutter.gradle` tries to process it because the plugin has an `android/build.gradle` file and then it complains that the project wasn't loaded. The url_launcher parent plugin needs to get updated to depend on the most recent url_launcher_web plugin, which doesn't have an `android` directory. All the latest work in the Flutter sdk to handle platform plugins correctly requires that no `android` directory be present on non-android plugins.

Thanks.
