### ISSUE TITLE
compile release problem com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

### ISSUE THREAD

**Issue by prozaklob** [flutter/flutter#63136]
hi!
Im try compile android APP.

debug - ok
profile - ok

im trying delete cache/build
upgrade flutter
read google ~day

pubspec
```
dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^1.4.2
  rxdart: ^0.23.1
  flutter_launcher_icons: ^0.6.1
  shared_preferences: ^0.4.3
  json_annotation: ^2.0.0
  http: ^0.12.0
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.16
```

build.gradle root
```
buildscript {
    repositories {
        jcenter()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath 'com.google.gms:google-services:4.3.2'
    }

}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


```

build.gradle app
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "by.skifnet.balans"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
}

    buildTypes {
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.13'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    implementation 'com.google.firebase:firebase-messaging:20.2.4'
    implementation 'com.android.support:multidex:1.0.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared_preferences:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     C:\Users\admin\.gradle\caches\transforms-2\files-2.1\47ea24391513ab50879c87f9090979ca\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\admin\.gradle\caches\transforms-2\files-2.1\47ea24391513ab50879c87f9090979ca\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       4,4s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️  Creating `android\settings_aar.gradle`...
[!] Flutter tried to create the file `android\settings_aar.gradle`, but failed.
To manually update `settings.gradle`, follow these steps:

    1. Copy `settings.gradle` as `settings_aar.gradle`
    2. Remove the following code from `settings_aar.gradle`:

        def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
        def properties = new Properties()

        assert localPropertiesFile.exists()
        localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"

Please create the file and run this command again.
```

**Comment by prozaklob** [comment]
Im fixed error

im just update all dependencies in pubpsec to latest verion:

```
dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.1
  flutter_launcher_icons: ^0.7.5
  shared_preferences: ^0.5.8
  json_annotation: ^3.0.1
  http: ^0.12.2

dev_dependencies:
  build_runner: ^1.1.2
  json_serializable: ^3.3.0
```
