### ISSUE TITLE
rsync: [sender] link_stat "/Users/abdo/dev/flutter-projects/BenAsham/ios/Flutter/App.framework" failed: No such file or directory (2)

### ISSUE THREAD

**Issue by AbdOoSaed** [flutter/flutter#63150]
## Steps to Reproduce

1. ...flutter run
2. ...
3. ...

## Logs

```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                            9.8s
Failed to build iOS app
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
Error output from Xcode build:
↳
** BUILD FAILED **


Xcode's output:
↳
/Users/abdo/dev/flutter-projects/BenAsham/ios/Runner/AppDelegate.swift:15:64: warning: conditional cast from 'AppDelegate' to 'UNUserNotificationCenterDelegate' always succeeds
            UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
                                                               ^
sending incremental file list
rsync: [sender] link_stat "/Users/abdo/dev/flutter-projects/BenAsham/ios/Flutter/App.framework" failed: No such file or directory (2)

sent 19 bytes  received 12 bytes  62.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1307) [sender=3.2.2]
Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Planning build
note: Constructing build description







/Users/abdo/Library/Developer/Xcode/DerivedData/Runner-csmmijsmsskgcrfkavotgdhunvmv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Scri
                            pt-3B06AD1E1E4923F5004D2608.sh
                        ♦ mkdir -p -- /Users/abdo/dev/flutter-projects/BenAsham/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
                        ♦ rsync -av --delete /Users/abdo/dev/flutter-projects/BenAsham/ios/Flutter/App.framework
                        /Users/abdo/dev/flutter-projects/BenAsham/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
                        sending incremental file list
                        rsync: [sender] link_stat "/Users/abdo/dev/flutter-projects/BenAsham/ios/Flutter/App.framework" failed: No such file or directory (2)
                    
                        sent 19 bytes  received 12 bytes  62.00 bytes/sec
                        total size is 0  speedup is 0.00
                        rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1307) [sender=3.2.2]
                        Command PhaseScriptExecution failed with a nonzero exit code
                    
                    
[+6567 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 11 Pro Max.
[   +3 ms] "flutter run" took 54,779ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +277 ms] ensureAnalyticsSent: 252ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1

```

```
abdos-iMac-Pro:~ abdo$ flutter doctor -v
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.3 19D76, locale en-EG)
    • Flutter version 1.20.0 at /Users/abdo/dev/flutter
    • Framework revision 916c3ac648 (5 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/abdo/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.8538.45

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • 581CF638-58AA-4CA6-A366-A9347CB0ADBB • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @AbdOoSaed 
Can you please more details of the issue,  did you modify podfile?
Can you please provide your `flutter doctor -v` your `flutter run --verbose`, your `podfile`, your `pubspec.yaml`  and a complete reproducible minimal code sample
Thank you

**Comment by AbdOoSaed** [comment]
flutter doctor -v
```

abdos-iMac-Pro:~ abdo$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.3 19D76, locale en-EG)
    • Flutter version 1.20.1 at /Users/abdo/dev/flutter
    • Framework revision 2ae34518b8 (33 hours ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/abdo/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.8538.45

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 581CF638-58AA-4CA6-A366-A9347CB0ADBB • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

**Comment by AbdOoSaed** [comment]
podfile

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

**Comment by AbdOoSaed** [comment]
pubspec.yaml

```
name: ibnalsham
description: ibnalsham.

version: 5.0.0+5

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^1.1.5
  quiver: ^2.1.3
  loading: ^1.0.2
  loading_overlay: ^0.2.1
  fab_circular_menu: ^1.0.0
  flutter_datetime_picker: ^1.3.8
  flutter_open_whatsapp: ^0.1.2
  url_launcher: ^5.4.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  json_serializable: ^3.3.0
  json_annotation: ^3.0.1
  cached_network_image: 2.2.0+1
  flutter_swiper: ^1.1.6
  provider: ^4.1.3
  flutter_staggered_grid_view: ^0.3.0
  moor_flutter: ^3.0.0
  flutter_local_notifications: ^1.4.4+1
  pin_code_text_field: ^1.6.0


  #New Dependencies
  datetime_picker_formfield:
  intl:
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  connectivity: 0.4.8+6
  flutter_facebook_login: 3.0.0
  google_sign_in: 4.5.1
  firebase_auth:
  timeline_list: ^0.0.5
  grouped_buttons: ^1.0.4
  progress_dialog: ^1.2.4
  flutter_svg: ^0.17.3+1
  flutter_map: 0.9.0
  timeago:
  firebase_messaging:
  flutter_localizations:
    sdk: flutter 
  android_alarm_manager: ^0.4.5+11
  sailor: ^0.7.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.1.0
  build_runner: ^1.10.0


  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
flutter_icons:
  image_path: "assets/images/logo.png"
  ios: true
  android: false
  adaptive_icon_background: "assets/images/logo1.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/logo1.png" # only available for Android 8.0 devices and above
#  to add icon for app
#  to run => flutter pub run flutter_launcher_icons:main
flutter_native_splash:
  image: assets/images/logo1.png
  color: ffffff
#    to add icon and color to splash screen
#    to run => flutter pub pub run flutter_native_splash:create


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langs/ar.json
    - assets/langs/en.json

    - assets/images/addresses/empty_addresses.svg
    - assets/images/logo.png
    - assets/images/no_connection.svg

    - assets/images/splash/logo.png
    - assets/images/splash/splash.png
    - assets/images/forgot_password.svg

    - assets/images/points/points_gift.png
    - assets/images/favourites/favourite_empty.svg
    - assets/images/home/gift.png
    - assets/images/home/home.svg
    - assets/images/home/home_active.svg
    - assets/images/home/category.svg
    - assets/images/home/category_active.svg
    - assets/images/home/points.svg
    - assets/images/home/points_active.svg
    - assets/images/home/profile.svg
    - assets/images/home/profile_active.svg
    - assets/images/home/offers.svg
    - assets/images/home/offers_active.svg

    - assets/images/meal/meal_points.png

    - assets/images/cart/view_cart_background.png
    - assets/images/cart/cart_empty.svg
    - assets/images/my_order/my_order_empty.svg

    - assets/images/cart/cart_icon.svg
    - assets/images/cart/cart_icon_notification.svg
    - assets/images/cart/quantity_container.png

    - assets/images/completion_dialog/phone.png
    - assets/images/completion_dialog/progress_bar.png



    

  
  fonts:
    - family: arabic
      fonts:
        - asset: assets/fonts/arabic_light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

```
