### ISSUE TITLE
`flutter pub get` hangs on stable 1.20.1

### ISSUE THREAD

**Issue by kika** [flutter/flutter#63206]
When it hangs `-v` shows the conflict, that is never output without `-v` and then it just sits there wasting CPU.

Minimal repro case

<details>
  <summary>This one hangs</summary>

```yaml
name: myproject
description: MyProject

version: 1.0.1+60

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.1.6
  functional_data: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_gherkin: any
  functional_data_generator: ^0.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
```  
</details>

<details>
  <summary>This one errors out with conflict (as expected)</summary>

```yaml
name: myproject
description: MyProject

version: 1.0.1+60

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.2.2
  functional_data: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_gherkin: any
  functional_data_generator: ^0.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
```  
</details>

The only difference is `meta: ^1.1.6` in first one and `meta: ^1.2.2` in the second

<details>
  <summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.1 at /Volumes/ExtStripe/Scratch/flutter
    • Framework revision 2ae34518b8 (2 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kika/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 5.1.1 (API 22) (emulator)
    • iPhone 5s (mobile)                 • 0B3D73C5-1448-4647-A42E-5D37434D3126 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)

• No issues found!  
</details>

Also commented at https://github.com/dart-lang/pub/issues/2262#issuecomment-670611847
