### ISSUE TITLE
Respect podspec module_name

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#63240]
## Use case

A recent update to flutter (on master, not sure if it has reached other branches yet) has broken a plugin I use, [Objectbox](https://pub.dev/packages/objectbox). The issue is that they have a native package called 'objectbox' which is included by the dart plugin. Before this version they were able to get away without having any objc/swift code and therefore didn't have a framework, and so there was no name collision. However, with the new changes in master it seems as though having a plugin implementation is required.

They could theoretically get around this by publishing a separate package, but that seems really silly and leads to package bloat on pub.dev as well as more difficulty for whoever is maintaining it.

## Proposal

Instead, I'd like to propose supporting something that cocoapods has support for - setting the `s.module_name`. If this is set to something else, it eliminates the collision with the native package (i.e. objectboxdart). However, in the GeneratedPluginRegistrant.m file, it always generates it with name 'objecbox'.

If the flutter tooling supports it, it'd be great if it could be read from the podspec, but I'm going to guess that'd not possible so a perfectly great alternative would be the ability to define it directly in the pubspec.yaml for the package, something like this: 
```yaml
flutter:
  plugin:
    platforms:
      android:
        package: io.objectbox.flutter
        pluginClass: ObjectboxPlugin
      ios:
        pluginClass: ObjectboxPlugin
        moduleName: objecboxdart
```
If the `moduleName` isn't defined, it defaults to the package name as it does now. This would allow for easy overlap with native frameworks that have the same name as the flutter packages.
