### ISSUE TITLE
flutter\packages\fluttertools\gradle\flutter.gradle' as it does not exist.

### ISSUE THREAD

**Issue by lllleejessie** [flutter/flutter#63331]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\asus\Desktop\Flutter_Tutorial\second_tuto\android\app\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not read script 'C:\src\flutter\flutter\packages\fluttertools\gradle\flutter.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

flutter doctor -v

PS C:\Users\asus\Desktop\Flutter_Tutorial\second_tuto> flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter\flutter
    • Framework revision 0b8abb4724 (6 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\asus\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\asus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

KINDLY ASSIST THIS ERROR. Thanks

_Originally posted by @lllleejessie in https://github.com/flutter/flutter/issues/46094#issuecomment-671052718_

**Comment by iapicca** [comment]
@lllleejessie 
you might want to run `flutter upgrade -f`
also your providing full `flutter run -v` and your `pubspec.yaml` is often a good idea

**Comment by lllleejessie** [comment]
**_### pubspec.yaml_**
name: second_tuto
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

### _flutter run -v_
[  +41 ms] executing: [C:\src\flutter\flutter\] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +119 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\src\flutter\flutter\] git describe --match v*.*.* --first-parent    
--long --tags
[ +399 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.8-0-g0b8abb472
[  +21 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +110 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\flutter\] git ls-remote --get-url origin
[  +61 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +113 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +343 ms] executing: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe devices
-l
[  +42 ms] Exit code 0 from: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe
devices -l
[   +1 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86
           model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +89 ms] C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554
shell getprop
[ +106 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +62 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.      
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.      
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.  
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update. 
[+1255 ms] Generating
C:\Users\asus\Desktop\Flutter_Tutorial\second_tuto\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +203 ms] ro.hardware = ranchu
[ +130 ms] Using hardware rendering with device Android SDK built for x86. If you get graphicsartifacts,
                    consider enabling software rendering with "--enable-software-rendering".  
[ +117 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +87 ms] executing: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s
emulator-5554 shell -x logcat -v time -t 1
[  +84 ms] Exit code 0 from: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe -semulator-5554 shell -x logcat -v time -t 1
[   +2 ms] --------- beginning of main
           08-10 06:12:36.947 I/system_server( 1786): Background concurrent copying GC freed  
           78057(5MB) AllocSpace objects, 3(60KB) LOS objects, 34% free, 11MB/17MB, paused    
           1.096ms total 152.422ms
[  +15 ms] executing: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +27 ms] executing: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s
emulator-5554 logcat -v time -T 08-10 06:12:36.947
[  +79 ms] Android Debug Bridge version 1.0.40
           Version 4797878
           Installed as C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe        
[  +16 ms] executing: C:\Users\asus\AppData\Local\Android\sdk\platform-tools\adb.exe
start-server
[  +80 ms] Building APK
[  +24 ms] Running Gradle task 'assembleDebug'...
[   +8 ms] gradle.properties already sets `android.enableR8`
[   +8 ms] Using gradle from
C:\Users\asus\Desktop\Flutter_Tutorial\second_tuto\android\gradlew.bat.
[  +60 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +533 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +17 ms] executing: [C:\Users\asus\Desktop\Flutter_Tutorial\second_tuto\android\]
C:\Users\asus\Desktop\Flutter_Tutorial\second_tuto\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\asus\Desktop\Flutter_Tutorial\second_tuto\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-x86 assembleDebug
[+6476 ms] Starting a Gradle Daemon (subsequent builds will be faster)
[+27017 ms] > Configure project :app
[  +19 ms] WARNING: The option setting 'android.enableR8=true' is experimental and
unsupported.
[   +3 ms] The current default is 'false'
[  +36 ms] Consider disabling R8 by removing 'android.enableR8=true' from your
gradle.properties before publishing your app.
[+2646 ms] FAILURE: Build failed with an exception.
[   +9 ms] * Where:
[  +14 ms] Build file
'C:\Users\asus\Desktop\Flutter_Tutorial\second_tuto\android\app\build.gradle' line: 26        
[   +2 ms] * What went wrong:
[   +2 ms] A problem occurred evaluating project ':app'.
[ +125 ms] > Could not read script
'C:\src\flutter\flutter\packages\fluttertools\gradle\flutter.gradle' as it does not exist.    
[   +2 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug    
option to get more log output. Run with --scan to get full insights.
[   +3 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 35s
[ +396 ms] Running Gradle task 'assembleDebug'... (completed in 37.4s)
[  +57 ms] "flutter run" took 40,306ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64) 
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45) 
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64) 
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45) 
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)     
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5) 

###  **_flutter upgrade_**
Your flutter checkout has local changes that would be erased by upgrading. If you want to keepthese changes, it is recommended that you stash them via "git stash" or else commit the       
changes to a local branch. If it is okay to remove local changes, then re-run this command    
with --force.

**Comment by TahaTesser** [comment]
Hi @lllleejessie 
Looks like you're using an old version of Flutter from 6 months ago 
Can you upgrade to latest `stable` channel and try again with new project `flutter create myapp`
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persist after upgrade,   Can you please provide your `flutter doctor -v` **with upgrade** your `flutter run --verbose`   **with upgrade**  and a complete reproducible minimal code sample using  `flutter create myapp`
Thank you

**Comment by lllleejessie** [comment]
**The error still persists after the upgrade. Kindly refer below. Thanks!**
Error: Could not resolve the package 'characters' in 'package:characters/characters.dart'.
/C:/src/flutter/flutter/packages/flutter/lib/src/material/text_field.dart:9:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
/C:/src/flutter/flutter/packages/flutter/lib/widgets.dart:18:1: Error: Not found: 'package:characters/characters.dart'
export 'package:characters/characters.dart';
^
/C:/src/flutter/flutter/packages/flutter/lib/src/rendering/editable.dart:10:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
/C:/src/flutter/flutter/packages/flutter/lib/src/services/text_formatter.dart:9:8: Error: Not found: 'package:characters/characters.dart'
import 'package:characters/characters.dart';
       ^
/C:/src/flutter/flutter/packages/flutter/lib/src/material/text_field.dart:822:61: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
  int get _currentLength => _effectiveController.value.text.characters.length;
                                                            ^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/material/text_field.dart:824:118: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
  bool get _hasIntrinsicError => widget.maxLength != null && widget.maxLength > 0 && _effectiveController.value.text.characters.length > widget.maxLength;
                                                                                                                     ^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/rendering/editable.dart:244:64: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
       assert(obscuringCharacter != null && obscuringCharacter.characters.length == 1),
                                                               ^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/rendering/editable.dart:361:35: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    assert(value != null && value.characters.length == 1);
                                  ^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/rendering/editable.dart:567:11: Error: 'Characters' isn't a type.
    final Characters remaining = string.characters.skipWhile((String currentString) {
          ^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/rendering/editable.dart:567:41: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    final Characters remaining = string.characters.skipWhile((String currentString) {
                                        ^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/rendering/editable.dart:600:47: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    for (final String currentString in string.characters) {
                                              ^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/rendering/editable.dart:602:40: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
          !_isWhitespace(currentString.characters.first.toString().codeUnitAt(0))) {
                                       ^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/services/text_formatter.dart:355:11: Error: 'CharacterRange' isn't a type.
    final CharacterRange iterator = CharacterRange(value.text);
          ^^^^^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/services/text_formatter.dart:355:37: Error: Method not found: 'CharacterRange'.
    final CharacterRange iterator = CharacterRange(value.text);
                                    ^^^^^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/services/text_formatter.dart:356:20: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    if (value.text.characters.length > maxLength) {
                   ^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/services/text_formatter.dart:375:61: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
    if (maxLength != null && maxLength > 0 && newValue.text.characters.length > maxLength) {
                                                            ^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/services/text_formatter.dart:378:25: Error: The getter 'characters' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
      if (oldValue.text.characters.length == maxLength) {
                        ^^^^^^^^^^
Unhand
led exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Acharacters%2Fcharacters.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.e
n
tityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:659:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:853:21)
<asynchronous suspension>
#3      Frontend
Compiler.compile (package:frontend_server/frontend_server.dart:574:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (pack
age:flutter_frontend_s
erver/server.dart:43:22)
#5      starter (package:flutter_frontend_server/server.dart:182:27)
#6      main (file:///C:/b/s/w/ir/cac
he/build
er/src/flutter/flutter_frontend_server/bin/starter.dart:9:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _R
awReceivePortImpl._handleMessage (dart
:
i
solate-patch/isolate_patch.dar
t:168:12)



FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s

**Comment by lllleejessie** [comment]
**flutter doctor -v** _even though no issues found here_
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 1.20.1 at C:\src\flutter\flutter
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\asus\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\asus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by jmagman** [comment]
`fluttertools` package should be `flutter_tools`, where is that coming from?

**Comment by jmagman** [comment]
Can you attach `C:\Users\asus\Desktop\Flutter_Tutorial\second_tuto\android\app\build.gradle`?  Did you happen to edit that file from `flutter_tools` to `fluttertools`?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by allansrc** [comment]
Please make sure that your local.prorperties/keys.properties files has the correct path to your flutter sdk directory, and then, to "packages/flutter_tools/..."

**Comment by Warns** [comment]
@jmagman I'm having a similar issue.

Everything works fine locally, but running the project on GitHub Actions along with Fastlane gives this error as it seems it can't see the packages or SDK. Please see below my files; I can include whatever else is needed for you to see whats the prob.

```
name: myapp
description: A new Flutter project.

/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.10.4-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  adobe_xd: ^1.0.0+1
  bloc: ^6.1.1
  bloc_test: ^7.1.0
  built_collection: ">=2.0.0 <5.0.0"
  built_value: ^7.1.0
  contained_tab_bar_view: ^0.7.1
  cupertino_icons: ^0.1.3
  dartz: ^0.9.2
  dio: ^3.0.9
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0
  flutter_colored_progress_indicators: ^1.2.0
  flutter_disposebag: ^1.0.0
  flutter_mobx: ^1.1.0
  flutter_provider: ^1.1.1
  flutter_recaptcha_v2: ^0.1.0
  flutter_screenutil: 0.5.3
  flutter_sheet_localization: ^2.0.1
  flutter_staggered_animations: ^0.1.2
  font_awesome_flutter: ^8.10.1
  formz: ^0.3.2
  fsearch: ^1.0.1
  get_storage: ^1.3.2
  getwidget: ^1.2.4
  http: ^0.12.2
  image_picker: ^0.6.7+17
  intl: ^0.16.1
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  kartal: ^1.1.0
  line_icons: ^0.2.0
  liquid_progress_indicator: ^0.3.2
  material_design_icons_flutter: ^4.0.5755
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  path: ^1.7.0
  google_fonts: ^1.1.2
  percent_indicator: ^2.1.9
  responsive_assistant: ^0.0.7
  rx_shared_preferences: ^1.3.5
  settings_ui: ^0.5.0
  shared_preferences: ^0.5.12+4
  sizer: ^1.1.8
  tuple: ^1.0.3
  vexana: ^1.3.1

dependency_overrides: null
#rxdart: ^0.26.0-nullsafety.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
  flutter_sheet_localization_generator: ^2.1.2
  pedantic: ^1.9.0
  quiver: ">=0.21.0 <3.0.0"
  test: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/davletvm.jpeg
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/SociallMe.png
    - assets/images/platform_facebook.png
    - assets/images/platform_twitter.png
    - assets/images/plat_youtube.png
    - assets/images/plat_linked_in.png
    - assets/images/plat_pinterest.png
    - assets/images/pcgamer_plat.png
    - assets/images/haberportal_web_araz.png
    - assets/images/haber_portal_one_grey.png
    - assets/images/haber_portal_one_blue.png
    - assets/images/blog_plat_paraanaliz.png
    - assets/images/blog_plat_rotasiz.png
    - assets/images/blog_plat_ego.png
    - assets/images/blog_plat_one_blue.png
    - assets/images/cigdem.png
    - assets/animations/
    - assets/langs/tr-TR.json
    - assets/langs/en-US.json
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
```

`./android/build.gradle`

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

Is it something about `project.buildDir = "${rootProject.buildDir}/${project.name}"`? How am I to point the project running on GitHub Actions runner to see the files it needs?

**Comment by Warns** [comment]
@jmagman I'm having a similar issue.

`Could not read script '/Users/user/Developer/flutter/packages/flutter_tools/gradle/flutter.gradle' as it does not exist.`

Everything works fine locally, but running the project on GitHub Actions along with Fastlane gives this error as it seems it can't see the packages or SDK. Please see below my files; I can include whatever else is needed for you to see whats the prob.

`pubspec.yaml`

```
name: myapp
description: A new Flutter project.

/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.10.4-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  adobe_xd: ^1.0.0+1
  bloc: ^6.1.1
  bloc_test: ^7.1.0
  built_collection: ">=2.0.0 <5.0.0"
  built_value: ^7.1.0
  contained_tab_bar_view: ^0.7.1
  cupertino_icons: ^0.1.3
  dartz: ^0.9.2
  dio: ^3.0.9
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0
  flutter_colored_progress_indicators: ^1.2.0
  flutter_disposebag: ^1.0.0
  flutter_mobx: ^1.1.0
  flutter_provider: ^1.1.1
  flutter_recaptcha_v2: ^0.1.0
  flutter_screenutil: 0.5.3
  flutter_sheet_localization: ^2.0.1
  flutter_staggered_animations: ^0.1.2
  font_awesome_flutter: ^8.10.1
  formz: ^0.3.2
  fsearch: ^1.0.1
  get_storage: ^1.3.2
  getwidget: ^1.2.4
  http: ^0.12.2
  image_picker: ^0.6.7+17
  intl: ^0.16.1
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  kartal: ^1.1.0
  line_icons: ^0.2.0
  liquid_progress_indicator: ^0.3.2
  material_design_icons_flutter: ^4.0.5755
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  path: ^1.7.0
  google_fonts: ^1.1.2
  percent_indicator: ^2.1.9
  responsive_assistant: ^0.0.7
  rx_shared_preferences: ^1.3.5
  settings_ui: ^0.5.0
  shared_preferences: ^0.5.12+4
  sizer: ^1.1.8
  tuple: ^1.0.3
  vexana: ^1.3.1

dependency_overrides: null
#rxdart: ^0.26.0-nullsafety.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
  flutter_sheet_localization_generator: ^2.1.2
  pedantic: ^1.9.0
  quiver: ">=0.21.0 <3.0.0"
  test: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/davletvm.jpeg
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/SociallMe.png
    - assets/images/platform_facebook.png
    - assets/images/platform_twitter.png
    - assets/images/plat_youtube.png
    - assets/images/plat_linked_in.png
    - assets/images/plat_pinterest.png
    - assets/images/pcgamer_plat.png
    - assets/images/haberportal_web_araz.png
    - assets/images/haber_portal_one_grey.png
    - assets/images/haber_portal_one_blue.png
    - assets/images/blog_plat_paraanaliz.png
    - assets/images/blog_plat_rotasiz.png
    - assets/images/blog_plat_ego.png
    - assets/images/blog_plat_one_blue.png
    - assets/images/cigdem.png
    - assets/animations/
    - assets/langs/tr-TR.json
    - assets/langs/en-US.json
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
```

`./android/build.gradle`

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

Is it something about `project.buildDir = "${rootProject.buildDir}/${project.name}"`? How am I to point the project running on GitHub Actions runner to see the files it needs?
