### ISSUE TITLE
Accidentally fall in fullscreen mode on both Android and iOS

### ISSUE THREAD

**Issue by ngoan98tv** [flutter/flutter#63332]
Recently I realize that my app starting in fullscreen mode (status bar is hidden) while I haven't changed `SystemUIOverlays` options yet. Then, I try `SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);` but it's not working.

I tried to create a new app to check if it's due to Flutter or my app. But the new app work fine. I think the problem is from one of  the dependencies but I don't know which one.

## Steps to Reproduce
I have no clue to reproduce it.
I have used `flutter_native_splash`. When opening the app, on the splash screen, status bar display well, but at the end of the splash screen, the status bar start hidden.

**Expected results:** 
The app should show system overlays as normal.

**Actual results:** 
The status bar is hidden. 
The app run in fullscreen mode.

<details>
  <summary>Source code</summary>

pubspec.yaml

```yaml
name: myapp
description: myapp
publish_to: 'none'
version: 2.24.107+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.0.5
  http: ^0.12.0+4
  flutter_vector_icons: ^0.2.1
  shimmer: ^1.1.1
  shared_preferences: ^0.5.7
  intl: ^0.16.1
  cached_network_image: ^2.1.0+1
  wc_flutter_share: ^0.2.0
  image_picker: ^0.6.6+1
  extended_image: ^0.7.3+1
  image_editor: ^0.7.1
  path_provider: ^1.6.8
  http_parser: ^3.1.4
  url_launcher: ^5.4.7
  cloud_firestore: ^0.13.5
  flutter_slidable: ^0.5.4
  fl_chart: ^0.10.0
  carousel_slider: ^2.1.0
  palette_generator: ^0.2.3
  language_pickers: ^0.2.0+1
  i18n_extension: ^1.4.1 
  flutter_inappwebview: ^4.0.0+4
  after_layout: ^1.0.7+2
  visibility_detector: ^0.1.5
  firebase_messaging: ^6.0.16
  connectivity: ^0.4.9
  firebase_crashlytics: ^0.1.4+1
  firebase_analytics: ^5.0.16
  firebase_performance: ^0.3.2
  http_retry: ^0.1.1+3
  flutter_cache_manager: ^1.4.1
  flutter_user_agent: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9

# Run this command to apply flutter_icons config
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_square_magenta.png"
  adaptive_icon_foreground: "#ffffff"

flutter_native_splash:
  image: assets/logo-rect-pink-xl.png
  color: "#FDFDFD"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
```
flutter analyze
```
Analyzing mobile-client...                                              
No issues found! (ran in 8.8s)
```

flutter doctor -v

```
[✓] Flutter (Channel master, 1.21.0-8.0.pre.121, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-8.0.pre.121 at /opt/flutter
    • Framework revision bc079c162c (9 hours ago), 2020-08-09 00:56:01 -0400
    • Engine revision ece904289b
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/tvngoan/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Redmi Note 7 (mobile) • e09ec41b • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

</details>
