### ISSUE TITLE
Error on running  build_runner  after upgrading to version Flutter Channel stable, 1.20.1

### ISSUE THREAD

**Issue by yeras-is** [flutter/flutter#63501]
## Steps to Reproduce

1. modify pubspec 
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_translation: ^0.17.1
  responsive_builder: ^0.2.0+2
  provider: ^4.0.5+1
  get: ^3.1.1
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  kinfolk_gui: ^1.0.0+1
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  kinfolk: ^0.0.8

flutter_intl:
  enabled: true

dependency_overrides:
  path: 1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: ^1.10.0

```
2. Create Entity 
```
import 'package:hive/hive.dart';

 @HiveType(typeId: 0)
class AbstractDictionary {
  AbstractDictionary({
    this.id,
    this.version,
    this.createTs,
    this.createdBy,
    this.updateTs,
    this.updatedBy,
    this.deleteTs,
    this.deletedBy,
    this.legacyId,
    this.langValue1,
    this.description1,
    this.langValue2,
    this.description2,
    this.langValue3,
    this.description3,
    this.langValue4,
    this.description4,
    this.langValue5,
    this.description5,
    this.startDate,
    this.endDate,
    this.code,
    this.isSystemRecord,
    this.active,
    this.order,
    this.name,
    this.entityName,
  });

   @HiveField(0)
  String id;
   @HiveField(1)
  int version;
   @HiveField(2)
  String entityName;
   @HiveField(3)
  DateTime createTs;
   @HiveField(4)
  String createdBy;
   @HiveField(5)
  DateTime updateTs;
   @HiveField(6)
  String updatedBy;
   @HiveField(7)
  DateTime deleteTs;
   @HiveField(8)
  String deletedBy;
   @HiveField(9)
  String legacyId;
   @HiveField(10)
  String langValue1;
   @HiveField(11)
  String description1;
   @HiveField(12)
  String langValue2;
   @HiveField(13)
  String description2;
   @HiveField(14)
  String langValue3;
   @HiveField(15)
  String description3;
   @HiveField(16)
  String langValue4;
   @HiveField(17)
  String description4;
   @HiveField(18)
  String langValue5;
   @HiveField(19)
  String description5;
   @HiveField(20)
  DateTime startDate;
   @HiveField(21)
  DateTime endDate;
   @HiveField(22)
  String code;
   @HiveField(23)
  bool isSystemRecord;
   @HiveField(24)
  bool active;
   @HiveField(25)
  int order;
   @HiveField(26)
  String name;
}

```
3. run command 
```
flutter packages pub run build_runner build --delete-conflicting-outputs
```

## Logs
```
C:\Users\maiha\AndroidStudioProjects\crm>flutter packages pub run build_runner bu
ild --delete-conflicting-outputs
Precompiling executable...
Precompiled build_runner:build_runner.
[INFO] Generating build script...
[INFO] Generating build script completed, took 306ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 5.3s

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/hive_generator-0.7.1/lib/
src/type_adapter_generator.dart:60:76: Error: Getter not found: 'ENUM'.    check(
element.kind == ElementKind.CLASS || element.kind == ElementKind.ENUM,
                                                                ^^^^
pub finished with exit code 78

```

## Doctor
```
C:\Users\maiha\AndroidStudioProjects\crm>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version
    10.0.18363.959], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.47.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by yeras-is** [comment]
solve with modified pubspec 
```
environment:
  sdk: ">=2.9.0-13.0 <3.0.0" <- modified to solve build_runner 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_translation: ^0.17.1
  responsive_builder: ^0.2.0+2
  provider: ^4.0.5+1
  get: ^3.1.1
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  table_calendar: ^2.2.3
  flutter_login: ^1.0.14
  font_awesome_flutter: ^8.8.1
  fsearch: ^1.0.0
  supercharged: ^1.7.0
  kinfolk_gui: ^1.0.0+1
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  kinfolk: ^0.0.8
  build_resolvers: ^1.3.11  <- modified to solve build_runner 
 
flutter_intl:
  enabled: true

dependency_overrides:
  path: 1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: ^1.10.0

```
