### ISSUE TITLE
The method 'FirebaseStorageImage.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.

### ISSUE THREAD

**Issue by eturk1** [flutter/flutter#63862]
I can no longer compile and run my app.

on Flutter stable channel (have tried all channels)
Seems like an inconsistency in the packages?

```
dependencies:
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  firebase_storage_image: ^0.4.0

```

Errors:
```
../../../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage_image-0.4.0/lib/firebase_storage_image.dart:54:24: Error: The method 'FirebaseStorageImage.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(FirebaseStorageImage key) =>
                       ^
../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:578:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^

```
