### ISSUE TITLE
[device_info] Unique ID retrieved from plugin is different after reinstallation

### ISSUE THREAD

**Issue by tapizquent** [flutter/flutter#64063]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
    Add `device_info` to pubspec.yaml
3. Get device id with the following method:
```
Future<String> _getDeviceId() async {
    String deviceId;
    DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
    if (Platform.isAndroid) {
      final androidInfo = await deviceInfo.androidInfo;
      deviceId = androidInfo.androidId;
    } else {
      final iosInfo = await deviceInfo.iosInfo;
      deviceId = iosInfo.identifierForVendor;
    }
    return deviceId;
  }
```

**Expected results:** The same ID should be returned regardless of reinstallation

**Actual results:** A different ID was returned

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment]
Hi @tapizquent 
Can you please provide your `pubspec.yaml`?
Thank you

**Comment by tapizquent** [comment]
@pedromassangocode 

Hey Pedro
```
name: icay
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
 ** other packages **
  device_info: ^0.4.2+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  ** dev packages **

flutter_icons:
  image_path: "images/launcher_icons/ic_launcher.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family:  AdditionalIcons
      fonts:
       - asset: fonts/AdditionalIcons.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
