### ISSUE TITLE
flutter_driver and firebase_messaging are incompatible

### ISSUE THREAD

**Issue by zeromaro** [flutter/flutter#64312]
Hey y'all,

With latest Firebase updates, it seems some dependencies are clashing.

Flutter version
```
Flutter (Channel master, 1.21.0-10.0.pre.212, on macOS 11.0 20A5354i, locale en-HK)
```
`pubspec.yaml`
```
<..>
environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  <..>
  firebase_messaging: ^7.0.0
  <..>

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  <..>

```
```
Because every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.1 and firebase_messaging 7.0.0 depends on platform ^2.0.0, flutter_driver from sdk is incompatible with firebase_messaging 7.0.0.
And because no versions of firebase_messaging match >7.0.0 <8.0.0, flutter_driver from sdk is incompatible with firebase_messaging ^7.0.0.
So, because fluid depends on both firebase_messaging ^7.0.0 and flutter_driver any from sdk, version solving failed.
```

Any ideas, is it solvable on current `master`? Downgrading flutter to ...139 works well.
