### ISSUE TITLE
Flutter release apk size is very large in flutter sdk version 1.20

### ISSUE THREAD

**Issue by umair-ilyas** [flutter/flutter#64388]
I am making a very simple app with 15 screens. And when i run this command [flutter run --release](url). My release apk size is 26.2mb, which is very large.

My flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Android Studio (version 4.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

My pubspec.yaml file contain these dependencies:
```
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  provider: any
  image_picker: ^0.6.7+4
  menu_button: ^1.2.1
  pin_code_fields: ^5.0.1
  flutter_pdfview:
  path_provider:
  http:
```

![github](https://user-images.githubusercontent.com/45622742/90956630-bbcf1600-e4a1-11ea-88a1-d68cb05c9c08.jpg)

These files takes the more space. Is there any way that we can reduce the release apk size. For apps like this, the size is very large. In my previous flutter sdk version 1.17 the release apk size of 30 screen app is not more than 15 mb.
