### ISSUE TITLE
NoSuchMethodError: The getter 'value' was called on null in borders.dart in paintBorder at line 717

### ISSUE THREAD

**Issue by ryanhz** [flutter/flutter#64531]
## Steps to Reproduce

I don't really know how to reproduce it, it is from sentry's report

**Expected results:** 

No exception

**Actual results:** 

<details>
  <summary>Logs</summary>

```
NoSuchMethodError
NoSuchMethodError: The getter 'value' was called on null.
Receiver: null
Tried calling: value
borders.dart in paintBorder at line 717
box_border.dart in Border.paint at line 547
box_decoration.dart in _BoxDecorationPainter.paint at line 481
proxy_box.dart in RenderDecoratedBox.paint at line 2077
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
proxy_box.dart in RenderProxyBoxMixin.paint at line 133
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
shifted_box.dart in RenderShiftedBox.paint at line 72
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2752
flex.dart in RenderFlex.paint at line 975
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
proxy_box.dart in RenderProxyBoxMixin.paint at line 133
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
proxy_box.dart in RenderProxyBoxMixin.paint at line 133
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
proxy_box.dart in RenderProxyBoxMixin.paint at line 133
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
proxy_box.dart in RenderProxyBoxMixin.paint at line 133
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
proxy_box.dart in RenderProxyBoxMixin.paint at line 133
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
proxy_box.dart in RenderProxyBoxMixin.paint at line 133
proxy_box.dart in RenderDecoratedBox.paint at line 2096
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2752
flex.dart in RenderFlex.paint at line 975
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
shifted_box.dart in RenderShiftedBox.paint at line 72
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2752
flex.dart in RenderFlex.paint at line 975
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2752
flex.dart in RenderFlex.paint at line 975
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
basic.dart in _RenderColoredBox.paint at line 7325
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
shifted_box.dart in RenderShiftedBox.paint at line 72
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2752
flex.dart in RenderFlex.paint at line 975
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext.paintChild at line 191
single_child_scroll_view.dart in _RenderSingleChildViewport.paint.paintContents at line 588
object.dart in PaintingContext.pushLayer at line 398
object.dart in PaintingContext.pushClipRect at line 454
single_child_scroll_view.dart in _RenderSingleChildViewport.paint at line 592
object.dart in RenderObject._paintWithContext at line 2316
object.dart in PaintingContext._repaintCompositedChild at line 142
object.dart in PaintingContext.repaintCompositedChild at line 102
object.dart in PipelineOwner.flushPaint at line 989
binding.dart in RendererBinding.drawFrame at line 405
binding.dart in WidgetsBinding.drawFrame at line 914
binding.dart in RendererBinding._handlePersistentFrameCallback at line 286
binding.dart in SchedulerBinding._invokeFrameCallback at line 1117
binding.dart in SchedulerBinding.handleDrawFrame at line 1055
binding.dart in SchedulerBinding._handleDrawFrame at line 971
Called from: zone.dart in _rootRun
```

```
 flutter analyze
Analyzing mrfussy...                                                    
No issues found! (ran in 13.3s)
```

```
flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-2.0.pre.34, on Mac OS X 10.15.6 19G2021, locale en-AU)
    • Flutter version 1.22.0-2.0.pre.34 at /Users/Ryan/Applications/flutter
    • Framework revision fe68f695ff (3 days ago), 2020-08-21 16:04:17 -0700
    • Engine revision d495da20d0
    • Dart version 2.10.0 (build 2.10.0-49.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/Ryan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • SM G950F (mobile) • ce0317136509a4d80c • android-arm64 • Android 9 (API 28)
```

</details>

**Comment by sidrao2006** [comment]
Could you please check your code for the usage of decorated box or any other form of decoration

**Comment by Abhishek01039** [comment]
Hi, @ryanhz as @sidrao2006  suggested do it.
if you don't figure it out then share the code in which you are using any form of decoration.
thanks.

**Comment by markusaksli-nc** [comment]
Hi @ryanhz  
Can you please provide your `pubspec.yaml` and `flutter run --release --verbose` logs?
Thank you

**Comment by ryanhz** [comment]
@markusaksli-nc  Sorry, I really don't know how to reproduce it, even I have the code.

Looking at borders.dart: 717
`paint.color = right.color;`
It sounds like `right.color` is null, but right is not null

Sometimes, the same error happened on line 755:
`paint.color = left.color;` 
Which is like `left.color` is null, but left is not null

The closest thing that has null border is those code:
```dart
BoxDecoration(
	border: (count != list.length)? Border(
		bottom: BorderSide(
			color: Color.fromRGBO(0, 0, 0, 0.2),
			width: 1.0
		),
	) : null,
)
```
```dart
BoxDecoration(
	border: Border(
		left: BorderSide(
			color: clazz.bgColor,
			width: 6.0,
			style: BorderStyle.solid,
		)
	),
)
```
 
```dart
BoxDecoration(
	border: Border(
		right: BorderSide(
			color: clazz.bgColor,
			width: 6.0,
			style: BorderStyle.solid,
		)
	),
)
```
`clazz.bgColor` may be null

I think BorderSide() constructor's color  should be not null-able, alternatively, in the code, if it is null, assign default 
`const Color(0xFF000000)`

Having a default value still can't prevent passing null value into it.


pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^2.0.2+1
  badges: ^0.0.6
  calendar_views: ^0.5.2
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.8.1
  convert: ^2.1.1
  dart_otp: ^1.3.0
  dio: ^1.0.4
  dropdown_menu:
    git: https://github.com/ryanhz/flutter_dropdown_menu.git
  easy_debounce: ^1.0.1
  encrypt: ^4.0.2
  dash_chat: ^1.1.14
  file_picker: ^1.9.0+1
  fluent_i18n: ^1.0.0
  flutter_app_badger: ^1.1.2
  flutter_blue:
    git:
      url: https://github.com/ryanhz/flutter_blue.git
      ref: master
  flutter_chips_input:
    git: https://github.com/ryanhz/flutter_chips_input.git
  flutter_circular_chart: ^0.1.0
  flutter_easyrefresh:
    git: https://github.com/ryanhz/flutter_easyrefresh.git
  flutter_form_builder:
    git: https://github.com/ryanhz/flutter_form_builder.git
  flutter_html: ^0.9.6
  flutter_icons: ^1.1.0
  flutter_image: ^3.0.0
  flutter_linkify: ^2.1.0
  flutter_local_notifications: ^1.4.3
  flutter_platform_widgets:
    git: https://github.com/ryanhz/flutter_platform_widgets.git
  flutter_speed_dial: ^1.1.1
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.4.0
  intl: ^0.16.0
  nfc_emulator: ^1.0.1+1
  open_file: ^2.0.3
  overlay_support: ^1.0.4
  package_info: ^0.4.1
  qr_flutter: ^2.0.0+51
  settings_ui: ^0.3.0
  sentry: ^2.2.0
  smart_select: ^3.0.3
  swipedetector: ^1.2.0
  sy_flutter_widgets: ^0.1.4
  table_calendar: ^2.1.0
  tinycolor: ^1.0.2
  tuple: ^1.0.2
  uni_links: ^0.2.0

  add_2_calendar: ^1.3.0
  audioplayers: ^0.14.0
  barcode_scan:
    git: https://github.com/ryanhz/flutter_barcode_reader.git
  device_info: ^0.4.0+2
  firebase_messaging: ^6.0.16
  image_picker: ^0.6.1+4
  launch_review: ^2.0.0
  path_provider: ^1.2.2
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+3
  url_launcher: ^5.2.5
  webview_flutter: ^0.3.13
  nfc_in_flutter:
    git: https://github.com/ryanhz/nfc_in_flutter.git
  community_material_icon: ^3.5.95
```
