### ISSUE TITLE
Run application fail with new flutter version

### ISSUE THREAD

**Issue by billysutomo** [flutter/flutter#64747]
## Steps to Reproduce

1. Run `flutter build apk`.

**Expected results:** 
Application running on emulator

**Actual results:** 
Build application fail

<details>
  <summary>Logs</summary>

```
 +442 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Build file '/home/billysutomo/Engineering/code/mobile-flutter/android/build.gradle' line: 26
[        ] * What went wrong:
[        ] A problem occurred evaluating root project 'android'.
[        ] > A problem occurred configuring project ':app'.
[        ]    > java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 0s
[ +364 ms] Running Gradle task 'assembleRelease'... (completed in 0.8s)
[   +8 ms] "flutter apk" took 1,279ms.
[   +6 ms] Gradle task assembleRelease failed with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:411:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
info • Unused import: 'widgets/custom_widgets.dart' • lib/screens/home/my_hebo/my_hebo_screen.dart:2:8 • unused_import
   info • 'typed' is deprecated and shouldn't be used. Use stream.cast instead • lib/services/file_service.dart:17:44 • deprecated_member_use
   info • 'typed' is deprecated and shouldn't be used. Use stream.cast instead • lib/services/file_service.dart:47:44 • deprecated_member_use
   info • 'typed' is deprecated and shouldn't be used. Use stream.cast instead • lib/services/file_service.dart:76:44 • deprecated_member_use
   info • The value of the local variable 'a' isn't used • lib/widgets/preview_campaign.dart:92:17 • unused_local_variable
   info • The declaration '_downloadInstagramPost' isn't referenced • lib/widgets/preview_campaign.dart:115:3 • unused_element
   info • The declaration '_downloadInstagramStory' isn't referenced • lib/widgets/preview_campaign.dart:133:3 • unused_element

7 issues found. (ran in 1.2s)
```

```
[✓] Flutter (Channel beta, 1.20.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.2 at /home/billysutomo/snap/flutter/common/flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/billysutomo/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment]
Hi @billysutomo
Can you please provide your `flutter build appbundle --verbose` and your `pubspec.yaml`?
Thank you

**Comment by billysutomo** [comment]
Hi @pedromassangocode 
Below output of `flutter build appbundle --verbose`
```
[  +84 ms] executing: [/home/billysutomo/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +177 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] bbfbf1770cca2da7c82e887e4e4af910034800b6
[   +1 ms] executing: [/home/billysutomo/snap/flutter/common/flutter/] git tag --contains HEAD
[ +566 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.2
[   +6 ms] executing: [/home/billysutomo/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/billysutomo/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +37 ms] executing: [/home/billysutomo/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +95 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +90 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +102 ms] Found plugin android_intent at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/android_intent-0.3.5/
[ +218 ms] Found plugin file_picker at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-1.4.3+2/
[  +43 ms] Found plugin flutter_plugin_android_lifecycle at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.5/
[   +3 ms] Found plugin fluttertoast at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/
[  +16 ms] Found plugin geocoder at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/geocoder-0.2.1/
[   +3 ms] Found plugin geolocator at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-5.2.1/
[  +22 ms] Found plugin google_api_availability at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/google_api_availability-2.0.2/
[  +17 ms] Found plugin google_map_location_picker at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/google_map_location_picker-3.2.1/
[  +15 ms] Found plugin google_maps_flutter at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.24/
[  +51 ms] Found plugin location_permissions at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/location_permissions-2.0.4+1/
[  +84 ms] Found plugin package_info at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+13/
[   +6 ms] Found plugin path_provider at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.10/
[   +5 ms] Found plugin path_provider_linux at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+1/
[  +26 ms] Found plugin path_provider_macos at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[ +115 ms] Found plugin shared_preferences at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/
[  +14 ms] Found plugin shared_preferences_macos at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+3/
[  +15 ms] Found plugin shared_preferences_web at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+2/
[ +332 ms] Found plugin android_intent at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/android_intent-0.3.5/
[  +10 ms] Found plugin file_picker at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-1.4.3+2/
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.5/
[        ] Found plugin fluttertoast at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.3/
[   +1 ms] Found plugin geocoder at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/geocoder-0.2.1/
[        ] Found plugin geolocator at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-5.2.1/
[   +1 ms] Found plugin google_api_availability at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/google_api_availability-2.0.2/
[   +1 ms] Found plugin google_map_location_picker at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/google_map_location_picker-3.2.1/
[        ] Found plugin google_maps_flutter at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.24/
[   +3 ms] Found plugin location_permissions at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/location_permissions-2.0.4+1/
[   +2 ms] Found plugin package_info at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+13/
[   +1 ms] Found plugin path_provider at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.10/
[        ] Found plugin path_provider_linux at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+1/
[        ] Found plugin path_provider_macos at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[   +3 ms] Found plugin shared_preferences at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/
[        ] Found plugin shared_preferences_macos at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+3/
[   +1 ms] Found plugin shared_preferences_web at /home/billysutomo/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+2/
[ +170 ms] Generating /home/billysutomo/Engineering/code/mobile-flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +42 ms] Running Gradle task 'bundleRelease'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +1 ms] Using gradle from /home/billysutomo/Engineering/code/mobile-flutter/android/gradlew.
[        ] /home/billysutomo/Engineering/code/mobile-flutter/android/gradlew mode: 33277 rwxrwxr-x.
[  +15 ms] executing: /usr/local/android-studio/jre/bin/java -version
[  +42 ms] Exit code 0 from: /usr/local/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +2 ms] executing: [/home/billysutomo/Engineering/code/mobile-flutter/android/] /home/billysutomo/Engineering/code/mobile-flutter/android/gradlew -Pverbose=true
-Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib/main.dart -Ptrack-widget-creation=true -Pshrink=true -Ptree-shake-icons=true bundleRelease
[ +741 ms] Starting a Gradle Daemon (subsequent builds will be faster)
[+3587 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Build file '/home/billysutomo/Engineering/code/mobile-flutter/android/build.gradle' line: 26
[        ] * What went wrong:
[        ] A problem occurred evaluating root project 'android'.
[        ] > A problem occurred configuring project ':app'.
[        ]    > java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 4s
[ +348 ms] Running Gradle task 'bundleRelease'... (completed in 4.7s)
[   +3 ms] "flutter appbundle" took 6,282ms.
[   +3 ms] Gradle task bundleRelease failed with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:411:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[  +98 ms] ensureAnalyticsSent: 97ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
And below content of `pubspec.yaml`
```
name: hebo_mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  http: ^0.12.0+2
  file_picker: ^1.4.3+2
  google_map_location_picker: ^3.2.1
  google_maps_flutter: ^0.5.21+15
  flutter_google_places: ^0.2.3
  geocoder: ^0.2.1
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6
  flutter_datetime_picker: ^1.3.4
  equatable: ^1.1.0
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  path_provider: ^1.6.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/icons/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
