### ISSUE TITLE
Bundling assets only on a specific platform (and remove assets on another platform)

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#64993]
## Steps to Reproduce

Hi thanks for the wonderful Flutter! I have some images (1.1MB) that should only be used in Android, not iOS. Therefore, I want to *remove* those images from the IPA file in iOS. I have read the official doc, but it did not mention things like this :/

**Expected results:** 

Give some options, such as (pubspec.yaml):
```
flutter:
  assets:
    android:
      - some_images_only_in_android/
    ios:
      - some_images_only_in_ios/
   all:
      - some_images_for_both/
```

**Actual results:** No such feature

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
