### ISSUE TITLE
Bundling assets only on a specific platform (and remove assets on another platform)

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#65065]
**NOTE: This is *not* a duplicate!** My previous issue https://github.com/flutter/flutter/issues/64993 is closed because of wrongly marked as a duplicate. Thus I have no choice but to create it again :/

(Why not duplicate of #8230 : I want to bundle those 1MB photos only in Android. Thus, in the final .ipa file of iOS, there are no such photos taking space.)

## Steps to Reproduce

Hi thanks for the wonderful Flutter! I have some images (1.1MB) that should only be used in Android, not iOS. Therefore, I want to *remove* those images from the IPA file in iOS. I have read the official doc, but it did not mention things like this :/

**Expected results:** 

Give some options, such as (pubspec.yaml):
```
flutter:
  assets:
    android:
      - some_images_only_in_android/
    ios:
      - some_images_only_in_ios/
   all:
      - some_images_for_both/
```

**Actual results:** No such feature

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
