### ISSUE TITLE
W/FlutterEngine(30444): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@7a0372e) but could not find and invoke the GeneratedPluginRegistrant.

### ISSUE THREAD

**Issue by CaLouro** [flutter/flutter#65261]
Hello everyone.

I've been getting this error on flutter console and I don't know what it means or implies, and I'd like some help. 

`W/FlutterEngine(30444): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@7a0372e) but could not find and invoke the GeneratedPluginRegistrant.`

This error doesn't show 100% of the time, but it's very frequent. Additionally I've been getting errors on Firebase Installations API and I thought this could be the reason.

I thank any help on this problem.

<details>
  <summary>Logs</summary>

```
flutter analyze
Analyzing <my_project>...
No issues found! (ran in 29.0s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Microsoft Windows [versÃ£o 10.0.19041.450], locale pt-BR)
    • Flutter version 1.20.3 at C:\Users\caios\Documents\flutter
    • Framework revision 216dee60c0 (3 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\caios\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\caios\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[✓] Connected device (1 available)
    • SM G965U1 (mobile) • 35494b4435563098 • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

**Comment by iapicca** [comment]
@CaLouro 
if the problem is with firebase the issue should be opened [here](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by CaLouro** [comment]
Hey @iapicca I don't think the problem is with Firebase. For me it looks like an error with Flutter Engine that errors a Firebase API

But thanks for reminding me of the flutterfire repo, I'll see if something like this was posted there

**Comment by CaLouro** [comment]
Hi @TahaTesser, checking what you asked for:

<details>
  <summary> Project level build.gradle</summary>

```gradle
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
</details>

<details>
  <summary>My unchanged MainActivity.kt</summary>

```kotlin
package com.gmail.dev.caiolouro.boi_na_balanca

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```
</details>

<details>
  <summary>pubspec.yaml</summary>

```yaml
name: boi_na_balanca
description: The project for the Boi na Balaça Android app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+5

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.2.0-dev.5
  firebase_auth: ^0.18.0+1
  # google_sign_in:


  # State and management packages
  flutter_modular:
  mobx:
  flutter_mobx:

  # Internationalization and formatting
  intl:
  date_format:
  currency_textfield:

  # Interface helpers
  admob_flutter: ^1.0.0-beta.5
  # flutter_auth_buttons:
  flutter_form_builder: ^3.13.0

  # Mock packages
  # cloud_firestore_mocks:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generated code
  build_runner: ^1.10.1
  mobx_codegen:
  modular_codegen:

  # Launcher helpers
  flutter_launcher_name:
  flutter_launcher_icons:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logos/logo2-transp.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_name:
  name: "Boi na Balança"

flutter_icons:
  ios: false
  android: true
  image_path: "assets/logos/logo2-circ.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/logos/logo2-transp.png"
```
</details>

I was trying to reproduce the error, but I couldn't, it doesn't show every time, so I'm not including the `flutter run -v` log, sorry. If I eventually can, I'll sent it.

Thanks for all the help.
