### ISSUE TITLE
[flutter_web] [google_sign_in] iOS error g.gaek is not a function

### ISSUE THREAD

**Issue by shashwatadi** [flutter/flutter#65375]
Getting this error on some client devices when trying to sign in with Google:

Device: iPad Mini
iOS version: 9.3.6

![Uploading WhatsApp Image 2020-09-07 at 5.01.40 PM.jpeg…]()

**Comment by pedromassangocode** [comment]
Hi @shashwatadi 
Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by shashwatadi** [comment]
Hi @pedromassangocode, unfortunately, I don't have any such device to test this on. 

```
pubspec.yaml

name: Kohbee
description: Live classes for CBSE, ICSE

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  firebase_auth: any
  google_sign_in: ^4.5.1
  http: ^0.12.1
  moor: ^3.1.0
  flare_flutter: ^2.0.1
  google_fonts: ^1.1.0
  curved_navigation_bar: ^0.3.3
  get_it: ^4.0.2
  intl: ^0.16.1
  xml: ^4.2.0
  crypto: ^2.1.5
  url_launcher: ^5.5.0
  stacked: ^1.7.4
  uuid: ^2.2.0
  universal_html: ^1.2.1
  oktoast: ^2.3.2
  platform_detect: ^1.4.0
  flutter_slidable: ^0.5.5
  flutter_launcher_icons: ^0.7.5
  flutter_custom_tabs: ^0.6.0
  dash_chat: ^1.1.14
  firebase: ^7.3.0
  cloud_firestore:
  image_picker: ^0.6.7+4
  timeago: ^2.0.26
  social_share: ^2.0.5
  grouped_list: ^3.3.0
  logger: ^0.6.0
  firebase_analytics: ^6.0.0
  flutter_spinkit: ^4.1.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.1.0
  build_runner: ^1.10.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/Icon-192.png"
  image_path_ios: "assets/icons/apple-icon.png"

flutter:

  uses-material-design: true

  assets:
      - assets/images/
```

```
flutter doctor -v

[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.13.6 17G13035, locale en-IN)
    • Flutter version 1.20.0 at /Users/shashwataditya/tools/flutter
    • Framework revision 916c3ac648 (5 weeks ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shashwataditya/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/shashwataditya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.7.5 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83
```
