### ISSUE TITLE
Lagging After Upload into TestFlight

### ISSUE THREAD

**Issue by congfandi** [flutter/flutter#65597]
Hi guys, i have some problem here... My app going well on development, after i upload into TestFlight my app so laggy, it's like the UI late to update... can someone tell me what should i do ?

i have been splitting the ui to micro compenent but nothing happen and my app still lagging.

thanks for help and here my flutter doctor

 **Flutter Doctor**
```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-ID)
    • Flutter version 1.20.3 at /Users/congfandi/development/flutter
    • Framework revision 216dee60c0 (9 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/congfandi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 4C97FEF2-E3C8-4A85-8B90-D5B4B5BF06F9
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!
```

@TahaTesser

**Comment by TahaTesser** [comment]
Hi @congfandi 

Can you please provide  `pubspec.yaml`, `flutter run --release --verbose` from the terminal and copy full logs into a plain text file (`.txt`) and attach it in the comment  and  [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

**Comment by congfandi** [comment]
> Hi @congfandi
> 
> Can you please provide `pubspec.yaml`, `flutter run --release --verbose` from the terminal and copy full logs into a plain text file (`.txt`) and attach it in the comment and [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> 
> Thank you

thank you,,

here my ```pubspec.yaml```

```
name: apps
description: KAHAGO App development by Flutter Concept

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+23

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+3
  http: ^0.12.0+4
  flutter_image_compress: ^0.6.5+1
  provider: ^4.0.4
  cached_network_image: ^2.0.0
  flutter_html: ^0.11.1
  sqflite: ^1.3.0
  path_provider: ^1.5.1
  autocomplete_textfield: ^1.7.3
  overlay_support: ^1.0.3
  google_maps_flutter: ^0.5.30
  geocoder: ^0.2.1
  location: ^3.0.2
  webview_flutter: ^0.3.22+1
  intl: ^0.16.1
  toast: ^0.1.5
  banner_view: ^1.1.2
  package_info: ^0.4.0+18
  open_appstore: ^1.0.2
  tutorial_coach_mark: ^0.3.0
  sentry: ^3.0.1
  device_info: ^0.4.2+4
  flutter_countdown_timer: ^1.0.0
  flutter_downloader: ^1.4.4
  barcode_widget: ^1.4.0
  url_launcher: ^5.5.0
  firebase_messaging: ^6.0.16
  connectivity: ^0.4.9
  keyboard_actions: ^3.3.0+1
  loadmore: ^1.0.4
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - locales/
    - assets/images/
    - assets/icons/
    - assets/onboarding/
    - assets/icons/profile/
    - assets/notif/
    - assets/navbar/active/
    - assets/navbar/deactive/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: KAHAGO
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.otf
        - asset: assets/fonts/SourceSansPro-Bold.otf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

[Terminal Saved Output.txt](https://github.com/flutter/flutter/files/5208163/Terminal.Saved.Output.txt)


FYI, this is not all pages got lag,, its just 1 page got laggy..
