### ISSUE TITLE
Flutter_assets/packages taking too much space in release build.

### ISSUE THREAD

**Issue by Kishan-Somaiya** [flutter/flutter#65611]
As you can see in the below image of ananlyze apk, Flutter_assets/packages is taking too much of storage, making my app total size 90mb. earlier it was 27mb. I think this issue occured after upgrading to Flutter 1.20.2, but i'm not sure.  Size of apk using split-per-abi is 75 mb. Size of debug-build is 301mb after installing. I don't know what's wrong here.

![image](https://user-images.githubusercontent.com/62096591/92883961-04d61280-f42f-11ea-812c-d09c364306b4.png)

<details><summary>my pubspec.yaml</summary>

```
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.8
  http: ^0.12.0+1
  fluttertoast: ^3.0.1
  modal_progress_hud: ^0.1.2
  cupertino_icons: ^0.1.2
  email_validator: '^1.0.0'
  json_annotation: ^2.4.0
  connectivity: ^0.4.9
  flutter_socket_io: ^0.6.0
  adhara_socket_io: ^0.4.1
  file_picker: ^1.3.8
  http_parser: ^3.1.3
  # video_player: ^0.5.1
  video_player: ^0.10.1+6
  # video_player: ^0.10.12+2
  flutter_gallery: ^2.4.0+20400
  native_video_view: ^0.2.1
  flutter_staggered_grid_view: "^0.3.0"
  chewie: ^0.9.10
  # camera: ^0.5.7+4
  camera: ^0.5.8+5
  path_provider: ^1.2.0
  intl: ^0.16.1
  # country_code_picker: ^1.1.7
  pushy_flutter: 1.0.14
  autocomplete_textfield: ^1.7.3
  dio: ^3.0.2
  emoji_picker: ^0.1.0
  grouped_buttons: ^1.0.4
  auto_size_text: ^2.1.0
  percent_indicator: 2.1.1+1
  flutter_tags: "^0.4.8"
  sleek_circular_slider: ^1.1.0
  flutter_share_me: ^0.9.1  
  country_code_picker: ^1.3.7
  image_picker: ^0.6.4
  flutter_facebook_login: ^3.0.0
  # video_player:
  #     git:
  #       url: git://github.com/flutter/plugins.git
  #       path: packages/video_player
  flutter_twitter_login:
    git: git://github.com/eudangeld/flutter_twitter_login.git
  google_sign_in: ^4.4.1
  firebase_auth: ^0.16.0
  flappy_search_bar: ^1.7.2
  flutter_typeahead: ^1.8.1
  cached_network_image: ^2.2.0+1

 dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  flutter_launcher_icons: "^0.7.2"
  flutter_svg: ^0.18.1
# dependency_overrides:
#   chewie: ^0.9.10
#   video_player: ^0.6.0
#   custom_chewie: ^0.7.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/"
```
</details>
