### ISSUE TITLE
Flutter keeps getting stuck in "Syncing files to device" when installing app on a real iOS Device. 

### ISSUE THREAD

**Issue by real1900** [flutter/flutter#65746]
I see : 

**Running Xcode build...
Xcode build done.                                           426.0s
Installing and launching...
Waiting for Suleman’s iPhone  to report its views...
Debug service listening on ws://localhost:59585/ws
Syncing files to device Suleman’s iPhone ...**

Flutter doctor shows: 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.5 19F101, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.2)
[✓] Connected device (4 available)
    ! Error: Suleman’s iPhone 6s is not connected. Xcode will continue when Suleman’s iPhone 6s is connected. (code -13)

• No issues found!

**Comment by ykrank** [comment]
this bug make my app could not debug in ios

**Comment by pedromassangocode** [comment]
Hi @real1900 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by lvlrSajjad** [comment]
I have this problem too
This is my flutter doctor:
```
 flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.3 at /Users/lvlrx/development/flutter
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lvlrx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Sajjad Asadi’s iPhone (mobile) • cd1ab62b9ce2e34bb73637391f9e97b36cf2ce2c • ios • iOS 13.6

• No issues found!
lxvr.xaus@Sajjads-MacBook-Pro pmx_flutter_v2 % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.3 at /Users/lvlrx/development/flutter
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lvlrx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Sajjad Asadi’s iPhone (mobile) • cd1ab62b9ce2e34bb73637391f9e97b36cf2ce2c • ios • iOS 13.6

• No issues found!
```
This is my pubspec.yaml
```
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.3+200113

environment:
  sdk: ">=2.2.2 <3.0.0"
#  flutter: ^1.17.0

dependencies:
  flutter:
    sdk: flutter
  inject:
    path: ./injection/inject.dart/package/inject
  apple_sign_in: 0.1.0
  audioplayers: 0.16.1
  cached_network_image: 2.3.2+1
  #  carousel_slider: 1.4.1
  cloud_firestore: 0.14.0+2
  cloud_functions: 0.6.0
  connectivity: 0.4.9+2
  country_pickers: 1.3.0
  cupertino_icons: 1.0.0
  device_id: 0.2.0
  device_info: 0.4.2+7
  firebase_ml_vision: 0.9.6+2
  #  firebase_admob: 0.9.3+4
  firebase_analytics: 6.0.0
  firebase_auth: 0.18.0+1
  firebase_core: 0.5.0
  firebase_crashlytics: 0.1.4+1
  firebase_messaging: 7.0.0
  firebase_performance: 0.4.0
  firebase_remote_config: 0.4.0
  firebase_storage: 4.0.0
  flare_flutter: 2.0.6
  flash: 1.3.1
  flutter_cache_manager: 1.4.2
  flutter_facebook_login: 3.0.0
  #  flutter_ip: 0.2.0
  flutter_native_splash: 0.1.9
  flutter_secure_storage: 3.3.3
  flutter_slidable: 0.5.7
  #  flutter_svg: 0.17.4
  font_awesome_flutter: 8.8.1
  geocoder: 0.2.1
  geohash: 0.2.1
  geolocator: 6.0.0+4
  geocoding: 1.0.3
  google_sign_in: 4.5.3
  googleapis: 0.55.0
  http: 0.12.2
  image_cropper: 1.3.1 # Don't upgrade this plugin to 1.3.0 because it has a pod problem
  image_downloader: 0.20.0
  image_picker: 0.6.7+7
  #  in_app_purchase: ^0.3.4+1
  intl: 0.16.1
  #  json_serializable: 3.1.0
  local_auth: 0.6.3+1
  location: 3.0.2
  location_permissions: 3.0.0+1
  material_design_icons_flutter: 3.4.5045+1 # For now, it is better to stick with this version because It seems new version changed icon names - - 7 may 2020
  package_info: 0.4.3
  path: 1.7.0
  path_provider: 1.6.14
  permission_handler: 5.0.1+1
  photo_view: 0.10.2
  reorderables: 0.3.2
  rxdart: 0.24.1
  sembast: 2.4.7+6
  share: 0.6.5
  shared_preferences: 0.5.10
  store_redirect: 1.0.2
  transparent_image: 1.0.0
  url_launcher: 5.5.3
  vibration: 1.4.0
  smooth_page_indicator: 0.2.0
  flutter_app_badger: 1.1.2
  rate_my_app: 0.7.1+1
  agora_rtc_engine: 3.0.1-dev.7
  carousel_slider: 2.2.1
  auto_animated: 2.1.0
  circular_countdown_timer: 0.0.6
  #  flutter_inapp_purchase: 2.2.0
  purchases_flutter: 1.2.1
  sembast_cloud_firestore_type_adapters:
    git:
      url: git://github.com/tekartik/sembast_flutter_more.dart
      path: cloud_firestore_type_adapters
      ref: dart2
    version: '>=0.1.0'
#  flutter_voip_push_notification: 0.0.3
#  flutter_call_kit: 0.0.2
#  flutter_callkit_voximplant: 1.1.0+2
#  algolia: 0.1.7
#  clipboard_manager: ^0.0.4
#  flutter_google_places: 0.2.3
#  flutter_twitter_login: 1.1.0
#  geoflutterfire: 2.0.3+8
#  toast: 0.1.5
#  video_player: 0.10.5
#dependency_overrides:
#  firebase_core: 0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
#  build_runner: 1.10.0
  inject_generator:
    path: ./injection/inject.dart/package/inject_generator
#  cloud_firestore_mocks: 0.4.1
#  firebase_storage_mocks: 0.1.0
#  google_sign_in_mocks: 0.1.0+2
#  firebase_auth_mocks: 0.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/countries.json
    - assets/no_profile_picture.png
    - assets/notification.mp3
    - assets/soft_notification.mp3
    - assets/matched.mp3
    - assets/message.mp3

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
