### ISSUE TITLE
Video_player displays black screen on iOS

### ISSUE THREAD

**Issue by Colir** [flutter/flutter#65853]
Hello.
I've black screen when launching video_player on iOS 13.7 on iphone 7 (real device) with mp4 video (network url).
Video is loading but can't be played (no sound also).

Hope i'm giving enought information.

Thank you

video_player: ^0.10.12+2

`[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G73, locale fr-FR)
    • Flutter version 1.20.3 at /Users/Colir/Documents/Flutter/flutter
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Colir/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Mi A3 (mobile)           • e8c856892b1e                             • android-arm64 • Android 10 (API 29)
    • iPhone de Colir (mobile) • 1d690c3bad00d174027e92c78734d2dbe5ed91fe • ios           • iOS 13.7

• No issues found!`

**Comment by TahaTesser** [comment]
Hi @Colir 
Can you please provide`flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) with sample image URL 
Thank you

**Comment by Colir** [comment]
@TahaTesser  yep i'will do that before the week ends.

**Comment by Colir** [comment]
Hello @TahaTesser . i'm late , sorry for that i'have less time than i thought. I bring you some thing as soon as i can

**Comment by Colir** [comment]
@TahaTesser...please forgive me...
After multiple test, the problem is not really the on i thought. 

1/ First, the issue is not "video_player display black screen on ios", but "video_player won't read video on ios"
2/ Secondly, the core of the problem is an issue between video_player and Chewie player's overlay (https://github.com/brianegan/chewie)

When we use this code

```
    void initState() {
      super.initState();
      _controller = VideoPlayerController.network(_url)
        ..initialize().then((_) {
          setState(() {
            _stackViewIndex = 0;
            _controller.play();
          });
        });


      _chewieController = ChewieController(
        videoPlayerController: _controller,
        aspectRatio: 16.0 / 9.0,
        allowedScreenSleep: false,
        autoPlay: true,
        autoInitialize : true,
        allowFullScreen : true,
        looping: true,
      );
    }
```

Video is not working (video_player just show the first frame of the video, but can't play it)
**However, this code work with video_player 0.9.0**

But if we remove this part 
```
    ..initialize().then((_) {
        setState(() {
          _stackViewIndex = 0;
          _controller.play();
        });
      });
```


All work great.


I'm a little bit confuse, as the first code work with a lower version of video_player....

Anyway thanks for your time.
Apologize me for this wrong issue creation.

If you have any suggestion on how to solve this...

Thanks again

**Comment by TahaTesser** [comment]
Hi @Colir 
To better address, the issue, can you please a complete reproducible minimal code sample.
If it doesn't reproduce with a lower version of `video_player`, it might be an issue
Thank you

**Comment by Colir** [comment]
Hi @TahaTesser ,
here is my complete reproducible minimal code sample.

This sample show the bug under ios.
Juste change video_player to version 0.9 in pubspec.yaml to get it work

Thansk you

pubspec.yaml

```
 name: videoplayer
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  video_player: ^0.10.12+2
  chewie: ^0.9.10

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #
  assets:
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

main.dart

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';
import 'package:chewie/chewie.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return  MaterialApp(
          title: 'Video_player Test',
          home: VideoPlayerApp('https://www.sample-videos.com/video312/mp4/480/big_buck_bunny_480p_30mb.mp4','test'),
        );
  }
}


class VideoPlayerApp extends StatefulWidget {
  final url, fileName;

  VideoPlayerApp(this.url,  this.fileName);

  @override
  _VideoPlayerApp createState() => _VideoPlayerApp(this.url, this.fileName);
}

class _VideoPlayerApp extends State<VideoPlayerApp> {
  var _url, _fileName;
  VideoPlayerController _controller;
  ChewieController _chewieController;

  bool startedPlaying = false;
  num _stackViewIndex = 1;

  _VideoPlayerApp(this._url, this._fileName);


  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(_url)
    // this is the evil part : issue between chewie & video_player
      ..initialize().then((_) {
        setState(() {
          _stackViewIndex = 0;
          _controller.play();
        });
      });
    //

    _chewieController = ChewieController(
      videoPlayerController: _controller,
      aspectRatio: 16.0 / 9.0,
      allowedScreenSleep: false,
      autoPlay: true,
      autoInitialize : true,
      allowFullScreen : true,
      looping: true,
    );
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(_fileName),
      ),
      body:  IndexedStack(
          index: _stackViewIndex,
          children :[
            Container (
              color: Colors.black,
              child : Center(
                  child:AspectRatio(
                    aspectRatio: _controller.value.aspectRatio,
                    child: Stack(
                      alignment: Alignment.bottomCenter,
                      children: <Widget>[
                        VideoPlayer(_controller),
                        VideoProgressIndicator(_controller, allowScrubbing: true),
                      ],
                    ),
                  )
              ),
            ),
            Container (
                child : SafeArea(
                  child : Container(
                      child: Center(
                          child: CircularProgressIndicator()
                      )
                  ),
                )
            ),
          ]
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _controller.value.isPlaying
                ? _controller.pause()
                : _controller.play();
          });
        },
        child: Icon(
          _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
        ),
      ),
    );
  }


  @override
  void dispose() {
    _controller.dispose();
    _chewieController.dispose();
    super.dispose();
  }

}

```
