### ISSUE TITLE
Custom fonts - Dealing with multiple versions of the same fonts

### ISSUE THREAD

**Issue by nelsonkam** [flutter/flutter#6607]
I'm trying to apply a custom font to my app but I ran into a bug (I'm not sure I can call it a bug though :smirk: ). So this is the issue, adding these two code snippets (separately) results into two different renderings.

```
fonts:
  - family: Rubik
    fonts:
      - asset: assets/fonts/Rubik-Black.ttf
      - asset: assets/fonts/Rubik-Medium.ttf
      - asset: assets/fonts/Rubik-Regular.ttf
```

Renders this:

![images_n76ykujg5vsb6v2gzbcejy1psct2_1477951914510screenshot_2016-10-31-23-11-35](https://cloud.githubusercontent.com/assets/8492909/19873630/69be3596-9fc0-11e6-8ecd-2325be5dcc27.png)
```
fonts:
  - family: Rubik
    fonts:
      - asset: assets/fonts/Rubik-Regular.ttf
      - asset: assets/fonts/Rubik-Medium.ttf
      - asset: assets/fonts/Rubik-Black.ttf
```
Renders this:

![images_n76ykujg5vsb6v2gzbcejy1psct2_1477952404355screenshot_2016-10-31-23-19-55](https://cloud.githubusercontent.com/assets/8492909/19873688/c0fe3d88-9fc0-11e6-98ec-bff5d9192864.png)

It seems that the order of the assets matters or that the `fonts` mapping only considers the first asset. Anyway this is a strange behavior.

## Flutter Version
Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision b41645cc17 (3 days ago) • 2016-10-28 14:37:17
Engine • revision 1bc79ded38
Tools • Dart 1.21.0-dev.2.0

**Comment by eseidelGoogle** [comment]
@jason-simmons may have context, I think he wired up custom fonts originally.

**Comment by jason-simmons** [comment]
Each asset for a font family in flutter.yaml should be marked with the font's attributes, e.g.:

```
fonts:
  - family: Foo
    fonts:
      - asset: Foo-Regular.ttf
      - asset: Foo-Medium.ttf
        weight: 500
      - asset: Foo-Black.ttf
        weight: 900
```

The Flutter engine will use these attributes to select the font that most closely matches a given text style.

The packages/flutter_tools/schema directory in the Flutter repository defines the schema for flutter.yaml.

I saw that the Gallery example is just listing the three variants of its custom font with no attributes.  I don't think that's right.
