### ISSUE TITLE
Spanish date picker input's placeholder is wrong

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#66227]
https://github.com/flutter/flutter/blob/51fa704642774c6b6ae64c91642b62801e233e1b/packages/flutter_localizations/lib/src/l10n/material_es.arb#L58

This line should be `dd/mm/aaaa`. If you select a date, it shows it in the correct format (dd/mm/aaaa), but placeholder has a wrong format.

```
Flutter 1.22.0-10.0.pre.269 • channel master • https://github.com/flutter/flutter.git
Framework • revision 51fa704642 (25 hours ago) • 2020-09-19 11:27:04 -0700
Engine • revision 4b8477d115
Tools • Dart 2.10.0 (build 2.10.0-142.0.dev)
```

**Comment by pedromassangocode** [comment]
Reproducible on latest `master` channel.

Leaving this for reference: https://en.wikipedia.org/wiki/Date_and_time_notation_in_Spain

**Comment by TheBiirb** [comment]
Can we have a sample code for this? Thanks!

**Comment by Zazo032** [comment]
> Can we have a sample code for this? Thanks!

Sample code:

<details>
<summary>pubspec.yaml</summary>

```yaml
name: sample
description: Sample Flutter application.
version: 1.0.0+1

environment:
  flutter: ^1.22.0
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
```
</details>

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(SampleApp());

class SampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeRoute(),
      locale: Locale('es'),
      localizationsDelegates: GlobalMaterialLocalizations.delegates,
    );
  }
}

class HomeRoute extends StatelessWidget {
  const HomeRoute();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.calendar_today),
        onPressed: () {
          showDatePicker(
            context: context,
            initialDate: DateTime.now(),
            firstDate: DateTime(2020, 1, 1),
            lastDate: DateTime(2020, 12, 31),
            initialEntryMode: DatePickerEntryMode.input,
          );
        },
      ),
    );
  }
}
```
</details>
