### ISSUE TITLE
Flutter couldn't start the installed app: couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by abdulmuaz97** [flutter/flutter#66263]
I found lots of issues like this but no suitable solution worked fine. So I decided to open a new one and hopefully I can get a solution for this issue.
I'm gonna present everything you may need to know

### The Console Log (after successful build)

```
[  +45 ms] Installing build\app\outputs\flutter-apk\app.apk...
[   +2 ms] executing: C:\AndroidSDK\platform-tools\adb.exe -s 9WV4C18522003027 install -t -r E:\System\Projects\FLUTTER\Flutter Projects\Tests\omniaty_app\build\app\outputs\flutter-apk\app.apk
[+65977 ms] Performing Streamed Install
                     Success
[   +3 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 66.0s)
[  +45 ms] executing: C:\AndroidSDK\platform-tools\adb.exe -s 9WV4C18522003027 shell echo -n 2f8278d32cab1229441e409e17c949db99acbd7d > /data/local/tmp/sky.com.example.omniaty_app.sha1
[ +135 ms] ANE LX1 startApp
[   +5 ms] executing: C:\AndroidSDK\platform-tools\adb.exe -s 9WV4C18522003027 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true--ez enable-checked-mode true --ez verify-entry-points true com.example.omniaty_app/com.example.omniaty_app.MainActivity
[ +229 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.omniaty_app/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[ +944 ms] E/FlutterLoader( 6102): Flutter initialization failed.
[   +8 ms] E/FlutterLoader( 6102): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file
"/data/app/com.example.omniaty_app-AY58JNYP1dGZHy5ookVKDQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.omniaty_app-AY58JNYP1dGZHy5ookVKDQ==/lib/arm64, /system/lib64, /product/lib64]]] couldn'tfind "libflutter.so"
[  +96 ms] E/FlutterLoader( 6102):      at java.util.concurrent.FutureTask.report(FutureTask.java:123)
[   +2 ms] E/FlutterLoader( 6102):      at java.util.concurrent.FutureTask.get(FutureTask.java:193)
[   +2 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:193)
[   +6 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:284)
[   +3 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:190)
[  +29 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:233)
[  +33 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:153)
[   +4 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:411)
[  +29 ms] E/FlutterLoader( 6102):      at android.app.Activity.performCreate(Activity.java:7458)
[  +33 ms] E/FlutterLoader( 6102):      at android.app.Activity.performCreate(Activity.java:7448)
[  +33 ms] E/FlutterLoader( 6102):      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
[  +31 ms] E/FlutterLoader( 6102):      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
[   +4 ms] E/FlutterLoader( 6102):      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
[   +3 ms] executing: C:\AndroidSDK\platform-tools\adb.exe version
[  +64 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as C:\AndroidSDK\platform-tools\adb.exe
[   +6 ms] executing: C:\AndroidSDK\platform-tools\adb.exe start-server
[  +45 ms] Installing build\app\outputs\flutter-apk\app.apk...
[   +2 ms] executing: C:\AndroidSDK\platform-tools\adb.exe -s 9WV4C18522003027 install -t -r E:\System\Projects\FLUTTER\Flutter Projects\Tests\omniaty_app\build\app\outputs\flutter-apk\app.apk
[+65977 ms] Performing Streamed Install
                     Success
[   +3 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 66.0s)
[  +45 ms] executing: C:\AndroidSDK\platform-tools\adb.exe -s 9WV4C18522003027 shell echo -n 2f8278d32cab1229441e409e17c949db99acbd7d > /data/local/tmp/sky.com.example.omniaty_app.sha1
[ +135 ms] ANE LX1 startApp
[   +5 ms] executing: C:\AndroidSDK\platform-tools\adb.exe -s 9WV4C18522003027 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true--ez enable-checked-mode true --ez verify-entry-points true com.example.omniaty_app/com.example.omniaty_app.MainActivity
[ +229 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.omniaty_app/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[ +944 ms] E/FlutterLoader( 6102): Flutter initialization failed.
[   +8 ms] E/FlutterLoader( 6102): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file
"/data/app/com.example.omniaty_app-AY58JNYP1dGZHy5ookVKDQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.omniaty_app-AY58JNYP1dGZHy5ookVKDQ==/lib/arm64, /system/lib64, /product/lib64]]] couldn'tfind "libflutter.so"
[  +96 ms] E/FlutterLoader( 6102):      at java.util.concurrent.FutureTask.report(FutureTask.java:123)
[   +2 ms] E/FlutterLoader( 6102):      at java.util.concurrent.FutureTask.get(FutureTask.java:193)
[   +2 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:193)
[   +6 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:284)
[   +3 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:190)
[  +29 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:233)
[  +33 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:153)
[   +4 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:411)
[  +29 ms] E/FlutterLoader( 6102):      at android.app.Activity.performCreate(Activity.java:7458)
[  +33 ms] E/FlutterLoader( 6102):      at android.app.Activity.performCreate(Activity.java:7448)
[  +33 ms] E/FlutterLoader( 6102):      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
[  +31 ms] E/FlutterLoader( 6102):      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
[   +4 ms] E/FlutterLoader( 6102):      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
[  +27 ms] E/FlutterLoader( 6102):      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
[   +7 ms] E/FlutterLoader( 6102):      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[  +28 ms] E/FlutterLoader( 6102):      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[  +35 ms] E/FlutterLoader( 6102):      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
[   +4 ms] E/FlutterLoader( 6102):      at android.os.Handler.dispatchMessage(Handler.java:112)
[   +2 ms] E/FlutterLoader( 6102):      at android.os.Looper.loop(Looper.java:216)
[   +4 ms] E/FlutterLoader( 6102):      at android.app.ActivityThread.main(ActivityThread.java:7625)
[   +3 ms] E/FlutterLoader( 6102):      at java.lang.reflect.Method.invoke(Native Method)
[   +1 ms] E/FlutterLoader( 6102):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
[   +2 ms] E/FlutterLoader( 6102):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
[  +30 ms] E/FlutterLoader( 6102): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file
"/data/app/com.example.omniaty_app-AY58JNYP1dGZHy5ookVKDQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.omniaty_app-AY58JNYP1dGZHy5ookVKDQ==/lib/arm64, /system/lib64, /product/lib64]]] couldn'tfind "libflutter.so"
[  +38 ms] E/FlutterLoader( 6102):      at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
[   +8 ms] E/FlutterLoader( 6102):      at java.lang.System.loadLibrary(System.java:1672)
[   +2 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:145)
[   +1 ms] E/FlutterLoader( 6102):      at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:140)
[  +33 ms] E/FlutterLoader( 6102):      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[  +36 ms] E/FlutterLoader( 6102):      at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
[   +5 ms] E/FlutterLoader( 6102):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
[   +3 ms] E/FlutterLoader( 6102):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[   +5 ms] E/FlutterLoader( 6102):      at java.lang.Thread.run(Thread.java:784)

```

### The (pubspec.yaml) file
```yaml
name: omniaty_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  
  dio: ^3.0.10
  get_it: ^4.0.4
  flutter_bloc: ^6.0.4
  shared_preferences: ^0.5.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


```

### Flutter doctor -v
```
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (6 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\AndroidSDK
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\AbdulMuaz Aqeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[√] Connected device (1 available)
    • ANE LX1 (mobile) • 9WV4C18522003027 • android-arm64 • Android 9 (API 28)

• No issues found!
```

### The (main.dart) sample of my code
```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:get_it/get_it.dart';
import 'package:shared_preferences/shared_preferences.dart';
// app imports
import 'src/Utils/utils.dart';
import 'src/Routes/app_routes.dart';
import 'src/Themes/app_themes.dart';
import 'src/Blocs/bloc_providers.dart';
import 'src/Utils/service_locator.dart';
import 'src/Blocs/Locale_Cubit/locale_cubit.dart';
import 'src/Localization/app_localizations_setup.dart';

void main() {
  // ServiceLocator.init();
  runApp(MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // final locator = GetIt.I.get<SharedPreferences>();
    // locator.setString('msg', 'Hello, World!');
    // print(locator.getString('msg'));

    return MultiBlocProvider(
      providers: BlocProviders.providers,
      child: BlocBuilder<LocaleCubit, LocaleState>(
        buildWhen: (previous, current) => previous.locale.languageCode != current.locale.languageCode,
        builder: (_, localeState) => MaterialApp(
          // app localization
          locale: localeState.locale,
          supportedLocales: AppLocalizationsSetup.supportedLocales,
          localizationsDelegates: AppLocalizationsSetup.localizationsDelegates,
          localeResolutionCallback: AppLocalizationsSetup.localeResolutionCallback,
          title: Utils.appName,
          // app themes
          theme: AppThemes.lightTheme,
          // app routes
          onGenerateRoute: AppRoutes.onGenerateRoutes,
          onUnknownRoute: AppRoutes.onUnknownRoute,
        ),
      ),
    );
  }
}

```

Hope you can find a suitable solution for this issue.
