### ISSUE TITLE
App Crash while using writeAsBytes to write pdf to it.

### ISSUE THREAD

**Issue by anandsubbu007** [flutter/flutter#66421]
It is working fine in debug mode.
but crash in a release.

I'm facing this problem now. I'm using Flutter master branch. 2 months ago it is working fine in release mode. 
I also tried 
```
flutter run --no-shrink
```
and also tried after flutter clean
```      Directory documentDirectory = await getTemporaryDirectory();
      String documentPath = documentDirectory.path;
      filepath = "$documentPath/doc.pdf";
      File file = File(filepath);
      await file.writeAsBytes(pdf.save());
      _pdfdoc = await PDFDocument.fromFile(file);
```
nothing works. I'm facing this issue in release mode only.
app crash at --> file.writeAsBytes(pdf.save());

**Comment by darshankawar** [comment]
Hi @anandsubbu007,
Please provide `flutter doctor -v` , `pubspec.yaml`, crash log and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by anandsubbu007** [comment]
May I know how to get crash log in release mode?

**Comment by anandsubbu007** [comment]
```
[√] Flutter (Channel dev, 1.22.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
    • Flutter version 1.22.0-1.0.pre at C:\Flutter Components\Flutter
    • Framework revision ce40de69b7 (5 weeks ago), 2020-08-20 07:31:50 -0700
    • Engine revision 81027ab0cc
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\anand\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\anand\AppData\Local\Android\Sdk
    • Java binary at: C:\Flutter Components\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Flutter Components\Android Studio
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\anand\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.51
```

**Comment by anandsubbu007** [comment]
```
version: 1.0.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  provider: ^4.0.5+1
  getflutter: ^1.0.11
  csv: ^4.0.3
  file_picker: ^1.9.0+1
  path_provider: ^1.6.8
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.11+1
  sqflite: ^1.3.0+1
  image_picker: ^0.6.0+9
  ext_storage: ^1.0.3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  google_sign_in: ^4.4.6
  permission_handler: ^5.0.0+hotfix.6
  pdf: ^1.11.2
  multiselectchipgroup: ^0.1.3
  grouped_checkbox: ^1.0.0
  flutter_xlider: ^3.4.0
  flutter_typeahead: ^1.8.3
  carousel_pro: ^1.0.0
  flutter_secure_storage: ^3.3.3
  flutter_plugin_pdf_viewer: ^1.0.7
  open_file: ^3.0.1
  upi_india: ^2.1.2
  flutter_email_sender: ^3.0.1
  wc_flutter_share: ^0.2.2
  flutter_downloader: ^1.4.4
  connectivity: ^0.4.8+6
  image_cropper: ^1.2.3
  in_app_review: ^0.2.0+4
  rate_my_app: ^0.7.2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/
    - assets/Open_Sans/

```
