### ISSUE TITLE
Shared Preferences does not work for android although it is working for iOS

### ISSUE THREAD

**Issue by FaheemuddinKhan** [flutter/flutter#66442]
I have shared preferences installed and working fine in the app for iOS. But the same app has issues persisting data running on android.

shared_preferences 0.5.12

<details><summary>pubspec.yaml</summary>

```
name: timetracker
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.3+4
  camera: ^0.5.8+6
  flutter_map: ^0.8.2
  user_location: any
  provider: ^4.3.2+2
  tuple: ^1.0.3
  date_utils: any
  sqflite: ^1.3.1+1
  postgres: ^2.2.0
  flutter_simple_dependency_injection: ^1.0.3
  load: ^0.1.6
  shared_preferences: ^0.5.12
  get_it: ^5.0.0
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNextCyr-UltraLight.ttf
          weight: 100
        - asset: assets/fonts/AvenirNextCyr-Regular.ttf
          weight: 400
        - asset: assets/fonts/AvenirNextCyr-Demi.ttf
          weight: 500
        - asset: assets/fonts/AvenirNextCyr-Medium.ttf
          weight: 600
        - asset: assets/fonts/AvenirNextCyr-Bold.ttf
          weight: 700

        
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
</details>

<details><summary>code</summary>

```dart
Future<void> main()  async {
    // WidgetsFlutterBinding.ensureInitialized();
    // SystemChrome.setEnabledSystemUIOverlays([]);
    // SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
    WidgetsFlutterBinding.ensureInitialized();
    await setupLocator();
    var sharedPrefService = locator.get<SharedPreferences>();
    sharedPrefService.reload();
    print(sharedPrefService.getKeys());
    print(sharedPrefService.getBool("remember_me"));

    if(sharedPrefService.getBool("remember_me") == false){ 
      sharedPrefService.clear();
    }
    await Injection.initInjection();
    List<CameraDescription> cameras = [];
  //  Obtain a list of the available cameras on the device.
  var firstCamera;
    try {
      cameras = await availableCameras();
      firstCamera = cameras.first;
    } on CameraException catch (e) {
      print(e);
      print("Error occured in camera exception");
    }
    // Get a specific camera from the list of available cameras.
    
    runApp(MyApp());
 
}

class MyApp extends StatelessWidget {

  var sharedPrefService = locator.get<SharedPreferences>();
  @override
  Widget build(BuildContext context) {
    print(sharedPrefService.getBool("remember_me"));
     return MultiProvider(
       providers: [
        ChangeNotifierProvider.value(
          value: AuthenticationProvider(),
        ),
      ],
            child: new MaterialApp(
        onGenerateRoute: RouteGenerator.generateRoute,
        initialRoute: (sharedPrefService.getBool("remember_me") == true) ? homeRoute : introductionRoute,
    ),
     ); 
  }
}


import 'package:get_it/get_it.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:timetracker/core/services/shared_prefs.dart';


final locator = GetIt.instance;



Future setupLocator() async {
  var instance = await SharedPreferences.getInstance();
  locator.registerSingleton<SharedPreferences>(instance);
}
```
</details>

<details><summary>flutter doctor -v</summary>
```
[✓] Flutter (Channel dev, 1.23.0-4.0.pre, on Mac OS X 10.15.2 19C57 x86_64, locale en-SA)
    • Flutter version 1.23.0-4.0.pre at /Users/faheemuddinkhan/Development/flutter
    • Framework revision 83dd176777 (17 hours ago), 2020-09-22 12:04:44 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/faheemuddinkhan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```
</details>
