### ISSUE TITLE
flutter web The Method 'BlocProvider' isn't defined for the type<StateClassFromStatefulWidget>

### ISSUE THREAD

**Issue by wlnoor** [flutter/flutter#66689]
Hay, i found some error in my aplication (Flutter Web), when i was create some BlocProvider or BlocListener Widgets in my view and i found this message (error) : 

![image](https://user-images.githubusercontent.com/28283735/94319908-da9b5d80-ffb5-11ea-812f-fbae891b100f.png)

i think this is error not from the package bloc, so i am ask here to find any solution, 

this my code : 
```
class HeaderHomeScreen extends StatefulWidget {
    @override
    _HeaderHomeScreenState createState() => _HeaderHomeScreenState();
}

class _HeaderHomeScreenState extends State<HeaderHomeScreen> {
    BalanceBloc balanceBloc;
    BalanceRepository balanceRepository;

    @override
    void initState() {
        super.initState();
        initRepository();
        initBloc();
    }

    void initRepository() {
        balanceRepository = new BalanceRepository();
    }

    void initBloc() {
        balanceBloc = new BalanceBloc(
            balanceRepository
        );
    }

    @override
    Widget build(BuildContext context) {
        balanceBloc.add(BalanceFetching());
        return BlocProvider(
            create: (context) {
                return this.balanceBloc;
            },
            child: BlocListener<BalanceBloc, BalanceState> (
                bloc: this.balanceBloc,
                listener: (BuildContext context, BalanceState state) {
                    if (state is BalanceFetchError) {
                        Scaffold.of(context).showSnackBar(
                            SnackBar(
                                content: Text('${state.error}'),
                                backgroundColor: Colors.red,
                            ),
                        );
                    }
                },
                child: BlocBuilder<BalanceBloc, BalanceState>(
                    bloc: this.balanceBloc,
                    builder: (BuildContext context, BalanceState state) {
                        if (state is BalanceFetchLoading) {
                            return buildCardHeader();
                        }

                        if (state is BalanceFetchSuccess) {
                            return buildCardHeader(balance: state.balance);
                        }
                    }
                )
            ),
        );
    }
}
```

this is my pubspec.yaml : 
```
dependencies:
  flutter_web: any
  http: ^0.12.2
  equatable: ^1.2.0
  bloc: ^6.0.3
  crypto: ^2.1.5
  dio: ^3.0.9

dev_dependencies:
  flutter_web_test: any
  build_runner: any
  build_web_compilers: any
  test: ^1.3.4

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
```

flutter version : 
```
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (11 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

flutter doctor : 
```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.49.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
