### ISSUE TITLE
I am getting HTTP 400 Error code, when connecting to the api

### ISSUE THREAD

**Issue by ameer227** [flutter/flutter#66716]
Hi Team,

I have developed .NET Core 3.1 API and published in the server. It is working fine in POSTMAN.

Here are my API Links
http://ameer2003-001-site1.atempurl.com/api/Exam/GetQuestionPaper

Request Body:
{
    "examID": "NEET",
    "questionPaperNo": "2",
    "userID": "Basha"
}

This api is working fine for me in POSTMAN, but when I created flutter app, using http package, when I call the get method. I get 400 HTTP Status Code. 
Could any one provide me the sample flutter app, connecting above API, which is in working.

Thanks for your support in advance.
![API_Working](https://user-images.githubusercontent.com/71919086/94332344-0c321a00-fff2-11ea-855c-4e0a66e4f3d2.PNG)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by hamdikahloun** [comment]
Hi @ameer227 

Please add internet permission to `yourApp\android\app\src\main\AndroidManifest.xml` : 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.request">
   <uses-permission android:name="android.permission.INTERNET" />
   <application
     .....................
     .....................
    </application>
</manifest>
```
<details>
  <summary>main.dart</summary>


```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

getQuestionPaper() async {
  final http.Response response = await http.post(
    'http://ameer2003-001-site1.atempurl.com/api/Exam/GetQuestionPaper',
    headers: <String, String>{
      'Content-Type': 'application/json; charset=UTF-8',
    },
    body: jsonEncode(<String, String>{
      "examID": "NEET",
      "questionPaperNo": "2",
      "userID": "Basha"
    }),
  );

  if (response.statusCode == 200) {
    print(response.body);
  } else {
    throw Exception('Failed to get question paper.');
  }
}

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() {
    return _MyAppState();
  }
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Question Paper'),
        ),
        body: Container(
          child: RaisedButton(
            child: Text('Get Question Paper'),
            onPressed: () {
              getQuestionPaper();
            },
          ),
        ),
      ),
    );
  }
}

```


</details>

<details>
  <summary>pubspec.yaml</summary>



```
name: yourApp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```


</details>
