### ISSUE TITLE
Semantic Labels for TextSpans with GestureRecognizer do not show up if there are additional TextSpans attached after it

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#66861]
b/169155017

One of the g3 teams have built their own html widget generator which works by emitting several `TextSpan` objects. When one of those objects have a GestureRecognizer (for links), it gets dropped if the text span that comes after it is long enough to not fit into the same row.

```
TextSpan:
   TextSpan:
     "Before link. "
   TextSpan:
     inherit: true
     color: Color(0xff1a73e8)
     semanticsLabel: ""
     TextSpan:
       "This is a link"
       recognizer: TapGestureRecognizer
   TextSpan:
     "After Link, there is some long text that does not fit to a single line."
```

See internal bug for reproduction.
