### ISSUE TITLE
Error when add 'firebase_messaging' in pubspec.yaml

### ISSUE THREAD

**Issue by paivalucas** [flutter/flutter#67026]
Hi. I'm trying to add 'firebase_messaging' in my pubspec.yaml but when I do 'flutter pub get' it returns the following error:
```
Running "flutter pub get" in app...                             
Because cloud_firestore_web >=0.2.0+1 depends on cloud_firestore_platform_interface >=2.0.1 <2.1.0 and cloud_firestore >=0.14.1 depends on cloud_firestore_platform_interface ^2.1.0, cloud_firestore_web >=0.2.0+1 is incompatible with cloud_firestore >=0.14.1.

So, because SOLID_pagow_app depends on cloud_firestore ^0.14.1 which depends on cloud_firestore_web ^0.2.0+1, version solving failed.
pub get failed (1; So, because SOLID_pagow_app depends on cloud_firestore ^0.14.1 which depends on cloud_firestore_web ^0.2.0+1, version solving failed.)
exit code 1
```

### My pubspec.yaml -> dependencies
```
dependencies:
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^1.2.5+1
  firebase_storage: ^4.0.1
  brasil_fields: ^0.1.0
  cloud_firestore: ^0.14.1
  firebase_auth: ^0.18.1
  image_picker: ^0.6.6+1
  image_cropper: ^1.2.2
  validadores: ^1.0.2
  firebase_ml_vision: ^0.9.6+2
  firebase_messaging: ^7.0.1
  firebase_core: ^0.5.0
  http: ^0.12.2
  flutter:
    sdk: flutter
```
 
### My 'flutter doctor -v'
```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [versÃ£o 10.0.19041.508], locale pt-BR)
    • Flutter version 1.20.4 at C:\src\flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\lucas\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\lucas\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.    
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\lucas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
