### ISSUE TITLE
/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths

### ISSUE THREAD

**Issue by wizhob2020** [flutter/flutter#67156]
Hi Team 
I am facing this issue when I am trying to make iOS build.  I am mention my pubspec.yml as given bellow
```
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  agora_rtc_engine: ^3.0.1-dev.7
  permission_handler: ^5.0.0+hotfix.3
  image_picker:
  chopper: ^2.4.0
  provider: ^3.0.0+1
  shared_preferences: any
  connectivity: ^0.4.3+2
  dio: any
  configurable_expansion_tile: ^1.0.0
  json_annotation: any
  pin_code_text_field: ^1.5.1
  flutter_html: ^0.11.1
  search_map_place: ^0.1.1
  geolocator: ^5.1.3
  http: ^0.12.0+4
  cached_network_image: ^2.0.0
  flutter_screenutil: ^1.1.0
  socket_io_client: ^0.9.9
  bubble: ^1.1.9+1
  gallery_saver: ^1.0.7
  pull_to_refresh: ^1.5.8
  fimber: ^0.4.0
  timeago: ^2.0.26
  google_fonts: ^0.3.5
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.2.1
  share: ^0.6.3+6
  overlay_support: ^1.0.3
  device_info: ^0.4.2+1
  uuid: ^2.0.4
  photo_view: ^0.9.1
  line_awesome_icons: ^1.0.4+2
  line_icons: ^0.2.0
  flutter_sound: ^2.1.1
  file: ^5.0.4
  image_cropper: any
  admob_flutter: "^1.0.0-beta.2"
  google_sign_in: ^4.4.4
  back_button_interceptor: ^4.2.3
  expandable: ^4.1.4
  flutter_datetime_picker: ^1.3.8
  table_calendar: ^2.2.3
  add_2_calendar: ^1.4.0
  rating_dialog: ^1.0.0
  flutter_email_sender: ^3.0.1
  kommunicate_flutter_plugin: ^1.0.3
  font_awesome_flutter: ^8.5.0
  smooth_star_rating: ^1.0.3
  intl: ^0.16.0
  searchable_dropdown: ^1.1.3
  firebase_auth: ^0.16.0
  package_info: ^0.4.1
  firebase_remote_config: ^0.3.1
  url_launcher: ^5.5.0
  firebase_crashlytics: ^0.1.3
  flutter_launcher_icons: "^0.7.0"
  flutter_automation: ^1.3.3
  file_picker: ^1.13.2
  apple_sign_in: ^0.1.0
  random_color: ^1.0.5
  wakelock: ^0.1.4+1
  flare_flutter:
  notifier:
    path: ../notifier-master
  flutter_share: ^1.0.2+1
  jitsi_meet: ^0.4.1
  uni_links: ^0.4.0
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^2.3.4
  build_runner:

  json_serializable: any

flutter:


  assets:
    - assets/images/


  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Black.otf
        - asset: assets/fonts/Gotham-Bold.otf
        - asset: assets/fonts/Gotham-BookItalic.otf
        - asset: assets/fonts/Gotham-Light.otf
        - asset: assets/fonts/Gotham-Thin.otf
        - asset: assets/fonts/Gotham-ThinItalic.otf
        - asset: assets/fonts/Gotham-XLight.otf
        - asset: assets/fonts/Gotham-XLightItalic.otf
        - asset: assets/fonts/GothamBold.ttf
        - asset: assets/fonts/GothamBoldItalic.ttf
        - asset: assets/fonts/GothamBook.ttf
        - asset: assets/fonts/GothamBookItalic.ttf
        - asset: assets/fonts/GothamLight.ttf
        - asset: assets/fonts/GothamLightItalic.ttf
        - asset: assets/fonts/GothamMedium_1.ttf
        - asset: assets/fonts/GothamMedium.ttf
        - asset: assets/fonts/GothamMediumItalic.ttf

```

When I am installing pod file getting this issue please see this.
```
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/xxxxx/Documents/wizHob/ios2oct/ios/Flutter/Flutter.framework)
```
