### ISSUE TITLE
Flutter after upgrade to 1.22, getting error while build in ios 

### ISSUE THREAD

**Issue by mehtahardikr** [flutter/flutter#67296]
`../../../flutter/packages/flutter/lib/src/foundation/assertions.dart:103:56: Error: Null safety features are disabled for this library. Try removing the package language version or setting the language version to 2.10 or higher.   void filter(List<StackFrame> stackFrames, List<String?> reasons);`

Any solution realy appreciated.

**Comment by awhitford** [comment]
In your `pubspec.yaml`, what does your `environment` say?  Maybe try:
```
 environment:
  sdk: ">=2.10.0 <3.0.0"
```

Then run `flutter pub get`.

**Comment by mehtahardikr** [comment]
@awhitford : by applying this. i got this error after splash , it stucks

```
[VERBOSE-2:shell.cc(209)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[37550:287070] [VERBOSE-2:engine.cc(205)] Could not prepare to run the isolate.
[37550:287070] [VERBOSE-2:engine.cc(144)] Engine not prepare and launch isolate.
[37550:287070] [VERBOSE-2:shell.cc(486)] Could not launch engine with configuration.
```

**Comment by darshankawar** [comment]
@mehtahardikr 
Did you try running `flutter clean` after upgrade ?
What channel are you on ? Also provide `pubspec.yaml`.
Thanks.

**Comment by mehtahardikr** [comment]
yes tried.
channel  : stable
```

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.2
  shared_preferences: any
  pubnub: ^2.0.1
  uuid: ^2.0.4
  country_currency_pickers: ^1.0.1
  #dio: ^3.0.3
  intl: ^0.16.1
  meta: ^1.2.3
  connectivity: ^0.4.9+3
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dependency_overrides:
 # meta: 1.1.8
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```
