### ISSUE TITLE
local_auth requires fragment activity. Changing suggested code won't work or creates other errors

### ISSUE THREAD

**Issue by ofer026** [flutter/flutter#67472]
I'm using local_auth version 0.6.3+2 and when I'm to use it I'm getting an error `PlatformException(no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null, null)` 
I saw issue #33429 and tried the solutions people suggested but neither of them worked.
When  I change my main activity to a fragment activity, which results to this code: 
```
import android.os.Bundle;
import io.flutter.app.FlutterFragmentActivity;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterFragmentActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //GeneratedPluginRegistrant.registerWith(this);
    }
}
```
Created another error when I run the app with firebase:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)`
and I didn't mange to find a solution that worked for me to solve this error.

flutter doctor -v:
```
flutter doctor -v
[√] Flutter (Channel beta, 1.22.0, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0 at D:\Flutter\flutter
    • Framework revision d408d302e2 (7 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ofero\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at D:\OFER\Java\IDE\IntelliJ IDEA Community Edition 2019.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.43.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Web Server (web)             • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 85.0.564.68

! Doctor found issues in 1 category.
```
pubspec.yaml:
```
# Firebase
  firebase_auth: ^0.18.1+1
  cloud_firestore: ^0.14.1+2
  firebase_core: ^0.5.0
  google_sign_in: ^4.5.1
  cloud_functions: ^0.6.0+1
  # Fingerprint Auth
  local_auth: ^0.6.3+2
  # State management
  provider:

  shared_preferences: ^0.5.8

  # UI packages
  simple_animations: ^1.3.3
  flutter_svg: ^0.18.0
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1

```
