### ISSUE TITLE
MissingPluginException firebase_auth and connectivity for iOS

### ISSUE THREAD

**Issue by DotSyndicate** [flutter/flutter#67612]
## Steps to Reproduce

1. Flutter, create a new project.
2. Add firebase_auth and connectivity to pubspec.yaml.
3. Run the following command inside the iOS folder.
`pod init`
4. Add the following to the PodfIle that has been created:
```
pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
```
5. Follow all the steps that are required to integrate Firebase with iOS app like adding the app to firebase, downloading the plist file from FIrebase.
6. Run
`pod install`
7. Run the following command for iOS device:
`flutter run`

**Expected results:** 
```
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Xcode build done.                                           41.4s
Connecting to VM Service at ws://127.0.0.1:54186/3BiV2Ue8nFY=/ws
```

**Actual results:**
```
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Xcode build done.                                           41.4s
Connecting to VM Service at ws://127.0.0.1:54186/3BiV2Ue8nFY=/ws
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method currentUser on channel plugins.flutter.io/firebase_auth)
[38;5;244m#0      MethodChannel._invokeMethod[39;49m 
 package:flutter/…/services/platform_channel.dart
<asynchronous suspension>
[38;5;244m#1      MethodChannel.invokeMethod[39;49m 
 package:flutter/…/services/platform_channel.dart
[38;5;244m#2      MethodChannel.invokeMapMethod[39;49m 
 package:flutter/…/services/platform_channel.dart
[38;5;248m#3      MethodChannelFirebaseAuth.getCurrentUser[39;49m 
 package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart
[38;5;248m#4      FirebaseAuth.currentUser[39;49m 
 package:firebase_auth/src/firebase_auth.dart
[38;5;248m#5      PhoneAuth.init[39;49m 
 package:hustler/Services/phone_auth.dart
[38;5;248m#6      new PhoneAuth.initialize[39;49m 
 package:hustler/Services/phone_auth.dart
[38;5;248m#7      _MyAppState.build[39;49m 
 package:hustler/main.dart
[38;5;244m#8      StatefulElement.build[39;49m 
 package:flutter/…/widgets/framework.dart
#9      Comp<…>

[38;5;248m════════ Exception caught by services library ══════════════════════════════════[39;49m
[38;5;244mThe following MissingPluginException was thrown while activating platform stream on channel plugins.flutter.io/connectivity_status:[39;49m
MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/connectivity_status)

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      MethodChannel._invokeMethod[39;49m 
 package:flutter/…/services/platform_channel.dart
[38;5;244m<asynchronous suspension>[39;49m
[38;5;244m#1      MethodChannel.invokeMethod[39;49m 
 package:flutter/…/services/platform_channel.dart
[38;5;244m#2      EventChannel.receiveBroadcastStream.<anonymous closure>[39;49m 
 package:flutter/…/services/platform_channel.dart
[38;5;244m#3      EventChannel.receiveBroadcastStream.<anonymous closure>[39;49m 
 package:flutter/…/services/platform_channel.dart
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Application finished.
Exited (sigterm)
```

pubspec.yaml file:
```
name: hustler
description: Hustler

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.7+3
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.14
  firebase_storage: ^3.1.6
  firebase_database: ^3.1.6
  firebase_auth: ^0.16.0
  searchable_dropdown: ^1.1.3
  image_picker: ^0.6.7+2
  intl: ^0.16.1
  url_launcher: ^5.4.11
  connectivity: ^0.4.9
  geolocator: ^5.3.2+2
  provider: ^4.1.3+1
  carousel_slider: ^2.1.0
  permission_handler: ^5.0.1+1
  progress_dialog: ^1.2.4
  google_maps_flutter: ^0.5.29
  timeline_tile: ^0.1.2
  flutter_staggered_grid_view: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```

flutter doctor output:
```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0 at /Users/mehdisurani/Desktop/flutter
    • Framework revision d408d302e2 (9 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mehdisurani/Library/Android/sdk
    • Platform android-29, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (2 available)
    • ASUS X00TD (mobile)                 • J8AAGF02V45097J                      • android-arm64 • Android 9 (API 28)
    • iPhone SE (2nd generation) (mobile) • A56B9133-B804-43D8-8354-1187937B7C70 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-0
      (simulator)

• No issues found!
```
