### ISSUE TITLE
Flutter 1.22.1 - version mismatch flutter_test breaks flutter pub get

### ISSUE THREAD

**Issue by mwawrusch** [flutter/flutter#67843]
I got this message since the last update:

Because every version of flutter_test from sdk depends on path 1.8.0-nullsafety.1 and roji_wallet depends on path 1.7.0, flutter_test from sdk is forbidden

Here are the relevant parts from my pub dev:

```
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
```
