### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(network_error, com.google.android.gms.common.api.ApiException: 7: , null, null)

### ISSUE THREAD

**Issue by chirag-chopra** [flutter/flutter#68915]
I am trying to implement google-signin using [this](https://pub.dev/packages/google_sign_in) plugin

**Below is my function**

```
Future<String> googleSignIn() async {
    final GoogleSignInAccount googleSignInAccount =
        await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleSignInAuthentication =
        await googleSignInAccount.authentication;
    final AuthCredential authCredential = GoogleAuthProvider.credential(
        accessToken: googleSignInAuthentication.accessToken,
        idToken: googleSignInAuthentication.idToken);
    final UserCredential userCredential =
        await _firebaseAuth.signInWithCredential(authCredential);
    final User user = userCredential.user;
    assert(user.displayName != null);
    assert(user.email != null);
    print(user.displayName);
    print(user.email);

    final User currentUser = _firebaseAuth.currentUser;
    assert(currentUser.uid == user.uid);

    return 'Error occured';
  }
```

but it's not working and throwing an error.

Below are the logs
/com.geotaskie(29835): ProcessProfilingInfo new_methods=3287 is saved saved_to_disk=1 resolve_classes_delay=8000
I/Timeline(29835): Timeline: Activity_launch_request time:73727325
W/ActivityThread(29835): handleWindowVisibility: no activity for token android.os.BinderProxy@3cbb984
I/Timeline(29835): Timeline: Activity_launch_request time:73727371
D/ForceDarkHelper(29835): updateByCheckExcludeList: pkg: com.geotaskie activity: com.google.android.gms.auth.api.signin.internal.SignInHubActivity@6e83dd
I/chatty  (29835): uid=10268(com.geotaskie) identical 1 line
D/ForceDarkHelper(29835): updateByCheckExcludeList: pkg: com.geotaskie activity: com.google.android.gms.auth.api.signin.internal.SignInHubActivity@6e83dd
E/flutter (29835): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(network_error, com.google.android.gms.common.api.ApiException: 7: , null, null)
E/flutter (29835): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:582
E/flutter (29835): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:159
E/flutter (29835): <asynchronous suspension>
E/flutter (29835): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter (29835): #3      MethodChannel.invokeMapMethod
package:flutter/…/services/platform_channel.dart:359
E/flutter (29835): #4      MethodChannelGoogleSignIn.signIn
package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45
E/flutter (29835): #5      GoogleSignIn._callMethod
package:google_sign_in/google_sign_in.dart:233
E/flutter (29835): <asynchronous suspension>
E/flutter (29835): #6      GoogleSignIn._addMethodCall
package:google_sign_in/google_sign_in.dart:288
E/flutter (29835): #7      GoogleSignIn.signIn
package:google_sign_in/google_sign_in.dart:359
E/flutter (29835): #8      Authentication.newSignInGoogle
package:geotaskie/…/firebase_auth/firebase_auth_service.dart:11
E/flutter (29835): #9      _welcomeScreenState.build.<anonymous closure>
package:geotaskie/screens/pageViewerScreen.dart:170
E/flutter (29835): #10     _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:993
E/flutter (29835): #11     _InkResponseState.build.<anonymous closure>
package:flutter/…/material/ink_well.dart:1111
E/flutter (29835): #12     GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter (29835): #13     TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter (29835): #14     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter (29835): #15     BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:222
E/flutter (29835): #16     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:476
E/flutter (29835): #17     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:77
E/flutter (29835): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:122

**FLUTTE DOCTOR:-**
**Note: I use VS CODE for development.** 

C:\Users\Chirag>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by pedromassangocode** [comment]
Hi @chirag-chopra 
Can you please provide the complete error log and your `pubspec.yaml`?
I will need a minimal complete code sample to reproduce the issue as well.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by flywheelms** [comment]
Same plugin and error in my app.

**Comment by aadarshadhakalg** [comment]
same error here

**Comment by aadarshadhakalg** [comment]
```

Future<bool> signInWithFacebook() async {
    // Trigger the sign-in flow
    final AccessToken result = await FacebookAuth.instance.login();

    // Create a credential from the access token
    final FacebookAuthCredential facebookAuthCredential =
        FacebookAuthProvider.credential(result.token);

    // Once signed in, return the UserCredential
    try {
      await FirebaseAuth.instance.signInWithCredential(facebookAuthCredential);
      return true;
    } on FirebaseAuthException catch (e) {
      if (e.code == 'account-exists-with-different-credential') {
        // The account already exists with a different credential
        String email = e.email;

        // Fetch a list of what sign-in methods exist for the conflicting user
        try {
          List<String> userSignInMethods =
              await auth.fetchSignInMethodsForEmail(email);
          Get.rawSnackbar(
              title: "Duplicate Account Found",
              message: "Please sign in with $userSignInMethods.first");
        } catch (e) {
          print(e.toString);
        }
      } else {
        Get.rawSnackbar(title: "Error!", message: "$e.code");
      }
      return false;
    } catch (e) {
      Get.rawSnackbar(title: "Error!", message: "e");
      return false;
    }
  }
```

my function

```

name: ebidhya
description: A new Flutter Project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  get:
  dio: ^3.0.10
  google_fonts: ^1.1.1
  form_field_validator: ^1.0.1
  firebase_core: "0.5.3"
  firebase_auth: "^0.18.4+1"
  google_sign_in: "^4.5.6"
  flutter_facebook_auth: "^1.0.0"
  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

pubspec.yaml

```

I/behavior::(27592): DIALOG_ONLY
I/Timeline(27592): Timeline: Activity_launch_request time:490698257 intent:Intent { act=DIALOG_ONLY cmp=co.techquantum.ebidhya/com.facebook.FacebookActivity (has extras) }
W/ActivityThread(27592): handleWindowVisibility: no activity for token android.os.BinderProxy@20ca014
I/Timeline(27592): Timeline: Activity_launch_request time:490698546 intent:Intent { cmp=com.facebook.katana/.ProxyAuth (has extras) }
E/flutter (27592): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Instance of 'FacebookAuthException'
E/flutter (27592): #0      FacebookAuth.login
package:flutter_facebook_auth/src/facebook_auth.dart:35
E/flutter (27592): <asynchronous suspension>
E/flutter (27592): #1      AuthController.signInWithFacebook
package:ebidhya/…/controllers/auth.dart:209
E/flutter (27592): #2      LoginFormController.loginWithFacebook
package:ebidhya/…/controllers/loginform.dart:50
E/flutter (27592): #3      _LoginPageState.build.<anonymous closure>.<anonymous closure>
package:ebidhya/…/views/login.dart:211

```

Error Log


```
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /home/aadarsha/snap/flutter/common/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/aadarsha/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9+11-post-Uos-1deb10u1)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Redmi Y3 (mobile) • 192.168.1.69:5555 • android-arm64 • Android 9 (API 28)

```

flutter doctor
