### ISSUE TITLE
Flutter create . doesn't add PodFile to macos directory (for desktop mac build)

### ISSUE THREAD

**Issue by moda20** [flutter/flutter#69069]
## Steps to Reproduce

1. Run `flutter create .` on an existing application to add support for macOS
2. the direcotry macos is created but it is missing a PodFile that is necessary for the build
3. I tried to run the app `flutter run` with only my mac connected and I get the error: `Exception: Podfile missing` 

**Expected results:** 
Building the app
**Actual results:** 
Error related to missing podFile that is supposed to be created automatically
<details>
  <summary>Logs</summary>

```
[ +128 ms] executing: [/Users/userone/Downloads/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] bcac9d4ff4cc020d7557dea55383dbb6622ae8dd
[        ] executing: [/Users/userone/Downloads/flutter/] git tag --points-at
HEAD
[ +163 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [/Users/userone/Downloads/flutter/] git describe --match
*.*.* --first-parent --long --tags
[  +73 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long
--tags
[        ] 1.24.0-1.0.pre-95-gbcac9d4ff4
[  +10 ms] executing: [/Users/userone/Downloads/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/userone/Downloads/flutter/] git ls-remote --get-url
origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +44 ms] executing: [/Users/userone/Downloads/flutter/] git rev-parse
--abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +5 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.5
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19F96
[        ] executing: sysctl hw.optional.arm64
[   +4 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +43 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +53 ms] executing: /Users/userone/Library/Android/sdk/platform-tools/adb
devices -l
[   +7 ms] executing: /usr/bin/xcode-select --print-path
[   +5 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Library/Developer/CommandLineTools
[   +1 ms] executing: /usr/bin/xcodebuild -version
[   +3 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active
developer directory '/Library/Developer/CommandLineTools' is a command line
tools instance
[        ] Xcode not found. Run 'flutter doctor' for more information.
[   +1 ms] executing: /usr/bin/xcodebuild -version
[   +3 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active
developer directory '/Library/Developer/CommandLineTools' is a command line
tools instance
[  +31 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +17 ms] executing: /usr/bin/xcodebuild -version
[   +3 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active
developer directory '/Library/Developer/CommandLineTools' is a command line
tools instance
[ +109 ms] Found plugin path_provider at
/Users/userone/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.1/
[ +117 ms] Found plugin path_provider at
/Users/userone/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.1/
[  +31 ms] Generating
/Users/userone/Documents/flutter_ecommerce_app/android/app/src/main/java/io/flutt
er/plugins/GeneratedPluginRegistrant.java
[  +27 ms] executing: /usr/bin/xcodebuild -version
[  +25 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active
developer directory '/Library/Developer/CommandLineTools' is a command line
tools instance
[        ] executing: /usr/bin/xcodebuild -version
[  +12 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active
developer directory '/Library/Developer/CommandLineTools' is a command line
tools instance
[  +61 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +4 ms] complete
[   +4 ms] Launching lib/main.dart on macOS in debug mode...
[   +5 ms] /Users/userone/Downloads/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/Users/userone/Downloads/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_s
erver.dart.snapshot --sdk-root
/Users/userone/Downloads/flutter/bin/cache/artifacts/engine/common/flutter_patche
d_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true
--output-dill
/var/folders/kd/tv339_k92zqdh35j94z8d9vh0000gn/T/flutter_tools.OCUm9f/flutter_to
ol.uN1M3S/app.dill --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill
build/01094840f26094a3fe371d8be6b9cb48.cache.dill.track.dill
--flutter-widget-cache
[  +44 ms] Found plugin path_provider at
/Users/userone/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.1/
[  +39 ms] <- compile package:flutter_ecommerce_app/main.dart
[+8681 ms] Exception: Podfile missing
[  +11 ms] "flutter run" took 9,350ms.
[   +6 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:622:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1033:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues
(package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure>
           (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure>
           (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback
           (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage
           (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +257 ms] ensureAnalyticsSent: 254ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-2.0.pre.95, on Mac OS X 10.15.5 19F96
    darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)
```

</details>

**Comment by darshankawar** [comment]
@moda20 
Do you have plugins in your existing project ?  The `podfile` is generated only if you have plugins in your project. If there are no plugins, the podfile won't generate. So the issue seem not to be related with podfile. 
Can you try `flutter clean` and then run `flutter run -d macos` ? Also check [this](https://flutter.dev/desktop) document on adding macOS support on existing project.

**Comment by moda20** [comment]
@darshankawar 
i don't think i have any plugins, although the logs show that it tries and finds path_provider plugin.
here is my pubspec.yaml. 
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
are the icons counted as plugins in this sense ?
