### ISSUE TITLE
 Failed to transform guava-20.0.jar 

### ISSUE THREAD

**Issue by krishna700** [flutter/flutter#69094]
After flutter version upgrade from 1.12 to 1.17.5, the app was running fine. But build_runner was not working. Then I did `flutter pub upgrade `  after the upgrade the build_runner is working but the app is not building. 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':path_provider:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':path_provider:debugCompileClasspath'.
   > Failed to transform guava-20.0.jar (com.google.guava:guava:20.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: C:\Users\Krishna\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\20.0\89507701249388e1ed5ddcf8c41f4ce1be7831ef\guava-20.0.jar.
         > Cannot parse result path string: 
android/build.gradle
```
buildscript {
    repositories {
        google()
        jcenter()
        
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath 'com.google.gms:google-services:4.3.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.0.0-beta02'
       
    }
}

allprojects {
    repositories {
        google()
        jcenter()
       
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 30

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
     
        applicationId "***************"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
        
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.firebase:firebase-messaging:20.1.0'
    implementation 'com.android.support:multidex:1.0.3'
   
}

apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'


```
pubspec.yaml

```
name: ************
description: ************


version: 7.6.0+60

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.16.1
  provider: ^4.0.4
  after_layout: 1.0.7+2
  json_annotation: ^3.0.1
  localstorage: ^3.0.1+4
  package_info: ^0.4.3
  device_info: ^0.4.2+7
  launch_review: ^2.0.0
  store_redirect: ^1.0.2
  youtube_player_flutter: ^7.0.0+7

 
  #
  firebase_core : ^0.5.0
  firebase_messaging: ^6.0.9
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.4+1
  notification_permissions: ^0.4.4
  flutter_local_notifications: ^1.2.0+3
  firebase_dynamic_links: ^0.5.0+9
  #
  google_maps_flutter: ^0.5.24+1
  location: ^3.0.2
  #
  connectivity: ^0.4.8+1
  url_launcher: ^5.4.2
  html_unescape: 1.0.1+3
  flutter_webview_plugin: ^0.3.10+1
  #
  configurable_expansion_tile: ^1.0.0
  pull_to_refresh: ^1.5.8
  
  #
  intro_slider: ^2.2.9
  extended_image: 1.1.0
  carousel_slider: ^2.2.1
  dotted_border: ^1.0.6
  chips_choice: ^1.2.0

  
 



  #
  toast: ^0.1.5
  flutter_typeahead: ^1.8.0
  flushbar: ^1.10.2
  flutter_datetime_picker: ^1.4.0
  pin_code_text_field: ^1.5.1
  font_awesome_flutter: ^8.7.0
  #
  badges: ^1.1.0
  flutter_multiselect: 0.5.1
  share: ^0.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.7.4
  json_serializable: ^3.2.5


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon_ios.png"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - lib/common/config/config.json
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf

```
