### ISSUE TITLE
[v1.22.2] IOGPUMetalCommandBuffer, io.flutter.1.io -  iOS TestFlight release Crashes (background mode)

### ISSUE THREAD

**Issue by NickJokic** [flutter/flutter#69102]
Internal: b/172177383

## Background
- Our Flutter app is experiencing sudden TestFlight crashes after upgrading from **v1.16.3** _(dev channel, pre-metal)_ to **v1.22.2** _(stable channel)_.
- The crashes occur for most of the users on multiple iOS versions (12.x - 14.x)
- The app is using a native mobility SDK, which starts the app automatically **(in background)**, when significant location/motion changes are detected.
- Crash occurs, while the app is in **background & significant location changes stop** (e.g. traveling from A to B is finished) .
- We were already experiencing similar _(maybe connected)_ **background/gpu/metal**-related crashes in Flutter **v1.17.x**, which kept us glued to **v1.16.3**.

### Stack Traces
The crash captured by Crashlytics:

**EXC_BAD_ACCESS KERN_INVALID_ADDRESS**
```
Crashed: io.flutter.1.io
0  IOGPU                          0x1cb298b8c -[IOGPUMetalCommandBuffer commandBufferResourceInfo] + 12
1  AGXMetalA9                     0x1d812f4e0 (Missing)
2  AGXMetalA9                     0x1d80ae408 (Missing)
3  AGXMetalA9                     0x1d80baff0 (Missing)
4  Flutter                        0x106013134 (Missing)
5  Flutter                        0x1060161e4 (Missing)
6  Flutter                        0x105f27e84 (Missing)
7  Flutter                        0x105f27ae4 (Missing)
8  Flutter                        0x105f45a64 (Missing)
9  Flutter                        0x105f336f4 (Missing)
10 Flutter                        0x105f510d4 (Missing)
11 Flutter                        0x105f332d0 (Missing)
12 Flutter                        0x105f104d4 (Missing)
13 Flutter                        0x105fc8ac4 (Missing)
14 Flutter                        0x10610f670 (Missing)
15 Flutter                        0x105da8768 (Missing)
16 Flutter                        0x10610ef50 (Missing)
17 Flutter                        0x105da744c (Missing)
18 Flutter                        0x105da93c0 (Missing)
19 CoreFoundation                 0x1922a4a30 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
20 CoreFoundation                 0x1922a4634 __CFRunLoopDoTimer + 1004
21 CoreFoundation                 0x1922a3b14 __CFRunLoopDoTimers + 324
22 CoreFoundation                 0x19229deb0 __CFRunLoopRun + 1912
23 CoreFoundation                 0x19229d200 CFRunLoopRunSpecific + 572
24 Flutter                        0x105da929c (Missing)
25 Flutter                        0x105da8c24 (Missing)
26 libsystem_pthread.dylib        0x1d7bcab70 _pthread_start + 288
27 libsystem_pthread.dylib        0x1d7bcf880 thread_start + 8
```

### Full crash logs
The full crash logs of 3 similar captured crashing occurrences can be found in this gist: https://gist.github.com/NickJokic/21105d573e2750cf126dab5ba004b1c3 

## Steps to Reproduce
The steps can be reproduced from our side by doing the following:
1. Having the Flutter app installed in release mode (TestFlight)
2. Having the app closed and travelling _(moving with the device)_ from A --> B
3. The app gets automatically started in background upon significant location/motion changes are detected. The app then tracks the sensor/location data.
4. After being stationary --> Unlocking the screen --> TestFlight crash popup gets shown

**Expected results:** 
Stable background location/motion tracking with no crashes.

**Actual results:** 
TestFlight crash popup gets shown.

<details>
  <summary>Logs</summary>

**Flutter --version output:**
```
Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (12 days ago) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2
```

**Flutter doctor output:**
```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)
```

**pubspec.yaml dependencies:**
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: 3.2.0
  bloc: 3.0.0
  equatable: ^1.2.5
  graphql: ^3.1.0-beta.4
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  firebase_crashlytics: ^0.1.4+1
  package_info: ^0.4.3
  hydrated_bloc: 3.1.0
  connectivity: ^0.4.9+5
  google_maps_flutter: ^1.0.3
  permission_handler: ^5.0.1+1
  wc_flutter_share: ^0.2.2
  url_launcher: ^5.7.5
  fl_chart: ^0.12.0
  intl: ^0.16.1
  flutter_spinkit: ^4.1.2+1
  auto_size_text: ^2.1.0
  flutter_rounded_progress_bar: ^0.1.2
  device_info: ^0.4.2+9
  flutter_rating_bar: ^3.0.1+1
  liquid_progress_indicator: ^0.3.2
  smooth_page_indicator: ^0.2.0
  flutter_device_type: ^0.2.0
  cached_network_image: ^2.3.3
  email_validator: ^1.0.6
  shared_preferences: ^0.5.12+2
  open_mail_app: ^0.0.3
  instabug_flutter: ^9.1.6
  direct_select_flutter: ^1.0.6
  flutter_svg: ^0.19.1
  version: ^1.2.0
  ansicolor: ^1.0.5
  provider: ^4.3.2
  freezed: ^0.12.2
```

</details>
