### ISSUE TITLE
[image_picker 0.6.7+12] Crash detected by Google Play when publishing when not setting minifyEnabled & shrinkResources to false 

### ISSUE THREAD

**Issue by egodefroy** [flutter/flutter#69188]
From the Google Play console

Problem found on 
Samsung Galaxy S9
1080x2009
Android 8.0 (SDK 26)
3 584 Mo
ARM64_V8
en_U

and on:

Motorola moto e5 play
480x960
Android 8.1 (SDK 27)
1 024 Mo
ARM_V7
en_US

````
java.lang.RuntimeException: Unable to destroy activity {com.egylis.mysafeclient/com.egylis.mysafeclient.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.d.c(androidx.lifecycle.f)' on a null object reference
````

Full stack
````
FATAL EXCEPTION: main
Process: com.egylis.mysafeclient, PID: 28751
java.lang.RuntimeException: Unable to destroy activity {com.egylis.mysafeclient/com.egylis.mysafeclient.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.d.c(androidx.lifecycle.f)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4603)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4621)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.d.c(androidx.lifecycle.f)' on a null object reference
	at io.flutter.plugins.imagepicker.ImagePickerPlugin.h(Unknown Source:21)
	at io.flutter.plugins.imagepicker.ImagePickerPlugin.g(Unknown Source:0)
	at io.flutter.embedding.engine.c.h(Unknown Source:54)
	at io.flutter.embedding.android.f.p(Unknown Source:58)
	at io.flutter.embedding.android.e.F(Unknown Source:7)
	at io.flutter.embedding.android.e.onDestroy(Unknown Source:11)
	at android.app.Activity.performDestroy(Activity.java:7462)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnDestroy(MonitoringInstrumentation.java:1)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4590)
	... 9 more

````

flutter doctor 

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.57, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale fr-FR)
    • Flutter version 1.24.0-4.0.pre.57 at
      /Users/egylis/Documents/Development/Flutter/flutter
    • Framework revision fdac8a9d1f (3 days ago), 2020-10-25 19:47:02 -0400
    • Engine revision d4a3c9c471
    • Dart version 2.11.0 (build 2.11.0-256.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/egylis/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • iPad Air (mobile) • B8DD5903-CACA-422C-902C-7D72AE3BFCB8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)
    • Web Server (web)  • web-server                           • web-javascript • Flutter
      Tools
    • Chrome (web)      • chrome                               • web-javascript • Google
      Chrome 86.0.4240.111

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @egodefroy 
Can you please provide your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by egodefroy** [comment]
Hi @TahaTesser 

pubspec.yaml

````
name: msc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.13
  camera: ^0.5.8+10
  device_info: ^0.4.2+9
  encrypt: ^4.1.0
  excel: ^1.1.5
  flutter_blue: ^0.7.2
  frccblue:
    git:
      url: https://github.com/frcc00/frccblue
  # image: ^2.1.18
  image_picker: ^0.6.7+12
  package_info: '>=0.4.3 <2.0.0'
  path: ^1.7.0
  path_provider: ^1.6.21
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.2
  protect: ^0.0.2
  qr_code_scanner: ^0.0.13
  qr_flutter: ^3.2.0
  share: '>=0.6.5+4 <2.0.0'
  shared_preferences: ^0.5.12+2
  synchronized: ^2.2.0+2
  uuid: ^2.2.2
  webview_flutter: ^1.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
  - family: Billabong
    fonts:
    - asset: assets/fonts/Billabong.ttf
  assets:
      - assets/images/
      - assets/audio/
      - assets/templates/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
````
run --release --verbose

````
flutter run --release --verbose
[ +137 ms] executing: [/Users/egylis/Documents/Development/Flutter/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fdac8a9d1f321388d71e35f825b40c05901e74f0
[        ] executing: [/Users/egylis/Documents/Development/Flutter/flutter/] git tag
--points-at HEAD
[  +68 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [/Users/egylis/Documents/Development/Flutter/flutter/] git describe
--match *.*.* --first-parent --long --tags
[  +20 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.24.0-3.0.pre-57-gfdac8a9d1f
[   +9 ms] executing: [/Users/egylis/Documents/Development/Flutter/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/egylis/Documents/Development/Flutter/flutter/] git ls-remote
--get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +52 ms] executing: [/Users/egylis/Documents/Development/Flutter/flutter/] git rev-parse
--abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +43 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +66 ms] executing: /Users/egylis/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[+1063 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 12.1
           Build version 12A7403
[   +2 ms] executing: sysctl hw.optional.arm64
[  +14 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcdevice list --timeout 2
[   +4 ms] xcrun simctl list --json devices
[        ] executing: xcrun simctl list --json devices
[  +39 ms] List of devices attached
           ce12182ccac1b80c0b7e   device usb:339738624X product:gts4lwifixx model:SM_T830
           device:gts4lwifi transport_id:1
[ +211 ms] {
                      "devices" : {

........(iOS)
}

[  +18 ms] /Users/egylis/Library/Android/sdk/platform-tools/adb -s ce12182ccac1b80c0b7e
shell getprop
[ +107 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[  +99 ms] Downloading Web SDK...
[+1232 ms] Content
https://storage.googleapis.com/flutter_infra/flutter/d4a3c9c471d18c734d30a7e99993ffa3aa3a0
178/flutter-web-sdk-darwin-x64.zip md5 hash: FTYDQrtaPPdJU275Fqrkng==
[+2053 ms] Downloading Web SDK... (completed in 3,3s)
[        ] executing: unzip -o -q
/Users/egylis/Documents/Development/Flutter/flutter/bin/cache/downloads/storage.googleapis
.com/flutter_infra/flutter/d4a3c9c471d18c734d30a7e99993ffa3aa3a0178/flutter-web-sdk-darwin
-x64.zip -d /Users/egylis/Documents/Development/Flutter/flutter/bin/cache/flutter_web_sdk
[+1191 ms] Exit code 0 from: unzip -o -q
/Users/egylis/Documents/Development/Flutter/flutter/bin/cache/downloads/storage.googleapis
.com/flutter_infra/flutter/d4a3c9c471d18c734d30a7e99993ffa3aa3a0178/flutter-web-sdk-darwin
-x64.zip -d /Users/egylis/Documents/Development/Flutter/flutter/bin/cache/flutter_web_sdk
[ +527 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[ +111 ms] Multiple devices found:
[   +6 ms] ro.hardware = qcom
[ +171 ms] SM T830 (mobile)  • ce12182ccac1b80c0b7e                 • android-arm64  •
Android 10
                    (API 29)
[   +2 ms] iPad Air (mobile) • B8DD5903-CACA-422C-902C-7D72AE3BFCB8 • ios            •
           com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)
[        ] Web Server (web)  • web-server                           • web-javascript •
Flutter Tools
[        ] Chrome (web)      • chrome                               • web-javascript •
Google Chrome
           86.0.4240.111
[   +2 ms] [0]: SM T830 (ce12182ccac1b80c0b7e)
[        ] [1]: iPad Air (B8DD5903-CACA-422C-902C-7D72AE3BFCB8)
[        ] [2]: Web Server (web-server)
[        ] [3]: Chrome (chrome)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+67765 ms] run --release --verbose
[        ] Please choose one (To quit, press "q/Q")
[        ] : 

````
