### ISSUE TITLE
Flutter web Github Page white screen

### ISSUE THREAD

**Issue by dleurs** [flutter/flutter#69287]
Dear Flutter developer,

I am having a white screen on my flutter web app on github pages, while it is working fine on dev.

However, Github Pages is one of the three recommended way to deliver Flutter Web on Flutter doc. 

I will reproduce the error with the basic flutter app :

```bash
cd /tmp;
flutter channel beta;
flutter --version; #Flutter 1.23.0-18.1.pre • channel beta
flutter create flutter_web;
cd flutter_web;
flutter config --enable-web;
flutter packages get;
flutter run -d chrome; #Working fine
mkdir .github;
mkdir .github/workflows
touch .github/workflows/workflow.yml
```
Replace below [YOUR_USER_NAME] and [YOUR_GITHUB_REPO_NAME]
```yaml
name: Flutter Web

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        #flutter-version: '1.12.x'
        channel: 'beta' # Currently you have to use beta channel for Flutter web.
    - run: flutter upgrade # You also get the flutter version
    - run: flutter config --enable-web
    - run: flutter packages get
    - run: flutter build web --release
    - run: pwd # To check working-directory is fine
    - run: ls
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git init
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git config user.name  "CI"
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git config user.email "flutter-ci@github.com"
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/[YOUR_USER_NAME]/[YOUR_GITHUB_REPO_NAME].git
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git checkout -b gh-pages
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git add .
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git commit -m "Updated docs" --allow-empty
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git push --force secure-origin gh-pages
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
```
```bash
git init;
git add -A
git commit -m "initial commit"
```
1. Create a github repo, called like YOUR_GITHUB_REPO_NAME
2. Generate a github access token in https://github.com/settings/tokens
3. Add this token in your project in a new Secret, in YourProject > Settings > Secrets. This secret should be called ACCESS_TOKEN
```bash
git remote add origin git@github.com:[YOUR_USER_NAME]/[YOUR_REPO_NAME].git
git push -u origin master
```
Finally, go to YourGitHubProject > Settings > Githup Pages, to get the URL

Problem, white screen :

<img width="942" alt="Screenshot 2020-10-29 at 10 06 21" src="https://user-images.githubusercontent.com/58068925/97547723-7281d200-19ce-11eb-854e-c3232a4fb81d.png">

Thank you for your time,
Stay safe

**Comment by darshankawar** [comment]
@dleurs 
Check you check if [this](https://stackoverflow.com/questions/64415471/flutter-web-on-github-pages-not-showing-content) solution works for you.

**Comment by dleurs** [comment]
You are right thank you ! 
new workflow.yml
```yaml
name: Flutter Web

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        #flutter-version: '1.12.x'
        channel: 'beta' # Currently you have to use beta channel for Flutter web.
    - run: flutter upgrade # You also get the flutter version
    - run: flutter config --enable-web
    - run: flutter packages get
    - run: flutter build web --release
    - run: pwd
    - run: ls
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    
    - run: cat index.html
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: sed -i '/base href/d' index.html #For MacOS : sed -i '' '/base href/d' index.html
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: cat index.html
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web

    - run: git init
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git config user.name  "CI"
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git config user.email "flutter-ci@github.com"
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/[YOUR_USER_NAME]/[YOUR_GITHUB_REPO_NAME].git
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git checkout -b gh-pages
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git add .
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git commit -m "Updated docs" --allow-empty
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
    - run: git push --force secure-origin gh-pages
      working-directory: /home/runner/work/[YOUR_GITHUB_REPO_NAME]/[YOUR_GITHUB_REPO_NAME]/build/web
```
