### ISSUE TITLE
Exception caught by image resource service, Unable to load asset: diamond.png

### ISSUE THREAD

**Issue by SaajidNawwar** [flutter/flutter#69320]
Below is the code i used to get the image from assets. But it doesnt work.

main.dart

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('I Am Rich'),
          backgroundColor: Colors.blueGrey[900],
        ),
        backgroundColor: Colors.blueGrey,
        body: Center(
          child: Image(image: AssetImage('diamond.png')),
        ),
      ),
    ),
  );
}
```

pubspec.yaml

```
name: flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/diamond.png
```
