### ISSUE TITLE
App Store is rejecting App with Widget Extension

### ISSUE THREAD

**Issue by ppb1701** [flutter/flutter#69510]
`ITMS-90853: Invalid font - There was an error validating the font named 'All3PIcons-Regular' at 'Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf'. ‘name’ table structure.

ITMS-90853: Invalid font - There was an error validating the font named 'All3PIcons-Regular' at 'Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf'. ‘name’ table usability.`

It uploads fine but submitting for review for testflight triggers the response and drop of the build.  I had several testflight builds without a problem until the widget extension was added.  Which works locally and even will download as an internal test build until the submit for review drops it.

Building from Latest Master Flutter channel.

**Comment by sidrao2006** [comment]
@ppb1701 , did you face the same errors in stable as well?
Could you please post the outputs of `flutter run -v` and `flutter doctor -v`?
Thank you!

**Comment by pedromassangocode** [comment]
Hi @ppb1701 
Can you share the "widget extension" causing this?
Please provide your `flutter doctor -v` and the complete message (if any) you received from the review process.
Thank you

**Comment by ppb1701** [comment]
Flutter doctor -v (from master)
```
check_it_off git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-7.0.pre.43, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.24.0-7.0.pre.43 at /usr/local/Caskroom/flutter/1.20.2/flutter
    • Framework revision 4996f60b20 (2 days ago), 2020-10-31 19:24:53 +0800
    • Engine revision 3460519398
    • Dart version 2.12.0 (build 2.12.0-3.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/Patrick/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • 74010FE1-DD61-4F0F-9F56-D80BF6CEC055 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```

**Comment by ppb1701** [comment]
flutter run -v  (from master)
[run.txt](https://github.com/flutter/flutter/files/5474924/run.txt)

**Comment by ppb1701** [comment]
my widget extension
[widgetextension.pdf](https://github.com/flutter/flutter/files/5474935/widgetextension.pdf)

**Comment by ppb1701** [comment]
--
 
Dear Developer,We identified one or more issues with a recent submission for TestFlight review for your app, "Check It Off Task Management" 1.0.5 (5). Please correct the following issues, then upload again.ITMS-90853: Invalid font - There was an error validating the font named 'All3PIcons-Regular' at 'Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf'. ‘name’ table structure.ITMS-90853: Invalid font - There was an error validating the font named 'All3PIcons-Regular' at 'Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf'. ‘name’ table usability.Best regards,The App Store Team

**Comment by ppb1701** [comment]
<img width="687" alt="Screen Shot 2020-11-02 at 7 25 11 AM" src="https://user-images.githubusercontent.com/68674902/97867817-8d10bf80-1cdc-11eb-9ac2-b5b970e5d89c.png">

**Comment by ppb1701** [comment]
So from Stable channel
flutter doctor -v
[doctor.txt](https://github.com/flutter/flutter/files/5474970/doctor.txt)

flutter run -v
[run.txt](https://github.com/flutter/flutter/files/5474974/run.txt)

It's submitted for review.  I'll add on if it goes on thru or rejects again

**Comment by pedromassangocode** [comment]
Hi @ppb1701 
I don't think this is related to any kind of extension but with the fonts you are using.
Can you tell me where did you get those fonts and how you added them into the project?

Will need you to provide the `pubspec.yaml` as well.
Thank you

**Comment by ppb1701** [comment]
Ok so on stable, it was approved for TestFlight.


The fonts are material and cupertino.


pubspec
```
name: check_it_off
description: A new Flutter application.

version: 1.0.5+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  sqflite: ^1.3.1+1
  path_provider: ^1.6.18
  introduction_screen: ^1.0.9
  splashscreen: ^1.2.0
  shared_preferences: ^0.5.12
  url_launcher: ^5.7.2
  rflutter_alert: ^1.1.0
  toggle_switch: ^0.1.8
  numberpicker: ^1.2.1
  device_calendar: ^3.1.0
  add_to_calendar: ^1.2.0+1
  flutter_switch: ^0.1.3
  quick_actions: ^0.4.0+10
  flutter_local_notifications: ^2.0.1
  rxdart: ^0.24.1
  redux: ^4.0.0+3
  redux_persist: ^0.8.4
  flutter_redux: ^0.6.0
  background_fetch: ^0.6.0
  recase: ^3.0.0
  timezone: ^0.5.7
  flutter_native_timezone: ^1.0.4
  flutter_widgetkit: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
```
