### ISSUE TITLE
Execution failed for task ':app:bundleDebugResources'

### ISSUE THREAD

**Issue by rch16** [flutter/flutter#69542]
I'm trying to package up my flutter app to deploy to the google play store. At this point please note that I had no problems building the ios version of the application. I have also followed all steps found in the documentation: [Build and release an Android app](https://flutter.dev/docs/deployment/android).

i ran:

`flutter build appbundle --no-shrink --debug`

output: 

```
FAILURE: Build failed with an exception.                          
                                                                        
* What went wrong:                                              
Execution failed for task ':app:bundleDebugResources'.                  
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /Users/beccahallam/GitHub/UniMate/unimate/build/app/intermediates/bundle_manifest/debug/processDebugManifest/bundle-manifest/AndroidManifest.xml:25: AAPT: error: '@mimap/ic_launcher' is incompatible with attribute icon (attr) reference.
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 35s                                                     
Running Gradle task 'bundleDebug'...                                    
Running Gradle task 'bundleDebug'... Done                          37.3s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.   
Running Gradle task 'assembleAarRelease'...  
```

my android/build.gradle file:

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
//        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        configurations.all {
            resolutionStrategy {
                force "com.google.android.gms:play-services-basement:16.0.1"
                force "com.google.android.gms:play-services-tasks:16.0.1"
                force "com.google.firebase:firebase-common:19.3.1"
                force "com.google.android.gms:play-services-measurement-base:17.6.0"
//                force "com.google.android.gms:play-services-measurement:17.5.0"
//                force "com.google.android.gms:play-services-measurement:17.5.0"
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

//googleServices { disableVersionCheck = false }

//com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = false
```

my app/build.gradle file:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "uk.co.unimate"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }

}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.android.support:support-v4:30.1.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'com.google.firebase:firebase-bom:25.12.0'
    implementation 'com.google.firebase:firebase-firestore:21.4.1'
    implementation 'com.google.firebase:firebase-firestore-ktx:21.4.3'
    implementation 'com.google.firebase:firebase-analytics:17.6.0'
    implementation'com.google.firebase:firebase-auth:19.4.0'
}

//googleServices { disableVersionCheck = false }

//com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = false
```

my pubspec.yaml file:

```
name: unimate
description: Log. Track. Predict.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_icons: ^1.1.0
  flutter_hex_color: ^1.0.2
  google_fonts: ^1.1.1
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  firebase_analytics: ^6.1.0
  cloud_firestore: ^0.14.2
  modal_progress_hud: ^0.1.3
  percent_indicator: ^2.1.8
  flutter_rounded_date_picker: ^1.0.5+1
  sleek_circular_slider: ^1.2.0
  flutter_linkify: ^3.1.3
  mailto: ^1.0.0
  url_launcher: ^5.0.3
  flutter_email_sender: ^3.0.1
  flutter_expanded_tile: ^0.2.1
  assorted_layout_widgets: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path_android: "android/app/src/main/res/mipmap-hdpi/ic_launcher.png"
  android: true
  ios: false
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
```

flutter doctor --v output:

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.51, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-4.0.pre.51 at /Users/beccahallam/Developer/flutter
    • Framework revision 720dff6a94 (9 days ago), 2020-10-24 03:57:03 -0400
    • Engine revision 432974a52b
    • Dart version 2.11.0 (build 2.11.0-251.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/beccahallam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • 00875843-5C8F-4BCA-9039-EC06B522D470 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
```

my main/AndroidManifest.xml file:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="uk.co.unimate"
    xmlns:tools="http://schemas.android.com/tools">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        tools:replace="android:label"
        android:name="io.flutter.app.FlutterApplication"
        android:label="UniMate"
        android:icon="@mimap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>
```

If someone could help me resolve this issue ASAP, that would be amazing! I am working to a tight deadline, and have so far been unable to find a similar issue on the web with a solution that works for me. Please let me know if you require any further information!
