### ISSUE TITLE
url_launcher throws missing plugin exception when published (android)

### ISSUE THREAD

**Issue by ilkerokutman** [flutter/flutter#69674]
## Steps to Reproduce

```
  _launchCall() async {
    try {
      if (await canLaunch("tel:${appSettings.phone}")) {
        var res = await launch("tel:${appSettings.phone}");
        Toast.show(res.toString(), context);
      } else {
        Toast.show("could not dial ${appSettings.phone}", context);
      }
    } catch (ex) {
      Toast.show("${ex.toString()}", context);
    }
  }
```

iOS works on debug and release runs and works on Testflight & Appstore
Android works on debug
Android works with command "flutter run --release"  (with signature)
Actually cant see the toast, immediately switchs to dial screen.

Android does not work when published (beta release or internal app sharing) "flutter build appbundle" or apks
Exception toast says: 
`MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)`

<details>
<summary>pubspec.yaml</summary>

```
name: myapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.53+2020110306

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.1 #flutter pub run flutter_launcher_icons:main -f pubspec.yaml
  dio: ^3.0.10
  get: ^3.12.1
  flutter_guid: ^0.1.0
  toast: ^0.1.5
  image_picker: ^0.6.7+11
  modal_progress_hud: ^0.1.3
  flutter_svg: ^0.19.0
  flutter_local_notifications: ^2.0.0
  rflutter_alert: ^1.1.0
  url_launcher: ^5.7.8
  flutter_datetime_picker: ^1.4.0
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon_call.svg
    - assets/images/icon_enroll.svg
    - assets/images/icon_link.svg
    - assets/images/icon_pressure_reminder.svg
    - assets/images/icon_profile.svg
    - assets/images/icon_query.svg

```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
```

```
```

io@ios-Mac-mini dunlop % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-TR)
    • Flutter version 1.22.3 at /Users/io/Library/Flutter
    • Framework revision 8874f21e79 (5 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/io/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9002
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • GT N7100 (mobile)            • 4df1f32b147e9f67                         • android-arm   • Android 5.1.1 (API 22)
    • Redmi Note 8 Pro (mobile)    • onr4kz8x49kve6pj                         • android-arm64 • Android 10 (API 29)
    • Company iPhone’u (mobile) • 3a2b7cd02008d86c4fafb29185a53f540a8f09cb • ios           • iOS 10.3.4
    ! Error: Company iPhone’u is busy: Making Company iPhone’u ready for development. Xcode will continue when Company iPhone’u is finished. (code -10)

• No issues found!

```
```

</details>

<details>
<summary>building</summary>

```
io@ios-Mac-mini myapp % flutter clean && flutter build appbundle
Cleaning Xcode workspace...                                         2.9s
Deleting build...                                                  260ms
Deleting .dart_tool...                                              19ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting App.framework...                                            3ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in dunlop...                              0.5s
Removed unused resources: Binary resource data reduced from 74KB to 71KB: Removed 3%
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        41.9s
✓ Built build/app/outputs/bundle/release/app-release.aab (21.1MB).

```
</details>
