### ISSUE TITLE
Opening a flutter application on iOS device causes any other audio to stop playing (video_player cannot seem to play in background?)

### ISSUE THREAD

**Issue by ObserverMoment** [flutter/flutter#69757]
### Tested Devices
iPhone X iOS 14
iPad Pro 10" iOS 13.7

1. Play some audio / music on your device. Podcast (Apple), music (Spotify) - both the same result.
2. Open your flutter application.
3. The audio / music playing will cut out.

The issue is only present on initial launch of your flutter application - not if you switch back to the app when it is already open.

**See #44535**

**Running `flutter analyze` returns no issues**

**The issue does not reproduce on the empty default app. So is likely some interaction with a library**

```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Applications/flutter
    • Framework revision 84f3d28555 (3 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/richbeans/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0
```

### Installed dependencies
Could one of these be causing the issue?

```
environment:
  sdk: ^2.7.2
  flutter: ^1.22.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  supercharged: ^1.10.0
    
  graphql_flutter: ^3.1.0
  http: ^0.12.2
  get_it: ^5.0.1

  intl: ^0.16.1
  devicelocale: ^0.3.2

  flutter_dotenv: ^2.1.0
  url_launcher: ^5.7.5

  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  
  google_sign_in: ^4.5.5
  apple_sign_in: ^0.1.0
  email_validator: ^1.0.6

  flutter_svg: ^0.19.0
  cupertino_icons: ^1.0.0
  keyboard_dismisser: ^1.0.2
  percent_indicator: ^2.1.7+4
  flutter_xlider: ^3.4.0
  flutter_spinkit: ^4.1.2+1
  flutter_rating_bar: ^3.0.1+1
  simple_animations: ^2.2.3
  sliding_up_panel: ^1.0.2
  carousel_slider: ^2.3.1
  shimmer: ^1.1.2
  lottie: ^0.6.0

  table_calendar: ^2.3.0

  reorderables: ^0.3.2
  flutter_slidable: ^0.5.5
  modal_bottom_sheet: ^0.2.0+1

  # https://github.com/flutter/flutter/issues/66627
  video_player:
    git:
      url: git://github.com/ponnamkarthik/plugins.git
      path: packages/video_player/video_player
  youtube_player_flutter: ^7.0.0+7
  flutter_video_info: ^1.0.1

  assets_audio_player: ^2.0.10
  spotify: ^0.3.7+1

  uploadcare_client: ^2.1.1

  image_cropper: ^1.3.1
  image_picker: ^0.6.7+12

  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1

  path_provider: ^1.6.21
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.2
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
```
