### ISSUE TITLE
[iOS][WebView] Gesture recognizers Invalidation when  drop down control center only in iOS 13.5.x

### ISSUE THREAD

**Issue by XutongGithub** [flutter/flutter#69948]
## PROBLEM:
I download webview_flutter plugin,and running example flutter Application on iOS (actual device [iPhone Xs Max] **only in** system: iOS 13.5.x) is very buggy.

**but in Flutter version 1.17.5, there is no problem or in iOS 14.0.x actual device.**

## OPERATION:
When I drop down control center，screen will freeze and all touches can not work.

## ENVIRONMENT:
**Here excerpts of the pubspec.yaml :**
```
name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
version: 1.0.6
homepage: https://github.com/flutter/plugins/tree/master/packages/webview_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin
      ios:
        pluginClass: FLTWebViewFlutterPlugin
```

**Here is my flutter doctor -v :**
```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-CN)
    • Flutter version 1.22.1 at /Users/fjrb/Desktop/FZDev/flutter
    • Framework revision f30b7f4db9 (4 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/fjrb/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • fjrb’s iPhone (mobile) • ********-0019714C0105****            • ios • iOS 13.5.1
    • iPhone 11 (mobile)     • ******60-26D3-44B3-B9C9-9*****7E0E1 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

```

email: 582714473@qq.com
