### ISSUE TITLE
Android Studio run application failed

### ISSUE THREAD

**Issue by venshine** [flutter/flutter#70077]
I create a new flutter project by Android Studio's default template, then I run the application, but I got the error.
```
[   +4 ms] ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[   +6 ms] executing: /Users/venshine/Work/AndroidSdk/build-tools/29.0.2/aapt dump xmltree /Users/venshine/Work/WorkSpace/AndroidProjects/my/test_flutter/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[  +24 ms] Exit code 0 from: /Users/venshine/Work/AndroidSdk/build-tools/29.0.2/aapt dump xmltree /Users/venshine/Work/WorkSpace/AndroidProjects/my/test_flutter/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.venshine.test_flutter" (Raw: "com.venshine.test_flutter")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="test_flutter" (Raw: "test_flutter")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.venshine.test_flutter.MainActivity" (Raw: "com.venshine.test_flutter.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] Stopping app 'app.apk' on Mi 10.
[        ] executing: /Users/venshine/Work/AndroidSdk/platform-tools/adb -s c9e14780 shell am force-stop com.venshine.test_flutter
[  +59 ms] executing: /Users/venshine/Work/AndroidSdk/platform-tools/adb -s c9e14780 shell pm list packages com.venshine.test_flutter
[  +78 ms] Installing APK.
[   +2 ms] executing: /Users/venshine/Work/AndroidSdk/platform-tools/adb version
[   +8 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as /Users/venshine/Work/AndroidSdk/platform-tools/adb
[        ] executing: /Users/venshine/Work/AndroidSdk/platform-tools/adb start-server
Installing build/app/outputs/flutter-apk/app.apk...
[{"event":"app.progress","params":{"appId":"1d61f418-6e0a-45fe-8693-a52ca36d2a23","id":"1","progressId":null,"message":"Installing build/app/outputs/flutter-apk/app.apk..."}}]
[  +12 ms] executing: /Users/venshine/Work/AndroidSdk/platform-tools/adb -s c9e14780 install -t -r /Users/venshine/Work/WorkSpace/AndroidProjects/my/test_flutter/build/app/outputs/flutter-apk/app.apk
[+1743 ms] Performing Streamed Install
           Success
[{"event":"app.progress","params":{"appId":"1d61f418-6e0a-45fe-8693-a52ca36d2a23","id":"1","progressId":null,"finished":true}}]
[   +5 ms] executing: /Users/venshine/Work/AndroidSdk/platform-tools/adb -s c9e14780 shell echo -n c929c4d735a55a4606ac9f9f3c5b6e83d3c83d31 > /data/local/tmp/sky.com.venshine.test_flutter.sha1
[  +33 ms] Mi 10 startApp
[   +5 ms] executing: /Users/venshine/Work/AndroidSdk/platform-tools/adb -s c9e14780 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.venshine.test_flutter/com.venshine.test_flutter.MainActivity
[  +78 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.venshine.test_flutter/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[   +9 ms] Error waiting for a debug connection: The log reader stopped unexpectedly
[   +2 ms] Error launching application on Mi 10.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:474:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[{"event":"app.stop","params":{"appId":"1d61f418-6e0a-45fe-8693-a52ca36d2a23"}}]
[   +5 ms] executing: /Users/venshine/Work/AndroidSdk/platform-tools/adb -s c9e14780 forward --list
[   +8 ms] Exit code 0 from: /Users/venshine/Work/AndroidSdk/platform-tools/adb -s c9e14780 forward --list
[  +16 ms] "flutter run" took 56,611ms.
[{"id":0,"error":"app '1d61f418-6e0a-45fe-8693-a52ca36d2a23' not found","trace":"#0      AppDomain.stop 
```

flutter doctor -v
```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G2021, locale
    zh-Hans-CN)
    • Flutter version 1.22.3 at /Users/venshine/Work/flutter
    • Framework revision 8874f21e79 (10 天前), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/venshine/Work/AndroidSdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.8.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Mi 10 (mobile) • c9e14780 • android-arm64 • Android 11 (API 30)

• No issues found!

```

**Comment by pedromassangocode** [comment]
Hi @venshine 
Can you please provide your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by venshine** [comment]
@pedromassangocode 
my pubspec.yamll
```
name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
I already delete previous project, then reboot computer, and  I create a new flutter porject again, then It works, so I already cannot provider `flutter run --verbose` , What can I do for you.
