### ISSUE TITLE
【pigeon】Error: This project cannot run with sound null safety, because one or more project dependencies do not

### ISSUE THREAD

**Issue by o0starshine0o** [flutter/flutter#70355]
When I run bash:
```bash
flutter pub run pigeon pigeons/message.dart
```
I get this error:
```bash
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: Error: This project cannot run with sound null safety, because one or more project dependencies do not
support null safety:

 - package:pigeon
 - package:args

Run 'pub outdated --mode=null-safety' to determine if versions of your
dependencies supporting null safety are available.
Instance of '_StringStackTrace'pub finished with exit code 255
```
Here is my `pubspec.yaml`:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Pigeon is a code generator tool to make communication between Flutter and the host platform type-safe and easier.
  pigeon: ^0.1.14
```
and flutter version
```
Flutter (Channel master, 1.24.0-8.0.pre.191
Flutter version 1.24.0-8.0.pre.191
Framework revision 281522bc87
Engine revision c5cbbb000f
Dart version 2.12.0 (build 2.12.0-31.0.dev)
----

Any suggestion is appreciation. 

@gaaclarke
