### ISSUE TITLE
gradient.dart:369:27: Error: Optional parameter 'colors' should have a default value because its type 'List<Color>' doesn't allow null.

### ISSUE THREAD

**Issue by steelx** [flutter/flutter#70383]
My project used to work, but recently I switched to different machine.
And when I try to run the project I get following error

```
Container(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  Color.fromRGBO(
                    215,
                    117,
                    255,
                    1,
                  ).withOpacity(0.5),
                  Color.fromRGBO(
                    255,
                    188,
                    117,
                    1,
                  ).withOpacity(0.9),
                ],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
                stops: [0, 1],
              ),
            ),
          ),
```

I even did `flutter clean` restart machine as well.

```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
/opt/flutter/packages/flutter/lib/src/painting/gradient.dart:369:27: Error: Optional parameter 'colors' should have a default value because its type 'List<Color>' doesn't allow null.
 - 'List' is from 'dart:core'.
 - 'Color' is from 'dart:ui'.
    @required List<Color> colors,
                          ^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/opt/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/opt/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exception: Gradle task assembleDebug failed with exit code 1

```

Below is the code from flutters **gradient.dart** file which is causing the issue.

```
class LinearGradient extends Gradient {
  /// Creates a linear gradient.
  ///
  /// The [colors] argument must not be null. If [stops] is non-null, it must
  /// have the same length as [colors].
  const LinearGradient({
    this.begin = Alignment.centerLeft,
    this.end = Alignment.centerRight,
    @required List<Color> colors,
    List<double>? stops,
    this.tileMode = TileMode.clamp,
    GradientTransform? transform,
  }) : assert(begin != null),
       assert(end != null),
       assert(tileMode != null),
       super(colors: colors, stops: stops, transform: transform);
```

**flutter doctor -v**    

```
> flutter doctor -v                
[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_IN)
    • Flutter version 1.22.3 at /opt/flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/ajinkya/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

Plugins installed
![image](https://user-images.githubusercontent.com/3184210/98957631-6433ca00-2527-11eb-813d-f65dd6be7acf.png)

**pubspec.yml**

```
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  bubble_tab_indicator: ^0.1.4
  fl_chart: ^0.9.4
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12
  rxdart: ^0.24.1
  http: ^0.12.2
  search_map_place: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
  network_image_mock: ^1.0.0
  #test: 1.15.0
```

**flutter run -v**
[https://pastebin.run/CjbQtNJWxT](https://pastebin.run/CjbQtNJWxT)
