### ISSUE TITLE
Lower-bound SDK constraint warning doesn't specify which pubspec is wrong

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#70435]
## Message

```cmd
[C:\src\auto_size_text] flutter pub get
Running "flutter pub get" in auto_size_text...                   2,614ms
pubspec.yaml has no lower-bound SDK constraint.
You should edit pubspec.yaml to contain an SDK constraint:

environment:
  sdk: '>=2.10.0 <3.0.0'

See https://dart.dev/go/sdk-constraint
Running "flutter pub get" in example...
pub get failed (65; See https://dart.dev/go/sdk-constraint)
```

## pubspec.yaml

```yaml
[C:\src\auto_size_text] type pubspec.yaml
name: auto_size_text
description: Flutter widget that automatically resizes text to fit perfectly within its bounds.
version: 2.1.0
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/auto_size_text

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: '>=1.4.0 <3.0.0'
```

## Flutter Doctor

```
[C:\src\auto_size_text] flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-8.0.pre.229, on Microsoft Windows [Version 10.0.19041.610], locale en-US)
    • Flutter version 1.24.0-8.0.pre.229 at c:\flutter
    • Framework revision 7cda6866b0 (2 hours ago), 2020-11-12 22:39:02 -0500
    • Engine revision dddb532b5c
    • Dart version 2.12.0 (build 2.12.0-37.0.dev)

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30711.63
    • Windows 10 SDK version 10.0.19041.0
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] VS Code (version 1.51.0)
    • VS Code at C:\Users\tim\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.610]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.183
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.58

! Doctor found issues in 1 category.
```

**Comment by timsneath** [comment]
Ah -- looks like this is because `example\pubspec.yaml` has an incorrectly tabbed constraint:

```yaml
name: example
description: AutoSizeText Example

version: 1.0.0

environment:
sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true 
```

Then the bug is that the specific `pubspec.yaml` at fault should be called out, since otherwise there's no clear indication of what's wrong.
