### ISSUE TITLE
webview_flutter crashes with black screen on Android 5.1 device. runs fine on emulator

### ISSUE THREAD

**Issue by janithsg** [flutter/flutter#70565]
my app is crashing when installed on a device with Android 5.1. 
But it is working fine on the same Android 5.1 emulator and all other android versions I have tested.

Android Device is this POS machine:
https://www.aliexpress.com/item/32882746248.html

Android Version: 5.1

I am having the same issue as this.
https://github.com/flutter/flutter/issues/35698

Stucking and gives a black screen and crash.

This is flutter doctor output:

````
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
    ! Error: Dev iPhone is not connected. Xcode will continue when Dev iPhone is
      connected. (code -13)

• No issues found!
````

pubspec.yaml file
```
name: testapp
description: testapp

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.0.4
  shared_preferences: ^0.5.7+1
  http:
  progress_dialog: ^1.2.4
  flutter_html: ^0.11.1
  fluttertoast: ^4.0.0
  local_auth: ^0.6.2+2
  custom_switch: ^0.0.1
  image_picker: ^0.6.7+2
  webview_flutter: ^1.0.7
  permission_handler: ^5.0.1+1
  image_gallery_saver: ^1.6.0
  share: ^0.6.4+3
  fluttercontactpicker: ^2.4.2
  qr_flutter: ^3.2.0
  firebase_messaging: ^6.0.16
  connectivity: ^0.4.9+5
  sprintf: ^4.1.0
  url_launcher: ^5.7.2
  flutter_linkify: ^3.1.3
  qr_code_tools: ^0.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/AppIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/TopNavIcons/
    - assets/i18n/ar.json
    - assets/i18n/en.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

Code of the screen:
```
class MyWebView extends StatefulWidget {
  final String initialUrl;

  MyWebView({this.initialUrl});

  @override
  _MyWebViewState createState() => _MyWebViewState();
}

class _MyWebViewState extends State<MyWebView> {
  ProgressDialog progressIndicator;
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  @override
  Widget build(BuildContext context) {
    progressIndicator = new ProgressDialog(context,
        type: ProgressDialogType.Normal, isDismissible: false, showLogs: true);

    return Scaffold(
      body: Builder(
        builder: (BuildContext context) {
          return WebView(
            initialUrl: 'https://flutter.dev',
            javascriptMode: JavascriptMode.unrestricted,
            onWebViewCreated: (WebViewController webViewController) {
              _controller.complete(webViewController);
            },
            navigationDelegate: (NavigationRequest request) {
              if (request.url.startsWith('https://www.youtube.com/')) {
                print('blocking navigation to $request}');
                return NavigationDecision.prevent;
              }
              print('allowing navigation to $request');
              return NavigationDecision.navigate;
            },
            onPageStarted: (String url) {
              print('Page started loading: $url');
            },
            onPageFinished: (String url) {
              print('Page finished loading: $url');
            },
            gestureNavigationEnabled: true,
          );
        },
      ),
    );
  }
```

Debug Console Output:

[errorlog.txt](https://github.com/flutter/flutter/files/5542315/errorlog.txt)
