### ISSUE TITLE
`$flutter build ios-framework --xcframework` fails at time of building FBLPromises.framework which is dependency of some Flutter module

### ISSUE THREAD

**Issue by VasylZa** [flutter/flutter#70563]
## Steps to Reproduce
Run ios framework build. eg. `$flutter build ios-framework --xcframework`

```yaml
pubspec.yaml in my case contains following dependencies:
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider:
  get_it: ^4.0.1
  protobuf:
  permission_handler: ^5.0.1+1
  intl: ^0.16.0
  vector_math: any
  just_debounce_it: 3.0.0+2
  wakelock: ^0.1.4+2
  http: 0.12.1
  hive: ^1.4.3
  hive_flutter: ^0.3.0+2
  cached_network_image: 2.2.0+1
  flutter_cache_manager: 1.4.1
  google_maps_flutter: ^0.5.28+1
  polyline: ^1.0.2
  json_serializable: ^3.3.0
  table_calendar: ^2.2.3
  flutter_staggered_grid_view: ^0.3.2
  pedantic: ^1.9.0
  carousel_slider: ^2.2.1
  tuple: ^1.0.3
  package_info: ^0.4.1
  shared_preferences: ^0.5.12+2
  timeago: ^2.0.27
  progress_dialog: ^1.2.4
  uuid: 2.2.2
  retry: ^3.0.1
  pin_code_fields: ^5.1.0
  assets_audio_player: ^2.0.12
  url_launcher: ^5.7.2
  vibration: ^1.7.1
  path_provider: ^1.6.18
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.0.2
  firebase_crashlytics: ^0.2.1+1
```
## Logs

$ flutter build ios-framework --xcframework
 
```bash
Building frameworks for com.......ui in debug mode...
 ├─Populating Flutter.framework...                                  0.9s
 ├─Creating Flutter.xcframework...                                  4.2s
 ├─Building App.framework...                                        3.7s
 ├─Creating App.xcframework...                                      4.0s
 ├─Building plugins...                                                  
  124.7s (!)                                       
Unable to create universal FBLPromises.framework: 2020-11-14 04:12:17.240 xcodebuild[9603:1959855]  DTDeviceKit: deviceType from 16d4f83a4e665f21c224cc08039067478c7c73b8 was NULL
2020-11-14 04:12:17.383 xcodebuild[9603:1959921]  DTDeviceKit: deviceType from 16d4f83a4e665f21c224cc08039067478c7c73b8 was NULL
2020-11-14 04:12:17.383 xcodebuild[9603:1959921]  DTDeviceKit: deviceType from 16d4f83a4e665f21c224cc08039067478c7c73b8 was NULL

Please, note. FBLPromises.framework is build under:
...../build/ios/framework/Debug/iphoneos/Debug-iphoneos/PromisesObjC/FBLPromises.framework  folder
but `$flutter build ...` command expexts it in:
...../build/ios/framework/Debug/iphoneos/Debug-iphoneos/FBLPromises/FBLPromises.framework  folder
```

```bash
$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-UA)
    • Flutter version 1.22.4 at /Volumes/Linux/flutter
    • Framework revision 1aafb3a8b9 (2 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vasylz/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • MT’s iPhone (mobile) • 16d4f83a4e665f21c224cc08039067478c7c73b8 • ios • iOS 13.6
```
