### ISSUE TITLE
With webview_flutter in the project, debug runs everything fine.After packaged into APK, JS cannot invoke the JavascriptChannel method

### ISSUE THREAD

**Issue by qinrunhao** [flutter/flutter#70667]
webview_flutter: ^1.0.7
There are no logs available here

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1198], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 3.6)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[√] Connected device (1 available)

• No issues found!

```

**Comment by joniaiuser** [comment]
Seems related: https://github.com/flutter/flutter/issues/70655

**Comment by pedromassangocode** [comment]
Hi @qinrunhao 
Can you please provide additional information?
Please provide your `flutter doctor -v`. Does Flutter print anything into the console?

**Comment by qinrunhao** [comment]
I used the adb tracking log, but I get nothing.
I tested that packaged APK and JS can invoke JavascriptChannel when there is only WebView in a project.But in my project, it was packaged and unusable, and there was no log.I'm trying to reduce some of the dependencies on the project.
```
flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale zh-CN)
    • Flutter version 1.22.4 at G:\bin\flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at G:\bin\android-sdk-windows
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = G:\bin\android-sdk-windows
    • Java binary at: D:\soft\soft\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\soft\soft\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\soft\soft\IDEA
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

[√] Connected device (1 available)
    • COL AL10 (mobile) • VBJDU18519015303 • android-arm64 • Android 8.1.0 (API 27)
```
my pubspec.yml:
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  path_provider: ^1.6.21
#  shared_preferences: ^0.5.12+2
  connectivity: ^2.0.1
  intl: ^0.16.1
#  flutter_localizations:
#    sdk: flutter
  webview_flutter: ^1.0.7
  fluttertoast: ^3.1.3
  flutter_swiper: ^1.1.6
  local_auth: ^0.6.3+3
#  flutter_string_encryption: ^0.3.1
#  device_info: 0.4.0+2
  image_picker: ^0.5.4+3
  common_utils: ^1.2.1
#  rxdart: ^0.22.6
  sp_util: ^1.0.1
#  cached_network_image: ^2.0.0
  package_info: ^0.4.3+2
  flutter_markdown: ^0.5.0
  permission_handler: ^5.0.1+1
  open_file: ^3.0.3
  url_launcher: ^5.0.2
  cupertino_icons: ^0.1.3

dev_dependencies:
#  为安卓、IOS生成闪屏图片，引入该包后，运行命令 flutter pub pub run flutter_native_splash:create
#  相关配置在文件flutter_native_splash.yaml中
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - resources/
```
