### ISSUE TITLE
prefer_final_locals and prefer_final_in_for_each completely break flutter analyze

### ISSUE THREAD

**Issue by NatoBoram** [flutter/flutter#70692]
After adding `prefer_final_locals`, the behaviour of `flutter analyze` became completely unpredictable, going as far as to report `prefer_single_quotes` when it was explicitly set to `false` in `analysis_options.yaml`. It is also possible that `prefer_final_in_for_each` breaks `flutter analyze` by reporting `prefer_final_locals` errors, even when `prefer_final_locals: false` is set explicitely.

```yaml
# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
linter:
  rules:
    always_use_package_imports: true
    annotate_overrides: false
    directives_ordering: true
    omit_local_variable_types: false
    prefer_final_in_for_each: true
    prefer_single_quotes: false
```

## Steps to Reproduce

1. Add `prefer_final_locals` and `prefer_final_in_for_each` to your `analysis_options.yaml`
2. Run `flutter analyze`
3. Run `dartfix -w --fix=prefer_final_locals lib test`
4. Undo changes via git, but keep `prefer_final_in_for_each`
5. Run `flutter analyze`

## Logs

```bash
[ +132 ms] executing: [C:\Users\natob\Applications\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +121 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1aafb3a8b9b0c36241c5f5b34ee914770f015818
[        ] executing: [C:\Users\natob\Applications\flutter/] git tag --points-at HEAD
[ +112 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.4
[   +8 ms] executing: [C:\Users\natob\Applications\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +76 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +16 ms] executing: [C:\Users\natob\Applications\flutter/] git rev-parse --abbrev-ref HEAD
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
# ...
[  +13 ms] Analyzing live_app... (completed in 27,4s)
[ +133 ms]    info - Prefer final for variable declarations if they are not reassigned - lib\core\logger\bloc\logger_bloc.dart:48:17 - prefer_final_locals
# ...
[ +369 ms] "flutter analyze" took 30 936ms.
[ +194 ms] 29 issues found. (ran in 27.6s)
[ +140 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
                    #1      AnalyzeOnce.analyze (package:flutter_tools/src/commands/analyze_once.dart:186:7)
                    #2      _rootRunUnary (dart:async/zone.dart:1198:47)
                    #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                    #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                    #10     AnalysisServer.dispose (package:flutter_tools/src/dart/analysis.dart)
                    #11     _rootRunUnary (dart:async/zone.dart:1198:47)
                    #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
                    #18     _rootRun (dart:async/zone.dart:1190:13)
                    #19     _CustomZone.run (dart:async/zone.dart:1093:19)
                    #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
                    #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
                    #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
                    #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
                    #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
                    #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[+1832 ms] ensureAnalyticsSent: 0ms
[ +168 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +5 ms] exiting with code 1
```

```bash
[√] Flutter (Channel unknown, 1.22.4, on Microsoft Windows [Version 10.0.19042.630], locale fr-CA)
    • Flutter version 1.22.4 at C:\Users\natob\Applications\flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\natob\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\ProgramData\scoop\apps\android-studio\current\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\ProgramData\scoop\apps\android-studio\current
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.63

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment]
Hi @NatoBoram 
Reproducible steps are not clear,  here what i did
Add `analysis_options.yaml` to new stable channel project

```yaml
# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
linter:
  rules:
    always_use_package_imports: true
    annotate_overrides: false
    directives_ordering: true
    omit_local_variable_types: false
    prefer_final_in_for_each: true
    prefer_final_locals: true // removed later for dartfix
```
### logs
```bash
tahatesser@Tahas-MacBook-Pro stable_flutter % flutters analyze   
Analyzing stable_flutter...                                             
No issues found! (ran in 2.7s)
tahatesser@Tahas-MacBook-Pro stable_flutter % dartfix -w --fix=prefer_final_locals lib test
Calculating fixes...           2.8s
Found 0 changes in 0 files.

There are no recommended changes.
tahatesser@Tahas-MacBook-Pro stable_flutter % flutters analyze                             
Analyzing stable_flutter...                                             
No issues found! (ran in 1.4s)
tahatesser@Tahas-MacBook-Pro stable_flutter % 
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (5 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (1 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.2

! Doctor found issues in 1 category.
```

</details>
