### ISSUE TITLE
[google_sign_in] Sign in fails after adding google-services.json to project which manages users outside of Firebase

### ISSUE THREAD

**Issue by FlutterGandhi** [flutter/flutter#70695]
We were using the google_sign_in package without Firebase for a few months now without any problems, while managing users in a different database. 
For a new feature I had to implement Firebase. As soon as I add the generated `google-services.json` from Firebase to my project, the sign in fails with the exception mentioned below.

I tried passing our `OAuth 2.0 Client ID` (which is set [here](https://console.developers.google.com/apis/credentials)) without success like this:
`final _googleSignIn = GoogleSignIn(
  scopes: [
    'email',
  ],
  clientId: 'MY-CLIENT-ID'
);`

I also tried changing `client_id` in `google-services.json` to our `OAuth 2.0 Client ID`. 

In the [source code](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java) I found a comment (line 329) which hints at the problem.

So I guess the question is: Is there currently a way to prevent the google_sign_in package from using data from `google-services.json` if it is present in the project?

## Steps to Reproduce

1. Create new Flutter project
2. Add a basic Google Sign In without Firebase (e.g. [like this](https://medium.com/flutter-community/flutter-sign-in-with-google-in-android-without-firebase-a91b977d166f))
3. Create and setup a new Firebase project
4. Add generated google-services.json to Flutter project

**Expected results:** Google Sign In should continue to work when passing `clientId`

**Actual results:** Google Sign In throws the following exception: `PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)`

**Comment by TahaTesser** [comment]
Hi @FlutterGandhi 
Can you please provide your `flutter doctor -v` your `pubspec.yaml`
Thank you

**Comment by FlutterGandhi** [comment]
Hi @TahaTesser,

sure, here you go:
<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G73, locale de-DE)
    • Flutter version 1.22.2 at /Users/FlutterGandhi/Documents/flutter
    • Framework revision 84f3d28555 (5 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/FlutterGandhi/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554
      • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max (mobile)         • B2AC8A93-6E02-40A2-87D9-6BC5B6841102
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
```
</details>
<details>
<summary>pubspec.yaml</summary>

```
environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^3.0.1
  get: 3.1.2
  intl: ^0.16.1
  http: ^0.12.0+4
  google_fonts: ^1.0.0
  shared_preferences: ^0.5.7
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  sign_in_with_apple: ^2.5.1
  json_serializable: ^3.3.0
  url_launcher: ^5.7.8
  sqflite: ^1.3.0
  cached_network_image: ^2.2.0+1
  flutter_auth_buttons: ^0.8.0
  flutter_markdown: ^0.4.0
  share: '>=0.6.4+3 <2.0.0'
  path_provider: ^1.6.9
  native_pdf_view: ^3.6.0
  wiredash: ^0.1.0
  uni_links: ^0.4.0
  flutter_swiper: ^1.1.6
  dotted_border: ^1.0.5
  image_picker: ^0.6.7+1
  image_cropper: ^1.3.1
  reorderables: ^0.3.2
  auto_size_text: ^2.1.0
  in_app_review: ^0.2.1+1
  device_info: '>=0.4.2+4 <2.0.0'
  package_info: '>=0.4.1 <2.0.0'
  flutter_keyboard_visibility: ^3.3.0
  agora_rtc_engine: ^3.1.3
  agora_rtm: ^0.9.14
  permission_handler: ^5.0.1+1
  wakelock: ^0.2.1
  firebase_core: ^0.5.2
  firebase_analytics: ^6.2.0
  cloud_firestore: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/
```
</details>

<details>
  <summary>flutter run -verbose</summary>
Do you need the complete output?
Output when I tap the button which executes _googleSignIn.signIn() and then tap on a google account in the dialog:

```
[  +34 ms] W/ActivityThread(12787): handleWindowVisibility: no activity for
token android.os.BinderProxy@3e7e47
[  +88 ms] D/EGL_emulation(12787): eglMakeCurrent: 0xe81c4580: ver 3 0 (tinfo
0xc93cee20)
[+10881 ms] I/flutter (12787): PlatformException(sign_in_failed,
com.google.android.gms.common.api.ApiException: 10: , null, null)
```
</details>
