### ISSUE TITLE
Flutter app not running on ios14 , on macos Catalina, Xcode Version 12.2

### ISSUE THREAD

**Issue by cmdrootaccess** [flutter/flutter#70824]
App runs in xcode but not running in android studio with flutter.

```
Launching lib/main.dart on Root’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: VYG4PPPOI
Running pod install...
Running Xcode build...
Xcode build done.                                           61.2s
Installing and launching...
Could not run build/ios/iphoneos/Runner.app on 1033f7da16cab0196779877eff0dd2c4e01.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Root’s iPhone.
```

flutter doctor -v

```
root@Roots-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-8.0.pre.304, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
    • Flutter version 1.24.0-8.0.pre.304 at /Users/root/flutter
    • Framework revision c6290500f8 (7 hours ago), 2020-11-18 17:29:28 -0800
    • Engine revision 35a0b9fe68
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/root/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Root’s iPhone (mobile) • 1033f7da16cab0196779877eff0dd2c4e01 • ios • iOS 14.2

• No issues found!
```

**Comment by pedromassangocode** [comment]
Hi @cmdrootaccess 
Can you please try this:
>Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

If the issue persists provide your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by cmdrootaccess** [comment]
#  flutter run --verbose
[log.txt](https://github.com/flutter/flutter/files/5579235/log.txt)

# pubspec.yaml
```
name: birdapp
description: Flutter Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
#  sdk: ">=2.1.0 <3.0.0"
   sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^1.1.4
  simple_animations: ^1.3.3
#  rxdart: 0.22.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: 4.3.2
  transparent_image: 1.0.0
  google_fonts: ^0.3.9
  http: ^0.12.0+4
#  flutter_cache_manager: 1.2.2
  cached_network_image: 2.1.0+1
  flushbar: ^1.10.2
#  flutter_svg: ^0.14.1
  url_launcher: ^5.4.5
  image_picker: 0.6.6+1
  flutter_settings: ^1.0.2
  device_info: 0.4.2+4
  crypto: 2.1.5
  sqflite: 1.3.0+2
  path_provider: 1.6.10
  searchable_dropdown: 1.1.3
#  google_maps_flutter: 0.5.28+1
  firebase_messaging: 6.0.16
  shared_preferences: 0.5.7+3
  flutter_webview_plugin: 0.3.11
  webview_flutter: ^0.1.1
  flutter_staggered_grid_view: 0.3.2
#  google_maps_place_picker: 0.9.5
#  frideos: 1.0.1
  font_awesome_flutter: ^8.0.1
  flutter_facebook_login: 3.0.0
  dio: 3.0.10
  html: ^0.14.0+3

dev_dependencies:
  flutter_automation: 1.3.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
