### ISSUE TITLE
Custom 'fontFamily' is not working

### ISSUE THREAD

**Issue by ChkBuk** [flutter/flutter#71350]
https://github.com/ChkBuk/FlutterPlayground/blob/8f2f97c66cac5c85dd02feee22d1882a66ef8396/lib/main.dart#L17

I am fresher for 'Flutter' and I tried to add font family from google fonts to my app.
I have added the following steps 

1. Download google font (IndieFlower-Regular.ttf)
2. Created a folder 'fonts' in the root directory and copied the .tff file.
3. Added it to pubspec.yaml file and get dependencies.
4. Added into .dart file as follows

`style: TextStyle(
                color: Colors.black87,
                fontSize: 25.0,
                fontFamily: 'IndieFlower'),
          ),`
But when run the application, it font family does not apply. Can anybody help with this issue?

**Comment by iapicca** [comment]
the indentation in [your pubspec.yaml](https://github.com/ChkBuk/FlutterPlayground/blob/8f2f97c66cac5c85dd02feee22d1882a66ef8396/pubspec.yaml) looks weird

```yaml
 # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
fonts:
  - family: IndieFlower
    fonts:
      - asset: fonts/IndieFlower-Regular.ttf
uses-material-design: true
```
also I don't see the folder in [your project](https://github.com/ChkBuk/FlutterPlayground/tree/8f2f97c66cac5c85dd02feee22d1882a66ef8396)
