### ISSUE TITLE
Mention required dependencies in Flutter test docs

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#7154]
## Steps to Reproduce

https://flutter.io/testing/ doesn't mention these dependencies are required

```yaml
dev_dependencies:
  test: '>=0.12.17 <0.13.0'
  flutter_test:
    sdk: flutter
```

Consider adding it to the default `pubspec.yaml` created by `flutter create`
