### ISSUE TITLE
[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1062)] Check failed: CheckException(env).

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#71579]
I'm having this problem in the app when I access a screen with webview, the app exits unexpectedly and displays these errors on the console

```console
D/        ( 5520): HostConnection::get() New Host Connection established 0x8722c300, tid 5535
D/        ( 5520): HostConnection::get() New Host Connection established 0x8736f800, tid 5533
W/cr_media( 5520): Requires BLUETOOTH permission
E/libEGL  ( 5520): validate_display:99 error 3008 (EGL_BAD_DISPLAY)
D/        ( 5520): HostConnection::get() New Host Connection established 0x78e7e540, tid 5610
E/chromium( 5520): [ERROR:gl_surface_egl.cc(335)] eglChooseConfig failed with error EGL_SUCCESS
D/EGL_emulation( 5520): eglCreateContext: 0x889cd720: maj 2 min 0 rcv 2
D/EGL_emulation( 5520): eglMakeCurrent: 0x889cd720: ver 2 0 (tinfo 0x79010730)
I/art     ( 5520): Background sticky concurrent mark sweep GC freed 10494(826KB) AllocSpace objects, 25(1200KB) LOS objects, 3% free, 41MB/42MB, paused 8.384ms total 23.079ms
D/EGL_emulation( 5520): eglMakeCurrent: 0x87098c80: ver 2 0 (tinfo 0x8737c630)
I/VideoCapabilities( 5520): Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil( 5520): HW encoder for video/avc is not available on this device.
E/chromium( 5520): [ERROR:gl_surface_egl.cc(335)] eglChooseConfig failed with error EGL_SUCCESS
D/EGL_emulation( 5520): eglCreateContext: 0x6b47d180: maj 2 min 0 rcv 2
D/EGL_emulation( 5520): eglMakeCurrent: 0x6b47d180: ver 2 0 (tinfo 0x79010730)
E/eglCodecCommon( 5520): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5520): glUtilsParamSize: unknow param 0x000085b5
E/GLConsumer( 5520): [SurfaceTexture-0-5520-0] attachToContext: invalid current EGLDisplay
E/flutter ( 5520): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
E/flutter ( 5520):      at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:290)
E/flutter ( 5520):
F/flutter ( 5520): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1062)] Check failed: CheckException(env).
E/eglCodecCommon( 5520): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 5520): glUtilsParamSize: unknow param 0x000085b5
W/google-breakpad( 5520): ### ### ### ### ### ### ### ### ### ### ### ### ###
W/google-breakpad( 5520): Chrome build fingerprint:
W/google-breakpad( 5520): 69.0.3497.100
W/google-breakpad( 5520): 349710017
W/google-breakpad( 5520): ### ### ### ### ### ### ### ### ### ### ### ### ###
F/libc    ( 5520): Fatal signal 6 (SIGABRT), code -6 in tid 5553 (1.raster)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_google_phone_x86/generic_x86:7.1.1/NYC/6695155:userdebug/test-keys'
Revision: '0'
ABI: 'x86'
pid: 5520, tid: 5553, name: 1.raster  >>> br.gov.rj.riodasostras.riodasostrasapp <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1062)] Check failed: CheckException(env).
'
    eax 00000000  ebx 00001590  ecx 000015b1  edx 00000006
    esi 89580978  edi 89580920
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
    eip a81a4424  ebp 8957e7b8  esp 8957e75c  flags 00000296
backtrace:
    #00 pc ffffe424  [vdso:a81a4000] (__kernel_vsyscall+16)
    #01 pc 0007a03c  /system/lib/libc.so (tgkill+28)
    #02 pc 00075885  /system/lib/libc.so (pthread_kill+85)
    #03 pc 0002785a  /system/lib/libc.so (raise+42)
    #04 pc 0001ee36  /system/lib/libc.so (abort+86)
    #05 pc 000210d4  /data/app/br.gov.rj.riodasostras.riodasostrasapp-1/lib/x86/libflutter.so (offset 0x118a000)     
Lost connection to device.
```

```console
flutter doctor -v
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [versÃ£o 10.0.19042.630], locale pt-BR)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at C:\Users\isaque\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\isaque\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

```yaml
name: riodasostrasapp
description: App Oficial da Prefeitura de Rio das Ostras
version: 1.0.2+3

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  connectivity: ^2.0.2
  url_launcher: ^5.7.10
  share: ^0.6.5+4
  #map_launcher: ^1.0.0
  map_launcher: ^0.4.3
  device_id: ^0.2.0
  device_info: ^1.0.0
  location_permissions: ^3.0.0+1
  location: ^3.1.0
  flutter_inappwebview: ^4.0.0+4

  #firebase services
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_analytics: ^5.0.16

  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  flutter_advanced_networkimage: ^0.7.0
 
  #webview_flutter: ^0.3.22+1
  webview_flutter: ^1.0.7
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  queries: ^0.1.14
  #flutter_svg: ^0.17.4
  intl: ^0.16.1

  http: ^0.12.2
  dio: ^3.0.10
  universal_html: ^1.2.2
  essential_rest: ^1.1.22
  #wideget para infinit scroll
  incrementally_loading_listview: ^0.3.0
  
  #bloc state manager  
  flutter_bloc: ^4.0.0 #^3.2.0
  bloc: ^4.0.0
  #mobx state manager
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  #redux state manager
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  redux_thunk: ^0.3.0
  #provider state manager
  provider: ^4.1.2
  flutter_modular: ^2.0.1
  equatable: ^1.1.1

  carousel_slider: ^2.3.1
  #para armazenar o token  
  flutter_secure_storage: ^3.3.5
  #gerar codigo qr
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  jaguar_jwt: ^2.1.6

  riodasostrasapp_core:
    hosted:
      name: riodasostrasapp_core
      url: http://pub.riodasostras.rj.gov.br:4000
    version: ^1.0.39

dependency_overrides:
  rxdart: ^0.24.1
  #flutter_svg: ^0.19.2+1
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.10.6
  mobx_codegen: ^1.1.2
  slidy: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700      
    - family: pmro_app
      fonts:
        - asset: assets/fonts/pmro.ttf         
     
   
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
      
```
