### ISSUE TITLE
Clear documentation for using assets in a flutter package

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#71770]
There is no useful information on how to include assets into a flutter package, and use it in for example a widget in that same package.

Essentially

Package:
- Some Icon
- Some Dummy widget that shows said icon

App: 
- Uses the above package dummy widget -> `Error: Unable to load asset`

I have tried adding the assets tags in yml, I have also tried shoving them in the lib folder, but resources just load.

**Comment by preetshah21699** [comment]
The default pubspec.yaml file has proper information on how to use assets. You can add the following to your pubspec.yaml file.
```
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/English_content.json
    - assets/Images/BG.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: ./fonts/PlayfairDisplay-Regular.ttf
        - asset: ./fonts/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: ./fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: ./fonts/PlayfairDisplay-BoldItalic.ttf
          style: italic
          weight: 700
```
In the above code, the "assets" folder is in the root project directory.

You can use the same path in widgets to load images and other assets into your app.

`
AssetImage('assets/Images/BG.png')
`
The above loads an image from the asset from one of the paths specified in pubspec.yaml.
`
rootBundle.loadString("assets/English_content.json")
`
The above code loads the a json file as string which I will parse later.
