### ISSUE TITLE
No named parameter with the name 'shadowThemeOnly' at 1.24.0-10.2 sdk beta version

### ISSUE THREAD

**Issue by tazik561** [flutter/flutter#71785]
I have a flutter pwa project that is works fine with `1.23.0-18.1.pre` sdk version. Now i upgraded sdk to `1.24.0-10.2.pre` :
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
```
Now i can't run my project:

```
[+9019 ms]
../../../../../Software/Linux/Flutter/flutter/.pub-cache/git/persianDatePicker-b20d15502d6cae5c5bc9b4219789e16b15debb26/lib/widget/dialo
                    g.dart:725:45: Error: No named parameter with the name 'shadowThemeOnly'.
[        ]   final ThemeData theme = Theme.of(context, shadowThemeOnly: true);
[        ]                                             ^^^^^^^^^^^^^^^
[        ] ../../../../../Software/Linux/Flutter/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this
candidate, but
           the arguments don't match.
[        ]   static ThemeData of(BuildContext context) {
[        ]                    ^^
[+1781 ms] lib/widget/date_picker/widget/dialog.dart:725:45: Error: No named parameter with the name 'shadowThemeOnly'.
[        ]   final ThemeData theme = Theme.of(context, shadowThemeOnly: true);
[        ]                                             ^^^^^^^^^^^^^^^
[        ] ../../../../../Software/Linux/Flutter/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this
candidate, but
           the arguments don't match.
[        ]   static ThemeData of(BuildContext context) {
[        ]                    ^^
[+23071 ms] Syncing files to device Chrome... (completed in 36.4s)
[        ] Synced 0.0MB.
[        ] Failed to compile application.
[   +2 ms] "flutter run" took 43,951ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:617:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1080:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:931:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```
• No issues found!

This is my pubspec.yaml:
```
dependency_overrides:
  analyzer: 0.40.4
  build_resolvers: '1.4.1'

dependencies:
  flutter:
    sdk: flutter
  persian_datetime_picker:
    git:
      url: https://gitlab.com/mortezabagheridev/persianDatePicker.git
  after_layout: ^1.0.7+2
  barcode_scan: ^1.0.0
  carousel_slider: ^2.2.1
  ...
dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: 1.10.3
  hive_generator: ^0.8.1
  json_serializable: ^3.5.0
  retrofit_generator: ^1.4.0+1
```
