### ISSUE TITLE
release apk not work, but run release is work

### ISSUE THREAD

**Issue by stevenBang** [flutter/flutter#71902]
## Steps to Reproduce

If I use Android studio run --release, it's work
but use build apk --release, Only a white screen after installation (not gray)

## AndroidManifest.xml

```
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="my.com.app">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <application
        android:name=".Application"
        android:label="Flutter APP"
        android:allowBackup="true"
        android:requestLegacyExternalStorage="true"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:showWhenLocked="true"
            android:turnScreenOn="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>

        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="high_importance_channel" />
    </application>
</manifest>
```

## pubspec.yaml
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #https://pub.dev/packages/event_bus
  event_bus: ^1.1.1
  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.7
  fluttertoast: ^4.0.0
  passwordfield: ^0.0.5
  smooth_page_indicator: ^0.1.5
  http: ^0.12.0+4
  flappy_search_bar: ^1.7.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1
  progress_dialog: ^1.2.2
  enum_to_string: ^1.0.9
  stripe_payment: ^1.0.0
  firebase_core: ^0.5.0
  image_picker: ^0.6.7+1
  provider: ^4.1.0
  dio: ^3.0.8
  #https://pub.dev/packages/flare_flutter
#  flare_flutter: ^2.0.3
  rating_dialog: ^1.0.0
  dots_indicator: ^1.2.0
  file_picker: ^2.1.0
  firebase_messaging: ^8.0.0-dev.7
  #https://pub.dev/packages/path_provider
  path_provider: ^1.6.8

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^6.0.0

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.18.0
  cloud_firestore: ^0.14.0+2
  flutter_keyboard_visibility: ^3.2.1
  intl: 0.16.1
  lottie: ^0.4.0
  package_info: ^0.4.0+6
  url_launcher: ^5.5.0
  flutter_tagging: ^2.2.0+3
  image_cropper: ^1.3.0
  flutter_local_notifications: ^3.0.1+2
  webview_flutter: ^1.0.4
  google_sign_in: ^4.5.3
  firebase_auth_oauth: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
```

## doctor --verbose
```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64, locale zh-Hant-TW)
    • Flutter version 1.22.4 at /Users/steven/flutter
    • Framework revision 1aafb3a8b9 (4 周前), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/steven/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • AE22C81E-AE5A-49C9-8CC5-66BE43B94842 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

• No issues found!
```
