### ISSUE TITLE
Flutter iOS app crashes in flutter::TransformLayer::Paint > SkAutoCanvasRestore::~SkAutoCanvasRestore()

### ISSUE THREAD

**Issue by w3ggy** [flutter/flutter#71908]
Our app crashes randomly with a small stack trace which doesn't help with investigating the problem. Locally it doesn't reproduce. I suppose it crashes on [VideoPlayer](https://pub.dev/packages/video_player) (we working on gathering details of these crashes). I couldn't symbolize the output like it is described [here](https://github.com/flutter/flutter/wiki/Crashes) because it is not trivial for iOS. Right now I have no idea what is the problem and how to find it. I tried to find it by stack trace with no success.

## Steps to Reproduce

1. Currently I have no steps for reproducing. It crashes randomly on:
- 13.6.0 (17G68) iPad Pro
- 12.4.9 (16H5) iPhone 6
- 13.3.1 (17D50) iPhone 7
- 13.6.1 (17G80) iPad Air 2
- 13.7.0 (17H35) iPad Pro (10.5-inch)
- 14.2.0 (18B92) iPad Pro

**Crashlog  from 13.3.1 (17D50) iPhone 7 (it looks very  similar on all devices):** 

```
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000070
__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__

Crashed: com.apple.main-thread
0  Flutter                        0x100c3f3a0 (Missing)
1  Flutter                        0x100cdc400 (Missing)
2  Flutter                        0x100c3f3e4 (Missing)
3  Flutter                        0x100c22444 (Missing)
4  Flutter                        0x100c1e43c (Missing)
5  Flutter                        0x100c20c54 (Missing)
6  Flutter                        0x100c1e43c (Missing)
7  Flutter                        0x100c2241c (Missing)
8  Flutter                        0x100c1e43c (Missing)
9  Flutter                        0x100c2241c (Missing)
10 Flutter                        0x100c1e43c (Missing)
11 Flutter                        0x100c20c54 (Missing)
12 Flutter                        0x100c1e43c (Missing)
13 Flutter                        0x100c2241c (Missing)
14 Flutter                        0x100c1e43c (Missing)
15 Flutter                        0x100c2241c (Missing)
16 Flutter                        0x100c1e43c (Missing)
17 Flutter                        0x100c2241c (Missing)
18 Flutter                        0x100c1e43c (Missing)
19 Flutter                        0x100c1c6bc (Missing)
20 Flutter                        0x100e9c584 (Missing)
21 Flutter                        0x100bd344c (Missing)
22 Flutter                        0x100bd53c0 (Missing)
23 CoreFoundation                 0x1a8ff103c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
24 CoreFoundation                 0x1a8ff0d78 __CFRunLoopDoTimer + 880
25 CoreFoundation                 0x1a8ff0448 __CFRunLoopDoTimers + 276
26 CoreFoundation                 0x1a8feb584 __CFRunLoopRun + 1920
27 CoreFoundation                 0x1a8feaadc CFRunLoopRunSpecific + 464
28 GraphicsServices               0x1b2f8b328 GSEventRunModal + 104
29 UIKitCore                      0x1ad0f863c UIApplicationMain + 1936
30 Runner                         0x1006eb5e8 main + 6 (AppDelegate.swift:6)
31 libdyld.dylib                  0x1a8e74360 start + 4
```

<details>

```
[✓] Flutter (Channel unknown, 1.22.2, on macOS 11.0.1 20B29, locale en-RU)
    • Flutter version 1.22.2 at /Users/artem/flutter
    • Framework revision 84f3d28555 (8 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/artem/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/artem/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/artem/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

```

</details>

**Comment by darshankawar** [comment]
@w3ggy 
Is your app add-to-app ?  Can you also provide `pubspec.yaml` ?

**Comment by w3ggy** [comment]
No, it is a Flutter app from scratch except for two local plugins related to AirPlay (`flutter_airplay_button` and `flutter_audio_session`).
My initial question could be incorrect a little bit. To the start, I want to know in which Flutter component the issue is happening? Because I have no way to reproduce it on my devices and stack trace has no useful information (at least for me)

<details
```
name: name
description: The Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  built_value_generator: ^7.1.0
  built_collection: ^4.3.2

  firebase_core: ^0.5.1
  firebase_analytics: ^6.1.0
  firebase_crashlytics: ^0.2.2
  firebase_messaging: ^7.0.3

  flutter_svg: ^0.19.0
  image_picker: ^0.6.7+11

  freezed_annotation: ^0.11.0
  json_serializable: ^3.5.0

  auto_size_text: ^2.1.0
  table_calendar: ^2.3.0

  flutter_secure_storage: ^3.3.4

  rxdart: ^0.24.1

  keyboard_actions: ^3.3.1

  http_parser: ^3.1.4

  video_player: ^0.11.0
  flutter_airplay_button:
    path: ./local_plugins/flutter_airplay_button

  flutter_audio_session:
    path: ./local_plugins/flutter_audio_session

  webview_flutter: ^1.0.0

  uni_links: ^0.4.0

  cupertino_icons: ^1.0.0

  shared_preferences: ^0.5.12

  keyboard_visibility: ^0.5.6

  native_device_orientation: ^0.4.3

  cached_network_image: ^2.3.2+1

  image_cropper: 1.3.1

  url_launcher: ^5.7.2

  tutorial_coach_mark: ^0.5.1
  smooth_page_indicator: ^0.2.0

  native_pdf_view: ^3.8.0

  flutter_segment: ^3.0.0

  wakelock: ^0.2.0

  package_info: ^0.4.3

  flutter_cache_manager: ^1.4.2

  phone_state_i: ^0.0.3

  share: ^0.6.5+4

dev_dependencies:
  build_runner: ^1.10.2
  effective_dart: ^1.2.4
  freezed: ^0.11.6
  flutter_launcher_icons: ^0.8.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/fit/svg/
    - assets/images/fit/png/
    - assets/images/golf/svg/
    - assets/images/golf/png/
    - assets/images/common/png/
    - assets/images/common/svg/
    - assets/files/fit/
    - assets/files/golf/
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham/Gotham-Ultra.ttf
          weight: 900
        - asset: assets/fonts/Gotham/Gotham-UltraItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Gotham/Gotham-Black.ttf
          weight: 800
        - asset: assets/fonts/Gotham/Gotham-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Gotham/Gotham-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gotham/Gotham-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Gotham/Gotham-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gotham/Gotham-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Gotham/Gotham-Book.ttf
          weight: 400
        - asset: assets/fonts/Gotham/Gotham-BookItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Gotham/Gotham-Light.ttf
          weight: 300
        - asset: assets/fonts/Gotham/Gotham-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Gotham/Gotham-XLight.ttf
          weight: 200
        - asset: assets/fonts/Gotham/Gotham-XLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Gotham/Gotham-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gotham/Gotham-Thin.ttf
          weight: 100
          style: italic

```
</details>
