### ISSUE TITLE
[device_info] build error on master channel

### ISSUE THREAD

**Issue by worldofsites** [flutter/flutter#71968]
flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.25.0-5.0.pre.108, on Microsoft Windows [Version 10.0.19042.630], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.51.1)
[√] Connected device (3 available)

• No issues found!
```

device_info version:
```
device_info: ^1.0.0
```

debug console output
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Frameworks\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\android\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'device_info'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 5.6.2. If using the gradle wrapper, try editing the distributionUrl in C:\Frameworks\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.6.4-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 929ms


Exception: The plugin device_info could not be built due to the issue above.
```

**works** on ```flutter-1.25-candidate.6``` branch (1.25.0-5.0.pre.61)
**not works** on ```flutter-1.25-candidate.7``` branch (1.25.0-5.0.pre.108)

**Comment by shatanikmahanty** [comment]
![Screenshot 2020-12-09 113537](https://user-images.githubusercontent.com/67138059/101591524-bc6cc780-3a12-11eb-871c-e2f64667bf15.png)
Click on the red marked(gradle-wrapper.properties) file under android\gradle directory.
You will find : 

`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`

Change it to : 

`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`

**Comment by worldofsites** [comment]
@shatanikmahanty 
``device_info` it's not my library -> https://github.com/flutter/plugins/tree/master/packages/device_info

**Comment by shatanikmahanty** [comment]
No you need to change the distribution url in your own project

**Comment by worldofsites** [comment]
@shatanikmahanty 
in my project already 5.6.4.
it's not related to my project.

**Comment by shatanikmahanty** [comment]
Ooh ok my bad

**Comment by pedromassangocode** [comment]
Hi @worldofsites 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`. 
Thank you

**Comment by worldofsites** [comment]
gradle-wrapper.properties:
```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
```

flutter doctor -v:
```
[√] Flutter (Channel master, 1.25.0-5.0.pre.108, on Microsoft Windows [Version 10.0.19042.685], locale ru-RU)
    • Flutter version 1.25.0-5.0.pre.108 at C:\Frameworks\flutter
    • Framework revision 995aa138cd (29 hours ago), 2020-12-08 09:18:02 +0530
    • Engine revision b0d31ae166
    • Dart version 2.12.0 (build 2.12.0-125.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Frameworks\android_sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\Frameworks\android_sdk
    • ANDROID_SDK_ROOT = C:\Frameworks\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.52

• No issues found!
```

flutter run --verbose:
```
[  +62 ms] executing: [C:\Frameworks\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +79 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 995aa138cdfe9fda8bdb54203f1bbf2d8ad5d8e1
[   +1 ms] executing: [C:\Frameworks\flutter/] git tag --points-at 995aa138cdfe9fda8bdb54203f1bbf2d8ad5d8e1
[  +81 ms] Exit code 0 from: git tag --points-at 995aa138cdfe9fda8bdb54203f1bbf2d8ad5d8e1
[   +1 ms] executing: [C:\Frameworks\flutter/] git describe --match *.*.* --long --tags 995aa138cdfe9fda8bdb54203f1bbf2d8ad5d8e1
[ +112 ms] Exit code 0 from: git describe --match *.*.* --long --tags 995aa138cdfe9fda8bdb54203f1bbf2d8ad5d8e1
[   +2 ms] 1.25.0-4.0.pre-108-g995aa138cd
[  +32 ms] executing: [C:\Frameworks\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [C:\Frameworks\flutter/] git ls-remote --get-url origin
[  +45 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +78 ms] executing: [C:\Frameworks\flutter/] git rev-parse --abbrev-ref HEAD
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +52 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +42 ms] executing: C:\Frameworks\android_sdk\platform-tools\adb.exe devices -l
[  +50 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:sdk_gphone_x86 device:generic_x86_arm transport_id:1
[   +5 ms] C:\Frameworks\android_sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +48 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] Skipping pub get: version match.
[  +24 ms] Found plugin device_info at C:\Frameworks\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\
[  +46 ms] Found plugin integration_test at C:\Frameworks\flutter\packages\integration_test\
[  +58 ms] Found plugin device_info at C:\Frameworks\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-1.0.0\
[  +31 ms] Found plugin integration_test at C:\Frameworks\flutter\packages\integration_test\
[   +5 ms] Generating C:\Projects\demo\test_app\test_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +43 ms] ro.hardware = ranchu
[  +13 ms] Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software rendering with  
           "--enable-software-rendering".
[  +21 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +3 ms] complete
[   +4 ms] Launching lib\main.dart on sdk gphone x86 in debug mode...
[  +10 ms] C:\Frameworks\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Frameworks\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Frameworks\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata --output-dill C:\Users\user\AppData\Local\Temp\flutter_tools.9acb7c86\flutter_tool.ee88f18a\app.dill  
--packages C:\Projects\demo\test_app\test_app\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\152a2ce78bff4a6f74a44ed554717a64.cache.dill.track.dill --flutter-widget-cache --enable-experiment=alternative-invalidation-strategy    
[   +9 ms] executing: C:\Frameworks\android_sdk\build-tools\29.0.3\aapt dump xmltree
C:\Projects\demo\test_app\test_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +17 ms] Exit code 0 from: C:\Frameworks\android_sdk\build-tools\29.0.3\aapt dump xmltree
C:\Projects\demo\test_app\test_app\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.test_app" (Raw: "com.example.test_app")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="test_app" (Raw: "test_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.test_app.MainActivity" (Raw: "com.example.test_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +12 ms] executing: C:\Frameworks\android_sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +19 ms] <- compile package:test_app/main.dart
[  +42 ms] --------- beginning of main
           12-09 09:09:38.237 W/Binder:194_2(  194): type=1400 audit(0.0:6107): avc: denied { read } for name="wakeup35" dev="sysfs"
           ino=18326 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
[  +39 ms] executing: C:\Frameworks\android_sdk\platform-tools\adb.exe version
[  +28 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Frameworks\android_sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Frameworks\android_sdk\platform-tools\adb.exe start-server
[  +27 ms] Building APK
[  +12 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] Using gradle from C:\Projects\demo\test_app\test_app\android\gradlew.bat.
[   +1 ms] C:\Projects\demo\test_app\test_app\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +7 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +91 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: [C:\Projects\demo\test_app\test_app\android/] C:\Projects\demo\test_app\test_app\android\gradlew.bat -Pverbose=true    
-Ptarget-platform=android-x86 -Ptarget=C:\Projects\demo\test_app\test_app\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +966 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[   +1 ms] Build file 'C:\Projects\demo\test_app\test_app\android\app\build.gradle' line: 24
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':app'.
[        ] > Failed to apply plugin [id 'com.android.internal.version-check']
[        ]    > Minimum supported Gradle version is 6.5. Current version is 5.6.4. If using the gradle wrapper, try editing the
distributionUrl in C:\Projects\demo\test_app\test_app\android\gradle\wrapper\gradle-wrapper.properties to gradle-6.5-all.zip
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 
get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 821ms
[ +510 ms] Running Gradle task 'assembleDebug'... (completed in 1 587ms)
[+3011 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 5 333ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)  
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>


[  +86 ms] ensureAnalyticsSent: 63ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1
```


pubspec.yaml:
```
name: test_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: ^1.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
