### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException - iOs app is put to foreground then crashes

### ISSUE THREAD

**Issue by BogsBalangat** [flutter/flutter#71971]
We got this crash from ios 14.2.0, device iPhone 6s.
Based on our initial check, the user puts the app to the background and after a few seconds, puts it back to the foreground then the app crashes.

# Steps to Reproduce

We don't have a way to reproduce this issue. We only got this crash from production and can not reproduce it.

**Expected results:** 
App should not crash

**Actual results:** 
App crashes with the following stack trace:
```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x18ace19d4 __exceptionPreprocess
1  libobjc.A.dylib                0x19e692b54 objc_exception_throw
2  CoreFoundation                 0x18abf04fc -[CFPrefsSearchListSource addManagedSourceForIdentifier:user:]
3  Foundation                     0x18bee8878 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKitCore                      0x18d9baeec -[_UIDiffableDataSourceState initWithGenerationID:identifiers:sections:dataSourceSnapshot:]
5  UIKitCore                      0x18cc883f8 __56-[__UIDiffableDataSource reloadFromSnapshot:completion:]_block_invoke
6  UIKitCore                      0x18cc884e4 __56-[__UIDiffableDataSource reloadFromSnapshot:completion:]_block_invoke.175
7  libdispatch.dylib              0x18a91a280 _dispatch_client_callout
8  libdispatch.dylib              0x18a8c9b8c _dispatch_lane_barrier_sync_invoke_and_complete
9  UIKitCore                      0x18cc88180 -[__UIDiffableDataSource reloadFromSnapshot:completion:]
10 UIKitCore                      0x18cc885d0 -[__UIDiffableDataSource applyDifferencesFromSnapshot:animatingDifferences:completion:]
11 UIKitCore                      0x18cc845f0 -[UICollectionViewDiffableDataSource applySnapshot:animatingDifferences:completion:]
12 ShareSheet                     0x19aa83f00 -[UIActivityContentViewController refreshContent]
13 ShareSheet                     0x19aa8dd9c -[UIActivityViewController willEnterForeground:]
14 CoreFoundation                 0x18ac44360 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
15 CoreFoundation                 0x18ac44320 ___CFXRegistrationPost_block_invoke
16 CoreFoundation                 0x18ac43918 _CFXRegistrationPost
17 CoreFoundation                 0x18ac43310 _CFXNotificationPost
18 Foundation                     0x18be770a0 -[NSNotificationCenter postNotificationName:object:userInfo:]
19 UIKitCore                      0x18d56032c -[UIApplication _sendWillEnterForegroundCallbacks]
20 UIKitCore                      0x18cc1ff7c __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke_2
21 UIKitCore                      0x18d1475ec _UIScenePerformActionsWithLifecycleActionMask
22 UIKitCore                      0x18cc1f830 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
23 UIKitCore                      0x18cc1f284 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
24 UIKitCore                      0x18cc1f65c -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
25 UIKitCore                      0x18cc1ef18 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
26 UIKitCore                      0x18cc26bc4 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
27 UIKitCore                      0x18d060a2c +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:]
28 UIKitCore                      0x18d15ed14 _UISceneSettingsDiffActionPerformChangesWithTransitionContext
29 UIKitCore                      0x18cc268b8 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
30 UIKitCore                      0x18ca65e84 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke
31 UIKitCore                      0x18ca64924 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
32 UIKitCore                      0x18ca65ad0 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
33 UIKitCore                      0x18d087790 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
34 FrontBoardServices             0x199677fc0 -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:]
35 FrontBoardServices             0x1996a07fc __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2
36 FrontBoardServices             0x199684f20 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
37 FrontBoardServices             0x1996a0748 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke
38 libdispatch.dylib              0x18a91a280 _dispatch_client_callout
39 libdispatch.dylib              0x18a8bf930 _dispatch_block_invoke_direct$VARIANT$mp
40 FrontBoardServices             0x1996c3f20 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
41 FrontBoardServices             0x1996c3be8 -[FBSSerialQueue _targetQueue_performNextIfPossible]
42 FrontBoardServices             0x1996c40bc -[FBSSerialQueue _performNextFromRunLoopSource]
43 CoreFoundation                 0x18ac61be0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
44 CoreFoundation                 0x18ac61ae0 __CFRunLoopDoSource0
45 CoreFoundation                 0x18ac60e28 __CFRunLoopDoSources0
46 CoreFoundation                 0x18ac5b3d0 __CFRunLoopRun
47 CoreFoundation                 0x18ac5ab90 CFRunLoopRunSpecific
48 GraphicsServices               0x1a0f7d598 GSEventRunModal
49 UIKitCore                      0x18d544638 -[UIApplication _run]
50 UIKitCore                      0x18d549bb8 UIApplicationMain
51 Runner                         0x10459690c main + 7 (AppDelegate.swift:7)
52 libdyld.dylib                  0x18a939588 start

```

**Flutter Doctor:** 
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.22.1, on Mac OS X 10.15.5 19F101, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

• No issues found!

```

**Comment by TahaTesser** [comment]
Hi @BogsBalangat 
Can you please provide your `flutter doctor -v`  with verbose and your `pubspec.yaml`
Thank you

**Comment by BogsBalangat** [comment]
Hi @TahaTesser ,

Here is the flutter doctor -v output:
```
[✓] Flutter (Channel beta, 1.22.1, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.22.1 at /Users/bogs/flutter/flutter
    • Framework revision f30b7f4db9 (9 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/bogs/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Web Server (web)             • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 87.0.4280.88
```

Here is our pubspec.yml:

```
name: app_name
description: app_description
version: 0.0.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  shared_preferences: 0.5.6+1
  http: 0.12.2
  path_provider: 1.6.18
  device_info: 0.4.1+4
  device_id: 0.2.0
  crypto: ^2.0.3
  async:
  get_it: 4.0.2
  rect_getter: ^0.0.1
  mailer: ^1.2.3
  location: 2.3.5
  latlong: ^0.6.1
  firebase_messaging: 7.0.3
  firebase_analytics: 6.0.2
  firebase_core: 0.5.0+1
  audioplayers: 0.14.0
  uni_links: 0.2.0
  flutter_launcher_icons: ^0.6.1
  package_info: 0.4.0+13
  connectivity: 0.4.9
  flutter_facebook_login: 3.0.0
  add_2_calendar: 1.4.0
  cached_network_image: 2.1.0+1
  firebase_crashlytics: 0.2.1+1
  timezone: 0.5.6
  share: ^0.6.3+5
  corsac_jwt: ^0.1.2
  diacritic: ^0.1.0
  uuid: 2.0.4
  flutter_bloc: 5.0.1
  equatable: 0.5.1
  toast: 0.1.5
  flutter_sidekick: 0.1.3
  chewie: 0.9.10
  permission_handler: 4.2.0+hotfix.3
  apple_sign_in: 0.1.0
  maps_launcher: 1.2.0
  logging: 0.11.3+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  mockito: ^4.0.0
  flutter_driver:
    sdk: flutter
  flutter_gherkin: 1.1.7+3
  glob: 1.1.7
  random_string: 1.1.0
```

Thank you
