### ISSUE TITLE
Flutter build iOS failed.

### ISSUE THREAD

**Issue by deveshgarg-max** [flutter/flutter#72057]
```bash
Xcode's output:
↳

Undefined symbols for architecture arm64:
      "OBJC_CLASS$_GeneratedPluginRegistrant", referenced from:
          objc-class-ref in AppDelegate.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see
    invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description
```

I have done all the steps that need to solve it.
I have used these references 
https://github.com/flutter/flutter/issues/23556#issuecomment-433817284 
https://github.com/flutter/flutter/issues/56567

My Pubspec.YAML

```yaml
name: ************
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 
  shared_preferences: 
  flutter_spinkit:
  provider: 
  geocoder: 
  http:  
  geolocator: 
  location: ^3.1.0
  google_fonts: 
  hexcolor: 
  fluttertoast: 
  firebase_database: ^4.4.0
  url_launcher:
  google_maps_flutter: 
  google_maps_webservice: 
  flutter_polyline_points:
  image_picker_modern: ^0.4.12+3 
  firebase_storage:
  material_design_icons_flutter:
  firebase_auth: ^0.18.4+1
  flutter_local_notifications:
  latlong:
  google_directions_api: ^0.5.0
  lottie:
  flutter_rating_bar: ^3.0.1+1
  country_code_picker: ^1.6.2
  search_map_place: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Untitled-1-01-01.png"
  adaptive_icon_foreground: "assets/Untitled-1-01-01.png"


flutter:


  assets:
    - assets/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/Raleway-Bold.ttf
          weight: 800
        - asset: assets/Raleway-Light.ttf


```
