### ISSUE TITLE
[White screen build apk in release mode with flutter 1.22.4 running on Android 7]

### ISSUE THREAD

**Issue by Vanessa-Berazategui** [flutter/flutter#72089]
Hi all, I've been struggling to make an apk in release mode work during days (in all cases in debug mode works perfect).

I could make it work on Android 10 with this configuration: 

```bash
build.gradle:
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

targetSdkVersion: 
29

ndk:
20.0.5594570
```

gradle-wrapper.properties:
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-bin.zip`

But I couldn´t make it work on Android 7 which is my client OS.

![Screenshot_20201210-170951](https://user-images.githubusercontent.com/37006656/101824412-ee615500-3b0a-11eb-8e66-7adf00205e3a.png)

flutter doctor -v

```bash
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale es-UY)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\vberazategui\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7547

[√] Connected device (2 available)
    • A920 (mobile)  • 0821208723 • android-arm   • Android 7.1.2 (API 25)
    • Mi A2 (mobile) • 45ba699    • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```
pubspect.yaml

```yaml
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  global_configuration: ^1.5.0
  logger: ^0.7.0
  path_provider: ^1.6.7
  barcode_scan: ^3.0.1
  provider: ^4.0.5
  async: ^2.4.0
  shared_preferences: ^0.5.7
  get_it: ^4.0.4
  dartz: ^0.9.1
  injectable: ^1.0.4
  flushbar: ^1.10.4
  auto_route: ^0.6.7
  flutter_slidable: ^0.5.7
  package_info: ^0.4.3
  logger_flutter: ^0.7.1
  permission_handler: ^5.0.1+1
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  injectable_generator: ^1.0.4
  auto_route_generator: ^0.6.8
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  image_path: 'assets/images/trade_mark/app_icon.png'
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/config/
    - assets/gif/
    - assets/images/background/
    - assets/images/trade_mark/
    - assets/images/shopping_cart/
    - assets/images/action/
    - assets/images/payment/
    - assets/images/article/
    - assets/images/shape/
    - assets/images/draw/
```
flutter run release --verbose 
-------------------------------
[flutter_run_release_verbose.txt](https://github.com/flutter/flutter/files/5675411/flutter_run_release_verbose.txt)

Could you help me?

Thanks in advance.

**Comment by TahaTesser** [comment]
Hi @Vanessa-Berazategui 
White/Gray screen indicates crash in a release build, similar to the red crash screen in debug mode. 
Something in your code is crashing and you seem to have third-party, please debug your ap[ and check what code is causing this crash.


Just a quick look in logs, I can see you're a discontinued package  https://pub.dev/packages/barcode_scan, not saying that is the cause but please remove discontinued packages and isolate the code that's causing the crash
```
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: activity (line=62)
                   A: android:name(0x01010003)="de.mintware.barcode_scan.BarcodeScannerActivity" (Raw: "de.mintware.barcode_scan.BarcodeScannerActivity")
[   +2 ms] Stopping app 'app.apk' on A920.
```

If you can reproduce the issue without any third-patty packages, please provide  your `flutter run  --release --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Vanessa-Berazategui** [comment]
Hi, thank you for your response, I will test your suggestions. But what I see extrange is that flutter build apk --release works perfect in Android 10 which is my  phone and the same code gives me a white/grey screen in client device which has Android 7.

**Comment by Vanessa-Berazategui** [comment]
Well, I finally configured the project like this:

```
build.gradle:
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

targetSdkVersion: 
29

ndk:
20.0.5594570

gradle-wrapper.properties:
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-bin.zip
```

flutter doctor -v

```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1256], locale es-UY)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\vberazategui\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7547

[√] Connected device (2 available)
    • A920 (mobile)  • 0821208723 • android-arm   • Android 7.1.2 (API 25)
    • Mi A2 (mobile) • 45ba699    • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

And started to comment individual packages and I found the problem was associated with the package https://pub.dev/packages/package_info, specifically when I injected the module with the package https://pub.dev/packages/get_it in this way:

```
@module
abstract class PackageInformationInjectableModule {
  @lazySingleton
  @preResolve
  Future<PackageInfo> get packageInfo => PackageInfo.fromPlatform();
}

and used like this:

@LazySingleton(as: PackageInformation)
class PackageInformationImpl implements PackageInformation {

	...

	final PackageInfo packageInfo;

	PackageInformationImpl({
		...,
		@required this.packageInfo,
	});

	@override
	Future<Either<Failure, String>> getVersion() async {
		try {
		  final result = packageInfo.version;
		  return right(result);
		} catch (e) {
		  ...
		}
	}
}
```

I had to change it, and use it like this:

```
@override
Future<Either<Failure, String>> getVersion() async {
	try {
	  PackageInfo packageInfo = await PackageInfo.fromPlatform();
	  final result = packageInfo.version;

	  return right(result);
	} catch (e) {
	  logger.e('Oops, an unexpected error occurred... ' + e.toString());
	  return left(PackageInformationFailure());
	}
}
```
Also to regenerate injections I had to downgrade https://pub.dev/packages/build_runner to version 1.10.2.

pubspect.yaml

```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  global_configuration: ^1.5.0
  logger: ^0.7.0
  path_provider: ^1.6.7
  barcode_scan: ^3.0.1
  provider: ^4.0.5
  async: ^2.4.0
  shared_preferences: ^0.5.7
  get_it: ^4.0.4
  dartz: ^0.9.1
  injectable: ^1.0.4
  flushbar: ^1.10.4
  auto_route: ^0.6.7
  flutter_slidable: ^0.5.7
  package_info: ^0.4.3
  logger_flutter: ^0.7.1
  permission_handler: ^5.0.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.2
  injectable_generator: ^1.0.4
  auto_route_generator: ^0.6.8
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  image_path: 'assets/images/trade_mark/app_icon.png'
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/config/
    - assets/gif/
    - assets/images/background/
    - assets/images/trade_mark/
    - assets/images/shopping_cart/
    - assets/images/action/
    - assets/images/payment/
    - assets/images/article/
    - assets/images/shape/
    - assets/images/draw/
```

It's really strange this behaviour.

Thank you.
