### ISSUE TITLE
local_auth ^0.6.3+4 is incompatible with flutter_localizations from sdk.

### ISSUE THREAD

**Issue by zhangwei911** [flutter/flutter#72320]
```
Running "flutter pub get" in xysmart...
Because no versions of local_auth match >0.6.3+4 <0.7.0 and local_auth 0.6.3+4 depends on intl >=0.15.1 <0.17.0, local_auth ^0.6.3+4 requires intl >=0.15.1 <0.17.0.
And because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, local_auth ^0.6.3+4 is incompatible with flutter_localizations from sdk.
So, because xysmart depends on both flutter_localizations any from sdk and local_auth ^0.6.3+4, version solving failed.
pub get failed (1; So, because xysmart depends on both flutter_localizations any from sdk and local_auth ^0.6.3+4, version solving failed.)
```

**Comment by TahaTesser** [comment]
Hi @zhangwei911 
This is caused non-null-safety version of `local_auth`, you're proabably not on stable channel 
Can you please switch to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

and then add 
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  local_auth: ^0.6.3+4
```

**Comment by masewo** [comment]
What is the solution for people being on beta channel?

**Comment by andreujuanc** [comment]
Hi @TahaTesser 
Some, like me, use the beta to compile to web. And now I cannot do so.
I already upgraded to `intl: ^0.17.0-nullsafety.2` and now I get this constraint on local_auth.

This is a blocker for us, any ideas?

**Comment by TahaTesser** [comment]
Thanks, guys, it looks like a problem for sure.
Ther is no workaround on the `beta` channel 

```yaml
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-133.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.1
  local_auth: ^0.6.3+4
  intl: any
```

<details> 
<summary>logs</summary> 

```bash
PS C:\Users\Taha\AndroidStudioProjects\beta_flutter> flutterb pub get
Because local_auth >=0.6.0+1 depends on intl >=0.15.1 <0.17.0 and every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, local_auth >=0.6.0+1 is incompatible with flutter_localizations from sdk.
So, because beta_flutter depends on both flutter_localizations any from sdk and local_auth ^0.6.3+4, version solving failed.   
Running "flutter pub get" in beta_flutter...                            
pub get failed (1; So, because beta_flutter depends on both flutter_localizations any from sdk and local_auth ^0.6.3+4, versionsolving failed.)
PS C:\Users\Taha\AndroidStudioProjects\beta_flutter>
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.25.0-8.1.pre at C:\Code\flutter_beta
    • Framework revision 8f89f6505b (5 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 5.0.2 (API 21) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
```

</details>

**Comment by andreujuanc** [comment]
Thanks for confirming this @TahaTesser !

I think we should have this kind of tests so this does not happen in beta as often. I mean, we all understand what `beta software` is, but `local_auth` and `intl` are "first party" plugins and IMHO this change shouldn't have made it to the beta channel.

We removed local_auth temporarily, looking forward to add it back again.

**Comment by AnshGaikwad** [comment]
@andreujuanc You can try downgrading flutter to 1.22.5, if you want to use local_auth package in your project.

**Comment by andreujuanc** [comment]
@AnshGaikwad That's what I did last year.
Actually today in the morning we migrated to flutter v2, but now intl library is not yet on nullable. There was a workaround and we managed to build it on v2!!

**Comment by Milos5611** [comment]
@andreujuanc what workaround you have? 
This becomes a huge problem for us to release.

**Comment by andreujuanc** [comment]
I copied pasted it from somewhere else

```yaml
dependency_overrides: 
  # For intl
  intl: ^0.17.0
  intl_translation:
    git:
      url: git://github.com/dart-lang/intl_translation.git
      ref: 1a18d5a676ce94918f486ef699cb479f7578fdb6
```

Trust no-one
