### ISSUE TITLE
FAILURE: Build failed with an exception. <gnu/stubs-32.h>

### ISSUE THREAD

**Issue by ErnestoAbram** [flutter/flutter#72415]
In Ubuntu 20 when I compile for Android get this error:
```bash
* What went wrong:
Execution failed for task ':bitmap:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/ernesto/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/ernesto/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/bitmap-0.0.6/android/.cxx/cmake/debug/armeabi-v7a --target bitmap} ....

/snap/flutter/current/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
  # include <gnu/stubs-32.h>
            ^~~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.
```
```bash
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.24.0-10.2.pre at /home/ernesto/snap/flutter/common/flutter
    • Framework revision 022b333a08 (hace 4 semanas), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ernesto/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-1)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Web Server (web)                 • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 87.0.4280.88
```
I try to install libc-32 and other thinks, but it don work anywhere.

Flutter is working for me in other projects in Android and web.

```yaml
this is my puscpec:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  firebase_ml_vision: ^0.9.10
  bitmap: ^0.0.6
  #light: ^1.0.0 
  


  edge_detection: ^1.0.5

  intl: ^0.16.1

  provider: ^4.1.3


  fluttertoast: ^4.0.1

  slider_button: ^0.5.0

  url_launcher: ^5.7.8
  geolocator: ^5.1.3
  font_awesome_flutter: ^8.10.0

  pdf: ^1.9.0
  flutter_signature_pad: ^2.0.2

  torch_compat: ^1.0.2

  camera: ^0.5.8+11

  google_fonts: ^1.1.1

  #flutter_webview_plugin: ^0.3.11

  #jitsi_meet: ^0.4.2

  flutter_secure_storage: ^3.3.5

  path_provider:
  path:


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/eqalogo.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
