### ISSUE TITLE
Crash during application build

### ISSUE THREAD

**Issue by MrCsabaToth** [flutter/flutter#72475]
## Steps to Reproduce

1. I have an application with 25 plugins and I hit a mysterious release-only crash. Here's the pubspec.yaml:

```
name: track_my_indoor_exercise
description: Recording indoor exercises as if circling in a Velodrome or on a running track.
publish_to: "none"

version: 1.1.17+26

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  e2e: any
  floor: any
  flutter_blue: any
  flutter_brand_icons: any
  get: any
  http: any
  intl: any
  http_parser: any
  listview_utils: any
  share_files_and_screenshot_widgets: any
  shared_preferences: any
  sqflite: any
  uni_links: any
  url_launcher: any
  wakelock: any
  charts_flutter: any
  preferences: any
  loading_overlay: any
  fab_circular_menu: any
  device_info: any
  expandable: any
  progress_indicators: any
  data_connection_checker: any
  datetime_picker_formfield: any
  file_picker: any
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: any
  floor_generator: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
```
It's important to note that this is the third time I experience release only crash problems. This latest was with `file_picker`, a month ago it was with `flutter_blue` out of the blue. This is a systemic issue that once the android port is scaffolded it can become stale. After "nuking" and re-creating the android port the new code is significantly different and not just because now Kotlin (and Swift) is the default. So I was chasing the https://github.com/miguelpruivo/flutter_file_picker/issues/545 issue. Unfortunately my application is not open source yet.

2. Exit all running Android Studio instances.
3. Back up the android and ios folders to a temporary location.
4. Delete the android and ios folders in the project.
5. Still in the project folder `flutter create .`
6. Use a merge tool and re-introduce some intricate details certain plugins needed (extra permissions or other manifest changes for example), copy your launcher icons, etc. Rename the package route if needed. This is time consuming.
7. Start Android studio.
8. After the dust settled open pubspec.yaml and click on get (I know there's command line but this is how I went)
9. At this point I don't remember if I opened a second Android Studio with the android project only. When I do that a make command generates a bunch of stuff for each plugin.
10. In the Flutter project Android Studio click the menu: Build > Flutter > Build App Bundle

**Expected results:** The build start and either it fails with error or success messages.

**Actual results:** The build seemingly hangs forever (because crash happened in a background process).

(BTW there's no Build window, just a "Messages" window, I want to see the full Build output)

<details>
  <summary>flutter_01.log</summary>

## command

flutter --no-color attach --machine --device-id=c98b8376 lib/main.dart

## exception

StateError: Bad state: Future already completed

```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:56:18)
<asynchronous suspension>
#2      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:263:11)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-10.2.pre at /home/csaba/flutter
    • Framework revision 022b333a08 (4 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/csaba/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/csaba/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /home/csaba/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • ONEPLUS A6003 (mobile) • c98b8376   • android-arm64  • Android 10 (API 29)
    • Web Server (web)       • web-server • web-javascript • Flutter Tools
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```
</details>
