### ISSUE TITLE
Text Widget change original text when locale is set to RTL 

### ISSUE THREAD

**Issue by ashamp** [flutter/flutter#72606]
![image](https://user-images.githubusercontent.com/6055170/102654192-94573400-4189-11eb-9924-77f84f154ac6.png)

**Comment by ashamp** [comment]
➜  flutter_arabic_issue flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 1.22.4 at /Users/macbook/Documents/flutter
    • Framework revision 1aafb3a8b9 (5 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9002
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPhone 6s (mobile) • 446368C7-C29F-458E-A7FD-72FECCAB11D9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4
      (simulator)

**Comment by ashamp** [comment]
```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool isArabic = true;
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Arabic issue',
      localizationsDelegates: [
        GlobalCupertinoLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [Locale('ar'), Locale('en')],
      locale: isArabic ? Locale('ar') : Locale('en'),
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text('1 USD = 6.4 CNY'),
              Text('helo word'),
              Text('helo helo, word.'),
              Text('مرحبا'),
              Text('curren language is ${isArabic ? 'ar' : 'en'}'),
              FlatButton(
                onPressed: () {
                  setState(() {
                    isArabic = !isArabic;
                  });
                },
                color: Color(0xff00ff00),
                child: Text('switch language'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

**Comment by ashamp** [comment]
pubspec.yaml
```
name: flutter_arabic_issue
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

    flutter:

  uses-material-design: true

```
