### ISSUE TITLE
TextField broken after Flutter upgrade

### ISSUE THREAD

**Issue by ed4ed** [flutter/flutter#72719]
I just upgraded flutter and I started having problems with TextField. Basically as soon as it gets focus (either by tap or with autofocus enable), it will kill the current page/route. There is a 2 second delay between the focus in the widget and the exit.
Here is my code, but it happens everywhere I use a TextField:

```
import 'dart:core';
import 'package:capture/utils/SizeConfig.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_blue/flutter_blue.dart';
import 'package:back_button_interceptor/back_button_interceptor.dart';
import 'package:capture/utils/CustomColors.dart';
import '../utils/RadarUtils.dart';

const String AUTH_PASSWORD = "xxx";

class ParameterAuthentication extends StatefulWidget{

  ParameterAuthentication(){}

  @override
  State<StatefulWidget> createState() {
    return _ParameterAuthentication();
  }
}

class _ParameterAuthentication extends State<ParameterAuthentication>  with WidgetsBindingObserver {
  TextEditingController _writeController;
  var _c;

  _ParameterAuthentication(){
    _writeController = TextEditingController();
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    BackButtonInterceptor.add(myInterceptor);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return DefaultTabController(
      length: 3,
      child: WillPopScope(
          onWillPop: _onBackPressed,
          child: Scaffold (
              appBar: AppBar(
                title: Text('Authentication'),
              ),
              body:  Card(
                margin: EdgeInsets.fromLTRB(SizeConfig.safeBlockHorizontal*2, SizeConfig.safeBlockVertical*1, SizeConfig.safeBlockHorizontal*2, SizeConfig.safeBlockVertical*1),    //(10, 10, 10, 10), old
                elevation: 1,
                color: CustomColors.StartecCardGrey,
                child: _buildParameterAuthView(),
              )
          )
      ),
    );
  }

  /// Function That Triggers when you hit the back key
  bool myInterceptor(bool stopDefaultButtonEvent, RouteInfo routeInfo) {
    print("BACK BUTTON!"); // Do some stuff.
    _onBackPressed();
    //Navigator.pop(context); //Not needed here
    return false;
  }

  Future<bool> _onBackPressed() async {
    return Future.value(false);
  }

  /// Build the Parameters List
  ListView _buildParameterAuthView() {
    List<Container> containers = new List<Container>();
    var _c;

    //Add the title
    containers.add(
      Container(
        padding: EdgeInsets.fromLTRB(SizeConfig.safeBlockHorizontal*0, SizeConfig.safeBlockVertical*1, SizeConfig.safeBlockHorizontal*1, SizeConfig.safeBlockVertical*1),   //(0, 10, 5, 10), old
        child:
        Text("Password for Admin access", style:
          TextStyle(fontWeight: FontWeight.bold,
            color: CustomColors.StartecOrange,
            fontSize: SizeConfig.safeBlockHorizontal*5.5,   //25 old
          ),
          overflow: TextOverflow.fade,
          maxLines: 1,
          softWrap: false,
        ),
      ),
    );
    //Add separator
    containers.add(
      Container(
        height: SizeConfig.safeBlockVertical*0.1, //1.0, old
        width: MediaQuery.of(context).copyWith().size.width -25,  //130 old
        color:CustomColors.StartecSeparatorGrey,),
    );
    //Add margin
    containers.add(
      Container(
        padding: EdgeInsets.fromLTRB(SizeConfig.safeBlockHorizontal*1, SizeConfig.safeBlockVertical*2, SizeConfig.safeBlockHorizontal*1, SizeConfig.safeBlockVertical*3),   //(5, 10, 5, 15), old
        height: SizeConfig.safeBlockVertical*2, //10.0, old
        width: MediaQuery.of(context).copyWith().size.width -25,  //130 old
        color: CustomColors.StartecCardGrey,),
    );

    //Add TextField for password
    containers.add(
        Container(
          child:  TextField(
            controller: _writeController,
            autofocus: true,
          ),
        )
    );

    //Add Button
    containers.add(
        Container(
          child:  FlatButton(
            child: Text("Send", style: TextStyle(color: Colors.white),),
            color: CustomColors.StartecOrange,
            onPressed: () {
              if(_c.text == AUTH_PASSWORD)
                Navigator.pop(context, true);
              else
                Navigator.pop(context, false);
            },
          ),
        )
    );

    return ListView(
      padding: const EdgeInsets.all(8),
      children: <Widget>[
        ...containers,
      ],
    );
  }

}

```

This is the flutter version I use:
```
flutter --version
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (11 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

This is the output of flutter doctor:
```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /home/eddy/flutter
    • Framework revision 7891006299 (11 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/eddy/Android/Sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/eddy/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Pixel 4a (mobile) • 0B191JEC201443 • android-arm64 • Android 11 (API 30)

! Doctor found issues in 2 categories.
```

This is my pubspec.yaml:
```
name: capture
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0" #">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adobe_xd: ^0.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_blue: ^0.7.2
  synchronized: ^2.2.0
  progress_dialog: ^1.1.0+1
  future_progress_dialog: ^0.1.1
  back_button_interceptor: ^4.0.0
  flutter_range_slider: ^1.5.0


  vector_math: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/map.png

```

If anyone could help me I would really appreciate it since my App was almost ready for production. Thank you in advance!
