### ISSUE TITLE
iOS Appstore version has many crashes on Flutter Channel beta, 1.25.0-8.1.pre

### ISSUE THREAD

**Issue by ghostgzt** [flutter/flutter#72949]
ios appstore version has many crash on Flutter Channel beta, 1.25.0-8.1.pre

@mraleph 
@aam 

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.6 19G73 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.25.0-8.1.pre at /Users/gentle/Public/Flutter
    • Framework revision 8f89f6505b (9 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

users crash log:

```
Application received signal SIGABRT
(null)
((
	0   CoreFoundation                      0x0000000199c9488c AF3F8E01-C130-3464-AD40-C5532D273483 + 1202316
	1   libobjc.A.dylib                     0x00000001ae1eac50 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000199b8d4a4 AF3F8E01-C130-3464-AD40-C5532D273483 + 124068
	3   Runner                              0x0000000102f85dd0 Runner + 171472
	4   libsystem_platform.dylib            0x00000001e30a6290 73F3E459-0F82-3377-A7D1-EF05CAE41C0A + 21136
	5   libsystem_pthread.dylib             0x00000001e30abb40 pthread_kill + 272
	6   libsystem_c.dylib                   0x00000001a2fb8b74 abort + 104
	7   Metal                               0x00000001af9af9d4 MTLGetWarningMode + 0
	8   IOGPU                               0x00000001d5e434a0 AF4EE382-C732-33EA-B942-EFE906469CB7 + 13472
	9   Metal                               0x00000001af99f990 7EBA2500-A6BB-3049-ADF3-BB6649B0E3CA + 555408
	10  IOGPU                               0x00000001d5e45150 AF4EE382-C732-33EA-B942-EFE906469CB7 + 20816
	11  AGXMetalA12                         0x00000001e42c2208 AGXMetalA12 + 2695688
	12  AGXMetalA12                         0x00000001e42f887c AGXMetalA12 + 2918524
	13  Flutter                             0x00000001037a40b0 Flutter + 2474160
	14  Flutter                             0x00000001037a7078 Flutter + 2486392
	15  Flutter                             0x00000001036b6364 Flutter + 1500004
	16  Flutter                             0x00000001036b5fe0 Flutter + 1499104
	17  Flutter                             0x00000001036d1208 Flutter + 1610248
	18  Flutter                             0x00000001036c1a1c Flutter + 1546780
	19  Flutter                             0x00000001036dc52c Flutter + 1656108
	20  Flutter                             0x00000001036c15ec Flutter + 1545708
	21  Flutter                             0x000000010369bc70 Flutter + 1391728
	22  Flutter                             0x000000010375928c Flutter + 2167436
	23  Flutter                             0x0000000103901918 Flutter + 3905816
	24  Flutter                             0x000000010380ad80 Flutter + 2895232
	25  Flutter                             0x00000001039011f8 Flutter + 3903992
	26  Flutter                             0x0000000103809af0 Flutter + 2890480
	27  Flutter                             0x000000010380b958 Flutter + 2898264
	28  CoreFoundation                      0x0000000199c10fa0 AF3F8E01-C130-3464-AD40-C5532D273483 + 663456
	29  CoreFoundation                      0x0000000199c10ba0 AF3F8E01-C130-3464-AD40-C5532D273483 + 662432
	30  CoreFoundation                      0x0000000199c0fffc AF3F8E01-C130-3464-AD40-C5532D273483 + 659452
	31  CoreFoundation                      0x0000000199c09ee4 AF3F8E01-C130-3464-AD40-C5532D273483 + 634596
	32  CoreFoundation                      0x0000000199c0921c CFRunLoopRunSpecific + 600
	33  Flutter                             0x000000010380b834 Flutter + 2897972
	34  Flutter                             0x000000010380b23c Flutter + 2896444
	35  libsystem_pthread.dylib             0x00000001e30aab40 _pthread_start + 320
	36  libsystem_pthread.dylib             0x00000001e30b3768 thread_start + 8
)

dSYM UUID: 4C6182AD-77DB-3189-9692-7CC024B6039C
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: Runner
Base Address: 0x0000000102f5c000
```

```
Application received signal SIGSEGV
(null)
((
    0 CoreFoundation 0x000000018fac1880 935533F2-35EE-314E-A760-E74521F68435 + 1202304
    1 libobjc.A.dylib 0x00000001a4a30c50 objc_exception_throw + 60
    2 CoreFoundation 0x000000018f9ba4a4 935533F2-35EE-314E-A760-E74521F68435 + 124068
    3 Runner 0x0000000101011dd0 Runner + 171472
    4 libsystem_platform.dylib 0x00000001db28d290 AD029366-1E30-32CD-8E4C-A025B49E513B + 21136
    5 Flutter 0x00000001019d134c Flutter + 4215628
    6 Flutter 0x00000001019d134c Flutter + 4215628
    7 Flutter 0x00000001019d0fdc Flutter + 4214748
    8 Flutter 0x00000001019d0c4c Flutter + 4213836
    9 Flutter 0x00000001019d0c4c Flutter + 4213836
    10 Flutter 0x00000001019af408 Flutter + 4076552
    11 Flutter 0x00000001019ae420 Flutter + 4072480
    12 Flutter 0x0000000101ab1448 Flutter + 5133384
    13 App 0x0000000108e15414 Precompiled_Stub_CallAutoScopeNative + 80
    14 App 0x0000000108e65488 Precompiled__SecureFilterImpl_14069316__newX509CertificateWrapper_14069316_1534 + 56
    15 App 0x00000001096266c0 Precompiled__SecureFilterImpl_14069316_handshake__anonymous_closure__23298 + 376
    16 App 0x0000000108e33530 Precompiled_____rootRunUnary_4048458_568 + 216
    17 App 0x0000000108e3362c Precompiled_____rootRunUnary_4048458__rootRunUnary_4048458_569 + 132
    18 App 0x00000001094186ac Precompiled__CustomZone_4048458_runUnary_18429 + 196
    19 App 0x0000000109423884 Precompiled__CustomZone_4048458_runUnaryGuarded_18644 + 116
    20 App 0x00000001093fc03c Precompiled__BufferingStreamSubscription_4048458__sendData_4048458_18034 + 192
    21 App 0x00000001092f31e4 Precompiled__BufferingStreamSubscription_4048458__add_4048458_17437 + 156
    22 App 0x00000001092f24c4 Precompiled__StreamController_4048458__add_4048458_17409 + 184
    23 App 0x00000001093f34ac Precompiled__StreamController_4048458_add_17871 + 140
    24 App 0x0000000108e4f530 Precompiled__StreamController_4048458_add_add_1025 + 44
    25 App 0x00000001096d8a04 Precompiled__Closure_0150898_dyn_call_23867 + 544
    26 App 0x0000000108e55c78 Precompiled__RawReceivePortImpl_1026248__handleMessage_1026248_1218 + 56
    27 App 0x0000000108e15210 Precompiled_Stub_InvokeDartCode + 268
    28 Flutter 0x0000000101a9dfcc Flutter + 5054412
    29 Flutter 0x0000000101aa55bc Flutter + 5084604
    30 Flutter 0x0000000101ab0168 Flutter + 5128552
    31 Flutter 0x0000000101900b28 Flutter + 3361576
    32 Flutter 0x000000010188daf0 Flutter + 2890480
    33 Flutter 0x000000010188f958 Flutter + 2898264
    34 CoreFoundation 0x000000018fa3dfa0 935533F2-35EE-314E-A760-E74521F68435 + 663456
    35 CoreFoundation 0x000000018fa3dba0 935533F2-35EE-314E-A760-E74521F68435 + 662432
    36 CoreFoundation 0x000000018fa3cffc 935533F2-35EE-314E-A760-E74521F68435 + 659452
    37 CoreFoundation 0x000000018fa36ee4 935533F2-35EE-314E-A760-E74521F68435 + 634596
    38 CoreFoundation 0x000000018fa3621c CFRunLoopRunSpecific + 600
    39 Flutter 0x000000010188f834 Flutter + 2897972
    40 Flutter 0x000000010188f23c Flutter + 2896444
    41 libsystem_pthread.dylib 0x00000001db291b40 _pthread_start + 320
    42 libsystem_pthread.dylib 0x00000001db29a768 thread_start + 8
)
dSYM UUID: 4C6182AD-77DB-3189-9692-7CC024B6039C
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: Runner
Base Address: 0x0000000100fe8000
```

```
Application received signal SIGABRT
(null)
((
	0   CoreFoundation                      0x00000001a657f9ec 6FD5304A-9759-3E22-A863-456EAB55F4CC + 1157612
	1   libobjc.A.dylib                     0x00000001ba8e8b54 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001a64824d0 6FD5304A-9759-3E22-A863-456EAB55F4CC + 120016
	3   Runner                              0x0000000102b29dd0 Runner + 171472
	4   libsystem_platform.dylib            0x00000001edff2d90 2B25322B-286E-3302-9D09-0CD510D369B4 + 28048
	5   libsystem_pthread.dylib             0x00000001ee0029e8 pthread_kill + 212
	6   libsystem_c.dylib                   0x00000001af26d8f4 abort + 100
	7   Flutter                             0x0000000103575c70 Flutter + 4758640
	8   Flutter                             0x000000010368df7c Flutter + 5906300
	9   Flutter                             0x0000000103423cf4 Flutter + 3374324
	10  Flutter                             0x0000000103422490 Flutter + 3368080
	11  Flutter                             0x0000000103422658 Flutter + 3368536
	12  Flutter                             0x00000001034a6ec4 Flutter + 3911364
	13  Flutter                             0x00000001034a3fcc Flutter + 3899340
	14  Flutter                             0x00000001034a5be8 Flutter + 3906536
	15  Flutter                             0x00000001034a41e8 Flutter + 3899880
	16  Flutter                             0x00000001033aaae0 Flutter + 2878176
	17  libsystem_pthread.dylib             0x00000001ee001b3c _pthread_start + 288
	18  libsystem_pthread.dylib             0x00000001ee006880 thread_start + 8
)

dSYM UUID: 4C6182AD-77DB-3189-9692-7CC024B6039C
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: Runner
Base Address: 0x0000000102b00000
```
```
Application received signal SIGSEGV
(null)
((
	0   CoreFoundation                      0x000000018e5c91d0 &lt;redacted&gt; + 148
	1   libobjc.A.dylib                     0x000000018d00055c objc_exception_throw + 56
	2   CoreFoundation                      0x000000018e5c9100 &lt;redacted&gt; + 0
	3   Runner                              0x00000001000a1dd0 Runner + 171472
	4   libsystem_platform.dylib            0x000000018d659338 _sigtramp + 36
	5   Security                            0x000000018ea195bc &lt;redacted&gt; + 304
	6   Security                            0x000000018ea1a8f4 &lt;redacted&gt; + 52
	7   Security                            0x000000018ea1b160 &lt;redacted&gt; + 248
	8   libsystem_trace.dylib               0x000000018d676204 _os_activity_initiate + 76
	9   Security                            0x000000018ea18e78 &lt;redacted&gt; + 232
	10  Security                            0x000000018ea18f00 SecTrustEvaluate + 64
	11  Flutter                             0x00000001009ca184 Flutter + 4120964
	12  Flutter                             0x0000000100ac1c0c Flutter + 5135372
	13  Flutter                             0x0000000100ac02b0 Flutter + 5128880
	14  Flutter                             0x0000000100abfe44 Flutter + 5127748
	15  Flutter                             0x0000000100b44c0c Flutter + 5671948
	16  Flutter                             0x0000000100afc758 Flutter + 5375832
	17  libsystem_pthread.dylib             0x000000018d65d850 &lt;redacted&gt; + 240
	18  libsystem_pthread.dylib             0x000000018d65d760 &lt;redacted&gt; + 0
	19  libsystem_pthread.dylib             0x000000018d65ad94 thread_start + 4
)

dSYM UUID: 4C6182AD-77DB-3189-9692-7CC024B6039C
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: Runner
Base Address: 0x0000000100078000
```

**Comment by iapicca** [comment]
@ghostgzt 
can you provide your `flutter run --release -v` as well

**Comment by ghostgzt** [comment]
i don't crash but many appstore users crash!

**Comment by iapicca** [comment]
@ghostgzt 
can you provide the list of devices which are experiencing crashes

**Comment by ghostgzt** [comment]
> @ghostgzt
> can you provide the list of devices which are experiencing crashes
![微信截图_20201226213619](https://user-images.githubusercontent.com/4105507/103152405-8bd2af00-47c2-11eb-92c1-1357efec154f.png)

**Comment by aam** [comment]
@flutter-symbolizer-bot 92ae191c17  release arm64 https://github.com/flutter/flutter/issues/72949#issue-774680072

**Comment by aam** [comment]
@flutter-symbolizer-bot engine#92ae191c17  release arm64 https://github.com/flutter/flutter/issues/72949#issue-774680072

**Comment by aam** [comment]
@flutter-symbolizer-bot force ios release arm64 engine#92ae191c17  https://github.com/flutter/flutter/issues/72949#issue-774680072

**Comment by TahaTesser** [comment]
Hi @ghostgzt 
Can you please provide your `pubspec.yaml`
Thank you

**Comment by ghostgzt** [comment]
> Hi @ghostgzt
> Can you please provide your `pubspec.yaml`
> Thank you

```
name: xxx
description: xxx

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter  


  cupertino_icons: ^0.1.2


  event_bus: ^1.1.0

  io: ^0.3.3
  

  shared_preferences: ^0.5.4+9

  connectivity: ^0.4.6+1
  fluttertoast: ^4.0.1

  flutter_staggered_grid_view: ^0.3.0

  sqflite: ^1.1.7+2


  simple_gesture_detector: ^0.1.3
  extended_image: any #^1.5.0
  extended_text: any #^4.1.0

  intl: any #^0.16.1

  gbk2utf8: ^1.0.0
  big5: ^0.0.4

  url_launcher: ^5.2.2
  draggable_scrollbar: ^0.0.4
  dragable_flutter_list: ^1.0.2
  share_extend: ^1.1.1
  path_provider: ^1.4.4
  flutter_speed_dial: ^1.2.4
  pull_to_refresh: ^1.5.7
  image: ^2.1.4

  provider: ^4.1.2


  archive: ^2.0.13
  file_picker: 1.6.1
  uni_links: ^0.4.0


  qr_flutter: ^3.1.0




  ext_storage: ^1.0.3

  liquid_progress_indicator: ^0.3.2

  flutter_local_notifications: ^1.4.4



  flutter_icons: ^1.1.0  
  pretty_json: ^1.0.9

  sliding_sheet: ^0.3.5

  shifting_tabbar: ^0.3.1

  filesystem_picker: ^1.0.1
  uuid: ^2.2.0
  solid_bottom_sheet: ^0.1.9
  flutter_highlight: ^0.6.0
  hive: ^1.4.4
  html: ^0.14.0+3
  meedu_player: any #^0.4.0+3
  dio:
    git: 
      url: https://github.com/flutterchina/dio.git
      path: dio
  flustars: ^0.3.2
  flutter_swiper: any
  install_apk_plugin: any
  flutter_native_image: any
  keyboard: any
  permission: any
  flutter_cache_manager: any
  imei_plugin: any
  flutter_umeng_analytics_fork: any
  package_info: any
  flutter_statusbar_manager: any



dev_dependencies:

flutter:

  uses-material-design: true

  assets:
    - img/
   
```
