### ISSUE TITLE
[MacOS] Apple rejects MacOS archive with "ITMS-90332: Invalid Symbolic Link"

### ISSUE THREAD

**Issue by GyuriMajercsik** [flutter/flutter#73028]
I created a release build for MacOS with Flutter master channel (v1.26.0-2.0.pre.137) and uploaded the archive to Apple with xcode.

The binary was uploaded successfully but Apple rejected it due to bellow errors: 
> ITMS-90332: Invalid Symbolic Link - The symbolic link 'com.example.ios.pkg/Payload/example.app/Contents/Frameworks/FlutterMacOS.framework/Headers' resolves to an invalid location. Make sure that the symbolic link does not resolve to itself, and that the location exists and is contained within the app bundle.
> 
> ITMS-90332: Invalid Symbolic Link - The symbolic link 'com.example.ios.pkg/Payload/example.app/Contents/Frameworks/FlutterMacOS.framework/Modules' resolves to an invalid location. Make sure that the symbolic link does not resolve to itself, and that the location exists and is contained within the app bundle.

I attached the full logs of `flutter build macos --release -v` at the end of this ticket. 

I also noticed that `Runner.xcodeproj` was modified by the build but I'm not sure if it is related:  
![image](https://user-images.githubusercontent.com/1482221/103204779-c04c8500-4900-11eb-997e-0f641c8d0f2e.png)

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.137, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.137 at /Users/gyuri/tools/flutter
    • Framework revision 8f5d0371af (2 days ago), 2020-12-26 11:07:36 +0330
    • Engine revision f5364860ab
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gyuri/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

[build.log](https://github.com/flutter/flutter/files/5746629/build.log)

**Comment by stuartmorgan** [comment]
Can you provide the output of running `ls -l` on the `example.app` in your build directory?

**Comment by TahaTesser** [comment]
Hi @GyuriMajercsik 
Please provide details asked above and your `pubspec.yaml` 
Thank you

**Comment by GyuriMajercsik** [comment]
Sure, here are the requested information: 

```
gyuri@Gheorghes-MacBook-Pro macos % ls -l
total 16
drwxr-xr-x   4 gyuri  staff   128 Dec 28 14:24 Build
drwxr-xr-x   5 gyuri  staff   160 Dec 28 14:24 Logs
drwxr-xr-x  79 gyuri  staff  2528 Dec 28 14:29 ModuleCache.noindex
drwxr-xr-x   2 gyuri  staff    64 Dec 28 14:24 SourcePackages
-rw-r--r--   1 gyuri  staff   351 Dec 28 14:25 info.plist
-rw-r--r--   1 gyuri  staff   420 Dec 28 14:25 pod_inputs.fingerprint
```

```
name: deescus
description: Deescus Flutter application

version: 1.2.1+72

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  firebase_analytics: ^6.3.0
  firebase_dynamic_links: ^0.6.3
  firebase_crashlytics: ^0.2.4
  firebase_storage: ^5.2.0
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.7.2

#  this is only until Firebase Cloud Storage is available on web
  firebase: ^7.3.2

  flutter_screenutil: ^3.2.0
  logging: ^0.11.4
  get_it: ^4.0.2
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0
  #  this was set for Web and Mac
  flutter_svg: ^0.19.1
  #  flutter_svg: ^0.17.4
  shared_preferences: ^0.5.12+4
  device_id: ^0.2.0
  device_info: ^1.0.0
  package_info: ^0.4.3+2
  enum_to_string: ^1.0.13
  after_layout: ^1.0.7+2
  flare_flutter: ^2.0.6
  stream_transform: ^1.2.0
  country_code_picker: ^1.6.2
  responsive_builder: ^0.3.0
  webview_flutter: ^1.0.7
  universal_html: ^1.2.3
  url_launcher: ^5.7.10
  reorderables: ^0.3.2
  file_picker_cross: ^4.2.6
  rxdart: ^0.24.1
  mime: ^0.9.7

  #  this is for MacOS
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 927f8cbc09b35d85245c095f2db8df9b186f6618

  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr
      ref: 1.0-dev

  flutter:
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
#  flutter_cupertino_localizations: ^1.0.1


  cupertino_icons: ^0.1.2

dev_dependencies:
  mockito: ^4.1.1
  #  flutter_launcher_icons: ^0.7.5

  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/config/development/
    - assets/config/production/

  fonts:
    - family: HKGrotesk
      fonts:
        - asset: assets/fonts/HKGrotesk-Regular.otf
          weight: 400
        - asset: assets/fonts/HKGrotesk-Bold.otf
          weight: 700
        - asset: assets/fonts/HKGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/HKGrotesk-SemiBold.otf
          weight: 600
```
