### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider))

### ISSUE THREAD

**Issue by onurc4kir** [flutter/flutter#73209]
I'm getting this error on android when run my app. I've already tried flutter clean and update some packages to latest version. 

I wasn't getting this error when it stopped working on the project 2-3 weeks ago.

`MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)`

Packages that I use.

**Edit:** Error is getting out when I remove `flutter_facebook_auth: ^1.0.2+2` package.

```
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  #cupertino_icons: ^1.0.0

  google_fonts: ^1.1.1
  provider: ^4.3.2+2
  #page transition animation
  page_transition: '^1.1.7+2'
  #for some UI elements not very essential
  flui: 0.9.2
  #ios style date picker
  flutter_datetime_picker: ^1.4.0
  get_it: ^5.0.1
  #Height, age, range slider
  flutter_xlider: ^3.4.0
  #For picking image from gallery
  image_picker: ^0.6.7+12
  image_pickers: ^1.0.8+7

  #For reading icons at flutter
  flutter_svg: ^0.19.1
  flutter_icons: ^1.1.0

  #For showing loading icon when provider state changes
  loading_overlay: ^0.2.1
  flutter_styled_toast: ^1.4.0+1
  #Firebase Packages
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.0.1
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.6
  flutter_facebook_auth: ^1.0.2+2
  #firebase_database: ^4.4.0

  #maps and geolocation packages Using At MapPage
  google_maps_flutter: ^1.0.6
  google_place: ^0.3.3
  #getting user current location.
  geolocator: ^6.1.4

  #cluster manager for Google Maps. Using at MapPage
  google_maps_cluster_manager: ^0.2.0

  #to make bottom container for map Using at MapPage
  sliding_up_panel: ^1.0.2
  #To get LatLng from an address or to get Address From an LatLng
  geocoder: ^0.2.1

  #For swipe cards
  swipe_stack: ^1.0.0

  #For creating timing indicator at match and likes page. Look at circular avatars
  percent_indicator: ^2.1.8

  #to make location search based on geohash.
  geoflutterfire: ^2.2.1

  #for local data managment. Key value pairs
  shared_preferences: ^0.5.12+4
  #cache image and loading indicator fo them
  cached_network_image: ^2.4.1

  #to draw chart. Used at venue detail page.
  fl_chart: ^0.12.0

  # Create unique id for firebase documents
  uuid: ^2.2.2

  path_provider: ^1.6.24
  #some stream operations do
  rxdart: ^0.24.1
  #Google recaptcha plugin
  flutter_recaptcha_v2: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
