### ISSUE TITLE
[shared_preferences] Windows Desktop app : Please enable Developer Mode in your system settings 

### ISSUE THREAD

**Issue by jeremy-giles** [flutter/flutter#73207]
I've an error when I run my Windows Desktop application.
Without shared_preferences dependencie my application start, not with.

I activated the developer option on my Windows and my application is running. Is this the correct handling / configuration? I haven't seen anything in the documentation on this.

**Error**
```
Running "flutter pub get" in barcode_generator...
Building with plugins requires symlink support.

Please enable Developer Mode in your system settings. Run
  start ms-settings:developers
to open settings.
```

**pubspec.yaml**
```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^3.2.0
  image: ^2.1.19

  filepicker_windows: ^1.0.0

  shared_preferences: ^0.5.12+4
```

**Flutter config**
```
Settings:
  enable-web: true
  enable-windows-desktop: true

Analytics reporting is currently enabled.
```

**Flutter Doctor**
```
[√] Flutter (Channel master, 1.26.0-2.0.pre.167, on Microsoft Windows [version 10.0.18363.1256], locale fr-CH)
    • Flutter version 1.26.0-2.0.pre.167 at C:\Users\***\Documents\Flutter\SDK\flutter\flutter
    • Framework revision d3a2259541 (2 days ago), 2020-12-31 15:14:03 -0500
    • Engine revision 82b4ae86d6
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\***\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\***\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30517.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.18363.1256]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 87.0.664.66
```
