### ISSUE TITLE
Google Sign In with Firebase Auth return error on older android

### ISSUE THREAD

**Issue by ArvinCS** [flutter/flutter#73229]
I'm using Google Sign In combined with firebase authentication for my app. They work well until I updated those packages into the latest version.

I tested it on 2 different versions of android (Pie and Marshmellow), pie works well but marshmallow returns an error every I logged in the google account.

Here is the error:

> E/com.google.android.gms.internal.firebase-auth-api.zzvj( 4137): Failed to parse error for string [ Error 400 (Bad Request)!!1 {margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px} > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}400. That’s an error. Your client has issued a malformed or illegal request. That’s all we know.] with exception: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

The code:
```
GoogleSignIn _googleSignIn = GoogleSignIn();
Future<bool> trySignIn() async {
  try {
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth = await googleUser?.authentication;

    final auth.AuthCredential credential = auth.GoogleAuthProvider.credential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );

    _firebaseUser = (await _firebaseAuth.signInWithCredential(credential)).user; // error in this line

    Brand.currentBrand = Brand(_firebaseUser.uid);

    return true;
  } catch (error) {
    print(error); 
  }
  return false;
}
```

Pubspec.yaml:
```
name: giveaway_admin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.4+1
  google_sign_in: ^4.5.1
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  dio: ^3.0.10
  auto_size_text: ^2.1.0
  flutter_feather_icons: ^1.0.3
  image_picker: ^0.6.7+15
  intl: ^0.16.1
  shimmer: ^1.1.2
  draggable_scrollbar: ^0.0.4
  carousel_slider: ^2.3.1
  fluttertoast: ^7.1.6
  flutter_datetime_picker: ^1.4.0
  ntp: ^1.0.7
  uuid: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/giveawayindo.png
  - images/giveawayindo-white.png
  - images/icon-giveawayindo.png
  - images/icon-giveawayindo-white.png
  - images/google.png
  - images/icon-app-giveawayindo.png
```

My flutter doctor -v:

> [√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
>     • Flutter version 1.22.5 at C:\flutter
>     • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
>     • Engine revision ae90085a84
>     • Dart version 2.10.4
> 
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
>     • Android SDK at C:\Users\Arvin\SDK\Android
>     • Platform android-29, build-tools 29.0.0
>     • ANDROID_HOME = C:\Users\Arvin\SDK\Android
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 46.0.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code, 64-bit edition (version 1.52.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.18.0
> 
> [√] Connected device (1 available)
>     • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
> 
> ! Doctor found issues in 1 category.
