### ISSUE TITLE
WebView on iOS seems to have a strange behavior on the navigationDelegate

### ISSUE THREAD

**Issue by alexanderchmielewski** [flutter/flutter#73242]
Hi all,

I'm building a simple WebView for an online magazine both for Android and for iOS.
```
webview_flutter: ^1.0.7
```
The online magazine runs on Wordpress.

The Wordpress site also has clickable display ads in it.

My main goal is to avoid the WebView itself from navigation away from the BaseUrl.
But the user shall be able to launch external links (like external links in articles or even ads).

On Android it was fairly easy creating a NavigationDelegate like this
```
navigationDelegate: (NavigationRequest request) {
                      if (request.url.startsWith(baseUrl)) {
                        print('allowing navigation to $request');
                        return NavigationDecision.navigate;
                      } else {
                        print('blocking navigation to $request}');
                        launchUrl(request.url);
                        return NavigationDecision.prevent;
                      }
```

im using the 
```
url_launcher: ^5.7.10
```
dependency to launch external Urls in a separate browser.

This totally worked fine on Android.

But moving on to iOS all the external loaded links via JavaScript etc. triggered the NavigationDelegate to fire each and every time.

Luckily I got rid of it by using the variable isForMainFrame, so I adopted my NavigationDelegate a bit.

```
navigationDelegate: (NavigationRequest request) {
                      if (request.url.startsWith(baseUrl) {
                        print('allowing navigation to $request');
                        return NavigationDecision.navigate;
                      } else if (request.isForMainFrame) {
                        print('allowing navigation to $request');
                        launch(request.url);
                        return NavigationDecision.prevent;
                      } else {
                        print('blocking navigation to $request}');
                        return NavigationDecision.prevent;
                      }
                    },
```

the request.isForMainFrame is returned true if I explicitly click on an external link, which starts not with the baseUrl. And all the Sideloading thing is blocked by the else block.

The next challenge I encountered is, that the online magazine uses a third party consent management platform which auto loads via JavaScript but runs the else-block.

As a result of that I needed to adjust the very first line of the NavigationDelegate in order to allow the baseUrl AND the url of the third party site to function properly in my WebView.

So far so good ...
But today I noticed, that all embeds like YouTube / Twitter etc.(via iFrame or so) within an article are also triggering navigationDelegate resulting from the code above into a NavigationDecision.prevent and the embed won't appear in the WebView at all.

As a workaround I created a simple handler method which manages a WhiteList so that my NavigationDelegate looks like this

```
navigationDelegate: (NavigationRequest request) {
                      if (isWhiteListed(request.url)) {
                        print('allowing navigation to $request');
                        return NavigationDecision.navigate;
                      } else if (request.isForMainFrame) {
                        print('allowing navigation to $request');
                        launch(request.url);
                        return NavigationDecision.prevent;
                      } else {
                        print('blocking navigation to $request}');
                        return NavigationDecision.prevent;
                      }
                    }
```

The problem that I see here is the general maintainability of the App since I need to either create a huge whitelist beforehand, create something like a cloudConfig. Or always create a breaking change version of the app, when something new needs to be whitelisted.

Is this behavior intended on iOS, that the NavigationDelegate is triggered much more than on Android?

**Comment by pedromassangocode** [comment]
Hi @alexanderchmielewski 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml`, the steps to reproduce the issue, the actual vs expected result and a minimal complete reproducible code sample?
Thank you

**Comment by alexanderchmielewski** [comment]
Hi @pedromassangocode,

thanks for your response.

flutter doctor -v returns:
```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    de-DE)
    • Flutter version 1.22.5 at /Users/alchmi/development/sdk/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/alchmi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • CC8351FC-AEBD-43A3-B0FD-77E9461C5F95 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 3 categories.
```


### pubspec.yaml
```
name: webview_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### Minimalistic Code Example
```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  String initialUrl = "https://www.zeitjung.de";

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WebView(
          initialUrl: initialUrl,
          javascriptMode: JavascriptMode.unrestricted,
          navigationDelegate: (NavigationRequest request) {
            if (request.url.startsWith(initialUrl)) {
              print('allowing navigation to $request');
              return NavigationDecision.navigate;
            } else {
              print('launching external navigation to $request');
              launch(request.url.toString());
              return NavigationDecision.prevent;
            }
          }),
    );
  }
}
```


### Expected Behavior (Both on Android and iOS)
Only explicit clicks within the WebView will trigger the navigation delegate and according to the function above there is a check if the requested url starts with the `initialUrl`. 
Also all embedded content will be displayed like Youtube Videos.

### Actual Behavior
Working as expected on Android

**Problems on iOS** 
All side loaded content from ads or YouTube video embeds will trigger the else block resulting in a new browser to be opened.
For YouTube embed example change the initialUrl to `https://www.zeitjung.de/kinofilme-highlights-2021/`

### Workaround minimalistic code with YouTube embed
```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  String initialUrl = "https://www.zeitjung.de/kinofilme-highlights-2021/";

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WebView(
          initialUrl: initialUrl,
          javascriptMode: JavascriptMode.unrestricted,
          navigationDelegate: (NavigationRequest request) {
            if (request.url.startsWith(initialUrl)
            || request.url.startsWith("https://www.youtube.com")) {
              print('allowing navigation to $request');
              return NavigationDecision.navigate;
            } else if (request.isForMainFrame) {
              print('allowing navigation to $request');
              launch(request.url);
              return NavigationDecision.prevent;
            } else {
              print('blocking navigation to $request}');
              return NavigationDecision.prevent;
            }
          }),
    );
  }
}
```
