### ISSUE TITLE
[plugins/share] sharing text from iOS to gmail app, text duplicates in subject and text is duplicated twice in body

### ISSUE THREAD

**Issue by mehulcs** [flutter/flutter#73304]
## Steps to Reproduce

1. Run `flutter create share_bug`.
2. Update the files as follows:

**pubspec.yaml**
```yaml
name: share_bug
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  share: ^0.6.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
**main.dart**

Replace `_incrementCounter` function with below,

```
  void _incrementCounter() {
    Share.share('check out my website https://example.com');
  }
```
 
3.1 Run the application and click on the floating action button plus.
3.2 From the bottom modal menu click on the Gmail icon.

**Expected results:** 
Gmail app should app opens with a comose email screen that auto-fills the body of the email with the text shared from the share plugin that is `check out my website https://example.com`.
.

**Actual results:**
Gmail app opens with a compose email screen but, the subject of the email has prefilled the shared text, and also the body of the email includes shared text twice. Screenshot below,

<img src="https://user-images.githubusercontent.com/26503020/103625469-076df200-4f61-11eb-883d-a9a9315e441e.jpg" width="300">

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on macOS 11.1 20C69, locale en-GB)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[!] Android Studio (not installed)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

</details>
