### ISSUE TITLE
while Making any Http Request on real device to server by using IP and port   getting SocketException and  wrong port number in logs

### ISSUE THREAD

**Issue by zubairshahzad** [flutter/flutter#73325]
i have created web service on my personal server in same  network .. this web server is working fine  and available on same network .
i have  test with postman from android device . and i also create one native  andorid application using  java  .its working fine in native android .

but in a flutter, i have  test  three  libraries  getting below results  please help to fix  this  issue

```dart
static String baseurl ="http://10.183.121.43:5000/";

try { Response response = await Dio().get(constant.baseurl+"hello/"); print(response); } catch (e) { print(e); }
try {
                                     await RawSocket.connect("10.183.121.43", 5000);
                                   } catch (e) {
                                     print(e);
                                   }
```

Error  :
SocketException: OS Error: Connection timed out, errno = 110, address = 10.183.121.43, port = 55705
----------

```yaml
http: 0.12.2
  logs:
    git:
      url: https://github.com/pq/logs.git
      ref: master
  rflutter_alert: 1.0.3
  shared_preferences: 0.5.12+4
  image_picker: 0.6.7+17
  dio: 3.0.10
  progress_dialog: 1.2.4
  location: 3.0.0
```
