### ISSUE TITLE
[web]: NetworkImage crash while loading images

### ISSUE THREAD

**Issue by ConcenTech** [flutter/flutter#73327]
Flutter 1.25.0-8.1.pre

After upgrading, running my project from vscode (F5 or `Run > Start Debugging`) results in my  network images not being visible and text font to be different. No errors are shown.

If I use `flutter run` in the terminal, my app performs as expected.

If I run from vscode, under sources in chrome dev tools there is a canvaskit package not present when using `flutter run`
unpkg.com > canvaskit-wasm@0.19.0/bin

**Comment by pedromassangocode** [comment]
Hi @ConcenTech 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` and a minimal complete reproducible code sample?
Thank you

**Comment by ConcenTech** [comment]
>  [√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-GB)
>     • Flutter version 1.25.0-8.1.pre at C:\src\flutter
>     • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
>     • Engine revision 92ae191c17
>     • Dart version 2.12.0 (build 2.12.0-133.2.beta)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Users\kgcar\AppData\Local\Android\sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 4.1.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [√] VS Code (version 1.52.1)
>     • VS Code at C:\Users\kgcar\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.18.0
> 
> [√] Connected device (2 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
>     • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66
> 
> • No issues found!


Pubspec from code example included, as reproducible
```
name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

```


Code Example:
Create a new flutter project and use the demo template. 
Add:
`Image.network(
                    'https://prevention.cancer.gov/sites/default/files/uploads/news_and_event/download-icon.png')`
This image is just an example I grabbed, not the one I actually use.

Run from the Run menu in vscode.
Run from the terminal with 'flutter run'
Compare the two side by side. The fonts will be different & the image will only show with `flutter run`
