### ISSUE TITLE
Allow including additional license files in NOTICES with pubspec.yaml configuration

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#73363]
Occasionally, assets will have an additional license file that should be distributed with the application (for example, fonts, images, et cetera).

FYI @Hixie as the license expert for whether this is OK.

While it is possible to add these files as assets and then use the existing framework infrastructure to load and parse them, it seems like it would be more useful to allow the tool to bundle them into NOTICES along with the existing license bundling logic.

This could be done by specifying the additional license files in the pubspec.yaml:

```yaml
flutter:
  assets:
    - assets/some_licensed_art.png
  licenses:
    - assets/some_licensed_art_license.txt
```

* This file would not be available as an asset, instead it would be concatenated into the license file.
* This would work for transitive dependencies as well.
