### ISSUE TITLE
App crashed after setting font family

### ISSUE THREAD

**Issue by lordlamee** [flutter/flutter#73763]
After the recent upgrade, I have been experiencing fatal crashes once I set the font family
//MAIN.DART

```
`MaterialApp(
           theme: ThemeData(
             fontFamily: "ProximaNova",
           ),
          home: SplashScreen(),
        ),`
```

//CONSOLE ERROR LOG 

```
Syncing files to device TECNO CF7...
E/flutter (10690): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter (10690): 
F/flutter (10690): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
F/libc    (10690): Fatal signal 6 (SIGABRT), code -6 in tid 10721 (1.ui), pid 10690 (xample.paxnaira)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'TECNO/H399/TECNO-CF7:8.1.0/O11019/BCDEFH-200630V244:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 10690, tid: 10721, name: 1.ui  >>> com.example.paxnaira <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
'
    r0 00000000  r1 000029e1  r2 00000006  r3 00000008
    r4 000029c2  r5 000029e1  r6 94efd324  r7 0000010c
    r8 00000000  r9 00000000  sl 94efd4a8  fp 94efd4a8
    ip afb3824c  sp 94efd310  lr b206289d  pc b205c3ee  cpsr 20070030
backtrace:
    #00 pc 0001a3ee  /system/lib/libc.so (abort+63)
    #01 pc 000127c3  /data/app/com.example.paxnaira-a6xnSwZntrMrBQq8cPRS6A==/lib/arm/libflutter.so (offset 0x1002000)
Lost connection to device.




**flutter doctor -v **


[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\OG\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\OG\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • TECNO CF7 (mobile) • 041901193J004025 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by darshankawar** [comment]
@lordlamee 
I tried a sample font family on latest stable using Android 8.1.0 device which compiled and ran the app properly without any issues.

<img width="373" alt="Screenshot 2021-01-12 at 3 29 31 PM" src="https://user-images.githubusercontent.com/67046386/104299244-fdad3700-54ea-11eb-827c-d90e04b07a02.png">

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        fontFamily:'NotoSansKR'
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • AOSP on IA Emulator (mobile)        • emulator-5556
      • android-x86 • Android 9 (API 28) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.

```

</details>

Can you provide as much details about the crash as possible ? Do you see the crash consistently everytime ?
Also provide `flutter run --verbose`, `pubspec.yaml`.

**Comment by lordlamee** [comment]
@darshankawar Yes I get the crash consistently every time

It also crashes with the same error log if I set the font family in the `TextStyle` in any text widget.

It also occurred with different projects 

```
**pubspec.yaml**

description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_icons: ^1.1.0
  pin_code_fields: ^6.0.1
  equatable: ^1.2.5
  provider: ^4.3.2+3
  dartz: ^0.9.2
  fdottedline: ^1.0.1
  bezier_chart: ^1.0.17+1
  local_auth: ^0.6.3+4
  connectivity: ^2.0.2
  http: ^0.12.2
  get_it: ^5.0.3
  shared_preferences: ^0.5.12+4
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/ProximaNova-Regular.ttf
        - asset: fonts/ProximaNova-RegularIt.ttf
        - asset: fonts/ProximaNova-Semibold.ttf
        - asset: fonts/ProximaNova-SemiboldIt.ttf
        - asset: fonts/ProximaNova-BoldIt.ttf
        - asset: fonts/ProximaNova-Bold.ttf
        - asset: fonts/ProximaNova-ExtrabldIt.ttf
        - asset: fonts/ProximaNova-Extrabld.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**flutter doctor --verbose**

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\OG\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\OG\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```
