### ISSUE TITLE
google_maps_flutter_web Polyline patterns not working

### ISSUE THREAD

**Issue by BoHellgren** [flutter/flutter#73779]
I use the following keywork on the GoogleMap widget:
 polylines: Set<Polyline>.of(polylines.values)
Where polylines is set as follows:
```
polylineCoordinates = decodeEncodedPolyline(r"_lgiJ_hkmBs@eEiB_@NsF`CR? ...
    PolylineId id = PolylineId("poly");
    Polyline polyline = Polyline(
        polylineId: id,
        color: Colors.red,
        width: 3,
        patterns: [PatternItem.dash(15), PatternItem.gap(5)],
        points: polylineCoordinates);
    polylines[id] = polyline;
```
This results in a dashed line on Android, as it should. But the same code gives a solid line on web.

**Comment by pedromassangocode** [comment]
Hi @BoHellgren 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by BoHellgren** [comment]
flutter doctor -v
```
D:\AndroidStudioProjects\nds_konst>flutter doctor -v
[√] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Version
    10.0.18363.1316], locale sv-SE)
    • Flutter version 1.25.0-8.2.pre at D:\flutter_windows\flutter
    • Framework revision b0a2299859 (9 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.42.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • SM G970F (mobile) • RF8M3164L6B • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      87.0.4280.141
    • Edge (web)        • edge        • web-javascript • Microsoft Edge
      87.0.664.66

• No issues found!

D:\AndroidStudioProjects\nds_konst>
```
pubspec.yaml
```
name: ndskonst
description: Hitta konsten i NDS

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+8

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^1.0.10
  google_maps_flutter_web: ^0.1.0+8
  geolocator: ^6.1.13
  js: ^0.6.2
  firebase_admob: ^0.9.3+2
  photo_view: ^0.10.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    - assets/markers/
    - assets/descriptions/
```
Code (also for illustrating Flutter issue 73789):
```
import 'dart:typed_data';
import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(
    MapsPage(),
  );
}

class MapsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MapsHome(),
    );
  }
}

class MapsHome extends StatefulWidget {
  @override
  _MapsHomeState createState() {
    return _MapsHomeState();
  }
}

class _MapsHomeState extends State<MapsHome> {
  LatLng _kMapCenter = LatLng(52.4478, -3.5402);
  Map<PolylineId, Polyline> polylines = {};
  List<LatLng> polylineCoordinates = [LatLng(52.447858013765305, -3.541443205678288), LatLng(52.44821765976425, -3.5392277011756144)];

  Future<Set<Marker>> initMap() async {
    PolylineId id = PolylineId("poly");
    Polyline polyline = Polyline(
        polylineId: id,
        color: Colors.red,
        width: 3,
        patterns: [PatternItem.dash(15), PatternItem.gap(5)],
        points: polylineCoordinates);
    polylines[id] = polyline;

    BitmapDescriptor destIcon = await createCustomMarkerBitmap(1, 'assets/markers/artmarker.png');
    print('********************* $destIcon');
    Set<Marker> _markers = Set<Marker>();
    _markers.add(Marker(
        markerId: MarkerId("marker_1"),
        position: _kMapCenter,
        icon: destIcon,
        infoWindow: InfoWindow(title: 'test')));
    print(_markers);
    return _markers;
  }

  @override
  Widget build(BuildContext context) {
    print('***************************************build');
    return FutureBuilder(
      future: initMap(),
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        if (snapshot.hasData) {
          return GoogleMap(
            initialCameraPosition: CameraPosition(
              target: _kMapCenter,
              zoom: 18.0,
            ),
            markers: snapshot.data,
            polylines: Set<Polyline>.of(polylines.values),
            //   onMapCreated: _onMapCreated,
          );
        } else {
          return Center(
            child: CircularProgressIndicator(),
          );
        }
      },
    );
  }

  Future<BitmapDescriptor> createCustomMarkerBitmap(int markerNumber, String imageURL) async {
    int markerWidth = 100;
    // if (kIsWeb) markerWidth= 30; else markerWidth = 100;
    PictureRecorder recorder = new PictureRecorder();
    Canvas c = Canvas(recorder);

    final data1 = await rootBundle.load(imageURL);
    var markerImage = await decodeImageFromList(data1.buffer.asUint8List());
    c.drawImageRect(
        markerImage,
        Rect.fromLTRB(0.0, 0.0, markerImage.width.toDouble(), markerImage.height.toDouble()),
        Rect.fromLTRB(0.0, 0.0, markerWidth.toDouble(), markerWidth.toDouble()),
        Paint());

    TextSpan span = TextSpan(
      style: TextStyle(color: Colors.black, fontSize: markerWidth / 3, fontWeight: FontWeight.bold),
      text: markerNumber.toString(),
    );
    TextPainter tp = TextPainter(text: span, textAlign: TextAlign.left, textDirection: TextDirection.ltr);
    tp.layout();
    tp.paint(c, Offset(markerNumber > 9 ? markerWidth / 3.5 : markerWidth / 2.5, markerWidth / 5.5));

    var p = recorder.endRecording();
    ByteData pngBytes =
        await (await p.toImage(markerWidth, markerWidth)).toByteData(format: ImageByteFormat.png);
    Uint8List data = Uint8List.view(pngBytes.buffer);
    return BitmapDescriptor.fromBytes(data);
  }
}
```
Result of flutter run, on Android phone:
![image](https://user-images.githubusercontent.com/18601125/104620337-2bcb7c00-568f-11eb-80bc-1154c30998ae.png)

Result of flutter run d:chrome --web-renderer canvaskit:
![image](https://user-images.githubusercontent.com/18601125/104620464-50275880-568f-11eb-81b9-6db94e388989.png)
