### ISSUE TITLE
Getting error when trying to build apk 

### ISSUE THREAD

**Issue by sureace** [flutter/flutter#73843]
Hi, 
      I am getting unknown error, when i try to build apk for release. It is working fine when i run it in device or emulator. It is happening after update to new android studio and gardle plugins. I could not find any clue to fix this issue. Could you please help me on this.

Pubspec.yaml
---------------
<details>
<summary>pubspec</summary>

```yaml
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: ^0.5.5
  connectivity_plus: ^0.7.1
  equatable: ^1.2.5
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.13
  flutter_bloc: ^6.1.1
  google_fonts: ^1.1.1
  google_sign_in: ^4.5.9
  meta: ^1.2.4
  sign_in_with_apple: ^2.5.4
  pin_code_fields: ^6.0.2
  sms_autofill: ^1.2.7
  bot_toast: ^3.0.5
  image_picker: ^0.6.7+21
  image_cropper: ^1.3.1
  sqflite: ^1.3.2+2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
```
</details>

Flutter doctor
---------------

<details>
<summary>flutter doctor -v</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E287 darwin-x64,
    locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!
```
</details>

Error
-------

<details>
<summary>logs</summary>

```bash
flutter build apk --release
You are building a fat APK that includes binaries for android-arm,
android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app
bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform
        android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform
        android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:
        https://developer.android.com/studio/build/configure-apk-splits#configur
        e-abi-split
Unexpected object (Class with illegal cid, full-aot): 0x110ae63e1 Library:'package:win32/src/kernel32.dart' Class: ::
Dart snapshot generator failed with exit code -6                        
Unexpected object (Class with illegal cid, full-aot): 0x11427cb71 Library:'package:win32/src/kernel32.dart' Class: ::
Dart snapshot generator failed with exit code -6                        
Unexpected object (Class with illegal cid, full-aot): 0x1165663e1 Library:'package:win32/src/kernel32.dart' Class: ::
Dart snapshot generator failed with exit code -6                        
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/********/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/Users/****/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 49s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      50.7s
Gradle task assembleRelease failed with exit code 1
```
</details>

Thanks,
Suresh. P
