### ISSUE TITLE
App crashes on iOS 10.3.x

### ISSUE THREAD

**Issue by sullenel** [flutter/flutter#73971]
Our app crashes on launch for users with iOS 10.3.x on iphone 5/6s/7 and ipad 4. I initially thought it is the same as https://github.com/flutter/flutter/issues/73865 but I'm not sure they are related after looking at all logs. There are cases where users pass the initial screen after network requests, before the app crashes. 

Crash log:
Crashlytics
```
Crashed: DartWorker
0  libobjc.A.dylib                0x1b9a4dc6 objc_msgSend + 5
1  Security                       0x1caee0db validate_array_of_items + 248
2  Security                       0x1caef53b SecTrustValidateInput + 32
3  Security                       0x1caefb3d __SecTrustEvaluateIfNecessary_block_invoke_2 + 14
4  libsystem_trace.dylib          0x1bfa7305 _os_activity_initiate_impl + 34
5  libsystem_trace.dylib          0x1bfa7327 _os_activity_initiate + 18
6  Security                       0x1caefb2b __SecTrustEvaluateIfNecessary_block_invoke + 192
7  libdispatch.dylib              0x1bde9a35 _dispatch_barrier_sync_f_invoke + 50
8  Security                       0x1caed63f SecTrustEvaluateIfNecessary + 442
9  Security                       0x1caed961 SecTrustEvaluate + 44
10 Flutter                        0x13a2893 (Missing)
11 Flutter                        0x146e449 (Missing)
12 Flutter                        0x146cf91 (Missing)
13 Flutter                        0x146cbb1 (Missing)
14 Flutter                        0x14d73e9 (Missing)
15 Flutter                        0x149dcef (Missing)
16 libsystem_pthread.dylib        0x1bf9493b _pthread_body + 216
17 libsystem_pthread.dylib        0x1bf9485d _pthread_start + 234
18 libsystem_pthread.dylib        0x1bf92468 thread_start + 8
```

Xcode
```
Thread 21 Crashed:
0   libobjc.A.dylib               	0x1c6e4dc6 objc_msgSend + 6
1   Security                      	0x1d82e0da validate_array_of_items + 248 (SecTrust.c:1204)
2   Security                      	0x1d82f53a SecTrustValidateInput + 32 (SecTrust.c:1245)
3   Security                      	0x1d82fb3c __SecTrustEvaluateIfNecessary_block_invoke_2 + 14 (SecTrust.c:1307)
4   libsystem_trace.dylib         	0x1cce7304 _os_activity_initiate_impl + 34 (activity.c:139)
5   libsystem_trace.dylib         	0x1cce7326 _os_activity_initiate + 18 (activity.c:154)
6   Security                      	0x1d82fb2a __SecTrustEvaluateIfNecessary_block_invoke + 192 (SecTrust.c:1307)
7   libdispatch.dylib             	0x1cb29a34 _dispatch_barrier_sync_f_invoke + 50 (queue.c:3446)
8   Security                      	0x1d82d63e SecTrustEvaluateIfNecessary + 442 (SecTrust.c:1287)
9   Security                      	0x1d82d960 SecTrustEvaluate + 44 (SecTrust.c:955)
10  Flutter                       	0x0134a892 0x100f000 + 3389586
11  Flutter                       	0x01416448 0x100f000 + 4224072
12  Flutter                       	0x01414f90 0x100f000 + 4218768
13  Flutter                       	0x01414bb0 0x100f000 + 4217776
14  Flutter                       	0x0147f3e8 0x100f000 + 4654056
15  Flutter                       	0x01445cee 0x100f000 + 4418798
16  libsystem_pthread.dylib       	0x1ccd493a _pthread_body + 216 (pthread.c:697)
17  libsystem_pthread.dylib       	0x1ccd485c _pthread_start + 234 (pthread.c:744)
18  libsystem_pthread.dylib       	0x1ccd2468 thread_start + 8
```

**Expected results:**
No crashes?

**Actual results:**
App crashes on launch or right after it

<details>

```
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.25.0-8.2.pre at /Users/el/Dev/.flutter
    • Framework revision b0a2299859 (9 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/el/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/el/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
@flutter-symbolizer-bot force ios https://github.com/flutter/flutter/issues/73971#issue-786289989 arm64

**Comment by TahaTesser** [comment]
Hi @sullenel 
Can you please provide your `pubspec.yaml`?
Thank you

**Comment by TahaTesser** [comment]
@flutter-symbolizer-bot force ios https://github.com/flutter/flutter/issues/73971#issue-786289989 arm64

**Comment by sullenel** [comment]
Hi @TahaTesser 
Sure

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider:
  rxdart:
  dio:
  email_validator:
  smooth_page_indicator:
  shimmer:
  intl:
  animations:
  flutter_rating_bar: ^3.0.0
  ntp: ^1.0.0
  visibility_detector:
  flutter_spinkit:
  scrollable_positioned_list:
  path:
  circular_reveal_animation:
  show_up_animation:
  html:
  xml:
  maps_toolkit:
  cached_network_image: ^2.4.0
  google_maps_flutter:
  geolocator: ^6.0.0
  geocoding: ^1.0.0
  sqflite: ^1.0.0
  path_provider:
  shared_preferences:
  package_info:
  device_info:
  sms_autofill:
  url_launcher: ^5.0.0
  system_clock:
  flutter_inappwebview:
  flutter_libphonenumber:
  firebase_core:
  firebase_analytics:
  firebase_messaging: ^8.0.0-0
  firebase_crashlytics:
  flutter_local_notifications:
  facebook_app_events:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
```
