### ISSUE TITLE
[proposal][web] compile all files that have the main function into .js files 

### ISSUE THREAD

**Issue by p554157atch** [flutter/flutter#74221]
As you guys already know, web projects can include various JS files.
`flutter build web` only compiles the `main.dart` file and ignores other files that have the `main` method.

My flutter `web` directory has a file named `print.dart` that has a`main` function that prints `hello`, I'm running `flutter build web` but the `print.dart`  file is not getting compiled into a `print.dart.js` file similar to how it gets compiled in a Angular Dart project. 

I'm trying to apply `build_web_compilers` builder on the file but it is not working with the `flutter build web` command.

Any suggestions are welcome.

**Comment by pedromassangocode** [comment]
Hi @p554157atch 
See https://stackoverflow.com/a/55510264

Closing this as invalid Flutter issue.
Thank you

**Comment by p554157atch** [comment]
@pedromassangocode  you are not understanding what I'm trying to do.

I don't want to run a different dart file as the main file, I'm trying to compile all files that have the `main` function into js files so I can have multiple files compiled for multiple pages such as `options.html` and `popup.html` for chrome and firefox extensions.

Similar to how separate HTML pages have separate JS files.

Right now, flutter only compiles the `main.dart` and ignores everything else.
And since we can not use `build_runner` on flutter projects I can not setup custom build configurations.

**Comment by p554157atch** [comment]
If you have worked on angular dart projects, if a dart file in `web` directory has a non empty `main` method then it is compiled to `.dart.js` equivalent, however flutter does not.

**Comment by p554157atch** [comment]
I have flutter web directory with multiple files that have the `main` method.
but flutter build web only compiles the main.dart file.
How can I force flutter to compile other files too that have the main method for a web project ?

**Comment by p554157atch** [comment]
I tried the `flutter build web -t filname` command, what it selects the target file from the lib directory to be used as the main entry point but it still ignores all files in the `web` directory.

To be more elaborate as to what I'm trying to do is apply the `build_web_compiles` builder on the `web` directory when the `flutter build web` is called, so that files in the `web` directory that have `main` method will also be compiled, like they are compiles for Angular Dart projects.

Here is my `build.yaml` but it is not applying on the `web` directory when `flutter build web` is called:

```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          generate_for:
            - web/**.dart
          dart2js_args:
            - --fast-startup
            - --omit-implicit-checks
            - --trust-primitives
            - --csp
```
