### ISSUE TITLE
Flutter in_app_purchase method queryProductDetails crashing app

### ISSUE THREAD

**Issue by milanP96** [flutter/flutter#74224]
Fetching products from Google is problem. Actually building it in flutter after calling queryProductDetails. If i enter set of wrong ID flutter do not have to build any object and it not crashing app, but when I flutter receive something and starting building objects app is crashing with log:

``E/AndroidRuntime(22618): java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles()Ljava/lang/String; in class Lcom/android/billingclient/api/SkuDetails; or its super classes (declaration of 'com.android.billingclient.api.SkuDetails' appears in /data/app/com.icd.tourguide-QLilN64t5w0c7y2_ABuIxA==/base.apk!classes2.dex) E/AndroidRuntime(22618): at io.flutter.plugins.inapppurchase.Translator.fromSkuDetail(Translator.java:27) E/AndroidRuntime(22618): at io.flutter.plugins.inapppurchase.Translator.fromSkuDetailsList(Translator.java:49) E/AndroidRuntime(22618): at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl$1.onSkuDetailsResponse(MethodCallHandlerImpl.java:185) E/AndroidRuntime(22618): at com.android.billingclient.api.zzj.run(com.android.billingclient:billing@@3.0.0:8) E/AndroidRuntime(22618): at android.os.Handler.handleCallback(Handler.java:900) E/AndroidRuntime(22618): at android.os.Handler.dispatchMessage(Handler.java:103) E/AndroidRuntime(22618): at android.os.Looper.loop(Looper.java:219) E/AndroidRuntime(22618): at android.app.ActivityThread.main(ActivityThread.java:8347) E/AndroidRuntime(22618): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime(22618): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) E/AndroidRuntime(22618): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055) I/Process (22618): Sending signal. PID: 22618 SIG: 9``

This issue https://github.com/flutter/flutter/issues/59400 is not helpful for me because I do not have com.android.billingclient:billing in my project.

What I am doing is:

```

InAppPurchaseConnection _iap = InAppPurchaseConnection.instance;

bool available = await _iap.isAvailable();

if(available) {

final ProductDetailsResponse response = await _iap.queryProductDetails({"token_test"});

}
```

**Comment by TahaTesser** [comment]
Hi @milanP96 
I can't understand your explanation, can you please clarify the issue better? 
I tried to reproduce the issue using your snippet on the latest `in_app_purchase: ^0.3.5+1`, locally and also play store internal release.  No crashes or errors in the `logcat`.

<details> 
<summary>code sample</summary> 

```dart

import 'package:flutter/material.dart';
import 'package:in_app_purchase/in_app_purchase.dart';

class IAPScreen extends StatefulWidget {
  @override
  _IAPScreenState createState() => _IAPScreenState();
}

class _IAPScreenState extends State<IAPScreen> {
  String result;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text(result ?? 'No data'),
            RaisedButton(
              child: Text('queryProductDetails'),
              onPressed: () async {
                InAppPurchaseConnection _iap = InAppPurchaseConnection.instance;

                bool available = await _iap.isAvailable();

                if (available) {
                  final ProductDetailsResponse response =
                      await _iap.queryProductDetails({"token_test"});

                  setState(() {
                    result =
                        "response.productDetails: ${response.productDetails}";
                  });
                }
              },
            ),
          ],
        ),
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.22.5 at C:\Code\flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Code\SDK
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

</details>

Can you please provide your `flutter doctor -v`, your `in_app_purchase` version, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by milanP96** [comment]
Hi @TahaTesser 
My dependencies:
`
```yaml
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.0
  intl: ^0.15.8
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+1
  google_sign_in: ^4.5.6
  flutter_facebook_login: ^3.0.0
  flutter_rating_bar: ^3.2.0+1
  contained_tab_bar_view: ^0.7.0
  loadmore: ^1.0.4
  flutter_pagination_helper: ^1.0.1+2
  multi_select_flutter: ^3.1.6
  flutter_slidable: ^0.5.7
  in_app_purchase: ^0.3.5+1
  flutter_inapp_purchase: ^3.0.1
  image_picker: ^0.6.7+21
  path: ^1.7.0
  firebase_messaging: ^7.0.3
  syncfusion_flutter_calendar: ^18.4.34
  flushbar: ^1.10.4
  web_socket_channel: ^1.1.0
  flutter_launcher_icons: ^0.8.1
  package_info: ^0.4.3+2
````
