### ISSUE TITLE
[Solved] Multiple issues, including [device_info] Minimum supported Gradle version is 5.6.4. Current version is 5.6.2

### ISSUE THREAD

**Issue by jaggzh** [flutter/flutter#74714]
Other mentions:
https://github.com/flutter/flutter/issues/60014
https://github.com/flutter/flutter/issues/56683

[Edit] I am able to `flutter run`, both using the emulator and an attached mobile device; however, `flutter build apk --target-platform android-arm64` and `flutter run --release` cause errors -- the first situation being a gradle version error:

With device_info: ^1.0.0:
```
A problem occurred evaluating root project 'device_info'.                       
> Failed to apply plugin [id 'com.android.internal.version-check']              
   > Minimum supported Gradle version is 5.6.4. Current version is 5.6.2.
If using the gradle wrapper, try editing the distributionUrl in
/home/jaggz/.gradle/daemon/5.6.2/gradle/wrapper/gradle-wrapper.properties to gradle-5.6.4-all.zip
```

There is no daemon/5.6.2/gradle folder there.
My app is currently at flutter 1.24.0-10.2.pre
```
$ flutter doctor -v # would like to tell you:
[✓] Flutter (Channel unknown, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-10.2.pre at /home/jaggz/projects/flutter/flutter
    • Framework revision 022b333a08 (10 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/jaggz/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/jaggz/Android/Sdk
    • Java binary at: /mnt/bigfs/home/jaggz/projects/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.16.3
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio
    • Android Studio at /mnt/bigfs/home/jaggz/projects/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /mnt/bigfs/home/jaggz/projects/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • ONEPLUS A6000 (mobile) • ...   • android-arm64  • Android 10 (API 29)
    • Linux (desktop)        • linux      • linux-x64      • Linux
    • Web Server (web)       • web-server • web-javascript • Flutter Tools
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
As there is no folder there (~/.gradle/daemon/5.6.2/gradle doesn't exist at all), instead I edited:
```flutter/.pub-cache/hosted/pub.dartlang.org/device_info-1.0.0/android/gradle/wrapper/gradle-wrapper.properties``` to set the distributionUrl to use 6.3 (also tried 5.6.4).  Those result in the following errors (with 5.6.4 also giving some lint:deprecation errors, not included below):
```
Running "flutter pub get" in mapp...                               879ms
Running Gradle task 'assembleRelease'...                        
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':flutter_twitter_login:verifyReleaseResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/jaggz/.gradle/caches/transforms-2/files-2.1/415ea6a7f330b007067d3b262df6e871/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     /home/jaggz/.gradle/caches/transforms-2/files-2.1/415ea6a7f330b007067d3b262df6e871/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Running Gradle task 'assembleRelease'...                           16.6s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin assets_audio_player...
Running Gradle task 'assembleAarRelease'...                        859ms
✓ Built build/app/outputs/repo.
Building plugin assets_audio_player_web...
Running Gradle task 'assembleAarRelease'...                      2,155ms
✓ Built build/app/outputs/repo.
Building plugin audioplayers...
Running Gradle task 'assembleAarRelease'...                      1,875ms
✓ Built build/app/outputs/repo.
Building plugin connectivity...
Running Gradle task 'assembleAarRelease'...                      1,628ms
✓ Built build/app/outputs/repo.
Building plugin device_info...
Running Gradle task 'assembleAarRelease'...                        714ms
✓ Built build/app/outputs/repo.
Building plugin firebase_core...
Running Gradle task 'assembleAarRelease'...                      1,366ms

FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':generateReleaseRFile'.
> Could not resolve all files for configuration ':releaseRuntimeClasspath'.
   > Could not find com.google.firebase:firebase-bom:25.12.0.
     Searched in the following locations:
       - https://storage.googleapis.com/download.flutter.io/com/google/firebase/firebase-bom/25.12.0/firebase-bom-25.12.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/google/firebase/firebase-bom/25.12.0/firebase-bom-25.12.0.jar
     Required by:           project :
   > Could not find com.google.firebase:firebase-core:.
     Required by:          project :
   > Could not find androidx.annotation:annotation:1.1.0.
     Searched in the following locations:
       - https://storage.googleapis.com/download.flutter.io/androidx/annotation/annotation/1.1.0/annotation-1.1.0.pom
       - https://storage.googleapis.com/download.flutter.io/androidx/annotation/annotation/1.1.0/annotation-1.1.0.jar
     Required by:          project :

* Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
======================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':javaPreCompileRelease'.
> Could not resolve all files for configuration ':releaseCompileClasspath'.
   > Could not find com.google.firebase:firebase-bom:25.12.0.
     Required by:          project :
   > Could not find com.google.firebase:firebase-core:.
     Required by:          project :
   > Could not find androidx.annotation:annotation:1.1.0.
     Required by:          project :
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
========================================================
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
The plugin firebase_core could not be built due to the issue above.
```

My pubspec.yaml:
```
name: grass_fed_grasshoppers
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  email_validator: ^1.0.0
  video_player: ^0.11.0  # linux+android
  provider: ^4.1.2
#  social_login_2: ^0.0.3
  social_login_3: ^0.1.2
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  #device_info: ^0.4.2+6
  device_info: ^1.0.0   # jaggz
  #device_info: ^2.0.0-nullsafety.2   # jaggz
  fluttertoast: ^7.0.2
  shared_preferences: ^0.5.8
  connectivity: ^2.0.2
  flutter_spinkit: ^4.1.2
  google_sign_in: ^4.5.1
  flutter_facebook_auth: ^0.3.0
  flutter_twitter_login: any
  firebase_core: ^0.5.0+1
  image_picker: 0.6.7+12
  flutter_signin_button: ^1.0.0
  file: ^5.0.4
  http: any
  path_provider: ^1.1.0
  permission: ^0.1.7
  cached_network_image: ^2.3.2+1
  shimmer: ^1.1.1
  step_progress_indicator: ^0.2.5+8
  in_app_purchase: 0.3.4+16
  #  audioplayers: 0.16.1
  audioplayers: <=0.16.2
  # audioplayers: ^0.17.0 #  Yoshi
  assets_audio_player: 2.0.13+1
  pdf_platform_view: ^0.5.0+2
  share: ^0.6.5+4
  hexcolor: 1.0.6
  flutter_swiper: ^1.1.6
  firebase_auth:
    path: package/firebase_auth
  flutter_country_picker:
    path: package/flutter_country_picker
  native_video_view:
    path: package/native_video_view
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - assets/
    - lib/assets/language/

  # Testing substituting everything with Noto...
  fonts:
    - family: NotoBlack
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoBlackItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoBold
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoBoldItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoHeavy
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoHeavyItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoLight
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoLightItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoMedium
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoMediumItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoRegular
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoRegularItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoSemibold
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoSemiboldItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoThin
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoThinItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoUltralight
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoUltralightItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

    - family: NotoBlack
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoBold
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoBlackItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoBoldItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoExtraBold
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoExtraBoldItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoLight
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoLightItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoMedium
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoMediumItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoRegular
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoSemiBold
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: NotoSemiBoldItalic
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
```
