### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider io.flutter.plugins.imagepicker.ImagePickerFileProvider: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.imagepicker.ImagePickerFileProvider" on path: DexPathList[[zip file "/data/app/com.foo.foo-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.foo.foo-1, /vendor/lib, /system/lib]]

### ISSUE THREAD

**Issue by LostInDarkMath** [flutter/flutter#74841]
Hi there!
I tried to run my Flutter application on an old Android 4.3 phone. It works fine on newer devices but I like to offer support for older devices as well.
So, when I try to start my application I get the following error:

```
√ Built build\app\outputs\flutter-apk\app-debug.apk.
E/AndroidRuntime(12820): FATAL EXCEPTION: main
E/AndroidRuntime(12820): Process: com.foo.foo, PID: 12820
E/AndroidRuntime(12820): java.lang.RuntimeException: Unable to get provider io.flutter.plugins.imagepicker.ImagePickerFileProvider: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.imagepicker.ImagePickerFileProvider" on path: DexPathList[[zip file "/data/app/com.foo.foo-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.foo.foo-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(12820): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5236)
E/AndroidRuntime(12820): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4828)
E/AndroidRuntime(12820): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711)
E/AndroidRuntime(12820): 	at android.app.ActivityThread.access$1600(ActivityThread.java:175)
E/AndroidRuntime(12820): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
E/AndroidRuntime(12820): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12820): 	at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(12820): 	at android.app.ActivityThread.main(ActivityThread.java:5602)
E/AndroidRuntime(12820): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12820): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(12820): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime(12820): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime(12820): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(12820): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.imagepicker.ImagePickerFileProvider" on path: DexPathList[[zip file "/data/app/com.foo.foo-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.foo.foo-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(12820): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
E/AndroidRuntime(12820): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime(12820): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime(12820): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5221)
E/AndroidRuntime(12820): 	... 12 more

```

Do you have any idea how I can fix this?

**Comment by LostInDarkMath** [comment]
I forgot to mention that my `pubspec.yaml` file looks like the following:
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  pedantic: ^1.9.0
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21
  intl: ^0.16.1
  location: ^3.2.4 
  path_provider: ^1.6.8
  http: ^0.12.2
  loading_overlay: ^0.2.1
  chips_choice: ^2.0.1 
  shared_preferences: ^0.5.12+4  
  flutter_secure_storage: ^3.3.5
  flutter_launcher_icons: ^0.8.1 
  dash_chat: ^1.1.15
```
