### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences

### ISSUE THREAD

**Issue by 00neon** [flutter/flutter#74988]
Hi!

When I'm triying to compile my apk in my device, I always get the same error **ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences**
I have tried a lot of configurations but nothing, I'm so desperate, I need to solve this error for to continue in my work..... :( :( 

Here is my flutter doctor:

```
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [VersiÃ³n 10.0.10240], locale es-ES)
    • Flutter version 1.25.0-8.3.pre at C:\sdk\flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\prog10\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\prog10\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\prog10\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.52.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • POCOPHONE F1 (mobile) • android-arm64 • Android 10 (API 29)

• No issues found!

```

My pubsec.yaml's configuration is the following:
```
name: myapp
description: App 

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_launcher_icons: ^0.7.2
  provider: ^3.2.0
  splashscreen: ^1.2.0
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.0+3
  cached_network_image: ^2.0.0-rc
  flutter_html: ^0.10.4
  datetime_picker_formfield: 
    path: ./assets/packages/datetime_picker_formfield/
  intl: ">=0.15.8 <1.0.0"
  table_calendar: ^2.0.1
  photo_view: ^0.7.0
  firebase_core: 0.4.4
  firebase_auth: 0.15.3
  # cloud_firestore: ^0.12.9+4
  cloud_firestore: ^0.13.4
  firebase_messaging: ^5.1.6
  flutter_image_compress: ^0.6.3
  maps_launcher: ^1.2.0
  barcode_scan: ^1.0.0
  flutter_inappwebview: ^2.1.0+1
  flutter_share: ^1.0.2+1
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon-paciente.png
  image_path_ios: assets/icon-paciente.png

flutter:

  uses-material-design: true

  assets:
    - assets/loader.gif
    - assets/logo.png
    - assets/logo-header.png
    - assets/icon.png
    - assets/icon-dark.png
    - assets/icon-paciente.png
    - assets/placeholder.png
    - assets/patient1.jpg
    - assets/patient2.jpg
    - assets/patient3.jpg
    - assets/medicamento1.jpg
    - assets/medicamento2.jpg
    - assets/medicamento3.jpg
    - assets/paypal.png
    - assets/paypal.jpg

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
        - asset: assets/fonts/Comfortaa-Medium.ttf
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
```

I want to know where is the problem, please anybody can help me?

Best regards!
