### ISSUE TITLE
Unit testing local_auth package fails.

### ISSUE THREAD

**Issue by pkhivesara** [flutter/flutter#75043]
## Steps to Reproduce

Writing a unit test on the ``local_auth`` package causes a failure:
```
package:flutter/src/services/platform_channel.dart 157:7  MethodChannel._invokeMethod

MissingPluginException(No implementation found for method getAvailableBiometrics on channel plugins.flutter.io/local_auth)
```

Sample test:
```
  test('Check if user is authenticated via FaceId', () async {
    final bioMetricServices = MockLocalAuth();
    when(bioMetricServices.getAvailableBiometrics())
        .thenAnswer((_) async => Future.value([BiometricType.face]));

    when(bioMetricServices.authenticateWithBiometrics(localizedReason: "hh",stickyAuth: true,useErrorDialogs: true,sensitiveTransaction: true))
    .thenAnswer((realInvocation) => Future.value(true));


    var flag = await BiometricService.authenticate();
    expect(flag, true);
  });
  

class MockLocalAuth extends Mock implements LocalAuthentication {}
```

Is there any any additional steps that we need to perform?

**Comment by iapicca** [comment]
@pkhivesara 
your code sample doesn't seem reproducible

<details>
<summary>pubspec.yaml</summary>

```yaml
name: thirty_jan
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^0.6.3+4



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.4

flutter:
  uses-material-design: true

```

</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:local_auth/local_auth.dart';
import 'package:mockito/mockito.dart';

class MockLocalAuth extends Mock implements LocalAuthentication {}

void main() {
  test('Check if user is authenticated via FaceId', () async {
    final bioMetricServices = MockLocalAuth();
    when(bioMetricServices.getAvailableBiometrics())
        .thenAnswer((_) async => Future.value([BiometricType.face]));

    when(bioMetricServices.authenticateWithBiometrics(
            localizedReason: "hh",
            stickyAuth: true,
            useErrorDialogs: true,
            sensitiveTransaction: true))
        .thenAnswer((realInvocation) => Future.value(true));

    var flag = await BiometricService.authenticate(); 
    // !! error: `Undefined name 'BiometricService'.
    // !! Try correcting the name to one that is defined, or defining the name.`
    // !! expect(flag, true);
  });
}

```

</details>

can you specify the import for `BiometricService` and provide you `flutter doctor -v` and `pubspec.yaml`

**Comment by pkhivesara** [comment]
@iapicca The ``Biometric`` class is a custom class which essentially authenticates the user.

```
 static Future<bool> authenticate() async {
    bool authenticated;
    String localizedReason = '';
    List<BiometricType> availableBiometrics = await _getAvailableBiometrics();
    if (availableBiometrics.contains(BiometricType.face)) {
      // Face ID.
      localizedReason = 'Scan your face to authenticate.';
    } else if (availableBiometrics.contains(BiometricType.fingerprint)) {
      // Touch ID.
      localizedReason = 'Scan your fingerprint to authenticate.';
    }

    try {
      authenticated = await LocalAuthentication().authenticateWithBiometrics(
        localizedReason: localizedReason,
        stickyAuth: true,
        //useErrorDialogs: true,
        //sensitiveTransaction: true,
      );
      print('Authentication Successful, Return: $authenticated');
    } on PlatformException catch (e) {
      authenticated = false;
      print(e);
    }
    return authenticated;
  }
  ```
  
  pubspec.yaml
  ``` 
dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  shared_preferences: ^0.5.12+4
  local_auth: ^0.6.3+4
  flutter_switch: ^0.2.0
  flutter_slidable:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.4
  test:
  ```
  
  ```
  [✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/xxx/flutter/flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

⣻Unable to find any JVMs matching version "1.8".                                                                                                                                                                                                                        [!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/xxx/Library/Android/Android/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Users/xxx/Library/Android/Android/Contents
    • Try updating or re-installing Android Studio.

! Doctor found issues in 3 categories.
```

The doctor has been complaining every since upgrading Flutter but I am able to compile the app.
