### ISSUE TITLE
> Same! Any solutions coming soon. I am in real hurry to fix this 😟

### ISSUE THREAD

**Issue by mobeloper** [flutter/flutter#76085]
> Same! Any solutions coming soon. I am in real hurry to fix this 😟
> Any work around or quick fixes anyone?

```yaml
dependency_overrides:
  shared_preferences:
    git:
      url: https://github.com/Flutter-Dart-Open-Source/plugins.git
      path: packages/shared_preferences/shared_preferences
      ref: update_prefs
```

_Originally posted by @hoc081098 in https://github.com/flutter/flutter/issues/71595#issuecomment-778802368_
