### ISSUE TITLE
Add docs for pubspec.yaml font options 

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#76335]
Looking at the cookbook for custom fonts we can see there are options like `style`:

```
flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700 
```

`style`, `weight`, etc.... What are all the options available? What do they do? Where do they live? What do they eat?

Some docs on all the options available and why use then would be very helpful.
