### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method sendtext on channel sample.test.platform/text)

### ISSUE THREAD

**Issue by FrankInpark2005** [flutter/flutter#76373]
dart
```dart
 static const MethodChannel _methodChannel = const MethodChannel('sample.test.platform/text');
  Future<String> getStringReturnFromPlatform(String text) async {
    return await _methodChannel.invokeMethod<String>(
        'sendtext', {'message': text});
  }
```

java
```java
public class MainActivity extends FlutterActivity {    
    private String CHANNEL = "sample.test.platform/text";
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
        BinaryMessenger binaryMessenger = flutterEngine.getDartExecutor().getBinaryMessenger();
        MethodChannel.MethodCallHandler methodCallHandler = new MethodChannel.MethodCallHandler() {
            @Override
            public void onMethodCall(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                String strFlutterMessage = call.argument("message");
                result.success(strFlutterMessage + " : From Java ");
            }
        };
        MethodChannel methodChannel = new MethodChannel(binaryMessenger , CHANNEL);
        methodChannel.setMethodCallHandler(methodCallHandler);
    }
```

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18362.1139], locale th-TH)
    • Flutter version 1.22.6 at D:\Download\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\AndroidSDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\AndroidSDK\platform-tools
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

pubspec.yaml

<details>
<summary>pubspec.yaml</summary>

```yaml
name: test_flutter_module_2
description: A new Flutter module.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  nb_utils: 3.2.0
  http:
  crypto: ^2.1.5
  cached_network_image: ^2.2.0
  lottie: 0.5.1
  flutter_html: 0.8.2
  shared_preferences: ^0.5.12+4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lang/

  module:
    androidX: true
    androidPackage: com.example.test_contenter_module_2
    iosBundleIdentifier: com.example.testContenterModule2
```

</details>
