### ISSUE TITLE
Building with a macOS plugin: "Plugin `url_launcher_linux` doesn't implement a plugin interface"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#76396]
On top of #74469 I see confusing output when I build for a macOS app
```
Plugin `url_launcher_linux` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      linux:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `url_launcher_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.

To set a default implementation, use:
flutter:
  plugin:
    platforms:
      macos:
        default_package: <plugin-implementation>

To implement an interface, use:
flutter:
  plugin:
    implements: <plugin-interface>

Plugin `url_launcher_windows` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
To set a default implementation, use:
flutter:
  plugin:
    platforms:
      windows:
        default_package: <plugin-implementation>

To implement an interface, use:

flutter:
  plugin:
    implements: <plugin-interface>
```

### Steps to Reproduce
1. flutter create --platforms=macos test_macos_plugin
2. Add `url_launcher:` to pubspec.yaml
3. Run in Xcode or `flutter run -v`

**Comment by jmagman** [comment]
@blasten

**Comment by blasten** [comment]
I was unable to reproduce it. what version did it resolve to (from .packages)?

**Comment by blasten** [comment]
Actually, I had modified the pub cache in order to test the changes.  This is the intended behavior, and I will submit a fix to the offending plugins.

**Comment by CodinMoldovanu** [comment]
@jmagman What Flutter version are you using? I was encountering this while using the `master` branch of the Flutter repo, switched to stable and everything is behaving nicely.

**Comment by narumishi** [comment]
This should be warnings for `plugin` which not implements all platforms, should not shown when building `application`?

```
Plugin `audioplayers` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      macos:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `connectivity_plus_linux` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      linux:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `connectivity_plus_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      macos:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `connectivity_plus_windows` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      windows:                                                          
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `file_chooser` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      linux:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `file_chooser` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      macos:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `file_chooser` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      windows:                                                          
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `flutter_audio_desktop` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      linux:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `flutter_audio_desktop` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      windows:                                                          
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `flutter_qjs` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      linux:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `flutter_qjs` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      macos:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `flutter_qjs` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      windows:                                                          
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `package_info` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      macos:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `path_provider_linux` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      linux:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `path_provider_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      macos:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `path_provider_windows` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      windows:                                                          
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `shared_preferences_linux` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      linux:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `shared_preferences_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      macos:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `shared_preferences_windows` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      windows:                                                          
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `sqflite` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      macos:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `url_launcher_linux` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      linux:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `url_launcher_macos` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      macos:                                                            
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>                                      
                                                                        
Plugin `url_launcher_windows` doesn't implement a plugin interface, nor sets a default implementation in pubspec.yaml.
                                                                        
To set a default implementation, use:                                   
flutter:                                                                
  plugin:                                                               
    platforms:                                                          
      windows:                                                          
        default_package: <plugin-implementation>                        
                                                                        
To implement an interface, use:                                         
flutter:                                                                
  plugin:                                                               
    implements: <plugin-interface>   
```
