### ISSUE TITLE
Flutter Build Error On IOS - Old Packages

### ISSUE THREAD

**Issue by onurc4kir** [flutter/flutter#76693]
Hello, My flutter project was working when I left it 2 months ago but now When I try to build IOS it gives me error which is very long. I created new project and copy my pubspec.yaml file to it and it run. But when I copy my lib folder again it gives me same error message.
What I tried :
1. stable channel, clean and upgrade.
2.  Creating new project and copy lib. and pubspeb.yaml
3. Deleting some old packages
4. change ios deployment target '9.0' to '11.0'  

I'm using beta channel and latest version of flutter. My Xcode Version is 12.4.

pubspec.yaml

```


version: 1.0.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^1.1.1
  provider: ^4.3.2+2
  #page transition animation
  page_transition: '^1.1.7+2'
  #for some UI elements not very essential
  flui: 0.9.2
  #ios style date picker
  flutter_datetime_picker: ^1.4.0
  get_it: ^5.0.1
  #Height, age, range slider
  flutter_xlider: ^3.4.0
  #For picking image from gallery
  image_picker: ^0.6.7+12
  image_pickers: ^1.0.8+7

  #For reading icons at flutter
  flutter_svg: ^0.20.0-nullsafety.3
  flutter_icons: ^1.1.0
  #For showing loading icon when provider state changes
  loading_overlay: ^0.2.1
  #flutflutter_styled_toast: ^1.5.2+1
  #Firebase Packages
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.0.1
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.6
  flutter_facebook_login: ^3.0.0
  #firebase_database: ^4.4.0

  #maps and geolocation packages Using At MapPage
  google_maps_flutter: ^1.0.6
  google_place: ^0.3.3
  #getting user current location.
  geolocator: ^6.1.4

  #cluster manager for Google Maps. Using at MapPage
  google_maps_cluster_manager: ^0.2.0

  #to make bottom container for map Using at MapPage
  sliding_up_panel: ^1.0.2
  #To get LatLng from an address or to get Address From an LatLng
  geocoder: ^0.2.1

  #For swipe cards
  swipe_stack: ^1.0.0

  #For creating timing indicator at match and likes page. Look at circular avatars
  percent_indicator: ^2.1.8

  #to make location search based on geohash.
  geoflutterfire: ^2.2.1

  #for local data managment. Key value pairs
  shared_preferences: ^0.5.12+4
  #cache image and loading indicator fo them
  cached_network_image: ^2.4.1

  #to draw chart. Used at venue detail page.
  fl_chart: 0.20.0-nullsafety1

  # Create unique id for firebase documents
  uuid: ^2.2.2

  path_provider: ^1.6.24
  #some stream operations do
  rxdart: ^0.24.1
  #Google recaptcha plugin
  #flutter_recaptcha_v2: ^0.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

```

Debug Console Log
```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
 lib/main.dart
Xcode build done.                                           11.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    While building module 'firebase_core' imported from /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/ios/Classes/FLTFirebaseFirestorePlugin.m:6:
    In file included from <module-includes>:1:
    In file included from /Users/onur/Developer/spottapp/ios/Pods/Target Support Files/firebase_core/firebase_core-umbrella.h:13:
    In file included from /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebaseCorePlugin.h:11:
    /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebasePlugin.h:9:9: error: include of non-modular header inside framework module 'firebase_core.FLTFirebasePlugin': '/Users/onur/Developer/spottapp/ios/Pods/Headers/Public/FirebaseCore/FirebaseCore.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import <FirebaseCore/FirebaseCore.h>
            ^
    1 error generated.
    /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/ios/Classes/FLTFirebaseFirestorePlugin.m:6:9: fatal error: could not build module 'firebase_core'
    #import <firebase_core/FLTFirebasePluginRegistry.h>
     ~~~~~~~^
    2 errors generated.
    While building module 'firebase_core' imported from /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/ios/Classes/FLTFirebaseFirestoreWriter.m:6:
    In file included from <module-includes>:1:
    In file included from /Users/onur/Developer/spottapp/ios/Pods/Target Support Files/firebase_core/firebase_core-umbrella.h:13:
    In file included from /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebaseCorePlugin.h:11:
    /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebasePlugin.h:9:9: error: include of non-modular header inside framework module 'firebase_core.FLTFirebasePlugin': '/Users/onur/Developer/spottapp/ios/Pods/Headers/Public/FirebaseCore/FirebaseCore.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import <FirebaseCore/FirebaseCore.h>
            ^
    1 error generated.
    /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/ios/Classes/FLTFirebaseFirestoreWriter.m:6:9: fatal error: could not build module 'firebase_core'
    #import <firebase_core/FLTFirebasePlugin.h>
     ~~~~~~~^
    2 errors generated.
    While building module 'firebase_core' imported from /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/ios/Classes/FLTFirebaseFirestoreReader.m:6:
    In file included from <module-includes>:1:
    In file included from /Users/onur/Developer/spottapp/ios/Pods/Target Support Files/firebase_core/firebase_core-umbrella.h:13:
    In file included from /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebaseCorePlugin.h:11:
    /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebasePlugin.h:9:9: error: include of non-modular header inside framework module 'firebase_core.FLTFirebasePlugin': '/Users/onur/Developer/spottapp/ios/Pods/Headers/Public/FirebaseCore/FirebaseCore.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import <FirebaseCore/FirebaseCore.h>
            ^
    1 error generated.
    /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.4/ios/Classes/FLTFirebaseFirestoreReader.m:6:9: fatal error: could not build module 'firebase_core'
    #import <firebase_core/FLTFirebasePlugin.h>
     ~~~~~~~^
    2 errors generated.
    While building module 'firebase_core' imported from /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.4+1/ios/Classes/FLTFirebaseAuthPlugin.m:5:
    In file included from <module-includes>:1:
    In file included from /Users/onur/Developer/spottapp/ios/Pods/Target Support Files/firebase_core/firebase_core-umbrella.h:13:
    In file included from /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebaseCorePlugin.h:11:
    /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebasePlugin.h:9:9: error: include of non-modular header inside framework module 'firebase_core.FLTFirebasePlugin': '/Users/onur/Developer/spottapp/ios/Pods/Headers/Public/FirebaseCore/FirebaseCore.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import <FirebaseCore/FirebaseCore.h>
            ^
    1 error generated.
    /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.4+1/ios/Classes/FLTFirebaseAuthPlugin.m:5:9: fatal error: could not build module 'firebase_core'
    #import <firebase_core/FLTFirebasePluginRegistry.h>
     ~~~~~~~^
    2 errors generated.
    While building module 'firebase_core' imported from /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-5.2.0/ios/Classes/FLTFirebaseStoragePlugin.m:6:
    In file included from <module-includes>:1:
    In file included from /Users/onur/Developer/spottapp/ios/Pods/Target Support Files/firebase_core/firebase_core-umbrella.h:13:
    In file included from /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebaseCorePlugin.h:11:
    /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebasePlugin.h:9:9: error: include of non-modular header inside framework module 'firebase_core.FLTFirebasePlugin': '/Users/onur/Developer/spottapp/ios/Pods/Headers/Public/FirebaseCore/FirebaseCore.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import <FirebaseCore/FirebaseCore.h>
            ^
    1 error generated.
    /Users/onur/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-5.2.0/ios/Classes/FLTFirebaseStoragePlugin.m:6:9: fatal error: could not build module 'firebase_core'
    #import <firebase_core/FLTFirebasePluginRegistry.h>
     ~~~~~~~^
    2 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
Exited (sigterm)

```

Flutter doctor -v
```

[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on macOS 11.2.1
    20D74 darwin-x64, locale en-TR)
    • Flutter version 1.26.0-17.6.pre at
      /Users/onur/Developer/flutter
    • Framework revision a29104a69b (8 days ago), 2021-02-16
      09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android
    SDK version 30.0.2)
    • Android SDK at /Users/onur/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) •
      025247E3-C767-4FE2-81DB-6F10C7D45D5B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

```
