### ISSUE TITLE
RangeError (length): Invalid value: Only valid value is 0: 1. Error thrown Instance of 'ErrorDescription'

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#76700]
We just released our app. And are seeing these crashes in production. But the stacktrace is not leading me somewhere usefull. 

RangeError (length): Invalid value: Only valid value is 0: 1. Error thrown Instance of 'ErrorDescription

```
Non-fatal Exception: FlutterError
0  ???                            0x0 first (dart:core)
1  ???                            0x0 assembleSemanticsNode + 436 (paragraph.dart:436)
2  ???                            0x0 compileChildren + 3717 (object.dart:3717)
3  ???                            0x0 compileChildren + 3709 (object.dart:3709)
4  ???                            0x0 compileChildren + 3709 (object.dart:3709)
5  ???                            0x0 compileChildren + 3709 (object.dart:3709)
6  ???                            0x0 compileChildren + 3709 (object.dart:3709)
7  ???                            0x0 compileChildren + 3709 (object.dart:3709)
8  ???                            0x0 compileChildren + 3709 (object.dart:3709)
9  ???                            0x0 compileChildren + 3709 (object.dart:3709)
10 ???                            0x0 compileChildren + 3663 (object.dart:3663)
11 ???                            0x0 compileChildren + 3709 (object.dart:3709)
12 ???                            0x0 compileChildren + 3587 (object.dart:3587)
13 ???                            0x0 _updateSemantics + 2631 (object.dart:2631)
14 ???                            0x0 flushSemantics + 1081 (object.dart:1081)
15 ???                            0x0 drawFrame + 441 (binding.dart:441)
16 ???                            0x0 drawFrame + 914 (binding.dart:914)
17 ???                            0x0 _handlePersistentFrameCallback + 302 (binding.dart:302)
18 ???                            0x0 _invokeFrameCallback + 1117 (binding.dart:1117)
19 ???                            0x0 handleDrawFrame + 1055 (binding.dart:1055)
20 ???                            0x0 _handleDrawFrame + 971 (binding.dart:971)
```
## Steps to Reproduce

I can't reproduce the issue. I see these crashes in firebase.

<details>
  <summary>Logs</summary>

```
No problems with the analyzer
```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-BE)
    • Flutter version 1.22.6 at /Users/vanlooverenkoen/fvm/versions/stable
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
                                                                                                                                                                                                                                                                                                                             [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vanlooverenkoen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

</details>

**Comment by TahaTesser** [comment]
Hi @vanlooverenkoen 
The crash is on Android or IOS? 
Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.

Related to https://github.com/flutter/flutter/issues/70612 
Thank you

**Comment by vanlooverenkoen** [comment]
I have the non-fatal crash on iOS & Android. My flutter doctor is already added to the logs. & crashlog is also available. already. 

I can't reproduce the non fatal crash myself because I have no clue where to look. Or where it could be happening. 

I first tought it had something to do with a Text widget because of the paragraph.dart but I can't find something usefull there.

This is my pubspec.yaml.

```
name: my_app
description: description
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  kiwi: 2.0.1
  dio: 3.0.10
  retrofit: 1.3.4+1
  provider: 4.3.2+2
  json_annotation: 3.1.0
  niddler_dart: 0.10.3
  shared_preferences: 0.5.12+2
  flutter_secure_storage: 3.3.5
  mockito: 4.1.3
  connectivity: 1.0.0
  path_provider: 1.6.27
  flutter_svg: 0.19.1
  path: 1.8.0-nullsafety.1
  scroll_when_needed: 1.0.0
  tuple: 1.0.3
  keyboard_avoider: 0.1.2
  animations: 1.1.2
  flushbar: 1.10.4
  google_maps_flutter: 1.0.3
  cached_network_image: 2.3.3
  shimmer: 1.1.2
  flutter_blurhash: 0.5.0
  location: 3.0.2
  permission_handler: 5.0.1+1
  after_layout: 1.0.7+2
  firebase_core: 0.5.0+1
  firebase_analytics: 6.0.2
  firebase_crashlytics: 0.2.1+1
  firebase_messaging: 7.0.3
  fitted_text_field_container: 1.3.1+1
  app_settings: 4.0.4
  url_launcher: 5.7.7
  image_picker: 0.6.7+12
  simple_image_crop: 0.1.3
  device_info: 0.4.2+9
  visibility_detector: 0.1.5
  package_info: 0.4.3
  uuid: 2.2.2
  share: 0.6.5+3
  flare_flutter: 2.0.6
  pull_to_refresh: 1.6.2
  auto_size_text: 2.1.0
  android_intent: 0.3.7+7
  rxdart: 0.24.1
  audioplayer: 0.8.1
  background_location_tracker:
    git: git@github.com:icapps/flutter-background-location-tracker.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  model_generator: 3.2.0
  build_runner: 1.10.3
  json_serializable: 3.5.0
  retrofit_generator: 1.4.0
  kiwi_generator: 2.0.1
  icapps_translations: 3.0.5
  icapps_generator: 0.3.0
  icapps_license: 0.0.6

flutter:

```
