### ISSUE TITLE
"NoSuchMethodError: The method 'streamListen' was called on null" when launching Flutter in profile mode

### ISSUE THREAD

**Issue by sabetAI** [flutter/flutter#76865]
flutter run --machine --target lib\main.dart -d R58M31F6ZRX --profile --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --devtools-server-address http://127.0.0.1:9100/

## exception

NoSuchMethodError: NoSuchMethodError: The method 'streamListen' was called on null.
Receiver: null
Tried calling: streamListen("Extension")

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      waitForExtension (package:flutter_tools/src/resident_runner.dart:1513:21)
#2      ResidentRunner._callDevToolsUriExtension (package:flutter_tools/src/resident_runner.dart:1318:11)
#3      ResidentRunner.maybeCallDevToolsUriServiceExtension (package:flutter_tools/src/resident_runner.dart:1309:11)
#4      ResidentRunner.serveAndAnnounceDevTools (package:flutter_tools/src/resident_runner.dart:1301:11)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel dev, 1.27.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-CA)
    • Flutter version 1.27.0-1.0.pre at C:\src\flutter
    • Framework revision 68c96f100e (3 weeks ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\alisa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (3 available)
    • SM G975W (mobile) • R58M31F6ZRX • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 88.0.705.74

• No issues found!
```
## pubspec.yaml
```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_treeview: any
  flappy_search_bar: 1.4.1
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_auth: ^0.18.0
  google_sign_in: ^4.5.6
  apple_sign_in: ^0.1.0
  google_fonts: ^1.1.2

  rxdart: ^0.25.0
  provider: ^4.3.2+3
  font_awesome_flutter: ^8.11.0
  tree_view: ^0.0.5
  flutter_html: ^1.1.1
  flutter_widget_from_html_core: ^0.5.1+4

  uuid: ^2.0.4
  intl: ^0.16.1

  modal_bottom_sheet: ^1.0.0+1
  hooks_riverpod: ^0.12.4

  sliding_up_panel: ^1.0.2
  quiver: ^2.1.5
  flutter_layout_grid: ^0.11.6
  linked_scroll_controller: ^0.1.2
  dotted_border: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
```
