### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#77073]
my application encountered such crash

* "keys" section looks compeletely unrelated (see second screenshot)
* there weren't any other cases of this
* and no, i don't have any memory leaks in my code (like not disposing video_player or etc.)

```
Crashed: com.apple.root.default-qos
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000724416120

0  libobjc.A.dylib                0x23c05bbf0 objc_retain + 16
1  Runner                         0x1009210e8 APMInAppPurchaseEventParametersFromProductAndTransactionV2 + 2244028
2  Runner                         0x100923528 -[APMInAppPurchaseTransactionReporter reportTransactionsFromArray:] + 2253308
3  Runner                         0x100923c9c __80-[APMInAppPurchaseTransactionReporter paymentQueue:updatedFilteredTransactions:]_block_invoke + 2255216
4  libdispatch.dylib              0x23c8a8a38 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x23c8a97d4 _dispatch_client_callout + 16
6  libdispatch.dylib              0x23c84dc80 _dispatch_queue_override_invoke + 684
7  libdispatch.dylib              0x23c85a030 _dispatch_root_queue_drain + 372
8  libdispatch.dylib              0x23c85a8d4 _dispatch_worker_thread2 + 128
9  libsystem_pthread.dylib        0x23ca8a1b4 _pthread_wqthread + 464
10 libsystem_pthread.dylib        0x23ca8ccd4 start_wqthread + 4
```

![image](https://user-images.githubusercontent.com/39104740/109687038-eeb23f00-7b93-11eb-864a-8473de1376d0.png)
![image](https://user-images.githubusercontent.com/39104740/109686722-954a1000-7b93-11eb-9e4e-b804d7caa1f4.png)

<details>
  <summary>dependencies</summary>

```yaml
dependencies:
  # video_player: ^1.0.1
  video_player:
    # path: /users/danya/dev/projects/plugins/packages/video_player/video_player
    git:
      url: https://github.com/nt4f04uNd/plugins.git
      path: packages/video_player/video_player/      # this is forked version of the plugin to workaround the https://github.com/flutter/flutter/issues/72878
      ref: composition                               # the version corresponds to 2.0.0-nullsafety.8
    #   ref: looper
  json_annotation: ^4.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  get_it: ^6.0.0
  cupertino_icons: ^1.0.2
  rxdart: ^0.24.1
  flutter_svg: ^0.20.0-nullsafety.3
  animations: ^2.0.0-nullsafety.0
  package_info: ^2.0.0
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  async: ^2.5.0
  flutter_bloc: ^6.0.5
  equatable: ^1.2.6
  flutter_phoenix: ^0.1.0
  flutter_cache_manager_firebase: ^1.1.0
  wakelock: ^0.4.0-nullsafety.0
  sqflite: ^1.3.2+2
  path: ^1.8.0
  enum_to_string: ^2.0.0-nullsafety.1
  multiple_localization: ^0.2.0-nullsafety.0
  assets_audio_player:
    git:
      url: https://github.com/nt4f04uNd/Flutter-AssetsAudioPlayer
      ref: nt4f04und
  flare_flutter: ^2.0.6
  vibration: ^1.7.4-nullsafety.0
  fluttertoast: ^8.0.1-nullsafety.0
  timezone: ^0.6.1
  devicelocale: ^0.3.3
  flutter_native_timezone: ^1.0.4
  flutter_local_notifications: ^4.0.1+1
  in_app_purchase: ^0.4.0
  in_app_review: ^1.0.3
  connectivity: ^3.0.0-nullsafety.3
  firebase_core: ^0.5.2
  cloud_functions: ^0.7.0
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^4.0.1
  firebase_crashlytics: ^0.2.3
  firebase_analytics: ^6.0.2
  # firebase_messaging: ^8.0.0-dev.10
  firebase_messaging:
    git:
      url: git://github.com/abilia/flutterfire.git
      ref: ios-background-support
      path: packages/firebase_messaging/
  nt4f04unds_widgets:
    # path: C:/dev/projects/native/nt4f04unds_widgets
    git:
      url: https://github.com/nt4f04uNd/nt4f04unds_widgets/
      ref: b7505c41857d0767a246cdf278df8a3b9a7353ee # dev branch
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  analyzer: 1.0.0
  crypto: ^2.0.0
  convert: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.1
  # intl_translation: ^0.17.10
  intl_translation:
    git: 
      url: https://github.com/nt4f04uNd/intl_translation
      ref: oracle
  flutter_test:
    sdk: flutter
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel texture_buildable, 1.27.0-2.0.pre.100, on Microsoft Windows [Version 10.0.19041.804], locale ru-RU)
    • Flutter version 1.27.0-2.0.pre.100 at c:\dev\src\flutter
    • Framework revision 76080cd46c (9 days ago), 2021-02-21 18:22:32 +0300
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.74

! Doctor found issues in 1 category.
```
</details>

<details>
  <summary>firebase message</summary>

> The stack trace indicates that heap corruption may have caused your app to crash. Memory corruption can occur pretty easily from freeing a dangling pointer, a thread race or bad pointer arithmetic. The important thing to keep in mind is that the resulting crash may happen long after the initial corruption. As a result, the stack trace for this crash might not provide any clues to the location of the bug in your code. However, you can still fix memory issues with tools from Apple. For speedy resolution of memory corruption issues, we recommend regularly auditing your app with Xcode's memory debugging facilities: Visual Memory Debugger, Zombies Instrument, Address Sanitizer, Thread Sanitizer and malloc diagnostics.
</details>
