### ISSUE TITLE
flutter_localizations issue when trying to run "flutter run"

### ISSUE THREAD

**Issue by dcb-online** [flutter/flutter#77279]
Hi there, since I upgraded to Flutter v 2 I have been receiving this error when trying to build my project:

```
Running "flutter pub get" in bloepapiercoza...
Because every version of flutter_localizations from sdk depends on intl 0.17.0 and fstore depends on intl ^0.16.1, flutter_localizations from sdk is forbidden.
So, because fstore depends on flutter_localizations any from sdk, version solving failed.
pub get failed (1; So, because fstore depends on flutter_localizations any from sdk, version solving failed.)
```

This is what I get when retrieving "doctor --verbose"

```
C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.804], locale en-ZA)
    • Flutter version 2.0.0 at C:\src\flutter
    • Framework revision 60bd88df91 (26 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Rihaco\AppData\Local\Android\sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
Process finished with exit code 0
```

This is my pubspec.yaml content that includes the following:

```
name: fstore
description: Mobile commerce app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.9.4+3001

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  inspireui:
    path: ./modules/common_library
  flutter:
    sdk: flutter

  # FIREBASE PACKAGES
  cloud_firestore: 0.14.4
  firebase_analytics: 6.3.0
  firebase_auth: 0.18.4+1
  firebase_core: 0.5.3
  firebase_database: 4.4.0
  firestore_ui: 1.12.0

  # STATE MANAGEMENT
  provider: 4.3.2+3

  # UI
  animated_splash: 1.0.0
  animated_text_kit: 3.0.2
  animations: 1.1.2
  awesome_card: 1.1.0
  carousel_pro: 1.0.0
  configurable_expansion_tile: 1.0.0
  country_code_picker: 1.7.0
  country_pickers: 1.3.0
  custom_splash: 0.0.2
  flare_splash_screen: 3.0.1
  rive: ^0.6.4
  flash: 1.3.1
  flutter_spinkit: 4.1.2+1
  flutter_staggered_grid_view: 0.3.2
  flutter_statusbarcolor: 0.2.3
  flutter_swiper: 1.1.6
  visibility_detector: 0.1.5
  font_awesome_flutter: 8.11.0
  image_picker: 0.6.7+15
  multi_image_picker: ^4.7.14
  intro_slider: 2.3.3
  liquid_swipe: 1.5.0
  page_indicator: 0.3.0
  percent_indicator: 2.1.8
  pin_code_fields: 6.0.1
  pull_to_refresh: 1.6.3
  rate_my_app: 0.7.2
  rubber: 0.4.0
  sticky_headers: 0.1.8+1
  wave: 0.1.0
  zoom_widget: 0.1.3
  cupertino_icons: any

  # WEB TOOLS
  flutter_html: 1.1.1
  video_player: 1.0.1
  html_unescape: 1.0.2
  webview_flutter: 1.0.7
  flutter_widget_from_html: ^0.5.1+3
  flutter_webview_plugin: 0.3.11
  responsive_builder: 0.3.0

  # MAP
  google_maps_flutter: 1.0.6
  location: 2.3.5 # use this version to compatible with fluxbuilder

  # STORAGE
  localstorage: 3.0.3+6
  shared_preferences: 0.5.12+4

  # CONNECTIVITY
  connectivity: 2.0.2
  http: 0.12.2
  http_auth: 0.3.1
  url_launcher: 5.7.10
  uni_links: 0.4.0
  firebase_dynamic_links: 0.6.3

  # AUTHENTICATION
  apple_sign_in: 0.1.0
  flutter_facebook_login: 3.0.0
  google_sign_in: 4.5.6

  # PUSH NOTIFICATION
  firebase_messaging: 7.0.3
  notification_permissions: 0.4.8
  onesignal_flutter: 2.6.2

  # PAYMENTS
  stripe_sdk: 3.2.0
  razorpay_flutter: 1.2.3

  # IMAGES
  extended_image: 1.5.0
  cached_network_image: 2.4.1
  transparent_image: 1.0.0

  # ADS
  facebook_audience_network: 0.7.1
  firebase_admob: 0.10.3 # used with firebase core 5.0.0

  # TOOLS
  auto_size_text: 2.1.0
  event_bus: 1.1.1
  google_fonts: 1.1.1
  random_string: 2.1.0
  share: 0.6.5+4
  sms_autofill: 1.2.6
  #Json Serialization
  json_annotation: 3.1.1
  timeago: 2.0.29
  universal_platform: ^0.1.3
  uuid: 2.2.2
  validate: 1.7.0
  vector_math: any
  async: ^2.4.2
  easy_debounce: 1.0.2
  jwt_decoder: ^1.0.3
  charts_flutter: 0.9.0
  flutter_image_compress: ^0.7.0
  encrypt: ^4.1.0
  adaptive_breakpoints: 0.0.3
  intl: ^0.16.1


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    version: any
  flutter_launcher_icons: 0.8.1
  pedantic: 1.8.0+1 # Analysis
  mockito: ^4.1.1 # Testing

  #To run json serializer, run:
  # flutter pub run build_runner build --build-filter="lib/models/serializers/*.dart" --delete-conflicting-outputs
  # flutter pub run build_runner serve --build-filter="lib/models/serializers/*.dart"
  build_runner: 1.10.9
  json_serializable: 3.5.1
#  intl_translation: 0.17.10


#####################
# Enable this overrides if using the Flutter master/dev channel

#dependency_overrides:
#  intl: 0.17.0-nullsafety.2
#####################

# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/mocks/
    - lib/config/states/
    - lib/config/stories/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - assets/google_fonts/
  fonts:
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
```

How do I resolve this issue as I am still a beginner when it comes to flutter?

**Comment by IchordeDionysos** [comment]
You can easily fix this by upgrading ` intl`.

Or in other words just replace this line:

```
  intl: ^0.16.1
```
 
With this line:
 
```
  intl: ^0.17.0
```

**Comment by dcb-online** [comment]
Hi @IchordeDionysos ,

Thank you for the suggestion however when doing that I get the following error:

```
Because fstore depends on charts_flutter 0.9.0 which depends on intl >=0.15.2 <0.17.0, intl >=0.15.2 <0.17.0 is required.
So, because fstore depends on intl ^0.17.0, version solving failed.
pub get failed (1; So, because fstore depends on intl ^0.17.0, version solving failed.)
```

**Comment by IchordeDionysos** [comment]
Oh I see, what you can try is this:


```
dependency_overrides:
  intl: ^0.17.0
```

**Comment by TahaTesser** [comment]
Hi @dcb-online 
overridng intl solves the conflcts, thanks @IchordeDionysos 

```yaml

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  charts_flutter: ^0.9.0
  cupertino_icons: ^1.0.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0
```


<details> 
<summary>flutter doctor -v</summary> 

```bash[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (14 hours ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM M025F (mobile) • R9ZR205XX0A • android-arm    • Android 10 (API 29)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 11.2.2 20D80
      darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      88.0.4324.192

• No issues found!
```

</details>

Closing as resolved, If you disagree, please write in the comments and I will reopen it.
Thank you
