### ISSUE TITLE
Problem with IOS run after upgrade to latest stable latest SDK release 

### ISSUE THREAD

**Issue by EgHubs** [flutter/flutter#77487]
## Steps to Reproduce

It was working before upgrading to latest stable channel, now it only works with android when I tried ios run I ran into the following problem

## Logs

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                             35.8s
Running Xcode build...                                                  
Xcode build done.                                           46.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    In file included from
    /Users/shalaby/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/wifi_info_flutter-2.0.0/ios/Classes/WifiInfoFlutterPlugin.m:5:
    /Users/shalaby/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/wifi_info_flutter-2.0.0/ios/Classes/WifiInfoFlutterPlugin.h:5:9: fatal
    error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
```

flutter doctor log

```
Mahmouds-MacBook-Air:~ shalaby$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en)
    • Flutter version 2.0.0 at /Users/shalaby/Developer/flutter
    • Framework revision 60bd88df91 (3 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/shalaby/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • E118D356-6965-4777-9CD6-4218B22D2654 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

My pubspec.yami file

```
environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  firebase_messaging: ^9.0.0
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_database: ^6.1.0
  sqflite: ^2.0.0+2
  fluttertoast: ^8.0.1-nullsafety.0
  cached_network_image: ^3.0.0-nullsafety
  geolocator: ^7.0.1
  http: ^0.13.0
  modal_progress_hud: ^0.1.3
  connectivity: ^3.0.2
  shared_preferences: ^2.0.3
  flutter_icons: ^1.1.0
  animated_text_kit: ^4.0.0
  flutter_phoenix: ^0.1.0
  data_connection_checker: ^0.3.4
  provider: ^5.0.0
  wifi_iot: ^0.2.0
  device_info: ^2.0.0
  wifi_info_flutter: ^2.0.0
  app_settings: 4.1.0
  #workmanager: ^0.2.3
  path_provider: ^2.0.1
  flutter_local_notifications: ^5.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  background_fetch: 1.0.0-nullsafety.1
```

It is important to note, that I already tried following steps:

1-Remove ios/Flutter/Flutter.podspec and afterwards wrote flutter clean --> was not working (solution link: #70895)
2-Remove Podfile, Podfile.lock and Flutter.podspec, writing then flutter clean and install new pods (was some stack overflow suggestion)
