### ISSUE TITLE
XYZ requires SDK version >=2.12.0 <3.0.0, version solving failed.

### ISSUE THREAD

**Issue by MalteBoehm** [flutter/flutter#77522]
Hello, today I tried to run my project on my notebook but somehow it keeps complaining when i run Pub get.

`The current Dart SDK version is 2.12.0-133.7.beta.

Because flutter_project_name requires SDK version >=2.12.0 <3.0.0, version solving failed.
pub get failed (1; Because flutter_project_name requires SDK version >=2.12.0 <3.0.0, version solving failed.)`
### This is my pubspec.yml
```
name: flutter_project_name
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_driver_helper: any

  cupertino_icons: ^1.0.2
  google_fonts: any

  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.2+2
```

### Settings

```Flutter 2.1.0-11.0.pre.145 • channel master • https://github.com/flutter/flutter.git
Framework • revision a0ba646408 (2 days ago) • 2021-03-05 22:09:03 -0500
Engine • revision f751d04fa0
Tools • Dart 2.13.0 (build 2.13.0-107.0.dev)
```

### Flutter Doctor 

```
C:\tools\Flutter\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.804], locale de-DE)
    • Flutter version 1.25.0-8.3.pre at C:\tools\Flutter\flutter
    • Framework revision 5d36f2e7f5 (7 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\boema\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.45

! Doctor found issues in 2 categories.
Process finished with exit code 0
```

Thanks for your help
