### ISSUE TITLE
☂️  Unable to upgrade flutter dependencies: dependency conflicts

### ISSUE THREAD

**Issue by pedromassangocode** [flutter/flutter#77681]
I've seem so many issues related to dependencies conflicts in the past few days and they are still popping up. This issue is an umbrella issue to keep track of the related issues and let people discuss about it as those issues usually are not related to Flutter dependencies.

Some Flutter packages are now part of the framework (`flutter_localizations`) so if you are getting it from pub.dev you may have some conflict. To fix this you just need to get it from the framework:

```yaml
flutter_localizations:
  sdk: flutter
```

To import the `integration_test` package it may depend on which channel you are using, for example, on latest dev channel you should get it from the sdk (as in the example above) rather than the version on pub.dev. See https://github.com/flutter/flutter/issues/71379#issuecomment-772055489 for details.

### Tip

If you are facing similar issues, verify wether the package with conflict is related to a first-party package/plugin (aka Flutter team's packages), if not, file an issue in the package's repository.

### Workaround

You can make the use of [Dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) to override the version of packages with conflicts.

### Flutter plugin/packages related issues

For those issues related to Flutter plugin/packages we need to somehow keep dependencies in sync while updating them, see https://github.com/flutter/flutter/issues/72682 as a example where a package from the SDK depends on `intl: ^0.17.0-nullsafety.2` but the `local_auth` package depended on `intl: [...] <0.17.0`. While this can be fixed with dependency overrides, for some users that may be confusing as those packages are considered "Google packages" but it can't work with the Google Product itself as it was pointed out: "2 packages maintained by Google incompatible with each other" in https://github.com/flutter/flutter/issues/77491#issuecomment-793446299.

### Related issues

https://github.com/flutter/flutter/issues/77677
https://github.com/flutter/flutter/issues/77491
https://github.com/flutter/flutter/issues/77515
https://github.com/flutter/flutter/issues/77459
https://github.com/flutter/flutter/issues/77282
https://github.com/flutter/flutter/issues/77593
https://github.com/flutter/flutter/issues/77522
https://github.com/flutter/flutter/issues/77458
https://github.com/flutter/flutter/issues/77377
https://github.com/flutter/flutter/issues/77322
https://github.com/flutter/flutter/issues/77279
https://github.com/flutter/flutter/issues/72682

**Please post your comments here (and look for fixes) before filling another similar issue in this repository.**

**Comment by stuartmorgan** [comment]
As a general note, most of this category of issues is an expected short-term effect of the null-safety transition. Since migrating to null-safety is almost always a breaking change, we have a situation where almost every package in the ecosystem is undergoing a breaking version change at roughly the same time. As a result, it will often be the case that packages that have migrated (and thus rolled their dependencies forward) will have conflicts with those that haven't.

Usually the solution is just to wait until all your dependencies have migrated before updating any packages. (There are some specific cases where it's not that simple, like the SDK case mentioned above.)

**Comment by himanshusharma89** [comment]
For my case, I was facing this similar issue: #77522 and got to know that the SDK versions in fvm were not upgraded. So anyone using fvm can check his/her SDK version for such an issue.

**Comment by LostInDarkMath** [comment]
Are there any plans when `flutter_localization` and `integration_test` (both from SDK) will be up to date including up to date depencies?
I see a lot of errors like this:
```
Because every version of integration_test from sdk depends on args 1.6.0 and flutter_launcher_icons >=0.9.0 depends on args 2.0.0, integration_test from sdk is incompatible with flutter_launcher_icons >=0.9.0.
So, because foo depends on both flutter_launcher_icons ^0.9.0 and integration_test any from sdk, version solving failed.
```

**Comment by pedromassangocode** [comment]
> Are there any plans when `flutter_localization` and `integration_test` (both from SDK) will be updated including up to date dependencies?
> I see a lot of errors like this:
> 
> ```
> Because every version of integration_test from sdk depends on args 1.6.0 and flutter_launcher_icons >=0.9.0 depends on args 2.0.0, integration_test from sdk is incompatible with flutter_launcher_icons >=0.9.0.
> So, because foo depends on both flutter_launcher_icons ^0.9.0 and integration_test any from sdk, version solving failed.
> ```

Can you please provide your `flutter doctor -v` and your `pubspec.yaml`?

**Comment by LostInDarkMath** [comment]
```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 6.1.7601], locale de-DE)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\WILLI\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\WILLI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Mi A2 Lite (mobile) • c1c1eca99806 • android-arm64  • Android 10 (API 29)
    • Chrome (web)        • chrome       • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

```yaml
name: foo
description: Foo
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  pedantic: ^1.11.0 
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  intl: ^0.17.0 
  location: ^4.1.1 
  path_provider: ^2.0.1
  http: ^0.13.1 
  loading_overlay: ^0.3.0  
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^4.1.0  
  flutter_launcher_icons: ^0.9.0  
  dash_chat: ^1.1.15-nullsafety 
  workmanager: ^0.3.0  
  flutter_local_notifications: ^5.0.0+1  
  is_lock_screen: ^2.0.0 
  flutter_ringtone_player: ^3.0.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  logging: ^1.0.1 
  badges: ^2.0.0-nullsafety.1 
  string_validator: ^0.3.0  
  url_launcher: ^6.0.3
  # equatable: ^2.0.0 
  pagination_view: ^2.0.0-nullsafety.0  

flutter_test:
  sdk: flutter
flutter_driver:
  sdk: flutter

dev_dependencies:
  test: ^1.15.7
  flutter_test:
    sdk: flutter
#  integration_test:  # see https://github.com/flutter/flutter/issues/77681
#    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/logo.png"

flutter:
  uses-material-design: true

  assets:
    - lang/de.json   
    - lang/en.json
    - resources/ 
    - environment.env
```

If i uncomment the `integration_test` and run `flutter pub get` I get the error I mentioned above:
```
Because every version of integration_test from sdk depends on args 1.6.0 and flutter_launcher_icons 0.9.0 depends on args 2.0.0, integration_test from sdk is incompatible with flutter_launcher_icons 0.9.0.

And because no versions of flutter_launcher_icons match >0.9.0 <0.10.0, integration_test from sdk is incompatible with flutter_launcher_icons ^0.9.0.

So, because foo depends on both flutter_launcher_icons ^0.9.0 and integration_test any from sdk, version solving failed.
pub get failed (1; So, because conngenial depends on both flutter_launcher_icons ^0.9.0 and integration_test any from sdk, version solving failed.)
```

This might be caused by old dependencies in the SDK version of `integration_test` is guess. So my question is: When you plan to update them?
