### ISSUE TITLE
Flutter androidx-migration Plugin Creating an Issue. Flutter V.1.22.6

### ISSUE THREAD

**Issue by Insha-Siddiquii** [flutter/flutter#77828]
I recently upgraded to flutter from version 1.17.5 stable to flutter version 1.22.6 stable and here is my **flutter doctor -v** output:

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.6 at D:\Drive\FlutterSDKs\flutter_latest\flutter 
    • Framework revision 9b2d32b605 (7 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\insha.siddiqui\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\insha.siddiqui\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\insha.siddiqui\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (1 available)
    • CPH1729 (mobile)  • android-arm64 • Android 7.1.1 (API 25)
```

**Problem:**
I want to use this plugin ( https://pub.dev/packages/adyen_flutter ) but somehow unable to do so as every time I added this plugin in my pubsec.yaml and try to run with a basic example code, I got the following errors

```
D:\Drive\FlutterSDKs\flutter_latest\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java:110: error: cannot find symbol
        HostProvider hostProvider = environment.equals("TEST") ? CardApi.TEST : CardApi.LIVE_EU;
        ^
  symbol:   class HostProvider
  location: class AdyenFlutterPlugin
D:\Drive\FlutterSDKs\flutter_latest\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java:146: error: cannot access Api
D:\Drive\FlutterSDKs\flutter_latest\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java:76: error: cannot find symbol
        HostProvider hostProvider = environment.equals("TEST") ? CardApi.TEST : CardApi.LIVE_EU;
        ^
  symbol:   class HostProvider
  location: class AdyenFlutterPlugin
D:\Drive\FlutterSDKs\flutter_latest\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java:76: error: cannot access HostProvider
        HostProvider hostProvider = environment.equals("TEST") ? CardApi.TEST : CardApi.LIVE_EU;
                                                                        ^
  class file for com.adyen.checkout.base.HostProvider not found
        CardApi cardApi = CardApi.getInstance(this.activity.getApplication(), hostProvider);
                                 ^
  class file for com.adyen.checkout.base.internal.Api not found
Note: D:\Drive\FlutterSDKs\flutter_latest\flutter\.pub-cache\hosted\pub.dartlang.org\adyen_flutter-0.0.3\android\src\main\java\com\pikaway\adyen_flutter\AdyenFlutterPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adyen_flutter:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**PS**
previously on version 1.17.5 I can easily run the app with this plugin but now I am getting the same issue on flutter v 1.17.5 as well.

**pubsec.yaml**
```
name: flutter_adyen_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  adyen_flutter: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



```

@FlutterIssues @pedromassango @zoechi Please help me out, how can I resolve this error.
