### ISSUE TITLE
Flutter Build APK, Error: Type 'CupertinoDialog' not found. extension CupertinoDialogShow on CupertinoDialog {

### ISSUE THREAD

**Issue by artmxra7** [flutter/flutter#77849]
## Flutter Build APK, Error: Type 'CupertinoDialog' not found

1. Run `flutter build apk --debug `.
2.  i got the error is Error: Type 'CupertinoDialog' not found. extension CupertinoDialogShow on CupertinoDialog 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs of error</summary>

```
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

/C:/Users/artmx/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ndialog-3.1.0/lib/src/dialogExtension.dart:88:34: Error: Type 'CupertinoDialog' not found.
extension CupertinoDialogShow on CupertinoDialog {
                                 ^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        39.9s
Gradle task assembleDebug failed with exit code 1
```

</details>

<details>
  <summary>pubspec.yaml</summary>

```
name: demoapp_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: any
  path_provider: any
  shared_preferences: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  smooth_star_rating: ^1.1.1
  intl: ^0.17.0
  http: ^0.12.0+4
  geolocator: ^6.1.6
  sprintf: "^4.0.0"
  connectivity: ^0.4.2
  flutter_html: ^0.8.2
  fluttertoast: ^4.0.0
  get_it: ^5.0.1
  carousel_slider: ^2.3.1
  google_maps_flutter: ^1.0.2
  animated_stack: ^0.1.0
  url_launcher: ^5.0.3
  provider: ^4.0.2
  sliding_up_panel: ^1.0.2
  flutter_spinkit: "^4.1.2"
  rounded_loading_button: ^1.0.0
  flutter_login_facebook: ^0.3.0
  flutter_twitter: ^1.1.3
  crypto: ^2.1.5
  random_string: ^2.1.0
  image_picker: ^0.6.7+12
  flutter_custom_dialog: ^1.0.20
  ndialog: ^3.1.0
  direct_select: "^1.0.3"
  day_night_time_picker: ^0.3.0+2
  cached_network_image: ^2.3.3
  social_share_plugin: ^0.3.1+1
  onesignal_flutter: ^2.0.0


  # flutter_zoom_drawer:
  #   git:
  #     url: https://github.com/mgflutter/flutter_zoom_drawer

  easy_localization: ^2.3.3
  incrementally_loading_listview: ^0.3.0
  shimmer: ^1.1.2
  html_unescape: ^1.0.2
  image_viewer: ^1.0.0
  photo_view: ^0.10.2
  drag_down_to_pop: ^0.2.1
  get_version: ^0.2.2
  # android_intent: ^0.3.6+12
  # permission_handler: ^5.0.1+1
  # location_permissions: ^3.0.0
  flutter_cache_manager: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/langs/
    - assets/maps/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```


```

```
D:\demo_flutter>flutter doctor -v
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-ID)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\artmx\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\artmx\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\artmx\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\artmx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Redmi 5A (mobile) • f252072a7d05 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```

</details>

pleasee help mee....
