### ISSUE TITLE
Font collection must have at least one valid typeface.

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#77913]
### Problem

```
[VERBOSE-2:FontFamily.cpp(184)] Could not get cmap table size!
[VERBOSE-2:FontCollection.cpp(94)] Font collection must have at least one valid typeface.
```

### Code

```yaml
# pubspec.yaml
flutter:
  # (...)

  fonts:
    - family: Noto Color Emoji
      fonts:
        - asset: assets/fonts/Noto/NotoColorEmoji.ttf

```

Noto Color Emoji os from here: https://noto-website-2.storage.googleapis.com/pkgs/Noto-unhinted.zip

```dart
TextFormField(
  style: TextStyle(fontFamily: 'Noto Color Emoji'),
),
```

### Doctor

```
[✓] Flutter (Channel unknown, 2.0.1, on macOS 11.1 20C69 darwin-arm, locale en-GB)
    • Flutter version 2.0.1 at /Users/albert/fvm/versions/2.0.1
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
```
