### ISSUE TITLE
Target of URI doesn't exist: 'package:flutter/material.dart'.

### ISSUE THREAD

**Issue by hit3ham** [flutter/flutter#78199]
my flutter project was working correctly suddenly after flutter update I see this error and also the same for all the files inside the lib directory , when I try to import them without the word "package:"  it works for the files inside lib directory but not for material or provider packages , I tired flutter clean and get pub but the same error 

![image](https://user-images.githubusercontent.com/20839437/111130986-7af33780-8580-11eb-9925-3ad20b14357d.png)

here is the result of flutter doctor -v 

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18362.30], locale en-US)
    • Flutter version 2.0.1 at D:\mobileapps\flutter
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\hit-ham\AppData\Local\Android\sdk
    • Platform android-29, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.2)
    • VS Code at C:\Users\hit-ham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

here is the pubsbec.yaml 

```
name: developet_shopping
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  intl: ^0.16.1
  http: ^0.12.2 
  dropdown_formfield: ^0.1.2
  shared_preferences: ^0.5.8 
  flutter_barcode_scanner: ^1.0.1
  flutter_launcher_icons: ^0.8.1 
  flutter_typeahead: ^1.8.8
  carousel_pro: ^1.0.0    
  dropdown_search: ^0.4.8
  flutter_svg: ^0.19.3
  search_app_bar: ^1.0.2+2
  image_picker: ^0.6.7+22
  image_form_field: ^0.1.0
  url_launcher: ^5.7.10
  flutter_datetime_picker: ^1.5.0
 

dev_dependencies:
  flutter_test: 
    sdk: flutter
```
 thanks for your help
