### ISSUE TITLE
Snap on Ubuntu Core RPi3 fails to render

### ISSUE THREAD

**Issue by AlanGriffiths** [flutter/flutter#78446]
## Steps to Reproduce

With the demo app and the snapcraft YAML below:
```
snapcraft remote-build --launchpad-accept-public-upload
scp super-cool-app_0.1.0_arm64.snap <the RPi>:~
```

on the RPi

```
snap install mir-kiosk
snap install --dangerous super-cool-app_0.1.0_arm64.snap
```

**Expected results:** The demo displays correctly

**Actual results:** Only the decorations display

### Additional details:

Something goes wrong using the `vc4_dri.so` driver on ARM64/RPi3

There's a relevant log line:
```
2021-03-17T17:00:41Z -[16793]: Failed to start Flutter renderer: Unable to create a GL context
```

And the problem can be hidden by adding `LIBGL_ALWAYS_SOFTWARE=true` to the launch command.

<details>
  <summary>snapcraft.yaml</summary>

```
name: super-cool-app
version: 0.1.0
summary: Super Cool App
description: Super Cool App that does everything!

architectures:
  - build-on: amd64
  - build-on: arm64

confinement: strict
base: core18
grade: stable

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/flutterdemo
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build

  super-cool-app:
    command-chain:
      - bin/wayland-launch
    command: flutterdemo
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build

parts:
  super-cool-app:
    plugin: flutter
    source: flutterdemo
    flutter-target: lib/main.dart # The main entry-point file of the application

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl pulseaudio wayland
    stage-packages:
      - inotify-tools

  assets:
    plugin: nil
    stage-packages:
      - dmz-cursor-theme
      - fonts-dejavu
      - fonts-freefont-ttf
      - fonts-ubuntu

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
```
</details>
