### ISSUE TITLE
Maps is flickering on hot reload or marker updates

### ISSUE THREAD

**Issue by neoacevedo** [flutter/flutter#78638]
Hi,

Basically is this comment in StackOverflow: https://stackoverflow.com/questions/66245336/flutter-constant-flickering-in-the-map?noredirect=1#comment117118610_66245336

The minimal code doesn't show this performance: https://github.com/flutter/flutter/issues/43785#issuecomment-790855719

The main problem, the full code is a production app so I can't share anything about the code.

What the most I can share is the full widget structure:

```
WillPop
- MaterialApp
-- Scaffold
--- AppBar
--- SizedBox
---- Column
----- Container
------ Row
------- Text with setState
------- Widget2
----- Container
------ Flexible
-------- Column (visible when click in BottomNavigation to be offline)
-------- FractionallySizedBox
--------- GoogleMaps (visible when click in BottomNavigation to be online)
--- FloatingActionButton
--- BottomNavigationBar
```
When I do a hot reload, the map flicks and the zoom is lost.

When I track the current location, with any marker inside the map, it starts to flick, and if I let the app running for a while, it closes automatically.

<details>
<summary>Flutter doctor</summary>

```
  [✓] Flutter (Channel stable, 1.22.6, on Linux, locale es_CO.UTF-8)
      • Flutter version 1.22.6 at /home/nestor/bin/flutter-sdk
      • Framework revision 9b2d32b605 (hace 8 semanas), 2021-01-22 14:36:39 -0800
      • Engine revision 2f0af37152
      • Dart version 2.10.5
  
  [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
      • Android SDK at /home/nestor/Android/Sdk
      • Platform android-30, build-tools 30.0.3
      • Java binary at: /home/nestor/bin/android-studio/jre/bin/java
      • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
      ✗ Android license status unknown.
        Run `flutter doctor --android-licenses` to accept the SDK licenses.
        See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
  
  [!] Android Studio
      • Android Studio at /home/nestor/bin/android-studio
      ✗ Flutter plugin not installed; this adds Flutter specific functionality.
      ✗ Dart plugin not installed; this adds Dart specific functionality.
      • android-studio-dir = /home/nestor/bin/android-studio
      • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
  
  [✓] VS Code (version 1.54.3)
      • VS Code at /usr/share/code
      • Flutter extension version 3.20.0
  
  [✓] Connected device (1 available)
      • GT N5110 (mobile) • 41038b16e6ad4043 • android-arm • Android 7.1.2 (API 25)
  
  ! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @neoacevedo 
To better address the issue, can you please create a minimal code sample with the widget structure you mentioned and you can fill dummy text or images to make the space
Thank you

**Comment by neoacevedo** [comment]
I have set a minimal code: https://github.com/flutter/flutter/issues/43785#issuecomment-790855719
Also, I have said, a minimal code never will get the real issue.

**Comment by TahaTesser** [comment]
Hi @neoacevedo 
Thanks for the details, I can reproduce the flickering issue on multiple devices when using your code sample

<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:location/location.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:permission_handler/permission_handler.dart' as permission;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
      //routes: routes,
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  ClientRequestPageState createState() => ClientRequestPageState();
}

class ClientRequestPageState extends State<MyHomePage> {
  final GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();

  /// Ubicación actual.
  LocationData currentLocation;

  final Location location = Location();

  /// Broadcast para ubicaciones.
  StreamSubscription<LocationData> _locationSubscription;

  /// Placa del vehículo asignado.
  String text = "ABC";

  /// Controlador del mapa.
  GoogleMapController mapController;

  /// Centra el mapa en las coordenadas indicadas.
  LatLng _center = LatLng(0, 0);

  /// Marcador de ubicación del conductor.
  Marker markerLocation;

  /// Icono de marcador de conductor.
  BitmapDescriptor markerDriverIcon;

  /// Vector para marcadores (conductor y cliente).
  final Map<MarkerId, Marker> _markers = <MarkerId, Marker>{};

  /// ID para el marcador del conductor.
  MarkerId markerId = MarkerId("driver");

  /// Zoom original del mapa.
  double zoom = 17.0;

  /// URL de la imagen de perfil.
  String imgProfile;

  String clientImgProfile;

  /// Imagen para el botón de Ubicación.
  String locationButtonAsset = "images/location_normal.png";

  String alertButtonAsset = "images/panic.png";

  bool isOffline = false;

  Map<Permission, permission.PermissionStatus> statuses;

  Future<void> _checkBackgroundMode() async {
    try {
      final bool result = await location.isBackgroundModeEnabled();
      print("Background? $result");
    } on PlatformException catch (e) {
      print("Code: ${e.code}. Msg: ${e.message}");
    }
  }

  /// Solicita el permiso de ubicación
  void _requestPermission() async {
    try {
      statuses = await [
        Permission.storage,
        Permission.contacts,
        Permission.phone,
        Permission.location
      ].request();
      location.getLocation().then((location) {
        currentLocation = location;
        _center = LatLng(currentLocation.latitude, currentLocation.longitude);
        // Crear el marcador de ubicación.
        markerLocation = Marker(
          markerId: markerId,
          position: LatLng(location.latitude, location.longitude),
        );

        setState(() {
          _markers[markerId] = markerLocation;
        });

        if (mapController != null) {
          mapController.animateCamera(CameraUpdate.newCameraPosition(
              CameraPosition(
                  target: LatLng(_center.latitude, _center.longitude),
                  zoom: zoom)));
        }
      });
    } on PlatformException catch (e) {
      if (e.code == "PERMISSION_DENIED") {
        print("No se pudo obtener la ubicación.");
        currentLocation = null;
      }
      print(e);
    }
  }

  /// Crea el controlador para el mapa cuando este es renderizado.
  void _onMapCreated(GoogleMapController controller) {
    mapController = controller;
    print("zoom: $zoom");
    _startLocationUpdates();
  }

  /// Actualiza el valor del zoom del mapa.
  void _onCameraMove(CameraPosition position) {
    if (position.zoom >= zoom) {
      zoom = position.zoom;
    }
  }

  Future _startLocationUpdates() async {
    _locationSubscription =
        location.onLocationChanged.listen((currentLocation) {
      // Controlar que con cualquier salto del GPS, el marcador no se mueva si no se está avanzando.
      if (currentLocation.accuracy <= 8 && currentLocation.speed >= 1) {
        _center = LatLng(currentLocation.latitude, currentLocation.longitude);
        if (mapController != null) {
          setState(() => _markers[markerId] = markerLocation.copyWith(
              positionParam:
                  LatLng(currentLocation.latitude, currentLocation.longitude)));
        }
      }
    });
  }

  void _updateButtonUi() {
    setState(() {
      isOffline = !isOffline;
    });
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    setState(() {
      text = "BLABLABLA";
    });

    _requestPermission();

    _checkBackgroundMode();
  }

  @override
  void dispose() {
    _locationSubscription.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    double cHeight = MediaQuery.of(context).size.height - 20 * 1.45;

    return MaterialApp(
        home: Scaffold(
      key: scaffoldKey,
      resizeToAvoidBottomInset: false,
      backgroundColor: Colors.greenAccent,
      //drawer: MenuDrawer(context),
      appBar: AppBar(
        title: Text(
          "Application",
          style: TextStyle(color: Colors.yellow, fontSize: 14),
        ),
        backgroundColor: Colors.greenAccent,
      ), //ApplicationBar(scaffoldKey),
      body: SizedBox(
          height: cHeight,
          child: Column(children: [
            Container(
                key: UniqueKey(),
                alignment: Alignment.centerRight,
                padding: EdgeInsets.only(right: 10),
                height: 54,
                decoration: BoxDecoration(color: Colors.greenAccent),
                child: Row(
                  key: UniqueKey(),
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    Text(
                      text ?? "",
                      style: TextStyle(
                          color: Colors.white,
                          fontSize: 20,
                          fontWeight: FontWeight.normal),
                    ),
                  ],
                )),
            Flexible(
                key: UniqueKey(),
                child: FractionallySizedBox(
                  key: UniqueKey(),
                  heightFactor: 1,
                  child: GoogleMap(
                      key: UniqueKey(),
                      onMapCreated: _onMapCreated,
                      onCameraMove: _onCameraMove,
                      markers: Set<Marker>.of(_markers.values),
                      zoomControlsEnabled: false,
                      mapToolbarEnabled: false,
                      initialCameraPosition: CameraPosition(
                        target: _center,
                        zoom: zoom,
                      )),
                )),
            //)
          ])),
      bottomNavigationBar: BottomAppBar(
        child: Container(
            key: UniqueKey(),
            height: 54,
            child: FlatButton(
              color: Colors.greenAccent,
              child: Center(
                  child: Text(
                !isOffline ? 'DESCONECTARSE' : 'CONECTARSE',
                style: TextStyle(color: Colors.white, fontSize: 16),
              )),
              onPressed: () {
                _updateButtonUi();
              },
            )),
      ),
      floatingActionButton: InkWell(
        onTap: () {
          mapController.animateCamera(CameraUpdate.newCameraPosition(
              CameraPosition(
                  target: LatLng(_center.latitude, _center.longitude),
                  zoom: zoom)));
        },
        child: Image.asset(locationButtonAsset, width: 40, height: 40),
      ),
    ));
  }
}

// import 'dart:async';

// import 'package:flutter/material.dart';
// import 'package:google_maps_flutter/google_maps_flutter.dart';

// void main() => runApp(MyApp());

// class MyApp extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Flutter Google Maps Demo',
//       home: MapSample(),
//     );
//   }
// }

// class MapSample extends StatefulWidget {
//   @override
//   State<MapSample> createState() => MapSampleState();
// }

// class MapSampleState extends State<MapSample> {
//   Completer<GoogleMapController> _controller = Completer();

//   static final CameraPosition _kGooglePlex = CameraPosition(
//     target: LatLng(37.42796133580664, -122.085749655962),
//     zoom: 14.4746,
//   );

//   static final CameraPosition _kLake = CameraPosition(
//       bearing: 192.8334901395799,
//       target: LatLng(37.43296265331129, -122.08832357078792),
//       tilt: 59.440717697143555,
//       zoom: 19.151926040649414);

//   @override
//   Widget build(BuildContext context) {
//     return new Scaffold(
//       body: GoogleMap(
//         mapType: MapType.hybrid,
//         initialCameraPosition: _kGooglePlex,
//         onMapCreated: (GoogleMapController controller) {
//           _controller.complete(controller);
//         },
//       ),
//       floatingActionButton: FloatingActionButton.extended(
//         onPressed: _goToTheLake,
//         label: Text('To the lake!'),
//         icon: Icon(Icons.directions_boat),
//       ),
//     );
//   }

//   Future<void> _goToTheLake() async {
//     final GoogleMapController controller = await _controller.future;
//     controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
//   }
// }
``` 

</details>

<details> 
<summary>pubspec.yaml</summary> 

```yaml
name: stable_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.1
  location: ^4.0.2
  permission_handler: ^6.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • IN2011 (mobile) • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-x64     • macOS 11.2.3 20D91
      darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.230, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.230 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 975fb0f06c (3 hours ago), 2021-03-23 21:33:05 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • IN2011 (mobile) • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-x64     • macOS 11.2.3 20D91
      darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

</details>

Thank you
