### ISSUE TITLE
flutter_web_plugins dart: html not found

### ISSUE THREAD

**Issue by shinewanna** [flutter/flutter#78962]
After upgraded to  Flutter 2, can't run my app.

I'm not using my app for web but it getting error with web, it's getting this below error even i migrate my app with web.
it's pointing flutter_web_plugins

flutter version: before- 1.22.0 , after- 2.0.3

<details> 
<summary>logs</summary> 

```bash
Launching lib/main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Invalid depfile: /Users/luke/app/chocholay_zay_app2/.dart_tool/flutter_build/179a193a512410f9cff7a3343ef48521/kernel_snapshot.d
Invalid depfile: /Users/luke/app/chocholay_zay_app2/.dart_tool/flutter_build/179a193a512410f9cff7a3343ef48521/kernel_snapshot.d
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:9:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:5:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^

../../development/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.3/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^

../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:32:57: Error: Type 'html.EventListener' not found.
typedef _AddPopStateListener = ui.VoidCallback Function(html.EventListener);
                                                        ^^^^^^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:76:48: Error: Type 'html.EventListener' not found.
  external ui.VoidCallback addPopStateListener(html.EventListener fn);

                                               ^^^^^^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:34:39: Error: Type 'html.EventListener' not found.
  ui.VoidCallback addPopStateListener(html.EventListener fn);

                                      ^^^^^^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:97:39: Error: Type 'html.EventListener' not found.
  ui.VoidCallback addPopStateListener(html.EventListener fn) {
                                      ^^^^^^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:217:28: Error: Type 'html.EventListener' not found.
  void addPopStateListener(html.EventListener fn);

                           ^^^^^^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:223:31: Error: Type 'html.EventListener' not found.
  void removePopStateListener(html.EventListener fn);
                              ^^^^^^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:287:3: Error: Type 'html.Location' not found.
  html.Location get _location => html.window.location;
  ^^^^^^^^^^^^^

../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:288:3: Error: Type 'html.History' not found.
  html.History get _history => html.window.history;

  ^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:291:28: Error: Type 'html.EventListener' not found.
  void addPopStateListener(html.EventListener fn) {
                           ^^^^^^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:296:31: Error: Type 'html.EventListener' not found.
  void removePopStateListener(html.EventListener fn) {
                              ^^^^^^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:7:7: Error: Type 'AnchorElement' not found.

final AnchorElement _urlParsingNode = AnchorElement();
      ^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:20:7: Error: Type 'Element' not found.
final Element? _baseElement = document.querySelector('base');
      ^^^^^^^

../../development/flutter/.pub-cache/hosted/pub.dartlang.org/gradient_app_bar-0.1.3/lib/gradient_app_bar.dart:407:57: Error: No named parameter with the name 'nullOk'.
    final ScaffoldState scaffold = Scaffold.of(context, nullOk: true);

                                                        ^^^^^^
../../development/flutter/packages/flutter/lib/src/material/scaffold.dart:1952:24: Context: Found this candidate, but the arguments don't match.
  static ScaffoldState of(BuildContext context) {
                       ^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/gradient_app_bar-0.1.3/lib/gradient_app_bar.dart:637:15: Error: Method not found: 'TypeMatcher'.
        const TypeMatcher<RenderSliverFloatingPersistentHeader>());
              ^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/gradient_app_bar-0.1.3/lib/gradient_app_bar.dart:636:20: Error: The method 'ancestorRenderObjectOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorRenderObjectOfType'.
    return context.ancestorRenderObjectOfType(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^

../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:45:14: Error: Method not found: 'allowInterop'.
    getPath: allowInterop(strategy.getPath),
             ^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:46:15: Error: Method not found: 'allowInterop'.
    getState: allowInterop(strategy.getState),
              ^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:47:26: Error: Method not found: 'allowInterop'.
    addPopStateListener: allowInterop(strategy.addPopStateListener),
                         ^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:48:25: Error: Method not found: 'allowInterop'.
    prepareExternalUrl: allowInterop(strategy.prepareExternalUrl),
                        ^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:49:16: Error: Method not found: 'allowInterop'.
    pushState: allowInterop(strategy.pushState),
               ^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:50:19: Error: Method not found: 'allowInterop'.
    replaceState: allowInterop(strategy.replaceState),
                  ^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:51:9: Error: Method not found: 'allowInterop'.
    go: allowInterop(strategy.go),
        ^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:76:53: Error: 'EventListener' isn't a type.
  external ui.VoidCallback addPopStateListener(html.EventListener fn);
                                                    ^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:34:44: Error: 'EventListener' isn't a type.
  ui.VoidCallback addPopStateListener(html.EventListener fn);
                                           ^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:97:44: Error: 'EventListener' isn't a type.
  ui.VoidCallback addPopStateListener(html.EventListener fn) {
                                           ^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:217:33: Error: 'EventListener' isn't a type.
  void addPopStateListener(html.EventListener fn);

                                ^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:223:36: Error: 'EventListener' isn't a type.
  void removePopStateListener(html.EventListener fn);
                                   ^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:287:39: Error: Getter not found: 'window'.
  html.Location get _location => html.window.location;
                                      ^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:288:37: Error: Getter not found: 'window'.
  html.History get _history => html.window.history;
                                    ^^^^^^

../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:291:33: Error: 'EventListener' isn't a type.
  void addPopStateListener(html.EventListener fn) {
                                ^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:292:10: Error: Getter not found: 'window'.
    html.window.addEventListener('popstate', fn);
         ^^^^^^

../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:296:36: Error: 'EventListener' isn't a type.
  void removePopStateListener(html.EventListener fn) {
                                   ^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:297:10: Error: Getter not found: 'window'.

    html.window.removeEventListener('popstate', fn);
         ^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:7:7: Error: 'AnchorElement' isn't a type.
final AnchorElement _urlParsingNode = AnchorElement();
      ^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:7:39: Error: Method not found: 'AnchorElement'.
final AnchorElement _urlParsingNode = AnchorElement();
                                      ^^^^^^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:20:7: Error: 'Element' isn't a type.
final Element? _baseElement = document.querySelector('base');
      ^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:20:31: Error: Getter not found: 'document'.
final Element? _baseElement = document.querySelector('base');
                              ^^^^^^^^
../../development/flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart:66:5: Error: Method not found: 'webOnlySetPluginHandler'.

    ui.webOnlySetPluginHandler(handleFrameworkMessage);
    ^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
[38;5;248m#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:36:7)[39;49m
[38;5;248m#1      asFileUri (package:vm/kernel_front_end.dart:599:37)[39;49m
[38;5;248m#2      writeDepfile (package:vm/kernel_front_end.dart:738:21)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:558:9)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#4      starter (package:flutter_frontend_server/server.dart:180:12)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#5      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)[39;49m
[38;5;244m<asynchronous suspension>[39;49m


FAILURE: Build failed with an exception.

* Where:
Script '/Users/luke/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1029

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/luke/development/flutter/bin/flutter'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

</details>

<details> 
<summary>pubspec.yaml</summary> 

```yaml
name: eslite
description: A new Flutter application.

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.26.0
  easy_localization: 
  shared_preferences: 
  flutter_i18n: 
  http: ^0.12.0+4
  connectivity: ^3.0.2
  font_awesome_flutter: ^8.8.1
  image_picker:
  multi_image_picker: ^4.6.5+rc.1
  dio: ^3.0.9
  pull_to_refresh: ^1.6.2
  cached_network_image: ^2.0.0-rc.1
  location: ^3.0.1
  google_maps_flutter: ^2.0.1
  bottom_navy_bar: ^5.3.2
  flutter_staggered_grid_view: ^0.3.2
  path_provider: ^1.6.5
  apple_sign_in: ^0.1.0
  path:
  photo_view: ^0.10.3
  carousel_slider: ^3.0.0
  firebase_core: ^0.7.0 
  cloud_firestore: ^0.16.0+1 #0.12.11
  firebase_storage: ^7.0.0  #^3.1.6
  firebase_messaging: ^8.0.0-dev.15 #5.1.6
  firebase_auth:
  flutter_image_compress: ^0.7.0
  audioplayers: ^0.16.1
  percent_indicator: ^2.1.1+1
  progress_indicators: ^0.1.4
  exif: ^1.0.1
  get_version: ^0.2.2
  device_info: ^2.0.0
  animations: ^2.0.0
  auto_size_text: ^2.1.0
  #url_launcher: 
  multiselectable_dropdown: ^0.0.4
  flutter_floating_menu: ^0.0.2
  flutter_local_notifications: ^4.0.1+1
  youtube_player_flutter: ^6.1.0+4
  vibration: ^1.2.4
  cupertino_range_slider: ^1.0.1
  fluttertoast: ^7.1.8
  audio_recorder: ^1.0.2
  permission_handler: ^5.0.1+1
  flutter_sms: ^2.1.1
  flutter_facebook_login: ^3.0.0
  share: ^2.0.0
  gradient_app_bar: ^0.1.3
  intl:
  shimmer: ^1.1.1
  flare_flutter: ^2.0.6
  image: ^2.1.4
  flutter_staggered_animations: ^1.0.0
  responsive_builder: ^0.3.0
  velocity_x: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - resources/langs/
    - assets/

  fonts:
    - family: logo
      fonts:
        - asset: fonts/icomoon.ttf

    - family: zawgyi
      fonts:
        - asset: fonts/ZawgyiOne2008.ttf
        - asset: fonts/Raleway-Regular.ttf
          weight: 700

    - family: pyitaungsu
      fonts:
        - asset: fonts/Pyidaungsu-1.8_Regular.ttf
        - asset: fonts/Raleway-Regular.ttf
          weight: 700

    - family: pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
        - asset: fonts/Raleway-Regular.ttf
          weight: 700
```

</details>
