### ISSUE TITLE
video_player crashes in amazon_fire_tv stick

### ISSUE THREAD

**Issue by Gauravkatva** [flutter/flutter#79136]
We are building flutter app for amazon fire tv (android app) and when we try to open the video player screen the app crashes and exits.
```
Stack(
        children: [
          Center(
            child: _controller.value.initialized
                ? AspectRatio(
                    aspectRatio: _controller.value.aspectRatio,
                    child: VideoPlayer(_controller),
                  )
                // : CircularProgressIndicator(),
                : CupertinoActivityIndicator(
                    radius: 40,
                  ),
          ),
          Positioned(
            child: Align(
              alignment: Alignment.bottomCenter,
              child: BottomBar(
                controller: _controller,
                backward: () {
                  _controller.seekTo(
                      _controller.value.position + Duration(seconds: -10));
                  setState(() {});
                },
                forward: () {
                  _controller.seekTo(
                      _controller.value.position + Duration(seconds: 10));
                  setState(() {});
                },
                // currentVideoPosition: _controller.value.position,
                playPause: () {
                  setState(() {
                    _controller.value.isPlaying
                        ? _controller.pause()
                        : _controller.play();
                  });
                },
                stop: () {
                  Navigator.of(context).pop();
                },
              ),
            ),
          ),
        ],
      ),
```

here is the result of flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.1 20C69 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!
```

Here is the result of flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.1 20C69 darwin-arm, locale en-US)
    • Flutter version 2.0.3 at /Users/ryankumar/development/flutter
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ryankumar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

Please help us regarding this issue

**Comment by TahaTesser** [comment]
Hi @Gauravkatva 
Are you using the latest `video_player: ^2.1.0`and Is there a way you can provide crash logs?
Thank you

**Comment by Gauravkatva** [comment]
First of all thanks for your reply. I am using the latest ``` video_player ```package. Here is my my ```pubspec.yaml``` file content. 
```
name: fire_tv
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  video_player:
  dio:
  http:
  native_video_view: 
  better_player:
  flutter_easyloading:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
When we run the app in debug in the real amazon_fire_tv, there was some output on the terminal, let me also share that logs with you, may be that can help.
```
ryankumar@Ryans-MacBook-Pro-2 fire_tv % flutter run 
Launching lib/main.dart on AFTSSS in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        22.3s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                22.1s
Syncing files to device AFTSSS...                                   89ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on AFTSSS is available at: http://127.0.0.1:58059/lGXKo4N2BtQ=/

Flutter DevTools, a Flutter debugger and profiler, on AFTSSS is available at: http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A58059%2FlGXKo4N2BtQ%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
I/flutter (11280): Url: https://kdhkbkto2d.execute-api.us-east-1.amazonaws.com/productionclear/homeData
I/ConfigStore(11280): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::vsyncEventPhaseOffsetNs retrieved: 1000000 (default)
I/ConfigStore(11280): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::vsyncSfEventPhaseOffsetNs retrieved: 1000000 (default)

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 86 pixels on the bottom.

The relevant error-causing widget was:
  Column file:///Users/ryankumar/Desktop/flutter_test/fire_tv/lib/components/movie_tile.dart:31:12

To inspect this widget in Flutter DevTools, visit:
http://127.0.0.1:9101/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A58059%2FlGXKo4N2BtQ%3D%2F&inspectorRef=inspector-0

The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be
seen. If the content is legitimately bigger than the available space, consider clipping it with a
ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
like a ListView.
The specific RenderFlex in question is: RenderFlex#bce3a OVERFLOWING:
  creator: Column ← MovieTile ← RepaintBoundary ← IndexedSemantics ←
    NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← KeyedSubtree ←
    SliverGrid ← MediaQuery ← SliverPadding ← Viewport ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=293.3, h=293.3)
  size: Size(293.3, 293.3)
  direction: vertical
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: start
  textDirection: ltr
  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: A RenderFlex overflowed by 86 pixels on the bottom.

Another exception was thrown: A RenderFlex overflowed by 86 pixels on the bottom.

Another exception was thrown: A RenderFlex overflowed by 86 pixels on the bottom.

Another exception was thrown: A RenderFlex overflowed by 86 pixels on the bottom.```
After that we lost the connection to the device. Note that by this above run command we run the apk in debug mode. We also try to run this in the release mode. But the issue was same, the application crashed.

What to do next? thanks!!!
