### ISSUE TITLE
Flutter pub get problem

### ISSUE THREAD

**Issue by acbirja2** [flutter/flutter#79736]
Hello, my probelm in android studio run flutter pub get.
I have a problem how can I solve this.

C:\src\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in Flutter-BuySell...   

Because flutterbuyandsell depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because flutterbuyandsell depends on intl 0.16.1, version solving failed.
pub get failed (1; So, because flutterbuyandsell depends on intl 0.16.1, version solving failed.)

Process finished with exit code 1

**pubspec.yaml**

```
name: flutterbuyandsell
description: A new Flutter ecommerce store application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+14

# CCV 2.1 = 2.1.0+14
# CCV 2.0 = 2.0.0+13
# CCV 1.9 = 1.9.0+12
# CCV 1.8 = 1.8.0+11
# CCV 1.7 = 1.7.0+10
# CCV 1.6 = 1.6.0+9
# CCV 1.5 = 1.5.0+7
# CCV 1.4 = 1.4.0+6
# CCV 1.4 = 1.4.0+5
# CCV 1.3 = 1.3.0+4
# CCV 1.2 = 1.2.0+3
# CCV 1.1 = 1.1.0+2
# CCV 1.0 = 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: 0.5.10
  optimized_cached_image: 1.0.0
  http: 0.12.2
  provider: 4.3.2+2
  connectivity: 0.4.9+2
  dynamic_theme: 1.0.1
  sembast: 2.4.7+6
  path_provider: 1.6.14
  intl: 0.16.1
  shimmer: 1.1.1
  url_launcher: 5.5.2
  carousel_slider: 2.2.1
  firebase_core: 0.5.0
  firebase_messaging: 7.0.0
  firebase_database: 4.0.0
  firebase_auth: 0.18.1
  flutter_native_admob: 2.1.0+3
  google_sign_in: 4.5.3
  flutter_facebook_login: 3.0.0
  flutter_webview_plugin: 0.3.11
  photo_view: 0.10.2
  progress_dialog: 1.2.4
  braintree_payment: 1.2.4
  easy_localization: 2.3.3
  launch_review: 2.0.0
  package_info: 0.4.3
  flutter_icons: 1.1.0
  stripe_payment: 1.0.7
  flutter_credit_card: 0.1.3
  fluttertoast: 7.0.4
  permission_handler: 5.0.1+1
  flutter_map: 0.10.1+1
  latlong: 0.6.1
  geocoder: 0.2.1
  geolocator: 5.1.3
  multi_image_picker: 4.7.12
  flutter_widget_from_html: 0.5.0
  # flutter_share: 1.0.5
  share: 0.6.5+4
  apple_sign_in: 0.1.0
  razorpay_flutter: 1.2.2
  group_radio_button: 1.0.1
  flutter_native_image: 0.0.5+2
  flutter_paystack: 1.0.4+1
  firebase_dynamic_links: 0.5.0+11
  in_app_purchase: 0.3.4+16
  camera: 0.5.8+11
  flutter_linkify: ^4.0.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_local_notifications:
  #  path: lib/utils/local_noti/

 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/placeholder_circle_image.png
   - assets/images/placeholder_image.png
   - assets/langs/ar-DZ.json
   - assets/langs/en-US.json
   - assets/langs/hi-IN.json
   - assets/langs/de-DE.json
   - assets/langs/es-ES.json
   - assets/langs/fr-FR.json
   - assets/langs/id-ID.json
   - assets/langs/it-IT.json
   - assets/langs/ja-JP.json
   - assets/langs/ko-KR.json
   - assets/langs/ms-MY.json
   - assets/langs/pt-PT.json
   - assets/langs/ru-RU.json
   - assets/langs/th-TH.json
   - assets/langs/tr-TR.json
   - assets/langs/zh-CN.json
   - assets/images/verify_email_icon.jpg
   - assets/images/down.png
   - assets/images/baesline_access_time_black_24.png
   - assets/images/baseline_check_green_24.png
   - assets/images/baseline_graph_black_24.png
   - assets/images/baseline_price_down_black_24.png
   - assets/images/baseline_price_up_black_24.png
   - assets/images/baseline_empty_item_grey_24.png
   - assets/images/home_icon/discount_products.png
   - assets/images/home_icon/easy_payment.png
   - assets/images/home_icon/featured_products.png
   - assets/images/home_icon/free_download.png
   - assets/images/trending.png
   - assets/images/flutter_buy_and_sell_logo.png
   - assets/images/flutter_buy_and_sell_logo_light.png
   - assets/images/baseline_pin_black_24.png
   - assets/images/baseline_favourite_grey_24.png
   - assets/images/default_image.png
   - assets/images/baseline_promotion_color_74.png
   - assets/images/user_default_photo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
