### ISSUE TITLE
[web][canvaskit] Scrollable emoji freezes the app 

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#79882]
We've run into an issue where if you place emojis in a grid on Web (CanvasKit renderer) and scroll the whole app will lock up.

Progress indicator is only to demonstrate when frames are being dropped by the app.

https://user-images.githubusercontent.com/666539/113762128-41789c80-96e6-11eb-9e00-d441216a85d5.mov

## Flutter doctor

```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

• No issues found!
```

## MCVE

```yaml
name: spike_emoji_grid
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  emojis: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

```dart
import 'dart:ui';

import 'package:emojis/emoji.dart';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final emojis = Emoji.all();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Emoji CanvasKit Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: Container(
            height: 400,
            width: 400,
            color: Colors.red.shade100,
            child: Scrollbar(
              child: GridView.builder(
                itemCount: emojis.length,
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 8,
                  mainAxisSpacing: 8,
                  crossAxisSpacing: 8,
                ),
                itemBuilder: (context, index) {
                  return Text(
                    emojis[index % emojis.length].char,
                    style: TextStyle(fontSize: 20),
                  );
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```
