### ISSUE TITLE
Pre-null-safe-migration apps using local_auth are broken by Flutter 2.0

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#80005]
Consider the following pubspec file:

```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  local_auth: ">=0.6.0+1 <1.0.0-nullsafety.3"
```

This project would be able to `flutter pub get` prior to Flutter 2, but since Flutter 2 [pins the `intl` dependency to `0.17.0`](https://github.com/flutter/flutter/blob/flutter-1.26-candidate.17/packages/flutter_localizations/pubspec.yaml#L11), the developer gets the following error when trying to fetch packages:

```
Because local_auth >=0.6.0+1 <1.0.0-nullsafety.3 depends on intl >=0.15.1 <0.17.0 and every version of flutter_localizations from sdk depends on intl 0.17.0, local_auth >=0.6.0+1 <1.0.0-nullsafety.3 is incompatible with flutter_localizations from sdk.
So, because foo depends on both flutter_localizations any from sdk and local_auth >=0.6.0+1 <1.0.0-nullsafety.3, version solving failed.
```

But if they can't yet upgrade to null safety because some of their other dependencies haven't yet upgraded, then they're stuck, and they can no longer run their project at all.

Related: https://github.com/dart-lang/intl_translation/issues/134

/cc @poitch @stuartmorgan @leafpetersen
