### ISSUE TITLE
[animations] The `animations` library causes the page to be unable to slide back

### ISSUE THREAD

**Issue by kw214** [flutter/flutter#80032]
The `animations` library is used in the project, I found that the page cannot be returned by sliding

**Comment by pedromassangocode** [comment]
Hi @realkimmy 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample?
Thank you

**Comment by realkimmy** [comment]
[repo](https://github.com/realkimmy/animations_bug_reporter)

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.4 at /Users/ying/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ying/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/ying/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (4 available)
    • yz的iPhone (mobile)         • 9bb79b4b2747dbd2d2cb7bb9da2e3cb5fb5f7e4b • ios            • iOS 14.4.2
    • iPhone 12 Pro Max (mobile) • 8E8B6DBB-6AC6-42FE-A784-D23869473FD2     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)            • macos                                    • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

`pubspec.yaml`

```
name: xxx
description: 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.11.0
  webview_flutter: ^1.0.7
  flutter_inappwebview: ^5.0.5+3
  device_info: ^2.0.0
  share: ^2.0.0
  localstorage: ^3.0.6+9
  provider: ^4.3.3
  flutter_bloc: ^6.1.3
  hydrated_bloc: ^6.1.0
  http: ^0.12.0+2
  flutter_color_plugin: ^0.0.2
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  pretty_dio_logger: ^1.1.1
  flutter_svg: ^0.19.3
  intl: ^0.17.0
  flutter_sticky_header: ^0.5.0
  flutter_staggered_grid_view: ^0.3.4
  adaptive_dialog: ^0.10.0+5
  cached_network_image: ^2.5.0
  rate_my_app: ^0.7.2
  uni_links: ^0.4.0
  bot_toast: ^3.0.5
  flutter_markdown: ^0.5.2
  bubble_tab_indicator: ^0.1.4
  splashscreen: ^1.3.5
  json_annotation: ^3.0.0
  flutter_splash_screen: ^0.1.0
  open_appstore: ^1.0.2
  flutter_highlight: ^0.7.0
  sentry_flutter: ^4.0.6
  lottie: ^0.7.0+1
  google_fonts: ^1.1.2
  package_info: ^0.4.3+4
  vibration: ^1.7.3
  flutter_colorpicker: ^0.3.5
  flutter_widget_from_html: ^0.5.2+1
  flutter_linkify: ^4.1.0
  dots_indicator: ^1.2.0
  graphql_flutter: ^4.0.1
  extended_text: ^5.0.5
  animations: ^2.0.0
  cupertino_back_gesture: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.3


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
#          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  generate: true
```
