### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by PINHOf** [flutter/flutter#80229]
Hello,

There are several topics about this subject through stackoverflow & flutter github repository, but none of the solutions have worked for me. I created & published an App for iOS & Android store 2 months ago. I use a windows computer to code & deploy to Android and to deploy to iOS I borrowed a MacOS. Everything worked without any problem.

Recently, the client of the App asked for a few changes, so I just updated the code in my windows computer, sent to github repository & pull from github in the MacOS. It works on windows but unfortunately since then I'm unable to Build, Analyze or Archive through Xcode.

The error is **Command PhaseScriptExecution failed with a nonzero exit code**.

### Log of the error
[https://pastebin.com/XLQKBjiq](https://pastebin.com/XLQKBjiq)

### flutter build ios --verbose (too long to paste on www.pastebin.com)
[https://zerobin.net/?3bda0e68ee35cbb8#ZP2uoI9f1y+ORDk7RKqM2tgJT5aboXNDMX66fbQ5pmA=](https://zerobin.net/?3bda0e68ee35cbb8#ZP2uoI9f1y+ORDk7RKqM2tgJT5aboXNDMX66fbQ5pmA=)

### flutter doctor -v
> [✓] Flutter (Channel master, 2.1.0-13.0.pre.574, on macOS 11.1 20C69 darwin-x64, locale en-PT)
>     • Flutter version 2.1.0-13.0.pre.574 at /users/yok/documents/flutter
>     • Framework revision 02efffc134 (35 hours ago), 2021-04-10 03:49:01 -0400
>     • Engine revision 8863afff16
>     • Dart version 2.13.0 (build 2.13.0-222.0.dev)
> 
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, please use
>       `flutter config --android-sdk` to update to that location.
> 
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.3, Build version 12C33
>     • CocoaPods version 1.10.1
> 
> [✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
>     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
> 
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 4 categories.

### pubspec.yaml
```
name: ********
description: ************

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.7+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  image_picker: ^0.6.7+11
  dio: ^3.0.10
  convex_bottom_bar: ^2.5.0
  flutter_spinkit: "^4.1.2"
  adaptive_dialog: ^0.9.0+1
  shared_preferences: ^0.5.12+4
  firebase_messaging: ^7.0.3
  date_picker_timeline: ^1.2.1
  flutter_picker: ^1.1.5
  file_picker: ^2.1.4
  photo_view: ^0.10.3
  url_launcher: ^5.7.10
  flutter_launcher_icons: ^0.8.1
  flutter_native_image: ^0.0.5
  flutter_local_notifications: ^3.0.3

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

### What have I tried:

- flutter clean
- fluter pub get
- pod deintegrate
- pod install
- clone again the project (doesn't work)
- create a new flutter project (works!)
- And so many other things I can't even remember (https://stackoverflow.com/questions/53289524/xcode-10-2-1-command-phasescriptexecution-failed-with-a-nonzero-exit-code)
