### ISSUE TITLE
Error in pubspec.yaml: Unexpected child "asserts" found under "flutter"

### ISSUE THREAD

**Issue by ron-don** [flutter/flutter#80345]
Using Flutter, I get the following error message when building:

Error detected in pubspec.yaml:
Unexpected child "asserts" found under "flutter".

What is there to change in order to get rid of this error message ?

Here is my pubspec.yaml file:

[pubspec.txt](https://github.com/flutter/flutter/files/6301804/pubspec.txt)

Here is my flutter doctor -v log:

[flutter doctor -v.txt](https://github.com/flutter/flutter/files/6301809/flutter.doctor.-v.txt)

**Comment by darshankawar** [comment]
@ron-don 
Used your pubspec.yaml as-is, in a sample app and flutter pub get was run without any issues:

```
/Users/dhs/Documents/Fluttersdk/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in macbug...                              3.3s
Process finished with exit code 0
```

<details>
<summary> pubspec.yaml </summary>

```
name: prisons
description: PMS

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: 0.12.1
  flutter_staggered_grid_view: ^0.3.0
  data_tables: ^1.0.1
  get_it: ^2.0.1
  modal_progress_hud: ^0.1.3
  flutter_form_builder: ^5.0.0
  file_picker: 1.4.2
  path_provider: ^1.4.5
  fit_image: ^0.1.2
  flutter_typeahead: ^3.1.0
  flutter_keyboard_visibility:
  url_launcher: ^6.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+4
  image_cropper: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/uploadPerson.png
    - images/fingerprintUpload.png
    - images/prisonModule.png
    - images/PrisonImage.jpg
    - images/cameraButton.png
    - images/uploadButton.png
    - images/registration_screen.png
    - images/logo.png
    - images/leftFaceIcon.png
    - images/rightFaceIcon.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #    - family: MyFlutterApp
  #      fonts:
  #        - asset: assets/fonts/MyFlutterApp.ttf
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "images/logo.png"

```

</details>

Double check your pubspec.yaml to see if there are any indentation or typos which could be throwing the issue at your end.
