### ISSUE TITLE
ViewPostIme pointer 0,1 and onTap/onPressed not working on specific android physical device

### ISSUE THREAD

**Issue by umbertogrimaldi** [flutter/flutter#80346]
After upgrade my flutter version to 2.0 (2.0.3/2.04), if I'm using specific physical device (Samsung A8 and A6+), every time I touch on the screen, I'm getting this messages on terminal, and the onTap event is completely not working.

`D/ViewRootImpl@MainActivity: ViewPostIme pointer 0`

followed by

`D/ViewRootImpl@MainActivity: ViewPostIme pointer 1`

Can someone help me? I've several apps afflicted by this issue.

MY LOGS:

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/umbertogrimaldi/flutter
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/umbertogrimaldi/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SLA L02 (mobile)             • R4BBB17A17500798                     • android-arm    • Android 7.0 (API 24)
    • AOSP on IA Emulator (mobile) • emulator-5556                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone 12 Pro (mobile)       • 219DD62F-D57D-4CF5-BC1C-877E3122699F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 89.0.4389.114
    ! Error: UMBERTO’s iPhone is not connected. Xcode will continue when UMBERTO’s iPhone is connected. (code -13)

```

</details>

<details>
<summary>pubspec.yaml</summary>

```yaml

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_settings: ^4.1.0
  auto_size_text: ^2.1.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  custom_refresh_indicator: ^0.9.0
  device_info_plus: ^1.0.0
  firebase_analytics: ^7.1.1
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.0
  firebase_dynamic_links: ^0.8.0
  firebase_messaging: ^9.0.0
  flutter_app_badger: ^1.2.0
  flutter_cache_manager: ^2.1.2
  flutter_exif_rotation: ^0.4.1
  flutter_secure_storage: ^4.1.0
  html: ^0.15.0
  http: ^0.13.0
  image_picker: ^0.7.3
  intl: ^0.17.0
  json_annotation: ^4.0.0
  json_serializable: ^4.0.3
  mime: ^1.0.0
  optimized_cached_image: ^2.0.0
  package_info: ^2.0.0
  permission_handler: ^6.1.0
  provider: ^5.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^1.1.2
  span_builder: ^0.1.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/
    - lib/assets/graphics/
    - lib/assets/images/
```

</details>
