### ISSUE TITLE
Disable default SSL pinning in flutter

### ISSUE THREAD

**Issue by MadhusudhanSahni** [flutter/flutter#80414]
Hi,
I am using the version of flutter(1.20.1). I came across the same issue the security team is requesting to disable the SSL pinning in my app. but I do not enable the SSL pinning. So how we can disable default SSL pinning from the flutter app. 
Here are the dependencies used in App -

<details> 
<summary>pubspec.yaml</summary> 

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc_pattern: ^0.0.1+1
  provider: ^4.3.1
  flutter_spinkit: "^4.1.1"
  google_fonts: ^0.2.0
  flutter_echarts: ^1.3.5
  number_display: ^2.3.0
  charts_flutter: ^0.9.0
  horizontal_data_table: ^1.0.5+5
  search_widget: ^1.0.2
  lottie: ^0.5.1
  dio: ^3.0.10
  xml: ^3.5.0
  fluttertoast: ^7.0.2
  shared_preferences: ^0.5.8
  firebase_crashlytics: ^0.1.4+1
  carousel_slider: ^2.2.1
  expandable: ^4.1.4
  get_it: ^4.0.4
  rxdart: ^0.24.1
  flutter_secure_storage: ^3.3.3
  local_auth: ^0.6.1
  webview_flutter: ^0.3.24
  flutter_webview_plugin: ^0.3.11
  passcode_screen: ^1.2.0
  percent_indicator: ^2.1.7+4
  url_launcher: ^5.7.6
  firebase_messaging: ^7.0.3
```

</details>

And here are the Screenshot shared by the VAPT(Security) team.

![1](https://user-images.githubusercontent.com/32368287/114514875-6080ac80-9c59-11eb-9514-1d56c59ca412.jpeg)

Here is the Doctor Summary:-
![Screenshot 2021-04-14 at 1 26 52 PM](https://user-images.githubusercontent.com/32368287/114674832-43191480-9d25-11eb-83a7-adf86e2f4c4f.png)

Thanks

_Originally posted by @MadhusudhanSahni in https://github.com/flutter/flutter/issues/35852#issuecomment-818520363_
