### ISSUE TITLE
FLTURLLauncherPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found     #import <Flutter/Flutter.h> after Flutter upgrade to 2.0.4 channel Stable

### ISSUE THREAD

**Issue by KJBoricha** [flutter/flutter#80489]
```console
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from /Users/macpro5/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.3/ios/Classes/FLTURLLauncherPlugin.m:7:
    /Users/macpro5/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.3/ios/Classes/FLTURLLauncherPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
```

**Comment by TahaTesser** [comment]
Hi @KJBoricha 
Thanks for filing the issue, please try this [solution ](https://github.com/flutter/flutter/issues/70895#issuecomment-744734693) or [this](https://github.com/flutter/flutter/issues/70895#issuecomment-792755327)

**Comment by acanturgut** [comment]
@TahaTesser I tried mentioned solutions still same for me. 

```
In file included from /usr/local/Caskroom/flutter/2.0.4/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-1.0.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.m:5:
    /usr/local/Caskroom/flutter/2.0.4/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-1.0.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.h:8:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    While building module 'firebase_core' imported from /usr/local/Caskroom/flutter/2.0.4/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-1.0.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.h:12:
    In file included from <module-includes>:1:
    In file included from /Users/acanturgut/Documents/done/done-flutter/ios/Pods/Target Support Files/firebase_core/firebase_core-umbrella.h:13:
    //usr/local/Caskroom/flutter/2.0.4/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.2/ios/Classes/FLTFirebaseCorePlugin.h:8:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    2 errors generated.

```

Flutter run --verbose result 

```
[+2227 ms] Could not build the application for the simulator.
[   +3 ms] Error launching application on iPhone 12 mini.
[   +7 ms] "flutter run" took 313,425ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

Flutter doctor

```
> $ flutter doctor                                                                                                                 ⬡ 10.23.0 [±master ●]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
@acanturgut
Your issue is related `firebase_crashlytics`, it is been fixed, updated package https://github.com/flutter/flutter/issues/79575

**Comment by erperejildo** [comment]
> firebase_crashlytics

Maybe a stupid question but how do I update it?

**Comment by acanturgut** [comment]
@erperejildo That's strange. It should be inside of the  pubspec.yaml`. I updated latest version and problem was resolved. Might be libraries using but it is quite impossible. Could you share your error message. Maybe it is not related with `firebase_crashlytics`.

**Comment by erperejildo** [comment]
```
** BUILD FAILED **


Xcode's output:
↳
    In file included from /Users/dani/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.3/ios/Classes/FLTURLLauncherPlugin.m:7:
    /Users/dani/development/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.3/ios/Classes/FLTURLLauncherPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by acanturgut** [comment]
Great problem is `url_launcher` plugin when you update it. Your problem will be resolved.

**Comment by erperejildo** [comment]
> Great problem is `url_launcher` plugin when you update it. Your problem will be resolved.

I have the latest version, 6.0.3:
https://pub.dev/packages/url_launcher/install

**Comment by acanturgut** [comment]
If you read the logs it is says which libraries has problem 

```
  /Users/dani/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/ios/Classes/FLTSharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
```
 ⬆️ 
    
For this one `FLTSharedPreferencesPlugin`

**Comment by erperejildo** [comment]
> If you read the logs it says which libraries have problem
> 
> ```
>   /Users/dani/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/ios/Classes/FLTSharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
>     #import <Flutter/Flutter.h>
> ```
> 
> ⬆️
> 
> For this one `FLTSharedPreferencesPlugin`
> 
> Try to remove or upgrade libraries. But your problem is not related with `crashanlytics`

Sorry but still not understanding. All my libraries are updated. You pointed out to shared_preferences:
https://pub.dev/packages/shared_preferences/install
2.0.5 is the latest

**Comment by TahaTesser** [comment]
@erperejildo 
Have you tried deleting ` rm ios/Flutter/Flutter.podspec` 
I am pretty sure `fatal error: 'Flutter/Flutter.h' file not found` is also fixed, I don't see this issue anymore 
If nothing works, `flutter pub cache repair`

**Comment by erperejildo** [comment]
> @erperejildo
> Have you tried deleting ` rm ios/Flutter/Flutter.podspec`
> I am pretty sure `fatal error: 'Flutter/Flutter.h' file not found` is also fixed, I don't see this issue anymore
> If nothing works, `flutter pub cache repair`

Yes and also tried removing the whole ios folder and pasting a new fresh one created from a new created project and updating my Podfile.

Also something that didn't work:
- Created a new project
- Run iOS: ok
- Copied my pubspec.yaml (see below)
- Run iOS: the error
- Copied again the original pubspec.yaml
- Clean project
- Run iOS: the error
- Clean cache
- Run iOS: the error
- Reinstall Flutter:
- etc


Everything is updated:
```
name: my_rents
description: Manage your properties and their rents easily

version: 2.0.3+2.0.3

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dapackages: ^1.6.0 # keeps packages updated
  firebase_crashlytics: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter_cupertino_localizations: ^1.0.1
  flutter_translate: ^2.0.1
  flutter_google_places: ^0.3.0
  google_mobile_ads: ^0.12.1+1
  #  firebase_admob: 0.11.0+1 # REMOVE AND USE THE NEW ONE
  maps_launcher: ^2.0.0
  progress_dialog: ^1.2.4 # NO NULL
  uuid: ^3.0.4 # IDs for events
  cloudinary_public: ^0.8.1+1
  provider: ^5.0.0
  firebase_auth: ^1.1.2
  firebase_analytics: ^8.0.2
  firebase_core: ^1.1.0
  cloud_firestore: ^1.0.7
  http: ^0.13.1
  flutter_facebook_login: ^3.0.0 # NO NULL
  apple_sign_in: ^0.1.0 # NO NULL
  google_sign_in: ^5.0.2
  shared_preferences: ^2.0.5
  intl: ^0.17.0 # locales for table_calendar and datetime manipulation
  flutter_downloader: ^1.6.0
  jiffy: ^4.1.0 # date manipulation
  permission_handler: ^7.0.0
  path_provider: ^2.0.1
  after_init: ^0.1.2 # NO NULL
  flutter_email_sender: ^5.0.0
  flutter_launcher_icons: ^0.9.0
  file_picker: ^3.0.1 # for multiple images selection
  image_picker: ^0.7.4 # for camera
  image: ^3.0.2
  url_launcher: ^6.0.3
  transparent_image: ^2.0.0
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_svg: ^0.22.0
  table_calendar: ^3.0.0
  add_2_calendar: ^2.1.0
  flutter_local_notifications: ^5.0.0+2
  contacts_service: ^0.6.1 # get contacts
  in_app_purchase: ^0.5.2
  device_info: ^2.0.0
  flutter_platform_widgets: ^1.4.1
  flutter_native_splash: ^1.1.8+4
  intl_phone_number_input: ^0.7.0+1  # NO NULL
  country_pickers: ^2.0.0
  currency_picker: ^2.0.3
  #  country_currency_pickers: ^1.0.1 # NO NULL
  flutter_open_whatsapp: ^0.1.2 # NO NULL
  reorderables: ^0.4.1 # NO NULL reorder rent fields
  drag_and_drop_gridview: ^1.0.8 # NO NULL
  pdf: ^3.3.0
  printing: ^5.2.1 # necessary for the above one
  open_file: ^3.2.0 # necessary for the above one
#  syncfusion_flutter_calendar: ^19.1.56

# generate new splashscreen: flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/icon.jpg
  color: 'ffffff'
  fill_horizontal: true

# generate new icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/icon.jpg'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/images/versions/
    - assets/icons/
    - assets/fonts/

```
