### ISSUE TITLE
Unsupported operation: dart:isolate is not supported on dart4web

### ISSUE THREAD

**Issue by jayeshindianic** [flutter/flutter#80493]
Flutter web is working on desktop browser but issues on mobile browser
even in release or debug mode , its just stuck 
`Unsupported operation: dart:isolate is not supported on dart4web`
just show this error nothing else,
i have alredy try to remove all print(). but its not working

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (1 available)

• No issues found!
```

```
name: xyz
description: xyz
version: 3.2.2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl:
  intl_translation:
  barcode_scan:
  google_maps_flutter:
  google_maps: ^5.1.0
  connectivity:
  share:
  http:
  google_fonts: ^1.1.2
  firebase_analytics: ^7.1.1
  firebase: 7.3.0
  firebase_dynamic_links: ^0.8.0
  shared_preferences:
  get: ^3.26.0
  auto_size_text: ^2.1.0
  cached_network_image:
  url_launcher:
  flutter_html:
  font_awesome_flutter:
  carousel_pro:
  nice_button:
  sentry_flutter:
  http: any
  collection: ^1.14.6
  json_annotation:
  intl: ^0.16.1
  timeago: ^2.0.2
  rxdart: any
  protobuf: ^1.1.1



dev_dependencies:
  pedantic:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_goldens:
    sdk: flutter

publish_to: none

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

```
