### ISSUE TITLE
Mark integration_test discontinued on pub.dev

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#80607]
Since the `integration_test` package is now vendored with the SDK, we should update the README on the published version to tell users how to use the SDK vendored version:

```yaml
dependencies:
  integration_test:
    sdk: flutter
```

<img width="753" alt="Screen Shot 2021-04-16 at 4 37 19 PM" src="https://user-images.githubusercontent.com/1145719/115094339-076f7d80-9ed2-11eb-88ab-bb5752ce89e6.png">
