### ISSUE TITLE
pub get failed (server unavailable) trying to get packages

### ISSUE THREAD

**Issue by ben-hu99** [flutter/flutter#80635]
Hello,

New to flutter I am getting the following output when trying to get packages. 
```

[counter] flutter pub get
Running "flutter pub get" in counter...                     
Because counter depends on random_strings any which doesn't exist (could not find package random_strings at https://pub.dartlang.org), version solving failed.

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

Because counter depends on random_strings any which doesn't exist (could not find package random_strings at https://pub.dartlang.org), version solving failed.

pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
```
pubspec.yaml
```
name: counter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  google_sign_in:
  shared_preferences:
  random_strings:
  firebase_auth:
  cloud_firestore:
  cupertino_icons:

dev_dependencies:
 flutter_test:
   sdk: flutter

flutter:
  uses-material-design: true
```
Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.928], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.55.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
@ben-hu99 
please try these steps:
- upgrade flutter to the latest stable 
    running `flutter upgrade -f`
- add the latest version to your dependencies 
    replacing your environment and dependencies with the one below

```yaml
environment:
   sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.3
  google_sign_in: ^5.0.2
  shared_preferences: ^2.0.5
  random_string: ^2.1.0
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.5
  cupertino_icons: ^1.0.2
```
- **_delete_** you `pubspec.lock` and run `flutter pub get`
