### ISSUE TITLE
Flutter application can not take response from any request after upgraded

### ISSUE THREAD

**Issue by tam-dev** [flutter/flutter#80700]
My case: After upgrade to Flutter Channel Stable version 2.0.5 from version 2.0.0 my app can not take res from any request to the server (I am using DIO) No log, no debugger console, no error,... I have tried to downgrade to 2.0.0, change the channel, clone the project into another machine, but still not resolve problem. I was stuck for 5 days...

Here is my pubsec:

```
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # Packages
  flutter_onboard: ^0.1.0
  splashscreen: ^1.3.5
  flutter_screenutil: ^4.0.2+3
  pin_code_fields: ^6.0.2
  dots_indicator: ^1.2.0
  animated_bottom_navigation_bar: ^0.2.1
  circular_reveal_animation: ^1.1.5
  auto_size_text: ^2.1.0
  expandable: ^4.1.4
  # carousel_slider: ^2.3.1
  flutter_bloc: ^6.1.1
  bloc: ^6.1.1
  rxdart: ^0.25.0
  equatable: ^1.2.3
  meta: ^1.1.8
  flutter_html: ^0.8.2
  qr_code_scanner: ^0.3.0
  flutter_easyloading: ^2.2.2
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  sign_in_with_apple: ^2.5.4
  carousel_slider: ^3.0.0
  cached_network_image: ^2.5.0
  flutter_secure_storage: ^3.3.3
  webview_flutter: ^1.0.7
  flutter_datetime_picker: ^1.5.0
  flutter_spinkit: ^4.1.2+1
  package_info: ^0.4.3+4

  # firebase's packages
  firebase_crashlytics: ^2.0.0
  firebase_analytics: ^8.0.0
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3

  # dependencies
  image_picker: ^0.7.4
  image: ^3.0.2
  flutter_svg: ^0.21.0+1
  pull_to_refresh: ^1.6.5
  device_info: ^2.0.0
  sim_info: ^0.1.3
  permission_handler: ^6.1.3
  geolocator: ^7.0.3
  url_launcher: ^6.0.3

  # easy_localization: ^2.0.2
  # http client
  http_parser: ^4.0.0
  connectivity: ^3.0.3
  http: ^0.13.1
  dio: ^4.0.0
  
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  shared_preferences: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/graphics/
    
    - assets/svg/onboard/
    - assets/svg/icons/
    - assets/svg/graphics/

    - assets/languages/
    - 
```
