### ISSUE TITLE
[Android]: App gets stuck upon performing hot reload

### ISSUE THREAD

**Issue by itssidhere** [flutter/flutter#80704]
## Logs

<details>
<summary>Logs</summary>

```
[√] Flutter (Channel master, 2.2.0-11.0.pre.161, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.2.0-11.0.pre.161 at D:\Program Files\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ce18d702e9 (3 hours ago), 2021-04-19 01:44:02 -0400
    • Engine revision 60f12daf85
    • Dart version 2.14.0 (build 2.14.0-8.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\sidjh\AppData\AndroidSDK
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = D:\sidjh\AppData\AndroidSDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at D:\Program Files\IntelliJ IDEA Community Edition 2019.2.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 192.8052

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.72
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!
```

**Dart: Capture Logs**
```
[2:28:35 PM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.ImageSizesForFrame","isolate":{"type":"@Isolate","id":"isolates/1935007456741807","name":"main","number":"1935007456741807","isSystemIsolate":false},"timestamp":1618822715037,"extensionData":{"<Unknown Image(200×200)>":{"source":"<Unknown Image(200×200)>","displaySize":{"width":114.2857142857143,"height":114.28571428571428},"imageSize":{"width":200.0,"height":200.0},"displaySizeInBytes":69659,"decodedSizeInBytes":213333}}}}}
[2:28:35 PM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.ImageSizesForFrame","isolate":{"type":"@Isolate","id":"isolates/1935007456741807","name":"main","number":"1935007456741807","isSystemIsolate":false},"timestamp":1618822715149,"extensionData":{"<Unknown Image(480×480)>":{"source":"<Unknown Image(480×480)>","displaySize":{"width":40.00000000000003,"height":40.0},"imageSize":{"width":480.0,"height":480.0},"displaySizeInBytes":8533,"decodedSizeInBytes":1228800}}}}}
[2:28:35 PM] [FlutterRun] [Info] [Flutter] <== [+1288 ms] This is taking a long time; will now check for paused isolates.
[2:28:35 PM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.ImageSizesForFrame","isolate":{"type":"@Isolate","id":"isolates/1935007456741807","name":"main","number":"1935007456741807","isSystemIsolate":false},"timestamp":1618822715189,"extensionData":{"<Unknown Image(200×200)>":{"source":"<Unknown Image(200×200)>","displaySize":{"width":114.2857142857143,"height":114.28571428571428},"imageSize":{"width":200.0,"height":200.0},"displaySizeInBytes":69659,"decodedSizeInBytes":213333}}}}}
[2:28:35 PM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates/1935007456741807","name":"main","number":"1935007456741807","isSystemIsolate":false},"timestamp":1618822715225,"extensionData":{"number":848,"startTime":224952923,"elapsed":179053,"build":69929,"raster":74141,"vsyncOverhead":33671}}}}
[2:28:35 PM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates/1935007456741807","name":"main","number":"1935007456741807","isSystemIsolate":false},"timestamp":1618822715225,"extensionData":{"number":849,"startTime":225116156,"elapsed":27018,"build":6838,"raster":10216,"vsyncOverhead":9425}}}}
[2:28:35 PM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates/1935007456741807","name":"main","number":"1935007456741807","isSystemIsolate":false},"timestamp":1618822715225,"extensionData":{"number":850,"startTime":225165004,"elapsed":30373,"build":7891,"raster":18654,"vsyncOverhead":2979}}}}
[2:28:35 PM] [FlutterRun] [Info] [Flutter] <== [  +84 ms] Found 0 newly paused isolate(s).
[2:28:35 PM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.ImageSizesForFrame","isolate":{"type":"@Isolate","id":"isolates/1935007456741807","name":"main","number":"1935007456741807","isSystemIsolate":false},"timestamp":1618822715264,"extensionData":{"<Unknown Image(480×480)>":{"source":"<Unknown Image(480×480)>","displaySize":{"width":40.00000000000003,"height":40.0},"imageSize":{"width":480.0,"height":480.0},"displaySizeInBytes":8533,"decodedSizeInBytes":1228800}}}}}
```

</details>

**Comment by darshankawar** [comment]
@itssidhere 
Is this for web or mobile ?
Can you provide `pubspec.yaml` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue you are facing ?
Thanks.

**Comment by itssidhere** [comment]
@darshankawar This is for mobile.

I cannot share a minimum reproducible code as the project is private. However I can share the Dart: Capture logs. Would that work?

**Comment by itssidhere** [comment]
**Pubspec.yaml**

```
version: 0.0.94378+466
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_database: ^6.1.1
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^1.0.1
  firebase_messaging: ^9.1.0
  firebase_dynamic_links: ^0.8.0
  firebase_analytics: ^7.1.1
  image_picker: ^0.7.3
  firebase_storage: ^8.0.1
  firebase_remote_config: ^0.9.0-dev.1
  google_sign_in: ^5.0.1
  audioplayers: ^0.18.1
  in_app_purchase: ^0.5.1+1
  url_launcher: ^6.0.3
  fluttertoast: 7.1.6
  flutter_colorpicker: ^0.4.0
  image_cropper: ^1.3.1
  photo_view: ^0.11.1
  share: ^2.0.1
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  random_color: ^1.0.5
  extended_image: ^4.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  package_info: ^2.0.0
  flutter_slidable: ^0.5.7
  font_awesome_flutter: ^9.0.0
  shimmer: ^1.1.2
  json_annotation: ^4.0.1
  uuid: ^3.0.2
  auto_size_text: ^2.1.0
  animated_text_kit: ^4.1.1
  intl: ^0.17.0
  vibration: ^1.7.3
  flutter_local_notifications: ^5.0.0
  bubble: ^1.2.1
  flutter_linkify: ^5.0.0
  connectivity: ^3.0.3
  slider_button: ^0.6.0
  awesome_dialog: ^1.3.2
  device_info: ^2.0.0
  page_transition: ^1.1.7+6
  flutter_screenutil: ^4.0.2+5
  flutter_spinkit: ^5.0.0
  
  timeago: ^3.0.2
  local_auth: ^1.1.0
  rate_my_app: ^1.1.0+1
  get_it: ^6.0.0
  like_button: ^2.0.2
  provider: ^5.0.0
  get: ^4.1.4

  palette_generator: ^0.3.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_native_timezone: ^1.0.4
  smooth_page_indicator: ^0.2.0
  badges: ^1.1.6
  transparent_image: ^2.0.0

  giphy_get: ^2.0.0-nullsafety.2

  youtube_player_iframe: 
    git: 
      url: "https://github.com/itssidhere/youtube_player_flutter.git"
      path: packages/youtube_player_iframe


  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.0

publish_to: none

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  build_runner:
  json_serializable:
  hive_generator: ^1.0.0
  pedantic: ^1.9.2

# For information on the1 generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - logo/fb-logo.png
    - logo/glogo.png
    - assets/dp/
    - assets/icons/
```
