### ISSUE TITLE
Flutter Web Release render issues

### ISSUE THREAD

**Issue by delizondo** [flutter/flutter#80821]
Hi

I have the following problem, my project has been developed using Flutter Web (not interested in mobile support), while in development everything works/renders perfectly, however, when I build the project for release is not being rendered correctly (just a gray square is displayed)

pubspec.yaml

```
environment:
  sdk: '>=2.10.0 <3.0.0'  

dependencies:
  flutter:
    sdk: flutter
  #flutter_localizations:
  #  sdk: flutter
  
  firebase: ^9.0.1
  firebase_auth: ^1.0.3
  intl: ^0.17.0
  google_maps: ^5.1.0
  country_code_picker: ^2.0.1
  url_launcher: ^6.0.3
  url_launcher_web: ^2.0.0
  flutter_typeahead: ^3.1.0
  flutter_bloc: ^7.0.0
  #corsac_jwt: ^0.4.0
  image_picker_web: ^2.0.1
  table_calendar: ^3.0.0  
  html_editor_enhanced: ^1.8.0
  shared_preferences: ^2.0.5
  json_annotation: ^3.1.1
  #intl_utils: ^2.1.0
  mime_type: ^1.0.0  
  http: ^0.13.1
  fixar_core:
    path: ../fixar_core



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.5.1

```

Flutter Doctor: 
```
delizondo@MacBook-Pro % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (1 available)

• No issues found!
```

Dart version:
```
delizondo@MacBook-Pro  % dart --version
Dart SDK version: 2.12.4 (stable) (Thu Apr 15 12:26:53 2021 +0200) on "macos_x64"
```

I'm using VS Code as my main IDE for development, and is hosted in Firebase Hosting

While developing the app, this is how the login screen renders

<img width="1052" alt="Screen Shot 2021-04-20 at 15 39 17" src="https://user-images.githubusercontent.com/1301103/115467346-9b04bf00-a1ee-11eb-963c-2d522d0c7e17.png">

However after I create the release build and push it to the hosting server, this is how it renders

<img width="1116" alt="Screen Shot 2021-04-20 at 15 39 26" src="https://user-images.githubusercontent.com/1301103/115467432-be2f6e80-a1ee-11eb-818e-9616c443f17a.png">

I've tried multiple variations of the build command to generate the release build, but all with the same result

* flutter build web --target=lib/main_dev.dart
* flutter build web --web-renderer html --target=lib/main_dev.dart
* flutter build web --web-renderer canvaskit --target=lib/main_dev.dart

At this point I have no idea how to proceed, suggestions?
