### ISSUE TITLE
The new format reminder of pubspec.yaml is missing in <Upgrading pre 1.12 Android projects>

### ISSUE THREAD

**Issue by franticn** [flutter/flutter#80844]
We migrated our plugin by follow this documentation [Upgrading pre 1.12 Android projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#Full-Flutter%20app%20migration),but we found that if you dont migrating an existing plugin to use the new shcema, you always uses the old Android embedding(which registers the plugins by static method `registerWith`).

When we modify the `pubspec.yaml` like these, the new Android embedding will be work
Previous plugin's `pubspec.yaml`:

```yaml
name: sample
version: 0.0.1

flutter:
    plugin:
        androidPackage: io.flutter.plugins.sample
        pluginClass: SamplePlugin
```

New plugin's `pubspec.yaml`:

```yaml
name: sample
version: 0.0.1

flutter:
    plugin:
        platforms:
            android:
                package: io.flutter.plugins.sample
                pluginClass: SamplePlugin
            ios:
                pluginClass: SamplePlugin
```

So do we need to improve this documentation and inform developers that the format of the yaml file will also affect the registration method.
