### ISSUE TITLE
White screen on iOS version of mobile web application

### ISSUE THREAD

**Issue by deappspecialist** [flutter/flutter#81167]
Currently developing a web app with Flutter web. Building, running and accessing the Firebase hosted application works fine when I'm on my laptop or Android device, however when I try to visit the application on a mobile iOS device I get a blank screen. I have tested this with several devices and they all show the same blank page. In order to find the culprit I have tried the following:

- Building and deploying with channels master / dev / beta
- Adding and omitting canvas and/or --release to the build using `flutter build web --web-renderer canvaskit --release`
- Cleaning my project along with deleting all generated code using `flutter clean && find lib -maxdepth 20 -type f \\( -name \\"*.freezed.dart\\" -o -name \\"*.g.dart\\" -o -name \\"*.chopper.dart\\" \\) -delete`
- Changing `<base href="/">` to `<base href="./">` in my index.html
- Updating the first iOS meta tag to `<meta name="mobile-web-app-capable" content="yes">` in my index.html
- Searching StackOverflow and Flutter issues for similar issues with no result
- Cleaning my cache and trying different phones

Edit: Safari on desktop also seems to cause a white screen (!)

My `pubspec.yaml`:

```
name: X
description: X

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at <https://developer.android.com/studio/publish/versioning>
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# <https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html>
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1

  # Stacked
  stacked: ^2.0.2

  # Data
  freezed: ^0.14.1+2
  freezed_annotation: ^0.14.1
  json_serializable: ^4.1.0

  # Util
  get: 4.1.1
  intl: ^0.17.0
  get_it: ^6.0.0
  url_strategy: ^0.2.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  logger: ^1.0.0
  flutter_screenutil: ^5.0.0
  flutter_form_builder: ^6.0.0-nullsafety.1

  # Https
  chopper: 4.0.0-nullsafety.0

  # UI
  progress_indicators: ^1.0.0
  cupertino_icons: ^1.0.2
  overlay_support: ^1.2.1
  flutter_svg: ^0.21.0+1
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  stacked_generator: ^0.3.3
  chopper_generator: 4.0.0-nullsafety.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - icon/
    - svg/
    - font/

  # An image asset can refer to one or more resolution-specific "variants", see
  # <https://flutter.dev/assets-and-images/#resolution-aware>.

  # For details regarding adding assets from package dependencies, see
  # <https://flutter.dev/assets-and-images/#from-packages>

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see <https://flutter.dev/custom-fonts/#from-packages>
flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: LocalizedStrings # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
#  localizely: # Optional settings if you use Localizely platform. Read more: <https://localizely.com/flutter-localization-workflow>
#    project_id: # Get it from the <https://app.localizely.com/projects> page.
#    branch: # Get it from the “Branches” page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
#    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
#    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
#    download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
#    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false

```

My `index.html`:

```
<!DOCTYPE html>
<html>
<head>
    <base href="./">

    <meta charset="UTF-8">
    <meta content="IE=Edge" http-equiv="X-UA-Compatible">
    <meta name="description" content="X">

    <!-- iOS meta tags & icons -->
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="dashboard">
    <link rel="apple-touch-icon" href="icons/Icon-192.png">

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="favicon.png"/>

    <title>X</title>
    <link rel="manifest" href="manifest.json">
</head>
<body>
<!-- This script installs service_worker.js to provide PWA functionality to
     application. For more information, see:
     <https://developers.google.com/web/fundamentals/primers/service-workers> -->
<script>
    if ('serviceWorker' in navigator) {
        window.addEventListener('flutter-first-frame', function () {
            navigator.serviceWorker.register('flutter_service_worker.js?v=107771284');
        });
    }
</script>
<!--Firebase-->
<script src="<https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js>"></script>
<script src="<https://www.gstatic.com/firebasejs/7.20.0/firebase-analytics.js>"></script>
<script src="<https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js>"></script>
<script src="<https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js>"></script>
<script>
    var firebaseConfig = {
//
    };
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
</script>
<script src="main.dart.js" type="application/javascript"></script>
</body>
</html>

```
My `main.dart`:

```
import 'package:dashboard/app/theme.dart';
import 'package:dashboard/generated/l10n.dart';
import 'package:dashboard/service/string/string_service.dart';
import 'package:dashboard/ui/view/login/login_view.dart';
import 'package:dashboard/ui/view/startup/startup_view.dart';
import 'package:dashboard/util/constants/ui_constants.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/localization/form_builder_localizations.dart';
import 'package:get/get.dart';
import 'package:overlay_support/overlay_support.dart';

import 'app/app.dart';

Future<void> main() async {
  await AppSetup.initialise();
  runApp(
    const MyApp(),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  String _onGenerateTitle(BuildContext context) {
    StringService.locate.initialise(context);
    return StringService.locate.core.title;
  }

  @override
  Widget build(BuildContext context) {
    return OverlaySupport.global(
      child: GetMaterialApp(
        defaultTransition: Transition.fadeIn,
        transitionDuration: AbsDurations.defaultAnimation,
        unknownRoute: GetPage<void>(
          name: '/notfound',
          page: () => const StartupView(),
        ),
        initialRoute: StartupView.route,
        getPages: [
          GetPage<void>(
            name: StartupView.route,
            page: () => const StartupView(),
          ),
          GetPage<void>(
            name: LoginView.route,
            page: () => const LoginView(),
          ),
          // GetPage(
          //   name: '/user/:id',
          //   page: () => UserProfile(),
          // ),
        ],
        onGenerateTitle: _onGenerateTitle,
        theme: AppConfig.theme,
        navigatorKey: Get.key,
        enableLog: false,
        localizationsDelegates: const [
          LocalizedStrings.delegate,
          DefaultMaterialLocalizations.delegate,
          DefaultWidgetsLocalizations.delegate,
          DefaultCupertinoLocalizations.delegate,
          FormBuilderLocalizations.delegate,
        ],
        supportedLocales: LocalizedStrings.delegate.supportedLocales,
      ),
    );
  }
}
```

What's causing this problem and how do I fix it?

App address: https://winkle-dev.web.app/

## Steps to Reproduce

It's a bit hard to provide reproducing steps as I'm not sure where the problem is coming from. Deploying older version of the application provide the same result. Normal version on Android and desktop, white on iOS.

1. Create flutter app
2. Add firebase hosting
3. Add pubspec.yaml and pub get
4. Add main.dart
5. Replace routes with simple widget
6. Deploy to firebase hosting

**Expected results:** 

Same version on iOS mobile web as on Android and Desktop.

**Actual results:** 

White screen without error messages.

<details>
  <summary>Logs</summary>

```
[  +54 ms] Error: iPhone is not connected. Xcode will continue when iPhone is connected.
(code -13)
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[ +111 ms] Skipping pub get: version match.
[  +44 ms] Found plugin cloud_firestore at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-1.0.3/
[   +8 ms] Found plugin cloud_firestore_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.3/
[   +9 ms] Found plugin firebase_auth at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
[   +8 ms] Found plugin firebase_auth_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.3/
[   +1 ms] Found plugin firebase_core at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.2/
[   +2 ms] Found plugin firebase_core_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.2/
[  +31 ms] Found plugin path_provider at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +2 ms] Found plugin path_provider_linux at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +4 ms] Found plugin path_provider_macos at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +2 ms] Found plugin path_provider_windows at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[ +110 ms] Found plugin cloud_firestore at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-1.0.3/
[   +1 ms] Found plugin cloud_firestore_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.3/
[   +4 ms] Found plugin firebase_auth at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
[   +1 ms] Found plugin firebase_auth_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.3/
[        ] Found plugin firebase_core at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.2/
[   +1 ms] Found plugin firebase_core_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.2/
[  +19 ms] Found plugin path_provider at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[        ] Found plugin path_provider_linux at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[        ] Found plugin path_provider_macos at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +1 ms] Found plugin path_provider_windows at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[  +33 ms] Generating
/Users/bbmanuputty/Documents/Projects/Flutter/dashboard/android/app/src/main/java/io/flu
tter/plugins/GeneratedPluginRegistrant.java
[ +205 ms] Launching lib/main.dart on Chrome in debug mode...
[  +96 ms] Updating assets
[ +360 ms] Manifest contained wildcard assets. Inserting missing file into build graph
to force rerun. for more information see #56466.
[   +3 ms] Waiting for connection from debug service on Chrome...
[  +12 ms] Found plugin cloud_firestore at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-1.0.3/
[   +1 ms] Found plugin cloud_firestore_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.3/
[   +3 ms] Found plugin firebase_auth at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
[        ] Found plugin firebase_auth_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.3/
[        ] Found plugin firebase_core at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.2/
[        ] Found plugin firebase_core_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.2/
[   +9 ms] Found plugin path_provider at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[        ] Found plugin path_provider_linux at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[        ] Found plugin path_provider_macos at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[        ] Found plugin path_provider_windows at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[  +30 ms] Found plugin cloud_firestore at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-1.0.3/
[   +1 ms] Found plugin cloud_firestore_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-1.0.3/
[   +3 ms] Found plugin firebase_auth at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
[        ] Found plugin firebase_auth_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.3/
[        ] Found plugin firebase_core at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.2/
[        ] Found plugin firebase_core_web at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.2/
[  +10 ms] Found plugin path_provider at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[        ] Found plugin path_provider_linux at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[        ] Found plugin path_provider_macos at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +1 ms] Found plugin path_provider_windows at
/Users/bbmanuputty/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[  +85 ms] <- reset
[   +5 ms] /Users/bbmanuputty/Flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/bbmanuputty/Flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.sn
apshot --sdk-root /Users/bbmanuputty/Flutter/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/0v/sk7gxssn5yg9j1_9p4bv_3fm0000gn/T/flutter_tools.sRIH0q/flutter_tool.FuTZG
f/app.dill --libraries-spec
file:///Users/bbmanuputty/Flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/Users/bbmanuputty/Documents/Projects/Flutter/dashboard/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root
/var/folders/0v/sk7gxssn5yg9j1_9p4bv_3fm0000gn/T/flutter_tools.sRIH0q/flutter_tools.2YNI
LZ --filesystem-scheme org-dartlang-app --initialize-from-dill
build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///Users/bbmanuputty/Flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--no-sound-null-safety
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+21988 ms] Waiting for connection from debug service on Chrome... (completed in 22.2s)
[        ] Synced 42.6MB.
[        ] <- accept
[        ] Caching compiled dill
[ +141 ms] Using Google Chrome 89.0.4389.90 

[+2062 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:55550/devtools/browser/498102eb-8538-44f1-a100-47ef2b1e82b6
[ +887 ms] DwdsInjector: Received request for entrypoint at
http://localhost:55532/main_module.bootstrap.js
[   +7 ms] MetadataProvider: Loading debug metadata...
[  +19 ms] MetadataProvider: Loaded debug metadata
[  +17 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:55532/main_module.bootstrap.js
[+3885 ms] DevHandler: Debug service listening on ws://127.0.0.1:55574/SEZgBSFs1bY=/ws

[   +8 ms] Debug service listening on ws://127.0.0.1:55574/SEZgBSFs1bY=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +1 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".

```

```
bbmanuputty@Brians-MacBook-Pro-2 dashboard % flutter analyze
Analyzing dashboard...                                                  

warning • Prefer const with constant constructors • test/widget_test.dart:15:29 •
       prefer_const_constructors

1 issue found. (ran in 4.2s)
bbmanuputty@Brians-MacBook-Pro-2 dashboard % 

```

```
```
[✓] Flutter (Channel dev, 2.2.0-10.1.pre, on Mac OS X 10.15.7 19H524 darwin-x64, locale
    en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (1 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected.
      (code -13)

• No issues found!

```
```

</details>
