### ISSUE TITLE
WorkManager is not initialized properly

### ISSUE THREAD

**Issue by atleugim** [flutter/flutter#81442]
When i run my app the debugger console throws an exception related with workmanager, like this.

**FATAL EXCEPTION: main**
```
E/AndroidRuntime(18384): Process: com.google.android.apps.walletnfcrel, PID: 18384
E/AndroidRuntime(18384): java.lang.RuntimeException: Unable to create application com.google.commerce.tapandpay.android.application.TapAndPayApplication: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.

I'm working on the latest stable version (2.0.5) with sound null-safety
**_Here is my flutter doctor -v_**

$ flutter doctor -v
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [VersiÃ³n 10.0.19042.631], locale es-CO)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\MyUser\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Redmi Note 9 Pro (mobile) • d0a82e4e • android-arm64  • Android 10 (API 29)
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 90.0.4430.93

• No issues found!


**_And the packages i use_**
http: ^0.13.1
share: ^2.0.1
cached_network_image: ^3.0.0
google_fonts: ^2.0.0
url_launcher: ^6.0.3

```

**Comment by darshankawar** [comment]
@atleugim 
Can you try `flutter clean` and then `flutter run` to see if it resolves your issue ?
Thanks.

**Comment by atleugim** [comment]
@darshankawar 
I do that everytime i run project, the issue is still there.

**Comment by darshankawar** [comment]
@atleugim 
Can you also try `flutter pub cache repair' ?
If issue still persists, can you provide complete `pubspec.yaml` ?

**Comment by atleugim** [comment]
@darshankawar 

I've made the `flutter pub cache repair` but te issue is still there

This is my  **pubspec.yaml**

```
name: myproject
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.13.1
  share: ^2.0.1
  cached_network_image: ^3.0.0
  google_fonts: ^2.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrounds/
```
