### ISSUE TITLE
iOS App runs in debug and release mode locally but crashes on startup when loaded from TestFlight

### ISSUE THREAD

**Issue by Jshewmaker** [flutter/flutter#81498]
## Steps to Reproduce

1. `flutter run --release -t lib/main_prod.dart --flavor prod` will load the app locally and app runs fine
2. `flutter build ipa -t lib/main_prod.dart --flavor prod`  and pushed to the App Store crashes on start up

The app was working fine for the last 4 months. Now it crashes on startup when downloaded from test flight. I am unsure how to see the logs of what is going wrong since it runs fine locally. I have tried re-adding the GoogleService-info.plist a few times and deleted the project from my Mac and reloaded from GitHub. Nothing seems to work

Tested on beta and stable branches

<details> 
<summary>pubspec.yaml</summary> 
	
```yaml
name: divvy
description: A new Flutter project.
publish_to: none

version: 2.2.0+0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  intl: ^0.16.1
  font_awesome_flutter: ^8.4.0
  flutter_bloc: ^6.1.0
  bloc: ^6.1.0
  provider: ^4.3.2+2
  formz: ^0.2.0
  meta: ^1.1.8
  pedantic: ^1.9.0
  cloud_firestore: ^0.12.10+2
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.5
  webview_flutter: ^1.0.3
  url_launcher: ^5.7.5
  flutter_masked_text: ^0.8.0
  jiffy: ^3.0.1
  toast: ^0.1.5
  #SHA-3 Hashing library
  web3dart: ^1.2.3
  bip39: ^1.0.3
  bip32: ^1.0.5
  cryptography: ^1.4.1
  google_fonts: ^1.1.1
  camera: ^0.5.8+17
  video_player: ^1.0.1
  path_provider: ^1.6.24
  path: ^1.7.0
  image_picker: ^0.6.7+15
  dropdown_date_picker: ^0.1.1+2
  marquee: ^1.6.1
  authentication_repository:
    path: packages/authentication_repository

flutter_icons:
  image_path: "assets/divvy_icon.png"
  image_path_android: "assets/divvy_icon.png"
  android: true
  ios: true

dev_dependencies:
 flutter_launcher_icons: "^0.8.0"

flutter_test:
  sdk: flutter
  bloc_test: ^7.0.0
  mockito: ^4.0.0


  
flutter:
  uses-material-design: true
  assets:
    - assets/
```

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
`[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.0.5 at /Users/joshuashewmaker/Development/flutter
    • Framework revision adc687823a (13 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/joshuashewmaker/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!`
```
		
</details>
