### ISSUE TITLE
fatal error: 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by jeffmayn** [flutter/flutter#81651]
## Steps to Reproduce

Untill yesterday my app was compiling fine to both android and iOS, now suddenly I get this fatal error when i run ``` flutter build ios```

Ive tried
- ``` flutter clean ```
- delete derived data
- deleting the ios-folder completely
- ``` flutter create . ```
- updating the podfile to have ios 10 as platform
-  ``` flutter build ios ``` again

## Logs

<details>
<summary>Logs</summary>

```
flutter build ios                            
Running "flutter pub get" in myApp...                      999ms
Building <removed for public view> for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: <removed for public view>
Running pod install...                                            254,3s
Running Xcode build...                                                  
Xcode build done.                                           325,8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    In file included from /Users/jeffmayn/.pub-cache/hosted/pub.dartlang.org/streams_channel-0.3.0/ios/Classes/FlutterStreamsChannel.m:4:
    /Users/jeffmayn/.pub-cache/hosted/pub.dartlang.org/streams_channel-0.3.0/ios/Classes/FlutterStreamsChannel.h:4:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Encountered error while building for device.
```

```
```

</details>

<details>
<summary>Flutter doctor -v output</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale da-DK)
    • Flutter version 2.0.6 at /Users/jeffmayn/Desktop/Development/flutter
    • Framework revision 1d9032c7e1 (3 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jeffmayn/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

</details>

<details>
<summary>pubspec.yaml</summary>

```
name: myApp
description: A new Flutter application.

version: 1.0.2+36

environment:
  #sdk: ">=2.2.2 <3.0.0"
  sdk: ">=2.2.2 <3.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_core_platform_interface: 4.0.0
  firebase_storage_web: 1.0.0
  firebase_auth_web: 1.0.3
  firebase_core: ^1.1.0
  firebase_core_web: 1.0.2
  firebase_storage: 8.0.0
  firebase_messaging: 9.0.0
  firebase_dynamic_links: ^0.5.0+11
  firebase_auth: 1.0.0
  cloud_firestore: 1.0.0
  cloud_firestore_web: 1.0.3
  modal_progress_hud: ^0.1.3
  table_calendar: ^2.2.3
  provider: 5.0.0
  path_provider: 2.0.1
  path_provider_platform_interface: 2.0.0
  path: ^1.6.4
  flutter_slidable: ^0.5.4
  sliding_up_panel: ^1.0.0
  image_picker: 0.7.4
  geolocation: ^1.1.2
  geolocator: ^5.1.5
  google_maps_flutter: 2.0.1
  permission_handler: 6.0.1
  fluttertoast: ^7.1.8
  camera: 0.8.0
  font_awesome_flutter: ^8.8.1
  intl: 0.17.0
  file_picker: 3.0.0
  uuid: 3.0.1
  crypto: 3.0.0
  share: ^0.6.4
  shared_preferences: 2.0.3
  matrix4_transform: ^1.1.3
  clipboard_manager: ^0.0.4
  image_cropper: ^1.2.2
  date_time_picker: 2.0.0
  native_pdf_view: ^4.0.1
  pdf: 3.0.1
  flutter_html: ^0.11.1
  http_parser: 4.0.0
  plugin_platform_interface: 2.0.0
  workmanager: ^0.2.3
  http: 0.13.0
  image_gallery_saver: ^1.6.7
  animated_floatactionbuttons: ^0.1.0
  #image_editor_pro: ^1.0.9
  cupertino_icons: ^1.0.2
  vertical_card_pager: ^1.4.0
  url_launcher: 6.0.3
  expansion_tile_card: 2.0.0
  stripe_payment: 1.0.11
  js: ^0.6.3
  flip_card: 0.5.0
  flutter_contacts: 0.3.3+1
  maps_launcher: 2.0.0
  awesome_dialog: 1.3.2
  upgrader: 3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

```

</details>

<details>
<summary>Podfile</summary>

```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
  end
 end
end

```

</details>
