### ISSUE TITLE
Show flag values for `flutter config`

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#81665]
## Use case

Currently, running `flutter config` lists all available flags, but not its value or default value. For example:

```
--[no-]enable-web                            Enable or disable Flutter for web. This setting will take effect on the
                                                 master, dev, beta, and stable channels.
                                                 setting will take effect on the master, dev, beta, and stable channels.
                                                 Newer beta versions are available on the beta channel.
```

## Proposal

Add some text to show the default and/or current value of the flag, for example:

```
--[no-]enable-web                            Enable or disable Flutter for web. This setting will take effect on the
                                                 master, dev, beta, and stable channels.
                                                 setting will take effect on the master, dev, beta, and stable channels.
                                                 Newer beta versions are available on the beta channel.
                                                 Defaults to `false`. Current value is `true`.
```

**Comment by jmagman** [comment]
@Zazo032 If you look at the bottom of the `flutter config` output you should see the current values of the configs that are set, so you don't need the `Current value is "true".` part (and we wouldn't include that dynamic lookup in help output, which is what the top part is). 
```
Settings:
  ios-signing-cert: Apple Development (123456)
  enable-web: true
  enable-linux-desktop: true
  enable-macos-desktop: true
  enable-windows-desktop: true
  enable-android: true
```
But fair point about not knowing what the default values are.
