### ISSUE TITLE
Lost connection to device when performing hot restart in iOS

### ISSUE THREAD

**Issue by kosaku47** [flutter/flutter#81977]
When I hot restart my project, it lost connection to device.

**Log when debug to iOS simulator**
```
Performing hot restart...
[  +17 ms] Scanned through 735 files in 13ms
Syncing files to device iPhone 12 Pro Max...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:news_share_app/main.dart 7955af13-ecd5-4b83-9271-37bf20d961f5
[        ] <- 7955af13-ecd5-4b83-9271-37bf20d961f5
[ +176 ms] Updating files.
[  +43 ms] DevFS: Sync finished
[        ] Synced 44.0MB.
[        ] <- accept
[ +522 ms] Hot restart performed in 757ms.
[   +5 ms] Restarted application in 770ms.
[+1083 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +5 ms] DevFS: Deleting filesystem on the device (file:///Users/nakanokousaku/Library/Developer/CoreSimulator/Devices/D0BC281A-5EC4-4030-B497-1E25E5251FC0/data/Containers/Data/Application/7E518A9F-C659-43F0-9538-4EDB91FB1C59/tmp/news_share_appxXwhDI/news_share_app/)
```

**Log when debug to iPhone**
```
Performing hot restart...
[ +20 ms] Scanned through 735 files in 13ms
Syncing files to device Kosakuのiphone...
[ ] <- reset
[ ] Compiling dart to kernel with 0 updated files
[ ] <- recompile package:news_share_app/main.dart 7c5ad187-bdd4-4449-8082-9a6ead2d87e9
[ ] <- 7c5ad187-bdd4-4449-8082-9a6ead2d87e9
[ +147 ms] Updating files.
[ +919 ms] DevFS: Sync finished
[ ] Synced 44.0MB.
[ ] <- accept
[ +210 ms] Hot restart performed in 1,292ms.
[ +2 ms] Restarted application in 1,305ms.
[ +391 ms] -[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x2835c7430
[ ] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x2835c7430'
[ ] *** First throw call stack:
[ ] (0x1a47ed86c 0x1b9809c50 0x1a46f495c 0x1a47f0438 0x1a47f2740 0x102c7f068 0x102c81148 0x102c8f200 0x102c8d16c 0x102c8c1c0 0x107db8694 0x107558038 0x10785741c 0x1077f681c 0x1077f8ed4 0x1a4769fa0 0x1a4769ba0 0x1a4768ffc 0x1a4762ee4 0x1a476221c 0x1bc32f784 0x1a71a2ee8 0x1a71a875c 0x102bd2ac0 0x1a44226b0)
[ ] libc++abi.dylib: terminating with uncaught exception of type NSException
[ +675 ms] Process 8597 stopped
[ ] * thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
[ ] frame #0: 0x00000001d2740414 libsystem_kernel.dylib__pthread_kill + 8 [ ] libsystem_kernel.dylib__pthread_kill:
[ ] -> 0x1d2740414 <+8>: b.lo 0x1d2740434 ; <+40>
[ ] 0x1d2740418 <+12>: pacibsp
[ ] 0x1d274041c <+16>: stp x29, x30, [sp, #-0x10]!
[ ] 0x1d2740420 <+20>: mov x29, sp
[ ] Target 0: (Runner) stopped.
[ ] ios-deploy exited with code 0
[ +154 ms] Service protocol connection closed.
[ ] Lost connection to device.
[ +2 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/673377E4-BD5E-4269-B698-F69A98C88B96/tmp/news_share_appI00rdb/news_share_app/)
```

<details>
<summary>flutter doctor</summary>
<pre>
<code>
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale ja-JP)
    • Flutter version 2.0.5 at /Users/nakanokousaku/development/flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/nakanokousaku/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • D0BC281A-5EC4-4030-B497-1E25E5251FC0 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.27 beta

• No issues found!

</code>
</pre>
</details>

**Comment by darshankawar** [comment]
@kosaku47 
Can you provide `pubspec.yaml`, `info.plist` ?

Does it only occur when you hot restart ? or while `flutter run` or hot reload too ?  Can you provide the steps you took which leads to this error ?

Thanks.

**Comment by kosaku47** [comment]
@darshankawar 
It only occurs when I hot restart. Hot reload and flutter run work.

**pubspec.yaml**
```
name: news_share_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^2.0.1

  cupertino_icons: ^1.0.3
  #firebase
  cloud_firestore: ^1.0.4
  firebase_auth: ^1.1.3
  firebase_core: ^1.1.0
  firebase_crashlytics: ^2.0.2
  #firebase_performance: ^0.6.0
  firebase_analytics: ^8.0.3

  firebase_messaging: ^9.1.3
  firebase_remote_config: ^0.10.0-dev.0
  firebase_storage: ^8.0.5


  # logic package
  hooks_riverpod: ^0.14.0+3

  # web api
  html: ^0.15.0
  http: ^0.13.3


  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.1
  uuid: ^3.0.4
  url_launcher: ^6.0.3
  package_info: ^2.0.0
  animate_do: ^2.0.0

  adaptive_dialog: ^0.10.0+5

  cached_network_image: ^3.0.0
  image_picker: ^0.7.4
  #path: ^1.8.0
  flutter_image_compress: ^1.0.0
  flutter_colorpicker: ^0.4.0
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.2
  sign_in_with_apple: ^3.0.0
  crypt: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: ^0.8.1
  build_runner: ^2.0.2
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
  pedantic_mono: ^1.11.0+2
  test: ^1.16.5
  mockito: ^5.0.3
  simple_logger: ^1.8.0+1
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  ios: true
  image_path: "assets/images/app_icon/pachira_icon.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/Black Logo Square@1x.png
 ```

**info.plist**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>$(DEFINE_APP_NAME)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(APP_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.975154777661-cnpmhe6o7r5mkd1ft7o218elcq7qqs3c</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app requires to access your photo library</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

```
