### ISSUE TITLE
Please update the dependencies of the flutter packages!

### ISSUE THREAD

**Issue by LostInDarkMath** [flutter/flutter#82537]
Hi there, 
I cannot use your test_packages since they require old depencies which my flutter app does not support.

## flutter_driver:
```
Because every version of flutter_driver from sdk depends on test_api 0.2.19 and test 1.17.4 depends on test_api 0.4.0, flutter_driver from sdk is incompatible with test 1.17.4.
And because no versions of test match >1.17.4 <2.0.0, flutter_driver from sdk is incompatible with test ^1.17.4.
So, because foo depends on both test ^1.17.4 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because foo depends on both test ^1.17.4 and flutter_driver any from sdk, version solving failed.)
```

```
Because every version of flutter_driver from sdk depends on args 1.6.0 and flutter_launcher_icons 0.9.0 depends on args 2.0.0, flutter_driver from sdk is incompatible with flutter_launcher_icons 0.9.0.
And because no versions of flutter_launcher_icons match >0.9.0 <0.10.0, flutter_driver from sdk is incompatible with flutter_launcher_icons ^0.9.0.
So, because foo depends on both flutter_launcher_icons ^0.9.0 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because foo depends on both flutter_launcher_icons ^0.9.0 and flutter_driver any from sdk, version solving failed.)
```

## flutter_test
```
Because every version of flutter_test from sdk depends on test_api 0.2.19 and test 1.17.4 depends on test_api 0.4.0, flutter_test from sdk is incompatible with test 1.17.4.
And because no versions of test match >1.17.4 <2.0.0, flutter_test from sdk is incompatible with test ^1.17.4.
So, because foo depends on both test ^1.17.4 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because foo depends on both test ^1.17.4 and flutter_test any from sdk, version solving failed.)
```

## integration_test
```
Because every version of integration_test from sdk depends on args 1.6.0 and flutter_launcher_icons 0.9.0 depends on args 2.0.0, integration_test from sdk is incompatible with flutter_launcher_icons 0.9.0.
And because no versions of flutter_launcher_icons match >0.9.0 <0.10.0, integration_test from sdk is incompatible with flutter_launcher_icons ^0.9.0.
So, because foo depends on both flutter_launcher_icons ^0.9.0 and integration_test any from sdk, version solving failed.
pub get failed (1; So, because foo depends on both flutter_launcher_icons ^0.9.0 and integration_test any from sdk, version solving failed.)
```
## Steps to Reproduce

Use the following `pubspec.yaml` and run `flutter pub get`:
```yaml
name: foo
description: Foo
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  pedantic: ^1.11.0
  image_cropper: ^1.4.0 
  image_picker: ^0.7.5 
  intl: ^0.17.0 
  location: ^4.1.1 
  path_provider: ^2.0.1
  http: ^0.13.3 
  loading_overlay: ^0.3.0 
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^4.2.0  
  flutter_launcher_icons: ^0.9.0
  dash_chat: ^1.1.15-nullsafety 
  workmanager: ^0.4.0
  flutter_local_notifications: ^5.0.0+4
  is_lock_screen: ^2.0.0 
  flutter_ringtone_player: ^3.0.0
  flutter_dotenv: ^4.0.0-nullsafety.1
  logging: ^1.0.1  
  badges: ^2.0.0-nullsafety.1
  string_validator: ^0.3.0 
  url_launcher: ^6.0.3 
  pagination_view: ^2.0.0-nullsafety.0 

dev_dependencies:
  test: ^1.17.4
  flutter_driver:  # TODO currently incompatible
    sdk: flutter
  flutter_test:  # TODO currently incompatible
    sdk: flutter
  integration_test:  # TODO currently incompatible
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/logo.png"
```

## Flutter doctor -v output
```
C:\flutter>flutter doctor -v
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 6.1.7601], locale de-DE)
    • Flutter version 2.0.6 at C:\flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\WILLI\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\WILLI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

## A suggestion
Maybe you could implement an auto-roller for this as suggested here: https://github.com/flutter/flutter/issues/37985
