### ISSUE TITLE
Firebase authStateChanges() not working correctly on Flutter Web  but same code woking on android

### ISSUE THREAD

**Issue by SureshKumar311** [flutter/flutter#83038]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... i had trying to build flutter web app with firebase auth and i had used streamprovider for authchanges and an model class to store User data 
4. when i had run my flutter app and logined .. at the time authchanges  was updated to model class but after restart  the update of model class from authStateChanges() stream is not working
5. but same code is working correctly on android 
6. plz help guys tq

sample code :
main.dart code :
```
import 'package:flutter/material.dart';
import 'package:project_center/Screen/Homepage.dart';
import 'package:project_center/Screen/Navationbar/Navbar.dart';
import 'package:get/get.dart';
import 'package:project_center/Screen/login/wrapper.dart';
import 'package:project_center/services/authenation.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamProvider<CustomUser>.value(
      value: Authservice().user,
      initialData: null,
      child: GetMaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          fontFamily: "Montserrat",
          // textTheme: GoogleFonts.latoTextTheme(
          //   Theme.of(context).textTheme,
          // ),
        ),
        home: Wrappper(),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        height: MediaQuery.of(context).size.height,
        width: MediaQuery.of(context).size.width,
        decoration: BoxDecoration(
          gradient: LinearGradient(
              begin: Alignment.centerLeft,
              end: Alignment.centerRight,
              colors: [
                Color.fromRGBO(195, 20, 50, 1.0),
                Color.fromRGBO(36, 11, 54, 1.0)
              ]),
        ),
        child: SingleChildScrollView(
          child: Column(
            children: <Widget>[
              Navbar(),
              Padding(
                padding: const EdgeInsets.symmetric(
                    vertical: 20.0, horizontal: 40.0),
                child: LandingPage(),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```
authcode :
```
import 'dart:async';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'package:fluttertoast/fluttertoast.dart';

void showterror(total) {
  Fluttertoast.showToast(
    msg: "Error $total !!!",
    toastLength: Toast.LENGTH_SHORT,
    gravity: ToastGravity.CENTER,
    timeInSecForIosWeb: 1,
    backgroundColor: Colors.amberAccent[400],
    textColor: Colors.white,
    fontSize: 20.0,
  );
}

autherror(errorcode) {
  if (errorcode.code == 'user-not-found') {
    showterror("User not Found");
  } else if (errorcode.code == "wrong-password") {
    showterror("wrong password");
  } else if (errorcode.code == 'email-already-in-use') {
    showterror("Email is Already in Use");
  } else if (errorcode.code == 'errorCode') {
    showterror("User has Made an Error");
  }
}

class CustomUser with ChangeNotifier {
  final String uid;
  final String name;
  final String email;
  final String photourl;
  final bool emailVerified;
  CustomUser(
      {this.uid, this.name, this.email, this.photourl, this.emailVerified});
}

class Authservice {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  CustomUser _customUserModel(User user) {
    return user != null
        ? CustomUser(
            uid: user.uid,
            name: user.displayName,
            email: user.email,
            photourl: user.photoURL,
            emailVerified: user.emailVerified,
          )
        : null;
  }

//stream

  Stream<CustomUser> get user {
    return _auth.authStateChanges().map(_customUserModel);
  }

// sign in Anon
  Future signInAnon() async {
    try {
      UserCredential result = await _auth.signInAnonymously();

      User user = result.user;
      return _customUserModel(user);
    } catch (e) {
      print("the errorag in $e");
      return null;
    }
  }

  //sigup with email
  Future sigupwithemail({email, passwd}) async {
    try {
      UserCredential result = await _auth.createUserWithEmailAndPassword(
          email: email, password: passwd);
      User user = result.user;
      // creating new record for new user

      try {
        await user.sendEmailVerification();
        print("email is send ");

        return _customUserModel(user);
      } catch (e) {
        print("An error occured while trying to send email verification ");

        return null;
      }
    } catch (signUpError) {
      autherror(signUpError);
    }
  }

  Future resetpasswd(email) async {
    try {
      await _auth.sendPasswordResetEmail(email: email);
      print("reset email sended");
      Get.snackbar('Note', 'Reset Email has Been Sent',
          backgroundColor: Colors.white);
    } catch (e) {
      print("An error occured while trying to send reset email verification ");
    }
  }

  //signin with email
  Future signinwithemail({email, passwd}) async {
    try {
      UserCredential result = await _auth.signInWithEmailAndPassword(
          email: email, password: passwd);
      User user = result.user;
      if (user.emailVerified == true) {
        return _customUserModel(user);
      } else {
        showterror("Please Verify Your Account");
        print("the error in verifi email");

        return null;
      }
    } catch (signUpError) {
      autherror(signUpError);
    }
  }

  //signout
  Future signOutGoogle() async {
    try {
      print("User Signed Out");

      return await _auth.signOut();
    } catch (e) {
      print("the errr in signout $e");
      return null;
    }
  }
}

```

wrapper code:
```
import 'package:flutter/material.dart';
import 'package:project_center/Screen/Navationbar/contact.dart';
import 'package:project_center/main.dart';
import 'package:project_center/services/authenation.dart';
import 'package:provider/provider.dart';

class Wrappper extends StatefulWidget {
  @override
  _WrappperState createState() => _WrappperState();
}

class _WrappperState extends State<Wrappper> {
  // final FirebaseAuth _auth = FirebaseAuth.instance;
  @override
  Widget build(BuildContext context) {
    final user = Provider.of<CustomUser>(context);
    if (user != null && user.uid != null) {
      return MyHomePage();
    } else
      return Contact();
  }
}

```
sample img :
myhomepage :

![Screenshot (75)](https://user-images.githubusercontent.com/51741195/119022178-f37dd680-b9bd-11eb-830e-35a36c3f6546.png)

about page:

![Screenshot (74)](https://user-images.githubusercontent.com/51741195/119022193-f7a9f400-b9bd-11eb-80f6-363301c25cfc.png)

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```


pubspec code : 
name: project_center
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^5.0.0
  fluttertoast: ^8.0.7
  lottie: ^1.0.1
  # adobe_xd: ^2.0.0+1
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.3
  get: ^4.1.4
  google_fonts: ^2.1.0

  shared_preferences: ^2.0.5
  #firebase

  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


```

```




PS C:\Users\ASUS\Desktop\work space\flutter_project\flutter_coding\project_center> flutter run --verbose
[  +67 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[   +1 ms] executing: [C:\flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +48 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +34 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +71 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +82 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +61 ms] executing: C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +40 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +69 ms] Multiple devices found:
[  +25 ms] Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
[   +1 ms] Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.62
[   +1 ms] [1]: Chrome (chrome)
[        ] [2]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[   +1 ms] : 
[+3197 ms] 1
[  +13 ms] Skipping pub get: version match.
[  +34 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.2.0\
[   +7 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.3\
[   +3 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\
[   +4 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +5 ms] Found plugin fluttertoast at C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.7\
[  +24 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +3 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +3 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +5 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +12 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +2 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +3 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +3 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +3 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[  +13 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +4 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +3 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +86 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.2.0\
[   +3 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.3\
[   +1 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\
[   +2 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +3 ms] Found plugin fluttertoast at C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.7\
[  +14 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +1 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +4 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +6 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +2 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +2 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +3 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +2 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[  +11 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +2 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +26 ms] Generating C:\Users\ASUS\Desktop\work
space\flutter_project\flutter_coding\project_center\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +87 ms] Launching lib\main.dart on Chrome in debug mode...
[  +86 ms] Updating assets
[ +155 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +3 ms] Waiting for connection from debug service on Chrome...
[  +13 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.2.0\
[   +3 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.3\
[   +1 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\
[   +3 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +1 ms] Found plugin fluttertoast at C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.7\
[  +16 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +2 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +2 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +5 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +1 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +4 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +2 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +2 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[   +6 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +1 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +2 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +2 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +17 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.2.0\
[   +4 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.3\
[   +1 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\
[   +1 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.1.0\
[   +3 ms] Found plugin fluttertoast at C:\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.7\
[   +9 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +1 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +1 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +3 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +6 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +1 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +1 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +2 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +1 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[   +5 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +4 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +2 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +77 ms] <- reset
[   +5 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/ --incremental       
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\ASUS\AppData\Local\Temp\flutter_tools.1e2b75b9\flutter_tool.2208116d\app.dill --libraries-spec
file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\ASUS\Desktop\work
space\flutter_project\flutter_coding\project_center\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts  
--track-widget-creation --filesystem-root C:\Users\ASUS\AppData\Local\Temp\flutter_tools.1e2b75b9\flutter_tools.d86e55e8 --filesystem-scheme
org-dartlang-app --initialize-from-dill build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +10 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+19944 ms] Waiting for connection from debug service on Chrome... (completed in 20.2s)
[   +1 ms] Synced 40.0MB.
[        ] <- accept
[        ] Caching compiled dill
[ +250 ms] Using Opening in existing browser session.

[+1315 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on ws://127.0.0.1:52289/devtools/browser/65966ad0-283b-4051-8ccd-2c970009554d
[ +471 ms] DwdsInjector: Received request for entrypoint at http://localhost:52265/main_module.bootstrap.js
[   +6 ms] MetadataProvider: Loading debug metadata...
[  +12 ms] MetadataProvider: Loaded debug metadata
[   +7 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:52265/main_module.bootstrap.js
[+7947 ms] DevHandler: Debug service listening on ws://127.0.0.1:52319/WWRM3qayS0k=/ws

[  +12 ms] Debug service listening on ws://127.0.0.1:52319/WWRM3qayS0k=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+5779 ms] DevHandler: Stopped debug service on ws://127.0.0.1:52317

[+1335 ms] Application finished.
[  +25 ms] "flutter run" took 41,507ms.
[ +271 ms] ensureAnalyticsSent: 257ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[ +249 ms] Shutdown hooks complete
[   +3 ms] exiting with code 0
```

```
S C:\Users\ASUS\Desktop\work space\flutter_project\flutter_coding\project_center> flutter analyze
Analyzing project_center...                                             
No issues found! (ran in 2.9s)
PS C:\Users\ASUS\Desktop\work space\flutter_project\flutter_coding\project_center> 
```

```
PS C:\Users\ASUS\Desktop\work space\flutter_project\flutter_coding\project_center> flutter doctor -v
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-IN)
    • Flutter version 2.0.6 at C:\flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!
```

</details>
