### ISSUE TITLE
Explain federal plugin structure better

### ISSUE THREAD

**Issue by EPNW** [flutter/flutter#83117]
I'm currently migrating [a plugin](https://github.com/EPNW/opus_flutter/tree/null-safety) to the new federal plugin structure.
I have two (somewhat interconected) problems:

### How does federal plugin registration actually work?
[Developing packages & plugins on flutter.dev](https://flutter.dev/docs/development/packages-and-plugins/developing-packages) refers to [How To Write a Flutter Web Plugin: Part 2](https://medium.com/flutter/how-to-write-a-flutter-web-plugin-part-2-afdddb69ece6). There we are walked through the porcess of creating a federal plugin structure. But it is never explained, how flutter actually sets `UrlLauncherPlatform.instance`. And for web, the impelmented `UrlLauncherPlugin ` contains a misterious, not documented function
```dart
  /// Registers this class as the default instance of [UrlLauncherPlatform].
  static void registerWith(Registrar registrar) {
    UrlLauncherPlatform.instance = UrlLauncherPlugin();
  }
```
My guess is, that the pubspec.yaml tells flutter to look into the ` url_launcher_web.dart` file for a `UrlLauncherPlugin` class, which should have a register function by this:
```yaml
flutter:
  plugin:
    platforms:
      web:
        pluginClass: UrlLauncherPlugin
        fileName: url_launcher_web.dart
```
Could you please point me to where plugin registration is documented?

### Am I forced to use a class in Android and iOS?
While the Android and iOS versions of my plguin contain platform specific code (in form of native c code), they don't contain java or swift code. I don't want to be forced to have a java (or swift) class in my plugin, but it seems if I remove the generated one building fails. I also removed
```yaml
flutter:
  plugin:
    platforms:
      android:
        package: eu.epnw.opus_flutter_android
        pluginClass: OpusFlutterAndroid

```
from my `pubspec.yaml`, and replaced it with 
```yaml
flutter:
  plugin:
    platforms:
      android:
        pluginClass: OpusFlutterAndroid
        fileName: opus_flutter_android.dart

```
like in the example above, but now `flutter packages get` complains about
```
Invalid plugin specification opus_flutter_android.
Invalid "android" plugin specification.
```
I guess Android is not allowed to use a dart file for plugin registration?
I could live with just erasing all the content from the generated java class like [here](https://github.com/EPNW/opus_flutter/blob/a391278ce62dc1f567516acf7db1f4300e06e968/opus_flutter_android/android/src/main/java/eu/epnw/opus_flutter_android/OpusFlutterAndroidPlugin.java), but then again: How is my plugin registered?

### Lastly I want to mention while [How To Write a Flutter Web Plugin: Part 2](https://medium.com/flutter/how-to-write-a-flutter-web-plugin-part-2-afdddb69ece6) states
> Before we walk through how to actually implement a plugin, it’s worth discussing how we structure multi-platform plugins on the Flutter team. We intend for the plugins owned by the Flutter team to be models showing best practices for implementing Flutter plugins.

[flutters own plugins](https://github.com/flutter/plugins/tree/master/packages) don't follow the recommended approach for Android and iOS. Android and iOS code seem to be part of the app-facing package and not delegated to a platform specific plugin.

Edit: What I mean by this: Does that mean that we should not use the federal system for Android and iOS, or have you just not migrated yet 😅?
