### ISSUE TITLE
 test >=1.17.0 incompatible with Flutter 2.2

### ISSUE THREAD

**Issue by Ragnaroek** [flutter/flutter#83164]
## Steps to Reproduce

1. Upgrade Flutter to version 2.2
2. Update test to version 1.17.4 (latest at the moment)
3. Run flutter pub get

dev_dependencies section in the pubspec.yaml:

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test: 1.0.2+3
  test: 1.17.4
```

## Logs

I get this error:
```
Because test >=1.17.0 depends on test_api 0.4.0 and every version of flutter_driver from sdk depends on test_api 0.3.0, test >=1.17.0 is incompatible with flutter_driver from sdk.
So, because xxx depends on both flutter_driver any from sdk and test 1.17.4, version solving failed.
```

Don't see how I can resolve this other than waiting for a new Flutter release with updated dependencies that makes it compatible again?
