### ISSUE TITLE
gitlab-CI: WebSocketException: Connection to 'http://127.0.0.1:33655#' was not upgraded to websocket

### ISSUE THREAD

**Issue by boldt** [flutter/flutter#83344]
**Hint**: I cross-posted this issue also on https://github.com/cirruslabs/docker-images-flutter/issues/158, since I don't know whether it's a flutter issue or an issue with the docker-image.

## Environment

* Flutter 2.2.0
* Gitlab CI

## Steps to Reproduce

I created the standard "getting started" app:

```
flutter create flutter_test_mwe
```

On our local machines, we can run `flutter test`, which succeeds:

![grafik](https://user-images.githubusercontent.com/750793/119500140-c0de3000-bd67-11eb-8b6e-5f2c803cc1ba.png)

Now, we want to build the app with gitlab-CI. We're using the image `cirrusci/flutter:2.2.0`:

```
variables:
  FLUTTER_VERSION: 2.2.0

stages:
  - build
  - deploy

build_and_test_job:
  stage: build
  image: cirrusci/flutter:$FLUTTER_VERSION
  script:
    - flutter pub get
    - flutter test
    - flutter build apk
  tags:
    - docker
  only:
    - merge_requests
```

Now, `flutter test`crashes with the error:

> WebSocketException: Connection to 'http://127.0.0.1:33655#' was not upgraded to websocket

![grafik](https://user-images.githubusercontent.com/750793/119500380-06026200-bd68-11eb-9cfe-8af7cebd7c7c.png)
