### ISSUE TITLE
Release build of app crash upon opening, flutter 2.2.0

### ISSUE THREAD

**Issue by rh-id** [flutter/flutter#83393]
## Steps to Reproduce

1. open google play store and update the app
2. tap to open the app
3. the app shows splash screen
4. the app crash

![Screenshot_20210526-134731_Market Feedback Agent](https://user-images.githubusercontent.com/58564005/119616958-745c2880-be2b-11eb-9f93-4b22478fcbe4.jpg)

Tested Device: Samsung Galaxy S7, Android 8.0.0

Note on few things:
1. The app didn't crash on Oppo A53, Android 10, Color OS V7.2
2. The app works fine on flutter 2.0.5, it seemed to break after updating to 2.2.0 
3. there seemed to be no issue running on debug mode at emulator.
4. The app works fine after clean re-installation. Uninstalling previous version (flutter 2.0.5) and installing the latest app (flutter 2.2.0)

Flutter Doctor:
```
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0 at /home/rubyh/Flutter/flutter
    • Framework revision b22742018b (11 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/rubyh/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/rubyh/Android/Sdk
    • ANDROID_SDK_ROOT = /home/rubyh/Android/Sdk
    • Java binary at: /home/rubyh/Apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.
```

**Comment by TahaTesser** [comment]
Hi @rh-id 
Can you please provide your `crash logs` (instead of screenshot), your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by rh-id** [comment]
hi @TahaTesser, no `crash logs` the above screenshot is taken upon crash and tapping `Send Feedback`. the app run with no issue with `flutter run --release --verbose` on flutter 2.2.0

Pubspec:
```
name: my_gig_profile
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.4.6+36

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.1
  path: ^1.7.0
  flutter_localizations:
    sdk: flutter
  provider: ^4.3.2
  uuid: ^2.2.2
  path_provider: ^1.6.22
  flutter_typeahead: ^1.8.8
  pdf: ^1.11.2
  intl: ^0.17.0
  open_file: ^3.0.3
  numberpicker: ^1.3.0
  sortedmap: ^0.4.2+1
  android_alarm_manager: '>=0.4.5+17 <2.0.0'
  rxdart: ^0.24.1
  package_info: ^0.4.3+2
  webview_flutter: ^1.0.7
  launch_review: ^2.0.0
  mime: ^0.9.7
  flushbar: ^1.10.4
  image: ^2.1.19
  auto_animated: ^3.0.0
  shared_preferences:
    git:
      url: https://github.com/rh-apps/plugins.git
      ref: app-shared_preferences
      path: packages/shared_preferences/shared_preferences
  flutter_serviceloader_plugin:
    git:
      url: https://github.com/rh-apps/flutter_serviceloader_plugin.git
      ref: app
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```
