### ISSUE TITLE
NullPointerException for 'google_maps_flutter' plugin

### ISSUE THREAD

**Issue by flutter2k20** [flutter/flutter#83579]
Hi,

I am seeing the following NPE for my app at the Google Play Console - this error happened on Note 10+, but there are other devices as well impacted by this issue. 

I am using latest version of google_maps_flutter plugin and my Flutter version is 2.2.0.

Looks like error occurs during some cleanup of resources, but not sure how to avoid it. 

Any idea what could be causing this error?

```

java.lang.RuntimeException: 
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5602)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5641)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8506)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.NullPointerException: 
  at io.flutter.plugins.googlemaps.GoogleMapController.setGoogleMapListener (GoogleMapController.java:2)
  at io.flutter.plugins.googlemaps.GoogleMapController.dispose (GoogleMapController.java:14)
  at io.flutter.plugin.platform.VirtualDisplayController.dispose (VirtualDisplayController.java:16)
  at io.flutter.plugin.platform.PlatformViewsController.flushAllViews (PlatformViewsController.java:22)
  at io.flutter.plugin.platform.PlatformViewsController.onDetachedFromJNI (PlatformViewsController.java)
  at io.flutter.embedding.engine.FlutterEngine.destroy (FlutterEngine.java:36)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:90)
  at io.flutter.embedding.android.FlutterActivity.release (FlutterActivity.java:7)
  at io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java:11)
  at android.app.Activity.performDestroy (Activity.java:8459)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1344)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5587)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5641)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8506)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

**Comment by deveshgarg-max** [comment]
Hey @flutter2k20,
I just used the latest version of ```google_maps_flutter: ^2.0.6``` and not found any error can you please tell in detail what steps are you following to reproduce this error.
Here is my example code for ```google_maps_flutter: ^2.0.6```

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Completer<GoogleMapController> _controller = Completer();

  static const LatLng _center = const LatLng(45.521563, -122.677433);

  void _onMapCreated(GoogleMapController controller) {
    _controller.complete(controller);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Maps Sample App'),
          backgroundColor: Colors.green[700],
        ),
        body: GoogleMap(
          onMapCreated: _onMapCreated,
          initialCameraPosition: CameraPosition(
            target: _center,
            zoom: 11.0,
          ),
        ),
      ),
    );
  }
}
```

**Comment by flutter2k20** [comment]
> Hey @flutter2k20,
> I just used the latest version of `google_maps_flutter: ^2.0.6` and not found any error can you please tell in detail what steps are you following to reproduce this error.
> Here is my example code for `google_maps_flutter: ^2.0.6`
> 
> ```
> import 'dart:async';
> 
> import 'package:flutter/material.dart';
> import 'package:google_maps_flutter/google_maps_flutter.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatefulWidget {
>   @override
>   _MyAppState createState() => _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
>   Completer<GoogleMapController> _controller = Completer();
> 
>   static const LatLng _center = const LatLng(45.521563, -122.677433);
> 
>   void _onMapCreated(GoogleMapController controller) {
>     _controller.complete(controller);
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         appBar: AppBar(
>           title: Text('Maps Sample App'),
>           backgroundColor: Colors.green[700],
>         ),
>         body: GoogleMap(
>           onMapCreated: _onMapCreated,
>           initialCameraPosition: CameraPosition(
>             target: _center,
>             zoom: 11.0,
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```

The issue is happening on some of the user devices for my app and the error I posted above showed up in PlayConsole. This seems to be happening when the user is closing the app - as per my understanding. I am not sure about the exact steps as the error is happening on a remote/user device(s) and we don't have access to it.

**Comment by deveshgarg-max** [comment]
hey @flutter2k20  there is no issue in latest version of ```google_maps_flutter: ^2.0.6```  without more information i cant comment what is the problem please provide more information like your code or steps you followed i can suggest right now
1. Check google maps API key
2. Check is there anything you sending null as arg in dart code
3. run your application in flutter run --release and do test.

Thanks

**Comment by TahaTesser** [comment]
Hi @flutter2k20 
Can you please provide your `build.gradle` from `your/android/app`. See https://github.com/flutter/flutter/issues/69188 and also please provide your complete `pubspec.yaml` and `flutter run --release`
Thank you

**Comment by flutter2k20** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3 20E232 darwin-x64, locale en-CA)
    • Flutter version 2.2.0 at /Users/*******/flutter
    • Framework revision b22742018b (2 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/*******/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7846.93

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

**Comment by flutter2k20** [comment]
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
def configured = true
try {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
} catch (IOException e) {
    configured = false
    logger.error('Release signing information not found.')
}

project.ext {
    APP_ID = configured ? keystoreProperties['appId'] : "**********"
    KEYSTORE_STORE_FILE = configured ? rootProject.file(keystoreProperties['storeFile']) : null
    KEYSTORE_STORE_PASSWORD = keystoreProperties['storePassword']
    KEYSTORE_KEY_ALIAS = keystoreProperties['keyAlias']
    KEYSTORE_KEY_PASSWORD = keystoreProperties['keyPassword']
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

//android.buildTypes.release.ndk.debugSymbolLevel = 'FULL'

android {
    ndkVersion "22.0.7026061"
    signingConfigs {
        release {
            storeFile project.KEYSTORE_STORE_FILE
            storePassword project.KEYSTORE_STORE_PASSWORD
            keyAlias project.KEYSTORE_KEY_ALIAS
            keyPassword project.KEYSTORE_KEY_PASSWORD
        }
    }

    compileSdkVersion 29

    lintOptions {
        disable 'InvalidPackage'
    }
   
    defaultConfig {
        applicationId project.APP_ID
        minSdkVersion 20
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.google.guava:guava:30.1.1-android'
    implementation 'androidx.work:work-runtime:2.5.0'
    implementation 'androidx.preference:preference:1.1.1'
    implementation 'com.google.android.gms:play-services-location:18.0.0'
    implementation 'com.google.firebase:firebase-messaging:21.0.1'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by flutter2k20** [comment]
```
name: **********
description: ********************

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.22+122

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  intl: ^0.17.0
  http: ^0.13.1
  google_maps_flutter: ^2.0.5
  shared_preferences: ^2.0.5
  latlong2: ^0.8.0
  geocoder: ^0.2.1
  app_settings: ^4.1.0
  device_info: ^2.0.0
  #google_mobile_ads: ^0.12.0
  native_admob_flutter: ^1.3.2
  in_app_purchase: ^0.5.2
  share: ^2.0.1
  package_info: ^2.0.0
  image: ^3.0.2
  url_launcher: ^6.0.3
  google_fonts: ^2.0.0
  flutter_launcher_icons: ^0.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/images/logo.png
   - assets/certs/tomcat.cer
   - assets/images/blank.png
   - assets/images/start.png
   - assets/images/end.png
   - assets/images/error-loading.png
   - assets/images/loading.png
   - assets/images/splashscreen-background-top.png
   - assets/images/splashscreen-background-bottom.png
   - assets/fonts/font-38.zip
   - assets/fonts/font-48.zip
   - assets/fonts/font-72.zip

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
