### ISSUE TITLE
MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by vishnukvmd** [flutter/flutter#83613]
Unlike most other issues citing the same error, this is happening on **debug** mode.

**Crash Log**
```
E/flutter (30994): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter (30994): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (30994): <asynchronous suspension>                            
E/flutter (30994): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:78:24)
E/flutter (30994): <asynchronous suspension>                            
E/flutter (30994): #2      _runWithLogs (package:photos/main.dart:155:18)
E/flutter (30994): <asynchronous suspension>                            
E/flutter (30994): #3      _runInForeground (package:photos/main.dart:67:10)
E/flutter (30994): <asynchronous suspension>                            
E/flutter (30994): #4      main (package:photos/main.dart:62:3)         
E/flutter (30994): <asynchronous suspension>                            
```

This issue is device/platform specific and is happening on a Xiaomi Redmi 3S running Android 6.0.1. The same code is working fine on devices running a newer version of Android.

Since this is happening in the debug mode, there is no minification or obfuscation happening. 

I've already tried the following:
1. Downgraded gradle to 3.5.0 as suggested by https://github.com/flutter/flutter/issues/78625#issuecomment-803230115.
2. Upgraded `flutter_plugin_android_lifecycle` to v2.0.2. as suggested by https://github.com/flutter/flutter/issues/78625#issuecomment-809915540
3. `flutter channel master`
4. Created a new project, copy-pasted my `lib` folder and `pubspec.yaml` into it.

None of these steps have helped.

Here's my doctor summary:
```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.120, on Mac OS X 10.15.4 19E266 darwin-x64, locale en-US)
    • Flutter version 2.3.0-17.0.pre.120 at /Users/vishnu/work/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c42ec8592f (22 hours ago), 2021-05-28 22:34:02 -0400
    • Engine revision aca8aa2335
    • Dart version 2.14.0 (build 2.14.0-165.0.dev)
```

Here's are the dependencies in my `pubspec.yaml`
```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  photo_manager: ^1.0.6
  provider: ^3.1.0
  sqflite: ^2.0.0+3
  sqflite_migration: ^0.3.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  dio: ^4.0.0
  image: ^3.0.2
  share: ^2.0.1
  photo_view: ^0.11.1
  visibility_detector: ^0.2.0
  event_bus: ^2.0.0
  sentry: ^5.0.0
  super_logging:
    path: thirdparty/super_logging
  archive: ^3.1.2
  flutter_email_sender: ^5.0.0
  like_button: ^2.0.2
  logging: ^0.11.4
  flutter_image_compress:
    path: thirdparty/flutter_image_compress
  flutter_typeahead: ^1.8.1
  fluttertoast: ^8.0.6
  video_player: ^2.0.0
  chewie: ^1.0.0
  cached_network_image: ^3.0.0
  animate_do: ^1.7.2
  flutter_cache_manager: ^3.0.1
  computer: ^1.0.2
  flutter_secure_storage: ^4.2.0
  uni_links: ^0.5.1
  crisp: ^0.1.3
  flutter_sodium:
    path: thirdparty/flutter_sodium
  pedantic: ^1.9.2
  page_transition: "^1.1.7+2"
  scrollable_positioned_list: ^0.1.10
  connectivity: ^3.0.3
  url_launcher: ^6.0.3
  fluttercontactpicker: ^4.4.0
  in_app_purchase:
    path: thirdparty/in_app_purchase
  expansion_card: ^0.1.0
  flutter_password_strength: ^0.1.6
  flutter_inappwebview: ^5.3.2
  background_fetch: ^0.7.2
  # flutter_inapp_purchase: ^3.0.1
  google_nav_bar: ^5.0.5
  package_info_plus: ^1.0.1
  local_auth: ^1.1.5
  flutter_windowmanager: ^0.0.2
  flutter_user_agent: ^1.2.2
  quiver: ^3.0.1
  move_to_background: ^1.0.2
  loading_animations: ^2.1.0
  dots_indicator: ^2.0.0
  flutter_local_notifications: ^5.0.0+4
  open_file: ^3.2.1
  email_validator: '^1.0.6'
```

Please let me know if there's any other information I can provide.
