### ISSUE TITLE
Gotham fonts are buggy in the Flutter

### ISSUE THREAD

**Issue by davidgaspardev** [flutter/flutter#83616]
## Gotham fonts are buggy in the Flutter

Gotham fonts are not rendered correctly in Flutter. When I don't report the `fontFamily` argument in TextStyle, the fonts **work perfectly**, but when I explicitly report the `fontFamily` argument in TextStyle, it doesn't get the correct fonts and still generates an infinite size error for some fonts.

`pubspec.yaml`
```yaml
name: Oppy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Gotham
      fonts:
        - asset: lib/app/assets/fonts/gotham-black.ttf
          weight: 900
        - asset: lib/app/assets/fonts/gotham-bold.ttf
          weight: 700
        - asset: lib/app/assets/fonts/gotham-medium.ttf
          weight: 500
        - asset: lib/app/assets/fonts/gotham-regular.ttf
        - asset: lib/app/assets/fonts/gotham-light.ttf
          weight: 300
        - asset: lib/app/assets/fonts/gotham-thin.ttf
          weight: 100
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

`lib/app/helpers/widgets/label.dart`
```dart
/// External package
import 'package:flutter/material.dart';
/// Internal Package
import 'package:hoppy/app/helpers/palette.dart';

/// Label
/// It's a customized [Text] Widget
class Label extends Text {

  /// Text padding [EdgeInsets]
  final EdgeInsets padding;

  /// Contructor
  Label(String text, {
    Key? key,
    int? maxLines,
    // Default values
    double height = 1, /** fontSize * 1 */
    Color color = Palette.greyJet,
    TextAlign textAlign = TextAlign.start,
    double fontSize = 18,
    String fontFamily = "Gotham",
    FontStyle fontStyle = FontStyle.normal,
    FontWeight fontWeight = FontWeight.normal,
    this.padding = EdgeInsets.zero
  }): super(text, 
    key: key,
    maxLines: maxLines,
    textAlign: textAlign,
    // Setting style to the text
    style: TextStyle(
      decoration: TextDecoration.none,
      color: color,
      height: height,
      fontSize: fontSize,
      fontFamily: fontFamily, // <----------- if you comment this line works just fine
      fontStyle: fontStyle,
      fontWeight: fontWeight,
    )
  );

  /// Build text
  @override
  Widget build(BuildContext context) {
    // Return widget
    return Padding(
      padding: padding,
      child: super.build(context),
    );
  }
}

```

`lib/app/screens/access_screen.dart`
```dart
/// External package
import 'package:flutter/material.dart';
import 'package:hoppy/app/helpers/widgets/label.dart';
/// Internal packages
import 'package:hoppy/app/helpers/widgets/provider.dart';
import 'package:hoppy/app/screens/access/access_controller.dart';
import 'package:hoppy/app/helpers/palette.dart';

/// Access Screem
class AccessScreen extends StatelessWidget {

  static final String routeName = "/access";

  final AccessController _controller = AccessController();

  @override
  Widget build(BuildContext context) {
    return Provider<AccessController>(
      controller: _controller,
      screen: _screen,
    );
  }

  Widget _screen() {
    return Container(
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: <Color>[
            Palette.orangePantone,
            Palette.orangeWeb
          ],
        ),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Label("Hello World - Thin", fontWeight: FontWeight.w100),
          Label("Hello World - Thin italic", fontWeight: FontWeight.w100, fontStyle: FontStyle.italic),
          Label("Hello World - Light", fontWeight: FontWeight.w300),
          Label("Hello World - Light italic", fontWeight: FontWeight.w300, fontStyle: FontStyle.italic),
          Label("Hello World - Regular", fontSize: 16),
          Label("Hello World - Regular italic", fontStyle: FontStyle.italic),
          Label("Hello World - Medium", fontWeight: FontWeight.w500),
          Label("Hello World - Medium italic", fontWeight: FontWeight.w500, fontStyle: FontStyle.italic),
          Label("Hello World - Bold", fontWeight: FontWeight.bold),
          Label("Hello World - Bold italic", fontWeight: FontWeight.bold, fontStyle: FontStyle.italic),
          Label("Hello World - Black", fontWeight: FontWeight.w900),
        ]
      ),
    );
  }
}

```

Text without `fontFamily`
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-30 at 01 18 44](https://user-images.githubusercontent.com/37712275/120091888-5cafc900-c0e5-11eb-8e21-fd536b17bceb.png)

Text with `fontFamily`
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-30 at 01 19 42](https://user-images.githubusercontent.com/37712275/120091905-7f41e200-c0e5-11eb-8248-ca1281379a10.png)
Error: RenderParagraph object was given an infinite size during layout.

#### Why does everything work well when I am not informing the `fontFamily`, moreover how does he know the font I want, and why does this nonsense error occur when I inform `fontFamily` which is the right way?

<details>
  <summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>
