### ISSUE TITLE
[maps] App  prints `exceeded sample count in FrameTime` 

### ISSUE THREAD

**Issue by nikhiladmin** [flutter/flutter#83687]
My app continously logging 
`androidmapsapi- identical 17 lines
I/Counters( 8336): exceeded sample count in FrameTime` 
and network speed over 500 kb/s continously .

  ```
GoogleMap(
                polylines: _polylines,
                onTap: (latlng) {
                  setState(() {
                    ontaped = !ontaped;
                  });
                },
                buildingsEnabled: true,
                mapToolbarEnabled: false,
                myLocationEnabled: false,
                markers: Set<Marker>.of(_markers.values),
                trafficEnabled: _trafic,
                zoomControlsEnabled: false,
                mapType: MapType.normal,
                onCameraMoveStarted: () {},
                onCameraMove: _onCameraMoving,
                onCameraIdle: () {
                  if (_markerIdCounter == 1 && _startPosition != null) {
                    Provider.of<Home>(context, listen: false)
                        .getAddress(_startPosition)
                        .then((value) {
                      setState(() {
                        _startController.text = value;
                      });
                    });
                  } else if (_markerIdCounter == 2) {
                    Provider.of<Home>(context, listen: false)
                        .getAddress(_endPosition)
                        .then((value) {
                      setState(() {
                        _endController.text = value;
                      });
                    });
                  }
                },
                initialCameraPosition: _initial,
                onMapCreated: _onMapCreated),
```

It work fine before I just some changes API key .
How can i fix it .

**Comment by TahaTesser** [comment]
Hi @nikhiladmin 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by davemg3** [comment]
Well...i  started having same message with my google_maps_flutter: ^2.0.1 without changing the version and the API keys...will try to achieve a minimal code sample after some rest

**Comment by Jaykocha** [comment]
same here! drives me crazy :/. Did not even change anything! Yesterday it was still fine!
Using google_maps_flutter: ^2.0.3 

It is not happening on all my phones but on some! When the map is touched and you move it or zoom in or out I get easily over a thousand `I/Counters(20519): exceeded sample count in FrameTime` prints in like a few seconds. If the map is not touched or anything, then it prints that `exceeded sample count in FrameTime` like 1 time every second. Also my Logcat in Android Studio goes absolutely crazy. 

For me, it stops when I remove the line: "myLocationEnabled: true" in GoogleMap Widget.

@nikhiladmin @davemg3 Were you able to resolve the issue?

**Comment by Jaykocha** [comment]
@davemg3 @TahaTesser @nikhiladmin 

I was still not able to resolve this issue and frankly don't know where to look for it. I only found out it is connected to the request of location updates from GPS (android logcat flooding shows that).

Any ideas??

**Comment by duzenko** [comment]
Same here

**Comment by VaneeOfficialNet** [comment]
I'm also facing the same issue.. any google map version that doesn't have the issue?

**Comment by JobSeow** [comment]
Am also facing the same issues. Wondering if it has been fixed? I ran the code off Google Maps Flutter page, under "Sample Usage"  [https://pub.dev/packages/google_maps_flutter](url), without third party packages and the warning of `I/Counters(13406): exceeded sample count in FrameTime` still appears when map is touched/zoomed in 

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}
```

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
    • Flutter version 2.0.1 at C:\Users\XXXX\Documents\flutter_windows_2.0.1-stable\flutter
    • Framework revision c5a4b4029c (5 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Job\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\XXXXXX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • G8441 (mobile) • XXXXXX• android-arm64  • Android 9 (API 28)
    • Chrome (web)   • chrome     • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)     • edge       • web-javascript • Microsoft Edge 91.0.864.59

• No issues found! 
```

</details>
<details>
<summary>pubspec.yaml</summary>

```
name: googlemaps
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

</details>
<details>
<summary>flutter run --verbose </summary>

```
[ +118 ms] Syncing files to device XXXXX...
[   +3 ms] <- reset
[   +1 ms] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:googlemaps/main.dart 5affb19f-f05b-4187-84b7-337d67d400ae
[        ] <- 5affb19f-f05b-4187-84b7-337d67d400ae
[  +83 ms] Updating files.
[   +1 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device XXXX... (completed in 92ms)
[   +3 ms] Synced 0.0MB.
[   +1 ms] <- accept
[  +15 ms] Connected to _flutterView/0x7684ea3820.
[  +10 ms] Flutter run key commands.
[  +23 ms] r Hot reload. 
[   +3 ms] R Hot restart.
[   +2 ms] h Repeat this help message.
[   +2 ms] d Detach (terminate "flutter run" but leave application running).
[   +2 ms] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[   +1 ms] An Observatory debugger and profiler on G8441 is available at: http://127.0.0.1:64017/cvJ1AAvz80Y=/
[   +2 ms]
           Flutter DevTools, a Flutter debugger and profiler, on G8441 is available at: http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A64017%2FcvJ1AAvz80Y%3D%2F
[   +1 ms] Running with unsound null safety
[   +3 ms] For more information see https://dart.dev/null-safety/unsound-null-safety
[ +118 ms] I/zzbz    (13406): Making Creator dynamically
[  +32 ms] W/tter.googlemap(13406): Unsupported class loader
[   +5 ms] W/tter.googlemap(13406): Skipping duplicate class check due to unsupported classloader
[   +4 ms] I/DynamiteModule(13406): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203113001
[   +2 ms] I/DynamiteModule(13406): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203113001
[   +2 ms] V/DynamiteModule(13406): Dynamite loader version >= 2, using loadModule2NoCrashUtils
[   +4 ms] W/tter.googlemap(13406): Unknown chunk type '200'.
[  +15 ms] W/tter.googlemap(13406): Unsupported class loader
[   +6 ms] W/tter.googlemap(13406): Skipping duplicate class check due to unsupported classloader
[  +42 ms] I/Google Maps Android API(13406): Google Play services client version: 12451000
[   +8 ms] I/Google Maps Android API(13406): Google Play services package version: 212418029
[   +6 ms] I/Google Maps Android API(13406): Google Play services maps renderer version(legacy): 203113001
[  +25 ms] W/tter.googlemap(13406): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
[ +392 ms] W/Google Maps Android API(13406): Deprecation notice: In a future release, indoor will no longer be supported on satellite, hybrid or terrain type maps. Even where
indoor is not supported, isIndoorEnabled() will continue to return the value that has been set via setIndoorEnabled(), as it does now. By default, setIndoorEnabled is 'true'.
The API release notes (https://developers.google.com/maps/documentation/android-api/releases) will let you know when indoor support becomes unavailable on those map types.
[  +53 ms] E/GoogleMapController(13406): Cannot enable MyLocation layer as location permissions are not granted
[+1147 ms] I/Counters(13406): exceeded sample count in FrameTime
[  +84 ms] I/Counters(13406): exceeded sample count in FrameTime
[ +723 ms] W/DynamiteModule(13406): Local module descriptor class for com.google.android.gms.googlecertificates not found.
[  +12 ms] I/DynamiteModule(13406): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
[   +4 ms] I/DynamiteModule(13406): Selected remote version of com.google.android.gms.googlecertificates, version >= 6
[  +12 ms] W/tter.googlemap(13406): Unsupported class loader
[  +26 ms] W/tter.googlemap(13406): Skipping duplicate class check due to unsupported classloader
[+83690 ms] I/Counters(13406): exceeded sample count in FrameTime
[  +14 ms] I/Counters(13406): exceeded sample count in FrameTime
[  +27 ms] I/Counters(13406): exceeded sample count in FrameTime
[   +1 ms] I/Counters(13406): exceeded sample count in FrameTime
[  +28 ms] I/Counters(13406): exceeded sample count in FrameTime
[   +4 ms] I/Counters(13406): exceeded sample count in FrameTime
```

</details>
<details>
<summary>flutter --version</summary>

```
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (5 months ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

```

</details>
