### ISSUE TITLE
New apps that use UIWebView are no longer accepted.

### ISSUE THREAD

**Issue by hasnainelahi** [flutter/flutter#83712]
Hope you are doing well. 
New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. IOS 10.0. Apple rejecting my binary. 
Anyone can help me with an exact solution for flutter.

<details> 
<summary>pubspec.yaml</summary> 
	
```yaml
pubspec.yaml: 
    cupertino_icons: ^1.0.2
    toast: ^0.1.5
    intl:
    feather_icons_flutter: ^4.7.4
    dio:
    image_picker:
    flutter_svg:
    shared_preferences:
    cached_network_image:
    flutter_launcher_icons: ^0.9.0
    flutter_verification_code: ^1.0.1
    clipboard: ^0.1.3
    ribbon: ^0.0.1
    bubble: ^1.2.1
    socket_io_client: ^1.0.1
    share: ^2.0.1
    pull_to_refresh: ^2.0.0
    webview_flutter: ^2.0.8
    firebase_core: ^0.7.0
    firebase_auth: ^0.20.1
    firebase_messaging: ^8.0.0-dev.15
    utopic_toast: ^0.1.3
    email_validator: ^2.0.1
    flutter_facebook_login: ^3.0.0
    google_sign_in: ^4.5.9
    flutter_twitter_login:
      git: git://github.com/eudangeld/flutter_twitter_login.git
```

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
    [✓] Flutter (Channel stable, 2.2.1, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
        • Flutter version 2.2.1 at /Users/hasnainelahi/Developer/flutter
        • Framework revision 02c026b03c (5 days ago), 2021-05-27 12:24:44 -0700
        • Engine revision 0fdb562ac8
        • Dart version 2.13.1
    
    [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
        • Android SDK at /Users/hasnainelahi/Library/Android/sdk
        • Platform android-30, build-tools 30.0.2
        • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
        • All Android licenses accepted.
    
    [✓] Xcode - develop for iOS and macOS
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Xcode 12.3, Build version 12C33
        • CocoaPods version 1.10.1
    
    [✓] Chrome - develop for the web
        • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
    [✓] Android Studio (version 4.1)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    
    [✓] VS Code (version 1.56.2)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.22.0
    
    [✓] Connected device (1 available)
        • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    
    • No issues found!
```

</details>
