### ISSUE TITLE
Vin decoder - Error: Null safety features are disabled for this library.

### ISSUE THREAD

**Issue by nijatmursali** [flutter/flutter#83800]
Hello, 

I have update my Flutter to latest version and I'm now facing issue with some packages. 

The error is:

```
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/vin_decoder_base.dart:20:22: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  ExtendedVehicleInfo? _info;
                     ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/vin_decoder_base.dart:29:21: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  bool valid([String? number]) {
                    ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/vin_decoder_base.dart:39:6: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  int? getYear() {
     ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/vin_decoder_base.dart:67:9: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  String? getManufacturer() {
        ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/vin_decoder_base.dart:86:9: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  String? getChecksum() {
        ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/vin_decoder_base.dart:108:16: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  Future<String?> getMakeAsync() async {
               ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/vin_decoder_base.dart:115:16: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  Future<String?> getModelAsync() async {
               ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/vin_decoder_base.dart:122:16: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  Future<String?> getVehicleTypeAsync() async {
               ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:6:9: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  String? value;
        ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:7:9: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  String? valueId;
        ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:8:9: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  String? variable;
        ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:9:6: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  int? variableId;
     ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:27:6: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  int? count;
     ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:28:9: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  String? message;
        ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:29:9: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  String? searchCriteria;
        ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:30:20: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  List<NHTSAResult>? results;
                   ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:81:9: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  String? make;
        ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:82:9: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  String? model;
        ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:83:9: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  String? vehicleType;
        ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:85:36: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
  static Future<ExtendedVehicleInfo?> getExtendedVehicleInfo(String vin) async {
                                   ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/vin_decoder_base.dart:22:8: Error: Type 'required' not found.
  VIN({required this.number, this.extended = false})
       ^^^^^^^^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/vin_decoder_base.dart:22:8: Error: 'required' isn't a type.
  VIN({required this.number, this.extended = false})
       ^^^^^^^^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:43:18: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
          results!.add(NHTSAResult.fromJson(v));
                 ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:57:12: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
    results!.forEach((f) {
           ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:60:58: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
          info.vehicleType = normalizeStringValue(f.value!);
                                                         ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:63:51: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
          info.make = normalizeStringValue(f.value!);
                                                  ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/vin_decoder-0.1.4/lib/src/nhtsa_model.dart:66:52: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
          info.model = normalizeStringValue(f.value!);
```

The thing is that I don't even have that package installed and I don't know why it gives error exactly. My pubspec.yaml is 

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  firebase_analytics: ^8.1.0
  firebase_core: ^1.0.4
  firebase_auth_web: ^1.0.7
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.4
  firebase_messaging: ^10.0.0
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^9.0.0
  flutter_cupertino_date_picker: ^1.0.26+2
  http_parser: ^4.0.0
  dio: ^4.0.0-prev3
  flutter_speed_dial: ^2.0.0
  image_picker: ^0.6.3+4
  image_cropper: ^1.4.0
  modal_progress_hud: ^0.1.3
  easy_localization: ^3.0.0
  cached_network_image: ^3.0.0
  keyboard_dismisser: ^2.0.0
  validators: ^2.0.0
  flutter_credit_card: ^0.1.4
  intl: ^0.17.0
  country_code_picker: ^2.0.1
  stripe_payment: ^1.0.11
  credit_card_type_detector: ^1.0.2
  country_list_pick: ^1.0.1+4
  audiofileplayer: ^2.0.0
  vibration: ^1.7.3
  bordered_text: ^1.0.1
  google_sign_in: ^5.0.3
  random_string: ^2.1.0
  carousel_slider: ^3.0.0
  pinput: ^1.2.0
  flutter_easyloading: ^3.0.0
  delayed_display: ^2.0.0
  flutter_swiper: ^1.1.6
  splashscreen: ^1.3.5
```

My flutter version

```
Flutter 2.3.0-16.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision fa5883b78e (12 days ago) • 2021-05-21 13:04:03 -0700
Engine • revision 2f067fc4c5
Tools • Dart 2.14.0 (build 2.14.0-136.0.dev)
```

The thing is that everything was working till before 3 hours, but right after that it just stopped working. My ```flutter doctor``` doesn't have any errors as well. 

I would like to know how to solve this Vin decoder error as I don't have that package.
