### ISSUE TITLE
[google_maps_flutter]not showing up after publishing on play store

### ISSUE THREAD

**Issue by Osmancn** [flutter/flutter#84352]
When I install the apk I created, it works, but when I throw that apk to the play store, it does not work.

![Screen Shot 2021-06-10 at 18 16 35](https://user-images.githubusercontent.com/37872740/121551876-ab7c2d80-ca18-11eb-8936-e95b2a29e66f.png)

<details> 
<summary>pubspec.yaml</summary> 
	
```yaml
name: pratiko
description: Pratiko

version: 2.5.6+120

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_sequence_animation: "^3.0.0"
  flutter_launcher_icons: "^0.7.0"
  flutter_launcher_name: "^0.0.1"
  shared_preferences: ^0.5.12+4
  carousel_slider: ^2.3.1
  http: ^0.12.2
  flutter_platform_widgets: ^1.1.0
  pin_code_fields: ^6.0.2
  expandable: ^4.1.4
  font_awesome_flutter: ^8.11.0
  cached_network_image: ^2.5.0
  flutter_slidable: ^0.5.7
  photo_view: ^0.10.3
  flutter_datetime_picker: ^1.5.0
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  image_picker: ^0.6.7+22
  pull_to_refresh: ^1.6.4
  file_picker: ^2.1.6
  signalr_core: ^1.0.8
  shimmer: ^1.1.2
  package_info: ^0.4.3
  html: ^0.14.0+3
  url_launcher: ^5.7.2
  advance_pdf_viewer: ^1.2.2
  smart_select: ^4.3.2
  image_cropper: ^1.3.1
  edge_detection: ^1.0.5
  flutter_native_image: ^0.0.5
  mixpanel_flutter: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  showcaseview: ^1.0.0
  qr_code_scanner: ^0.3.5
  google_maps_flutter: ^1.2.0
  geolocator: ^6.2.1
  barcode_scan2: ^4.0.1
```

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 2.0.3 at /Users/osmancan/flutter
    • Framework revision 4d7946a68d (3 months ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/osmancan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
```

</details>
