### ISSUE TITLE
I have a problem with my Android Studio, when i try to run my app from Web

### ISSUE THREAD

**Issue by coja99** [flutter/flutter#84768]
I get this error, every time I run my app to Chrome(web). 

<details> 
<summary>logs</summary> 
	
```console
>TypeError: Cannot read property 'app' of undefined
    at Object.app$ [as app] (http://localhost:53187/packages/firebase_core_web/src/interop/core.dart.lib.js:31:101)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:53187/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:773:64)
    at Function.registerWith (http://localhost:53187/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:692:73)
    at Object.registerPlugins (http://localhost:53187/packages/first_flutter_app/generated_plugin_registrant.dart.lib.js:16:46)
    at main (http://localhost:53187/web_entrypoint.dart.lib.js:31:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:53187/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:53187/dart_sdk.js:37453:7)
    at main$ (http://localhost:53187/web_entrypoint.dart.lib.js:30:18)
    at http://localhost:53187/main_module.bootstrap.js:19:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:53187/main_module.bootstrap.js:18:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:53187/dwds/src/injected/client.js:8825:21)
    at http://localhost:53187/dwds/src/injected/client.js:22713:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53187/dwds/src/injected/client.js:3851:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53187/dwds/src/injected/client.js:11063:12)
    at Object._asyncStartSync (http://localhost:53187/dwds/src/injected/client.js:3815:20)
    at main__closure1.$call$body$main__closure (http://localhost:53187/dwds/src/injected/client.js:22725:16)
    at main__closure1.call$1 (http://localhost:53187/dwds/src/injected/client.js:22652:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:53187/dwds/src/injected/client.js:4185:16)
    at _CustomZone.runUnary$2$2 (http://localhost:53187/dwds/src/injected/client.js:12436:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:53187/dwds/src/injected/client.js:12383:14)
    at _ControllerSubscription._sendData$1 (http://localhost:53187/dwds/src/injected/client.js:11959:19)
    at _DelayedData.perform$1 (http://localhost:53187/dwds/src/injected/client.js:12148:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:53187/dwds/src/injected/client.js:12197:14)
    at Object._microtaskLoop (http://localhost:53187/dwds/src/injected/client.js:4023:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:53187/dwds/src/injected/client.js:4029:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:53187/dwds/src/injected/client.js:10932:9)
    at invokeClosure (http://localhost:53187/dwds/src/injected/client.js:1259:26)
    at MutationObserver.<anonymous> (http://localhost:53187/dwds/src/injected/client.js:1278:18)
```

</details>

This is my pubspec.yaml file:

>name: kuda-ici
description: A new Flutter project.
The following line prevents the package from being accidentally published to
pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

<details> 
<summary>pubspec.yaml</summary> 
	
```yaml
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


   The following adds the Cupertino Icons font to your application.
   Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  firebase_storage: ^8.1.3
  firebase_core: ^1.3.0
  cloud_firestore_web: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

 For information on the generic Dart part of this file, see the
 following page: https://dart.dev/tools/pub/pubspec
 The following section is specific to Flutter.

flutter:

   The following line ensures that the Material Icons font is
   included with your application, so that you can use the icons in
   the material Icons class.
  uses-material-design: true

   To add assets to your application, add an assets section, like this:
  assets:
    - images/prijava.png
    - images/registracija.png
    - images/a_dot_ham.jpeg

   An image asset can refer to one or more resolution-specific "variants", see
   https://flutter.dev/assets-and-images/#resolution-aware.

   For details regarding adding assets from package dependencies, see
   https://flutter.dev/assets-and-images/#from-packages

   To add custom fonts to your application, add a fonts section here,
   in this "flutter" section. Each entry in this list should have a
   "family" key with the font family name, and a "fonts" key with a
   list giving the asset and other descriptors for the font. For
  example:
   fonts:
     - family: Schyler
       fonts:
         - asset: fonts/Schyler-Regular.ttf
         - asset: fonts/Schyler-Italic.ttf
           style: italic
     - family: Trajan Pro
       fonts:
         - asset: fonts/TrajanPro.ttf
         - asset: fonts/TrajanPro_Bold.ttf
           weight: 700
```

</details>
