### ISSUE TITLE
url launcher give me error in android

### ISSUE THREAD

**Issue by AbanoubWagih94** [flutter/flutter#84786]
i got this error with url launcher 
```
       E/flutter (16254): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No 
       implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
      E/flutter (16254): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
      E/flutter (16254): <asynchronous suspension>
      E/flutter (16254): #1      canLaunch (package:url_launcher/url_launcher.dart:123:10)
      E/flutter (16254): <asynchronous suspension>
      E/flutter (16254): #2      _ImageSlidersState.build.<anonymous closure>.<anonymous closure> 
      (package:/screens/explore_screen/components/images_sliders.dart:30:25)
      E/flutter (16254): <asynchronous suspension>
      E/flutter (16254):
      D/ColorViewRootUtil(16254): swipeFromBottom!
```
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.2 at E:\abanoub\flutter
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/DELL/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.57.0)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • CPH1937 (mobile) • 383ad24b • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 91.0.864.48

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @AbanoubWagih94 
Can you please provide,a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample and your `url_luncher` version
Thank you

**Comment by AbanoubWagih94** [comment]
@TahaTesser 

```
   GestureDetector(
                  onTap: () async {
                    if (await canLaunch(item.url)) {
                      final bool nativeAppLaunchSucceeded = await launch(
                        item.url,
                        forceSafariVC: false,
                        universalLinksOnly: true,
                      );
                      if (!nativeAppLaunchSucceeded) {
                        await launch(
                          item.url,
                          forceSafariVC: true,
                        );
                      }
                    }
                  },
                  child: ClipRRect(
                    borderRadius: BorderRadius.all(Radius.circular(5.0)),
                    child: FadeInImage.assetNetwork(
                      imageErrorBuilder: (BuildContext context,
                          Object exception, StackTrace stackTrace) {
                        return Image.asset('assets/images/slider.png');
                      },
                      image: 'https://www.ibookcast.com/uploads/images/${item.pic}',
                      placeholder: 'assets/images/slider.png',
                      fit: BoxFit.cover,
                      width: double.infinity,
                    ),
                  ),
                ),
```
and logs 
```
   [  +36 ms] D/ColorViewRootUtil( 5062): swipeFromBottom!
[  +43 ms] E/flutter ( 5062): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No
implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
[   +8 ms] E/flutter ( 5062): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
[  +11 ms] E/flutter ( 5062): <asynchronous suspension>
[  +12 ms] E/flutter ( 5062): #1      canLaunch (package:url_launcher/url_launcher.dart:123:10)
[   +5 ms] E/flutter ( 5062): <asynchronous suspension>
[  +20 ms] E/flutter ( 5062): #2      _ImageSlidersState.build.<anonymous closure>.<anonymous closure>
(package:ibook/screens/explore_screen/components/images_sliders.dart:29:25)
[  +12 ms] E/flutter ( 5062): <asynchronous suspension>
[   +2 ms] E/flutter ( 5062): 
```
pubspec.yaml file
```
name: ibook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  flutter_svg: ^0.21.0+1
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  google_sign_in: ^5.0.1
  flutter_facebook_auth: ^3.3.2+2
  flutter_facebook_login: ^3.0.0
  url_launcher: ^6.0.3 
  dio: ^4.0.0
  get: ^4.1.4
  provider: ^5.0.0
  carousel_slider: ^3.0.0
  font_awesome_flutter: ^9.0.0
  json_annotation: ^3.1.1
  flutter_typeahead: ^3.1.3
  intl: ^0.17.0
  flutter_offline: ^2.0.0
  group_radio_button: ^1.1.0
dev_dependencies:
  flutter_launcher_icons: 
  json_serializable: 
  build_runner:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ibook_icon.png"   
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
