### ISSUE TITLE
iOS App Rejected due to UIWebView are no longer accepted

### ISSUE THREAD

**Issue by naeemAkee** [flutter/flutter#85003]
Hello Respected!

I'm using latest Flutter version and latest plugins but still my app is rejecting due to 

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale
    en-PK)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)
```

pubspec.yaml file 
```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_rating_bar: ^3.2.0+1
  dotted_border: ^2.0.0
  image_picker: ^0.8.0+3
  flutter_html: ^2.1.0
  jiffy: ^4.1.0
  geocoder: ^0.2.1
  geolocator: ^7.1.0
  url_launcher: ^6.0.6
  flutter_facebook_login: ^3.0.0
  android_intent: ^2.0.2
  badges: ^1.1.6
  google_static_maps_controller: ^0.4.1
  percent_indicator: ^2.1.9
  fluttertoast: ^7.1.6
  async: ^2.4.2
  multiselect_formfield: ^0.1.5
  google_maps_flutter: ^2.0.6
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
  firebase_auth: ^1.4.1
  google_sign_in: ^5.0.4
  flutter_twitter_login: ^1.1.0
  data_connection_checker: ^0.3.4
  social_share: ^2.1.1
  screenshot: ^0.3.0
  flutter_launcher_icons: ^0.9.0
  html_editor_enhanced: ^2.1.1
  webview_flutter: ^2.0.8



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"



dev_dependencies:
  flutter_test:
    sdk: flutter

```

Please help me in that, I'm facing this issue from couple of days.

Thank you please.
