### ISSUE TITLE
App not installed error after Flutter 2.2

### ISSUE THREAD

**Issue by akfaisel** [flutter/flutter#85301]
Hi

Three months back, I developed a Flutter project (using Flutter 1.22) and built apk using `flutter build apk`

Now I have updated my Flutter to 2.2 Stable. I built apk for the same code (without any modification to the source code) but this time the apk is not installing. I'm getting "App not installed"

The apk files are uploaded at https://ufile.io/f/k1gx0

_Note: These apks are neither signed nor available at Play Store. This app is purely for internal circulation only._

**Expected:** The new apk is supposed to install over the old version.

**Actual:** App not installed error.

If I uninstall the old apk and install the new apk, the installation goes well. But if I uninstall, old app data gets cleared. 

### Here is my Flutter Doctor report
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.1052], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Connected device (3 available)

• No issues found!
```
### Here is my pubspec.yaml

```
name: projacct
description: Personal Project and Accounting app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  fluttertoast: ^7.1.6
  intl: ^0.16.1
  percent_indicator: ^2.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
```
This issue is driving me nuts.

Please help me.
