### ISSUE TITLE
Execution failed for task ':app:checkDebugAarMetadata'.

### ISSUE THREAD

**Issue by cgfischer** [flutter/flutter#85711]
I have a flutter application that has been building reliably but today fails to build with this error (see details below).  I successfully built this application yester on several Windows 10 development machines.  The same code now fails (starting July 1) on those same development machines even though the code didn't change and now new software was installed (unless there was an automatic Windows update?).

<details> 
<summary>logs</summary> 
	
```console
Launching lib\main.dart on sdk gphone x86 arm in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (30) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.core:core-ktx:1.7.0-alpha01.
        AAR metadata file: C:\Users\cf\.gradle\caches\transforms-2\files-2.1\ca6971022d1745afd625d4f72b79b8d7\jetified-core-ktx-1.7.0-alpha01\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (30) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.core:core:1.7.0-alpha01.
        AAR metadata file: C:\Users\cf\.gradle\caches\transforms-2\files-2.1\8a2e49ffc55c3a818fc5d26b43ba6f79\core-1.7.0-alpha01\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 52s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin audioplayers...
Welcome to Gradle 4.10.2!
Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC6
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block
For more details see https://docs.gradle.org/4.10.2/release-notes.html
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\projects\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.18.3\android\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'audioplayers'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 4.10.2 is not compatible with the Kotlin Gradle plugin. Please use Gradle 5.3 or newer, or the previous version of the Kotlin plugin.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s

Exception: The plugin audioplayers could not be built due to the issue above.
Exited (sigterm)
```
 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
C:\projects\gcr-mobile>flutter doctor -v
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
    • Flutter version 2.2.2 at C:\projects\flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\cf\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.59

• No issues found!
```

</details>

</details>

<details> 
<summary>pubspec.yaml</summary> 
	
```yaml
name: gcrunner
description: GC Runner Application project.

publish_to: 'none'

version: 1.1.6+168

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^3.0.2+2
  intl: ^0.17.0
  flutter_app_badger: ^1.2.0
  package_info: ^2.0.2
  connectivity: ^3.0.6
  wifi_info_flutter: ^2.0.2
  stack_trace: ^1.10.0
  geolocator: ^7.0.3
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^4.2.0
  device_info: ^2.0.2
  http: ^0.13.3
  http_interceptor: ^0.4.1
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.0.2
  uuid: ^3.0.4
  charts_flutter: ^0.10.0
  flutter_markdown: ^0.6.1
  audioplayers: ^0.18.3
  url_launcher: ^6.0.4
  percent_indicator: ^3.0.1
  video_player: ^2.1.4
  firebase_core: ^1.0.2
  firebase_messaging: ^9.1.0
  cupertino_icons: ^1.0.0
  json_annotation: ^3.1.1
  receive_sharing_intent: ^1.4.3
  linkify: ^4.0.0
  logger: ^1.0.0
  synchronized: ^3.0.0
  pdf_render: ^1.0.11
  gallery_saver: ^2.1.0
  path_provider: ^2.0.2
  mime: ^1.0.0
  youtube_player_flutter: ^8.0.0
  # webview_flutter: ^1.0.7
  # youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  build_runner: ^1.11.5
  json_serializable: ^3.5.1

flutter_icons:
  image_path: "icons/icon-test.png"
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/mgcc-home.jpg
    - assets/hole-stats-help.md
    - assets/round-stats-help.md
    - assets/icons8-mu-52.png
    - assets/golfball.mp3
    - assets/golfswing.mp3
    - assets/crowd-cheer-1.wav
    - assets/missedLeft.png
    - assets/missedRight.png
    - assets/missedDeep.png
    - assets/missedShort.png
    - assets/hitFairway.png
    - assets/splash-image.jpg
    - assets/couplesleague.jpg
    - assets/mensleague.jpg
    - assets/membergame.jpg
    - assets/news.jpg
    - assets/test.jpg
    - assets/womensleague.jpg
    - assets/social.jpg
    - assets/private.jpg

  fonts:
    - family: DroidSansMono
      fonts:
        - asset: fonts/DroidSansMono.ttf

```

</details>
