### ISSUE TITLE
After upgrading to null safety hot reload not working on iOS & Android => blank/white screen

### ISSUE THREAD

**Issue by JonasKuschel** [flutter/flutter#86015]
Hi,
since upgrading to null safety months ago my hot reload is not working anymore on Android emulator & iOS simulator. Whenever I try to hot reload(Android studio & vscode), the application disappears and the ios & android emulator goes blank/white screen. The app shows up again when using hot restart.

Things I have tried and didn't fix it:
 * switched flutter to master channel (see #49185)
 * Created a new flutter application and transfering the code
 * Trying to exclude some extensions & code to see if they created the error
 * Reviewing package migration guides
 * Reviewing null safety migration guide 
 * `flutter clean`

Any ideas to fix this issue?

Thank you for your support

Jonas

## Package versions before updating:
```
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0
  injectable: ^1.0.5
  auto_route: ^0.6.9
  get_it: ^6.0.0
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  firebase_auth: ^1.0.3
  google_sign_in: ^5.0.1
  flutter_facebook_auth: ^3.3.2+2
  sign_in_with_apple: ^3.0.0
  firebase_dynamic_links: ^0.8.0
  intl: ^0.17.0
  time: ^1.2.0
  uuid: ^2.2.0
  kt_dart: ^0.7.0
  reorderables: ^0.2.12
  json_annotation: ^3.0.1
  crypto: ^2.1.5
  qr_code_scanner: ^0.2.1
  flutter_bloc: ^7.0.0
  dartz: ^0.9.0-dev.6
  flutter_hooks: ^0.8.0
  rxdart: ^0.23.1
  provider: ^5.0.0
  email_validator: ^2.0.1
  string_validator: ^0.3.0
  flutter_slidable: ^0.5.4
  auth_buttons: ^0.0.4
  another_flushbar: ^1.10.17
  implicitly_animated_reorderable_list: ^0.1.9
  font_awesome_flutter: ^8.11.0
  modal_bottom_sheet: ^1.0.0+1
  meta: ^1.1.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.1.1
  build_runner:
  freezed: ^0.12.6
  auto_route_generator: ^0.6.10
  injectable_generator: ^1.0.6
  json_serializable: ^3.2.5
flutter:
  uses-material-design: true
```
## Package versions after updating:
```
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^0.14.1
  injectable: ^1.2.2
  auto_route: ^1.0.2
  get_it: ^6.1.1
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  firebase_auth: ^1.1.0
  google_sign_in: ^5.0.1
  flutter_facebook_auth: ^3.3.2+2
  sign_in_with_apple: ^3.0.0
  firebase_dynamic_links: ^0.8.0
  intl: ^0.17.0
  time: ^2.0.0
  uuid: ^3.0.4
  kt_dart: ^0.9.0
  reorderables: ^0.4.1
  json_annotation: ^4.0.1
  crypto: ^3.0.1
  qr_code_scanner: ^0.4.0
  flutter_bloc: ^7.0.0
  dartz: ^0.10.0-nullsafety.1
  flutter_hooks: ^0.16.0
  rxdart: ^0.26.0
  provider: ^5.0.0
  email_validator: ^2.0.1
  string_validator: ^0.3.0
  flutter_slidable: ^0.6.0
  auth_buttons: ^1.0.0
  another_flushbar: ^1.10.17
  implicitly_animated_reorderable_list: ^0.4.0-dev+4
  font_awesome_flutter: ^9.0.0
  modal_bottom_sheet: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  build_runner: ^1.12.2
  freezed: ^0.14.0
  auto_route_generator: ^1.0.2
  injectable_generator: ^1.2.2
  json_serializable: ^4.0.0

flutter:
  uses-material-design: true
```

## `flutter run --verbose`
No errors are displayed in the logs. I captured the logs with --verbose but they are pretty long. I can send them via pm.

## `flutter analyze`
No Issues found

## `flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale de-DE)
    • Flutter version 2.2.3 at /Users/jonaskuschel/Developer/flutter
    • Framework revision f4abaa0735 (vor 6 Tagen), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/jonaskuschel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
```
