### ISSUE TITLE
Error running on iPhone. IOS 14.6 

### ISSUE THREAD

**Issue by Gastrolize** [flutter/flutter#86123]
Hello,

if I try to run my Project on my iPad or iPhone iOS 14.6 it crashes with the following error:

```console
[+30015 ms] Error launching application on iPhone.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

On my iPad Pro 14.6 does it work.

My Plugins: 

<details> 
<summary>pubspec.yaml</summary> 
	
```yaml
flutter:
    sdk: flutter
  smooth_star_rating: ^1.1.1
  http: ^0.13.0
  connectivity: ^3.0.2
  flutter_screenutil: ^5.0.0+2
  google_sign_in: ^5.0.4
  shimmer: ^2.0.0
  flutter_facebook_login: ^3.0.0
  banners: ^0.3.0
  apple_sign_in: ^0.1.0
  device_info: ^2.0.0
  data_connection_checker: ^0.3.4
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.3.0
  firebase_crashlytics: ^2.0.1
  firebase_core: ^1.0.4
  firebase_storage: ^9.0.0
  firebase_auth: ^2.0.0
  geolocator: ^7.0.1
  location: ^4.1.1
  imei_plugin: ^1.2.0
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.6
  local_auth: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  overlay_support: ^1.2.1
  flutter_slidable: ^0.6.0
  keyboard_avoider: ^0.1.2
  uni_links: ^0.5.1
  flutter_statusbarcolor: ^0.2.3
  path_provider: ^2.0.1
  intl: ^0.17.0
  onesignal_flutter: ^3.0.0
  permission_handler: ^8.1.2
  map_launcher: ^2.1.1
  flutter_spinkit: ^5.0.0
  geocoder: ^0.2.1
  transformer_page_view: ^0.1.6
  pinput: ^1.0.0
  google_maps_webservice: ^0.0.18
  majascan: ^0.4.0
  mailer: ^5.0.0
  scroll_to_index: ^2.0.0
  mollie: ^0.8.2
  carousel_pro: ^1.0.0
  flutter_cache_manager: ^3.1.2
  qr_flutter: ^4.0.0
  http_auth: ^1.0.0
  google_maps_flutter: ^2.0.1
  apple_maps_flutter: ^1.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_staggered_animations: "^1.0.0"
  dropdown_below: ^0.0.8
  quiver: ^3.0.1
  animated_widgets: ^1.1.0
  vibrate: ^0.0.4
  flutter_cupertino_localizations: ^1.0.1
  badges: ^2.0.1
  simple_animations: ^3.1.1
  url_launcher: ^6.0.2
  encrypt: ^5.0.0-beta.1
  uuid: ^3.0.0
  crypto: ^3.0.0
  plugin_platform_interface: ^2.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3`
```

</details>

Flutter Doctor:

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

I tried:

flutter clean
rm -rf Flutter/Framework

reinstalled Xcode
reinstalled flutter

made a restart on my Mac (Big Sur)

tried diff IDE, pod cache clean, cocoa pods ffi gems installed nothing worked.
