### ISSUE TITLE
Flutter iOS gives error on build ipa despite run works

### ISSUE THREAD

**Issue by bonfry** [flutter/flutter#86340]
Hi. I'm tryin to create ipa for publishing app to TestFlight, but , despite flutter run works very well, the ipa build give me error. I am executing flutter 2.2.3 on Mac OS Big Sur on Xcode 12.5.

## Steps to Reproduce

pubspec.yaml
```
name: levante
description: Levante Fregene app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  webview_flutter: ^2.0.9
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^0.5.1
  flutter_svg: ^0.22.0
  permission_handler: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Lota
      fonts:
        - asset: assets/fonts/LotaGrotesque-Black.ttf
          weight: 900
        - asset: assets/fonts/LotaGrotesque-BlackIt.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/LotaGrotesque-Bold.ttf
          weight: 700
        - asset: assets/fonts/LotaGrotesque-BoldIt.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/LotaGrotesque-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LotaGrotesque-SemiBoldIt.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/LotaGrotesque-Regular.ttf
        - asset: assets/fonts/LotaGrotesque-RegularIt.ttf
          style: italic
        - asset: assets/fonts/LotaGrotesque-Light.ttf
          weight: 300
        - asset: assets/fonts/LotaGrotesque-LightIt.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/LotaGrotesque-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LotaGrotesque-ExtraLightIt.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/LotaGrotesque-Thin.ttf
          weight: 100
        - asset: assets/fonts/LotaGrotesque-ThinIt.ttf
          weight: 100
          style: italic
```

Flutter build ipa --verbose
[https://drive.google.com/file/d/1OM3JZPPp-83SqrxpMDOfgZ21SWcxppyK/view?usp=sharing](log link)

Flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale it-IT)
    • Flutter version 2.2.3 at /Users/bonfry/flutter
    • Framework revision f4abaa0735 (12 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bonfry/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

</details>
