### ISSUE TITLE
NumberFormat nonbreakable space + FontWeight bug

### ISSUE THREAD

**Issue by jscti** [flutter/flutter#86352]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
Add a custom font in pubspec.yaml 
```
  fonts:
    - family: "Jost"
      fonts:
        - asset: "assets/fonts/google/Jost/Jost-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/google/Jost/Jost-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/google/Jost/Jost-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/google/Jost/Jost-Bold.ttf"
          weight: 700
    - family: "JostBold"
      fonts:
        - asset: "assets/fonts/google/Jost/Jost-Bold.ttf"
          weight: 700
```

3. Display text with :
```
Text(
  NumberFormat().format(10000),
  style: const TextStyle(
    fontFamily: 'Jost',
    fontWeight: FontWeight.bold,
  ),
)
```
(my Locale was Fr_FR)

**Expected results: (10<visible space>000) **
<img width="98" alt="Capture d’écran 2021-07-13 à 16 21 06" src="https://user-images.githubusercontent.com/1594035/125468693-082c87ce-2cb3-4671-ac6d-0bb9f74e7e7c.png">

**Actual results:**
<img width="94" alt="Capture d’écran 2021-07-13 à 16 20 55" src="https://user-images.githubusercontent.com/1594035/125468794-b6047c69-cabf-4597-bba4-7b06e1a23696.png">
=> space separator was swallowed

So :
 - Number format outputs non breakable spaces
 - When using fontWeight to override the FontWeight, flutter chooses the right font variant file from pubspec.yaml BUT inject somehow a bug by not respecting the letter spacing (here non secable spaces)
 - This can be verified easily because the output is as expected (visible space) when using : 
 ```
Text(
  NumberFormat().format(10000).toString(),
  style: const TextStyle(
    fontFamily: 'JostBold'
  ),
)
```
- So this bug seems to prevent the use of FontWeight totally for me, and I must use fontFamily to properly switch font variant

Video showing the problem :
- step 1 : `fontFamily:'Jost'` = ok
- step 2 : `fontFamily:'Jost', fontWeight: FontWeight.bold` = KO
- step 3: `fontFamily:'JostBold'` = ok

https://user-images.githubusercontent.com/1594035/125472587-4f290d02-f3f2-45f9-b7c3-bc841ede1663.mov

Or Am i missing something ? Thanks :)

<details>
 ```
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (5 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```
</details>
