### ISSUE TITLE
GitHub Actions and remote git dependencies

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [flutter/flutter#86420]
I have a dependency that uses git, i.e.:

```
dependencies:
  package1:
    git:
      url: git://github.com/flutter/packages.git
      path: packages/package1
```

Locally, it is working perfectly, but in GitHub Actions, it says it can't find the `pubspec.yaml` of that dependency.

I tried to add a personal access token to the `checkout` action, but it doesn't work.
