### ISSUE TITLE
Image.network Crash with iOS 10.x.x

### ISSUE THREAD

**Issue by WilliamMaybe** [flutter/flutter#86472]
Our app crashes on launch for users with iOS 10.3.x on iphone 5/6s/7 and ipad 4. I initially thought it is the same as #73971  but I'm not sure they are related after looking at all logs. There are cases where users pass the initial screen after network requests, before the app crashes.

Crash log:
```
Thread 19 Crashed:: DartWorker  Dispatch queue: trust
0   libobjc.A.dylib               	0x0000000110085acb objc_msgSend + 11
1   com.apple.Security            	0x00000001160e1b46 validate_array_of_items + 238
2   com.apple.Security            	0x00000001160e3546 SecTrustValidateInput + 45
3   com.apple.Security            	0x00000001160e3d65 __SecTrustEvaluateIfNecessary_block_invoke_2 + 21
4   libsystem_trace.dylib         	0x0000000116566fad _os_activity_initiate_impl + 53
5   com.apple.Security            	0x00000001160e3d49 __SecTrustEvaluateIfNecessary_block_invoke + 276
6   libdispatch.dylib             	0x00000001162a2792 _dispatch_client_callout + 8
7   libdispatch.dylib             	0x00000001162873de _dispatch_barrier_sync_f_invoke + 126
8   com.apple.Security            	0x00000001160e0d5b SecTrustEvaluateIfNecessary + 616
9   com.apple.Security            	0x00000001160e1211 SecTrustEvaluate + 62
10  io.flutter.flutter            	0x00000001122414e6 dart::bin::TrustEvaluateHandler(long long, _Dart_CObject*) + 182
11  io.flutter.flutter            	0x000000011238b51e dart::NativeMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >) + 206
12  io.flutter.flutter            	0x0000000112389403 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) + 307
13  io.flutter.flutter            	0x0000000112389a26 dart::MessageHandler::TaskCallback() + 470
14  io.flutter.flutter            	0x0000000112482b78 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) + 344
15  io.flutter.flutter            	0x0000000112482e1d dart::ThreadPool::Worker::Main(unsigned long) + 93
16  io.flutter.flutter            	0x000000011240374f dart::ThreadStart(void*) + 159
17  libsystem_pthread.dylib       	0x000000011664c109 _pthread_start + 148
18  libsystem_pthread.dylib       	0x0000000116647b8b thread_start + 15
```

```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.4 20F71 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.0.2 at /Users/maybe/Desktop/Flutter/flutter
    • Framework revision 8962f6dc68 (4 months ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/maybe/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
```

</details>

<code>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            if (_counter > 1)
              Image.network(
                  'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fbpic.588ku.com%2Felement_origin_min_pic%2F16%2F07%2F06%2F17577cd55945262.jpg%21r650&refer=http%3A%2F%2Fbpic.588ku.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1628911948&t=596bcc2d64732fce717e04d5a512eb9c'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


```

</code>

**Comment by WilliamMaybe** [comment]
pubspec.yaml:

```
name: demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
