### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code" Failed to codesign App.framework/App: resource fork, Finder information, or similar detritus not allowed / white screen while running on physical device on IOS

### ISSUE THREAD

**Issue by jay2jp** [flutter/flutter#87193]
I left a comment on #80978 but that issue is a bit older and closed so I decided to bring it up here .Basically what happens is I get hit with a Command PhaseScriptExecution error while trying to use ```flutter run -t (my main file) -v ``` but when I build it with ``` flutter build ios -t (my main file) ``` it builds fine but does not run from the terminal . If I run that build in Xcode on a simulator (iPhone 11) It runs fine but the moment I try to run it on my physical device (iPhone 10) it gets stuck on a white screen. and then if I archive that build and send it to my testers the app crashes on launch. Below is the comment I left on #80978. 

I've been dealing with this issue for a while now and I'm on the most up-to-date version of flutter. going through my logs i think it's related to the issue #64502. I tried adding the ```xattr -r -d com.apple.FinderInfo .``` But that didn't work and I don't think it was relevant due to being on version 2.2.3. I should probably add that I've been working on this app since flutter 1.4 ish so it does not include sound null safety. 

 

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (1 available)
    ! Error: Jay2j’s iPhone is not connected. Xcode will continue when Jay2j’s iPhone is connected. (code -13)

```

Packages
```
dependencies:
  charts_flutter: ^0.10.0
  flutter_animation_progress_bar: ^1.0.5
  menu_button: ^1.4.2+1
  simple_tooltip: ^0.1.14
  flutter_slidable: ^0.5.7
  flutter:
    sdk: flutter
  polygon_clipper: ^1.0.2
  cupertino_icons: ^0.1.2
  outline_material_icons: ^0.1.1
  get_it: ^4.0.2
  font_awesome_flutter: ^8.7.0
  carousel_pro: ^1.0.0
  flutter_screenutil: ^1.1.0
  email_validator: '^1.0.0'
  http: ^0.13.3
  sembast: ^2.4.10+4
  double_back_to_close_app: ^0.1.1
  path: ^1.7.0
  shared_preferences: ^0.5.3+4
  flushbar: ^1.8.2
  passwordfield: ^0.0.2
  json_annotation: ^4.0.0
  pin_code_text_field: ^1.3.7
  fluttertoast: ^3.1.2  
  intl: ^0.17.0
  flutter_custom_clippers: ^1.0.4
  bottom_sheet_stateful: ^0.1.1
  rflutter_alert: ^1.0.3
  firebase_crashlytics: ^2.0.0
  firebase_dynamic_links: ^0.5.0+11
  firebase_auth: ^1.0.2
  firebase_remote_config: ^0.10.0
  firebase_analytics: ^8.0.0
  dropdownfield: ^1.0.3
  grouped_buttons: ^1.0.4
  progress_dialog: ^1.2.0
  flutter_sticky_header: ^0.4.0
  flutter_pagewise: ^1.2.3
  material_design_icons_flutter: ^3.2.4495
  auto_size_text: ^2.1.0
  avatar_glow: ^1.0.0
  url_launcher: ^6.0.4
  html: ^0.15.0
  percent_indicator: "^2.1.1"
  date_format: ^1.0.8
  flutter_dash: ^0.0.1
  open_file: ^3.0.1
  flutter_full_pdf_viewer: ^1.0.4
  path_provider:  ^2.0.0
  geolocator: ^5.1.3
  package_info: ^2.0.2
  geocoder: ^0.2.1
  google_maps_webservice: ^0.0.20-nullsafety.5 
  geocoding: ^2.0.0
  flutter_spinkit: ^2.1.0
  flutter_google_places: ^0.2.5
  address_search_field: ^4.0.1
  google_maps_flutter: ^2.0.2
  background_fetch:
  permission_handler: ^6.0.1
  flutter_secure_storage: ^3.3.3 
  shimmer: ^1.1.1
  local_auth: ^1.1.6
  date_range_picker: ^1.0.7 
  plaid_flutter: ^1.1.1
  page_transition: ^1.1.6
  decimal: ^0.3.0
  firebase_messaging: ^10.0.0
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.3
  flutter_multi_formatter: ^1.1.8
  swipedetector: ^1.2.0
  #cached_network_image: ^2.5.1
  keyboard_actions: "^3.3.1+1"
  syncfusion_flutter_charts: ^18.3.48
  fl_chart: ^0.12.0
  ant_icons: ^1.0.0
  flutter_svg: ^0.19.3
  notifications_enabled: ^0.0.2
  flutter_native_timezone: ^1.0.4
  firebase_storage: ^8.0.1
  webview_flutter: ^2.0.8
  flutter_inappwebview: ^5.3.2

  
```

[verboseLogs.txt](https://github.com/flutter/flutter/files/6893255/verboseLogs.txt)
