### ISSUE TITLE
[web] TextOverflow.ellipsis adds unicode character “▯” (U+25AF) at the end of the text when using custom fonts

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#87402]
`TextOverflow.ellipsis` produces undesired output on Flutter Web when using a custom font.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update `main.dart` with the code sample

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      title: 'Ellipsis bug',
      theme: ThemeData(fontFamily: 'Prompt'),
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: 100,
            child: Text(
              "testzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
              overflow: TextOverflow.ellipsis,
            ),
          ),
        ),
      ),
    ),
  );
}
```
3. Add a font under the `font` directory, and update the pubspec.yaml to use the font.
```
  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Regular.ttf
```
[prompt-regular.zip](https://github.com/flutter/flutter/files/6911210/prompt-regular.zip)

4. Run the app with `flutter run -d chrome`
5. Observe that the text overflow produces a strange character at the end.

**Expected results:** 
The text gets the ellipsis at the end to indicate overflow.

**Actual results:** 
The text gets an ellipsis _and_ the unicode character “▯” (U+25AF) is appended to the ellipsis.

<img width="122" alt="Screenshot 2021-07-31 at 14 47 43" src="https://user-images.githubusercontent.com/23480364/127740332-664023ce-1998-439d-a1a4-e9182de95fe4.png">

I cannot reproduce this on a mobile device.

My font configuration:
```
  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Regular.ttf
        - asset: fonts/Prompt-Light.ttf
          weight: 300
        - asset: fonts/Prompt-Medium.ttf
          weight: 500
        - asset: fonts/Prompt-SemiBold.ttf
          weight: 600
        - asset: fonts/Prompt-Bold.ttf
          weight: 700
        - asset: fonts/Prompt-Black.ttf
          weight: 900
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-BE)
    • Flutter version 2.2.3 at /Users/navaronbracke/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • motorola one (mobile) • 192.168.0.150:5555 • android-arm64  • Android 10
      (API 29)
    • Chrome (web)          • chrome             • web-javascript • Google
      Chrome 92.0.4515.107

• No issues found!
```
