### ISSUE TITLE
Error when typing @ in TextFormField on Desktop Flutter

### ISSUE THREAD

**Issue by cindRoberta** [flutter/flutter#87641]
## Steps to Reproduce
In TextFormField when I type `@` on Desktop Flutter, I get the error message:

```
Another exception was thrown: A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a
different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests,
please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event:
KeyUpEvent#03a62(physicalKey: PhysicalKeyboardKey#7001f(usbHidUsage: "0x0007001f", debugName: "Digit 2"), logicalKey:
LogicalKeyboardKey#00032(keyId: "0x00000032", keyLabel: "2", debugName: "Digit 2"), character: null, timeStamp:
8:59:57.059000) and the recorded logical key LogicalKeyboardKey#00040(keyId: "0x00000040", keyLabel: "@", debugName: "At")
```

## pubscpec.yaml dependencies
```
  cupertino_icons: ^1.0.2
  get: ^4.3.4
  get_storage: ^2.0.3
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master
  cloud_firestore: ^2.4.0
  google_sign_in: ^5.0.7
  firebase_storage: ^10.0.1
  firebase_auth: ^3.0.1
```

## System informations
```
$ uname -r
5.13.5-100.fc33.x86_64

$ cat /etc/os-release
PRETTY_NAME="Fedora 33 (Workstation Edition)"
```

## Flutter informations
```
flutter --version
Flutter 2.5.0-2.0.pre.124 • channel master • https://github.com/flutter/flutter.git
Framework • revision b375059ee7 (29 hours ago) • 2021-08-02 19:55:03 -0700
Engine • revision 29f9df723f
Tools • Dart 2.14.0 (build 2.14.0-368.0.dev)
```
