### ISSUE TITLE
Running Palette Generator inside an async function freezes the app for a bit

### ISSUE THREAD

**Issue by Sheharyar566** [flutter/flutter#87842]
I was trying to use the palette generator plugin by flutter team. However, when I run the function, the UI freezes for two seconds or three. Here is how im trying to use it:
```
void _generateColorPalette(BuildContext context) async {
    try {
      if (this.imageData == null) {
        return;
      }

      setState(() {
        isLoading = true;
      });

      final PaletteGenerator _temp = await PaletteGenerator.fromImageProvider(
          MemoryImage(imageData as Uint8List));

      setState(() {
        isLoading = false;
        pallete = _temp.colors.toList();
      });

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Pallete Generated!'),
          behavior: SnackBarBehavior.floating,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(50.0),
          ),
        ),
      );
    } catch (e) {
      setState(() {
        isLoading = false;
      });
      print('Error occured while generating the palette: $e');
    }
  }
```

I also tried using it in a compute function but to no avail cause i get this error: 
```
Restarted application in 2,281ms.
I/Timeline( 4948): Timeline: Activity_launch_request time:96984061
W/Activity( 4948): Slow Operation: Activity com.example.glitter/.MainActivity onActivityResult took 187ms
I/flutter ( 4948): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 4948): The following _CastError was thrown while resolving an image:
I/flutter ( 4948): Null check operator used on a null value
I/flutter ( 4948):
I/flutter ( 4948): When the exception was thrown, this was the stack:
I/flutter ( 4948): #0      ImageProvider.resolveStreamForKey
I/flutter ( 4948): #1      ImageProvider.resolve.<anonymous closure>
I/flutter ( 4948): #2      ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure>
I/flutter ( 4948): #3      SynchronousFuture.then
I/flutter ( 4948): #4      ImageProvider._createErrorHandlerAndKey.<anonymous closure>
I/flutter ( 4948): #8      ImageProvider._createErrorHandlerAndKey
I/flutter ( 4948): #9      ImageProvider.resolve
I/flutter ( 4948): #10     PaletteGenerator.fromImageProvider
I/flutter ( 4948): #11     _ImageScreenState.generatePallete
I/flutter ( 4948): #12     _IsolateConfiguration.apply
I/flutter ( 4948): #13     _spawn.<anonymous closure>
I/flutter ( 4948): #14     _spawn.<anonymous closure>
I/flutter ( 4948): #15     Timeline.timeSync (dart:developer/timeline.dart:163:22)
I/flutter ( 4948): #16     _spawn
I/flutter ( 4948): #17     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
I/flutter ( 4948): (elided 4 frames from class _RawReceivePortImpl and dart:async)
I/flutter ( 4948):
I/flutter ( 4948): Image provider: MemoryImage(Uint8List#e9679, scale: 1.0)
I/flutter ( 4948): Image configuration: ImageConfiguration(devicePixelRatio: 1.0)
I/flutter ( 4948): Image key: MemoryImage(Uint8List#e9679, scale: 1.0)
I/flutter ( 4948): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4948): Error occured: TimeoutException: Timeout occurred trying to load from MemoryImage(Uint8List#e9679, scale: 1.0)
Reloaded 1 of 949 libraries in 1,408ms.
I/flutter ( 4948): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 4948): The following _CastError was thrown while resolving an image:
I/flutter ( 4948): Null check operator used on a null value
I/flutter ( 4948):
I/flutter ( 4948): When the exception was thrown, this was the stack:
I/flutter ( 4948): #0      ImageProvider.resolveStreamForKey
I/flutter ( 4948): #1      ImageProvider.resolve.<anonymous closure>
I/flutter ( 4948): #2      ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure>
I/flutter ( 4948): #3      SynchronousFuture.then
I/flutter ( 4948): #4      ImageProvider._createErrorHandlerAndKey.<anonymous closure>
I/flutter ( 4948): #8      ImageProvider._createErrorHandlerAndKey
I/flutter ( 4948): #9      ImageProvider.resolve
I/flutter ( 4948): #10     PaletteGenerator.fromImageProvider
I/flutter ( 4948): #11     _ImageScreenState.generatePallete
I/flutter ( 4948): #12     _IsolateConfiguration.apply
I/flutter ( 4948): #13     _spawn.<anonymous closure>
I/flutter ( 4948): #14     _spawn.<anonymous closure>
I/flutter ( 4948): #15     Timeline.timeSync (dart:developer/timeline.dart:163:22)
I/flutter ( 4948): #16     _spawn
I/flutter ( 4948): #17     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
I/flutter ( 4948): (elided 4 frames from class _RawReceivePortImpl and dart:async)
I/flutter ( 4948):
I/flutter ( 4948): Image provider: MemoryImage(Uint8List#53605, scale: 1.0)
I/flutter ( 4948): Image configuration: ImageConfiguration(devicePixelRatio: 1.0)
I/flutter ( 4948): Image key: MemoryImage(Uint8List#53605, scale: 1.0)
I/flutter ( 4948): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4948): Error occured: TimeoutException: Timeout occurred trying to load from MemoryImage(Uint8List#53605, scale: 1.0)
Reloaded 2 of 949 libraries in 1,273ms.
```

Heres how I was trying to use it in isolate:
```
  void _generateColorPalette(BuildContext context) async {
    try {
      if (this.imageData == null) {
        return;
      }

      setState(() {
        isLoading = true;
      });

      // final PaletteGenerator _temp = await PaletteGenerator.fromImageProvider(
      //     MemoryImage(imageData as Uint8List));

      final List<Color>? _temp =
          await compute(generatePalette, imageData as Uint8List);

      if (_temp == null) {
        return;
      }

      setState(() {
        isLoading = false;
        // pallete = _temp.colors.toList();
        pallete = _temp;
      });

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Pallete Generated!'),
          behavior: SnackBarBehavior.floating,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(50.0),
          ),
        ),
      );
    } catch (e) {
      setState(() {
        isLoading = false;
      });
      print('Error occured while generating the palette: $e');
    }
  }
```

and the isolated function:
```
Future<List<Color>?> generatePalette(Uint8List _image) async {
  try {
    final PaletteGenerator _generator =
        await PaletteGenerator.fromImageProvider(MemoryImage(_image));

    return _generator.colors.toList();
  } catch (e) {
    print('Error occured while generating palette in the isolate: $e');
  }
}
```

Any ideas on what might be missing?

## Details

**Target Platform: Android**
**Target OS version/browser: Android 10**
**Devices: Redmi 8**

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @Sheharyar566,
Thanks for filing the issue, please provide the output of `flutter doctor -v` along with [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), This helps to better investigate the issue.

Thank you.

**Comment by Sheharyar566** [comment]
ah sure... here it is...
```flutter doctor -v```
```
λ flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\Installations\AS\SDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = E:\Installations\AS\SDK
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category
```

and a minimum reproducable example..
```
import 'package:palette_generator/palette_generator.dart';

// Generates palette from image data
      final PaletteGenerator _temp = await PaletteGenerator.fromImageProvider(
          MemoryImage(widget.imageData));
```

The freeze effect is way stronger for large images... for example this one 

```Pubspec.yaml```
```
name: glitter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  palette: ^1.1.0+1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flex_color_picker: ^2.1.2
  palette_generator: ^0.3.0
  image_picker: ^0.8.2
  uuid: ^3.0.4
  another_flushbar: ^1.10.24
  image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
