### ISSUE TITLE
Targets of URI doesn't exist: 'package:timeago/timeago.dart'---import 'package:cached_network_image/cached_network_image.dart'---import 'package:path_provider/path_provider.dart';

### ISSUE THREAD

**Issue by Abderrezak-douba** [flutter/flutter#88006]
```dart
import 'package:MeeM/pages/header.dart';
import 'package:MeeM/pages/progress.dart';
import 'package:MeeM/pages/signup_page.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:timeago/timeago.dart';


class Comments extends StatefulWidget {
  final String postId;
  final String postOwnerId;
  final String postMediaUrl;

  Comments({
    this.postId,
    this.postOwnerId,
    this.postMediaUrl,
  });

  @override
  _CommentsState createState() => _CommentsState(
        postId: this.postId,
        postOwnerId: this.postOwnerId,
        postMediaUrl: this.postMediaUrl,
      );
}

class _CommentsState extends State<Comments> {
  TextEditingController commentController = TextEditingController();
  final String postId;
  final String postOwnerId;
  final String postMediaUrl;

  _CommentsState({
    this.postId,
    this.postOwnerId,
    this.postMediaUrl,
  });

  buildComments() {
    return StreamBuilder(
        stream: commentsRef
            .doc(postId)
            .collection('comments')
            .orderBy('createdTime', descending: false)
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return CircularProgress();
          }
        });
  }

  addComment() {
    commentsRef.doc(postId).collection('comments').add({
      'username': currentUser.username,
      'comment': commentController.text,
      'createdTime': createdTime,
      'avatarUrl': currentUser.photoUrl,
      'userId': currentUser.id,
    });
    commentController.clear();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: header(titleText: 'Comments'),
      body: Column(
        children: [
          Expanded(child: buildComments()),
          Divider(),
          ListTile(
            title: TextFormField(
              controller: commentController,
              decoration: InputDecoration(labelText: 'Write a Comment...'),
            ),
            trailing: OutlineButton(
              onPressed: addComment,
              borderSide: BorderSide.none,
              child: Text('Post'),
            ),
          ),
        ],
      ),
    );
  }
}

class Comment extends StatelessWidget {
  final String username;
  final String userId;
  final String avatarUrl;
  final String comment;
  final Timestamp createdTime;

  Comment({
    this.username,
    this.userId,
    this.avatarUrl,
    this.comment,
    this.createdTime,
  });

  factory Comment.fromDocument(DocumentSnapshot doc) {
    return Comment(
      username: doc['username'],
      userId: doc['userId'],
      avatarUrl: doc['avatarUrl'],
      comment: doc['comment'],
      createdTime: doc['createdTime'],
    );
  }
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ListTile(
          title: Text(comment),
          leading: CircleAvatar(
            backgroundImage: CachedNetworkImageProvider(avatarUrl),
          ),
          subtitle: Text(createdTime.toString()),
        ),
        Divider(),
      ],
    );
  }
}
```

I faced this problem while i did upgrade my dependencies and this mine :

```yaml
dependencies:
  flutter:
    sdk: flutter
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #image picker
  image_picker: ^0.8.2
  #video player
  video_player: ^2.1.10
  #file path
  file_picker: ^3.0.3
  #image cropper
  image_cropper: ^1.4.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.5
  geolocator: ^7.3.1
  uuid: ^3.0.4
  image: ^3.0.2
  animator: ^3.1.0
  flutter_svg: ^0.22.0
cupertino_icons: ^1.0.3
path_provider: ^2.0.2
timeago: ^3.1.0
cached_network_image: ^3.1.0
flutter_svg: ^0.19.3 
flutter_svg_provider: ^0.1.9
xfile: ^1.1.0
shared_preferences: ^2.0.6
async: ^2.8.1
getwidget: ^2.0.3
flutter_image_compress: ^1.1.0
```

someone can help me with

**Comment by jamesderlin** [comment]
As mentioned on https://stackoverflow.com/questions/68733814/, your `pubspec.yaml` file is misindented, and indentation matters.

**Comment by maheshmnj** [comment]
@Abderrezak-douba, Please share the output of `flutter doctor -v` and `flutter pub get` to better address the issue.

Thank you.

**Comment by Abderrezak-douba** [comment]
@maheshmnj , ok wait just minutes

**Comment by Abderrezak-douba** [comment]
@maheshmnj , this my flutter doctor -v output :
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\Abdou>flutter doctor -v
[ΓêÜ] Flutter (Channel stable, 2.2.3, on Microsoft Windows [version 6.1.7601],
    locale en-US)
    ΓÇó Flutter version 2.2.3 at C:\Users\Abdou\Desktop\abdou projects\flutter
    ΓÇó Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    ΓÇó Engine revision 241c87ad80
    ΓÇó Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)

    ΓÇó Android SDK at C:\Users\Abdou\AppData\Local\Android\sdk
    ΓÇó Platform android-30, build-tools 30.0.2
    ΓÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ΓÇó Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    X Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[ΓêÜ] Chrome - develop for the web
    ΓÇó Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[ΓêÜ] Android Studio (version 4.1.0)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio
    ΓÇó Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    ΓÇó Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    ΓÇó Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[ΓêÜ] IntelliJ IDEA Community Edition (version 2020.3)
    ΓÇó IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition
      2020.2.2
    ΓÇó Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    ΓÇó Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[ΓêÜ] VS Code (version 1.56.1)
    ΓÇó VS Code at C:\Users\Abdou\AppData\Local\Programs\Microsoft VS Code
    ΓÇó Flutter extension version 3.25.0

[ΓêÜ] Connected device (2 available)
    ΓÇó Chrome (web) ΓÇó chrome ΓÇó web-javascript ΓÇó Google Chrome 92.0.4515.1
07
    ΓÇó Edge (web)   ΓÇó edge   ΓÇó web-javascript ΓÇó Microsoft Edge 83.0.478.5
0

! Doctor found issues in 1 category.

**Comment by jamesderlin** [comment]
Did fixing the indentation in `pubspec.yaml` not fix your problem?

**Comment by Abderrezak-douba** [comment]
i am using VScode

**Comment by Abderrezak-douba** [comment]
@jamesderlin  nope

**Comment by maheshmnj** [comment]
@Abderrezak-douba  could you please share the output of `flutter pub get` as requested above.

**Comment by jamesderlin** [comment]
> @jamesderlin nope

Sorry for being skeptical, but it seems highly suspicious that the packages you have issues with are among the ones that are missing indentation in your `pubspec.yaml` file.  Note that your `pubspec.yaml` file also lists duplicate packages, so you also would need to remove duplicates after fixing the indentation.  Your `pubspec.yaml` file should look like:

```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #image picker
  image_picker: ^0.8.2
  #video player
  video_player: ^2.1.10
  #file path
  file_picker: ^3.0.3
  #image cropper
  image_cropper: ^1.4.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.5
  geolocator: ^7.3.1
  uuid: ^3.0.4
  image: ^3.0.2
  animator: ^3.1.0
  flutter_svg: ^0.22.0
  path_provider: ^2.0.2
  timeago: ^3.1.0
  cached_network_image: ^3.1.0
  flutter_svg_provider: ^0.1.9
  xfile: ^1.1.0
  shared_preferences: ^2.0.6
  async: ^2.8.1
  getwidget: ^2.0.3
  flutter_image_compress: ^1.1.0
```
