### ISSUE TITLE
[plugins] Inconsistent `implements` in federated plugins' pubspec.yaml

### ISSUE THREAD

**Issue by Sunbreak** [flutter/flutter#88222]
## Actual results

https://github.com/flutter/plugins/blob/master/packages/connectivity/connectivity_macos/pubspec.yaml#L13

```yaml
flutter:
  plugin:
    implements: connectivity_platform_interface
    platforms:
```

## Expected results

**Change to app-facing pacakge**

```yaml
flutter:
  plugin:
    implements: connectivity_platform
    platforms:
```

**Or remove it and all of below as well**

- path_provider
  - https://github.com/flutter/plugins/blob/master/packages/path_provider/path_provider_linux/pubspec.yaml#L13
  - https://github.com/flutter/plugins/blob/master/packages/path_provider/path_provider_macos/pubspec.yaml#L13
  - https://github.com/flutter/plugins/blob/master/packages/path_provider/path_provider_windows/pubspec.yaml#L13

- url_launcher
  - https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_macos/pubspec.yaml#L13
  - https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_windows/pubspec.yaml#L13
  - https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_linux/pubspec.yaml#L13

- shared_preferences
  - https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences_macos/pubspec.yaml#L13
  - https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences_windows/pubspec.yaml#L13
  - https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences_linux/pubspec.yaml#L13
