### ISSUE TITLE
Unable to load assets: Solved

### ISSUE THREAD

**Issue by abbiesgame** [flutter/flutter#88579]
First of all, **I tried writing assets in pubspec.yaml** 

```
 ...
 flutter:
   uses-material-design: true
   assets:
     - images/diamond.png

```

then, when I did "AssetImage("diamond.png")" it gave me "unable to load asset: diamond.png" 
So, I checked 
  - yaml indentation 
  - flutter doctor, flutter clean
and still not working.

Second, **I tried without using yaml**

`AssetImage("images/diamond.png")`

it still didn't work, although some pictures worked, such as, banana.jpg.

It's not working on any emulators.
