### ISSUE TITLE
My app crashes when downloading it from App store on ios 14

### ISSUE THREAD

**Issue by ahmed951** [flutter/flutter#88958]
I published an app on app store last week and it was approved from the app store.
I first download the app on my iPhone and it crashes when I open it before the splash screen and sometimes it opened the first page then crash.
I then try the app on my friends devices and it worked perfectly without any crashes but in this week I found that it crashes also on 6 or 7 devices from xCode reports.
My device's version is 14.0.1 and all the crashes are from ios 14 and the app is working without any problems on android.
This is an image from xCode.

![crashes2](https://user-images.githubusercontent.com/42003517/130792656-c6188bce-d045-4d51-847e-4bdb1f3ac4f5.jpg)

I have published the app from my friend's mac.

Running `flutter doctor -v`  on my laptop:
```
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19043.1165], locale en-US)
    • Flutter version 2.0.2 at D:\flutter
    • Framework revision 8962f6dc68 (6 months ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ju\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.59.1)
    • VS Code at C:\Users\ju\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!
```
Running `flutter doctor -v`  on my friend's mac:

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.3.1 20E241 darwin-x64, locale
    en-EG)
    • Flutter version 2.0.3 at /Users/ahmedalaa/Developer/flutter
    • Framework revision 4d7946a68d (5 months ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ahmedalaa/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

```

`Pubspec.yaml` :

```yaml


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^4.0.0
  device_info: ^2.0.0
  shared_preferences: ^2.0.5
  screen: ^0.0.5
  fluttertoast: ^8.0.3
  just_audio: ^0.9.5
  audio_video_progress_bar: ^0.6.2
  connectivity_plus: ^1.0.6
  data_connection_checker: ^0.3.4
  dio: any
  flutter_archive: ^4.0.1
  http: ^0.13.3
  flutter_html: ^2.0.0
  device_preview: ^0.7.4 
  rate_my_app: ^1.1.1
  share: ^2.0.4
  flutter_email_sender: ^5.0.2
  url_launcher: ^6.0.9
  scrollable_positioned_list: ^0.1.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logoIcon.png"
  image_path_ios: "assets/images/logoIconIOS.jpg"

```
