### ISSUE TITLE
[Web] [2.5] flutter build web error in release mode

### ISSUE THREAD

**Issue by dbbd59** [flutter/flutter#89740]
With Flutter 2.5 when running a build in release mode for web (in debug and profile mode everything works)
`flutter build web` or `flutter run -d chrome -release`
this error occurs:

**error**
```console
$ flutter build web

💪 Building with sound null safety 💪

Target dart2js failed: Exception: .dart_tool/flutter_build/84eec494fbee080600a8e4af15280059/main.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.14.0), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Null check operator used on a null value
#0      BinaryPrinter.visitExtension (package:kernel/binary/ast_to_binary.dart:2448:73)
#1      Extension.accept (package:kernel/ast.dart:1583:38)
#2      BinaryPrinter.writeExtensionNode (package:kernel/binary/ast_to_binary.dart:469:10)
#3      BinaryPrinter.writeExtensionNodeList (package:kernel/binary/ast_to_binary.dart:367:7)
#4      BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1048:5)
#5      Library.accept (package:kernel/ast.dart:553:38)
#6      BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:441:10)
#7      BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:746:9)
#8      BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:585:7)
#9      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#10     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:567:14)
#11     KernelLoaderTask.load.<anonymous closure>.<anonymous closure> (package:compiler/src/kernel/loader.dart:193:19)
#12     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#13     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart:186:9)
<asynchronous suspension>
#14     Compiler.runInternal (package:compiler/src/compiler.dart:281:29)
<asynchronous suspension>



Compiling lib/main.dart for the Web...                             11.5s
Exception: Failed to compile application for the Web.
```

<details> 
<summary>flutter doctor -v</summary> 
	
```console
$  flutter doctor -v      
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-IT)
    • Flutter version 2.5.0 at /Users/davidebolzoni/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (28 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/davidebolzoni/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63
```
	
</details>

**Comment by dbbd59** [comment]
**pubspec.yaml**

```
name: flutter_web_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_popup_menu: ^1.0.0
  bloc: ^7.1.0
  easy_localization: ^3.0.0
  flutter_bloc: ^7.2.0
  flutter_dotenv: ^5.0.2
  flutter_json_viewer: ^1.0.1
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  http: ^0.13.3
  injectable: ^1.5.0
  json_serializable: ^5.0.0
  layout: ^1.0.2
  provider: ^6.0.0
  routemaster: ^0.10.0-dev2
  rxdart: ^0.27.0
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.1.0
  build_runner: ^2.1.2
  ficcanaso: ^2.0.7
  flutter_native_splash: ^1.2.3
  freezed: ^0.14.5
  injectable_generator: ^1.5.2
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/image/
    - assets/logo/
    - assets/translations/
```
