### ISSUE TITLE
flutter pub get error "user-info is not supported in url"

### ISSUE THREAD

**Issue by NaderGharibian** [flutter/flutter#89899]
hi there 👋
When I got the new version of Flutter 2.5.0. I got the following error while executing the `**flutter pub get**.`
I also removed the folder flutter cache. Again, my command gives an error.

_I'm up before the update. I did not have a problem in version 2.2.3. And it worked right_
# Error
**Running "flutter pub get" in Package-Identity...                
Error on line 17, column 9 of pubspec.yaml: Invalid description in the "company_identity" pubspec on the "company_base" dependency: user-info is not supported in url**
``` error
   ╷
17 │ ┌         name: company_base
18 │ │         url: http://michael:321@127.0.0.1:5000
19 │ │ 
20 │ │   # Value equality
21 │ │   equatable: ^2.0.3
   │ └──^
   ╵
```
pub get failed (65;    ╵)
Process finished with exit code 65

# pubspec.yaml

``` yaml

name: company_identity
description: test
version: 0.0.1
homepage: 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  company_base:
    hosted:
        name: company_base
        url: http://michael:321@127.0.0.1:5000


  equatable: ^2.0.3


  get:



  dartz: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

```
