### ISSUE TITLE
[image_picker] Android animated gif not working if maxWidth & maxHeight are set

### ISSUE THREAD

**Issue by PabloTortosaLopez** [flutter/flutter#90185]
## Steps to Reproduce

1. Run this example on Android
2. Tap on the floating action button
3. Select a GIF from the device
4. See GIF is not working

**`main.dart`**
```dart
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

final picker = ImagePicker();

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Uint8List? _image;

  void _pickImage() async {
    final image = await picker.pickImage(
      source: ImageSource.gallery,
      maxHeight: 2500,
      maxWidth: 2500,
    );
    if (image != null) {
      _image = await image.readAsBytes();
      setState(() {});
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: _image != null ? Image.memory(_image!) : SizedBox(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _pickImage,
        child: Icon(Icons.image),
      ),
    );
  }
}

```

**`pubspec.yaml`**
```yaml
name: my_app_gif
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  image_picker: ^0.8.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true


```

**Expected results:**
I would expect to see any GIF working as it happens on iOS.

**Actual results:**
GIF is not working if we set maxWidth & maxHeight on the pickImage method
