### ISSUE TITLE
Could not find package sky_services after updating local engine.

### ISSUE THREAD

**Issue by kartik1225** [flutter/flutter#90594]
I have built the engine locally and running the application with dependency_overrides but having issue while running.

## Steps to Reproduce

1. Compile the latest engine locally, [link](https://github.com/flutter/flutter/wiki/Compiling-the-engine).
2. Run the application with `dependency_overrides` in `pubspec.yaml`

## Error log

<details>
<summary>Error during application build</summary>

```
Running "flutter pub get" in package_name...
Because package_name depends on sky_services from path which doesn't exist (could not find package sky_services at "/Users/kartik/Code/experiments/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_services"), version solving failed.
pub get failed (66; Because package_name depends on sky_services from path which doesn't exist (could not find package sky_services at "/Users/kartik/Code/experiments/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_services"), version solving failed.)
```

### flutter doctor -v
```
[✓] Flutter (Channel master, 2.6.0-6.0.pre.171, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.6.0-6.0.pre.171 at /Users/kartik/ExternalLibs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 321c872ca7 (31 hours ago), 2021-09-22 02:38:06 -0400
    • Engine revision b0f3c0f7e4
    • Dart version 2.15.0 (build 2.15.0-127.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kartik/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Pixel 4a (mobile) • 0B291JEC201996 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

</details>

### pubspec.yaml

```
...

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^0.14.0+1
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.14.0+1
  gesture_x_detector: ^1.0.0
  undo: ^1.4.0
  matrix4_transform: ^2.0.0
  logger: ^1.1.0
  touchable: ^1.0.0

dependency_overrides:
  sky_engine:
    path: "/Users/kartik/Code/experiments/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_engine"
  sky_services:
    path: "/Users/kartik/Code/experiments/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_services"

dev_dependencies:
  flutter_test:
    sdk: flutter
...
```
