### ISSUE TITLE
Null safety issue in Codelab "Write a Flutter desktop application"

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#90746]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
---

Insted of filling out the form I rather explain:

Codelab "Write a Flutter desktop application" null safety issue in stage 5
https://codelabs.developers.google.com/codelabs/flutter-github-graphql-client?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F#4

Please add a section how to cope with this fact in the codelab that you might run into a null safety issue: 

```
PS C:\flutterprojects\github_graphql_client_test_1> flutter pub run build_runner build --delete-conflicting-outputs
Failed to build build_runner:build_runner:
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:build_runner_core
 - package:build_runner
 - package:build_config
 - package:build_daemon
 - package:code_builder

For solutions, see https://dart.dev/go/unsound-null-safety
/c:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:91:37: Error: Operator '[]' cannot be called on 'ArgResults?' because it is potentially null.
 - 'ArgResults' is from 'package:args/src/arg_results.dart' ('/C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/args-2.3.0/lib/src/arg_results.dart').
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
                                    ^
/c:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:91:49: Warning: Operand of null-aware operation '??' has type 'bool' which excludes null.
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
                                                ^
/c:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:101:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dynamic>' which excludes null.
 - 'StreamSubscription' is from 'dart:async'.
  await logListener?.cancel();
        ^
pub finished with exit code 1
PS C:\flutterprojects\github_graphql_client_test_1>
```

**Comment by RoarGronmo** [comment]
Found a temporary solution:

Change the dependencies in `pubspec.yaml` to

```
...
dependencies:
  flutter:
    sdk: flutter
  gql: ^0.13.0
  gql_exec: ^0.3.0
  gql_link: ^0.4.0
  gql_http_link: ^0.4.0
  http: ^0.13.3
  oauth2: ^2.0.0
  url_launcher: ^6.0.12
...
...
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  gql_build: ^0.2.0
  pedantic: ^1.11.1
  flutter_lints: ^1.0.4
...

```

You will still get some warnings, but no redliners anymore
