### ISSUE TITLE
iOS crash libc++abi.dylib std::__terminate(void (*)())  Fatal Exception: std::__1::system_error recursive_mutex lock failed: Invalid argument

### ISSUE THREAD

**Issue by BlakeWuh** [flutter/flutter#90783]
## Steps to Reproduce

1. I could not reproduce the crash.
2. It crash on some users' phone.

**Expected results:** 

won't crash

**Actual results:** 

```
 libc++abi.dylib
std::__terminate(void (*)()) 
 Fatal Exception: std::__1::system_error
recursive_mutex lock failed: Invalid argument
Crashed: io.flutter.1.ui
0   FirebaseCrashlytics            0x10144c434 FIRCLSProcessRecordAllThreads + 397 (FIRCLSProcess.c:397)
1   FirebaseCrashlytics            0x10144c818 FIRCLSProcessRecordAllThreads + 428 (FIRCLSProcess.c:428)
2   FirebaseCrashlytics            0x1014455a0 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3   FirebaseCrashlytics            0x10143fd1c __FIRCLSExceptionRecord_block_invoke + 218 (FIRCLSException.mm:218)
4   libdispatch.dylib              0x19d01a280 _dispatch_client_callout + 16
5   libdispatch.dylib              0x19cffd0f4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6   FirebaseCrashlytics            0x10143f4b4 FIRCLSExceptionRecord + 225 (FIRCLSException.mm:225)
7   FirebaseCrashlytics            0x10143f154 FIRCLSTerminateHandler() + 285 (FIRCLSException.mm:285)
8   libc++abi.dylib                0x1b0d03154 std::__terminate(void (*)()) + 16
9   libc++abi.dylib                0x1b0d05bec __cxa_get_exception_ptr + 30
10  libc++abi.dylib                0x1b0d05bac __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 130
11  libc++.1.dylib                 0x1b0cdd418 std::__1::__throw_system_error(int, char const*) + 88
12  libc++.1.dylib                 0x1b0cd2b4c std::__1::recursive_mutex::unlock() + 34
13  Flutter                        0x103ecd250 (Missing)
14  Flutter                        0x103eea2e0 (Missing)
15  Flutter                        0x103ee76d0 (Missing)
16  Flutter                        0x103ee02c0 (Missing)
17  Flutter                        0x103f83a94 (Missing)
18  Flutter                        0x1040a1db8 (Missing)
19  App                            0x109812488 Precompiled_Stub_CallAutoScopeNative + 80
20  App                            0x109881aa4 Precompiled_Paragraph__layout_15065589_2209 + 60
21  App                            0x109881e08 Precompiled_Paragraph_layout_2214 + 80
22  App                            0x1098ce568 Precompiled_TextPainter_layout_3557 + 616
23  App                            0x1098fb8e0 Precompiled_RenderParagraph__layoutText_368149678_4504 + 264
24  App                            0x1098fb788 Precompiled_RenderParagraph__layoutTextWithConstraints_368149678_4503 + 160
25  App                            0x10a59ada4 Precompiled_RenderParagraph_performLayout_52173 + 164
26  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
27  App                            0x1099be190 Precompiled_ChildLayoutHelper_layoutChild_7768 + 52
28  App                            0x1099be1e0 Precompiled_ChildLayoutHelper_layoutChild_layoutChild_7769 + 36
29  App                            0x1098cfd24 Precompiled_RenderFlex__computeSizes_742478290_3575 + 776
30  App                            0x10a5a3ab0 Precompiled_RenderFlex_performLayout_52216 + 124
31  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
32  App                            0x10a59b98c Precompiled_RenderConstrainedBox_performLayout_52179 + 164
33  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
34  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
35  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
36  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
37  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
38  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
39  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
40  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
41  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
42  App                            0x109910a74 Precompiled_RenderStack_layoutPositionedChild_4857 + 412
43  App                            0x10a5a6194 Precompiled_RenderStack_performLayout_52221 + 648
44  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
45  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
46  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
47  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
48  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
49  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
50  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
51  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
52  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
53  App                            0x10a59eb60 Precompiled__RenderLayoutBuilder_881188862_performLayout_52206 + 156
54  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
55  App                            0x1099be190 Precompiled_ChildLayoutHelper_layoutChild_7768 + 52
56  App                            0x1099be1e0 Precompiled_ChildLayoutHelper_layoutChild_layoutChild_7769 + 36
57  App                            0x1098d0318 Precompiled_RenderFlex__computeSizes_742478290_3575 + 2300
58  App                            0x10a5a3ab0 Precompiled_RenderFlex_performLayout_52216 + 124
59  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
60  App                            0x1099be190 Precompiled_ChildLayoutHelper_layoutChild_7768 + 52
61  App                            0x1099be1e0 Precompiled_ChildLayoutHelper_layoutChild_layoutChild_7769 + 36
62  App                            0x109916d4c Precompiled_RenderStack__computeSize_765419958_4936 + 632
63  App                            0x10a5a5f90 Precompiled_RenderStack_performLayout_52221 + 132
64  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
65  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
66  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
67  App                            0x1099bc3c0 Precompiled_MultiChildLayoutDelegate_layoutChild_7706 + 132
68  App                            0x10a8e9ef4 Precompiled__ScaffoldLayout_652420462_performLayout_64328 + 1504
69  App                            0x1099bc1bc Precompiled_MultiChildLayoutDelegate__callPerformLayout_737472081_7704 + 328
70  App                            0x10a59b734 Precompiled_RenderCustomMultiChildLayoutBox_performLayout_52177 + 172
71  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
72  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
73  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
74  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
75  App                            0x10a59c370 Precompiled__RenderCustomClip_753160605_performLayout_52187 + 56
76  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
77  App                            0x10a59cb40 Precompiled__RenderProxyBox_RenderBox_RenderObjectWithChildMixin_RenderProxyBoxMixin_753160605_performLayout_52193 + 144
78  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
79  App                            0x1099be190 Precompiled_ChildLayoutHelper_layoutChild_7768 + 52
80  App                            0x1099be1e0 Precompiled_ChildLayoutHelper_layoutChild_layoutChild_7769 + 36
81  App                            0x109916d4c Precompiled_RenderStack__computeSize_765419958_4936 + 632
82  App                            0x10a5a5f90 Precompiled_RenderStack_performLayout_52221 + 132
83  App                            0x10a6078e0 Precompiled_RenderObject_layout_53856 + 1020
84  App                            0x1099bc3c0 Precompiled_MultiChildLayoutDelegate_layoutChild_7706 + 132
85  App                            0x10a8e9ef4 Precompiled__ScaffoldLayout_652420462_performLayout_64328 + 1504
86  App                            0x1099bc1bc Precompiled_MultiChildLayoutDelegate__callPerformLayout_737472081_7704 + 328
87  App                            0x10a59b734 Precompiled_RenderCustomMultiChildLayoutBox_performLayout_52177 + 172
88  App                            0x1099c9bd0 Precompiled_RenderObject__layoutWithoutResize_750266271_7989 + 56
89  App                            0x1099c9b44 Precompiled_PipelineOwner_flushLayout_7988 + 520
90  App                            0x1099c9050 Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_SchedulerBinding_ServicesBinding_PaintingBinding_SemanticsBinding_RendererBinding_311399801_drawFrame_7978 + 52
91  App                            0x1099c8b18 Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_SchedulerBinding_ServicesBinding_PaintingBinding_SemanticsBinding_RendererBinding_WidgetsBinding_311399801_drawFrame_7969 + 188
92  App                            0x1099c8834 Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_SchedulerBinding_ServicesBinding_PaintingBinding_SemanticsBinding_RendererBinding_311399801__handlePersistentFrameCallback_736452173_7966 + 32
93  App                            0x1099c87fc Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_SchedulerBinding_ServicesBinding_PaintingBinding_SemanticsBinding_RendererBinding_311399801__handlePersistentFrameCallback_736452173__handlePersistentFrameCallback_736452173_7965 + 44
94  App                            0x1098aa434 Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_SchedulerBinding_311399801__invokeFrameCallback_774222615_2981 + 104
95  App                            0x1098aa33c Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_SchedulerBinding_311399801_handleDrawFrame_2980 + 684
96  App                            0x1098aa070 Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_SchedulerBinding_311399801__handleDrawFrame_774222615_2979 + 292
97  App                            0x1098a9f34 Precompiled__WidgetsFlutterBinding_BindingBase_GestureBinding_SchedulerBinding_311399801__handleDrawFrame_774222615__handleDrawFrame_774222615_2978 + 40
98  App                            0x10982d29c Precompiled_____rootRun_4048458_513 + 200
99  App                            0x10982d388 Precompiled_____rootRun_4048458__rootRun_4048458_514 + 124
100 App                            0x10a930630 Precompiled__CustomZone_4048458_run_65372 + 176
101 App                            0x10a9346f0 Precompiled__CustomZone_4048458_runGuarded_65464 + 52
102 App                            0x10987117c Precompiled_____invoke_15065589_1860 + 156
103 App                            0x109874100 Precompiled_PlatformDispatcher__drawFrame_15065589_1910 + 40
104 App                            0x10987b970 Precompiled_____drawFrame_15065589_2081 + 32
105 App                            0x10987b9a4 Precompiled_____drawFrame_15065589__drawFrame_15065589_2082 + 24
106 App                            0x109812284 Precompiled_Stub_InvokeDartCode + 268
107 Flutter                        0x10408cf24 (Missing)
108 Flutter                        0x10408da34 (Missing)
109 Flutter                        0x10416db3c (Missing)
110 Flutter                        0x103f892f4 (Missing)
111 Flutter                        0x103ea611c (Missing)
112 Flutter                        0x103ba6f34 (Missing)
113 Flutter                        0x103e4df78 (Missing)
114 Flutter                        0x103e4fdf8 (Missing)
115 CoreFoundation                 0x19d361a30 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
116 CoreFoundation                 0x19d361634 __CFRunLoopDoTimer + 1004
117 CoreFoundation                 0x19d360b14 __CFRunLoopDoTimers + 324
118 CoreFoundation                 0x19d35aeb0 __CFRunLoopRun + 1912
119 CoreFoundation                 0x19d35a200 CFRunLoopRunSpecific + 572
120 Flutter                        0x103e4fcd4 (Missing)
121 Flutter                        0x103e4f6d8 (Missing)
122 libsystem_pthread.dylib        0x1e2cc2b70 _pthread_start + 288
123 libsystem_pthread.dylib        0x1e2cc7880 thread_start + 8
```

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/Shared/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

</details>

**Comment by TahaTesser** [comment]
Hi @BlakeWuh 
Unfortunately, the Flutter version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.

I kindly advise you to update to the latest Flutter `stable`, if you encounter the issue again, please comment below with the details from the latest stable, including steps to replicate the issue.

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?

Thank you

**Comment by BlakeWuh** [comment]
OK. We may upgrade flutter in about 2 weeks. After upgrading, if we encounter the issue again, I'll comment again

**Comment by brunovsiqueira** [comment]
I am having the exact same issue with several users this week. I am using Flutter 2.5.1 • channel stable.

@TahaTesser could you please provide some information on this?

**Comment by TahaTesser** [comment]
@brunovsiqueira 
Can you please provide your `flutter doctor -v`, your `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by brunovsiqueira** [comment]
**crash logs:**
```
Crashed: dart:io EventHandler
0  FirebaseCrashlytics            0x1061f8d88 FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x1061f9168 FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x1061f1f84 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x1061ec958 __FIRCLSExceptionRecord_block_invoke + 92
4  libdispatch.dylib              0x18998381c _dispatch_client_callout + 20
5  libdispatch.dylib              0x189992910 _dispatch_lane_barrier_sync_invoke_and_complete + 60
6  FirebaseCrashlytics            0x1061ec114 FIRCLSExceptionRecord + 216
7  FirebaseCrashlytics            0x1061ebdbc FIRCLSTerminateHandler() + 600
8  libc++abi.dylib                0x19e980fa0 std::__terminate(void (*)()) + 20
9  libc++abi.dylib                0x19e983c0c __cxa_get_exception_ptr + 34
10 libc++abi.dylib                0x19e983bb8 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 138
11 libc++.1.dylib                 0x19e95a3f0 std::__1::__throw_system_error(int, char const*) + 100
12 libc++.1.dylib                 0x19e94eb0c std::__1::mutex::try_lock() + 38
13 Flutter                        0x106ea2598 (Ausente)
14 Flutter                        0x107095374 (Ausente)
15 Flutter                        0x106f13b70 (Ausente)
16 Flutter                        0x10714e128 (Ausente)
17 Flutter                        0x1071dff64 (Ausente)
18 Flutter                        0x106fef524 (Ausente)
19 Flutter                        0x10701ccc4 (Ausente)
20 libsystem_pthread.dylib        0x1d5b20bfc _pthread_start + 320
21 libsystem_pthread.dylib        0x1d5b29758 thread_start + 8
```

**flutter doctor -v:**
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.2.3 20D91 darwin-x64, locale en-BR)
    • Flutter version 2.5.1 at /Users/vianabr/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vianabr/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61

! Doctor found issues in 1 category.

**pubspec.yaml:**

```
name: BTGPass
description: App do BTG+ business

version: 3.3.22

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  amplify_auth_cognito: 0.2.4
  amplify_core: 0.2.4
  amplify_flutter: 0.2.4
  another_flushbar: 1.10.23
  auto_size_text: 3.0.0-nullsafety.0
  auto_size_text_field: 1.0.1
  brasil_fields: 1.2.0
  carousel_slider: 4.0.0
  collection: 1.15.0
  connectivity_plus: 1.1.0
  cupertino_icons: 1.0.3
  currency_text_input_formatter: 2.1.3
  dartz: 0.10.0
  device_info_plus: 2.1.0
  dio: 4.0.0
  firebase_analytics: 8.3.2
  firebase_core: 1.6.0
  firebase_crashlytics: 2.2.1
  firebase_messaging: 10.0.7
  firebase_remote_config: 0.11.0
  fl_chart: 0.40.0
  flare_flutter: 3.0.1
  flutter:
    sdk: flutter
  flutter_device_type: 0.4.0
  flutter_dotenv: 5.0.2
  flutter_facetec:
    git:
      url: https://btgpactual.visualstudio.com/PME/_git/flutter_facetec
      ref: develop-downgrade
  flutter_keyboard_visibility: 5.0.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 4.1.0
  flutter_svg: 0.22.0
  fluttercontactpicker: 4.5.1
  infinite_scroll_pagination: 3.1.0
  intl: 0.17.0
  loader_overlay: 2.0.2+1
  local_auth: 1.1.6
  lottie: 1.2.0
  mask_text_input_formatter: 2.0.0
  modal_bottom_sheet: 2.0.0
  open_file: 3.2.1
  orquestra:
    git:
      url: https://btgpactual.visualstudio.com/PME/_git/Orquestra
      ref: develop
  otp: 3.0.1
  package_info_plus: 1.0.6
  path_provider: 2.0.2
  percent_indicator: 3.0.1
  permission_handler: 8.1.4+2
  provider: 5.0.0
  retry: 3.1.0
  rxdart: 0.27.2
  safe_device: 1.0.8
  share_plus: 2.1.4
  shimmer: 2.0.0
  sliver_tools: 0.2.5
  story: 0.5.1
  timezone: 0.8.0
  url_launcher: 6.0.8
  validators: 3.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
  mockito: 5.0.11
  test: 1.17.10

flutter_icons:
  android: true
  ios: true
  image_path: "icon/logo_app_store.png"

flutter:

  uses-material-design: true
  assets:
    - lib/shared/config/env/.dev.env
    - lib/shared/config/env/.uat.env
    - lib/shared/config/env/.prod.env
    - assets/svgs/
    - assets/svgs/open_finance/
    - assets/animations/splash.json
    - assets/animations/loading.json
    - assets/json/bank_list.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NeueHaasUnicaPro
      fonts:
        - asset: fonts/Linotype-Neue-Haas-Unica-Pro.otf
        - asset: fonts/Linotype-Neue-Haas-Unica-Pro-Thin.otf
        - asset: fonts/Linotype-Neue-Haas-Unica-Pro-Medium.otf
        - asset: fonts/Linotype-Neue-Haas-Unica-Pro-Bold.otf

    - family: Moderat
      fonts:
        - asset: fonts/Moderat-Regular.otf
          weight: 400
        - asset: fonts/Moderat-Light.otf
          weight: 300
        - asset: fonts/Moderat-Bold.otf
          weight: 700
        - asset: fonts/Moderat-Regular-Italic.otf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
```

**affected devices:**

14.7.1 - iPhone 12 Pro Max
15.0.0 - iPhone 12 Pro Max
14.7.1 - iPhone SE (2nd generation)
15.0.0 - iPhone 12 Pro
15.0.0 - iPhone XR
14.7.1 - iPhone 11 Pro Max
14.7.1 - iPhone 12 Pro
14.7.1 - iPhone 12
14.8.0 - iPhone 11


It is not possible to run it in the same OS Version of the affected devices.
