### ISSUE TITLE
flutter drive outputs both "Some tests failed" and "All tests passed"

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#90908]
**Expected results:**

`flutter drive` does not output "All tests passed." if any tests failed

**Actual results:**

```
I/flutter ( 9905): 00:17 +0 -1: (tearDownAll)
W/onsight.fritte( 9905): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/flutter ( 9905): 00:17 +1 -1: Some tests failed.
All tests passed.
```

This is effecting my integration tests, causing them to pass on github actions (which works via console output) when they should be failing

```
name: Integration Tests
on: [pull_request]

jobs:
  integration_test:
    timeout-minutes: 30
    runs-on: macos-latest
    strategy:
      matrix:
        filename: [
            "customer_flow.dart",
            "failed_login.dart"
        ]
    name: "Android"
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
          customVersion: '2.5.1'
      - name: "Build generated files"
        run: flutter clean && flutter pub get && flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: "${{ matrix.filename }}"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          script: "flutter drive --driver=test_driver/integration_test.dart --target=integration_test/${{ matrix.filename }} --android-emulator"
```
