### ISSUE TITLE
Execution failed for task ':video_player:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by jonahzheng** [flutter/flutter#90918]
video_player: 2.2.5

```
D:\flutter_prj\test\test>flutter run

Launching lib\main.dart on VIVO X20 in debug mode...
Running Gradle task 'assembleDebug'...
C:\Users\95\.gradle\caches\transforms-2\files-2.1\c965a91661fb2f55fa6404c083cbd784\jetified-exoplayer-common-2.14.1-api.jar(com/google/android/exoplayer2/util/Util.class): warning: Cannot find annotation method 'value()' in type 'EnsuresNonNull': class file for org.checkerframework.checker.nullness.qual.EnsuresNonNull not found
C:\Users\95\.gradle\caches\transforms-2\files-2.1\c965a91661fb2f55fa6404c083cbd784\jetified-exoplayer-common-2.14.1-api.jar(com/google/android/exoplayer2/util/Util.class): warning: Cannot find annotation method 'value()' in type 'EnsuresNonNull'
error: warnings found and -Werror specified
1 error
2 warnings

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':video_player:compileDebugJavaWithJavac'.
```

```
PS D:\flutter_prj\test\test>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.60.2)
[√] Connected device (2 available)
```

**Comment by danagbemava-nc** [comment]
Hi @jonahzheng, I attempted to reproduce this issue with the `video_player` example, however, the projects runs just fine for me. 

Is there any more additional information you can provide? 

Also, please provide the full output of `flutter run -v`.

I suspect that the issue might be coming from your `.gradle` cache, so if possible, try to clear your gradle cache and clean the project and rerun it, please make sure you have a stable internet connection when you run the project again.

Thank you

**Comment by jonahzheng** [comment]
hi @danagbemava-nc 
modify，
```
group 'io.flutter.plugins.videoplayer'
version '1.0-SNAPSHOT'
def args = ["-Xlint:deprecation","-Xlint:unchecked","-Werror"]
```
to

```
group 'io.flutter.plugins.videoplayer'
version '1.0-SNAPSHOT'
def args = ["-Xlint:deprecation","-Xlint:unchecked"]
```
the demo projects can run.

**the demo' pubspes.yaml**
```
name: test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  permission_handler: ^8.1.3
  video_player: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

**D:\flutter_prj\test\test>flutter doctor -v**

```

[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 2.5.1 at D:\flutter_sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (12 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
    • Pub download mirror http://mirrors.cnnic.cn/dart-pub
    • Flutter download mirror http://mirrors.cnnic.cn/flutter

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\PlatformSDKs\android-sdk-windows
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\PlatformSDKs\android-sdk-windows
    • ANDROID_SDK_ROOT = D:\PlatformSDKs\android-sdk-windows
    • Java binary at: C:\Program Files\Java\jdk1.8.0_25\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at E:\tools\IntelliJ IDEA 2021.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (2 available)
    • VIVO X20 (mobile) • 127.0.0.1:7555 • android-x86    • Android 6.0.1 (API 23)
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 94.0.4606.61

! Doctor found issues in 1 category.
```
