### ISSUE TITLE
Module 'google_maps_flutter' not found

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#91228]
I can build an archive through xcode, but I can't debug my app with "flutter run"

This is the output: 
```
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...                                              5.1s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      1,209ms
Xcode build done.                                           13.6s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:569ED4A8-EAA5-4C38-A56B-D7A954C4100A, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:74C4703C-6895-4073-917D-418D80934BD7, OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:6470EA6F-9ABB-4882-B797-6E15C13A77B3, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:5C07935F-48B4-4BCF-BDFD-492AAC66DD63, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:058B01B2-3FD6-450A-8D4C-79F286B44299, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:A549F47E-3874-4CAE-BC08-0C2D6FC7971F, OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:7B78FF7E-5EC9-4ECE-B7F6-20309BA87AD1, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:A1C84769-03D8-48A2-8700-B752DEB1B134, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:3588504A-BDA5-47AA-BF12-05776DE8A5A4, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:7FD12DFF-5DA3-46EE-B785-182369287B38, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:F6BD872E-28AA-4C07-97E0-09050F9E2275, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:F2C74116-B79D-439B-9160-136877221F19, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:1D475B40-9F0C-4ECA-A0D9-DA6D487705C6, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:65B3F9A3-F82F-4339-B809-BF906B4F2961, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:2579823C-8B8D-4613-8CA8-9C7556AA7EC2, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:F85CCA39-23C1-4F2E-BAB7-6EF06743C99C, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:E70C0022-62D3-4DBE-941D-55E2D2B0926F, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:1A2EBF14-6B49-4B41-ABFB-CF2B5224DF04, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:3BB898FB-FAD0-4569-8CFA-4BB0CEA30474, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:A4440BE9-8A3A-4D87-AE20-79A79B55D778, OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:EF43BF5C-8BF8-4B1B-9FA6-D81FC65528C8, OS:15.0, name:iPod touch (7th generation) }
    { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008103-0001458102A1001E }
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/threeofthem/Projects/clickapo/ios/Runner/GeneratedPluginRegistrant.m:60:9: fatal error: module 'google_maps_flutter' not found
    @import google_maps_flutter;
     ~~~~~~~^~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    /Users/threeofthem/Projects/clickapo/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
    range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Try' from project 'Pods')
    /Users/threeofthem/Projects/clickapo/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
    range of supported deployment target versions is 9.0 to 15.0.99. (in target 'PINOperation' from project 'Pods')
    /Users/threeofthem/Projects/clickapo/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
    range of supported deployment target versions is 9.0 to 15.0.99. (in target 'GCDWebServer' from project 'Pods')
    /Users/threeofthem/Projects/clickapo/ios/Pods/Pods.xcodeproj: warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'GCDWebServer'
    from project 'Pods')
    /Users/threeofthem/Projects/clickapo/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
    range of supported deployment target versions is 9.0 to 15.0.99. (in target 'FMDB' from project 'Pods')
    /Users/threeofthem/Projects/clickapo/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
    range of supported deployment target versions is 9.0 to 15.0.99. (in target 'PINCache' from project 'Pods')
    /Users/threeofthem/Projects/clickapo/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
    range of supported deployment target versions is 9.0 to 15.0.99. (in target 'HLSCachingReverseProxyServer' from project 'Pods')
    /Users/threeofthem/Projects/clickapo/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
    range of supported deployment target versions is 9.0 to 15.0.99. (in target 'GoogleUtilitiesComponents' from project 'Pods')
```

flutter doctor: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.6.0-12.0.pre.185, on macOS 11.3 20E217 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

• No issues found!
```

Podfile: 
```
$FirebaseAnalyticsWithoutAdIdSupport = true

$supportedVersion = '11.0'

platform :ios, $supportedVersion

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'vpn' do
  use_frameworks!
  use_modular_headers!
  pod 'OpenVPNAdapter', :git => 'https://github.com/ss-abramchuk/OpenVPNAdapter.git', :tag => '0.7.0'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=*]"] = "armv7"
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $supportedVersion
  end
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DELPOYMENT_TARGET'] = $supportedVersion
      if Gem::Version.new($supportedVersion) > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $supportedVersion
      end
    end
  end
end

```

pubspec.yaml: 
```
name: clickapo
description: Ihre Apotheken

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.7
  clickapo_rest_api:
    git:
      url: https://matan-ljubas:MEkFdyPtF9CxQLwe9fNh@bitbucket.org/sbetroisdorf/clickapo_rest_api.git
  intl: ^0.17.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  device_info_plus: ^2.2.0
  image_picker: ^0.8.4+2
  flutter_custom_tabs: ^1.0.3
  google_maps_flutter: ^2.0.11
  url_launcher: ^6.0.12
  uni_links: ^0.5.1
  firebase_core: ^1.7.0
  firebase_analytics: ^8.3.3
  speech_to_text: ^5.1.1
  location: ^4.3.0
  camera: ^0.9.4+1
  google_ml_kit: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  flutter_openvpn:
    git:
      url: https://matan-ljubas:MEkFdyPtF9CxQLwe9fNh@bitbucket.org/sbetroisdorf/vpn.git

flutter:
  
  uses-material-design: true
  
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/error/
    - assets/images/auth/ 
    - assets/images/nav_bar/
    - assets/images/home/
    - assets/images/cart/
    - assets/images/checkout/
    - assets/images/apofinder/
    
  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
    - family: Custom Icons
      fonts:
        - asset: assets/fonts/Custom-Icons.ttf
```

We should definitely get together and meet sometimes considering how much time I'm spending here with you.
