### ISSUE TITLE
Huge crash from Google Play Console when upgrade flutter from 2.0.6 to 2.5.2 on Android

### ISSUE THREAD

**Issue by dodatw** [flutter/flutter#91962]
We face huge crash from Google Play Console when upgrade flutter from 2.0.6 to 2.5.2.
We never see this issue at Flutter 2.0.6.
I cannot reproduce this from my side.

The crash info:
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
libflutter.so!libflutter.so (offset 0x2cd000)

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.youcam.videoeditor.reface.makeup <<<

backtrace:
  #00  pc 0000000000796360  /data/app/com.youcam.videoeditor.reface.makeup--fE7q_x5tDm4rdaI1HDxMA==/lib/arm64/libflutter.so!libflutter.so (offset 0x2cd000)
  #00  pc 00000000004f7710  /data/app/com.youcam.videoeditor.reface.makeup--fE7q_x5tDm4rdaI1HDxMA==/lib/arm64/libflutter.so!libflutter.so (offset 0x2cd000)
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale zh-Hant-TW)
    • Flutter version 2.5.2 at /Users/rdapp/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 周前), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/rdapp/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 11.6 20G165 darwin-x64
    ! Error: Tommy’s iPhone is not connected. Xcode will continue when Tommy’s iPhone is connected. (code -13)
```
</details>

<details>
<summary>pubspec.yaml</summary>

```
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: ^1.1.0                             #BSD
  firebase_analytics: ^8.3.0                        #BSD
  firebase_crashlytics: ^2.0.2                      #BSD
  firebase_dynamic_links: ^2.0.8                    #BSD
  firebase_performance: ^0.7.0+8                    #BSD
  in_app_purchase: ^1.0.9                           #BSD
  cupertino_icons: ^1.0.3                           #MIT
  bot_toast: ^4.0.1                                 #Apache 2.0
  modal_bottom_sheet: ^2.0.0                        #MIT
  device_info: ^2.0.0                               #BSD
  logger: ^1.0.0                                    #MIT
  adaptive_dialog: ^0.10.0+5                        #MIT
  permission_handler: ^8.2.5                        #MIT
  shared_preferences: ^2.0.5                        #BSD
  sprintf: ^6.0.0                                   #BSD
  video_player: ^2.1.1                              #BSD
  path_drawing: ^0.5.0                              #MIT
  image_picker: ^0.8.4+2                            #Apache 2.0
  path_provider: ^2.0.1                             #BSD
  http: ^0.13.3                                     #BSD
  flutter_native_timezone: ^2.0.0                   #Apache 2.0
  xml2json: ^5.1.0                                  #MIT
  sqflite: ^2.0.0+3                                 #MIT
  path: ^1.8.0                                      #BSD
  json_annotation: ^4.0.1                           #BSD
  scrollable_positioned_list: ^0.2.0-nullsafety.0   #BSD
  flutter_inappwebview: ^5.3.2                      #Apache 2.0
  package_info: ^2.0.0                              #BSD
  percent_indicator: ^3.0.1                         #BSD
  image: ^3.0.2                                     #Apache 2.0
  device_apps: ^2.1.1                               #Apache 2.0
  url_launcher: ^6.0.3                              #BSD
  uuid: ^3.0.4                                      #MIT
  uni_links: ^0.5.1                                 #BSD
  connectivity: ^3.0.3                              #BSD
  synchronized: ^3.0.0                              #BSD
  archive: ^3.1.2                                   #Apache 2.0
  storage_space: ^1.0.0+2                           #BSD
  collection: ^1.15.0                               #BSD
  ios_utsname_ext: ^2.0.0                           #MIT
  auto_size_text: ^3.0.0-nullsafety.0               #MIT
  dio: ^4.0.0                                       #MIT
  pretty_json: ^2.0.0                               #BSD
  flutter_cache_manager: ^3.1.2                     #MIT
  enum_to_string: ^2.0.1                            #MIT
  cached_network_image: ^3.1.0                      #MIT
  in_app_review: ^2.0.2                             #MIT
  lottie: ^1.0.1                                    #MIT
  share: ^2.0.1                                     #BSD
  flutter_local_notifications: ^5.0.0+3             #BSD
  vibration: ^1.7.4-nullsafety.0                    #BSD
  wakelock: ^0.5.3+3                                #BSD
  draggable_scrollbar: ^0.1.0                       #MIT
  system_info: ^1.0.0                               #BSD
  appsflyer_sdk: ^6.2.4+4-nullsafety                #MIT
  facebook_app_events: ^0.12.0                      #Apache 2.0
  in_app_update: ^2.0.0                             #MIT
  open_store: ^0.2.4                                #MIT
  country_codes: ^2.0.1                             #MIT
  cpu_reader: ^3.0.0                                #MIT
  outline_gradient_button: ^2.0.0+1                 #BSD

  notification_reactor:                             #BSD
    path: ./packages/notification_reactor/
  photo_manager:                                    #Apache 2.0
    path: ./packages/photo_manager-0.5.8/
  photo_widget:                                     #Apache 2.0
    path: ./packages/photo_widget-0.0.3/

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  flutter_driver:
  #    sdk: flutter
  test: ^1.16.5
  json_serializable: ^4.1.1           #BSD
  build_runner: ^2.0.2                #BSD
  flutter_launcher_icons: ^0.9.0      #MIT
  mockito: ^5.0.15                    #Apache 2.0
  flutter_lints: ^1.0.4

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```
</details>
