### ISSUE TITLE
Flutter web icons not showing in aws amplify hosting

### ISSUE THREAD

**Issue by ianvillamia** [flutter/flutter#92150]
## Steps to Reproduce

1. Create an AWS amplify project and add your repo there for hosting
2.  Use this build setting below
3.  Deploy
```
      version: 1
      frontend:
        phases:
          preBuild:
            commands:
            - git clone https://github.com/flutter/flutter.git -b stable --depth 1
            - export PATH="$PATH:`pwd`/flutter/bin"
          # IMPORTANT - Please verify your build commands
          build:
            commands: 
            - flutter build web -t ./lib/main.dart
        artifacts:
          # IMPORTANT - Please verify your build output directory
          baseDirectory: build/web
          files:
            - '**/*'
        cache:
          paths: []
```

**Results:** 

![Screen Shot 2021-10-20 at 10 42 22 PM](https://user-images.githubusercontent.com/25190455/138115484-fa9b2466-e688-45f6-9fa4-b46635308d15.png)

<details>
<summary>Code Sample</summary>

```dart


Wrap(
                          children: quickLinks.map((e) {
                            return InkWell(
                              onTap: () {
                                //todo add links
                                log(e.title);
                           
                              },
                              child: Padding(
                                padding: const EdgeInsets.only(right: 24),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    ClipOval(
                                      child: Material(
                                        color: ColorConstant.skyBlue,
                                        child: Padding(
                                          padding: const EdgeInsets.all(8.0),
                                          child: SizedBox(
                                            width: 48,
                                            height: 48,
                                            child: Icon(
                                              e.icon,
                                              color: Colors.white,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Padding(
                                      padding: const EdgeInsets.all(8.0),
                                      child: Text(
                                        e.title,
                                        textAlign: TextAlign.center,
                                        style: const TextStyle(
                                            color: Colors.black),
                                      ),
                                    )
                                  ],
                                ),
                              ),
                            );
                          }).toList(),
                        ),
```

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>
