### ISSUE TITLE
mac builds are taking significantly longer

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#92936]
1 hr 44 mins: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/12567/overview

vs 

10 mins: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/12559/overview

This started happening sometime yesterday:

![image](https://user-images.githubusercontent.com/1006071/139956815-18169a76-86c2-428b-bb5d-4b31c36d01e0.png)

This is on mac-host-engine, but i've seen this on other mac variants as well.

**Comment by keyonghan** [comment]
Seems Goma is not working correctly:
```
request: total=3962 success=3962 failure=0
 compiler_proxy: fail=0
 compiler_info: stores=0 store_dups=0 miss=0 fail=33
 goma: finished=0 cache_hit=0 local_cachehit=0 aborted=0 retry=0 fail=0
 fallback_in_setup:
  parse_fail=0 no_remote=24 http_disabled=0
  compiler_info_fail=3938 compiler_disabled=0 requested_by_user=0 update_required_files=0
 local: run=3962 killed=0 finished=3962
```
