### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by nicusbonannus** [flutter/flutter#92982]
Hi, I am facing the same issue that others developers have when trying to deploy my flutter app for App Store.
I read the others related issues, but I couldn't find a solution to my particular configuration.

I also run a deep search on my project looking for uiwebview references, but I didn't find anything.

I am running out of ideas, can you please help me to figure it out which package might be causing the problem?

Thanks in advance

This is my 
### flutter doctor -v : 
```
[✓] Flutter (Channel stable, 2.5.2, on Mac OS X 10.15.7 19H2 darwin-x64, locale es-AR)
    • Flutter version 2.5.2 at /Users/eryxdev/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (5 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/eryxdev/Library/Android/sdk
    • Platform android-29, build-tools 32.0.0-rc1
    • ANDROID_HOME = /Users/eryxdev/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69
```

This is the content from my 
### pubspec.yaml:
```

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player:

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  provider: ^6.0.1
  device_info: ^2.0.2
  package_info: ^2.0.2
  get_it: ^7.2.0
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.8
  permission_handler: ^8.1.4+2
  image_picker: ^0.8.3+2
  enum_to_string: ^2.0.1
  flutter_better_camera: ^1.0.2+1
  path_provider: ^2.0.6
  flutter_secure_storage: ^4.2.1
  location: ^4.1.1
  crypto: ^3.0.0
  archive: ^3.0.0
  intl: ^0.17.0
  esys_flutter_share: ^1.0.2
  event_bus: ^2.0.0
  video_thumbnail: ^0.4.3
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.12 #last
  flutter_email_sender: ^5.0.2
  webview_flutter: ^2.1.2 #last
  flutter_date_pickers: ^0.2.4
  gallery_saver: ^2.0.1
  linkwell: ^2.0.6
  imei_plugin: ^1.2.0 #last
  flutter_ffmpeg: ^0.4.0
  flat_icons_flutter: ^1.0.2
  image: ^3.0.2
  exif:
  flutter_exif_rotation: ^0.4.1
  flutter_twitter: ^1.1.3 #last
  geolocator: ^7.0.3
  flutter_switch: ^0.3.2 #last
  flutter_plugin_android_lifecycle: ^2.0.2
  social_share: ^2.1.1 #last
  youtube_player_flutter: ^8.0.0 #last
  smart_select: ^4.3.2
  csv: ^5.0.0
  share: ^2.0.1
  thumbnails: ^1.0.1 #last

dependency_overrides:
  intl: ^0.17.0
  path: 1.8.0-nullsafety
  clock: ^1.1.0-nullsafety
  path_provider: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

```

And this is the content of my 
### pubspec.lock:
```
packages:
  archive:
    dependency: "direct main"
    description:
      name: archive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.6"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.1"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  clock:
    dependency: "direct overridden"
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.0"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  cross_file:
    dependency: transitive
    description:
      name: cross_file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  crypto:
    dependency: "direct main"
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.1"
  csv:
    dependency: "direct main"
    description:
      name: csv
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.0"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  device_info:
    dependency: "direct main"
    description:
      name: device_info
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  device_info_platform_interface:
    dependency: transitive
    description:
      name: device_info_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  enum_to_string:
    dependency: "direct main"
    description:
      name: enum_to_string
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  esys_flutter_share:
    dependency: "direct main"
    description:
      name: esys_flutter_share
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  event_bus:
    dependency: "direct main"
    description:
      name: event_bus
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  exif:
    dependency: "direct main"
    description:
      name: exif
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  ffi:
    dependency: transitive
    description:
      name: ffi
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.2"
  flat_icons_flutter:
    dependency: "direct main"
    description:
      name: flat_icons_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_better_camera:
    dependency: "direct main"
    description:
      name: flutter_better_camera
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2+1"
  flutter_cupertino_localizations:
    dependency: "direct main"
    description:
      name: flutter_cupertino_localizations
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  flutter_date_pickers:
    dependency: "direct main"
    description:
      name: flutter_date_pickers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.6"
  flutter_email_sender:
    dependency: "direct main"
    description:
      name: flutter_email_sender
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.2"
  flutter_exif_rotation:
    dependency: "direct main"
    description:
      name: flutter_exif_rotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.1"
  flutter_ffmpeg:
    dependency: "direct main"
    description:
      name: flutter_ffmpeg
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"
  flutter_inappwebview:
    dependency: transitive
    description:
      name: flutter_inappwebview
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.3.2"
  flutter_localizations:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_plugin_android_lifecycle:
    dependency: "direct main"
    description:
      name: flutter_plugin_android_lifecycle
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  flutter_secure_storage:
    dependency: "direct main"
    description:
      name: flutter_secure_storage
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.1"
  flutter_switch:
    dependency: "direct main"
    description:
      name: flutter_switch
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_twitter:
    dependency: "direct main"
    description:
      name: flutter_twitter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  fluttertoast:
    dependency: "direct main"
    description:
      name: fluttertoast
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.0.8"
  gallery_saver:
    dependency: "direct main"
    description:
      name: gallery_saver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.2"
  geolocator:
    dependency: "direct main"
    description:
      name: geolocator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.7.1"
  geolocator_android:
    dependency: transitive
    description:
      name: geolocator_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  geolocator_apple:
    dependency: transitive
    description:
      name: geolocator_apple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.2"
  geolocator_platform_interface:
    dependency: transitive
    description:
      name: geolocator_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.6"
  geolocator_web:
    dependency: transitive
    description:
      name: geolocator_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  get_it:
    dependency: "direct main"
    description:
      name: get_it
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.2.0"
  html:
    dependency: transitive
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.0"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.4"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  image:
    dependency: "direct main"
    description:
      name: image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.8"
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.4+3"
  image_picker_for_web:
    dependency: transitive
    description:
      name: image_picker_for_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.4"
  image_picker_platform_interface:
    dependency: transitive
    description:
      name: image_picker_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.1"
  imei_plugin:
    dependency: "direct main"
    description:
      name: imei_plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.0"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.3"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.0"
  linkwell:
    dependency: "direct main"
    description:
      name: linkwell
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  location:
    dependency: "direct main"
    description:
      name: location
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.0"
  location_platform_interface:
    dependency: transitive
    description:
      name: location_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
  location_web:
    dependency: transitive
    description:
      name: location_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.10"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  mime:
    dependency: transitive
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  nested:
    dependency: transitive
    description:
      name: nested
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  package_info:
    dependency: "direct main"
    description:
      name: package_info
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  path:
    dependency: "direct overridden"
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0-nullsafety"
  path_provider:
    dependency: "direct main"
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  path_provider_windows:
    dependency: transitive
    description:
      name: path_provider_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  permission_handler:
    dependency: "direct main"
    description:
      name: permission_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.2.5"
  permission_handler_platform_interface:
    dependency: transitive
    description:
      name: permission_handler_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.7.0"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.4.0"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.2"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  process:
    dependency: transitive
    description:
      name: process
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.4"
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.1"
  rflutter_alert:
    dependency: "direct main"
    description:
      name: rflutter_alert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  share:
    dependency: "direct main"
    description:
      name: share
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  shared_preferences:
    dependency: "direct main"
    description:
      name: shared_preferences
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8"
  shared_preferences_linux:
    dependency: transitive
    description:
      name: shared_preferences_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  shared_preferences_macos:
    dependency: transitive
    description:
      name: shared_preferences_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  shared_preferences_platform_interface:
    dependency: transitive
    description:
      name: shared_preferences_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  shared_preferences_web:
    dependency: transitive
    description:
      name: shared_preferences_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  shared_preferences_windows:
    dependency: transitive
    description:
      name: shared_preferences_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  smart_select:
    dependency: "direct main"
    description:
      name: smart_select
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.2"
  social_share:
    dependency: "direct main"
    description:
      name: social_share
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  sprintf:
    dependency: transitive
    description:
      name: sprintf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"
  thumbnails:
    dependency: "direct main"
    description:
      name: thumbnails
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  url_launcher:
    dependency: "direct main"
    description:
      name: url_launcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.12"
  url_launcher_linux:
    dependency: transitive
    description:
      name: url_launcher_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  url_launcher_macos:
    dependency: transitive
    description:
      name: url_launcher_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  url_launcher_platform_interface:
    dependency: transitive
    description:
      name: url_launcher_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  url_launcher_web:
    dependency: transitive
    description:
      name: url_launcher_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  url_launcher_windows:
    dependency: transitive
    description:
      name: url_launcher_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  video_player:
    dependency: "direct main"
    description:
      name: video_player
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.6"
  video_player_platform_interface:
    dependency: transitive
    description:
      name: video_player_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.0"
  video_player_web:
    dependency: transitive
    description:
      name: video_player_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  video_thumbnail:
    dependency: "direct main"
    description:
      name: video_thumbnail
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.3"
  webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  webview_flutter_platform_interface:
    dependency: transitive
    description:
      name: webview_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  win32:
    dependency: transitive
    description:
      name: win32
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.10"
  xdg_directories:
    dependency: transitive
    description:
      name: xdg_directories
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  xml:
    dependency: transitive
    description:
      name: xml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.3.1"
  youtube_player_flutter:
    dependency: "direct main"
    description:
      name: youtube_player_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.0.0"
sdks:
  dart: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"
```
