### ISSUE TITLE
luci.swarming salt state failing on new mac machines

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#93078]
```
----------
          ID: /Library/LaunchDaemons/org.swarm.bot.plist
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'dict object' has no attribute 'swarming_py_version'
     Started: 13:14:50.544254
    Duration: 170.812 ms
     Changes:   
----------
          ID: org.swarm.bot
    Function: service.running
      Result: False
     Comment: One or more requisite failed: luci/swarming./Library/LaunchDaemons/org.swarm.bot.plist
     Started: 13:14:50.715931
    Duration: 0.003 ms
     Changes:   
```
