### ISSUE TITLE
[Web] Build Blank Screen while initialize Firebase

### ISSUE THREAD

**Issue by fahadahmed84650** [flutter/flutter#93231]
App Compiles properly, but browser stuck in loading.... with White Blank Screen

**I getting Exception Error Here when Initialize Firebase**
```
  await ui.webOnlyInitializePlatform();
```

**Firebase Initialize code**
```
void main() async {
  setPathUrlStrategy();
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(const MyApp());
}

```
**full file code:-**

```
// @dart=2.12
// Flutter web bootstrap script for package:mywebappp/main.dart.

import 'dart:ui' as ui;
import 'dart:async';

import 'package:mywebappp/main.dart' as entrypoint;
import 'package:flutter_web_plugins/flutter_web_plugins.dart';
import 'package:mywebappp/generated_plugin_registrant.dart';

typedef _UnaryFunction = dynamic Function(List<String> args);
typedef _NullaryFunction = dynamic Function();
Future<void> main() async {
  registerPlugins(webPluginRegistrar);
  await ui.webOnlyInitializePlatform();
  if (entrypoint.main is _UnaryFunction) {
    return (entrypoint.main as _UnaryFunction)(<String>[]);
  }
  return (entrypoint.main as _NullaryFunction)();
}

```  

**Flutter Doctor:-**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.6.0-11.0.pre, on Microsoft Windows [Version 10.0.22000.282], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.0)
[√] Connected device (2 available)

• No issues found!

```

**Pubspec.yaml:-**

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  get: ^4.3.8
  google_fonts: ^2.1.0
  logger: ^1.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

```
