### ISSUE TITLE
[desktop][windows] something wrong with windows desktop application destructor when it refers two or more plugins

### ISSUE THREAD

**Issue by yinquanyy** [flutter/flutter#93234]
Windows desktop applications refer to two or more plugins. When the application is closed, only one plugin C++ destructor is called

the first plugin's destructor
```
MyjdcPlugin::~MyjdcPlugin() {
  std::cout << "MyjdcPlugin::~MyjdcPlugin()" << std::endl;
}
```

the second plugin's destructor
```
GojdcPlugin::~GojdcPlugin() {
  std::cout << "GojdcPlugin::~GojdcPlugin()" << std::endl;
}
```

when the app closed, only output:
```
MyjdcPlugin::~MyjdcPlugin()
```

flutter --version
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (3 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

**Comment by darshankawar** [comment]
@yinquanyy 
Can you provide us steps to replicate and minimal code sample that shows this behavior ?
Thanks.

**Comment by yinquanyy** [comment]
> @yinquanyy Can you provide us steps to replicate and minimal code sample that shows this behavior ? Thanks.

ok

1. create project:
flutter create testjdc

mkdir plugins
cd plugins

2. create first plugin:
flutter create --template=plugin --platforms=windows gojdc
and then change the GojdcPlugin::~GojdcPlugin() code to
```
GojdcPlugin::~GojdcPlugin() {
  std::cout << "GojdcPlugin::~GojdcPlugin()" << std::endl;
}
```

3. create another plugin:
flutter create --template=plugin --platforms=windows myjdc
and then change the MyjdcPlugin::~MyjdcPlugin() code to
```
MyjdcPlugin::~MyjdcPlugin() {
  std::cout << "MyjdcPlugin::~MyjdcPlugin()" << std::endl;
}
```

4. add gojdc & myjdc to testjdc's pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  myjdc:
    path: ./plugins/myjdc
  gojdc:
    path: ./plugins/gojdc
```

5. run the app:
flutter run testjdc

6. close the app. and console output:
```
MyjdcPlugin::~MyjdcPlugin()
```
