### ISSUE TITLE
[tool] Flutter create's Skeleton app has an out-of-date min dart version

### ISSUE THREAD

**Issue by IanWadham** [flutter/flutter#93982]
## Steps to Reproduce

1. Use `flutter create --template=skeleton myapp` to create a new "List View / Detail View Flutter application that follows community best practices".
2. In myapp include a line 

```dart
typedef MyClass = List<int>;
```

(i.e. a List of integers, in case my angle brackets disappear from the bug-reporting window).
3. The new app fails to compile. The compiler complains about a "non-function typedef".
4. The problem occurs because the `pubspec.yaml` file generated by flutter create specifies `Dart version 2.12`.
5. We are now up to `Dart 2.14.x`, which permits typedef of a Class and many examples in the Dart documentation show that.
6. This feature was added in `Dart 2.13`.
7. The skeleton template, and maybe all the other Flutter templates, need to be kept up-to-date with the latest versions of Flutter and Dart, otherwise new users of Flutter and Dart will be led astray, as I was.

**Comment by danagbemava-nc** [comment]
Pubspec.yaml from `flutter create --template=skeleton`

<details>
<summary> info from create </summary>

```yaml
name: myapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

```

<img width="1193" alt="Screenshot 2021-11-22 at 13 11 38" src="https://user-images.githubusercontent.com/88313112/142867708-7499f437-4386-4f5a-9a2e-0f2957804cb0.png">



</details>
