### ISSUE TITLE
[webview_flutter] _CastError: Null check operator used on a null value on Android

### ISSUE THREAD

**Issue by m-ochyra** [flutter/flutter#94152]
I have error reported by Sentry on my production app:

```
_CastError: Null check operator used on a null value
  File "android_webview_api_impls.dart", line 326, in WebSettingsHostApiImpl.setUserAgentStringFromInstance
  File "android_webview.dart", line 333, in WebSettings.setUserAgentString
  File "webview_android_widget.dart", line 334, in WebViewAndroidPlatformController._setUserAgent
  File "webview_android_widget.dart", line 183, in WebViewAndroidPlatformController.updateSettings
  File "webview.dart", line 605, in WebViewController._updateSettings
  File "webview.dart", line 597, in WebViewController._updateWidget
  File "webview.dart", line 327, in _WebViewState.didUpdateWidget.<fn>
  File "zone.dart", line 1436, in _rootRunUnary
```
I have installed webview_flutter v2.3.1 and webview_flutter_android v2.3.0:
```yaml
  webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.1"
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
  webview_flutter_platform_interface:
    dependency: transitive
    description:
      name: webview_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.0"
```

## Steps to Reproduce

Personally, I can't reproduce it by myself, but error occurs on my production app and number of reports is growing.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-x64, locale pl-PL)
    • Flutter version 2.5.3 at /Users/m.ochyra/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/m.ochyra/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 4.1.2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 1 category.
```

</details>
