### ISSUE TITLE
Reject android 11 - All Files Access Permission: Not a core feature

### ISSUE THREAD

**Issue by vietdhfpt** [flutter/flutter#94649]
## Issue when update compile sdk version 30.

Thank you for reading. My app is working properly on old version. But after upgrading to sdk version 30. I am facing serious problem related to new policy android 11. I have tried many ways but still getting rejected by android.

<details>
<summary>Reject details.</summary>

```
The feature you identified that is dependent on this permission does not appear to be critical to the core functionality of your app.

Core functionality is defined as the main purpose of the app. Without this core functionality, the app is "broken" or rendered unusable. The core functionality, as well as any core features that comprise this core functionality, must all be prominently documented and promoted in the app's description.

Please update your app so that the feature does not use this permission or ensure that the core functionality is prominently documented and promoted in the app's description and resubmit your app on Play Developer console.

Policy: All Files Access Permission

Files and directory attributes on a user's device are regarded as personal and sensitive user data subject to the Personal and Sensitive Information policy and the following requirements:

Apps should only request access to device storage which is critical for the app to function, and may not request access to device storage on behalf of any third-party for any purpose that is unrelated to critical user-facing app functionality.
Android devices running Android "R" (Android 11) or later, will require the MANAGE_EXTERNAL_STORAGE permission in order to manage access in shared storage. All apps that target R or later and request broad access to shared storage ("All files access") must successfully pass an appropriate access review prior to publishing. Apps allowed to use this permission must clearly prompt users to enable "All files access" for their app under "Special app access" settings. For more information on the R requirements, please see this help article.

Read more about Use of All Files Access Permission
See Android storage use cases and best practices
Address this issue in the Play Console.
```

</details>

**App details.**

<details>
<summary>Manifest file.</summary>

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.netstars.paperpos">
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove"/>
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" tools:node="remove"/>

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:allowBackup="false"
        android:label="@string/app_name_gradle"
        android:icon="@mipmap/ic_launcher"
        android:requestLegacyExternalStorage="true">
        <meta-data android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"
        />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/notification_icon"
        />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorNotification"
        />
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
            />
            <!-- <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
            /> -->
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2"
        />
    </application>
</manifest>
```

</details>

<details>
<summary>Build gradle file.</summary>

```
android {
    compileSdkVersion 31

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId ""
        minSdkVersion 23
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
}
```

</details>

<details>
<summary>Pubspec file.</summary>

```
  # Firebase
  firebase_analytics: 8.3.4
  firebase_core: 1.10.0
  firebase_crashlytics: 2.3.0
  firebase_remote_config: 0.11.0+2
  firebase_messaging: 11.1.0
  firebase_in_app_messaging: 0.5.0+13
  firebase_dynamic_links: 3.0.1
  firebase_auth: 3.2.0
  firebase_storage: 10.1.0
  cloud_firestore: 3.1.1

  # Orthers
  uuid: 3.0.5
  permission_handler: 8.3.0
  audioplayers: 0.20.0
  printing: 5.6.0
  url_launcher: 6.0.17
  pinput: 1.2.0
  camera: 0.9.4
  cupertino_icons: 1.0.4
  keyboard_dismisser: 2.0.0
  rxdart:
  provider: 6.0.1
  shared_preferences: 2.0.9
  flutter_screenutil: 2.3.1
  path_provider: 2.0.7
  image_picker: 0.8.4+4
  fl_chart: 0.40.2
  syncfusion_flutter_charts: 19.3.56
  sqflite: 2.0.0+4
  path: 1.8.0
  flutter_staggered_grid_view: 0.4.1
  keyboard_actions: 3.4.4
  modal_bottom_sheet: 2.0.0 # Present new widgets like that ios 13
  smooth_star_rating: 1.1.1
  pull_to_refresh: 2.0.0
  flutter_launcher_icons: 0.9.2
  qr_flutter: 4.0.0 # create qr
  device_info: 2.0.3
  cron: 0.4.0
  package_info: 2.0.2
  store_redirect: 2.0.0
  enum_to_string: 2.0.1
  timer_count_down: 2.2.0
  random_string: 2.3.1
  flutter_spinkit: 5.1.0 # Loading animation
  share: 2.0.4
  flutter_native_image: 0.0.6+1
  connectivity: 3.0.6
  showcaseview: 1.1.4
  flutter_datetime_picker: 1.5.0
  get: 4.5.1
  logger: 1.1.0
  dio: 4.0.4
  http: 0.13.4
  lottie: 1.2.1
  flutter_local_notifications: 9.1.4
  dartz: 0.10.0
  equatable: 2.0.3
  flutter_swipe_action_cell: 2.1.5
  sprintf: 6.0.0
  qr_code_scanner: 0.6.1
  flutter_speed_dial: 4.6.6
  carousel_slider: 4.0.0
  cached_network_image: 3.2.0
  scan: 1.5.0
  flutter_native_timezone: 2.0.0
  flash: 2.0.3
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-x64, locale en-VN)
    • Flutter version 2.5.3 at /Users/dhv/fvm/versions/2.5.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/dhv/Library/Android/sdk
    • Platform android-31, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

</details>
