### ISSUE TITLE
Cannot open file, path = 'C:\Users\...\Pub\Cache\_temp\direbea2aa8\test\fixtures\invalid\n_structure_<.>.json' The file name, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by Bestfastfire** [flutter/flutter#94718]
When I run `flutter pub get` Im gettind this error:

`Cannot open file, path = 'C:\Users\Woton\AppData\Local\Pub\Cache\_temp\direbea2aa8\test\fixtures\invalid\n_structure_<.>.json' (OS Error: The file name, directory name, or volume label syntax is incorrect.
, errno = 123)
pub get failed (66; , errno = 123))`

I've tried:

1 - `flutter clean`
2 - `flutter pub cache repair`
3 - Delete folder `Pub` in AppData
4 - Delete folder `Cache` in `flutte\bin\cache`

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [versÃ£o 10.0.19043.1348], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
[√] Android Studio (version 4.2)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
[√] VS Code (version 1.62.3)
[√] Connected device (4 available)
```

My pubspec:

```
name: dentista_de_cavalo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+24

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Sugbscription
  qonversion_flutter: ^4.3.0

  # Configuration
  flutter_cupertino_localizations: ^1.0.1
  shared_preferences: ^2.0.6
  platform_device_id: ^1.0.1
  fragment_navigate: ^1.1.1+1
  country_pickers: ^2.0.0
  path_provider: ^2.0.2

  # Widgets
  flutter_calendar_carousel: ^1.4.12
  floating_action_bubble: ^1.1.1
  modal_progress_hud: ^0.1.3
  super_rich_text: ^0.2.1
  page_transition: ^2.0.2
  fluttertoast: ^7.0.2
  expandable: ^4.1.4
  signature: 4.1.1

  # Validate / Transform
  mask_text_input_formatter: ^1.0.6
  enum_to_string: ^1.0.9
  date_format: ^1.0.8
  cpfcnpj: ^1.0.3
  uuid: 3.0.4

  # Image
  cached_network_image: ^3.0.0
  image_editor_pro: ^1.1.8
  image_picker: ^0.7.4 #
  image_cropper: 1.4.0
  flutter_svg: ^0.22.0

  gesture_zoom_box: ^0.0.3

  # Firebase
  firebase_analytics: ^8.1.1
  firebase_database: ^7.1.0
  firebase_storage: ^8.1.1
  cloud_firestore: ^2.2.1
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1

  # PDF
  open_file: ^3.0.1 #
  printing: ^5.2.1 #
  pdf: ^3.3.0

dependency_overrides:
  # intl: 0.17.0-nullsafety.2
  url_launcher: ^6.0.17
  rxdart: ^0.22.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  ios: true
  image_path: "asset/main_icon.png"

flutter:
  uses-material-design: true

  assets:
    - images/ondotograma_corrigido.png
    - images/background/auth.jpg
    - images/middle_logo.png
    - images/ic_splash.svg
    - images/unknown.png
    - images/ic_box.svg
    - images/logo.png

    # lang
    - lang/pt_BR.json
    - lang/en_US.json
    - lang/es_ES.json
```
