### ISSUE TITLE
dartPluginClass with android results in an error on build

### ISSUE THREAD

**Issue by jhancock4d** [flutter/flutter#95012]
## Steps to Reproduce

1. Create a platform interface package with a interface etc. per the docs.
2. Create a basic package that does android/ios
3. Implement the interface in the /lib folder
4. Add the android and ios definitions to pubspec.yaml
5. Create example project that consumes this.
6. Build example project with flutter build apk --debug

Here's what my pubspec.yaml looks like:

```
flutter:
  plugin:
    platforms:
      web:
        default_package: openidconnect_web
      windows:
        default_package: openidconnect_windows
      ios:
        dartPluginClass: OpenIdConnectDefaultPlatform
      android:
        dartPluginClass: OpenIdConnectDefaultPlatform
```

I've also tried adding the explicit file name like you do for web like so:         fileName: default_platform.dart

When testing the windows implementation, I get the following which appears to be erroring on the ios/android code:

.dart_tool/flutter_build/generated_main.dart(23,9): error GA0A3EB9C: Undefined name 'OpenIdConnectDefaultPlatform'. [D:\Repos\concerti\openidconnect\openidconnect\example\build\windows\flutter\flutter_assemble.vcxproj]
.dart_tool/flutter_build/generated_main.dart:1
.dart_tool/flutter_build/generated_main.dart(34,9): error GA0A3EB9C: Undefined name 'OpenIdConnectDefaultPlatform'. [D:\Repos\concerti\openidconnect\openidconnect\example\build\windows\flutter\flutter_assemble.vcxproj]

**Expected results:** 
Should build normally per the announcement and the documentation (which uses windows as an example, but doesn't error with android and ios and you'd think would just work because of the merge from August.  It shouldn't need any platform folders just to work either.

**Actual results:** 

* Where:
Script 'C:\Users\xxx\flutter\packages\flutter_tools\gradle\app_plugin_loader.gradle' line: 27

* What went wrong:
A problem occurred evaluating script.
> assert pluginDirectory.exists()
         |               |
         |               false
         D:\Repos\xxx\yyy\android

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

I then added the android folder, which got me a different error message:

: Error: Undefined name 'OpenIdConnectDefaultPlatform'.
.dart_tool/flutter_build/generated_main.dart:23
        OpenIdConnectDefaultPlatform.registerWith();

But that exists:

```
class OpenIdConnectDefaultPlatform extends OpenIdConnectPlatform {
  static void registerWith(Registrar registrar) {
    OpenIdConnectPlatform.instance = OpenIdConnectDefaultPlatform();
  }
  ...
}
```
