### ISSUE TITLE
Add new 'empty' project template that has no boilerplate code or comments

### ISSUE THREAD

**Issue by fivesprites** [flutter/flutter#95118]
## Use case

As a developer, I want to create a project without the boilerplate example code and comments.  This applies to the _main.dart_ file and the _pubspec.yaml_ file.

It would be super helpful to just call '_flutter create -t empty_' and it generates a new project but with a main.dart with only a main() method and a pubspec.yaml with only the most minimal of fields and very little commenting.

This is more a feature for the more seasoned developers who regularly create projects and don't want to be encumbered by boilerplate.

## Proposal

Update the 'flutter' tool to include a new template 'empty' which, like 'app' and 'skeleton' will create a new project but only include the most basic main.dart and pubspec.yaml files.

`flutter create -t empty my_empty_project`

**main:dart:**
`void main() { }
`

**pubspec.yaml:**
```
name: {{projectName}}
description: {{description}}

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: {{dartSdkVersionBounds}}

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

```
