### ISSUE TITLE
Flutter build apk: Could not resolve net.minidev:json-smart:[1.3.1,2.3].

### ISSUE THREAD

**Issue by phongdh-lftv** [flutter/flutter#95241]
## Steps to Reproduce

1. Execute `flutter build apk` 
**Results:** 
```
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:minifyReleaseWithR8'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].              
     Required by:                                                       
         project :app > project :stripe_payment > com.stripe:stripe-android:10.4.6 > com.stripe:stripe-3ds2-android:1.2.2 > com.nimbusds:nimbus-jose-jwt:7.8
      > Failed to list versions for net.minidev:json-smart.             
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/net/minidev/json-smart/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/net/minidev/json-smart/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/net/minidev/json-smart/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 20s
```

File: android/app/build.gradle
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "my.application"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.browser:browser:1.2.0'

    // Import the BoM for the Firebase platform
    // implementation platform('com.google.firebase:firebase-bom:26.2.0')
    implementation platform('com.google.firebase:firebase-bom')

    // Declare the dependencies for the Firebase Cloud Messaging and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
}

apply plugin: 'com.google.gms.google-services'
```
</details>

File: android/build.gradle
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.5.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by mamuseferha** [comment]
Hi @phongdh-lftv 
From what I can see, the issue is related to a 3rd party plugin (stripe_payment) rather than to Flutter itself. 
```
Could not resolve net.minidev:json-smart:[1.3.1,2.3].              
     Required by:                                                       
         project :app > project :stripe_payment > com.stripe:stripe-android:10.4.6 > com.stripe:stripe-3ds2-android:1.2.2 > com.nimbusds:nimbus-jose-jwt:7.8
```
Please open the issue in the dedicated [repository](https://github.com/jonasbark/flutter_stripe_payment/issues).

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by phongdh-lftv** [comment]
@mamuseferha Thank you for your response.

No it's not dedicated repository. I've tried set some implementation to `android/app/build.gradle` but it's problems with issue.
**Note: Build on ios successfully**
```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:lintVitalRelease'.   
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].              
     Required by:                                                       
         project :app > com.nimbusds:nimbus-jose-jwt:7.8                
      > Failed to list versions for net.minidev:json-smart.             
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/net/minidev/json-smart/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/net/minidev/json-smart/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/net/minidev/json-smart/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 9s 
```

**File: android/app/build.gradle**
```
.
.
.
dependencies {
    .
    .
    .
    implementation 'com.stripe:stripe-android:10.4.6' // <~~ added
    implementation 'com.stripe:stripe-3ds2-android:1.2.2' // <~~ added
    implementation 'com.nimbusds:nimbus-jose-jwt:7.8' // <~~ added
}
.
.
.
```

**Run: `flutter doctor -v`**
```
flutter doctor -v
[✓] Flutter (Channel flutter-1.22-candidate.0, 1.21.0-10.0.pre.145, on macOS 11.6 20G165, locale en-VN)
    • Flutter version 1.21.0-10.0.pre.145 at /Users/account/development/flutter
    • Framework revision 3c9f68bc7e (1 year, 4 months ago), 2020-08-18 16:28:45 -0700
    • Engine revision b58f70f2c8
    • Dart version 2.10.0 (build 2.10.0-38.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/account/Library/Android/sdk
    • Platform android-31, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Run `flutter run -v`**
```
[ +128 ms] executing: [/Users/account/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +71 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 3c9f68bc7ecee5b901999d20805352defdd44a45
[        ] executing: [/Users/account/development/flutter/] git tag --points-at HEAD
[ +106 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: [/Users/account/development/flutter/] git describe --match *.*.* --first-parent --long --tags
[  +71 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.21.0-9.0.pre-145-g3c9f68bc7e
[  +13 ms] executing: [/Users/account/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/flutter-1.22-candidate.0
[        ] executing: [/Users/account/development/flutter/] git ls-remote --get-url origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +23 ms] executing: [/Users/account/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] flutter-1.22-candidate.0
[  +45 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +15 ms] executing: /Users/account/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +228 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +1 ms] Xcode 12.5
           Build version 12E262
[   +3 ms] executing: xcrun --find xcdevice
[  +17 ms] Exit code 0 from: xcrun --find xcdevice
[        ] /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice
[        ] executing: xcrun xcdevice list --timeout 2
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[        ] executing: /usr/bin/xcrun simctl list --json devices
[  +43 ms] List of devices attached
[ +108 ms] {
            "devices" : {
                .
                .
                .
            }
        }
[   +5 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +58 ms] No supported devices connected.
[  +12 ms] "flutter run" took 4,136ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:352:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:882:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:785:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:774:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #21     _rootRun (dart:async/zone.dart:1190:13)
           #22     _CustomZone.run (dart:async/zone.dart:1093:19)
           #23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[   +4 ms] ensureAnalyticsSent: 0ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**File: pubspec.yaml**
```
name: Name
description: Description

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: 0.12.2
  stripe_payment: ^1.0.9
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.8.1
  font_awesome_flutter: ^8.10.0
  fluttertoast: ^7.1.1
  image_picker: ^0.6.7+14
  geolocator: ^6.1.6
  geocoding: ^1.0.5
  google_maps_flutter: ^0.5.33
  uuid: ^2.2.2
  cached_network_image: ^2.3.3
  pin_code_fields: ^5.2.0
  autocomplete_textfield: ^1.7.3
  carousel_slider: ^2.3.1
  flutter_webview_plugin: ^0.3.11
  alphabet_list_scroll_view: ^1.0.6
  flutter_google_places: ^0.2.0
  nanoid: ^0.1.0
  share: ^0.6.5+4
  dio: ^3.0.10
  url_launcher: ^5.7.6
  quiver: ^2.1.5
  provider: ^4.3.2+3
  flutter_local_notifications: ^4.0.1+2
  permission_handler: ^5.1.0+2
  algolia: ^0.1.7
  syncfusion_flutter_charts: 18.3.53
  flutter_rating_bar: ^3.1.0
  package_info: ^0.4.3+4
  pub_semver: ^1.4.4
  app_tracking_transparency: ^1.1.0+1
  flutter_datetime_picker: ^1.5.0
  flutter_app_badger: ^1.1.2


  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.3
  firebase_storage: ^4.0.0
  firebase_auth: ^0.18.3
  firebase_analytics: ^6.3.0
  firebase_messaging: ^7.0.3
  firebase_crashlytics: ^0.2.4
  firebase_remote_config: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#096FCA"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Medium
      fonts:
            - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
flutter_intl:
  enabled: true

```
