### ISSUE TITLE
BottomNavigationBarItem has wrong colors when BottomNavigationBar is shifting

### ISSUE THREAD

**Issue by wolframm** [flutter/flutter#95494]
When the `BottomNavigationBar` is set to `BottomNavigationBarType.shifting`, it uses white color for each `BottomNavigationBarItem` item when brightness is light, which makes them almost invisible. When the brightness is dark, it uses black, which is also almost invisible. When the bar is set to `BottomNavigationBarType.fixed`, the bar item colors are correct, when it is set to `BottomNavigationBarType.fixed`, the colors are wrong. Please fix.

`main.dart`

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SOME TITLE'),
      ),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: 0,
        type: BottomNavigationBarType.shifting,
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.card_giftcard), label: 'Gifts'),
          BottomNavigationBarItem(icon: Icon(Icons.shopping_cart), label: 'Cart'),
          BottomNavigationBarItem(icon: Icon(Icons.storefront, size: 35), label: 'Shop'),
          // BottomNavigationBarItem(icon: Icon(Icons.settings), label: 'Settings'),
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            Text(
              'SOME CONTENT',
            ),
          ],
        ),
      ),
    );
  }
}
```

`pubspec.yaml`

```
name: flex
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

`Flutter Doctor`

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)
```

<img width="443" alt="Screen Shot 2021-12-18 at 8 45 47 PM" src="https://user-images.githubusercontent.com/6116001/146652512-1c20fe94-dd3f-4185-a540-fe2283da8195.png">
