### ISSUE TITLE
Method not found: 'getUserDirectory'. ../…/lib/path_provider_linux.dart:

### ISSUE THREAD

**Issue by hathemi** [flutter/flutter#95557]
How can i resolve this issue ? 

```
.../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/xdg_directories-0.2.0/lib/xdg_directories.dart: Error: The control character U+0000 can only be used in strings and comments.
../…/lib/xdg_directories.dart:1
: Error: Undefined name 'dataHome'.
../…/lib/path_provider_linux.dart:29
    final directory = Directory(path.join(xdg.dataHome.path, processName));
                                              ^^^^^^^^
: Error: Method not found: 'getUserDirectory'.
../…/lib/path_provider_linux.dart:39
    return Future.value(xdg.getUserDirectory('DOCUMENTS')?.path);
                            ^^^^^^^^^^^^^^^^
: Error: Method not found: 'getUserDirectory'.
../…/lib/path_provider_linux.dart:44

    return Future.value(xdg.getUserDirectory('DOWNLOAD')?.path);
                            ^^^^^^^^^^^^^^^^

```
flutter doctor -v
[√] Flutter (Channel dev, 2.9.0-0.1.pre, on Microsoft Windows [version 10.0.19043.1415], locale fr-FR)
    • Flutter version 2.9.0-0.1.pre at C:\Users\Asus\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (6 days ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Asus\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Asus\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\Asus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Infinix X682B (mobile) • 061162511I001282 • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)             • edge             • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!
```

```

**Comment by darshankawar** [comment]
@hathemi 
Can you try commenting out below line and try to see if you still get same behavior ?

```
`if (Platform.isAndroid) {
      WebView.platform = SurfaceAndroidWebView();
    }`
```

**Comment by darshankawar** [comment]
@hathemi 
When did you start getting these errors ?
Did you change / update any plugins ?
Can you try `flutter clean` or `flutter pub cache repair` and then `flutter run` to see if it helps ?
Also, try switching to latest master and see if you still get same errors.

```
flutter channel master
flutter upgrade
```

**Comment by hathemi** [comment]
HI @darshankawar 
it's an existing project and i need to run it on my phone.
i have tried 
```
flutter channel master
flutter upgrade
```
```
flutter upgrade
Flutter is already up to date on channel master
Flutter 2.9.0-1.0.pre.145 • channel master • https://github.com/flutter/flutter.git
Framework • revision 209d316b4b (74 minutes ago) • 2021-12-21 02:59:21 -0500
Engine • revision 202e4a6d16
Tools • Dart 2.16.0 (build 2.16.0-123.0.dev) • DevTools 2.9.1
```
but unfortunately still the same error showing!!
should i need to downgrade some packages ??

**Comment by darshankawar** [comment]
@hathemi 
Is your project migrated to null safety or not ?
Both the methods seems to be part of the package `xdg_directories` https://pub.dev/packages/xdg_directories, but your project compiler isn't recognizing them. Can you provide your `pubspec.yaml` ?

**Comment by hathemi** [comment]
@darshankawar  sure 

```
name: projectB
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_font_icons: ^2.2.4
  salomon_bottom_bar: ^3.1.0
  achievement_view: ^0.2.1
  google_fonts: ^2.1.0
  hexcolor: ^2.0.5
  url_launcher: ^5.1.3
  responsive_framework: ^0.1.4
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/girl1.png
    - assets/girl2.png
    - assets/girl3.png
    - assets/girl4.png
    - assets/girl5.png
    - assets/back1.jpg
    - assets/col1.jpg
    - assets/col2.jpg
    - assets/col3.jpg
    - assets/col4.jpg
    - assets/back2.png
    - assets/back3.png
```
