### ISSUE TITLE
[tool_crash] _CastError: Null check operator used on a null value

### ISSUE THREAD

**Issue by hihiron-2d2** [flutter/flutter#95560]
When I try to implement Localization in flutter, I get an error when I fill in generate: true in yaml.

The error statement is
"Oops; flutter has exited unexpectedly: "Null check operator used on a null value".
A crash report has been written to /Users/user/development/Shop-Client/flutter_24.log."
This will result in

How should I resolve the issue in this case?

```yaml
name: shop_client
description: Flutter project for ATELIER Shop.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line

  # 追加パッケージはここに
  provider: ^5.0.0

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+1
  flutter_native_splash: ^1.3.2
  riverpod: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: "assets/images/atelier_logo.png"
  color: "4DD0E1"

flutter:
  uses-material-design: true
  generate: true

  assets :
    - assets/images/icon-home.png
    - assets/images/icon-grocery.png
    - assets/images/icon-drink.png
    - assets/images/icon-appliances.png
    - assets/images/icon-medicine.png
    - assets/images/icon-candy.png
    - assets/images/icon-alcohol.png
    - assets/images/icon-softdrink.png
    - assets/images/beer1.jpg
    - assets/images/beer2.jpg
    - assets/images/beer3.jpg
    - assets/images/beer4.png
    - assets/images/beer5.jpg
    - assets/images/beer6.png
    - assets/images/wine.jpg
    - assets/images/atelier_logo.png
```

## command

```
flutter --no-color pub get
```

## exception

_CastError: Null check operator used on a null value

```
#0      describeLocale
(package:flutter_tools/src/localizations/localizations_utils.dart:219:49)
#1      LocalizationsGenerator._generateBaseClassFile
(package:flutter_tools/src/localizations/gen_l10n.dart:1113:34)
#2      LocalizationsGenerator._generateCode
(package:flutter_tools/src/localizations/gen_l10n.dart:1200:46)
#3      LocalizationsGenerator.writeOutputFiles
(package:flutter_tools/src/localizations/gen_l10n.dart:1275:47)
#4      generateLocalizations
(package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
#5      GenerateLocalizationsTarget.build
(package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
#6      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous suspension>
#7      FlutterBuildSystem.build
(package:flutter_tools/src/build_system/build_system.dart:606:16)
<asynchronous suspension>
#8      generateLocalizationsSyntheticPackage
(package:flutter_tools/src/dart/generate_synthetic_packages.dart:58:30)
<asynchronous suspension>
#9      PackagesGetCommand._runPubGet
(package:flutter_tools/src/commands/packages.dart:134:7)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand
(package:flutter_tools/src/commands/packages.dart:176:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64,
locale ja-JP)
    • Flutter version 2.8.1 at /Users/user/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup
for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Users/user/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86
   • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        •
web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```
