### ISSUE TITLE
Execution failed for task ':camera:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by sahilb8** [flutter/flutter#95895]
![up](https://user-images.githubusercontent.com/43825458/147547680-c2470867-2c37-49a2-ba2e-3d66e4afae39.jpg)

<details>
<summary>pubspec.yaml</summary>

```yaml
name: avysh_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 4.0.0+55

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^1.9.5
  cupertino_icons: ^1.0.2
  loading_indicator: ^2.1.1
  device_info_plus: ^3.1.0
  permission_handler: ^8.1.6
  http: ^0.13.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.2
  webview_flutter: ^2.0.8
  flutter_inappwebview: ^5.3.2
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.7
  pin_code_fields: ^7.2.0
  url_launcher: ^6.0.8
  get_it: ^7.2.0
  firebase_dynamic_links: ^2.0.6
  firebase_analytics: ^8.2.0
  firebase_crashlytics: ^2.2.0
  socket_io_client: ^1.0.1
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  intl: ^0.17.0
  razorpay_flutter: ^1.2.3
  cached_network_image: ^3.1.0
  share: ^2.0.4
  image_picker: ^0.8.4
  package_info_plus: ^1.0.6 
  contacts_service: ^0.6.1
  mime: ^1.0.0
  firebase_messaging_web: ^2.0.5
  connectivity_plus: ^1.1.0
  flutter_downloader: ^1.7.1
  flutter_uploader: 3.0.0-beta.2
  readmore: ^2.1.0
  marquee: ^2.2.0
  open_file: ^3.2.1
  file_picker: ^4.2.0
  scrollable_positioned_list: ^0.2.2 #For chat message list view
  flutter_local_notifications: ^9.1.4
  html_unescape: ^2.0.0
  camera: ^0.9.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
```
</details>

Cant build the app.
