### ISSUE TITLE
[webview_flutter] Framework not found

### ISSUE THREAD

**Issue by H-Zaman** [flutter/flutter#95946]
After adding webview to my project, when i tried to built an archive to release to testflight suddenly this popped up, saying *Link webview_flutter_wkwebview (armv7)*,
this was the xcode log
```
Ld /Users/anasrazzaq/Library/Developer/Xcode/DerivedData/Runner-gootwubzqzanufbpybnjwhoulsxf/
Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/webview_flutter_wkwebview.build/Objects-normal/
armv7/Binary/webview_flutter_wkwebview normal armv7 (in target 'webview_flutter_wkwebview' from project 'Pods')
    cd /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr
/bin/clang -target armv7-apple-ios9.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -L/Users/anasrazzaq/Library/Developer
/Xcode/DerivedData/Runner-gootwubzqzanufbpybnjwhoulsxf/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/webview_flutter_wkwebview -F/Users
/anasrazzaq/Library/Developer/Xcode/DerivedData/Runner-gootwubzqzanufbpybnjwhoulsxf/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/webview_flutter_wkwebview -F/Users/anasrazzaq/Downloads/flutter/bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-arm64_armv7 -filelist /
Users/anasrazzaq/Library/Developer/Xcode/DerivedData/Runner-gootwubzqzanufbpybnjwhoulsxf/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/webview_flutter_wkwebview.build/Objects-normal/armv7/webview_flutter_wkwebview.LinkFileList -install_name @rpath/webview_flutter_wkwebview.framework/webview_flutter_wkwebview -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/anasrazzaq/Library/Developer/Xcode/DerivedData/Runner-gootwubzqzanufbpybnjwhoulsxf/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/webview_flutter_wkwebview.build/Objects-normal/armv7/webview_flutter_wkwebview_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/anasrazzaq/Library/Developer/Xcode/DerivedData/Runner-gootwubzqzanufbpybnjwhoulsxf/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/webview_flutter_wkwebview -fobjc-arc -fobjc-link-runtime -framework Flutter -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/anasrazzaq/Library/Developer/Xcode/DerivedData/Runner-gootwubzqzanufbpybnjwhoulsxf/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/webview_flutter_wkwebview.build/Objects-normal/armv7/webview_flutter_wkwebview_dependency_info.dat -o /Users/anasrazzaq/Library/Developer/Xcode/DerivedData/Runner-gootwubzqzanufbpybnjwhoulsxf/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/webview_flutter_wkwebview.build/Objects-normal/armv7/Binary/webview_flutter_wkwebview

ld: framework not found Flutter
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Help please

**Comment by maheshmnj** [comment]
Hi @H-Zaman, Thanks for filing the issue. Please share the complete output of `flutter doctor -v`, your`pubspec.yaml`. Does the app build and run fine locally in release mode by when `flutter run -v --release` Also does `flutter build ios --release` works?

if any of these fails then please share the complete logs by running the same command with `-v` flag.

**Comment by H-Zaman** [comment]
@maheshmnj  heres the ```flutter doctor -v```
```
nasrazzaq@Anass-MacBook-Air repocoin-userapp % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.8.1 at /Users/anasrazzaq/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/anasrazzaq/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.62.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web)
 • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
heres the pubspec.yaml
```
name: scanerapp
description: RepoCoin User APP.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^5.1.0
  dio: ^4.0.0
  get_storage: ^2.0.3
  get: ^4.3.8
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  lottie: ^1.1.0
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.0.15
  open_mail_app: ^0.3.0
  intl: ^0.17.0
  confetti: ^0.6.0-nullsafety
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  animated_text_kit: ^4.2.1
  geolocator: ^7.6.2
  flutter_geocoder: ^0.2.2-nullsafety
  google_maps_flutter: ^2.0.8
  flutter_countdown_timer: ^4.1.0
  flutter_fortune_wheel: ^1.1.0
  simple_gradient_text: ^1.2.2
  gesture_x_detector: ^1.0.0
  flutter_facebook_auth: ^3.5.2
  flutter_polyline_points: ^1.0.0
  jiffy: ^4.1.0
  square_in_app_payments: ^1.7.1
  visibility_detector: ^0.2.0
  flutter_rating_bar: ^4.0.0
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  cloud_firestore: ^2.5.3
  share_plus: ^3.0.2
  package_info: ^2.0.2
  fl_chart: ^0.40.2
  http:
  flutter_beep: ^1.0.0
  permission_handler: ^8.3.0
  google_mobile_ads: ^1.0.1
  flutter_svg: ^1.0.0
  flutter_animation_progress_bar: ^2.0.1
  webview_flutter: ^3.0.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  implicitly_animated_reorderable_list: ^0.4.2


dev_dependencies:

  flutter_native_splash: ^1.2.4
  flutter_launcher_icons: ^0.9.2
  lints: ^1.0.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/animations/
    - assets/images/
    - assets/images/icons/
    - assets/images/spin_wheel/

  fonts:
    - family: cBold
      fonts:
        - asset: assets/fonts/CircularStd-Bold.otf
    - family: cBook
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf
```
when i connect my phone and run it from android studio it works fine for both android and ios,
but ```flutter build ios --release``` this throws an error,
```
Building com.repocoin.scanerapp for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: R4K57KZB9P
Running pod install...                                             12.5s
Running Xcode build...                                                  
Xcode build done.                                           10.7s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[65953]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1f33b3130) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1082ec2c8). One of the two will be used. Which one is undefined.
    objc[65953]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1f33b3180) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1082ec318). One of the two will be used. Which one is undefined.
    2021-12-30 12:07:49.103 xcodebuild[65953:85709595] warning:  The file reference for "Firebase.debug.xcconfig" is a member of multiple groups ("Support Files" and
    "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If
    you want a reference to the same file in more than one group, please add another reference to the same path.
    2021-12-30 12:07:49.104 xcodebuild[65953:85709595] warning:  The file reference for "Firebase.release.xcconfig" is a member of multiple groups ("Support Files" and
    "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If
    you want a reference to the same file in more than one group, please add another reference to the same path.
    2021-12-30 12:07:49.108 xcodebuild[65953:85709595] warning:  The file reference for "GoogleUtilities.debug.xcconfig" is a member of multiple groups ("Support Files" and
    "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If
    you want a reference to the same file in more than one group, please add another reference to the same path.
    2021-12-30 12:07:49.108 xcodebuild[65953:85709595] warning:  The file reference for "GoogleUtilities.release.xcconfig" is a member of multiple groups ("Support Files"
    and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).
    If you want a reference to the same file in more than one group, please add another reference to the same path.
    * BUILD FAILED *


Xcode's output:
↳
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Runner.xcodeproj: warning: AssetsLibrary is deprecated. Consider migrating to Photos instead. (in target 'Runner'
    from project 'Runner')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'leveldb-library' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'gRPC-Core' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'gRPC-C++' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'abseil' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'FMDB' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'BoringSSL-GRPC' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'AppAuth' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'GoogleInterchangeUtilities' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'FirebaseInstanceID' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'FirebaseAnalytics' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'GoogleSymbolUtilities' from project 'Pods')
    /Users/anasrazzaq/StudioProjects/repocoin-userapp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
    of supported deployment target versions is 9.0 to 15.2.99. (in target 'GoogleSignIn' from project 'Pods')

Encountered error while building for device.

```
