### ISSUE TITLE
Unable to run flutter project 2.8.1

### ISSUE THREAD

**Issue by JoDeveloper** [flutter/flutter#95953]
I've upgraded flutter to 2.8.1 after creating new project and hit run I get this 

```
Launching lib/main.dart on sdk gphone x86 in debug mode...
lib/main.dart:1
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.IllegalArgumentException: Error decoding percent encoded characters
	at sun.net.www.ParseUtil.decode(ParseUtil.java:216)
	at sun.misc.URLClassPath$JarLoader.<init>(URLClassPath.java:834)
	at sun.misc.URLClassPath$3.run(URLClassPath.java:576)
	at sun.misc.URLClassPath$3.run(URLClassPath.java:566)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:565)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:530)
	at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:495)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
```

here is flutter doctor 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Linux Mint 20.2 5.4.0-91-generic, locale
    en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories
```

**Comment by mamuseferha** [comment]
Hi @JoDeveloper 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by JoDeveloper** [comment]
@mamuseferha 





```flutter doctor -v```

```
[✓] Flutter (Channel stable, 2.8.1, on Linux Mint 20.2 5.4.0-91-generic, locale
    en_US.UTF-8)
    • Flutter version 2.8.1 at /home/joe/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/joe/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /home/joe/Android/Sdk
    • ANDROID_SDK_ROOT = /home/joe/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API
      30) (emulator)
    • Linux (desktop)         • linux         • linux-x64   • Linux Mint 20.2
      5.4.0-91-generic

! Doctor found issues in 2 categories.
```


```
pubspec.yaml
```



```
name: citycab
description: An open source ride hailing app with flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 
  cloud_firestore: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

```
