### ISSUE TITLE
io.flutter.1.raster crash on iOS15.1.0, EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000075f0

### ISSUE THREAD

**Issue by bgokcan** [flutter/flutter#96164]
my app crashed with following log at random times. It happens both in production and locally in profile mode. we have e2e tests developed with Flutter driver. it crashes randomly during those tests.

effected devices: iphone 11, ipone se.(we have not so many users in production. it is a new app)

```
Crashed: io.flutter.1.raster
0  libsystem_platform.dylib       0xe30 _platform_memset + 176
1  Flutter                        0x17aebc (Missing)
2  Flutter                        0x17b238 (Missing)
3  Flutter                        0x1a85f0 (Missing)
4  Flutter                        0x1d7904 (Missing)
5  Flutter                        0x223b6c (Missing)
6  Flutter                        0x21fa88 (Missing)
7  Flutter                        0x18767c (Missing)
8  Flutter                        0x187b98 (Missing)
9  Flutter                        0x5566c (Missing)
10 Flutter                        0x4f9264 (Missing)
11 Flutter                        0x47e548 (Missing)
12 Flutter                        0x3b46f4 (Missing)
13 Flutter                        0x3b4c10 (Missing)
14 Flutter                        0x2ec858 (Missing)
15 Flutter                        0x3b4308 (Missing)
16 Flutter                        0x3b5c40 (Missing)
17 Flutter                        0x3b4ec4 (Missing)
18 Flutter                        0x3bd304 (Missing)
19 Flutter                        0x2eb0c8 (Missing)
20 Flutter                        0x2ee694 (Missing)
21 CoreFoundation                 0xae268 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
22 CoreFoundation                 0x32c40 __CFRunLoopDoTimer + 1076
23 CoreFoundation                 0x2d43c __CFRunLoopDoTimers + 328
24 CoreFoundation                 0xbc58 __CFRunLoopRun + 1944
25 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
26 Flutter                        0x2ee560 (Missing)
27 Flutter                        0x2edd20 (Missing)
28 libsystem_pthread.dylib        0x19a4 _pthread_start + 148
29 libsystem_pthread.dylib        0xea0 thread_start + 8
```

Flutter doctor output

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-TR)
    • Flutter version 2.8.1 at /Users/kaptan/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kaptan/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

```

my pubspec.yaml:

```
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  provider: ^6.0.0
  image_picker: ^0.8.4
  screenshot: ^1.2.3
  path_provider: ^2.0.8
  flutter_svg: ^0.23.0+1
  google_fonts: ^2.1.0
  flutter_dropdown: ^1.0.0+hotfix.1
  sqflite: ^2.0.0+4
  uuid: ^3.0.4
  image: ^3.0.2
  video_player: ^2.2.0
#  flutter_cache_manager: ^3.1.2
  visibility_detector: ^0.2.0
  flutter_xlider:
    git:
      url: https://github.com/Ali-Azmoud/flutter_xlider.git
      ref: master
  flex_color_picker: ^2.1.2
  image_editor: ^1.0.1
  extended_image: ^4.2.1
  reorderables: ^0.4.1
  matrix_gesture_detector: ^0.2.0-nullsafety.1
  image_size_getter: ^1.0.0
  flutter_secure_storage: ^5.0.2
  flutter_form_builder: ^7.0.0
  undo: ^1.3.1
  basic_utils: ^3.6.0
  fluttertoast: ^8.0.8
  photo_manager: ^1.3.9+1
  sliding_up_panel: ^2.0.0+1
  auto_size_text: ^3.0.0-nullsafety.0
  #photo_view: ^0.13.0 https://github.com/bluefireteam/photo_view/issues/478
  photo_view: ^0.12.0
  cached_network_image: ^3.2.0
  clippy_flutter: ^2.0.0-nullsafety.1
  webview_flutter: ^2.0.12
  logger: ^1.1.0
  tuple: ^2.0.0
  percent_indicator: ^3.0.1
  date_utils: ^0.2.0
  modal_bottom_sheet: ^2.0.0
  share_plus: ^3.0.4
  firebase_core: ^1.10.0
  firebase_analytics: ^8.3.4
  firebase_crashlytics: ^2.3.0
  package_info: ^2.0.2
  gallery_saver: ^2.1.3
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.10
  flutter_spinkit: ^5.1.0
  in_app_review: ^2.0.3
  page_transition: ^2.0.2
  keyboard_utils: ^1.3.0
  giphy_get: ^2.0.3
  auto_size_text_field: ^1.0.1

  video_util:
    path: ../../internal-flutter-plugins/video_util

  iap_util:
    path: ../../internal-flutter-plugins/iap_util




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  collection: ^1.15.0-nullsafety.4
  buttons_tabbar: ^1.3.1
  upgrader: ^3.9.0
  json_annotation: ^4.4.0
  dart_jsonwebtoken: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.4
  git: ^2.0.0
  t_stats: ^3.0.0
  test: ^1.17.2
  logging: ^1.0.2







flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash_logo.png


flutter_icons:
  image_path_android: "assets/launcher/1024x1024@2x.jpg"
  image_path_ios: "assets/launcher/1024x1024@2x.jpg"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
    - assets/svg/text/
    - assets/svg/image/
    - assets/svg/home/
    - assets/svg/drawer/
    - assets/svg/my-stories/
    - assets/svg/sticker/social/
    - assets/png/
    - assets/png/2x/
    - assets/png/3x/
    - assets/locales/
    - assets/splash/
```
