### ISSUE TITLE
Flutter app crashing after releasing on play store

### ISSUE THREAD

**Issue by whiz-kid** [flutter/flutter#96289]
I've developed an app in flutter. It runs perfectly for ios and is live on app store. Now when I run it for android platform it runs fine both in debug and release mode. But when I create bundle and upload it on play store it crashes with following error :
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5320)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5350)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2257)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:233)
  at android.app.ActivityThread.main (ActivityThread.java:8030)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:631)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:978)
Caused by: java.lang.NullPointerException: 
  at io.flutter.plugins.imagepicker.ImagePickerPlugin.tearDown (ImagePickerPlugin.java:21)
  at io.flutter.plugins.imagepicker.ImagePickerPlugin.onDetachedFromActivity (ImagePickerPlugin.java)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity (FlutterEngineConnectionRegistry.java:54)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:58)
  at io.flutter.embedding.android.FlutterActivity.release (FlutterActivity.java:7)
  at io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java:11)
  at android.app.Activity.performDestroy (Activity.java:8251)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1364)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5305)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5350)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2257)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:233)
  at android.app.ActivityThread.main (ActivityThread.java:8030)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:631)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:978)
```

Help me understand the problem and how to fix it. Highly appreciate your help.

**Comment by jayjah** [comment]
@whiz-kid Well, in the first place it's a typical Java-Nullpointer error, but this error comes from the plugin `ImagePicker`, which you are using and NOT from Flutter itself. But when I look closer into the source-code from that plugin it seems you're using a kinda old version of that plugin. 

Could you post your pubspec.yaml?

**Comment by whiz-kid** [comment]
Here is my pubspec.yaml

```
name: app_fl
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.6.2+3
  get: ^4.3.8
  http_parser: ^4.0.0
  http: ^0.13.3
  flutter_easyloading: ^3.0.3
  flutter_session: ^0.1.1
  flutter_plugin_android_lifecycle: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"


flutter_icons:
  image_path: "assets/icon.png"
  android: "launcher_icon"
  ios : true
  remove_alpha_ios: true


flutter:
  assets:
    - "google.png"
  uses-material-design: true
```
