### ISSUE TITLE
On engine->framework roll PRs run benchmark tests in presubmit, without upload

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#96409]
Detect benchmark test failures (not performance regressions) like https://github.com/flutter/flutter/issues/96188 in presubmit on engine roll PR try builds.  Do not upload the performance results.

Engine roll can be detected by the version path:
```yaml
runIf:
  - bin/internal/engine.version
```

See where something similar was done in the engine: https://github.com/flutter/flutter/issues/89669 and https://flutter-review.googlesource.com/c/recipes/+/18020

```yaml
  - name: Linux Benchmarks (no-upload)
    recipe: engine/engine_metrics
    properties:
      build_host: "true"
      upload_metrics: "false"
    timeout: 60
    scheduler: luci
```
https://github.com/flutter/engine/blob/475f6f152d8ffbfba8c91d80989540e4df8a1c34/.ci.yaml#L149-L155
