### ISSUE TITLE
GitLab CI/cd pipeline failed : Cannot invoke method toInteger() on null object in build.gradle

### ISSUE THREAD

**Issue by talbiislam96** [flutter/flutter#96605]
I am trying to run build android build stage on GitLab CI pipeline, and am getting this error :

``` 
Build file '/builds/wecraft.tn/projects/xenon/front/mobile/android/app/build.gradle' line: 47
40* What went wrong:
41A problem occurred evaluating project ':app'.
42> Cannot invoke method toInteger() on null object

 ```
The error occurred because he couldn't get the mindk version in this line :

``` 
minSdkVersion localProperties.getProperty('flutter.minSdkVersion').toInteger()
         targetSdkVersion localProperties.getProperty('flutter.targetSdkVersion').toInteger()

 ```
The minsdk and targetSdkversion are both declared in localProperties file in new flutter sdk version , the file is declared by default in android's gitignore file . My question
 is how do I fix this error without having to push the file , can I declare the mindsdkversion in the ci/cd script ?

here's my current gitlabci file:

``` 

image: "cirrusci/flutter:2.8.1"
before_script:
  - flutter pub get


stages:
  - test # All jobs related for testing such as Unit Test
  - build
flutter_test: # Name of the lane
  stage: test # type of stage
  script:
    - flutter test # Run Flutter test
flutter_build_android: #Job name
  stage: build # kind of job
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
```
If anyone knows the solution please do not hesitate to respond thank you so much.
