### ISSUE TITLE
I had my application working with flutter 2.0.1 and now its 2.8.2 and its start giving error | Error: Member not found: 'PlatformInterface.verify'.     PlatformInterface.verify(instance, _token)

### ISSUE THREAD

**Issue by GautamSinghRathor** [flutter/flutter#96846]
Error 
-------
```
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_platform_interface-2.0.5/lib/url_launcher_platform_interface.dart:37:23: Error: Member not found: 'PlatformInterface.verify'.
    PlatformInterface.verify(instance, _token);
                      ^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_platform_interface-5.0.1/lib/video_player_platform_interface.dart:35:23: Error: Member not found: 'PlatformInterface.verify'.
    PlatformInterface.verify(instance, _token);
                      ^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter_platform_interface-1.8.1/lib/src/platform_interface/webview_cookie_manager.dart:33:23: Error: Member not found: 'PlatformInterface.verify'.
    PlatformInterface.verify(instance, _token);
                      ^^^^^^
2 FAILURE: Build failed with an exception.

* Where:
Script '/home/enbake/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/enbake/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

```

Flutter Doctor 
------------------
```
[✓] Flutter (Channel stable, 2.8.2-0.0.pre.1, on Ubuntu 20.04.2 LTS 5.11.0-46-generic, locale en_GB.UTF-8)
    • Flutter version 2.8.2-0.0.pre.1 at /home/enbake/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d993220b44 (3 weeks ago), 2021-12-27 17:52:48 +0530
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/enbake/Android/Sdk
    • Platform android-31, build-tools 32.0.0
    • ANDROID_HOME = /usr/lib/android-sdk/
    • Java binary at: /home/enbake/software/android-studio-2020.3.1.26-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/enbake/Downloads/flutter_theme/android-studio-2020.3.1.26-linux/android-studio
    • Flutter plugin version 63.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio
    • Android Studio at /home/enbake/software/android-studio-2020.3.1.26-linux/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/enbake/software/android-studio-2020.3.1.26-linux/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.57.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Redmi Note 8 (mobile) • 945507b9 • android-arm64  • Android 11 (API 30)
    • Chrome (web)          • chrome   • web-javascript • Google Chrome 91.0.4472.106

• No issues found!
```

Pubspec file 
-----------------
```
environment:
  sdk: ">=2.11.0 <3.0.0"
  # sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  flutter_html: ^2.2.1
  shared_preferences: ^0.5.12+4
  material_design_icons_flutter: ^4.0.5755
  google_fonts: ^1.1.1
  im_stepper: ^0.1.2+8
  toast: ^0.1.5
  flushbar: ^1.10.4
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+17
  http: ^0.12.2
  dio: ^4.0.0
  stripe_payment: ^1.1.4
  gx_file_picker: ^1.9.0+2
  flutter_icons: ^1.1.0
  hexcolor: ^2.0.3
  # youtube_player_flutter: ^7.0.0+7
  flutter_cached_pdfview: ^0.3.5
  video_player: ^2.2.11
  pagination_view: ^1.0.4+2
  timezone: ^0.7.0
  date_format: ^2.0.2
  get_it: ^4.0.0
  auto_size_text: ^2.1.0
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.3
  flutter_overlay_loader: ^0.0.2
  amazon_cognito_identity_dart: ^0.0.22
  aws_s3: ^0.1.1+hotfix.5
  flick_video_player: ^0.3.1
  visibility_detector: ^0.2.0
  url_launcher: ^6.0.18
  intl: ^0.17.0
  firebase_messaging: ^10.0.4
  cached_network_image: ^2.4.1
  youtube_player_iframe: ^2.2.2
  flutter_launcher_icons: ^0.9.2
  convert: ^3.0.0

dependency_overrides:
  http_parser: ^4.0.0
  plugin_platform_interface: ^1.0.2
  provider: ^4.3.2+2
  flutter_cached_pdfview: ^0.3.3
  wakelock: ^0.4.0
  image: ^3.0.2
  crypto: ^3.0.0
```
