### ISSUE TITLE
[Android] App downloaded from Playstore is rebooting the device

### ISSUE THREAD

**Issue by tuanhwing** [flutter/flutter#97193]
Some users are reporting on Google Play that the app is restarting device!
Devices : HUAWEI P20/P20Lite, Galaxy A41.

Every time open the app, it will restart the device after a few seconds. After reboot this problem still occurs and only on my app. However, the following days did not have this problem and used the app normally.

## Steps to Reproduce

Unfortunately I do not have any devices that reproduce this, I ran the app in release mode in several devices (including HUAWEI P20Lite, Samsung A12, A31, A21s, J5, J6, ...) and none reproduce this error.

pubspec.yaml 

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dio: ^4.0.0
  device_info: ^2.0.0
  advertising_id: ^0.9.2
  date_time_picker: ^1.0.0
  fluttertoast: ^7.0.2
  path_provider: ^2.0.0
  event_bus: ^1.1.1
  image: ^3.0.1
  settings_ui: ^0.3.0
  shared_preferences: ^0.5.7
  smooth_page_indicator: ^0.2.0
  package_info: ^0.4.0+17
  date_format: ^1.0.9
  permission_handler: ^6.0.0
  exif: 3.0.0
  assets_audio_player: ^3.0.2
  webview_flutter: ^2.1.1
  formz: ^0.3.1
  equatable: ^2.0.2

  pull_to_refresh: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  file_picker: 3.0.4
  image_picker: 0.8.1
  advance_pdf_viewer: any
  visibility_detector: ^0.1.5
  shimmer: ^2.0.0
  flutter_typeahead: ^3.1.0
  cached_network_image: ^3.0.0
  kana_kit: ^2.0.0
  month_picker_dialog: ^0.4.0
  fl_chart: 0.36.2
  camera: 0.9.4+2
  path: 1.8.0
  flutter_keyboard_visibility: ^5.0.0
  flutter_cache_manager: ^3.0.2
  flutter_rating_bar: ^4.0.0
  app_settings: ^4.1.1
  flutter_pdfview: ^1.0.4
  flutter_config: 2.0.0
  flutter_launcher_icons: 0.9.2
  flutter_mute: 0.0.3
  flutter_webview_plugin: 0.4.0
  firebase_core: ^1.0.0
  firebase_analytics: ^8.0.0
  firebase_messaging: ^10.0.0
  firebase_crashlytics: ^2.1.1
  flutter_app_badger: 1.2.0
```
With this information, it is difficult to check the problem. 

Could you suggest, what CAN possibly be the cause of rebooting? How can I find the reason of rebooting.
Yes, I know, I didn't provide enough information, but any advices would be really helpful for me.

I found these other reports: 
https://github.com/flutter/flutter/issues/32261
https://stackoverflow.com/questions/47101821/phone-restarts-automatically-while-using-the-app

Maybe : Phones generally restart if there too many process for cpu to handle nowadays all phones are well optimised so I won't found this trouble.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-VN)
    • Flutter version 2.5.3 at /Users/TuanHwing/Desktop/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/TuanHwing/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • SM J600G (mobile) • 520064014b39557b • android-arm    • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.

```

</details>
