### ISSUE TITLE
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs; message=StandardFileSystem only supports file:* and data:* URIs)

### ISSUE THREAD

**Issue by dancb10** [flutter/flutter#97447]
I've started having some weird issues with Flutter and I'm not exactly sure when they started to show. Everything was working fine and suddenly I started having the following issues when trying to build the app for IOS:

```
 ../../../.pub-cache/hosted/pub.dartlang.org/js-0.6.3/lib/js.dart:8:1: Error: Not found: 'dart:js'
    export 'dart:js' show allowInterop, allowInteropCaptureThis;
    ^
    ../../../.pub-cache/hosted/pub.dartlang.org/js-0.6.3/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'
    export 'dart:js_util';
    ^
    ../../../.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.5.4/lib/src/interop/utils/js_interop.dart:25:12: Error: Method not found: 'hasProperty'.
      if (util.hasProperty(jsObject, 'toDateString')) {
               ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.5.4/lib/src/interop/utils/utils.dart:45:31: Error: Method not found: 'getProperty'.
          map[key] = dartify(util.getProperty(jsObject, key), customDartify);
                                  ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.5.4/lib/src/interop/utils/utils.dart:78:22: Error: Method not found: 'newObject'.
        var jsMap = util.newObject();
                         ^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.5.4/lib/src/interop/utils/utils.dart:80:12: Error: Method not found: 'setProperty'.
          util.setProperty(jsMap, key, jsify(value, customJsify));
               ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.5.4/lib/src/interop/utils/utils.dart:86:12: Error: Method not found: 'allowInterop'.
        return allowInterop(dartObject);
               ^^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.5.4/lib/src/interop/utils/utils.dart:100:10: Error: Method not found: 'callMethod'.
        util.callMethod(jsObject, method, args);
             ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.5.4/lib/src/interop/utils/utils.dart:113:15: Error: Method not found: 'promiseToFuture'.
      return util.promiseToFuture(thenable);
                  ^^^^^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.5.4/lib/src/interop/utils/utils.dart:121:27: Error: Method not found: 'allowInterop'.
      return PromiseJsImpl<S>(allowInterop((
                              ^^^^^^^^^^^^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs; message=StandardFileSystem only supports file:* and data:* URIs)
    #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:614:37)
    #2      writeDepfile (package:vm/kernel_front_end.dart:754:21)
    <asynchronous suspension>
    #3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:571:9)
    <asynchronous suspension>
    #4      starter (package:flutter_frontend_server/server.dart:85:12)
    <asynchronous suspension>
    #5      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
    <asynchronous suspension>
```

Note that I used to have Android, IOS and Web as part of the same project but in the meantime I splitted mobile from web. There is nothing in the mobile app which relates to web.
So my pubspec file looks like this:
```
dependencies:
  flutter:
    sdk: flutter
    
  flutter_easyloading: ^2.2.0
  provider: ^5.0.0
  path: ^1.7.0
  page_transition: ^2.0.4
  sizer: ^2.0.15

  flutter_material_color_picker: ^1.0.5
  flutter_icons: ^1.1.0
  cupertino_icons: ^0.1.3
  google_fonts: ^2.1.0
  emojis: ^0.9.3
  flutter_native_splash: ^1.3.1

  build_runner: ^1.10.12
  path_provider: ^2.0.6
  permission_handler: ^8.2.5
  intl: ^0.17.0
  auto_size_text: ^3.0.0

  flutter_image_compress: ^1.1.0
  flutter_native_image: ^0.0.5+3
  flutter_absolute_path: ^1.0.6
  file_picker: ^4.2.7
  mime: ^1.0.0

  geolocator: ^7.0.3
  geocoding: ^2.0.0
  google_maps_flutter: ^2.0.6
  connectivity: ^3.0.6
  http2: ^2.0.0

  camera: ^0.9.4+3
  video_player: ^2.2.6

  timer_builder: ^2.0.0
  # audio_recorder: ^1.0.1
  # audioplayers: ^0.16.2

  # overlay_container: ^0.0.5+1
  string_validator: ^0.3.0
  country_picker: ^2.0.9
  
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4

  cloud_firestore: ^3.1.0
  firebase_storage: ^10.2.3
```

Flutter version 2.8.1
```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)`
```
I tried upgrading/changing flutter version, switching branches master/stable, rebuilt cache, removed all web related packages, changed desired IOS deployment versions from 10 to 14, modified the Podfile, reinstalled everything for Ios from ruby to pod to everything. Recreated the app from scratch, removed the Ios directory then executed flutter create, tried everything but can't seem to get rid of this error.
Tried commenting out in the js file that import line     `export 'dart:js' show allowInterop, allowInteropCaptureThis;`. Tried conditional importing.
Removed the .pub-cache directory and rebuilt the cache
Why does it complain about flutter-web-core package when this is a mobile app and I'm trying to build for it?
Nothing worked and I don't know what to try more
Please advice on how to fix this
