### ISSUE TITLE
Android : A problem occurred evaluating project ':app'

### ISSUE THREAD

**Issue by antoinepemeja** [flutter/flutter#97453]
Hello,

Since few days I have this error when I build the Android project.
This problem occurs in my Mac and in Bitrise.

```
* Where:
Build file '/****/android/app/build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_edythw0r3sm4156zagxs7pxes.android() is applicable for argument types: (build_edythw0r3sm4156zagxs7pxes$_run_closure2) values: [build_edythw0r3sm4156zagxs7pxes$_run_closure2@60085455]
```

I didn't change my android configuration.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

• No issues found!
```

My pubspec.yaml

```
name: *****
description: *****

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  provider: ^6.0.0
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.2
  dio: ^4.0.0-prev3
  firebase_core: ^1.1.0
  firebase_analytics: ^9.0.3
  firebase_crashlytics: ^2.2.3
  firebase_messaging: ^11.2.3
  flutter_riverpod: ^1.0.0
  video_player: ^2.2.15
  pin_code_fields: ^7.3.0
  step_progress_indicator: ^1.0.1
  webview_flutter: ^3.0.0
  intercom_flutter: ^6.0.0
  url_launcher: ^6.0.12
  lottie: ^1.2.1
  intl_phone_number_input: ^0.7.0+2
  keyboard_actions: ^3.4.4
  youtube_player_flutter: ^8.0.0
  flutter_stripe: ^2.0.2
  iso_countries: ^2.1.0
  firebase_dynamic_links: ^4.0.2
  advance_pdf_viewer: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:

  uses-material-design: true

  generate: true

  assets:
      - assets/json/data/
      - assets/json/mocks/
      - assets/json/animation/
      - assets/images/
      - assets/videos/
      - assets/html/
      - assets/pdf/
      - configs/

  fonts:
    - family: Acta
      fonts:
        - asset: fonts/acta/Acta-Display-Light.otf
    - family: Avenir
      fonts:
        - asset: fonts/avenir/Avenir-Black.ttf
        - asset: fonts/avenir/Avenir-BlackOblique.ttf
        - asset: fonts/avenir/Avenir-Book.ttf
        - asset: fonts/avenir/Avenir-BookOblique.ttf
        - asset: fonts/avenir/Avenir-Heavy.ttf
          weight: 800
        - asset: fonts/avenir/Avenir-HeavyOblique.ttf
        - asset: fonts/avenir/Avenir-Light.ttf
          weight: 300
        - asset: fonts/avenir/Avenir-LightOblique.ttf
        - asset: fonts/avenir/Avenir-Medium.ttf
          weight: 500
        - asset: fonts/avenir/Avenir-MediumOblique.ttf
        - asset: fonts/avenir/Avenir-Oblique.ttf
        - asset: fonts/avenir/Avenir-Roman.ttf
```

My android/gradle.properties

```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```

My android/build.gradle

```
buildscript {
    ext.kotlin_version = '1.5.0'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

My android/app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdkVersion 30

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
    }

    defaultConfig {
        applicationId ****
        minSdkVersion 21
        targetSdkVersion 30
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias ****
            keyPassword ****
            storeFile ****
            storePassword ****
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }

    flavorDimensions "env"

    productFlavors {
        dev {
            dimension "env"
            applicationIdSuffix ".dev"
            versionNameSuffix "-dev"
            resValue "string", "app_name", "Dev 1829"
        }
        staging {
            dimension "env"
            applicationIdSuffix ".staging"
            versionNameSuffix "-staging"
            resValue "string", "app_name", "Staging 1829"
        }
        prod {
            dimension "env"
            resValue "string", "app_name", "Bollinger 1829"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
}
```

Thanks you
