### ISSUE TITLE
enable some package for some platform

### ISSUE THREAD

**Issue by TechComet** [flutter/flutter#97495]
Hi,

I write video app for Desktop, Web, Android & iOS

I use video_player package for Web, Android & iOS

but video_player not work on Desktop for that I use dart_vlc package on desktop

my problem if I want build to web I want remove dart_vlc from dependencies and add it again if I need build to Linux, Windows ..

need enable dependencies by platform like
```
ios_dependencies:
  video_player: ^2.2.16

windows_dependencies:
   dart_vlc: ^0.1.8


linux_dependencies:
   dart_vlc: ^0.1.8


```
