### ISSUE TITLE
select package version from git

### ISSUE THREAD

**Issue by TechComet** [flutter/flutter#97709]
I need get package form github
I know how to do it

```
dart_vlc:
dart_vlc_ffi:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      path: ffi
      ref: master
```

**But** my problem
it's get old version .. I need latest version

and I have question
how I can't select version from tags
