### ISSUE TITLE
Can't `flutter install` flavor to iOS device

### ISSUE THREAD

**Issue by bradyt** [flutter/flutter#98151]
Duplicate of https://github.com/flutter/flutter/issues/64856.

Flutter version is 2.10.0.

Project is configured with flavors for iOS, and build or run succeed, but install does not.

Reproduce is as follows:

```
> git clone https://github.com/flutter/flutter
> cd flutter/dev/integration_tests/flavors
```

Replace contents of `pubspec.yaml` with the following:

```yaml
name: flavors

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
```

Continue with the following:

```
> flutter build ios --flavor free
> flutter install -d 'iphone 14'

The Xcode project defines schemes: free, paid
You must specify a --flavor option to select one of the available schemes.
```

EDIT: links to repos mentioned in this comment and next one added for convenience:
- https://github.com/flutter/flutter/tree/master/dev/integration_tests/flavors
- https://github.com/bradyt/flutter-flavor-reproduce-steps
