### ISSUE TITLE
Flutter/Flutter.h' file not found when trying to do a build in xcode

### ISSUE THREAD

**Issue by liquidedgesolutions** [flutter/flutter#98187]
After flutter upgrade my project fails to build in Xcode with the following error:

```
In file included from /Users/eduanastle/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/ios/Classes/JavaScriptChannelHandler.m:5:
/Users/eduanastle/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/ios/Classes/JavaScriptChannelHandler.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
```
## Steps to Reproduce

This is a Build-time error, running 'flutter run' fails and throws the error

Expected results:  The app should run on the simulator/device
Actual results: The error is thrown and the build fails

See here for a zip file containing all the logs we were able to generate: [logs.zip](https://github.com/flutter/flutter/files/8040561/logs.zip)

flutter doctor -v output: 

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.10.0 at /Users/eduanastle/Documents/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (8 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • D594C8D4-D51B-4A26-958C-1B765D901DF3 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by liquidedgesolutions** [comment]
[logs.zip](https://github.com/flutter/flutter/files/8040566/logs.zip)

**Comment by maheshmnj** [comment]
Hi @liquidedgesolutions, Thanks for filing the issue.

> webview_flutter-1.0.7/ios/Classes/JavaScriptChannelHandler.m:5:

It seems like you are using a old version of webview_plugin could you please try upgrading to 3.0.0 and see if that fixes the issue? Also does the app build fine when running from the terminal with lfutter tool?

**Comment by liquidedgesolutions** [comment]
Hi

We've updated all plugins and dependencies to their latest version, but we are still getting the flutter/h file not found error when trying to build iOS version.

Attached all the files (--verbose, doctor etc).

[flutter_logs.zip](https://github.com/flutter/flutter/files/8114385/flutter_logs.zip)

**Comment by liquidedgesolutions** [comment]
Also please note that what I mean by "latest" is that we've updated all plugins/dependencies to the latest resolvable versions ("flutter upgrade --major-versions").

**Comment by maheshmnj** [comment]
Thanks for the update @liquidedgesolutions, Are you using the plugin `webview_flutter_wkwebview` Can you please share your `pubspec.yaml`, podfile ? 

```
> [ +138 ms] Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found

/Users/eduanastle/Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.7.1/ios/Clas
                    ses/JavaScriptChannelHandler.h:4:8
                    
[   +3 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 12. 
```

Thanks

**Comment by liquidedgesolutions** [comment]
Thanks for the reply :-)

We are not including "webview_flutter_wkwebview" plugin in pubspec.yaml file (see attached)
[pubspec_and_podfile.zip](https://github.com/flutter/flutter/files/8117003/pubspec_and_podfile.zip)

We're not using the webview_flutter_wkwebview plugin directly.. We're using flutter_html, which then seems to be including "webview_flutter_wkwebview" for some reason.

**Comment by maheshmnj** [comment]
Thanks for the info @liquidedgesolutions, Your profile seems to be forcing each pod to use IOS_DEPLOYMENT_TARGET 9.0 while some of the firestore plugins require a minimum deployment target of 10.0. You can find the list here
https://firebase.flutter.dev/docs/manual-installation/ios/

Please try removing these line from the podfile
> target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end

and ensure you have deployment target set to 10.0 at two places by opening the app in xcode by running

```
open ios/Runner.xcworkspace
```

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/31410839/155271102-bdf7144d-4043-424f-9e99-bd2f00031147.png">

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/31410839/155271131-db5bffc8-a48f-4c3f-9fdb-1554f544a8b6.png">

Please try the above and see if it helps fix the issue.

**Comment by liquidedgesolutions** [comment]
Thanks for the suggestion, we'll implement that immediately!

**Comment by liquidedgesolutions** [comment]
No luck, unfortunately, still giving the same error:
![unknown (2)](https://user-images.githubusercontent.com/80834007/155287165-55cd9f52-730b-4050-a030-70a58449239c.png)
![unknown (1)](https://user-images.githubusercontent.com/80834007/155287174-0a579374-7584-4d9d-b201-606e7efd1c90.png)
![unknown](https://user-images.githubusercontent.com/80834007/155287177-9c9e619a-cce1-492e-8400-3eab7f85dec5.png)

**Comment by maheshmnj** [comment]
Thanks for the update, I tried adding all your plugins in a newly created flutter project, set the minimum deployment target to 10 the build failed due to firebase core did not resolve to a known version so I commented out all the firebase plugins and  I was able to build the app successfully.

Labeling this issue for further investigattion from the team.


<details>
<summary>podfile</summary>

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```
</details> 

<details>
<summary>pubspec.yaml</summary>

```yaml
name: maps_sample
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  path: any
    
  # additional packages
  http: ^0.13.4
  gender_selection: "^1.0.0"
  flutter_holo_date_picker: ^1.0.1+2
  xml: ^5.1.2
  xml2json: ^5.3.1
  url_launcher: ^6.0.3
  provider: ^6.0.2
  barcode_widget: ^2.0.1
  sqflite: any
  path_provider: any
  path_provider_macos: any
  connectivity: ^3.0.3

  # firebase_dynamic_links: ^4.0.6
  # firebase_analytics: ^9.1.0
  # firebase_crashlytics: ^2.5.1
  # firebase_core: ^1.12.0
  # firebase_auth: ^0.6.2+1
  # cloud_firestore: ^3.1.8
  # firebase_messaging: ^11.2.6
  # provider_architecture: ^1.1.1
  get_it: ^7.2.0
  # flutter_bcrypt: ^1.0.7
  intl: ^0.17.0
  simple_html_css: ^3.0.1
  flutter_html: ^2.0.0
  sizer: ^2.0.15
  shared_preferences: ^2.0.7

  # nova:
  #   path: packages/flutter_nova
    

  # flutter_svg: ^0.22.0
  # build_runner: ^1.6.2
  # build_web_compilers: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.5
  sqflite_common_ffi: any
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
</details>


cc: @jmagman
