### ISSUE TITLE
`flutter build ios` fails with `vm/compiler/backend/linearscan.cc: 2726: error: unreachable code`

### ISSUE THREAD

**Issue by zand-yasin** [flutter/flutter#98466]
Hello flutter team, i have an issue while building my application for ios, i have spending days i appreciate your supports
my project runs properly in development process so the issue is just when i wanted to deploy my app on testflight mode,
when i type **flutter build ios** for reaching out my build version of the app it gives me  this result 

```
../../third_party/dart/runtime/vm/compiler/backend/linearscan.cc: 2726: error: unreachable code
Dart snapshot generator failed with exit code -6
Failed to package /Users/user/Desktop/pojectname.
```

i tried with master and stable channel both were same. this is a list of my packages i have used in my app

```
dependencies:
  another_flushbar: ^1.10.23
  flutter_launcher_icons: ^0.9.2
  cached_network_image: ^3.1.0+1
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.3
  device_preview: ^1.0.0
  dio: ^4.0.0
  easy_localization: ^3.0.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.0
  flutter_sound: 9.1.2
  get_it: 7.2.0
  http: ^0.13.3
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  just_audio: ^0.9.16
  material_dialog: ^1.0.0-nullsafety.1
  mobx: ^2.0.1
  path_provider: ^2.0.2
  permission_handler: 8.3.0
  photo_view: ^0.13.0
  provider: ^6.0.1
  pusher_client: ^2.0.0
  sembast: ^3.1.0+2
  shared_preferences: ^2.0.6
  sliding_up_panel: ^2.0.0+1
  validators: ^3.0.0
  xxtea: ^2.1.0
```

and this is my **flutter doctor** on stable channel

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6.1 20G224 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.50.1)
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

• No issues found!

and this is my machine information

macOS Big Sur
version: 11.6.1
processor: 3.1 GHz Dual-Core Intel Core i7

 Your sincere
