### ISSUE TITLE
[Request] flutter pub get --all for local sub modules/packages

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#98517]
I'm working on a project with multiple local dependencies and the get process is hard.
I need to call flutter pub get multiple times in multiple directories. I wish there was a `flutter pub get --all` that looked into `path: ...` inside pubspec.yaml and automatically called `flutter pub get` in the other modules.

**Comment by christopherfujino** [comment]
So this should work already. What `dart pub get` does (which `flutter pub get` delegates to), is recursively detect each dependency (and then transitive dependency); once it has this flattened list of all required dependencies (which you can see in `pubspec.lock`), it ensures they are all present locally.

Thus, you should not even have to call `flutter pub get` on your other modules in order to run your top level app; just once in your app project directory.

I verified this locally with this minimal repro:

`//mini_mono_repo/dep/pubspec.yaml`:

```
name: my_great_dep
dependencies:
  shelf: any

environment:
  sdk: '>=2.10.0 < 3.0.0'
```

`//mini_mono_repo/dep/lib/dep.dart':

```
import 'package:shelf/shelf.dart';

void libFunc() {
  final _ = MyServer();
  print('hi');
}

class MyServer extends Server {
  Uri get url => throw 'yikes';
  void mount(Handler handler) {}
  Future close() async {}
}
```

I never call `pub get` in this dependency package. Now, in my main app:

`//mini_mono_repo/app/pubspec.yaml`:

```
name: my_great_app
description: A Flutter app with a local path dependency

environment:
  sdk: ">=2.17.0-105.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  my_great_dep:
    path: ../dep

flutter:
  uses-material-design: true
```

and the entrypoint, `//mini_mono_repo/app/lib/main.dart`:

```
import 'package:flutter/material.dart';
import 'package:my_great_dep/dep.dart';

void main() {
  libFunc();
  runApp(
    const Center(
      child: Text('App compiled!', textDirection: TextDirection.ltr),
    ),
  );
}
```

When I try to run the app BEFORE calling `flutter pub get`, I get a failure that `my_great_dep` is not found. However, AFTER calling `flutter pub get` ONLY in my app directory, the app compiles and I have `shelf` linked to the app.

---

@bernaferrari If you do not call `flutter pub get` on your dependent modules, are you hitting a build error? If so, then that is a different issue.
