### ISSUE TITLE
Because every version of alpha_vantage_package depends on http ^0.12.0+4 and front depends on http ^0.13.4, alpha_vantage_package is forbidden.

### ISSUE THREAD

**Issue by learner00000** [flutter/flutter#98847]
I tried to install `alpha_vantage` and got the following error:

_**Because every version of alpha_vantage_package depends on http ^0.12.0+4 and front depends on http ^0.13.4, alpha_vantage_package is forbidden.
So, because front depends on alpha_vantage_package ^1.0.0, version solving failed.
pub get failed (1; So, because front depends on alpha_vantage_package ^1.0.0, version solving failed.)
exit code 1**_

This is my `pubspec.yaml` file:
```

name: front
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.11
  get: ^4.6.1
  google_fonts: ^2.1.1
  universal_platform: ^1.0.0+1
  alpha_vantage_package: ^1.0.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

```
