### ISSUE TITLE
Images not showing when I deploy to firebase

### ISSUE THREAD

**Issue by jake1808** [flutter/flutter#99399]
Hello I just started making a webapp and I am using firebase as my hosting platform. I have a couple of assets that I use locally to build my app. they found in `root->assets`  when I run the webapp on my machine everything displays however when I push and deploy it it won't show on the live webapp. 

the webapp looks like this when I run it locally:
![image](https://user-images.githubusercontent.com/51802968/156383229-3d628940-3cd2-4b28-a257-0df68c797e40.png)

it looks like this when I run it on this link https://portfolio-34678.web.app/#/:
![image](https://user-images.githubusercontent.com/51802968/156383499-2ecf1857-5587-49b7-9403-9a887497a9d1.png)

when I checked my inspector I was faces with this error:
`main.dart.js:6640          GET https://portfolio-34678.web.app/assets/circular_avatar_1.PNG 404`

`Error while trying to load an asset: Failed to load asset at "assets/circular_avatar_1.PNG" (404)`

here is the flutter code where I call the image:
```
            Image(
              image: AssetImage('circular_avatar_1.PNG'),
              height: 138,
              width: 138,
            ), 
```

**Comment by maheshmnj** [comment]
Hi @jake1808, Thanks for filing the issue. I visited your web app and its failing with 404 error, So It looks like the path is incorrect. If you have your image asset in `root/assets` then you should be accessing it using 

```
AssetImage('assets/circular_avatar_1.PNG'),
```

And I believe the reason it works locally is because of the inconsistency which is being tracked here https://github.com/flutter/flutter/issues/86833

**Comment by jake1808** [comment]
Hi @maheshmnj, I tried the solution you proposed but it's still not working. I moved the image to `root/assets/images`  then called it like this image: `AssetImage('assets/images/circular_avatar_1.PNG')` still facing the same 404 error. maybe having  a look at my github workflow would help here it is:

```
name: Build and Release APK
on: push
jobs:
    hosting:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v1

        # Install Flutter command
        - uses: subosito/flutter-action@v1
          with:
            channel: 'dev'

        # Build Website
        - name: Build Website
          run: |
            flutter config --enable-web
            flutter pub get
            flutter build web --release
          working-directory: ./

        # Deploy Firebase Hosting
        - name: Deploy Firebase Hosting
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting:portfolio-34678
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_34678 }}
            PROJECT_PATH: ./

```
